### ISSUE TITLE
spack graph --concretize crashes for complex graphs

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#1098]
mac-127459:spack gartung$ spack graph --concretize gallery@dev%gcc@4.9.3 
...

| | | |/| |_|_|_|_|_|/Traceback (most recent call last):
  File "/Users/gartung/spack/bin/spack", line 179, in <module>
    main()
  File "/Users/gartung/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/Users/gartung/spack/lib/spack/spack/cmd/graph.py", line 63, in graph
    graph_ascii(specs[0], debug=spack.debug)
  File "/Users/gartung/spack/lib/spack/spack/graph.py", line 499, in graph_ascii
    graph.write(spec, color=color, out=out)
  File "/Users/gartung/spack/lib/spack/spack/graph.py", line 426, in write
    self._back_edge_line(prev_ends, b, i, False, 'left-1')
  File "/Users/gartung/spack/lib/spack/spack/graph.py", line 303, in _back_edge_line
    advance(flen,      lambda: [("| ", self._pos)] )
  File "/Users/gartung/spack/lib/spack/spack/graph.py", line 280, in advance
    self._write_edge(*e)
  File "/Users/gartung/spack/lib/spack/spack/graph.py", line 161, in _write_edge
    name = self._frontier[index][sub]
IndexError: list index out of range

**Comment by adamjstewart** [comment]
`gallery` doesn't appear to be in Spack yet. Can you post the package.py for it? Does this occur for any other packages currently in Spack?

**Comment by adamjstewart** [comment]
Nvm, got it to crash with:
```
spack graph --concretize py-pillow+freetype+jpeg2000+lcms+tiff
```

**Comment by adamjstewart** [comment]
Doesn't crash when you don't use `--concretize` though. And doesn't crash when there are fewer dependencies.

**Comment by gartung** [comment]
Sorry that is in a package repo artstack-spack and dependent packages in repo hep-spack

**Comment by pramodk** [comment]
I see this issue with stat:
```
$ spack graph stat
o  stat
|\
| |\
| | |\
| | | |\
| | | | |\
| | | | | |\
| | | | | | |\
| | | | | | | |\
| | | | | | | | |\
| | | | | | | | | |\
| | o | | | | | | | |  py-pygtk
| |/| | | | | | | | |
| | |\ \ \ \ \ \ \ \ \
| | | |\ \ \ \ \ \ \ \ \
| | | | |\ \ \ \ \ \ \ \ \
| | | | | |\ \ \ \ \ \ \ \ \
| | | | | | |\ \ \ \ \ \ \ \ \
| | o | | | | | | | | | | | | |  py-pygobject
| | | | | | | |/| | |_|/Traceback (most recent call last):
  File "/homea/hch05/hch054/spack/bin/spack", line 192, in <module>
    main()
  File "/homea/hch05/hch054/spack/bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/homea/hch05/hch054/spack/lib/spack/spack/cmd/graph.py", line 66, in graph
    graph_ascii(specs[0], debug=spack.debug)
  File "/homea/hch05/hch054/spack/lib/spack/spack/graph.py", line 501, in graph_ascii
    graph.write(spec, color=color, out=out)
  File "/homea/hch05/hch054/spack/lib/spack/spack/graph.py", line 427, in write
    'left-1')
  File "/homea/hch05/hch054/spack/lib/spack/spack/graph.py", line 307, in _back_edge_line
    advance(flen,      lambda: [("| ", self._pos)])
  File "/homea/hch05/hch054/spack/lib/spack/spack/graph.py", line 284, in advance
    self._write_edge(*e)
  File "/homea/hch05/hch054/spack/lib/spack/spack/graph.py", line 165, in _write_edge
    name = self._frontier[index][sub]
IndexError: list index out of range
```

>  spack graph --dot stat

 works fine.

**Comment by pramodk** [comment]
perfect, all looks good with #1862 !
