### ISSUE TITLE
glib 2.42.1 not building correctly on CrayXC-SuSE11

### ISSUE THREAD

**Issue by robertdfrench** [LLNL/spack#1134]
I am having a hard time building glib on Cray systems. Spack builds it just fine on RHEL and Mac OS. It seems to be hitting a snag in `/usr/bin/dtrace`. I wonder if this is just a faulty dtrace that is provided with SuSE? Has anyone else run into this?

Relevant errors:
```
make[2]: Entering directory `/tmp/frenchrd/spack-stage/spack-stage-8szQIo/glib-2.42.1/glib'
  GEN      glibconfig-stamp
  GEN      glib_probes.lo
Traceback (most recent call last):
  File "/usr/bin/dtrace", line 281, in <module>
    main()
  File "/usr/bin/dtrace", line 268, in main
    filename + ".o"], shell=False)
  File "/usr/lib64/python2.6/subprocess.py", line 470, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[2]: *** [glib_probes.lo] Error 1
```

**Comment by robertdfrench** [comment]
I have fixed this for myself by listing the system glib in my packages.yaml. On the line where dtrace blows up, it looks like it is attempting to open the Spack compiler wrapper, but since this works correctly on other systems, I am choosing to assign blame to old SLES rather than Spack.
