### ISSUE TITLE
module refresh broken

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1144]
We might want to ignore this until #1135... But just an FYI `spack module refresh` is broken:
```
==> Regenerating tcl module files.
Traceback (most recent call last):
  File "/apps/spack/bin/spack", line 179, in <module>
    main()
  File "/apps/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/apps/spack/lib/spack/spack/cmd/module.py", line 101, in module
    module_refresh()
  File "/apps/spack/lib/spack/spack/cmd/module.py", line 92, in module_refresh
    if os.path.isdir(cls.path):
AttributeError: type object 'TclModule' has no attribute 'path'
```

@tgamblin Is there a reason why we took out `{TclModule,Dotkit}.path`, in a15aee5 for the mock testing changes? ` cmd/module.py` needs the `path` [here](https://github.com/LLNL/spack/blob/eb388306fde0f636e595b5ac5eae37a3c5850f4b/lib/spack/spack/cmd/module.py#L92).

**Comment by mwilliammyers** [comment]
Ooops just read the comments in #1135 more closely which fixes this...
