### ISSUE TITLE
python2 & python3 bindings fail to build for opencv

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1232]
This scenario occurs at least with the following packages in the DAG:
`opencv 3.1.0`
`python 2.7.11`
`python 3.5.1`
`py-numpy 1.11.0`
`openblas 0.2.18`

I have been working on adding `cuda` support for `opencv `and in the process noticed that the `python` bindings were not being built. I am pretty sure it has to do with `numpy` throwing the error below when python tries to load it because it can't find `libopenblas.so.0`. Openblas, by default satisfies the blas requirement for `py-numpy`...

```
-- Found PythonLibs: /apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/python-3.5.1-7mzxfy5ht65wzhbjs6ibonv5buw55umv/lib/libpython3.5m.so (found suitable exact version "3.5.1")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/py-numpy-1.11.0-ftvt4fx5y3xasud7lf6xyk2asjnfupcz/lib/python3.5/site-packages/numpy-1.11.0-py3.5-linux-x86_64.egg/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/py-numpy-1.11.0-ftvt4fx5y3xasud7lf6xyk2asjnfupcz/lib/python3.5/site-packages/numpy-1.11.0-py3.5-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/py-numpy-1.11.0-ftvt4fx5y3xasud7lf6xyk2asjnfupcz/lib/python3.5/site-packages/numpy-1.11.0-py3.5-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/py-numpy-1.11.0-ftvt4fx5y3xasud7lf6xyk2asjnfupcz/lib/python3.5/site-packages/numpy-1.11.0-py3.5-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/apps/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/py-numpy-1.11.0-ftvt4fx5y3xasud7lf6xyk2asjnfupcz/lib/python3.5/site-packages/numpy-1.11.0-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libopenblas.so.0: cannot open shared object file: No such file or director
```

I have tried  various different `cmake` tricks to no avail. I have even explicitly specified `openblas` as an explicit dependency to `opencv`, which obviously is not a fix, in the hopes that `spack` would add it's paths to the environment. But that didn't work probably because `spack` doesn't use `LD_LIBRARY_PATH`s etc., instead it uses `LDLIBS` and `LDPATH` (if I am not mistaken). I have also held `cmake`'s hand a little to help it find the correct python to build by doing:
```
 if spec.satisfies('^python@3:'):
            cmake_options.append('-DBUILD_opencv_python3=ON')
        elif spec.satisfies('^python@2:2.7.11'):
            cmake_options.append('-DBUILD_opencv_python2=ON')
```
which is a more elegant solution (props to `spack`!) to what `linuxbrew` and `homebrew` do [here](https://github.com/Linuxbrew/homebrew-science/blob/71e45eca40ffee8945f38695045d0e32e2245019/opencv3.rb#L141).

Maybe we could try to manually specify the python lib and includes like `linuxbrew` and `homebrew` do [here](https://github.com/Linuxbrew/homebrew-science/blob/71e45eca40ffee8945f38695045d0e32e2245019/opencv3.rb#L198)? But I would rather let `cmake` work it's magic if possible...

Can anyone confirm that the python bindings (manifested with a `cv.so`) are not being built for them?

p.s. if you run `spack` in verbose mode you can catch whether or not `cmake` has found the correct `python2` and `python3` libs etc. when it does its usual summary print out at then of the configure step, thus saving you 8ish minutes of time...

**Comment by mwilliammyers** [comment]
I just noticed #1188...

**Comment by mwilliammyers** [comment]
#1888 does indeed fix this issue.
