### ISSUE TITLE
`spack setup`: fails with AttributeError

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1242]
I am currently trying the command to see what needs to be modified in #1186. Filing issues as I see them (on `LLNL/develop`) : 
```
$ pwd
/home/mculpo/tmp/spack/ibmisc-0.1.0

$ ls
add_license.py  cmake  CMakeLists.txt  CMakeLists.txt.with_find  configme  ibmisc-devel-GCC-4.9.3.eb  LICENSE  pylib  README.md  slib  spack-build.env  spack-build.out  tests

$ spack setup ibmisc~netcdf~proj~udunits2~boost~python~googletest~blitz@0.1.0
==> Installing ibmisc
==> python is already installed in /home/mculpo/github/spack-llnl/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/python-2.7.11-cali4n6cc275duixxwoqvme7ciyzdv7l
==> doxygen is already installed in /home/mculpo/github/spack-llnl/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/doxygen-1.8.11-bodgnq4vvqmyzr4ejuy2o5uoupnkxgm7
==> cmake is already installed in /home/mculpo/github/spack-llnl/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/cmake-3.5.2-cjy7dyxzysrart3a3odcw6rzkpjzqkao
==> eigen is already installed in /home/mculpo/github/spack-llnl/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/eigen-3.2.7-tcbg3t5jbnqyll7qzpf2nlqajhqfdtfy
==> No need to fetch for DIY.
==> Sources for DIY stages are not cached
==> Using source directory: /home/mculpo/tmp/spack/ibmisc-0.1.0
==> No patches needed for ibmisc
==> Building ibmisc
Traceback (most recent call last):
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/build_environment.py", line 513, in fork
    function()
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/package.py", line 989, in build_process
    self.install(self.spec, self.prefix)
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/package.py", line 1553, in install
    self.install_setup()
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/package.py", line 1611, in install_setup
    '-DCMAKE_Fortran_COMPILER=%s' % os.environ['SPACK_FC']] + \
AttributeError: 'module' object has no attribute 'get_std_cmake_args'
==> Warning: Keeping install prefix in place despite error.
  Spack will think this package is installed. Manually remove this directory to fix:
  /home/mculpo/github/spack-llnl/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/ibmisc-0.1.0-4s5ct3qk7h2llgp47lncsr2c4k6iqwe2
==> Error: Installation process had nonzero exit code : 256
```

**Comment by citibeth** [comment]
See #1250.  Sorry, that one didn't make it into the final PR #543

For the code I'm running, see: https://github.com/citibeth/spack/tree/efischer/faster-virtuals
