### ISSUE TITLE
spack info : broken after build-dep merge

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1256]
Reproducible by : 
```
$ spack info openjpeg
Package:    openjpeg
Homepage:   https://github.com/uclouvain/openjpeg

Safe versions:  
    2.1      https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
    2.0.1    https://github.com/uclouvain/openjpeg/archive/version.2.0.1.tar.gz
    2.0      https://github.com/uclouvain/openjpeg/archive/version.2.0.tar.gz
    1.5.2    https://github.com/uclouvain/openjpeg/archive/version.1.5.2.tar.gz
    1.5.1    https://github.com/uclouvain/openjpeg/archive/version.1.5.1.tar.gz

Variants:
    None

Build Dependencies:
Traceback (most recent call last):
  File "/home/mculpo/github/spack-llnl/bin/spack", line 179, in <module>
    main()
  File "/home/mculpo/github/spack-llnl/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/cmd/info.py", line 111, in info
    print_text_info(pkg)
  File "/home/mculpo/github/spack-llnl/lib/spack/spack/cmd/info.py", line 87, in print_text_info
    deps = pkg.dependencies(deptype)
TypeError: 'dict' object is not callable
```
I tried to modify : 
```
$ git diff
diff --git a/lib/spack/spack/cmd/info.py b/lib/spack/spack/cmd/info.py
index 5774034..6fd4ac6 100644
--- a/lib/spack/spack/cmd/info.py
+++ b/lib/spack/spack/cmd/info.py
@@ -84,7 +84,7 @@ def print_text_info(pkg):
     for deptype in ('build', 'link', 'run'):
         print
         print "%s Dependencies:" % deptype.capitalize()
-        deps = pkg.dependencies(deptype)
+        deps = pkg.spec.dependencies(deptype)
         if deps:
             colify(deps, indent=4)
         else:
```
But the result was no good either : 
```
$ spack info openjpeg
Package:    openjpeg
Homepage:   https://github.com/uclouvain/openjpeg

Safe versions:  
    2.1      https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
    2.0.1    https://github.com/uclouvain/openjpeg/archive/version.2.0.1.tar.gz
    2.0      https://github.com/uclouvain/openjpeg/archive/version.2.0.tar.gz
    1.5.2    https://github.com/uclouvain/openjpeg/archive/version.1.5.2.tar.gz
    1.5.1    https://github.com/uclouvain/openjpeg/archive/version.1.5.1.tar.gz

Variants:
    None

Build Dependencies:
****    None   ****

Link Dependencies:
    None

Run Dependencies:
    None

Virtual packages: 
    None

Description:
     OpenJPEG is an open-source JPEG 2000 codec written in C language. It
    has been developed in order to promote the use of JPEG 2000, a still-
    image compression standard from the Joint Photographic Experts Group
    (JPEG). Since April 2015, it is officially recognized by ISO/IEC and
    ITU-T as a JPEG 2000 Reference Software.
```

**Comment by adamjstewart** [comment]
`spack graph` is also broken:
```
$ spack graph openjpeg
Traceback (most recent call last):
  File "/soft/spack/bin/spack", line 179, in <module>
    main()
  File "/soft/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/cmd/graph.py", line 63, in graph
    graph_ascii(specs[0], debug=spack.debug)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/graph.py", line 501, in graph_ascii
    graph.write(spec, color=color, out=out)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/graph.py", line 392, in write
    topo_order = topological_sort(spec, reverse=True)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/graph.py", line 105, in topological_sort
    for dep in children(node).values():
AttributeError: 'list' object has no attribute 'values'
```
