### ISSUE TITLE
Conditional test dependencies not added to spec

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#12613]
Something major must have broken very recently, because this bug didn't exist 3 weeks ago when I was working on #12170.

I'm trying to install numpy, but when I run the unit tests, it turns out `pytest` isn't added as a dependency. The package contains:
```python
    depends_on('py-nose@1.0.0:', when='@:1.14', type='test')                    
    depends_on('py-pytest', when='@1.15:', type='test')    
```
If I run:
```console
$ spack install --test=root py-numpy
==> intel-mkl@2019.4 : externally installed in /opt/intel
==> intel-mkl@2019.4 : already registered in DB
==> diffutils is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-jvgimm7dfdzbuwjxhmrmrzfangw3r3ry
==> bzip2 is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/bzip2-1.0.8-llnc6sqphf7yp4drig6njzzkxctjwfse
==> expat is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/expat-2.2.5-ivx3l77irr7xnft6v2xduzqier7zlct3
==> pkgconf is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/pkgconf-1.6.1-gws4nai5kqznvyfk2uaz5o26td45oq6x
==> ncurses is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/ncurses-6.1-nhodl3ckldkmn6nfzgtymzlsn7mm3htq
==> readline is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/readline-7.0-kn3u3qhqwktlvjpr47ism2uqqgstvvf2
==> gdbm is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdbm-1.18.1-pvjwideh43qybd2ifi65gjxq2dd6p4nj
==> libiconv is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libiconv-1.15-6y7tjlqeuu7qmpv3zokgbdowqs7emk7y
==> xz is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/xz-5.2.4-snwzcouby3x3ztkutupqzmqwbbxh2tur
==> zlib is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/zlib-1.2.11-nqnlnxddpa4qfz5cnf4grnct57ds25ks
==> libxml2 is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libxml2-2.9.9-owmrtw347mtch4jm4cium25nvsjamqkf
==> tar is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/tar-1.31-vyjf7fdqrr6ybqblhuujonbcguepjbne
==> gettext is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gettext-0.19.8.1-n3673flplqiagvozwgyeezzs4u22gvrr
==> libffi is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libffi-3.2.1-rmioaofogfk7efvt3cpb3d433sevjnaf
==> perl is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/perl-5.26.2-agbs3wmvu2qp3hjc3amdhpo4znwkcwxs
==> openssl is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openssl-1.1.1c-lqiupxyyvankdx6zybheqiocy33cfnhl
==> sqlite is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/sqlite-3.28.0-mijtevf42dqzctgyaizz44skbyqwxgol
==> python is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/python-3.7.4-4o2smrf7lfyyg5pa6gu4q4rmjwdtxrel
==> py-setuptools is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-setuptools-41.0.1-amzguxfvxjiqaivtv7sxakdrapupbtv7
==> Installing py-numpy
...
==> [2019-08-27-20:43:00.538422] '/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/python-3.7.4-4o2smrf7lfyyg5pa6gu4q4rmjwdtxrel/bin/python3.7' '-c' 'import numpy; numpy.test("full", verbose=2)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-numpy-1.17.1-zu2emnwpzq4mefyg4vpyeiphn64ctquz/lib/python3.7/site-packages/numpy/_pytesttester.py", line 122, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'
```
it doesn't add the `py-pytest` dependency. But if I do:
```console
$ spack install --test=root py-numpy@1.17.0
==> intel-mkl@2019.4 : externally installed in /opt/intel
==> intel-mkl@2019.4 : already registered in DB
==> diffutils is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/diffutils-3.7-jvgimm7dfdzbuwjxhmrmrzfangw3r3ry
==> bzip2 is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/bzip2-1.0.8-llnc6sqphf7yp4drig6njzzkxctjwfse
==> expat is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/expat-2.2.5-ivx3l77irr7xnft6v2xduzqier7zlct3
==> pkgconf is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/pkgconf-1.6.1-gws4nai5kqznvyfk2uaz5o26td45oq6x
==> ncurses is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/ncurses-6.1-nhodl3ckldkmn6nfzgtymzlsn7mm3htq
==> readline is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/readline-7.0-kn3u3qhqwktlvjpr47ism2uqqgstvvf2
==> gdbm is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdbm-1.18.1-pvjwideh43qybd2ifi65gjxq2dd6p4nj
==> libiconv is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libiconv-1.15-6y7tjlqeuu7qmpv3zokgbdowqs7emk7y
==> xz is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/xz-5.2.4-snwzcouby3x3ztkutupqzmqwbbxh2tur
==> zlib is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/zlib-1.2.11-nqnlnxddpa4qfz5cnf4grnct57ds25ks
==> libxml2 is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libxml2-2.9.9-owmrtw347mtch4jm4cium25nvsjamqkf
==> tar is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/tar-1.31-vyjf7fdqrr6ybqblhuujonbcguepjbne
==> gettext is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gettext-0.19.8.1-n3673flplqiagvozwgyeezzs4u22gvrr
==> libffi is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libffi-3.2.1-rmioaofogfk7efvt3cpb3d433sevjnaf
==> perl is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/perl-5.26.2-agbs3wmvu2qp3hjc3amdhpo4znwkcwxs
==> openssl is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/openssl-1.1.1c-lqiupxyyvankdx6zybheqiocy33cfnhl
==> sqlite is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/sqlite-3.28.0-mijtevf42dqzctgyaizz44skbyqwxgol
==> python is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/python-3.7.4-4o2smrf7lfyyg5pa6gu4q4rmjwdtxrel
==> py-setuptools is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-setuptools-41.0.1-amzguxfvxjiqaivtv7sxakdrapupbtv7
==> py-atomicwrites is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-atomicwrites-1.1.5-tnmuobbfpx4cup67dfvphizas2o5pzxt
==> py-attrs is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-attrs-18.1.0-36epqfqjluqj66sqsopzlckjxryl4qzf
==> py-six is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-six-1.12.0-rnxesoishseodeag23dovmejiyzlwmzy
==> py-more-itertools is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-more-itertools-4.3.0-psaitjhb646j54e37wvtcvj5bugarad2
==> py-setuptools-scm is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-setuptools-scm-3.1.0-b6lcwj2vhjv5fjroeux757pdmx3hdaj6
==> py-pluggy is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-pluggy-0.7.1-uzcmx3ckh6y472hmrexwu55rl5muz4pb
==> py-py is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-py-1.5.4-wir74mgvvhwvqvc4zvg3x45hogzjngwp
==> py-pytest is already installed in /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-pytest-4.3.0-xemkacmzrs7brdc4j6v7i35kiolbaaw7
==> Installing py-numpy
```
it does add the `py-pytest` dependency.

**Comment by tldahlgren** [comment]
Caches can lead to some "interesting" behaviors.
