### ISSUE TITLE
`No such spec in database` error

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1266]
This command
```
spack install -j24 cactusext +funhpc +julia +llvm +simulationio %gcc@6.1.0-spack
```
led to this error:
```
==> Installing cactusext
==> openmpi is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/openmpi-2.0.0-5l3pomaqonrx3phvbm4kblzsms56ljtj
==> hwloc is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/hwloc-1.11.3-xgdwohjb2o26uftzaqtcmwf2ejxlhidw
==> git is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/git-2.8.1-jh72meyfuritl2wexqmckrshmufe7az4
==> papi is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/papi-5.4.3-tnovpyennp4cerqns4xnfscfvl6d3zlz
==> hdf5-blosc is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/hdf5-blosc-master-6m7xtyqubxsb2merc36i2oyhtdvno3zp
==> lmod is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/lmod-6.4.1-i2xu3l63aipam7bdlu3ig4eriqtjnbbd
==> hdf5 is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/hdf5-1.10.0-patch1-jfa4zar7ysebuadia7zlhoebrlaeo5lv
==> python is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/python-2.7.11-y6bfneoxof25qt6wgdsbfsra62grfdnz
==> lua is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/lua-5.3.2-xe6niqb4cwgkdpq33qjoi3rby3vcdnew
==> fftw is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/fftw-3.3.4-ojokm7aahpro46e4tvoqgsc57lzbfdum
==> openssl is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/openssl-1.0.2h-ookfh4fsbv5ijqjsewerc5vvf4hzfme6
==> julia is already installed in /home/ux452368/comet/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/julia-master-bzqdzwekzl3geaeyuexssnelbnwfiwsf
Traceback (most recent call last):
  File "/home/ux452368/comet/src/spack/bin/spack", line 179, in <module>
    main()
  File "/home/ux452368/comet/src/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/cmd/install.py", line 91, in install
    explicit=True)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/package.py", line 943, in do_install
    run_tests=run_tests)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/package.py", line 1096, in do_install_dependencies
    dep.package.do_install(**kwargs)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/package.py", line 925, in do_install
    rec = spack.installed_db.get_record(self.spec)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/database.py", line 76, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/database.py", line 461, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/home/ux452368/comet/src/spack/lib/spack/spack/database.py", line 456, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! julia@master%gcc@6.1.0-spack+binutils~cxx+hdf5+mpi~plot~python arch=linux-centos6-x86_64^binutils@2.25%gcc@6.1.0-spack+gold~krellpatch~libiberty arch=linux-centos6-x86_64^bzip2@1.0.6%gcc@6.1.0-spack arch=linux-centos6-x86_64^cmake@3.5.2%gcc@6.1.0-spack~doc+ncurses+openssl~qt arch=linux-centos6-x86_64^curl@7.49.1%gcc@6.1.0-spack arch=linux-centos6-x86_64^expat@2.1.0%gcc@6.1.0-spack arch=linux-centos6-x86_64^git@2.8.1%gcc@6.1.0-spack arch=linux-centos6-x86_64^hdf5@1.10.0-patch1%gcc@6.1.0-spack+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=linux-centos6-x86_64^hwloc@1.11.3%gcc@6.1.0-spack arch=linux-centos6-x86_64^libpciaccess@0.13.4%gcc@6.1.0-spack arch=linux-centos6-x86_64^libsigsegv@2.10%gcc@6.1.0-spack arch=linux-centos6-x86_64^m4@1.4.17%gcc@6.1.0-spack+sigsegv arch=linux-centos6-x86_64^ncurses@6.0%gcc@6.1.0-spack arch=linux-centos6-x86_64^openmpi@2.0.0%gcc@6.1.0-spack~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verbs+vt arch=linux-centos6-x86_64^openssl@1.0.2h%gcc@6.1.0-spack arch=linux-centos6-x86_64^python@2.7.11%gcc@6.1.0-spack~ucs4 arch=linux-centos6-x86_64^readline@6.3%gcc@6.1.0-spack arch=linux-centos6-x86_64^sqlite@3.8.5%gcc@6.1.0-spack arch=linux-centos6-x86_64^zlib@1.2.8%gcc@6.1.0-spack arch=linux-centos6-x86_64'
```

This happens on Comet at SDSC; the same Spack command works fine on other systems. How do I debug this?

**Comment by adamjstewart** [comment]
I just had this problem as well. I installed OpenFOAM, which depends on MVAPICH2 and Flex, among other things. MVAPICH2 installed correctly but Flex failed during fetching. I figured it might be a transient problem so I ran the exact same installation command again but then I see:

```
KeyError: 'No such spec in database! mvapich2@2.2b%gcc@6.1.0~debug~gforker+hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell~slurm~sock arch=linux-centos6-x86_64^libpciaccess@0.13.4%gcc@6.1.0 arch=linux-centos6-x86_64^libsigsegv@2.10%gcc@6.1.0 arch=linux-centos6-x86_64^libtool@2.4.6%gcc@6.1.0 arch=linux-centos6-x86_64^m4@1.4.17%gcc@6.1.0+sigsegv arch=linux-centos6-x86_64'
```

It's not like my spec is slightly different, because I ran `spack install -v --keep-stage openfoam` both times. It's almost like Spack doesn't add packages to the database unless the final installation succeeds.

**Comment by davydden** [comment]
i saw something similar today, `spack reindex` solved the issue.

**Comment by adamjstewart** [comment]
Yeah, that's what I did. Still a bug though.

**Comment by adamjstewart** [comment]
At this point, I'm pretty much getting this error message after every single installation. If I install a package and it crashes, none of the dependencies it built are in the database. I have to run `spack reindex @tgamblin do you have any idea what is going on here?

**Comment by tgamblin** [comment]
@adamjstewart @eschnett: can you supply a reproducer?  `openfoam` and `cactusext` aren't in the mainline yet.

**Comment by adamjstewart** [comment]
@tgamblin All you need to reproduce it is to build a package and its dependencies and have an intermediary dependency fail. From a fresh Spack clone on the latest develop branch **with no packages installed**:

1. `spack edit m4` and comment out `make('install')`.

2. `spack install gmp`. This will install libsigsegv but crash when trying to install m4 because nothing was installed.

3. `spack install gmp`. This produces the aforementioned error message, complaining that libsigsegv is already installed, but no such spec is found in the database.

If I had to guess, I would say the problem is that we aren't adding installs to the database immediately after they are installed, we are adding them after the final installation is complete.

**Comment by tgamblin** [comment]
@adamjstewart: you're not using #1535 are you?

**Comment by adamjstewart** [comment]
@tgamblin Nope, this is on develop 7f57405eac19fd2f28d32e7c69348112653ad6e8

**Comment by robertdfrench** [comment]
I have been running into this as well. If spack gets interrupted, it seems
to not record any packages which were built successfully.

**Comment by adamjstewart** [comment]
Ping. This bug is still present in the current develop and happens for me several times a day. Anytime a dependency fails to build, I have to run `spack reindex` to add the rest of the dependencies to the database.

**Comment by mathstuf** [comment]
> All you need to reproduce it is to build a package and its dependencies and have an intermediary dependency fail

For clarity, if the final package fails, this issue also happens.
