### ISSUE TITLE
spack reindex uses full hash length although install_hash_length: 8 in config.yaml

### ISSUE THREAD

**Issue by phxyz12** [LLNL/spack#12797]
Dear all

I updated spack today (pull onto my install from March this year). When I try to reindex the package db, I get errors like this:

```
[swadm@build01 defaults]$ spack reindex
==> Error: [Errno 2] No such file or directory: '/cfs/software/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-fz7hgwhylw6ubl4ezih77f27y3ewi7g6'
```

It seems that Spack tries to use full length hashes in the name of the package install dir. Actually, in my config.yaml I've set install_hash_length: 8 and hence the real install dir of the package in the error above is:

```
cfs/software/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-fz7hgwhy
```

### Steps to reproduce the issue

Using 

```
spack find -l
```

I can see all installed packages indicating a correct hash.

When I use

```
spack reindex
```

I get the error above.

### Error Message

Here is the output using

```
spack -d --stacktrace reindex
```

```
[swadm@build01 defaults]$ spack -d --stacktrace reindex
lib/spack/spack/cmd/__init__.py:99 ==> [2019-09-12-14:26:17.587763] Imported reindex from built-in commands
lib/spack/spack/cmd/__init__.py:99 ==> [2019-09-12-14:26:17.589738] Imported reindex from built-in commands
lib/spack/spack/config.py:684 ==> [2019-09-12-14:26:17.623162] Reading config file /data/swadm/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-09-12-14:26:17.637177] Reading config file /data/swadm/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-09-12-14:26:17.641480] Reading config file /data/swadm/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:214 ==> [2019-09-12-14:26:17.674241] DATABASE LOCK TIMEOUT: 120s
lib/spack/spack/database.py:218 ==> [2019-09-12-14:26:17.674405] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/llnl/util/lock.py:334 ==> [2019-09-12-14:26:17.675155] WRITE LOCK: /cfs/software/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-09-12-14:26:17.675407] WRITE LOCK: /cfs/software/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/spack/database.py:556 ==> [2019-09-12-14:27:21.693470] RECONSTRUCTING FROM SPEC.YAML: gcc@4.9.4%gcc@4.8.5~binutils languages=c,c++,fortran patches=27e982924b2fcac628c289aa9975753d645fd9308f3bdc1b09ae2444aa6547e0,7112abbff4f89980b907c01913d3075a354c6ba8c96b2c453e6941ce9fd99c4c,f5643d90fd8fdc8e86ae886b39c3ffb710daeefd5848c3c08447b77b77cdf162,f73de87bce5575d4792f9b62fd0c4ddd94849dc66b6aea908631ac1fd54350ae ~piclibs~strip arch=linux-centos7-x86_64 ^gmp@6.1.2%gcc@4.8.5 arch=linux-centos7-x86_64 ^mpc@1.1.0%gcc@4.8.5 arch=linux-centos7-x86_64 ^mpfr@3.1.6%gcc@4.8.5 patches=66a5d58364113a21405fc53f4a48f4e8 arch=linux-centos7-x86_64
lib/spack/llnl/util/lock.py:334 ==> [2019-09-12-14:27:21.694067] WRITE LOCK: /cfs/software/spack/.spack-db/lock[0:0] [Released]
Traceback (most recent call last):
  File "/data/swadm/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/data/swadm/spack/lib/spack/spack/main.py", line 697, in main
    return _invoke_command(command, parser, args, unknown)
  File "/data/swadm/spack/lib/spack/spack/main.py", line 447, in _invoke_command
    return_val = command(parser, args)
  File "/data/swadm/spack/lib/spack/spack/cmd/reindex.py", line 14, in reindex
    spack.store.store.reindex()
  File "/data/swadm/spack/lib/spack/spack/store.py", line 68, in reindex
    return self.db.reindex(self.layout)
  File "/data/swadm/spack/lib/spack/spack/database.py", line 530, in reindex
    directory_layout, old_data)
  File "/data/swadm/spack/lib/spack/spack/database.py", line 558, in _construct_from_directory_layout
    inst_time = os.stat(spec.prefix).st_ctime
OSError: [Errno 2] No such file or directory: '/cfs/software/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-fz7hgwhylw6ubl4ezih77f27y3ewi7g6'
```

### Information on your system

Platform: CentOS 7.6 on Intel x86

-----

Many thanks in advance.

Kind regards,

Pascal

**Comment by alalazo** [comment]
I just tried to modify `config.yaml` and install `zlib`. Confirmed that the full hash is used but I got no error on reindex:
```console
$ spack --version
0.14.0-90-c0032a3
```
