### ISSUE TITLE
Cannot install py-numpy: "No module named setuptools"

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1281]
```
==> Already downloaded /xfs1/eschnetter/spacktest/spack/var/spack/stage/py-numpy-1.11.0-urymgx5gdatropsqd2ehdfjoln44isa6/py-numpy-1.11.0.tar.gz
==> Already staged py-numpy-1.11.0-urymgx5gdatropsqd2ehdfjoln44isa6 in /xfs1/eschnetter/spacktest/spack/var/spack/stage/py-numpy-1.11.0-urymgx5gdatropsqd2ehdfjoln44isa6
==> No patches needed for py-numpy
==> Building py-numpy
==> '/xfs1/eschnetter/spacktest/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.0-spacktest/python-2.7.12-b5sf3vacbqfghadqm6uj2tti2oemd3xy/bin/python' 'setup.py' 'install' '--prefix=/xfs1/eschnetter/spacktest/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.0-spacktest/py-numpy-1.11.0-urymgx5gdatropsqd2ehdfjoln44isa6'
Running from numpy source directory.

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install numpy`   (last Numpy release on PyPi)


Traceback (most recent call last):
  File "setup.py", line 386, in <module>
    setup_package()
  File "setup.py", line 363, in setup_package
    from setuptools import setup
ImportError: No module named setuptools
```

I used this package definition for an umbrella package:
```
from spack import *

class Umbrella(Package):
    homepage = "Umbrella package"
    # This is just a dummy download
    url = "http://zlib.net/zlib-1.2.8.tar.gz"
    version('1.2.8', '44d667c142d7cda120332623eab69f40')

    depends_on("boost +mpi")
    depends_on("fftw +mpi +openmp")
    depends_on("git")
    depends_on("gsl")
    depends_on("hdf5 +mpi")
    depends_on("hdf5-blosc")
    depends_on("hwloc")
    depends_on("jemalloc")
    depends_on("julia")
    # depends_on("julia +hdf5 +mpi")
    depends_on("llvm")
    depends_on("lmod")
    depends_on("openblas +openmp")
    depends_on("openmpi")
    depends_on("papi")
    depends_on("petsc +boost +hdf5 +mpi")
    depends_on("py-h5py +mpi")
    depends_on("py-mpi4py")
    depends_on("py-numpy")
    depends_on("py-scipy")
    # Specify version @2.7.12 explicitly to circumvent a concretization bug
    depends_on("python @2.7.12")
    depends_on("qthreads")
    depends_on("swig")
    depends_on("tmux")

    def install(self, spec, prefix):
        # This package does not install anything; it only installs its
        # dependencies
        mkdirp(prefix.lib)
```

**Comment by adamjstewart** [comment]
Try adding `depends_on('py-setuptools')` to py-numpy and see if that solves the problem for you.

**Comment by eschnett** [comment]
Yes, this corrects the error.
