### ISSUE TITLE
`spack module refresh` is broken

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1289]
```
spack module refresh
==> Regenerating tcl module files.
Traceback (most recent call last):
  File "/xfs1/eschnetter/spacktest/spack/bin/spack", line 179, in <module>
    main()
  File "/xfs1/eschnetter/spacktest/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/xfs1/eschnetter/spacktest/spack/lib/spack/spack/cmd/module.py", line 154, in module
    module_refresh()
  File "/xfs1/eschnetter/spacktest/spack/lib/spack/spack/cmd/module.py", line 145, in module_refresh
    if os.path.isdir(cls.path):
AttributeError: type object 'TclModule' has no attribute 'path'
```

**Comment by tgamblin** [comment]
@alalazo

**Comment by mwilliammyers** [comment]
@eschnett @tgamblin Are we not still waiting for #1135 to be merged? Or was this fixed elsewhere?

**Comment by alalazo** [comment]
@tgamblin See #1135 in the description under **Fixes** .
