### ISSUE TITLE
JDK install problem: AttributeError: 'module' object has no attribute 'dir_util'

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1364]
I'm cleaning up my nextflow package (which I haven't touched in days).  Now I can't install the jdk.

I've rebased onto the tip of develop, and I'm using the python that spack built instead of CentOS 7's.  Not sure what else changed.

Here's what I see:

```
[throgg@spack-central spack]$ spack install nextflow
==> Installing nextflow
==> Installing jdk
==> [Jdk] Adding required commandline options to curl before performing fetch: ['-j', '-H', 'Cookie: oraclelicense=accept-securebackup-cookie']
==> Already downloaded /home/throgg/spack/var/spack/stage/jdk-8u92-linux-x64-fzug57sw2sdor4dsjooesubqttyk43a7/jdk-8u92-linux-x64.tar.gz
==> Already staged jdk-8u92-linux-x64-fzug57sw2sdor4dsjooesubqttyk43a7 in /home/throgg/spack/var/spack/stage/jdk-8u92-linux-x64-fzug57sw2sdor4dsjooesubqttyk43a7
==> No patches needed for jdk
==> Building jdk
Traceback (most recent call last):
  File "/home/throgg/spack/lib/spack/spack/build_environment.py", line 512, in fork
    function()
  File "/home/throgg/spack/lib/spack/spack/package.py", line 997, in build_process
    self.install(self.spec, self.prefix)
  File "/home/throgg/spack/var/spack/repos/builtin/packages/jdk/package.py", line 70, in install
    distutils.dir_util.copy_tree(".", prefix)
AttributeError: 'module' object has no attribute 'dir_util'
==> Error: Installation process had nonzero exit code : 256
```

This change fixes it, but usual Python newbie disclaimers apply:

```
--- a/var/spack/repos/builtin/packages/jdk/package.py
+++ b/var/spack/repos/builtin/packages/jdk/package.py
@@ -26,6 +26,7 @@
 # Author: Justin Too <too1@llnl.gov>
 #
 import distutils
+from distutils.dir_util import copy_tree

 import spack
 from spack import *
@@ -67,4 +68,4 @@ class Jdk(Package):
         super(Jdk, self).do_fetch(mirror_only)

     def install(self, spec, prefix):
-        distutils.dir_util.copy_tree(".", prefix)
+        copy_tree(".", prefix)
```

Is this a Real Bug(tm) or something I did?  If its a bug, I can PR it.

**Comment by citibeth** [comment]
My guess is something changed in `distutils` somewhere.  Your fix looks fine, can you submit it as a PR?  The alternative would be to do:
```
- import distutils
+ import distutils.dir_util
```

Then you shouldn't have to change the code below at all.

**Comment by hartzell** [comment]
Done, #1374.
