### ISSUE TITLE
Crash with `spack deactivate -a ...`

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1372]
[This could well be user error....]

`spack deactivate -a` crashed.  The details are in the final code block.  The rest is context.

I'm still trying to get my head around extensions, so I installed r-shiny (a couple of packages are out of date, a PR's on the way) and did this:

```
[throgg@spack-central spack]$ spack activate r-shiny
==> Activated extension r-R6@2.1.2%gcc@5.4.0 arch=linux-centos7-x86_64-r3mzzmi for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-digest@0.6.9%gcc@5.4.0 arch=linux-centos7-x86_64-m2sqzn6 for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-rcpp@0.12.6%gcc@5.4.0 arch=linux-centos7-x86_64-h4lnm7e for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-htmltools@0.3.5%gcc@5.4.0 arch=linux-centos7-x86_64-4fywxyo for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-httpuv@1.3.3%gcc@5.4.0 arch=linux-centos7-x86_64-vh2puab for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-jsonlite@1.0%gcc@5.4.0 arch=linux-centos7-x86_64-cg6jy6f for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-mime@0.5%gcc@5.4.0 arch=linux-centos7-x86_64-gx5ztlo for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-xtable@1.8-2%gcc@5.4.0 arch=linux-centos7-x86_64-t52tspc for R@3.3.1~external-lapack%gcc@5.4.0
==> Activated extension r-shiny@0.13.2%gcc@5.4.0 arch=linux-centos7-x86_64-kqimhjd for R@3.3.1~external-lapack%gcc@5.4.0
[throgg@spack-central spack]$ find /home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk | grep shiny
/home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk/rlib/R/library/shiny
/home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk/rlib/R/library/shiny/LICENSE
[...]
```

Then I deactivated it and was curious if the dependencies were still 'activated' (checked *jsonlite*):

```
[throgg@spack-central spack]$ spack deactivate r-shiny
==> Deactivated extension r-shiny@0.13.2%gcc@5.4.0 arch=linux-centos7-x86_64-kqimhjd for R@3.3.1~external-lapack%gcc@5.4.0
[throgg@spack-central spack]$ find /home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk | grep shiny
[throgg@spack-central spack]$ find /home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk | grep jsonlite
/home/throgg/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/R-3.3.1-wapajixhz5htjddymx3pn7vgcyqhhcrk/rlib/R/library/jsonlite
[...]
```

Then I tried the `-a` option, which didn't work because I'd already deactivated *r-shiny*.

So I reactivated it and then tried `deactivate -r` and got the following crash:

```
[throgg@spack-central spack]$ spack deactivate -a r-shiny
==> Error: r-shiny@0.13.2%gcc@5.4.0 arch=linux-centos7-x86_64-kqimhjd is not activated.
[throgg@spack-central spack]$ spack activate r-shiny
==> Activated extension r-shiny@0.13.2%gcc@5.4.0 arch=linux-centos7-x86_64-kqimhjd for R@3.3.1~external-lapack%gcc@5.4.0
[throgg@spack-central spack]$ spack deactivate -a r-shiny
==> Deactivating r-shiny@0.13.2%gcc@5.4.0 arch=linux-centos7-x86_64-kqimhjd and all dependencies.
Traceback (most recent call last):
  File "/home/throgg/spack/bin/spack", line 179, in <module>
    main()
  File "/home/throgg/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/throgg/spack/lib/spack/spack/cmd/deactivate.py", line 70, in deactivate
    topo_order = topological_sort(spec)
  File "/home/throgg/spack/lib/spack/spack/graph.py", line 105, in topological_sort
    for dep in children(node).values():
AttributeError: 'list' object has no attribute 'values'
[throgg@spack-central spack]$
```

**Comment by adamjstewart** [comment]
Hmm, not sure why it would need to call graph.py, but this is probably fixed by #1330.

**Comment by adamjstewart** [comment]
Is this fixed now that #1330 is merged?

**Comment by hartzell** [comment]
@adamjstewart -- I'm trying to recreate this, but can't get the R bits to build anymore (issues have been filed, you have been helpful... :smile:).  Will keep poking at it.

**Comment by hartzell** [comment]
I can not reproduce this as of:

```
commit 2b94d7cf8eb97e7dd08ea26da0d3481dd36927d5
Merge: 3ea1325 5d48c10
Author: becker33 <becker33@llnl.gov>
Date:   Mon Aug 8 13:28:56 2016 -0700
```
