### ISSUE TITLE
Cryptic error message for compilers.yaml after OS update

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1476]
I'm getting this weird error every time I try to run `spack spec` or `spack install` on the latest develop:

```
Traceback (most recent call last):
  File "/home/ajstewart/spack/bin/spack", line 179, in <module>
    main()
  File "/home/ajstewart/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/ajstewart/spack/lib/spack/spack/cmd/spec.py", line 58, in spec
    spec.concretize()
  File "/home/ajstewart/spack/lib/spack/spack/spec.py", line 1246, in concretize
    self._concretize_helper())
  File "/home/ajstewart/spack/lib/spack/spack/spec.py", line 1067, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/ajstewart/spack/lib/spack/spack/spec.py", line 1067, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/ajstewart/spack/lib/spack/spack/spec.py", line 1078, in _concretize_helper
    spack.concretizer.concretize_compiler(self),
  File "/home/ajstewart/spack/lib/spack/spack/concretize.py", line 345, in concretize_compiler
    while not _proper_compiler_style(matches[index], spec.architecture):
IndexError: list index out of range
```

Oddly enough, I don't see this error message on our cluster; only on my laptop. I updated my laptop to Fedora 24 the other day, so that may be related. It now runs Python 2.7.12. Does anyone have any ideas?

**Comment by adamjstewart** [comment]
Figured it out. The problem was that my `compilers.yaml` still had the Fedora 23 compiler. Just had to re-run `spack compiler add` and it works now.

We should probably add a more useful error message for having no available compilers on this OS.

**Comment by BarrySmith** [comment]
Got hit with this again after some friendly sys-admin upgraded a machine I haven't used in a few weeks. I, of course, completely forgot I had gotten this problem before #1851 and only a search of issues refreshed my memory.  You definitely need spack to be a bit nicer with useful error messages in this situation. I am already missing too much hair :-)

**Comment by scheibelp** [comment]
I will look at this by the end of the week and provide an update by the end of 3/10
