### ISSUE TITLE
archive for GitFetchStrategy at least for resources fails on assert

### ISSUE THREAD

**Issue by trws** [LLNL/spack#1520]
Somehow the GitFetchStrategy, at least for resources and at least for resources with tags, attempts to archive as a tar.gz, which asserts that there be a .tar.gz extension, without adding said extension.  This comes up with the llvm package when mixing the cling git repos into the mix, will follow up with more details if they become available.

**Comment by JaroslavHron** [comment]
Any more datils on this? Probably i see the same problem:
```
Traceback (most recent call last):
  File "/usr/local/pkg/spack_dev/lib/spack/spack/build_environment.py", line 521, in fork
    function()
  File "/usr/local/pkg/spack_dev/lib/spack/spack/package.py", line 925, in build_process
    self.do_patch()
  File "/usr/local/pkg/spack_dev/lib/spack/spack/package.py", line 745, in do_patch
    self.do_stage()
  File "/usr/local/pkg/spack_dev/lib/spack/spack/package.py", line 734, in do_stage
    self.do_fetch(mirror_only)
  File "/usr/local/pkg/spack_dev/lib/spack/spack/package.py", line 726, in do_fetch
    self.stage.cache_local()
  File "/usr/local/pkg/spack_dev/lib/spack/spack/util/pattern.py", line 84, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/usr/local/pkg/spack_dev/lib/spack/spack/stage.py", line 371, in cache_local
    spack.fetch_cache.store(self.fetcher, self.mirror_path)
  File "/usr/local/pkg/spack_dev/lib/spack/spack/fetch_strategy.py", line 860, in store
    fetcher.archive(dst)
  File "/usr/local/pkg/spack_dev/lib/spack/spack/fetch_strategy.py", line 606, in archive
    super(GitFetchStrategy, self).archive(destination, exclude='.git')
  File "/usr/local/pkg/spack_dev/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/pkg/spack_dev/lib/spack/spack/fetch_strategy.py", line 410, in archive
    assert (extension(destination) == 'tar.gz')
AssertionError
==> Error: Installation process had nonzero exit code : 256
```
using `resource()` with `git=` and `tag=`

**Comment by tgamblin** [comment]
@scheibelp: can you look at this one?

**Comment by scheibelp** [comment]
I can look into reproducing/fixing.

@JaroslavHron @trws do you know of a particular package in the repo that triggers this? or do you have a package.py you could attach which reproduces? Thanks!

**Comment by trws** [comment]
Try the llvm package using a version that uses tags.

**Comment by scheibelp** [comment]
Thanks I can reproduce the issue. I think I can resolve it today - the bug has to do with mirror_path construction for resource stages in Package._make_resource_stage
