### ISSUE TITLE
spack install llvm fails

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#15333]
`spack install llvm` is failing for me. I have the full output below, but the gist of it is that I get this error:

>   >> 857    CMake Error at /tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyz
>             zpurwqukh3wfeazimpnnelw7h2t4o/spack-src/lldb/docs/CMakeLists.txt:32
>              (get_target_property):
>      858      get_target_property() called with non-existent target "swig_wrapp
>             er".
> 

I'm not very savvy with cmake, so I'm not sure where this swig_wrapper property should be defined. It's also not clear to me who is to blame (i.e., this may be a bug in LLDB's cmake files). I did do some Google searching, and this is related to -DLLDB_DISABLE_PYTHON:Bool=TRUE being defined, which the llvm package defines with the ~python variant. This problem occurs with LLVM version 9.0.0 and 9.0.1, but not with 8.0.0.
 

> [testnewm@opal186 spack]$ ./bin/spack install llvm
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libiconv-1.16-mqkdx7bouqvxtv3vnsv5wbznqxjayixq
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/pkgconf-1.6.3-6llfswwqpuen74nokzl5svey5alrn34k
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/xz-5.2.4-sogjktqmpjvf2qxllrg5iw4onqjts6ne
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/zlib-1.2.11-q6cqrdto4iktfg6qyqcc5u4vmfmwb7iv
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libbsd-0.10.0-w7ypvsvc3vrmfkha7xei3bshoh6weedf
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libffi-3.2.1-d2qqz3c7dwtwhy4hzfme67u5gcs4tfqf
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/pcre-8.43-euujk3sdm2rfo7snbdqgx4o6xvcims3a
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/tar-1.32-4rewdu3ojdebt6bh7z7lamitnd6jqksh
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/diffutils-3.7-vo3dwmzrciclnnffakguirtskbkirpzs
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libxml2-2.9.9-du2pbfm4uihgrndgtgegrfdgb4lip2gn
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/expat-2.2.9-brv5ea7ytywc6jfuswvob54ltgzlplc5
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/swig-4.0.0-eircimzrcfngaa6xten7fra4sk3hljqg
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/bzip2-1.0.8-uqkiukpjvphwvw2z5cixcsqldvavkmgt
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/readline-8.0-d7wyzslwmkhbjjnwyfw26ryt6w2ycgey
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/gettext-0.20.1-yu5foe6u4h55me4jzqep55qahvb7cb2t
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/gdbm-1.18.1-4oeheqngmce6lfdwzkhho4xjtmodx2sn
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/sqlite-3.30.1-4p46itzsnxzn4kblxvzrgs7pnym42ygt
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/perl-5.30.1-rvd5qkt52nzgl5xygw3w2tcswwmrm2vq
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/openssl-1.1.1d-2ftox4bi4fr2oj2r5w3k7xhztieeuqhn
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/perl-data-dumper-2.173-fw4koba234av5pyx2ffwameiyfkiwge7
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/cmake-3.16.2-v6uuojtytntsnb4gcfpojnaowcttzmvi
> [+] /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz
> ==> 16519: Installing llvm
> ==> Using cached archive: /usr/WS2/testnewm/spack/var/spack/cache/_source-cache/archive/be/be7b034641a5fda51ffca7f5d840b1a768737779f75f7c4fd18fe2d37820289a.tar.gz
> ==> Staging archive: /var/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/llvmorg-9.0.1.tar.gz
> ==> Created stage in /var/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o
> ==> Applied patch /usr/WS2/testnewm/spack/var/spack/repos/builtin/packages/llvm/constexpr_longdouble_9.0.patch
> ==> 16519: llvm: Building llvm [CMakePackage]
> ==> 16519: llvm: Executing phase: 'cmake'
> ==> Error: ProcessError: Command exited with status 1:
>     'cmake' '/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/spack-src/llvm' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib64;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/gettext-0.20.1-yu5foe6u4h55me4jzqep55qahvb7cb2t/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/bzip2-1.0.8-uqkiukpjvphwvw2z5cixcsqldvavkmgt/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libxml2-2.9.9-du2pbfm4uihgrndgtgegrfdgb4lip2gn/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libiconv-1.16-mqkdx7bouqvxtv3vnsv5wbznqxjayixq/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/xz-5.2.4-sogjktqmpjvf2qxllrg5iw4onqjts6ne/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/zlib-1.2.11-q6cqrdto4iktfg6qyqcc5u4vmfmwb7iv/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/pcre-8.43-euujk3sdm2rfo7snbdqgx4o6xvcims3a/lib' '-DCMAKE_PREFIX_PATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/cmake-3.16.2-v6uuojtytntsnb4gcfpojnaowcttzmvi;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/perl-data-dumper-2.173-fw4koba234av5pyx2ffwameiyfkiwge7;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/swig-4.0.0-eircimzrcfngaa6xten7fra4sk3hljqg;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6' '-DLLVM_REQUIRES_RTTI:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_EH:BOOL=ON' '-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libomp' '-DPYTHON_EXECUTABLE:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz/bin/python3.7' '-DCUDA_TOOLKIT_ROOT_DIR:PATH=IGNORE' '-DCUDA_SDK_ROOT_DIR:PATH=IGNORE' '-DCUDA_NVCC_EXECUTABLE:FILEPATH=IGNORE' '-DLIBOMPTARGET_DEP_CUDA_DRIVER_LIBRARIES:STRING=IGNORE' '-DLLDB_DISABLE_PYTHON:Bool=TRUE' '-DLLVM_BINUTILS_INCDIR=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/include' '-DCLANG_DEFAULT_CXX_STDLIB=libc++' '-DLINK_POLLY_INTO_TOOLS:Bool=ON' '-DLLVM_TARGETS_TO_BUILD:STRING=NVPTX;AMDGPU;X86' '-DGCC_INSTALL_PREFIX=/usr/tce/packages/gcc/gcc-8.1.0' '-DCMAKE_BUILD_WITH_INSTALL_RPATH=1' '-DLLVM_ENABLE_PROJECTS:STRING=clang;clang-tools-extra;openmp;lldb;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly'
> 
> 1 error found in build log:
>      851    -- Looking for compression_encode_buffer in compression
>      852    -- Looking for compression_encode_buffer in compression - not found
>      853    -- Symbols (liblldb): exporting all symbols from the lldb namespace
>      854    -- Found Doxygen: /bin/doxygen (found version "1.8.5") found compon
>             ents: doxygen dot
>      855    -- Found epydoc - /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-bro
>             adwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz/bin/
>             epydoc
>      856    -- Found dot - /bin/dot
>   >> 857    CMake Error at /tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyz
>             zpurwqukh3wfeazimpnnelw7h2t4o/spack-src/lldb/docs/CMakeLists.txt:32
>              (get_target_property):
>      858      get_target_property() called with non-existent target "swig_wrapp
>             er".
>      859    
>      860    
>      861    -- Failed to find LLVM FileCheck
>      862    -- Version: 0.0.0
>      863    -- Performing Test HAVE_CXX_FLAG_STD_CXX11
> 
> See build log for details:
>   /var/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/spack-build-out.txt
> 
> ==> Error: Failed to install llvm due to ChildError: ProcessError: Command exited with status 1:
>     'cmake' '/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/spack-src/llvm' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib64;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/gettext-0.20.1-yu5foe6u4h55me4jzqep55qahvb7cb2t/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/bzip2-1.0.8-uqkiukpjvphwvw2z5cixcsqldvavkmgt/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libxml2-2.9.9-du2pbfm4uihgrndgtgegrfdgb4lip2gn/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libiconv-1.16-mqkdx7bouqvxtv3vnsv5wbznqxjayixq/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/xz-5.2.4-sogjktqmpjvf2qxllrg5iw4onqjts6ne/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/zlib-1.2.11-q6cqrdto4iktfg6qyqcc5u4vmfmwb7iv/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/pcre-8.43-euujk3sdm2rfo7snbdqgx4o6xvcims3a/lib' '-DCMAKE_PREFIX_PATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/cmake-3.16.2-v6uuojtytntsnb4gcfpojnaowcttzmvi;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/perl-data-dumper-2.173-fw4koba234av5pyx2ffwameiyfkiwge7;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/swig-4.0.0-eircimzrcfngaa6xten7fra4sk3hljqg;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6' '-DLLVM_REQUIRES_RTTI:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_EH:BOOL=ON' '-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libomp' '-DPYTHON_EXECUTABLE:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz/bin/python3.7' '-DCUDA_TOOLKIT_ROOT_DIR:PATH=IGNORE' '-DCUDA_SDK_ROOT_DIR:PATH=IGNORE' '-DCUDA_NVCC_EXECUTABLE:FILEPATH=IGNORE' '-DLIBOMPTARGET_DEP_CUDA_DRIVER_LIBRARIES:STRING=IGNORE' '-DLLDB_DISABLE_PYTHON:Bool=TRUE' '-DLLVM_BINUTILS_INCDIR=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/include' '-DCLANG_DEFAULT_CXX_STDLIB=libc++' '-DLINK_POLLY_INTO_TOOLS:Bool=ON' '-DLLVM_TARGETS_TO_BUILD:STRING=NVPTX;AMDGPU;X86' '-DGCC_INSTALL_PREFIX=/usr/tce/packages/gcc/gcc-8.1.0' '-DCMAKE_BUILD_WITH_INSTALL_RPATH=1' '-DLLVM_ENABLE_PROJECTS:STRING=clang;clang-tools-extra;openmp;lldb;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly'
> 1 error found in build log:
>      851    -- Looking for compression_encode_buffer in compression
>      852    -- Looking for compression_encode_buffer in compression - not found
>      853    -- Symbols (liblldb): exporting all symbols from the lldb namespace
>      854    -- Found Doxygen: /bin/doxygen (found version "1.8.5") found compon
>             ents: doxygen dot
>      855    -- Found epydoc - /usr/WS2/testnewm/spack/opt/spack/linux-rhel7-bro
>             adwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz/bin/
>             epydoc
>      856    -- Found dot - /bin/dot
>   >> 857    CMake Error at /tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyz
>             zpurwqukh3wfeazimpnnelw7h2t4o/spack-src/lldb/docs/CMakeLists.txt:32
>              (get_target_property):
>      858      get_target_property() called with non-existent target "swig_wrapp
>             er".
>      859    
>      860    
>      861    -- Failed to find LLVM FileCheck
>      862    -- Version: 0.0.0
>      863    -- Performing Test HAVE_CXX_FLAG_STD_CXX11
> 
> See build log for details:
>   /var/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/spack-build-out.txt
> Traceback (most recent call last):
>   File "/usr/WS2/testnewm/spack/lib/spack/spack/build_environment.py", line 801, in child_process
>     return_value = function()
>   File "/usr/WS2/testnewm/spack/lib/spack/spack/installer.py", line 1109, in build_process
>     phase(pkg.spec, pkg.prefix)
>   File "/usr/WS2/testnewm/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
>     phase(spec, prefix)
>   File "/usr/WS2/testnewm/spack/lib/spack/spack/build_systems/cmake.py", line 242, in cmake
>     inspect.getmodule(self).cmake(*options)
>   File "/usr/WS2/testnewm/spack/lib/spack/spack/util/executable.py", line 189, in __call__
>     proc.returncode, long_msg)
> spack.util.executable.ProcessError: Command exited with status 1:
>     'cmake' '/tmp/testnewm/spack-stage/spack-stage-llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/spack-src/llvm' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/llvm-9.0.1-uyzzpurwqukh3wfeazimpnnelw7h2t4o/lib64;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/gettext-0.20.1-yu5foe6u4h55me4jzqep55qahvb7cb2t/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/bzip2-1.0.8-uqkiukpjvphwvw2z5cixcsqldvavkmgt/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libxml2-2.9.9-du2pbfm4uihgrndgtgegrfdgb4lip2gn/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libiconv-1.16-mqkdx7bouqvxtv3vnsv5wbznqxjayixq/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/xz-5.2.4-sogjktqmpjvf2qxllrg5iw4onqjts6ne/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/zlib-1.2.11-q6cqrdto4iktfg6qyqcc5u4vmfmwb7iv/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx/lib;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/pcre-8.43-euujk3sdm2rfo7snbdqgx4o6xvcims3a/lib' '-DCMAKE_PREFIX_PATH:STRING=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/cmake-3.16.2-v6uuojtytntsnb4gcfpojnaowcttzmvi;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/perl-data-dumper-2.173-fw4koba234av5pyx2ffwameiyfkiwge7;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/ncurses-6.1-2mb4gfutb2ae7urvqwminjqiauz3xr7l;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/swig-4.0.0-eircimzrcfngaa6xten7fra4sk3hljqg;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/libedit-3.1-20191231-7dzoe5kh7j44pdgdt7zhy32kscgvbyzx;/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6' '-DLLVM_REQUIRES_RTTI:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_EH:BOOL=ON' '-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libomp' '-DPYTHON_EXECUTABLE:PATH=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/python-3.7.6-3r6qnnsxmx3vwuib7j4wk7kyznl42pdz/bin/python3.7' '-DCUDA_TOOLKIT_ROOT_DIR:PATH=IGNORE' '-DCUDA_SDK_ROOT_DIR:PATH=IGNORE' '-DCUDA_NVCC_EXECUTABLE:FILEPATH=IGNORE' '-DLIBOMPTARGET_DEP_CUDA_DRIVER_LIBRARIES:STRING=IGNORE' '-DLLDB_DISABLE_PYTHON:Bool=TRUE' '-DLLVM_BINUTILS_INCDIR=/usr/WS2/testnewm/spack/opt/spack/linux-rhel7-broadwell/gcc-8.1.0/binutils-2.33.1-pic6qzbrf2i7h66otaicbkzgygtuc6g6/include' '-DCLANG_DEFAULT_CXX_STDLIB=libc++' '-DLINK_POLLY_INTO_TOOLS:Bool=ON' '-DLLVM_TARGETS_TO_BUILD:STRING=NVPTX;AMDGPU;X86' '-DGCC_INSTALL_PREFIX=/usr/tce/packages/gcc/gcc-8.1.0' '-DCMAKE_BUILD_WITH_INSTALL_RPATH=1' '-DLLVM_ENABLE_PROJECTS:STRING=clang;clang-tools-extra;openmp;lldb;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly'
> 
>

**Comment by hainest** [comment]
I can confirm this is still an issue with the current head of develop (9d1f71e89), but installing 8.0.0 and 10.0.0 works fine.

**Comment by sskutnik** [comment]
I am also experiencing this issue on Big Sur (macOS 11.4), with `llvm-9.0.1`, compiling with `clang-12.0.5`

Digging into the logs, it looks like it's failing in the compile here:

```
/private/var/folders/7m/941_v1hs1957zx9sn_br50r0yj4h5b/T/qv9/spack-stage/spack-stage-llvm-9.0.1-3nz6x644typz5vq6xkpqwwlu4xmf3v73/spack-src/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:31: error: invalid application of 'sizeof' to an incomplete type 'struct stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                              ^     ~~~~~~~~~~~~~~~
/private/var/folders/7m/941_v1hs1957zx9sn_br50r0yj4h5b/T/qv9/spack-stage/spack-stage-llvm-9.0.1-3nz6x644typz5vq6xkpqwwlu4xmf3v73/spack-src/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:45: note: forward declaration of '__sanitizer::stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                                            ^
/private/var/folders/7m/941_v1hs1957zx9sn_br50r0yj4h5b/T/qv9/spack-stage/spack-stage-llvm-9.0.1-3nz6x644typz5vq6xkpqwwlu4xmf3v73/spack-src/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:195:33: error: invalid application of 'sizeof' to an incomplete type 'struct statfs64'
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                ^     ~~~~~~~~~~~~~~~~~
/private/var/folders/7m/941_v1hs1957zx9sn_br50r0yj4h5b/T/qv9/spack-stage/spack-stage-llvm-9.0.1-3nz6x644typz5vq6xkpqwwlu4xmf3v73/spack-src/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:195:47: note: forward declaration of '__sanitizer::statfs64'
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                              ^
2 errors generated.
```

Note that this _seems_ to be similar to observed issues with building `clang` on Big Sur observed over at MacPorts:

https://trac.macports.org/ticket/61477
