### ISSUE TITLE
[Bug] Package Built but not in Database

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1568]
@davydden @adamjstewart @tgamblin 

I did `spack install modele`.  This failed on `modele`.  I immediately repeated `spack install modele`, which produced the following error on `everytrace`, one of `modele`'s dependencies:

```
==> everytrace is already installed in /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3/everytrace-develop-6jjehjenba2xqm6v6s37erahxzjxrblr
Traceback (most recent call last):
  File "bin/spack", line 184, in <module>
    main()
  File "bin/spack", line 161, in main
    return_val = command(parser, args)
  File "/home2/rpfische/spack2/lib/spack/spack/cmd/install.py", line 92, in install
    explicit=True)
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 909, in do_install
    run_tests=run_tests)
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 1059, in do_install_dependencies
    dep.package.do_install(**kwargs)
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 891, in do_install
    rec = spack.installed_db.get_record(self.spec)
  File "/home2/rpfische/spack2/lib/spack/spack/database.py", line 76, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home2/rpfische/spack2/lib/spack/spack/database.py", line 468, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/home2/rpfische/spack2/lib/spack/spack/database.py", line 463, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! everytrace@develop%gcc@4.9.3+fortran+mpi arch=linux-centos7-x86_64^cmake@3.6.0%gcc@4.9.3~doc+ncurses+openssl~qt arch=linux-centos7-x86_64^hwloc@1.11.3%gcc@4.9.3 arch=linux-centos7-x86_64^libpciaccess@0.13.4%gcc@4.9.3 arch=linux-centos7-x86_64^libsigsegv@2.10%gcc@4.9.3 arch=linux-centos7-x86_64^libtool@2.4.6%gcc@4.9.3 arch=linux-centos7-x86_64^m4@1.4.17%gcc@4.9.3+sigsegv arch=linux-centos7-x86_64^ncurses@6.0%gcc@4.9.3 arch=linux-centos7-x86_64^openmpi@2.0.0%gcc@4.9.3~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-centos7-x86_64^openssl@system%gcc@4.9.3 arch=linux-centos7-x86_64'
```

My guess is this is related to #1561, that something somewhere is handling `develop` versions in a way that breaks this code.  Any pointers to what might be going wrong?

**Comment by adamjstewart** [comment]
@citibeth This is unrelated to #1561. See #1266. Basically, the problem is that instead of adding each dependency to the database immediately after it is installed, Spack is waiting for the final package to be installed before adding everything at once. Obviously this is a bug. To workaround the problem for the time being, simply run `spack reindex`.

**Comment by tgamblin** [comment]
Duplicates #1266
