### ISSUE TITLE
[Bug] Private git downloads broken

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1569]
@tgamblin @adamjstewart 

I have a package `modele` sitting on a git server that requires authentication to login.  I've set up this authentication via SSH in my `.ssh/` directory.  My `package.py` file states:
```
    version('landice',
        git='simplex.giss.nasa.gov:/giss/gitrepo/modelE.git',
        branch='landice')
```
I can do `simplex.giss.nasa.gov:/giss/gitrepo/modelE.git` just fine.  However, when Spack tries to download, the git server asks me for a password (see below)?  Any ideas on what's happening?  I haven't yet been able to  debug this due to #1568.

```
==> Trying to clone git repository:
  simplex.giss.nasa.gov:/giss/gitrepo/modelE.git
  on branch landice
Cloning into 'modelE'...


+-----------------------------------------------------------------------+
|             * * * W A R N I N G       W A R N I N G * * *             |
|                                                                       |
|                     U.S. GOVERNMENT COMPUTER                          |
|                                                                       |
|      If not authorized to access this system, disconnect NOW.         |
|                                                                       |
|     YOU SHOULD HAVE NO EXPECTATION OF PRIVACY. By continuing, you     |
|     consent to your keystrokes and data content being monitored.      |
|                                                                       |
|   If you do not have authorization you are warned to disconnect at    |
|   once. Actual or attempted use, access, communication, or            |
|   examination by unauthorized persons is a criminal violation of      |
|   Title 18, United States Code, Section 1030.                         |
+-----------------------------------------------------------------------+


Enter passphrase for key '/home2/rpfische/.ssh/id_rsa': Traceback (most recent call last):
  File "/home2/rpfische/spack2/lib/spack/spack/build_environment.py", line 525, in fork

    function()
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 925, in build_process
    self.do_patch()
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 745, in do_patch
    self.do_stage()
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 734, in do_stage
    self.do_fetch(mirror_only)
  File "/home2/rpfische/spack2/lib/spack/spack/package.py", line 719, in do_fetch
    self.stage.fetch(mirror_only)
  File "/home2/rpfische/spack2/lib/spack/spack/util/pattern.py", line 84, in getter
    getattr(item, self.name)(*args, **kwargs)  File "/home2/rpfische/spack2/lib/spack/spack/stage.py", line 343, in fetch

==> Error: Keyboard interrupt.
    self.fetcher.fetch()
  File "/home2/rpfische/spack2/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
    return fun(self, *args, **kwargs)
  File "/home2/rpfische/spack2/lib/spack/spack/fetch_strategy.py", line 577, in fetch
    self.git(*(args + ['--depth', '1', self.url]))
  File "/home2/rpfische/spack2/lib/spack/spack/util/executable.py", line 161, in __call__
    out, err = proc.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 797, in communicate
    self.wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

**Comment by citibeth** [comment]
Funny thing... I encountered this bug yesterday; but when I tried to repeat the bug, I was stopped by #1568.  Today, I want past #1568 with a `spack reindex`, and then repeated: `bin/spack install modele`.  This time, the download worked just fine.

I don't know what's going on.  But if I can't repeat this, there's really nothing to debug.
