### ISSUE TITLE
Installation issue: blast-plus

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#16196]
When I build blast-plus on my `linux-centos8-aarch64` system, a build error reported:
```console
$spack install -v blast-plus
checking for dpkg-architecture... no
configure: error: Unable to find static libstdc++ requested by --with-bin-release.
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly/spack-src/c++/configure' '--prefix=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly' '--with-bin-release' '--without-debug' '--with-mt' '--without-boost' '--with-dll' '--without-static' '--without-static-exe' '--with-jpeg=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libjpeg-turbo-2.0.3-hd7odkwhxh7mjnfrbmxbi5d6bcdzy3ab' '--with-png=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libpng-1.6.37-qogkixx6s4s5b7aax5kmfeskpum2lms2' '--with-freetype=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/freetype-2.10.1-dpfayc4amqf2pbvlujzpim5v3cxfxid4' '--without-hdf5' '--with-z=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/zlib-1.2.11-r26fdvv4oowwlm4yozeoozfvg6kkkeoa' '--with-bz2=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/bzip2-1.0.8-3z4cm7torpanvuhuihxyb27zr3mjkarn' '--with-lzo=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/lzo-2.10-2gf6ago32atveouyy2xsokeu42aswnzw' '--with-gnutls=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/gnutls-3.6.8-nbh2tykjf5e3c5ri2afzcthnsmxlosac' '--with-openssl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/openssl-1.1.1f-d7q5m67fw37b3yx5ecwz3vavyreoph2m' '--with-pcre=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/pcre-8.43-wfibdgpfa4y5h7j73zvg4w6yxse4b6pc' '--with-python=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/python-3.7.6-3l76x2zpiklatzhne5e7xa6dvkw7nvgr' '--with-perl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/perl-5.30.1-jjanez4jarykzlbl7o3dqo7ceehlloyz'

1 error found in build log:
     34    checking whether /home/xiaojun/spack/lib/spack/env/gcc/gcc  has an option to discard unneeded shared libraries... -Wl,--as-needed
     35    checking whether /home/xiaojun/spack/lib/spack/env/gcc/gcc  has an option to link in whole static archives... -Wl,--whole-archive
     36    checking whether _LIBCPP_VERSION is declared... no
     37    checking how to enable C++ '11 features in /home/xiaojun/spack/lib/spack/env/gcc/g++ ... -std=gnu++11
     38    checking how to enable C '11 or at least '99 features in /home/xiaojun/spack/lib/spack/env/gcc/gcc ... -std=gnu11 -fgnu89-inline
     39    checking for dpkg-architecture... no
  >> 40    configure: error: Unable to find static libstdc++ requested by --with-bin-release.

See build log for details:
  /tmp/root/spack-stage/spack-stage-blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly/spack-build-out.txt

==> Error: Failed to install blast-plus due to ChildError: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly/spack-src/c++/configure' '--prefix=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly' '--with-bin-release' '--without-debug' '--with-mt' '--without-boost' '--with-dll' '--without-static' '--without-static-exe' '--with-jpeg=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libjpeg-turbo-2.0.3-hd7odkwhxh7mjnfrbmxbi5d6bcdzy3ab' '--with-png=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libpng-1.6.37-qogkixx6s4s5b7aax5kmfeskpum2lms2' '--with-freetype=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/freetype-2.10.1-dpfayc4amqf2pbvlujzpim5v3cxfxid4' '--without-hdf5' '--with-z=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/zlib-1.2.11-r26fdvv4oowwlm4yozeoozfvg6kkkeoa' '--with-bz2=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/bzip2-1.0.8-3z4cm7torpanvuhuihxyb27zr3mjkarn' '--with-lzo=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/lzo-2.10-2gf6ago32atveouyy2xsokeu42aswnzw' '--with-gnutls=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/gnutls-3.6.8-nbh2tykjf5e3c5ri2afzcthnsmxlosac' '--with-openssl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/openssl-1.1.1f-d7q5m67fw37b3yx5ecwz3vavyreoph2m' '--with-pcre=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/pcre-8.43-wfibdgpfa4y5h7j73zvg4w6yxse4b6pc' '--with-python=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/python-3.7.6-3l76x2zpiklatzhne5e7xa6dvkw7nvgr' '--with-perl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/perl-5.30.1-jjanez4jarykzlbl7o3dqo7ceehlloyz'
1 error found in build log:
     34    checking whether /home/xiaojun/spack/lib/spack/env/gcc/gcc  has an option to discard unneeded shared libraries... -Wl,--as-needed
     35    checking whether /home/xiaojun/spack/lib/spack/env/gcc/gcc  has an option to link in whole static archives... -Wl,--whole-archive
     36    checking whether _LIBCPP_VERSION is declared... no
     37    checking how to enable C++ '11 features in /home/xiaojun/spack/lib/spack/env/gcc/g++ ... -std=gnu++11
     38    checking how to enable C '11 or at least '99 features in /home/xiaojun/spack/lib/spack/env/gcc/gcc ... -std=gnu11 -fgnu89-inline
     39    checking for dpkg-architecture... no
  >> 40    configure: error: Unable to find static libstdc++ requested by --with-bin-release.

See build log for details:
  /tmp/root/spack-stage/spack-stage-blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly/spack-build-out.txt
Traceback (most recent call last):
  File "/home/xiaojun/spack/lib/spack/spack/build_environment.py", line 802, in child_process
    return_value = function()
  File "/home/xiaojun/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/xiaojun/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/xiaojun/spack/lib/spack/spack/build_systems/autotools.py", line 298, in configure
    inspect.getmodule(self).configure(*options)
  File "/home/xiaojun/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly/spack-src/c++/configure' '--prefix=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/blast-plus-2.9.0-wunkydut522ea36rgx5xz33aipc6d7ly' '--with-bin-release' '--without-debug' '--with-mt' '--without-boost' '--with-dll' '--without-static' '--without-static-exe' '--with-jpeg=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libjpeg-turbo-2.0.3-hd7odkwhxh7mjnfrbmxbi5d6bcdzy3ab' '--with-png=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/libpng-1.6.37-qogkixx6s4s5b7aax5kmfeskpum2lms2' '--with-freetype=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/freetype-2.10.1-dpfayc4amqf2pbvlujzpim5v3cxfxid4' '--without-hdf5' '--with-z=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/zlib-1.2.11-r26fdvv4oowwlm4yozeoozfvg6kkkeoa' '--with-bz2=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/bzip2-1.0.8-3z4cm7torpanvuhuihxyb27zr3mjkarn' '--with-lzo=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/lzo-2.10-2gf6ago32atveouyy2xsokeu42aswnzw' '--with-gnutls=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/gnutls-3.6.8-nbh2tykjf5e3c5ri2afzcthnsmxlosac' '--with-openssl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/openssl-1.1.1f-d7q5m67fw37b3yx5ecwz3vavyreoph2m' '--with-pcre=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/pcre-8.43-wfibdgpfa4y5h7j73zvg4w6yxse4b6pc' '--with-python=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/python-3.7.6-3l76x2zpiklatzhne5e7xa6dvkw7nvgr' '--with-perl=/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/perl-5.30.1-jjanez4jarykzlbl7o3dqo7ceehlloyz'
```

And if I remove the `--with-bin-release` in `blast-plus/package.py` with follow patch, the build error is gone.
```
diff --git a/var/spack/repos/builtin/packages/blast-plus/package.py b/var/spack/repos/builtin/packages/blast-plus/package.py
index febe4fc15..a9d9df758 100644
--- a/var/spack/repos/builtin/packages/blast-plus/package.py
+++ b/var/spack/repos/builtin/packages/blast-plus/package.py
@@ -99,7 +99,7 @@ def configure_args(self):
         spec   = self.spec

         config_args = [
-            '--with-bin-release',
+#            '--with-bin-release',
             '--without-debug',
             '--with-mt',
             '--without-boost',
```

**Comment by hartzell** [comment]
It's trying to build static binaries and needs the static version of libstdc++.  That's usually a separate package (rpm,...) that needs to be installed via the OS.

An alternative fix to what you're providing is to install that package.  I *think* that if you build a compiler within Spack (a gcc) it will also build the static libraries.

**Comment by darmac** [comment]
Yah, so is it should depends_on gcc in this package.py?
I think most of the rpm/deb package will not include a static stdc++ ?
maybe we should build by spack...

**Comment by LutzWeischerFujitsu** [comment]
It looks like this is not solved, on A64FX, CentOS 8: 

[jw@cn05 jw]$ spack/bin/spack install blast-plus
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libiconv-1.16-pp6ex45xatkqm57evnnymts2e3jkjtgc
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/zlib-1.2.11-nssknf4ybspjgs5ip3g52h6gdsg7xvw4
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/pkgconf-1.7.3-kdzlczv6oqysvfvd6kwnpkjjblqoiame
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/xz-5.2.5-jtmowx7dpqrewoquz7adz5ljn6av2wcm
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libsigsegv-2.12-uuwjvkvewnesghp2jwo77mdqnyqasaxn
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/berkeley-db-18.1.40-xhqs6cvlnggxtzkysk2fr5rdmzkbar3h
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/nasm-2.15.05-txhnfxaynn4snhjwkpsj7b6xeheas7vd
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/lmdb-0.9.24-ihogsorx7vcwevs6z656cxwc25nltp43
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/lzo-2.10-aytanhf6r6fq6k2mlgm2s536e7av4bb2
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/pcre-8.44-2oeu3wxdsb72sqx5thzhtxh4lwtk6f6l
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libbsd-0.10.0-uyaxcptvjncrbqd4ll4fgfw3upb2tk6g
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libffi-3.3-irtrfdvukdvrcxy3lehlgll7s5g7blm4
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/diffutils-3.7-p5u2pdhngtumslqt5gjzod2p5cjiqilf
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/tar-1.32-25ss6x3ehcyflvuqyo3v4ajgmb7kzmii
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libpng-1.6.37-li34bp7jvpajzdp2smn4jh3572mm7yvr
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/ncurses-6.2-vsgvk3ktw3v5pvbdcdnqjynfjwf26lx3
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/util-linux-uuid-2.36-p2ovzsijah54no7tv6cieqkkygtmfzho
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libxml2-2.9.10-amicqitgaop2jx3kahmques5ck4p3ngp
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/m4-1.4.18-vpf7mp2xlvr3duamy4vc6qqe5g6zkjzr
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/expat-2.2.10-asbrkcc4enoin5hx72y2wwhse5l7wlyw
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/bzip2-1.0.8-tk2t636zh35aaclggn2pk76f6v5qw2js
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/readline-8.0-2bgw5veq6zdka6jq2rwqtitmt3rw3l3i
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libtool-2.4.6-7klygtmvowharn4zo652hvm43ih7iztn
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gettext-0.21-j2w7r34kq73eirvbgzwvcmueiy2dyoso
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/freetype-2.10.1-dyoc73a5ppiwcqfpucif7foem4s4ehqj
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gdbm-1.18.1-2dz44zlqyllstopcd42uorqaea6lne7p
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/sqlite-3.34.0-yn5c6am6zpkqd3kjfbhrtiwjyevpoj5t
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-5.32.0-frdefhbg5p3mvsvixidnnh4sp6n6n7xf
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/autoconf-2.69-p4mt7izhlu73hpsgwncwv3xl5722eorf
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/openssl-1.1.1i-y3kre56snhsybjhcktyywmbvmfqtmwi6
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/automake-1.16.3-dc74kpbotu3duvjuartzxliz7xyledfm
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/cmake-3.19.2-kqkqfjeelfp5hchzopmnh4g5cwyx57hh
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/python-3.8.7-uduadrnq3zce7h5jm332dcwoy5wumtdm
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gmp-6.1.2-z5ww55chlukjuropyrb4hwcpdg65jbbm
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libjpeg-turbo-2.0.6-4t27wcqztrncpbftoietl33mscccx3ll
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/nettle-3.4.1-mcgqxw3qymeejkjuoobjbgd7j43zesqh
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gnutls-3.6.14-2gzdudltpc6n2t53hmwvlvmfvcix5cz7
==> Installing blast-plus-2.11.0-fjncf36dyflhv6wlansj6sew7wyykkc7
==> No binary for blast-plus-2.11.0-fjncf36dyflhv6wlansj6sew7wyykkc7 found: installing from source
==> Using cached archive: /data/jw/spack/var/spack/cache/_source-cache/archive/d8/d88e1858ae7ce553545a795a2120e657a799a6d334f2a07ef0330cc3e74e1954.tar.gz
==> blast-plus: Executing phase: 'autoreconf'
==> blast-plus: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/jw/spack-stage/spack-stage-blast-plus-2.11.0-fjncf36dyflhv6wlansj6sew7wyykkc7/spack-src/c++/configure' '--prefix=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/blast-plus-2.11.0-fjncf36dyflhv6wlansj6sew7wyykkc7' '--with-bin-release' '--without-debug' '--with-mt' '--without-boost' '--with-dll' '--without-static' '--without-static-exe' '--with-jpeg=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libjpeg-turbo-2.0.6-4t27wcqztrncpbftoietl33mscccx3ll' '--with-png=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/libpng-1.6.37-li34bp7jvpajzdp2smn4jh3572mm7yvr' '--with-freetype=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/freetype-2.10.1-dyoc73a5ppiwcqfpucif7foem4s4ehqj' '--without-hdf5' '--with-z=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/zlib-1.2.11-nssknf4ybspjgs5ip3g52h6gdsg7xvw4' '--with-bz2=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/bzip2-1.0.8-tk2t636zh35aaclggn2pk76f6v5qw2js' '--with-lzo=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/lzo-2.10-aytanhf6r6fq6k2mlgm2s536e7av4bb2' '--with-gnutls=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gnutls-3.6.14-2gzdudltpc6n2t53hmwvlvmfvcix5cz7' '--with-openssl=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/openssl-1.1.1i-y3kre56snhsybjhcktyywmbvmfqtmwi6' '--with-pcre=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/pcre-8.44-2oeu3wxdsb72sqx5thzhtxh4lwtk6f6l' '--with-python=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/python-3.8.7-uduadrnq3zce7h5jm332dcwoy5wumtdm' '--with-perl=/data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-5.32.0-frdefhbg5p3mvsvixidnnh4sp6n6n7xf'

1 error found in build log:
     56    checking whether /data/jw/spack/lib/spack/env/gcc/gcc  has an option to discard unneeded shared libraries...
            -Wl,--as-needed
     57    checking whether /data/jw/spack/lib/spack/env/gcc/gcc  has an option to link in whole static archives... -Wl
           ,--whole-archive
     58    checking whether _LIBCPP_VERSION is declared... no
     59    checking how to enable C++ '14 features in /data/jw/spack/lib/spack/env/gcc/g++ ... -std=gnu++14
     60    checking how to enable C '11 or at least '99 features in /data/jw/spack/lib/spack/env/gcc/gcc ... -std=gnu11
            -fgnu89-inline
     61    checking for dpkg-architecture... no
  >> 62    configure: error: Unable to find static libstdc++ requested by --with-bin-release.

See build log for details:
  /tmp/jw/spack-stage/spack-stage-blast-plus-2.11.0-fjncf36dyflhv6wlansj6sew7wyykkc7/spack-build-out.txt

[jw@cn05 jw]$ spack/bin/spack debug report
* **Spack:** 0.16.0-948-9d1d37c432
* **Python:** 3.6.8
* **Platform:** linux-centos8-a64fx
* **Concretizer:** original
[jw@cn05 jw]$

**Comment by alansill** [comment]
> It's trying to build static binaries and needs the static version of libstdc++. That's usually a separate package (rpm,...) that needs to be installed via the OS.
> 
> An alternative fix to what you're providing is to install that package. I _think_ that if you build a compiler within Spack (a gcc) it will also build the static libraries.

Yes, the solution appears to be to install libstdc++-static separately at the OS level if you are using system-wide compilers, or separately in your spack installation ahead of time, for example by building and configuring a spack-supplied gcc in your compiler list. The issue could be better handled in the dependency resolution, I think.
