### ISSUE TITLE
Spack built python and pip can't install functional pipenv when using modules

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#16195]
I'm trying to use tools from a Spack installation to set up a python virtual environment.  I feel like I'm in a maze of twisty turny passages that I've been in before but can't remember the way out.

I've installed python@2.7.16 (I'm trying to get some vintage code working), py-pip, and py-setuptools, along with a bunch of other things.

I've done this:

```
module load python/2.7.16
module load py-pip/19.3-py2.7.16
module load py-setuptools/41.4.0-py2.7.16
rm Pipfile
rm Pipfile.lock
rm -rf ~/.local
pip install --user pipenv
pipenv install fastinterval
```

The pipenv runs for a while but eventually crashes like so:

```
⠦ Creating virtual environment...created virtual environment CPython2.7.16.final.0-64 in 44853ms
  creator CPython2Posix(dest=/home/george.hartzell/.local/share/virtualenvs/Primer3Wrapper-cACNdJ8_, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/george.hartzell/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/george.hartzell/.local/share/virtualenvs/Primer3Wrapper-cACNdJ8_
Creating a Pipfile for this project...
Installing fastinterval...
Adding fastinterval to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
✔ Success!
Updated Pipfile.lock (baf29e)!
Installing dependencies from Pipfile.lock (baf29e)...
An error occurred while installing bx-python==0.8.8 --hash=sha256:02b6ddc524598cb77e247fb28d2a6844fd1176853116dcac238ea05eee8a5623 --hash=sha256:04f86a465b234bf177aead698b4c0df6815985179b037cf9add65a9028168050 --hash=sha256:0e8213df9d4e0cb0738c6eb08147d4808763d43823b5afa0847f22e1a9938a59 --hash=sha256:1649f04e1ed1ef710b5b2b5d774613dd0888a9c9c7296e13175a9849332dd4a7 --hash=sha256:16b360b630af051b85f0da59a514be701d6a31bc40d3520cd947b394f07e47b9 --hash=sha256:2147c33a8845a003a8fa9f726a310fc405ceaf826ede6ae1e95b89578255dd05 --hash=sha256:23734c8514fe323deb99b674e5dab76a01526133a2daf6f05ade51dfc1278be2 --hash=sha256:35d7851e016f5e7b370385b3f812f7e6ecc1164565d7f0cf16b0edd151e54bd5 --hash=sha256:3897be25e7a916da603d1feca6d4f27d7e39eebea8fe1a7fbdd1f0b8a309ff6d --hash=sha256:3af8f6aa8ada757a97230a19faa8bee07b4fbf29d4974fcda01b25e1ab3c4ec6 --hash=sha256:3b95b02d032df9f59214e7b06e9579dd1fbb97a718d62d97b8bbb7c56bf6d7b5 --hash=sha256:3ca2b5ce6490ae3bf35e9e9725b34f997e0a9d80d0a79deae44e51161600770e --hash=sha256:3d2c32ed1eab0836fe46fe46d756da063445fbe6d0000c21fd3ab94e35faebf3 --hash=sha256:44946191d7428f132b7fd6f9bf03de944e5d073925fb0c6846e829791425d313 --hash=sha256:4af71439ef6fb56e4814e32897d54d079593c3753321a5f434709470d326e4ca --hash=sha256:4bae231f35a802d2d8719808da67ce87d3d4f80a14ff728f21f469677e2439bb --hash=sha256:577343f278d28da81ada958dca303e0f6c709674d14dffd27f5d47ef91fb6181 --hash=sha256:69bbd6997edd65ba3abe01fb05e9f6633cf110e0187cdcf332bbc74eca16c29b --hash=sha256:75b9025bceb77ea4255ec4fd2949198ad14803bcb32e3a1ab5462d757d3699ed --hash=sha256:7647fe13cf5d7c66f1d1c4bfdbb524a74d86f17db077d2be912387d2b6b45028 --hash=sha256:7885ab8b323f6bb4aa2c41ef853da6f9b192322b0e9dfd1e4d0674cbec03da12 --hash=sha256:9ae7c78c5f31b0b9c0eb01ecd6ac00210b1c5925bd53cd365fd4a61df187df2c --hash=sha256:ac77966039db3306a02a097de401e49467eb58e98eedc56f893b6e2bd78cd904 --hash=sha256:ad0808ab19c007e8beebadc31827e0d7560ac0e935f1100fb8cc93607400bb47 --hash=sha256:c15d82aa8e66af59e5e6e22599aae1e8f0b95c15b0fa18e6931713fde18ee548 --hash=sha256:c511a255982f6e7c01d2aaa13bad438d7002f887879493a3393294260264dad7 --hash=sha256:c862a6448d23100908a28c63e44b9f53897ade483dd493d06362b5bb61b468d9 --hash=sha256:c88397469b6f59ca2d339955b5631ce53ee4da9b349b0343af071ca4f5cb322b --hash=sha256:da9390b0648292a5e80c0c6b05e49d2485446a1ccc285f77603a159b44039c8d --hash=sha256:ddb40f293801214934699db00406b648c6964072ccdceb6e0eefb10692678ee6! Will try again.
An error occurred while installing pyfasta==0.5.2 --hash=sha256:ab08d75fa90253bc91933d10567d5d9cca2718f4796ef3bdc36b68df0e45b258! Will try again.
An error occurred while installing six==1.14.0 --hash=sha256:236bdbdce46e6e6a3d61a337c0f8b763ca1e8717c03b369e87a7ec7ce1319c0a --hash=sha256:8f3cd2e254d8f793e7f3d6d9df77b92252b52637291d0f0da013c76ea2724b6c! Will try again.
An error occurred while installing numpy==1.16.6 --hash=sha256:08bf4f66f190822f4642e036accde8da810b87fffc0b9409e7a00d9e54760099 --hash=sha256:1680c8d5086a88d293dfd1a10b6429a09140cacee878034fa2308472ec835db4 --hash=sha256:23cad5e5858dfb73c0e5bce03fe78e5e5908c22263156c58d4afdbb240683c6c --hash=sha256:345b1748e6b0d4773a518868c783b16fdc33a22683bdb863484cd29fe8d206e6 --hash=sha256:34e6bb44e3d9a663f903b8c297ede865b4dff039aa43cc9a0b249e02c27f1396 --hash=sha256:390f6e14a8d73591f086680464aa101a9be9187d0c633f48c98b429b31b712c2 --hash=sha256:3f423b06bf67cd1dbf72e13e9b53a9ca71972e5abf712ee6cb5d8cbb178fff02 --hash=sha256:55cae40d2024c56e7b79fb070106cb4289dcc6b55c62dba1d89a6944448c6a53 --hash=sha256:60c56922c9d759d664078fbef94132377ef1498ab27dd3d0cc7a21b346e68c06 --hash=sha256:6b1853364775edb85ceb0f7f8214d9e993d4d1d9bd3310eae80529ea14ba2ba6 --hash=sha256:77399828d96cca386bfba453025c34f22569909d90332b961d3d4341cdb46a84 --hash=sha256:7a5a1f49a643aa1ab3e0579da0a48b8a48ea4369eb63c5065459d0a37f430237 --hash=sha256:817eed5a6ec2fc9c1a0ee3fbf9a441c66b6766383580513ccbdf3121acc0b4fb --hash=sha256:97ddfa7688295d460ee48a4d76337e9fdd2506d9d1d0eee7f0348b42b430da4c --hash=sha256:9bb690692f3101583b0b99f3be362742e4f8ebe6c7934fa36cd8ca2b567a0bcc --hash=sha256:a1772dc227e3e415eeaa646d25690dc854bddc3d626e454c7c27acba060cb900 --hash=sha256:a1ffc9c770ccc2be9284310a3726c918b26ca19b34c0079e7a41aba950ab175f --hash=sha256:a4383edb1b8caa989c3541a37ef204916322c503b8eeacc7ee8f4ba24cac97b8 --hash=sha256:b9e334568ca1bf56598eddfac6db6a75bcf1c91aa90d598648f21e45207daeae --hash=sha256:c9fb4fcfcdcaccfe2c4e1f9e0133ed59df5df2aa3655f3d391887e892b0a784c --hash=sha256:d3c5377c6122de876e695937ef41ffee5d2831154c5e4856481b93406cdfeecb --hash=sha256:d759ca1b76ac6f6b6159fb74984126035feb1dee9f68b4b961889b6dc090f33a --hash=sha256:e5cf3fdf13401885e8eea8170624ec96225e2174eb0c611c6f26dd33b489e3ff! Will try again.
An error occurred while installing fastinterval==0.1.1 --hash=sha256:88a5b5800f382696c19474877cf8e988c461fd7b201fcf351f2b1ad56fb8e5cf! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:00
Installing initially failed dependencies...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:00
[pipenv.exceptions.InstallError]:   File "/home/george.hartzell/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "/home/george.hartzell/.local/lib/python2.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/home/george.hartzell/.local/lib/python2.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/home/george.hartzell/.local/lib/python2.7/site-packages/pipenv/core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "/home/george.hartzell/.local/lib/python2.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: []
[pipenv.exceptions.InstallError]: ['Traceback (most recent call last):', '  File "/home/george.hartzell/.local/share/virtualenvs/Primer3Wrapper-cACNdJ8_/bin/pip", line 5, in <module>', '    from pip._internal.cli.main import main', 'ImportError: No module named main']
ERROR: ERROR: Package installation failed...
```

If I do the same thing, but if I `spack activate py-pip ^python@2.7.16` instead of using Lmod to load py-pip and py-setuptools then it works.

Are modules supposed to work for this kind of thing?  I used to always just activate these two python libraries, but I had errors when I tried to explore `spack env` in an installation that had them activated...

**Comment by scheibelp** [comment]
> Are modules supposed to work for this kind of thing?

That may depend on the Python library: some inspect their own prefix, and some may inspect the prefix of Python itself. If the library expects those to be the same, it could get confused.

A couple questions:

* Does this occur with all modules you install with pipenv?
* Would you be able to check if a view fails in the same way? (you can install pip into the view and then use pipenv to add new packages)

> I used to always just activate these two python libraries, but I had errors when I tried to explore spack env in an installation that had them activated...

I think you are saying if you used `spack activate` in combination with Spack environments - yes we generally weren't sure how to support that sensibly so Environments typically reject packages with global activations.

**Comment by hartzell** [comment]
> I think you are saying if you used `spack activate` in combination with Spack environments - yes we generally weren't sure how to support that sensibly so Environments typically reject packages with global activations.

Yes, that's what I was saying and your reply makes sense.  Thanks!

**Comment by hartzell** [comment]
In the interim I've updated my spack installation and rebuilt things and I can't replicate this.  There's a good chance that I was having issues with things in ~/.local...

I'll close it and if I trip over it again I'll reopen.

Thanks for the followup.
