### ISSUE TITLE
Installation issue: glib

### ISSUE THREAD

**Issue by LDAmorim** [LLNL/spack#16214]
Hi all,

Sorry to bother you. I am trying a macOS-clang installation of `py-jupyter` and after having done some workarounds I find myself again a bit stuck on an issue that I don't understand how to fix.

Maybe the issue is similar to https://github.com/pybind/pybind11/issues/595 and https://lists.apple.com/archives/xcode-users/2016/Dec/msg00102.html, but I don't know how to try what they changed.

So I was wondering if you had any suggestions or fixes that I could try.

Thank you for all your help.

### Steps to reproduce the issue
```console
$ spack install glib
==> Warning: clang@11.0.3-apple cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> Warning: Missing a source id for gettext@0.20
==> gettext@0.20 : externally installed in /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gettext-0.20.1-hzoq5l22mfztxm43le6elarw3spsldqy
==> gettext@0.20 : already registered in DB
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gettext-0.20.1-hzoq5l22mfztxm43le6elarw3spsldqy
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/libffi-3.2.1-z5a645geugqdal6hdent6ncexra2ftci
==> libiconv@1.16 : externally installed in /usr
==> libiconv@1.16 : already registered in DB
[+] /usr
==> python@3.7.6 : externally installed in /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/python-3.7.6-jf3fylzmkcammhce6oleqazwo4qfb7zl
==> python@3.7.6 : already registered in DB
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/python-3.7.6-jf3fylzmkcammhce6oleqazwo4qfb7zl
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/pcre-8.43-rfttmpy3n4ichx3xsjksivk2w57kd53w
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/pkgconf-1.6.3-5eu2c6jojxkebrpsnkw4owpzvhkumz7d
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/zlib-1.2.11-rqiqrujgg5aemhk7eqjk3asbaukff37x
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/py-setuptools-41.4.0-licvt732h4opxowsk2j7jshgt2aqoqvy
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/ninja-1.10.0-ciqhnrsuipor4ep6otsxyp4e5bkomdpj
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/ncurses-6.2-cqw64pfhfhnycxlvncbgfbmnos2edzhv
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/meson-0.54.0-mu2x5z5fmrrn5fri4whpkvfkj6yz6a3t
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/readline-8.0-4jsebddi4vlbjvd6dzdoixuuwbuptbh3
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gdbm-1.18.1-6fk65ra2aoeep7cb7w45xdlppttr2vym
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/perl-5.30.1-eb7pj2tmpwgs4gnjmo3dfs366zn4gga4
==> 9982: Installing glib
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.3-apple for further details]
==> Fetching http://ftp.gnome.org/pub/gnome/sources/glib/2.64/glib-2.64.1.tar.xz
##################################################################################################################################################################### 100.0%##################################################################################################################################################################### 100.0%
==> Staging archive: /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf/glib-2.64.1.tar.xz
==> Created stage in /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf
==> Applied patch /Users/LDianaAmorim/Documents/opt/spack/var/spack/repos/builtin/packages/glib/meson-gettext.patch
==> 9982: glib: Building glib [Package]
==> 9982: glib: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j8' 'install'

1 error found in build log:
     1517    Could not strip file.
     1518    
     1519    Stdout:
     1520    
     1521    
     1522    Stderr:
  >> 1523    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: error: symbols referenced by indirect symbol table entries that 
             can't be stripped in: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf
             /lib/libglib-2.0.0.dylib
     1524    _NSSearchPathForDirectoriesInDomains
     1525    _UCCompareTextDefault
     1526    _UCCreateCollator
     1527    _UCGetCollationKey
     1528    __NSGetEnviron
     1529    ____chkstk_darwin

See build log for details:
  /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf/spack-build-out.txt

==> Error: Failed to install glib due to ChildError: ProcessError: Command exited with status 1:
    'ninja' '-j8' 'install'
1 error found in build log:
     1517    Could not strip file.
     1518    
     1519    Stdout:
     1520    
     1521    
     1522    Stderr:
  >> 1523    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: error: symbols referenced by indirect symbol table entries that 
             can't be stripped in: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf
             /lib/libglib-2.0.0.dylib
     1524    _NSSearchPathForDirectoriesInDomains
     1525    _UCCompareTextDefault
     1526    _UCCreateCollator
     1527    _UCGetCollationKey
     1528    __NSGetEnviron
     1529    ____chkstk_darwin

See build log for details:
  /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-glib-2.64.1-3qslb2e7otxja57e2p2b3r4q7fkdjpqf/spack-build-out.txt
Traceback (most recent call last):
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/build_environment.py", line 802, in child_process
    return_value = function()
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/multimethod.py", line 133, in __call__
    return spec_method(package_self, *args, **kwargs)
  File "/Users/LDianaAmorim/Documents/opt/spack/var/spack/repos/builtin/packages/glib/package.py", line 127, in install
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    'ninja' '-j8' 'install'
```

### Information on your system

* **Spack:** 0.14.2-702-def1d5e63
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake

My `~/.spack/darwin/packages.yaml` is:
```python
packages:
  cmake:
    buildable: False
    paths:
      cmake@3.17.0: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/cmake-3.17.0-6exaq5d4lp7sxf77nhk6kfkuajiy3qwm
  llvm:
    buildable: False
    paths:
      llvm@9.0.0: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/llvm-9.0.0-3qcfmwfcsffhy6t6abbz4v3ftoibvuzb
  python:
    buildable: False
    paths:
      python@3.7.6: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/python-3.7.6-jf3fylzmkcammhce6oleqazwo4qfb7zl
  gettext:
    buildable: False
    paths:
      gettext@0.20: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gettext-0.20.1-hzoq5l22mfztxm43le6elarw3spsldqy
  libiconv:
    buildable: False
    paths:
      libiconv: /usr
  all:
    providers:
      mpi: [mpich, openmpi]
```

And my `~/.spack/darwin/compilers.yaml` is:
```python
compilers:
- compiler:
    spec: clang@11.0.3-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {unset: []}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/gcc
      cxx: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/g++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-fdh4ye65koilywzhjbza74sdjmklmnea/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/4512142/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4512143/spack-build-out.txt)
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Apologies @scheibelp bouncing the issue back since I don't have access to a Mac and can't reproduce on `linux`:
```console
$ spack install glib %clang
[...]
==> 25941: glib: Successfully installed glib
  Fetch: 6.57s.  Build: 3m 7.27s.  Total: 3m 13.84s.
[+] /home/culpo/tmp/spack-issues/15966/store/linux-ubuntu18.04-broadwell/clang-9.0.0/glib-2.64.1-fhagwfx4jwbpq6kxfgoyi4mr3qxnzqus
```
I am working with:
* **Spack:** 0.14.2-895-9698907e7
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

The only unusual thing I spotted is that in the configuration there are "external" packages that are indeed installed by Spack. @LDAmorim is there any reason for that?

**Comment by LDAmorim** [comment]
Hi @alalazo , thanks for the reply and check.
I have a list of packages that I need to install. Some of them try to re-install packages that I already have, such as python. As a result when I try to use them, they become incompatible. So I try to find the "broader" installation of the package that is re-installed and use it as external.
Also, when I use gcc packages (MPI and openPMD-api) I need `cmake`, which spack can't install with gcc. So I use the clang spack installation of that package.
I don't think this is the best solution ... but I am still getting more familiar with spack.
So I might be doing many mistakes and not using the best workarounds.
My latest installation of packages was:
[log_macOS.txt](https://github.com/spack/spack/files/4559624/log_macOS.txt)

**Comment by scheibelp** [comment]
> Maybe the issue is similar to `pybind/pybind11#595`

It looks like we have some logic in the `glib` `package.py` which attempts to address the referenced issue:

```
    def setup_build_environment(self, env):
        if self.spec.satisfies('platform=darwin'):
            # https://github.com/pybind/pybind11/issues/595
            env.set('STRIP', 'strip -x')
```

Two possibilities that occur to me:

* The latest version of `glib` is ignoring the environment variable we set, and thereby running into the problem again. Could you try building a prior version of glib (`spack install glib@2.62.6`)?
* The symbol stripping options we use (`-x`) are too aggressive for this the latest version of `glib`. To test this, could you try using  `-X` (capital) or `-S` - those might succeed. From what I've read, `-x` (lower) should be perfectly safe.
