### ISSUE TITLE
pip fails with 'No module named pkg_resources' when run from env managed view

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#16250]
I've installed an environment that includes a view.  When I try to use `pip` from that view it fails with 

```
ImportError: No module named pkg_resources
```

### Steps to reproduce the issue

I have a large Spack installation that my CI system built last night.

I made a new clone of the repository and added the CI repo as an upstream (probably not important, but...).

I ran `spack compiler add` to add gcc@8.4.0 to my etc/spack/compilers.yaml file for this installation, then created an environment with `spack env create --without-view ape`.

I edited the `spack.yaml` to something like this (trimmed from real file):

```yaml
 This is a Spack Environment file.
 #
 # It describes a set of packages to be installed, along with
 # configuration settings.
 spack:
   include:
     - /local_scratch/hartzell/spack-env-experiments/my-packages.yaml
   # add package specs to the `specs` list
   specs:
     # many things deleted
     - tmux
     - tree
     - vim
     - wget
     - zsh
     - matrix:
         - ['^python@2.7.16', '^python@3.7.6']
         - [py-flake8, py-pip, py-virtualenv, py-setuptools]
   concretization: separately
   view:
     the_project:
       root: /tmp/moose
       select:
         - tmux
         - py-pip^python@2.7.16
         - py-setuptools^python@2.7.16
         - python@2.7.16
```

`my-packages.yaml` sets up the compiler and java provider and then just pins versions of things that I need:

```yaml
packages:
  all:
    compiler: [gcc@8.4.0, gcc@4.8.5]
    providers:
      java: [openjdk]
  aspell:
    version: [0.60.6.1]
  # ...
```

When I try to use the `pip` command from the view (e.g. to install `pipenv`), it fails.  I've tried simply putting the view's bin onto `PATH` as well as mucking about with `PYTHONPATH`.

```console
$ PATH=/tmp/moose/bin:$PATH pip install --user pipenv
Traceback (most recent call last):
  File "/tmp/moose/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
$ PYTHONPATH=/tmp/moose/lib/python2.7 PATH=/tmp/moose/bin:$PATH pip install --user pipenv
Traceback (most recent call last):
  File "/tmp/moose/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
$ PYTHONPATH=/tmp/moose/lib PATH=/tmp/moose/bin:$PATH pip install --user pipenv
Traceback (most recent call last):
  File "/tmp/moose/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
$
```

### Error Message

```console
$ spack --debug --stacktrace <command>
```

### Information on your system

$ spack debug report
* **Spack:** 0.14.1-701-b24134320
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake_avx512

### Additional information

- [ x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ x] I have searched the issues of this repo and believe this is not a duplicate
- [ N/A] I have run the failing commands in debug mode and reported the output

**Comment by hartzell** [comment]
I've tried this with and without activating the "ape" environment, with the same outcome.

**Comment by scheibelp** [comment]
Does `spack view status <the view location>` show `py-setuptools`?

Regarding

```
PYTHONPATH=/tmp/moose/lib/python2.7 PATH=/tmp/moose/bin:$PATH pip install --user pipenv
Traceback (most recent call last):
  File "/tmp/moose/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

I think you have to include `site-packages` if you want Python to find the py-setuptools resources this way (but if `py-setuptools` doesn't appear in the view as per the first question this won't matter either way).

Also as another sanity check, do `which pip`/`which python` return the Pythons you would expect (i.e. in `/tmp/moose/bin`)?

**Comment by adamjstewart** [comment]
@scheibelp is correct, the following should work:
```console
$ PYTHONPATH=/tmp/moose/lib/python2.7/site-packages PATH=/tmp/moose/bin:$PATH pip install --user pipenv
```
However, activating the environment _should_ set `PYTHONPATH` automatically.

**Comment by hartzell** [comment]
```
$ PYTHONPATH=/tmp/moose/lib/python2.7/site-packages PATH=/tmp/moose/bin:$PATH pip install --user pipenv
Traceback (most recent call last):
  File "/tmp/moose/bin/pip", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Urk.  Not sure what's up with all those other things (they are in the bigger env I built but did not include in the view part of `spack.yaml`.  Note the `==> Error: [/tmp/moose/] Package not linked: py-setuptools
` below:

```
$ spack view status /tmp/moose/
==> Error: [/tmp/moose/] Package not linked: boost
==> Error: [/tmp/moose/] Package not linked: bzip2
==> Error: [/tmp/moose/] Package not linked: curl
==> Error: [/tmp/moose/] Package not linked: expat
==> Error: [/tmp/moose/] Package not linked: gdbm
==> Error: [/tmp/moose/] Package not linked: gettext
==> Error: [/tmp/moose/] Package not linked: jemalloc
==> Error: [/tmp/moose/] Package not linked: libaio
==> Error: [/tmp/moose/] Package not linked: libbsd
==> Error: [/tmp/moose/] Package not linked: libedit
==> Error: [/tmp/moose/] Package not linked: libevent
==> Error: [/tmp/moose/] Package not linked: libffi
==> Error: [/tmp/moose/] Package not linked: libiconv
==> Error: [/tmp/moose/] Package not linked: libpng
==> Error: [/tmp/moose/] Package not linked: libsodium
==> Error: [/tmp/moose/] Package not linked: libxml2
==> Error: [/tmp/moose/] Package not linked: libzmq
==> Error: [/tmp/moose/] Package not linked: lz4
==> Error: [/tmp/moose/] Package not linked: mariadb
==> Error: [/tmp/moose/] Package not linked: msgpack-c
==> Error: [/tmp/moose/] Package not linked: ncurses
==> Error: [/tmp/moose/] Package not linked: openssl
==> Error: [/tmp/moose/] Package not linked: py-setuptools
==> Error: [/tmp/moose/] Package not linked: readline
==> Error: [/tmp/moose/] Package not linked: sqlite
==> Error: [/tmp/moose/] Package not linked: tar
==> Error: [/tmp/moose/] Package not linked: xz
==> Packages linked in [/tmp/moose/]:
-- linux-centos7-skylake_avx512 / gcc@8.4.0 ---------------------
    blat@35%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                            /tmp/moose/
    boost@1.72.0%gcc@8.4.0+atomic+chrono~clanglibcpp~container~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave  /tmp/moose/
    bzip2@1.0.8%gcc@8.4.0+shared                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    curl@7.56.0%gcc@8.4.0~darwinssl~gssapi~libssh~libssh2~nghttp2                                                                                                                                                                                                                                                                                                     /tmp/moose/
    expat@2.2.9%gcc@8.4.0+libbsd                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    gdbm@1.18.1%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                        /tmp/moose/
    gettext@0.20.1%gcc@8.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz                                                                                                                                                                                                                                                                                             /tmp/moose/
    ispcr@33%gcc@8.4.0 patches=53c1e068d9f156430bc500c0a5046f68dfa86b7437dbc9993c866bb85e01dce5                                                                                                                                                                                                                                                                       /tmp/moose/
    jemalloc@5.2.1%gcc@8.4.0~je~prof~stats                                                                                                                                                                                                                                                                                                                            /tmp/moose/
    kentutils@302.1%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                    /tmp/moose/
    libaio@0.3.110%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                     /tmp/moose/
    libbsd@0.10.0%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    libedit@3.1-20191231%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                               /tmp/moose/
    libevent@2.1.8%gcc@8.4.0+openssl                                                                                                                                                                                                                                                                                                                                  /tmp/moose/
    libffi@3.2.1%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                       /tmp/moose/
    libiconv@1.16%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    libpng@1.6.37%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    libsodium@1.0.18%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                   /tmp/moose/
    libxml2@2.9.9%gcc@8.4.0~python                                                                                                                                                                                                                                                                                                                                    /tmp/moose/
    libzmq@4.3.2%gcc@8.4.0+libsodium                                                                                                                                                                                                                                                                                                                                  /tmp/moose/
    lz4@1.9.2%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                          /tmp/moose/
    lzo@2.10%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                           /tmp/moose/
    mariadb@10.4.12%gcc@8.4.0 build_type=RelWithDebInfo +nonblocking                                                                                                                                                                                                                                                                                                  /tmp/moose/
    msgpack-c@3.0.1%gcc@8.4.0 build_type=RelWithDebInfo                                                                                                                                                                                                                                                                                                               /tmp/moose/
    ncurses@6.2%gcc@8.4.0~symlinks+termlib                                                                                                                                                                                                                                                                                                                            /tmp/moose/
    openssl@1.1.1f%gcc@8.4.0+systemcerts                                                                                                                                                                                                                                                                                                                              /tmp/moose/
    primer3@2.5.0%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                      /tmp/moose/
    py-pip@19.3%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                        /tmp/moose/
    py-setuptools@41.4.0%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                               /tmp/moose/
    python@2.7.16%gcc@8.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib                                                                                                                                                                                                          /tmp/moose/
    readline@8.0%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                       /tmp/moose/
    sqlite@3.30.1%gcc@8.4.0+column_metadata+fts~functions~rtree                                                                                                                                                                                                                                                                                                       /tmp/moose/
    tar@1.32%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                           /tmp/moose/
    unzip@6.0%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                          /tmp/moose/
    xz@5.2.5%gcc@8.4.0                                                                                                                                                                                                                                                                                                                                                           /tmp/moose/
    zlib@1.2.11%gcc@8.4.0+optimize+pic+shared                                                                                                                                                                                                                                                                                                                         /tmp/moose/
```

Same thing with `$ PATH=/tmp/moose/bin:$PATH spack view status /tmp/moose/`.

`which` doesn't do the right thing if you prefix it with PATH=..., but if I `export PATH=...` then I get

```
$ which pip
/tmp/moose/bin/pip
$ which python
/tmp/moose/bin/python
```

When I first set this up there were a bunch of weird errors, see #16248.  I kept beating on it and thought I'd won, but perhaps not...

**Comment by hartzell** [comment]
The various bits seem to be down there....

```
$ find /tmp/moose | grep setuptools
/tmp/moose/.spack/py-pip/repos/builtin/packages/py-setuptools
/tmp/moose/.spack/py-pip/repos/builtin/packages/py-setuptools/package.py
/tmp/moose/lib/python2.7/site-packages/pip/_internal/utils/setuptools_build.pyc
/tmp/moose/lib/python2.7/site-packages/pip/_internal/utils/setuptools_build.py
/tmp/moose/lib/python2.7/ensurepip/_bundled/setuptools-40.6.2-py2.py3-none-any.whl
/tmp/moose/lib/python2.7/distutils/tests/setuptools_extension.pyo
/tmp/moose/lib/python2.7/distutils/tests/setuptools_build_ext.pyo
/tmp/moose/lib/python2.7/distutils/tests/setuptools_build_ext.py
/tmp/moose/lib/python2.7/distutils/tests/setuptools_extension.py
/tmp/moose/lib/python2.7/distutils/tests/setuptools_extension.pyc
/tmp/moose/lib/python2.7/distutils/tests/setuptools_build_ext.pyc
```

**Comment by hartzell** [comment]
Well, I cloned a fresh spack installation, pointed it upstream and did this, which worked with a minimal spack.yaml:

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
    - python@2.7.16
    - py-setuptools^python@2.7.16
    - py-pip^python@2.7.16
  view:
    blort:
      root: /tmp/blort
      select:
        - python@2.7.16
        - py-setuptools^python@2.7.16
        - py-pip^python@2.7.16
```

```
share/spack/setup-env.sh
 spack env create --without-view ape
emacs var/spack/environments/ape/spack.yaml
spack compiler add --scope site $(spack location -i gcc@8.4.0)
spack -e ape install
PATH=/tmp/blort/bin:$PATH pip install --user pipenv
```

I'll start building it up to my real use case and try to see where it's going south.

Thanks for the eyes and thoughts.

**Comment by hartzell** [comment]
I realized that I had a `~/.local` dir hanging around from previous work.  Removed it and now:

```
PATH=/tmp/blort/bin:$PATH pip install --user pipenv
[...]
  Running setup.py install for setuptools ... done
  Running setup.py install for unknown ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2OynUw/configparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-huYV0v-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /compbio/home/george.hartzell/.local/lib/python2.7/site-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
    ************************************************************
    You are running Setuptools on Python 2, which is no longer
    supported and
    >>> SETUPTOOLS WILL STOP WORKING <<<
    in a subsequent release (no sooner than 2020-04-20).
    Please ensure you are installing
    Setuptools using pip 9.x or later or pin to `setuptools<45`
    in your environment.
    If you have done those things and are still encountering
    this message, please follow up at
    https://bit.ly/setuptools-py2-warning.
    ************************************************************
      sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
    WARNING: The wheel package is not available.
    ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2OynUw/configparser/setup.py", line 4, in <module>
        setuptools.setup()
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/compbio/home/george.hartzell/.local/lib/python2.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python2', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp53njCu', '--quiet', 'setuptools_scm[toml]>=3.4.1']' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2OynUw/configparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-huYV0v-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-2OynUw/configparser/
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$
```

Same for

```
$ PYTHONPATH=/tmp/blort/lib/python2.7/site-packages PATH=/tmp/blort/bin:$PATH pip install --user pipenv
```

This seems to work, but isn't very satisfying:

```
$ PYTHONPATH=/tmp/blort/lib/python2.7/site-packages PATH=/tmp/blort/bin:$PATH pip install --user --upgrade pip
$ PYTHONPATH=/tmp/blort/lib/python2.7/site-packages PATH=/tmp/blort/bin:$PATH pip install --user pipenv
[...]
  Running setup.py install for unknown ... done
  Running setup.py install for scandir ... done
  Running setup.py install for distlib ... done
  Running setup.py install for filelock ... done
Successfully installed appdirs-1.4.3 certifi-2020.4.5.1 contextlib2-0.6.0.post1 distlib-0.3.0 enum34-1.1.10 filelock-3.0.12 importlib-metadata-1.6.0 importlib-resources-1.4.0 pathlib2-2.3.5 pip-8.1.2 pipenv-2018.11.26 scandir-1.10.0 setuptools-0.9.8 singledispatch-3.4.0.3 typing-3.7.4.1 unknown unknown virtualenv-20.0.18 virtualenv-clone-0.5.4
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

particularly that bit about using an old version of pip, after I upgraded it just above.

**Comment by hartzell** [comment]
Ok.  :flushed: & :grimacing:

The main lesson here is probably not to work in `/tmp` on machines you didn't set up, you never know when some housekeeping script is going to remove your toys while you're playing with them.  

Secondary lesson is probably that dual-hat managers shouldn't code after a day of managing....

After pointing the view in `spack.yaml` at a safer `tmp/` dir, this works like a) I'd expect, b) you said it would.  Doesn't even look like I need `PYTHONPATH`.

``` sh
rm -rf /local_scratch/george.hartzell/tmp/blort/
rm -rf ~/.local
spack -e ape install
PATH=/local_scratch/george.hartzell/tmp/blort/bin:$PATH pip install --user pipenv
```

I'll give it a try when I'm fresher, but I wonder if I can I use `--root <dir>` or `--prefix <dir>` to install `pipenv` into a deployment/installation specific directory instead of a user's home?  I'm, perhaps irrationally, worried about different projects stepping on each other.
