### ISSUE TITLE
Installation issue: ncurses fails to build with XL compiler on ORNL ascent power system

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#16269]
### Steps to reproduce the issue

```console
$ spack install ncurses %xl@16.1
Note:  ncurses-6.1 builds, but ncurses-6.2 does not.
```
### Information on your system

* **Spack:** 0.11.2-6823-0c0f11c
* **Python:** 2.7.5
* **Platform:** linux-rhel7-power9le

no special package or module details.

### Additional information

[ncurses.console-out.txt](https://github.com/spack/spack/files/4525559/ncurses.console-out.txt)
[ncurses-spack-build-out.txt](https://github.com/spack/spack/files/4525560/ncurses-spack-build-out.txt)
[ncurses-spack-env.out.txt](https://github.com/spack/spack/files/4529246/ncurses-spack-env.out.txt)

No ncurses maintainers were listed

### General information
```[jgalarowicz@login1.ascent spack]$ spack install ncurses%xl@16.1
==> 117968: Installing pkgconf
==> Fetching http://distfiles.dereferenced.org/pkgconf/pkgconf-1.6.3.tar.xz
######################################################################## 100.0%
==> Staging archive: /tmp/jgalarowicz/spack-stage/spack-stage-pkgconf-1.6.3-awpimum6skyuvi2hbjaunqbyffeyjofm/pkgconf-1.6.3.tar.xz
==> Created stage in /tmp/jgalarowicz/spack-stage/spack-stage-pkgconf-1.6.3-awpimum6skyuvi2hbjaunqbyffeyjofm
==> No patches needed for pkgconf
==> 117968: pkgconf: Building pkgconf [AutotoolsPackage]
==> 117968: pkgconf: Executing phase: 'autoreconf'
==> 117968: pkgconf: Executing phase: 'configure'
==> 117968: pkgconf: Executing phase: 'build'
==> 117968: pkgconf: Executing phase: 'install'
==> 117968: pkgconf: Successfully installed pkgconf
  Fetch: 0.49s.  Build: 6.12s.  Total: 6.61s.
[+] /autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/pkgconf-1.6.3-awpimum6skyuvi2hbjaunqbyffeyjofm
==> 117968: Installing ncurses
==> Fetching https://ftpmirror.gnu.org/ncurses/ncurses-6.2.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/jgalarowicz/spack-stage/spack-stage-ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/ncurses-6.2.tar.gz
==> Created stage in /tmp/jgalarowicz/spack-stage/spack-stage-ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g
==> No patches needed for ncurses
==> 117968: ncurses: Building ncurses [AutotoolsPackage]
==> 117968: ncurses: Executing phase: 'autoreconf'
==> 117968: ncurses: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '../configure' '--prefix=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g' '--disable-stripping' '--with-shared' '--with-cxx-shared' '--enable-overwrite' '--without-ada' '--enable-pc-files' '--with-pkg-config-libdir=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/lib/pkgconfig' '--with-termlib' '--enable-termcap' '--enable-getcap' '--enable-tcap-names' '--disable-widec' '--without-manpages' '--without-tests'

2 errors found in build log:
     220    checking whether time.h and sys/time.h may both be included... yes
     221    checking for regcomp... no
     222    checking for regcomp in -lregex... no
     223    checking for regcomp in -lre... no
     224    checking for compile... no
     225    checking for compile in -lgen... no
  >> 226    configure: WARNING: cannot find regular expression library
     227    checking for regular-expression headers... no
     228    configure: WARNING: no regular expression header found
     229    checking for fcntl.h... yes
     230    checking for getopt.h... yes
     231    checking for limits.h... yes
     232    checking for locale.h... yes

     ...

     281    checking for strstr... no
     282    checking for sysconf... no
     283    checking for tcgetpgrp... no
     284    checking for times... no
     285    checking for tsearch... no
     286    checking for vsnprintf... no
  >> 287    configure: error: getopt is required for building programs

See build log for details:
  /tmp/jgalarowicz/spack-stage/spack-stage-ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/spack-build-out.txt

==> Error: Failed to install ncurses due to ChildError: ProcessError: Command exited with status 1:
    '../configure' '--prefix=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g' '--disable-stripping' '--with-shared' '--with-cxx-shared' '--enable-overwrite' '--without-ada' '--enable-pc-files' '--with-pkg-config-libdir=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/lib/pkgconfig' '--with-termlib' '--enable-termcap' '--enable-getcap' '--enable-tcap-names' '--disable-widec' '--without-manpages' '--without-tests'
2 errors found in build log:
     220    checking whether time.h and sys/time.h may both be included... yes
     221    checking for regcomp... no
     222    checking for regcomp in -lregex... no
     223    checking for regcomp in -lre... no
     224    checking for compile... no
     225    checking for compile in -lgen... no
  >> 226    configure: WARNING: cannot find regular expression library
     227    checking for regular-expression headers... no
     228    configure: WARNING: no regular expression header found
     229    checking for fcntl.h... yes
     230    checking for getopt.h... yes
     231    checking for limits.h... yes
     232    checking for locale.h... yes

     ...

     281    checking for strstr... no
     282    checking for sysconf... no
     283    checking for tcgetpgrp... no
     284    checking for times... no
     285    checking for tsearch... no
     286    checking for vsnprintf... no
  >> 287    configure: error: getopt is required for building programs

See build log for details:
  /tmp/jgalarowicz/spack-stage/spack-stage-ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/spack-build-out.txt
Traceback (most recent call last):
  File "/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/lib/spack/spack/build_environment.py", line 802, in child_process
    return_value = function()
  File "/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/var/spack/repos/builtin/packages/ncurses/package.py", line 84, in configure
  File "/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 1:
    '../configure' '--prefix=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g' '--disable-stripping' '--with-shared' '--with-cxx-shared' '--enable-overwrite' '--without-ada' '--enable-pc-files' '--with-pkg-config-libdir=/autofs/nccsopen-svm1_home/jgalarowicz/new.spack/spack/opt/spack/linux-rhel7-power9le/xl-16.1/ncurses-6.2-qa7hyuehtwfmio64azsq2zl6ndmfso6g/lib/pkgconfig' '--with-termlib' '--enable-termcap' '--enable-getcap' '--enable-tcap-names' '--disable-widec' '--without-manpages' '--without-tests'

[jgalarowicz@login1.ascent spack]$ spack --version
0.11.2-6824-a844467
```

**Comment by quellyn** [comment]
I can confirm this on a LANL Darwin Power9 node:

Spack arch:  linux-rhel7-power9le
Spack version:  0.14.2-706-5d008dc

ncurses 6.2 fails to build (same errors Jim encountered)
ncurses 6.1 builds fine

**Comment by white238** [comment]
Confirmed failure on ncurses@6.2 on rzmanta and rzansel with the following compiler spec:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: rhel7
    paths:
      cc:  /usr/tce/packages/xl/xl-2019.12.23/bin/xlc
      cxx: /usr/tce/packages/xl/xl-2019.12.23/bin/xlC
      f77: /usr/tce/packages/xl/xl-2019.12.23/bin/xlf2003
      fc:  /usr/tce/packages/xl/xl-2019.12.23/bin/xlf2003
    spec: xl@coral
    target: ppc64le
```
