### ISSUE TITLE
multi-user spack unable to record installation failure info due to missing file permissions

### ISSUE THREAD

**Issue by frankwillmore** [LLNL/spack#16283]
### Steps to reproduce the issue
Users in play on our multiuser installation include: willmore (myself), installationtest (dummy account for testing installation), and spack (service user that owns spack) 
These users are all in the 'software' group, and as such should have installation privileges, managed by Linux groups. Directories in the installation should be have 'software' as group owner with ```drwxrwsr-x``` privileges, files with ```-rw-rw-r--``` . 
 
Running 'spack install spack-dummy-package' (a testing package that actually builds) as installationtest user will generate the following error if it was not the last user to write  ```/lus/theta-fs0/software/spack/spack-dev/opt/spack/.spack-db/failures```.  

In this instance, a package failed to install because a proxy was not available for fetching the package, and spack attempted and was ***unable to record this failure*** due to permissions having not been set correctly on the failures directory: (see error message below)

```
spack@thetalogin5:~/alcf/tests> ll /lus/theta-fs0/software/spack/spack-dev/opt/spack/.spack-db/failures -d
drwxr-sr-x 2 spack software 4096 Apr 24 18:57 /lus/theta-fs0/software/spack/spack-dev/opt/spack/.spack-db/failures
```

```
console
$ spack <command1> <spec>
$ spack <command2> <spec>
...
```

### Error Message

```
==> 26740: Installing spack-dummy-package
==> Cloning git repository: https://github.com/frankwillmore/spack-dummy-package.git on branch master
fatal: unable to access 'https://github.com/frankwillmore/spack-dummy-package.git/': Failed to connect to proxy port 3128: No route to host
==> Fetching from [git] https://github.com/frankwillmore/spack-dummy-package.git on branch master failed.
==> Error: FetchError: All fetchers failed for spack-stage-spack-dummy-package-master-ol67tuxscyx5nafhuy3peoqiwdlr43j7

/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/package.py:1127, in do_fetch:
       1124                raise FetchError("Will not fetch %s" %
       1125                                 self.spec.format('{name}{@version}'), ck_msg)
       1126
  >>   1127        self.stage.create()
       1128        self.stage.fetch(mirror_only)
       1129        self._fetch_time = time.time() - start_time
       1130


==> Error: Failed to install spack-dummy-package due to ChildError: FetchError: All fetchers failed for spack-stage-spack-dummy-package-master-ol67tuxscyx5nafhuy3peoqiwdlr43j7
/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/package.py:1127, in do_fetch:
       1124                raise FetchError("Will not fetch %s" %
       1125                                 self.spec.format('{name}{@version}'), ck_msg)
       1126
  >>   1127        self.stage.create()
       1128        self.stage.fetch(mirror_only)
       1129        self._fetch_time = time.time() - start_time
       1130

Traceback (most recent call last):
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/installer.py", line 1046, in build_process
    pkg.do_patch()
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/package.py", line 1167, in do_patch
    self.do_stage()
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/package.py", line 1152, in do_stage
    self.do_fetch(mirror_only)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/package.py", line 1128, in do_fetch
    self.stage.fetch(mirror_only)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/stage.py", line 476, in fetch
    raise fs.FetchError(err_msg, None)
spack.fetch_strategy.FetchError: All fetchers failed for spack-stage-spack-dummy-package-master-ol67tuxscyx5nafhuy3peoqiwdlr43j7

==> Error: [Errno 13] Permission denied: '/lus/theta-fs0/software/spack/spack-dev/opt/spack/.spack-db/failures/spack-dummy-package-5ra5hmhuk5447crlpqph3dwn3oluqjkt'
```
### Information on your system

This is on ALCF theta, a Cray XC-40 running sles12/cnl6. 

***This is one of a number of similar file ownership issues that crop up when different users access the installation, as many files are either generated or re-written without group write permissons, e.g. :***

```
-rw-r--r-- 1 willmore software 168607 Apr 24 19:00 /lus/theta-fs0/software/spack/spack-dev/var/spack/misc-cache/patches/builtin-index.json
```

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by tldahlgren** [comment]
I don't have sticky bits on for my Spack database directories and my umask is `077` but my failure-related directory and files all allow `rwx` for owner _and group_ starting from `$SPACK_ROOT/opt/spack/.spack-db` on down.  All of my install directories are `drwxr-sr-x`.  So I'll keep digging.

**Comment by tldahlgren** [comment]
After some digging and chatting, Frank confirmed that the `packages.yaml` files for the three user accounts all have `permissions: all:` entries with at least `write: group` and `group: software` so we could be more explicit at least in terms of setting up the failure directories.

**Comment by frankwillmore** [comment]
I found an easy reproducer for a related permission issue: 
1. Delete $SPACK_ROOT/var/spack/misc-cache
2. spack spec any package
Result: misc-cache and everything under it is re-written without group permission, despite permission/ownership of parent directory:
 ```
 ll /lus/theta-fs0/software/spack/spack-dev/var/spack/ -d
drwxrwsr-x 10 spack software 4096 May 14 21:29 /lus/theta-fs0/software/spack/spack-dev/var/spack/
 ll /lus/theta-fs0/software/spack/spack-dev/var/spack/misc-cache/ -d
drwxr-sr-x 5 willmore software 4096 May 14 21:29 /lus/theta-fs0/software/spack/spack-dev/var/spack/misc-cache/
```

So subsequent attempts even to spec by the 'other' user fail:
```$ spack spec spack-dummy-package
Input spec
--------------------------------
spack-dummy-package

Concretized
--------------------------------
==> Error: Cannot access cache file: /lus/theta-fs0/software/spack/spack-dev/var/spack/misc-cache/providers/builtin-index.json
```
