### ISSUE TITLE
[Bug] spack --profile crashes

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1639]
```
$ spack --profile graph dyninst
o  dyninst
|\
| |\
| | |\
| o | |  libdwarf
|/ / /
o | |  libelf
 / /
o |  cmake
 /
o  boost
Traceback (most recent call last):
  File "/soft/spack-0.9.1/bin/spack", line 179, in <module>
    cProfile.run('main()', sort='tottime')
  File "/usr/lib64/python2.6/cProfile.py", line 36, in run
    result = prof.print_stats(sort)
  File "/usr/lib64/python2.6/cProfile.py", line 81, in print_stats
    pstats.Stats(self).strip_dirs().sort_stats(sort).print_stats()
  File "/usr/lib64/python2.6/pstats.py", line 232, in sort_stats
    sort_tuple = sort_tuple + sort_arg_defs[word][0]
KeyError: 'tottime'
```

**Comment by adamjstewart** [comment]
Might only crash for Python 2.6? Works for me with Python 2.7.
