### ISSUE TITLE
Leftover <prefix>/.spack/spec.yaml from failed installations

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#16478]
I'm trying to uninstall all of my installed packages. The process uninstalls a few hundred packages and then crashes with:
```
KeyError: 'libffi'
```

### Steps to reproduce the issue

```console
$ spack uninstall -ay
...
==> Error: Unable to read file: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/py-chardet-3.0.4-gqaa2mw2vk7fpx32f7fsmqh56i5daxp6/.spack/spec.yaml
Cause: 'libffi'
```

### Error Message

```console
$ spack -d uninstall -ay
...
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 760, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/uninstall.py", line 348, in uninstall
    uninstall_specs(args, specs)
  File "/Users/Adam/spack/lib/spack/spack/cmd/uninstall.py", line 323, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/Users/Adam/spack/lib/spack/spack/cmd/uninstall.py", line 225, in do_uninstall
    item.do_uninstall(force=force)
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 1769, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 1741, in uninstall_by_spec
    spack.hooks.pre_uninstall(spec)
  File "/Users/Adam/spack/lib/spack/spack/hooks/__init__.py", line 59, in __call__
    hook(*args, **kwargs)
  File "/Users/Adam/spack/lib/spack/spack/hooks/extensions.py", line 18, in pre_uninstall
    if pkg.is_activated(view):
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 1030, in is_activated
    exts = extensions_layout.extension_map(self.extendee_spec)
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 431, in extension_map
    return self._extension_map(spec).copy()
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 456, in _extension_map
    by_hash = self.layout.specs_by_hash()
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 361, in specs_by_hash
    for spec in self.all_specs():
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 343, in all_specs
    return [self.read_spec(s) for s in spec_files]
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 343, in <listcomp>
    return [self.read_spec(s) for s in spec_files]
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 230, in read_spec
    spec = spack.spec.Spec.from_yaml(f)
  File "/Users/Adam/spack/lib/spack/spack/spec.py", line 1939, in from_yaml
    return Spec.from_dict(data)
  File "/Users/Adam/spack/lib/spack/spack/spec.py", line 1926, in from_dict
    deps[name]._add_dependency(deps[dname], dtypes)
KeyError: 'libffi'
```

### Information on your system

* **Spack:** 0.14.2-979-7e5874c250
* **Python:** 3.7.6
* **Platform:** darwin-catalina-ivybridge

### Additional information

Could be related to #3690, but a completely different error message. Unfortunately, this isn't fixed by #16447. 

@aweits @alalazo may be interested in this.

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Here's the file it has trouble reading in the first error message: [spec.yaml](https://github.com/spack/spack/files/4583982/spec.txt)

**Comment by adamjstewart** [comment]
I uninstalled the failing package:
```console
$ spack uninstall -ayR py-chardet
```
Then confirmed that it was no longer installed:
```console
$ spack find py-chardet
==> No package matches the query: py-chardet
```
Then ran things again:
```console
$ spack uninstall -ay
...
==> Error: Unable to read file: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/py-chardet-3.0.4-gqaa2mw2vk7fpx32f7fsmqh56i5daxp6/.spack/spec.yaml
Cause: 'libffi'
```
It looks like this may be a leftover failed installation?
```console
$ la /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/py-chardet-3.0.4-gqaa2mw2vk7fpx32f7fsmqh56i5daxp6/
.spack
```
The only thing in that directory is a `spec.yaml` file. I'm going to try manually deleting it.

**Comment by adamjstewart** [comment]
Okay, manually deleting that file solved the issue. We should make this more robust. Maybe a try-except around the loop?

**Comment by adamjstewart** [comment]
Hmm, I just noticed I have many leftovers from failed installations that only contain a `.spack/spec.yaml` file. This might be a more serious problem than I thought:
```console
$ ls darwin-catalina-*/*
darwin-catalina-ivybridge/gcc-9.2.0:
openssl-1.1.1e-sj2ye4wzozgmjhehrsa2zyqyn5zm4mvq

darwin-catalina-x86_64/clang-11.0.0-apple:
bazel-0.19.2-unv4y6frcdxtpaurfxyynw7o75uw4p3i         tensorflow-1.12.1-ejsxx46htq2srzn46xf5jv5zoywuwizi    tensorflow-1.3.1-baz3bqxl272trhxvro6tvkbm6si2rm2u
dgl-0.4.2-mm4icj7y3p3eqv2rfxyxa6dsbusysd7f            tensorflow-1.12.2-f6226gmdyxdz4av3q5fscyjjvhaxp7yb    tensorflow-1.6.0-hjcjpuvqtlsd5di6qjsrdhu55lvrqq3p
py-scipy-1.4.1-vjugwgroqn2owcat7rxeqdpe6wnn5ft5       tensorflow-1.12.3-yeuz72mhuyot6d2t2f66z6wns5ekruha    tensorflow-1.7.1-6zqnngm72r2qgdxulgutdjo3jjwq3mwj
sentencepiece-0.1.85-diyhnhjtlkwbhtytah4wkkx4272l6nfr tensorflow-1.13.2-23ukxvltwzkmbnlqywgthsfc3sbgy522    tensorflow-1.8.0-4kw4igjl2knm4kaiob2jfft3mbwo37dh
tensorflow-1.1.0-ms7ppa5wjgxo5fuf73agr6ndr2rwtgod     tensorflow-1.14.0-h7rwso2qvedjvrg57tploe3j55tfrpgx    tensorflow-1.9.0-2vh4fsgccqdeku67kfiylkic4prxd4tb
tensorflow-1.10.0-4b5ll6kvgcnfx7mjrlx3yvsc4rrrn2ey    tensorflow-1.15.0-vmib4ootcxgfh66xv5qk6tlmbhhef7vv    tensorflow-2.0.0-5ygytffyo4jdkk6x5d7yuvwdlma3rcn7
tensorflow-1.10.1-gypelnhvqz3cwddwfk4teju3ae22p3cy    tensorflow-1.15.0-wxdi5m2eegzi4zlcii376exacbbojnav    tensorflow-2.0.0-hwt7t5y55y5iklrpydvvhea4yut2eitk
tensorflow-1.11.0-arj3umt2gtotkljrqwy4fm663fu4cok5    tensorflow-1.2.1-fxfkvcjshnjgyrlgnsurwpmpyipbmg52     tensorflow-2.1.0-rc0-sv6p675ahm2ggaaywtomoeifieavropq
tensorflow-1.11.0-nbgffuc7s6isydrp4vp67nnmx7noc3cb    tensorflow-1.3.0-m5a4ssnmrhcnmpjoauorld7fbb5jfq4y     tensorflow-2.1.0-rc0-tus2x2c666hc3drfrpkt5ofv325jo75b
tensorflow-1.12.0-iffgipnkxib4tzurpenlicrt6fag2s5p    tensorflow-1.3.1-6kqmonsqf7pzppds4tzpiqlen5fxleyl

darwin-catalina-x86_64/clang-11.0.3-apple:
gdal-3.0.4-cyeljcerulxuso536lrrv6eq3vdvsioi       py-numpy-1.18.2-hbbasosmeunxholf6zlyr2oxurj7fw2x  py-torch-1.5.0-c4nh5of475ait4wqcgo2qweh3hh7s6ur
gmp-6.1.2-bfwgwkc4tat3gjfxvj4pxfjqh354t2ue        py-srsly-2.0.1-nwnkpoz7ize2fixqvxqbeyszzr5bhecd   py-torch-1.5.0-ppmaznhqo3gizojkr34upzaf36qzs6bd
py-grpcio-1.25.0-26ah7vljpxwwohlkvlqit5zlmq75dofb py-torch-1.4.0-mvz4t3orm7ry6ewcko7ezqvwhvsnl6gc   py-tqdm-4.999-6m4uyscv2cp73nw55t4hxz433vmrgytd
py-grpcio-1.25.0-jlt4txlc4ftgr4kxxwm3e2wfl4ofijec py-torch-1.4.1-dmrkbyo5vo64dbevydvjd36a27dpjyhd
py-mock-1.0.1-oid4jnjgzqncre2nz6jtg5j2wyu4paz3    py-torch-1.4.1-oddhthm2ce2bw2fk2pkkktkznk7dv2n6
```

**Comment by scheibelp** [comment]
Do you know if you ever prematurely terminated an uninstall (e.g. with CTRL-C)?

Also based on the presence of the `spec.yaml` file, I'm thinking `spack reindex` would not work (which would be my first thought on something to try when Spack complains about inconsistent install state).

I'll have time to investigate this tomorrow (5/6)

**Comment by adamjstewart** [comment]
> Do you know if you ever prematurely terminated an uninstall (e.g. with CTRL-C)?

Definitely, hundreds of times. I might have even hit Ctrl-C multiple times in rapid succession.

**Comment by scheibelp** [comment]
To be clear, that *should* be OK, I'm just trying to brainstorm how this inconsistent state would be reached.

**Comment by scheibelp** [comment]
I still haven't cracked what's going on here, and I'll have to keep working on it tomorrow, but a couple things in the meantime:

* While I agree with https://github.com/spack/spack/issues/16478#issuecomment-624347257 that this error shouldn't prevent the package from being installed, the error itself (https://github.com/spack/spack/issues/16478#issue-612931449) is unexpected and appears to be due to an inconsistent `spec.yaml` file - I'd like to figure out how to track down the specific spec.yaml file that is causing the error and examine it more: I can write something to get that tomorrow unless I figure it out before then, or if there's only one spec.yaml in your install prefix which contains a mention of `libffi`, could you attach that here?
* The tensorflow package doesn't exist in Spack, I'm wondering if that might be related (although I have no idea for example if it's related to the `spec.yaml` that doesn't ingest).

**Comment by adamjstewart** [comment]
> or if there's only one spec.yaml in your install prefix which contains a mention of libffi, could you attach that here?

See my second comment above

> The tensorflow package doesn't exist in Spack, I'm wondering if that might be related (although I have no idea for example if it's related to the spec.yaml that doesn't ingest).

That could be related, these must have been created before `tensorflow` was renamed to `py-tensorflow`.

**Comment by scheibelp** [comment]
Thanks!

That spec.yaml is definitely malformed (i.e. should not have been generated by `Spec.to_yaml`). As for how it got into that state could be considered a secondary matter: `spack uninstall` should be robust enough to remove the prefix even if the Spec is malformed, so I'll add something tomorrow to allow for that.

**Comment by aweits** [comment]
I can get this behavior with this (assumes that revocap-coupler fails fetch for you):
```
spack install --log-format=junit --log-file=/tmp/fooooooo revocap-coupler
```
A quick snippet of how to prevent (not sure this is a valid fix, but a diff is sometimes worth a 1000 words):
```
diff --git a/lib/spack/spack/report.py b/lib/spack/spack/report.py
index e500f9fc0573..83e5dc34872f 100644
--- a/lib/spack/spack/report.py
+++ b/lib/spack/spack/report.py
@@ -134,6 +134,7 @@ def wrapper(installer, task, *args, **kwargs):
 
                 start_time = time.time()
                 value = None
+                e_return = None
                 try:
 
                     value = _install_task(installer, task, *args, **kwargs)
@@ -152,6 +153,7 @@ def wrapper(installer, task, *args, **kwargs):
                     package['stdout'] = fetch_package_log(pkg)
                     package['stdout'] += package['message']
                     package['exception'] = e.traceback
+                    e_return = e
 
                 except (Exception, BaseException) as e:
                     # Everything else is an error (the installation
@@ -160,6 +162,7 @@ def wrapper(installer, task, *args, **kwargs):
                     package['stdout'] = fetch_package_log(pkg)
                     package['message'] = str(e) or 'Unknown error'
                     package['exception'] = traceback.format_exc()
+                    e_return = e
 
                 finally:
                     package['elapsed_time'] = time.time() - start_time
@@ -180,6 +183,8 @@ def wrapper(installer, task, *args, **kwargs):
                     except StopIteration:
                         pass
 
+                if (e_return):
+                    raise e_return
                 return value
 
             return wrapper
```

**Comment by srya-b** [comment]
@scheibelp this is @adamjstewart reopening this issue on behalf of my roommate @sbaks0820.

I was trying to install a package when my laptop battery died during the installation. Now, whenever I try to install the same package, I see the following error:
```console
$ spack install python
[+] /home/surya/spack/opt/spack/linux-debian9-skylake/gcc-6.3.0/libiconv-1.16-ingery6hl4kr4n5smdyav5twxtkchdnb
==> Error: Unable to read file: /home/surya/spack/opt/spack/linux-debian9-skylake/gcc-6.3.0/libbsd-0.10.0-xbipc2oaeabagv4cgdlmo6y4sk2k5jck/.spack/spec.yaml
```
```console
$ spack -d install python
==> [2020-09-02-11:03:54.286524] Imported install from built-in commands
==> [2020-09-02-11:03:54.287505] Reading config file /home/surya/spack/etc/spack/defaults/config.yaml
==> [2020-09-02-11:03:54.302893] Imported install from built-in commands
==> [2020-09-02-11:03:54.304887] Reading config file /home/surya/spack/etc/spack/defaults/repos.yaml
==> [2020-09-02-11:03:54.362204] Reading config file /home/surya/spack/etc/spack/defaults/packages.yaml
==> [2020-09-02-11:03:54.435141] Reading config file /home/surya/.spack/linux/compilers.yaml
==> [2020-09-02-11:03:54.766547] Ordered hashes [libffi]: libffi/22/26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0
==> [2020-09-02-11:03:54.768019] DATABASE LOCK TIMEOUT: 3s
==> [2020-09-02-11:03:54.768066] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-09-02-11:03:54.822533] Initializing the build queue for python
==> [2020-09-02-11:03:54.973121] Acquiring a write lock on libiconv with timeout 1e-09
==> [2020-09-02-11:03:54.975025] Creating stage lock spack-stage-libiconv-1.16-ingery6hl4kr4n5smdyav5twxtkchdnb
==> [2020-09-02-11:03:54.980105] Flagging libiconv as installed
==> [2020-09-02-11:03:54.980153] Removing libiconv from diffutils's uninstalled dependencies.
==> [2020-09-02-11:03:54.980191] diffutils: Removed libiconv from uninstalled deps list: set()
==> [2020-09-02-11:03:54.980692] Removing libiconv from tar's uninstalled dependencies.
==> [2020-09-02-11:03:54.980739] tar: Removed libiconv from uninstalled deps list: set()
==> [2020-09-02-11:03:54.981277] Removing libiconv from libxml2's uninstalled dependencies.
==> [2020-09-02-11:03:54.981326] libxml2: Removed libiconv from uninstalled deps list: {'zlib', 'pkgconf', 'xz'}
==> [2020-09-02-11:03:54.981827] Removing libiconv from gettext's uninstalled dependencies.
==> [2020-09-02-11:03:54.981874] gettext: Removed libiconv from uninstalled deps list: {'tar', 'libxml2', 'xz', 'bzip2', 'ncurses'}
==> [2020-09-02-11:03:54.982445] Downgrading to a read lock on libiconv with timeout 1e-09
==> [2020-09-02-11:03:54.982530] Flagging libiconv as installed
==> [2020-09-02-11:03:54.982561] Removing libiconv from diffutils's uninstalled dependencies.
==> [2020-09-02-11:03:54.983053] Removing libiconv from tar's uninstalled dependencies.
==> [2020-09-02-11:03:54.983544] Removing libiconv from libxml2's uninstalled dependencies.
==> [2020-09-02-11:03:54.984039] Removing libiconv from gettext's uninstalled dependencies.
[+] /home/surya/spack/opt/spack/linux-debian9-skylake/gcc-6.3.0/libiconv-1.16-ingery6hl4kr4n5smdyav5twxtkchdnb
==> [2020-09-02-11:03:54.985163] Acquiring a write lock on libbsd with timeout 1e-09
==> [2020-09-02-11:03:54.986238] Creating stage lock spack-stage-libbsd-0.10.0-xbipc2oaeabagv4cgdlmo6y4sk2k5jck
Traceback (most recent call last):
  File "./spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/home/surya/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/surya/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/surya/spack/lib/spack/spack/cmd/install.py", line 397, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/home/surya/spack/lib/spack/spack/cmd/install.py", line 243, in install_spec
    spec.package.do_install(**kwargs)
  File "/home/surya/spack/lib/spack/spack/package.py", line 1575, in do_install
    builder.install(**kwargs)
  File "/home/surya/spack/lib/spack/spack/installer.py", line 1502, in install
    restage)
  File "/home/surya/spack/lib/spack/spack/installer.py", line 782, in _prepare_for_install
    if not partial and self.layout.check_installed(task.pkg.spec):
  File "/home/surya/spack/lib/spack/spack/directory_layout.py", line 318, in check_installed
    installed_spec = self.read_spec(spec_file_path)
  File "/home/surya/spack/lib/spack/spack/directory_layout.py", line 230, in read_spec
    spec = spack.spec.Spec.from_yaml(f)
  File "/home/surya/spack/lib/spack/spack/spec.py", line 1958, in from_yaml
    return Spec.from_dict(data)
  File "/home/surya/spack/lib/spack/spack/spec.py", line 1926, in from_dict
    nodes = data['spec']
TypeError: 'NoneType' object is not subscriptable
```
The file in question exists but is empty. We should handle this automatically.

This is on the latest develop branch:
* **Spack:** 0.15.4-809-ae44a8ff6
* **Python:** 3.5.3
* **Platform:** linux-debian9-skylake

**Comment by scheibelp** [comment]
Can you remove the spec with `spack uninstall -f python` and then reinstall it?

**Comment by adamjstewart** [comment]
@scheibelp I'm actually having trouble reproducing this on my own machine. Do I need something other than a `spec.yaml` file to reproduce this?

**Comment by alalazo** [comment]
@adamjstewart I could reproduce with a fresh clone and `zlib`:
```console
$ spack install zlib
[ ... ]
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu
$ rm /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu/.spack/spec.yaml 
$ touch /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu/.spack/spec.yaml
$ spack install zlib
==> Error: Unable to read file: /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu/.spack/spec.yaml
Cause: 'NoneType' object is not subscriptable
```

**Comment by RemiLacroix-IDRIS** [comment]
Hi there,

I am not completely sure I understand where those leftover `spec.yaml` come from.

I just noticed that we have some (edit: 22) in our Spack install dir and I am not sure what I should do about them (manually remove them?).

Rémi

**Comment by adamjstewart** [comment]
Is this still an issue? I haven't encountered this since 2020.

**Comment by RemiLacroix-IDRIS** [comment]
I am still seeing a few of those but we use a pretty old version of Spack so it might not be true for newer versions.
