### ISSUE TITLE
Installation issue: tau

### ISSUE THREAD

**Issue by tejendrapsingh** [LLNL/spack#16780]
### Steps to reproduce the issue

```console
$ spack install tau
...
```

### Information on your system

* **Spack:** 0.14.2-1209-bc145b2b3
* **Python:** 3.6.8
* **Platform:** linux-centos8-skylake

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4672689/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4672688/spack-build-env.txt)

@eugeneswalker @khuck  @sameershende @wspear

### General information

- [X ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ X] I have uploaded the build log and environment files
- [ X] I have searched the issues of this repo and believe this is not a duplicate

Hi!
I am getting an error while building the tau library. Basically, building of libunwind library failed. 
I am posting the terminal output below.

```
**`==> Error: ProcessError: Command exited with status 2:**
    **'make' '-j8'**

1 error found in build log:
     838    libtool: link: ar cru .libs/libunwind-coredump.a  coredump/_UCD_acc
            essors.o coredump/_UCD_create.o coredump/_UCD_destroy.o coredump/_U
            CD_access_mem.o coredump/_UCD_elf_map_image.o coredump/_UCD_find_pr
            oc_info.o coredump/_UCD_get_proc_name.o coredump/_UPT_elf.o coredum
            p/_UPT_access_fpreg.o coredump/_UPT_get_dyn_info_list_addr.o coredu
            mp/_UPT_put_unwind_info.o coredump/_UPT_resume.o coredump/_UCD_acce
            ss_reg_linux.o
     839    libtool: link: ranlib .libs/libunwind-coredump.a
     840    libtool: link: /home/tejendrapsingh/spack/lib/spack/env/gcc/gcc -sh
            ared  -fPIC -DPIC  .libs/os-linux.o mi/.libs/init.o mi/.libs/flush_
            cache.o mi/.libs/mempool.o mi/.libs/strerror.o x86_64/.libs/is_fpre
            g.o x86_64/.libs/regname.o x86_64/.libs/Los-linux.o mi/.libs/backtr
            ace.o mi/.libs/dyn-cancel.o mi/.libs/dyn-info-list.o mi/.libs/dyn-r
            egister.o mi/.libs/Ldyn-extract.o mi/.libs/Lfind_dynamic_proc_info.
            o mi/.libs/Lget_accessors.o mi/.libs/Lget_proc_info_by_ip.o mi/.lib
            s/Lget_proc_name.o mi/.libs/Lput_dynamic_unwind_info.o mi/.libs/Lde
            stroy_addr_space.o mi/.libs/Lget_reg.o mi/.libs/Lset_reg.o mi/.libs
            /Lget_fpreg.o mi/.libs/Lset_fpreg.o mi/.libs/Lset_caching_policy.o 
            mi/.libs/Lset_cache_size.o x86_64/.libs/setcontext.o x86_64/.libs/L
            apply_reg_state.o x86_64/.libs/Lreg_states_iterate.o x86_64/.libs/L
            create_addr_space.o x86_64/.libs/Lget_save_loc.o x86_64/.libs/Lglob
            al.o x86_64/.libs/Linit.o x86_64/.libs/Linit_local.o x86_64/.libs/L
            init_remote.o x86_64/.libs/Lget_proc_info.o x86_64/.libs/Lregs.o x8
            6_64/.libs/Lresume.o x86_64/.libs/Lstash_frame.o x86_64/.libs/Lstep
            .o x86_64/.libs/Ltrace.o x86_64/.libs/getcontext.o  -Wl,--whole-arc
            hive ./.libs/libunwind-dwarf-local.a ./.libs/libunwind-elf64.a -Wl,
            --no-whole-archive  -lc -lgcc_s  -g -O2 -nostartfiles -nostdlib   -
            Wl,-soname -Wl,libunwind.so.8 -o .libs/libunwind.so.8.0.1
     841    libtool: link: ( cd ".libs" && rm -f "libunwind-coredump.la" && ln 
            -s "../libunwind-coredump.la" "libunwind-coredump.la" )
     842    x86_64/.libs/Linit.o:(.bss+0x0): multiple definition of `_U_dyn_inf
            o_list'
     843    mi/.libs/dyn-info-list.o:(.bss+0x0): first defined here
**>> 844    collect2: error: ld returned 1 exit status **
     845    make[2]: *** [Makefile:3252: libunwind.la] Error 1
     846    make[2]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     847    make[1]: *** [Makefile:2163: all] Error 2
     848    make[1]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     849    make: *** [Makefile:603: all-recursive] Error 1

See build log for details:
  /tmp/tejendrapsingh/spack-stage/spack-stage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-build-out.txt

**==> Error: Failed to install libunwind due to ChildError: ProcessError: Command exited with status 2:**
    **'make' '-j8'**
1 error found in build log:
     838    libtool: link: ar cru .libs/libunwind-coredump.a  coredump/_UCD_acc
            essors.o coredump/_UCD_create.o coredump/_UCD_destroy.o coredump/_U
            CD_access_mem.o coredump/_UCD_elf_map_image.o coredump/_UCD_find_pr
            oc_info.o coredump/_UCD_get_proc_name.o coredump/_UPT_elf.o coredum
            p/_UPT_access_fpreg.o coredump/_UPT_get_dyn_info_list_addr.o coredu
            mp/_UPT_put_unwind_info.o coredump/_UPT_resume.o coredump/_UCD_acce
            ss_reg_linux.o
     839    libtool: link: ranlib .libs/libunwind-coredump.a
     840    libtool: link: /home/tejendrapsingh/spack/lib/spack/env/gcc/gcc -sh
            ared  -fPIC -DPIC  .libs/os-linux.o mi/.libs/init.o mi/.libs/flush_
            cache.o mi/.libs/mempool.o mi/.libs/strerror.o x86_64/.libs/is_fpre
            g.o x86_64/.libs/regname.o x86_64/.libs/Los-linux.o mi/.libs/backtr
            ace.o mi/.libs/dyn-cancel.o mi/.libs/dyn-info-list.o mi/.libs/dyn-r
            egister.o mi/.libs/Ldyn-extract.o mi/.libs/Lfind_dynamic_proc_info.
            o mi/.libs/Lget_accessors.o mi/.libs/Lget_proc_info_by_ip.o mi/.lib
            s/Lget_proc_name.o mi/.libs/Lput_dynamic_unwind_info.o mi/.libs/Lde
            stroy_addr_space.o mi/.libs/Lget_reg.o mi/.libs/Lset_reg.o mi/.libs
            /Lget_fpreg.o mi/.libs/Lset_fpreg.o mi/.libs/Lset_caching_policy.o 
            mi/.libs/Lset_cache_size.o x86_64/.libs/setcontext.o x86_64/.libs/L
            apply_reg_state.o x86_64/.libs/Lreg_states_iterate.o x86_64/.libs/L
            create_addr_space.o x86_64/.libs/Lget_save_loc.o x86_64/.libs/Lglob
            al.o x86_64/.libs/Linit.o x86_64/.libs/Linit_local.o x86_64/.libs/L
            init_remote.o x86_64/.libs/Lget_proc_info.o x86_64/.libs/Lregs.o x8
            6_64/.libs/Lresume.o x86_64/.libs/Lstash_frame.o x86_64/.libs/Lstep
            .o x86_64/.libs/Ltrace.o x86_64/.libs/getcontext.o  -Wl,--whole-arc
            hive ./.libs/libunwind-dwarf-local.a ./.libs/libunwind-elf64.a -Wl,
            --no-whole-archive  -lc -lgcc_s  -g -O2 -nostartfiles -nostdlib   -
            Wl,-soname -Wl,libunwind.so.8 -o .libs/libunwind.so.8.0.1
     841    libtool: link: ( cd ".libs" && rm -f "libunwind-coredump.la" && ln 
            -s "../libunwind-coredump.la" "libunwind-coredump.la" )
     842    x86_64/.libs/Linit.o:(.bss+0x0): multiple definition of `_U_dyn_inf
            o_list'
     843    mi/.libs/dyn-info-list.o:(.bss+0x0): first defined here
**>> 844    collect2: error: ld returned 1 exit status**
     845    make[2]: *** [Makefile:3252: libunwind.la] Error 1
     846    make[2]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     847    make[1]: *** [Makefile:2163: all] Error 2
     848    make[1]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     849    make: *** [Makefile:603: all-recursive] Error 1

See build log for details:
  /tmp/tejendrapsingh/spack-stage/spack-stage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-build-out.txt
Traceback (most recent call last):
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/home/tejendrapsingh/spack/lib/spack/spack/installer.py", line 1123, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/tejendrapsingh/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_systems/autotools.py", line 308, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/tejendrapsingh/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8'

**==> Warning: Skipping build of tau since libunwind failed**
`
`
```

**Comment by michaelkuhn** [comment]
This should be fixed by #16782, please give it a try.

**Comment by tejendrapsingh** [comment]
Thanks.
So, I need to remove this line `flag_handler = AutotoolsPackage.build_system_flags` and add these lines
```
+    def flag_handler(self, name, flags):
+        wrapper_flags = None
+
+        if name == 'cflags':
+            # https://github.com/libunwind/libunwind/pull/166
+            if self.spec.satisfies('@:1.4 %gcc@10:'):
+                wrapper_flags = ['-fcommon']
+
+        return (wrapper_flags, None, flags)
```

to the ` var/spack/repos/builtin/packages/libunwind/package.py file`, right?

**Comment by tejendrapsingh** [comment]
Thanks.
It worked!
Brilliant!
Closing this.
