### ISSUE TITLE
Installation issue: bzip, libtool with $padding in install tree

### ISSUE THREAD

**Issue by nithintsk** [LLNL/spack#16795]
Based off https://github.com/spack/spack/pull/16338 - OS support for $padding, I edited the file `$SPACK_ROOT/etc/spack/defaults/config.yaml` and changed the install tree to have $padding. 

```
  install_tree: $padding
```
The reason was that I wanted to have a very long install path to create binary packages. My package is dependent on bzip2 and libtool, but their installation is failing.

### Steps to reproduce the issue
In config.yaml, change install tree to `install_tree: $padding`

```console
-bash-4.2$ spack install --no-cache libtool
==> Warning: gcc@4.8.5 cannot build optimized binaries for "skylake_avx512". Using best target possible: "haswell"
==> 2726: Installing libsigsegv
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libsigsegv/libsigsegv-2.12.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libsigsegv/libsigsegv-2.12.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libsigsegv/libsigsegv-2.12.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libsigsegv/libsigsegv-2.12.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libsigsegv/libsigsegv-2.12.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libsigsegv/libsigsegv-2.12.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libsigsegv/libsigsegv-2.12.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libsigsegv/libsigsegv-2.12.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz failed.
==> Fetching https://ftpmirror.gnu.org/libsigsegv/libsigsegv-2.12.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/nithinsk/spack-stage/spack-stage-libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3/libsigsegv-2.12.tar.gz
==> Created stage in /tmp/nithinsk/spack-stage/spack-stage-libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3
==> No patches needed for libsigsegv
==> 2726: libsigsegv: Building libsigsegv [AutotoolsPackage]
==> 2726: libsigsegv: Executing phase: 'autoreconf'
==> 2726: libsigsegv: Executing phase: 'configure'
==> 2726: libsigsegv: Executing phase: 'build'
==> 2726: libsigsegv: Executing phase: 'install'
==> 2726: libsigsegv: Successfully installed libsigsegv
  Fetch: 2.04s.  Build: 12.72s.  Total: 14.76s.
[+] /storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/linux-centos7-haswell/gcc-4.8.5/libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3
==> 2726: Installing m4
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz failed.
==> Fetching https://ftpmirror.gnu.org/m4/m4-1.4.18.tar.gz
######################################################################## 100.0%
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616 was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616 failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616 was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/m4/m4-1.4.18-glibc-change-work-around.patch-fc9b616 failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 failed.
==> Fetching https://src.fedoraproject.org/rpms/m4/raw/5d147168d4b93f38a4833f5dd1d650ad88af5a8a/f/m4-1.4.18-glibc-change-work-around.patch
######################################################################## 100.0%
==> Staging archive: /tmp/nithinsk/spack-stage/spack-stage-m4-1.4.18-7x2wh2thcpfjgeqxf4vhrqw3suxldfab/m4-1.4.18.tar.gz
==> Created stage in /tmp/nithinsk/spack-stage/spack-stage-m4-1.4.18-7x2wh2thcpfjgeqxf4vhrqw3suxldfab
==> Applied patch /storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/var/spack/repos/builtin/packages/m4/gnulib-pgi.patch
==> Applied patch https://src.fedoraproject.org/rpms/m4/raw/5d147168d4b93f38a4833f5dd1d650ad88af5a8a/f/m4-1.4.18-glibc-change-work-around.patch
==> 2726: m4: Building m4 [AutotoolsPackage]
==> 2726: m4: Executing phase: 'autoreconf'
==> 2726: m4: Executing phase: 'configure'
==> 2726: m4: Executing phase: 'build'
==> 2726: m4: Executing phase: 'install'
==> 2726: m4: Successfully installed m4
  Fetch: 2.44s.  Build: 1m 0.30s.  Total: 1m 2.74s.
[+] /storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/linux-centos7-haswell/gcc-4.8.5/m4-1.4.18-7x2wh2thcpfjgeqxf4vhrqw3suxldfab
==> 2726: Installing libtool
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libtool/libtool-2.4.6.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libtool/libtool-2.4.6.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libtool/libtool-2.4.6.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/libtool/libtool-2.4.6.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2x/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libtool/libtool-2.4.6.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libtool/libtool-2.4.6.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libtool/libtool-2.4.6.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/libtool/libtool-2.4.6.tar.gz failed.
==> Fetching http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz
    URL http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz was not found!
==> Fetching from http://mvapich.cse.ohio-state.edu:8081/download/mvapich/spack-mirror/mvapich2-gdr/_source-cache/archive/e3/e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3.tar.gz failed.
==> Fetching https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/nithinsk/spack-stage/spack-stage-libtool-2.4.6-fzl2npjphl7uxgvt5k2bpegqsbmlj7pc/libtool-2.4.6.tar.gz
==> Created stage in /tmp/nithinsk/spack-stage/spack-stage-libtool-2.4.6-fzl2npjphl7uxgvt5k2bpegqsbmlj7pc
==> No patches needed for libtool
==> 2726: libtool: Building libtool [AutotoolsPackage]
==> 2726: libtool: Executing phase: 'autoreconf'
==> 2726: libtool: Executing phase: 'configure'
==> 2726: libtool: Executing phase: 'build'
==> 2726: libtool: Executing phase: 'install'
==> Error: OSError: [Errno 36] File name too long

/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/var/spack/repos/builtin/packages/libtool/package.py:63, in post_install:
         60        # GNU commands glibtool and glibtoolize instead of the BSD
         61        # variant; this happens frequently, for instance, on Darwin
         62        symlink(join_path(self.prefix.bin, 'libtool'),
  >>     63                join_path(self.prefix.bin, 'glibtool'))
         64        symlink(join_path(self.prefix.bin, 'libtoolize'),
         65                join_path(self.prefix.bin, 'glibtoolize'))

See build log for details:
  /tmp/nithinsk/spack-stage/spack-stage-libtool-2.4.6-fzl2npjphl7uxgvt5k2bpegqsbmlj7pc/spack-build-out.txt

==> Error: Failed to install libtool due to ChildError: OSError: [Errno 36] File name too long
/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/var/spack/repos/builtin/packages/libtool/package.py:63, in post_install:
         60        # GNU commands glibtool and glibtoolize instead of the BSD
         61        # variant; this happens frequently, for instance, on Darwin
         62        symlink(join_path(self.prefix.bin, 'libtool'),
  >>     63                join_path(self.prefix.bin, 'glibtool'))
         64        symlink(join_path(self.prefix.bin, 'libtoolize'),
         65                join_path(self.prefix.bin, 'glibtoolize'))

See build log for details:
  /tmp/nithinsk/spack-stage/spack-stage-libtool-2.4.6-fzl2npjphl7uxgvt5k2bpegqsbmlj7pc/spack-build-out.txt
Traceback (most recent call last):
  File "/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/lib/spack/spack/installer.py", line 1123, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/lib/spack/spack/package.py", line 112, in phase_wrapper
    callback(instance)
  File "/storage/users/nithinsk/verylongverylongverylongverylongverylong/spack/var/spack/repos/builtin/packages/libtool/package.py", line 64, in post_install
    symlink(join_path(self.prefix.bin, 'libtoolize'),
OSError: [Errno 36] File name too long

-bash-4.2$
...
```
### Information on your system
```
-bash-4.2$ spack debug report
* **Spack:** 0.14.2-1209-bc145b2
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake_avx512
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/4675166/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4675167/spack-build-out.txt)

```
-bash-4.2$ spack maintainers bzip2
-bash-4.2$ spack maintainers libtool
-bash-4.2$

```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by scottwittenburg** [comment]
@nithintsk I saw a similar issue with those packages on an Ubuntu system.  Even though the final generated path length (`3871` in the case of one of your pasted install paths) is less than the system max path (usually `4096` on linux, but you can check in your specific case by typing `getconf PATH_MAX /`), some packages had problems making symlinks with that length of path.  

In my case, I was able to use just `$padding` on some systems, but it failed on others with the same error message you reported.  I didn't know what was going on there,  so for that reason, I added the ability to specify explicitly the number of characters of padding you want.

Can you try with a smaller amount of padding and see if it resolves your situation?  You can replace `$padding` with `$padding:<padlen>`, where `padlen` can be any number, but should be smaller than what's getting computed by `getconf PATH_MAX /`.  Maybe try with `512`, `1024` or something larger.

**Comment by nithintsk** [comment]
Thanks for your reply Scott. It looks like the max path length on both my systems are 4096.

```
Source:
[senthilkumar.16@head ~]$ getconf PATH_MAX /
4096

Target:
-bash-4.2$ getconf PATH_MAX /
4096
```

I did see the $padding:<len> option and am glad it's there. Currently I'm using $padding:300 and have no issues with it. Just wanted to bring to your attention that $padding was not working for some packages. I have no further questions since $padding:<len> is a suitable workaround.
