### ISSUE TITLE
Spack install fails to use local source cache for git repo

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#16813]
### Runtime Environment
Using `spack@develop` w/ commit id `0b96082e7` from 20-May-2020 on `Ubuntu 18.04` for `x86_64`

### Problem
`spack install` isn't able to use the locally mirrored source of packages that rely on Git repositories, when the network is unavailable during `spack install`. The problem is easily illustrated below using the simple package `cinch@master` as an example. `cinch` has no explicit dependencies.

1. Create source cache for `cinch@master`
```
$> spack mirror create -D cinch@master
...
==> Adding package cinch@master to mirror
==> Successfully updated mirror in file:///opt/spack/var/spack/cache
  Archive stats:
    0    already present
    1    added
    0    failed to fetch.
```

2. Add the mirror

3. Disable network access

4. Try installing `cinch@master`
```
$> spack install cinch@master
==> Finding buildcaches at https://cache.e4s.io/e4s/build_cache
==> Fetching https://cache.e4s.io/e4s/build_cache/linux-ubuntu18.04-x86_64/gcc-7.3.0/cinch-master/linux-ubuntu18.04-x86_64-gcc-7.3.0-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2.spack

curl: (6) Could not resolve host: cache.e4s.io
==> Failed to fetch file from URL: https://cache.e4s.io/e4s/build_cache/linux-ubuntu18.04-x86_64/gcc-7.3.0/cinch-master/linux-ubuntu18.04-x86_64-gcc-7.3.0-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2.spack
    Curl failed with error 6
==> Fetching from https://cache.e4s.io/e4s/build_cache/linux-ubuntu18.04-x86_64/gcc-7.3.0/cinch-master/linux-ubuntu18.04-x86_64-gcc-7.3.0-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2.spack failed.
==> cinch exists in binary cache but with different hash
==> Fetching https://cache.e4s.io/e4s/cinch/cinch-master.tar.gz

curl: (6) Could not resolve host: cache.e4s.io
==> Failed to fetch file from URL: https://cache.e4s.io/e4s/cinch/cinch-master.tar.gz
    Curl failed with error 6
==> Fetching from https://cache.e4s.io/e4s/cinch/cinch-master.tar.gz failed.
==> Fetching https://cache.e4s.io/e4s/_source-cache/git/laristra/cinch.git/master.tar.gz

curl: (6) Could not resolve host: cache.e4s.io
==> Failed to fetch file from URL: https://cache.e4s.io/e4s/_source-cache/git/laristra/cinch.git/master.tar.gz
    Curl failed with error 6
==> Fetching from https://cache.e4s.io/e4s/_source-cache/git/laristra/cinch.git/master.tar.gz failed.
==> Cloning git repository: https://github.com/laristra/cinch.git on branch master
fatal: unable to access 'https://github.com/laristra/cinch.git/': Could not resolve host: github.com
==> Fetching from [git] https://github.com/laristra/cinch.git on branch master failed.
==> Error: FetchError: All fetchers failed for spack-stage-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2

/opt/spack/lib/spack/spack/package.py:1142, in do_fetch:
       1139                raise FetchError("Will not fetch %s" %
       1140                                 self.spec.format('{name}{@version}'), ck_msg)
       1141
  >>   1142        self.stage.create()
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145


==> Error: Failed to install cinch due to ChildError: FetchError: All fetchers failed for spack-stage-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2
/opt/spack/lib/spack/spack/package.py:1142, in do_fetch:
       1139                raise FetchError("Will not fetch %s" %
       1140                                 self.spec.format('{name}{@version}'), ck_msg)
       1141
  >>   1142        self.stage.create()
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145

Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/opt/spack/lib/spack/spack/installer.py", line 1056, in build_process
    pkg.do_patch()
  File "/opt/spack/lib/spack/spack/package.py", line 1182, in do_patch
    self.do_stage()
  File "/opt/spack/lib/spack/spack/package.py", line 1167, in do_stage
    self.do_fetch(mirror_only)
  File "/opt/spack/lib/spack/spack/package.py", line 1143, in do_fetch
    self.stage.fetch(mirror_only)
  File "/opt/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/opt/spack/lib/spack/spack/stage.py", line 476, in fetch
    raise fs.FetchError(err_msg, None)
spack.fetch_strategy.FetchError: All fetchers failed for spack-stage-cinch-master-52n2v525ejt5ekjyx5e5w6e2d2lwwin2
```

@becker33 @scottwittenburg @mpbelhorn @scheibelp 

Updated 6/2/2020: Explicitly state that the mirror is added, so that there is no confusion as to whether this behavior is due to the mirror not having been added

**Comment by scheibelp** [comment]
Did you `spack mirror add` the mirror after you created it? On Mac OS I can get Spack to download the git repository from the mirror:

```
$ spack mirror create -d test-mirror1 cinch@master
$ spack mirror add t1 file://`pwd`/test-mirror1
$ spack fetch cinch@master
==> Fetching file:///Users/scheibel1/Desktop/spack/spack/test-mirror1/cinch/cinch-master.tar.gz
######################################################################## 100.0%
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
```

Note that the Spack fetch cache avoids adding unverifiable sources (like the tip of a Git branch) but it should work with a mirror.

**Comment by eugeneswalker** [comment]
I did ‘spack mirror’ with a file containing list of specs. I was then able to install every non-Git package in the list of specs just fine— without network access. The Git ones failed, despite me being able to verify the existence of the source mirror for the specific Git-based packages. But, that said, I do not think I explicitly added the mirror.

**Comment by scheibelp** [comment]
If `spack mirror list` doesn't show the mirror, then Spack won't use it, and those sources would be getting picked up another way (perhaps Spack's default cache was updated at some point?). Can you let me know if it fails after using `spack mirror add`?

**Comment by eugeneswalker** [comment]
`spack mirror list` shows the mirror. I just didn't remember adding it, but I must've done it, because it is there.

Some more context:
I am running `spack install` on compute nodes where there is zero outside network access. On the compute nodes, `spack install` is ABLE to install every single spec except the Git-based ones, <em>using the local source mirror</em>. <b>It is only the Git-based packages which have trouble here</b>. You can test in a docker container by creating the mirror, adding it, then disconnecting the running container from the default bridge network, and then trying to `spack install` the Git-based package which you know to be available in the local source cache.

@scheibelp You say on MacOS you can observe `spack install` using the local source cache, but is that WITHOUT any network access?

**Comment by scheibelp** [comment]
> You say on MacOS you can observe spack install using the local source cache, but is that WITHOUT any network access?

Good point: no I haven't disconnected my system from the network. I will have to do that to confirm whether the mirror helps in my case.

**Comment by scheibelp** [comment]
I tried this while disconnected from the internet and it appeared to work OK (again, on my Mac). I'll note that generally versions like `@master` are less preferred, so would you be able to run `spack spec <the spec you want to install>` to ensure that everything you want is in the mirror? For example in the case of `cinch` I had to explicitly `spack install cinch@master`.

**Comment by eugeneswalker** [comment]
So I definitely screwed up on my reproducer. The problem I've been running into on the compute nodes is when installing `flecsi+cinch` .  I first do `spack mirror create -D flecsi+cinch` on a login node and make sure it was able to cache all the specs. I then go to the compute node, and run `spack install felsci+cinch`. Everything installs just fine until it reaches `cinch`:

```
$compute-node> spack install flecsi+cinch
...
==> 115225: Installing cinch
==> Finding buildcaches in /gpfs/wolf/scratch/lpeyrala/gen010/build_cache
==> Fetching file:///gpfs/wolf/scratch/lpeyrala/gen010/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
curl: (37) Couldn't open file /gpfs/wolf/scratch/lpeyrala/gen010/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
==> Failed to fetch file from URL: file:///gpfs/wolf/scratch/lpeyrala/gen010/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
    Curl failed with error 37
==> Fetching from file:///gpfs/wolf/scratch/lpeyrala/gen010/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml failed.
==> Fetching file:///gpfs/wolf/scratch/lpeyrala/gen010/cinch/cinch-master.tar.gz
curl: (37) Couldn't open file /gpfs/wolf/scratch/lpeyrala/gen010/cinch/cinch-master.tar.gz
==> Failed to fetch file from URL: file:///gpfs/wolf/scratch/lpeyrala/gen010/cinch/cinch-master.tar.gz
    Curl failed with error 37
==> Fetching from file:///gpfs/wolf/scratch/lpeyrala/gen010/cinch/cinch-master.tar.gz failed.
==> Fetching file:///gpfs/wolf/scratch/lpeyrala/gen010/_source-cache/git/laristra/cinch.git/master.tar.gz
curl: (37) Couldn't open file /gpfs/wolf/scratch/lpeyrala/gen010/_source-cache/git/laristra/cinch.git/master.tar.gz
==> Failed to fetch file from URL: file:///gpfs/wolf/scratch/lpeyrala/gen010/_source-cache/git/laristra/cinch.git/master.tar.gz
    Curl failed with error 37
==> Fetching from file:///gpfs/wolf/scratch/lpeyrala/gen010/_source-cache/git/laristra/cinch.git/master.tar.gz failed.
==> Cloning git repository: https://github.com/laristra/cinch.git on branch master
==> Error: FetchError: All fetchers failed for spack-stage-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t

/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/package.py:1142, in do_fetch:
       1139                raise FetchError("Will not fetch %s" %
       1140                                 self.spec.format('{name}{@version}'), ck_msg)
       1141
  >>   1142        self.stage.create()
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145
```

`flecsi+cinch` has like 15 dependencies including boost and cmake, and I was hoping to avoid having anyone who was generous enough to look at this problem have to build all those just to tease out the problem. Unfortunately it looks like the problem is only showing its head in that form. Sorry about this confusion. I just now did a fresh clone of Spack, ran `spack mirror flecsi+cinch` on login node, and then ran `spack install flecsi+cinch` on compute node, and got this error output. Do you have any ideas?

**Comment by scheibelp** [comment]
Thanks for the clarification!

> Do you have any ideas?

The mirroring logic might be ignoring the dependency constraints and not adding the Git version to the mirror. A short term solution may be to explicitly add `cinch@master` to the mirror (like in https://github.com/spack/spack/issues/16813#issuecomment-637727880). Note you would want to do this in addition to mirroring `flecsi+cinch` like

```
spack mirror create --dependencies flecsi+cinch
spack mirror create cinch@master
```

I should be able to create the mirror and compare it to the specs without building anything, so that won't hold me up, I'll try that out tomorrow. But if you let me know whether (a) you see the git version in the mirror currently and (b) whether this suggested temporary solution works then that would be useful.

**Comment by eugeneswalker** [comment]
Some more context here:

I have been creating my local source cache like this:
```
$login-node> spack mirror create -D flecsi+cinch
==> Adding package flecsi@1 to mirror
==> Successfully updated mirror in file:///gpfs/wolf/gen010/scratch/lpeyrala/spack/var/spack/cache
  Archive stats:
    1    already present
    0    added
    0    failed to fetch.
```
<b>Notice how I am not specifying a directory!!</b> It is storing these in `$SPACK_ROOT/var/spack/cache`

Then when I run on the compute node:
```
$compute-node> spack install flecsi+cinch
...
==> Error: Failed to install cinch due to ChildError: SystemExit: 1
/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/package.py:1142, in do_fetch:
       1139                raise FetchError("Will not fetch %s" %
       1140                                 self.spec.format('{name}{@version}'), ck_msg)
       1141
  >>   1142        self.stage.create()
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145

Traceback (most recent call last):
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/installer.py", line 1056, in build_process
    pkg.do_patch()
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/package.py", line 1182, in do_patch
    self.do_stage()
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/package.py", line 1167, in do_stage
    self.do_fetch(mirror_only)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/package.py", line 1143, in do_fetch
    self.stage.fetch(mirror_only)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/stage.py", line 464, in fetch
    self.fetcher.fetch()
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
    return fun(self, *args, **kwargs)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/fetch_strategy.py", line 795, in fetch
    git = self.git
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/fetch_strategy.py", line 752, in git
    self._git = which('git', required=True)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/util/executable.py", line 263, in which
    exe = which_string(*args, **kwargs)
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/spack/util/executable.py", line 242, in which_string
    tty.die("spack requires '%s'. Make sure it is in your path." % args[0])
  File "/gpfs/wolf/gen010/scratch/lpeyrala/spack/lib/spack/llnl/util/tty/__init__.py", line 227, in die
    sys.exit(1)
SystemExit: 1
```

That is what I've been doing and it obviously isn't working.

IT DOES WORK if I create the source cache like this:
```
$login-node> spack mirror create -d mirror -D flecsi+cinch
...
==> Successfully updated mirror in file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror
  Archive stats:
    0   already present
    16    added
    0    failed to fetch.

$login-node> spack mirror add local mirror

$login-node> spack mirror list
local    file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror

$login-node> ssh compute-node

$compute-node> spack install flecsi+cinch
...
==> 157568: Installing cinch
==> Finding buildcaches in /gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache
==> Fetching file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
curl: (37) Couldn't open file /gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
==> Failed to fetch file from URL: file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml
    Curl failed with error 37
==> Fetching from file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t.spec.yaml failed.
==> Fetching file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/cinch/cinch-master.tar.gz
######################################################################## 100.0%
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Staging archive: /tmp/lpeyrala/spack-stage/spack-stage-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t/master.tar.gz
==> Created stage in /tmp/lpeyrala/spack-stage/spack-stage-cinch-master-qj2b6cdxw5wbq35z7ddhyukssqwa7f4t
==> No patches needed for cinch
==> 157568: cinch: Building cinch [Package]
==> 157568: cinch: Executing phase: 'install'
==> 157568: cinch: Successfully installed cinch
  Fetch: 0.05s.  Build: 0.71s.  Total: 0.77s.
...
```

So, everything works if I explicitly state what directory to store the mirrored sources in, and then make sure I `spack mirror add` that directory. That all works. It does not work if I let Spack put the mirrored sources in `$SPACK_ROOT/var/spack/cache`. At least, it seems like it isn't working for `cinch` in `flecsi+cinch`. Other packages were able to be installed using the cached sources in `$SPACK_ROOT/var/spack/cache` but not cinch, and I think it may be more general to Git-based packages, but I don't know.

For example, even though the following doesn't work for the `cinch` in `flecsi+cinch`, it does work for `zip`:
```
$login-node> spack mirror create -D zip
$login-node> ssh compute-node
$compute-node> spack install zip
...
==> 158666: Installing zip
==> Finding buildcaches in /gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache
==> Fetching file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f.spec.yaml
curl: (37) Couldn't open file /gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f.spec.yaml
==> Failed to fetch file from URL: file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f.spec.yaml
    Curl failed with error 37
==> Fetching from file:///gpfs/wolf/gen010/scratch/lpeyrala/mirror/build_cache/linux-rhel7-ppc64le-gcc-6.4.0-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f.spec.yaml failed.
==> Using cached archive: /gpfs/wolf/gen010/scratch/lpeyrala/spack/var/spack/cache/_source-cache/archive/f0/f0e8bb1f9b7eb0b01285495a2699df3a4b766784c1765a8f1aeedf63c0806369.tar.gz
==> Staging archive: /tmp/lpeyrala/spack-stage/spack-stage-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f/zip30.tar.gz
==> Created stage in /tmp/lpeyrala/spack-stage/spack-stage-zip-3.0-fgzr4xysx53era3thrszf2tqmxl3ry5f
==> No patches needed for zip
==> 158666: zip: Building zip [MakefilePackage]
==> 158666: zip: Executing phase: 'edit'
==> 158666: zip: Executing phase: 'build'
==> 158666: zip: Executing phase: 'install'
==> 158666: zip: Successfully installed zip
  Fetch: 0.07s.  Build: 3.63s.  Total: 3.70s.
```

Odd, right?

**Comment by scheibelp** [comment]
This should be documented or otherwise clarified to the user, but Spack avoids attempting to retrieve "unstable" versions from its internal source cache (so even if an archive of a Git branch tip is stored there, Spack won't look for it there) : my goal with that was to avoid a user accidentally pulling in the tip of a branch and then transparently downloading that cached version indefinitely. 

With an explicitly-created mirror, it is understood that the user should be able to put anything they want in it.

**Comment by eugeneswalker** [comment]
Ok. Gotcha. So this is intended behavior then. Should we close this issue? Thanks for helping me with this.

**Comment by scheibelp** [comment]
Absolutely - you are welcome! I'm trying to decide if the issue should remain open so I can figure out how to clarify this to users
