### ISSUE TITLE
Installation issue: meep

### ISSUE THREAD

**Issue by huqy** [LLNL/spack#16936]
Hi I am unable to install meep through spack by getting the error below. It can be reproduced by running a container from the spack's docker image `spack/centos7:latest`. Please advise. Thanks.

```console
[centos] ~: spack install meep
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gsl-2.5-glr7krli4li4oi7gzwrgafxsgeqdqpqj
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libatomic-ops-7.6.6-aaa32v65nin44ticonytvxbqwwsxnh4s
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libiconv-1.16-qazxaa4lnd2ukd44fjzdhayyxvcg3wyu
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/pkgconf-1.6.3-2qrpgpdjr5kso7gjbkq2xntoljyuldwd
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/xz-5.2.5-rcyjfkv7lwnibnpah22vdo35fvycag4o
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/zlib-1.2.11-pkmj6e72vggig3epxjcwxgzmxncaqnmp
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libsigsegv-2.12-ymriiurzbqgc5sty6h7zsbys2p2miwh3
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libffi-3.3-2zxlme5gqhe56lykdumo6pnuk627xmsy
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openblas-0.3.9-ynzalxqedw2ky4au5ab2cpq2v2joqbot
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/util-macros-1.19.1-wmglf72gmndo3euipggm6rncy744en2m
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/bdw-gc-8.0.0-7ea4ouavgt3gm35ypvv5g5t6on3nchnu
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/diffutils-3.7-jknorwe54bgplxnyom6sgwnbkong3jww
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/tar-1.32-v3iynan2575fichxxpjh4aqvs7pkle5c
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libunistring-0.9.10-o2r2guvz2ys5irc5cuby4u5onzy6vbdl
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/ncurses-6.2-tbpd5z45tamug3s3u3utt3rhay77lduh
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libxml2-2.9.10-3foymu42tqna2po3m3oi65bgulxxpunq
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/m4-1.4.18-7x2wh2thcpfjgeqxf4vhrqw3suxldfab
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/harminv-1.4-n3adprtja37tz6kibv5i5j4wpd4usogv
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/bzip2-1.0.8-ersrl36bb43nnkjwe4t4gdur5jnwlzye
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/readline-8.0-3jeiguwntbums72jmkcfbzplsstwa5rn
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libtool-2.4.6-fzl2npjphl7uxgvt5k2bpegqsbmlj7pc
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gettext-0.20.2-kapb6qjzmekccfuovpj2elbyfh2yovx5
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gdbm-1.18.1-7xh2soiwyepqubqwwhmtlrarqzz2kdna
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libpciaccess-0.13.5-7dqpxasta4nojspfwcobu7gibqnyrq5f
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/perl-5.30.2-uay4u7vmgddt7dlwcu5ymn7a4m5ydhlt
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/autoconf-2.69-6k6kik7nq5wxeply2fdsqyv34rmsxhe5
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/automake-1.16.2-ipyg4haxqgw3dvq7ti5ycsre752wljya
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gmp-6.1.2-zn55wh7voutcbk46jzwgfyjfincjyuhh
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/numactl-2.0.12-5pz4h3prscq4uoxja3ef5zib322wnqqo
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/guile-2.2.6-r2o7sn7qfrterqqh3zji5x3fow7tbd7m
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/hwloc-1.11.11-3v4f56plwdi55ktsnhlnpbdmabbwvcfb
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libctl-3.2.2-k4fzre5kscd4hro33ntvwpabch35rwxs
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-3.1.6-g66vm2br5owrccusmabiuhdhzoaaxb4m
[+] /opt/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/hdf5-1.10.6-utbirqmawzdto55lnxdhdr7etxm5buhs
==> 9728: Installing meep
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/56/564c1ff1b413a3487cf81048a45deabfdac4243a1a37ce743f4fcf0c055fd438.tar.gz
==> Staging archive: /tmp/root/spack-stage/spack-stage-meep-1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/meep-1.3.tar.gz
==> Created stage in /tmp/root/spack-stage/spack-stage-meep-1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt
==> No patches needed for meep
==> 9728: meep: Building meep [AutotoolsPackage]
==> 9728: meep: Executing phase: 'autoreconf'
==> 9728: meep: Executing phase: 'configure'
==> 9728: meep: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'

6 errors found in build log:
     273    structure.cpp:1511:51: warning: deprecated conversion from string c
            onstant to 'char*' [-Wwrite-strings]
     274       number no_size = 2.0 / ctl_get_number("infinity");
     275                                                       ^
     276      CXX      main.o
     277      CXX      geom.o
     278    meep_wrap.cxx: In function 'int SwigVector3_Check(SCM)':
  >> 279    meep_wrap.cxx:1384:23: error: 'SCM_VECTORP' was not declared in thi
            s scope
     280       return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
     281                           ^
  >> 282    meep_wrap.cxx:1384:47: error: 'SCM_VECTOR_LENGTH' was not declared 
            in this scope
     283       return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
     284                                                   ^
     285    main.cpp: In function 'void main_entry(void*, int, char**)':
     286    main.cpp:223:22: warning: deprecated conversion from string constan
            t to 'char*' [-Wwrite-strings]
     287       ctl_include(CTL_SCM);
     288                          ^

     ...

     716    ctl-io.cpp:1496:36: warning: deprecated conversion from string cons
            tant to 'char*' [-Wwrite-strings]
     717     list lo_t = ctl_get_list("geometry");
     718                                        ^
     719    ctl-io.cpp:1504:58: warning: deprecated conversion from string cons
            tant to 'char*' [-Wwrite-strings]
     720     ensure_periodicity = ctl_get_boolean("ensure-periodicity");
     721                                                              ^
  >> 722    make[3]: *** [meep_wrap.o] Error 1
     723    make[3]: *** Waiting for unfinished jobs....
     724    make[3]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src/libctl'
  >> 725    make[2]: *** [all] Error 2
     726    make[2]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src/libctl'
  >> 727    make[1]: *** [all-recursive] Error 1
     728    make[1]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src'
  >> 729    make: *** [all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-meep-1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-build-out.txt

==> Error: Failed to install meep due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j4'
6 errors found in build log:
     273    structure.cpp:1511:51: warning: deprecated conversion from string c
            onstant to 'char*' [-Wwrite-strings]
     274       number no_size = 2.0 / ctl_get_number("infinity");
     275                                                       ^
     276      CXX      main.o
     277      CXX      geom.o
     278    meep_wrap.cxx: In function 'int SwigVector3_Check(SCM)':
  >> 279    meep_wrap.cxx:1384:23: error: 'SCM_VECTORP' was not declared in thi
            s scope
     280       return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
     281                           ^
  >> 282    meep_wrap.cxx:1384:47: error: 'SCM_VECTOR_LENGTH' was not declared 
            in this scope
     283       return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
     284                                                   ^
     285    main.cpp: In function 'void main_entry(void*, int, char**)':
     286    main.cpp:223:22: warning: deprecated conversion from string constan
            t to 'char*' [-Wwrite-strings]
     287       ctl_include(CTL_SCM);
     288                          ^

     ...

     716    ctl-io.cpp:1496:36: warning: deprecated conversion from string cons
            tant to 'char*' [-Wwrite-strings]
     717     list lo_t = ctl_get_list("geometry");
     718                                        ^
     719    ctl-io.cpp:1504:58: warning: deprecated conversion from string cons
            tant to 'char*' [-Wwrite-strings]
     720     ensure_periodicity = ctl_get_boolean("ensure-periodicity");
     721                                                              ^
  >> 722    make[3]: *** [meep_wrap.o] Error 1
     723    make[3]: *** Waiting for unfinished jobs....
     724    make[3]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src/libctl'
  >> 725    make[2]: *** [all] Error 2
     726    make[2]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src/libctl'
  >> 727    make[1]: *** [all-recursive] Error 1
     728    make[1]: Leaving directory `/tmp/root/spack-stage/spack-stage-meep-
            1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-src'
  >> 729    make: *** [all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-meep-1.3-3ykmkkur3etuqxxojsf2czss2ubxvszt/spack-build-out.txt
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/opt/spack/lib/spack/spack/installer.py", line 1123, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/opt/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/opt/spack/lib/spack/spack/build_systems/autotools.py", line 308, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/opt/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/opt/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 2:
    'make' '-j4'
```

**Comment by longlong10086** [comment]
Encountered the same error, do you have a solution now?
