### ISSUE TITLE
Installation issue: visit

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#16965]
I'm trying to install visit on Centos 7 using gcc 7.3.1 provided by devtoolset-7.

### Steps to reproduce the issue

If spack is checked out on branch develop, I get an unsatisfiable version constraint:
```console
$ cd spack
$ git checkout develop
$ spack speck visit
...
==> Error: An unsatisfiable version constraint has been detected for spec:
...
while trying to concretize the partial spec:

    py-setuptools@46.1.3%gcc@8.4.0 arch=linux-opensuse_leap15-haswell


py-setuptools requires python version 3.5:, but spec asked for 2.7.18
$ spack speck visit ^python@3.5
...
==> Error: An unsatisfiable version constraint has been detected for spec:
...
visit requires python version 2.6:2.8, but spec asked for 3.5
```

When checked out on v0.14.2, it fails when it tries to install the dependency qt
```console
$ cd spack
$ git checkout v0.14.2
$ spack install visit
...
==> 12765: Installing qt
==> Fetching http://download.qt.io/archive/qt/5.14/5.14.1/single/qt-everywhere-src-5.14.1.tar.xz
==> Staging archive: /tmp/andrew/spack-stage/spack-stage-qt-5.14.1-lc52pytmpgeruszc2whhgs4jfxcseevt/qt-everywhere-src-5.14.1.tar.xz
==> Created stage in /tmp/andrew/spack-stage/spack-stage-qt-5.14.1-lc52pytmpgeruszc2whhgs4jfxcseevt
==> Applied patch /home/andrew/spack/var/spack/repos/builtin/packages/qt/qt5-pcre.patch
==> Ran patch() for qt
==> 12765: qt: Building qt [Package]
==> 12765: qt: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 3:
    './configure' '-prefix' '/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/qt-5.14.1-lc52pytmpgeruszc2whhgs4jfxcseevt' '-v' '-opensource' '-opengl' '-release' '-confirm-license' '-optimized-qmake' '-no-pch' '-system-freetype' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/freetype-2.10.1-44b3zl3w2d4fbnpfwitib665znithd5k/include/freetype2' '-fontconfig' '-openssl-linked' '' '-I/usr/include' '-system-sqlite' '-R' '/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/sqlite-3.30.1-yfpks6qgtdcduoq7rzq7fjqr2yvzofxd/lib' '-shared' '-system-harfbuzz' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/harfbuzz-2.3.1-rf7hniptamhaymfxf4khqn6bynyd4lbq/lib' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/harfbuzz-2.3.1-rf7hniptamhaymfxf4khqn6bynyd4lbq/include' '-system-pcre' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/pcre2-10.31-zqzdm2xexd4nqxrdv6qoqf4khhofiexy/lib' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/pcre2-10.31-zqzdm2xexd4nqxrdv6qoqf4khhofiexy/include' '-system-doubleconversion' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/double-conversion-2.0.1-2gwru5lqxslyadevmnymq6bt2csubxdj/lib' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/double-conversion-2.0.1-2gwru5lqxslyadevmnymq6bt2csubxdj/include' '-system-libpng' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/libpng-1.6.37-5yln2v5yqxg6yqsmkuj56qrloigwyvqi/lib' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/libpng-1.6.37-5yln2v5yqxg6yqsmkuj56qrloigwyvqi/include' '-system-libjpeg' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/libjpeg-turbo-2.0.3-tkg3isbtkrl4yr34hbevaggmsni2udfq/lib64' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/libjpeg-turbo-2.0.3-tkg3isbtkrl4yr34hbevaggmsni2udfq/include' '-system-zlib' '-L/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/zlib-1.2.11-ng6232cbhcm5k24ua3w7wnemyskyo4wr/lib' '-I/home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/zlib-1.2.11-ng6232cbhcm5k24ua3w7wnemyskyo4wr/include' '-nomake' 'examples' '-no-dbus' '-platform' 'linux-g++' '-no-eglfs' '-no-directfb' '-no-gtk' '-system-xcb' '-skip' 'webengine' '-skip' 'wayland'

66 errors found in build log:
     280     >                  from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
     281     >                  from /opt/rh/devtoolset-7/root/usr/include/c++/7/optional:38,
     282     >                  from /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/node_handle.h:39,
     283     >                  from /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_tree.h:72,
     284     >                  from /opt/rh/devtoolset-7/root/usr/include/c++/7/map:60,
     285     >                  from main.cpp:7:
  >> 286     > /opt/rh/devtoolset-7/root/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
     287     >  #include_next <stdlib.h>
     288     >                ^~~~~~~~~~
     289     > compilation terminated.
  >> 290     > gmake: *** [main.o] Error 1
```

### Information on your system

`spack debug report` fails when spack is checked out on v0.14.2.

On develop:
* **Spack:** 0.14.2-1335-94e7733
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell

packages.yaml:
```yaml
packages:
  cmake:
    version: [3.15.5]
  boost:
    version: [1.69.0]
    variants: +mpi
  eigen:
    version: [3.3.4]
  jsoncpp:
    version: [1.8.3]
  vtk:
    version: [8.1.0]
    variants: -opengl2
  llvm:
    variants: -lldb
  mesa:
    variants: -llvm +glx
  opengl:
    paths:
      opengl@4.5 arch=linux: /usr
    version: [system]
    buildable: False
  openglu:
    paths:
      openglu@1.3 arch=linux: /usr
    version: [system]
    buildable: False
  openssl:
    paths:
      openssl: /usr
    version: [system]
    buildable: False
  
  all:
    compiler: [gcc]
    providers:
      mpi: [mpich@3.3.2]
      lapack: [netlib-lapack]
      blas: [netlib-lapack]
      gl: [opengl]
      glu: [openglu]
```

In compilers.yaml
```yaml
- compiler:
    spec: gcc@7.3.1
    paths:
      cc: /opt/rh/devtoolset-7/root/usr/bin/gcc
      cxx: /opt/rh/devtoolset-7/root/usr/bin/g++
      f77: /opt/rh/devtoolset-7/root/usr/bin/gfortran
      fc: /opt/rh/devtoolset-7/root/usr/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4735308/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4735310/spack-build-env.txt)

Maintainers:
* visit: @cyrush 
* qt: @sethrj 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
The QT error looks like your GCC compiler configuration might be missing some flags or install components. The concretization error is because Visit requires python 2.7 but spack defaults to 3.x. Also it looks like you misspelled “spec” but I guess spack anticipated such typos 😅

**Comment by cyrush** [comment]
@andymwood I make some changes to develop recently, and when I did - I added some comments in the package about install specs to try.

Here is a snippet:
```
    # linux:
    #  spack install visit ^python+shared ^glib@2.56.3 ^py-setuptools@44.1.0
    #
    # macOS:
    #  spack install visit ^python+shared ^glib@2.56.3 ^py-setuptools@44.1.0 \
    #                      ^qt~framework
```
I still think there is something that needs to be fixed for linux, I think we need to add GLU dep.

**Comment by andymwood** [comment]
@cyrush Thanks for the response. I've tried that and now get this when it tries to install glib:
```console
==> 31094: glib: Building glib [Package]
==> 31094: glib: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     567    Making all in glib
     568    make[2]: Entering directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
     569      GEN      glibconfig-stamp
     570      GEN      glib_probes.h
     571      GEN      glib_probes.lo
     572    ImportError: No module named site
  >> 573    make[2]: *** [glib_probes.h] Error 1
     574    make[2]: *** Waiting for unfinished jobs....
     575    ImportError: No module named site
  >> 576    make[2]: *** [glib_probes.lo] Error 1
     577    config.status: executing glib/glibconfig.h commands
     578    config.status: glib/glibconfig.h is unchanged
     579      GEN      glibconfig-stamp
     580    config.status: creating glib/glibconfig.h.win32
     581    make[2]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
  >> 582    make[1]: *** [all-recursive] Error 1
     583    make[1]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src'
  >> 584    make: *** [all] Error 2

See build log for details:
  /tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-build-out.txt

==> Error: Failed to install glib due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j16'
4 errors found in build log:
     567    Making all in glib
     568    make[2]: Entering directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
     569      GEN      glibconfig-stamp
     570      GEN      glib_probes.h
     571      GEN      glib_probes.lo
     572    ImportError: No module named site
  >> 573    make[2]: *** [glib_probes.h] Error 1
     574    make[2]: *** Waiting for unfinished jobs....
     575    ImportError: No module named site
  >> 576    make[2]: *** [glib_probes.lo] Error 1
     577    config.status: executing glib/glibconfig.h commands
     578    config.status: glib/glibconfig.h is unchanged
     579      GEN      glibconfig-stamp
     580    config.status: creating glib/glibconfig.h.win32
     581    make[2]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
  >> 582    make[1]: *** [all-recursive] Error 1
     583    make[1]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src'
  >> 584    make: *** [all] Error 2

See build log for details:
  /tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-build-out.txt
Traceback (most recent call last):
  File "/home/andrew/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/home/andrew/spack/lib/spack/spack/installer.py", line 1130, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/andrew/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/andrew/spack/lib/spack/spack/multimethod.py", line 133, in __call__
    return spec_method(package_self, *args, **kwargs)
  File "/home/andrew/spack/var/spack/repos/builtin/packages/glib/package.py", line 173, in install
    if self.run_tests:
  File "/home/andrew/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/andrew/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j16'
```
[glib-spack-build-out.txt](https://github.com/spack/spack/files/4756939/glib-spack-build-out.txt)

**Comment by cyrush** [comment]
Hmm, by the looks of:

`ImportError: No module named site`

looks like glib is using python in its build system and for some reason the python it is calling is not viable. 

Was python built before this, or is that later in the build chain?

**Comment by andymwood** [comment]
Python is built first:
```console
==> 26889: Installing python
==> Fetching https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
==> Staging archive: /tmp/andrew/spack-stage/spack-stage-python-2.7.18-2bdbd4imlmfmy5ddkldnqzcfvufyfvf4/Python-2.7.18.tgz
==> Created stage in /tmp/andrew/spack-stage/spack-stage-python-2.7.18-2bdbd4imlmfmy5ddkldnqzcfvufyfvf4
==> Ran patch() for python
==> 26889: python: Building python [AutotoolsPackage]
==> 26889: python: Executing phase: 'autoreconf'
==> 26889: python: Executing phase: 'configure'
==> 26889: python: Executing phase: 'build'
==> 26889: python: Executing phase: 'install'
==> 26889: python: Successfully installed python
  Fetch: 2.67s.  Build: 2m 10.79s.  Total: 2m 13.46s.
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/python-2.7.18-2bdbd4imlmfmy5ddkldnqzcfvufyfvf4
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/lcms-2.9-ixwxupeb6w3dlgiir3jqhzhehhiplvkp
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/texinfo-6.5-5qyzc373rgynfc6fpzui62vjihxbfznk
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/help2man-1.47.11-s3472btsqkvpgklglmop4gaqoy7erbgx
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/libx11-1.6.7-xdw7rj5rcgqlcjtehhpmpx4frjcwly6d
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/autoconf-2.69-fbk2ciqp2nluly63jzcqr4q73falx7qf
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/xcb-util-image-0.4.0-llk6fsansuybg6jxqqyttrihzop3pq6u
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/mkfontdir-1.0.7-qfdzxtgt2umdpivihda5q54tbvo4amrr
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/bdftopcf-1.0.5-ulijrqbtzygbcqqx4tzusyhqsvoies7n
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/icu4c-65.1-zjfunp5ckyhiyz5vqcnxmamf644zrj72
==> 26889: Installing py-setuptools
==> Fetching https://pypi.io/packages/source/s/setuptools/setuptools-44.1.0.zip
==> Staging archive: /tmp/andrew/spack-stage/spack-stage-py-setuptools-44.1.0-6ktwnh7jhq5rvfe3kvx7ossmqgvmzofk/setuptools-44.1.0.zip
==> Created stage in /tmp/andrew/spack-stage/spack-stage-py-setuptools-44.1.0-6ktwnh7jhq5rvfe3kvx7ossmqgvmzofk
==> No patches needed for py-setuptools
==> 26889: py-setuptools: Building py-setuptools [PythonPackage]
==> 26889: py-setuptools: Executing phase: 'build'
==> 26889: py-setuptools: Executing phase: 'install'
==> 26889: py-setuptools: Successfully installed py-setuptools
  Fetch: 1.05s.  Build: 1.89s.  Total: 2.94s.
[+] /home/andrew/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.1/py-setuptools-44.1.0-6ktwnh7jhq5rvfe3kvx7ossmqgvmzofk
==> 26889: Installing glib
==> Fetching http://ftp.gnome.org/pub/gnome/sources/glib/2.56/glib-2.56.3.tar.xz
==> Staging archive: /tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/glib-2.56.3.tar.xz
==> Created stage in /tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu
==> Applied patch /home/andrew/spack/var/spack/repos/builtin/packages/glib/no-Werror=format-security.patch
==> 26889: glib: Building glib [Package]
==> 26889: glib: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     567    Making all in glib
     568    make[2]: Entering directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
     569      GEN      glibconfig-stamp
     570      GEN      glib_probes.h
     571      GEN      glib_probes.lo
     572    ImportError: No module named site
  >> 573    make[2]: *** [glib_probes.h] Error 1
     574    make[2]: *** Waiting for unfinished jobs....
     575    ImportError: No module named site
  >> 576    make[2]: *** [glib_probes.lo] Error 1
     577    config.status: executing glib/glibconfig.h commands
     578    config.status: glib/glibconfig.h is unchanged
     579      GEN      glibconfig-stamp
     580    config.status: creating glib/glibconfig.h.win32
     581    make[2]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src/glib'
  >> 582    make[1]: *** [all-recursive] Error 1
     583    make[1]: Leaving directory `/tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-src'
  >> 584    make: *** [all] Error 2

See build log for details:
  /tmp/andrew/spack-stage/spack-stage-glib-2.56.3-ai6qirpy6jqy4nv4wibel6b3b7fr43eu/spack-build-out.txt
```
