### ISSUE TITLE
Installation issue: fftw@3.3.8 with intel@19.0.5 and intel-mpi@2019.5.281

### ISSUE THREAD

**Issue by ssergien** [LLNL/spack#17036]
### Steps to reproduce the issue

```console
$ spack install -v fftw@3.3.8 %intel@19.0.5 ^intel-mpi@2019.5.281
     ...

     5231                     from ../../../../dft/simd/generic-simd128/../comm
             on/n1fv_13.c(229),
     5232    ../../../../dft/simd/generic-simd128/../common/n1fv_11.c(196): war
             ning #1368: excess initializers are ignored
     5233           DVK(KP755749574, +0.755749574354258283774035843972344420179
             717445);
     5234           ^
     5235
     5236                     from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):
  >> 5237    ../../../../simd-support/simd-generic128.h(208): error: expression
              must have pointer-to-object type
     5238           V ti = VDUPH(tx);
     5239                  ^
     5240
     5241    In file included from ../../../../dft/simd/n1f.h(21),
     5242                     from ../../../../dft/simd/generic-simd128/../comm
             on/n1fv_13.c(229),
     5243                     from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):
  >> 5244    ../../../../simd-support/simd-generic128.h(208): error: expression
              must have pointer-to-object type
     5245           V ti = VDUPH(tx);
     5246                  ^
     5247
     5248    In file included from ../../../../dft/simd/n1f.h(21),
     5249                     from ../../../../dft/simd/generic-simd128/../comm
             on/n1fv_13.c(229),
     5250                     from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):

     ...

     5329
     5330    In file included from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):
     5331    ../../../../dft/simd/generic-simd128/../common/n1fv_13.c(241): war
             ning #1368: excess initializers are ignored
     5332           DVK(KP011599105, +0.011599105605768290721655456654083252189
             827041);
     5333           ^
     5334
  >> 5335    make[5]: *** [n1fv_6.lo] Error 1
     5336    In file included from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):
     5337    ../../../../dft/simd/generic-simd128/../common/n1fv_13.c(242): war
             ning #1368: excess initializers are ignored
     5338           DVK(KP156891391, +0.156891391051584611046832726756003269660
             212636);
     5339           ^
     5340
     5341    In file included from ../../../../dft/simd/generic-simd128/n1fv_13
             .c(3):

     ...

     5390
     5391    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             16.c (code 2)
     5392    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             8.c (code 2)
     5393    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             11.c (code 2)
     5394    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             14.c (code 2)
     5395    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             3.c (code 2)
  >> 5396    make[5]: *** [n1fv_8.lo] Error 1
  >> 5397    make[5]: *** [n1fv_16.lo] Error 1
  >> 5398    make[5]: *** [n1fv_11.lo] Error 1
  >> 5399    make[5]: *** [n1fv_14.lo] Error 1
     5400    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             32.c (code 2)
  >> 5401    make[5]: *** [n1fv_3.lo] Error 1
     5402    compilation aborted for ../../../../dft/simd/generic-simd128/n1fv_
             13.c (code 2)
  >> 5403    make[5]: *** [n1fv_32.lo] Error 1
  >> 5404    make[5]: *** [n1fv_13.lo] Error 1
     5405    make[5]: Leaving directory `/tmp/stas/spack-stage/spack-stage-fftw
             -3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-src/double/dft/simd/
             generic-simd128'
  >> 5406    make[4]: *** [all] Error 2
     5407    make[4]: Leaving directory `/tmp/stas/spack-stage/spack-stage-fftw
             -3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-src/double/dft/simd/
             generic-simd128'
  >> 5408    make[3]: *** [all-recursive] Error 1
     5409    make[3]: Leaving directory `/tmp/stas/spack-stage/spack-stage-fftw
             -3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-src/double/dft/simd'
  >> 5410    make[2]: *** [all-recursive] Error 1
     5411    make[2]: Leaving directory `/tmp/stas/spack-stage/spack-stage-fftw
             -3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-src/double/dft'
  >> 5412    make[1]: *** [all-recursive] Error 1
     5413    make[1]: Leaving directory `/tmp/stas/spack-stage/spack-stage-fftw
             -3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-src/double'
  >> 5414    make: *** [all] Error 2

See build log for details:
  /tmp/stas/spack-stage/spack-stage-fftw-3.3.8-hfkb3pianmghnswebswcqdclspzufsl4/spack-build-out.txt
Traceback (most recent call last):
  File "/data/stas/spack-latest/lib/spack/spack/build_environment.py", line 819, in child_process
    return_value = function()
  File "/data/stas/spack-latest/lib/spack/spack/installer.py", line 1130, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/data/stas/spack-latest/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/data/stas/spack-latest/var/spack/repos/builtin/packages/fftw/package.py", line 202, in build
  File "/data/stas/spack-latest/var/spack/repos/builtin/packages/fftw/package.py", line 199, in for_each_precision_make
  File "/data/stas/spack-latest/lib/spack/spack/build_environment.py", line 132, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/data/stas/spack-latest/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 2:
    'make' '-j16'
```

### Information on your system

```$ spack debug report
* **Spack:** 0.14.2-1386-0de12be
* **Python:** 2.7.5
* **Platform:** linux-centos7-sandybridge
```

```
$ cat packages.yaml
packages:
  all:
    # Set Intel as default compiler
    compiler: [intel, gcc, pgi, nag]
    providers:
      # Set Intel MKL as default BLAS/LAPACK provider
      blas:   [intel-mkl, netlib-lapack]
      lapack: [intel-mkl, netlib-lapack]
      fftw3: [intel-mkl]
      # Set Intel MPI as default MPI implementation
      mpi: [intel-mpi, mvapich2, mpich, openmpi]
    target: [x86_64]
  openssl:
    paths:
      openssl@1.0.2k arch=linux-centos7-x86_64: /usr
    buildable: False
  cpio:
    paths:
      cpio@2.11 arch=linux-centos7-x86_64: /usr
    buildable: False
  m4:
    paths:
      m4@1.4.17 arch=linux-centos7-x86_64: /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/intel-19.0.5/m4-1.4.17-tmumwia
    buildable: False
```
```
$ cat compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc:  /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-t6vopxd/bin/gcc
      cxx: /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-t6vopxd/bin/g++
      f77: /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-t6vopxd/bin/gfortran
      fc:  /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-t6vopxd/bin/gfortran
    spec: gcc@9.3.0
    target: x86_64
- compiler:
    environment:
      set:
        INTEL_LICENSE_FILE: 28518@licence.server
    modules: []
    operating_system: centos7
    paths:
      cc:  /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.3.0/intel-19.0.5-2rppjg7/bin/icc
      cxx: /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.3.0/intel-19.0.5-2rppjg7/bin/icpc
      f77: /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.3.0/intel-19.0.5-2rppjg7/bin/ifort
      fc:  /data/stas/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.3.0/intel-19.0.5-2rppjg7/bin/ifort
    spec: intel@19.0.5
    target: x86_64
```
### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4759291/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4759333/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by viniciusferrao** [comment]
I have the same issue with fftw@3.3.8%intel@20.0.166
