### ISSUE TITLE
Enable Python bindings in PMIx

### ISSUE THREAD

**Issue by rhc54** [LLNL/spack#17083]
We are seeing an uptick in the number of people wanting to use PMIx in Python libraries and applications. I'm not sure of your distribution policies, but it might be worth considering enabling the Python bindings in the PMIx package.

Building the bindings requires Cython (in the standard locations for the Python being used) plus addition of the `--enable-python-bindings` configure option. It will generate an "egg" that is installed in the prefix location - this would have to be added to the rpm or whatever method you choose for distributing it.

**Comment by s-sajid-ali** [comment]
@rhc54  : I attempted to add a `python` variant to `PMIx` ([here](https://github.com/s-sajid-ali/spack/commit/16156a0beafae3b8b67ea0cfdea6182dab743ce1)) as per the above and hit the following error. Build logs are attached.

```
==> 8334: Installing pmix
==> Cloning git repository: https://github.com/openpmix/openpmix.git on branch master
==> No checksum needed when fetching with git
==> Already staged spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7 in /tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7
==> No patches needed for pmix
==> 8334: pmix: Building pmix [AutotoolsPackage]
==> 8334: pmix: Executing phase: 'autoreconf'
==> 8334: pmix: Executing phase: 'configure'
==> 8334: pmix: Executing phase: 'build'
==> 8334: pmix: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

1 error found in build log:
     2500    make[2]: Entering directory '/tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-src/bindings/python'
     2501    make[3]: Entering directory '/tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-src/bindings/python'
     2502    /home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4.0/python-3.7.7-346oribwjjj3s6juafsplkp7bgu35kgb/bin/python ../../bindings
             /python/construct.py --src="../../include"
     2503    make[3]: Nothing to be done for 'install-data-am'.
     2504    /home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4.0/python-3.7.7-346oribwjjj3s6juafsplkp7bgu35kgb/bin/python ../../bindings
             /python/setup.py build_ext --include-dirs="../../include" --library-dirs="/home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4
             .0/pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/lib" --user
     2505
  >> 2506    Error compiling Cython file:
     2507    ------------------------------------------------------------
     2508    ...
     2509    PMIX_GLOBAL                                = 3
     2510    PMIX_INTERNAL                              = 4
     2511    PMIX_RANGE_UNDEF                           = 0
     2512    PMIX_RANGE_RM                              = 1

See build log for details:
  /tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-build-out.txt

==> Error: Failed to install pmix due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'
1 error found in build log:
     2500    make[2]: Entering directory '/tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-src/bindings/python'
     2501    make[3]: Entering directory '/tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-src/bindings/python'
     2502    /home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4.0/python-3.7.7-346oribwjjj3s6juafsplkp7bgu35kgb/bin/python ../../bindings
             /python/construct.py --src="../../include"
     2503    make[3]: Nothing to be done for 'install-data-am'.
     2504    /home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4.0/python-3.7.7-346oribwjjj3s6juafsplkp7bgu35kgb/bin/python ../../bindings
             /python/setup.py build_ext --include-dirs="../../include" --library-dirs="/home/sajid/packages/spack/opt/spack/linux-centos8-broadwell/gcc-8.4
             .0/pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/lib" --user
     2505
  >> 2506    Error compiling Cython file:
     2507    ------------------------------------------------------------
     2508    ...
     2509    PMIX_GLOBAL                                = 3
     2510    PMIX_INTERNAL                              = 4
     2511    PMIX_RANGE_UNDEF                           = 0
     2512    PMIX_RANGE_RM                              = 1

See build log for details:
  /tmp/sajid/spack-stage/spack-stage-pmix-master-afalozxzahbo5xgnoesyg2gv5dda4cn7/spack-build-out.txt
Traceback (most recent call last):
  File "/home/sajid/packages/spack/lib/spack/spack/build_environment.py", line 823, in child_process
    return_value = function()
  File "/home/sajid/packages/spack/lib/spack/spack/installer.py", line 1133, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/sajid/packages/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/sajid/packages/spack/lib/spack/spack/build_systems/autotools.py", line 336, in install
    inspect.getmodule(self).make(*self.install_targets)
  File "/home/sajid/packages/spack/lib/spack/spack/build_environment.py", line 133, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/sajid/packages/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

[sajid@xrmlite ~]$
```

Note : The configure script shipped with release tarballs does not seem to support `--enable-python-bindings` which only works when building from git. 
```
[sajid@xrmlite pmix-3.1.5]$ pwd
/home/sajid/Downloads/temp/pmix-3.1.5
[sajid@xrmlite pmix-3.1.5]$ ./configure --help | grep python
[sajid@xrmlite pmix-3.1.5]$
```


[spack-build-env.txt](https://github.com/spack/spack/files/4826460/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4826461/spack-build-out.txt)

**Comment by rhc54** [comment]
Deeply sorry for the incredible delay. Between retiring and health issues, I'm afraid I allowed this to fall off my radar. However, increasing requests for the bindings has raised it to my attention again.

I checked the latest tarball (v4.2.2) and it does have the `--enable-python-bindings` option in configure. Not sure why the v3.1.5 tarball was lacking it, but perhaps we can focus on the v4.2.2 release for now?

In building the bindings, I hit some errors that have appeared since the last time I built them, so let me investigate that and return here once they are fixed.

**Comment by s-sajid-ali** [comment]
No worries about the delay and hope you're feeling better now! 

I tried the same recipe and I am now about to build for the `v4.1.2` release as shown below:
```
sasyed@MAC-140753 ~> spack find -ldv pmix+python
-- darwin-monterey-m1 / apple-clang@14.0.0 ----------------------
vszmjxl pmix@4.1.2~docs+pmi_backwards_compatibility+python~restful build_system=autotools
fsvx5od     gnuconfig@2021-08-14 build_system=generic
pwqg2uj     hwloc@2.8.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static
rwr3nyw         libxml2@2.10.1~python build_system=autotools
a3gjfoq             libiconv@1.16 build_system=autotools libs=shared,static
akymjsj         ncurses@6.3~symlinks+termlib abi=none build_system=autotools
3i2zrh5         pkgconf@1.8.0 build_system=autotools
aj3mi6a     libevent@2.1.12+openssl build_system=autotools
67ditao         openssl@1.1.1s~docs~shared build_system=generic certs=mozilla
swpxclg             ca-certificates-mozilla@2022-10-11 build_system=generic
t5axno4             perl@5.36.0+cpanm+shared+threads build_system=generic
rsuynw2                 berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc
jqexx2h     py-cython@0.29.32 build_system=python_pip
yhnfeal         py-pip@22.2.2 build_system=generic
rzyario         py-setuptools@65.5.0 build_system=generic
rpfednl         py-wheel@0.37.1 build_system=generic
x52og7f     python@3.10.8+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060
ulxrn4a         apple-libuuid@1353.100.2 build_system=bundle
o54nfsb         bzip2@1.0.8~debug~pic+shared build_system=generic
hg4szzn             diffutils@3.8 build_system=autotools
pvy5rr7         expat@2.4.8~libbsd build_system=autotools
wmvqarf         gdbm@1.23 build_system=autotools
mxkemt5         gettext@0.21.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools
y3lphic             tar@1.34 build_system=autotools zip=pigz
wajhg5a                 pigz@2.7 build_system=makefile
tnjjnod                 zstd@1.5.2+programs build_system=makefile compression=none libs=shared,static
ovc3aec         libffi@3.4.2 build_system=autotools
yjqmxgs         readline@8.1.2 build_system=autotools
ifckayw         sqlite@3.39.4+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools
taxyz2c         xz@5.2.7~pic build_system=autotools libs=shared,static
hbmwwdm         zlib@1.2.13+optimize+pic+shared build_system=makefile

==> 1 installed package
```
What should the lower bound of this feature be?

**Comment by rhc54** [comment]
Oh - that's fantastic! Let's just set it at v4.1.2 since we know that one works. I'm pushing people to update to the v4.2 series anyway, so that should be fine.

Thanks so much! I'll advise when I get v4.2.2 (well, it will be a v4.2.3 release to fix the buglets I found) ready to go.
