### ISSUE TITLE
Ripgrep won't install

### ISSUE THREAD

**Issue by hhoeflin** [LLNL/spack#17152]
I ran spack install ripgrep and am running into a failure related to llvm. Complete novice, sorry if doing something wrong. I also installed llvm, but does not help.

### Steps to reproduce the issue

```console
$ spack install ripgrep
```

### Error Message
```
==> 98346: Installing ripgrep
==> Error: KeyError: 'No spec with name llvm in ripgrep@11.0.2%gcc@6.4.0 arch=linux-centos7-haswell ^bzip2@1.0.8%gcc@6.4.0+shared arch=linux-centos7-haswell ^cmake@3.17.1%gcc@6.4.0~doc+ncurses+openssl+ownlibs~qt patches=1c540040c7e203dd8e27aa20345ecb07fe06570d56410a24a266ae570b1c4c39 arch=linux-centos7-haswell ^diffutils@3.7%gcc@6.4.0 arch=linux-centos7-haswell ^expat@2.2.9%gcc@6.4.0+libbsd arch=linux-centos7-haswell ^gdbm@1.18.1%gcc@6.4.0 arch=linux-centos7-haswell ^gettext@0.20.2%gcc@6.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-haswell ^gmake@4.2.1%gcc@6.4.0~guile+nls patches=ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f,fe5b60d091c33f169740df8cb718bf4259f84528b42435194ffe0dd5b79cd125 arch=linux-centos7-haswell ^libbsd@0.10.0%gcc@6.4.0 arch=linux-centos7-haswell ^libffi@3.3%gcc@6.4.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-centos7-haswell ^libgit2@1.0.1%gcc@6.4.0~curl+ssh build_type=RelWithDebInfo https=system arch=linux-centos7-haswell ^libiconv@1.16%gcc@6.4.0 arch=linux-centos7-haswell ^libssh2@1.8.0%gcc@6.4.0+shared build_type=RelWithDebInfo arch=linux-centos7-haswell ^libxml2@2.9.10%gcc@6.4.0~python arch=linux-centos7-haswell ^ncurses@6.2%gcc@6.4.0~symlinks+termlib arch=linux-centos7-haswell ^openssl@1.1.1g%gcc@6.4.0+systemcerts arch=linux-centos7-haswell ^perl@5.30.2%gcc@6.4.0+cpanm+shared+threads arch=linux-centos7-haswell ^pkgconf@1.7.3%gcc@6.4.0 arch=linux-centos7-haswell ^python@3.7.7%gcc@6.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-centos7-haswell ^readline@8.0%gcc@6.4.0 arch=linux-centos7-haswell ^rust@1.44.0%gcc@6.4.0+analysis+clippy~rls+rustfmt+src arch=linux-centos7-haswell ^sqlite@3.31.1%gcc@6.4.0+column_metadata+fts~functions~rtree arch=linux-centos7-haswell ^tar@1.32%gcc@6.4.0 arch=linux-centos7-haswell ^texinfo@6.5%gcc@6.4.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-centos7-haswell ^xz@5.2.5%gcc@6.4.0 arch=linux-centos7-haswell ^zlib@1.2.11%gcc@6.4.0+optimize+pic+shared arch=linux-centos7-haswell'

/home/hoeflho1/spack/var/spack/repos/builtin/packages/ripgrep/package.py:29, in setup_build_environment:
         27    def setup_build_environment(self, env):
         28        env.append_flags('LLVM_CONFIG_PATH',
  >>     29                         join_path(self.spec['llvm'].prefix.libexec.llvm,
         30                                   'llvm-config'))
         31        env.append_flags('LIBCLANG_PATH', self.spec['llvm'].prefix.lib)


==> Error: Failed to install ripgrep due to ChildError: KeyError: 'No spec with name llvm in ripgrep@11.0.2%gcc@6.4.0 arch=linux-centos7-haswell ^bzip2@1.0.8%gcc@6.4.0+shared arch=linux-centos7-haswell ^cmake@3.17.1%gcc@6.4.0~doc+ncurses+openssl+ownlibs~qt patches=1c540040c7e203dd8e27aa20345ecb07fe06570d56410a24a266ae570b1c4c39 arch=linux-centos7-haswell ^diffutils@3.7%gcc@6.4.0 arch=linux-centos7-haswell ^expat@2.2.9%gcc@6.4.0+libbsd arch=linux-centos7-haswell ^gdbm@1.18.1%gcc@6.4.0 arch=linux-centos7-haswell ^gettext@0.20.2%gcc@6.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-haswell ^gmake@4.2.1%gcc@6.4.0~guile+nls patches=ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f,fe5b60d091c33f169740df8cb718bf4259f84528b42435194ffe0dd5b79cd125 arch=linux-centos7-haswell ^libbsd@0.10.0%gcc@6.4.0 arch=linux-centos7-haswell ^libffi@3.3%gcc@6.4.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-centos7-haswell ^libgit2@1.0.1%gcc@6.4.0~curl+ssh build_type=RelWithDebInfo https=system arch=linux-centos7-haswell ^libiconv@1.16%gcc@6.4.0 arch=linux-centos7-haswell ^libssh2@1.8.0%gcc@6.4.0+shared build_type=RelWithDebInfo arch=linux-centos7-haswell ^libxml2@2.9.10%gcc@6.4.0~python arch=linux-centos7-haswell ^ncurses@6.2%gcc@6.4.0~symlinks+termlib arch=linux-centos7-haswell ^openssl@1.1.1g%gcc@6.4.0+systemcerts arch=linux-centos7-haswell ^perl@5.30.2%gcc@6.4.0+cpanm+shared+threads arch=linux-centos7-haswell ^pkgconf@1.7.3%gcc@6.4.0 arch=linux-centos7-haswell ^python@3.7.7%gcc@6.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-centos7-haswell ^readline@8.0%gcc@6.4.0 arch=linux-centos7-haswell ^rust@1.44.0%gcc@6.4.0+analysis+clippy~rls+rustfmt+src arch=linux-centos7-haswell ^sqlite@3.31.1%gcc@6.4.0+column_metadata+fts~functions~rtree arch=linux-centos7-haswell ^tar@1.32%gcc@6.4.0 arch=linux-centos7-haswell ^texinfo@6.5%gcc@6.4.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-centos7-haswell ^xz@5.2.5%gcc@6.4.0 arch=linux-centos7-haswell ^zlib@1.2.11%gcc@6.4.0+optimize+pic+shared arch=linux-centos7-haswell'
/home/hoeflho1/spack/var/spack/repos/builtin/packages/ripgrep/package.py:29, in setup_build_environment:
         27    def setup_build_environment(self, env):
         28        env.append_flags('LLVM_CONFIG_PATH',
  >>     29                         join_path(self.spec['llvm'].prefix.libexec.llvm,
         30                                   'llvm-config'))
         31        env.append_flags('LIBCLANG_PATH', self.spec['llvm'].prefix.lib)

Traceback (most recent call last):
  File "/home/hoeflho1/spack/lib/spack/spack/spec.py", line 3180, in __getitem__
    (x for x in self.traverse()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoeflho1/spack/lib/spack/spack/build_environment.py", line 818, in child_process
    setup_package(pkg, dirty=dirty)
  File "/home/hoeflho1/spack/lib/spack/spack/build_environment.py", line 707, in setup_package
    pkg.setup_build_environment(build_env)
  File "/home/hoeflho1/spack/var/spack/repos/builtin/packages/ripgrep/package.py", line 30, in setup_build_environment
    'llvm-config'))
  File "/home/hoeflho1/spack/lib/spack/spack/spec.py", line 3185, in __getitem__
    raise KeyError("No spec with name %s in %s" % (name, self))
KeyError: 'No spec with name llvm in ripgrep@11.0.2%gcc@6.4.0 arch=linux-centos7-haswell ^bzip2@1.0.8%gcc@6.4.0+shared arch=linux-centos7-haswell ^cmake@3.17.1%gcc@6.4.0~doc+ncurses+openssl+ownlibs~qt patches=1c540040c7e203dd8e27aa20345ecb07fe06570d56410a24a266ae570b1c4c39 arch=linux-centos7-haswell ^diffutils@3.7%gcc@6.4.0 arch=linux-centos7-haswell ^expat@2.2.9%gcc@6.4.0+libbsd arch=linux-centos7-haswell ^gdbm@1.18.1%gcc@6.4.0 arch=linux-centos7-haswell ^gettext@0.20.2%gcc@6.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-haswell ^gmake@4.2.1%gcc@6.4.0~guile+nls patches=ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f,fe5b60d091c33f169740df8cb718bf4259f84528b42435194ffe0dd5b79cd125 arch=linux-centos7-haswell ^libbsd@0.10.0%gcc@6.4.0 arch=linux-centos7-haswell ^libffi@3.3%gcc@6.4.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-centos7-haswell ^libgit2@1.0.1%gcc@6.4.0~curl+ssh build_type=RelWithDebInfo https=system arch=linux-centos7-haswell ^libiconv@1.16%gcc@6.4.0 arch=linux-centos7-haswell ^libssh2@1.8.0%gcc@6.4.0+shared build_type=RelWithDebInfo arch=linux-centos7-haswell ^libxml2@2.9.10%gcc@6.4.0~python arch=linux-centos7-haswell ^ncurses@6.2%gcc@6.4.0~symlinks+termlib arch=linux-centos7-haswell ^openssl@1.1.1g%gcc@6.4.0+systemcerts arch=linux-centos7-haswell ^perl@5.30.2%gcc@6.4.0+cpanm+shared+threads arch=linux-centos7-haswell ^pkgconf@1.7.3%gcc@6.4.0 arch=linux-centos7-haswell ^python@3.7.7%gcc@6.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-centos7-haswell ^readline@8.0%gcc@6.4.0 arch=linux-centos7-haswell ^rust@1.44.0%gcc@6.4.0+analysis+clippy~rls+rustfmt+src arch=linux-centos7-haswell ^sqlite@3.31.1%gcc@6.4.0+column_metadata+fts~functions~rtree arch=linux-centos7-haswell ^tar@1.32%gcc@6.4.0 arch=linux-centos7-haswell ^texinfo@6.5%gcc@6.4.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-centos7-haswell ^xz@5.2.5%gcc@6.4.0 arch=linux-centos7-haswell ^zlib@1.2.11%gcc@6.4.0+optimize+pic+shared arch=linux-centos7-haswell'
```
```console
$ spack --debug --stacktrace <command>
```

### Information on your system

vanilla spack installation with no changes from initial install.
```
~> spack debug report
* **Spack:** 0.14.2-1465-ad18933ef
* **Python:** 3.4.8
* **Platform:** linux-centos7-haswell
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
There's possibly an error in the recipe. Can you check if `ripgrep` is supposed to depend on `llvm`? That dependency isn't encoded in `package.py` currently.

**Comment by alalazo** [comment]
@ax3l

**Comment by hartzell** [comment]
One of the cartons that ripgrep loads is/was onig_sys, which tries/tried to use llvm-config as part of compiling the oniguruma [SIC?] library.  There's a bit of discussion about it in an issue centered around bat, https://github.com/spack/spack/issues/16298.

I believe that something's changed, I've had luck at work (still working through the process to get approval to push stuff out...) just deleting that entire `setup_build_environment` function in the ripgrep package.

It's worth a try, and/or a look upstream at ripgrep to see if/what they've changed.

**Comment by ax3l** [comment]
@alalazo I wish I knew more, I just assisted @hartzell by merging #15343 :D

**Comment by hartzell** [comment]
Note that @AndrewGaspar's big rust cleanup includes a bit that deletes the llvm dependency:

https://github.com/spack/spack/pull/16185/files#diff-0fe83e4d90bf103731e9cb531114778cL28-L31

(That link doesn't work that well....  Search down through the PR for ripgrep/package.py and notice the deletion of L28-L31)

**Comment by AndrewGaspar** [comment]
Yeah, I removed all but the most recent versions of each Rust package (we can change this if desired), and, as noted, it no longer requires llvm to build.

**Comment by hhoeflin** [comment]
Thanks for this - will this be merged soon?

**Comment by accopeland** [comment]
Same issue on spack v0.18 and applying hartzell's solution (deleting that entire setup_build_environment function in the ripgrep package.) also worked for me on Rocky Linux release 8.6 (Green Obsidian)
