### ISSUE TITLE
"spack install" command core-dumps while installing a particular package within a hybrid Spack environment

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#17238]
### Steps to reproduce the issue

Our site has a complex code with many dependencies. In the past we've generally stuck to compiling with Intel or GCC on an x86_64 architecture, but we are attempting to expand our reach onto more platforms and toolchains. Case in point:  the IBM XL 16.1.1 compiler and Spectrum MPI.

Because it's proven impossible to build out the entire dependency tree using XL, we've adopted a hybrid approach that consists of two anonymous Spack environments, with a structure like this:

```console
|-- ENV
|   |-- common
|   |   |-- config.yaml
|   |   |-- mirrors.yaml
|   |   |-- modules.yaml
|   |   |-- repos.yaml
|   |-- GCC
|   |   |-- compilers.yaml
|   |   |-- packages.yaml
|   |   |-- spack.yaml
|   |-- XL
|       |-- compilers.yaml
|       |-- packages.yaml
|       |-- spack.yaml
|-- spack
|   |-- bin
|   |-- CHANGELOG.md
|   |-- COPYRIGHT
.
.
.
|-- local-spack-repo.
|   |-- packages
|   |-- README.md
.
.
.
```

The two directories "GCC" and "XL" contain environment-specific information (compilers, packages to install, etc.), while the directory "common" contains files that are referenced by all environments. In practice, we do this:

1. Activate a Spack environment and build all the packages we possibly can with GCC 9.2.0:
```console
$ spack env activate -d ./ENV/GCC/
$ spack env status
==> In environment /projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/ENV/GCC

$ spack concretize
$ spack install -v
.
.
.
$ spack env loads 
$ spack env deactivate
```

2. Amend the XL environment's `packages.yaml` so that it loads all possible dependencies from the GCC environment, e.g.:

```console
 trilinos:
    buildable: False
    modules:
      trilinos@12.18.1: trilinos/12.18.1-gcc-9.2.0-iaq2qoo
    variants: ['+amesos2', '~muelu', '~mumps', '+nox', '~suite-sparse', '+superlu-dist']
```
3. Repeat Step 1 for the XL environment

### Error Message

The above approach works well up until we hit a particular homegrown package, shapo. When we activate our XL environment and attempt to install it, spack errors out with:

```console
==> Error: Failed to install shapo due to ChildError: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/build_environment.py:830, in child_process:
        827            tb_string = traceback.format_exc()
        828
        829            # build up some context from the offending package so we can
  >>    830            # show that, too.
        831            package_context = get_package_context(tb)
        832
        833            build_log = None

Traceback (most recent call last):
  File "/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/build_environment.py", line 812, in child_process
    setup_package(pkg, dirty=dirty)
  File "/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/build_environment.py", line 734, in setup_package
    load_external_modules(pkg)
  File "/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/build_environment.py", line 682, in load_external_modules
    load_module(dep.external_module)
  File "/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/util/module_cmd.py", line 109, in load_module
    module('load', mod)
  File "/projects/shavano/dev/quellyn/dw/DWP9X/spack-environments/DWP9X_16.1.1/1.0/spack/lib/spack/spack/util/module_cmd.py", line 72, in module
    env_dict = json.loads(env_json)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

[shapo-install-debug.xl_r.txt](https://github.com/spack/spack/files/4827894/shapo-install-debug.xl_r.txt)

I can install this same package within the GCC environment without issue. But inside the XL environment, Spack doesn't even complete the staging portion of the shapo source.

I should also say that I have a nearly identical setup with GCC 9.2.0 and PGI 19.7, and the same error occurs there when I try to build shapo under PGI.

Can someone give me some pointers on how to troubleshoot this?

Thanks!
Quellyn

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2-1284-de63e1c2a
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
```

[ENV.tar.gz](https://github.com/spack/spack/files/4827914/ENV.tar.gz)

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by quellyn** [comment]
We've observed this same error (`JSONDecodeError`) on other packages -- but only on systems that have an older default Python installation (e.g., RHEL7, Python 3.6.8). If we load a newer Python (3.7.2), then this issue goes away.

Given that we have a workaround, and eventually the systems in question will retire or be upgraded, I'm closing this.
