### ISSUE TITLE
buildcache for foreign architecture no longer readable

### ISSUE THREAD

**Issue by frankwillmore** [LLNL/spack#17469]
I generated a buildcache with cnl7 (alcf iota), copied the mirror to a cnl6 system (alcf theta) and tried to list packages.
When building the cache with spack v0.14.2, I was able to view the packages, but not install. When building with v0.15.0, I am neither able to view nor install. 

### Steps to reproduce the issue

```console
熊俊傑@thetalogin1:~/spack$ git checkout v0.14.2
HEAD is now at 7a68a4d85... update CHANGELOG.md for 0.14.2
熊俊傑@thetalogin1:~/spack$ spack buildcache list -al arch=cray-cnl7-mic_knl 
==> Finding buildcaches in /home/willmore/mirror/build_cache
==> Finding buildcaches in /tmp/mirror/build_cache
==> Finding buildcaches in /tmp/build_cache
==> Finding buildcaches in /home/willmore/spack-mirror/build_cache
-- cray-cnl7-mic_knl / gcc@7.3.0 --------------------------------
jscdp26 hdf5@1.10.6  ek675oc zlib@1.2.11

-- cray-cnl7-mic_knl / gcc@9.2.0 --------------------------------
bl5unjg hdf5@1.8.16  zjoxq7c kokkos@3.1.01   zmjwtet zlib@1.2.11
4b3p7v2 hdf5@1.10.6  4itl6jz numactl@2.0.12
熊俊傑@thetalogin1:~/spack$ git checkout v0.15.0
Previous HEAD position was 7a68a4d85... update CHANGELOG.md for 0.14.2
HEAD is now at d4bf70d98... changelog for v0.15.0
熊俊傑@thetalogin1:~/spack$ spack buildcache list -al arch=cray-cnl7-mic_knl 
==> Finding buildcaches at file:///home/willmore/mirror/build_cache
==> Error: Can't recreate arch for spec cray-cnl7-mic_knl on current arch cray-cnl6-haswell; spec architecture is too different
```

tgamblin:
it’s complaining about the OS difference so I believe it should work fine after the upgrade but that’s not great — you want it to list and show what’s there regardless of the host OS right? 

willmore:
yes. It looks like the -o option [for buildcache install] came with v0.15.0 so I upgraded, but I could at least list the packages with the v0.14.2.

### Information on your system

熊俊傑@thetalogin1:~/spack$ spack debug report
* **Spack:** 0.15.0
* **Python:** 3.4.6
* **Platform:** cray-sles12-haswell

(This is not the correct target architecture,which should reflectr mic_knl instead of haswell; this also changed since v0.14.2 and reported in issue #16707) 

### Debug output
```
熊俊傑@thetalogin1:~/spack$ spack -d buildcache list -al arch=cray-cnl7-mic_knl 
==> [2020-07-10-22:47:52.140418, 32101] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
==> [2020-07-10-22:47:52.145034, 32101] default to front-end architecture
==> [2020-07-10-22:47:52.187344, 32101] Imported buildcache from built-in commands
==> [2020-07-10-22:47:52.190937, 32101] Imported buildcache from built-in commands
==> [2020-07-10-22:47:52.191575, 32101] Reading config file /home/willmore/.spack/cray/mirrors.yaml
==> [2020-07-10-22:47:52.195722, 32101] Finding buildcaches at file:///home/willmore/mirror/build_cache
==> [2020-07-10-22:47:52.196035, 32101] Reading config file /gpfs/mira-home/willmore/spack/etc/spack/defaults/config.yaml
==> [2020-07-10-22:47:52.219533, 32101] DATABASE LOCK TIMEOUT: 3s
==> [2020-07-10-22:47:52.219589, 32101] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-07-10-22:47:52.290808, 32101] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
==> [2020-07-10-22:47:52.294602, 32101] default to front-end architecture
Traceback (most recent call last):
  File "/home/willmore/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/main.py", line 761, in main
    return _invoke_command(command, parser, args, unknown)
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/main.py", line 489, in _invoke_command
    return_val = command(parser, args)
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/cmd/buildcache.py", line 756, in buildcache
    args.func(args)
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/cmd/buildcache.py", line 491, in listspecs
    specs = bindist.get_specs(args.allarch)
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/binary_distribution.py", line 888, in get_specs
    spec_arch = architecture.arch_for_spec(indexed_spec.architecture)
  File "/gpfs/mira-home/willmore/spack/lib/spack/spack/architecture.py", line 476, in arch_for_spec
    "spec architecture is too different" % (arch_spec, sys_type()))
ValueError: Can't recreate arch for spec cray-cnl7-mic_knl on current arch cray-cnl6-haswell; spec architecture is too different
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by gartung** [comment]
This functionality was removed with the switch to inxex.json
https://github.com/spack/spack/pull/15002

**Comment by gartung** [comment]
@scottwittenburg
