### ISSUE TITLE
Installation issue: flang [llvm-flang clang++ can't find libstdc++ from GCC@9.3.0]

### ISSUE THREAD

**Issue by owainkenwayucl** [LLNL/spack#17557]
On our systems, installing `flang` fails because `clang++` from llvm-flang can't find libstdc++ when run through `cmake`.  Outside of `cmake` it can comfortably build C++ binaries.

### Steps to reproduce the issue

*(With a completely clean checkout of spack, cleared out ~/.spack etc)*

```console
$ spack install gcc@9.3.0
...
(load the gcc module)
$ spack compiler find
...
$ spack install flang%gcc@9.3.0
...
==> 3200: flang: Building flang [CMakePackage]
==> 3200: flang: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib64;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/hwloc-2.2.0-3a7dynrtd4gviwoy3rdug4yfeqmfx7bg/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libpciaccess-0.13.5-zrabhv3blezuen6f2u7ygcnd36zjghvu/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libxml2-2.9.10-disjrhzhml66h7rgd2xhghr36hovtrzq/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libiconv-1.16-q6ijt4fwluabo4kgg2cbtwuzvyscwqnv/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/xz-5.2.5-lqz2e3d3yr75ozfybiv5evuj2cqgjxuz/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/zlib-1.2.11-4bfingovokhjb46k463vlfh235ne2frl/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri/lib' '-DCMAKE_PREFIX_PATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbpspzvfvyv2' '-DWITH_WERROR=OFF' '-DCMAKE_C_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang' '-DCMAKE_CXX_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++' '-DCMAKE_Fortran_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/flang' '-DFLANG_LIBOMP=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib/libomp.so' '-DPYTHON_EXECUTABLE=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg/bin/python3.7' '-DFLANG_OPENMP_GPU_NVIDIA=OFF' '/tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-src'

5 errors found in build log:
     7     -- Detecting C compiler ABI info
     8     -- Detecting C compiler ABI info - done
     9     -- Detecting C compile features
     10    -- Detecting C compile features - done
     11    -- Check for working CXX compiler: /scratch/home/uccaoke/Source/spac
           k-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190
           329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++
     12    -- Check for working CXX compiler: /scratch/home/uccaoke/Source/spac
           k-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190
           329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++ - broken
  >> 13    CMake Error at /scratch/home/uccaoke/Source/spack-example/opt/spack/
           linux-rhel7-broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbp
           spzvfvyv2/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (me
           ssage):
     14      The C++ compiler
     15    
     16        "/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel
           7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev3
           56cpge/bin/clang++"
     17    
     18      is not able to compile a simple test program.
     19    

     ...

     25        gmake[1]: Entering directory `/tmp/uccaoke/spack-stage/spack-sta
           ge-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build/CMake
           Files/CMakeTmp'
     26        Building CXX object CMakeFiles/cmTC_0eb7c.dir/testCXXCompiler.cx
           x.o
     27        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev35
           6cpge/bin/clang++     -o CMakeFiles/cmTC_0eb7c.dir/testCXXCompiler.c
           xx.o -c /tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mheco
           p3a2achd4ecmzz3ja7mlfyix/spack-build/CMakeFiles/CMakeTmp/testCXXComp
           iler.cxx
     28        Linking CXX executable cmTC_0eb7c
     29        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbpspzvfvyv2/b
           in/cmake -E cmake_link_script CMakeFiles/cmTC_0eb7c.dir/link.txt --v
           erbose=1
     30        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev35
           6cpge/bin/clang++       -rdynamic CMakeFiles/cmTC_0eb7c.dir/testCXXC
           ompiler.cxx.o  -o cmTC_0eb7c
  >> 31    ld: cannot find -lstdc++
  >> 32        clang-7: error: linker command failed with exit code 1 (use -v t
           o see invocation)
  >> 33        gmake[1]: *** [cmTC_0eb7c] Error 1
     34        gmake[1]: Leaving directory `/tmp/uccaoke/spack-stage/spack-stag
           e-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build/CMakeF
           iles/CMakeTmp'
  >> 35        gmake: *** [cmTC_0eb7c/fast] Error 2
     36    
     37    
     38    
     39    
     40    
     41      CMake will not be able to correctly generate this project.

See build log for details:
  /tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build-out.txt

==> Error: Failed to install flang due to ChildError: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib64;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/hwloc-2.2.0-3a7dynrtd4gviwoy3rdug4yfeqmfx7bg/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libpciaccess-0.13.5-zrabhv3blezuen6f2u7ygcnd36zjghvu/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libxml2-2.9.10-disjrhzhml66h7rgd2xhghr36hovtrzq/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libiconv-1.16-q6ijt4fwluabo4kgg2cbtwuzvyscwqnv/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/xz-5.2.5-lqz2e3d3yr75ozfybiv5evuj2cqgjxuz/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/zlib-1.2.11-4bfingovokhjb46k463vlfh235ne2frl/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri/lib' '-DCMAKE_PREFIX_PATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbpspzvfvyv2' '-DWITH_WERROR=OFF' '-DCMAKE_C_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang' '-DCMAKE_CXX_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++' '-DCMAKE_Fortran_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/flang' '-DFLANG_LIBOMP=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib/libomp.so' '-DPYTHON_EXECUTABLE=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg/bin/python3.7' '-DFLANG_OPENMP_GPU_NVIDIA=OFF' '/tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-src'
5 errors found in build log:
     7     -- Detecting C compiler ABI info
     8     -- Detecting C compiler ABI info - done
     9     -- Detecting C compile features
     10    -- Detecting C compile features - done
     11    -- Check for working CXX compiler: /scratch/home/uccaoke/Source/spac
           k-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190
           329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++
     12    -- Check for working CXX compiler: /scratch/home/uccaoke/Source/spac
           k-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190
           329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++ - broken
  >> 13    CMake Error at /scratch/home/uccaoke/Source/spack-example/opt/spack/
           linux-rhel7-broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbp
           spzvfvyv2/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (me
           ssage):
     14      The C++ compiler
     15    
     16        "/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel
           7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev3
           56cpge/bin/clang++"
     17    
     18      is not able to compile a simple test program.
     19    

     ...

     25        gmake[1]: Entering directory `/tmp/uccaoke/spack-stage/spack-sta
           ge-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build/CMake
           Files/CMakeTmp'
     26        Building CXX object CMakeFiles/cmTC_0eb7c.dir/testCXXCompiler.cx
           x.o
     27        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev35
           6cpge/bin/clang++     -o CMakeFiles/cmTC_0eb7c.dir/testCXXCompiler.c
           xx.o -c /tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mheco
           p3a2achd4ecmzz3ja7mlfyix/spack-build/CMakeFiles/CMakeTmp/testCXXComp
           iler.cxx
     28        Linking CXX executable cmTC_0eb7c
     29        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbpspzvfvyv2/b
           in/cmake -E cmake_link_script CMakeFiles/cmTC_0eb7c.dir/link.txt --v
           erbose=1
     30        /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7
           -broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev35
           6cpge/bin/clang++       -rdynamic CMakeFiles/cmTC_0eb7c.dir/testCXXC
           ompiler.cxx.o  -o cmTC_0eb7c
  >> 31    ld: cannot find -lstdc++
  >> 32        clang-7: error: linker command failed with exit code 1 (use -v t
           o see invocation)
  >> 33        gmake[1]: *** [cmTC_0eb7c] Error 1
     34        gmake[1]: Leaving directory `/tmp/uccaoke/spack-stage/spack-stag
           e-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build/CMakeF
           iles/CMakeTmp'
  >> 35        gmake: *** [cmTC_0eb7c/fast] Error 2
     36    
     37    
     38    
     39    
     40    
     41      CMake will not be able to correctly generate this project.

See build log for details:
  /tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-build-out.txt
Traceback (most recent call last):
  File "/scratch/home/uccaoke/Source/spack-example/lib/spack/spack/build_environment.py", line 846, in child_process
    return_value = function()
  File "/scratch/home/uccaoke/Source/spack-example/lib/spack/spack/installer.py", line 1145, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/scratch/home/uccaoke/Source/spack-example/lib/spack/spack/package.py", line 109, in phase_wrapper
    phase(spec, prefix)
  File "/scratch/home/uccaoke/Source/spack-example/lib/spack/spack/build_systems/cmake.py", line 338, in cmake
    inspect.getmodule(self).cmake(*options)
  File "/scratch/home/uccaoke/Source/spack-example/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/lib64;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/hwloc-2.2.0-3a7dynrtd4gviwoy3rdug4yfeqmfx7bg/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libpciaccess-0.13.5-zrabhv3blezuen6f2u7ygcnd36zjghvu/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libxml2-2.9.10-disjrhzhml66h7rgd2xhghr36hovtrzq/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/libiconv-1.16-q6ijt4fwluabo4kgg2cbtwuzvyscwqnv/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/xz-5.2.5-lqz2e3d3yr75ozfybiv5evuj2cqgjxuz/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/zlib-1.2.11-4bfingovokhjb46k463vlfh235ne2frl/lib;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri/lib' '-DCMAKE_PREFIX_PATH:STRING=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/pgmath-20190329-76x7pu5bwmave7lzokzhd6yyx6sezwri;/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/cmake-3.17.3-rvovftuse7bkwgk6o22onbpspzvfvyv2' '-DWITH_WERROR=OFF' '-DCMAKE_C_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang' '-DCMAKE_CXX_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++' '-DCMAKE_Fortran_COMPILER=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/flang' '-DFLANG_LIBOMP=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/lib/libomp.so' '-DPYTHON_EXECUTABLE=/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-to7yawiia3pyzsoi7xv4fs74t6zukulg/bin/python3.7' '-DFLANG_OPENMP_GPU_NVIDIA=OFF' '/tmp/uccaoke/spack-stage/spack-stage-flang-20190329-ie4mhecop3a2achd4ecmzz3ja7mlfyix/spack-src'


```

### Information on your system

* **Spack:** 0.15.1
* **Python:** 2.7.5
* **Platform:** linux-rhel7-broadwell

Our "default" GCC is an install of GCC 4.9.2 in `/shared/ucl/apps/gcc/4.9.2/`

I have a pull request https://github.com/spack/spack/pull/17480 which resolves this in a hacky way by passing the path to GCC 9.3.0's `lib64` directory through cmake.

Here is `compilers.yaml` after I've added GCC 9.3.0 from Spack to it in the second step above:

```yaml
compilers:
- compiler:
    paths:
      cc: /shared/ucl/apps/gcc/4.9.2/bin/gcc
      cxx: /shared/ucl/apps/gcc/4.9.2/bin/g++
      f77: /shared/ucl/apps/gcc/4.9.2/bin/gfortran
      fc: /shared/ucl/apps/gcc/4.9.2/bin/gfortran
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.9.2
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx:
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
- compiler:
    paths:
      cc: /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-4.9.2/gcc-9.3.0-kpzynjjb7p6y5lsnogtwvo3c7y45x2hk/bin/gcc
      cxx: /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-4.9.2/gcc-9.3.0-kpzynjjb7p6y5lsnogtwvo3c7y45x2hk/bin/g++
      f77: /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-4.9.2/gcc-9.3.0-kpzynjjb7p6y5lsnogtwvo3c7y45x2hk/bin/gfortran
      fc: /scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-4.9.2/gcc-9.3.0-kpzynjjb7p6y5lsnogtwvo3c7y45x2hk/bin/gfortran
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@9.3.0
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4931967/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4932011/spack-build-env.txt) *- note I've redacted parts of this*

The package maintainer is @naromero77

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by owainkenwayucl** [comment]
Just to prove that this is something weird going only inside cmake, compiling [a simple C++ program](https://github.com/UCL-RITS/pi_examples/blob/master/cpp_pi_dir/calculate_pi.cpp) with `clang++` from llvm-flang:

```console
$ module load llvm-flang-20190329-gcc-9.3.0-e3tkdt7
$ which clang++
/scratch/home/uccaoke/Source/spack-example/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/llvm-flang-20190329-e3tkdt7bfxr6i3vaz5vozuoev356cpge/bin/clang++
$ clang++ -o pi_clang calculate_pi.cpp 
$ ./pi_clang
Calculating PI using:
  1000000000 slices
  1 process
Obtained value for PI: 3.1415926535899708
Time taken: 3.8966590000000001 seconds
```

**Comment by naromero77** [comment]
Thanks. Give me a couple of days to work on this.

**Comment by naromero77** [comment]
Thanks for reporting the problem. I was unable to reproduce it on my system locally. This does not mean the problem is not there, and I do believe that this is a real problem for you.

Based on a hunch, instead of passing that extra flag to `-DCMAKE_CXX_FLAGS`, give this patch a try:
```
diff --git a/var/spack/repos/builtin/packages/flang/package.py b/var/spack/repos/builtin/packages/flang/package.py
index f0f49ae50..2d435eed6 100644
--- a/var/spack/repos/builtin/packages/flang/package.py
+++ b/var/spack/repos/builtin/packages/flang/package.py
@@ -71,6 +71,10 @@ def cmake_args(self):
                 spec['python'].command.path)
         ]
 
+        if self.compiler.name == "gcc":
+            gcc_prefix = ancestor(self.compiler.cc, 2)
+            options.append('-DGCC_INSTALL_PREFIX=' + gcc_prefix)
+
         if '+cuda' in spec:
             options.append('-DFLANG_OPENMP_GPU_NVIDIA=ON')
         else:
```

**Comment by owainkenwayucl** [comment]
Unfortunately that didn't solve the problem.

I combined our two methods though to this which worked:

```diff
--- package.py.orig     2020-07-20 09:57:19.000000000 +0100
+++ package.py  2020-07-20 10:01:44.000000000 +0100
@@ -71,6 +71,11 @@
                 spec['python'].command.path)
         ]
 
+        if self.compiler.name == "gcc":
+            gcc_prefix = ancestor(self.compiler.cc, 2)
+            options.append('-DCMAKE_CXX_FLAGS=-L%s' % os.path.join(
+               gcc_prefix, 'lib64'))
+
         if '+cuda' in spec:
             options.append('-DFLANG_OPENMP_GPU_NVIDIA=ON')
         else:
```

**Comment by naromero77** [comment]
Can you spell out how you are loading the GCC module? (It should NOT be necessary, but knowing the details may help with reproducing the error).

```
$ spack install gcc@9.3.0
...
(load the gcc module)
$ spack compiler find
```

Basically, clarify the steps between the first and second spack commands above.

**Comment by naromero77** [comment]
I am also adding Tom Scogland @trws . Even though this is not the main `llvm` package, he may have some insight into this issue.

**Comment by owainkenwayucl** [comment]
The normal way so:

```
$ module use --append /home/uccaoke/Source/spack-example/share/spack/modules/linux-rhel7-broadwell/
$ module load gcc-9.3.0-gcc-4.9.2-kpzynjj
```

**Comment by owainkenwayucl** [comment]
I should point out it's something that's revealed specifically on our clusters.  I also have access to machines at UCL run by the Computer Science department which don't exhibit this - I wonder if it's visible due to the skeleton install of the OS we deploy.  

A good example of the minimal nature of this is that there is no g++ 4.8.5 binary from the RHEL system install as you can see in the `compilers.yaml` file:

```yaml
...
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx:
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
...
```

(there is a `libstdc++.so` though - I looked)

But on the other hand I feel on the user side it should be picking up `libstdc++` from the GCC 9.3.0 install which would be the expected behaviour.  If that makes sense.

**Comment by naromero77** [comment]
If you skip the `module use ...` and `module load ...`, do you still have the same issue?

**Comment by naromero77** [comment]
As a last attempt to fix the issue without injecting additional flags into `-DCMAKE_CXX_FLAGS`, could you please add the patch below to BOTH `llvm-flang` and the `flang` package:
> Thanks for reporting the problem. I was unable to reproduce it on my system locally. This does not mean the problem is not there, and I do believe that this is a real problem for you.
> 
> Based on a hunch, instead of passing that extra flag to `-DCMAKE_CXX_FLAGS`, give this patch a try:
> 
> ```
> diff --git a/var/spack/repos/builtin/packages/flang/package.py b/var/spack/repos/builtin/packages/flang/package.py
> index f0f49ae50..2d435eed6 100644
> --- a/var/spack/repos/builtin/packages/flang/package.py
> +++ b/var/spack/repos/builtin/packages/flang/package.py
> @@ -71,6 +71,10 @@ def cmake_args(self):
>                  spec['python'].command.path)
>          ]
>  
> +        if self.compiler.name == "gcc":
> +            gcc_prefix = ancestor(self.compiler.cc, 2)
> +            options.append('-DGCC_INSTALL_PREFIX=' + gcc_prefix)
> +
>          if '+cuda' in spec:
>              options.append('-DFLANG_OPENMP_GPU_NVIDIA=ON')
>          else:
> ```

Thank you for your patience.

**Comment by owainkenwayucl** [comment]
> If you skip the `module use ...` and `module load ...`, do you still have the same issue?

It happens regardless of whether the modules are loaded or not (once GCC 9.3.0 in `compilers.yaml`.  I just had those is as steps as from a clean install of spack (if that makes sense).

I'll test the patch above and get back to you.

**Comment by owainkenwayucl** [comment]
I *believe* making the change to `llvm-flang` (obviously replacing `options` with `args`) has fixed it - I'm just doing a complete rebuild to be sure.

Once i've done that I'll amend the pull request.

(re patience, don't worry, I'd rather have a good solution rather than a fast one).

**Comment by owainkenwayucl** [comment]
The patch has been merged in so I'm closing this issue - thanks for the help getting this fixed.
