### ISSUE TITLE
Installation issue: netlib-scalapack and trilinos

### ISSUE THREAD

**Issue by biri1987** [LLNL/spack#17713]
Hi,

I'm really new in Spack and I'm trying to install Trilinos on my macOS machine (Catalina 10.15.6) without success. The installation fails when netlib-scalapack has to be installed. 

Do you have any suggestion?

Thank you in advance for all your help,
Gabriele

### Steps to reproduce the issue

```console
$ spack install trilinos
==> Warning: apple-clang@11.0.0 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> 65338: Installing netlib-scalapack
==> Finding buildcaches at https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/darwin-catalina-x86_64-apple-clang-11.0.0-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk.spec.yaml
curl: (22) The requested URL returned error: 404 Not Found                                                                                                       

==> Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/darwin-catalina-x86_64-apple-clang-11.0.0-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk.spec.yaml
    URL https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/darwin-catalina-x86_64-apple-clang-11.0.0-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk.spec.yaml was not found!
==> Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/darwin-catalina-x86_64-apple-clang-11.0.0-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk.spec.yaml failed.
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.0 for further details]
==> Using cached archive: /Users/gabriele/spack/var/spack/cache/_source-cache/archive/61/61d9216cf81d246944720cfce96255878a3f85dec13b9351f1fa0fd6768220a6.tgz
==> Staging archive: /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/spack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk/scalapack-2.1.0.tgz
==> Created stage in /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/spack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk
==> Applied patch /Users/gabriele/spack/var/spack/repos/builtin/packages/netlib-scalapack/int_overflow.patch
==> 65338: netlib-scalapack: Building netlib-scalapack [CMakePackage]
==> 65338: netlib-scalapack: Executing phase: 'cmake'
==> 65338: netlib-scalapack: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     2848    
     2849      775 |             CALL IGEBR2D( ONEDCONTEXT, 'ALL', ' ', 1, 1, TORECV, 1, 0,
     2850          |                                                         2
     2851    ......
     2852      778 |                CALL IGEBR2D( ONEDCONTEXT, 'ALL', ' ', TORECV, 1, IWORK,
     2853          |                                                                 1
  >> 2854    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
  >> 2855    make[2]: *** [CMakeFiles/scalapack.dir/SRC/psstebz.f.o] Error 1
     2856    make[2]: *** Waiting for unfinished jobs....
     2857    2 warnings generated.
     2858    [ 33%] Building Fortran object CMakeFiles/scalapack.dir/SRC/sstein2.f.o
     2859    /Users/gabriele/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.0/openmpi-3.1.6-rq44ux2m5xsdn3yq5abjprx5yxteuzk6/bin/mpif90 -DAdd_ -Dscalapa
             ck_EXPORTS -I/Users/gabriele/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.0/openmpi-3.1.6-rq44ux2m5xsdn3yq5abjprx5yxteuzk6/include  -O2 -
             g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -c /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/s
             pack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk/spack-src/SRC/sstein2.f -o CMakeFiles/scalapack.dir/SRC/sstein2.f.o
  >> 2860    make[1]: *** [CMakeFiles/scalapack.dir/all] Error 2
  >> 2861    make: *** [all] Error 2

See build log for details:
  /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/spack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk/spack-build-out.txt

==> Error: Failed to install netlib-scalapack due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j16'
4 errors found in build log:
     2848    
     2849      775 |             CALL IGEBR2D( ONEDCONTEXT, 'ALL', ' ', 1, 1, TORECV, 1, 0,
     2850          |                                                         2
     2851    ......
     2852      778 |                CALL IGEBR2D( ONEDCONTEXT, 'ALL', ' ', TORECV, 1, IWORK,
     2853          |                                                                 1
  >> 2854    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
  >> 2855    make[2]: *** [CMakeFiles/scalapack.dir/SRC/psstebz.f.o] Error 1
     2856    make[2]: *** Waiting for unfinished jobs....
     2857    2 warnings generated.
     2858    [ 33%] Building Fortran object CMakeFiles/scalapack.dir/SRC/sstein2.f.o
     2859    /Users/gabriele/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.0/openmpi-3.1.6-rq44ux2m5xsdn3yq5abjprx5yxteuzk6/bin/mpif90 -DAdd_ -Dscalapa
             ck_EXPORTS -I/Users/gabriele/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.0/openmpi-3.1.6-rq44ux2m5xsdn3yq5abjprx5yxteuzk6/include  -O2 -
             g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC   -c /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/s
             pack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk/spack-src/SRC/sstein2.f -o CMakeFiles/scalapack.dir/SRC/sstein2.f.o
  >> 2860    make[1]: *** [CMakeFiles/scalapack.dir/all] Error 2
  >> 2861    make: *** [all] Error 2

See build log for details:
  /var/folders/jm/m6sb9njx0sv5mv51f9d7pkyc0000gn/T/gabriele/spack-stage/spack-stage-netlib-scalapack-2.1.0-piujjxghd4rx4a6dgp3ukjgngsvodsjk/spack-build-out.txt
Traceback (most recent call last):
  File "/Users/gabriele/spack/lib/spack/spack/build_environment.py", line 846, in child_process
    return_value = function()
  File "/Users/gabriele/spack/lib/spack/spack/installer.py", line 1145, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/Users/gabriele/spack/lib/spack/spack/package.py", line 109, in phase_wrapper
    phase(spec, prefix)
  File "/Users/gabriele/spack/lib/spack/spack/build_systems/cmake.py", line 344, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/Users/gabriele/spack/lib/spack/spack/build_environment.py", line 133, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/Users/gabriele/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j16'

==> Warning: Skipping build of trilinos since netlib-scalapack failed
==> Warning: Skipping build of mumps since netlib-scalapack failed

```

### Information on your system

* **Spack:** 0.15.1
* **Python:** 3.7.4
* **Platform:** darwin-catalina-skylake

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4982267/spack-build-out.txt)

* [spack-build-env.txt](https://github.com/spack/spack/files/4982270/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by biri1987** [comment]
[spack-build-out.txt](https://github.com/spack/spack/files/4982266/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4982265/spack-build-env.txt)

**Comment by alalazo** [comment]
Can you please post the output of:
```console
$ spack config get compilers
```
?

**Comment by biri1987** [comment]
Hi alalazo,

here the output:
```
compilers:
- compiler:
    spec: apple-clang@11.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.1.0
    paths:
      cc: /usr/local/bin/gcc-10
      cxx: /usr/local/bin/g++-10
      f77: /usr/local/bin/gfortran-10
      fc: /usr/local/bin/gfortran-10
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@4.2.1
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77:
      fc:
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
Thank you!

**Comment by sethrj** [comment]
This looks like an issue with some of the older Fortran code inside `netlib-scalapack` relying on unspecified/non-standards-compliant behavior, probably triggered by a change in default with GCC 10 (which you're using) compared to older versions. GCC10 is pretty new.

Trilinos is unrelated to the build error itself; spack fails while building the upstream code. You should be able to work around this by building trilinos with the `~mumps` variant. Frankly, I recommend turning off everything in trilinos that you don't need for your app (or set of apps). For reference, my installation uses the variant:
```
trilinos@12.18.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~fortrilinos~glm~gtest+hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo gotype=long_long
```
which depends only on `hdf5` and `blas`.

**Comment by biri1987** [comment]
Dear @sethrj,

thank you for your quick response! I if use your installation command it works! 

I do not understand one stuff: you say that I'm using GCC10 but if I force the installation with `spack install trilinos%gcc@10.1.0` I get:

    ==> Error: Conflicts in concretized spec trilinos@12.18.1%gcc@10.1.0~adios2~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost~cgns~chaco~complex~debug~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran~fortrilinos+glm+gtest+hdf5+hypre+ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos+matio~mesquite+metis~minitensor+ml+mpi+muelu+mumps+netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~shards+shared~shylu~stk~stratimikos+suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 build_type=RelWithDebInfo gotype=long arch=darwin-catalina-skylake/iuwtlbe

    List of matching conflicts for spec:

    cmake@3.17.3%gcc@10.1.0~doc+ncurses+openssl+ownlibs~qt arch=darwin-catalina-skylake
        ^ncurses@6.2%gcc@10.1.0~symlinks+termlib arch=darwin-catalina-skylake
            ^pkgconf@1.7.3%gcc@10.1.0 arch=darwin-catalina-skylake
        ^openssl@1.1.1g%gcc@10.1.0+systemcerts arch=darwin-catalina-skylake
            ^perl@5.30.3%gcc@10.1.0+cpanm+shared+threads arch=darwin-catalina-skylake
                ^gdbm@1.18.1%gcc@10.1.0 patches=7f569b9287e9e5a4236636eef32ff3428f0462ec17aea359e0ebee07649f1f16 arch=darwin-catalina-skylake
                    ^readline@8.0%gcc@10.1.0 arch=darwin-catalina-skylake
            ^zlib@1.2.11%gcc@10.1.0+optimize+pic+shared arch=darwin-catalina-skylake

    1. "%gcc platform=darwin" conflicts with "cmake" [CMake does not compile with GCC on macOS yet, use clang. See: https://gitlab.kitware.com/cmake/cmake/-/issues/20620]

The same if I use GCC8.4. I'm sorry to bother you but I'm trying to understand how it works. 

Thank you!
Gabriele

**Comment by sethrj** [comment]
Sorry @biri1987 , I missed your response. I think (on mac systems) Spack automatically adds any available GCC compilers to the `fortran`/`f77` keys of your apple-clang compiler, so that it becomes a "mixed" toolchain. It's still using clang for C++; the error you get with the `%gcc@10` is because the GNU C++ compilers don't work well on newer mac versions.

I'm going to close this until it can be replicated on another system with GCC10.  The upcoming spack support for "compilers as dependencies" should allow for finer-grain control for whether it's a fortran or c++ conflict.
