### ISSUE TITLE
==> Error: invalid literal for int() with base 10: '' When installing

### ISSUE THREAD

**Issue by anne-glerum** [LLNL/spack#17811]
I want to install the latest dealii. I have updated my spack with `git pull`.
On the developer branch, `spack spec` and `spack install` with any package name (tried dealii, gcc and libelf)
give the error 
 ```console 
==> Error: invalid literal for int() with base 10: ''
```
Reverting to the old spack commit where I was at before git pull (a940ff34d; this does not contain the latest dealii release), I can do `spack spec dealii@9.1.0` without getting the above error.

Should I maybe update other components of my system before the spack dealii install?

I did run `$ spack clean -a` in between failed installs. 

### Steps to reproduce the issue

```console
$ git pull
$ spack spec gcc
```

### Error Message

```console
$ spack --debug --stacktrace install gcc
lib/spack/spack/cmd/__init__.py:122 ==> [2020-07-31-17:16:51.544707] Imported install from built-in commands
lib/spack/spack/config.py:805 ==> [2020-07-31-17:16:51.546102] Reading config file /Applications/Spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:122 ==> [2020-07-31-17:16:51.560562] Imported install from built-in commands
lib/spack/spack/config.py:805 ==> [2020-07-31-17:16:51.562857] Reading config file /Applications/Spack/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:805 ==> [2020-07-31-17:16:51.656260] Reading config file /Applications/Spack/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:805 ==> [2020-07-31-17:16:51.671428] Reading config file /Applications/Spack/spack/etc/spack/defaults/darwin/packages.yaml
lib/spack/spack/config.py:805 ==> [2020-07-31-17:16:51.732760] Reading config file /Users/acglerum/.spack/darwin/compilers.yaml
lib/spack/spack/util/executable.py:159 ==> [2020-07-31-17:16:51.775700] '/usr/bin/clang' '--version'
Traceback (most recent call last):
  File "/Applications/Spack/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Applications/Spack/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Applications/Spack/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/Applications/Spack/spack/lib/spack/spack/cmd/install.py", line 330, in install
    args.spec, concretize=True, tests=tests)
  File "/Applications/Spack/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/Applications/Spack/spack/lib/spack/spack/spec.py", line 2171, in concretize
    self._concretize_helper(concretizer))
  File "/Applications/Spack/spack/lib/spack/spack/spec.py", line 1996, in _concretize_helper
    concretizer, presets, visited
  File "/Applications/Spack/spack/lib/spack/spack/spec.py", line 1996, in _concretize_helper
    concretizer, presets, visited
  File "/Applications/Spack/spack/lib/spack/spack/spec.py", line 1996, in _concretize_helper
    concretizer, presets, visited
  File "/Applications/Spack/spack/lib/spack/spack/spec.py", line 2009, in _concretize_helper
    concretizer.adjust_target(self),
  File "/Applications/Spack/spack/lib/spack/spack/concretize.py", line 525, in adjust_target
    return next(self._adjust_target_answer_generator)
  File "/Applications/Spack/spack/lib/spack/spack/concretize.py", line 518, in _make_only_one_call
    yield self._adjust_target(spec)
  File "/Applications/Spack/spack/lib/spack/spack/concretize.py", line 560, in _adjust_target
    current_target.optimization_flags(spec.compiler)
  File "/Applications/Spack/spack/lib/spack/spack/architecture.py", line 226, in optimization_flags
    compiler.name, str(compiler_version)
  File "/Applications/Spack/spack/lib/spack/llnl/util/cpu/microarchitecture.py", line 256, in optimization_flags
    if satisfies_constraint(compiler_entry, version):
  File "/Applications/Spack/spack/lib/spack/llnl/util/cpu/microarchitecture.py", line 242, in satisfies_constraint
    version = tuplify(version)
  File "/Applications/Spack/spack/lib/spack/llnl/util/cpu/microarchitecture.py", line 240, in <lambda>
    tuplify = lambda x: tuple(int(y) for y in x.split('.'))
  File "/Applications/Spack/spack/lib/spack/llnl/util/cpu/microarchitecture.py", line 240, in <genexpr>
    tuplify = lambda x: tuple(int(y) for y in x.split('.'))
ValueError: invalid literal for int() with base 10: '
```

### Information on your system

``` console
$ /usr/bin/clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
``` console
$ spack debug report
* **Spack:** 0.15.3
* **Python:** 3.7.4
* **Platform:** darwin-mojave-skylake
```

``` console
$ vi ~/.spack/darwin/compilers.yaml
  1 compilers:
  2 - compiler:
  3     environment: {}
  4     extra_rpaths: []
  5     flags: {}
  6     modules: []
  7     operating_system: mojave
  8     paths:
  9       cc: /usr/bin/clang
 10       cxx: /usr/bin/clang++
 11       f77: null
 12       fc: null
 13     spec: clang@10.0.1-apple
 14     target: x86_64
 15 - compiler:
 16     environment: {}
 17     extra_rpaths: []
 18     flags: {}
 19     modules: []
 20     operating_system: mojave
 21     paths:
 22       cc: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/gcc
 23       cxx: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/g++
 24       f77: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/gfortran
 25       fc: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/gfortran
 26     spec: gcc@9.1.0
 27     target: x86_64
 28 - compiler:
 29     environment: {}
 30     extra_rpaths: []
 31     flags: {}
 32     modules: []
 33     operating_system: mojave
 34     paths:
 35       cc: /usr/bin/clang
 36       cxx: /usr/bin/clang++
 37       f77: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/gfortran
 38       fc: /Applications/Spack/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gcc-9.1.0-zjbhw3an52zst4lx2i5umeyolzmeshfh/bin/gfortran
 39     spec: clang@10.0.1-apple-gfortran9.1.0
 40     target: x86_64
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

``` console
$ spack test
... 
=============================================================================== short test summary info ================================================================================
FAIL lib/spack/spack/test/stage.py::TestStage::()::test_get_stage_root_in_spack
FAIL lib/spack/spack/test/cmd/env.py::test_env_activate_default_view_root_unconditional
SKIP [13] /Applications/Spack/spack/lib/spack/spack/test/conftest.py:283: could not find executables: patchelf
SKIP [1] lib/spack/spack/test/mirror.py:134: requires subversion, git, and mercurial to be installed
SKIP [1] lib/spack/spack/test/packaging.py:49: This test requires gpg
SKIP [1] lib/spack/spack/test/cmd/ci.py:674: This test requires gpg
SKIP [1] lib/spack/spack/test/ci.py:64: This test requires gpg
SKIP [2] /Applications/Spack/spack/lib/spack/spack/test/git_fetch.py:184: Not testing get_full_repo for older git 1.7.0
SKIP [4] lib/spack/spack/test/hg_fetch.py:25: requires mercurial to be installed
SKIP [1] lib/spack/spack/test/hg_fetch.py:80: requires mercurial to be installed
SKIP [1] lib/spack/spack/test/mirror.py:126: requires mercurial to be installed
SKIP [1] lib/spack/spack/test/relocate.py:181: implementation for MacOS still missing
SKIP [3] lib/spack/spack/test/relocate.py:201: implementation for MacOS still missing
SKIP [1] lib/spack/spack/test/cmd/buildcache.py:31: implementation for MacOS still missing
SKIP [1] lib/spack/spack/test/cmd/buildcache.py:40: implementation for MacOS still missing
SKIP [1] lib/spack/spack/test/cmd/flake8.py:62: flake8 is not installed.
SKIP [1] lib/spack/spack/test/cmd/gpg.py:63: These tests require gnupg2
SKIP [44] /Applications/Spack/spack/lib/spack/spack/test/llnl/util/lock.py:152: requires filesystem: '/nfs/tmp2/acglerum'
SKIP [44] /Applications/Spack/spack/lib/spack/spack/test/llnl/util/lock.py:152: requires filesystem: '/p/lscratch*/acglerum'
SKIP [1] /Applications/Spack/spack/lib/spack/spack/test/util/spack_lock_wrapper.py:48: user has no group with gid == uid
XFAIL lib/spack/spack/test/cmd/commands.py::test_no_pipe_error
XFAIL lib/spack/spack/test/cmd/help.py::test_reuse_after_help
```

**Comment by adamjstewart** [comment]
Hi @anne-glerum, it's great to see more geophysicists using Spack!

I think the problem here is that the Apple Clang compiler was renamed from `%clang@10.0.1-apple` to `%apple-clang@10.0.1` (see #17110). If you make those updates in your `compilers.yaml`, I _think_ it should fix your problem.

The reason it wasn't being caught before was that Spack doesn't yet support microarch-specific optimizations for Apple Clang. Now that LLVM Clang and Apple Clang have been split into separate compilers, we can add optimizations for Clang but skip Apple Clang. Also, I'm not sure if there's a bug in how we handle the `-gfortran9.1.0` appended to the version.

@alalazo and @becker33 are the microarch experts, so they may have more insight than me.

**Comment by anne-glerum** [comment]
Thanks for your quick reply @adamjstewart ! 
To get the installation started I created a new compiler with the exact same settings, just the new name and adapted my install command accordingly:
`spack install dealii ^cmake@3.9.4 %apple-clang@10.0.1-gfortran9.1.0`
The install unfortunately fails halfway through with the `berkeley-db` package in the build phase (all errors are related to atomic), but that's probably a separate issue?

**Comment by adamjstewart** [comment]
The berkeley-db bug was just fixed, if you update to the latest develop you should be able to get past that.

**Comment by anne-glerum** [comment]
Yes, great! Sorry for not seeing that, I thought I had checked for issues/PRs on berkely-db.

**Comment by adamjstewart** [comment]
@anne-glerum were you ever able to get dealii installed?

**Comment by anne-glerum** [comment]
@adamjstewart Actually, no. I got past this error (so this issue can be closed), but ran into dependency issues that I cannot recall any more. But I ended up installing dealii with candi, which was successful. Thanks for the help!

**Comment by adamjstewart** [comment]
Thanks @anne-glerum, if you ever encounter other issues with Spack feel free to open a new issue!
