### ISSUE TITLE
buildcache create does not work with uninstalled root specs of environment

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#17858]
`spack buildcache` tries to create a cache entry for non-installed root specs:

### Steps to reproduce the issue

```console
$ spack env create my_env
$ spack -e my_env install --only=dependencies perl
$ spack -e my_env buildcache create -d tmp
==> Error: perl does not match any installed packages.
==> Error: use one of the matching specs above
```

### Error Message

```console
# spack --debug --stacktrace -e ci buildcache create -d tmp
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-03-22:53:22.459456] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-03-22:53:22.461071] Imported buildcache from built-in commands
lib/spack/spack/config.py:805 ==> [2020-08-03-22:53:22.462045] Reading config file /opt/spack/var/spack/environments/ci/spack.yaml
lib/spack/spack/config.py:805 ==> [2020-08-03-22:53:22.472989] Reading config file /opt/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/cmd/buildcache.py:361 ==> [2020-08-03-22:53:22.474214] Buildcache files will be output to file:///tmp/build_cache
lib/spack/spack/cmd/buildcache.py:253 ==> [2020-08-03-22:53:22.474733] find_matching_specs: about to parse specs for {perl}
lib/spack/spack/database.py:362 ==> [2020-08-03-22:53:22.475940] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:366 ==> [2020-08-03-22:53:22.476053] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:805 ==> [2020-08-03-22:53:22.477811] Reading config file /opt/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:805 ==> [2020-08-03-22:53:22.479661] Reading config file /etc/spack/repos.yaml
lib/spack/spack/cmd/buildcache.py:268 ==> [2020-08-03-22:53:22.528319] Error: perl does not match any installed packages.
lib/spack/spack/cmd/buildcache.py:273 ==> [2020-08-03-22:53:22.528420] Error: use one of the matching specs above
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/buildcache.py", line 775, in buildcache
    args.func(args)
  File "/opt/spack/lib/spack/spack/cmd/buildcache.py", line 459, in createtarball
    rebuild_index=args.rebuild_index)
  File "/opt/spack/lib/spack/spack/cmd/buildcache.py", line 363, in _createtarball
    matches = find_matching_specs(pkgs, env=env)
  File "/opt/spack/lib/spack/spack/cmd/buildcache.py", line 273, in find_matching_specs
    tty.die('use one of the matching specs above')
  File "/opt/spack/lib/spack/llnl/util/tty/__init__.py", line 239, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system

* **Spack:** 0.15.3
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
This solves #17859 in the sense that it does not error, but at the same time it also skips creating tarballs of dependencies of uninstalled root specs, so it simply does nothing for packages installed as `spack install --only=dependencies [spec]` inside an environment.
