### ISSUE TITLE
Regression in environment matrix spec resolution

### ISSUE THREAD

**Issue by dennisklein** [LLNL/spack#18049]
[One of our spack environments](https://github.com/FairRootGroup/FairSoft/blob/7ebe61adcb0ddbf65cba21e1c93fce5728a2fbbb/test/env/fairlogger.yaml) that has worked with spack `0.14` no longer works with spack `0.15`:

```yaml
spack:
  definitions:
  - no_pretty: ['@1.1.0', '@1.2.0', '@1.3.0']
  - all:
    - $no_pretty
    - matrix:
      -
        - '@1.4.0'
        - '@1.5.0'
        - '@1.6.0'
        - '@1.6.1'
        - '@1.6.2'
        - '@1.7.0'
        - '@1.8.0'
        - '@develop'
      - ['+pretty', '~pretty']
  specs:
  - matrix:
    - ['fairlogger']
    - [$all]
  view: false
```

### Error Message

With the activated [environment](https://github.com/FairRootGroup/FairSoft/blob/7ebe61adcb0ddbf65cba21e1c93fce5728a2fbbb/test/env/fairlogger.yaml) from above:

```
$ spack --debug --stacktrace concretize -f
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-13-15:53:09.661670] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-13-15:53:09.662179] Imported concretize from built-in commands
lib/spack/spack/config.py:835 ==> [2020-08-13-15:53:09.769914] Reading config file /home/dklein/projects/FairSoft2/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:835 ==> [2020-08-13-15:53:09.771156] Reading config file /home/dklein/projects/FairSoft2/spack/etc/spack/repos.yaml
lib/spack/spack/config.py:835 ==> [2020-08-13-15:53:09.771772] Reading config file /home/dklein/projects/FairSoft2/test/env/fairlogger/spack.yaml
lib/spack/spack/main.py:765 ==> [2020-08-13-15:53:09.804206] InvalidModuleNameError: Invalid module name:
lib/spack/spack/error.py:55 ==> [2020-08-13-15:53:09.804383] Error: Invalid module name:
Traceback (most recent call last):
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/cmd/concretize.py", line 22, in concretize
    concretized_specs = env.concretize(force=args.force)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/environment.py", line 1005, in concretize
    return self._concretize_separately()
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/environment.py", line 1071, in _concretize_separately
    self.user_specs, self.user_specs.specs_as_constraints):
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/spec_list.py", line 58, in specs_as_constraints
    constraints.extend(_expand_matrix_constraints(item))
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/spec_list.py", line 184, in _expand_matrix_constraints
    for c in _expand_matrix_constraints(r, specify=False)])
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/spec_list.py", line 206, in _expand_matrix_constraints
    spack.variant.substitute_abstract_variants(test_spec)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/variant.py", line 608, in substitute_abstract_variants
    pkg_variant = spec.package_class.variants.get(name, None)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/spec.py", line 1185, in package_class
    return spack.repo.path.get_pkg_class(self.fullname)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/repo.py", line 654, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/repo.py", line 1081, in get_pkg_class
    class_name = nm.mod_to_class(pkg_name)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/util/naming.py", line 52, in mod_to_class
    validate_module_name(mod_name)
  File "/home/dklein/projects/FairSoft2/spack/lib/spack/spack/util/naming.py", line 154, in validate_module_name
    raise InvalidModuleNameError(mod_name)
spack.util.naming.InvalidModuleNameError: Invalid module name:
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.15.3-508-5512340a5
* **Python:** 3.8.5
* **Platform:** linux-fedora32-skylake
```

The `/home/dklein/projects/FairSoft2` directory in the error output above is this git repo: https://github.com/dennisklein/FairSoft/tree/spack_0_15_3

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

### Quick fix

`git bisect`ing reveals https://github.com/spack/spack/commit/2795414a80839208c3463e49f197fee25f2be0f8 to introduce the regression. I have *fixed* it in our spack fork like this for now: https://github.com/FairRootGroup/spack/commit/5668256776fb07b0ac88c9f65fc8832fac5d1c60. If you want this fix, I can prepare a PR and some unit test coverage.

---

cc: @ChristianTackeGSI

**Comment by scheibelp** [comment]
@becker33 I'm curious about your thoughts on this:

For matrices that expand to anonymous specs, the check added in https://github.com/spack/spack/pull/16893 will fail; the fix added at https://github.com/FairRootGroup/spack/commit/5668256776fb07b0ac88c9f65fc8832fac5d1c60 addresses that, although I'm curious if you think there would be an advantage to this vs. holding off on variant substitution until all matrices are expanded (i.e. don't do variant replacement on sub-matrices). I can see an advantage to the latter approach as it might extend well to other checks we want to do (which may also fail on anonymous specs).

**Comment by becker33** [comment]
@scheibelp I think the value of an easy fix for this problem is pretty high compared to trying to optimize for something we want later, and I think that variant substitution is sufficiently "one-off" within Spack that we're unlikely to code ourselves into a corner here.

@dennisklein have you tried this out with an `exclude` clause in the outer matrix? Either way, I think we would appreciate a PR with this fix!
