### ISSUE TITLE
Matplotlib + ffmpeg crashes when saving MP4 file

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#18071]
When I build `py-matplotlib+movies` (which pulls in a dependency on `ffmpeg`), matplotlib crashes when I try to save an MP4 file.

### Steps to reproduce the issue

It should be possible to follow any matplotlib animation tutorial like https://towardsdatascience.com/animations-with-matplotlib-d96375c5442c and save the result as an MP4 file to reproduce the issue.

### Error Message

```
MovieWriter stderr:
[h264_v4l2m2m @ 0x55dd693b2ec0] Could not find a valid device
[h264_v4l2m2m @ 0x55dd693b2ec0] can't configure encoder
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

Traceback (most recent call last):
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 251, in saving
    yield self
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 1137, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 363, in grab_frame
    dpi=self.dpi, **savefig_kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 456, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./plot.py", line 74, in <module>
    main(args)
  File "./plot.py", line 45, in main
    ani.save(fp)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 1137, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 253, in saving
    self.finish()
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 353, in finish
    self.cleanup()
  File "/home/adam/eclipse/.spack-env/view/lib/python3.7/site-packages/matplotlib/animation.py", line 390, in cleanup
    self._proc.returncode, self._proc.args, out, err)
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x480', '-pix_fmt', 'rgba', '-r', '5.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', 'results/CO2.mp4']' returned non-zero exit status 1.
```

### Information on your system

* **Spack:** 0.14.2-2198-4a2136670
* **Python:** 3.7.8
* **Platform:** linux-ubuntu20.04-skylake

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

@xjrc I see that you're the maintainer for the `ffmpeg` package recipe. Any idea what's going wrong here? Maybe `py-matplotlib` needs to depend on a certain variant of `ffmpeg`? When I use the version of `ffmpeg` on my system, things work just fine.

**Comment by xjrc** [comment]
@adamjstewart: It may be that the default `ffmpeg` that we build doesn't support MP4 and its associated codecs, which wouldn't surprise me given how intricate the configuration process is for the library. I did some quick googling and found the following useful tidbits:

1. [MP4 Support Requires `libavformat`](https://github.com/alberthdev/alberthdev-misc/wiki/Build-your-own-tiny-FFMPEG#background)
2. [MP4 Support May Also Require MP4 Muxer](https://stackoverflow.com/a/54756991)

As a first pass, I'd try to just add `avformat` to the list of `variant_opts` in the `ffmpeg` package (similar to `avresample`) and see if explicitly enabling that helps. If there are still issues, I'd recommend incorporating some of the muxer configuration options referenced in the second link above.

I don't have time to test these workarounds at present, but I can try to help this weekend or early next week if you need it.

**Comment by adamjstewart** [comment]
@xjrc I tried the following patch:
```diff
diff --git a/var/spack/repos/builtin/packages/ffmpeg/package.py b/var/spack/repos/builtin/packages/ffmpeg/package.py
index cc3a0216e..c9642eab1 100644
--- a/var/spack/repos/builtin/packages/ffmpeg/package.py
+++ b/var/spack/repos/builtin/packages/ffmpeg/package.py
@@ -58,7 +58,8 @@ class Ffmpeg(AutotoolsPackage):
     #         description='XML parsing, needed for dash demuxing support')
     variant('libzmq', default=False, description='message passing via libzmq')
     variant('lzma', default=False, description='lzma support')
-    variant('avresample', default=False, description='AV reasmpling component')
+    variant('avformat', default=False, description='AV mux and demux handler')
+    variant('avresample', default=False, description='AV resampling component')
     variant('openssl', default=False, description='needed for https support')
     variant('sdl2', default=False, description='sdl2 support')
     variant('shared', default=True, description='build shared libraries')
@@ -152,6 +153,7 @@ def configure_args(self):
             'libopus',
             'libspeex',
             'libvorbis',
+            'avformat',
             'avresample',
             'openssl',
             'shared',
@@ -177,4 +179,7 @@ def configure_args(self):
         for variant_opt in variant_opts:
             config_args += self.enable_or_disable(variant_opt)

+        if '+avformat' in spec:
+            config_args.append('--enable-muxer=mp4')
+
         return config_args
```
and built `ffmpeg+avformat`, but I'm still seeing the same error message. I'm having trouble reproducing on macOS, so this may be specific to Linux. I have to return my work laptop, so I'm not sure how easy it will be for me to debug this in the future. This is fairly low priority, but I would like to make `py-matplotlib` more robust for saving MP4 files in the future.

**Comment by alalazo** [comment]
Changed this one to "build error", since it seems more due to the recipe than to core Spack.
