### ISSUE TITLE
Valid concretization requiring older version is not found in dependency resolution

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#18086]
Due a pinned version on the libzqm dependency of cppzmq, but an open version libzqm dependency in py-pyzmq, a bundle package that depends on both cppzmq and py-pyzmq results in an unsatisfiable version constraint even though a satisfiable version can be hinted at (and, arguably, should have been found). This may point to a class of unsatisfiable version constraints elsewhere that can be resolved.

### Steps to reproduce the issue

```console
$ spack create -t bundle -n zmqbug
```
Add a version and two generic dependencies:
```python
    version('1.0.0')
    depends_on('cppzmq')
    depends_on('py-pyzmq')
```
```console
$ spack spec zmqbug
$ spack spec zmqbug ^libzmq@4.2.5
```

### Error Message

The first spec (no hinting) fails with:
```console
$ spack spec zmqbug
Input spec
--------------------------------
zmqbug

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    libzmq@4.3.2%gcc@9.3.0+libsodium arch=linux-ubuntu20.04-ivybridge


while trying to concretize the partial spec:

    cppzmq@4.3.0%gcc@9.3.0 build_type=RelWithDebInfo arch=linux-ubuntu20.04-ivybridge
        ^cmake@3.13.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-ivybridge


cppzmq requires libzmq version 4.2.5, but spec asked for 4.3.2
```

The second spec (with hinting) succeeds:
```console
$ spack spec zmqbug ^libzmq@4.2.5
Input spec
--------------------------------
zmqbug
    ^libzmq@4.2.5

Concretized
--------------------------------
zmqbug@1.0.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
    ^cppzmq@4.3.0%gcc@9.3.0 build_type=RelWithDebInfo arch=linux-ubuntu20.04-ivybridge
        ^cmake@3.13.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt patches=1c540040c7e203dd8e27aa20345ecb07fe06570d56410a24a266ae570b1c4c39 arch=linux-ubuntu20.04-ivybridge
        ^libzmq@4.2.5%gcc@9.3.0+libsodium arch=linux-ubuntu20.04-ivybridge
            ^libsodium@1.0.18%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
            ^pkgconf@1.7.3%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
    ^py-pyzmq@18.1.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
        ^py-cffi@1.13.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
            ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu20.04-ivybridge
            ^py-pycparser@2.19%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                ^py-setuptools@46.1.3%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                    ^python@3.7.7%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-ubuntu20.04-ivybridge
                        ^bzip2@1.0.8%gcc@9.3.0+shared arch=linux-ubuntu20.04-ivybridge
                            ^diffutils@3.7%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                                ^libiconv@1.16%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                        ^expat@2.2.9%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-ivybridge
                            ^libbsd@0.10.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                        ^gdbm@1.18.1%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                            ^readline@8.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                                ^ncurses@6.2%gcc@9.3.0~symlinks+termlib arch=linux-ubuntu20.04-ivybridge
                        ^gettext@0.20.2%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-ivybridge
                            ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-ubuntu20.04-ivybridge
                                ^xz@5.2.5%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                                ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-ivybridge
                            ^tar@1.32%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
                        ^openssl@1.1.1g%gcc@9.3.0+systemcerts arch=linux-ubuntu20.04-ivybridge
                            ^perl@5.30.3%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-ivybridge
                        ^sqlite@3.31.1%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-ubuntu20.04-ivybridge
        ^py-cython@0.29.16%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
        ^py-py@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-ivybridge
            ^py-setuptools-scm@4.1.2%gcc@9.3.0~toml arch=linux-ubuntu20.04-ivybridge
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.4
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-ivybridge
```

Minimal packages/zmqbug/package.py:
```python
from spack import *
class Zmqbug(BundlePackage):
    version('1.0.0')
    depends_on('cppzmq')
    depends_on('py-pyzmq')
```

```console
$ spack --debug --stacktrace spec zmqbug
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-15-17:33:42.830263] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-08-15-17:33:42.831970] Imported spec from built-in commands
Input spec
--------------------------------
zmqbug

Concretized
--------------------------------
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:42.836936] Reading config file /usr/local/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:42.856110] Reading config file /usr/local/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:42.858451] Reading config file /home/wdconinc/.spack/linux/repos.yaml
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:42.978372] Reading config file /usr/local/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:42.998922] Reading config file /home/wdconinc/.spack/linux/packages.yaml
lib/spack/spack/config.py:805 ==> [2020-08-15-17:33:43.115847] Reading config file /home/wdconinc/.spack/linux/compilers.yaml
lib/spack/spack/main.py:765 ==> [2020-08-15-17:33:43.172310] UnsatisfiableVersionSpecError: An unsatisfiable version constraint has been detected for spec:

    libzmq@4.3.2%gcc@9.3.0+libsodium arch=linux-ubuntu20.04-ivybridge


while trying to concretize the partial spec:

    cppzmq@4.3.0%gcc@9.3.0 build_type=RelWithDebInfo arch=linux-ubuntu20.04-ivybridge
        ^cmake@3.13.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-ivybridge


cppzmq requires libzmq version 4.2.5, but spec asked for 4.3.2
lib/spack/spack/error.py:55 ==> [2020-08-15-17:33:43.172976] Error: An unsatisfiable version constraint has been detected for spec:

    libzmq@4.3.2%gcc@9.3.0+libsodium arch=linux-ubuntu20.04-ivybridge


while trying to concretize the partial spec:

    cppzmq@4.3.0%gcc@9.3.0 build_type=RelWithDebInfo arch=linux-ubuntu20.04-ivybridge
        ^cmake@3.13.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-ivybridge


cppzmq requires libzmq version 4.2.5, but spec asked for 4.3.2
Traceback (most recent call last):
  File "/usr/local/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/local/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/usr/local/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    spec.concretize()
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2168, in concretize
    changes = (self.normalize(force, tests=tests,
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2650, in normalize
    any_change = self._normalize_helper(
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2588, in _normalize_helper
    changed |= self._merge_dependency(
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2547, in _merge_dependency
    changed |= spec_dependency._normalize_helper(
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2588, in _normalize_helper
    changed |= self._merge_dependency(
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2524, in _merge_dependency
    changed |= spec_deps[dep.name].constrain(dep)
  File "/usr/local/spack/lib/spack/spack/spec.py", line 2724, in constrain
    raise UnsatisfiableVersionSpecError(self.versions, other.versions)
spack.spec.UnsatisfiableVersionSpecError: An unsatisfiable version constraint has been detected for spec:

    libzmq@4.3.2%gcc@9.3.0+libsodium arch=linux-ubuntu20.04-ivybridge


while trying to concretize the partial spec:

    cppzmq@4.3.0%gcc@9.3.0 build_type=RelWithDebInfo arch=linux-ubuntu20.04-ivybridge
        ^cmake@3.13.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-ivybridge


cppzmq requires libzmq version 4.2.5, but spec asked for 4.3.2
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

Note: In order to work around this issue, I am simultaneously filing a PR #18087 to remove the version pinning on cppzmq by adding a more recent version.

**Comment by alalazo** [comment]
Thanks for the report @wdconinc! We currently employ an ad-hoc algorithm for constraint resolution that doesn't do as much backtracking as it should - hence the issue you are reporting. I am marking it as a duplicate since it's, generally speaking, of the same kind as many other issues reported for the concretizer. For instance:
```console
$ spack spec hdf5 ^jdk
Input spec
--------------------------------
hdf5
    ^jdk

Concretized
--------------------------------
==> Error: Package hdf5 does not depend on jdk
```
even though there would be a way to satisfy my request by adding a `+java` to `hdf5`:
```console
$ spack spec hdf5+java ^jdk
Input spec
--------------------------------
hdf5+java
    ^jdk

Concretized
--------------------------------
hdf5@1.10.6%gcc@10.1.0~cxx~debug~fortran~hl+java+mpi+pic+shared~szip~threadsafe api=none arch=linux-ubuntu18.04-broadwell
    ^jdk@14_36%gcc@10.1.0 arch=linux-ubuntu18.04-broadwell
    ...
```
The good news is that these issues with the current concretizer are being solved in a branch where a new concretizer is being developed (`features/solver`) by @tgamblin A good place to have more general information on it is [this talk](https://fosdem.org/2020/schedule/event/dependency_solving_not_just_sat/) from FOSDEM 2020. Let me know if you have any other questions or comments.

**Comment by wdconinc** [comment]
Not an issue anymore with current concretizer.
