### ISSUE TITLE
Language version flag checks do not work for non-standard compiler spec names

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#18111]
### Steps to reproduce the issue
1. Change a clang spec name in a `compilers.yaml` to use an alias, e.g., `clang@9.0.0` to `clang@beta2019.11.14`
2. Attempt to build a C++11 (or greater) project with that compiler

### Error Message

```
==> [2020-08-17-10:42:39.147654] Error: UnsupportedCompilerFlag: clang (< 3.3) does not support the C++11 standard (as compiler.cxx11_flag).
    If you think it should, please edit the compiler.clang subclass to implement the cxx11_flag property and submit a pull request or issue.

spack/var/spack/repos/builtin/packages/superlu-dist/package.py:89, in flag_handler:
         86    def flag_handler(self, name, flags):
         87        flags = list(flags)
         88        if name == 'cxxflags':
  >>     89            flags.append(self.compiler.cxx11_flag)
         90        if name == 'cflags' and '%pgi' not in self.spec:
         91            flags.append('-std=c99')
         92        return (None, None, flags)


Traceback (most recent call last):
  File "spack/lib/spack/spack/build_environment.py", line 845, in child_process
    setup_package(pkg, dirty=dirty)
  File "spack/lib/spack/spack/build_environment.py", line 720, in setup_package
    set_compiler_environment_variables(pkg, build_env)
  File "spack/lib/spack/spack/build_environment.py", line 273, in set_compiler_environment_variables
    injf, envf, bsf = handler(pkg, flag, spec.compiler_flags[flag])
  File "spack/var/spack/repos/builtin/packages/superlu-dist/package.py", line 90, in flag_handler
    if name == 'cflags' and '%pgi' not in self.spec:
  File "spack/lib/spack/spack/compilers/clang.py", line 95, in cxx11_flag
    self, "the C++11 standard", "cxx11_flag", "< 3.3"
spack.compiler.UnsupportedCompilerFlag: clang (< 3.3) does not support the C++11 standard (as compiler.cxx11_flag).
    If you think it should, please edit the compiler.clang subclass to implement the cxx11_flag property and submit a pull request or issue.
==> [2020-08-17-10:42:39.148077] Flagging superlu-dist as failed: UnsupportedCompilerFlag: clang (< 3.3) does not support the C++11 standard (as compiler.cxx11_flag).

```

### Information on your system

* **Spack:** 0.15.4
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

Currently the cxx11 flag logic for clang (and gcc) checks against `self.version`, which in the case of an aliased compiler name will not match the "real" version of the compiler.  Possibly the condition could be changed to something like the following:
```py
if ver(self.get_real_version()) < ver('3.3'):
    raise UnsupportedCompilerFlag
```
This uses the self-reported compiler version instead of what the user has named a given compiler in their `compilers.yaml` file.

**Comment by adamjstewart** [comment]
You can also change the compiler version to `clang@2019.11.14.beta`, that should work fine.
