### ISSUE TITLE
macOS nightly build tests are failing

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#18370]
### Steps to reproduce the issue

```console
$ spack install qt
```

with an external qt install as in our CI (#18642)
```
spack config add packages:opengl:paths:opengl@4.1:/usr/X11R6
```

fails with
```
2020-08-28T02:56:56.9860450Z [+] /Users/runner/work/spack/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/py-ipykernel-5.1.1-hxmeesoggzdzyhjczzdtfeguqpjzwk5k
2020-08-28T02:56:57.7652100Z ==> Installing qt
2020-08-28T02:56:57.7652340Z ==> No binary for qt found: installing from source
2020-08-28T02:58:40.9692410Z ==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.3 for further details]
2020-08-28T02:58:40.9694820Z ==> Warning: Copying Xcode from /Applications/Xcode_11.6.app to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/runner/spack-stage/xcode-select/apple-clang/11.0.3 in order to add spack wrappers to it. Please do not interrupt.
2020-08-28T02:58:40.9789700Z ==> Error: AttributeError: Query of package 'opengl' for 'libs' failed
2020-08-28T02:58:40.9789900Z 	prefix : /usr/X11R6
2020-08-28T02:58:40.9791750Z 	spec : opengl@4.1%apple-clang@11.0.3 arch=darwin-catalina-x86_64
2020-08-28T02:58:40.9791950Z 	queried as : opengl
2020-08-28T02:58:40.9792060Z 	extra parameters : []
2020-08-28T02:58:40.9792120Z 
2020-08-28T02:58:40.9792240Z /Users/runner/work/spack/spack/lib/spack/spack/build_environment.py:863, in child_process:
2020-08-28T02:58:40.9792370Z         860            tb_string = traceback.format_exc()
2020-08-28T02:58:40.9792480Z         861
2020-08-28T02:58:40.9792620Z         862            # build up some context from the offending package so we can
2020-08-28T02:58:40.9792740Z   >>    863            # show that, too.
2020-08-28T02:58:40.9792860Z         864            package_context = get_package_context(tb)
2020-08-28T02:58:40.9792970Z         865
2020-08-28T02:58:40.9793080Z         866            build_log = None
2020-08-28T02:58:40.9793150Z 
2020-08-28T02:58:40.9793200Z 
2020-08-28T02:58:41.0313570Z ==> Warning: Skipping build of py-pyqt5 since qt failed
2020-08-28T02:58:41.0314200Z ==> Warning: Skipping build of py-qtconsole since py-pyqt5 failed
2020-08-28T02:58:41.0314670Z ==> Warning: Skipping build of py-jupyter since py-qtconsole failed
2020-08-28T02:58:41.0315160Z ==> Error: Terminating after first install failure: AttributeError: Query of package 'opengl' for 'libs' failed
2020-08-28T02:58:41.0315310Z 	prefix : /usr/X11R6
2020-08-28T02:58:41.0315750Z 	spec : opengl@4.1%apple-clang@11.0.3 arch=darwin-catalina-x86_64
2020-08-28T02:58:41.0315870Z 	queried as : opengl
2020-08-28T02:58:41.0316600Z 	extra parameters : []
2020-08-28T02:58:41.0316730Z /Users/runner/work/spack/spack/lib/spack/spack/build_environment.py:863, in child_process:
2020-08-28T02:58:41.0316860Z         860            tb_string = traceback.format_exc()
2020-08-28T02:58:41.0316970Z         861
2020-08-28T02:58:41.0317100Z         862            # build up some context from the offending package so we can
2020-08-28T02:58:41.0317220Z   >>    863            # show that, too.
2020-08-28T02:58:41.0317340Z         864            package_context = get_package_context(tb)
2020-08-28T02:58:41.0317450Z         865
2020-08-28T02:58:41.0317560Z         866            build_log = None
2020-08-28T02:58:41.0317620Z 
2020-08-28T02:58:41.0317720Z Traceback (most recent call last):
2020-08-28T02:58:41.0319350Z   File "/Users/runner/work/spack/spack/lib/spack/spack/build_environment.py", line 846, in child_process
2020-08-28T02:58:41.0319560Z     setup_package(pkg, dirty=dirty)
2020-08-28T02:58:41.0319780Z   File "/Users/runner/work/spack/spack/lib/spack/spack/build_environment.py", line 722, in setup_package
2020-08-28T02:58:41.0319930Z     set_build_environment_variables(pkg, build_env, dirty)
2020-08-28T02:58:41.0320140Z   File "/Users/runner/work/spack/spack/lib/spack/spack/build_environment.py", line 336, in set_build_environment_variables
2020-08-28T02:58:41.0320270Z     dep_link_dirs.extend(query.libs.directories)
2020-08-28T02:58:41.0320440Z   File "/Users/runner/work/spack/spack/lib/spack/spack/spec.py", line 900, in __get__
2020-08-28T02:58:41.0320590Z     raise AttributeError(message)
2020-08-28T02:58:41.0321120Z AttributeError: Query of package 'opengl' for 'libs' failed
2020-08-28T02:58:41.0321250Z 	prefix : /usr/X11R6
2020-08-28T02:58:41.0321700Z 	spec : opengl@4.1%apple-clang@11.0.3 arch=darwin-catalina-x86_64
2020-08-28T02:58:41.0321830Z 	queried as : opengl
2020-08-28T02:58:41.0321940Z 	extra parameters : []
2020-08-28T02:58:41.0321990Z 
2020-08-28T02:58:43.3941210Z ##[error]Process completed with exit code 1.
2020-08-28T02:58:43.4034300Z Post job cleanup.
2020-08-28T02:58:44.0585030Z [command]/usr/local/bin/git version
2020-08-28T02:58:44.0900940Z git version 2.28.0
2020-08-28T02:58:44.0975530Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-08-28T02:58:44.1060350Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-08-28T02:58:44.2691900Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-08-28T02:58:44.2752070Z http.https://github.com/.extraheader
2020-08-28T02:58:44.2765750Z [command]/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-08-28T02:58:44.2855920Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-08-28T02:58:44.4345960Z Cleaning up orphan processes
```

### Information on your system

any recent macOS

### Additional information

See:
https://github.com/spack/spack/runs/1039421566?check_suite_focus=true

I think it's caused by this line:
  https://github.com/spack/spack/blob/25021ec2280cc61ec7e6ea7ea39dec773eb796c0/var/spack/repos/builtin/packages/qt/package.py#L272

because `.libs` does not exist for a virtual package ? (but for mesa)

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
@ax3l Seems reasonable. Could you print `spack spec qt` or whatever concretization of QT variants/version/deps?

**Comment by sethrj** [comment]
@ax3l My packages.yaml contains
```
  opengl:
    buildable: false
    paths: {opengl@2.1: /opt/X11}
```
and builds qt yaml without complaint. On my system, `/usr/X11R6` is a symlink to `../private/var/select/X11` which is a symlink to `/opt/X11`.

The concretization that worked for me:
```
qt@5.14.2%apple-clang@11.0.0~dbus~debug~examples+framework~gtk+opengl~phonon+shared~sql~ssl~tools~webkit freetype=none patches=7f34d48d2faaa108dc3fcc47187af1ccd1d37ee0f931b42597b820f03a99864c arch=darwin-catalina-x86_64
```

**Comment by adamjstewart** [comment]
> because `.libs` does not exist for a virtual package?

That's an interesting theory. According to the docs for `ForwardQueryToPackage`, we should be accounting for this:

```python
        """Retrieves the property from Package using a well defined chain       
        of responsibility.                                                      
                                                                                
        The order of call is:                                                   
                                                                                
        1. if the query was through the name of a virtual package try to        
            search for the attribute `{virtual_name}_{attribute_name}`          
            in Package                                                          
                                                                                
        2. try to search for attribute `{attribute_name}` in Package            
                                                                                
        3. try to call the default handler                                      
                                                                                
        The first call that produces a value will stop the chain.               
                                                                                
        If no call can handle the request then AttributeError is raised with a  
        message indicating that no relevant attribute exists.                   
        If a call returns None, an AttributeError is raised with a message      
        indicating a query failure, e.g. that library files were not found in a 
        'libs' query.                                                           
        """                          
```
So it should be working. If you want, you can try renaming `libs` to `gl_libs` in the `opengl` package.

I think it's more likely that OpenGL isn't installed at all on our GitHub Actions runners, or it's installed in a different directory than the one we're using. I tried replacing it with `spack external find opengl` but it wasn't able to find anything. I would love for our macOS build tests to pass again...

@alalazo may have comments on the above

**Comment by adamjstewart** [comment]
A simple test leads me to believe that our `libs` attribute should be working fine as long as OpenGL is actually installed:
```console
$ spack python
Spack version 0.15.4
Python 3.7.8, Darwin x86_64
>>> from spack.spec import Spec
>>> s = Spec('gl')
>>> s.concretize()
>>> s.package.libs
LibraryList(['/opt/X11/lib/libGL.dylib'])
```
This is with the following entry in `packages.yaml`:
```yaml
packages:
  opengl:
    buildable: false
    externals:
    - spec: opengl@2.1
      prefix: /opt/X11
```
P.S. The format of `packages.yaml` changed, but we didn't change the format of `spack config add` used by our CI. Is this the issue?

**Comment by adamjstewart** [comment]
I tried debugging this on GitHub Actions but was having trouble viewing the output. It didn't seem like `spack external find opengl` was working, so maybe OpenGL isn't actually installed on their macOS machines? If that's the case, we may want to switch from `py-jupyter` to `py-jupyterlab` or `py-notebook`, which don't have that `qt` dependency that takes forever to build and relies on `opengl`.

P.S. Has anyone tried using a Spack-installed Jupyter Notebook or Lab? I get import errors where it can't find any of my Spack-installed libs, even though they're in an active environment. Jupyter Lab fails because it can't find `ipykernel_launcher`, even though I can import it in `python`.

**Comment by adamjstewart** [comment]
Trying to build `qt` on my macOS with an external OpenGL to confirm that this is an issue with GitHub Actions, not with qt/opengl/libs on virtual dependencies.

**Comment by ax3l** [comment]
Yes, looks like potentially the GH runner for macOS removed OpenGL from its image recently? Let's see if we can pull this in via [brew](https://formulae.brew.sh/formula/glfw): #18684

**Comment by ax3l** [comment]
Oh, overlooked this:
> P.S. The format of packages.yaml changed, but we didn't change the format of spack config add used by our CI. Is this the issue?

Maybe all we need is
`-`
>          spack config add packages:opengl:paths:opengl@4.1:/usr/X11R6 
`+`
>          spack config add packages:opengl:externals:[spec:opengl@4.1,prefix:/usr/X11R6]
or so?

**Comment by ax3l** [comment]
@adamjstewart what is the new `spack config add` syntax actually for this array-argument? Tried around but could not pass it properly for `spec` and `prefix`.

**Comment by adamjstewart** [comment]
No idea. I think @becker33  wrote the syntax and @alalazo  changed the packages format.
