### ISSUE TITLE
Strange concretization error "Invalid Version range" due to slack version specification of the external dependency

### ISSUE THREAD

**Issue by albestro** [LLNL/spack#18419]
I noticed a strange behavior with version ranges. After some troubleshooting (thanks @haampie), we found the root reason in my configuration, but I think it is worth mentioning what happened.

What happened is that due to my `packages.yaml` configuration having a "superficially" described version (i.e. `python@3`), the package `weechat` containing the directive `depends_on("python@3.5:")` caused

```console
$ spack spec weechat
...
==> Error: Invalid Version range: 3.5:3
```

Changing in `package.yaml` to `python@3.8.5` solved the problem.

I know it is a good practice to give as much details as it is possible when specifying an external package, but I think it is worth mentioning this behavior since I found the error message misleading. Even after understanding the root of the problem, I'm still thinking that it was not the kind of error message I would have expected (e.g. I think it is a failed constraint, isn't it?).

### Steps to reproduce the issue

For the sake of the example, I will target `weechat ^ python`, but I don't think it is related to a specific pair. 

The main requirement for reproducing it, I think it is having an external `python` package in `packages.yaml` with a partially specified version (i.e. `python@3`).

### Error Message

```console
$ spack --debug --stacktrace spec weechat
...
Traceback (most recent call last):
  File "/Users/ialberto/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Users/ialberto/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ialberto/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ialberto/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    spec.concretize()
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2211, in concretize
    self._expand_virtual_packages(concretizer),
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2132, in _expand_virtual_packages
    copy.normalize(force=True)
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2695, in normalize
    any_change = self._normalize_helper(
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2633, in _normalize_helper
    changed |= self._merge_dependency(
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2569, in _merge_dependency
    changed |= spec_deps[dep.name].constrain(dep)
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 2797, in constrain
    changed |= self.versions.intersect(other.versions)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 89, in coercing_method
    return method(a, b, *args, **kwargs)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 753, in intersect
    isection = self.intersection(other)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 89, in coercing_method
    return method(a, b, *args, **kwargs)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 744, in intersection
    result.add(s.intersection(o))
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 92, in coercing_method
    return getattr(ca, method.__name__)(cb, *args, **kwargs)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 89, in coercing_method
    return method(a, b, *args, **kwargs)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 559, in intersection
    return VersionRange(start, end)
  File "/Users/ialberto/spack/lib/spack/spack/version.py", line 389, in __init__
    raise ValueError("Invalid Version range: %s" % self)
ValueError: Invalid Version range: 3.5:3
```

### Information on your system

* **Spack:** 0.15.4-770-c07204d66
* **Python:** 3.8.5
* **Platform:** darwin-mojave-skylake

`packages.yaml` file
```yaml
packages:
...
  python:
    externals:
    - spec: python@3
      prefix: /usr/local/
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
This is a known limitation of the concretizer. If you add an external package, you should specify the exact version (3.8.5), not just 3. This should hopefully be fixed by @tgamblin's experimental concretizer.
