### ISSUE TITLE
Environment with package depending on scalapack and concretized with `intel-mkl`

### ISSUE THREAD

**Issue by nrichart** [LLNL/spack#18692]
I managed to create an environment that cannot be installed.
The problems seems to come from the `build_system` intel when a package depends en scalapack in en environment. The `spec_root` spec is not pointing to the proper spec and the blacs library cannot be determine since `spec_root` is not the proper spec depending on `mpi`

### Steps to reproduce the issue

```console
$ spack env create test
$ spack --env test add superlu%intel ^intel-mkl ^cmake@3.16.5
$ spack --env test add mumps%intel ^intel-mkl ^intel-mpi
$ spack --env test concretize
$ speck --env test install
```

If you do the add in the other order, mumps fist superlu after it works fine.
I did not manage to make the installation fail outside of the environment

### Error Message

```console
$ spack --debug --stacktrace --env test install
...
lib/spack/spack/installer.py:1145 ==> [2020-09-16-16:52:01.220771] mumps: Executing phase: 'install'
lib/spack/spack/error.py:55 ==> [2020-09-16-16:52:01.411345] Error: InstallError: Cannot find a BLACS library for the given MPI.

/home/richart/test/arvine/spack.v1/lib/spack/spack/build_systems/intel.py:824, in scalapack_libs:
        821            blacs_lib = 'libmkl_blacs_intelmpi'
        822        elif '^mpt' in spec_root:
        823            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    824        else:
        825            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        826
        827        int_suff = '_' + self.intel64_int_suffix

See build log for details:
  /home/richart/test/arvine.v1/tmp/spack-stage-mumps-5.3.3-5nzshjpdnu5kojx3t5jeoiqufn6w53cb/spack-build-out.txt

Traceback (most recent call last):
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/build_environment.py", line 846, in child_process
    return_value = function()
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/installer.py", line 1150, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/richart/test/arvine/spack.v1/var/spack/repos/builtin/packages/mumps/package.py", line 262, in install
  File "/home/richart/test/arvine/spack.v1/var/spack/repos/builtin/packages/mumps/package.py", line 199, in write_makefile_inc
    if '+ptscotch' in self.spec or '+scotch' in self.spec:
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/spec.py", line 877, in __get__
    value = f()
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/spec.py", line 864, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, specialized_name))
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/build_systems/intel.py", line 825, in scalapack_libs
    raise_lib_error('Cannot find a BLACS library for the given MPI.')
  File "/home/richart/test/arvine/spack.v1/lib/spack/spack/build_systems/intel.py", line 48, in raise_lib_error
    raise InstallError("\n\t".join(str(i) for i in args))
spack.installer.InstallError: Cannot find a BLACS library for the given MPI.
```

### Information on your system

* **Spack:** 0.15.4
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by nrichart** [comment]
Is there any update on this bug?
From what I could see it is in intel-mkl when it accesses the root spec. It takes the first of a list and this is not the spec that required scalapack

**Comment by alalazo** [comment]
@nrichart Apologies for the delay, the issue got lost in the Github stream. We plan a release in a few days, so this particular bug is not likely to make it, but I added it to the next project board so we'll be sure to have a look at it.

**Comment by alalazo** [comment]
Confirmed the bug is still present on:

* **Spack:** 0.17.1-735-f8d4b4746c
* **Python:** 3.9.7
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
