### ISSUE TITLE
Spack loses track of installs when a build fails

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#1891]
When a build fails, it seems that spack is losing track of some installs:

```
==> freetype is already installed in /Users/kitware/code/depot/group-bld/spack/src/opt/spack/darwin-yosemite-x86_64/clang-7.0.2-apple/freetype-2.5.3-7o6h6oqs55ndcejmrnrtxg2l6ic4xo5l
Traceback (most recent call last):
  File "bin/spack", line 192, in <module>
    main()
  File "bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/cmd/install.py", line 92, in install
    explicit=True)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/package.py", line 934, in do_install
    dirty=dirty)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/package.py", line 1085, in do_install_dependencies
    dep.package.do_install(**kwargs)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/package.py", line 915, in do_install
    rec = spack.installed_db.get_record(self.spec)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/database.py", line 78, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/database.py", line 526, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/Users/kitware/code/depot/group-bld/spack/src/lib/spack/spack/database.py", line 521, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! freetype@2.5.3%clang@7.0.2-apple arch=darwin-yosemite-x86_64^libpng@1.6.24%clang@7.0.2-apple arch=darwin-yosemite-x86_64^zlib@1.2.8%clang@7.0.2-apple arch=darwin-yosemite-x86_64'
```

A `spack reindex` fixes things.

**Comment by adamjstewart** [comment]
Duplicate of #1266.

**Comment by mathstuf** [comment]
Continuing discussion over there.
