### ISSUE TITLE
Update buildcache keys index on S3 fails if there are no keys

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#19220]
Running `spack buildcache update-index --keys` or `spack buildcache create --rebuild-index` fails with a stack trace if the mirror doesn't have any keys.  However, it seems like it should not be an error to attempt to update the keys index if there are no keys, instead spack should just print a warning indicating there were no keys found and not exit with an error code or exception.

### Steps to reproduce the issue

```console
root@5bcb4d8da0f8:/# spack --version
0.15.4-1311-09d0623be
root@5bcb4d8da0f8:/work# spack mirror add amirror s3://some-bucket/mirror-with-no-keys
root@5bcb4d8da0f8:/# spack -d buildcache update-index --keys -d s3://some-bucket/mirror-with-no-keys
==> [2020-10-07-15:16:41.028326] Imported buildcache from built-in commands
==> [2020-10-07-15:16:41.031261] Imported buildcache from built-in commands
==> [2020-10-07-15:16:41.032513] Reading config file /work/spack/etc/spack/defaults/mirrors.yaml
==> [2020-10-07-15:16:41.034770] Reading config file /root/.spack/mirrors.yaml
==> [2020-10-07-15:16:41.036442] Reading config file /root/.spack/linux/mirrors.yaml
==> [2020-10-07-15:16:41.038776] Reading config file /work/spack/etc/spack/defaults/config.yaml
==> [2020-10-07-15:16:41.058556] DATABASE LOCK TIMEOUT: 3s
==> [2020-10-07-15:16:41.058654] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/work/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/work/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/work/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/work/spack/lib/spack/spack/cmd/buildcache.py", line 793, in buildcache
    args.func(args)
  File "/work/spack/lib/spack/spack/cmd/buildcache.py", line 781, in buildcache_update_index
    url_util.join(outdir, bindist.build_cache_relative_path()))
  File "/work/spack/lib/spack/spack/binary_distribution.py", line 303, in generate_package_index
    for entry in web_util.list_url(cache_prefix)
  File "/work/spack/lib/spack/spack/util/web.py", line 321, in list_url
    for key in _iter_s3_prefix(s3, url)))
  File "/work/spack/lib/spack/spack/util/web.py", line 320, in <genexpr>
    key.split('/', 1)[0]
  File "/work/spack/lib/spack/spack/util/web.py", line 289, in _iter_s3_prefix
    client, bucket, prefix, num_entries, start_after=key)
  File "/work/spack/lib/spack/spack/util/web.py", line 277, in _list_s3_objects
    iter = _iter_s3_contents(result['Contents'], prefix)
KeyError: 'Contents'
```

### Information on your system

```
root@5bcb4d8da0f8:/# spack debug report
* **Spack:** 0.15.4-1311-09d0623be
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-haswell
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
FYI @opadron

**Comment by scottwittenburg** [comment]
So I just realized this one is for the buildcache index, but the same thing happens with the gpg keys index.  I was thinking I'll post another stack trace here, since these are so similar it's maybe not worth making a second issue?

**Comment by scottwittenburg** [comment]
Here's a reproducer and stack trace from the key index update failure:

```
root@5bcb4d8da0f8:/# spack mirror add amirror s3://spack-mirrors/test/bincache-no-keys
root@5bcb4d8da0f8:/# spack install pkgconf 
==> Installing pkgconf
==> No binary for pkgconf found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/b8/b846aea51cf696c3392a0ae58bef93e2e72f8e7073ca6ad1ed8b01c85871f9c0.tar.xz
######################################################################################################################################################################################################################################## 100.0%
==> pkgconf: Executing phase: 'autoreconf'
==> pkgconf: Executing phase: 'configure'
==> pkgconf: Executing phase: 'build'
==> pkgconf: Executing phase: 'install'
[+] /work/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/pkgconf-1.7.3-dmeftucgcnnhvol5oan7gpurhryovh2c
root@5bcb4d8da0f8:/# spack buildcache create -u -a --mirror-url s3://spack-mirrors/test/bincache-no-keys pkgconf
==> Buildcache files will be output to s3://spack-mirrors/test/bincache-no-keys/build_cache
root@5bcb4d8da0f8:/# spack -d buildcache update-index --keys --mirror-url s3://spack-mirrors/test/bincache-no-keys            
==> [2020-10-07-15:47:59.871815] Imported buildcache from built-in commands
==> [2020-10-07-15:47:59.874622] Imported buildcache from built-in commands
==> [2020-10-07-15:47:59.875441] Reading config file /work/spack/etc/spack/defaults/mirrors.yaml
==> [2020-10-07-15:47:59.877691] Reading config file /root/.spack/mirrors.yaml
==> [2020-10-07-15:47:59.879222] Reading config file /root/.spack/linux/mirrors.yaml
==> [2020-10-07-15:47:59.881073] Reading config file /work/spack/etc/spack/defaults/config.yaml
==> [2020-10-07-15:47:59.901010] DATABASE LOCK TIMEOUT: 3s
==> [2020-10-07-15:47:59.901121] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-10-07-15:48:00.713640] Retrieving spec.yaml files from s3://spack-mirrors/test/bincache-no-keys/build_cache to build index
==> [2020-10-07-15:48:00.714289] fetching s3://spack-mirrors/test/bincache-no-keys/build_cache/linux-ubuntu18.04-x86_64-gcc-7.3.0-pkgconf-1.7.3-dmeftucgcnnhvol5oan7gpurhryovh2c.spec.yaml
==> [2020-10-07-15:48:01.995405] Retrieving key.pub files from s3://spack-mirrors/test/bincache-no-keys/build_cache/_pgp to build key index
Traceback (most recent call last):
  File "/work/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/work/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/work/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/work/spack/lib/spack/spack/cmd/buildcache.py", line 793, in buildcache
    args.func(args)
  File "/work/spack/lib/spack/spack/cmd/buildcache.py", line 788, in buildcache_update_index
    bindist.generate_key_index(keys_url)
  File "/work/spack/lib/spack/spack/binary_distribution.py", line 350, in generate_key_index
    for entry in web_util.list_url(key_prefix, recursive=False)
  File "/work/spack/lib/spack/spack/util/web.py", line 321, in list_url
    for key in _iter_s3_prefix(s3, url)))
  File "/work/spack/lib/spack/spack/util/web.py", line 320, in <genexpr>
    key.split('/', 1)[0]
  File "/work/spack/lib/spack/spack/util/web.py", line 289, in _iter_s3_prefix
    client, bucket, prefix, num_entries, start_after=key)
  File "/work/spack/lib/spack/spack/util/web.py", line 277, in _list_s3_objects
    iter = _iter_s3_contents(result['Contents'], prefix)
KeyError: 'Contents'
```

**Comment by scottwittenburg** [comment]
@eugeneswalker If you run into something like this when you're implementing a command to update only the key index, ping me, as I already have a proposed fix in a branch.

**Comment by alalazo** [comment]
@scottwittenburg Is this still an issue? Or can we close it?

**Comment by scottwittenburg** [comment]
I just tested it, this seems to be fixed.
