### ISSUE TITLE
Lammps build for GPU fails

### ISSUE THREAD

**Issue by thomasbrTTU** [LLNL/spack#19440]
Trying to build lammps for the NVIDIA V100 GPU and I receive different errors. Using gcc@8.3.1 and cuda@10.2.89. Would like to be able to build with gcc@10.1.0 but receive other errors. Thanks

### Steps to reproduce the issue
```console
$ spack install openmpi@4.0.4%gcc@8.3.1 +cuda fabrics=ucx +legacylaunchers +pmi schedulers=slurm +thread_multiple ^ucx@1.9.0 ^cuda@10.2.89
$ spack install lammps +cuda +exceptions +granular +kokkos +kspace +latte +manybody +mc +misc +molecule +mpi +mpiio +peri +poems +python +qeq +replica +rigid +shock +snap +spin +srd +user-atc +user-h5md +user-lb +user-meamc +user-misc +user-netcdf +user-omp +user-reaxc +voronoi cuda_arch=70 ^netcdf-c %gcc@8.3.1 ^hdf5 %gcc@8.3.1 +hl+fortran+szip ^openmpi@4.0.4/7vlewfj ^kokkos@3.1.01 ^cuda@10.2.89
```
### Error Message
The error message varies.
RUN 1 and 2: ==> Error: Package cuda does not depend on x or z
RUN 3: ==> Error: Package cuda does not depend on l, i, b, i, c, o, n, or v
RUN 4 and 5: ==> Error: Package cuda does not depend on z, l, i, or b
```console
$ spack --debug --stacktrace install lammps +cuda +exceptions +granular +kokkos +kspace +latte +manybody +mc +misc +molecule +mpi +mpiio +peri +poems +python +qeq +replica +rigid +shock +snap +spin +srd +user-atc +user-h5md +user-lb +user-meamc +user-misc +user-netcdf +user-omp +user-reaxc +voronoi cuda_arch=70 ^netcdf-c %gcc@8.3.1 ^hdf5 %gcc@8.3.1 +hl+fortran+szip ^openmpi@4.0.4/7vlewfj ^kokkos@3.1.01 ^cuda@10.2.89
lib/spack/spack/cmd/__init__.py:122 ==> [2020-10-21-08:32:44.991354] Imported install from built-in commands
lib/spack/spack/config.py:872 ==> [2020-10-21-08:32:45.049579] Reading config file /home/thomasbr/acceptance-tests/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:122 ==> [2020-10-21-08:32:45.080056] Imported install from built-in commands
lib/spack/spack/database.py:362 ==> [2020-10-21-08:32:45.240649] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:366 ==> [2020-10-21-08:32:45.241276] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:872 ==> [2020-10-21-08:32:45.534020] Reading config file /home/thomasbr/acceptance-tests/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/cmd/install.py:339 ==> [2020-10-21-08:32:45.692164] SpackError: Package cuda does not depend on x or z
lib/spack/spack/main.py:765 ==> [2020-10-21-08:32:45.692446] SpackError: Package cuda does not depend on x or z
lib/spack/spack/error.py:55 ==> [2020-10-21-08:32:45.712948] Error: Package cuda does not depend on x or z
Traceback (most recent call last):
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/spec.py", line 2224, in concretize
    user_spec_deps = self.flat_dependencies(copy=False)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/spec.py", line 2415, in flat_dependencies
    flat_deps[spec.name].constrain(spec)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/spec.py", line 2836, in constrain
    changed |= self._constrain_dependencies(other)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/spec.py", line 2863, in _constrain_dependencies
    dep_spec_copy = other.get_dependency(name)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/spec.py", line 1054, in get_dependency
    raise InvalidDependencyError(self.name, name)
spack.spec.InvalidDependencyError: Package cuda does not depend on x or z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/cmd/install.py", line 337, in install
    args.spec, concretize=True, tests=tests)
  File "/home/thomasbr/acceptance-tests/spack/lib/spack/spack/cmd/__init__.py", line 181, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Package cuda does not depend on x or z
```
### Information on your system

$ spack debug report
* **Spack:** 0.15.4-1480-a9d25ea01
* **Python:** 3.6.8
* **Platform:** linux-centos8-zen2

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Unfortunately I'm not able to reproduce this on macOS.

> RUN 1 and 2: ==> Error: Package cuda does not depend on x or z
> RUN 3: ==> Error: Package cuda does not depend on l, i, b, i, c, o, n, or v
> RUN 4 and 5: ==> Error: Package cuda does not depend on z, l, i, or b

This error message usually means that there is a package in Spack that uses something like:
```python
depends_on('foo ^bar')
```
`depends_on` cannot handle dependencies of dependencies at the moment. I believe I removed most if not all of those in #18220, but if you find more please submit a PR to fix those.

**Comment by thomasbrTTU** [comment]
We were able to eventually get the build to work using the following spec

lammps@20200505 +cuda cuda_arch=70 +cuda_mps +exceptions +granular +kspace +kokkos
      +latte +manybody +mc +misc +molecule +mpi +mpiio +peri +poems +python +qeq +replica
      +rigid +shock +snap +spin +srd +user-atc +user-h5md +user-lb +user-meamc +user-misc
      +user-netcdf +user-omp +user-reaxc +voronoi ^openblas@0.3.10 threads=openmp
      ^netcdf-c@4.7.3 +mpi +parallel-netcdf ^parallel-netcdf@1.12.1 ~cxx ~fortran
      ^hdf5@1.10.6 +fortran +mpi +hl +threadsafe +szip ^kokkos@3.1.01 +cuda cuda_arch=70
      +cuda_uvm +cuda_lambda +openmp +wrapper ^fftw@3.3.8 +mpi +openmp +pfft_patches

Thanks
