### ISSUE TITLE
Problem with py-pep8

### ISSUE THREAD

**Issue by Rombur** [LLNL/spack#1960]
I think that #1883 broke spack for me. It looks like py-pep8 is in a weird state on my machine. I cannot uninstall it, I get this error `==> Error: Package py-pep8 not found.` but `spack find` shows it is still there. I don't really care except that I can't run `spack module refresh` because I get  `==> Error: Package py-pep8 not found.`

**Comment by adamjstewart** [comment]
Yes, sorry about that. I renamed the `py-pep8` package because the upstream developers did. You can get things working again by manually deleting `py-pep8` (go to the installation directory and give it a good ol' `rm -rf`) and run `spack reindex`. That should do the trick.

**Comment by Rombur** [comment]
I don't know if I deleted something wrong but now `spack module refresh` crashes with:

Traceback (most recent call last):
  File "/home/bt2/spack/bin/spack", line 192, in <module>
    main()
  File "/home/bt2/spack/bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/home/bt2/spack/lib/spack/spack/cmd/module.py", line 251, in module
    callbacks[args.subparser_name](module_type, args.specs, args)
  File "/home/bt2/spack/lib/spack/spack/cmd/module.py", line 216, in refresh
    file2writer[item.file_name].append(item)
  File "/home/bt2/spack/lib/spack/spack/modules.py", line 551, in file_name
    return join_path(self.path, self.spec.architecture, self.use_name)
  File "/home/bt2/spack/lib/spack/spack/modules.py", line 304, in use_name
    naming_tokens = self.tokens
  File "/home/bt2/spack/lib/spack/spack/modules.py", line 286, in tokens
    'prefix': self.spec.package.prefix
  File "/home/bt2/spack/lib/spack/spack/package.py", line 688, in prefix
    return self.spec.prefix
  File "/home/bt2/spack/lib/spack/spack/spec.py", line 963, in prefix
    return Prefix(spack.install_layout.path_for_spec(self))
  File "/home/bt2/spack/lib/spack/spack/directory_layout.py", line 124, in path_for_spec
    _check_concrete(spec)
  File "/home/bt2/spack/lib/spack/spack/directory_layout.py", line 42, in _check_concrete
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!

**Comment by adamjstewart** [comment]
Hmm, did you have anything that depended on `py-pep8`? You may have to delete/reinstall that too.

**Comment by Rombur** [comment]
Yes, I had ```py-autopep8``` but I deleted it.

**Comment by adamjstewart** [comment]
Unfortunately, I've never used Spack's module support. Perhaps @alalazo could comment on this.

**Comment by alalazo** [comment]
@Rombur Are you allowed to : 

1. Checkout a previous commit (I mean pre #1883)
3. `spack reindex`
2. `spack uninstall -a -d py-pep8 #Hopefully will remove py-pep8 and any dependee`
3. Checkout latest develop
4. `spack reindex`
5. `spack module refresh`

?

The error there seems more due to the fact that an installed module cannot be found rather than some error in the module generation logic...

**Comment by Rombur** [comment]
It didn't work because `py-pep8` was already removed :-( I will try find if there is still a dependence by hand

**Comment by Rombur** [comment]
Well I ended up nuking everything..
