### ISSUE TITLE
OS X: "spack find" with new spack clone gives "Bad file descriptor"

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#1966]
(I initially put this in the comment of #1904)

On OSX I follow these steps:
* Clone new repo 
* No packages are installed 
* Try to find packages as:
```bash
$ git clone https://github.com/llnl/spack.git spack-llnl
Cloning into 'spack-llnl'...
remote: Counting objects: 44080, done.
................

 $ cd spack-llnl/

$ ./bin/spack find
Traceback (most recent call last):
  File "./bin/spack", line 192, in <module>
    main()
  File "./bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/Users/kumbhar//spack-llnl/lib/spack/spack/cmd/find.py", line 148, in find
    specs = set(spack.installed_db.query(**q_args))
  File "/Users/kumbhar//spack-llnl/lib/spack/spack/database.py", line 630, in query
    with self.read_transaction():
  File "/Users/kumbhar//spack-llnl/lib/spack/llnl/util/lock.py", line 219, in __enter__
    self._as = self._acquire_fn()
  File "/Users/kumbhar//spack-llnl/lib/spack/spack/database.py", line 447, in _read
    self.reindex(spack.install_layout)
  File "/Users/kumbhar//spack-llnl/lib/spack/spack/database.py", line 351, in reindex
    with transaction:
  File "/Users/kumbhar//spack-llnl/lib/spack/llnl/util/lock.py", line 218, in __enter__
    if self._enter() and self._acquire_fn:
  File "/Users/kumbhar//spack-llnl/lib/spack/llnl/util/lock.py", line 249, in _enter
    return self._lock.acquire_write(self._timeout)
  File "/Users/kumbhar//spack-llnl/lib/spack/llnl/util/lock.py", line 142, in acquire_write
    self._lock(fcntl.LOCK_EX, timeout)   # can raise LockError.
  File "/Users/kumbhar//spack-llnl/lib/spack/llnl/util/lock.py", line 84, in _lock
    fcntl.lockf(self._fd, op | fcntl.LOCK_NB)
IOError: [Errno 9] Bad file descriptor
```
* Once you install first package, this doesn't appear.
* Doesn't happen on linux/other platforms

**Comment by tgamblin** [comment]
Fixed by #1562
