### ISSUE TITLE
Patching stages relies on side effects from memoization

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#19670]
While debugging #19501 I ran into issues evaluating the `Spec.patches` properties. Trying to debug those issues I noticed that our mechanism for applying patches relies on side effects from memoization to change the `Patch.path` attribute to the right object.

This behavior has been introduced in #10150 The line that adds the path to the patch objects is:

https://github.com/spack/spack/blob/b2d6c634216a0ee2f0532372456ad389dd6fb427/lib/spack/spack/patch.py#L210

Without memoization a temporary object is returned and the path applied to it is not reflected in the spec from which it originated.

### Steps to reproduce the issue
Remove `lang.memoized` from the following lines in `spec.py`:

https://github.com/spack/spack/blob/b2d6c634216a0ee2f0532372456ad389dd6fb427/lib/spack/spack/spec.py#L3065-L3067

and then try to apply patches to any package that needs them:
```console
$ spack  patch findutils
==> Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/de/ded4c9f73731cd48fec3b6bdaccce896473b6d8e337e9612e16cf1431bb1169d.tar.gz
==> Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/84/84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e
==> Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/bd/bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2
==> Error: Path for patch not set in apply: https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-fflush.patch
```

### Error Message
The stacktrace for the failing command is:

<details>
<summary> spack -d --stacktrace patch findutils</summary>

```console
$ spack -d --stacktrace patch findutils
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-02-08:42:42.396634] Imported patch from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-02-08:42:42.397771] Imported patch from built-in commands
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.401526] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.420934] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.421465] Reading config file /home/culpo/.spack/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.423318] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.516144] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:42.548992] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/compilers.yaml
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.674482] ncurses applying constraint pkgconfig
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.675302] readline applying constraint ncurses
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.676141] gdbm applying constraint readline
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.678408] perl applying constraint gdbm
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.679164] perl applying constraint berkeley-db
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.679957] autoconf applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.680734] autoconf applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.683592] automake applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.684398] automake applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.689418] libtool applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.690602] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.694274] texinfo applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.695181] findutils applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.696079] findutils applying constraint automake
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.696891] findutils applying constraint libtool
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.697641] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.698399] findutils applying constraint texinfo
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.769016] findutils applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.769856] autoconf applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.770652] autoconf applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.771359] perl applying constraint gdbm
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.772075] gdbm applying constraint readline
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.772833] readline applying constraint ncurses
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.773536] ncurses applying constraint pkgconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.774282] perl applying constraint berkeley-db
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.775068] findutils applying constraint automake
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.775816] automake applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.776670] automake applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.777354] findutils applying constraint libtool
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.778099] libtool applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.779129] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.779875] findutils applying constraint texinfo
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.780967] texinfo applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.852062] findutils applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.852898] autoconf applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.856322] m4 applying constraint libsigsegv
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.857054] autoconf applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.857978] perl applying constraint gdbm
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.858743] gdbm applying constraint readline
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.859574] readline applying constraint ncurses
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.860627] ncurses applying constraint pkgconf@1.7.3%gcc@10.2.0 arch=linux-ubuntu18.04-broadwell
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.861665] perl applying constraint berkeley-db
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.862481] autoconf applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.863263] autoconf applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.864291] findutils applying constraint automake
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.865135] automake applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.866011] automake applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.866724] findutils applying constraint libtool
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.867496] libtool applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.868530] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.869237] findutils applying constraint texinfo
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.869977] texinfo applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.870781] findutils applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.871482] findutils applying constraint automake
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.872173] findutils applying constraint libtool
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.872923] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.873624] findutils applying constraint texinfo
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.940126] findutils applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.941015] autoconf applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.941858] m4 applying constraint libsigsegv
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.942665] autoconf applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.943529] perl applying constraint gdbm
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.944274] gdbm applying constraint readline
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.945050] readline applying constraint ncurses
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.946029] ncurses applying constraint pkgconf@1.7.3%gcc@10.2.0 arch=linux-ubuntu18.04-broadwell
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.947081] perl applying constraint berkeley-db
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.947811] findutils applying constraint automake
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.948574] automake applying constraint autoconf
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.949303] automake applying constraint perl
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.950001] findutils applying constraint libtool
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.950818] libtool applying constraint m4@1.4.6:
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.951927] findutils applying constraint m4
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.953080] findutils applying constraint texinfo
lib/spack/spack/spec.py:2597 ==> [2020-11-02-08:42:42.954042] texinfo applying constraint perl
lib/spack/spack/spec.py:2316 ==> [2020-11-02-08:42:43.018010] Ordered hashes [findutils]: findutils/0/84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e, findutils/1/bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2
lib/spack/spack/spec.py:2316 ==> [2020-11-02-08:42:43.018454] Ordered hashes [m4]: m4/3/3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00, m4/9/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
lib/spack/spack/spec.py:2316 ==> [2020-11-02-08:42:43.018814] Ordered hashes [gdbm]: gdbm/14/7f569b9287e9e5a4236636eef32ff3428f0462ec17aea359e0ebee07649f1f16
lib/spack/spack/spec.py:2316 ==> [2020-11-02-08:42:43.019267] Ordered hashes [texinfo]: texinfo/20/1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1, texinfo/23/12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a
lib/spack/spack/database.py:362 ==> [2020-11-02-08:42:43.021835] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:366 ==> [2020-11-02-08:42:43.022112] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/stage.py:312 ==> [2020-11-02-08:42:43.106177] Creating stage lock spack-stage-findutils-4.6.0-6wex3ldlbkrkb5xx4hublbfo4gg2ahfq
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:43.107382] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:43.109470] Reading config file /home/culpo/.spack/mirrors.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-08:42:43.111579] Reading config file /home/culpo/.spack/linux/mirrors.yaml
lib/spack/spack/fetch_strategy.py:582 ==> [2020-11-02-08:42:43.128733] Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/de/ded4c9f73731cd48fec3b6bdaccce896473b6d8e337e9612e16cf1431bb1169d.tar.gz
lib/spack/spack/stage.py:312 ==> [2020-11-02-08:42:43.146652] Creating stage lock spack-stage-zizdxm8j
lib/spack/spack/fetch_strategy.py:582 ==> [2020-11-02-08:42:43.148120] Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/84/84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e
lib/spack/spack/stage.py:312 ==> [2020-11-02-08:42:43.148617] Creating stage lock spack-stage-r_iuxl61
lib/spack/spack/fetch_strategy.py:582 ==> [2020-11-02-08:42:43.149896] Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/bd/bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2
lib/spack/spack/stage.py:593 ==> [2020-11-02-08:42:43.150274] Already staged spack-stage-findutils-4.6.0-6wex3ldlbkrkb5xx4hublbfo4gg2ahfq in /tmp/pytest-of-culpo/pytest-89/mock-stage0/spack-stage-findutils-4.6.0-6wex3ldlbkrkb5xx4hublbfo4gg2ahfq
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/patch.py", line 32, in patch
    package.do_patch()
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/package.py", line 1346, in do_patch
    patch.apply(self.stage)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/patch.py", line 81, in apply
    "Path for patch not set in apply: %s" % self.path_or_url)
AssertionError: Path for patch not set in apply: https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-fflush.patch
```
</details>

### Information on your system

* **Spack:** 0.15.4-1768-b2d6c63421
* **Python:** 3.8.5
* **Platform:** linux-ubuntu18.04-broadwell

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed in #20384
