### ISSUE TITLE
can't seem to set swr on mesa

### ISSUE THREAD

**Issue by joequant** [LLNL/spack#19674]
```
spack spec mesa swr=none
```
### Error message

```
[user@9126c7eb0f3d packages]$ spack spec mesa swr=none
Input spec
--------------------------------
mesa swr=none

Concretized
--------------------------------
==> Error: Unexpected token: '='
```

```console
$ spack --debug --stacktrace <command>
```
```
lib/spack/spack/main.py:765 ==> [2020-11-02-11:34:45.940136] SpecParseError: Unexpected token: '='
lib/spack/spack/error.py:55 ==> [2020-11-02-11:34:45.940396] Error: Unexpected token: '='
Traceback (most recent call last):
  File "/usr/lib/spack/spack/spec.py", line 4181, in do_parse
    self.unexpected_token()
  File "/usr/lib/spack/spack/parse.py", line 131, in unexpected_token
    self.next_token_error("Unexpected token: '%s'" % self.next.value)
  File "/usr/lib/spack/spack/parse.py", line 124, in next_token_error
    raise ParseError(message, self.text, self.token.end)
spack.parse.ParseError: Unexpected token: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/usr/lib/spack/spack/cmd/spec.py", line 103, in spec
    spec.concretize()
  File "/usr/lib/spack/spack/spec.py", line 2239, in concretize
    self._concretize_helper(concretizer))
  File "/usr/lib/spack/spack/spec.py", line 2081, in _concretize_helper
    concretizer.concretize_variants(self)))
  File "/usr/lib/spack/spack/concretize.py", line 354, in concretize_variants
    preferred_variants = PackagePrefs.preferred_variants(spec.name)
  File "/usr/lib/spack/spack/package_prefs.py", line 151, in preferred_variants
    spec = spack.spec.Spec("%s %s" % (pkg_name, variants))
  File "/usr/lib/spack/spack/spec.py", line 1019, in __init__
    spec_list = SpecParser(self).parse(spec_like)
  File "/usr/lib/spack/spack/parse.py", line 152, in parse
    return self.do_parse()
  File "/usr/lib/spack/spack/spec.py", line 4184, in do_parse
    raise SpecParseError(e)
spack.spec.SpecParseError: Unexpected token: '='

```
### Information on your system

[user@9126c7eb0f3d packages]$ spack debug report
* **Spack:** 0.15.4
* **Python:** 3.8.5
* **Platform:** linux-mageia8-skylake

### Additional information

- [X ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ X] I have searched the issues of this repo and believe this is not a duplicate
- [ X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
I'm having trouble replicating this issue on my current setup

```
* **Spack:** 0.15.4-1772-62eab8923         # latest spack as of this morning
* **Python:** 3.8.2
* **Platform:** darwin                     # Mac OS
```

So I have a couple questions:

* Are you able to replicate this on the latest Spack?
* Could you mention what shell program you are using (e.g. bash)?
* Has this worked for you recently?

Thanks!

**Comment by joequant** [comment]
spack install mesa -llvm swr=none

works

spack install mesa -llvm~swr=none
spack install mesa -llvm+swr=none

doesn't

**Comment by alalazo** [comment]
@joequant Both:
```console
$ spack install mesa -llvm~swr=none
$ spack install mesa -llvm+swr=none
```
are syntax errors since you can't mix Boolean variants like `+swr` with key/value variants like `swr=none`. What was your intent when typing `+swr=none`?
