### ISSUE TITLE
bug: spack install from multiple spec hashes fails

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#19694]
When I try to install a package using explicit dependencies `foo ^bar/abcdef ^baz/012345` it fails to concretize and claims to detect uninstalled dependencies (the common dependents of `bar` and `baz`). However, installing `foo` works, even when both `bar/abcdef` and `baz/012345` are direct (and installed) dependencies.

I think this is related to #15219.

### Steps to reproduce the issue

I added a new package `foo` with
```python
    depends_on('hdf5~mpi')
    depends_on('libpng')
```

The concretized spec for `foo` is:
```console
 -   5iwbwrj  foo@1.2.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
[+]  ge6mzmk      ^hdf5@1.10.7%apple-clang@12.0.0~cxx~debug~fortran~hl~java~mpi+pic+shared~szip~threadsafe api=none arch=darwin-catalina-x86_64
[+]  x2anksg          ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
[+]  mt5wqvh      ^libpng@1.6.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
```

Installing works (until the actual mock `make` command anyway) for `foo`, `foo ^hdf5/ge6mzmk`, `foo ^zlib/x2anksg`, and 
`foo ^libpng/mt5wqvh`, but fails when `foo ^hdf5/ge6mzmk ^libpng/mt5wqvh`.

### Error Message

```console
$ spack --debug --stacktrace install foo ^hdf5/ge6mzmk ^libpng/mt5wqvh
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-02-18:39:16.762346] Imported install from built-in commands
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.769411] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.786831] Reading config file /rnsdhpc/code/spack/etc/spack/config.yaml
lib/spack/spack/config.py:602 ==> [2020-11-02-18:39:16.788908] OUTDATED CONFIGURATION FILE [section=config, scope=site, dir=/rnsdhpc/code/spack/etc/spack]
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-02-18:39:16.789385] Imported install from built-in commands
lib/spack/spack/database.py:361 ==> [2020-11-02-18:39:16.794409] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:365 ==> [2020-11-02-18:39:16.794694] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.825528] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.827463] Reading config file /rnsdhpc/code/spack/etc/spack/repos.yaml
lib/spack/spack/spec.py:2632 ==> [2020-11-02-18:39:16.902038] foo applying constraint hdf5~mpi
lib/spack/spack/spec.py:2632 ==> [2020-11-02-18:39:16.903320] foo applying constraint libpng
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.907435] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.928496] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/darwin/packages.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.933057] Reading config file /rnsdhpc/code/spack/etc/spack/packages.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.960574] Reading config file /Users/s3j/.spack/packages.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.989061] Reading config file /rnsdhpc/code/spack/etc/spack/compilers.yaml
lib/spack/spack/config.py:909 ==> [2020-11-02-18:39:16.998410] Reading config file /Users/s3j/.spack/darwin/compilers.yaml
lib/spack/spack/spec.py:2632 ==> [2020-11-02-18:39:17.021217] foo applying constraint hdf5~mpi
lib/spack/spack/spec.py:2632 ==> [2020-11-02-18:39:17.032756] foo applying constraint libpng
lib/spack/spack/installer.py:1013 ==> [2020-11-02-18:39:17.041312] Initializing the build queue for foo
lib/spack/spack/installer.py:960 ==> [2020-11-02-18:39:17.061970] Acquiring a write lock on zlib with timeout 1e-09
lib/spack/spack/stage.py:312 ==> [2020-11-02-18:39:17.064047] Creating stage lock spack-stage-zlib-1.2.11-x2anksgssxsxa7pcnhzg5k3dhgacglze
lib/spack/spack/installer.py:1406 ==> [2020-11-02-18:39:17.068035] Flagging zlib as installed
lib/spack/spack/installer.py:1411 ==> [2020-11-02-18:39:17.068241] Removing zlib from hdf5's uninstalled dependencies.
lib/spack/spack/installer.py:1779 ==> [2020-11-02-18:39:17.068399] hdf5: Removed zlib from uninstalled deps list: set()
lib/spack/spack/installer.py:976 ==> [2020-11-02-18:39:17.069012] Downgrading to a read lock on zlib with timeout 1e-09
lib/spack/spack/installer.py:1406 ==> [2020-11-02-18:39:17.069243] Flagging zlib as installed
lib/spack/spack/installer.py:1411 ==> [2020-11-02-18:39:17.069440] Removing zlib from hdf5's uninstalled dependencies.
[+] /rnsdhpc/code/spack/opt/spack/apple-clang/zlib/x2anksg
lib/spack/spack/installer.py:960 ==> [2020-11-02-18:39:17.070664] Acquiring a write lock on hdf5 with timeout 1e-09
lib/spack/spack/stage.py:312 ==> [2020-11-02-18:39:17.071725] Creating stage lock spack-stage-hdf5-1.10.7-ge6mzmkatyxcasyznj2bnmvmvwgytu7r
lib/spack/spack/installer.py:1406 ==> [2020-11-02-18:39:17.080558] Flagging hdf5 as installed
lib/spack/spack/installer.py:1411 ==> [2020-11-02-18:39:17.080755] Removing hdf5 from foo's uninstalled dependencies.
lib/spack/spack/installer.py:1779 ==> [2020-11-02-18:39:17.080919] foo: Removed hdf5 from uninstalled deps list: {'libpng'}
lib/spack/spack/installer.py:976 ==> [2020-11-02-18:39:17.081499] Downgrading to a read lock on hdf5 with timeout 1e-09
lib/spack/spack/installer.py:1406 ==> [2020-11-02-18:39:17.081715] Flagging hdf5 as installed
lib/spack/spack/installer.py:1411 ==> [2020-11-02-18:39:17.081854] Removing hdf5 from foo's uninstalled dependencies.
[+] /rnsdhpc/code/spack/opt/spack/apple-clang/hdf5/ge6mzmk
lib/spack/spack/installer.py:1481 ==> [2020-11-02-18:39:17.082446] Error: Detected uninstalled dependencies for libpng: {'zlib'}
lib/spack/spack/main.py:765 ==> [2020-11-02-18:39:17.082607] InstallError: Cannot proceed with libpng: 1 uninstalled dependency: zlib
lib/spack/spack/error.py:55 ==> [2020-11-02-18:39:17.083894] Error: Cannot proceed with libpng: 1 uninstalled dependency: zlib
Traceback (most recent call last):
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/rnsdhpc/code/spack/lib/spack/spack/cmd/install.py", line 405, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/rnsdhpc/code/spack/lib/spack/spack/cmd/install.py", line 256, in install_spec
    spec.package.do_install(**kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/package.py", line 1602, in do_install
    builder.install(**kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/installer.py", line 1484, in install
    raise InstallError(
spack.installer.InstallError: Cannot proceed with libpng: 1 uninstalled dependency: zlib
```

Interestingly, when concretizing with the offending spec, `zlib` is written in the concretization twice:
```
$ spack spec -Il foo ^hdf5/ge6mzmk ^libpng/mt5wqvh
Input spec
--------------------------------
 -   foo
[+]      ^hdf5@1.10.7%apple-clang@12.0.0~cxx~debug~fortran~hl~java~mpi+pic+shared~szip~threadsafe api=none arch=darwin-catalina-x86_64
[+]          ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
[+]      ^libpng@1.6.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
[+]          ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64

Concretized
--------------------------------
 -   5iwbwrj  foo@1.2.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
[+]  ge6mzmk      ^hdf5@1.10.7%apple-clang@12.0.0~cxx~debug~fortran~hl~java~mpi+pic+shared~szip~threadsafe api=none arch=darwin-catalina-x86_64
[+]  x2anksg          ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
[+]  mt5wqvh      ^libpng@1.6.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
[+]  x2anksg          ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.15.4-1776-b4ea74c11
* **Python:** 3.8.3
* **Platform:** darwin-catalina-skylake
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
This was fixed at some point :)
