### ISSUE TITLE
0 cached builds after `buildcache create` error

### ISSUE THREAD

**Issue by milljm** [LLNL/spack#19825]
### Steps to reproduce the issue

```console
$ spack install foo
$ spack buildcache create --rebuild-index -a -k mirror -m mirror /foo-hash
$ spack buildcache list -a
==> 1 cached builds.
<trimmed>
$ spack install bar
$ spack buildcache create -rebuild-index -a -k mirror -m mirror /bar-hash
--------------------------^ accidentally used wrong switch
$ spack buildcache list -a
==> 0 cached builds.

# repeated attempts at rebuilding the index does not solve the issue:
$ spack buildcache update-index -d file:///path/to/mirror
<takes it's time as if processing data, no errors>
$ spack buildcache list -a
==> 0 cached builds.
```

### Error Message

```console
$ spack --debug --stacktrace buildcache create -rebuild-index -a -k mirror -m mirror /abc123
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-09-13:55:36.695807] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-09-13:55:36.699573] Imported buildcache from built-in commands
usage: spack buildcache create [-hrfua] [-k key]
                               (-d directory | -m mirror-name | --mirror-url mirror-url)
                               [--rebuild-index] [-y SPEC_YAML]
                               [--only {package,dependencies}]
                               ...
spack buildcache create: error: argument -r/--rel: ignored explicit argument 'ebuild-index'
lib/spack/spack/config.py:909 ==> [2020-11-09-13:55:36.702023] Reading config file /data/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-09-13:55:36.720273] Reading config file /home/test/.spack/config.yaml
Traceback (most recent call last):
  File "/data/spack/lib/spack/external/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/data/spack/lib/spack/external/argparse.py", line 1960, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/data/spack/lib/spack/external/argparse.py", line 1868, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -r/--rel: ignored explicit argument 'ebuild-index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/spack/lib/spack/spack/main.py", line 748, in main
    args, unknown = parser.parse_known_args()
  File "/data/spack/lib/spack/external/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/data/spack/lib/spack/external/argparse.py", line 1942, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/data/spack/lib/spack/external/argparse.py", line 1919, in consume_positionals
    take_action(action, args)
  File "/data/spack/lib/spack/external/argparse.py", line 1828, in take_action
    action(self, namespace, argument_values, option_string)
  File "/data/spack/lib/spack/external/argparse.py", line 1128, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/data/spack/lib/spack/external/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/data/spack/lib/spack/external/argparse.py", line 1942, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/data/spack/lib/spack/external/argparse.py", line 1919, in consume_positionals
    take_action(action, args)
  File "/data/spack/lib/spack/external/argparse.py", line 1828, in take_action
    action(self, namespace, argument_values, option_string)
  File "/data/spack/lib/spack/external/argparse.py", line 1128, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/data/spack/lib/spack/external/argparse.py", line 1761, in parse_known_args
    self.error(str(err))
  File "/data/spack/lib/spack/external/argparse.py", line 2392, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/data/spack/lib/spack/external/argparse.py", line 2380, in exit
    _sys.exit(status)
SystemExit: 2
```

### Information on your system

* **Spack:** 0.15.4-1807-a62f1834c
* **Python:** 3.7.3
* **Platform:** linux-centos7-zen2

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

### Workaround:

Once you encounter the error, if you add a new package correctly, the buildcache returns. Still, even with a failed `list` view, my other nodes continue to download items from the buildcache correctly. So really, the error is possibly with the `list` sub-command only. Making this far less critical than it first appears.

**Comment by milljm** [comment]
I would like to add; Even after deleting the index.json and index.json.hash files on the mirror, and instructing spack to rebuild the index, does not solve the issue. I have to add a new package correctly to get that list view back.

**Comment by scheibelp** [comment]
What does `spack mirror list` show?

Also, regarding 

`$ spack buildcache create --rebuild-index -a -k mirror -m mirror /foo-hash`

`-k mirror` looks odd to me: `-k` is supposed to specify a signing key (should be a file).

**Comment by milljm** [comment]
```bash
[CentOS-7.7][~]> spack mirror list
meowbuild       file:///data/mirror
spack-public    https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/
```

```bash
[CentOS-7.7][~]> spack gpg list
/data/spack/opt/spack/gpg/pubring.gpg
-------------------------------------
pub   4096R/2025CEAE 2020-10-19
uid                  meowbuild (GPG created for Spack) <jason.miller@inl.gov>
```

I have an internally named mirror that I didn't want to bother you all with. In my very early design of setting up this cluster, for use with Spack and Singularity, I decided to name the mirror the same as the cluster. So it then made since to name the key the same.

Without going into a lot of detail (and perhaps this is the source of my issue), I configure Singularity to map certain mount points to be made available within the instance to make managing Spack easier across the cluster (sharing of the ~/.spack folder, but not the /data/spack directory)

**Comment by scheibelp** [comment]
```
$ spack --debug --stacktrace buildcache create -rebuild-index -a -k mirror -m mirror /abc123
spack buildcache create: error: argument -r/--rel: ignored explicit argument 'ebuild-index'
```

Did you run this with `--rebuild-index`? Your output mentions `-rebuild-index` but for "full-word" option names you have to prefix with `--` (two dashes).

**Comment by scheibelp** [comment]
> Did you run this with --rebuild-index? Your output mentions -rebuild-index but for "full-word" option names you have to prefix with -- (two dashes).

I got a bit confused: your command line examples include cases with `--rebuild-index` and `-rebuild-index`, but the error output appears to be for `-rebuild-index` (EDIT: I accidentally said `--rebuild-index` when my whole point was that the error message was for the initial failed run with `-rebuild-index`). I think it would be more helpful to see error output for the invocation using `--rebuild-index` (or if you could explicitly mention that the error was not associated with the last command).

In any case, `spack buildcache update-index -d file:///path/to/mirror` works for me: I can add packages with `spack buildcache create` and I see the packages with `spack buildcache list` after `spack buildcache update-index`. This is on an ubuntu 18.04 docker image. 

> Without going into a lot of detail (and perhaps this is the source of my issue), I configure Singularity to map certain mount points to be made available within the instance to make managing Spack easier across the cluster (sharing of the ~/.spack folder, but not the /data/spack directory)

Can you replicate the issue in a locally-created mirror directory?

**Comment by milljm** [comment]
I purposefully used one dash, because I thought that was the originator of the issue I am experiencing... I am coming back now to possibly close this issue, because now it's more or less appearing to be random. Not exactly sure whats going on to be honest.

**Comment by milljm** [comment]
Posting in case it helps. What you are seeing is two consecutive runs of `spack --debug --stacktrace buildcache list -a` back-to-back. The first one works, the second fails:
```pre
[CentOS-7.7][~]> spack --debug --stacktrace buildcache list -a
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-10-08:41:03.721529] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-10-08:41:03.725298] Imported buildcache from built-in commands
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:03.726902] Reading config file /data/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:03.744309] Reading config file /home/moosetest/.spack/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:03.761727] Reading config file /data/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:03.763118] Reading config file /home/moosetest/.spack/mirrors.yaml
lib/spack/spack/binary_distribution.py:399 ==> [2020-11-10-08:41:03.771047] Fetching index from file:///data/mirror/build_cache/index.json
lib/spack/spack/binary_distribution.py:379 ==> [2020-11-10-08:41:04.032444] Unable to read index hash https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json.hash
  Download failed: HTTP Error 404: Not Found
  1
lib/spack/spack/binary_distribution.py:399 ==> [2020-11-10-08:41:04.033687] Fetching index from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json
lib/spack/spack/binary_distribution.py:407 ==> [2020-11-10-08:41:04.242157] Unable to read index https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json
  Download failed: HTTP Error 404: Not Found
  1
lib/spack/spack/database.py:362 ==> [2020-11-10-08:41:04.244157] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:366 ==> [2020-11-10-08:41:04.244285] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/cmd/buildcache.py:522 ==> [2020-11-10-08:41:04.311700] 215 cached builds.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
autoconf@2.69                automake@1.16.2      diffutils@3.7              gcc@5.1.0   gdbm@1.18.1     gperf@3.1  libgcrypt@1.8.5    libtool@2.4.6   mpc@1.1.0   ncurses@6.0  pkgconf@1.7.3  tcl@8.6.8    zstd@1.4.5
autoconf@2.69                berkeley-db@18.1.40  environment-modules@4.5.1  gcc@9.3.0   gdbm@1.18.1     isl@0.14   libgpg-error@1.37  libxml2@2.9.10  mpc@1.1.0   ncurses@6.2  readline@8.0   tcl@8.6.10
autoconf-archive@2019.01.06  bzip2@1.0.8          environment-modules@4.5.1  gcc@9.3.0   gettext@0.20.2  isl@0.20   libiconv@1.16      libxslt@1.1.33  mpfr@3.1.6  perl@5.30.3  readline@8.0   xz@5.2.5
automake@1.16.2              ccache@3.7.9         gawk@5.0.1                 gcc@10.2.0  gmp@6.1.2       isl@0.21   libsigsegv@2.12    m4@1.4.18       mpfr@4.0.2  perl@5.30.3  tar@1.32       zlib@1.2.11

-- linux-centos7-x86_64 / gcc@5.1.0 -----------------------------
autoconf@2.69    berkeley-db@18.1.40  gdbm@1.18.1  libiconv@1.16      libsigsegv@2.12  libxml2@2.9.10  mpich@3.3.2  perl@5.30.3    readline@8.0  util-macros@1.19.1  zlib@1.2.11
automake@1.16.2  findutils@4.6.0      hwloc@2.2.0  libpciaccess@0.16  libtool@2.4.6    m4@1.4.18       ncurses@6.0  pkgconf@1.7.3  texinfo@6.5   xz@5.2.5

-- linux-centos7-zen2 / gcc@9.3.0 -------------------------------
autoconf@2.69                cppunit@1.14.0             freetype@2.10.1  hdf5@1.10.7       libgpg-error@1.37    libxml2@2.9.10  nasm@2.15.05     pkgconf@1.7.3         py-pillow@7.2.0           readline@8.0        vtk@8.2.0
autoconf@2.69                diffutils@3.7              gawk@5.0.1       help2man@1.47.11  libiconv@1.16        libxml2@2.9.10  ncurses@6.0      py-bottleneck@1.2.1   py-pyparsing@2.4.2        sqlite@3.31.1       xz@5.2.5
autoconf-archive@2019.01.06  double-conversion@2.0.1    gcc@9.3.0        hwloc@2.2.0       libjpeg-turbo@2.0.4  libxslt@1.1.33  ncurses@6.2      py-certifi@2020.6.20  py-python-dateutil@2.8.0  sqlite@3.33.0       xz@5.2.5
automake@1.16.2              double-conversion@2.0.1    gcc@9.3.0        hwloc@2.2.0       libpciaccess@0.16    lz4@1.9.2       netcdf-c@4.7.3   py-cycler@0.10.0      py-pytz@2020.1            sqlite@3.33.0       zlib@1.2.11
automake@1.16.2              eigen@3.3.7                gdbm@1.18.1      hwloc@2.2.0       libpng@1.6.37        m4@1.4.18       netcdf-c@4.7.4   py-cython@0.29.21     py-setuptools@50.1.0      tar@1.32
berkeley-db@18.1.40          eigen@3.3.8                gdbm@1.18.1      isl@0.20          libpng@1.6.37        mpc@1.1.0       netcdf-cxx@4.2   py-kiwisolver@1.1.0   py-setuptools-scm@4.1.2   tcl@8.6.8
boost@1.73.0                 environment-modules@4.5.1  gettext@0.20.2   jsoncpp@1.9.2     libsigsegv@2.12      mpfr@3.1.6      netcdf-cxx@4.2   py-matplotlib@3.3.2   py-six@1.14.0             texinfo@6.5
boost@1.74.0                 expat@2.2.9                gettext@0.21     jsoncpp@1.9.2     libtiff@4.0.10       mpfr@4.0.2      openblas@0.3.10  py-mock@3.0.5         py-sympy@1.4              texinfo@6.5
bzip2@1.0.8                  fftw@3.3.8                 gettext@0.21     lcov@1.15.1       libtiff@4.1.0        mpich@3.3.2     openssl@1.1.1g   py-mpmath@1.1.0       python@3.7.8              util-macros@1.19.1
ccache@3.7.11                fftw@3.3.8                 gmp@6.1.2        libbsd@0.10.0     libtool@2.4.6        mpich@3.3.2     openssl@1.1.1h   py-numexpr@2.7.0      python@3.7.8              valgrind@3.15.0
cmake@3.18.1                 findutils@4.6.0            gperf@3.1        libffi@3.3        libuuid@1.0.3        mpich@3.3.2     perl@5.30.3      py-numpy@1.19.3       qhull@2020.1              valgrind@3.15.0
cmake@3.18.4                 freetype@2.10.1            hdf5@1.10.6      libgcrypt@1.8.5   libxml2@2.9.10       nasm@2.14.02    perl@5.30.3      py-pandas@1.1.4       readline@8.0              vtk@8.2.0

-- linux-centos7-zen2 / gcc@10.2.0 ------------------------------
autoconf@2.69    berkeley-db@18.1.40  gdbm@1.18.1  libiconv@1.16      libsigsegv@2.12  libxml2@2.9.10  mpich@3.3.2  perl@5.30.3    readline@8.0  util-macros@1.19.1  zlib@1.2.11
automake@1.16.2  findutils@4.6.0      hwloc@2.2.0  libpciaccess@0.16  libtool@2.4.6    m4@1.4.18       ncurses@6.0  pkgconf@1.7.3  texinfo@6.5   xz@5.2.5
[CentOS-7.7][~]> spack --debug --stacktrace buildcache list -a
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-10-08:41:13.845380] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-10-08:41:13.849161] Imported buildcache from built-in commands
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:13.850795] Reading config file /data/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:13.867946] Reading config file /home/moosetest/.spack/config.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:13.885026] Reading config file /data/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:909 ==> [2020-11-10-08:41:13.886405] Reading config file /home/moosetest/.spack/mirrors.yaml
lib/spack/spack/binary_distribution.py:388 ==> [2020-11-10-08:41:13.893960] Cached index for file:///data/mirror already up to date
lib/spack/spack/binary_distribution.py:379 ==> [2020-11-10-08:41:14.096749] Unable to read index hash https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json.hash
  Download failed: HTTP Error 404: Not Found
  1
lib/spack/spack/binary_distribution.py:399 ==> [2020-11-10-08:41:14.097952] Fetching index from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json
lib/spack/spack/binary_distribution.py:407 ==> [2020-11-10-08:41:14.253759] Unable to read index https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/index.json
  Download failed: HTTP Error 404: Not Found
  1
lib/spack/spack/cmd/buildcache.py:522 ==> [2020-11-10-08:41:14.255346] 0 cached builds.
[CentOS-7.7][~]> 
```

I think I am narrowing in on my issue. I'll report my findings when I find them, but I don't think this is a Spack bug.

**Comment by milljm** [comment]
When I force Spack to not use the cache file it creates (fails to create is why, and my next goal), it seems to work:
```diff
diff --git a/lib/spack/spack/binary_distribution.py b/lib/spack/spack/binary_distribution.py
index a7393f440..45a92cd45 100644
--- a/lib/spack/spack/binary_distribution.py
+++ b/lib/spack/spack/binary_distribution.py
@@ -382,7 +382,8 @@ def fetch_and_cache_index(self, mirror_url, expect_hash=None):
         # index from the mirror is when we already have a hash for this
         # mirror, we were able to retrieve one from the mirror, and
         # the two hashes are the same.
-        if expect_hash and fetched_hash:
+        #if expect_hash and fetched_hash:
+        if False:
             if fetched_hash == expect_hash:
                 tty.debug('Cached index for {0} already up to date'.format(
                     mirror_url))
```
Because when this is my change:
```diff
diff --git a/lib/spack/spack/binary_distribution.py b/lib/spack/spack/binary_distribution.py
index a7393f440..aea262ced 100644
--- a/lib/spack/spack/binary_distribution.py
+++ b/lib/spack/spack/binary_distribution.py
@@ -383,7 +383,8 @@ def fetch_and_cache_index(self, mirror_url, expect_hash=None):
         # mirror, we were able to retrieve one from the mirror, and
         # the two hashes are the same.
         if expect_hash and fetched_hash:
-            if fetched_hash == expect_hash:
+            #if fetched_hash == expect_hash:
+            if False:
                 tty.debug('Cached index for {0} already up to date'.format(
                     mirror_url))
                 return False
```
I receive this error instead:
```pre
[CentOS-7.7][~]> spack buildcache list -a
==> Error: [Errno 2] No such file or directory: '/data/spack/opt/spack/indices/27dc15847e_6fa702af39.json'
```

**Comment by scheibelp** [comment]
> Posting in case it helps. What you are seeing is two consecutive runs of spack --debug --stacktrace buildcache list -a back-to-back. The first one works, the second fails:

Thanks for elaborating: I can replicate that myself: running `spack buildcache list` the first time works but not the second time. Adding a new package to the cache with `spack buildcache create` followed by `update-index` appears to allow `buildcache list` to work *once*, but the second time it shows no specs.

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/19848 fixes the problem for me, would you be able to try it and let me know if it works for you?

**Comment by milljm** [comment]
This appears to fix my issue (if it helps). 
```diff
diff --git a/lib/spack/spack/binary_distribution.py b/lib/spack/spack/binary_distribution.py
index a7393f440..6c73ce08c 100644
--- a/lib/spack/spack/binary_distribution.py
+++ b/lib/spack/spack/binary_distribution.py
@@ -308,6 +308,9 @@ def update(self):
                 # this, we should never set False again, only True.
                 spec_cache_clear_needed = needs_regen
                 spec_cache_regenerate_needed = needs_regen
+                if not needs_regen:
+                    self._associate_built_specs_with_mirror(cached_index_path,
+                                                            cached_mirror_url)
             else:
                 # No longer have this mirror, cached index should be removed
                 items_to_remove.append({
```
It looks like https://github.com/spack/spack/blob/dd96a86511b45a9f9a94a09c9db7ea10be87c2fa/lib/spack/spack/cmd/buildcache.py#L512

when called is expecting a list being populated by: https://github.com/spack/spack/blob/dd96a86511b45a9f9a94a09c9db7ea10be87c2fa/lib/spack/spack/binary_distribution.py#L180

But it never reaches this point, as the list is empty of mirrors.

Hope this helps! Thanks for the awesome product!

**Comment by milljm** [comment]
Woops, my browser didn't update with your latest response. I'll give your change a go, and let you know! Thanks again!

**Comment by milljm** [comment]
@scheibelp confirmed #19848 fixes my issue.

Cheers!
