### ISSUE TITLE
Where/when does`spack load` write to the file system 

### ISSUE THREAD

**Issue by CreRecombinase** [LLNL/spack#19835]
I ran `spack --stacktrace load r@4.0.2` (but it happens with everything) and I got:

```lib/spack/spack/main.py:772 ==> Error: [Errno 122] Disk quota exceeded```

If I run in debug mode I get: 
```
t.cri.nknoblauch@cri16in001:/scratch/t.cri.nknoblauch/polyg_scratch/workflow:spack --debug --stacktrace load r@4.0.2
lib/spack/spack/cmd/__init__.py:102 ==> [2020-11-09-20:31:00.125122, 101128] Imported load from built-in commands
lib/spack/spack/cmd/__init__.py:102 ==> [2020-11-09-20:31:00.127824, 101128] Imported load from built-in commands
lib/spack/spack/config.py:706 ==> [2020-11-09-20:31:00.177898, 101128] Reading config file /gpfs/data/xhe-lab/software/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:706 ==> [2020-11-09-20:31:00.200301, 101128] Reading config file /home/t.cri.nknoblauch/.spack/config.yaml
lib/spack/spack/database.py:339 ==> [2020-11-09-20:31:00.215561, 101128] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:343 ==> [2020-11-09-20:31:00.216146, 101128] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/llnl/util/lock.py:537 ==> [2020-11-09-20:31:00.219027, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Acquiring] 
lib/spack/llnl/util/lock.py:178 ==> [2020-11-09-20:31:00.220241, 101128] read locking [0:0]: timeout 3 sec
lib/spack/llnl/util/lock.py:477 ==> [2020-11-09-20:31:00.221222, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 20:31:00.220422] 
lib/spack/spack/config.py:706 ==> [2020-11-09-20:31:00.971813, 101128] Reading config file /gpfs/data/xhe-lab/software/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:706 ==> [2020-11-09-20:31:00.977709, 101128] Reading config file /home/t.cri.nknoblauch/.spack/linux/repos.yaml
lib/spack/llnl/util/lock.py:537 ==> [2020-11-09-20:31:01.096124, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Releasing] 
lib/spack/llnl/util/lock.py:477 ==> [2020-11-09-20:31:01.096724, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Released at 20:31:01.096327] 
lib/spack/llnl/util/lock.py:537 ==> [2020-11-09-20:31:01.099701, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Acquiring] 
lib/spack/llnl/util/lock.py:178 ==> [2020-11-09-20:31:01.100256, 101128] read locking [0:0]: timeout 3 sec
lib/spack/llnl/util/lock.py:477 ==> [2020-11-09-20:31:01.100666, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 20:31:01.100355] 
lib/spack/llnl/util/lock.py:537 ==> [2020-11-09-20:31:01.886758, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Releasing] 
lib/spack/llnl/util/lock.py:477 ==> [2020-11-09-20:31:01.887268, 101128] READ LOCK (database): /gpfs/data/xhe-lab/software/spack/opt/spack/.spack-db/lock[0:0] [Released at 20:31:01.886947] 
Traceback (most recent call last):
  File "/gpfs/data/xhe-lab/software/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/cmd/load.py", line 76, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/user_environment.py", line 83, in environment_modifications_for_spec
    spec, context='run'
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/build_environment.py", line 740, in modifications_from_dependencies
    pkg = spec.package
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/spec.py", line 1155, in package
    self._package = spack.repo.get(self)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 1194, in get
    return path.get(spec)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 94, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 653, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 94, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 892, in get
    package_class = self.get_pkg_class(spec.name)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 1086, in get_pkg_class
    module = self._get_pkg_module(pkg_name)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/repo.py", line 1060, in _get_pkg_module
    prepend=_package_prepend)
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/util/imp/imp_importer.py", line 41, in load_source
    with prepend_open(path, text=prepend) as f:
  File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/gpfs/data/xhe-lab/software/spack/lib/spack/spack/util/imp/imp_importer.py", line 66, in prepend_open
    tf.seek(0)
IOError: [Errno 122] Disk quota exceeded

```

How do i figure out where this is happening?  I have spack installed on a pretty buggy `gpfs` system, but I can still write files to the system so it isn't an actual disk quota issue as far as I'm aware. 

### Information on your system

```
usage: spack debug [-h] SUBCOMMAND ...
spack debug: error: argument SUBCOMMAND: invalid choice: 'report' choose from:
    create-db-tarball
```
Sorry I'm using spack `0.14.0` and don't know how to upgrade.  I'm using Python 2.6.6 (because I can't spack load a better one)

### Additional information

- [?] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by CreRecombinase** [comment]
Update: If I `module load ` a newer (spack generated) python, the problem goes away, so I guess it's an ancient python issue

**Comment by alalazo** [comment]
> If I module load a newer (spack generated) python, the problem goes away, so I guess it's an ancient python issue

Thanks for the report and follow-up.

**Comment by alalazo** [comment]
We dropped support of Python < 3.6, so closing this one
