### ISSUE TITLE
SLEPc fails with dlopen python error / write lock related?

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1996]
subj:

```
==> './configure' '--prefix=/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/slepc-3.7.1-oc6ogg2tsdcry4nv6oj6z2y5umddqc2s' '--with-arpack-dir=/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/arpack-ng-3.4.0-pu5wkjbz4hbozonicrjrys4dwjkkdciv/lib' '--with-arpack-flags=-lparpack,-larpack'
Traceback (most recent call last):
  File "./configure", line 10, in <module>
    execfile(os.path.join(os.path.dirname(__file__), 'config', 'configure.py'))
  File "./config/configure.py", line 140, in <module>
    import slepc, petsc, arpack, blzpack, trlan, feast, primme, blopex, sowing, lapack
  File "/private/var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/davydden/spack-stage/spack-stage-Y_CyFI/slepc-3.7.1/config/packages/petsc.py", line 22, in <module>
    import package, os, sys, commands
  File "/private/var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/davydden/spack-stage/spack-stage-Y_CyFI/slepc-3.7.1/config/package.py", line 22, in <module>
    import os, sys, commands, tempfile, shutil, urllib, urlparse, tarfile
  File "/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-rol3whbb472kx3xpjtiog7s2575lihqd/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-rol3whbb472kx3xpjtiog7s2575lihqd/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-rol3whbb472kx3xpjtiog7s2575lihqd/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-rol3whbb472kx3xpjtiog7s2575lihqd/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-rol3whbb472kx3xpjtiog7s2575lihqd/lib/python2.7/lib-dynload/_io.so
```

whereas in the terminal i see

```
==> Building slepc
==> WRITE LOCK: /Users/davydden/spack/opt/spack/.spack-db/prefix_lock[4061808767187575438:1] [Released]
==> WRITE LOCK: /Users/davydden/spack/var/spack/stage/.lock[4337877610633411025:1] [Released]
```

I have not seen those `WRITE LOCK` warnings before. Could be somehow related.

**Comment by alalazo** [comment]
May be [this](http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder) ?

**Comment by davydden** [comment]
`spack load python` before running `spack install` fixed the issue.  No idea what is happening....

**Comment by davydden** [comment]
fixed by https://github.com/LLNL/spack/pull/2560
