### ISSUE TITLE
spack test doesn't support Python 3.8 + macOS

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#20025]
The `spack test` command doesn't seem to work with Python 3, at least for me:
```console
$ python3 $(which spack) test run m4
==> Spack test 5zpwbxxu43yidobk5y7qwagzxo77jeyx
$ python3 $(which spack) test results --logs
==> Results for test suite '5zpwbxxu43yidobk5y7qwagzxo77jeyx':
==>   m4-1.4.18-kzezvfi FAILED

==>   m4-1.4.18-qlyhwnr FAILED

$ python2 $(which spack) test run m4
==> Spack test 5zpwbxxu43yidobk5y7qwagzxo77jeyx
==> Testing package m4-1.4.18-kzezvfi
==> Testing package m4-1.4.18-qlyhwnr
$ python2 $(which spack) test results --logs
==> Results for test suite '5zpwbxxu43yidobk5y7qwagzxo77jeyx':
==>   m4-1.4.18-kzezvfi PASSED
==> Testing package m4-1.4.18-kzezvfi
==> [2020-11-20-16:11:31.081381] test: ensuring m4 version is 1.4.18
==> [2020-11-20-16:11:31.085485] '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/m4-1.4.18-kzezvfiholjl32zfa2vfkmvycrcp7rq6/bin/m4' '--version'
m4 (GNU M4) 1.4.18
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.
PASSED
==> [2020-11-20-16:11:31.155946] test: ensuring m4 example succeeds
==> [2020-11-20-16:11:31.157026] '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/m4-1.4.18-kzezvfiholjl32zfa2vfkmvycrcp7rq6/bin/m4' '/Users/Adam/.spack/test/5zpwbxxu43yidobk5y7qwagzxo77jeyx/m4-1.4.18-kzezvfi/data/m4/hello.m4'

// macro is defined
Hello, World!
PASSED

==>   m4-1.4.18-qlyhwnr PASSED
==> Testing package m4-1.4.18-qlyhwnr
==> [2020-11-20-16:11:47.213468] test: ensuring m4 version is 1.4.18
==> [2020-11-20-16:11:47.220733] '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/gcc-10.2.0/m4-1.4.18-qlyhwnrpg6e66gdldgivjps47fyu6gbn/bin/m4' '--version'
m4 (GNU M4) 1.4.18
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.
PASSED
==> [2020-11-20-16:11:47.316219] test: ensuring m4 example succeeds
==> [2020-11-20-16:11:47.317434] '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/gcc-10.2.0/m4-1.4.18-qlyhwnrpg6e66gdldgivjps47fyu6gbn/bin/m4' '/Users/Adam/.spack/test/5zpwbxxu43yidobk5y7qwagzxo77jeyx/m4-1.4.18-qlyhwnr/data/m4/hello.m4'

// macro is defined
Hello, World!
PASSED
```

### Information on your system

$ spack debug report
* **Spack:** 0.16.0-32-3fbda07a87
* **Python:** 3.8.6
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@scheibelp I've narrowed this down a bit. With Python 2.7 and 3.7, I'm unable to reproduce this. But with Python 3.8 and macOS, I can. This looks like another Python 3.8 + macOS bug in develop.

**Comment by adamjstewart** [comment]
Ping @scheibelp @becker33, can we bump this up in priority?

**Comment by adamjstewart** [comment]
Has anyone had a chance to work on this? It keeps getting bumped from one release to the next.

**Comment by tldahlgren** [comment]
@adamjstewart I'm not having the problem with the latest `develop` on my Mac (Big Sur, Python 3.9.5 and 2.7.16).  I see this is listed in the `0.16.3` and you were using `0.16.0`.  Should I be testing with a specific release or commit?

**Comment by adamjstewart** [comment]
Oh interesting, maybe it was fixed recently. I'll investigate.

**Comment by adamjstewart** [comment]
I'm so confused, I can't even reproduce this on the 0.16.0 release anymore. I guess we can close this for now until someone encounters it again and figures out how to reproduce.

**Comment by adamjstewart** [comment]
Just reproduced this again. Going to try to figure out what changed. I'm now in an environment with a Spack-built Python, so that may affect things.

**Comment by adamjstewart** [comment]
Okay, if I remove the try-except logic in `spack.install_test.TestSuite.__call__`, I get the same error message as in #23892:
```
==> Error: maximum recursion depth exceeded while pickling an object
```
@alalazo just fixed this for installations in #25658, looks like we need to add this to another method to fix it for smoke tests.

**Comment by adamjstewart** [comment]
Tried adding a `TestSuite.__reduce__` method but it didn't solve the issue, so the issue isn't with pickling `TestSuite` but some other object.

**Comment by adamjstewart** [comment]
Figured out how to figure out which object is having trouble being pickled. After removing the try-except logic:
```console
$ spack --stacktrace test run
...
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/test.py", line 411, in test
    globals()['test_%s' % args.test_command](args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/test.py", line 193, in test_run
    test_suite(remove_directory=not args.keep_stage,
  File "/Users/Adam/spack/lib/spack/spack/install_test.py", line 129, in __call__
    spec.package.do_test(
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 1791, in do_test
    spack.build_environment.start_build_process(self, test_process, kwargs)
  File "/Users/Adam/spack/lib/spack/spack/build_environment.py", line 1111, in start_build_process
    serialized_pkg = spack.subprocess_context.PackageInstallContext(pkg)
  File "/Users/Adam/spack/lib/spack/spack/subprocess_context.py", line 69, in __init__
    self.serialized_env = serialize(ev._active_environment)
  File "/Users/Adam/spack/lib/spack/spack/subprocess_context.py", line 41, in serialize
    pickle.dump(obj, serialized_obj)
RecursionError: maximum recursion depth exceeded while pickling an object
```
If I print the object we're trying to serialize, it gives me `spack.environment.Environment`. Going to try to add a `__reduce__` method to that.
