### ISSUE TITLE
mesa with test dependencies fail to concretize

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#20079]
When trying to install `mesa` with test dependencies, one gets errors during concretization with both the original and the new concretizer.

### Steps to reproduce the issue

```console
$ spack install --test=all mesa
[ ... ]
```

### Error Message
With the ASP-based concretizer one gets
```console
$ spack install --test=all mesa
==> Error: argument of type 'bool' is not iterable
```
the full stacktrace is:

<details>
<summary>$ spack -d install --test=all mesa </summary>

```console
$ spack -d install --test=all mesa
==> [2020-11-25-06:00:43.245416] Imported install from built-in commands
==> [2020-11-25-06:00:43.247920] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2020-11-25-06:00:43.281755] Reading config file /home/culpo/.spack/config.yaml
==> [2020-11-25-06:00:43.284750] Imported install from built-in commands
==> [2020-11-25-06:00:43.290039] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2020-11-25-06:00:44.668260] Reading config file /home/culpo/.spack/linux/compilers.yaml
==> [2020-11-25-06:00:44.813981] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2020-11-25-06:00:44.850561] Reading config file /home/culpo/.spack/packages.yaml
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/bin/spack", line 66, in <module>
    sys.exit(spack.main.main())
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/install.py", line 302, in install
    specs = spack.cmd.parse_specs(
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2469, in concretize
    self._new_concretize(tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2445, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 1838, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 620, in solve
    solver_setup.setup(self, specs, tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 1484, in setup
    self.pkg_rules(pkg, tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 901, in pkg_rules
    self.package_dependencies_rules(pkg, tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 920, in package_dependencies_rules
    if t == 'test' and (not tests or pkg.name not in tests):
TypeError: argument of type 'bool' is not iterable
```
</details>

With the old concretizer there's an infinite recursion:
```console
$ spack  install --test=all mesa
==> Error: maximum recursion depth exceeded while calling a Python object
```

### Information on your system

* **Spack:** 0.16.0-59-408824f365
* **Python:** 3.8.6
* **Platform:** linux-ubuntu18.04-broadwell
* **Concretizer:** original, clingo

### Additional information

Error originally reported by @vvolkl on Slack

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
After a quick fix for the clingo issue (will submit a PR for that) here's the unsat core that is obtained:

<details>
<summary>$ spack  install --test=all mesa</summary>

```console
$ spack  install --test=all mesa
==> The following constraints are unsatisfiable:
  declared_dependency("icedtea","jdk","build")
  declared_dependency("libmng","cmake","build")
  declared_dependency("librsvg","cairo","build")
  declared_dependency("librsvg","rust","build")
  declared_dependency("mesa","py-mako","build")
  declared_dependency("py-attrs","py-coverage","test")
  declared_dependency("py-attrs","py-hypothesis","test")
  declared_dependency("py-attrs","py-pytest","test")
  declared_dependency("py-attrs","py-setuptools","build")
  declared_dependency("py-httpbin","py-werkzeug","build")
  declared_dependency("py-importlib-resources","py-wheel","build")
  declared_dependency("py-mako","py-mock","test")
  declared_dependency("py-mako","py-pytest","test")
  declared_dependency("py-mako","py-setuptools","build")
  declared_dependency("py-mock","py-pytest-cov","test")
  declared_dependency("py-pytest","py-attrs","build") :- node("py-pytest"),version_satisfies("py-pytest","3.5:").
  declared_dependency("py-pytest-cov","py-pytest","build")
  declared_dependency("py-pytest-httpbin","py-httpbin","build")
  declared_dependency("py-requests","py-pytest-httpbin","test")
  declared_dependency("py-sphinx","py-requests","build")
  declared_dependency("py-traceback2","py-unittest2","test")
  declared_dependency("py-unittest2","py-traceback2","build")
  declared_dependency("py-werkzeug","py-requests","test")
  declared_dependency("py-wheel","py-pytest","test")
  provides_virtual("icedtea","java")
  provides_virtual("jdk","java")
  root("mesa")
  version_declared("py-pytest","3.5.1",9)
  version_declared("py-pytest","3.7.1",8)
  version_declared("py-pytest","3.7.2",7)
  version_declared("py-pytest","4.3.0",6)
  version_declared("py-pytest","4.6.2",5)
  version_declared("py-pytest","4.6.5",4)
  version_declared("py-pytest","4.6.9",3)
  version_declared("py-pytest","5.1.1",2)
  version_declared("py-pytest","5.2.1",1)
  version_declared("py-pytest","5.3.4",0)
  version_satisfies("py-pytest","3.6:") :- depends_on("py-pytest-cov","py-pytest"),node("py-pytest-cov").
  virtual("java")
==> Error: mesa does not satisfy unknown
```

</details>

**Comment by alalazo** [comment]
A circular dependency is activated by tests:
```
py-attrs -> depends_on(py-pytest, type=test)
py-pytest -> depends_on(py-attrs)
```
