### ISSUE TITLE
install of m4 hangs during configure

### ISSUE THREAD

**Issue by odoublewen** [LLNL/spack#20217]
### Steps to reproduce the issue

```console
$ spack install m4
```

### Information on your system

```
$ spack/bin/spack debug report
* **Spack:** 0.16.0
* **Python:** 3.4.3
* **Platform:** linux-ubuntu14.04-broadwell
* **Concretizer:** original

$ cat packages.yaml 
packages:
  all:
    compiler: [gcc@8.4.0]
```

### Additional information

I wonder if this might be related to #10493.  Possibly, like that issue, my spack is on an NAS filesystem. (The staging dir, on `/tmp`, is local, however.)  Like that issue, the traceback upon keyboard interrupt shows that Spack was stuck in `log.py`:

```console
==> Installing m4-1.4.18-vlt4klqmalwgnszby63obyudnhfrop3e
==> No binary for m4-1.4.18-vlt4klqmalwgnszby63obyudnhfrop3e found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/ab/ab2633921a5cd38e48797bf5521ad259bdc4b979078034a3b790d7fec5493fab.tar.gz
######################################################################## 100.0%
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/fc/fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
######################################################################## 100.0%
==> m4: Executing phase: 'autoreconf'
==> m4: Executing phase: 'configure'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
==> Error: Failed to install m4 due to KeyboardInterrupt: 
  File "/foobar/home/osolberg/spack3/spacktree/spack/lib/spack/llnl/util/tty/log.py", line 763, in _writer_daemon
    line = _retry(in_pipe.readline)()
  File "/foobar/home/osolberg/spack3/spacktree/spack/lib/spack/llnl/util/tty/log.py", line 825, in wrapped
    return function(*args, **kwargs)
KeyboardInterrupt

==> Error: Keyboard interrupt.
```

It will hang at `==> m4: Executing phase: 'configure'` for hours, days, as long as I let it.

After killing, if I retry again, it might or might not work.  Seems to hang about 50% of the time.

If I do a `spack build-env m4 bash` and cd to the staging/src dir, and then do a `./configure` -- it succeeds **every** time, and only takes about 45 seconds.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers  **(I have not, b/c I don't think this is an issue with the package build, per se)**
- [ ] I have uploaded the build log and environment files **(ibid, and also b/c there are path names I would have to obfuscate)**
- [X] I have searched the issues of this repo and believe this is not a duplicate

FYI @hartzell

**Comment by odoublewen** [comment]
Also, I confirmed that this still occurs when I am using a supported version of Py3:
```
⟫ spack/bin/spack debug report                                                                                                                                                       
* **Spack:** 0.16.0
* **Python:** 3.8.1
* **Platform:** linux-ubuntu14.04-broadwell
* **Concretizer:** original
```

**Comment by odoublewen** [comment]
Closing because, inexplicably, I can no longer reproduce this behavior, which was so vexing me a week ago.   My gremlins have moved on, it would seem.

**Comment by odoublewen** [comment]
For future reference, in case I or anyone else ever sees this again, here's where the build gets hung up:

```
checking whether printf supports size specifiers as in C99... yes
checking whether printf supports 'long double' arguments... yes
checking whether printf supports infinite 'double' arguments... yes
checking whether printf supports infinite 'long double' arguments... yes
checking whether printf supports the 'a' and 'A' directives... yes
checking whether printf supports the 'F' directive... yes
             <------------------------- hang was happening here (spack install -v m4)... the lines below are from when it works.
checking whether printf supports the 'n' directive... no
checking whether printf supports the 'ls' directive... yes
checking whether printf supports the grouping flag... yes
checking whether printf supports the left-adjust flag correctly... yes
```
