### ISSUE TITLE
With Clingo arbitrary external package versions are not allowed 

### ISSUE THREAD

**Issue by ilbiondo** [LLNL/spack#20244]
### Steps to reproduce the issue

Try and solve / concretise an external package that previously worked with the old concretiser.

```console


$ spack solve slurm
==> The following constraints are unsatisfiable:
  external_only("slurm")
  root("slurm")
  version_declared("slurm","19-05-6-1",2)
  version_satisfies("slurm","19.05.6") :- external_spec("slurm",0).


```

With the following external definition:

```
  slurm:
    buildable: false
    externals:
    - spec: slurm@19.05.6
      prefix: /usr
```

### Error Message

```console
$ spack -d spec slurm
==> [2020-12-04-14:40:10.678728] Imported spec from built-in commands
==> [2020-12-04-14:40:10.679839] Imported spec from built-in commands
Input spec
--------------------------------
slurm

Concretized
--------------------------------
==> [2020-12-04-14:40:10.682664] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/packages.yaml
==> [2020-12-04-14:40:10.714131] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/compilers.yaml
==> [2020-12-04-14:40:10.727205] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/var/spack/environments/S6g1-IB-test1/spack.yaml
==> [2020-12-04-14:40:10.839162] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/defaults/repos.yaml
==> [2020-12-04-14:40:10.841616] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/repos.yaml
==> [2020-12-04-14:40:10.842923] Reading config file /users/dcsrsoft/.spack/linux/repos.yaml
==> [2020-12-04-14:40:13.190121] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/compilers.yaml
==> [2020-12-04-14:40:13.249151] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/defaults/packages.yaml
==> [2020-12-04-14:40:13.272832] Reading config file /dcsrsoft/spack/hetre/v0.2/spack/etc/spack/packages.yaml
==> [2020-12-04-14:40:22.598398] The following constraints are unsatisfiable:
  external_only("slurm")
  root("slurm")
  version_declared("slurm","19-05-6-1",1)
  version_satisfies("slurm","19.05.6") :- external_spec("slurm",0).
==> [2020-12-04-14:40:22.603311] UnsatisfiableSpecError: slurm does not satisfy unknown
==> [2020-12-04-14:40:22.605218] Error: slurm does not satisfy unknown
Traceback (most recent call last):
  File "/dcsrsoft/spack/hetre/v0.2/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/dcsrsoft/spack/hetre/v0.2/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/dcsrsoft/spack/hetre/v0.2/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "/dcsrsoft/spack/hetre/v0.2/spack/lib/spack/spack/spec.py", line 2469, in concretize
    self._new_concretize(tests)
  File "/dcsrsoft/spack/hetre/v0.2/spack/lib/spack/spack/spec.py", line 2448, in _new_concretize
    raise spack.error.UnsatisfiableSpecError(
spack.error.UnsatisfiableSpecError: slurm does not satisfy unknown
```

### Information on your system

```
$ spack --version
0.16.0-163-98517af
```

### Additional information

As suggested by @alalazo changing the declared version to match one in package.py resolves the immediate issue.

```
  slurm:
    buildable: false
    externals:
    - spec: slurm@19-05-6-1
      prefix: /usr
```

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This must be a weird interaction of our solver setup and the version semantics. A configuration file like:
```yaml
packages:
  slurm:
    buildable: false
    externals:
    - spec: slurm@foo
      prefix: /usr
```
works perfectly, but I can reproduce the issue with the `packages.yaml` posted above. In the logic program I could find:
```
version_satisfies("slurm", "19.05.6") :- 1 { version("slurm", "19-05-6-1") } 1.
1 { version("slurm", "19-05-6-1") } 1 :- version_satisfies("slurm", "19.05.6").
```
which is clearly wrong. I think `19.05.6` has been considered not a fixed version, but a range.

**Comment by stevenrbrandt** [comment]
So it turns out that all I needed to do was:
```
module unload cray-mpich
module unload cuda
```
