### ISSUE TITLE
Issues with cYAML on BG/Q

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#2027]
From #2010: On BG/Q, @pramodk gets this error when loading the default `repos.yaml` with cYAML:

```
$ ./bin/spack --version
Traceback (most recent call last):
  File "./bin/spack", line 98, in <module>
    import spack
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/__init__.py", line 74, in <module>
    repo = spack.repository.RepoPath()
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/repository.py", line 131, in __init__
    repo_dirs = spack.config.get_config('repos')
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/config.py", line 403, in get_config
    data = scope.get_section(section)
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/config.py", line 248, in get_section
    data   = _read_config_file(path, schema)
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/config.py", line 323, in _read_config_file
    data = syaml.load(f)
  File "/home/kumbhar/tmp_tk/spack/lib/spack/spack/util/spack_yaml.py", line 213, in load
    return yaml.load(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 702, in _yaml.CParser.get_single_node (ext/_yaml.c:7647)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:10396)
yaml.reader.ReaderError: unacceptable character #x0000: control characters are not allowed
  in "/home/kumbhar/tmp_tk/spack/etc/spack/defaults/repos.yaml", position 546
```

**Comment by tgamblin** [comment]
@pramodk: can you verify this?

**Comment by pramodk** [comment]
Don't see this issue while using develop, so all looks good!
