### ISSUE TITLE
Install from spec yaml fails while in active environment

### ISSUE THREAD

**Issue by opadron** [LLNL/spack#20324]
### Steps to reproduce the issue

```console
$ docker run --rm -it spack/centos7

# from within container:
$ spack spec --yaml zlib > zlib.yaml
$ spack install -f ./zlib.yaml  # OK
 ...
$ spack uninstall --all --yes
==> Successfully uninstalled zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64/64vg6e4
```
```console
$ spack env create --without-view test
==> Created environment 'test' in /opt/spack/var/spack/environments/test
==> You can activate this environment with:
==>   spack env activate test
$ spack env activate test
$ spack --debug --stacktrace install -f ./zlib.yaml  # FAIL
```

### Error Message

```console
lib/spack/spack/cmd/__init__.py:122 ==> [2020-12-10-17:16:19.629926] Imported install from built-in commands
lib/spack/spack/config.py:907 ==> [2020-12-10-17:16:19.634329] Reading config file /opt/spack/var/spack/environments/test/spack.yaml
lib/spack/spack/cmd/__init__.py:122 ==> [2020-12-10-17:16:19.637631] Imported install from built-in commands
lib/spack/spack/config.py:907 ==> [2020-12-10-17:16:19.651607] Reading config file /opt/spack/etc/spack/defaults/repos.yaml
Traceback (most recent call last):
  File "/opt/spack/bin/spack", line 66, in <module>
    sys.exit(spack.main.main())
  File "/opt/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 371, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 207, in install_specs
    concrete = env.concretize_and_add(abstract, concrete)
  File "/opt/spack/lib/spack/spack/environment.py", line 1185, in concretize_and_add
    s for s in self.user_specs if s.satisfies(user_spec)
StopIteration
```

### Information on your system

* **Spack:** 0.16.0
* **Python:** 2.7.5
* **Platform:** linux-centos7-x86_64
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The semantic changed. As of:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo


```console
$ spack -E spec -j zlib > zlib.json
$ spack add ./zlib.json 
==> Adding zlib@=1.2.13%gcc@=9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake to environment /tmp/spack-85ort0qn

```
