### ISSUE TITLE
Concretiser issue : "IndexError: list index out of range"

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2032]
This from comment in #2030: If I have added XL compiler for only os=CNK but tries to concretise for os=redhat6, then get following error:

```bash
$ spack spec mpich %xl os=redhat6

Input spec
------------------------------
  mpich%xl arch=bgq-redhat6-None

Normalized
------------------------------
  mpich%xl arch=bgq-redhat6-None

Concretized
------------------------------
Traceback (most recent call last):
  File "/home/kumbhar/spack/bin/spack", line 192, in <module>
    main()
  File "/home/kumbhar/spack/bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/home/kumbhar/spack/lib/spack/spack/cmd/spec.py", line 57, in spec
    spec.concretize()
  File "/home/kumbhar/spack/lib/spack/spack/spec.py", line 1327, in concretize
    self._concretize_helper())
  File "/home/kumbhar/spack/lib/spack/spack/spec.py", line 1159, in _concretize_helper
    spack.concretizer.concretize_compiler(self),
  File "/home/kumbhar/spack/lib/spack/spack/concretize.py", line 385, in concretize_compiler
    while not _proper_compiler_style(matches[index], spec.architecture):
IndexError: list index out of range
```

**Comment by alalazo** [comment]
Is this still an issue?
