### ISSUE TITLE
Cray Compiler Discovery on Tulip

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/spack#20352]
### Steps to reproduce the issue

```console
$ module load cce/12.0.0.248
$ spack compiler find
==> Added 1 new compiler to /home/users/coe62716/.spack/cray/compilers.yaml
    cce@12.0.0.248
==> Compilers are defined in the following files:
    /home/users/____/.spack/cray/compilers.yaml
$ spack compiler info cce@12.0.0.248
cce@12.0.0.248:
        paths:
                cc = cc
                cxx = CC
                f77 = ftn
                fc = ftn
        modules  = ['PrgEnv-cray', 'cce/12.0.0.248']
        operating system  = rhel8
$ spack install zlib %cce@12.0.0.248
==> Installing zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn
==> No binary for zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn found: installing from source
==> Error: CompilerAccessError: Compiler 'cce@12.0.0.248' has executables that are missing or are not executable: ['CC', 'ftn', 'ftn']

/home/users/coe62716/workspace/spack/lib/spack/spack/build_environment.py:863, in _setup_pkg_and_run:
        860        tb_string = traceback.format_exc()
        861
        862        # build up some context from the offending package so we can
  >>    863        # show that, too.
        864        package_context = get_package_context(tb)
        865
        866        logfile = None
```

Once I add the compilers to `~/.spack/cray/compilers.yaml`, it all works fine:
```console
$ spack install zlib %cce@12.0.0.248
==> Installing zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn
==> No binary for zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn found: installing from source
==> Using cached archive: /home/users/coe62716/workspace/spack/var/spack/cache/_source-cache/archive/c3/c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1.tar.gz
==> zlib: Executing phase: 'install'
[+] /home/users/coe62716/workspace/spack/opt/spack/cray-rhel8-zen/cce-12.0.0.248/zlib-1.2.11-blm5t
```

### Error Message

```console
$ spack --debug --stacktrace install zlib %cce@12.0.0.248
lib/spack/spack/installer.py:1057 ==> [2020-12-12-11:07:40.377277] Installing zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn
lib/spack/spack/installer.py:271 ==> [2020-12-12-11:07:40.733855] No binary for zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn found: installing from source
lib/spack/spack/util/executable.py:162 ==> [2020-12-12-11:07:39.846884] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
lib/spack/spack/platforms/cray.py:154 ==> [2020-12-12-11:07:39.865758] default to front-end architecture
lib/spack/spack/cmd/__init__.py:122 ==> [2020-12-12-11:07:39.923781] Imported install from built-in commands
lib/spack/spack/config.py:907 ==> [2020-12-12-11:07:39.926296] Reading config file /home/users/coe62716/workspace/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:122 ==> [2020-12-12-11:07:39.959596] Imported install from built-in commands
lib/spack/spack/config.py:907 ==> [2020-12-12-11:07:39.962317] Reading config file /home/users/coe62716/workspace/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:907 ==> [2020-12-12-11:07:40.057351] Reading config file /home/users/coe62716/workspace/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:907 ==> [2020-12-12-11:07:40.103319] Reading config file /home/users/coe62716/.spack/cray/compilers.yaml
lib/spack/spack/util/executable.py:162 ==> [2020-12-12-11:07:40.226001] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
lib/spack/spack/platforms/cray.py:154 ==> [2020-12-12-11:07:40.232510] default to front-end architecture
lib/spack/spack/spec.py:2394 ==> [2020-12-12-11:07:40.245193] Ordered hashes [zlib]: zlib/0/e93f7400712c2814905815204dadbdebcb91dc77dd586f60cbc82efa102fb539
lib/spack/spack/database.py:362 ==> [2020-12-12-11:07:40.246784] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:366 ==> [2020-12-12-11:07:40.247024] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/installer.py:1333 ==> [2020-12-12-11:07:40.265129] Initializing the build queue from the build requests
lib/spack/spack/installer.py:976 ==> [2020-12-12-11:07:40.265315] Initializing the build queue for zlib
lib/spack/spack/installer.py:2009 ==> [2020-12-12-11:07:40.266438] Processing dependencies for zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn: ('build', 'link', 'run')
lib/spack/spack/database.py:461 ==> [2020-12-12-11:07:40.368358] Removing failure marking for zlib
lib/spack/spack/installer.py:1339 ==> [2020-12-12-11:07:40.369886] Ensure all dependencies know all dependents across specs
lib/spack/spack/installer.py:921 ==> [2020-12-12-11:07:40.371026] Acquiring a write lock on zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn with timeout 1e-09
lib/spack/spack/stage.py:312 ==> [2020-12-12-11:07:40.375708] Creating stage lock spack-stage-zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn
lib/spack/spack/installer.py:383 ==> [2020-12-12-11:07:40.377476] Searching for binary cache of zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn
lib/spack/spack/config.py:907 ==> [2020-12-12-11:07:40.378401] Reading config file /home/users/coe62716/workspace/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/binary_distribution.py:1331 ==> [2020-12-12-11:07:40.732461] Did not find cray-rhel8-zen-cce-11.0.1.28-zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn.spec.yaml on https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/cray-rhel8-zen-cce-12.0.0.248-zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn.spec.yaml
  Download failed: HTTP Error 404: Not Found
lib/spack/spack/error.py:55 ==> [2020-12-12-11:07:41.260228] Error: CompilerAccessError: Compiler 'cce@11.0.1.28' has executables that are missing or are not executable: ['CC', 'ftn', 'ftn']

/home/users/coe62716/workspace/spack/lib/spack/spack/build_environment.py:863, in _setup_pkg_and_run:
        860        tb_string = traceback.format_exc()
        861
        862        # build up some context from the offending package so we can
  >>    863        # show that, too.
        864        package_context = get_package_context(tb)
        865
        866        logfile = None


Traceback (most recent call last):
  File "/home/users/coe62716/workspace/spack/lib/spack/spack/build_environment.py", line 846, in _setup_pkg_and_run
    context=context)
  File "/home/users/coe62716/workspace/spack/lib/spack/spack/build_environment.py", line 730, in setup_package
    set_compiler_environment_variables(pkg, env)
  File "/home/users/coe62716/workspace/spack/lib/spack/spack/build_environment.py", line 216, in set_compiler_environment_variables
    compiler.verify_executables()
  File "/home/users/coe62716/workspace/spack/lib/spack/spack/compiler.py", line 333, in verify_executables
    raise CompilerAccessError(self, missing)
spack.compiler.CompilerAccessError: Compiler 'cce@12.0.0.248' has executables that are missing or are not executable: ['CC', 'ftn', 'ftn']
lib/spack/spack/installer.py:1263 ==> [2020-12-12-11:07:41.260584] Flagging zlib-1.2.11-blm5td5gwhpmqn3vnlwzojnnpflyiekn as failed: CompilerAccessError: Compiler 'cce@11.0.1.28' has executables that are missing or are not executable: ['CC', 'ftn', 'ftn']
lib/spack/spack/main.py:765 ==> [2020-12-12-11:07:41.265682] ChildError: CompilerAccessError: Compiler 'cce@12.0.0.248' has executables that are missing or are not executable: ['CC', 'ftn', 'ftn']
```

### Information on your system

* **Spack:** 0.16.0-44-5c623b03b
* **Python:** 3.6.8
* **Platform:** cray-rhel8-zen
* **Concretizer:** original

### Additional information

Possible duplicate of #17301?

CPU info: AMD EPYC 7601 32-Core Processor

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by ashermancinelli** [comment]
Looks like I had to load the cray collection first, then try to discover the compiler:
```console
$ module restore PrgEnv-cray
$ module switch cce/11.0.1 cce/12.0.0.248
$ spack compiler remove cce@12.0.0.248
$ spack compiler find
```
After this installing with `%cce@12.0.0.248` worked. If this is by design, perhaps this could be added to the documentation?

**Comment by alalazo** [comment]
Cray system based on environments have been deprecated, so I'll close this issue as won't fix :disappointed:
