### ISSUE TITLE
Logger dies (fails package build) when it encounters non-ascii character

### ISSUE THREAD

**Issue by nightlark** [LLNL/spack#20410]
### Steps to reproduce the issue

I got this error by running this command:

```console
$ spack install cairo
```

I'm using gcc 10.2.0 and running the command using bash -- other packages using the same build system work fine.

### Error Message

```console
 ==> cairo: Executing phase: 'build'
 ==> Error: Exception occurred in writer daemon!
 Traceback (most recent call last):
   File "/usr/workspace/spack/lib/spack/llnl/util/tty/log.py", line 763, in _writer_daemon
     line = _retry(in_pipe.readline)()
   File "/usr/workspace/spack/lib/spack/llnl/util/tty/log.py", line 825, in wrapped
     return function(*args, **kwargs)
   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 232: ordinal not in range(128)
 ==> Error: ProcessError: Command exited with status -13:
     'make' '-j16'
```

Running with --debug gives:

```console
Traceback (most recent call last):
  File "/usr/workspace/spack/lib/spack/spack/build_environment.py", line 851, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/usr/workspace/spack/lib/spack/spack/installer.py", line 1673, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/usr/workspace/spack/lib/spack/spack/package.py", line 109, in phase_wrapper
    phase(spec, prefix)
  File "/usr/workspace/spack/lib/spack/spack/build_systems/autotools.py", line 344, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/usr/workspace/spack/lib/spack/spack/build_environment.py", line 139, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/usr/workspace/spack/lib/spack/spack/util/executable.py", line 198, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j16'
==> [2020-12-15-10:54:06.380905] Flagging cairo-1.16.0-ns6mrdoarewzmfkneuq7xjv7ed74ck32 as failed: ProcessError: Command exited with status -13:
    'make' '-j16'
==> [2020-12-15-10:54:06.438865] ChildError: ProcessError: Command exited with status -13:
    'make' '-j16'
```

### Information on your system

* **Spack:** 0.16.0-230-86ae63b
* **Python:** 3.6.8
* **Platform:** linux-rhel7-thunderx2
* **Concretizer:** original

* gcc 10.2.0 installed with spack - maybe something related to how gcc formats output in newer versions, or a weird character in one of the cairo source files?

I'm currently trying to build it on another system using gcc 4.9.3; if that works I'll try a copy of gcc 10.2.0 on the other system and see if it starts failing. Given that some languages could be using fancy unicode characters like smiley faces (or diacritics) as part of their output, the logger seems like it should be able to ignore them without making a package build fail.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by nightlark** [comment]
Actually, this might be related to #15285, and it looks like there's PR #15206 as a possible fix.

**Comment by nightlark** [comment]
Okay, pretty sure this is just another instance of the locale issue. Closing duplicate.
