### ISSUE TITLE
compiler configuration error

### ISSUE THREAD

**Issue by iulian787** [LLNL/spack#20535]
We are trying to configure intel compilers for spack, on a ubuntu 14 system
we see this:
spack spec zlib%intel
Input spec
--------------------------------
zlib%intel

Concretized
--------------------------------
==> Error: Single '}' encountered in format string

in debug mode, we see this:
spack -d spec zlib%intel
==> [2020-12-23-09:12:52.246600] Imported spec from built-in commands
==> [2020-12-23-09:12:52.248892] Imported spec from built-in commands
Input spec
--------------------------------
zlib%intel

Concretized
```
--------------------------------
==> [2020-12-23-09:12:52.252889] Reading config file /nfs/fathom/3rdparty/spack/etc/spack/defaults/config.yaml
==> [2020-12-23-09:12:52.296989] Reading config file /nfs/fathom/3rdparty/spack/etc/spack/defaults/repos.yaml
==> [2020-12-23-09:12:52.525499] Reading config file /nfs/fathom/3rdparty/spack/etc/spack/defaults/packages.yaml
==> [2020-12-23-09:12:52.593493] Reading config file /homes/fathom/.spack/linux/compilers.yaml
Traceback (most recent call last):
  File "/homes/fathom/3rdparty/spack/bin/spack", line 66, in <module>
    sys.exit(spack.main.main())
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/spec.py", line 2530, in concretize
    self._old_concretize(tests)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/spec.py", line 2330, in _old_concretize
    self._concretize_helper(concretizer))
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/spec.py", line 2168, in _concretize_helper
    concretizer.adjust_target(self),
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/concretize.py", line 593, in adjust_target
    return next(self._adjust_target_answer_generator)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/concretize.py", line 586, in _make_only_one_call
    yield self._adjust_target(spec)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/concretize.py", line 628, in _adjust_target
    current_target.optimization_flags(spec.compiler)
  File "/nfs/fathom/3rdparty/spack/lib/spack/spack/architecture.py", line 228, in optimization_flags
    compiler.name, str(compiler_version)
  File "/nfs/fathom/3rdparty/spack/lib/spack/external/archspec/cpu/microarchitecture.py", line 264, in optimization_flags
    flags = flags_fmt.format(**compiler_entry)
ValueError: Single '}' encountered in format string
```

we also see this:
spack compiler info intel
intel@17.0.2:
	paths:
		cc = /soft/com/packages/intel/17/u2/bin/icc
		cxx = /soft/com/packages/intel/17/u2/bin/icpc
		f77 = /soft/com/packages/intel/17/u2/bin/ifort
		fc = /soft/com/packages/intel/17/u2/bin/ifort
	modules  = []
	operating system  = ubuntu14.04

Also, in ~/.spack/linux/compilers.yaml, we have this:
```
54 - compiler:
55     spec: intel@17.0.2
56     paths:
57       cc: /soft/com/packages/intel/17/u2/bin/icc
58       cxx: /soft/com/packages/intel/17/u2/bin/icpc
59       f77: /soft/com/packages/intel/17/u2/bin/ifort
60       fc: /soft/com/packages/intel/17/u2/bin/ifort
61     flags: {}
62     operating_system: ubuntu14.04
63     target: x86_64
64     modules: []
65     environment: {}
66     extra_rpaths: []

```
the compiler is working fine
icc --version
icc (ICC) 17.0.2 20170213
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.
