### ISSUE TITLE
uninstall -a <pkg> causes a ValueError exception

### ISSUE THREAD

**Issue by trws** [LLNL/spack#206]
With 2+ versions of a package installed, under some circumstances the `-a` flag to uninstall will cause DirectoryLayout to emit an exception about specs.  See below:

```
scogland at rzalastor1 in ~/spack (shell-arg-handling-fix●●)
$ spack uninstall cram
spack uninstall cram
==> Error: cram matches multiple packages:

-- chaos_5_x86_64_ib / gcc@4.4.7 --------------------------------
m3vzgwx cram@1.0.1

-- chaos_5_x86_64_ib / gcc@4.9.2 --------------------------------
uj2ipaz cram@1.0.1

You can either:
  a) Use a more specific spec, or
  b) use spack uninstall -a to uninstall ALL matching specs.

scogland at rzalastor1 in ~/spack (shell-arg-handling-fix●●)   !1!
$ spack uninstall -a cram
spack uninstall -a cram
Traceback (most recent call last):
  File "/g/g12/scogland/spack/bin/spack", line 146, in <module>
    main()
  File "/g/g12/scogland/spack/bin/spack", line 127, in main
    return_val = command(parser, args)
  File "/g/g12/scogland/spack/lib/spack/spack/cmd/uninstall.py", line 95, in uninstall
    pkg.do_uninstall(force=args.force)
  File "/g/g12/scogland/spack/lib/spack/spack/package.py", line 916, in do_uninstall
    spack.hooks.pre_uninstall(self)
  File "/g/g12/scogland/spack/lib/spack/spack/hooks/__init__.py", line 69, in __call__
    hook(pkg)
  File "/g/g12/scogland/spack/lib/spack/spack/hooks/extensions.py", line 35, in pre_uninstall
    if pkg.activated:
  File "/g/g12/scogland/spack/lib/spack/spack/package.py", line 518, in activated
    exts = spack.install_layout.extension_map(self.extendee_spec)
  File "/g/g12/scogland/spack/lib/spack/spack/directory_layout.py", line 346, in extension_map
    _check_concrete(spec)
  File "/g/g12/scogland/spack/lib/spack/spack/directory_layout.py", line 45, in _check_concrete
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!
```

**Comment by tgamblin** [comment]
@lee218llnl, @trws: I actually fixed this problem here: https://github.com/LLNL/spack/pull/210/files#diff-104f190bab262c2d346a5813c06926aaL214

However, that is not merged yet and I need to tweak it a bit first.  I will commit a quick fix.

**Comment by trws** [comment]
:+1:
