### ISSUE TITLE
An install_tree used successfully for a while is no longer usable. Can't figure out why

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#20700]
I am setting an install location with config.yaml:
```yaml
config:
  install_tree:
    root: /lustre/scratch4/yellow/stam/pilotlight-spack-snow-install
```

Spack debug report:
```console
$ spack debug report
* **Spack:** 0.16.0-487-8956c8c7b
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original
```

Today, I am not able to use this install_tree and am getting the error `==> Error: '<' not supported between instances of 'tuple' and 'str'` with simple commands like `spack find` and `spack uninstall <spec>`. Setting the install path to something else or using the default path works. I've tried reverting to older spack commits (v0.16.0) and am still get this error. Any guidance is appreciated. Thanks!

### Steps to reproduce the issue

```console
$ spack config blame config
spack config blame config
---                                                                                                                                  config:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/config.yaml:2               install_tree:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/config.yaml:3                 root: /lustre/scratch4/yellow/stam/pilotlight-spack-snow-install
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:21       projections:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:22         all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:33     template_dirs:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:33     - $spack/share/spack/templates
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:34   
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:38   
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:39     # Locations where different types of modules should be installed.
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:40     module_roots:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:68       tcl: $spack/share/spack/modules
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:69       lmod: $spack/share/spack/lmod
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:70     build_stage:
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:70     - $tempdir/$user/spack-stage
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:70     - ~/.spack/stage
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:70     # - $spack/var/spack/stage
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:70   
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:76     # Directory in which to run tests and store test results.
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:80     # Tests will be stored in directories named by date/time and package
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:85     # name/hash.
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:91     test_stage: ~/.spack/test
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:96     source_cache: $spack/var/spack/cache
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:104    misc_cache: ~/.spack/cache
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:110    connect_timeout: 10
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:115    verify_ssl: True
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:120    suppress_gpg_warnings: False
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:128    install_missing_compilers: False
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:137    checksum: True
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:149    dirty: False
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:163    build_language: C
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:170    locks: True
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:178    ccache: False
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:184    concretizer: original
/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml:189    db_lock_timeout: 3
_builtin                                                                                                                               package_lock_timeout: !!null 'None'
_builtin                                                                                                                               shared_linking: rpath
```

### Error Message

```console
$ spack -d find
==> [2021-01-06-09:30:20.016371] Imported find from built-in commands
==> [2021-01-06-09:30:20.017870] Imported find from built-in commands
==> [2021-01-06-09:30:20.019519] Reading config file /yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/defaults/config.yaml
==> [2021-01-06-09:30:20.047304] Reading config file /yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/etc/spack/config.yaml
==> [2021-01-06-09:30:20.051110] DATABASE LOCK TIMEOUT: 3s
==> [2021-01-06-09:30:20.051184] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/cmd/find.py", line 204, in find
    results = args.specs(**q_args)
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/cmd/common/arguments.py", line 79, in _specs
    return spack.store.db.query(**kwargs)
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/database.py", line 1491, in query
    local_results = set(self.query_local(*args, **kwargs))
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/spack/database.py", line 1476, in query_local
    return sorted(self._query(*args, **kwargs))
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/llnl/util/lang.py", line 249, in <lambda>
    lambda s, o: o is not None and s._cmp_key() < o._cmp_key())
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/llnl/util/lang.py", line 249, in <lambda>
    lambda s, o: o is not None and s._cmp_key() < o._cmp_key())
  File "/yellow/usr/projects/paraview/stam/pilotlight/tests/spack/tmp_snow_master_intel_19.0.4.243/spack/lib/spack/llnl/util/lang.py", line 249, in <lambda>
    lambda s, o: o is not None and s._cmp_key() < o._cmp_key())
TypeError: '<' not supported between instances of 'tuple' and 'str'
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
Similar issues I could find are https://github.com/spack/spack/issues/20310 and https://github.com/spack/spack/issues/18880
- [x] I have run the failing commands in debug mode and reported the output

**Comment by eugeneswalker** [comment]
@becker33 Does this look familiar? I had this problem at one point, and then I think Greg fixed something and it went away.

**Comment by alalazo** [comment]
@EthanS94 Is there some reproducer to replicate the behavior you saw?
