### ISSUE TITLE
Meson's `find_library` does not search dependencies

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#20721]
Tried packaging a Meson-based project that uses `find_library()` to find `libbfd` from `binutils` (needed since it doesn't ship a pkg-config or CMake file), but Meson will only search the system directories and not dependencies. Building outside Spack (using `spack load binutils`) works as desired.

### Steps to reproduce the issue

Create a minimal Meson project that uses `find_library`:
```console
$ mkdir /tmp/bug-project && cd /tmp/bug-project
$ cat > meson.build <<EOF
project('test', 'c')
meson.get_compiler('c').find_library('bfd', static: true)
configure_file(configuration: {'TEST': 1}, output: 'test.h', install: true, install_dir: 'include')
EOF
$ spack create --skip-editor -fn bug
$ cat > "`spack location -p bug`"/package.py <<EOF
from spack import *
class Bug(MesonPackage):
    url = "https://example.com"
    version('master', url="file:///tmp/bug-project.tar")
    depends_on('binutils')
EOF
$ tar cf ../bug-project.tar -C .. bug-project
$ spack install --only dependencies bug
```
Configuring outside of Spack (using `LIBRARY_PATH`) works fine:
```console
$ LIBRARY_PATH=`spack location -i binutils`/lib64:`spack location -i binutils`/lib:$LIBRARY_PATH meson setup meson-build-1
The Meson build system
Version: 0.58.1
Source dir: /tmp/bug-project
Build dir: /tmp/bug-project/meson-build-1
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library bfd found: YES
Configuring test.h using configuration
Build targets in project: 0

Found ninja-1.10.1 at /tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/ninja-1.10.2-ug54hcqtm4zwztp4yjviz5rc5jauxnfe/bin/ninja
```
Configuring using `dev-build` or `install` however fails:
```console
$ spack --debug dev-build bug@master
...
==> [2021-08-02-08:12:15.668024] Installing bug-master-omnuvkajoxoeovenak52izbdia6pf5jc
==> [2021-08-02-08:12:15.668050] Searching for binary cache of bug-master-omnuvkajoxoeovenak52izbdia6pf5jc
==> [2021-08-02-08:12:15.668094] Reading config file /tmp/spack/etc/spack/defaults/mirrors.yaml
==> [2021-08-02-08:12:16.003390] Did not find linux-debian11-zen2-gcc-11.1.0-bug-master-omnuvkajoxoeovenak52izbdia6pf5jc.spec.yaml on https://mirror.spack.io/build_cache/linux-debian11-zen2-gcc-11.1.0-bug-master-omnuvkajoxoeovenak52izbdia6pf5jc.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-08-02-08:12:16.003567] No binary for bug-master-omnuvkajoxoeovenak52izbdia6pf5jc found: installing from source
==> [2021-08-02-08:12:16.136936] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
==> [2021-08-02-08:12:16.228274] [TOOLCHAIN] MATCH Gcc
==> [2021-08-02-08:12:16.230568] Adding compiler bin/ paths: /tmp/spack/lib/spack/env /tmp/spack/lib/spack/env/case-insensitive /tmp/spack/lib/spack/env/gcc
==> [2021-08-02-08:12:16.241962] No libraries found for tar
==> [2021-08-02-08:12:16.242046] No headers found for tar
==> [2021-08-02-08:12:16.245110] No libraries found for binutils
==> [2021-08-02-08:12:16.264303] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=True, prefix=""))'
==> [2021-08-02-08:12:16.285693] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_inc; print(get_python_inc(plat_specific=False, prefix=""))'
==> [2021-08-02-08:12:16.307516] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:12:16.344070] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'prefix'"'"'))'
==> [2021-08-02-08:12:16.373854] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:12:16.409865] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:12:16.435559] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'CC'"'"'))'
==> [2021-08-02-08:12:16.457622] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'LDSHARED'"'"'))'
==> [2021-08-02-08:12:16.483819] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'CXX'"'"'))'
==> [2021-08-02-08:12:16.505541] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'LDCXXSHARED'"'"'))'
==> [2021-08-02-08:12:16.548110] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-08-02-08:12:16.569285] '/usr/bin/g++-11' '-v' '/tmp/user/1000/spack-implicit-link-infow20t0xhc/main.c' '-o' '/tmp/user/1000/spack-implicit-link-infow20t0xhc/output'
==> [2021-08-02-08:12:16.600247] parsing implicit link info
==> [2021-08-02-08:12:16.600581] linker line:  /usr/lib/gcc/x86_64-linux-gnu/11/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper -plugin-opt=-fresolution=/tmp/user/1000/cckE52JK.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o /tmp/user/1000/spack-implicit-link-infow20t0xhc/output /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. /tmp/user/1000/cc3zIVwJ.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crtn.o
==> [2021-08-02-08:12:16.600652] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11
==> [2021-08-02-08:12:16.600683] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu
==> [2021-08-02-08:12:16.600708] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib
==> [2021-08-02-08:12:16.600731] linkdir: /lib/x86_64-linux-gnu
==> [2021-08-02-08:12:16.600753] linkdir: /lib/../lib
==> [2021-08-02-08:12:16.600775] linkdir: /usr/lib/x86_64-linux-gnu
==> [2021-08-02-08:12:16.600797] linkdir: /usr/lib/../lib
==> [2021-08-02-08:12:16.600819] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../..
==> [2021-08-02-08:12:16.600857] found raw link dirs: /usr/lib/gcc/x86_64-linux-gnu/11, /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu, /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib, /lib/x86_64-linux-gnu, /lib/../lib, /usr/lib/x86_64-linux-gnu, /usr/lib/../lib, /usr/lib/gcc/x86_64-linux-gnu/11/../../..
==> [2021-08-02-08:12:16.600933] found link dirs: /usr/lib/gcc/x86_64-linux-gnu/11, /usr/lib/x86_64-linux-gnu, /usr/lib, /lib/x86_64-linux-gnu, /lib
==> [2021-08-02-08:12:16.602104] No need to fetch for DIY.
==> [2021-08-02-08:12:16.602177] No checksum needed for DIY.
==> [2021-08-02-08:12:16.602216] Sources for DIY stages are not cached
==> [2021-08-02-08:12:16.602256] Using source directory: /tmp/bug-project
==> [2021-08-02-08:12:16.602316] No patches needed for bug
==> [2021-08-02-08:12:16.602372] bug: Building bug-master-omnuvkajoxoeovenak52izbdia6pf5jc [MesonPackage]
==> [2021-08-02-08:12:16.605889] bug: Executing phase: 'meson'
==> [2021-08-02-08:12:16.607756] 'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
The Meson build system
Version: 0.59.0
Source dir: /tmp/bug-project
Build dir: /tmp/bug-project/spack-build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: /tmp/spack/lib/spack/env/gcc/gcc (gcc 11.1.0 "gcc-11 (Debian 11.1.0-3) 11.1.0")
C linker for the host machine: /tmp/spack/lib/spack/env/gcc/gcc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64

../meson.build:2:24: ERROR: C static library 'bfd' not found

A full log can be found at /tmp/bug-project/spack-build/meson-logs/meson-log.txt
==> [2021-08-02-08:12:17.032247] Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
See build log for details:
  /tmp/bug-project/spack-build-out.txt

Traceback (most recent call last):
  File "/tmp/spack/lib/spack/spack/build_environment.py", line 1013, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/tmp/spack/lib/spack/spack/installer.py", line 1792, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/tmp/spack/lib/spack/spack/package.py", line 115, in phase_wrapper
    phase(spec, prefix)
  File "/tmp/spack/lib/spack/spack/build_systems/meson.py", line 162, in meson
    inspect.getmodule(self).meson(*options)
  File "/tmp/spack/lib/spack/spack/util/executable.py", line 225, in __call__
    raise ProcessError('Command exited with status %d:' %
spack.util.executable.ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
==> [2021-08-02-08:12:17.037752] Flagging bug-master-omnuvkajoxoeovenak52izbdia6pf5jc as failed: ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
==> [2021-08-02-08:12:17.039915] ChildError: ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
==> Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-omnuvkajoxoeovenak52izbdia6pf5jc/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
==> Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/bug-project' '--prefix=/tmp/spack/opt/spack/linux-debianunstable-zen2/gcc-10.2.0/bug-master-k74oxjaungxglzy4sohsnjsyyua56pdb' '--libdir=/tmp/spack/opt/spack/linux-debianunstable-zen2/gcc-10.2.0/bug-master-k74oxjaungxglzy4sohsnjsyyua56pdb/lib' '--buildtype=release' '--strip'
See build log for details:
  /tmp/bug-project/spack-build-out.txt
$ spack --debug install -nv bug
...
==> [2021-08-02-08:11:08.503172] Installing bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b
==> [2021-08-02-08:11:08.503202] Searching for binary cache of bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b
==> [2021-08-02-08:11:08.503248] Reading config file /tmp/spack/etc/spack/defaults/mirrors.yaml
==> [2021-08-02-08:11:09.022763] Did not find linux-debian11-zen2-gcc-11.1.0-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b.spec.yaml on https://mirror.spack.io/build_cache/linux-debian11-zen2-gcc-11.1.0-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-08-02-08:11:09.022949] No binary for bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b found: installing from source
==> [2021-08-02-08:11:09.138000] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
==> [2021-08-02-08:11:09.254319] [TOOLCHAIN] MATCH Gcc
==> [2021-08-02-08:11:09.255329] Adding compiler bin/ paths: /tmp/spack/lib/spack/env /tmp/spack/lib/spack/env/case-insensitive /tmp/spack/lib/spack/env/gcc
==> [2021-08-02-08:11:09.264742] No libraries found for tar
==> [2021-08-02-08:11:09.264824] No headers found for tar
==> [2021-08-02-08:11:09.267850] No libraries found for binutils
==> [2021-08-02-08:11:09.300777] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=True, prefix=""))'
==> [2021-08-02-08:11:09.338864] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_inc; print(get_python_inc(plat_specific=False, prefix=""))'
==> [2021-08-02-08:11:09.363554] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:11:09.386596] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'prefix'"'"'))'
==> [2021-08-02-08:11:09.423459] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:11:09.444999] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=False, standard_lib=False, prefix=""))'
==> [2021-08-02-08:11:09.486685] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'CC'"'"'))'
==> [2021-08-02-08:11:09.507901] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'LDSHARED'"'"'))'
==> [2021-08-02-08:11:09.530318] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'CXX'"'"'))'
==> [2021-08-02-08:11:09.554881] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/python-3.8.11-jgjrqu6v64tnj7bqdghjh26ecgorn6er/bin/python3.8' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'LDCXXSHARED'"'"'))'
==> [2021-08-02-08:11:09.606000] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-08-02-08:11:09.627120] '/usr/bin/g++-11' '-v' '/tmp/user/1000/spack-implicit-link-info75z_ohpc/main.c' '-o' '/tmp/user/1000/spack-implicit-link-info75z_ohpc/output'
==> [2021-08-02-08:11:09.658627] parsing implicit link info
==> [2021-08-02-08:11:09.658992] linker line:  /usr/lib/gcc/x86_64-linux-gnu/11/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper -plugin-opt=-fresolution=/tmp/user/1000/cc4R5Dla.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -o /tmp/user/1000/spack-implicit-link-info75z_ohpc/output /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. /tmp/user/1000/cc57jlJa.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crtn.o
==> [2021-08-02-08:11:09.659076] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11
==> [2021-08-02-08:11:09.659111] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu
==> [2021-08-02-08:11:09.659139] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib
==> [2021-08-02-08:11:09.659166] linkdir: /lib/x86_64-linux-gnu
==> [2021-08-02-08:11:09.659194] linkdir: /lib/../lib
==> [2021-08-02-08:11:09.659221] linkdir: /usr/lib/x86_64-linux-gnu
==> [2021-08-02-08:11:09.659247] linkdir: /usr/lib/../lib
==> [2021-08-02-08:11:09.659273] linkdir: /usr/lib/gcc/x86_64-linux-gnu/11/../../..
==> [2021-08-02-08:11:09.659319] found raw link dirs: /usr/lib/gcc/x86_64-linux-gnu/11, /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu, /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib, /lib/x86_64-linux-gnu, /lib/../lib, /usr/lib/x86_64-linux-gnu, /usr/lib/../lib, /usr/lib/gcc/x86_64-linux-gnu/11/../../..
==> [2021-08-02-08:11:09.659404] found link dirs: /usr/lib/gcc/x86_64-linux-gnu/11, /usr/lib/x86_64-linux-gnu, /usr/lib, /lib/x86_64-linux-gnu, /lib
==> [2021-08-02-08:11:09.661209] Checking existence of https://mirror.spack.io/bug/bug-master.tar
==> [2021-08-02-08:11:10.050133] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/bug/bug-master.tar
    Urllib fetch failed to verify url https://mirror.spack.io/bug/bug-master.tar
==> [2021-08-02-08:11:10.050491] Checking existence of file:///tmp/bug-project.tar
==> [2021-08-02-08:11:10.056139] Fetching file:///tmp/bug-project.tar
==> [2021-08-02-08:11:10.057356] Fetching from https://mirror.spack.io/bug/bug-master.tar failed.
==> [2021-08-02-08:11:10.057555] Staging archive: /tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/bug-project.tar
==> [2021-08-02-08:11:10.058338] '/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/tar-1.34-veysxngydxddopehawssldbizsoumttv/bin/tar' '-oxf' '/tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/bug-project.tar'
==> [2021-08-02-08:11:10.062922] Created stage in /tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b
==> [2021-08-02-08:11:10.063102] No patches needed for bug
==> [2021-08-02-08:11:10.063182] bug: Building bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b [MesonPackage]
==> [2021-08-02-08:11:10.066952] bug: Executing phase: 'meson'
==> [2021-08-02-08:11:10.068510] 'meson' '/tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/spack-src' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
The Meson build system
Version: 0.59.0
Source dir: /tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/spack-src
Build dir: /tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/spack-src/spack-build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: /tmp/spack/lib/spack/env/gcc/gcc (gcc 11.1.0 "gcc-11 (Debian 11.1.0-3) 11.1.0")
C linker for the host machine: /tmp/spack/lib/spack/env/gcc/gcc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64

../meson.build:2:24: ERROR: C static library 'bfd' not found

A full log can be found at /tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/spack-src/spack-build/meson-logs/meson-log.txt
==> [2021-08-02-08:11:10.540303] Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/user/1000/deepthought/spack-stage/spack-stage-bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/spack-src' '--prefix=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b' '--libdir=/tmp/spack/opt/spack/linux-debian11-zen2/gcc-11.1.0/bug-master-7vl5srbcdnxds7obnqbox5n4xi2qny3b/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared'
```

Note that this error only occurs when the `static:` flag is passed:
```console
$ rm -r spack-* *-build*
$ cat > meson.build <<EOF
project('test', 'c')
meson.get_compiler('c').find_library('bfd')
configure_file(configuration: {'TEST': 1}, output: 'test.h', install: true, install_dir: 'include')
EOF
$ tar cf ../bug-project.tar -C .. bug-project
$ spack --debug dev-build bug@master
# ... Completes without error
$ spack --debug install -nv bug
# ... Completes without error
```

### Information on your system

* **Spack:** 0.16.2-3754-ac8521e9b3
* **Python:** 3.9.2
* **Platform:** linux-debian11-zen2
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by michaelkuhn** [comment]
Does this also happen if you do `spack install` or only within `dev-build`?

**Comment by blue42u** [comment]
I can confirm it happens both within `spack install` and within `dev-build`, with the same log messages and on the current `develop`.
