### ISSUE TITLE
running `spack style` leaves a '.mypy_cache' directory behind

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#20798]
### Steps to reproduce the issue

```console
$ spack style
...
```

### Error Message

```console
$ git status
# On branch r-pixmap
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       .mypy_cache/
nothing added to commit but untracked files present (use "git add" to track)
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.11.2-10325-f4055ec
* **Python:** 3.8.7
* **Platform:** linux-centos7-broadwell
* **Concretizer:** original
```

```console
$ spack --debug style
==> [2021-01-12-10:40:54.990566] Imported style from built-in commands
==> [2021-01-12-10:40:54.992053] Imported style from built-in commands
==> [2021-01-12-10:40:54.993875] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR' 'develop...'
==> [2021-01-12-10:40:55.012867] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR' '--cached'
==> [2021-01-12-10:40:55.049336] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR'
==> [2021-01-12-10:40:55.102872] '/usr/bin/git' 'ls-files' '--exclude-standard' '--other'
==> [2021-01-12-10:40:55.181959] style: running code checks on spack.
==> [2021-01-12-10:40:55.182299] style: tools selected: flake8, mypy
==> [2021-01-12-10:40:55.182406] Modified files:
  var/spack/repos/builtin/packages/r-pixmap/package.py
==> [2021-01-12-10:40:55.182536] style: running flake8 checks on spack.
==> [2021-01-12-10:40:55.183897] '/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/py-flake8-3.8.2-e3rr6xb7xyf2r2jkqxgrfptcpw76mx7a/bin/flake8' 'var/spack/repos/builtin/packages/r-pixmap/package.py'
==> [2021-01-12-10:40:55.457874] Flake8 style checks were clean
==> [2021-01-12-10:40:55.458933] style: running mypy checks on spack.
==> [2021-01-12-10:40:55.459522] '/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/py-mypy-0.740-eh7swcmk3e5bwe4tnjjrhv7jq73mmzdh/bin/mypy' 'var/spack/repos/builtin/packages/r-pixmap/package.py'
var/spack/repos/builtin/packages/r-pixmap/package.py:6: error: Cannot find module named 'spack'
var/spack/repos/builtin/packages/r-pixmap/package.py:6: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
var/spack/repos/builtin/packages/r-pixmap/package.py:9: error: Name 'RPackage' is not defined
var/spack/repos/builtin/packages/r-pixmap/package.py:18: error: Name 'version' is not defined
Found 3 errors in 1 file (checked 1 source file)
==> [2021-01-12-10:40:58.188821] Error: mypy checks found errors
spack style found errors.
==> [2021-01-12-10:40:58.191196] Reading config file /opt/packages/gpjohnsn/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/opt/packages/gpjohnsn/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/packages/gpjohnsn/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/opt/packages/gpjohnsn/spack/lib/spack/spack/cmd/style.py", line 330, in style
    sys.exit(1)
SystemExit: 1
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Fixed by #20613
