### ISSUE TITLE
Installation issue of ruby-packages

### ISSUE THREAD

**Issue by ghost** [LLNL/spack#20833]
I am trying to create the recipe of glib2 which depends on native-package-installer and pkg-config.
Glib2, native-package-installer and pkg-config are the ruby packages.
When I install glib2 with my recipe, I get an error "cannot load such file -- pkg-config (LoadError)."
What should I do with this in this case?

The following is detailed information.

glib2: https://rubygems.org/gems/glib2
native-package-installer : https://rubygems.org/gems/native-package-installer
pkg-config : https://rubygems.org/gems/pkg-config

The error message is as follows.
It seems that the ruby that installed by spack can find the pkg-config.
However, ruby can not load the pkg-config when I install the glib2 by spack.

```
/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- pkg-config (LoadError)
        from /spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-glib2-3.4.3-wh2rwfxpp7r4oazglfwdrspt3qdvn2ks/gems/glib2-3.4.3/lib/mkmf-gnome.rb:19:in `<top (required)>'
        from /spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from extconf.rb:27:in `<main>'
```
I run "gem environment gempath" command on install method on recipes of glib2, then I can get a path of pkg-config.

```
==> [2020-12-28-12:01:15.850345] '/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/bin/gem' 'environment' 'gempath'
/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-glib2-3.4.3-wh2rwfxpp7r4oazglfwdrspt3qdvn2ks:/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-native-package-installer-1.0.9-mthicv2khskl4sc77tzkb7lea6f2zqw3:/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-pkg-config-1.4.4-r7w56kv7ctvwsqnytpmtlhgkzx4vs3ym
```

I also can get a pkg-config with "gem list".

```
==> [2020-12-28-12:01:16.177351] '/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/bin/gem' 'list'
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)

・・・

pkg-config (1.4.4)
```
Could you give me some advice on how to deal with this issue?

### Additional information
[recipes.zip](https://github.com/spack/spack/files/5808041/recipes.zip)
[spack-build-env.txt](https://github.com/spack/spack/files/5808043/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5808044/spack-build-out.txt)

**Comment by adamjstewart** [comment]
Maybe it depends on `pkgconfig` instead of `ruby-pkg-config`? Maybe `ruby-pkg-config` depends on `pkgconfig`?

**Comment by ghost** [comment]
Thank you for your advice. 

> Maybe it depends on pkgconfig instead of ruby-pkg-config? Maybe ruby-pkg-config depends on pkgconfig?

ruby-glib2 dose not depend on pkgconfig.
And ruby-pkg-config dose not depend on pkgconfig.

I changed the ruby-pkg-config to depend on pkgconfig and tried again.
However, the results didn't change.

This problem did not occur when I installed glib2 and pkg-config without use of spack.

It seems that  ruby package can not load other  ruby packages installed using spack ,when ruby package was installed using spack. 
Could you give me some advice on how to deal with this issue?

**Comment by adamjstewart** [comment]
Tbh I don't know a ton about Ruby. We are setting `GEM_PATH`, which I assume is what controls how Ruby dependencies are found. Pinging @Try2Code @t-brown @marcmengel @mathstuf @DiegoMagdaleno who may know more than me about Ruby.

**Comment by ghost** [comment]
Did you hear anything from them after that?
Please let me know if you need more information concerning this matter.

**Comment by Try2Code** [comment]
sry guys, was busy with work. I will give it shot today with what usually do with Ruby

**Comment by Try2Code** [comment]
I tested my rather big gemset with ruby@2.5.3  ruby@2.6.2  ruby@2.7.1 (all build with gcc-10.2). All went through without problems:
```benchmark-0.1.0   did_you_mean-1.4.0  io-console-0.5.6  net-pop-0.1.0     ostruct-0.2.0       readline-0.0.2      stringio-0.1.0   yaml-0.1.0
bigdecimal-2.0.0  etc-1.1.0           ipaddr-1.2.2      net-smtp-0.1.0    power_assert-1.1.7  readline-ext-0.1.0  strscan-1.0.3    zlib-1.1.0
bundler-2.1.4     fcntl-1.0.0         irb-1.2.3         net-telnet-0.2.0  prime-0.1.1         reline-0.1.3        test-unit-3.3.4
cgi-0.1.0         fiddle-1.0.0        json-2.3.0        numo-fftw-0.1.1   pstore-0.1.0        rexml-3.2.3         timeout-0.1.0
csv-3.1.2         fileutils-1.4.1     logger-1.4.2      numo-gsl-0.1.2    psych-3.1.0         rss-0.2.8           tracer-0.1.0
date-3.0.0        forwardable-1.3.1   matrix-0.2.0      observer-0.1.0    racc-1.4.16         ruby-netcdf-0.7.2   uri-0.10.0
dbm-1.1.0         gdbm-2.1.0          minitest-5.13.0   open3-0.1.0       rake-13.0.1         sdbm-1.0.0          webrick-1.6.0
delegate-0.1.0    getoptlong-0.1.0    mutex_m-0.1.0     openssl-2.1.2     rdoc-6.2.1          singleton-0.1.0     xmlrpc-0.3.0
```

those are pure ruby but also C-extensions. IMO it's ready to work with. Finally checked the glib2 gem package based on my system installation (Arch Linux):```❯ gem install glib2                                                                                                                                         ─╯
Fetching glib2-3.4.3.gem
Fetching native-package-installer-1.1.1.gem
Fetching pkg-config-1.4.5.gem
Successfully installed pkg-config-1.4.5
Successfully installed native-package-installer-1.1.1
Building native extensions. This could take a while...
Successfully installed glib2-3.4.3
3 gems installed
```

**Comment by Try2Code** [comment]
now the fun part: installing a library with spack and build a ruby gem on top of it

I tested this with ruby-2.7.1 and the following gems: 
* glib2
* ruby-netcdf
* gsl

All of them have spack packages for the underlying C-libs, so I installed and loaded them with spack before installing the ruby-libraries with gem. Everything went smoothly and the shared objects build for the ruby-libraries correctly link to the spack-installed C shared libraries. run tests with gsl and ruby-netcdf worked fine.

**Comment by Try2Code** [comment]
I am not familiar with glib2 and its ruby-bindings, so I don;t know what to run. any advice is welcome

**Comment by ghost** [comment]
Thank you for your comment.
I attached the recipes.zip on "Additional information". 
The recipes.zip contains three recipes which install gem files (glib2, pkg-config and native-package-installer).
These are recipes when this problem occuers.
glib2 depends on pkg-config and native-package-installer.
Could you try to install them using those recipes?

**Comment by Try2Code** [comment]
```Installing ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
==> No binary for ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn found: installing from source
==> Fetching https://rubygems.org/downloads/pkg-config-1.4.4.gem
######################################################################################################################################################## 100.0%
==> ruby-pkg-config: Executing phase: 'build'
==> ruby-pkg-config: Executing phase: 'install'
==> ruby-pkg-config: Successfully installed ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
  Fetch: 2.02s.  Build: 1.17s.  Total: 3.18s.
[+] /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
==> Installing ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
==> No binary for ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu found: installing from source
==> Fetching https://rubygems.org/downloads/native-package-installer-1.0.9.gem
######################################################################################################################################################## 100.0%
==> ruby-native-package-installer: Executing phase: 'build'
==> ruby-native-package-installer: Executing phase: 'install'
==> ruby-native-package-installer: Successfully installed ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
  Fetch: 1.90s.  Build: 0.87s.  Total: 2.77s.
[+] /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
==> Installing ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye
==> No binary for ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye found: installing from source
==> Fetching https://rubygems.org/downloads/glib2-3.4.3.gem
######################################################################################################################################################## 100.0%
==> ruby-glib2: Executing phase: 'build'
==> ruby-glib2: Executing phase: 'install'
==> ruby-glib2: Successfully installed ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye
  Fetch: 1.89s.  Build: 30.17s.  Total: 32.07s.
[+] /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye
```

recipes put next to the default packages. spack seems to handle the dependencies correctly. and the shared object of ruby-glib2 looks fine:

```
ldd /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/extensions/x86_64-linux/2.7.0-static/glib2-3.4.3/glib2.so
	linux-vdso.so.1 (0x00007fff49162000)
	libglib-2.0.so.0 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/glib-2.66.2-dhg7ncdgum6oz3q73wit7kt2siyhblh7/lib/libglib-2.0.so.0 (0x00007f01b6ef8000)
	libintl.so.8 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/gettext-0.21-tw4mo3k4f7hb7rqdukq4edhkfvgvkfl5/lib/libintl.so.8 (0x00007f01b6eeb000)
	libgobject-2.0.so.0 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/glib-2.66.2-dhg7ncdgum6oz3q73wit7kt2siyhblh7/lib/libgobject-2.0.so.0 (0x00007f01b6e8b000)
	libgthread-2.0.so.0 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/glib-2.66.2-dhg7ncdgum6oz3q73wit7kt2siyhblh7/lib/libgthread-2.0.so.0 (0x00007f01b6e86000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f01b6ced000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f01b6b22000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f01b6b00000)
	libpcre.so.1 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/pcre-8.44-vwy45wzm2v64xo6tqxuuq556hxxcwpi6/lib/libpcre.so.1 (0x00007f01b6abb000)
	libiconv.so.2 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/libiconv-1.16-z34qlnydgr6bmwapjlvhz6jcpljdz3ax/lib/libiconv.so.2 (0x00007f01b69bd000)
	libffi.so.7 => /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/libffi-3.3-nw2md7fp6qd7eqsqgykanftrt4roqai4/lib/../lib/libffi.so.7 (0x00007f01b69ae000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f01b70a3000)
```

**Comment by Try2Code** [comment]
anything else I can do?

I use 52058ad5a7 currently

**Comment by ghost** [comment]
You succeeded to install glib2 using my recipes, so I tried to install glib2 using my recipes and currently spack.
However, the results didn't change.

Maybe, did you install glib2 using my recipes on environment which installed glib2, pkg-config and native-package-installer using gem install command without recipes ?

I wonder that pkg-config and native-package-installer installed using gem command were loaded when glib2 was installed using recipes.

If so, could you try to install them using my recipes after uninstall glib2, pkg-config and native-package-installer in the following steps ?
Probably, this problem will reappear.

```
1. $ spack uninstall ruby-glib2 ruby-pkg-config ruby-native-package-installer

2. $ spack load ruby

3. $ gem uninstall glib2 pkg-config native-package-installer

4. $ spack install ruby-glib2
```

**Comment by Try2Code** [comment]
first run:
```
==> Installing ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
==> No binary for ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn found: installing from source
==> Using cached archive: /home/user/src/tools/spack/var/spack/cache/_source-cache/archive/23/23d64f7a82dec11baf00d09c5a9199b5dff28830723286e721f30b3b4c721a19
==> ruby-pkg-config: Executing phase: 'build'
==> ruby-pkg-config: Executing phase: 'install'
==> ruby-pkg-config: Successfully installed ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
  Fetch: 0.00s.  Build: 1.08s.  Total: 1.08s.
[+] /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-pkg-config-1.4.4-r3zqtu6dds5gavgcsazdkj5dlivt5gtn
==> Installing ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
==> No binary for ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu found: installing from source
==> Using cached archive: /home/user/src/tools/spack/var/spack/cache/_source-cache/archive/80/80bad0273706eeb4fc49ac8fa589b25eb6728c85a09fd241c8f0f06bdca32c5e
==> ruby-native-package-installer: Executing phase: 'build'
==> ruby-native-package-installer: Executing phase: 'install'
==> ruby-native-package-installer: Successfully installed ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
  Fetch: 0.00s.  Build: 1.71s.  Total: 1.72s.
[+] /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-native-package-installer-1.0.9-feflvnpyyaex24rz7k3wj2ibb3mjaefu
==> Installing ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye
==> No binary for ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye found: installing from source
==> Using cached archive: /home/user/src/tools/spack/var/spack/cache/_source-cache/archive/30/30265e3339927bb04c063ebb9793ee9014ac565699e07e4668f7abe35af58650
==> ruby-glib2: Executing phase: 'build'
==> ruby-glib2: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/bin/gem' 'install' 'glib2-3.4.3.gem'
See build log for details:
  /tmp/user/spack-stage/spack-stage-ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/spack-build-out.txt
```

error looks like this in more detail:
```
==> ruby-glib2: Executing phase: 'build'    
==> ruby-glib2: Executing phase: 'install'  
==> [2021-02-10-09:57:48.863815] '/home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/bin/gem' 'install' 'glib2-3.4.3.gem'
Building native extensions. This could take a while...                                                                                  
ERROR:  Error installing glib2-3.4.3.gem:   
        ERROR: Failed to build gem native extension.                                                                                    
                                            
    current directory: /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/gems/glib2-3.4.3/ext/glib2
/home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/bin/ruby -I /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snig
*** extconf.rb failed ***                   
Could not create Makefile due to some reason, probably lack of necessary                                                                
libraries and/or headers.  Check the mkmf.log file for more details.  You may                                                           
need configuration options.                 
                                            
Provided configuration options:             
        --with-opt-dir                      
        --without-opt-dir                   
        --with-opt-include                  
        --without-opt-include=${opt-dir}/include                                                                                        
        --with-opt-lib                      
        --without-opt-lib=${opt-dir}/lib    
        --with-make-prog                    
        --without-make-prog                 
        --srcdir=.                          
        --curdir                            
        --ruby=/home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/bin/$(RUBY_BASE_NAME)
/home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- pkg-c
        from /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/gems/glib2-3.4.3/lib/mkmf-gnome.rb:19:in `<top (required)>'
        from /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-2.7.1-snigqwpj7wer7rvtwsjwbi6w67bfuuaw/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from extconf.rb:27:in `<main>'      
                                            
extconf failed, exit code 1                 
                                            
Gem files will remain installed in /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/gems/glib2-3.4.3 for inspection.
Results logged to /home/user/src/tools/spack/opt/spack/linux-antergos-skylake/gcc-10.2.0/ruby-glib2-3.4.3-okqgdh4glc3ml5okszju23ppuhvffaye/extensions/x86_64-linux/2.7.0-static/glib2-3.4.3/gem_make.out 
```

**Comment by Try2Code** [comment]
But `gem install glib2` works without problems
```
gem install glib2                                                                                                                                                                                               ─╯
Fetching glib2-3.4.3.gem
Fetching pkg-config-1.4.5.gem
Fetching native-package-installer-1.1.1.gem
Successfully installed pkg-config-1.4.5
Successfully installed native-package-installer-1.1.1
Building native extensions. This could take a while...
Successfully installed glib2-3.4.3
3 gems installed
```

**Comment by Try2Code** [comment]
@takanori-ihara please let me know in case you need more testing my me - happy to help with this one :ocean:

**Comment by ghost** [comment]
I want to solve this problem which you reproduced for installing glib2 using recipe by spack.

I run "gem environment gempath" command on install method on recipes of glib2, then I can get a path of pkg-config.
```
==> [2020-12-28-12:01:15.850345] '/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/bin/gem' 'environment' 'gempath'
/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-glib2-3.4.3-wh2rwfxpp7r4oazglfwdrspt3qdvn2ks:/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-native-package-installer-1.0.9-mthicv2khskl4sc77tzkb7lea6f2zqw3:/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-pkg-config-1.4.4-r7w56kv7ctvwsqnytpmtlhgkzx4vs3ym
```

I also can get a pkg-config with "gem list".

```
==> [2020-12-28-12:01:16.177351] '/spack/ihara/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/ruby-2.7.1-sevf3kxjmb7qiyywlhioqjfsgkjznp7w/bin/gem' 'list'
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)

・・・

pkg-config (1.4.4)
```

It seems that the ruby that installed by spack can find the pkg-config installed by spack.
However, ruby can not load the pkg-config when I install the glib2 using recipe by spack.

Is there something that is considered to be the cause of that?
