### ISSUE TITLE
PCL

### ISSUE THREAD

**Issue by mlawsonca** [LLNL/spack#20984]
### Steps to reproduce the issue
```
$ spack -kL install pcl ipo=true build_type=Release  ^/knnhybb ^/c2z7xdw
...
==> Installing pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx
==> No binary for pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx found: installing from source
==> Fetching https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.11.1/source.tar.gz
######################################################################## 100.0%
==> pcl: Executing phase: 'cmake'
==> pcl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

2 errors found in build log:
     1459    0x104b2707 execute
     1460    	/var/tmp/mlawso/spack-stage/spack-stage-gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/spack-src/gcc/cfgexpand.c:6410
     1461    Please submit a full bug report,
     1462    with preprocessed source if appropriate.
     1463    Please include the complete backtrace with any bug report.
     1464    See <https://github.com/spack/spack/issues> for instructions.
  >> 1465    make[2]: *** [octree/CMakeFiles/pcl_octree.dir/build.make:85: octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o] Error 1
     1466    make[2]: Leaving directory '/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-build-rk6vazv'
  >> 1467    make[1]: *** [CMakeFiles/Makefile2:997: octree/CMakeFiles/pcl_octree.dir/all] Error 2
     1468    make[1]: *** Waiting for unfinished jobs....
     1469    [ 18%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_registration.cpp.o
     1470    cd /tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-build-rk6vazv/sample_consensus && /home/mlawso/bin/spack/lib/spack/env/gcc/g++ -DPCLAPI_E
             XPORTS -I/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-build-rk6vazv/include -I/var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2
             wwcdj4tnosovbtpauofytilx/spack-src/common/include -I/var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/search/include -I/var/tmp/mlawso
             /spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/sample_consensus/include -isystem /home/mlawso/bin/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/
             eigen-3.3.8-7zu4t7nycap5lvex7tkg432o55hsjb7f/include/eigen3 -isystem /var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/recognition/inc
             lude/pcl/recognition/3rdparty -isystem /home/mlawso/bin/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/boost-1.74.0-5mex2awuqrgb3qp7qbj2kljabwriyntf/include -Wabi=11 -Wall -Wext
             ra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion -mtune=native -ffloat-store -fopenmp -O3 -DNDEBUG -fPI
             C -fopenmp -std=c++14 -o CMakeFiles/pcl_sample_consensus.dir/src/sac_model_registration.cpp.o -c /var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofyti
             lx/spack-src/sample_consensus/src/sac_model_registration.cpp
     1471    [ 18%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_sphere.cpp.o
     1472    cd /tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-build-rk6vazv/sample_consensus && /home/mlawso/bin/spack/lib/spack/env/gcc/g++ -DPCLAPI_E
             XPORTS -I/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-build-rk6vazv/include -I/var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2
             wwcdj4tnosovbtpauofytilx/spack-src/common/include -I/var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/search/include -I/var/tmp/mlawso
             /spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/sample_consensus/include -isystem /home/mlawso/bin/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/
             eigen-3.3.8-7zu4t7nycap5lvex7tkg432o55hsjb7f/include/eigen3 -isystem /var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/recognition/inc
             lude/pcl/recognition/3rdparty -isystem /home/mlawso/bin/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/boost-1.74.0-5mex2awuqrgb3qp7qbj2kljabwriyntf/include -Wabi=11 -Wall -Wext
             ra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion -mtune=native -ffloat-store -fopenmp -O3 -DNDEBUG -fPI
             C -fopenmp -std=c++14 -o CMakeFiles/pcl_sample_consensus.dir/src/sac_model_sphere.cpp.o -c /var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spa
             ck-src/sample_consensus/src/sac_model_sphere.cpp
     1473    In file included from /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/include/c++/10.2.0/vector:72,
```
### Information on your system
* **Spack:** 0.16.0-578-295ad5e292
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original

```yaml
packages:
  tcl:
    version: [8.5]
    buildable: false
    externals:
    - spec: tcl@8.5
      prefix: /usr
  cuda:
    externals:
    - spec: cuda@10.1.243
      modules:
      - cuda/10.1.243
  openmpi:
    version: [4.1.0]
  cmake:
    version: [3.19.1]
  all:
    compiler: [gcc@10.2.0]
```
### Additional information
[spack-build-env.txt](https://github.com/spack/spack/files/5823320/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5823321/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

Also note: I used -L because I received the following error without it:
```
$ spack -d install pcl ipo=true build_type=Release
==> [2021-01-14-22:32:36.727977] Imported install from built-in commands
==> [2021-01-14-22:32:36.733344] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/config.yaml
==> [2021-01-14-22:32:36.776809] Imported install from built-in commands
==> [2021-01-14-22:32:36.782027] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/repos.yaml
==> [2021-01-14-22:32:49.900581] eigen applying constraint cmake
==> [2021-01-14-22:32:49.914691] flann applying constraint cmake
==> [2021-01-14-22:32:50.010920] diffutils applying constraint iconv
==> [2021-01-14-22:32:50.011970] bzip2 applying constraint diffutils
==> [2021-01-14-22:32:50.025426] boost applying constraint bzip2
==> [2021-01-14-22:32:50.026740] boost applying constraint zlib
==> [2021-01-14-22:32:50.028450] pcl applying constraint cmake@3.5:
==> [2021-01-14-22:32:50.029686] pcl applying constraint eigen@3.1:
==> [2021-01-14-22:32:50.030914] pcl applying constraint flann@1.7:
==> [2021-01-14-22:32:50.032240] pcl applying constraint boost@1.55:+date_time+filesystem+iostreams+system
==> [2021-01-14-22:32:50.034397] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/packages.yaml
==> [2021-01-14-22:32:50.092629] Reading config file /ascldap/users/mlawso/.spack/packages.yaml
Traceback (most recent call last):
  File "/ascldap/users/mlawso/bin/spack/bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "/home/mlawso/bin/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/mlawso/bin/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/mlawso/bin/spack/lib/spack/spack/cmd/install.py", line 309, in install
    args.spec, concretize=True, tests=tests)
  File "/home/mlawso/bin/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/mlawso/bin/spack/lib/spack/spack/spec.py", line 2530, in concretize
    self._old_concretize(tests)
  File "/home/mlawso/bin/spack/lib/spack/spack/spec.py", line 2329, in _old_concretize
    self._expand_virtual_packages(concretizer),
  File "/home/mlawso/bin/spack/lib/spack/spack/spec.py", line 2234, in _expand_virtual_packages
    candidates = concretizer.choose_virtual_or_external(spec)
  File "/home/mlawso/bin/spack/lib/spack/spack/concretize.py", line 146, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/home/mlawso/bin/spack/lib/spack/spack/concretize.py", line 101, in _valid_virtuals_and_externals
    candidates = spack.repo.path.providers_for(spec)
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 90, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 591, in providers_for
    providers = self.provider_index.providers_for(vpkg_spec)
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 575, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 985, in provider_index
    return self.index['providers']
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 407, in __getitem__
    self._build_all_indexes()
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 422, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/home/mlawso/bin/spack/lib/spack/spack/repo.py", line 447, in _build_index
    with misc_cache.write_transaction(cache_filename) as (old, new):
  File "/home/mlawso/bin/spack/lib/spack/llnl/util/lock.py", line 566, in __enter__
    if self._enter() and self._acquire_fn:
  File "/home/mlawso/bin/spack/lib/spack/llnl/util/lock.py", line 602, in _enter
    return self._lock.acquire_write(self._timeout)
  File "/home/mlawso/bin/spack/lib/spack/llnl/util/lock.py", line 330, in acquire_write
    wait_time, nattempts = self._lock(fcntl.LOCK_EX, timeout=timeout)
  File "/home/mlawso/bin/spack/lib/spack/spack/util/lock.py", line 31, in _lock
    return super(Lock, self)._lock(op, timeout)
  File "/home/mlawso/bin/spack/lib/spack/llnl/util/lock.py", line 199, in _lock
    .format(lock_type[op]))
llnl.util.lock.LockTimeoutError: Timed out waiting for a write lock.
```

**Comment by adamjstewart** [comment]
@tgamblin I'll let you handle the locking issue. I'll take a look at the build failure.

**Comment by adamjstewart** [comment]
Looks like an ICE. That's outside my area of expertise. I would contact the PCL developers: https://github.com/PointCloudLibrary/pcl/issues/new/choose

@michaelkuhn are there any known issues with using a Spack-installed GCC 10.2.0 on Power9?

**Comment by michaelkuhn** [comment]
> @michaelkuhn are there any known issues with using a Spack-installed GCC 10.2.0 on Power9?

Not that I know of but I also don't have access to a Power9 system.
