### ISSUE TITLE
Installation issue: 3dtk

### ISSUE THREAD

**Issue by mlawsonca** [LLNL/spack#20998]
### Steps to reproduce the issue

`$ spack -k install 3dtk cgal=true compact_octree=true ipo=true openmp=true ^/rdzugft`

```
==> Installing util-linux-uuid-2.36-6ay5c3ish3zt6qevkpdhupt2ijarct7e
==> No binary for util-linux-uuid-2.36-6ay5c3ish3zt6qevkpdhupt2ijarct7e found: installing from source
==> Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> Cannot find version 2.36 in url_list
==> Error: FetchError: All fetchers failed

/home/mlawso/bin/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332                                 self.spec.format('{name}{@version}'), ck_msg)
       1333
       1334        self.stage.create()
  >>   1335        err_msg = None if not self.manual_download else self.download_instr
       1336        self.stage.fetch(mirror_only, err_msg=err_msg)
       1337        self._fetch_time = time.time() - start_time
       1338

==> Installing sqlite-3.34.0-pey3dveui7bfkqsio4lesw7xloaaxchp
==> No binary for sqlite-3.34.0-pey3dveui7bfkqsio4lesw7xloaaxchp found: installing from source
==> Error: FetchError: All fetchers failed

/home/mlawso/bin/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332                                 self.spec.format('{name}{@version}'), ck_msg)
       1333
       1334        self.stage.create()
  >>   1335        err_msg = None if not self.manual_download else self.download_instr
       1336        self.stage.fetch(mirror_only, err_msg=err_msg)
       1337        self._fetch_time = time.time() - start_time
       1338

==> Installing metis-5.1.0-6acan2zzbqcc35x76pokfki44zgvvu7g
==> No binary for metis-5.1.0-6acan2zzbqcc35x76pokfki44zgvvu7g found: installing from source
==> Error: FetchError: All fetchers failed

/home/mlawso/bin/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332                                 self.spec.format('{name}{@version}'), ck_msg)
       1333
       1334        self.stage.create()
  >>   1335        err_msg = None if not self.manual_download else self.download_instr
       1336        self.stage.fetch(mirror_only, err_msg=err_msg)
       1337        self._fetch_time = time.time() - start_time
       1338

```

### Information on your system
* **Spack:** 0.16.0-577-b73cb64ba4
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original

packages.yaml:
```yaml
packages:
  tcl:
    version: [8.5]
    buildable: false
    externals:
    - spec: tcl@8.5
      prefix: /usr
  cuda:
    externals:
    - spec: cuda@10.1.243
      modules:
      - cuda/10.1.243
  openmpi:
    version: [4.1.0]
  cmake:
    version: [3.19.1]
  boost:
    version: [1.74.0]
  flann:
    version: [flann-1.9.1]
  all:
    compiler: [gcc@10.2.0]
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
The "-k being ignored" issue seems to be related to #19611 and #6708. Hopefully we can kill 3 birds with 1 stone here.

I have a feeling that there are two issues going on here. The first is that we give that unhelpful advice of using `-k` even though `-k` is already being given and clearly doesn't work. The second is that fetching is failing for some reason. I'm going to focus on fixing the second issue first.

This error is common with ancient versions of Python 2.6, but I've never seen it with Python 3.7 before. Perhaps Python was built without `+ssl`? Is Python 3.7 provided by the system, Spack-built, or built by the sys admins? Can you try running the following:
```console
$ python3 -c 'import ssl'
```

**Comment by adamjstewart** [comment]
Also, can you report the output of:
```console
$ spack -d fetch util-linux-uuid
```

**Comment by adamjstewart** [comment]
I believe @mlawsonca and @kuberry (#19611) are both at Sandia, so this could be specific to a machine there.

**Comment by adamjstewart** [comment]
Also also, what's the output of:
```
$ curl -O https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz
```
If it fails, you can add `--verbose` to get more info.

**Comment by mlawsonca** [comment]
`python3 -c 'import ssl'`
->No output
Confirmed my Spack installed version of python has +ssl, told the 3dtk install to use this Python and I still experienced the same build errors

`$ spack -d fetch util-linux-uuid`
```
==> [2021-01-15-19:38:27.120394] Imported fetch from built-in commands
==> [2021-01-15-19:38:27.122702] Imported fetch from built-in commands
==> [2021-01-15-19:38:27.125865] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/config.yaml
==> [2021-01-15-19:38:27.204288] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/repos.yaml
==> [2021-01-15-19:38:27.551823] util-linux-uuid applying constraint pkgconfig
==> [2021-01-15-19:38:27.554139] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/packages.yaml
==> [2021-01-15-19:38:27.676659] Reading config file /ascldap/users/mlawso/.spack/packages.yaml
==> [2021-01-15-19:38:28.013640] util-linux-uuid applying constraint pkgconf
==> [2021-01-15-19:38:28.022937] Reading config file /ascldap/users/mlawso/.spack/linux/compilers.yaml
==> [2021-01-15-19:38:28.358265] util-linux-uuid applying constraint pkgconf@1.7.3%gcc@10.2.0 arch=linux-rhel7-power9le
==> [2021-01-15-19:38:28.387000] DATABASE LOCK TIMEOUT: 3s
==> [2021-01-15-19:38:28.387177] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-01-15-19:38:28.931681] Creating stage lock spack-stage-util-linux-uuid-2.36-6ay5c3ish3zt6qevkpdhupt2ijarct7e
==> [2021-01-15-19:38:28.933148] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/mirrors.yaml
==> [2021-01-15-19:38:28.962058] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/82/82942cd877a989f6d12d4ce2c757fb67ec53d8c5cd9af0537141ec5f84a2eea3.tar.gz
==> [2021-01-15-19:38:28.974223] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/82/82942cd877a989f6d12d4ce2c757fb67ec53d8c5cd9af0537141ec5f84a2eea3.tar.gz'
==> [2021-01-15-19:38:29.282718] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/82/82942cd877a989f6d12d4ce2c757fb67ec53d8c5cd9af0537141ec5f84a2eea3.tar.gz
==> [2021-01-15-19:38:29.283151] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/util-linux-uuid/util-linux-uuid-2.36.tar.gz
==> [2021-01-15-19:38:29.284992] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/util-linux-uuid/util-linux-uuid-2.36.tar.gz'
==> [2021-01-15-19:38:29.570939] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/util-linux-uuid/util-linux-uuid-2.36.tar.gz
==> [2021-01-15-19:38:29.571348] Checking existence of https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz
==> [2021-01-15-19:38:29.573235] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz'
==> [2021-01-15-19:38:30.049640] FailedDownloadError: Failed to fetch file from URL: https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz
==> [2021-01-15-19:38:30.092818] SPIDER: [depth=0, max_depth=1, urls=4]
==> [2021-01-15-19:38:30.634804] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2021-01-15-19:38:30.634658] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2021-01-15-19:38:30.635342] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2021-01-15-19:38:30.635492] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2021-01-15-19:38:30.635075] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2021-01-15-19:38:30.635685] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2021-01-15-19:38:30.638634] SPIDER: [url=ParseResult(scheme='https', netloc='www.kernel.org', path='/pub/linux/utils/util-linux/', params='', query='', fragment=None)]
==> [2021-01-15-19:38:30.635251] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2021-01-15-19:38:30.641826] SPIDER: [url=ParseResult(scheme='https', netloc='www.kernel.org', path='/pub/linux/utils/util-linux', params='', query='', fragment=None)]
==> [2021-01-15-19:38:30.639232] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2021-01-15-19:38:30.645518] SPIDER: [url=ParseResult(scheme='https', netloc='www.kernel.org', path='/pub/linux/utils/util-linux/v2.29', params='', query='', fragment=None)]
==> [2021-01-15-19:38:30.649258] SPIDER: [url=ParseResult(scheme='https', netloc='www.kernel.org', path='/pub/linux/utils/util-linux/v2.29/', params='', query='', fragment=None)]
==> [2021-01-15-19:38:30.650261] SPIDER: [depth=1, max_depth=1, urls=0]
==> [2021-01-15-19:38:30.674769] KeyError: Version('2.36')
==> [2021-01-15-19:38:30.674982] Cannot find version 2.36 in url_list
==> [2021-01-15-19:38:30.675080] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/82/82942cd877a989f6d12d4ce2c757fb67ec53d8c5cd9af0537141ec5f84a2eea3.tar.gz failed.
==> [2021-01-15-19:38:30.675169] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/util-linux-uuid/util-linux-uuid-2.36.tar.gz failed.
==> [2021-01-15-19:38:30.675253] Fetching from https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz failed.
==> [2021-01-15-19:38:30.675374] FetchError: All fetchers failed
==> [2021-01-15-19:38:30.675459] Error: All fetchers failed
Traceback (most recent call last):
  File "/home/mlawso/bin/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/mlawso/bin/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/mlawso/bin/spack/lib/spack/spack/cmd/fetch.py", line 53, in fetch
    package.do_fetch()
  File "/home/mlawso/bin/spack/lib/spack/spack/package.py", line 1336, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/home/mlawso/bin/spack/lib/spack/spack/util/pattern.py", line 18, in __call__
    for item in self.container]
  File "/home/mlawso/bin/spack/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    for item in self.container]
  File "/home/mlawso/bin/spack/lib/spack/spack/stage.py", line 493, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
```


`$ curl -O --verbose https://www.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.gz`
  ```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to XXX
*   Trying 10.192.2.24...
* Connected to XXXXX
* Establish HTTP proxy tunnel to www.kernel.org:443
> CONNECT www.kernel.org:443 HTTP/1.1
> Host: www.kernel.org:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: XXXX
* Server certificate:
* 	subject: CN=kernel.org
* 	start date: Sep 15 00:00:00 2020 GMT
* 	expire date: Sep 27 23:59:59 2021 GMT
* 	common name: kernel.org
* 	issuer: XXXX
* NSS error -8172 (SEC_ERROR_UNTRUSTED_ISSUER)
* Peer's certificate issuer has been marked as not trusted by the user.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by adamjstewart** [comment]
Okay, given that even `curl` can't download this file, this seems to me like it isn't a Spack problem (although we could certainly have a more useful error message).

Can you try building `curl` with Spack and adding it to your `PATH`?

**Comment by mlawsonca** [comment]
`$ spack -d install curl`
```
...
==> [2021-01-15-19:56:57.592760] Acquiring a write lock on libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k with timeout 1e-09
==> [2021-01-15-19:56:57.607126] Creating stage lock spack-stage-libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k
==> [2021-01-15-19:56:57.612442] Installing libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k
==> [2021-01-15-19:56:57.612707] Searching for binary cache of libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k
==> [2021-01-15-19:56:57.613051] Reading config file /home/mlawso/bin/spack/etc/spack/defaults/mirrors.yaml
==> [2021-01-15-19:56:57.844969] Did not find linux-rhel7-power9le-gcc-10.2.0-libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k.spec.yaml on https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-rhel7-power9le-gcc-10.2.0-libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k.spec.yaml
  Download failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2021-01-15-19:56:57.848454] No binary for libidn2-2.3.0-m7zgbbubivcgqoqgtx6hg7wr66fac76k found: installing from source
==> [2021-01-15-19:56:58.306256] [TOOLCHAIN] MATCH Gcc
==> [2021-01-15-19:56:58.462674] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-01-15-19:56:58.873501] '/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/bin/g++' '-v' '/var/tmp/spack-implicit-link-infovplx6ivu/main.c' '-o' '/var/tmp/spack-implicit-link-infovplx6ivu/output'
==> [2021-01-15-19:56:59.031436] parsing implicit link info
==> [2021-01-15-19:56:59.033040] linker line:  /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/libexec/gcc/powerpc64le-unknown-linux-gnu/10.2.0/collect2 -plugin /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/libexec/gcc/powerpc64le-unknown-linux-gnu/10.2.0/liblto_plugin.so -plugin-opt=/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/libexec/gcc/powerpc64le-unknown-linux-gnu/10.2.0/lto-wrapper -plugin-opt=-fresolution=/var/tmp/ccWB7CHM.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -rpath /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib:/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib64 --eh-frame-hdr -V -m elf64lppc -dynamic-linker /lib64/ld64.so.2 -o /var/tmp/spack-implicit-link-infovplx6ivu/output /lib/../lib64/crt1.o /lib/../lib64/crti.o /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/crtbegin.o -L/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0 -L/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../.. /var/tmp/ccgwaMRA.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/crtend.o /lib/../lib64/crtn.o
==> [2021-01-15-19:56:59.033188] linkdir: /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0
==> [2021-01-15-19:56:59.033260] linkdir: /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../../../lib64
==> [2021-01-15-19:56:59.033328] linkdir: /lib/../lib64
==> [2021-01-15-19:56:59.033394] linkdir: /usr/lib/../lib64
==> [2021-01-15-19:56:59.033459] linkdir: /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../..
==> [2021-01-15-19:56:59.033554] found raw link dirs: /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0, /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0/../../..
==> [2021-01-15-19:56:59.033697] found link dirs: /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib/gcc/powerpc64le-unknown-linux-gnu/10.2.0, /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib64, /lib64, /usr/lib64, /home/mlawso/bin/spack/opt/spack/linux-rhel7-power8le/gcc-4.9.3/gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/lib
==> [2021-01-15-19:56:59.041235] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e1/e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5.tar.gz
==> [2021-01-15-19:56:59.042518] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e1/e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5.tar.gz'
==> [2021-01-15-19:56:59.325787] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e1/e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5.tar.gz
==> [2021-01-15-19:56:59.326281] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/libidn2/libidn2-2.3.0.tar.gz
==> [2021-01-15-19:56:59.328797] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/libidn2/libidn2-2.3.0.tar.gz'
==> [2021-01-15-19:56:59.607464] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/libidn2/libidn2-2.3.0.tar.gz
==> [2021-01-15-19:56:59.607933] Checking existence of https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz
==> [2021-01-15-19:56:59.609952] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz'
==> [2021-01-15-19:56:59.908381] FailedDownloadError: Failed to fetch file from URL: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz
==> [2021-01-15-19:56:59.908714] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e1/e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5.tar.gz failed.
==> [2021-01-15-19:56:59.908854] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/libidn2/libidn2-2.3.0.tar.gz failed.
==> [2021-01-15-19:56:59.908986] Fetching from https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz failed.
==> [2021-01-15-19:56:59.937650] Error: FetchError: All fetchers failed

/home/mlawso/bin/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332                                 self.spec.format('{name}{@version}'), ck_msg)
       1333
       1334        self.stage.create()
  >>   1335        err_msg = None if not self.manual_download else self.download_instr
       1336        self.stage.fetch(mirror_only, err_msg=err_msg)
       1337        self._fetch_time = time.time() - start_time
       1338


Traceback (most recent call last):
  File "/home/mlawso/bin/spack/lib/spack/spack/build_environment.py", line 856, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/mlawso/bin/spack/lib/spack/spack/installer.py", line 1641, in build_process
    pkg.do_patch()
  File "/home/mlawso/bin/spack/lib/spack/spack/package.py", line 1372, in do_patch
    self.do_stage()
  File "/home/mlawso/bin/spack/lib/spack/spack/package.py", line 1357, in do_stage
    self.do_fetch(mirror_only)
  File "/home/mlawso/bin/spack/lib/spack/spack/package.py", line 1336, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/home/mlawso/bin/spack/lib/spack/spack/util/pattern.py", line 18, in __call__
    for item in self.container]
  File "/home/mlawso/bin/spack/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    for item in self.container]
  File "/home/mlawso/bin/spack/lib/spack/spack/stage.py", line 493, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
```

**Comment by adamjstewart** [comment]
^ fixed by #21001

**Comment by mwkrentel** [comment]
@mlawsonca Could you test this again with the latest spack develop?
I think that PR #21864 probably solves at least half of your problem,
maybe all of it.

**Comment by mlawsonca** [comment]
Just tried rebuilding with:
`spack install 3dtk build_type=Release ipo=true opengl=false opencv=false ^/am3hz27 ^/fmbcdar ^/ejer7ul ^/r2ogl2a`

I have attached the command line output and the spack build outptu. 

[command-line-output-spack.txt](https://github.com/spack/spack/files/6052773/command-line-output-spack.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6052774/spack-build-out.txt)

I don't know if it's of any use, but when I built manually from the Git (which they say is still in testing), I had to make the following changes:

`/PathToSpack/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/libzip-1.2.0-ikozcyeowf2xgpikiqs2ebkejd3itst5/include/zip.h`
change
`#include <zipconf.h>` to 
`#include "../lib/libzip/include/zipconf.h"`

`/PathToSpack/spack/opt/spack/linux-rhel7-power9le/gcc-10.2.0/freeglut-3.2.1-4nqd5bzu7greysbblx23ava3mzzbwvge/include/GL/freeglut_std.h`
change
`#include <GL/glu.h>` to 
`#include<GL/glut.h>`

`/PathTo3DTK/src/show/callbacks_glut.cpp`
add `#include <GL/freeglut.h>`

`/PathTo3DTK/3DTK/3rdparty/CMakeLists.txt`
Put the apriltags references in 
`if (WITH_OPENCV AND WITH_EIGEN3`

**Comment by mwkrentel** [comment]
What I meant was that `spack -k` should now work which should fix your fetching
problems.  Anything after that is a separate problem.
