### ISSUE TITLE
Spack confused by Spack-installed Python3 environment

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2100]
I get the joyous stuff below when trying to run Spack after building (and loading modules for) a buch of Python3 stuff.   The workaround is pretty easy, just clear out your `$PYTHONPATH` before running Spack:

```
alias spack='PYTHONPATH= spack'
```

Still... maybe Spack should do this itself upon launch?

```
$ sh makenv-modele-ks 
Traceback (most recent call last):
  File "/home/rpfische/spack3/bin/spack", line 52, in <module>
    import nose
  File "/gpfsm/dnb53/rpfische/spack3/lib/spack/external/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/gpfsm/dnb53/rpfische/spack3/lib/spack/external/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/gpfsm/dnb53/rpfische/spack3/lib/spack/external/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/gpfsm/dnb53/rpfische/spack3/lib/spack/external/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/gpfsm/dnb53/rpfische/spack3/lib/spack/external/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2953, in <module>

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2939, in _call_aside

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2966, in _initialize_master_working_set

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 626, in _build_master

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 619, in __init__

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 675, in add_entry

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 1983, in find_on_path

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2371, in from_location

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2712, in _reload_version

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2336, in _version_from_file

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 2504, in _get_metadata

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 1874, in get_metadata_lines

  File "/gpfsm/dnb53/rpfische/spack3/opt/spack/linux-SuSE11-x86_64/gcc-5.3.0/py-setuptools-25.2.0-6we44zujmcs5bdv3jn7lzrr4gahg22sd/lib/python3.5/site-packages/setuptools-25.2.0-py3.5.egg/pkg_resources/__init__.py", line 1864, in get_metadata

  File "/usr/lib64/python2.6/io.py", line 1767, in read
    decoder.decode(self.buffer.read(), final=True))
  File "/usr/lib64/python2.6/io.py", line 1319, in decode
    output = self.decoder.decode(input, final=final)
  File "/usr/lib64/python2.6/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 174: invalid continuation byte in /usr/lib64/python2.6/site-packages/xmldiff-0.6.8-py2.6.egg-info
```

**Comment by mpbelhorn** [comment]
Per [PEP 394](https://www.python.org/dev/peps/pep-0394/) the binary for python3 should be called `python3` and not `python`. Python 2 scripts that don't expect `python` to be version 3 is a never ending world of misery for us Arch linux users and spack shouldn't be spreading the pain with it's own python3 installations.

It is also good practice to use explicit versions in script shabang lines like `#!/.../env python2` instead of just `#!/.../env python`. If there are systems out there that don't symlink python->python2->python2.X->python2.X.Y, then the admins of those systems should be shamed.

**Comment by citibeth** [comment]
>
> Per PEP 394 <https://www.python.org/dev/peps/pep-0394/> the binary for
> python3 should be called python3 and not python. Python 2 scripts that
> don't expect python to be version 3 is a never ending world of misery for
> us Arch linux users and spack shouldn't be spreading the pain with it's own
> python3 installations.
>

The binary is already called `python3`.  But the `$PYTHONPATH` for both of
those Pythons is called `PYTHONPATH`.  In this case, Python2 is being run
with a `$PYTHONPATH` only appropriate for Python3.


> It is also good practice to use explicit versions in script shabang lines
> like #!/.../env python2 instead of just #!/.../env python. If there are
> systems out there that don't symlink python->python2->python2.X->python2.X.Y,
> then the admins of those systems should be shamed.
>
Not all systems include a `python2` executable, unfortunately.  Macs, for
example, just have `python`.

**Comment by adamjstewart** [comment]
Spack now supports Python 3 so I think we can close this issue.
