### ISSUE TITLE
a bug in GMP package

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2113]
Our system administrator hit a bug today:

```
==> Staging archive: /calculate/spack/var/spack/stage/gmp-6.1.1-uq52e2ngj75qjzhuvlfk7ssvbeicaduj/gmp-6.1.1.tar.bz2
==> Created stage in /calculate/spack/var/spack/stage/gmp-6.1.1-uq52e2ngj75qjzhuvlfk7ssvbeicaduj
==> No patches needed for gmp
==> Building gmp [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
Traceback (most recent call last):
 File "./spack", line 202, in <module>
   main()
 File "./spack", line 179, in main
   return_val = command(parser, args)
 File "/calculate/spack/lib/spack/spack/cmd/install.py", line 117, in install
   package.do_install(**kwargs)
 File "/calculate/spack/lib/spack/spack/package.py", line 1183, in do_install
   dirty=dirty)
 File "/calculate/spack/lib/spack/spack/package.py", line 1183, in do_install
   dirty=dirty)
 File "/calculate/spack/lib/spack/spack/package.py", line 1183, in do_install
   dirty=dirty)
 File "/calculate/spack/lib/spack/spack/package.py", line 1183, in do_install
   dirty=dirty)
 File "/calculate/spack/lib/spack/spack/package.py", line 1268, in do_install
   spack.build_environment.fork(self, build_process, dirty=dirty)
 File "/calculate/spack/lib/spack/spack/build_environment.py", line 542, in fork
   raise exception
NameError: global name 'spec' is not defined

--------------------------------
gmp: package.py has the content:
--------------------------------
from spack import *


class Gmp(AutotoolsPackage):
   """GMP is a free library for arbitrary precision arithmetic,
      operating on signed integers, rational numbers, and
      floating-point numbers."""
   homepage = "https://gmplib.org"
   url = "https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2"

   version('6.1.1',  '4c175f86e11eb32d8bf9872ca3a8e11d')
   version('6.1.0',  '86ee6e54ebfc4a90b643a65e402c4048')
   version('6.0.0a', 'b7ff2d88cae7f8085bd5006096eed470')
   version('6.0.0',  '6ef5869ae735db9995619135bd856b84')

   depends_on('m4', type='build')

   def configure_args(self):
       args = ['--enable-cxx']
       # We need this flag if we want all the following checks to pass.
       if spec.compiler.name == 'intel':
           args.append('CXXFLAGS=-no-ftz')

       return args
~
```

From a quick glance it looks like a bug.

**Comment by davydden** [comment]
the bug was not there last Friday, could be related to https://github.com/LLNL/spack/pull/1186

@alalazo do you have any ideas?

**Comment by alalazo** [comment]
It's not a bug, it's a feature! :smile: 

There was a discussion as to pass or not arguments that were redundant, and I preferred not to. Just add: 
```
spec = self.spec 
```
at the beginning of the function and that should work.

**Comment by davydden** [comment]
oh, so it's a bug in the package as it should be 
```
if self.spec.compiler.name = ...
```
right?

**Comment by davydden** [comment]
PR incoming...

**Comment by davydden** [comment]
> There was a discussion as to pass or not arguments that were redundant

I agree with that and I like that only `spec` is passed.

**Comment by adamjstewart** [comment]
I disagree with the sentiment here. `spec` and `prefix` are very commonly used arguments, almost exclusively when determining `configure_args()`. If we want to remove them from all functions and only use `self`, I'm fine with that, but don't make `configure_args()` the only function that doesn't have `spec` and `prefix`. Otherwise I have to remember which functions have which arguments.

**Comment by alalazo** [comment]
@adamjstewart Let's say it like that : if you subclass from one of the classes in `build_systems` 99% of the time you will only override methods which have only `self`. I don't think that you'll very often need to change the workflow for `CMakePackage` of `AutotoolsPackage`, it will be much more common to just pass arguments or compute the build directory.
