### ISSUE TITLE
Metis is broken

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2118]
```
$ spack install metis@5.0.2
==> Installing metis
==> cmake is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/cmake-3.6.1-knsjcg5wlbnsy27ja5ngp5xdftflnv4a
==> Trying to fetch from file:///Users/davydden/spack/var/spack/cache/metis/metis-5.0.2.tar.gz
curl: (37) Couldn't open file /Users/davydden/spack/var/spack/cache/metis/metis-5.0.2.tar.gz
==> Fetching from file:///Users/davydden/spack/var/spack/cache/metis/metis-5.0.2.tar.gz failed.
==> Trying to fetch from http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.0.2.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/davydden/spack/var/spack/stage/metis-5.0.2-36gz5ygfj3o7ptkltsuh3t2cezy56g3y/metis-5.0.2.tar.gz
==> Created stage in /Users/davydden/spack/var/spack/stage/metis-5.0.2-36gz5ygfj3o7ptkltsuh3t2cezy56g3y
==> Applied patch install_gklib_defs_rename.patch
==> Ran patch() for metis
==> Building metis [Package]
==> Executing phase : 'install'
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 202, in <module>
    main()
  File "/Users/davydden/spack/bin/spack", line 179, in main
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/install.py", line 117, in install
    package.do_install(**kwargs)
  File "/Users/davydden/spack/lib/spack/spack/package.py", line 1268, in do_install
    spack.build_environment.fork(self, build_process, dirty=dirty)
  File "/Users/davydden/spack/lib/spack/spack/build_environment.py", line 542, in fork
    raise exception
AttributeError: 'functools.partial' object has no attribute '__module__'
```

@alalazo any guesses here? Maybe related to https://github.com/LLNL/spack/pull/1186. But I don't see any clues in `package.py` of `metis`.

**Comment by alalazo** [comment]
I'll have a look.

**Comment by tgamblin** [comment]
It's trying to raise the exception from the child process but it looks like whatever was sent back from the child is missing an attribute somewhere...

**Comment by alalazo** [comment]
I think it comes from `install` decorated with `@when`, I am looking at it right now.

**Comment by tgamblin** [comment]
Maybe `@when` needs to add some more metadata... that is pretty old and I'm not sure I did all the required things you're supposed to do when wrapping functions in Python.  The function object created by `@when` is in `multimethod.py`

**Comment by alalazo** [comment]
Thanks @tgamblin

**Comment by alalazo** [comment]
For the record, it was failing in `package.py:98`:
```python
@functools.wraps(phase) # <===
def phase_wrapper(spec, prefix):
    # Check instance attributes at the beginning of a phase
    self._on_phase_start(instance)
...
```
`phase` was a `functool.partial` instance and that apparently doesn't work very well when using the `functools.wraps` decorator as it misses the attribute `__module__`
