### ISSUE TITLE
Lock error in `develop` build

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#2129]
I suspect this is due to Travis running slowly -- currently lock tests rely on a 1m timeout.  Recording it here for posterity in case it was not transient slowness in the cloud.

FWIW, tests for the merged commit succeeded in the PR, and this only occurred for one of the tests cases after the merge to develop.

[Link to build # 4750](https://travis-ci.org/LLNL/spack/builds/170539111)

```
==> Successfully installed cmake-client
............Process Process-215:
Process Process-214:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/LLNL/spack/lib/spack/spack/test/lock.py", line 330, in p1
    self.run()
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 88, in run
    barrier.wait()  # ---------------------------------------- 10
  File "/home/travis/build/LLNL/spack/lib/spack/spack/util/multiproc.py", line 79, in wait
    self._target(*self._args, **self._kwargs)
    raise BarrierTimeoutError()
BarrierTimeoutError: <spack.util.multiproc.BarrierTimeoutError instance at 0x60c3320>
  File "/home/travis/build/LLNL/spack/lib/spack/spack/test/lock.py", line 366, in p2
    barrier.wait()  # ---------------------------------------- 10
  File "/home/travis/build/LLNL/spack/lib/spack/spack/util/multiproc.py", line 79, in wait
    raise BarrierTimeoutError()
BarrierTimeoutError: <spack.util.multiproc.BarrierTimeoutError instance at 0x60c34d0>
FException AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
.....Process Process-216:
Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/LLNL/spack/lib/spack/spack/test/lock.py", line 402, in p3
    barrier.wait()  # ---------------------------------------- 10
  File "/home/travis/build/LLNL/spack/lib/spack/spack/util/multiproc.py", line 92, in wait
    raise BarrierTimeoutError()
BarrierTimeoutError: <spack.util.multiproc.BarrierTimeoutError instance at 0x60c35a8>
...

======================================================================
FAIL: test_complex_acquire_and_release_chain (spack.test.lock.LockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/LLNL/spack/lib/spack/spack/test/lock.py", line 412, in test_complex_acquire_and_release_chain
    self.multiproc_test(p1, p2, p3)
  File "/home/travis/build/LLNL/spack/lib/spack/spack/test/lock.py", line 62, in multiproc_test
    self.assertEqual(p.exitcode, 0)
AssertionError: 1 != 0
----------------------------------------------------------------------
Ran 418 tests in 607.606s
FAILED (failures=1)
==> Tests Complete.
    418 tests run
      1 failures
      0 errors
==> List of failing tests:
  test_complex_acquire_and_release_chain (spack.test.lock.LockTest)
==> FAIL
```

**Comment by tgamblin** [comment]
Fixed in next merge to develop.  Reopen if it reoccurs.

**Comment by alalazo** [comment]
Happened again in #2169. Spurious failure on tests.

**Comment by tgamblin** [comment]
Could this be related to how fcntl locks are handled among processes since the new do_install?  I'm worried that the context handlers on the child/parent are getting out of sync. Ideally child processes' locks would be completely nested and a child wouldn't exit nested locks past a fork boundary, but I haven't looked to make sure that is happening.
