### ISSUE TITLE
Installation issue: mxnet python runtime error

### ISSUE THREAD

**Issue by jonglezb** [LLNL/spack#21327]
### Description

Mxnet now builds fine, but there is a runtime error. It happens on both x86_64 and ppc64le.

### Steps to reproduce the issue

Make sure that nvidia drivers are installed (outside of spack), this is needed at runtime.

```console
$ spack install -j64 mxnet +cuda cuda_arch=60 -opencv ^cuda@10.1.243 ^cudnn@7.6.5.32-10.1 ^openblas@0.3.12 ^python@3.7.0:3.7.999
(should work)
$ spack load mxnet
$ python3 -c "import mxnet; print('Num GPUs Available:', mxnet.context.num_gpus())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/mxnet-1.6.0-qjv4wocfd4jns7e5mbjtem3tga3spsgb/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/mxnet-1.6.0-qjv4wocfd4jns7e5mbjtem3tga3spsgb/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/mxnet-1.6.0-qjv4wocfd4jns7e5mbjtem3tga3spsgb/lib/python3.7/site-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/mxnet-1.6.0-qjv4wocfd4jns7e5mbjtem3tga3spsgb/lib/python3.7/site-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/python-3.7.9-c3a4tza6pxa35dfx5tinqxurisfyuxxa/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/mxnet-1.6.0-qjv4wocfd4jns7e5mbjtem3tga3spsgb/lib/libmxnet.so: undefined symbol: _ZN5mxnet2op16ElemwiseBinaryOp11DnsCsrCsrOpIN7mshadow3gpuENS0_10mshadow_op3mulEEEvRKN4nnvm9NodeAttrsERKNS_9OpContextERKNS_7NDArrayESG_NS_9OpReqTypeESG_b
$ which python3
/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/python-3.7.9-c3a4tza6pxa35dfx5tinqxurisfyuxxa/bin/python3
```

### Information on your system

* **Spack:** 0.16.0-1006-cbdf87cd28
* **Python:** 3.7.9
* **Platform:** linux-debian10-skylake_avx512
* **Concretizer:** original

### Additional information

@adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jonglezb** [comment]
The missing symbol seems related to mshadow.

Looking at mxnet's Makefile, I'm pretty sure it does not use the mshadow package from Spack but uses a built-in version.

I tried to add the following patch to the Spack package to force using the mshadow package from Spack:
```patch
diff --git a/Makefile b/Makefile
index 4746cc434..66b281273 100644
--- a/Makefile
+++ b/Makefile
@@ -40,6 +40,10 @@ ifndef DMLC_CORE
 endif
 CORE_INC = $(wildcard $(DMLC_CORE)/include/*/*.h)
 
+ifndef MSHADOW_PATH
+	MSHADOW_PATH = $(TPARTYDIR)/mshadow
+endif
+
 ifndef NNVM_PATH
 	NNVM_PATH = $(TPARTYDIR)/tvm/nnvm
 endif
@@ -86,7 +90,7 @@ ifeq ($(USE_MKLDNN), 1)
 	MKLDNNROOT = $(ROOTDIR)/3rdparty/mkldnn/build/install
 endif
 
-include $(TPARTYDIR)/mshadow/make/mshadow.mk
+include $(MSHADOW_PATH)/make/mshadow.mk
 include $(DMLC_CORE)/make/dmlc.mk
 
 # all tge possible warning tread
@@ -106,7 +110,7 @@ ifeq ($(DEBUG), 1)
 else
 	CFLAGS += -O3 -DNDEBUG=1
 endif
-CFLAGS += -I$(TPARTYDIR)/mshadow/ -I$(TPARTYDIR)/dmlc-core/include -fPIC -I$(NNVM_PATH)/include -I$(DLPACK_PATH)/include -I$(TPARTYDIR)/tvm/include -Iinclude $(MSHADOW_CFLAGS)
+CFLAGS += -I$(MSHADOW_PATH)/include/ -I$(TPARTYDIR)/dmlc-core/include -fPIC -I$(NNVM_PATH)/include -I$(DLPACK_PATH)/include -I$(TPARTYDIR)/tvm/include -Iinclude $(MSHADOW_CFLAGS)
 LDFLAGS = -pthread -ldl $(MSHADOW_LDFLAGS) $(DMLC_LDFLAGS)
 
 # please note that when you enable this, you might run into an linker not being able to work properly due to large code injection.
```

However, with this patch, I get tons of build errors, starting with:

```
/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/gcc-8.3.0-cva45sgdtwukvazpxc6eurpry7xpi4zl/bin/g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -DDMLC_MODERN_THREAD_LOCAL=0 -O3 -DNDEBUG=1 -I/grid5000/spack/opt/spack
/linux-debian10-x86_64/gcc-8.3.0/mshadow-20170721-yw347xwvfs7elruh6ddcxqrbwqrjm4km/include/ -I/var/spack/stage/root/spack-stage-mxnet-1.6.0-2yfqiqqgu2u7cgi6g2odpv4h6yhtzqfy/spack-src/3rdparty/dmlc-core/include -fPIC -I/var/spack/stage/roo
t/spack-stage-mxnet-1.6.0-2yfqiqqgu2u7cgi6g2odpv4h6yhtzqfy/spack-src/3rdparty/tvm/nnvm/include -I/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/openblas-0.3.12-sfmojuqa7vcjzmpbnns5fsubs7bnjhe6/include -I/var/spack/stage/root/sp
ack-stage-mxnet-1.6.0-2yfqiqqgu2u7cgi6g2odpv4h6yhtzqfy/spack-src/3rdparty/dlpack/include -I/var/spack/stage/root/spack-stage-mxnet-1.6.0-2yfqiqqgu2u7cgi6g2odpv4h6yhtzqfy/spack-src/3rdparty/tvm/include -Iinclude -funroll-loops -Wno-unused-
variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/cuda-10.1.243-kbifgwwbaoqq2pkzb6vqo2evsgrk7ryh/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_M
KL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=0 -DMXNET_USE_OPERATOR_TUNING=1 -DMSHADOW_INT64_TENSOR_SIZE=0 -DMSHADOW_USE_CUDNN=1 -DMXNET_USE_BLAS_OPEN=1  -I/grid5000/spack/opt/spack/linux-debian1
0-x86_64/gcc-8.3.0/cub-1.9.10-alaygvx2bzqlz36pfhha4bhnj2t6fh7e/include -I/grid5000/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/cudnn-7.6.5.32-10.1-tsdeuuhpqyk5nimsmvqf2ro46oytihf6/include -DMXNET_ENABLE_CUDA_RTC=1 -DMXNET_USE_NCCL=0 -
DMXNET_USE_LIBJPEG_TURBO=0 -MMD -c src/operator/random/pdf_op.cc -o build/src/operator/random/pdf_op.o
In file included from src/operator/numpy/random/./../../tensor/./elemwise_unary_op.h:33,
                 from src/operator/numpy/random/./../../tensor/./elemwise_binary_op.h:38,
                 from src/operator/numpy/random/./../../tensor/elemwise_binary_broadcast_op.h:36,
                 from src/operator/numpy/random/./np_normal_op.h:36,
                 from src/operator/numpy/random/np_normal_op.cc:25:
src/operator/numpy/random/./../../tensor/././cast_storage-inl.h:33:10: fatal error: ../../src/operator/tensor/init_op.h: No such file or directory                                                                                           
 #include "../../src/operator/tensor/init_op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jonglezb** [comment]
So, I'm starting to be out of my depth here.

@adamjstewart unless you have an idea, I guess I'll give up for now and try again when you have time to convert the package to CMake.

**Comment by adamjstewart** [comment]
No great ideas off the top of my head. You could open an issue with the OpenCV devs, but they'll probably just tell you to use CMake instead. I might try to port things to CMake in the near future. I don't like dropping the old version without warning but I don't really know anyone else who uses this package and it seems broken as is.

**Comment by adamjstewart** [comment]
Trying to port to CMake today, it looks like 1.3.0 actually has CMake support so I won't need to complicate the package much.
