### ISSUE TITLE
Installation issue: autoconf@2.69 can't download mirror due to patch file

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#21379]
### Steps to reproduce the issue

```console
$ spack -d mirror create -d ./tmp-mirror autoconf@2.69
...
==> [2021-01-28-09:50:14.519230] Fetching from https://git.savannah.gnu.org/cgit/autoconf.git/patch/?id=05972f49ee632cd98057a3caf82ebfb9574846da failed.
Traceback (most recent call last):
  File "/yellow/users/stam/projects/spack/lib/spack/spack/mirror.py", line 510, in _add_single_spec
    patch.stage.cache_mirror(mirror, mirror_stats)
  File "/yellow/users/stam/projects/spack/lib/spack/spack/stage.py", line 578, in cache_mirror
    self.fetch()
  File "/yellow/users/stam/projects/spack/lib/spack/spack/stage.py", line 493, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
==> [2021-01-28-09:50:14.522229] Successfully updated mirror in file:///yellow/users/stam/projects/spack/tmp-mirror
  Archive stats:
    1    already present
    0    added
    1    failed to fetch.
==> [2021-01-28-09:50:14.522392] Error: Failed downloads:
autoconf@2.69
```

If I comment this out, it works:
https://github.com/spack/spack/blob/bf33fe48050bb3d5b0b4f25f034d013320e0db24/var/spack/repos/builtin/packages/autoconf/package.py#L23-L25

@skosukhin I am running on a machine with firewalls, and I think they may be blocking this link. I don't run into this error on a local machine.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.0-1046-bf33fe4805
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers 
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by skosukhin** [comment]
Unfortunately, I don't know how I could help here. The patch is also available via a slightly different link. You can try it:
```python
patch('https://git.savannah.gnu.org/cgit/autoconf.git/rawdiff/?id=05972f49ee632cd98057a3caf82ebfb9574846da',
      sha256='2fd647bb59b17fb85c4a518b17fd298d7cfae93483cb9803947c4adbac882e67',
      when='@2.70')
```
We could add the patch directly to the Spack repo but there are many packages that download patches from various sources. So, it doesn't look like a good solution.

It is also interesting why Spack tries to download the patch although it is not for the version requested on the command line.

I just realized, maybe you should simply wait for the Amazon mirror to update. I don't know how long it usually takes though.

P.S. I wonder why this has the `build-error` tag. Maybe it means more than says.

**Comment by EthanS94** [comment]
Thanks for looking into this! It was weird to me too that it tries to download the patch. I would think specifying `autoconf@2.69` would avoid it, but I guess not.

> P.S. I wonder why this has the build-error tag. Maybe it means more than says.

That was me. I labelled as build-error, because the build failed when trying to download that patch. Maybe that's not the right label to use?

**Comment by sethrj** [comment]
@EthanS94 The installation process hadn't yet reached the "build" phase -- the `build-error` tag refers to an issue during the `build` (or `configure`) phase, during the call to make/configure/cmake.

**Comment by EthanS94** [comment]
@sethrj  I see. Thanks for clarifying!

**Comment by michaelkuhn** [comment]
> Thanks for looking into this! It was weird to me too that it tries to download the patch. I would think specifying `autoconf@2.69` would avoid it, but I guess not.

That seems to be normal, mirroring always fetches all patches for some reason. I also ran into problems in the past due to this.
