### ISSUE TITLE
Installation issue: Error: NoLibrariesError: Unable to recursively locate hpcx libraries

### ISSUE THREAD

**Issue by arstgr** [LLNL/spack#21462]
### Steps to reproduce the issue

```console
$ spack install --dirty cp2k@7.1 +mpi+libxc+openmp smm=libsmm %gcc@9.2.0 cppflags="-O3 -fopenmp" cflags="-O3 -fopenmp" fflags="-O3 -fopenmp" ^mpi@3: ^hpcx@2.7.0 ^scalapack ^openblas threads=openmp ^fftw +openmp
```

```console
module list:
1) /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/modulefiles/hpcx   
2) mpi/hpcx-v2.7.0
3) gcc-9.2.0
```

```console
ls /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi
bin  etc  include  lib  share  tests
```

### The error:
==> Installing cp2k
==> No binary for cp2k found: installing from source
==> cp2k: Executing phase: 'edit'
==> Error: NoLibrariesError: Unable to recursively locate hpcx libraries in /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi

/share/apps/spack/0.15.4/spack/var/spack/repos/builtin/packages/cp2k/package.py:356, in edit:
        353            ldflags.append(scalapack.search_flags)
        354
        355            libs.extend(scalapack)
==>    356            libs.extend(spec['mpi:cxx'].libs)
        357            libs.extend(self.compiler.stdcxx_libs)
        358
        359            if 'wannier90' in spec:

See build log for details:
  /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/spack-build-out.txt

### The error report when installing with --debug option:
==> [2021-02-03-06:35:28.736670] No patches needed for cp2k
==> [2021-02-03-06:35:28.736766] cp2k: Building cp2k [MakefilePackage]
==> [2021-02-03-06:35:28.742824] cp2k: Executing phase: 'edit'
==> [2021-02-03-06:35:28.854134] Error: NoLibrariesError: Unable to recursively locate hpcx libraries in /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi

/share/apps/spack/0.15.4/spack/var/spack/repos/builtin/packages/cp2k/package.py:356, in edit:
        353            ldflags.append(scalapack.search_flags)
        354
        355            libs.extend(scalapack)
==>    356            libs.extend(spec['mpi:cxx'].libs)
        357            libs.extend(self.compiler.stdcxx_libs)
        358
        359            if 'wannier90' in spec:

See build log for details:
  /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/spack-build-out.txt

### installing with --debug option
==> [2021-02-03-06:35:19.277923] Fetching from https://[ihadtoremoveit]/linux-centos7-x86_64-gcc-9.2.0-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3.spec.yaml failed.
==> [2021-02-03-06:35:19.282132] No binary for cp2k found: installing from source
==> [2021-02-03-06:35:19.433639] [TOOLCHAIN] MATCH Gcc
==> [2021-02-03-06:35:19.443560] No libraries found for libint
==> [2021-02-03-06:35:19.468881] No libraries found for hpcx
==> [2021-02-03-06:35:19.531921] No headers found for netlib-scalapack
==> [2021-02-03-06:35:20.108131] [DEPRECATED METHOD]
"hpcx" still defines the deprecated method "setup_dependent_environment" [should be split into "setup_dependent_build_environment" and "setup_dependent_run_environment"]
==> [2021-02-03-06:35:20.185029] '/apps/spack/hbv2/linux-centos7-x86_64/gcc-9.2.0/python-3.7.7-ztnaxbsqvgz65imyxdyrqzbek47xln4j/bin/python3.7' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('"'"'prefix'"'"'))'
==> [2021-02-03-06:35:20.349113] '/opt/gcc-9.2.0/bin/g++' '-v' '/tmp/spack-implicit-link-infopk2wqtiv/main.c' '-o' '/tmp/spack-implicit-link-infopk2wqtiv/output'
==> [2021-02-03-06:35:20.407268] parsing implicit link info
==> [2021-02-03-06:35:20.407602] linker line:  /opt/gcc-9.2.0/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/collect2 -plugin /opt/gcc-9.2.0/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/liblto_plugin.so -plugin-opt=/opt/gcc-9.2.0/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccA1FnlG.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-infopk2wqtiv/output /lib/../lib64/crt1.o /lib/../lib64/crti.o /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/crtbegin.o -L/opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0 -L/opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi/lib -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/nccl_rdma_sharp_plugin/lib -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/sharp/lib -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hcoll/lib -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hmc/lib -L/opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ucx/lib -L/opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../.. /tmp/ccXNzHqD.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/crtend.o /lib/../lib64/crtn.o
==> [2021-02-03-06:35:20.407679] linkdir: /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0
==> [2021-02-03-06:35:20.407741] linkdir: /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64
==> [2021-02-03-06:35:20.407769] linkdir: /lib/../lib64
==> [2021-02-03-06:35:20.407793] linkdir: /usr/lib/../lib64
==> [2021-02-03-06:35:20.407816] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi/lib
==> [2021-02-03-06:35:20.407840] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/nccl_rdma_sharp_plugin/lib
==> [2021-02-03-06:35:20.407863] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/sharp/lib
==> [2021-02-03-06:35:20.407885] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hcoll/lib
==> [2021-02-03-06:35:20.407907] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hmc/lib
==> [2021-02-03-06:35:20.407930] linkdir: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ucx/lib
==> [2021-02-03-06:35:20.407952] linkdir: /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../..
==> [2021-02-03-06:35:20.407989] found raw link dirs: /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0, /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/nccl_rdma_sharp_plugin/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/sharp/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hcoll/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hmc/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ucx/lib, /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../..
==> [2021-02-03-06:35:20.408088] found link dirs: /opt/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0, /opt/gcc-9.2.0/lib64, /lib64, /usr/lib64, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/nccl_rdma_sharp_plugin/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/sharp/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hcoll/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/hmc/lib, /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ucx/lib, /opt/gcc-9.2.0/lib
==> [2021-02-03-06:35:20.467145] Using cached archive: /apps/spack/cache/_source-cache/archive/cc/ccd711a09a426145440e666310dd01cc5772ab103493c4ae6a3470898cd0addb.tar.bz2
==> [2021-02-03-06:35:20.519181] Staging archive: /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/cp2k-7.1.tar.bz2
==> [2021-02-03-06:35:20.520239] '/usr/bin/tar' '-xf' '/mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/cp2k-7.1.tar.bz2'
==> [2021-02-03-06:35:28.735985] Created stage in /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3
==> [2021-02-03-06:35:28.736670] No patches needed for cp2k
==> [2021-02-03-06:35:28.736766] cp2k: Building cp2k [MakefilePackage]
==> [2021-02-03-06:35:28.742824] cp2k: Executing phase: 'edit'
==> [2021-02-03-06:35:28.854134] Error: NoLibrariesError: Unable to recursively locate hpcx libraries in /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi

/share/apps/spack/0.15.4/spack/var/spack/repos/builtin/packages/cp2k/package.py:356, in edit:
        353            ldflags.append(scalapack.search_flags)
        354
        355            libs.extend(scalapack)
==>    356            libs.extend(spec['mpi:cxx'].libs)
        357            libs.extend(self.compiler.stdcxx_libs)
        358
        359            if 'wannier90' in spec:

See build log for details:
  /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/spack-build-out.txt
Traceback (most recent call last):
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/build_environment.py", line 846, in child_process
    return_value = function()
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/installer.py", line 1150, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/share/apps/spack/0.15.4/spack/var/spack/repos/builtin/packages/cp2k/package.py", line 357, in edit
    libs.extend(self.compiler.stdcxx_libs)
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/spec.py", line 877, in __get__
    value = f()
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/spec.py", line 869, in <lambda>
    callbacks_chain.append(lambda: self.default(self, instance, cls))
  File "/share/apps/spack/0.15.4/spack/lib/spack/spack/spec.py", line 808, in _libs_default_handler
    raise spack.error.NoLibrariesError(msg.format(spec.name, spec.prefix))
spack.error.NoLibrariesError: Unable to recursively locate hpcx libraries in /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi
==> [2021-02-03-06:35:28.854476] Flagging cp2k as failed: NoLibrariesError: Unable to recursively locate hpcx libraries in /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi
/share/apps/spack/0.15.4/spack/var/spack/repos/builtin/packages/cp2k/package.py:356, in edit:
        353            ldflags.append(scalapack.search_flags)
        354
        355            libs.extend(scalapack)
==>    356            libs.extend(spec['mpi:cxx'].libs)
        357            libs.extend(self.compiler.stdcxx_libs)
        358
        359            if 'wannier90' in spec:

See build log for details:
  /mnt/resource/scratch/spack-stage/hpcuser/spack-stage-cp2k-7.1-k5y5v3kkvnjxgbwleh3q6t33dmz5usx3/spack-build-out.txt

### Information on your system

* **Spack:** 0.15.4
* **Python:** 3.6.8
* **Platform:** linux-centos7-x86_64

Trying to install cp2k on a system using hpcx mpi library. The file packages.yaml looks like this (indentation was not maintained here):
packages:
  hpcx:
    paths:
       hpcx@2.7.0: /opt/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-5.1-0.6.6.0-redhat7.6-x86_64/ompi
    buildable: False
  gcc:
    modules:
       gcc@9.2.0: gcc-9.2.0
    buildable: False
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [openmpi, mpich, mvapich2, hpcx]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user

### Additional information

* [spack-build-out.txt](
==> [2021-02-03-06:35:28.742824] cp2k: Executing phase: 'edit'
==> [2021-02-03-06:35:28.783778] '/apps/spack/hbv2/linux-centos7-x86_64/gcc-9.2.0/pkgconf-1.7.3-vpumgc4ptlmuyk4qb6vj7fjrwme4sqtw/bin/pkg-config' '--cflags' 'libint2'
==> [2021-02-03-06:35:28.790460] '/apps/spack/hbv2/linux-centos7-x86_64/gcc-9.2.0/pkgconf-1.7.3-vpumgc4ptlmuyk4qb6vj7fjrwme4sqtw/bin/pkg-config' '--libs' 'libint2')

 @dev-zero could you please take a look? many thanks in advance. 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by arstgr** [comment]
I commented out the line 
==> 356 libs.extend(spec['mpi:cxx'].libs)
and the installation went on without further problems. Results from case studies with the benchmarking test suits seem reasonable so far (additional tests are being done). 
The problem seems to be from hpcx mpi library, according to the compile time warnings ""hpcx" still defines the deprecated method "setup_dependent_environment" [should be split into "setup_dependent_build_environment" and "setup_dependent_run_environment"]. Hopefully this will be resolved in the future releases of hpcx.

**Comment by ltalirz** [comment]
Had the same issue and ended up with the same workaround.

Sorry to highjack this thread but I see you are specifying `smm=libsmm`. When I do so, I'm getting
```
        635                raise KeyError(
  >>    636                    "Point environment variable LIBSMM_PATH to "        637                    "the absolute path of the libsmm.a file"
        638                )    
```
I notice cp2k does not explicitly depend on libsmm, and there is no spack package for libsmm.
Do you happen to know where libsmm comes from on your case?
