### ISSUE TITLE
`spack add` fails when Python is in environment view

### ISSUE THREAD

**Issue by timmoon10** [LLNL/spack#21475]
I'd like to get Spack to build Python and install it to an environment. However, I run into errors when I try adding any other packages to the environment.

As far as I can tell, the problem is that the main Spack driver uses the Python that has been installed to the environment. However, adding a package to the environment involves moving the environment view to a temporary directory. Thus, the Python executable is trying to move/delete itself. This is exacerbated when I run on Lassen since the environment view and temporary directory are on different file systems (NFS vs. local memory).

I can work around this issue, and PR https://github.com/spack/spack/pull/21222 will make it nicer. However, it will not be obvious for other users when they run into this problem.

### Steps to reproduce the issue

```console
spack env rm --yes-to-all myenv
spack env create myenv
spack env activate myenv
spack add python@3.9.1
spack install
spack --debug add py-numpy
```

I can hack around this by changing the last line to:
```console
/path/to/external/python $(which spack) add py-numpy
```

I've been running on a Lassen compute node.

### Error Message

<details> 

```console
==> Successfully removed environment 'myenv'
==> Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
==> Created environment 'myenv' in /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv
==> You can activate this environment with:
==>   spack env activate myenv
==> Adding python@3.9.1 to environment myenv
==> Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
==> Concretized python@3.9.1
[+]  gh6tpuo  python@3.9.1%gcc@7.3.1+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4\
+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel7-power9le
[+]  kredonm      ^bzip2@1.0.8%gcc@7.3.1+shared arch=linux-rhel7-power9le
[+]  n3rvht5          ^diffutils@3.7%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  4b7rg3o              ^libiconv@1.16%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  dxieubm      ^expat@2.2.10%gcc@7.3.1+libbsd arch=linux-rhel7-power9le
[+]  6huorkj          ^libbsd@0.10.0%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  inn3u4z      ^gdbm@1.18.1%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  h4hkrjm          ^readline@8.0%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  dzfasfw              ^ncurses@6.2%gcc@7.3.1~symlinks+termlib arch=linux-rhel7-power9le
[+]  dpi7vke                  ^pkgconf@1.7.3%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  yh4ybey      ^gettext@0.21%gcc@7.3.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-power9le
[+]  kxsi6md          ^libxml2@2.9.10%gcc@7.3.1~python arch=linux-rhel7-power9le
[+]  bspsrxj              ^xz@5.2.5%gcc@7.3.1~pic arch=linux-rhel7-power9le
[+]  wup2hw6              ^zlib@1.2.11%gcc@7.3.1+optimize+pic+shared arch=linux-rhel7-power9le
[+]  fodcl7k          ^tar@1.32%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  ly5lkdk      ^libffi@3.3%gcc@7.3.1 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-rhel7-power9le
[+]  dc5d6iz      ^openssl@1.1.1i%gcc@7.3.1+systemcerts arch=linux-rhel7-power9le
[+]  7xiufol          ^perl@5.32.1%gcc@7.3.1+cpanm+shared+threads arch=linux-rhel7-power9le
[+]  marvz4h              ^berkeley-db@18.1.40%gcc@7.3.1 arch=linux-rhel7-power9le
[+]  tgpbfrk      ^sqlite@3.34.0%gcc@7.3.1+column_metadata+fts~functions~rtree arch=linux-rhel7-power9le
[+]  feekvth      ^util-linux-uuid@2.36%gcc@7.3.1 arch=linux-rhel7-power9le

==> Installing environment myenv
==> All of the packages are already installed
==> Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
==> [2021-02-03-18:19:19.457666] Imported add from built-in commands
==> [2021-02-03-18:19:19.458542] Imported add from built-in commands
==> [2021-02-03-18:19:19.568315] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/repos.yaml
==> [2021-02-03-18:19:19.572223] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/spack.yaml
==> [2021-02-03-18:19:20.968699] DATABASE LOCK TIMEOUT: 3s
==> [2021-02-03-18:19:20.968767] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-02-03-18:19:21.168633] TEMPORARY DIRECTORY CREATED [/var/tmp/tmpy2_svkw9]
==> [2021-02-03-18:19:20.938898] Adding py-numpy to environment myenv
Traceback (most recent call last):
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 806, in move
OSError: [Errno 18] Invalid cross-device link: '/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view' -> '/var/tmp/tmpy2_\
svkw9/view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/WS1/moon13/temp/20210201_build/spack/bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/cmd/add.py", line 35, in add
    env.write()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 1677, in write
    self.regenerate_views()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 1229, in regenerate_views
    view.regenerate(specs, self.roots())
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 563, in regenerate
    with fs.replace_directory_transaction(root):
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/contextlib.py", line 117, in __enter__
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/llnl/util/filesystem.py", line 687, in replace_directory_transaction
    shutil.move(src=directory_name, dst=tmp_dir)
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 818, in move
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 718, in rmtree
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 659, in _rmtree_safe_fd
  File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 657, in _rmtree_safe_fd
OSError: [Errno 39] Directory not empty: 'bin'
```

</details>

The error seems to arise at:
https://github.com/spack/spack/blob/457fc4c095c6d06cfdaa6634f81dfd4044cb4eab/lib/spack/llnl/util/filesystem.py#L687

@becker33  suggested running with PR https://github.com/spack/spack/pull/20720 (https://github.com/spack/spack/pull/20720/commits/83c9a32032891305aeff9a8293321860b8691baa), but that produced a different error:

<details> 

```
==> Successfully removed environment 'myenv'
==> Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
==> Created environment 'myenv' in /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv
==> You can activate this environment with:
==>   spack env activate myenv
==> Adding python@3.9.1 to environment myenv
==> Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
==> Error: /g/g17/moon13/.spack/packages.yaml:3: Additional properties are not allowed ('externals' was unexpected)
==> [2021-02-03-18:42:48.656908] Imported add from built-in commands
==> [2021-02-03-18:42:48.657789] Imported add from built-in commands
==> [2021-02-03-18:42:48.664475] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/repos.yaml
==> [2021-02-03-18:42:48.668425] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/spack.yaml
==> [2021-02-03-18:42:48.832976] DATABASE LOCK TIMEOUT: 3s
==> [2021-02-03-18:42:48.833039] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-02-03-18:42:48.848939] TEMPORARY DIRECTORY CREATED [/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/tmpa9maeavk\
]
==> [2021-02-03-18:42:48.850036] DIRECTORY MOVED [src=/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view, dest=/usr/WS1\
/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/tmpa9maeavk]
==> [2021-02-03-18:42:48.852826] TEMPORARY DIRECTORY DELETED [/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/tmpa9maeavk\
]
==> [2021-02-03-18:42:48.820224] Adding py-numpy to environment myenv
==> [2021-02-03-18:42:48.850473] Updating view at /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view
```

</details>

### Information on your system

```
* **Spack:** 0.16.0-1102-040204c261
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original
 ```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Could you include the output of `spack config blame packages` here?

(EDIT) Did you try the PR by checking out the PR branch?

**Comment by timmoon10** [comment]
<details> <summary> spack config blame packages </summary>

```
---                                                                            packages:
/g/g17/moon13/.spack/packages.yaml:2                                             python:
/g/g17/moon13/.spack/packages.yaml:3                                               externals:
/g/g17/moon13/.spack/packages.yaml:4                                               - spec: python@2.7.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
/g/g17/moon13/.spack/packages.yaml:5                                                 prefix: /usr
/g/g17/moon13/.spack/packages.yaml:6                                               - spec: python@3.4.10+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
/g/g17/moon13/.spack/packages.yaml:7                                                 prefix: /usr
/g/g17/moon13/.spack/packages.yaml:8                                               - spec: python@3.6.8+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
/g/g17/moon13/.spack/packages.yaml:9                                                 prefix: /usr
/g/g17/moon13/.spack/packages.yaml:10                                              - spec: python@3.7.2+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
/g/g17/moon13/.spack/packages.yaml:11                                                prefix: /usr/tce/packages/python/python-3.7.2
/g/g17/moon13/.spack/packages.yaml:12                                              - spec: python@2.7.16+bz2+ctypes+dbm~lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
/g/g17/moon13/.spack/packages.yaml:13                                                prefix: /usr/tcetmp
/g/g17/moon13/.spack/packages.yaml:14                                            git:
/g/g17/moon13/.spack/packages.yaml:15                                              externals:
/g/g17/moon13/.spack/packages.yaml:16                                              - spec: git@2.29.1+tcltk
/g/g17/moon13/.spack/packages.yaml:17                                                prefix: /usr/tce/packages/git/git-2.29.1
/g/g17/moon13/.spack/packages.yaml:18                                              - spec: git@1.8.3.1+tcltk
/g/g17/moon13/.spack/packages.yaml:19                                                prefix: /usr
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:17    all:
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:18      compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:19      providers:
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:20        D: [ldc]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:21        awk: [gawk]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:22        blas: [openblas, amdblis]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:23        daal: [intel-daal]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:24        elf: [elfutils]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:25        fftw-api: [fftw, amdfftw]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:26        gl: [mesa+opengl, mesa18, opengl]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:27        glx: [mesa+glx, mesa18+glx, opengl]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:28        glu: [mesa-glu, openglu]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:29        golang: [gcc]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:30        iconv: [libiconv]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:31        ipp: [intel-ipp]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:32        java: [openjdk, jdk, ibm-java]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:33        jpeg: [libjpeg-turbo, libjpeg]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:34        lapack: [openblas, amdlibflame]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:35        mariadb-client: [mariadb-c-client, mariadb]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:36        mkl: [intel-mkl]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:37        mpe: [mpe2]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:38        mpi: [openmpi, mpich]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:39        mysql-client: [mysql, mariadb-c-client]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:40        opencl: [pocl]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:41        osmesa: [mesa+osmesa, mesa18+osmesa]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:42        pil: [py-pillow]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:43        pkgconfig: [pkgconf, pkg-config]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:44        rpc: [libtirpc]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:45        scalapack: [netlib-scalapack, amdscalapack]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:46        sycl: [hipsycl]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:47        szip: [libszip, libaec]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:48        tbb: [intel-tbb]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:49        unwind: [libunwind]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:50        yacc: [bison, byacc]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:51        flame: [libflame, amdlibflame]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:52        uuid: [util-linux-uuid, libuuid]
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:53      permissions:
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:54        read: world
/usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml:55        write: user
```

</details>

Yes, I just checked out the PR branch, which gave me commit https://github.com/spack/spack/commit/83c9a32032891305aeff9a8293321860b8691baa. If I call `spack --debug install` after my snippet, it outputs:

<details>

```
==> [2021-02-04-07:36:46.976720] TEMPORARY DIRECTORY DELETED [/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/tmp8jye25rj]
==> [2021-02-04-07:36:47.562332] Imported install from built-in commands
==> [2021-02-04-07:36:47.564409] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/spack.yaml
==> [2021-02-04-07:36:47.569971] Imported install from built-in commands
==> [2021-02-04-07:36:47.579287] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/repos.yaml
==> [2021-02-04-07:36:47.774133] Reading config file /usr/WS1/moon13/temp/20210201_build/spack/etc/spack/defaults/packages.yaml
==> [2021-02-04-07:36:47.814513] Reading config file /g/g17/moon13/.spack/packages.yaml
==> [2021-02-04-07:36:47.829181] ConfigFormatError: /g/g17/moon13/.spack/packages.yaml:3: Additional properties are not allowed ('externals' was unexpected)
==> [2021-02-04-07:36:47.829247] Error: /g/g17/moon13/.spack/packages.yaml:3: Additional properties are not allowed ('externals' was unexpected)
Traceback (most recent call last):
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 771, in validate
    spack.schema.Validator(schema).validate(test_data)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/external/jsonschema/validators.py", line 114, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('externals' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['packages']['patternProperties']['\\w[\\w-]*']:
    {'additionalProperties': False,
     'default': {},
     'properties': {'buildable': {'default': True, 'type': 'boolean'},
                    'compiler': {'default': [],
                                 'items': {'type': 'string'},
                                 'type': 'array'},
                    'modules': {'default': {}, 'type': 'object'},
                    'paths': {'default': {}, 'type': 'object'},
                    'permissions': {'additionalProperties': False,
                                    'properties': {'group': {'type': 'string'},
                                                   'read': {'enum': ['user',
                                                                     'group',
                                                                     'world'],
                                                            'type': 'string'},
                                                   'write': {'enum': ['user',
                                                                      'group',
                                                                      'world'],
                                                             'type': 'string'}},
                                    'type': 'object'},
                    'providers': {'additionalProperties': False,
                                  'default': {},
                                  'patternProperties': {'\\w[\\w-]*': {'default': [],
                                                                       'items': {'type': 'string'},
                                                                       'type': 'array'}},
                                  'type': 'object'},
                    'target': {'default': [],
                               'items': {'type': 'string'},
                               'type': 'array'},
                    'variants': {'oneOf': [{'type': 'string'},
                                           {'items': {'type': 'string'},
                                            'type': 'array'}]},
                    'variants': {'oneOf': [{'type': 'string'},
                                           {'items': {'type': 'string'},
                                            'type': 'array'}]},
                    'version': {'default': [],
                                'items': {'anyOf': [{'type': 'string'},
                                                    {'type': 'number'}]},
                                'type': 'array'}},
     'type': 'object'}

On instance['packages']['python']:
    CommentedMap([('externals',
                   [CommentedMap([('spec',
                                   'python@2.7.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib'),
                                  ('prefix', '/usr')]),
                    CommentedMap([('spec',
                                   'python@3.4.10+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib'),
                                  ('prefix', '/usr')]),
                    CommentedMap([('spec',
                                   'python@3.6.8+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib'),
                                  ('prefix', '/usr')]),
                    CommentedMap([('spec',
                                   'python@3.7.2+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib'),
                                  ('prefix',
                                   '/usr/tce/packages/python/python-3.7.2')]),
                    CommentedMap([('spec',
                                   'python@2.7.16+bz2+ctypes+dbm~lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib'),
                                  ('prefix', '/usr/tcetmp')])])])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/cmd/install.py", line 277, in install
    concretized_specs = env.concretize()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 1009, in concretize
    return self._concretize_separately()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 1077, in _concretize_separately
    concrete = _concretize_from_constraints(uspec_constraints)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/environment.py", line 1682, in _concretize_from_constraints
    return s.concretized()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/spec.py", line 2323, in concretized
    clone.concretize()
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/spec.py", line 2170, in concretize
    self._expand_virtual_packages(concretizer),
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/spec.py", line 2075, in _expand_virtual_packages
    candidates = concretizer.choose_virtual_or_external(spec)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/concretize.py", line 120, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/concretize.py", line 94, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/package_prefs.py", line 194, in is_spec_buildable
    allpkgs = spack.config.get('packages')
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 722, in get
    return config.get(path, default, scope)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 547, in get
    value = self.get_config(section, scope=scope)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 508, in get_config
    data = scope.get_section(section)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 151, in get_section
    data   = read_config_file(path, schema)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 813, in read_config_file
    validate(data, schema)
  File "/usr/WS1/moon13/temp/20210201_build/spack/lib/spack/spack/config.py", line 777, in validate
    raise ConfigFormatError(e, data, filename, line_number)
spack.config.ConfigFormatError: /g/g17/moon13/.spack/packages.yaml:3: Additional properties are not allowed ('externals' was unexpected)
```

</details>

For my runs on the `develop` branch, I'm at commit https://github.com/spack/spack/commit/beb4d968ef73d1e8bebe9c4d4fbb89bff1001d8d.

**Comment by scheibelp** [comment]
Would you be able to temporarily move that config file and then see if #20720 addresses the issue for you?

I think this might be two separate problems (and I'd like to fix both but I think it will be worth establishing that they are second)

Another sanity check (if the above doesn't work): could you try

```
spack env activate foo
spack add python@3.9:
spack install
despacktivate           <--- I'm curious if deactivating/reactivating addresses an issue finding python
spack env activate foo
spack add py-numpy
```

**Comment by timmoon10** [comment]
No cigar, same error. From what I can tell, the main Spack driver chooses the Python exe at:
https://github.com/spack/spack/blob/52058ad5a749ffaf1e6621e0566387d70082533a/bin/spack#L14
If there is a Python exe in the environment view, then Spack will pick it up when it tries calling `python3`. PR https://github.com/spack/spack/pull/21222 gets around this by trying `SPACK_PYTHON` before trying `python3`.

**Comment by alalazo** [comment]
For the record, the real error seems to be:
```
File "/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view/lib/python3.9/shutil.py", line 806, in move
OSError: [Errno 18] Invalid cross-device link: '/usr/WS1/moon13/temp/20210201_build/spack/var/spack/environments/myenv/.spack-env/view' -> '/var/tmp/tmpy2_\
svkw9/view'
```
Similarly to #32687 I can't reproduce it on my machine, and I think the machine configuration where Spack is run is part of the issue.
