### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#21590]
### Steps to reproduce the issue

```console
$ spack spec pango ^cairo+svg
(...)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Concretizing just `cairo+svg` works just fine. 

I have done some debugging myself, and looks like this is caused by dependency loop: `cairo -> librsvg -> cairo`.

### Error Message

```console
$ spack --debug --stacktrace spec pango ^cairo+svg
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.978696] pango applying constraint cairo+fc+ft
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.980731] pango applying constraint glib
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.982485] pango applying constraint gobject-introspection
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.984373] pango applying constraint fontconfig
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.986169] pango applying constraint freetype@2:
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.987919] pango applying constraint libffi
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.988565] pango applying constraint pkgconf
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.990349] pango applying constraint harfbuzz
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.992277] pango applying constraint cairo+fc+ft
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.994354] pango applying constraint glib
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.996163] pango applying constraint gobject-introspection
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.997937] pango applying constraint fontconfig
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:25.999735] pango applying constraint freetype@2:
lib/spack/spack/spec.py:2765 ==> [2021-02-10-11:17:26.001487] pango applying constraint libffi
lib/spack/spack/config.py:908 ==> [2021-02-10-11:17:26.177562] Reading config file /home/sftnight/.spack/linux/compilers.yaml
Traceback (most recent call last):
  File "/workspace/vspack/spack/bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "/workspace/vspack/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/workspace/vspack/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/workspace/vspack/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2537, in concretize
    self._old_concretize(tests)
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2337, in _old_concretize
    self._concretize_helper(concretizer))
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2161, in _concretize_helper
    concretizer, presets, visited
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2161, in _concretize_helper
    concretizer, presets, visited
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2161, in _concretize_helper
    concretizer, presets, visited
  [Previous line repeated 985 more times]
  File "/workspace/vspack/spack/lib/spack/spack/spec.py", line 2159, in _concretize_helper
    for name in sorted(self._dependencies.keys()):
  File "/usr/lib64/python3.6/_collections_abc.py", line 702, in __len__
    return len(self._mapping)
RecursionError: maximum recursion depth exceeded
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.0-1226-bd83654
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment]
Full output from `spack --debug --stacktrace`: https://gist.github.com/iarspider/8ca3ebf51245e2048a0d5c12a34bab97

**Comment by alalazo** [comment]
This is usually a symptom of a circular dependency. Can you check what the ASP based concretizer says? It should emit unsat cores if this is a circular dependency issue.

**Comment by iarspider** [comment]
@alalazo if you can point me to the instructions for switching to `ASP based concretizer` - sure.

**Comment by haampie** [comment]
```
$ spack solve pango ^cairo+svg
==> The following constraints are unsatisfiable:
  dependency_condition(115,"cairo","librsvg")
  dependency_condition(1559,"pango","cairo")
  dependency_condition(1567,"pango","gobject-introspection")
  dependency_condition(454,"gobject-introspection","cairo")
  dependency_condition(870,"librsvg","gobject-introspection")
  dependency_type(115,"build")
  dependency_type(1559,"build")
  dependency_type(1567,"build")
  dependency_type(454,"build")
  dependency_type(870,"build")
  root("pango")
  variant("cairo","svg")
  variant_set("cairo","svg","True")
==> Error: Unsatisfiable spec.
```

**Comment by alalazo** [comment]
The circular dependency is:
```
cairo -> librsvg -> gobject-introspection -> cairo
```

**Comment by alalazo** [comment]
This is very unlikely to be solved with the original concretizer, while it probably needs #21564 to work correctly with the new concretizer.

**Comment by salotz-sitx** [comment]
```
* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.8.15
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo
```

```
--> spack spec cairo +svg
==> Error: Cyclic dependency detected between 'librsvg' and 'cairo'
    Consider changing variants to avoid the cycle
```
Just adding my experience.

**Comment by alalazo** [comment]
Closing, since the recursion error is gone when using the new concretizer. We have separate concretization of build deps in our roadmap which would solve the recursion. In the meanwhile:
![Screenshot from 2023-04-06 09-43-57](https://user-images.githubusercontent.com/4199709/230308987-c8d8d3f8-093f-4f3b-bb0b-8b0b717433e9.png)
