### ISSUE TITLE
spack install fails with AttributeError

### ISSUE THREAD

**Issue by healther** [LLNL/spack#2232]
I came across this error first, when trying to build a custom made spack package for one of our own modules. There it occurred once I added 
```
depends_on('py-numpy')
depends_on('py-scipy')
```
to the package.py file. So running ```spack install py-sbs``` completed without these two lines, but obviously it failed at runtime. So I did a ```spack uninstall py-sbs```, added the two lines to the package.py and did a ```spack install py-sbs```
This then failed with a python traceback like the one below. After doing a ```spack clean py-sbs```, ```spack purge -a``` and a ```spack reindex```, the install went through.

Now I'm seeing the error message below when trying to install ```py-matplotlib```. I'm not entirely sure how I "fixed" it for our own package. Can you provide me with any hints of where this originates at? I haven't touched py-matplotlib's package.py.

Any help would be greatly appreciated.

```
[hd_wv385@uc1n996 git]$ spack load --dependencies python@2.7.12%gcc@4.9.3
[hd_wv385@uc1n996 git]$ spack install py-matplotlib
Traceback (most recent call last):
  File "/home/hd/hd_hd/hd_wv385/git/spack/bin/spack", line 203, in <module>
    main()
  File "/home/hd/hd_hd/hd_wv385/git/spack/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/cmd/install.py", line 313, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/cmd/__init__.py", line 108, in parse_specs
    spec.concretize()  # implies normalize
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/spec.py", line 1330, in concretize
    self._expand_virtual_packages(),
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/spec.py", line 1247, in _expand_virtual_packages
    spec)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/concretize.py", line 122, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/concretize.py", line 62, in _valid_virtuals_and_externals
    providers = spack.repo.providers_for(spec)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/repository.py", line 75, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/repository.py", line 240, in providers_for
    providers = self.provider_index.providers_for(vpkg_spec)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/repository.py", line 234, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/repository.py", line 645, in provider_index
    self._update_provider_index()
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/repository.py", line 639, in _update_provider_index
    self._provider_index.to_yaml(new)
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/llnl/util/lock.py", line 312, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/pfs/data2/home/hd/hd_hd/hd_wv385/git/spack/lib/spack/spack/file_cache.py", line 152, in __exit__
    raise value
AttributeError
```

**Comment by citibeth** [comment]
I've never seen this.  @adamjstewart @alalazo @tgamblin  anyone?

**Comment by adamjstewart** [comment]
I've never seen this before. By the way, you shouldn't need to load Python and its dependencies to install Matplotlib, Spack does this internally. In fact, I have encountered a few problems when running Spack with a Spack-installed Python.

**Comment by citibeth** [comment]
One one system (but not another) I've found I had to load Python and its
deps to install some Python stuff.  I believe I've submitted an issue on it.

Spack doesn't work at all with my Python, since it's Python3.  I solve this
with:
```
alias spack='PYTHONPATH= spack'
```
If you're trying to have Spack avoid a Spack-installed Python2, the alias
would be a bit different.

**Comment by healther** [comment]
@citibeth Thanks for the alias trick.
However it does not alleviate my problem right now :/ I tried installing different packages, some work, some fail, however I can't give you any clear pattern

Works:
- tmux, vim
Fails:
- py-matplotlib, py-scikit-learn, py-scikit-image

I will try some additional packages today and keep this list updated, but I don't have an idea of where I could start to find the reason for this.

@adamjstewart If I don't load the python version I want matplotlib (or any other python module) to be installed for, how does spack know which version to install it for (thinking especially about py2 vs py3)

**Comment by adamjstewart** [comment]
@healther Have you read through [our documentation](http://spack.readthedocs.io/en/latest/index.html)? Basically, Spack doesn't look for dependencies in your PATH, PYTHONPATH, or anything like that. It builds them all based on the spec that you pass to it. If it finds that you have already installed them, it reuses them. A useful command to see what will get installed is `spack spec`. For example, run the following commands:
```
$ spack spec py-matplotlib
```
Spack defaults to the latest version of Python 2. 
```
$ spack spec py-matplotlib ^python@3.5.2
```
You'll see in the latter case, we tell Spack exactly which Python we want to build with.
