### ISSUE TITLE
unicode issue with spack mfem package with python 2

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#22459]
looks like there is a python 2 literal vs unicode issue in the mfem spack pacakge 

### Steps to reproduce the issue

```console
bin/spack install mfem~mpi~metis~zlib
```

### Error Message

```console
bin/spack -d install mfem~mpi~metis~zlib
==> [2021-03-22-11:35:42.084746] Imported install from built-in commands
==> [2021-03-22-11:35:42.086759] Reading config file /Users/harrison37/Work/alpine/spack/etc/spack/defaults/config.yaml
==> [2021-03-22-11:35:42.112031] Imported install from built-in commands
==> [2021-03-22-11:35:42.145861] Reading config file /Users/harrison37/Work/alpine/spack/etc/spack/defaults/repos.yaml
==> [2021-03-22-11:35:42.273335] Reading config file /Users/harrison37/Work/alpine/spack/etc/spack/defaults/packages.yaml
==> [2021-03-22-11:35:42.311565] Reading config file /Users/harrison37/Work/alpine/spack/etc/spack/defaults/darwin/packages.yaml
==> [2021-03-22-11:35:42.324870] Reading config file /Users/harrison37/.spack/darwin/compilers.yaml
==> [2021-03-22-11:35:42.423266] DATABASE LOCK TIMEOUT: 3s
==> [2021-03-22-11:35:42.423383] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-03-22-11:35:42.458759] Initializing the build queue from the build requests
==> [2021-03-22-11:35:42.458859] Initializing the build queue for mfem
==> [2021-03-22-11:35:42.459689] Processing dependencies for mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl: ('build', 'link', 'run')
==> [2021-03-22-11:35:42.499291] Removing failure marking for mfem
==> [2021-03-22-11:35:42.499660] Pkg id mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl has the following dependents:
==> [2021-03-22-11:35:42.500422] Ensure all dependencies know all dependents across specs
==> [2021-03-22-11:35:42.500977] Acquiring a write lock on mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl with timeout 1e-09
==> [2021-03-22-11:35:42.503725] Creating stage lock spack-stage-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl
==> [2021-03-22-11:35:42.731417] Installing mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl
==> [2021-03-22-11:35:42.731496] Searching for binary cache of mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl
==> [2021-03-22-11:35:42.731660] Reading config file /Users/harrison37/Work/alpine/spack/etc/spack/defaults/mirrors.yaml
==> [2021-03-22-11:35:42.916433] Did not find darwin-mojave-skylake-apple-clang-11.0.0-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl.spec.yaml on https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/darwin-mojave-skylake-apple-clang-11.0.0-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-03-22-11:35:42.919363] No binary for mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl found: installing from source
==> [2021-03-22-11:35:43.064067] [TOOLCHAIN] MATCH Aocc
==> [2021-03-22-11:35:43.064715] [TOOLCHAIN] MATCH AppleClang
==> [2021-03-22-11:35:43.065262] [TOOLCHAIN] MATCH Clang
==> [2021-03-22-11:35:43.065743] [TOOLCHAIN] MATCH Gcc
==> [2021-03-22-11:35:43.066187] [TOOLCHAINS] set(['AppleClang', 'Aocc', 'Gcc', 'Clang'])
==> [2021-03-22-11:35:43.066762] Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.0 for further details]
==> [2021-03-22-11:35:43.081232] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-03-22-11:35:43.179899] '/usr/bin/clang++' '-v' '/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoRJ3dfa/main.c' '-o' '/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoRJ3dfa/output'
==> [2021-03-22-11:35:43.328354] parsing implicit link info
==> [2021-03-22-11:35:43.329548] linker line:  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.14.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoRJ3dfa/output /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/main-bb0a8f.o -L/usr/local/lib -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
==> [2021-03-22-11:35:43.330370] linkdir: /usr/local/lib
==> [2021-03-22-11:35:43.331101] found raw link dirs: /usr/local/lib
==> [2021-03-22-11:35:43.331863] found link dirs: /usr/local/lib
==> [2021-03-22-11:35:43.347139] Using cached archive: /Users/harrison37/Work/alpine/spack/var/spack/cache/_source-cache/archive/43/4352a225b55948d2e73a5ee88cece0e88bdbe7ba6726a23d68b2736d3221a86d.tar.gz
==> [2021-03-22-11:35:43.359489] Staging archive: /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/harrison37/spack-stage/spack-stage-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl/mfem-4-2
==> [2021-03-22-11:35:43.361020] '/usr/bin/tar' '-oxf' '/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/harrison37/spack-stage/spack-stage-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl/mfem-4-2'
==> [2021-03-22-11:35:43.707494] Created stage in /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/harrison37/spack-stage/spack-stage-mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl
==> [2021-03-22-11:35:43.718160] Error: UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

/Users/harrison37/Work/alpine/spack/var/spack/repos/builtin/packages/mfem/package.py:733, in patch:
        731    def patch(self):
        732        # Remove the byte order mark since it messes with some compilers
  >>    733        filter_file(u'\uFEFF', '', 'fem/gslib.hpp')
        734        filter_file(u'\uFEFF', '', 'fem/gslib.cpp')
        735        filter_file(u'\uFEFF', '', 'linalg/hiop.hpp')


Traceback (most recent call last):
  File "/Users/harrison37/Work/alpine/spack/lib/spack/spack/build_environment.py", line 856, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/Users/harrison37/Work/alpine/spack/lib/spack/spack/installer.py", line 1648, in build_process
    pkg.do_patch()
  File "/Users/harrison37/Work/alpine/spack/lib/spack/spack/package.py", line 1450, in do_patch
    self.patch()
  File "/Users/harrison37/Work/alpine/spack/lib/spack/spack/multimethod.py", line 133, in __call__
    return spec_method(package_self, *args, **kwargs)
  File "/Users/harrison37/Work/alpine/spack/var/spack/repos/builtin/packages/mfem/package.py", line 734, in patch
    filter_file(u'\uFEFF', '', 'fem/gslib.cpp')
  File "/Users/harrison37/Work/alpine/spack/lib/spack/llnl/util/filesystem.py", line 163, in filter_file
    tty.debug(msg.format(filename, regex))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
==> [2021-03-22-11:35:43.719476] Flagging mfem-4.2.0-psdfs5sp27jwqdnpxaui3247vla6vjsl as failed: UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
==> [2021-03-22-11:35:43.725228] ChildError: UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
```

### Information on your system

```
* **Spack:** 0.16.1-1703-2607bdd25c
* **Python:** 2.7.16
* **Platform:** darwin-mojave-skylake
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

There are a few similar instances of issues, but they are for other pacakges or spack proper (not the mfem package)

**Comment by cyrush** [comment]
@markcmiller86  helped me stare at the files, it doesn't seem they actually have the `u\uFEFF` prefix BOM (byte order mark). They do have *a* BOM, but its a different one.

I suspect that in python 3, simply calling the `filter_file` (regardless of the input pattern) sanitizes the file b/c the following kwargs are used when reading the file:

`extra_kwargs = {'errors': 'surrogateescape'}`

but not sure this helps with the python 2 case. `filter_file` won't do the same accidental magic for us in python 2.  :-(

**Comment by markcmiller86** [comment]
Maybe not fix your problem here but since the `package.py` comments for filtering out BOM suggested compiler couldn't handle source files with BOM, one question is whether there are compiler flags you can pass to get around that? If so, these might help...

* https://stackoverflow.com/questions/7899795/is-it-possible-to-get-gcc-to-compile-utf-8-with-bom-source-files
* https://community.intel.com/t5/Intel-Fortran-Compiler/Severe-59-when-reading-a-file-ANSI-as-UTF-8/td-p/1176991

**Comment by cyrush** [comment]
thanks @markcmiller86, I don't have an easy way to test against the NVIDIA HPC SDK, which I think is the compiler set that this change was added for.

**Comment by cyrush** [comment]
Talking with mfem folks, they expect the byte order marks only exist in the 4.1 release. 

With this info, we can limit the patching to only 4.1.0. And that will allow folks to build with 4.2.

That doesn't resolve the issue with installing mfem 4.1.0 with spack when using  python 2, but I think its off the critical path for me (and others).

**Comment by v-dobrev** [comment]
I believe this issue is one of the issues addressed in https://github.com/spack/spack/pull/19748.

**Comment by alalazo** [comment]
Closing, since we don't support running on Python 2 anymore
