### ISSUE TITLE
Race condition on "spack config update" 

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#22585]
Context: I activated an environment and tried `spack install -j 20`, received an error about using an old config file:

```
==> Error: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

        spack config [--scope=<scope] update config

```

I then tried the above suggestion. 

`spack config update config`

This fails b/c it says spack can't write to the file -- the perms are bad.

Perms are fine in this case.  Looks like there is an issue with how the perms are checked when `spack.yaml` is used. 

More details below. 

### Steps to reproduce the issue

env file:

```
# tested against: spack develop
spack:
  specs:
  - zlib
  concretization: together
  config:
    install_tree: spack-build
    install_path_scheme: spack-libs/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}
  compilers:
  - compiler:
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      operating_system: ubuntu18.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
      flags: {}
      spec: gcc@7.5.0
```

```console
spack env activate .
spack concretize
spack install -j 20
spack -d config update config
```

The old nature has something to do with the compilers entry, but that's orthogonal to the problem here. 

Note: `spack install` does not fail out of the gate if I omit the `-j 20`, but `spack config update config` always fails once when in this state. 

The fact that `spack install -j 20` fails with the message about bad config, but `spack install` doesn't worries me.

I am trying to build and install to a subdir of where I am using the env file, not inside the spack dir. 

I also modified the `_can_update_config_file` in spack/lib/spack/spack/cmd/config.py see what was going on:

```
def _can_update_config_file(scope_dir, cfg_file):
    print("checking dir  = {0}".format(scope_dir))
    print("checking file = {0}".format(cfg_file))
    dir_ok = fs.can_write_to_dir(scope_dir)
    cfg_ok = fs.can_access(cfg_file)
    return dir_ok and cfg_ok
```
From the print out below, it seems like both the `scope_dir` and `cfg_file` point to the yaml file. 
I suspect since the yaml file is not a dir, the `fs.can_write_to_dir(scope_dir)` fails, thinking it can't update the file.

### Error Message

`spack install -j 20` error:

```
root@8dbfcc640e3f:/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel# spack env activate . 
root@8dbfcc640e3f:/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel# spack concretize 
==> Warning: gcc@7.5.0 cannot build optimized binaries for "zen3". Using best target possible: "zen"
==> Concretized zlib
 -   egwcgg2  zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu18.04-zen

==> Updating view at /ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/.spack-env/view
root@8dbfcc640e3f:/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel# spack -d install -j 20 
==> [2021-03-26-21:46:31.828289] Imported install from built-in commands
==> [2021-03-26-21:46:31.830771] Reading config file /ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/spack.yaml
==> [2021-03-26-21:46:31.837162] Imported install from built-in commands
Traceback (most recent call last):
  File "/_t/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/_t/spack/lib/spack/spack/main.py", line 754, in main
    args, unknown = parser.parse_known_args()
  File "/_t/spack/lib/spack/external/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/_t/spack/lib/spack/external/argparse.py", line 1942, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/_t/spack/lib/spack/external/argparse.py", line 1919, in consume_positionals
    take_action(action, args)
  File "/_t/spack/lib/spack/external/argparse.py", line 1828, in take_action
    action(self, namespace, argument_values, option_string)
  File "/_t/spack/lib/spack/external/argparse.py", line 1128, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/_t/spack/lib/spack/external/argparse.py", line 1754, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/_t/spack/lib/spack/external/argparse.py", line 1960, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/_t/spack/lib/spack/external/argparse.py", line 1900, in consume_optional
    take_action(action, args, option_string)
  File "/_t/spack/lib/spack/external/argparse.py", line 1828, in take_action
    action(self, namespace, argument_values, option_string)
  File "/_t/spack/lib/spack/spack/cmd/common/arguments.py", line 106, in __call__
    spack.config.set('config:build_jobs', jobs, scope='command_line')
  File "/_t/spack/lib/spack/spack/config.py", line 902, in set
    return config.set(path, value, scope)
  File "/_t/spack/lib/spack/spack/config.py", line 393, in _method
    return method(self, *args, **kwargs)
  File "/_t/spack/lib/spack/spack/config.py", line 690, in set
    self.update_config(section, section_data, scope=scope)
  File "/_t/spack/lib/spack/spack/config.py", line 393, in _method
    return method(self, *args, **kwargs)
  File "/_t/spack/lib/spack/spack/config.py", line 537, in update_config
    raise RuntimeError(msg)
RuntimeError: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

        spack config [--scope=<scope] update config

Note that previous versions of Spack will not be able to use the updated configuration.
```

`spack config update config` error:

```
root@8dbfcc640e3f:/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel# spack -d config update config
==> [2021-03-26-21:49:11.101191] Imported config from built-in commands
==> [2021-03-26-21:49:11.103302] Imported config from built-in commands
==> [2021-03-26-21:49:11.105243] Reading config file /ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/spack.yaml
checking dir  = /ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/spack.yaml
checking file = /ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/spack.yaml
==> [2021-03-26-21:49:11.111383] Error: Detected permission issues with the following scopes:

        [scope=env:/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel, cfg=/ascent/scripts/uberenv/spack_envs/ci/ubuntu_18_devel/spack.yaml]

Either ensure that you have sufficient permissions to modify these files or do not include these scopes in the update.
Traceback (most recent call last):
  File "/_t/spack/lib/spack/spack/main.py", line 768, in main
    return _invoke_command(command, parser, args, unknown)
  File "/_t/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/_t/spack/lib/spack/spack/cmd/config.py", line 474, in config
    action[args.config_command](args)
  File "/_t/spack/lib/spack/spack/cmd/config.py", line 274, in config_update
    tty.die(msg)
  File "/_t/spack/lib/spack/llnl/util/tty/__init__.py", line 239, in die
    sys.exit(1)
```

### Information on your system

* **Spack:** 0.16.1-1912-58ad774773
* **Python:** 2.7.17
* **Platform:** linux-ubuntu18.04-zen3
* **Concretizer:** original
root@8dbfcc640e3f:/ascent/s

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by cyrush** [comment]
updated the reproducer with a simpler env file, also tested on spack develop just to make sure it wasn't due to using  a branch

**Comment by becker33** [comment]
@cyrush have you tried using the new format to specify the install tree?

```
  config:
    install_tree: spack-build
    install_path_scheme: spack-libs/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}
```
can be replaced with
```
  config:
    install_tree:
      root: spack-build
      projections:
        all: 'spack-libs/{compiler.name}-{compiler.version}/{name}-{version}'
```

**Comment by cyrush** [comment]
thanks @becker33 , I'll give this a try!

**Comment by cyrush** [comment]
@becker33 i was able to do -j installs, thanks for the showing me the right format!

Should we close this, or do you want to keep it up this as an old format vs new format issue?

**Comment by becker33** [comment]
Let's leave it for now, I'll change the title.
