### ISSUE TITLE
Activating a python extension yields an 'Attribute Error'

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#2283]
When I attempted to activate the `py-numpy` package depending on python with ucs4, I get an `AttributeError`. Here is my stacktrace:

```
spack activate py-numpy^python~tk+ucs4
Traceback (most recent call last):
  File "/home/matthew/Software/NCSA/Vertical/spack/spack/bin/spack", line 203, in <module>
    main()
  File "/home/matthew/Software/NCSA/Vertical/spack/spack/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack/lib/spack/spack/cmd/activate.py", line 54, in activate
    spec.package.do_activate()
  File "/home/matthew/Software/NCSA/Vertical/spack/spack/lib/spack/spack/package.py", line 1554, in do_activate
    self.extendee_spec.package.activate(self, **self.extendee_args)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack/var/spack/repos/builtin/packages/python/package.py", line 349, in activate
    exts = spack.install_layout.extension_map(self.spec)
AttributeError: 'module' object has no attribute 'install_layout'
```

Is the problem only that there are details missing from the package.py file for py-numpy?

**Comment by adamjstewart** [comment]
This should have been fixed in #2197. Can you check out the latest develop and test it out?

**Comment by krafczyk** [comment]
Yep, I'm testing it now.

**Comment by krafczyk** [comment]
Okay, activating extensions works now.
