### ISSUE TITLE
Installation issue: Function not implemented

### ISSUE THREAD

**Issue by mingbairen** [LLNL/spack#22980]
[ff@mu01 preCICE]$ git clone -b develop https://github.com/spack/spack.git
[ff@mu01 preCICE]$ ls
spack
[ff@mu01 preCICE]$ . spack/share/spack/setup-env.sh
Traceback (most recent call last):
  File "/home/fengjingshen/preCICE/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/home/fengjingshen/preCICE/spack/lib/spack/spack/main.py", line 726, in main
    print_setup_info(*args.print_shell_vars.split(','))
  File "/home/fengjingshen/preCICE/spack/lib/spack/spack/main.py", line 679, in print_setup_info
    specs = spack.store.db.query(module_spec)
  File "/home/fengjingshen/preCICE/spack/lib/spack/spack/database.py", line 1492, in query
    local_results = set(self.query_local(*args, **kwargs))
  File "/home/fengjingshen/preCICE/spack/lib/spack/spack/database.py", line 1476, in query_local
    with self.read_transaction():
  File "/home/fengjingshen/preCICE/spack/lib/spack/llnl/util/lock.py", line 566, in __enter__
    if self._enter() and self._acquire_fn:
  File "/home/fengjingshen/preCICE/spack/lib/spack/llnl/util/lock.py", line 593, in _enter
    return self._lock.acquire_read(self._timeout)
  File "/home/fengjingshen/preCICE/spack/lib/spack/llnl/util/lock.py", line 305, in acquire_read
    wait_time, nattempts = self._lock(fcntl.LOCK_SH, timeout=timeout)
  File "/home/fengjingshen/preCICE/spack/lib/spack/spack/util/lock.py", line 31, in _lock
    return super(Lock, self)._lock(op, timeout)
  File "/home/fengjingshen/preCICE/spack/lib/spack/llnl/util/lock.py", line 186, in _lock
    if self._poll_lock(op):
  File "/home/fengjingshen/preCICE/spack/lib/spack/llnl/util/lock.py", line 210, in _poll_lock
    self._length, self._start, os.SEEK_SET)
OSError: [Errno 38] Function not implemented

[ff@mu01 preCICE]$ spack python --version
Python 3.6.9
[ff@mu01 preCICE]$ spack --version
0.16.1-2177-bff713a
[ff@mu01 preCICE]$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core) 

The above error occurred when entering the spack

**Comment by mingbairen** [comment]
I mainly want to install precice through spack. I have just operated it again：
[ff@mu01 spack2]$ ls
spack-develop  spack-develop.zip
[ff@mu01 spack2]$ . spack-develop/share/spack/setup-env.sh
[ff@mu01 spack2]$ spack install precice ^boost@1.74.0
==> Error: [Errno 38] Function not implemented
