### ISSUE TITLE
netlib-lapack install issue

### ISSUE THREAD

**Issue by Nandinihpc** [LLNL/spack#23073]
### Steps to reproduce the issue

```console
$ spack install <spec>
...
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Nandinihpc** [comment]
I am trying to install netlib-lapack and make it use the spack built openblas but it is not working. Please see the below output. 

spack spec --install-status netlib-lapack@3.8.0%gcc@10.2.0 +external-blas ^openblas/2zqwbx6
Input spec
--------------------------------
 -   netlib-lapack@3.8.0%gcc@10.2.0+external-blas
[+]      ^openblas@0.3.14%gcc@10.2.0 cflags="-march=broadwell -O3" cxxflags="-march=broadwell -O3" fflags="-march=broadwell -O3" ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=linux-centos8-broadwell

Concretized
--------------------------------
==> The following constraints are unsatisfiable:
  condition(1698)
  condition(1732)
  node("openblas")
  provider_condition(1698,"netlib-lapack","lapack")
  provider_condition(1732,"openblas","lapack")
  root("netlib-lapack")
  virtual("lapack")
==> Error: netlib-lapack@3.8.0%gcc@10.2.0+external-blas ^openblas@0.3.14%gcc@10.2.0 cflags="-march=broadwell -O3" cxxflags="-march=broadwell -O3" fflags="-march=broadwell -O3" ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=linux-centos8-broadwell does not satisfy unknown

**Comment by Nandinihpc** [comment]
this is the output of 
spack -debug --stacktrace spec --install-status netlib-lapack@3.8.0%gcc@10.2.0 +external-blas ^openblas@0.3.14/2zqwbx6

lib/spack/spack/solver/asp.py:217 ==> [2021-04-18-22:21:35.818181] The following constraints are unsatisfiable:
  condition(1698)
  condition(1732)
  node("openblas")
  provider_condition(1698,"netlib-lapack","lapack")
  provider_condition(1732,"openblas","lapack")
  root("netlib-lapack")
  virtual("lapack")
lib/spack/spack/main.py:775 ==> [2021-04-18-22:21:35.831179] UnsatisfiableSpecError: netlib-lapack@3.8.0%gcc@10.2.0+external-blas ^openblas@0.3.14%gcc@10.2.0 cflags="-march=broadwell -O3" cxxflags="-march=broadwell -O3" fflags="-march=broadwell -O3" ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=linux-centos8-broadwell does not satisfy unknown
lib/spack/spack/error.py:55 ==> [2021-04-18-22:21:35.839091] Error: netlib-lapack@3.8.0%gcc@10.2.0+external-blas ^openblas@0.3.14%gcc@10.2.0 cflags="-march=broadwell -O3" cxxflags="-march=broadwell -O3" fflags="-march=broadwell -O3" ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=linux-centos8-broadwell does not satisfy unknown
Traceback (most recent call last):
  File "/opt/apps/nfs/spack-quanah/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/apps/nfs/spack-quanah/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/opt/apps/nfs/spack-quanah/spack/lib/spack/spack/cmd/spec.py", line 109, in spec
    spec.concretize()
  File "/opt/apps/nfs/spack-quanah/spack/lib/spack/spack/spec.py", line 2577, in concretize
    self._new_concretize(tests)
  File "/opt/apps/nfs/spack-quanah/spack/lib/spack/spack/spec.py", line 2551, in _new_concretize
    self, "unknown", "Unsatisfiable!")
spack.error.UnsatisfiableSpecError: netlib-lapack@3.8.0%gcc@10.2.0+external-blas ^openblas@0.3.14%gcc@10.2.0 cflags="-march=broadwell -O3" cxxflags="-march=broadwell -O3" fflags="-march=broadwell -O3" ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=linux-centos8-broadwell does not satisfy unknown

**Comment by scheibelp** [comment]
@alalazo I think the main problem here is highlighted in https://github.com/spack/spack/issues/23073#issuecomment-822142811:

```
spack -debug --stacktrace spec --install-status netlib-lapack@3.8.0%gcc@10.2.0 +external-blas ^openblas@0.3.14/2zqwbx6
```

* The user specified `netlib-lapack+external-blas` so it should depend on `blas`
* The user specified a preexisting install of `openblas`
* `openblas` also provides `lapack`, so Spack is complaining that there are two `lapack` providers

(also note this is occurring with the new concretizer)

Is https://github.com/spack/spack/pull/15569 required for this?

**Comment by alalazo** [comment]
@scheibelp In general #15569 would be required. In this particular case I wonder if this is possible at all. My understanding is that `openblas` provides a unique library with both BLAS and LAPACK symbols in it, so I don't think one can easily use only the BLAS part as a building block for another LAPACK provider.

**Comment by Nandinihpc** [comment]
if so what is the exact command to use to build netlib-lapack?

**Comment by alalazo** [comment]
@Nandinihpc It depends what are your needs. If you just need `netlib-lapack` you can:
```console
$ spack install netlib-lapack
```
That will build both the BLAS and LAPACK part of the library, and won't be the fastest implementation ever though.
