### ISSUE TITLE
modules.yaml not working with LMOD as documented?

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#2311]
I am trying to follow the current documentation on `modules.yaml` found [here](https://spack.readthedocs.io/en/latest/module_file_tutorial.html#lua-hierarchical-module-files).  But when I create `~/.spack/modules.yaml` with the `enable::` keyword, I can't regenerate the modulefiles:

```
$ spack module refresh --module-type lmod -y
Traceback (most recent call last):
  File "/home/kellyt/temp/spack/bin/spack", line 129, in <module>
    module = spack.cmd.get_module(cmd)
  File "/home/kellyt/temp/spack/lib/spack/spack/cmd/__init__.py", line 74, in get_module
    level=0)
  File "/home/kellyt/temp/spack/lib/spack/spack/cmd/cd.py", line 26, in <module>
    import spack.modules
  File "/home/kellyt/temp/spack/lib/spack/spack/modules.py", line 65, in <module>
    CONFIGURATION = spack.config.get_config('modules')
  File "/home/kellyt/temp/spack/lib/spack/spack/config.py", line 403, in get_config
    data = scope.get_section(section)
  File "/home/kellyt/temp/spack/lib/spack/spack/config.py", line 248, in get_section
    data   = _read_config_file(path, schema)
  File "/home/kellyt/temp/spack/lib/spack/spack/config.py", line 326, in _read_config_file
    validate_section(data, schema)
  File "/home/kellyt/temp/spack/lib/spack/spack/config.py", line 220, in validate_section
    raise ConfigFormatError(e, data)
spack.config.ConfigFormatError: /home/kellyt/.spack/modules.yaml:11: Additional properties are not allowed ('enable:' was unexpected)
```

Ref: [modules.yaml.txt](https://github.com/LLNL/spack/files/586223/modules.yaml.txt)

What am I doing wrong?

**Comment by adamjstewart** [comment]
@alalazo

**Comment by alalazo** [comment]
@KineticTheory I am sorry but I cannot reproduce your issue neither on `ubuntu14` nor on `rhel6`. I used your exact same `modules.yaml` and just changed the version of `gcc` accordingly (`gcc@4.8` for the former, `gcc@4.4.7` for the latter). 

The stacktrace you posted seems to point to the fact that "somehow" the configuration mechanism of spack didn't take care of the double colon, which is strange. Are you using the latest version of `LLNL/develop` or an older one?

The one I used to try reproduce the issue is : 09470ec672a27a87a75c127d0c13a9945861da4a

Without any `modules.yaml`:
```console
$ spack module refresh --help
usage: spack module refresh [-h] [--delete-tree] [-m {tcl,dotkit}] [-y]
                            [constraint [constraint ...]]

positional arguments:
  constraint            Constraint to select a subset of installed packages

optional arguments:
  -h, --help            show this help message and exit
  --delete-tree         Delete the module file tree before refresh
  -m {tcl,dotkit}, --module-type {tcl,dotkit}
                        Type of module files
  -y, --yes-to-all      Assume "yes" is the answer to every confirmation
                        request.
```
Notice the `{tcl,dotkit}` above. With a `modules.yaml` containing `enable:` (single colon):
```console
$ spack module refresh --help
usage: spack module refresh [-h] [--delete-tree] [-m {tcl,lmod,dotkit}] [-y]
                            [constraint [constraint ...]]

positional arguments:
  constraint            Constraint to select a subset of installed packages

optional arguments:
  -h, --help            show this help message and exit
  --delete-tree         Delete the module file tree before refresh
  -m {tcl,lmod,dotkit}, --module-type {tcl,lmod,dotkit}
                        Type of module files
  -y, --yes-to-all      Assume "yes" is the answer to every confirmation
                        request.
```
With `enable::` (double colons):
```console
$ spack module refresh --help
usage: spack module refresh [-h] [--delete-tree] [-m {lmod}] [-y]
                            [constraint [constraint ...]]

positional arguments:
  constraint            Constraint to select a subset of installed packages

optional arguments:
  -h, --help            show this help message and exit
  --delete-tree         Delete the module file tree before refresh
  -m {lmod}, --module-type {lmod}
                        Type of module files
  -y, --yes-to-all      Assume "yes" is the answer to every confirmation
                        request.

```

**Comment by KineticTheory** [comment]
@alalazo Thanks for the detailed reply.  My working branch didn't have all of the required pieces.  The clue you provided (09470ec), convinced me to merge today's develop branch into my working branch.  This got me past the double colon issue.  Thank you!
