### ISSUE TITLE
Installation issue: Matlab R2019b

### ISSUE THREAD

**Issue by skylerpaulus** [LLNL/spack#23177]
### Steps to reproduce the issue

```console
$ spack install matlab@R2019b
==> Installing matlab-R2019b-xeapofx44ssc5xa4qkrtnxvxhj3lhezy
==> No binary for matlab-R2019b-xeapofx44ssc5xa4qkrtnxvxhj3lhezy found: installing from source
==> Error: FetchError: Manual download is required for matlab. Refer to https://www.mathworks.com/products/matlab.html for download instructions.

/opt/ohpc/pub/spack/lib/spack/spack/package.py:1369, in do_fetch:
       1366
       1367        self.stage.create()
       1368        err_msg = None if not self.manual_download else self.download_instr
  >>   1369        start_time = time.time()
       1370        self.stage.fetch(mirror_only, err_msg=err_msg)
       1371        self._fetch_time = time.time() - start_time
       1372


...
```

### Information on your system

I have the zip file for matlab: matlab_R2019b_glnxa64.zip located in /mnt/beegfs/home/spack (Created the user spack to handle everything related to spack) 

* **Spack:** 0.16.1-2318-fa06dbb
* **Python:** 3.6.8
* **Platform:** linux-centos7-ivybridge
* **Concretizer:** original

### Additional information

Build files where not created. 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cessenat** [comment]
Maybe you can try with
$ spack -d install -v matlab@R2019b
to get full log of what happens, but also did you put your downloaded file in
$SPACK_ROOT/var/spack/cache/matlab/matlab_R2019b.zip ?
There are more hints at
http://spack.readthedocs.io/en/latest/mirrors.html

**Comment by npf** [comment]
Hello, I'm following up on this issue since I'm also trying to install Matlab R2019b without success.

After placing `matlab_R2019b_glnxa64.zip` in my mirror in `matlab/matlab-R2019b.zip`, and running `spack install matlab mode=automated key=<my installation key>`, everything looks fine: checksum is ok, and the Matlab Installer GUI operations are indeed automated. But it stops at the selection of products to install. Only the "Network License Manager 11.16.2.1" is provided and it is not automatically selected.

When I select it and click "next", the GUI installer complete its duty, but spack finally reports an error: `spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/bin/glnxa64` is not found. Debug output below.

Unpacking the zipfile manually, it indeed seems to not provide the matlab tool itself, but sha256sum is ok, so I don't understand what's wrong.

Does anybody actually succeed in installing matlab R2019b with Spack ? Or any newer versions ? (R2019b is sadly the latest checksumed version if Spack's `matlab/package.py`)

```
==> [2022-02-23-17:44:05.262857] '/usr/bin/unzip' '-q' '/tmp/npf/spack-stage/spack-stage-matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/matlab_R2019b_glnxa64.zip'
==> [2022-02-23-17:44:07.465740] Created stage in /tmp/npf/spack-stage/spack-stage-matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe
==> [2022-02-23-17:44:07.466090] No patches needed for matlab
==> [2022-02-23-17:44:07.466156] matlab: Building matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe [Package]
==> [2022-02-23-17:44:07.466655] Found already existing license /home/npf/scm/spack/etc/spack/licenses/matlab/license.dat
==> [2022-02-23-17:44:07.479745] matlab: Executing phase: 'configure'
==> [2022-02-23-17:44:07.507999] matlab: Executing phase: 'install'
Preparing installation files ...
Installing ...
Finished
==> [2022-02-23-17:45:55.701190] Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/npf/scm/spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/bin/glnxa64'

/home/npf/scm/spack/var/spack/repos/builtin/packages/matlab/package.py:86, in post_install:
         84    def post_install(self):
         85        # Fix broken link
  >>     86        with working_dir(self.spec.prefix.bin.glnxa64):
         87            os.unlink('libSDL2.so')
         88            os.symlink('libSDL2-2.0.so.0.2.1', 'libSDL2.so')
         89

See build log for details:
  /tmp/npf/spack-stage/spack-stage-matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/spack-build-out.txt

Traceback (most recent call last):
  File "/home/npf/scm/spack/lib/spack/spack/build_environment.py", line 1045, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/npf/scm/spack/lib/spack/spack/installer.py", line 2011, in build_process
    return installer.run()
  File "/home/npf/scm/spack/lib/spack/spack/installer.py", line 1865, in run
    self._real_install()
  File "/home/npf/scm/spack/lib/spack/spack/installer.py", line 1972, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/home/npf/scm/spack/lib/spack/spack/package.py", line 138, in phase_wrapper
    callback(instance)
  File "/home/npf/scm/spack/var/spack/repos/builtin/packages/matlab/package.py", line 87, in post_install
    os.unlink('libSDL2.so')
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/npf/scm/spack/lib/spack/llnl/util/filesystem.py", line 648, in working_dir
    os.chdir(dirname)
FileNotFoundError: [Errno 2] No such file or directory: '/home/npf/scm/spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/bin/glnxa64'
==> [2022-02-23-17:45:55.701646] Flagging matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe as failed: FileNotFoundError: [Errno 2] No such file or directory: '/home/npf/scm/spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/bin/glnxa64'
==> [2022-02-23-17:45:55.708118] ChildError: FileNotFoundError: [Errno 2] No such file or directory: '/home/npf/scm/spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/matlab-R2019b-rhwszdvzifeml25s3zk3wji3nrvxbzwe/bin/glnxa64'
``` 

* **Spack:** 0.17.1-1176-c8c72877df
* **Python:** 3.7.3
* **Platform:** linux-debian10-skylake
* **Concretizer:** clingo

Sadly, `$ spack maintainers matlab` returns void.
Gently notifying committers of the `matlab/package.py` file: @adamjstewart @antoniokaust @DDevHan.
Thanks.

**Comment by antoniokaust** [comment]
@npf I think we (KAUST) were only able to automatically install MATLAB R2016b. So we started using `spack install matlab@Rxxxx{a|b} mode=interactive` to install it. This fires up MATLAB's GUI installer, you have to login with your MathWorks credentials then select all the components you want to install based on your license.

The error you're getting is because `post_install` gets called even if `install` failed. I could patch it if someone points me in the right direction, i.e. how to run it only if `install` runs successfully.

**Comment by npf** [comment]
Hello, thanks for the info. My last findings with 2019b:

- I can install with the spack mechanism (using Matlab's zip installer package) if and only if I provide my Matlab login/password: all Matlab products are offered then downloaded and installed
- I can install using the file installation key if using the installer from the Matlab ISO: all products are also offered and installed (no download required because all included in the ISO). But spack does not use the ISO, right ?
- It looks like I should maybe download Matlab's products before running the zip installer (possibly with spack), but I can't figure out how to do that... (there is an option for that in Matlab's 2022a zip installer, but it is disabled for me...)

So my conclusion is that Matlab installation with spack is broken for 2019b and more recent versions are not offered (no checksum). Since nobody maintains that Matlab spack package, I'm wondering if not better to remove the package from the spack release, so that nobody places any false hope in using it ;-).

**Comment by npf** [comment]
Ok, here are my last findings about matlab:
- 2019b: indeed as suggest by @antoniokaust, I can install with spack in interactive mode using my matlab user/password instead of a file installation key. To bad file installation key does not work, thus not allowing unattended install.
- 2022a: the installer seems to have changed a lot:
  - It seems to first require matlab products to be downloaded for offline install. This is to be done using the installer GUI, which unfortunately does not seem to very friendly to spack.
  - Then the installer_input.txt file must provide relevant information, among them `file installation key` and `products` to install (uncomment lines). 

BTW: I started to patch matlab/package.py to remove fixes that are not relevant with matlab 2022a:
```
diff --git a/var/spack/repos/builtin/packages/matlab/package.py b/var/spack/repos/builtin/packages/matlab/package.py
index 17cfe0e46a..daabceb5b9 100644
--- a/var/spack/repos/builtin/packages/matlab/package.py
+++ b/var/spack/repos/builtin/packages/matlab/package.py
@@ -26,6 +26,7 @@ class Matlab(Package):
     homepage = "https://www.mathworks.com/products/matlab.html"
     manual_download = True
 
+    version('R2022a', sha256='d80b8144d16181750c8320bfe41ef7cc92a2d8f4fbefd653d3d36ec5413afba7')
     version('R2019b', sha256='d60787263afb810283b7820c4c8d9cb1f854c7cb80f47e136643fd95bf5fbd59')
     version('R2018b', sha256='8cfcddd3878d3a69371c4e838773bcabf12aaf0362cc2e1ae7e8820845635cac')
     version('R2016b', sha256='a3121057b1905b132e5741de9f7f8350378592d84c5525faf3ec571620a336f2')
@@ -82,13 +83,14 @@ def install(self, spec, prefix):
 
     @run_after('install')
     def post_install(self):
-        # Fix broken link
-        with working_dir(self.spec.prefix.bin.glnxa64):
-            os.unlink('libSDL2.so')
-            os.symlink('libSDL2-2.0.so.0.2.1', 'libSDL2.so')
-
-        # Fix to random exceptions when changing display settings
-        # https://www.mathworks.com/matlabcentral/answers/373897-external-monitor-throws-java-exception
-        java_opts = os.path.join(self.spec.prefix.bin.glnxa64, 'java.opts')
-        with open(java_opts, 'w') as out:
-            out.write('-Dsun.java2d.xrender=false\n')
+        if not "@R2022a" in self.spec:
+            # Fix broken link
+            with working_dir(self.spec.prefix.bin.glnxa64):
+                os.unlink('libSDL2.so')
+                os.symlink('libSDL2-2.0.so.0.2.1', 'libSDL2.so')
+
+            # Fix to random exceptions when changing display settings
+            # https://www.mathworks.com/matlabcentral/answers/373897-external-monitor-throws-java-exception
+            java_opts = os.path.join(self.spec.prefix.bin.glnxa64, 'java.opts')
+            with open(java_opts, 'w') as out:
+                out.write('-Dsun.java2d.xrender=false\n')
```

**Comment by rkevk** [comment]
@npf I second the changes to `package.py`, since at least the first of those old fixes actually breaks the build process for matlab R2022a. The fixes should only be applied version-dependently; however, I don't know which versions do and which ones don't require the fixes.

**Comment by dacolombo** [comment]
Hi all,
I have managed to get the installation of Matlab working in an automated way (without the GUI), but using the [Matlab Package Manager (MPM)](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md) as it was suggested to me by the Matlab support. This would make the installation through spack simpler but also probably break reproducibility with previous versions, since the oldest Matlab version that can be installed with MPM is R2017b.
Apparently it would be possible to use the "silent" mode of installation by following the guide at [this link](https://it.mathworks.com/matlabcentral/answers/259632-how-can-i-get-matlab-installation-files-for-use-on-an-offline-machine) in Matlab forum, but I couldn't get it to work.

I have made a gist with the [package.py](https://gist.github.com/dacolombo/f847251657545d8fd351bd16ca8d8739) and the [file](https://gist.github.com/dacolombo/7d3f156cfb06cd3902281f9fccecfc7c) it uses to get a list of all the products installable just to present the possible solution using MPM.

I wanted to make a PR with the new package.py using MPM, but since this would break the compatibility with older version of Matlab maybe it's better to discuss it previously? Would it be better to make another package that uses MPM (e.g. named matlab-mpm)? Or is it ok to replace this implementation and discard versions older than R2017b?

**Comment by antoniokaust** [comment]
I like @dacolombo's idea to use MPM. I think it's OK to drop versions previous to R2017b.

Your GIST code looks ready. Did you test it? I saw you dropped the licensing bits, was a license installed in your destination folder?

**Comment by dacolombo** [comment]
Yes I tested it with R2022b and it works. I haven't tested it with previous versions yet.

To complete the installation with a valid license, it's enough to create the `licenses` directory in the prefix folder and put there the license file (that's what is done at the end of the install function). I have used the variant `license` to specify the path to that file.
