### ISSUE TITLE
building a "large" number of packages in environment fails with file descriptor error

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#23208]
I am currently building out a new software stack for our site, with a few different microarchitecture targets. I run `spack clean --all` before each target build. At some point, during the build of any target architecture, a failure will occur. At first the messages were lock related but it seemed related to the number of open files. I did not capture the exact message. I then bumped the limit for the number of open files and then get the following:
```
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/opt/packages/gpjohnsn/argon_stack/spack/lib/spack/llnl/util/tty/log.py", line 747, in _writer_daemon
    rlist, _, _ = _retry(select.select)(istreams, [], [], 1e-1)
  File "/opt/packages/gpjohnsn/argon_stack/spack/lib/spack/llnl/util/tty/log.py", line 830, in wrapped
    return function(*args, **kwargs)
ValueError: filedescriptor out of range in select()
==> Error: ProcessError: Command exited with status 1:
```

Since `select()` is limited to monitoring 1024 descriptors the error makes sense, although I am wondering why so many are open. To sum up, it was initially running out of file descriptors and failing. Ensuring more open files are possible then leads to an out of range, >1024, error in select(). It seems that files are not getting closed.

### Steps to reproduce the issue
Install a large number of packages in an environment. In my case, 1268 packages.
### Information on your system
* **Spack:** 0.16.1-2153-8d52200
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Likely fixed by #24794
