### ISSUE TITLE
CI pipeline fails while creating buildcache for go@1.16.2

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#23227]
I am unable to use the `spack ci` pipeline to create a buildcache for go@1.16.2.  I *am* able to create a buildcache from the command line.

The failure that is reported in `pipeline_log.txt` from the job's artifact is:

```
[...]
==> [2021-04-23-18:10:03.363732] Buildcache files will be output to file:///local_scratch/george.hartzell/tmp/spack_mirror/build_cache
Traceback (most recent call last):
  File "/opt/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/opt/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/ci.py", line 454, in ci
    args.func(args)
  File "/opt/spack/lib/spack/spack/cmd/ci.py", line 420, in ci_rebuild
    cdash_build_id, sign_binaries)
  File "/opt/spack/lib/spack/spack/ci.py", line 1319, in push_mirror_contents
    raise inst
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 158: ordinal not in range(128)
```

### Steps to reproduce the issue

I am currently unable to run `spack ci` pipelines using the standard images or local images built from the spack `develop` branch, see the [discussion](https://github.com/spack/spack/issues/20005#issuecomment-823676726) in #20005.

I am able to recreated it (and did for this bug report) by building an image using a Docker image using the `share/spack/docker/centos-7.dockerfile` Dockerfile and a copy of the Spack repo's develop branch with @alalazo's [patch for the problem](https://github.com/alalazo/spack/commit/a818dcc20f5e7b2b843d2be6afa9b7e1750ebb6b) applied.

From there, I have this `spack.yaml`:

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  specs:
    - go
  view: true
  mirrors:
    gh_tmp: /local_scratch/george.hartzell/tmp/spack_mirror
  gitlab-ci:
    image:
      name: gitlab.foo.com:5050/compeng/spack/containerize/vanilla-build-image:test-alalazo-ci-fix
      entrypoint: ["spack-env"]
    tags:
    - compeng-pete-large
    mappings:
    - match:
      - os=centos7
    enable-artifacts-buildcache: true
    script:
    - spack env activate --without-view .
    - spack -d ci rebuild
    service-job-attributes:
      tags:
      - compeng-pete-large
      image:
        name: gitlab.foo.com:5050/compeng/spack/containerize/vanilla-build-image:test-alalazo-ci-fix
        entrypoint: ["spack-env"]
```

and this `.gitlab-ci.yml`:

```yaml
default:
  image:
    name: gitlab.foo.com:5050/compeng/spack/containerize/vanilla-build-image:test-alalazo-ci-fix
    entrypoint: ["spack-env"]

stages: [generate, build]

generate-pipeline:
  stage: generate
  tags:
    - compeng-pete-large
  script:
    - spack env activate --without-view .
    - spack ci generate
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
```

### Error Message

The failure that is reported in `pipeline_log.txt` from the pipeline's final job's artifact is:

```
[...]
==> [2021-04-23-18:10:03.363732] Buildcache files will be output to file:///local_scratch/george.hartzell/tmp/spack_mirror/build_cache
Traceback (most recent call last):
  File "/opt/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/opt/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/ci.py", line 454, in ci
    args.func(args)
  File "/opt/spack/lib/spack/spack/cmd/ci.py", line 420, in ci_rebuild
    cdash_build_id, sign_binaries)
  File "/opt/spack/lib/spack/spack/ci.py", line 1319, in push_mirror_contents
    raise inst
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 158: ordinal not in range(128)
```

### Information on your system

From the container described above:

```
% docker run  -it --rm gitlab.foo.com:5050/compeng/spack/containerize/vanilla-build-image:test-alalazo-ci-fix
[root@57d1a8df5611 ~]# spack debug report
* **Spack:** 0.16.1
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by hartzell** [comment]
FYI @scottwittenburg, @alalazo

**Comment by hartzell** [comment]
FWIW, the problem may be due to trying to UTF-8 encode something that's already encoded, see [this disucssion](https://stackoverflow.com/a/24475405/11542197).

**Comment by scottwittenburg** [comment]
This looks familar to me.  I think maybe @shahzebsiddiqui or @adityakavalur may have seen this before, but I don't know how they eventually got around it, or if it's still affecting them.   

Either way, I'll take a look, thanks for reporting.

**Comment by adityakavalur** [comment]
I think the issue we had on Cori were related to path length, although @eugeneswalker might know better.

**Comment by alalazo** [comment]
@hartzell Is this still a relevant issue?

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if this is still considered relevant.
