### ISSUE TITLE
ruby-hpricot 0.8.6: rhel8 build fails: failed to build gem native extension

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#23349]
`ruby-hpricot@0.8.6` fails to build using:
* spack@develop (c27c70acd9b03084bfcf2a07cf6270fcf350e75d from `Thu Apr 29 15:24:47 2021 -0400`)
* RHEL 8 - GCC 8.3.1 (x86_64)

Note: not seeing this error on Ubuntu 20.04 w/ GCC 9.3.0

Container: `ecpe4s/rhel8-runner-x86_64:2021-03-01`
Concrete spec: [ruby-hpricot-3zgnes.spec.yaml.txt](https://github.com/spack/spack/files/6401484/ruby-hpricot-3zgnes.spec.yaml.txt)
Build log: [ruby-hpricot-build-out.txt](https://github.com/spack/spack/files/6401487/ruby-hpricot-build-out.txt)

```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --only dependencies --include-build-deps -f ./ruby-hpricot-3zgnes.spec.yaml
... OK

$> spack install --no-cache -f ./ruby-hpricot-3zgnes.spec.yaml
...
==> Installing ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/79/792f63cebe2f2b02058974755b4c8a3aef52e5daf37f779a34885d5ff2876017.tar.gz
==> No patches needed for ruby-hpricot
==> ruby-hpricot: Executing phase: 'build'
==> ruby-hpricot: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/bin/gem' 'install' '--norc' '--ignore-dependencies' 'hpricot-0.8.6.gem'

3 warnings found in build log:
  >> 5    WARNING:  licenses is empty, but is recommended.  Use a license identifier from
     6    http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
  >> 7    WARNING:  description and summary are identical
  >> 8    WARNING:  See https://guides.rubygems.org/specification-reference/ for help
     9      Successfully built RubyGem
     10     Name: hpricot
     11     Version: 0.8.6
     12     File: hpricot-0.8.6.gem
     13   ==> ruby-hpricot: Executing phase: 'install'
     14   ==> [2021-04-29-20:30:21.445363] '/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/bin/gem' 'install' '--norc' '--ig
          nore-dependencies' 'hpricot-0.8.6.gem'

See build log for details:
  /tmp/root/spack-stage/spack-stage-ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f/spack-build-out.txt
```

Relevant excerpt from full build log:
```
  Successfully built RubyGem
  Name: hpricot
  Version: 0.8.6
  File: hpricot-0.8.6.gem
==> ruby-hpricot: Executing phase: 'install'
==> [2021-04-29-20:30:21.445363] '/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/bin/gem' 'install' '--norc' '--ignore-dependencies' 'hpricot-0.8.6.gem'
Building native extensions. This could take a while...
ERROR:  Error installing hpricot-0.8.6.gem:
	ERROR: Failed to build gem native extension.

    current directory: /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f/gems/hpricot-0.8.6/ext/fast_xs
/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/bin/ruby -I /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0 -r ./siteconf20210429-2378-hbcj1e.rb extconf.rb
checking for stdio.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/bin/$(RUBY_BASE_NAME)
	--with-stdio-dir
	--without-stdio-dir
	--with-stdio-include
	--without-stdio-include=${stdio-dir}/include
	--with-stdio-lib
	--without-stdio-lib=${stdio-dir}/lib
/opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:613:in `try_cpp'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:1124:in `block in have_header'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:971:in `block in checking_for'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:331:in `open'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:970:in `checking_for'
	from /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-3.0.0-kspsemtwugyytk7ytmopwctj32k4ty37/lib/ruby/3.0.0/mkmf.rb:1123:in `have_header'
	from extconf.rb:2:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f/extensions/x86_64-linux/3.0.0-static/hpricot-0.8.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f/gems/hpricot-0.8.6 for inspection.
Results logged to /opt/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/ruby-hpricot-0.8.6-3zgnesyfmrm7ym6764boo4oatx6bth6f/extensions/x86_64-linux/3.0.0-static/hpricot-0.8.6/gem_make.out
```

@adamjstewart - just pinging you because you added the package and maybe you know what this means? From a google search it looks like this error comes up frequently on MacOS but I couldn't find much on RHEL 8 etiology.

**Comment by adamjstewart** [comment]
No idea, sorry
