### ISSUE TITLE
CCE doesn't support CXX standard flags beyond 11

### ISSUE THREAD

**Issue by jjellio** [LLNL/spack#23443]
### Error Message
```
==> [2021-05-05-04:48:15.627507] [TOOLCHAIN] MATCH Cce
==> [2021-05-05-04:48:15.641747] Error: UnsupportedCompilerFlag: cce (12.0) does not support the C++14 standard (as compiler.cxx14_flag).
    If you think it should, please edit the compiler.cce subclass to implement the cxx14_flag property and submit a pull request or issue.

/home/users/coe0201/src/spack/var/spack/repos/builtin/packages/icu4c/package.py:55, in flag_handler:
         52        if name == 'cxxflags':
         53            # Control of the C++ Standard is via adding the required "-std"
         54            # flag to CXXFLAGS in env
  >>     55            flags.append(getattr(self.compiler,
         56                         'cxx{0}_flag'.format(
         57                             self.spec.variants['cxxstd'].value)))
         58        return (None, flags, None)


Traceback (most recent call last):
  File "/home/users/coe0201/src/spack/lib/spack/spack/build_environment.py", line 912, in _setup_pkg_and_run
    setup_package(pkg, dirty=kwargs.get('dirty', False),
  File "/home/users/coe0201/src/spack/lib/spack/spack/build_environment.py", line 793, in setup_package
    set_compiler_environment_variables(pkg, env)
  File "/home/users/coe0201/src/spack/lib/spack/spack/build_environment.py", line 283, in set_compiler_environment_variables
    injf, envf, bsf = handler(pkg, flag, spec.compiler_flags[flag])
  File "/home/users/coe0201/src/spack/var/spack/repos/builtin/packages/icu4c/package.py", line 56, in flag_handler
    'cxx{0}_flag'.format(
  File "/home/users/coe0201/src/spack/lib/spack/spack/compiler.py", line 457, in cxx14_flag
    raise UnsupportedCompilerFlag(self,
spack.compiler.UnsupportedCompilerFlag: cce (12.0) does not support the C++14 standard (as compiler.cxx14_flag).
    If you think it should, please edit the compiler.cce subclass to implement the cxx14_flag property and submit a pull request or issue.
==> [2021-05-05-04:48:15.642110] Flagging icu4c-67.1-u4rpmlv5bmrkgmccepnlpejhyh36i4mi as failed: UnsupportedCompilerFlag: cce (12.0) does not support the C++14 standard (as compiler.cxx14_flag).
    If you think it should, please edit the compiler.cce subclass to implement the cxx14_flag property and submit a pull request or issue.
```

Glancing at `compilers/cce.py`, it only annotates C++11 - curiously, I never bumped into this, because Trilinos sets its own CXX flags via kokkos.

### compilers/cce.py
```yaml
    @property
    def cxx11_flag(self):
        if self.is_clang_based:
            return '-std=c++11'
        return "-h std=c++11"

    # no more c++ standards!
    # a very sad day  indeed
```
I'll be submitting a PR that adds flags (and referencing this)

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
See #24127 #35469
