### ISSUE TITLE
Installation issue: cp2k cxxflags JSONDecodeError

### ISSUE THREAD

**Issue by heaton-dev** [LLNL/spack#23570]
### Steps to reproduce the issue

```console
==> [2021-05-11-18:29:56.240127] No patches needed for cp2k
==> [2021-05-11-18:29:56.240313] cp2k: Building cp2k-8.1-youn4j57zf4fp67traiy57umgyz6t2e2 [MakefilePackage]
==> [2021-05-11-18:29:56.264231] cp2k: Executing phase: 'edit'
==> [2021-05-11-18:29:56.533192] Error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/lustre/software/aarch64/spack/var/spack/repos/builtin/packages/cp2k/package.py:300, in edit:
        297            ldflags  += ['-hnoomp']
        298
        299        if '@7:' in spec:  # recent versions of CP2K use C++14 CUDA code
  >>    300            cxxflags.append(self.compiler.cxx14_flag)
        301            nvflags.append(self.compiler.cxx14_flag)
        302
        303        ldflags.append(fftw.libs.search_flags)

See build log for details:
  /var/tmp/415400605.28jzaVCdwZ/br-jheaton/spack-stage/spack-stage-cp2k-8.1-youn4j57zf4fp67traiy57umgyz6t2e2/spack-build-out.txt

Traceback (most recent call last):
  File "/lustre/software/aarch64/spack/lib/spack/spack/build_environment.py", line 914, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/lustre/software/aarch64/spack/lib/spack/spack/installer.py", line 1776, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/lustre/software/aarch64/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
    phase(spec, prefix)
  File "/lustre/software/aarch64/spack/var/spack/repos/builtin/packages/cp2k/package.py", line 301, in edit
    nvflags.append(self.compiler.cxx14_flag)
  File "/lustre/software/aarch64/spack/lib/spack/spack/compilers/gcc.py", line 76, in cxx14_flag
    if self.real_version < ver('4.8'):
  File "/lustre/software/aarch64/spack/lib/spack/spack/compiler.py", line 349, in real_version
    self.get_real_version())
  File "/lustre/software/aarch64/spack/lib/spack/spack/compiler.py", line 525, in get_real_version
    with self._compiler_environment():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/lustre/software/aarch64/spack/lib/spack/spack/compiler.py", line 610, in _compiler_environment
    spack.util.module_cmd.load_module(module)
  File "/lustre/software/aarch64/spack/lib/spack/spack/util/module_cmd.py", line 105, in load_module
    module('unload', text[i + 1])
  File "/lustre/software/aarch64/spack/lib/spack/spack/util/module_cmd.py", line 72, in module
    env_dict = json.loads(env_json)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
==> [2021-05-11-18:29:56.533690] Flagging cp2k-8.1-youn4j57zf4fp67traiy57umgyz6t2e2 as failed: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
==> [2021-05-11-18:29:56.569692] ChildError: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...
```

### Information on your system

* **Spack:** 0.16.1-2582-fee5cf4e49
* **Python:** 3.6.10
* **Platform:** cray-sles15-thunderx2
* **Concretizer:** original

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/6461328/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6461329/spack-build-out.txt)

Installed with following command:

```
spack install cp2k@8.1 +openmp +mpi +plumed %gcc@9.3.0 smm=blas ^fftw +openmp ^openblas threads=openmp
```

Not sure why the error is being encountered since I've requested version 8.1 and the errant code seems to be for version 7?

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers @dev-zero 
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by dev-zero** [comment]
`@7:` is a version range to apply the code which follows for v7 and newer of CP2K.
But this is not really CP2K related, rather an error which occurs when parsing the output of a `module` command which is supposed to be JSON. Can you verify that the `module` you specified for the used compiler (check in `~/.spack/cray/compilers.yaml`) actually returns something valid for `module show ...`?
Btw, when building on ARM you may want to use ARM blas/lapack libraries, they should also work together with gcc (or there is usually a variant which does).

**Comment by heaton-dev** [comment]
I'll try the Arm libraries once I get this version to build 🙂

Module is fine:

```
> module show gcc/9.3.0
-------------------------------------------------------------------
/opt/modulefiles/gcc/9.3.0:

conflict         gcc
conflict         gcc-cross-aarch64
prepend-path     PATH /opt/gcc/9.3.0/bin
prepend-path     MANPATH /opt/gcc/9.3.0/snos/share/man
prepend-path     INFOPATH /opt/gcc/9.3.0/snos/share/info
prepend-path     LD_LIBRARY_PATH /opt/gcc/9.3.0/snos/lib64
setenv           GCC_PATH /opt/gcc/9.3.0
setenv           GCC_PREFIX /opt/gcc/9.3.0
setenv           GCC_VERSION 9.3.0
setenv           GNU_VERSION 9.3.0
-------------------------------------------------------------------
```

Seems I have two gcc@9.3.0 entries in `~/.spack/cray/compilers.yaml`, I even regenerated it by deleting the file and running `spack compiler find`.

excerpts:
```
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: cnl7
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/9.3.0
    environment: {}
    extra_rpaths: []

- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /opt/gcc/9.3.0/bin/gcc
      cxx: /opt/gcc/9.3.0/bin/g++
      f77: /opt/gcc/9.3.0/bin/gfortran
      fc: /opt/gcc/9.3.0/bin/gfortran
    flags: {}
    operating_system: sles15
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by heaton-dev** [comment]
I'll close this as it's not directly related to this package
