### ISSUE TITLE
Execute sentencepiece.py to report a error `cannot allocate memory in static TLS block`

### ISSUE THREAD

**Issue by simon28li** [LLNL/spack#23614]
### Steps to reproduce the issue

```console
$ spack install py-sentencepiece
$ cd $sentencepiece.py_dir
$ spack load py-sentencepiece
$ python sentencepiece.py
```

### Error Message

```console
[root@localhost site-packages]# python sentencepiece.py
Traceback (most recent call last):
  File "sentencepiece.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.8-jf6wr2bynimrvwful46fubsy53ikimhv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/gperftools-2.9.1-iwl7mtpvkogc3s6p7d45zmbixaccarb5/lib/libtcmalloc_minimal.so.4: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sentencepiece.py", line 21, in <module>
    _sentencepiece = swig_import_helper()
  File "sentencepiece.py", line 20, in swig_import_helper
    return importlib.import_module('_sentencepiece')
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.8-jf6wr2bynimrvwful46fubsy53ikimhv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/gperftools-2.9.1-iwl7mtpvkogc3s6p7d45zmbixaccarb5/lib/libtcmalloc_minimal.so.4: cannot allocate memory in static TLS block
```

### Information on your system

```console
* **Spack:** 0.16.1
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original
```

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

@adamjstewart Can you help me to see if it is the software itself or my own system? Thanks a lot.

**Comment by simon28li** [comment]
In addition, I would not have made this mistake if I removed the gperftools, that Sentencepiece depended on.

**Comment by adamjstewart** [comment]
I'm unable to reproduce this on macOS so I'm not sure how much help I can be. You might want to contact the sentencepiece developers.
