### ISSUE TITLE
Spack aborts no matter what the command is after git merge upstream/develop

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#2362]
Hi all,

I wanted to run with the latest spack code so I updated,  but now I can't do anything with spack.
I tried moving my $HOME/.spack files out of the way, but it didn't make a difference.
Does anyone have any insight into this?

Thanks,
Jim G

git fetch upstream

git merge upstream/develop

jeg@localhost spack]$ which spack
~/spack/bin/spack
[jeg@localhost spack]$ echo $SPACK_ROOT
/home/jeg/spack

[jeg@localhost spack]$ spack install cbtf
Traceback (most recent call last):
  File "/home/jeg/spack/bin/spack", line 99, in <module>
    import spack
  File "/home/jeg/spack/lib/spack/spack/__init__.py", line 74, in <module>
    import spack.repository
  File "/home/jeg/spack/lib/spack/spack/repository.py", line 45, in <module>
    import spack.spec
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 114, in <module>
    import spack.store
  File "/home/jeg/spack/lib/spack/spack/store.py", line 47, in <module>
    import spack.config
  File "/home/jeg/spack/lib/spack/spack/config.py", line 208, in <module>
    _platform = spack.architecture.platform().name
  File "/home/jeg/spack/lib/spack/llnl/util/lang.py", line 187, in __call__
    self.cache[args] = self.func(*args)
  File "/home/jeg/spack/lib/spack/spack/architecture.py", line 530, in platform
    return platform_cls()
  File "/home/jeg/spack/lib/spack/spack/platforms/linux.py", line 21, in __init__
    linux_dist = LinuxDistro()
  File "/home/jeg/spack/lib/spack/spack/operating_systems/linux_distro.py", line 16, in __init__
    from external.distro import linux_distribution
  File "/home/jeg/spack/lib/spack/external/distro.py", line 1049, in <module>
    _distroi = LinuxDistribution()
  File "/home/jeg/spack/lib/spack/external/distro.py", line 595, in __init__
    if include_lsb else {}
  File "/home/jeg/spack/lib/spack/external/distro.py", line 921, in _lsb_release_info
    out, err = out.decode('ascii'), err.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 250: ordinal not in range(128)

[jeg@localhost spack]$ spack uninstall papi
Traceback (most recent call last):
  File "/home/jeg/spack/bin/spack", line 99, in <module>
    import spack
  File "/home/jeg/spack/lib/spack/spack/__init__.py", line 74, in <module>
    import spack.repository
  File "/home/jeg/spack/lib/spack/spack/repository.py", line 45, in <module>
    import spack.spec
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 114, in <module>
    import spack.store
  File "/home/jeg/spack/lib/spack/spack/store.py", line 47, in <module>
    import spack.config
  File "/home/jeg/spack/lib/spack/spack/config.py", line 208, in <module>
    _platform = spack.architecture.platform().name
  File "/home/jeg/spack/lib/spack/llnl/util/lang.py", line 187, in __call__
    self.cache[args] = self.func(*args)
  File "/home/jeg/spack/lib/spack/spack/architecture.py", line 530, in platform
    return platform_cls()
  File "/home/jeg/spack/lib/spack/spack/platforms/linux.py", line 21, in __init__
    linux_dist = LinuxDistro()
  File "/home/jeg/spack/lib/spack/spack/operating_systems/linux_distro.py", line 16, in __init__
    from external.distro import linux_distribution
  File "/home/jeg/spack/lib/spack/external/distro.py", line 1049, in <module>
    _distroi = LinuxDistribution()
  File "/home/jeg/spack/lib/spack/external/distro.py", line 595, in __init__
    if include_lsb else {}
  File "/home/jeg/spack/lib/spack/external/distro.py", line 921, in _lsb_release_info
    out, err = out.decode('ascii'), err.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 250: ordinal not in range(128)

[jeg@localhost spack]$ spack find compilers
Traceback (most recent call last):
  File "/home/jeg/spack/bin/spack", line 99, in <module>
    import spack
  File "/home/jeg/spack/lib/spack/spack/__init__.py", line 74, in <module>
    import spack.repository
  File "/home/jeg/spack/lib/spack/spack/repository.py", line 45, in <module>
    import spack.spec
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 114, in <module>
    import spack.store
  File "/home/jeg/spack/lib/spack/spack/store.py", line 47, in <module>
    import spack.config
  File "/home/jeg/spack/lib/spack/spack/config.py", line 208, in <module>
    _platform = spack.architecture.platform().name
  File "/home/jeg/spack/lib/spack/llnl/util/lang.py", line 187, in __call__
    self.cache[args] = self.func(*args)
  File "/home/jeg/spack/lib/spack/spack/architecture.py", line 530, in platform
    return platform_cls()
  File "/home/jeg/spack/lib/spack/spack/platforms/linux.py", line 21, in __init__
    linux_dist = LinuxDistro()
  File "/home/jeg/spack/lib/spack/spack/operating_systems/linux_distro.py", line 16, in __init__
    from external.distro import linux_distribution
  File "/home/jeg/spack/lib/spack/external/distro.py", line 1049, in <module>
    _distroi = LinuxDistribution()
  File "/home/jeg/spack/lib/spack/external/distro.py", line 595, in __init__
    if include_lsb else {}
  File "/home/jeg/spack/lib/spack/external/distro.py", line 921, in _lsb_release_info
    out, err = out.decode('ascii'), err.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 250: ordinal not in range(128)
[jeg@localhost spack]$ 

spack install openspeedshop
Traceback (most recent call last):
  File "/home/jeg/spack4/spack/bin/spack", line 99, in <module>
    import spack
  File "/home/jeg/spack4/spack/lib/spack/spack/__init__.py", line 74, in <module>
    import spack.repository
  File "/home/jeg/spack4/spack/lib/spack/spack/repository.py", line 45, in <module>
    import spack.spec
  File "/home/jeg/spack4/spack/lib/spack/spack/spec.py", line 114, in <module>
    import spack.store
  File "/home/jeg/spack4/spack/lib/spack/spack/store.py", line 47, in <module>
    import spack.config
  File "/home/jeg/spack4/spack/lib/spack/spack/config.py", line 208, in <module>
    _platform = spack.architecture.platform().name
  File "/home/jeg/spack4/spack/lib/spack/llnl/util/lang.py", line 187, in __call__
    self.cache[args] = self.func(*args)
  File "/home/jeg/spack4/spack/lib/spack/spack/architecture.py", line 530, in platform
    return platform_cls()
  File "/home/jeg/spack4/spack/lib/spack/spack/platforms/linux.py", line 21, in __init__
    linux_dist = LinuxDistro()
  File "/home/jeg/spack4/spack/lib/spack/spack/operating_systems/linux_distro.py", line 16, in __init__
    from external.distro import linux_distribution
  File "/home/jeg/spack4/spack/lib/spack/external/distro.py", line 1049, in <module>
    _distroi = LinuxDistribution()
  File "/home/jeg/spack4/spack/lib/spack/external/distro.py", line 595, in __init__
    if include_lsb else {}
  File "/home/jeg/spack4/spack/lib/spack/external/distro.py", line 921, in _lsb_release_info
    out, err = out.decode('ascii'), err.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 250: ordinal not in range(128)
[jeg@localhost packages]$

**Comment by adamjstewart** [comment]
What is the output of the following command?
```
$ lsb_release -a
```

**Comment by jgalarowicz** [comment]
[jeg@localhost spack]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 19 (Schrödinger’s Cat)
Release:	19
Codename:	Schrödinger’sCat
[jeg@localhost spack]$

**Comment by adamjstewart** [comment]
Ha, it must be because of `Schrödinger’sCat`. We're using the distro Python module for linux distribution detection now. I'll file an issue with the distro developers. Hopefully they can put in a quick fix.

**Comment by adamjstewart** [comment]
Issue filed at https://github.com/nir0s/distro/issues/151

**Comment by jgalarowicz** [comment]
Hi Adam,
Thanks for looking at this!
Jim G

**Comment by citibeth** [comment]
Are you sure Spack is running here with Python2?  Just a guess, and probably not the cause of the problem...

**Comment by adamjstewart** [comment]
The issue is that we are using an out-of-date version of the `distro` package. See https://github.com/nir0s/distro/issues/151 for details. I'll update the package and submit a PR shortly.
