### ISSUE TITLE
Cannot declare view in `spack.yaml` environment any more

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#23642]
### Steps to reproduce the issue

I have a `spack.yaml` file that declares an environment. This file also declares a view. This used to work fine, but gives an error today after a `git pull`.

```console
$ spack --env-dir utils/spack/redshift concretize --force
```

### Error Message

The concretization itself seems to work fine. A `spack.lock` file is created. Then there is this error:

```console
Traceback (most recent call last):
  File "/Users/eschnett/src/CarpetX/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/main.py", line 774, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/main.py", line 498, in _invoke_command
    return_val = command(parser, args)
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/cmd/concretize.py", line 38, in concretize
    env.write()
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/environment.py", line 1878, in write
    self.regenerate_views()
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/environment.py", line 1335, in regenerate_views
    view.regenerate(specs, self.roots())
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/environment.py", line 616, in regenerate
    old_root = self._current_root
  File "/Users/eschnett/src/CarpetX/spack/lib/spack/spack/environment.py", line 502, in _current_root
    root = os.readlink(self.root)
OSError: [Errno 22] Invalid argument: '/Users/eschnett/src/CarpetX/Cactus/view'
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.1-2651-fc392d2f56
* **Python:** 3.8.5
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

My `spack.yaml` file is:
```yaml
# source ../spack/share/spack/setup-env.sh
# spack --env-dir utils/spack/redshift compiler find view-compilers && spack --env-dir utils/spack/redshift concretize --force && spack --env-dir utils/spack/redshift install --fail-fast --source
spack:
  definitions:
  - compilers:
    - gcc @11.1.0
  - packages:
    - adios +bzip2
    # +shared does not work on MacOS
    - amrex ~fortran +hdf5 +openmp +particles
    - boost cxxstd=17 +mpi
    - fftw +mpi +openmp
    - googletest
    - gsl
    # +pic +shared leads to segfaults (why?)
    - hdf5 @1.10.7 +cxx +fortran +hl +mpi ~pic ~shared +threadsafe
    - hwloc
    - jemalloc
    - jpeg
    - nsimd simd=AVX2
    - openblas
    - openmpi +thread_multiple
    - openssl
    - silo @4.10.2-bsd ~fortran ~pic ~shared
    - simulationio ~python
    - ssht
    - yaml-cpp
    - zlib
  specs:
  - matrix:
    - [$%compilers]
    - [$packages]
  - cmake %apple-clang @12.0.0
  - python %apple-clang @12.0.0
  concretization: together
  view: /Users/eschnett/src/CarpetX/Cactus/view
```

**Comment by haampie** [comment]
Yeah, this was a bit bumpy, the workaround is to just delete your old view directory

**Comment by tgamblin** [comment]
@haampie do you know what caused it?

**Comment by eschnett** [comment]
I think I found the cause: Spack switched view directories from being directories to being symlinks to directories. The new code tries to change the symlink, but doesn't handle the case when an old-style directory is still there.

**Comment by alalazo** [comment]
Closing as not relevant anymore (right now all supported versions of Spack use the symlink)
