### ISSUE TITLE
Run-time issue: python+tkinter

### ISSUE THREAD

**Issue by schmitts** [LLNL/spack#23780]
The tkagg backend does not work as expected, see below with a fresh Spack at 319f20d94ff68f781b4913d236e0587dfa0195ba.

```console
$ spack install py-matplotlib backend=tkagg
$ spack load -r py-matplotlib
$ python -c "import matplotlib.pyplot as plt; plt.plot([0],[1]); plt.show()"
...
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tcl8.6/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/library
```

The variants `tk` and `tcl` itself were installed:

```console
$ spack find --loaded -v | grep -e tcl -e tk   
py-matplotlib@3.4.2~animation~fonts+image~latex~movies backend=tkagg
python@3.8.10+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix+tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87
tcl@8.6.11
tk@8.6.10+xft+xss
``` 

### General information

* **Spack:** 0.16.1-2700-319f20d94f
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-haswell
* **Concretizer:** original

**Comment by adamjstewart** [comment]
I'm unable to reproduce this on macOS, tkagg seems to work just fine.

Can you try the following test to see if this actually involves matplotlib?
```console
$ python -c 'import tkinter; import _tkinter'
```
Can you also try:
```console
$ cd /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj
$ find . -name tk.tcl
```
For me, it's in `lib/tk8.6/tk.tcl`.

**Comment by adamjstewart** [comment]
Can you follow the debugging steps listed at https://wiki.python.org/moin/TkInter? One possibility is that you are using SSH and `DISPLAY` is not set (requires `ssh -Y`).

**Comment by schmitts** [comment]
I'm not using SSH and `DISPLAY` is set:

```
echo $DISPLAY
:0
```

Imports work but the test fails:

```
Python 3.8.10 (default, May 18 2021, 20:19:06) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> import tkinter
>>> tkinter._test() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/python3.8/tkinter/__init__.py", line 4557, in _test
    root = Tk()
  File "/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tcl8.6/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/library



This probably means that tk wasn't installed properly.
```

```
for d in /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tcl8.6/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/lib/tk8.6 /home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/library; do ls $d/tk.tcl; done
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tcl8.6/tk8.6/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tcl-8.6.11-uoh3u6zmjwbky6rhfojdihz6blnk5sy5/lib/tk8.6/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/lib/tk8.6/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/lib/tk8.6/tk.tcl': No such file or directory
ls: cannot access '/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/python-3.8.10-efzidqekqhq4y4raa2q4iabetuoqdnse/library/tk.tcl': No such file or directory
```

However, I do have a `tk.tcl` in:

```
/home/sschmitt/spack-tcl/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib/tk8.6/tk.tcl
```
Which has `tk8.6` at the end more compared to the search path reported above. When I symlink the contents of `tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib/tk8.6` one level down (to `tk-8.6.10-egp4nzel66d2273p3olurpjif6bhhkmj/lib`), things seems to work.

**Comment by adamjstewart** [comment]
Alright, I am actually seeing a possibly related bug on macOS:
```python
>>> tkinter._test()
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-oteamoaswrgdgdw6jhdrn4n7acir5c73/lib/python3.8/tkinter/__init__.py", line 4557, in _test
    root = Tk()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-oteamoaswrgdgdw6jhdrn4n7acir5c73/lib/python3.8/tkinter/__init__.py", line 2272, in __init__
    self._loadtk()
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-oteamoaswrgdgdw6jhdrn4n7acir5c73/lib/python3.8/tkinter/__init__.py", line 2288, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```
So it's picking up something, just the wrong one. I'll keep investigating.

**Comment by adamjstewart** [comment]
The Python build log actually points out this issue:
```
*** WARNING: renaming "_tkinter" since importing it failed: dlopen(/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-python-3.8.10-oteamoaswrgdgdw6jhdrn4n7acir5c73/spack-src/spack-build/build/lib.macosx-10.15.7-x86_64-3.8/_tkinter.cpython-38-darwin.so, 2): Library not loaded: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tk-8.6.10-sn76ddqkq3sircg4zaiphqc6j2sthcvj/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tcl-8.6.11-n7nea33urrk25rkoqpsc2tdcgai5u4z2/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libx11-1.7.0-vcsch4cw5xcbjepmtfhkto24me356zj5/lib/libtk8.6.dylib
  Referenced from: /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-python-3.8.10-oteamoaswrgdgdw6jhdrn4n7acir5c73/spack-src/spack-build/build/lib.macosx-10.15.7-x86_64-3.8/_tkinter.cpython-38-darwin.so
  Reason: image not found

Python build finished successfully!
The necessary bits to build these optional modules were not found:
ossaudiodev           spwd
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd
time


Following modules built successfully but were removed because they could not be imported:
_tkinter
```
This can be seen on the command line too:
```console
$ otool -L lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so
lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
$ otool -L lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin_failed.so 
lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin_failed.so:
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tcl-8.6.11-n7nea33urrk25rkoqpsc2tdcgai5u4z2/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.11)
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tk-8.6.10-sn76ddqkq3sircg4zaiphqc6j2sthcvj/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tcl-8.6.11-n7nea33urrk25rkoqpsc2tdcgai5u4z2/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libx11-1.7.0-vcsch4cw5xcbjepmtfhkto24me356zj5/lib/libtk8.6.dylib (compatibility version 8.6.0, current version 8.6.10)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by adamjstewart** [comment]
Possibly a bug in the tk build?
```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tk-8.6.10-sn76ddqkq3sircg4zaiphqc6j2sthcvj/lib/libtk8.6.dylib 
/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tk-8.6.10-sn76ddqkq3sircg4zaiphqc6j2sthcvj/lib/libtk8.6.dylib:
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tk-8.6.10-sn76ddqkq3sircg4zaiphqc6j2sthcvj/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/tcl-8.6.11-n7nea33urrk25rkoqpsc2tdcgai5u4z2/lib:/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libx11-1.7.0-vcsch4cw5xcbjepmtfhkto24me356zj5/lib/libtk8.6.dylib (compatibility version 8.6.0, current version 8.6.10)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libx11-1.7.0-vcsch4cw5xcbjepmtfhkto24me356zj5/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libxscrnsaver-1.2.2-pmikcsrah6qmsqa5ydwqse245byho3rb/lib/libXss.1.dylib (compatibility version 2.0.0, current version 2.0.0, weak)
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/libxext-1.3.3-dpw3fi3s423crfns3ss37cbv66ledu2g/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/zlib-1.2.11-x2anksgssxsxa7pcnhzg5k3dhgacglze/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
```

**Comment by adamjstewart** [comment]
I wonder if this is because `tk` and `tcl` aren't designed to be installed to different directories. During installation, the `tk` configure script issues the following warning:
```
configure: WARNING:
        Different --prefix selected for Tk and Tcl!
        [package require Tk] may not work correctly in tclsh.
```
Most package managers seem to have a single package that combines both `tcl` and `tk` and installs them to the same prefix:

* [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tcl-tk.rb)
* [Macports](https://github.com/macports/macports-ports/blob/master/x11/tk/Portfile)
* [Conda](https://github.com/conda-forge/tk-feedstock/blob/master/recipe/meta.yaml)

**Comment by adamjstewart** [comment]
Okay, thanks to a patch from Macports, I've fixed the bug I encountered on macOS. Now I'm getting the same bug as you were getting. Still digging to solve that one, but I might end up symlinking things like you suggest.

**Comment by adamjstewart** [comment]
Okay, I think I'm starting to lose my mind. If I install `tk` multiple times, sometimes it installs `lib/tk8.6/tk.tcl`, sometimes it installs `lib/tk.tcl`, and sometimes it doesn't install `tk.tcl` at all. Maybe it's a parallel build bug. Testing now.

**Comment by adamjstewart** [comment]
@schmitts I'm not sure how else to debug this problem. Can you try uninstalling and reinstalling `tk` a few times on your system to see where it installs `tk.tcl`? With #23825 my installation now consistently succeeds, but that is only a patch for macOS so won't help you.

**Comment by schmitts** [comment]
I've done

```
spack uninstall  --dependents --all tcl tk
spack install tk
```

a couple of times. `tk.tcl` always ends like below:

```
sschmitt@sierra ➜  ~/spack-tcl git:(develop) find -name tk.tcl
./opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-hioelpdlpihvlnph5nzdml3whkivz3co/share/tk/src/library/tk.tcl
./opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/tk-8.6.10-hioelpdlpihvlnph5nzdml3whkivz3co/lib/tk8.6/tk.tcl
```

**Comment by adamjstewart** [comment]
Opened up an issue with the `tk` developers, let's see what they say: https://core.tcl-lang.org/tk/tktview/447bd3e4abe17452d19a80e6840dcc8a2603fcbc

Alternatively, we can open an issue with the Python developers and get tkinter to search in `<prefix>/lib/tk8.6/tk.tcl`.

**Comment by adamjstewart** [comment]
According to the tk developers, `<prefix>/lib/tk8.6/tk.tcl` is indeed the correct installation location. I opened an issue with the Python developers to see if we can get Python to look in this directory: https://bugs.python.org/issue44253
