### ISSUE TITLE
spack uninstall fails for libxml2

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#238]
spack uninstall fails for libxml2, when without python bindings.

cab687@lee218:spack uninstall libxml2                         
Traceback (most recent call last):                            
  File "/nfs/tmp2/lee218/pkg/spack3/spack/bin/spack", line 163, in <module>
    main()                                                                 
  File "/nfs/tmp2/lee218/pkg/spack3/spack/bin/spack", line 144, in main    
    return_val = command(parser, args)                                     
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/cmd/uninstall.py", line 96, in uninstall                                                              
    pkg.do_uninstall(force=args.force)                                          
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/package.py", line 932, in do_uninstall                                                                
    spack.hooks.pre_uninstall(self)                                             
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/hooks/__init__.py", line 69, in __call__                                                              
    hook(pkg)                                                                   
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/hooks/extensions.py", line 35, in pre_uninstall                                                       
    if pkg.activated:                                                           
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/package.py", line 518, in activated                                                                   
    exts = spack.install_layout.extension_map(self.extendee_spec)               
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/directory_layout.py", line 345, in extension_map                                                      
    _check_concrete(spec)                                                       
  File "/nfs/tmp2/lee218/pkg/spack3/spack/lib/spack/spack/directory_layout.py", line 44, in _check_concrete                                                     
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')     
ValueError: Specs passed to a DirectoryLayout must be concrete!

**Comment by tgamblin** [comment]
@lee218llnl: does the fix I just checked in work for you?  The database support needs to properly mark specs representing a real install as concrete, as well.
