### ISSUE TITLE
can't stage cuda / unable to parse extension

### ISSUE THREAD

**Issue by simonpintarelli** [LLNL/spack#23862]
~~spack fails to stage cuda. I can't reproduce the bug on another system, although I couldn't resolve it even with a clean git clone and deleting all custom configuration.~~

spack v0.16.2 fails to fetch cuda.

### Steps to reproduce the issue

```console
$ spack install cuda@10.2.1%gcc@10.2.0
```

### Error Message
```
lib/spack/spack/main.py:777 ==> [2021-05-23-15:46:17.296207] MirrorError: Unable to parse extension from https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.1.0_linux.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)

lib/spack/spack/error.py:55 ==> [2021-05-23-15:46:17.296368] Error: Unable to parse extension from https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.1.0_linux.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)

Traceback (most recent call last):
  File "/home/simon/spack/lib/spack/spack/main.py", line 774, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/simon/spack/lib/spack/spack/main.py", line 498, in _invoke_command
    return_val = command(parser, args)
  File "/home/simon/spack/lib/spack/spack/cmd/install.py", line 351, in install
    env.install_all(args, **kwargs)
  File "/home/simon/spack/lib/spack/spack/environment.py", line 1543, in install_all
    self.install_specs(None, args=args, **install_args)
  File "/home/simon/spack/lib/spack/spack/environment.py", line 1586, in install_specs
    builder.install()
  File "/home/simon/spack/lib/spack/spack/installer.py", line 1513, in install
    self._prepare_for_install(task)
  File "/home/simon/spack/lib/spack/spack/installer.py", line 829, in _prepare_for_install
    if restage and task.pkg.stage.managed_by_spack:
  File "/home/simon/spack/lib/spack/spack/package.py", line 1021, in stage
    self._stage = self._make_stage()
  File "/home/simon/spack/lib/spack/spack/package.py", line 998, in _make_stage
    stage = self._make_root_stage(fetcher)
  File "/home/simon/spack/lib/spack/spack/package.py", line 972, in _make_root_stage
    mirror_paths = spack.mirror.mirror_archive_paths(
  File "/home/simon/spack/lib/spack/spack/mirror.py", line 316, in mirror_archive_paths
    ext = ext or _determine_extension(fetcher)
  File "/home/simon/spack/lib/spack/spack/mirror.py", line 263, in _determine_extension
    raise MirrorError(msg.format(fetcher.url))
spack.mirror.MirrorError: Unable to parse extension from https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.1.0_linux.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)
```

### Information on your system

```
* **Spack:** 0.16.2-2812-ec00d68ba1
* **Python:** 3.9.5
* **Platform:** linux-arch-skylake
* **Concretizer:** original
```

**Comment by simonpintarelli** [comment]
The bug was caused by a wrong spec trying to fetch an inexistent cuda version.
