### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#23891]
I believe I've found a possible file handle leak in Spack. This manifests itself when installing very large environments.

### Steps to reproduce the issue

I'm trying to install the following environment:
```yaml
spack:
  specs:

  # Shells
  - bash

  # Spack dependencies
  - clingo
  - gnupg
  - graphviz
  - kcov

  # Newer versions of Linux tools
  - watch
  - wget
  - unrar

  # Software installation tools
  - automake
  - autoconf
  - m4
  - cmake
  - ninja
  - patchelf
  - scons

  # Version control systems
  - mercurial
  - subversion

  # Python libraries
  - python
  - py-azureml-sdk
  - py-black
  - py-cartopy
  - py-cmocean
  - py-codecov
  - py-dask
  - py-fiona
  - py-flake8
  - py-flake8-import-order
  - py-geocube
  - py-geopandas
  - py-geoplot
  - py-inference-schema+numpy
  - py-ipywidgets
  - py-joblib
  - py-jupyterlab
  - py-matplotlib
  - py-metpy
  - py-mypy
  - py-numpy
  - py-openpyxl
  - py-pandas
  - py-pycocotools
  - py-pygeos
  - py-pyinstrument
  - py-pytest
  - py-pytest-cov
  - py-pytest-mock
  - py-pyyaml
  - py-rarfile
  - py-rasterio
  - py-scikit-learn
  - py-scipy
  - py-seaborn
  - py-setuptools
  - py-shapely
  - py-sphinx
  - py-sphinx-rtd-theme
  - py-sphinxcontrib-programoutput
  - py-statsmodels
  - py-tables
  - py-torch
  - py-torchvision
  - py-twine
  - py-vermin
  - py-wheel
  - py-xarray
  - py-xgboost

  # Research libraries
  - gdal
  - opencv

  concretization: together
```
A few of these packages aren't yet in Spack, but you should be able to substitute them with other packages and still reproduce this.

### Error Message

After successfully installing several packages, I eventually hit:
```
==> Installing py-pytest-cov-2.8.1-jvm5vpnwx3vgzanxse2putpvi6ft54o5
==> No binary for py-pytest-cov-2.8.1-jvm5vpnwx3vgzanxse2putpvi6ft54o5 found: installing from source
==> Warning: Missing a source id for apple-libuuid@1353.100.2
==> Error: Failed to install py-pytest-cov due to OSError: [Errno 24] Too many open files
==> Installing py-pytest-mock-1.11.1-f2yunbyvz5f7sm6p5fkunwpu3lu6zc2f
==> No binary for py-pytest-mock-1.11.1-f2yunbyvz5f7sm6p5fkunwpu3lu6zc2f found: installing from source
==> Warning: Missing a source id for apple-libuuid@1353.100.2
==> Error: Failed to install py-pytest-mock due to ProcessError: /usr/bin/git: Too many open files
    Command: '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
==> Installing py-requests-2.24.0-cbnrnlrvv32qea7ofousm62yr7g5o4eq
==> No binary for py-requests-2.24.0-cbnrnlrvv32qea7ofousm62yr7g5o4eq found: installing from source
==> Warning: Missing a source id for apple-libuuid@1353.100.2
==> Warning: Skipping build of py-azureml-core-1.23.0-ufhtrskom5dhrbf2ohomke6d75uaw5m5 since py-requests-2.24.0-cbnrnlrvv32qea7ofousm62yr7g5o4eq failed
==> Warning: Skipping build of py-azureml-pipeline-core-1.23.0-6o5oa3nknsfca3a2yrplbj6l2rikwwyp since py-azureml-core-1.23.0-ufhtrskom5dhrbf2ohomke6d75uaw5m5 failed
==> Error: [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/.spack-db/lock'
```

### Information on your system

* **Spack:** 0.16.1-2888-a284edb852
* **Python:** 3.8.10
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
When I run `spack -ddd install`, I also see:
```
==> [2021-05-25-12:10:56.640281, 54459] CorruptDatabaseError: error parsing database:
    [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/.spack-db/index.json'
==> [2021-05-25-12:10:56.640384, 54459] Error: error parsing database:
[Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/.spack-db/index.json'
Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 118, in remove_install_directory
    shutil.rmtree(path)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-cloblksy6vn52cmys3wm23fvsrww2xox/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-cloblksy6vn52cmys3wm23fvsrww2xox/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-cloblksy6vn52cmys3wm23fvsrww2xox/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/python-3.8.10-cloblksy6vn52cmys3wm23fvsrww2xox/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/py-ndg-httpsclient-0.5.1-5p7eunxeoixykmmdtfzsjcj3flabg2kk/.spack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/environment.py", line 1586, in install_specs
    builder.install()
  File "/Users/Adam/spack/lib/spack/spack/installer.py", line 1640, in install
    pkg.remove_prefix()
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 1296, in remove_prefix
    spack.store.layout.remove_install_directory(self.spec)
  File "/Users/Adam/spack/lib/spack/spack/directory_layout.py", line 120, in remove_install_directory
    raise RemoveFailedError(spec, path, e)
spack.directory_layout.RemoveFailedError: Could not remove prefix /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/py-ndg-httpsclient-0.5.1-5p7eunxeoixykmmdtfzsjcj3flabg2kk for py-ndg-httpsclient@0.5.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64/5p7eunx : [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/py-ndg-httpsclient-0.5.1-5p7eunxeoixykmmdtfzsjcj3flabg2kk/.spack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/database.py", line 711, in _read_from_file
    with open(filename, 'r') as f:
OSError: [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/.spack-db/index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 774, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 498, in _invoke_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/install.py", line 351, in install
    env.install_all(args, **kwargs)
  File "/Users/Adam/spack/lib/spack/spack/environment.py", line 1543, in install_all
    self.install_specs(None, args=args, **install_args)
  File "/Users/Adam/spack/lib/spack/spack/environment.py", line 1598, in install_specs
    self.regenerate_views()
  File "/Users/Adam/spack/lib/spack/spack/environment.py", line 1339, in regenerate_views
    view.regenerate(specs, self.roots())
  File "/Users/Adam/spack/lib/spack/spack/environment.py", line 604, in regenerate
    with spack.store.db.read_transaction():
  File "/Users/Adam/spack/lib/spack/llnl/util/lock.py", line 567, in __enter__
    self._as = self._acquire_fn()
  File "/Users/Adam/spack/lib/spack/spack/database.py", line 1013, in _read
    self._read_from_file(self._index_path)
  File "/Users/Adam/spack/lib/spack/spack/database.py", line 714, in _read_from_file
    raise CorruptDatabaseError("error parsing database:", str(e))
spack.database.CorruptDatabaseError: error parsing database:
    [Errno 24] Too many open files: '/Users/Adam/spack/opt/spack/.spack-db/index.json'
```

**Comment by adamjstewart** [comment]
Thanks to Activity Monitor, it looks like Spack has hundreds of open file handles for `/Users/Adam/spack/opt/spack/.spack-db/prefix_lock`.

**Comment by adamjstewart** [comment]
It looks like these file handles get cleaned up once each root spec in the environment finishes installing, but for specs with large DAGs like `py-azureml-sdk` we accrue too many open file handles and the ulimit is exceeded.

**Comment by adamjstewart** [comment]
Hit this again today.

**Comment by adamjstewart** [comment]
Hit this again today with a different environment:
```yaml
spack:
  specs:
  - "opencv+python3+imgcodecs+tiff+jpeg+png"
  - "pil@2.9:"
  - "python@3.6:+bz2"
  - "py-black@21:"
  - "py-fiona@1.5:"
  - "py-flake8@3.8:"
  - "py-h5py"
  - "py-ipywidgets@7:"
  - "py-isort@5.8:+colors"
  - "py-jupyterlab"
  - "py-matplotlib"
  - "py-mypy@0.900:"
  - "py-nbmake"
  - "py-nbsphinx@0.8.5:"
  - "py-numpy"
  - "py-omegaconf@2.1:"
  - "py-pycocotools"
  - "py-pydocstyle@6.1:+toml"
  - "py-pytest@6:"
  - "py-pytest-cov@2.4:"
  - "py-pytorch-lightning@1.3:"
  - "py-pytorch-sphinx-theme"
  - "py-radiant-mlhub@0.2.1:"
  - "py-rarfile@3:"
  - "py-rasterio@1.0.16:"
  - "py-rtree@0.5:"
  - "py-scikit-learn@0.18:"
  - "py-segmentation-models-pytorch@0.2:"
  - "py-setuptools@30.4:"
  - "py-sphinx@3:"
  - "py-torch@1.7:"
  - "py-torchmetrics"
  - "py-torchvision@0.3:"
  concretization: together
```

**Comment by tgamblin** [comment]
Are you building sequentially (and in one package at a time — package can be parallel) on one node or in parallel (multiple packages at a time)?

**Comment by adamjstewart** [comment]
Sequentially on my laptop

**Comment by tgamblin** [comment]
@adamjstewart can you see if #24794 fixes this?  It's been updated.
