### ISSUE TITLE
`spack config rm` does not remove the `compilers` section from an env

### ISSUE THREAD

**Issue by arekfu** [LLNL/spack#24242]
### Steps to reproduce the issue

```console
$ spack env create test
$ GCC_DIR=$(spack location -i gcc@7.5.0)  # for example, any compiler will do
$ spack env activate test
$ spack compiler add --scope env:test ${GCC_DIR}
```
After this command, `$SPACK_ROOT/var/spack/environments/test/spack.yaml` should contain a `compilers` section.
```console
$ spack config --scope env:test get compilers
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  compilers:
  - compiler:
      spec: gcc@7.5.0
      paths:
        cc: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gcc
        cxx: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/g++
        f77: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gfortran
        fc: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gfortran
      flags: {}
      operating_system: ubuntu16.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```
Now I try to remove the section
```console
$ spack config --scope env:test rm config:compilers
```
The command succeeds, but the `compilers` section is not removed from `spack.yaml`:
```console
$ spack config --scope env:test get compilers
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  compilers:
  - compiler:
      spec: gcc@7.5.0
      paths:
        cc: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gcc
        cxx: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/g++
        f77: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gfortran
        fc: /home/dm232107/src/spack/opt/spack/linux-ubuntu16.04-skylake/gcc-10.2.0/gcc-7.5.0-6xs6wkm7r2veak637opmyisphotmtsn2/bin/gfortran
      flags: {}
      operating_system: ubuntu16.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```
This gives an error instead:
```console
$ spack config --scope env:test rm compilers
==> Error: pop from empty list
```

### Error Message

```console
$ spack --debug --stacktrace config --scope env:test rm config:compilers
lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-10-19:20:33.430115] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-10-19:20:33.432503] Imported config from built-in commands
lib/spack/spack/config.py:981 ==> [2021-06-10-19:20:33.433397] Reading config file /volatile/home/dm232107/src/spack/var/spack/environments/test/spack.yaml
$ spack --debug --stacktrace config --scope env:test rm compilers
lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-10-19:20:47.113600] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-10-19:20:47.116044] Imported config from built-in commands
lib/spack/spack/config.py:981 ==> [2021-06-10-19:20:47.117845] Reading config file /volatile/home/dm232107/src/spack/var/spack/environments/test/spack.yaml
Traceback (most recent call last):
  File "/volatile/home/dm232107/src/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/main.py", line 774, in main
    return _invoke_command(command, parser, args, unknown)
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/main.py", line 498, in _invoke_command
    return_val = command(parser, args)
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/cmd/config.py", line 472, in config
    action[args.config_command](args)
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/cmd/config.py", line 217, in config_remove
    existing = spack.config.get(path, scope=scope)
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/config.py", line 898, in get
    return config.get(path, default, scope)
  File "/volatile/home/dm232107/src/spack/lib/spack/spack/config.py", line 645, in get
    section = parts.pop(0)
IndexError: pop from empty list
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2696-f1c849c
* **Python:** 3.8.1
* **Platform:** linux-ubuntu16.04-skylake
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed this one is still on develop (d19475c3b46b430ab93ab38cd1c8949ee0ef65bc):
```console
$ spack config rm compilers
==> Error: pop from empty list
```
