### ISSUE TITLE
spack setup example from docs doesn't work

### ISSUE THREAD

**Issue by TomasPuverle** [LLNL/spack#2449]
I get the following error:

➜  spack git:(develop) ✗ spack setup mylib@local
Traceback (most recent call last):
  File "/home/tom/dev/spack/bin/spack", line 206, in <module>
    main()
  File "/home/tom/dev/spack/bin/spack", line 183, in main
    return_val = command(parser, args)
  File "/home/tom/dev/spack/lib/spack/spack/cmd/setup.py", line 133, in setup
    with spack.installed_db.write_transaction():
AttributeError: 'module' object has no attribute 'installed_db'

**Comment by TomasPuverle** [comment]
Duplicate #2316
