### ISSUE TITLE
cuda (many versions): OverflowError: signed integer is greater than maximum on Ubuntu 20.04, 21.04

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#24589]
Cannot install, at least,`cuda@10.1.243:11.3.1` due to `OverflowError: signed integer is greater than maximum`:

Using:
* `spack@develop` (a7b6149cc02713de55cb5719b9dab2dfc0476303 from `Tue Jun 29 00:33:35 2021 -0400`)
* Ubuntu 20.04, Ubuntu 21.04
* GCC 9.3.0, GCC 10.3.0
* Python 3.8.5, Python 3.9.5

```
$> spack install cuda@11.3.1
...
==> Installing cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb
==> Fetching https://cache.e4s.io/build_cache/linux-ubuntu20.04-x86_64/gcc-9.3.0/cuda-11.3.1/linux-ubuntu20.04-x86_64-gcc-9.3.0-cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb.spack
==> Error: Failed to install cuda due to OverflowError: signed integer is greater than maximum
==> Error: signed integer is greater than maximum
```

```
$> spack -d install cuda@11.3.1
...
==> [2021-06-29-08:14:25.453897] Installing cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb
==> [2021-06-29-08:14:25.453935] Searching for binary cache of cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb
==> [2021-06-29-08:14:25.453997] Reading config file /spack/etc/spack/defaults/mirrors.yaml
==> [2021-06-29-08:14:25.586708] Did not find linux-ubuntu20.04-x86_64-gcc-9.3.0-cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb.spec.yaml on https://mirror.spack.io/build_cache/linux-ubuntu20.04-x86_64-gcc-9.3.0-cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-06-29-08:14:25.588309] Creating stage lock build_cache
==> [2021-06-29-08:14:25.588690] Checking existence of https://cache.e4s.io/build_cache/linux-ubuntu20.04-x86_64/gcc-9.3.0/cuda-11.3.1/linux-ubuntu20.04-x86_64-gcc-9.3.0-cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb.spack
==> [2021-06-29-08:14:25.673795] Fetching https://cache.e4s.io/build_cache/linux-ubuntu20.04-x86_64/gcc-9.3.0/cuda-11.3.1/linux-ubuntu20.04-x86_64-gcc-9.3.0-cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb.spack
==> [2021-06-29-08:14:25.807447] Flagging cuda-11.3.1-5japwam43c6ocqge56qnjgjs6c67spnb as failed: signed integer is greater than maximum
==> [2021-06-29-08:14:25.810523] Error: Failed to install cuda due to OverflowError: signed integer is greater than maximum
==> [2021-06-29-08:14:25.891387] Skip view update, this environment does not maintain a view
Traceback (most recent call last):
  File "/spack/bin/spack", line 77, in <module>
    sys.exit(spack.main.main())
  File "/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/install.py", line 471, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/spack/lib/spack/spack/cmd/install.py", line 271, in install_specs
    env.install_specs(specs_to_install, args=cli_args, **kwargs)
  File "/spack/lib/spack/spack/environment.py", line 1608, in install_specs
    builder.install()
  File "/spack/lib/spack/spack/installer.py", line 1574, in install
    self._install_task(task)
  File "/spack/lib/spack/spack/installer.py", line 1127, in _install_task
    _install_from_cache(pkg, cache_only, explicit, unsigned,
  File "/spack/lib/spack/spack/installer.py", line 274, in _install_from_cache
    installed_from_cache = _try_install_from_binary_cache(
  File "/spack/lib/spack/spack/installer.py", line 405, in _try_install_from_binary_cache
    return _process_binary_cache_tarball(pkg, binary_spec, explicit, unsigned,
  File "/spack/lib/spack/spack/installer.py", line 365, in _process_binary_cache_tarball
    tarball = binary_distribution.download_tarball(
  File "/spack/lib/spack/spack/binary_distribution.py", line 1052, in download_tarball
    stage.fetch()
  File "/spack/lib/spack/spack/stage.py", line 490, in fetch
    self.fetcher.fetch()
  File "/spack/lib/spack/spack/fetch_strategy.py", line 73, in wrapper
    return fun(self, *args, **kwargs)
  File "/spack/lib/spack/spack/fetch_strategy.py", line 318, in fetch
    partial_file, save_file = self._fetch_from_url(url)
  File "/spack/lib/spack/spack/fetch_strategy.py", line 356, in _fetch_from_url
    return self._fetch_urllib(url)
  File "/spack/lib/spack/spack/fetch_strategy.py", line 73, in wrapper
    return fun(self, *args, **kwargs)
  File "/spack/lib/spack/spack/fetch_strategy.py", line 385, in _fetch_urllib
    _data = response.read()
  File "/usr/lib/python3.8/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
```

@ax3l @Rombur @fspiga

**Comment by haampie** [comment]
Seems like you're hitting a bug in Python which is fixed in v3.10.0b1 and above: https://github.com/python/cpython/commit/89d1550d14ba689af12eeb726e4ff8ce73cee7e1

Although it looks weird we can't download 2GB+ files :thinking:

**Comment by eugeneswalker** [comment]
#24622 resolved the issue for me. Thank you!

**Comment by eugeneswalker** [comment]
https://github.com/spack/spack/pull/24623 Also resolved the issue for me. FYI
