### ISSUE TITLE
Spack on Spock

### ISSUE THREAD

**Issue by suchyta1** [LLNL/spack#24616]
I'm trying to use Spack to install software on Spock at OLCF. I've checked out either `releases/v0.16` or `develop`, and I'm running into errors with basic commands such as `spack find` or `spack complier find`, and these errors are the same regardless which branch I have checked out. The default Python is `Python 2.7.17`, but I've also tried the `cray-python/3.8.5.0`, and I see the same errors regardless which I have loaded. The examples below used `cray-python/3.8.5.0` and  the `develop` branch of Spack at the time that I cloned.

#### Example 1
```console
$ spack --debug --stacktrace find
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/util/executable.py:188 ==> [2021-06-30-09:20:38.299266] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/platforms/cray.py:154 ==> [2021-06-30-09:20:38.336908] default to front-end architecture
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-30-09:20:38.388508] Imported find from built-in commands
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-30-09:20:38.390065] Imported find from built-in commands
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py:986 ==> [2021-06-30-09:20:38.394245] Reading config file /autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/etc/spack/defaults/config.yaml
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py:986 ==> [2021-06-30-09:20:38.440006] Reading config file /ccs/home/esuchyta/.spack/cray/config.yaml
Traceback (most recent call last):
  File "/ccs/home/esuchyta/spack/wdmapp/spock/spack/bin/spack", line 77, in <module>
    sys.exit(spack.main.main())
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/find.py", line 215, in find
    results = args.specs(**q_args)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/common/arguments.py", line 78, in _specs
    return spack.store.db.query(**kwargs)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/lang.py", line 792, in __getattr__
    return getattr(self.ref_function(), name)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/store.py", line 228, in _store_db
    return store.db
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/lang.py", line 762, in __getattr__
    return getattr(self.instance, name)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/lang.py", line 752, in instance
    self._instance = self.factory()
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/store.py", line 209, in _store
    return Store(root=root,
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/store.py", line 163, in __init__
    self.db = spack.database.Database(
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/database.py", line 356, in __init__
    fs.mkdirp(self._db_dir)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/filesystem.py", line 630, in mkdirp
    raise e
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/filesystem.py", line 593, in mkdirp
    os.makedirs(path)
  File "/opt/cray/pe/python/3.8.5.0/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cray/pe/python/3.8.5.0/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cray/pe/python/3.8.5.0/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/opt/cray/pe/python/3.8.5.0/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/lustre'
```

#### Example 2
```console
$ spack compiler find
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/util/executable.py:188 ==> [2021-06-30-09:23:40.537651] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/platforms/cray.py:154 ==> [2021-06-30-09:23:40.572833] default to front-end architecture
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-30-09:23:40.619925] Imported compiler from built-in commands
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-06-30-09:23:40.622956] Imported compiler from built-in commands
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py:986 ==> [2021-06-30-09:23:41.060796] Reading config file /ccs/home/esuchyta/.spack/cray/compilers.yaml
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/main.py:774 ==> [2021-06-30-09:23:41.368539] ConfigFileError: Error parsing yamlNone: could not determine a constructor for the tag '!!python/unicode'
autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/error.py:55 ==> [2021-06-30-09:23:41.370008] Error: Error parsing yamlNone: could not determine a constructor for the tag '!!python/unicode'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 1108, in construct_undefined
    if node.flow_style is True:
AttributeError: 'ScalarNode' object has no attribute 'flow_style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 988, in read_config_file
    data = syaml.load_config(f)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/util/spack_yaml.py", line 309, in load_config
    return yaml.load(*args, **kwargs)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/main.py", line 75, in load
    return loader.get_single_data()
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 67, in get_single_data
    return self.construct_document(node)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 76, in construct_document
    for dummy in generator:
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/util/spack_yaml.py", line 153, in construct_yaml_seq
    for x in gen:
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 1044, in construct_yaml_seq
    data.extend(self.construct_sequence(node, data))
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 876, in construct_sequence
    ret_val.append(self.construct_object(child, deep=deep))
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 125, in construct_object
    data = next(generator)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/external/ruamel/yaml/constructor.py", line 1116, in construct_undefined
    raise ConstructorError(
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!!python/unicode'
  in "/ccs/home/esuchyta/.spack/cray/compilers.yaml", line 60, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/compiler.py", line 194, in compiler
    action[args.compiler_command](args)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/cmd/compiler.py", line 87, in compiler_find
    same_specs = spack.compilers.compilers_for_spec(
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/compilers/__init__.py", line 59, in converter
    return function(cspec_like, *args, **kwargs)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/compilers/__init__.py", line 297, in compilers_for_spec
    config = all_compilers_config(scope, init_config)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/compilers/__init__.py", line 181, in all_compilers_config
    _cache_config_file = get_compiler_config(scope, init_config)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/compilers/__init__.py", line 98, in get_compiler_config
    config = spack.config.get('compilers', scope=scope)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 903, in get
    return config.get(path, default, scope)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 648, in get
    value = self.get_config(section, scope=scope)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 588, in get_config
    return self._get_config_memoized(section, scope)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/llnl/util/lang.py", line 207, in _memoized_function
    func.cache[args] = func(*args)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 603, in _get_config_memoized
    data = scope.get_section(section)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 159, in get_section
    data   = read_config_file(path, schema)
  File "/autofs/nccs-svm1_home1/esuchyta/spack/wdmapp/spock/spack/lib/spack/spack/config.py", line 1002, in read_config_file
    raise ConfigFileError(
spack.config.ConfigFileError: Error parsing yamlNone: could not determine a constructor for the tag '!!python/unicode'
```

### Information on your system

* **Spack:** 0.16.2-3310-a7b6149cc0
* **Python:** 3.8.5
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if this is still considered relevant.
