### ISSUE TITLE
RuntimeError: Unable to locate python command in /usr/lib/python-exec/bin

### ISSUE THREAD

**Issue by permeakra** [LLNL/spack#24812]
Spack tries to find python in '/usr/lib/python-exec/bin' . WTF is this dir, I do not have it in ubuntu or gentoo.

```console
$  spack --debug --stacktrace solve quantum-espresso ~scalapack
lib/spack/spack/cmd/__init__.py:122 ==> [2021-07-09-20:47:43.593643] Imported solve from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-07-09-20:47:43.595450] Imported solve from built-in commands
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:43.601257] Reading config file /home/permeakra/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:370 ==> [2021-07-09-20:47:43.634601] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:374 ==> [2021-07-09-20:47:43.634871] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:370 ==> [2021-07-09-20:47:43.635590] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:374 ==> [2021-07-09-20:47:43.635814] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:199 ==> [2021-07-09-20:47:43.636026] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:211 ==> [2021-07-09-20:47:43.636638] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/permeakra/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:212 ==> [2021-07-09-20:47:43.636816] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/permeakra/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:211 ==> [2021-07-09-20:47:43.636996] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
lib/spack/spack/bootstrap.py:212 ==> [2021-07-09-20:47:43.637165] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
lib/spack/spack/bootstrap.py:211 ==> [2021-07-09-20:47:43.637342] [BOOTSTRAP CONFIG SCOPE] name=site, path=/home/permeakra/spack/etc/spack
lib/spack/spack/bootstrap.py:212 ==> [2021-07-09-20:47:43.637511] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/home/permeakra/spack/etc/spack/linux
lib/spack/spack/bootstrap.py:211 ==> [2021-07-09-20:47:43.637687] [BOOTSTRAP CONFIG SCOPE] name=user, path=/home/permeakra/.spack
lib/spack/spack/bootstrap.py:212 ==> [2021-07-09-20:47:43.637855] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/home/permeakra/.spack/linux
lib/spack/spack/bootstrap.py:248 ==> [2021-07-09-20:47:43.644634] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:43.647291] Reading config file /home/permeakra/spack/etc/spack/defaults/config.yaml
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.740452] diffutils applying constraint iconv
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.757979] ncurses applying constraint pkgconfig
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.759892] readline applying constraint ncurses
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.761311] gdbm applying constraint readline
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.765419] perl applying constraint gdbm
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.766854] perl applying constraint berkeley-db
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.768263] bison applying constraint diffutils
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.769625] bison applying constraint m4
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.771034] bison applying constraint perl
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.773021] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.774892] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.777899] clingo-bootstrap applying constraint cmake@3.16.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.780187] clingo-bootstrap applying constraint re2c@0.13:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.782486] clingo-bootstrap applying constraint bison@2.5:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.784075] clingo-bootstrap applying constraint python
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:43.786873] Reading config file /home/permeakra/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:43.834571] Reading config file /home/permeakra/.spack/packages.yaml
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.932737] clingo-bootstrap applying constraint cmake@3.16.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.935349] clingo-bootstrap applying constraint re2c@0.13:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.937250] clingo-bootstrap applying constraint bison@2.5:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.939106] clingo-bootstrap applying constraint python
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.940324] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.948098] clingo-bootstrap applying constraint cmake@3.16.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.949520] clingo-bootstrap applying constraint re2c@0.13:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.951030] clingo-bootstrap applying constraint bison@2.5:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.952337] clingo-bootstrap applying constraint python
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.953126] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.959602] clingo-bootstrap applying constraint cmake@3.16.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.961109] clingo-bootstrap applying constraint re2c@0.13:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.962472] clingo-bootstrap applying constraint bison@2.5:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:43.963922] clingo-bootstrap applying constraint python
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:43.973167] Reading config file /home/permeakra/.spack/linux/compilers.yaml
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:44.001543] clingo-bootstrap applying constraint cmake@3.16.0:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:44.003280] clingo-bootstrap applying constraint re2c@0.13:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:44.004897] clingo-bootstrap applying constraint bison@2.5:
lib/spack/spack/spec.py:2809 ==> [2021-07-09-20:47:44.006266] clingo-bootstrap applying constraint python
lib/spack/spack/spec.py:2484 ==> [2021-07-09-20:47:44.015789] Ordered hashes [cmake]: cmake/22/bf695e3febb222da2ed94b3beea600650e4318975da90e4a71d6f31a6d5d8c3d
lib/spack/spack/spec.py:2484 ==> [2021-07-09-20:47:44.016090] Ordered hashes [python]: python/6/0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:44.113223] Reading config file /home/permeakra/spack/etc/spack/defaults/config.yaml
lib/spack/spack/installer.py:1401 ==> [2021-07-09-20:47:44.199945] Initializing the build queue from the build requests
lib/spack/spack/installer.py:1015 ==> [2021-07-09-20:47:44.200189] Initializing the build queue for clingo-bootstrap
lib/spack/spack/installer.py:2131 ==> [2021-07-09-20:47:44.203857] Processing dependencies for clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3: ('build', 'link', 'run')
lib/spack/spack/installer.py:1869 ==> [2021-07-09-20:47:44.204164] Pkg id bison-3.7.6-m6urtv65iur7kdadltfqw6mzaa6nl47a has the following dependents:
lib/spack/spack/installer.py:1872 ==> [2021-07-09-20:47:44.204365] - clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/installer.py:1869 ==> [2021-07-09-20:47:44.224262] Pkg id cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm has the following dependents:
lib/spack/spack/installer.py:1872 ==> [2021-07-09-20:47:44.224496] - clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/installer.py:1869 ==> [2021-07-09-20:47:44.242506] Pkg id python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6 has the following dependents:
lib/spack/spack/installer.py:1872 ==> [2021-07-09-20:47:44.242759] - clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/installer.py:1869 ==> [2021-07-09-20:47:44.285435] Pkg id re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z has the following dependents:
lib/spack/spack/installer.py:1872 ==> [2021-07-09-20:47:44.285682] - clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/database.py:470 ==> [2021-07-09-20:47:44.301054] Removing failure marking for clingo-bootstrap
lib/spack/spack/installer.py:1869 ==> [2021-07-09-20:47:44.301406] Pkg id clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3 has the following dependents:
lib/spack/spack/installer.py:1407 ==> [2021-07-09-20:47:44.301964] Ensure all dependencies know all dependents across specs
lib/spack/spack/installer.py:323 ==> [2021-07-09-20:47:44.304195] bison@3.7.6 : externally installed in /usr
lib/spack/spack/installer.py:329 ==> [2021-07-09-20:47:44.304392] bison@3.7.6 : already registered in DB
[+] /usr (external bison-3.7.6-m6urtv65iur7kdadltfqw6mzaa6nl47a)
lib/spack/spack/installer.py:1379 ==> [2021-07-09-20:47:44.304629] Flagging bison-3.7.6-m6urtv65iur7kdadltfqw6mzaa6nl47a as installed
lib/spack/spack/installer.py:1386 ==> [2021-07-09-20:47:44.304812] Removing bison-3.7.6-m6urtv65iur7kdadltfqw6mzaa6nl47a from clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3's uninstalled dependencies.
lib/spack/spack/installer.py:1976 ==> [2021-07-09-20:47:44.305038] clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3: Removed bison-3.7.6-m6urtv65iur7kdadltfqw6mzaa6nl47a from uninstalled deps list: {'python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6', 're2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z', 'cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm'}
lib/spack/spack/installer.py:323 ==> [2021-07-09-20:47:44.305271] cmake@3.18.5 : externally installed in /usr
lib/spack/spack/installer.py:329 ==> [2021-07-09-20:47:44.305460] cmake@3.18.5 : already registered in DB
[+] /usr (external cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm)
lib/spack/spack/installer.py:1379 ==> [2021-07-09-20:47:44.305686] Flagging cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm as installed
lib/spack/spack/installer.py:1386 ==> [2021-07-09-20:47:44.305866] Removing cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm from clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3's uninstalled dependencies.
lib/spack/spack/installer.py:1976 ==> [2021-07-09-20:47:44.306075] clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3: Removed cmake-3.18.5-jbvp3dcdw7rk3pzkrxmboxxhe4fmoxcm from uninstalled deps list: {'python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6', 're2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z'}
lib/spack/spack/installer.py:323 ==> [2021-07-09-20:47:44.306303] python@3.9 : externally installed in /usr/lib/python-exec
lib/spack/spack/installer.py:329 ==> [2021-07-09-20:47:44.306493] python@3.9 : already registered in DB
[+] /usr/lib/python-exec (external python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6)
lib/spack/spack/installer.py:1379 ==> [2021-07-09-20:47:44.306715] Flagging python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6 as installed
lib/spack/spack/installer.py:1386 ==> [2021-07-09-20:47:44.306894] Removing python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6 from clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3's uninstalled dependencies.
lib/spack/spack/installer.py:1976 ==> [2021-07-09-20:47:44.307113] clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3: Removed python-3.9-cyikgbv5vykau6tskn7whaf575jtcpr6 from uninstalled deps list: {'re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z'}
lib/spack/spack/installer.py:961 ==> [2021-07-09-20:47:44.307850] Acquiring a write lock on re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z with timeout 1e-09
lib/spack/spack/installer.py:1379 ==> [2021-07-09-20:47:44.315288] Flagging re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z as installed
lib/spack/spack/installer.py:1386 ==> [2021-07-09-20:47:44.315650] Removing re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z from clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3's uninstalled dependencies.
lib/spack/spack/installer.py:1976 ==> [2021-07-09-20:47:44.315937] clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3: Removed re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z from uninstalled deps list: set()
lib/spack/spack/stage.py:323 ==> [2021-07-09-20:47:44.317369] Creating stage lock spack-stage-re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z
lib/spack/spack/installer.py:977 ==> [2021-07-09-20:47:44.317645] Downgrading to a read lock on re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z with timeout 1e-09
[+] /home/permeakra/.spack/bootstrap/store/linux-gentoo2-x86_64/gcc-10.3.0/re2c-1.2.1-pcooyrx7gelqmyaa3agavhb2sau7w46z
lib/spack/spack/installer.py:961 ==> [2021-07-09-20:47:44.318256] Acquiring a write lock on clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3 with timeout 1e-09
lib/spack/spack/installer.py:1121 ==> [2021-07-09-20:47:44.321389] Installing clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/installer.py:394 ==> [2021-07-09-20:47:44.321584] Searching for binary cache of clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/config.py:986 ==> [2021-07-09-20:47:44.322260] Reading config file /home/permeakra/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/binary_distribution.py:1368 ==> [2021-07-09-20:47:55.066384] Did not find linux-gentoo2-x86_64-gcc-10.3.0-clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3.spec.yaml on https://mirror.spack.io/build_cache/linux-gentoo2-x86_64-gcc-10.3.0-clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3.spec.yaml
  Download failed: HTTP Error 404: Not Found
lib/spack/spack/installer.py:282 ==> [2021-07-09-20:47:55.067168] No binary for clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3 found: installing from source
lib/spack/spack/util/executable.py:188 ==> [2021-07-09-20:47:55.208442] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
lib/spack/spack/compilers/__init__.py:740 ==> [2021-07-09-20:47:55.385051] [TOOLCHAIN] MATCH Gcc
lib/spack/spack/stage.py:323 ==> [2021-07-09-20:47:55.399059] Creating stage lock spack-stage-clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/error.py:55 ==> [2021-07-09-20:47:55.402583] Error: RuntimeError: Unable to locate python command in /usr/lib/python-exec/bin

/home/permeakra/spack/var/spack/repos/builtin/packages/python/package.py:656, in command:
        653                return Executable(path)
        654        else:
        655            msg = 'Unable to locate {0} command in {1}'
  >>    656            raise RuntimeError(msg.format(self.name, self.prefix.bin))


Traceback (most recent call last):
  File "/home/permeakra/spack/lib/spack/spack/build_environment.py", line 919, in _setup_pkg_and_run
    setup_package(pkg, dirty=kwargs.get('dirty', False),
  File "/home/permeakra/spack/lib/spack/spack/build_environment.py", line 801, in setup_package
    set_build_environment_variables(pkg, env, dirty)
  File "/home/permeakra/spack/lib/spack/spack/build_environment.py", line 380, in set_build_environment_variables
    dep_link_dirs.extend(query.libs.directories)
  File "/home/permeakra/spack/lib/spack/spack/spec.py", line 950, in __get__
    value = f()
  File "/home/permeakra/spack/lib/spack/spack/spec.py", line 939, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/home/permeakra/spack/var/spack/repos/builtin/packages/python/package.py", line 773, in libs
  File "/home/permeakra/spack/var/spack/repos/builtin/packages/python/package.py", line 691, in get_config_var
  File "/home/permeakra/spack/var/spack/repos/builtin/packages/python/package.py", line 657, in command
RuntimeError: Unable to locate python command in /usr/lib/python-exec/bin
lib/spack/spack/installer.py:1331 ==> [2021-07-09-20:47:55.403396] Flagging clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3 as failed: RuntimeError: Unable to locate python command in /usr/lib/python-exec/bin
lib/spack/spack/stage.py:323 ==> [2021-07-09-20:47:55.406914] Creating stage lock spack-stage-clingo-bootstrap-spack-tg2vprfyvc6m7btmlpr65ipmnkwi7xc3
lib/spack/spack/main.py:774 ==> [2021-07-09-20:47:55.407228] ChildError: RuntimeError: Unable to locate python command in /usr/lib/python-exec/bin

```

### Information on your system

* **Spack:** 0.16.2-3160-f31e52801d
* **Python:** 3.9.5
* **Platform:** linux-gentoo2-zen
* **Concretizer:** original

Python 3.9 active, python 3.8 available

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by permeakra** [comment]
[compilers.yaml.txt](https://github.com/spack/spack/files/6793933/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/6793934/packages.yaml.txt)

**Comment by alalazo** [comment]
Which Python command do you have available (full path)?

**Comment by permeakra** [comment]
@alalazo 
```
permeakra@spack-gentoo ~ $which python
/usr/bin/python
permeakra@spack-gentoo ~ $ stat /usr/bin/python
  File: /usr/bin/python -> python-exec2c
  Size: 13              Blocks: 0          IO Block: 4096   symbolic link
Device: 812h/2066d      Inode: 2356688     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-07-12 12:29:33.178357274 -0000
Modify: 2021-06-16 13:41:03.624587894 -0000
Change: 2021-06-16 13:41:06.168554049 -0000
 Birth: 2021-06-16 13:41:06.168554049 -0000
permeakra@spack-gentoo ~ $ /usr/bin/python-exec2c -h
Usage: /usr/bin/python-exec2c <script>

python-exec is a wrapper to run Python scripts in an environment
supporting parallel install of multiple Python implementations.
For more information, please see the included README file.

Additional options:
  --help, -h                   print this help message
  --list-implementations, -l   list supported implementations
  --version, -V                print the package name and version
permeakra@spack-gentoo ~ $ /usr/bin/python-exec2c -l
python3.9
python3.8
pypy3
permeakra@spack-gentoo ~ $ which python3.9
/usr/bin/python3.9
permeakra@spack-gentoo ~ $ stat /usr/bin/python3.9
  File: /usr/bin/python3.9
  Size: 14224           Blocks: 32         IO Block: 4096   regular file
Device: 812h/2066d      Inode: 2498308     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-07-12 01:57:51.900291068 -0000
Modify: 2021-06-16 17:53:43.080267032 -0000
Change: 2021-06-16 17:53:49.036187794 -0000
 Birth: 2021-06-16 17:53:43.080267032 -0000
```

**Comment by alalazo** [comment]
OT: I'll be available at spots this week + don't have a gentoo available quickly, so debug may proceed slower than usual :slightly_smiling_face: 

Can we try ruling out the `python-exec2c` script? From a clean environment you can try:
```console
$ unset SPACK_PYTHON
$ export SPACK_PYTHON=/usr/bin/python3.9
$ . share/spack/setup-env.sh
$ spack solve zlib
```
and report if clingo bootstraps successfully from sources.

**Comment by permeakra** [comment]
> report if clingo bootstraps successfully from sources.

It does. Please, could you help me to find what exactly python-exec2c breaks so I could report a bug?

**Comment by alalazo** [comment]
@permeakra I'll try to debug this with low priority. Can you check if bootstrapping from binaries with #22720 works on your system? The setup requires some manual work at the moment, but when the PR is merged the buildcache will be in a public location so everybody could pull from it.

**Comment by permeakra** [comment]
@alalazo I'll check later this week.

**Comment by alalazo** [comment]
@robertu94 The Gentoo specific issue in #24928 is being tracked here

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.
