### ISSUE TITLE
Installation issue: flex-2.6.4

### ISSUE THREAD

**Issue by kelbstf** [LLNL/spack#25279]
### Steps to reproduce the issue

Successful:
````console
spack -d -v install --fake flex
````
Failing:
````console
spack -d -v install flex
````

Errors apparently:
````console
make[2]: *** [Makefile:1833: stage1scan.c] Broken pipe
````

````console
File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/build_environment.py", \
line 838, in child_process
````
Errors in their context:

````console
$  spack -d -v install flex

( ... )

/bin/sh ../libtool  --tag=CC   --mode=link /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc  -g -O2 -version-info 2:0:0  -o libfl.la -rpath /opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/lib libmain.lo libyywrap.lo  -lm 
./stage1flex   -o stage1scan.c ./scan.l
make[2]: *** [Makefile:1833: stage1scan.c] Broken pipe
make[2]: *** Deleting file 'stage1scan.c'
make[2]: *** Waiting for unfinished jobs....
libtool: link: /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc -shared  -fPIC -DPIC  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -Wl,-soname -Wl,libfl.so.2 -o .libs/libfl.so.2.0.0
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
libtool: link: ranlib .libs/libfl.a
libtool: link: ( cd ".libs" && rm -f "libfl.la" && ln -s "../libfl.la" "libfl.la" )
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make[1]: *** [Makefile:575: all] Error 2
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make: *** [Makefile:533: all-recursive] Error 1
==&gt; [2021-08-05-18:35:03.601781, 1883439] WRITE LOCK (spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh): /tmp/root/spack-stage/.lock[8699948262418216499:1] [Releasing] (reads 0, writes 1)
==&gt; [2021-08-05-18:35:03.602065, 1883439] WRITE LOCK (spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh): /tmp/root/spack-stage/.lock[8699948262418216499:1] [Released at 18:35:03.602033] (reads 0, writes 0)
==&gt; [2021-08-05-18:35:03.610548, 1883434] Error: ProcessError: Command exited with status 2:
    'make' '-j2'

See build log for details:
  /tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-build-out.txt

Traceback (most recent call last):
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/build_environment.py", line 838, in child_process
    return_value = function()
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/installer.py", line 1140, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/build_systems/autotools.py", line 331, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/build_environment.py", line 133, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j2'
==&gt; [2021-08-05-18:35:03.932598, 1883434] Error: Failed to install flex due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j2'

( ... )

==> [2021-08-05-18:34:58.849152, 1883439] 1883434: flex: Executing phase: 'build'
==> [2021-08-05-18:34:58.849857, 1883439] 'make' '-j2'
Making all in src
make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make  all-am

( ... )

/bin/sh ../libtool  --tag=CC   --mode=link /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc  -g -O2 -version-info 2:0:0  -o libfl.la -rpath /opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/lib libmain.lo libyywrap.lo  -lm 
./stage1flex   -o stage1scan.c ./scan.l
make[2]: *** [Makefile:1833: stage1scan.c] Broken pipe
make[2]: *** Deleting file 'stage1scan.c'
make[2]: *** Waiting for unfinished jobs....
libtool: link: /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc -shared  -fPIC -DPIC  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -Wl,-soname -Wl,libfl.so.2 -o .libs/libfl.so.2.0.0
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
libtool: link: ranlib .libs/libfl.a
libtool: link: ( cd ".libs" && rm -f "libfl.la" && ln -s "../libfl.la" "libfl.la" )
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make[1]: *** [Makefile:575: all] Error 2
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make: *** [Makefile:533: all-recursive] Error 1
````
Errors according to build log:
````console
/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-build-out.txt

(...)
==> [2021-08-05-18:34:58.849152, 1883439] 1883434: flex: Executing phase: 'build'
==> [2021-08-05-18:34:58.849857, 1883439] 'make' '-j2'
Making all in src
make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make  all-am

(...)

libtool: link: /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o  -lm
/bin/sh ../libtool  --tag=CC   --mode=link /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc  -g -O2 -version-info 2:0:0  -o libfl.la -rpath /opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/lib libmain.lo libyywrap.lo  -lm 
./stage1flex   -o stage1scan.c ./scan.l
make[2]: *** [Makefile:1833: stage1scan.c] Broken pipe
make[2]: *** Deleting file 'stage1scan.c'
make[2]: *** Waiting for unfinished jobs....
libtool: link: /opt/ohpc/admin/spack/0.15.0/lib/spack/env/gcc/gcc -shared  -fPIC -DPIC  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -Wl,-soname -Wl,libfl.so.2 -o .libs/libfl.so.2.0.0
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
libtool: link: ranlib .libs/libfl.a
libtool: link: ( cd ".libs" && rm -f "libfl.la" && ln -s "../libfl.la" "libfl.la" )
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make[1]: *** [Makefile:575: all] Error 2
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-flex-2.6.4-54bme7efufngw5ierxtznhndwpmm37hh/spack-src/src'
make: *** [Makefile:533: all-recursive] Error 1

````

### Information on your system

* **Spack:** 0.15.0
* **Python:** 3.6.8
* **Platform:** linux-centos8-haswell
* Spack implemented via OHPC 2.2
* OS: CentOS8.4

### Additional information

[config.log.txt](https://github.com/spack/spack/files/6940677/config.log.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6940678/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6940680/spack-build-out.txt)
"spack maintainers flex" without result

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by scheibelp** [comment]
Are you able to replicate this with the current tip of Spack's develop branch (you might have to specify `flex@2.6.4` if a version has been added since Spack 0.15)?

**Comment by kelbstf** [comment]
Hello @scheibelp,
thank you very much for your response.
I also tested the explicit "spack -d -v install flex@2.6.4" (same result), but omitted that here as the generic version appeared to be more general. I
 believe that would download the latest release? I actually did not check that.
As OHPC newbie i did not manage to ascertain yet, whether i may update to latest spack 0.16.2 wihtout brealing it's integration into OHPC...
Best

**Comment by scheibelp** [comment]
> As OHPC newbie i did not manage to ascertain yet, whether i may update to latest spack 0.16.2 wihtout brealing it's integration into OHPC...

Would you be able to create a new directory with a fresh Spack install on the same system (and try installing flex with that)?

**Comment by kelbstf** [comment]
> Would you be able to create a new directory with a fresh Spack install on the same system (and try installing flex with that)?

Sure. Do you have s.th. in specifc in mind i should address in that parallel installation?

**Comment by kelbstf** [comment]
Hello @scheibelp,
i just managed to get flex-2.6.4-gcc-9.3.0 installed via spack 0.16.2 into a parallel installation on OHCP2.2 into
"/opt/ohpc/admin/spack-0.16.2".
It installed the following dependencies:
````console
spack find
==> 23 installed packages
-- linux-centos8-haswell / gcc@9.3.0 ----------------------------
autoconf@2.69        bison@3.7.6    findutils@4.8.0  gettext@0.21      libsigsegv@2.13  m4@1.4.19    pkgconf@1.7.4  xz@5.2.5
automake@1.16.3      bzip2@1.0.8    flex@2.6.4       help2man@1.47.16  libtool@2.4.6    ncurses@6.2  readline@8.1   zlib@1.2.11
berkeley-db@18.1.40  diffutils@3.7  gdbm@1.19        libiconv@1.16     libxml2@2.9.10   perl@5.34.0  tar@1.34
````
Since i am not sure yet how deep the integration of spack-ohpc.noarch into OHPC is, i can't figure whether i have to determine why the installation failed via spack "0.15.0-8.1.ohpc.2.0 "...
In particular the Lmod and SLURM integration is what i deem critical, while the compilers ssems to be no problem.
What do you reckon?
Best
