### ISSUE TITLE
SLEPc fails to configure with Spack's python

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2534]
I just wiped my installation of Spack to re-install and check things and got the error `Symbol not found: __PyCodecInfo_GetIncrementalDecoder`:
```
==> './configure' '--prefix=/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/slepc-3.7.3-rhcxmg2ntqe3v6epgljeseffnpa4gla2' '--with-arpack-dir=/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/arpack-ng-3.4.0-g76ncwdpqcyx5lm5e65ydwaetbx5sulo/lib' '--with-arpack-flags=-lparpack,-larpack'
Traceback (most recent call last):
  File "./configure", line 10, in <module>
    execfile(os.path.join(os.path.dirname(__file__), 'config', 'configure.py'))
  File "./config/configure.py", line 140, in <module>
    import slepc, petsc, arpack, blzpack, trlan, feast, primme, blopex, sowing, lapack
  File "/private/var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/davydden/spack-stage/spack-stage-ZOF1pH/slepc-3.7.3/config/packages/petsc.py", line 22, in <module>
    import package, os, sys, commands
  File "/private/var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/davydden/spack-stage/spack-stage-ZOF1pH/slepc-3.7.3/config/package.py", line 22, in <module>
    import os, sys, commands, tempfile, shutil, urllib, urlparse, tarfile
  File "/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-6dtr7kw2sj5zu7z7v3ox3agrmpw5cndt/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-6dtr7kw2sj5zu7z7v3ox3agrmpw5cndt/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-6dtr7kw2sj5zu7z7v3ox3agrmpw5cndt/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-6dtr7kw2sj5zu7z7v3ox3agrmpw5cndt/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.12-6dtr7kw2sj5zu7z7v3ox3agrmpw5cndt/lib/python2.7/lib-dynload/_io.so
```
Looking at the history of `python` package, i don't see what could have led to this.

For now will be using 
```
  python:
    version: [2.7.10]
    paths:
      python@2.7.10: /usr
    buildable: False
```

**Comment by citibeth** [comment]
My guess is your Spack-installed Python executable @2.7.10 is picking up system-installed Python 2.7.10 binary packages.

http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder

> For now will be using

I think that's the right choice for people who need Python only as build dependencies.

**Comment by davydden** [comment]
> My guess is your Spack-installed Python executable @2.7.10 is picking up system-installed Python 2.7.10 binary packages

Could be, but it certainly did do that before. So something must have changed so that this started to happen...

**Comment by citibeth** [comment]
2.7.11/12 were merged July 15, I suppose this isn't a change for you.

**Comment by davydden** [comment]
> 2.7.11/12 were merged July 15, I suppose this isn't a change for you.

no, for sure not. I have been using Spack build python when switching to Siera and the versions was 2.7.12. So the timeframe of this issue is roughly last two months.
