### ISSUE TITLE
spack develop clone with resources errors

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#25370]
### Steps to reproduce

When trying to use `spack develop` with Trilinos an error occurs during the call to `spack develop` and the Trilinos spec is not added as a develop spec
```
spack env create -d . 
spacktivate .
spack add trilinos
spack develop trilinos@develop
==> Configuring spec trilinos@develop for development at path trilinos
==> Error: [Errno 17] File exists: '/projects/wind/spack-manager/environments/cee/test/trilinos/.git'
```
Further inspection of the `spack.yaml` shows no development spec has been added.
The Trilinos repo that is cloned looks fine and will work if you manually add the develop spec to the `spack.yaml`.

If you run `spack develop trilinos@develop` again it will complete without error and the develop information will be added to `spack.yaml`

The same behavior also occurs when using `trilinos@master` for the develop spec.

### Error message

```
[psakiev@ascicgpu24 test2]$ spack -d develop trilinos@develop
==> [2021-08-11-14:49:43.245237] Imported develop from built-in commands
==> [2021-08-11-14:49:43.246412] Imported develop from built-in commands
==> [2021-08-11-14:49:43.254839] Configuring spec trilinos@develop for development at path trilinos
==> [2021-08-11-14:49:43.255758] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/repos.yaml
==> [2021-08-11-14:49:43.259631] Reading config file /ascldap/users/psakiev/.spack/repos.yaml
==> [2021-08-11-14:49:43.261874] Reading config file /projects/wind/spack-manager/environments/cee/test/test2/spack.yaml
==> [2021-08-11-14:49:43.443007] Creating stage lock spack-stage-trilinos-develop-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-11-14:49:43.443580] Creating stage lock resource-dtk-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-11-14:49:43.444084] Creating stage lock resource-scorec-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-11-14:49:43.444577] Creating stage lock resource-mesquite-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-11-14:49:43.445821] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/mirrors.yaml
==> [2021-08-11-14:49:43.448737] Checking existence of https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-08-11-14:49:43.449881] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz'
==> [2021-08-11-14:49:44.165162] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-08-11-14:49:44.165659] Checking existence of https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-08-11-14:49:44.167209] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/trilinos/trilinos-develop.tar.gz'
==> [2021-08-11-14:49:44.614361] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-08-11-14:49:44.614893] Cloning git repository: https://github.com/trilinos/Trilinos.git on branch develop
==> [2021-08-11-14:49:44.617186] '/usr/bin/git' '--version'
==> [2021-08-11-14:49:44.626395] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-11-14:49:44.634428] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-11-14:49:44.641397] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
Cloning into 'Trilinos'...
remote: Enumerating objects: 44939, done.
remote: Counting objects: 100% (44939/44939), done.
remote: Compressing objects: 100% (31639/31639), done.
remote: Total 44939 (delta 19978), reused 24625 (delta 12756), pack-reused 0
Receiving objects: 100% (44939/44939), 148.45 MiB | 12.30 MiB/s, done.
Resolving deltas: 100% (19978/19978), done.
Checking out files: 100% (51813/51813), done.
==> [2021-08-11-14:50:13.603800] Fetching from https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz failed.
==> [2021-08-11-14:50:13.604170] Fetching from https://mirror.spack.io/trilinos/trilinos-develop.tar.gz failed.
==> [2021-08-11-14:53:18.515127] Checking existence of https://mirror.spack.io/_source-cache/git/ornl-cees/DataTransferKit.git/master.tar.gz
==> [2021-08-11-14:53:18.520477] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/_source-cache/git/ornl-cees/DataTransferKit.git/master.tar.gz'
==> [2021-08-11-14:53:19.110079] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/ornl-cees/DataTransferKit.git/master.tar.gz
==> [2021-08-11-14:53:19.110334] Checking existence of https://mirror.spack.io/trilinos/dtk-develop.tar.gz
==> [2021-08-11-14:53:19.111736] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/trilinos/dtk-develop.tar.gz'
==> [2021-08-11-14:53:19.663709] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/trilinos/dtk-develop.tar.gz
==> [2021-08-11-14:53:19.664254] Cloning git repository: https://github.com/ornl-cees/DataTransferKit.git on branch master
==> [2021-08-11-14:53:19.665772] '/usr/bin/git' '--version'
==> [2021-08-11-14:53:19.674938] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-11-14:53:19.684325] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-11-14:53:19.692226] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'master' '--single-branch' '--depth' '1' 'https://github.com/ornl-cees/DataTransferKit.git'
Cloning into 'DataTransferKit'...
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 220 (delta 38), reused 63 (delta 2), pack-reused 0
Receiving objects: 100% (220/220), 243.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (38/38), done.
==> [2021-08-11-14:53:21.563262] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'submodule' 'update' '--init' '--recursive'
Submodule 'cmake/tribits' (https://github.com/tribitspub/tribits) registered for path 'cmake/tribits'
Submodule 'data' (https://github.com/ornl-cees/DTKData.git) registered for path 'data'
Submodule 'arborx' (https://github.com/arborx/arborx.git) registered for path 'packages/Search'
Cloning into 'cmake/tribits'...
remote: Enumerating objects: 22577, done.
remote: Counting objects: 100% (2468/2468), done.
remote: Compressing objects: 100% (894/894), done.
remote: Total 22577 (delta 1427), reused 2347 (delta 1351), pack-reused 20109
Receiving objects: 100% (22577/22577), 16.54 MiB | 5.21 MiB/s, done.
Resolving deltas: 100% (16669/16669), done.
Submodule path 'cmake/tribits': checked out '06e00a308f96e0f79a367c3ffacc9a7f3d15a84e'
Cloning into 'data'...
remote: Enumerating objects: 43, done.
remote: Total 43 (delta 0), reused 0 (delta 0), pack-reused 43
Unpacking objects: 100% (43/43), done.
Submodule path 'data': checked out '496547228a0a7696569891c45ac04e0b8942b2a1'
Cloning into 'packages/Search'...
remote: Enumerating objects: 12500, done.
remote: Counting objects: 100% (718/718), done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 12500 (delta 467), reused 576 (delta 407), pack-reused 11782
Receiving objects: 100% (12500/12500), 2.74 MiB | 2.70 MiB/s, done.
Resolving deltas: 100% (9142/9142), done.
Submodule path 'packages/Search': checked out 'f90641d8830571c1eb6a94231312580d6d2cc365'
==> [2021-08-11-14:53:32.291601] Fetching from https://mirror.spack.io/_source-cache/git/ornl-cees/DataTransferKit.git/master.tar.gz failed.
==> [2021-08-11-14:53:32.291955] Fetching from https://mirror.spack.io/trilinos/dtk-develop.tar.gz failed.
Traceback (most recent call last):
  File "/projects/wind/spack-manager/spack/bin/spack", line 77, in <module>
    sys.exit(spack.main.main())
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/cmd/develop.py", line 100, in develop
    changed = env.develop(spec, path, clone)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/environment.py", line 1166, in develop
    stage.steal_source(abspath)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 24, in __call__
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 24, in <listcomp>
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/stage.py", line 531, in steal_source
    shutil.copytree(entry, d)
  File "/usr/lib64/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/projects/wind/spack-manager/environments/cee/test/test2/trilinos/.git'
```

### Information on your system

```
[psakiev@ascicgpu24 test]$ spack debug report
* **Spack:** 0.16.2-3052-729d66a
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** original
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
The failure looks like it's with cloning `dtk`, which I'm not sure will even build as a "subrepo" for trilinos at present. Does it work if you delete the `when='+dtk @develop'` DTK resource inside the trilinos package?

**Comment by psakievich** [comment]
@sethrj unfortunately the error still persists even after commenting out the `dtk` variant for `develop`
```
[psakiev@ascicgpu24 test2]$ spack -d develop trilinos@develop
==> [2021-08-12-08:30:57.394681] Imported develop from built-in commands
==> [2021-08-12-08:30:57.396098] Imported develop from built-in commands
==> [2021-08-12-08:30:57.403937] Configuring spec trilinos@develop for development at path trilinos
==> [2021-08-12-08:30:57.404740] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/repos.yaml
==> [2021-08-12-08:30:57.408799] Reading config file /ascldap/users/psakiev/.spack/repos.yaml
==> [2021-08-12-08:30:57.411029] Reading config file /projects/wind/spack-manager/environments/cee/test/test2/spack.yaml
==> [2021-08-12-08:30:58.166300] Creating stage lock spack-stage-trilinos-develop-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-12-08:30:58.166977] Creating stage lock resource-scorec-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-12-08:30:58.167567] Creating stage lock resource-mesquite-xjqqtbwx3wofw4lwwodf6vaehx5y5t7e
==> [2021-08-12-08:30:58.168574] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/mirrors.yaml
==> [2021-08-12-08:30:58.172516] Checking existence of https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-08-12-08:30:58.174060] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz'
==> [2021-08-12-08:30:58.859638] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-08-12-08:30:58.860148] Checking existence of https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-08-12-08:30:58.861940] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/trilinos/trilinos-develop.tar.gz'
==> [2021-08-12-08:30:59.378336] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-08-12-08:30:59.378837] Cloning git repository: https://github.com/trilinos/Trilinos.git on branch develop
==> [2021-08-12-08:30:59.380225] '/usr/bin/git' '--version'
==> [2021-08-12-08:30:59.389327] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-12-08:30:59.398434] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-08-12-08:30:59.406024] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
Cloning into 'Trilinos'...
remote: Enumerating objects: 44939, done.
remote: Counting objects: 100% (44939/44939), done.
remote: Compressing objects: 100% (31685/31685), done.
remote: Total 44939 (delta 19956), reused 24558 (delta 12710), pack-reused 0
Receiving objects: 100% (44939/44939), 148.48 MiB | 12.65 MiB/s, done.
Resolving deltas: 100% (19956/19956), done.
Checking out files: 100% (51813/51813), done.
==> [2021-08-12-08:31:28.647113] Fetching from https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz failed.
==> [2021-08-12-08:31:28.647481] Fetching from https://mirror.spack.io/trilinos/trilinos-develop.tar.gz failed.
==> [2021-08-12-08:34:33.495602] Checking existence of https://mirror.spack.io/_source-cache/git/SCOREC/core.git/73c16eae073b179e45ec625a5abe4915bc589af2.tar.gz
==> [2021-08-12-08:34:33.500129] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/_source-cache/git/SCOREC/core.git/73c16eae073b179e45ec625a5abe4915bc589af2.tar.gz'
==> [2021-08-12-08:34:34.176745] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/SCOREC/core.git/73c16eae073b179e45ec625a5abe4915bc589af2.tar.gz
==> [2021-08-12-08:34:34.177062] Checking existence of https://mirror.spack.io/trilinos/scorec-develop.tar.gz
==> [2021-08-12-08:34:34.178843] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://mirror.spack.io/trilinos/scorec-develop.tar.gz'
==> [2021-08-12-08:34:34.671553] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/trilinos/scorec-develop.tar.gz
==> [2021-08-12-08:34:34.672105] Cloning git repository: https://github.com/SCOREC/core.git at commit 73c16eae073b179e45ec625a5abe4915bc589af2
==> [2021-08-12-08:34:34.673629] '/usr/bin/git' '--version'
==> [2021-08-12-08:34:34.683747] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' 'https://github.com/SCOREC/core.git'
Cloning into 'core'...
remote: Enumerating objects: 30573, done.
remote: Counting objects: 100% (3888/3888), done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 30573 (delta 3727), reused 3684 (delta 3635), pack-reused 26685
Receiving objects: 100% (30573/30573), 9.36 MiB | 5.61 MiB/s, done.
Resolving deltas: 100% (22473/22473), done.
==> [2021-08-12-08:34:38.013048] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'checkout' '73c16eae073b179e45ec625a5abe4915bc589af2'
HEAD is now at 73c16ea... pumi version 2.2.5
==> [2021-08-12-08:34:38.045069] Fetching from https://mirror.spack.io/_source-cache/git/SCOREC/core.git/73c16eae073b179e45ec625a5abe4915bc589af2.tar.gz failed.
==> [2021-08-12-08:34:38.045477] Fetching from https://mirror.spack.io/trilinos/scorec-develop.tar.gz failed.
Traceback (most recent call last):
  File "/projects/wind/spack-manager/spack/bin/spack", line 77, in <module>
    sys.exit(spack.main.main())
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/cmd/develop.py", line 100, in develop
    changed = env.develop(spec, path, clone)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/environment.py", line 1166, in develop
    stage.steal_source(abspath)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 24, in __call__
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 24, in <listcomp>
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/stage.py", line 531, in steal_source
    shutil.copytree(entry, d)
  File "/usr/lib64/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/projects/wind/spack-manager/environments/cee/test/test2/trilinos/.git'
```

**Comment by sethrj** [comment]
Hm, this looks like an issues with package `resource`s (rather than Trilinos itself) and the `spack develop` feature. @haampie I think `develop` is something you work on pretty often; do you have any ideas?

**Comment by haampie** [comment]
Yeah I think spack develop + resource is broken, but I didn't look into this.

**Comment by haampie** [comment]
@becker33 what's the idea with develop & resources? where do they go?

Another difficulty is that resources have a `when` clause that can only be evaluated after concretization, whereas `spack develop p@x.y.z` tries to clone before concretization based only on the version number. (Same applies to patches, which we don't handle either)

**Comment by haampie** [comment]
This is a solution, but it's very hacky & calling into internals:

```diff
diff --git a/lib/spack/spack/environment.py b/lib/spack/spack/environment.py
index cc5a066abb..7aeea86154 100644
--- a/lib/spack/spack/environment.py
+++ b/lib/spack/spack/environment.py
@@ -1162,9 +1162,7 @@ def develop(self, spec, path, clone=False):
         if clone:
             # "steal" the source code via staging API
             abspath = os.path.normpath(os.path.join(self.path, path))
-
-            stage = spec.package.stage
-            stage.steal_source(abspath)
+            spec.package._make_root_stage(spec.package.fetcher[0]).steal_source(abspath)
 
         # If it wasn't already in the list, append it
         self.dev_specs[spec.name] = {'path': path, 'spec': str(spec)}
```

**Comment by psakievich** [comment]
Bump on this. So are there any thoughts on @haampie's suggested solution?  @sethrj I'm also wondering if there is a package based solution for `Trilinos` as well?  Looking at my config and concretization it looks like `~scorec` is set so I'm wondering why this resource is even getting downloaded at all? If we could clean this up in the `Trilinos` package that would be a bandaid in right direction for me with the bonus of improving the package... :grin:

**Comment by sethrj** [comment]
> Bump on this. So are there any thoughts on @haampie's suggested solution?  @sethrj I'm also wondering if there is a package based solution for `Trilinos` as well?  Looking at my config and concretization it looks like `~scorec` is set so I'm wondering why this resource is even getting downloaded at all? If we could clean this up in the `Trilinos` package that would be a bandaid in right direction for me with the bonus of improving the package... :grin: 

Yeah the problem is that develop ignores variants so tries to always download the resources. And we can't remove the resource without removing the capability...

**Comment by psakievich** [comment]
Ah I see. That explains it.

**Comment by alalazo** [comment]
Related to #29540
