### ISSUE TITLE
Spack fetch error if url no longer exists and spack-public mirror removed

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#25419]
### Steps to reproduce

```
spack mirror rm --scope defaults spack-public
spack install pythia6
```

### Error message

```
$ spack -d install pythia6
==> [2021-08-13-12:37:56.134480] Imported install from built-in commands
==> [2021-08-13-12:37:56.139746] Reading config file /scratch/gartung/srcs/spack/etc/spack/defaults/config.yaml
==> [2021-08-13-12:37:56.191788] Imported install from built-in commands
==> [2021-08-13-12:37:56.193601] Reading config file /scratch/gartung/srcs/spack/etc/spack/defaults/repos.yaml
==> [2021-08-13-12:37:56.237078] pythia6 applying constraint cmake
==> [2021-08-13-12:37:56.237715] Reading config file /scratch/gartung/srcs/spack/etc/spack/defaults/packages.yaml
==> [2021-08-13-12:37:56.287690] Reading config file /scratch/gartung/srcs/spack/etc/spack/packages.yaml
==> [2021-08-13-12:37:56.314418] Reading config file /home/gartung/.spack/packages.yaml
==> [2021-08-13-12:37:56.323339] pythia6 applying constraint cmake
==> [2021-08-13-12:37:56.343533] Reading config file /scratch/gartung/srcs/spack/etc/spack/compilers.yaml
==> [2021-08-13-12:37:56.385056] pythia6 applying constraint cmake
==> [2021-08-13-12:37:56.388918] Ordered hashes [pythia6]: pythia6/0/d0817529347cbe70a4cac0da49410e5bf84f84d39f5e46810d8e278993e6e943
==> [2021-08-13-12:37:56.390575] Reading config file /scratch/gartung/srcs/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-08-13-12:37:56.393743] DATABASE LOCK TIMEOUT: 3s
==> [2021-08-13-12:37:56.393831] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-08-13-12:37:56.401552] Initializing the build queue from the build requests
==> [2021-08-13-12:37:56.401643] Initializing the build queue for pythia6
==> [2021-08-13-12:37:56.402070] Processing dependencies for pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw: ('build', 'link', 'run')
==> [2021-08-13-12:37:56.402250] Pkg id cmake-2.8.12.2-lfytfr3hr7w4o77fixjwxzrka5di5rqf has the following dependents:
==> [2021-08-13-12:37:56.402312] - pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.573344] Removing failure marking for pythia6
==> [2021-08-13-12:37:56.573612] Pkg id pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw has the following dependents:
==> [2021-08-13-12:37:56.574034] Ensure all dependencies know all dependents across specs
==> [2021-08-13-12:37:56.576252] cmake@2.8.12.2 : externally installed in /usr
==> [2021-08-13-12:37:56.576345] cmake@2.8.12.2 : already registered in DB
[+] /usr (external cmake-2.8.12.2-lfytfr3hr7w4o77fixjwxzrka5di5rqf)
==> [2021-08-13-12:37:56.576482] Flagging cmake-2.8.12.2-lfytfr3hr7w4o77fixjwxzrka5di5rqf as installed
==> [2021-08-13-12:37:56.576536] Removing cmake-2.8.12.2-lfytfr3hr7w4o77fixjwxzrka5di5rqf from pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw's uninstalled dependencies.
==> [2021-08-13-12:37:56.576627] pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw: Removed cmake-2.8.12.2-lfytfr3hr7w4o77fixjwxzrka5di5rqf from uninstalled deps list: set()
==> [2021-08-13-12:37:56.577099] Acquiring a write lock on pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw with timeout 1e-09
==> [2021-08-13-12:37:56.580252] Creating stage lock spack-stage-pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.580435] Creating stage lock resource-update_notes-6.4.28.txt-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.580570] Creating stage lock resource-lutp0613man2.pdf-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.580693] Creating stage lock resource-pythia6-announcement.txt-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.580813] Creating stage lock resource-main60.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.580929] Creating stage lock resource-main61.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581044] Creating stage lock resource-main62.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581157] Creating stage lock resource-main63.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581278] Creating stage lock resource-main64.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581391] Creating stage lock resource-main65.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581503] Creating stage lock resource-main66.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581616] Creating stage lock resource-main67.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581728] Creating stage lock resource-main68.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581840] Creating stage lock resource-main69.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.581951] Creating stage lock resource-main71.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582061] Creating stage lock resource-main72.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582169] Creating stage lock resource-main73.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582285] Creating stage lock resource-main75.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582396] Creating stage lock resource-main77.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582506] Creating stage lock resource-main78.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582616] Creating stage lock resource-main79.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582726] Creating stage lock resource-main81.f-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.582838] Creating stage lock resource-ttbar.lhe-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.584347] Installing pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.584437] Searching for binary cache of pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw
==> [2021-08-13-12:37:56.584560] Reading config file /scratch/gartung/srcs/spack/etc/spack/defaults/mirrors.yaml
==> [2021-08-13-12:37:56.586157] No Spack mirrors are currently configured
==> [2021-08-13-12:37:56.586274] No binary for pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw found: installing from source
==> [2021-08-13-12:37:56.605404] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
==> [2021-08-13-12:37:56.933873] [TOOLCHAIN] MATCH Gcc
==> [2021-08-13-12:37:56.937111] Adding compiler bin/ paths: /scratch/gartung/srcs/spack/lib/spack/env /scratch/gartung/srcs/spack/lib/spack/env/case-insensitive /scratch/gartung/srcs/spack/lib/spack/env/gcc
==> [2021-08-13-12:37:56.951105] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2021-08-13-12:37:57.039032] '/usr/bin/g++' '-v' '/tmp/spack-implicit-link-infonexjvp6t/main.c' '-o' '/tmp/spack-implicit-link-infonexjvp6t/output'
==> [2021-08-13-12:37:57.162749] parsing implicit link info
==> [2021-08-13-12:37:57.163825] linker line:  /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-infonexjvp6t/output /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. /tmp/cc9cHLlO.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
==> [2021-08-13-12:37:57.164118] linkdir: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
==> [2021-08-13-12:37:57.164296] linkdir: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64
==> [2021-08-13-12:37:57.164442] linkdir: /lib/../lib64
==> [2021-08-13-12:37:57.164572] linkdir: /usr/lib/../lib64
==> [2021-08-13-12:37:57.164696] linkdir: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../..
==> [2021-08-13-12:37:57.164847] found raw link dirs: /usr/lib/gcc/x86_64-redhat-linux/4.8.5, /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../..
==> [2021-08-13-12:37:57.165170] found link dirs: /usr/lib/gcc/x86_64-redhat-linux/4.8.5, /usr/lib64, /lib64, /usr/lib
==> [2021-08-13-12:37:57.174720] Checking existence of http://www.hepforge.org/archive/pythiasix/pythia-6.4.28.tgz
==> [2021-08-13-12:37:58.578313] FailedDownloadError: Failed to fetch file from URL: http://www.hepforge.org/archive/pythiasix/pythia-6.4.28.tgz
    Urllib fetch failed to verify url http://www.hepforge.org/archive/pythiasix/pythia-6.4.28.tgz
==> [2021-08-13-12:37:58.580464] Fetching from http://www.hepforge.org/archive/pythiasix/pythia-6.4.28.tgz failed.
==> [2021-08-13-12:37:58.611631] Error: FetchError: All fetchers failed

/scratch/gartung/srcs/spack/lib/spack/spack/package.py:1379, in do_fetch:
       1376
       1377        self.stage.create()
       1378        err_msg = None if not self.manual_download else self.download_instr
  >>   1379        start_time = time.time()
       1380        self.stage.fetch(mirror_only, err_msg=err_msg)
       1381        self._fetch_time = time.time() - start_time
       1382


Traceback (most recent call last):
  File "/scratch/gartung/srcs/spack/lib/spack/spack/build_environment.py", line 1013, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/scratch/gartung/srcs/spack/lib/spack/spack/installer.py", line 1890, in build_process
    return installer.run()
  File "/scratch/gartung/srcs/spack/lib/spack/spack/installer.py", line 1727, in run
    self.pkg.do_patch()
  File "/scratch/gartung/srcs/spack/lib/spack/spack/package.py", line 1416, in do_patch
    self.do_stage()
  File "/scratch/gartung/srcs/spack/lib/spack/spack/package.py", line 1401, in do_stage
    self.do_fetch(mirror_only)
  File "/scratch/gartung/srcs/spack/lib/spack/spack/package.py", line 1380, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/scratch/gartung/srcs/spack/lib/spack/spack/util/pattern.py", line 23, in __call__
    for item in self.container]
  File "/scratch/gartung/srcs/spack/lib/spack/spack/util/pattern.py", line 23, in <listcomp>
    for item in self.container]
  File "/scratch/gartung/srcs/spack/lib/spack/spack/stage.py", line 507, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
==> [2021-08-13-12:37:58.613119] Flagging pythia6-6.4.28-hkqkvacwuf23zvd67rwq3s2b3lksgihw as failed: FetchError: All fetchers failed
==> [2021-08-13-12:37:58.622721] ChildError: FetchError: All fetchers failed
```

### Information on your system

* **Spack:** 0.16.2-3907-f0875b2
* **Python:** 3.6.8
* **Platform:** linux-scientific7-skylake_avx512
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Both `wget` and `curl` also fail to download http://www.hepforge.org/archive/pythiasix/pythia-6.4.28.tgz, so I think this is an issue with the URL, not with Spack.

**Comment by gartung** [comment]
As I said in the linked PR the old url has gone away so a new one is needed.

**Comment by adamjstewart** [comment]
I think I was confused whether the issue was that the URL needed to be updated, or that a global `url` variable was required. Sorry for the confusion!

**Comment by gartung** [comment]
We were getting an error because the global url was invalid and the version line did not specify its own url. We specified the url in the version and Chris' question was whether the global url was needed in that case.
