### ISSUE TITLE
Cannot concretize ALL R packages together with clingo

### ISSUE THREAD

**Issue by jacorvar** [LLNL/spack#25537]
### Steps to reproduce

I've created an environment including ALL R packages (through `$ spack add $(spack list r-*)`) with the following config:
```yaml
spack:
  concretization: together
  config:
    concretizer: clingo
  view: true
  packages:
    r:
      variants: +X+rmath
  specs:
  ...
```
I'd like to concretize everything together in order to have one single package version if possible.

### Error message

However, I get the following error when concretizing:

```bash
$ spack -d --stacktrace concretize
lib/spack/spack/cmd/__init__.py:122 ==> [2021-08-20-14:03:48.623104] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-08-20-14:03:48.623944] Imported concretize from built-in commands
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:48.854255] Reading config file /usr/local/spack/var/spack/environments/r-4/spack.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:48.999403] Reading config file /usr/local/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:49.015392] Reading config file /usr/local/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:371 ==> [2021-08-20-14:03:49.050570] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:375 ==> [2021-08-20-14:03:49.051072] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:49.052297] Reading config file /usr/local/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:371 ==> [2021-08-20-14:03:49.069085] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:375 ==> [2021-08-20-14:03:49.069577] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:402 ==> [2021-08-20-14:03:49.070025] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:414 ==> [2021-08-20-14:03:49.071512] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/usr/local/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:415 ==> [2021-08-20-14:03:49.072101] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/usr/local/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:414 ==> [2021-08-20-14:03:49.072614] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
lib/spack/spack/bootstrap.py:415 ==> [2021-08-20-14:03:49.073029] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
lib/spack/spack/bootstrap.py:414 ==> [2021-08-20-14:03:49.073473] [BOOTSTRAP CONFIG SCOPE] name=site, path=/usr/local/spack/etc/spack
lib/spack/spack/bootstrap.py:415 ==> [2021-08-20-14:03:49.073825] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/usr/local/spack/etc/spack/linux
lib/spack/spack/bootstrap.py:414 ==> [2021-08-20-14:03:49.074145] [BOOTSTRAP CONFIG SCOPE] name=user, path=/usr/local/spack/.spack
lib/spack/spack/bootstrap.py:415 ==> [2021-08-20-14:03:49.074502] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/usr/local/spack/.spack/linux
lib/spack/spack/bootstrap.py:465 ==> [2021-08-20-14:03:49.100824] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:300 ==> [2021-08-20-14:03:49.101364] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:49.102323] Reading config file /usr/local/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:49.203053] Reading config file /usr/local/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:85 ==> [2021-08-20-14:03:49.319866] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /kt74l7kjzrlp3cgtj2576o33mhsrgyrw" provides the "clingo" Python module
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:49.320304] Reading config file /usr/local/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:52.286540] Reading config file /usr/local/spack/.spack/linux/compilers.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:52.293348] Reading config file /usr/local/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:989 ==> [2021-08-20-14:03:52.506650] Reading config file /usr/local/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/solver/asp.py:203 ==> [2021-08-20-14:04:20.836976] The following constraints are unsatisfiable:
  condition(3292)
  condition(4055)
  condition(6655)
  dependency_condition(3292,"r-aer","r-car")
  dependency_condition(4055,"r-car","r-pbkrtest")
  dependency_condition(6655,"r-pbkrtest","r-lme4")
  dependency_type(3292,"build")
  dependency_type(4055,"build")
  dependency_type(6655,"build")
  imposed_constraint(6655,"version_satisfies","r-lme4","1.1.10:")
  root("r-aer")
lib/spack/spack/concretize.py:737 ==> [2021-08-20-14:04:20.842562] Error: Unsatisfiable spec.
Traceback (most recent call last):
  File "/usr/local/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/local/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/usr/local/spack/lib/spack/spack/cmd/concretize.py", line 37, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/usr/local/spack/lib/spack/spack/environment.py", line 1134, in concretize
    return self._concretize_together(tests=tests)
  File "/usr/local/spack/lib/spack/spack/environment.py", line 1173, in _concretize_together
    concrete_specs = spack.concretize.concretize_specs_together(
  File "/usr/local/spack/lib/spack/spack/concretize.py", line 728, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/usr/local/spack/lib/spack/spack/concretize.py", line 737, in _concretize_specs_together_new
    tty.die("Unsatisfiable spec.")
  File "/usr/local/spack/lib/spack/llnl/util/tty/__init__.py", line 275, in die
    sys.exit(1)
SystemExit: 1
```
According to [#23307](https://github.com/spack/spack/pull/23307), this was already fixed, although it seems to persist.

### Information on your system

* **Spack:** 0.16.2-3961-d52a1b8279
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Hmm, are you sure that all the R packages can be concretized together? This is not the same issue as #23307 but is actually pointing to some conflict. Can you try to reduce the reproducer to something smaller by removing as many packages as possible in a way that `r-aer` still fails?

**Comment by jacorvar** [comment]
I'm pretty sure almost ALL (with a couple of exceptions out of ~900) R packages can be concretized together, at least with the following version (I know it's CentOS and not Ubuntu, should I expect a difference related to OS?):
```bash
$ spack debug report
* **Spack:** 0.16.1-1622-e9c3991
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** original
```
The following configuration (removing `config: concretizer: clingo` in the config) works when concretizing (with spack 0.16.2-3961-d52a1b8279):
```
spack:
  concretization: together
  packages:
    r:
      variants: +X+rmath
    harfbuzz:
      variants: +graphite2
  view: true
  specs:
  - r-a4
  - r-a4base
  - r-a4classif
  - r-a4core
  - r-a4preproc
  - r-a4reporting
  - r-abadata
  - r-abaenrichment
  - r-abind
  - r-absseq
  - r-acde
  - r-acepack
  - r-acgh
  - r-acme
  - r-ada
  - r-adabag
  - r-ade4
  - r-adegenet
  - r-adegraphics
  - r-adephylo
  - r-adespatial
  - r-adgoftest
  - r-adsplit
  - r-aer
  - r-afex
```

However, setting the concretizer to clingo (through `config: concretizer: clingo` in the config) results again in the same problem:
```
==> [2021-09-01-14:38:57.586697] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /kt74l7kjzrlp3cgtj2576o33mhsrgyrw" provides the "clingo" Python module
==> [2021-09-01-14:38:57.587316] Reading config file /tmp/usr/local3/spack/etc/spack/defaults/repos.yaml
==> [2021-09-01-14:39:01.414774] Reading config file /home/juan/.spack/linux/compilers.yaml
==> [2021-09-01-14:39:01.436664] Reading config file /tmp/usr/local3/spack/etc/spack/defaults/config.yaml
==> [2021-09-01-14:39:01.676759] Reading config file /tmp/usr/local3/spack/etc/spack/defaults/packages.yaml
==> [2021-09-01-14:39:15.819151] The following constraints are unsatisfiable:
  condition(3154)
  condition(3256)
  condition(3765)
  dependency_condition(3154,"r-aer","r-car")
  dependency_condition(3256,"r-car","r-pbkrtest")
  dependency_condition(3765,"r-pbkrtest","r-lme4")
  dependency_type(3154,"build")
  dependency_type(3256,"build")
  dependency_type(3765,"build")
  imposed_constraint(3765,"version_satisfies","r-lme4","1.1.10:")
  root("r-aer")
==> [2021-09-01-14:39:15.820718] Error: Unsatisfiable spec.
Traceback (most recent call last):
  File "/tmp/usr/local3/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/tmp/usr/local3/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/tmp/usr/local3/spack/lib/spack/spack/cmd/concretize.py", line 37, in concretize
    concretized_specs = env.concretize(force=args`force, tests=tests)
  File "/tmp/usr/local3/spack/lib/spack/spack/environment.py", line 1134, in concretize
    return self._concretize_together(tests=tests)
  File "/tmp/usr/local3/spack/lib/spack/spack/environment.py", line 1173, in _concretize_together
    concrete_specs = spack.concretize.concretize_specs_together(
  File "/tmp/usr/local3/spack/lib/spack/spack/concretize.py", line 728, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/tmp/usr/local3/spack/lib/spack/spack/concretize.py", line 737, in _concretize_specs_together_new
    tty.die("Unsatisfiable spec.")
  File "/tmp/usr/local3/spack/lib/spack/llnl/util/tty/__init__.py", line 275, in die
    sys.exit(1)
SystemExit: 1
```
