### ISSUE TITLE
Slepc python error

### ISSUE THREAD

**Issue by jppelteret** [LLNL/spack#2555]
I'm building `slepc` as part of the `deal.II`, and have specified a variant for the boost library in `packages.yaml` to ensure that only one version of `boost` gets built
```
  boost: # Variant list is crazy to ensure that all deal.II dependencies build against only one boost!
    version: [1.62.0]
    variants: +atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math+mpi+multithreaded+program_options+python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave
```

However, this leads to a configure-time error in the `slepc` package:
```
==> './configure' '--prefix=/Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/slepc-3.7.3-ex2bi2nxjf3t3mp7yy6spvy6noornf4b' '--with-arpack-dir=/Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/arpack-ng-3.4.0-ujwyurf4pgh5vz2gzyfhl34ikpdtlep4/lib' '--with-arpack-flags=-lparpack,-larpack'
Traceback (most recent call last):
  File "./configure", line 10, in <module>
    execfile(os.path.join(os.path.dirname(__file__), 'config', 'configure.py'))
  File "./config/configure.py", line 140, in <module>
    import slepc, petsc, arpack, blzpack, trlan, feast, primme, blopex, sowing, lapack
  File "/private/var/folders/lc/b4bjrtcn69d279m6rf4f42y00000gn/T/jp/spack-stage/spack-stage-8A_RPL/slepc-3.7.3/config/packages/petsc.py", line 22, in <module>
    import package, os, sys, commands
  File "/private/var/folders/lc/b4bjrtcn69d279m6rf4f42y00000gn/T/jp/spack-stage/spack-stage-8A_RPL/slepc-3.7.3/config/package.py", line 22, in <module>
    import os, sys, commands, tempfile, shutil, urllib, urlparse, tarfile
  File "/Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.12-pe3npk5rwg26kxq6fg4ybopjwg5fydfd/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.12-pe3npk5rwg26kxq6fg4ybopjwg5fydfd/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.12-pe3npk5rwg26kxq6fg4ybopjwg5fydfd/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.12-pe3npk5rwg26kxq6fg4ybopjwg5fydfd/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/jp/Programs/GitHub/Spack/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.12-pe3npk5rwg26kxq6fg4ybopjwg5fydfd/lib/python2.7/lib-dynload/_io.so
```

I was able to fix the problem by adding `depends_on('python @2.6:2.7')` to `slepc`'s package (which mirrors a line in `petsc`), but I'm not sure if this the "correct" fix. 

@davydden I believe that you now set a variant for `boost` in `packages.yaml`. Have you encountered this before?

**Comment by jppelteret** [comment]
Duplicate of #2534
