### ISSUE TITLE
Can't generate lmod modules for go, virtual package problem perhaps?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2567]
I'm having trouble generating `lmod` modules.  I've reduced my experiment to doing `spack install go` and a freshly spun up CentOS 7 system and then the following.

Here's what I have installed:

```
[hartzelg@delete-me spack]$ spack find
==> 19 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
autoconf@2.69  gettext@0.19.8.1                     libiconv@1.14    ncurses@6.0     tar@1.29
bzip2@1.0.6    git@2.11.0                           libsigsegv@2.10  openssl@1.0.2j  xz@5.2.2
curl@7.50.3    go@1.7.4                             libxml2@2.9.4    pcre@8.39       zlib@1.2.8
expat@2.2.0    go-bootstrap@1.4-bootstrap-20161024  m4@1.4.17        perl@5.24.0
```

I created a `modules.yaml` file like so:

```
[hartzelg@delete-me spack]$ cat ~/.spack/modules.yaml
modules:
  enable::
    - lmod
  lmod:
    hash_length: 0
```

and then tried to refresh the modules like so:

```
[hartzelg@delete-me spack]$ spack module refresh --module-type lmod --delete-tree -y
==> Regenerating lmod module files
Traceback (most recent call last):
  File "/home/hartzelg/spack/bin/spack", line 198, in <module>
    main()
  File "/home/hartzelg/spack/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/home/hartzelg/spack/lib/spack/spack/cmd/module.py", line 252, in module
    callbacks[args.subparser_name](module_type, specs, args)
  File "/home/hartzelg/spack/lib/spack/spack/cmd/module.py", line 236, in refresh
    x.write(overwrite=True)
  File "/home/hartzelg/spack/lib/spack/spack/modules.py", line 388, in write
    self.spec.package.setup_environment(spack_env, env)
  File "/home/hartzelg/spack/var/spack/repos/builtin/packages/go/package.py", line 108, in setup_environment
    spack_env.set('GOROOT_BOOTSTRAP', self.spec['go-bootstrap'].prefix)
  File "/home/hartzelg/spack/lib/spack/spack/spec.py", line 2284, in __getitem__
    raise KeyError("No spec with name %s in %s" % (name, self))
KeyError: 'No spec with name go-bootstrap in go@1.7.4%gcc@4.8.5+test arch=linux-centos7-x86_64^bzip2@1.0.6%gcc@4.8.5 arch=linux-centos7-x86_64^curl@7.50.3%gcc@4.8.5 arch=linux-centos7-x86_64^expat@2.2.0%gcc@4.8.5 arch=linux-centos7-x86_64^gettext@0.19.8.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-x86_64^git@2.11.0%gcc@4.8.5 arch=linux-centos7-x86_64^libiconv@1.14%gcc@4.8.5 arch=linux-centos7-x86_64^libxml2@2.9.4%gcc@4.8.5~python arch=linux-centos7-x86_64^ncurses@6.0%gcc@4.8.5 arch=linux-centos7-x86_64^openssl@1.0.2j%gcc@4.8.5 arch=linux-centos7-x86_64^pcre@8.39%gcc@4.8.5+utf arch=linux-centos7-x86_64^perl@5.24.0%gcc@4.8.5+cpanm arch=linux-centos7-x86_64^tar@1.29%gcc@4.8.5 arch=linux-centos7-x86_64^xz@5.2.2%gcc@4.8.5 arch=linux-centos7-x86_64^zlib@1.2.8%gcc@4.8.5+pic arch=linux-centos7-x86_64'
```

I *think* that what's going on has something to do with `go-bootstrap` being a virtual package, but I'm not sure what to do beyond that.

I don't think that `GOROOT_BOOTSTRAP` is relevant in the finished project, so one solution might be to arrange for it to be present during the bootstrap phase and not afterwards.  I can poke around a bit in that direction.

But it still doesn't seem like module generation should fail in this particular way.

http://spack.readthedocs.io/en/latest/tutorial_sc16_modules.html

**Comment by hartzell** [comment]
@alalazo -- I did read the tutorial, but I may have missed something... 😄

**Comment by hartzell** [comment]
These environment variables (from `go/package.py`, similar in `go-bootstrap`)

```
    def setup_environment(self, spack_env, run_env):
        spack_env.set('GOROOT_FINAL', self.spec.prefix)
        spack_env.set('GOROOT_BOOTSTRAP', self.spec['go-bootstrap'].prefix)
```

are only used in the build step.  

Would it be correct to just add a couple of `env['...']` statements before [line 94](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/go/package.py#L94) and would it have the same effect of setting them for that base step?

**Comment by hartzell** [comment]
I made the change mentioned above, and it builds a functional go and I can generate lua modules for it.  PR is #2577.

@alalazo is this an issue to keep open for investigation?  Should "I" hold off on merging the #2577?

**Comment by alalazo** [comment]
@hartzell Keep this open: the fact that this happened for a virtual package rings a bell. I remember I encountered some odd behavior in the DAG during module generation phase and I wonder if this could come from there. I'll try to have a look asap.

**Comment by hartzell** [comment]
Ok.  No panic on my end, though it's a loose thread I'd like to tie off.  Don't stay up all night for it... ;)

**Comment by alalazo** [comment]
The ultimate problem is that during module creation `go` has only one dependency, which is `git` (build, link, run) therefore the `KeyError` above. This is due to the fact that:

1. during module refresh the `spec` is retrieved from the db
2. `build` only dependencies are not stored in the db
3. and even if they were we don't traverse build only dependencies during module creation

Point 1 is necessary because [here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/cmd/module.py#L248) we need to filter on the spec being installed and known. 

**The problem is general and will be revealed by any package that in `setup_environment` & Co. tries to get a build-only dependency.**

A possible general solution is to:
- split `setup_environment` into `setup_run_environment` and `setup_spack_environment`
- do the same for `setup_dependent_environment`
- document that in `*_run_environment` build-only dependencies are not present


That said `go` seems to be quite involved on its own: `go` provides `golang` and depends on (type build) `go-bootstrap` which is also providing `golang`. Can we make bootstrapping part of `go` installation and get rid of the `go-bootstrap` package?

---

OT: I tested this on `--fake` installations because I couldn't build `go` on `ubuntu14` or `rhel6` due to errors involving `gettext`.

**Comment by alalazo** [comment]
@trws Just pinging in case you are interested in the issue

**Comment by trws** [comment]
Thanks @alalazo.  The odd golang dependency structure is because spack can't have a package depend on another version of itself (which would solve the issue), so we have go-bootstrap which can in principle be fulfilled by either gcc or a special old version of go that can be bootstrapped with c.  It's a pain, but it's the best I could come up with at the time.

Since those environment variables are build only, setting them for the bash env would be sufficient to take care of this particular case.

**Comment by hartzell** [comment]
@trws -- I've never tried to bootstrap a "modern" go release via gccgo.  Have you?  Is it simple (simpler than go-bootstrap?)?

@alalazo -- I'd like to clean up the go package by merging #2577.  If this is the only package that's walked into this particular lamp-post then I think your "possible general solution" above falls into the "You Ain't Gonna Need It" land.  It seems like there are bigger fish to fry.

**Comment by hartzell** [comment]
@alalazo 

> OT: I tested this on --fake installations because I couldn't build go on ubuntu14 or rhel6 due to errors involving gettext.

Is that gettext problem well known or newly discovered?

**Comment by alalazo** [comment]
@hartzell Try to have a look at #2588 (I asked for your review there). It's an alternative for #2577 that just touches `go`. The `gettext` problem seems to be due to include order and is [well know in the GNU community](https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined), but I didn't investigate it further.

**Comment by trws** [comment]
I haven't tried it since 1.6, but yes I've built with gcc-go with success, and originally had support in the spack packages for it as well (hence the virtual for golang and go-bootstrap deps). It's "easier" in that it's a clear dependency, but it takes much, much longer to build a gcc tool chain than to build an old go 1.4 with a system C toolchain.

In the end, the real issue as far as go is concerned is that there's no way to register a golang compiler as a compiler to spack, until that happens it's going to remain a bit odd for any self-hosted language that isn't c or fortran.




On December 14, 2016 at 3:17:38 PM PST, George Hartzell <notifications@github.com> wrote:

@trws<https://github.com/trws> -- I've never tried to bootstrap a "modern" go release via gccgo. Have you? Is it simple (simpler than go-bootstrap?)?

@alalazo<https://github.com/alalazo> -- I'd like to clean up the go package by merging #2577<https://github.com/LLNL/spack/pull/2577>. If this is the only package that's walked into this particular lamp-post then I think your "possible general solution" above falls into the "You Ain't Gonna Need It" land. It seems like there are bigger fish to fry.

-

**Comment by alalazo** [comment]
> I think your "possible general solution" above falls into the "You Ain't Gonna Need It" land. It seems like there are bigger fish to fry.

I agree: though it won't take a long time, it will touch a lot of files and every time you do something like this you have a chance of compromising some part of the code. And that would slow-down `v0.10`. So not a good time to do (or at least merge) this.

**Comment by tgamblin** [comment]
Fixed by #2588.
