### ISSUE TITLE
gpg publish command failing with `'NoneType' object has no attribute 'geturl'`

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/spack#25765]
### Steps to reproduce

```console
$ spack gpg list # Key is available
gpgconf: socketdir is '/run/user/0/gnupg'
/spack/opt/spack/gpg/pubring.kbx
--------------------------------
pub   rsa4096 2021-09-01 [SC]
      F9A3E0868809828374551412E1E35A1C6F84D69D
uid           [ultimate] Asher Mancinelli (GPG created for Spack) <ashermancinelli@gmail.com>
$ ls /cache/build_cache/_pgp # key exists in local buildcache
F9A3E0868809828374551412E1E35A1C6F84D69D.pub
$ spack mirror list # Mirror exists and contains packages 
minio           s3://spack
spack-public    https://mirror.spack.io
$ spack buildcache list # s3 is working
==> 1 cached build.
-- linux-ubuntu18.04-haswell / gcc@7.5.0 ------------------------
pkgconf@1.8.0
$ # GPG command used by failing spack command seems to work
$ GNUPGHOME=/spack/opt/spack/gpg/ '/usr/bin/gpg' '--list-public-keys' '--with-colons' '--fingerprint' 'F9A3E0868809828374551412E1E35A1C6F84D69D'
tru::1:1630537839:0:3:1:5
pub:u:4096:1:E1E35A1C6F84D69D:1630537392:::u:::scSC::::::23::0:
fpr:::::::::F9A3E0868809828374551412E1E35A1C6F84D69D:
uid:u::::1630537392::A3B3981D3131BF52CE3F912F236C5D1DF3BEA310::Asher Mancinelli (GPG created for Spack) <ashermancinelli@gmail.com>::::::::::0:
$ spack --debug gpg publish -m minio F9A3E0868809828374551412E1E35A1C6F84D69D
==> [2021-09-02-22:01:36.416531] Imported gpg from built-in commands
==> [2021-09-02-22:01:36.418643] Imported gpg from built-in commands
==> [2021-09-02-22:01:36.419643] '/usr/bin/gpg' '--version'
==> [2021-09-02-22:01:36.423000] '/usr/bin/gpgconf' '--version'
==> [2021-09-02-22:01:36.425094] '/usr/bin/gpgconf' '--dry-run' '--create-socketdir'
gpgconf: socketdir is '/run/user/0/gnupg'
==> [2021-09-02-22:01:36.427409] '/usr/bin/gpgconf' '--create-socketdir'
==> [2021-09-02-22:01:36.429513] '/usr/bin/gpg' '--list-public-keys' '--with-colons' '--fingerprint' 'F9A3E0868809828374551412E1E35A1C6F84D69D'
==> [2021-09-02-22:01:36.433820] Reading config file /spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/gpg.py", line 212, in gpg
    args.func(args)
  File "/spack/lib/spack/spack/cmd/gpg.py", line 207, in gpg_publish
    mirror, keys=args.keys, regenerate_index=args.rebuild_index)
  File "/spack/lib/spack/spack/binary_distribution.py", line 1598, in push_keys
    _build_cache_keys_relative_path)
  File "/spack/lib/spack/spack/util/url.py", line 151, in join
    for x in itertools.chain((base_url, path), extra)]
  File "/spack/lib/spack/spack/util/url.py", line 151, in <listcomp>
    for x in itertools.chain((base_url, path), extra)]
AttributeError: 'NoneType' object has no attribute 'geturl'
```

### Error message

```console
$ spack --debug gpg publish -m minio F9A3E0868809828374551412E1E35A1C6F84D69D
==> [2021-09-02-22:01:36.416531] Imported gpg from built-in commands
==> [2021-09-02-22:01:36.418643] Imported gpg from built-in commands
==> [2021-09-02-22:01:36.419643] '/usr/bin/gpg' '--version'
==> [2021-09-02-22:01:36.423000] '/usr/bin/gpgconf' '--version'
==> [2021-09-02-22:01:36.425094] '/usr/bin/gpgconf' '--dry-run' '--create-socketdir'
gpgconf: socketdir is '/run/user/0/gnupg'
==> [2021-09-02-22:01:36.427409] '/usr/bin/gpgconf' '--create-socketdir'
==> [2021-09-02-22:01:36.429513] '/usr/bin/gpg' '--list-public-keys' '--with-colons' '--fingerprint' 'F9A3E0868809828374551412E1E35A1C6F84D69D'
==> [2021-09-02-22:01:36.433820] Reading config file /spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/gpg.py", line 212, in gpg
    args.func(args)
  File "/spack/lib/spack/spack/cmd/gpg.py", line 207, in gpg_publish
    mirror, keys=args.keys, regenerate_index=args.rebuild_index)
  File "/spack/lib/spack/spack/binary_distribution.py", line 1598, in push_keys
    _build_cache_keys_relative_path)
  File "/spack/lib/spack/spack/util/url.py", line 151, in join
    for x in itertools.chain((base_url, path), extra)]
  File "/spack/lib/spack/spack/util/url.py", line 151, in <listcomp>
    for x in itertools.chain((base_url, path), extra)]
AttributeError: 'NoneType' object has no attribute 'geturl'
```

### Information on your system

Running in container ubuntu:18.04 with:
* **Spack:** 0.16.2-4117-03331de0f2
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-haswell
* **Concretizer:** original

with host:
* **Spack:** 0.16.2-4108-56ba3448db
* **Python:** 3.8.3
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by ashermancinelli** [comment]
@opadron As per convo on slack
