### ISSUE TITLE
Installation issue: distributed build of Trilinos

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#25840]
### Steps to reproduce the issue

@sethrj @kubery @keiat I am having problems with building Trilinos via `srun`.  I am able to build every other package in my DAG (~20) but not Trilinos.  It seems that the the compute nodes are always trying to restage `Trilinos` and I'm not sure why.  This could be a bigger issue in spack, but I only have this problem with `Trilinos`. The stage directory is not/should not be in a tmp dir
```
spack config blame config
---                                                                    config:
/projects/wind/spack-manager/environments/test/general_config.yaml:2     source_cache: ~/.spack/downloads
/projects/wind/spack-manager/environments/test/general_config.yaml:3     misc_cache: $spack/var/spack/cache
/projects/wind/spack-manager/environments/test/machine_config.yaml:2     module_roots:
/projects/wind/spack-manager/environments/test/machine_config.yaml:3       tcl: $spack/share/spack/modules
/projects/wind/spack-manager/environments/test/machine_config.yaml:4       lmod: $spack/share/spack/lmod
/projects/wind/spack-manager/environments/test/machine_config.yaml:5     build_stage:
/projects/wind/spack-manager/environments/test/machine_config.yaml:6     - $spack/var/spack/stage
/projects/wind/spack-manager/spack/etc/spack/defaults/config.yaml:62     - $tempdir/$user/spack-stage
/projects/wind/spack-manager/spack/etc/spack/defaults/config.yaml:63     - ~/.spack/stage
/projects/wind/spack-manager/spack/etc/spack/defaults/config.yaml:63     # - $spack/var/spack/stage
```
and  the stage on the compute nodes is indeed not in `$tmpdir`
```
srun -N 2 -n 2 spack location -s trilinos
/projects/wind/spack-manager/spack/var/spack/stage/psakiev/spack-stage-trilinos-develop-lqi4j65eqwl2vhfhzakngqzso4c6753u
/projects/wind/spack-manager/spack/var/spack/stage/psakiev/spack-stage-trilinos-develop-lqi4j65eqwl2vhfhzakngqzso4c6753u
```
However.  When I go to install even if I prestage I am getting the same failures about being unable to copy files
```
srun -N 1 -n 1 spack -d install -j 32
[... lots of debug stuff ...]
==> [2021-09-02-12:45:10.267256] Installing trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp
==> [2021-09-02-12:45:10.875471] No binary for trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp found: installing from source
==> [2021-09-02-12:45:04.679498] Removing netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka's uninstalled dependencies.
==> [2021-09-02-12:45:04.679574] amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka: Removed netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from uninstalled deps list: set()
==> [2021-09-02-12:45:04.679627] Removing netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu's uninstalled dependencies.
==> [2021-09-02-12:45:04.679689] nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu: Removed netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from uninstalled deps list: set()
==> [2021-09-02-12:45:04.679740] Removing netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp's uninstalled dependencies.
==> [2021-09-02-12:45:04.679800] trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp: Removed netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from uninstalled deps list: set()
==> [2021-09-02-12:45:04.679851] Removing netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs's uninstalled dependencies.
==> [2021-09-02-12:45:04.679913] nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs: Removed netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r from uninstalled deps list: {'nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu', 'trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp'}
==> [2021-09-02-12:45:04.680018] Downgrading to a read lock on netcdf-c-4.7.4-ar7anl7cafchmdbejayrn2e2bhrgdn7r with timeout 1e-09
==> [2021-09-02-12:45:04.685851] Acquiring a write lock on amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka with timeout 1e-09
==> [2021-09-02-12:45:04.693245] Creating stage lock spack-stage-amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka
==> [2021-09-02-12:45:04.693372] Flagging amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka as installed
==> [2021-09-02-12:45:04.693419] Removing amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka from exawind-master-qcywy7eq3chafzx5hsoljy6cgrpv2yym's uninstalled dependencies.
==> [2021-09-02-12:45:04.693485] exawind-master-qcywy7eq3chafzx5hsoljy6cgrpv2yym: Removed amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka from uninstalled deps list: {'nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs'}
==> [2021-09-02-12:45:04.693600] Downgrading to a read lock on amr-wind-main-mjwor5xjzcmpabexkc27wtwgglri2aka with timeout 1e-09
==> [2021-09-02-12:45:04.700952] Acquiring a write lock on nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu with timeout 1e-09
==> [2021-09-02-12:45:04.708598] Creating stage lock spack-stage-nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu
==> [2021-09-02-12:45:04.708724] Flagging nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu as installed
==> [2021-09-02-12:45:04.708772] Removing nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu from nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs's uninstalled dependencies.
==> [2021-09-02-12:45:04.708838] nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs: Removed nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu from uninstalled deps list: {'trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp'}
==> [2021-09-02-12:45:04.708944] Downgrading to a read lock on nccmp-1.9.0.1-5pgxojsvjxix6ssucrgzho7wxteeorzu with timeout 1e-09
==> [2021-09-02-12:45:04.715492] Acquiring a write lock on trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp with timeout 1e-09
==> [2021-09-02-12:45:04.744559] Creating stage lock spack-stage-trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp
==> [2021-09-02-12:45:10.266914] FileNotFoundError: [Errno 2] No such file or directory
==> [2021-09-02-12:45:10.267389] Searching for binary cache of trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp
==> [2021-09-02-12:45:10.269445] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/mirrors.yaml
==> [2021-09-02-12:45:10.875175] Did not find linux-rhel7-x86_64-gcc-8.3.1-trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp.spec.yaml on https://mirror.spack.io/build_cache/linux-rhel7-x86_64-gcc-8.3.1-trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2021-09-02-12:45:10.884124] Reading config file /projects/wind/spack-manager/spack/etc/spack/defaults/packages.yaml
==> [2021-09-02-12:45:11.216354] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
Cloning into 'Trilinos'...
error: unable to write file packages/rol/src/function/objective/ROL_Objective.hpp
error: unable to write file packages/rol/src/function/objective/ROL_ObjectiveDef.hpp
error: unable to write file packages/rol/src/function/objective/ROL_ObjectiveFromConstraint.hpp
error: unable to write file packages/rol/src/function/objective/ROL_ObjectiveFromConstraint_Def.hpp
error: unable to write file packages/rol/src/function/objective/ROL_QuadraticObjective.hpp
error: unable to write file packages/rol/src/function/objective/ROL_QuadraticObjective_Def.hpp
error: unable to write file packages/rol/src/function/objective/ROL_SlacklessObjective.hpp
[.. all the files of trilinos not found...]
[... more debug stuff...]
==> [2021-09-02-12:45:20.477447] linkdir: /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../..
==> [2021-09-02-12:45:20.477502] found raw link dirs: /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8, /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../..
==> [2021-09-02-12:45:20.477642] found link dirs: /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8, /opt/rh/devtoolset-8/root/usr/lib64, /lib64, /usr/lib64, /opt/rh/devtoolset-8/root/usr/lib
==> [2021-09-02-12:45:20.488762] Checking existence of https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-09-02-12:45:21.036350] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
    Urllib fetch failed to verify url https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz
==> [2021-09-02-12:45:21.036677] Checking existence of https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-09-02-12:45:21.592720] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
    Urllib fetch failed to verify url https://mirror.spack.io/trilinos/trilinos-develop.tar.gz
==> [2021-09-02-12:45:21.593285] Cloning git repository: https://github.com/trilinos/Trilinos.git on branch develop
==> [2021-09-02-12:45:21.606952] '/usr/bin/git' '--version'
==> [2021-09-02-12:45:21.615460] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-09-02-12:45:21.623451] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2021-09-02-12:45:21.629855] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
==> [2021-09-02-12:45:52.245411] ProcessError: Command exited with status 128:
==> [2021-09-02-12:45:21.629855] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
==> [2021-09-02-12:45:52.245411] ProcessError: Command exited with status 128:
    '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
==> [2021-09-02-12:45:52.245715] Fetching from https://mirror.spack.io/_source-cache/git/trilinos/Trilinos.git/develop.tar.gz failed.
==> [2021-09-02-12:45:52.245767] Fetching from https://mirror.spack.io/trilinos/trilinos-develop.tar.gz failed.
==> [2021-09-02-12:45:52.245808] Fetching from [git] https://github.com/trilinos/Trilinos.git on branch develop failed.
==> [2021-09-02-12:45:52.272071] Error: FetchError: All fetchers failed

/projects/wind/spack-manager/spack/lib/spack/spack/package.py:1376, in do_fetch:
       1373
       1374        self.stage.create()
       1375        err_msg = None if not self.manual_download else self.download_instr
  >>   1376        start_time = time.time()
       1377        self.stage.fetch(mirror_only, err_msg=err_msg)
       1378        self._fetch_time = time.time() - start_time
       1379


Traceback (most recent call last):
  File "/projects/wind/spack-manager/spack/lib/spack/spack/build_environment.py", line 1022, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/installer.py", line 1898, in build_process
    return installer.run()
  File "/projects/wind/spack-manager/spack/lib/spack/spack/installer.py", line 1735, in run
    self.pkg.do_patch()
  File "/projects/wind/spack-manager/spack/lib/spack/spack/package.py", line 1413, in do_patch
    self.do_stage()
  File "/projects/wind/spack-manager/spack/lib/spack/spack/package.py", line 1398, in do_stage
    self.do_fetch(mirror_only)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/package.py", line 1377, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 23, in __call__
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/util/pattern.py", line 23, in <listcomp>
    for item in self.container]
  File "/projects/wind/spack-manager/spack/lib/spack/spack/stage.py", line 507, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
==> [2021-09-02-12:45:52.273301] Flagging trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp as failed: FetchError: All fetchers failed
==> [2021-09-02-12:45:52.290133] Warning: Skipping build of nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs since trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp failed
==> [2021-09-02-12:45:52.290193] Flagging nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs as failed
==> [2021-09-02-12:45:52.305467] Warning: Skipping build of exawind-master-qcywy7eq3chafzx5hsoljy6cgrpv2yym since nalu-wind-master-gztjtf2ejackc6okhfq2uqydowpy3urs failed
==> [2021-09-02-12:45:52.305525] Flagging exawind-master-qcywy7eq3chafzx5hsoljy6cgrpv2yym as failed
==> [2021-09-02-12:45:52.345254] Downgrading to a read lock on trilinos-develop-5ovgze5t4bflekt3gw3z3owbchx6ppsp with timeout 1e-09
==> [2021-09-02-12:45:52.379123] Error: exawind-master-qcywy7eq3chafzx5hsoljy6cgrpv2yym: Package was not installed
==> [2021-09-02-12:45:52.682474] Skip view update, this environment does not maintain a view
==> [2021-09-02-12:45:52.683746] InstallError: Installation request failed.  Refer to reported errors for failing package(s).
==> [2021-09-02-12:45:52.683802] Error: Installation request failed.  Refer to reported errors for failing package(s).
Traceback (most recent call last):
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/cmd/install.py", line 359, in install
    env.install_all(**kwargs)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/environment.py", line 1483, in install_all
    self.install_specs(None, **install_args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/environment.py", line 1523, in install_specs
    builder.install()
  File "/projects/wind/spack-manager/spack/lib/spack/spack/installer.py", line 1679, in install
    raise InstallError('Installation request failed.  Refer to '
spack.installer.InstallError: Installation request failed.  Refer to reported errors for failing package(s).
srun: error: sb1299: task 0: Exited with exit code 1
```
I am able to build fine on the head node. This is only a problem on the compute nodes.

### Information on your system

```
* **Spack:** 0.16.2-4107-beb3524392
* **Python:** 3.6.8
* **Platform:** linux-rhel7-sandybridge
* **Concretizer:** clingo
```

### Additional information

The stage directory is empty when `srun` terminates so there is no build log or environment file available.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
Trilinos is one of the few packages that uses "resources" when it clones, and resources inside a parallel build might hit some sort of edge case.

**Comment by psakievich** [comment]
would someone else please try this out and see if it is just my system or an actual bug in spack?  @sethrj where do the resources get cloned? are they not in the same stage directory? if the resources aren't being cloned when I do `spack stage` then that seems like it could be a bug to me. I also tried staging the exact spec from concretization just in case this was the case.

**Comment by sethrj** [comment]
@psakievich Looking more carefully at your build log it appears that trilinos itself rather than one of its resources is failing to clone. Is it possible that there's a disk space issue or some other problem using your git in your home directory on a compute node? Does trilinos build when using only a single job on the compute node? Can you run
```
'/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/trilinos/Trilinos.git'
```
on a compute node in the stage directory?

**Comment by psakievich** [comment]
@sethrj I tried this script:
```
[psakiev@skybridge-login3 dist]$ more copy_test_script.sh 
#! /bin/bash
source /projects/wind/spack-manager/spack/share/spack/setup-env.sh
spack env activate /projects/wind/spack-manager/environments/dist/
cd $(spack location -s trilinos)
/usr/bin/git -c advice.detachedHead=false clone --branch develop --single-branch --depth 1 https://github.com/trilinos/Trilinos.git
```
and it seems to clone fine.
```
[psakiev@skybridge-login3 dist]$ srun -N 1 -n 1 copy_test_script.sh                                                                                                                                                                                                                                                                                                                                                                                                                
Cloning into 'Trilinos'...
Updating files: 100% (51897/51897), done.
[psakiev@skybridge-login3 dist]$ ls $(spack location -s trilinos)
Trilinos
[psakiev@skybridge-login3 dist]$ ls $(spack location -s trilinos)/Trilinos
checkin-test.py  clone_extra_repos.py  cmake  CMakeLists.txt  commonTools  _config.yml  CONTRIBUTING.md  Copyright.txt  CTestConfig.cmake  demos  doc  INSTALL  INSTALL.rst  LICENSE  packages  PackagesList.cmake  project-checkin-test-config.py  ProjectName.cmake  README  README.md  RELEASE_NOTES  sampleScripts  sparse_checkout.sh  TPLsList.cmake  Version.cmake
```
I tried with `srun spack install` right after this and it still fails.

**Comment by psakievich** [comment]
@sethrj I partially figured out the problem.  When the fetch operation is called it is done in a temp directory directly in spack that is not the stage directory, and then the files are copied from that temp dir to the stage later.

https://github.com/spack/spack/blob/f6eb16982ab2e7b9c2931281ca48acb9ebc07c1e/lib/spack/spack/fetch_strategy.py#L941-L947

This is indeed in a location that does not have enough storage to support cloning `Trilinos` on the compute nodes.  I put a print statement in `temp_cwd` and it gives the following location
```
trying fetcher: [git] https://github.com/trilinos/Trilinos.git on branch develop
stage dir <spack.stage.Stage object at 0x2aaab9a71ac8>
Creating temp dir:  /tmp/tmpxwkygzre
SystemExit: None
```

Looking in `tempfile.py` it looks like I can get around this by setting an environment variable like `TMPDIR`. (EDIT: looks like I just set it and it works now)

**Comment by psakievich** [comment]
I'm not sure why if I pre-stage the files I still get the error though.  It seems like there should be no need to run the `git clone` operation in `$TMPDIR` for that case.  I haven't really tracked that down. But this does explain why all my other packages in the DAG are building fine except `Trilinos`. `Trilinos` is probably the biggest individual package I deal with.

**Comment by psakievich** [comment]
@scheibelp out of curiosity why do we do this clone to `tmp` and then copy files over? Is there a performance advantage over just cloning to the stage directory?

**Comment by psakievich** [comment]
I'm just going to close this. Sounds like @becker33 and @tgamblin have plans to rework this staging procedure in the future.

**Comment by sethrj** [comment]
Nice debugging work @psakievich , sorry I wasn't any more help!
