### ISSUE TITLE
Spack concretisation issue on Cray KNL ('NoneType' object has no attribute 'to_cmp_dict')

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2587]
On the Cray KNL system I see : 

```
$ spack arch
cray-CNL-mic_knl

$ spack spec tau
Input spec
--------------------------------
tau
Normalized
--------------------------------
tau
    ^pdt
Concretized
--------------------------------
Traceback (most recent call last):
  File "/home/kumbhar/spack/bin/spack", line 198, in <module>
    main()
  File "/home/kumbhar/spack/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/cmd/spec.py", line 83, in spec
    spec.concretize()
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/spec.py", line 1543, in concretize
    self._concretize_helper())
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/spec.py", line 1362, in _concretize_helper
    changed |= dep.spec._concretize_helper(presets, visited)
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/spec.py", line 1362, in _concretize_helper
    changed |= dep.spec._concretize_helper(presets, visited)
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/spec.py", line 1362, in _concretize_helper
    changed |= dep.spec._concretize_helper(presets, visited)
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/spec.py", line 1372, in _concretize_helper
    (spack.concretizer.concretize_architecture(self),
  File "/xxxx/home/kumbhar/spack/lib/spack/spack/concretize.py", line 270, in concretize_architecture
    replacement_fields = [k for k, v in arch.to_cmp_dict().iteritems()
AttributeError: 'NoneType' object has no attribute 'to_cmp_dict'
```

Quickly looked into `lib/spack/spack/concretize.py` : 

```
        default_archs = [root_arch, sys_arch]
        while not spec.architecture.concrete and default_archs:
            arch = default_archs.pop(0)

            replacement_fields = [k for k, v in arch.to_cmp_dict().iteritems()
                                  if v and not getattr(spec.architecture, k)]
```

And at some point during concretisation, the value of  `default_archs` is:

```
[None, cray-sles12-None]
```

Could someone have a look?

**Comment by scheibelp** [comment]
Hi @pramodk I believe I can fix this - my target would be to have a PR before tomorrow

@tgamblin could you push https://github.com/LLNL/spack/pull/2549 (reverting the PR which assigns frontend architecture to build deps)? I'd like that to merge before fixing this.
