### ISSUE TITLE
Odd issue with already-installed oneAPI and Module Generate?

### ISSUE THREAD

**Issue by mathomp4** [LLNL/spack#25870]
### Steps to reproduce

I am on a cluster (NCCS Discover) where Intel oneAPI 2021.3 is already installed. So if I do:
```console
$ ml comp/intel/2021.3.0
$ spack compiler find
==> Added 2 new compilers to /home/mathomp4/.spack/linux/compilers.yaml
    oneapi@2021.3.0  intel@2021.3.0
==> Compilers are defined in the following files:
    /home/mathomp4/.spack/linux/compilers.yaml
```
so spack found them and in my `linux/compilers.yaml`:
```yaml
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles12
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2021.3.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/icx
      cxx: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/icpx
      f77: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/ifx
      fc: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/bin/ifx
    flags: {}
    operating_system: sles12
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
Now, I want the `ifort`, etc, so in `packages.yaml` I have:
```yaml
  intel:
    buildable: false
    externals:
    - spec: intel@2021.3.0%gcc@4.8
      modules:
        - comp/intel/2021.3.0
```
And now I want to "install" that so I can do `spack load intel@2021.3` and:
```console
$ spack install intel@2021.3.0
==> intel@2021.3.0 : has external module in ['comp/intel/2021.3.0']
[+] /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux (external intel-2021.3.0-ga2dlngst54wupld7bhytcd4qtzw3owc)
$ spack load intel@2021.3.0
==> Error: Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
```

### Error message

```console
$ spack --debug --stacktrace load intel@2021.3.0
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-09-09-11:18:42.788718] Imported load from built-in commands
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-09-09-11:18:42.789934] Imported load from built-in commands
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:42.853212] Reading config file /gpfsm/dnb44/mathomp4/spack/etc/spack/defaults/config.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:42.878304] Reading config file /home/mathomp4/.spack/config.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:42.881212] Reading config file /gpfsm/dnb44/mathomp4/spack/etc/spack/defaults/bootstrap.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/database.py:371 ==> [2021-09-09-11:18:42.908475] DATABASE LOCK TIMEOUT: 3s
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/database.py:375 ==> [2021-09-09-11:18:42.908866] PACKAGE LOCK TIMEOUT: No timeout
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:42.955524] Reading config file /gpfsm/dnb44/mathomp4/spack/etc/spack/defaults/repos.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:43.543436] Reading config file /gpfsm/dnb44/mathomp4/spack/etc/spack/defaults/modules.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:43.562110] Reading config file /gpfsm/dnb44/mathomp4/spack/etc/spack/defaults/linux/modules.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:43.572221] Reading config file /home/mathomp4/.spack/modules.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/config.py:991 ==> [2021-09-09-11:18:43.719659] Reading config file /home/mathomp4/.spack/linux/compilers.yaml
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:46 ==> [2021-09-09-11:18:43.835100] normalize_path.normalize_suite_dir:	trying /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries_2021.3.0
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:46 ==> [2021-09-09-11:18:43.835921] normalize_path.normalize_suite_dir:	trying /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries_2021.0.*
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:46 ==> [2021-09-09-11:18:43.836932] normalize_path.normalize_suite_dir:	trying /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries_*.*.*
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:46 ==> [2021-09-09-11:18:43.838024] normalize_path.normalize_suite_dir:	/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:46 ==> [2021-09-09-11:18:43.838872] file_to_source.normalize_path:	/usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py:1016 ==> [2021-09-09-11:18:43.839087] sourcing /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
gpfsm/dnb44/mathomp4/spack/lib/spack/spack/util/environment.py:643 ==> [2021-09-09-11:18:43.839309] EnvironmentModifications.from_sourcing_file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
Traceback (most recent call last):
  File "/discover/nobackup/mathomp4/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/cmd/load.py", line 79, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/user_environment.py", line 95, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/build_systems/intel.py", line 1027, in setup_run_environment
    env.extend(EnvironmentModifications.from_sourcing_file(f, *args))
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/util/environment.py", line 648, in from_sourcing_file
    raise RuntimeError(msg)
RuntimeError: Trying to source non-existing file: /usr/local/intel/oneapi/2021/compiler/2021.3.0/linux/compilers_and_libraries/linux/bin/compilervars.sh
```

### Information on your system

$ spack debug report
* **Spack:** 0.16.2-4196-e47f0d486c
* **Python:** 3.8.5
* **Platform:** linux-sles12-haswell
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Is this still an issue?

**Comment by mathomp4** [comment]
> Is this still an issue?

Hmm. I have no idea. My guess is...probably not? Though it is intel and the wacky split compilers, so...probably?

Eh. At this point, I'll close this and re-try with present day spack. Spack of 2021 is a bit old. :)
