### ISSUE TITLE
unable to detect Perlmutter system architecture

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#25914]
cc: @sleak 

### Steps to reproduce

We are unable to detect perlmutter architecture in spack. For more details see https://spackpm.slack.com/archives/C5W7NKZJT/p1631284957272400. 

I have debugged this with e4s branch `e4s-21.08` and `develop` branch and still getting same issue
```
siddiq90@login11> spack -d arch
==> [2021-09-13-09:11:21.597439] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
==> [2021-09-13-09:11:21.608167] NoPlatformError: Could not determine a platform for this machine.
==> [2021-09-13-09:11:21.608378] Error: Could not determine a platform for this machine.
Traceback (most recent call last):
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/main.py", line 774, in main
    setup_main_options(args)
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/main.py", line 478, in setup_main_options
    spack.config.set('config:debug', True, scope='command_line')
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/config.py", line 915, in set
    return config.set(path, value, scope)
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/llnl/util/lang.py", line 786, in __getattr__
    return getattr(self.instance, name)
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/llnl/util/lang.py", line 776, in instance
    self._instance = self.factory()
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/config.py", line 814, in _config
    _add_platform_scope(cfg, ConfigScope, name, path)
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/config.py", line 767, in _add_platform_scope
    platform = spack.architecture.platform().name
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/llnl/util/lang.py", line 190, in _memoized_function
    func.cache[args] = func(*args)
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/architecture.py", line 523, in _platform
    return platform_cls()
  File "/global/common/software/spackecp/perlmutter/e4s-21.08/spack/lib/spack/spack/platforms/cray.py", line 61, in __init__
    raise NoPlatformError()
spack.architecture.NoPlatformError: Could not determine a platform for this machine.
```

### Information on your system

```
siddiq90@login11> spack debug report
* **Spack:** 0.16.2-4211-d54a692e09
* **Python:** 3.6.12
==> Error: Could not determine a platform for this machine.
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by bvanessen** [comment]
@bvanessen I am also experiencing this.
