### ISSUE TITLE
Installation issue: cannot install package 

### ISSUE THREAD

**Issue by davinwei** [LLNL/spack#26052]
### Steps to reproduce the issue

i just do following 
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
$ cd spack/bin
$ ./spack install gcc@8.3.0 
==> Bootstrapping clingo from pre-built binaries
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64"

### Information on your system

my linux is centos7.9

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Can you share the output for `spack -d spec zlib`?

**Comment by davinwei** [comment]
> Can you share the output for `spack -d spec zlib`?
[opc@centos7-9-nonrdma-davin-20210916 ~]$ spack -d spec zlib
==> [2021-09-22-07:33:10.723364] Imported spec from built-in commands
==> [2021-09-22-07:33:10.724218] Imported spec from built-in commands
Input spec
--------------------------------
zlib

Concretized
--------------------------------
==> [2021-09-22-07:33:10.725683] Reading config file /home/opc/spack/etc/spack/defaults/config.yaml
==> [2021-09-22-07:33:10.746350] Reading config file /home/opc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-22-07:33:10.755796] Reading config file /home/opc/spack/etc/spack/defaults/config.yaml
==> [2021-09-22-07:33:10.774537] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-22-07:33:10.774582] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-22-07:33:10.774898] Reading config file /home/opc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-22-07:33:10.782782] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-22-07:33:10.782826] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-22-07:33:10.782883] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-09-22-07:33:10.783263] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/opc/spack/etc/spack/defaults
==> [2021-09-22-07:33:10.783307] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/opc/spack/etc/spack/defaults/linux
==> [2021-09-22-07:33:10.783339] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
==> [2021-09-22-07:33:10.783362] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
==> [2021-09-22-07:33:10.783386] [BOOTSTRAP CONFIG SCOPE] name=site, path=/home/opc/spack/etc/spack
==> [2021-09-22-07:33:10.783407] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/home/opc/spack/etc/spack/linux
==> [2021-09-22-07:33:10.783442] [BOOTSTRAP CONFIG SCOPE] name=user, path=/home/opc/.spack
==> [2021-09-22-07:33:10.783466] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/home/opc/.spack/linux
==> [2021-09-22-07:33:10.783712] Reading config file /home/opc/.spack/linux/compilers.yaml
==> [2021-09-22-07:33:10.793440] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-09-22-07:33:10.793488] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-09-22-07:33:10.793656] Reading config file /home/opc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-22-07:33:10.801863] Bootstrapping clingo from pre-built binaries
==> [2021-09-22-07:33:10.803414] Imported buildcache from built-in commands
==> [2021-09-22-07:33:10.807410] Imported buildcache from built-in commands
==> [2021-09-22-07:33:10.808284] Reading config file /home/opc/spack/etc/spack/defaults/config.yaml
==> [2021-09-22-07:33:10.827236] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-22-07:33:10.827280] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-22-07:33:10.843394] Reading config file /home/opc/spack/etc/spack/defaults/mirrors.yaml
==> [2021-09-22-07:33:10.910645] Cached index for https://mirror.spack.io/bootstrap/github-actions/v0.1 already up to date
==> [2021-09-22-07:33:10.915803] [BOOTSTRAP MODULE clingo] Try installing "clingo-bootstrap" from binary cache at "https://mirror.spack.io/bootstrap/github-actions/v0.1"
==> [2021-09-22-07:33:13.048181] ChildError: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/opc/spack-stage/spack-stage-patchelf-0.13-7m3ooumspsk5qaq2wqwx73rjq3tzhfvy/patchelf-0.13.tar.bz2'
==> [2021-09-22-07:33:13.050391] Reading config file /home/opc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-22-07:33:13.076130] diffutils applying constraint iconv
==> [2021-09-22-07:33:13.089262] ncurses applying constraint pkgconfig
==> [2021-09-22-07:33:13.090165] readline applying constraint ncurses
==> [2021-09-22-07:33:13.091116] gdbm applying constraint readline
==> [2021-09-22-07:33:13.094678] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.097052] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.097931] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.098813] perl applying constraint bzip2
==> [2021-09-22-07:33:13.099724] perl applying constraint zlib
==> [2021-09-22-07:33:13.100633] bison applying constraint diffutils
==> [2021-09-22-07:33:13.101538] bison applying constraint m4
==> [2021-09-22-07:33:13.102515] bison applying constraint perl
==> [2021-09-22-07:33:13.103570] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.104207] python applying constraint pkgconfig@0.9.0:
==> [2021-09-22-07:33:13.106140] python applying constraint pkgconfig@0.9.0:
==> [2021-09-22-07:33:13.108703] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.109794] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.111180] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.112217] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.114068] Reading config file /home/opc/spack/etc/spack/defaults/packages.yaml
==> [2021-09-22-07:33:13.187952] Reading config file /home/opc/spack/etc/spack/defaults/config.yaml
==> [2021-09-22-07:33:13.243844] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.245384] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.246302] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.247034] bison applying constraint diffutils
==> [2021-09-22-07:33:13.247422] diffutils applying constraint libiconv
==> [2021-09-22-07:33:13.248066] bison applying constraint m4
==> [2021-09-22-07:33:13.248744] bison applying constraint perl
==> [2021-09-22-07:33:13.249414] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.250105] gdbm applying constraint readline
==> [2021-09-22-07:33:13.250754] readline applying constraint ncurses
==> [2021-09-22-07:33:13.251169] ncurses applying constraint pkgconfig
==> [2021-09-22-07:33:13.251782] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.252409] perl applying constraint bzip2
==> [2021-09-22-07:33:13.253061] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.253686] perl applying constraint zlib
==> [2021-09-22-07:33:13.254468] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.254990] python applying constraint pkgconfig@0.9.0:
==> [2021-09-22-07:33:13.264910] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.266332] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.267233] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.267838] bison applying constraint diffutils
==> [2021-09-22-07:33:13.268253] diffutils applying constraint libiconv
==> [2021-09-22-07:33:13.268828] bison applying constraint m4
==> [2021-09-22-07:33:13.269520] bison applying constraint perl
==> [2021-09-22-07:33:13.270190] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.270788] gdbm applying constraint readline
==> [2021-09-22-07:33:13.271370] readline applying constraint ncurses
==> [2021-09-22-07:33:13.271746] ncurses applying constraint pkgconf
==> [2021-09-22-07:33:13.272336] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.272884] perl applying constraint bzip2
==> [2021-09-22-07:33:13.273460] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.273999] perl applying constraint zlib
==> [2021-09-22-07:33:13.274717] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.275217] python applying constraint pkgconf
==> [2021-09-22-07:33:13.283315] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.284717] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.285559] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.286173] bison applying constraint diffutils
==> [2021-09-22-07:33:13.286555] diffutils applying constraint libiconv
==> [2021-09-22-07:33:13.287182] bison applying constraint m4
==> [2021-09-22-07:33:13.287784] bison applying constraint perl
==> [2021-09-22-07:33:13.288404] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.289081] gdbm applying constraint readline
==> [2021-09-22-07:33:13.289657] readline applying constraint ncurses
==> [2021-09-22-07:33:13.290047] ncurses applying constraint pkgconf
==> [2021-09-22-07:33:13.290644] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.291237] perl applying constraint bzip2
==> [2021-09-22-07:33:13.291797] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.292365] perl applying constraint zlib
==> [2021-09-22-07:33:13.293126] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.371551] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.376767] openssl applying constraint zlib
==> [2021-09-22-07:33:13.377443] openssl applying constraint perl@5.14.0:
==> [2021-09-22-07:33:13.378273] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.378913] gdbm applying constraint readline
==> [2021-09-22-07:33:13.379719] readline applying constraint ncurses
==> [2021-09-22-07:33:13.380399] ncurses applying constraint pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
==> [2021-09-22-07:33:13.381179] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.381887] perl applying constraint bzip2
==> [2021-09-22-07:33:13.382733] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.383368] diffutils applying constraint libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
==> [2021-09-22-07:33:13.384238] perl applying constraint zlib
==> [2021-09-22-07:33:13.385031] cmake applying constraint ncurses
==> [2021-09-22-07:33:13.388481] cmake applying constraint openssl
==> [2021-09-22-07:33:13.389250] cmake applying constraint ncurses
==> [2021-09-22-07:33:13.390186] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.391166] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.391811] bison applying constraint diffutils
==> [2021-09-22-07:33:13.392442] bison applying constraint m4
==> [2021-09-22-07:33:13.394281] m4 applying constraint libsigsegv
==> [2021-09-22-07:33:13.394871] bison applying constraint perl
==> [2021-09-22-07:33:13.395536] bison applying constraint diffutils
==> [2021-09-22-07:33:13.396163] bison applying constraint m4
==> [2021-09-22-07:33:13.396772] bison applying constraint perl
==> [2021-09-22-07:33:13.397721] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.398744] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.399735] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.400683] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.401522] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.430928] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2021-09-22-07:33:13.434370] cmake applying constraint openssl
==> [2021-09-22-07:33:13.435093] openssl applying constraint zlib
==> [2021-09-22-07:33:13.435846] openssl applying constraint perl@5.14.0:
==> [2021-09-22-07:33:13.436718] perl applying constraint gdbm@:1.19
==> [2021-09-22-07:33:13.437382] gdbm applying constraint readline
==> [2021-09-22-07:33:13.438047] readline applying constraint ncurses
==> [2021-09-22-07:33:13.438731] ncurses applying constraint pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
==> [2021-09-22-07:33:13.439506] perl applying constraint berkeley-db
==> [2021-09-22-07:33:13.440235] perl applying constraint bzip2
==> [2021-09-22-07:33:13.440934] bzip2 applying constraint diffutils
==> [2021-09-22-07:33:13.441764] diffutils applying constraint libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
==> [2021-09-22-07:33:13.442663] perl applying constraint zlib
==> [2021-09-22-07:33:13.443480] cmake applying constraint ncurses
==> [2021-09-22-07:33:13.444460] clingo-bootstrap applying constraint re2c@0.13:
==> [2021-09-22-07:33:13.445466] clingo-bootstrap applying constraint bison@2.5:
==> [2021-09-22-07:33:13.446241] bison applying constraint diffutils
==> [2021-09-22-07:33:13.446870] bison applying constraint m4
==> [2021-09-22-07:33:13.447569] m4 applying constraint libsigsegv
==> [2021-09-22-07:33:13.448217] bison applying constraint perl
==> [2021-09-22-07:33:13.449034] clingo-bootstrap applying constraint python
==> [2021-09-22-07:33:13.467189] Ordered hashes [m4]: m4/41/bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89, m4/42/9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573
==> [2021-09-22-07:33:13.467334] Ordered hashes [berkeley-db]: berkeley-db/60/b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522
==> [2021-09-22-07:33:13.479715] [BOOTSTRAP MODULE clingo] Unexpected error "Conflicts in concretized spec "clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python build_type=Release arch=linux-centos7-x86_64/oxlgakx"

    List of matching conflicts for spec:

    clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python build_type=Release arch=linux-centos7-x86_64
        ^bison@3.7.6%gcc@4.8.5 arch=linux-centos7-x86_64
            ^diffutils@3.7%gcc@4.8.5 arch=linux-centos7-x86_64
                ^libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
            ^m4@1.4.19%gcc@4.8.5+sigsegv patches=9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573,bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89 arch=linux-centos7-x86_64
                ^libsigsegv@2.13%gcc@4.8.5 arch=linux-centos7-x86_64
            ^perl@5.34.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-x86_64
                ^berkeley-db@18.1.40%gcc@4.8.5+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos7-x86_64
                ^bzip2@1.0.8%gcc@4.8.5~debug~pic+shared arch=linux-centos7-x86_64
                ^gdbm@1.19%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^readline@8.1%gcc@4.8.5 arch=linux-centos7-x86_64
                        ^ncurses@6.2%gcc@4.8.5~symlinks+termlib abi=none arch=linux-centos7-x86_64
                            ^pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
                ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
        ^cmake@3.21.2%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
            ^openssl@1.1.1l%gcc@4.8.5~docs+systemcerts arch=linux-centos7-x86_64
        ^python@3.6%gcc@4.8.5+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-x86_64
        ^re2c@2.2%gcc@4.8.5 arch=linux-centos7-x86_64

1. "%gcc@:5.99.99" conflicts with "clingo-bootstrap" [C++14 support is required to bootstrap clingo]
"
==> [2021-09-22-07:33:13.480705] Reading config file /home/opc/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/opc/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/opc/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/opc/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/home/opc/spack/lib/spack/spack/cmd/spec.py", line 109, in spec
    spec.concretize()
  File "/home/opc/spack/lib/spack/spack/spec.py", line 2624, in concretize
    self._new_concretize(tests)
  File "/home/opc/spack/lib/spack/spack/spec.py", line 2594, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "/home/opc/spack/lib/spack/spack/solver/asp.py", line 1679, in solve
    driver = PyclingoDriver()
  File "/home/opc/spack/lib/spack/spack/solver/asp.py", line 292, in __init__
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "/home/opc/spack/lib/spack/spack/bootstrap.py", line 564, in ensure_clingo_importable_or_raise
    module='clingo', abstract_spec=clingo_root_spec()
  File "/home/opc/spack/lib/spack/spack/bootstrap.py", line 399, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64"

**Comment by tueda** [comment]
I got a similar error on CentOS6@Docker (I was trying Spack to see whether it works for our system). It is easy to reproduce:
```sh
docker run -it --rm centos:centos6
```
```sh
sed -i -e "s/^mirrorlist=http:\/\/mirrorlist.centos.org/#mirrorlist=http:\/\/mirrorlist.centos.org/g" /etc/yum.repos.d/CentOS-Base.repo
sed -i -e "s/^#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g" /etc/yum.repos.d/CentOS-Base.repo

yum install -y python gcc make patch bash tar gzip unzip bzip2 xz file gnupg2 git

mkdir -p /usr/local/opt
cd /usr/local/opt

git clone https://github.com/spack/spack.git
cd spack/bin

./spack install zlib  # This line failed.
```
```
==> Bootstrapping clingo from pre-built binaries
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: the original concretizer is currently being used.
        Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack starting at v0.18.0
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64"
```
```
* **Spack:** 0.16.3-4540-b96d836
* **Python:** 2.6.6
* **Platform:** linux-centos6-cascadelake
* **Concretizer:** clingo
```

**Comment by haampie** [comment]
@alalazo we really need better error handling here...

See the note here

https://spack.readthedocs.io/en/latest/getting_started.html#bootstrapping-clingo

> When bootstrapping from pre-built binaries, Spack currently requires patchelf on Linux ... If patchelf is not in the PATH, Spack will build it from sources, and a C++ compiler is required.

~It seems `patchelf` can't be built with GCC 4.x, we're missing a conflict for it.~ It can w/ GCC 4.8.5, `gcc-c++` was missing as a package?

As a backup, Spack tries to build clingo from sources, but that fails because clingo itself needs C++14 (= GCC >= 6).

So, it's a rather awkward bootstrapping issue Spack has to solve, basically we just need to ship patchelf binaries.

As a workaround, can you install patchelf with the system package manager?

**Comment by haampie** [comment]
Actually I think there's another issue: https://github.com/spack/spack/pull/26155 Spack has given up on `centos:6` since it's been EOL for about a year now, but the PR shows you the workaround to fix issues with python 2.6 and ssl.

We still run unit tests on centos:6 though, but we don't rebuild the centos:6-spack image anymore.

**Comment by tueda** [comment]
@haampie Based on your comment, I found that the following (still) works on the `centos:centos6` Docker image. Thank you!
```bash
sed -i -e "s/^mirrorlist=http:\/\/mirrorlist.centos.org/#mirrorlist=http:\/\/mirrorlist.centos.org/g" /etc/yum.repos.d/CentOS-Base.repo
sed -i -e "s/^#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/vault.centos.org/g" /etc/yum.repos.d/CentOS-Base.repo

yum install -y python gcc gcc-c++ make patch bash tar gzip unzip bzip2 xz file gnupg2 git
yum install -y epel-release
yum install -y patchelf

mkdir -p /usr/local/opt
cd /usr/local/opt

git clone https://github.com/spack/spack.git
cd spack
mkdir tmp
(
  cd tmp
  curl -OL https://github.com/alalazo/spack-bootstrap-mirrors/releases/download/v0.1-rc.2/bootstrap-buildcache.tar.gz
  tar xzf bootstrap-buildcache.tar.gz
  rm -f bootstrap-buildcache.tar.gz
)
sed -i "s|https://mirror.spack.io/bootstrap/github-actions/v0.1|file://$(pwd)/tmp/bootstrap-buildcache|g" etc/spack/defaults/bootstrap.yaml
cd bin

./spack install zlib  # It works.
```

**Comment by Sinan81** [comment]
`patchelf` trick worked for me.
