### ISSUE TITLE
Spack fails to splice old specs with missing patches

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#26167]
Spack cannot update the buildcache index of the main develop binary mirror (so far E4S only) because some old specs cannot be spliced.  The result of this is that pipelines are generating hundreds of unnecessary jobs for the E4S stacks (both on `ppc64le` and `x86_64` since they share a mirror), causing really long delays of 15 hrs or longer per pipeline.

Here's a summary of the problem, but see further down for an actual reproducer, because the following will only work if you have the proper S3 access credentials set, and then takes about an hour.

```console
spack -d buildcache update-index --mirror-url s3://spack-binaries-develop/e4s
...
==> [2021-09-21-16:31:02.595843]   hdf5/zc7lv7h -> 26
==> [2021-09-21-16:31:02.595931]     needs the following deps spliced:
==> [2021-09-21-16:31:02.595975]       mpich/pvaxhhe
==> [2021-09-21-16:31:02.748345] Warning: Encountered problem pushing package index to s3://spack-binaries-develop/e4s/build_cache: Couldn't find patch for package builtin.hdf5 with sha256: dd9491bbe833b13929cb14b52137f7f44a539b4bfc89fc31e6e50a36e3e1b171
==> [2021-09-21-16:31:02.765412] 
Traceback (most recent call last):
  File "/Users/scott/projects/spack/lib/spack/spack/binary_distribution.py", line 800, in generate_package_index
    s = s.splice(true_dep, True)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 4401, in splice
    _ = dep.full_hash()
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1577, in full_hash
    return self._cached_hash(ht.full_hash, length)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1540, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1519, in _spec_hash
    node_dict = self.to_node_dict(hash=hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1677, in to_node_dict
    package_hash = self.package_hash()
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1548, in package_hash
    return self._cached_hash(ht.package_hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1540, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1518, in _spec_hash
    return hash.override(self)
  File "/Users/scott/projects/spack/lib/spack/spack/hash_types.py", line 55, in <lambda>
    override=lambda s: s.package.content_hash())
  File "/Users/scott/projects/spack/lib/spack/spack/package.py", line 1546, in content_hash
    for p in self.spec.patches)
  File "/Users/scott/projects/spack/lib/spack/llnl/util/lang.py", line 190, in _memoized_function
    func.cache[args] = func(*args)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 3402, in patches
    patch = index.patch_for_package(sha256, self.package)
  File "/Users/scott/projects/spack/lib/spack/spack/patch.py", line 349, in patch_for_package
    % (pkg.fullname, sha256))
spack.patch.NoSuchPatchError: Couldn't find patch for package builtin.hdf5 with sha256: dd9491bbe833b13929cb14b52137f7f44a539b4bfc89fc31e6e50a36e3e1b171
```

After spack fetches all the yaml/json specs from the mirror, it iterates though them in order of fewest dependencies first (i.e. starting at the leaves) attempting to splice older specs whose dependencies may have been replaced with newer versions where the DAG hash didn't change, but the full hash did.  For each old spec that needs to be spliced, it needs to recompute the hash, and this is not possible for some specs if, e.g., it used to have a patch which no longer exists. 

### Steps to reproduce

Attached are two spec files (old yaml format) which can be used to illustrate the problem:

[linux-ubuntu18.04-ppc64le-gcc-7.5.0-gmp-6.1.2-n3pjbqd4n77ogmtkdxmmfj6rhsi4cglv.spec.yaml.txt](https://github.com/spack/spack/files/7212445/linux-ubuntu18.04-ppc64le-gcc-7.5.0-gmp-6.1.2-n3pjbqd4n77ogmtkdxmmfj6rhsi4cglv.spec.yaml.txt)
[linux-ubuntu18.04-ppc64le-gcc-7.5.0-mpfr-3.1.6-rdbuvka45i2lrt7jgnszbxfkoais5yj7.spec.yaml.txt](https://github.com/spack/spack/files/7212446/linux-ubuntu18.04-ppc64le-gcc-7.5.0-mpfr-3.1.6-rdbuvka45i2lrt7jgnszbxfkoais5yj7.spec.yaml.txt)

The process of updating the buiildcache index results in changing one of the files, so keep a second copy handy to replace if you plan to run the reproducer multiple times.

Put the files into a directory, e.g. `/work/mirror/build_cache/`, then run:

```
spack -d buildcache update-index --mirror-url file:///work/mirror
```

The command should fail something like this:

```
==> [2021-09-22-10:34:07.450279] Imported buildcache from built-in commands
==> [2021-09-22-10:34:07.457335] Imported buildcache from built-in commands
==> [2021-09-22-10:34:07.458285] Reading config file /Users/scott/projects/spack/etc/spack/defaults/mirrors.yaml
==> [2021-09-22-10:34:07.462654] Retrieving spec descriptor files from file:///Users/scott/Documents/spack/more_index_hash_work/mirror/build_cache to build index
==> [2021-09-22-10:34:07.462869] fetching file:///Users/scott/Documents/spack/more_index_hash_work/mirror/build_cache/linux-ubuntu18.04-ppc64le-gcc-7.5.0-mpfr-3.1.6-rdbuvka45i2lrt7jgnszbxfkoais5yj7.spec.yaml
==> [2021-09-22-10:34:07.463595] Reading config file /Users/scott/projects/spack/etc/spack/defaults/config.yaml
==> [2021-09-22-10:34:07.521472] fetching file:///Users/scott/Documents/spack/more_index_hash_work/mirror/build_cache/linux-ubuntu18.04-ppc64le-gcc-7.5.0-gmp-6.1.2-n3pjbqd4n77ogmtkdxmmfj6rhsi4cglv.spec.yaml
==> [2021-09-22-10:34:07.709696] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-22-10:34:07.709785] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-22-10:34:07.709865] Specs sorted by number of dependencies:
==> [2021-09-22-10:34:07.709934]   mpfr/rdbuvka -> 1
==> [2021-09-22-10:34:07.710177] Reading config file /Users/scott/projects/spack/etc/spack/defaults/repos.yaml
==> [2021-09-22-10:34:07.787508]     needs the following deps spliced:
==> [2021-09-22-10:34:07.787687]       gmp/n3pjbqd
==> [2021-09-22-10:34:09.623378] Warning: Encountered problem pushing package index to file:///Users/scott/Documents/spack/more_index_hash_work/mirror/build_cache: Couldn't find patch for package builtin.mpfr with sha256: 66a5d58364113a21405fc53f4a48f4e8
==> [2021-09-22-10:34:09.633572] 
Traceback (most recent call last):
  File "/Users/scott/projects/spack/lib/spack/spack/binary_distribution.py", line 800, in generate_package_index
    s = s.splice(true_dep, True)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 4401, in splice
    _ = dep.full_hash()
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1577, in full_hash
    return self._cached_hash(ht.full_hash, length)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1540, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1519, in _spec_hash
    node_dict = self.to_node_dict(hash=hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1677, in to_node_dict
    package_hash = self.package_hash()
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1548, in package_hash
    return self._cached_hash(ht.package_hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1540, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 1518, in _spec_hash
    return hash.override(self)
  File "/Users/scott/projects/spack/lib/spack/spack/hash_types.py", line 55, in <lambda>
    override=lambda s: s.package.content_hash())
  File "/Users/scott/projects/spack/lib/spack/spack/package.py", line 1546, in content_hash
    for p in self.spec.patches)
  File "/Users/scott/projects/spack/lib/spack/llnl/util/lang.py", line 190, in _memoized_function
    func.cache[args] = func(*args)
  File "/Users/scott/projects/spack/lib/spack/spack/spec.py", line 3402, in patches
    patch = index.patch_for_package(sha256, self.package)
  File "/Users/scott/projects/spack/lib/spack/spack/patch.py", line 349, in patch_for_package
    % (pkg.fullname, sha256))
spack.patch.NoSuchPatchError: Couldn't find patch for package builtin.mpfr with sha256: 66a5d58364113a21405fc53f4a48f4e8
```

I have started working on a fix for this problem in #25708 but it is currently stuck on the following problem: Once we successfully splice the spec (essentially by avoiding computing the package hash and instead putting `None` for it), the spliced spec now has a new DAG hash (build provenenance is included in the DAG hash).  The question is should we lie and write the spliced spec to the old hash?  Or should we write it to the new hash, which might mean that we no longer see it as a build cache hit and are forced to rebuild it from source?  Or should we change how we check if specs are up to date and start tracing down through build specs looking for a full hash match?

### Error message

Error message included with command, above.

### Information on your system

This can happen on any platform since there's no arch/platform/os requirement for running `spack buildcache update-index` against an arbitrary mirror.  But the version of spack could be important, as with old enough spack, the patch mentioned in the second error output above might actually exist.

```
$ spack debug report
* **Spack:** 0.16.2-4343-c3cb863b82
* **Python:** 3.7.9
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
fyi @alalazo

**Comment by alalazo** [comment]
This is where we are failing when looking for a non-existing patch:

https://github.com/spack/spack/blob/76ad001c563bfdd1821b590110cbe83e1b177d03/lib/spack/spack/package.py#L1545-L1546

It's true that in the spec we store the sha256 of the patches, so we don't need to look them up in the repository (via the index), but for some reason the patch level enters the full hash - and that seems to be an information that we don't store in spec.json / spec.yaml.

**Comment by scottwittenburg** [comment]
@alalazo The approach I took in #25708 is not sophisticated but just abandons the package hash on certain spliced specs.  In fact, I wasn't aware this was the underlying cause of needing to recompute the package hash in the first place, so this is interesting to find out.

But for sake of argument let's say we already stored the patch level in the spec.json|yaml, wouldn't we still need to recompute the hash of spliced specs due to the additional build provenance?  By that I mean either a new `build_spec` in the node dict, or else its contents updated.  That question is maybe for @nhanford or another splicing expert.  I may be mistaken, but if that's true I think we'd still end up stuck where we are now: splicing results in a new DAG hash, and we haven't decided what to do about that.

**Comment by alalazo** [comment]
I'm taking a step back and trying to make sense of why we need to splice specs when generating an `index.json` file. In this particular case we have a synthetic buildcache repository with 2 `spec.yaml` files, one for `mpfr` and one for `gmp`. They are consistent with each other i.e. 
- `mpfr` references the DAG hash of `gmp`
- `mpfr` and `gmp` have a full hash in their respective spec.yaml (but they don't have the full hash of their dependencies stored as an information)

and we want to generate an index for it. What I struggle to understand is why we splice during the generation of the index rather than when creating a new buildcache with:
```console
$ spack buildcache create ...
```
Off the top of my head it seems more correct to splice when we push something to a buildcache (we may be pushing some node which has the same DAG hash but different full hash) rather when generating the index. Apologies if this seems trivial, but I am trying to connect the dots.

**Comment by scottwittenburg** [comment]
@becker33 May want to chime in here, and maybe help me straighten out my understanding as well.

The `mpfr` in this case seems to have been written back before we put all the hashes into the `spec.yaml`, so it doesn't have a full hash, and neither does it's internal representation of its `gmp` dependency.  The `gmp` seems to have been updated later after we were writing full hashes into those files, but it's DAG hash didn't change, so `mpfr` could still use it.  At that point there's now a mismatch between those two files and what they think the full hash of `gmp` is: in the older `mpfr` file, it is empty, while it has a value in the newer `gmp` file.  

To update the mirror index, we fetch all the spec files from the mirror and add them to the temporary database (which is used to write the mirror index).  After that process, `gmp` is only going to be in that db once, thanks to the DAG hash collision, and only one notion of the full hash is going to end there, and that's what will end up in the index.  So when we generate the pipeline the next time, we'll end up thinking we have to rebuild one when we really don't.  By splicing the newer `gmp` into the older `mpfr`, we get consistency between the two specs and the representation in the index. 

As to question posed by @alalazo regarding why we don't do the splicing when we create the new `gmp` buildcache (which replaces the depenency out from under `mpfr`), I think that's something we should consider.  Currently the splicing really slows down rebuilding the mirror index, so spreading that out over the rebuild jobs which create/push the binary packages might be desirable.  And like he says, maybe it's more correct, but I'm not sure.  But I wonder how it would be accomplished?  Would we have to iterate over all the specs in the mirror looking for any possible dependents of the new `gmp` we just pushed (or are about to push)?  That doesn't sound good to me, but there's likely something I'm missing.

**Comment by alalazo** [comment]
> The mpfr in this case seems to have been written back before we put all the hashes into the spec.yaml, so it doesn't have a full hash,

It seems to have a full hash for itself as a top-level key at the very bottom, even though it's true it doesn't have the full hash for the `gmp` dependencies.

**Comment by scottwittenburg** [comment]
You're right, I didn't notice the full hash there.  I guess that spec was written at a time when we did have the full hash of the package only, but put it in a different location.  But as you point out, its dependency `gmp` doesn't have it, and that's the point of contention between the two serialized specs anyway.

**Comment by becker33** [comment]
@scottwittenburg have you discussed this with @nhanford recently? Nate, Todd, and I discussed this Tuesday and it sounds like the least harmful lie to tell to Spack is to execute the splice, but then manually delete the `build_spec` provenance and reattach the old dag_hash to the spliced object, before we push it to the mirror.

When we have the reusing concretizer and use full_hash everywhere, then this shouldn't be an issue.
