### ISSUE TITLE
Cannot bootstrap Spack on Alpine Linux

### ISSUE THREAD

**Issue by parke** [LLNL/spack#26394]
### Steps to reproduce

(Fyi, I am a new user of `spack`, so I may not know what I am doing.)

In a fresh Alpine Linux 3.14.2 chroot environment (and probably also in a native install of Alpine Linux), I run the following as root:

    #  apk  update
    #  apk  add  build-base  bash  git  python3

I then run the following as a non-root user:

    $  git  clone  -c feature.manyFiles=true  https://github.com/spack/spack.git
    $  .  spack/share/spack/setup-env.sh
    $  time  spack  --debug  --stacktrace  spec  zlib

(See error message below.)

If I install Alpine's `py3-clingo` package, then `spack` appears to run successfully, but `spack` prints warnings about the version of `clingo` it is using.

(See warning below.)

I can find similar bug reports for other OSes.  However, (1) they are marked as closed, (2) the issue is still occurring with Alpine Linux.

### Error message

```
$  time  spack  --debug  --stacktrace  spec  zlib
lib/spack/spack/cmd/__init__.py:122 ==> [2021-09-30-22:01:59.390481] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-09-30-22:01:59.391952] Imported spec from built-in commands
Input spec
--------------------------------
zlib

Concretized
--------------------------------
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.396546] Reading config file /home/parke/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.442425] Reading config file /home/parke/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.456440] Reading config file /home/parke/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:373 ==> [2021-09-30-22:01:59.484461] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:377 ==> [2021-09-30-22:01:59.484919] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.485813] Reading config file /home/parke/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:373 ==> [2021-09-30-22:01:59.497010] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:377 ==> [2021-09-30-22:01:59.497480] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:476 ==> [2021-09-30-22:01:59.497931] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:488 ==> [2021-09-30-22:01:59.498692] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/parke/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:489 ==> [2021-09-30-22:01:59.499041] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/parke/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:488 ==> [2021-09-30-22:01:59.499366] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
lib/spack/spack/bootstrap.py:489 ==> [2021-09-30-22:01:59.499721] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
lib/spack/spack/bootstrap.py:488 ==> [2021-09-30-22:01:59.500058] [BOOTSTRAP CONFIG SCOPE] name=site, path=/home/parke/spack/etc/spack
lib/spack/spack/bootstrap.py:489 ==> [2021-09-30-22:01:59.500307] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/home/parke/spack/etc/spack/linux
lib/spack/spack/bootstrap.py:488 ==> [2021-09-30-22:01:59.500582] [BOOTSTRAP CONFIG SCOPE] name=user, path=/home/parke/.spack
lib/spack/spack/bootstrap.py:489 ==> [2021-09-30-22:01:59.500886] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/home/parke/.spack/linux
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.502088] Reading config file /home/parke/.spack/linux/compilers.yaml
lib/spack/spack/bootstrap.py:556 ==> [2021-09-30-22:01:59.519363] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:374 ==> [2021-09-30-22:01:59.519783] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.520439] Reading config file /home/parke/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:991 ==> [2021-09-30-22:01:59.687723] Reading config file /home/parke/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:94 ==> [2021-09-30-22:02:33.614824] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9 /hmnv6gk5wha64k6r3s7hid35mzvhkuot" provides the "clingo" Python module
lib/spack/spack/config.py:991 ==> [2021-09-30-22:02:33.615723] Reading config file /home/parke/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:991 ==> [2021-09-30-22:02:33.620863] Reading config file /home/parke/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/parke/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/parke/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/parke/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/home/parke/spack/lib/spack/spack/cmd/spec.py", line 109, in spec
    spec.concretize()
  File "/home/parke/spack/lib/spack/spack/spec.py", line 2624, in concretize
    self._new_concretize(tests)
  File "/home/parke/spack/lib/spack/spack/spec.py", line 2594, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "/home/parke/spack/lib/spack/spack/solver/asp.py", line 1691, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "/home/parke/spack/lib/spack/spack/solver/asp.py", line 332, in solve
    self.control = clingo.Control()
AttributeError: module 'clingo' has no attribute 'Control'
Command exited with non-zero status 1
real    0m 38.79s
user    0m 35.99s
sys     0m 2.07s
```

And here is the warning I see if I install Alpine's `py3-clingo` package:

```
==> Warning: Spec clingo-bootstrap@spack%gcc@9.3.0~docs~ipo+python build_type=Release arch=linux-rhel5-x86_64 ^python@3.9%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel5-x86_64 did not provide module clingo
```

### Information on your system

$  spack  debug  report
* **Spack:** 0.16.3-4547-7694c58736
* **Python:** 3.9.5
* **Platform:** linux-alpine3-haswell
* **Concretizer:** clingo

Fyi, I am running the Alpine Linux chroot inside of an Lxroot virtual environment, but I don't think that makes a difference.  I suspect the same problem will be encountered on any system running Alpine Linux.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Still an issue as of: 

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
