### ISSUE TITLE
pkgconf fails install under ubuntu 16.04 because Python doesn't support format strings

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#26641]
### Steps to reproduce

Develop version of spack, and ubuntu 16.04

```console
$ spack install pkgconf
```
Here is an exact Dockerfile to reproduce it
```dockerfile
FROM ubuntu:16.04@sha256:454054f5bbd571b088db25b662099c6c7b3f0cb78536a2077d54adc48f00cd68

# docker build -t ghcr.io/rse-radiuss/ubuntu:<version> .

ARG uptodate_github_commit_spack__spack__develop=4e1fdfeb18c7ce02a09103cff2b556cf15feee49
ENV spack_commit=${uptodate_github_commit_spack__spack__develop}
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

LABEL maintainer="David Beckingsale <david@llnl.gov>,@vsoch"

RUN apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      curl \
      dh-autoreconf \
      git \
      gnupg2 \
      libssl-dev \
      ninja-build \
      python-dev \ 
      python3-pip \
      python3-setuptools \
      sudo \
      valgrind \
      vim \
      wget

# Install spack
WORKDIR /opt
RUN git clone https://github.com/spack/spack && \
    cd spack && \
    git reset --hard ${spack_commit}
ENV PATH=/opt/spack/bin:$PATH

# Use the autamus build cache for maybe faster install?
RUN python3 -m pip install botocore boto3 && \
    spack mirror add autamus s3://autamus-cache && \
    curl http://s3.amazonaws.com/autamus-cache/build_cache/_pgp/FFEB24B0A9D81F6D5597F9900B59588C86C41BE7.pub > key.pub && \
    spack gpg trust key.pub
```
To build and run
```bas
$ docker build -t pancakes .
$ docker run -it pancakes
# spack install pkgconf
```

### Error message

```console
root@1437bf099b36:/opt# spack install pkgconf
==> Installing pkgconf-1.8.0-wrfzcxiwuxp6n35gbncfhkne3rorsypj
==> Error: Failed to install pkgconf due to SyntaxError: invalid syntax (auth.py, line 121)
==> Error: invalid syntax (auth.py, line 121)
```

I think the Python is too old - and the package should have a constraint:

```
Traceback (most recent call last):
  File "/opt/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/opt/spack/lib/spack/spack/main.py", line 814, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 527, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 473, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 274, in install_specs
    builder.install()
  File "/opt/spack/lib/spack/spack/installer.py", line 1612, in install
    self._install_task(task)
  File "/opt/spack/lib/spack/spack/installer.py", line 1144, in _install_task
    full_hash_match):
  File "/opt/spack/lib/spack/spack/installer.py", line 279, in _install_from_cache
    pkg, explicit, unsigned=unsigned, full_hash_match=full_hash_match)
  File "/opt/spack/lib/spack/spack/installer.py", line 405, in _try_install_from_binary_cache
    pkg.spec, full_hash_match=full_hash_match)
  File "/opt/spack/lib/spack/spack/binary_distribution.py", line 1547, in get_mirrors_for_spec
    mirrors=mirrors_to_check)
  File "/opt/spack/lib/spack/spack/binary_distribution.py", line 1465, in try_direct_fetch
    _, _, fs = web_util.read_from_url(buildcache_fetch_url_json)
  File "/opt/spack/lib/spack/spack/util/web.py", line 127, in read_from_url
    response = _urlopen(req, timeout=_timeout, context=context)
  File "/opt/spack/lib/spack/spack/util/web.py", line 526, in _urlopen
    return opener(req, *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/opt/spack/lib/spack/spack/s3_handler.py", line 66, in s3_open
    url, headers, stream = _s3_open(orig_url)
  File "/opt/spack/lib/spack/spack/s3_handler.py", line 44, in _s3_open
    s3 = s3_util.create_s3_session(parsed)
  File "/opt/spack/lib/spack/spack/util/s3.py", line 31, in create_s3_session
    from boto3 import Session
  File "/usr/local/lib/python3.5/dist-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.5/dist-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.5/dist-packages/botocore/session.py", line 30, in <module>
    import botocore.client
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 16, in <module>
    from botocore.args import ClientArgsCreator
  File "/usr/local/lib/python3.5/dist-packages/botocore/args.py", line 26, in <module>
    from botocore.signers import RequestSigner
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 19, in <module>
    import botocore.auth
  File "/usr/local/lib/python3.5/dist-packages/botocore/auth.py", line 121
    pairs.append(f'{quoted_key}={quoted_value}')
                                              ^
SyntaxError: invalid syntax
```
Format strings weren't introduced into a bit after 3.5.

### Information on your system

See the Dockerfile above, that's the system :) And this:

```
# spack debug report
* **Spack:** 0.16.3-4791-4e1fdfe
* **Python:** 3.5.2
* **Platform:** linux-ubuntu16.04-skylake
* **Concretizer:** clingo
```

These issue text boxes are pretty groovy!

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by vsoch** [comment]
My current hack to fix it (in the Dockerfile before spack external find, after adding autamus) is to basically update to python 3.8
```dockerfile
# We need to upgrade Python 3 to at least 3.7 because pkgconf has format strings! yuck
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.8 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
    apt-get install -y python3.8-distutils && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    pip3 install botocore boto3
```
Then the build is successful.

**Comment by michaelkuhn** [comment]
Looking at the trace, I don't see how this is caused by pkgconf. This rather looks like an issue with fetching binaries from the mirror. Does it also happen with other packages?

**Comment by vsoch** [comment]
Right it looks like it’s botocore, but superficially the message appears alongside pkgconf - it wasn’t obvious until I added debug.

**Comment by haampie** [comment]
So, seems like an issue with pip not specifying proper version bounds? Do we know of a package manager that handles this better?

**Comment by vsoch** [comment]
I think because we know it's Python related, this isn't something that really spack can handle. So let's close - and it will be helpful if someone finds it and can use my hack err fix :)

**Comment by haampie** [comment]
I was joking but I mean, what's wrong with spack install py-boto3?

The issue is that pip gives you an incompatible botocore, right?

I also remember I tried installing boto3 with apt, but got a hopelessly broken version.

Maybe spack got it figured out in terms of giving you an optimal version compatible with your system python.

Otherwise do a multistage build for your build image where you run `spack install --only=dependencies spack` to get a recent python, and all of spack's deps.

**Comment by vsoch** [comment]
Yes I think so!
