### ISSUE TITLE
Giving spack "-debug" instead of "--debug" gives really confusing error..

### ISSUE THREAD

**Issue by marcmengel** [LLNL/spack#26772]
### Steps to reproduce

If you meant to type, say:
`spack --debug list gcc`
but instead typed
`spack -debug list gcc`
you get:
```
Traceback (most recent call last):
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/bin/spack", line 83, in <module>
    sys.exit(spack.main.main())
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/lib/spack/spack/main.py", line 713, in main
    env = ev.find_environment(args)
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/lib/spack/spack/environment.py", line 308, in find_environment
spack.environment.SpackEnvironmentError: no environment in bug
```
I suggest we check for specifically that environment name ("bug"), and add to the message:
"...did you mean --debug rather than -debug?"
because the message is otherwise really confusing given the intent of the user.

### Error message

```console
[mengel@fermicloud298 ~]$ spack -debug list gcc
Traceback (most recent call last):
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/bin/spack", line 83, in <module>
    sys.exit(spack.main.main())
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/lib/spack/spack/main.py", line 713, in main
    env = ev.find_environment(args)
  File "/scratch/supercalifragilisticexpialidocious_extra_padding_directory/spack/v0.16.1.fermi/NULL/lib/spack/spack/environment.py", line 308, in find_environment
    raise SpackEnvironmentError('no environment in %s' % env)
spack.environment.SpackEnvironmentError: no environment in bug
```

While this error message is *technically* correct (the options they typed did request a nonexistent
envrionment named "bug") the users real error was leaving a dash off of "--debug", so they don't
*think* they requested such an environment, and the output is really confusing.

### Information on your system

```
[mengel@fermicloud298 ~]$ spack debug report
* **Spack:** 0.16.1-1619-096c6ea
* **Python:** 3.8.6
* **Platform:** linux-scientific7-broadwell
* **Concretizer:** original
```
----------------------
Although I think you get this in *any* version of spack...

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I get the confusion, but this is expected and standard behavior. `-x -y -z arg` can be abbreviated to `-xyzarg` and people rely on this, like in `tar -xvzf filename`.

It just happens to be so that `-debug` is interpreted as `-d -e bug`.

**Comment by marcmengel** [comment]
I understand how the argument parsing works.  That's not the issue.

The issue is we can give a *better error message*.  If the name of the environment we cannot find happens to be "bug", there is a strong probability the user fat-fingered --debug, and we should mention that, as I would propose that it is far more likely that a user typoed --debug than that they did -e bug when they don't have a "bug" environment.

**Comment by haampie** [comment]
I disagree it requires a better error messages... we already provide tab completion for long arguments, and it's just a funny coincidence we have the -d and -e  flags.
