### ISSUE TITLE
`spack ci reproduce-build` fails on jobs from `develop` pipelines

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#26854]
### Steps to reproduce

Start with a failed job from a `develop` pipeline in gitlab CI, for example [this](https://gitlab.spack.io/spack/spack/-/jobs/1146018) one.  Following the instructions in the job trace results in:

```
$ spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/1146018/artifacts --working-dir /tmp/phist_repro
==> Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/1146018/artifacts

==> Job ran with the following image: ghcr.io/scottwittenburg/ecpe4s-ubuntu18.04-runner-x86_64:2021-05-15
checkout_commit: 5dc8094f8468a33404de018243a60ae2202d6a0f
merge_commit: None
==> Job ran with the following tags: ['spack', 'public', 'large', 'x86_64']

Run the following command:

    $ docker run --rm -v /tmp/phist_repro:/builds/spack/spack -ti ghcr.io/scottwittenburg/ecpe4s-ubuntu18.04-runner-x86_64:2021-05-15

Once inside the container:

    - Activate the environment

        $ source /builds/spack/spack/spack/share/spack/setup-env.sh
        $ spack env activate --without-view /builds/spack/spack/jobs_scratch_dir/reproduction

    - Run the install script

        $ /builds/spack/spack/jobs_scratch_dir/reproduction/install.sh

$ docker run --rm -v /tmp/phist_repro:/builds/spack/spack -ti ghcr.io/scottwittenburg/ecpe4s-ubuntu18.04-runner-x86_64:2021-05-15
root@447cc02c5908:/# source /builds/spack/spack/spack/share/spack/setup-env.sh
root@447cc02c5908:/# spack env activate --without-view /builds/spack/spack/jobs_scratch_dir/reproduction
root@447cc02c5908:/# /builds/spack/spack/jobs_scratch_dir/reproduction/install.sh
...
==> [2021-10-20-16:25:51.361793] Error: RuntimeError: Unable to locate python command in /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.10-ihtrj5dmjbjmlc2satbke4h4kagkrnq3/bin

/builds/spack/spack/spack/var/spack/repos/builtin/packages/python/package.py:668, in command:
        665                return Executable(path)
        666        else:
        667            msg = 'Unable to locate {0} command in {1}'
  >>    668            raise RuntimeError(msg.format(self.name, self.prefix.bin))


Traceback (most recent call last):
  File "/builds/spack/spack/spack/lib/spack/spack/build_environment.py", line 1027, in _setup_pkg_and_run
    pkg, dirty=kwargs.get('dirty', False), context=context)
  File "/builds/spack/spack/spack/lib/spack/spack/build_environment.py", line 781, in setup_package
    pkg.spec, context, custom_mods_only=False))
  File "/builds/spack/spack/spack/lib/spack/spack/build_environment.py", line 979, in modifications_from_dependencies
    add_modifications_for_dep(dspec)
  File "/builds/spack/spack/spack/lib/spack/spack/build_environment.py", line 960, in add_modifications_for_dep
    dpkg.setup_dependent_package(spec.package.module, spec)
  File "/builds/spack/spack/spack/var/spack/repos/builtin/packages/python/package.py", line 1004, in setup_dependent_package
    module.setup_py = Executable(
  File "/builds/spack/spack/spack/var/spack/repos/builtin/packages/python/package.py", line 669, in command
RuntimeError: Unable to locate python command in /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.10-ihtrj5dmjbjmlc2satbke4h4kagkrnq3/bin
```

The full output from running the `install.sh` script of the reproducer is attached.

I think the problem is that because the job was part of a `develop` pipeline, the install command in the script is generated without the `--no-check-signature` option, as the only source of binary dependencies in `develop` pipelines is the main `s3://spack-binaries-develop` mirror, where all the pkgs are signed with a signing key.  The reproducer runs that script, but has not trusted the public part of that signing key, so none of the dependency binaries can be verified, resulting in lots of output like:

```
==> [2021-10-20-16:23:46.112566] Fetching s3://spack-binaries-develop/e4s/build_cache/linux-ubuntu18.04-x86_64/gcc-7.5.0/gdbm-1.19/linux-ubuntu18.04-x86_64-gcc-7.5.0-gdbm-1.19-oftaepjelizkam37ezxwkuw27clnosqn.spack
==> [2021-10-20-16:23:48.364521] Extracting gdbm-1.19-oftaepjelizkam37ezxwkuw27clnosqn from binary cache
==> [2021-10-20-16:23:48.370993] '/usr/bin/gpg2' '--verify' '/tmp/tmpwkmcfdcx/linux-ubuntu18.04-x86_64-gcc-7.5.0-gdbm-1.19-oftaepjelizkam37ezxwkuw27clnosqn.spec.json.asc' '/tmp/tmpwkmcfdcx/linux-ubuntu18.04-x86_64-gcc-7.5.0-gdbm-1.19-oftaepjelizkam37ezxwkuw27clnosqn.spec.json'
gpg: Signature made Thu 23 Sep 2021 12:07:20 AM UTC
gpg:                using RSA key C1B1A375B724E210B58F30620C35BFA2EADD3E30
gpg: Can't check signature: No public key
```

It's not clear to me why these don't result in failure immediately (all the dependencies seem to get flagged as installed in spite of the errors), but after the reproducer fails, the install tree within the container is empty (no deps were installed), which explains why (in this case) the python command cannot be located.

There is another piece of evidence that the problem is failing to verify binaries.  If we start the whole reproducer process over, and simply insert the `--no-check-signaure` cli option into the install command in the `install.sh` script before running it, the reproducer works as expected (that is, the package fails to build in the same way it failed in the gitlab pipeline).

[spack_ci_reproducer_develop_fail.txt](https://github.com/spack/spack/files/7382890/spack_ci_reproducer_develop_fail.txt)

### Error message

Error messages are included above.

### Information on your system

In this case, I tried the reproducer on my macbook:

```
$ spack debug report
* **Spack:** 0.16.3-4943-1983d6d9d0
* **Python:** 3.7.9
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo
```

But the reproducer should be runnable anywhere spack and docker are installed/available.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@scottwittenburg Is this issue still relevant, given how many changes we had to pipelines since when it was submitted?

**Comment by alalazo** [comment]
Closing as outdated, we can open a new issue in case.
