### ISSUE TITLE
build_environment.py: 'module' object has no attribute 'PackageBase'

### ISSUE THREAD

**Issue by trmwzm** [LLNL/spack#2688]
Not sure how to deal with the error whose message I appended below ...

Adding the base class to "spack.package import Package" does the trick, but I have no idea what I am doing ...

`1 file changed, 1 insertion(+), 1 deletion(-)
lib/spack/spack/__init__.py | 2 +-

modified   lib/spack/spack/__init__.py
@@ -160,7 +160,7 @@ dirty = _config.get('dirty', False)
 #-----------------------------------------------------------------------------
 __all__ = []
 
-from spack.package import Package
+from spack.package import Package, PackageBase
 from spack.build_systems.makefile import MakefilePackage
 from spack.build_systems.autotools import AutotoolsPackage
 from spack.build_systems.cmake import CMakePackage
`
-------------------- error ----------------------

`==> Executing phase : 'install'
==> WRITE LOCK: /u/proj2/proj/trm/spack-emacs/opt/spack/.spack-db/prefix_lock[2843439391484420822:1] [Released]
==> WRITE LOCK: /u/proj2/proj/trm/spack-emacs/var/spack/stage/.lock[7968242201785533596:1] [Released]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/build_environment.py", line 564, in child_execution
    package_context = get_package_context(tb)
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/build_environment.py", line 627, in get_package_context
    if isinstance(obj, spack.PackageBase):
AttributeError: 'module' object has no attribute 'PackageBase'
^CSignal received : entering python shell.
Traceback:
  File "/home/trm/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/trm/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/trm/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/cmd/install.py", line 346, in install
    package.do_install(**kwargs)
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/package.py", line 1185, in do_install
    **kwargs
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/package.py", line 1185, in do_install
    **kwargs
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/package.py", line 1185, in do_install
    **kwargs
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/package.py", line 1185, in do_install
    **kwargs
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/package.py", line 1283, in do_install
    spack.build_environment.fork(self, build_process, dirty=dirty)
  File "/u/proj2/proj/trm/spack-emacs/lib/spack/spack/build_environment.py", line 592, in fork
    child_exc = parent_connection.recv()

`

**Comment by tgamblin** [comment]
Does #2687 fix this for you?
