### ISSUE TITLE
Installation issue: some Python packages on Centos7/RHEL7

### ISSUE THREAD

**Issue by tylerjereddy** [LLNL/spack#26998]
Sample reproducer for one of them in centos7 docker container: `spack install py-python-dateutil %gcc@9.3.1 ^py-setuptools@57.4.0` produces output like `pkg_resources.DistributionNotFound: The 'packaging>=20.0' distribution was not found and is required by the application`.

Sample patch that helped in my buildout scenario--not sure if the team would normally add conditional guards for certain operating systems.

```diff
diff --git a/var/spack/repos/builtin/packages/py-pytest-runner/package.py b/var/spack/repos/builtin/packages/py-pytest-runner/package.py
index 1221464..f0c01f1 100644
--- a/var/spack/repos/builtin/packages/py-pytest-runner/package.py
+++ b/var/spack/repos/builtin/packages/py-pytest-runner/package.py
@@ -17,3 +17,4 @@ class PyPytestRunner(PythonPackage):
 
     depends_on('py-setuptools', type=('build', 'run'))
     depends_on('py-setuptools-scm@1.15:', type='build')
+    depends_on('py-packaging@20.0:', type='build')
diff --git a/var/spack/repos/builtin/packages/py-python-dateutil/package.py b/var/spack/repos/builtin/packages/py-python-dateutil/package.py
index 50e207d..fa088a7 100644
--- a/var/spack/repos/builtin/packages/py-python-dateutil/package.py
+++ b/var/spack/repos/builtin/packages/py-python-dateutil/package.py
@@ -25,3 +25,4 @@ class PyPythonDateutil(PythonPackage):
     depends_on('py-setuptools@24.3:', type='build')
     depends_on('py-setuptools-scm', type='build', when='@2.7.0:')
     depends_on('py-six@1.5:', type=('build', 'run'))
+    depends_on('py-packaging@20.0:', type=('build'))
```

**Comment by adamjstewart** [comment]
Hmm, this doesn't make any sense, `py-pytest-runner` doesn't import `packaging` anywhere. `setuptools` does, but `setuptools` bundles its own `packaging` to prevent a circular dependency. It seems like your `setuptools` installation is broken. When you load it, is `PYTHONPATH` set correctly?

**Comment by tylerjereddy** [comment]
@adamjstewart I have the container open now, and I was just reproducing it for a user reporting the same issue, so let me know if there are other things you want me to provide you with:

(in centos7 container that has the issue)

- `spack load py-setuptools`
- `echo $PYTHONPATH`
- `/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages`

**Comment by adamjstewart** [comment]
Is that the correct path? Like does the directory have `pkg_resources` in it? Does the error message specify which file is trying to import `packaging`?

**Comment by tylerjereddy** [comment]
Seems like the correct path--this has stuff in it: `/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/`

I'll place the full traceback below the fold for `spack install py-python-dateutil ^py-setuptools@57.4.0`:

<details>

```
==> py-python-dateutil: Executing phase: 'build'
==> [2021-10-28-20:12:02.750738] '/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/python-3.8.11-24s7fpekrvbugyqe6ubjfo4vhwuquola/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
WARNING: The wheel package is not available.
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    setup(
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
    wheel.install_as_egg(dist_location)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/wheel.py", line 153, in _convert_metadata
    setup_dist = setuptools.Distribution(
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/python-3.8.11-24s7fpekrvbugyqe6ubjfo4vhwuquola/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/dist.py", line 806, in finalize_options
    for ep in sorted(eps, key=by_order):
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/setuptools/dist.py", line 805, in <lambda>
    eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/py-setuptools-57.4.0-yhopvo2hcn44iz3cj5k3hxeqvceynhhr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging>=20.0' distribution was not found and is required by the application

```

</details>


I also have access to a machine where this works just fine, though I haven't tried to dissect any differences in the files that may be present in both situations.

**Comment by adamjstewart** [comment]
Is this an external Python or a Spack-installed Python? When you run this Python, which of the following commands work (after running `spack load py-setuptools`):
```python
import setuptools
import pkg_resources
import packaging
```

**Comment by tylerjereddy** [comment]
```
[root@f7b5b869862b github_projects]# spack load py-setuptools
[root@f7b5b869862b github_projects]# which python
/github_projects/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.1/python-3.8.11-24s7fpekrvbugyqe6ubjfo4vhwuquola/bin/python
[root@f7b5b869862b github_projects]# python
Python 3.8.11 (default, Oct 27 2021, 21:55:22) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> import pkg_resources
>>> import packaging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
>>> 
```

**Comment by adamjstewart** [comment]
Hmm, I would have to dig deeper. I've been planning to switch our build system from `python setup.py install` to `pip install` for a while now. I'm guessing that this will solve the issue.

**Comment by tylerjereddy** [comment]
Ah yeah, PEP517/518 (`pyproject.toml`) compliant builds are probably the way to go, although many projects are taking quite some time to get there.

I guess we will vendor some patches internally or something for now.

**Comment by iarspider** [comment]
@adamjstewart I think this is exactly what we've discussed today: setuptools-scm depend on packaging. I have just submitted a PR to add that dependency.
