### ISSUE TITLE
Failed to install package in NixOS

### ISSUE THREAD

**Issue by Hong-Xiang** [LLNL/spack#27049]
### Steps to reproduce

Following instructions of install spack, but failed to install any package. Spack failed on build initial `perl` package,
```console
git clone git clone https://github.com/spack/spack.git
```

Then use nix shell to provide python and other utilities
```nix
{ pkgs ? import <nixpkgs> { } }:
with pkgs;
mkShell {
  buildInputs = [
    python38
    coreutils
  ];
  shellHook = ''
    . $spack/share/spack/setup-env.sh
  '';
}
```
which just provide python and other libs in current `$PATH` and related environment variables.

### Error message

```console
spack --debug --stacktrace install hdf5


lib/spack/spack/error.py:54 ==> [2021-10-29-09:49:07.904318] Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 errors found in build log:
     1294    LD_LIBRARY_PATH=/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src ./miniperl -Ilib make_ext.pl ext/Pod-Functions/pm_to_blib  MAKE="make" LIBPERL_A=libperl.so
     1295    ==> Please rerun the make command.  <==
     1296    false
     1297    make[1]: *** [Makefile:759: Makefile] Error 1
     1298    make[1]: Leaving directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/cpan/Pod-Perldoc'
     1299    make[1]: Entering directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/cpan/Pod-Perldoc'
  >> 1300    /nix/store/9r0a3dipi8saq2zasp668zsk6qhqp5jb-glibc-2.32-48-dev/include/bits/errno.h:23:3: error: #error "Never include <bits/errno.h> directly; use <errno.h> instead."
     1301       23 | # error "Never include <bits/errno.h> directly; use <errno.h> instead."
     1302          |   ^~~~~
     1303    make[1]: Entering directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/dist/XSLoader'
     1304    make[1]: Leaving directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/cpan/Pod-Checker'
     1305    Makefile out-of-date with respect to ../../lib/Config.pm ../../config.h
     1306    Cleaning current config before rebuilding Makefile...

     ...

     1561    Auto Detect Gzip OS Code..
     1562    Setting Gzip OS Code to 3 [Unix/Default]
     1563    Looks Good.
     1564    Setting license tag...
     1565    Adding META_MERGE...
     1566    make -f Makefile.old clean > /dev/null 2>&1
  >> 1567    Can't exec "pwd": No such file or directory at /run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/dist/PathTools/Cwd.pm line 204.
     1568    Generating a Unix-style Makefile
     1569    Writing Makefile for Digest::SHA
     1570    Generating a Unix-style Makefile
     1571    Writing Makefile for B
     1572    "../../miniperl" "-I../../lib" Makefile.PL "INSTALLDIRS=perl" "INSTALLMAN1DIR=none" "INSTALLMAN3DIR=none" "PERL_CORE=1" "LIBPERL_A=libperl.so" "LINKTYPE=dynamic" "PERL=../../miniperl"
     1573    ==> Your Makefile has been rebuilt. <==

     ...

     1580    false
     1581    make[1]: *** [Makefile:937: Makefile] Error 1
     1582    make[1]: Leaving directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/cpan/Digest-SHA'
     1583    make[1]: *** [Makefile:925: Makefile] Error 1
     1584    make[1]: Leaving directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/ext/B'
     1585    ==> Your Makefile has been rebuilt. <==
  >> 1586    Can't exec "pwd": No such file or directory at /run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/dist/PathTools/Cwd.pm line 204.
     1587    Generating a Unix-style Makefile
     1588    Writing Makefile for GDBM_File
     1589    ==> Please rerun the make command.  <==
     1590    false
     1591    make[1]: *** [Makefile:918: Makefile] Error 1
     1592    make[1]: Leaving directory '/run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-src/cpan/Digest-MD5'

See build log for details:
  /run/user/1000/xiang/spack-stage/spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre/spack-build-out.txt

Traceback (most recent call last):
  File "/home/xiang/spack/lib/spack/spack/build_environment.py", line 1028, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/xiang/spack/lib/spack/spack/installer.py", line 1952, in build_process
    return installer.run()
  File "/home/xiang/spack/lib/spack/spack/installer.py", line 1809, in run
    self._real_install()
  File "/home/xiang/spack/lib/spack/spack/installer.py", line 1916, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/home/xiang/spack/lib/spack/spack/package.py", line 135, in phase_wrapper
    phase(spec, prefix)
  File "/home/xiang/spack/var/spack/repos/builtin/packages/perl/package.py", line 236, in build
  File "/home/xiang/spack/lib/spack/spack/build_environment.py", line 147, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/xiang/spack/lib/spack/spack/util/executable.py", line 231, in __call__
    raise self.error
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j16'
lib/spack/spack/installer.py:1367 ==> [2021-10-29-09:49:08.032323] Flagging perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre as failed: ProcessError: Command exited with status 2:
    'make' '-j16'
lib/spack/spack/installer.py:1376 ==> [2021-10-29-09:49:08.034224] Warning: Skipping build of openssl-1.1.1l-y6rlhcf6l6jmpfw7ly3ixjl7ul5btmhi since perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre failed
lib/spack/spack/installer.py:1367 ==> [2021-10-29-09:49:08.034374] Flagging openssl-1.1.1l-y6rlhcf6l6jmpfw7ly3ixjl7ul5btmhi as failed
lib/spack/spack/installer.py:1376 ==> [2021-10-29-09:49:08.035056] Warning: Skipping build of cmake-3.21.3-4vdb4x2hks3plq42mi6vpcv7jmgvmzbx since openssl-1.1.1l-y6rlhcf6l6jmpfw7ly3ixjl7ul5btmhi failed
lib/spack/spack/installer.py:1367 ==> [2021-10-29-09:49:08.035204] Flagging cmake-3.21.3-4vdb4x2hks3plq42mi6vpcv7jmgvmzbx as failed
lib/spack/spack/installer.py:1376 ==> [2021-10-29-09:49:08.036414] Warning: Skipping build of clingo-bootstrap-spack-xfnxvdh6q2e5omsixxvz2mj75wrnrrr3 since cmake-3.21.3-4vdb4x2hks3plq42mi6vpcv7jmgvmzbx failed
lib/spack/spack/installer.py:1367 ==> [2021-10-29-09:49:08.036564] Flagging clingo-bootstrap-spack-xfnxvdh6q2e5omsixxvz2mj75wrnrrr3 as failed
lib/spack/spack/installer.py:1376 ==> [2021-10-29-09:49:08.037285] Warning: Skipping build of bison-3.8.2-mlbslwjvyg5qfrlgbtfgpzj2aewyx2d7 since perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre failed
lib/spack/spack/installer.py:1367 ==> [2021-10-29-09:49:08.037423] Flagging bison-3.8.2-mlbslwjvyg5qfrlgbtfgpzj2aewyx2d7 as failed
lib/spack/spack/stage.py:327 ==> [2021-10-29-09:49:08.039546] Creating stage lock spack-stage-perl-5.34.0-mek6vwo24bmcpceehu2pf7yg45mgxkre
lib/spack/spack/stage.py:327 ==> [2021-10-29-09:49:08.039770] Creating stage lock resource-cpanm-mek6vwo24bmcpceehu2pf7yg45mgxkre
lib/spack/spack/bootstrap.py:405 ==> [2021-10-29-09:49:08.039912] [BOOTSTRAP MODULE clingo] Unexpected error "Terminating after first install failure: ProcessError: Command exited with status 2:
    'make' '-j16'"
lib/spack/spack/config.py:1007 ==> [2021-10-29-09:49:08.041556] Reading config file /home/xiang/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/xiang/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/xiang/spack/lib/spack/spack/main.py", line 816, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/xiang/spack/lib/spack/spack/main.py", line 529, in _invoke_command
    return_val = command(parser, args)
  File "/home/xiang/spack/lib/spack/spack/cmd/install.py", line 394, in install
    specs = spack.cmd.parse_specs(
  File "/home/xiang/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/xiang/spack/lib/spack/spack/spec.py", line 2640, in concretize
    self._new_concretize(tests)
  File "/home/xiang/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "/home/xiang/spack/lib/spack/spack/solver/asp.py", line 1679, in solve
    driver = PyclingoDriver()
  File "/home/xiang/spack/lib/spack/spack/solver/asp.py", line 292, in __init__
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "/home/xiang/spack/lib/spack/spack/bootstrap.py", line 625, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(
  File "/home/xiang/spack/lib/spack/spack/bootstrap.py", line 418, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'spack-install' raised InstallError: Terminating after first install failure: ProcessError: Command exited with status 2:
    'make' '-j16'
    Please run `spack -d spec zlib` for more verbose error messages
```

### Information on your system

* **Spack:** 0.16.3-5058-890095e876
* **Python:** 3.8.9
* **Platform:** linux-nixos21-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by danielbarter** [comment]
The issue here is that when perl is being configured, it is finding both the desired `errno.h` and also the system specific `bits/errno.h`. If you look in `${glibc.dev}/include` you will see the `bits` folder, which the configuration is detecting as a normal header

**Comment by danielbarter** [comment]
What i said above was wrong. The same include errors happen on nixos, and things still build fine. The issue is in the perl script `Cwd.pm:183`:
```
my $found_pwd_cmd = defined($pwd_cmd);
unless ($pwd_cmd) {
    # Isn't this wrong?  _backtick_pwd() will fail if someone has
    # pwd in their path but it is not /bin/pwd or /usr/bin/pwd?
    # See [perl #16774]. --jhi
    $pwd_cmd = 'pwd';
}
```

**Comment by danielbarter** [comment]
this is fixed now in https://github.com/spack/spack/pull/33394. @haampie or @msimberg, feel free to close.

**Comment by msimberg** [comment]
> this is fixed now in #33394. @haampie or @msimberg, feel free to close.

I added a "fixes" comment on #33394 so this should be closed automatically when that is merged.

**Comment by alalazo** [comment]
Apologies, I read https://github.com/spack/spack/issues/27049#issuecomment-1287238193 but didn't notice the PR is still open
