### ISSUE TITLE
spack create mirror gives: Traceback with AttributeError: 'NoneType' object has no attribute '_concrete' message

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#2713]
When trying to create a spack mirror with the latest develop branch (1/1/17), I get this traceback.

[jeg@localhost]$ spack mirror create -d /home/jeg/spack-mirror -D openspeedshop+cbtf%gcc@4.8.3
Traceback (most recent call last):
  File "/home/jeg/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/jeg/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/jeg/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/jeg/spack/lib/spack/spack/cmd/mirror.py", line 224, in mirror
    action[args.mirror_command](args)
  File "/home/jeg/spack/lib/spack/spack/cmd/mirror.py", line 202, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/home/jeg/spack/lib/spack/spack/mirror.py", line 167, in create
    s.concretize()
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 1527, in concretize
    self._expand_virtual_packages(),
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 1422, in _expand_virtual_packages
    self_index = ProviderIndex(self.traverse(), restrict=True)
  File "/home/jeg/spack/lib/spack/spack/provider_index.py", line 87, in __init__
    self.update(spec)
  File "/home/jeg/spack/lib/spack/spack/provider_index.py", line 104, in update
    if spec.satisfies(provider_spec, deps=False):
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 2054, in satisfies
    if not self.variants.satisfies(other.variants, strict=var_strict):
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 633, in satisfies
    if strict or self.spec._concrete:
AttributeError: 'NoneType' object has no attribute '_concrete'
[jeg@localhost spack]$

**Comment by jgalarowicz** [comment]
@tgamblin Further testing shows that this error is tied to my krell components.  I can create mirrors for cmake and cbtf, but when I try cbtf-krell or openspeedshop, I get the error below.   Do you know how I might debug this issue?  The traceback shows something about multiple version function being called.
Thanks Jim G

[jeg@localhost spack]$ spack mirror create -d /home/jeg/spack-mirror -D cbtf
==> Adding package boost@1.59.0 to mirror
==> boost@1.59.0 : already added
==> Adding package openssl@1.0.2j to mirror
==> openssl@1.0.2j : already added
==> Adding package bzip2@1.0.6 to mirror
==> bzip2@1.0.6 : already added
==> Adding package ncurses@6.0 to mirror
==> ncurses@6.0 : already added
==> Adding package mrnet@5.0.1-2 to mirror
==> mrnet@5.0.1-2 : already added
==> Adding package libxml2@2.9.4 to mirror
==> libxml2@2.9.4 : already added
==> Adding package zlib@1.2.10 to mirror
==> zlib@1.2.10 : already added
==> Adding package xerces-c@3.1.4 to mirror
==> xerces-c@3.1.4 : already added
==> Adding package cbtf@1.8 to mirror
==> cbtf@1.8 : already added
==> Adding package pkg-config@0.29.1 to mirror
==> pkg-config@0.29.1 : already added
==> Adding package sqlite@3.8.5 to mirror
==> sqlite@3.8.5 : already added
==> Adding package xz@5.2.2 to mirror
==> xz@5.2.2 : already added
==> Adding package readline@6.3 to mirror
==> readline@6.3 : already added
==> Adding package cmake@3.7.1 to mirror
==> cmake@3.7.1 : already added
==> Adding package python@2.7.13 to mirror
==> python@2.7.13 : already added
==> Successfully updated mirror in /home/jeg/spack-mirror
  Archive stats:
    15   already present
    0    added
    0    failed to fetch.
[jeg@localhost spack]$ spack mirror create -d /home/jeg/spack-mirror -D cbtf-krell
Traceback (most recent call last):
  File "/home/jeg/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/jeg/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/jeg/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/jeg/spack/lib/spack/spack/cmd/mirror.py", line 224, in mirror
    action[args.mirror_command](args)
  File "/home/jeg/spack/lib/spack/spack/cmd/mirror.py", line 202, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/home/jeg/spack/lib/spack/spack/mirror.py", line 167, in create
    s.concretize()
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 1521, in concretize
    self._expand_virtual_packages(),
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 1416, in _expand_virtual_packages
    self_index = ProviderIndex(self.traverse(), restrict=True)
  File "/home/jeg/spack/lib/spack/spack/provider_index.py", line 87, in __init__
    self.update(spec)
  File "/home/jeg/spack/lib/spack/spack/provider_index.py", line 106, in update
    if spec.satisfies(provider_spec, deps=False):
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 2049, in satisfies
    if not self.variants.satisfies(other.variants, strict=var_strict):
  File "/home/jeg/spack/lib/spack/spack/spec.py", line 627, in satisfies
    if strict or self.spec._concrete:
AttributeError: 'NoneType' object has no attribute '_concrete'

**Comment by jgalarowicz** [comment]
This is now fixed by #2806
