### ISSUE TITLE
Spack fails to bootstrap clingo fedora 35

### ISSUE THREAD

**Issue by wortiz** [LLNL/spack#27218]
### Steps to reproduce

Seems to work fine with a checkout before 78c08fccd56d

Download spack with git and run:

```
spack -d solve zlib
```
Used same dnf packages as 

https://github.com/spack/spack/blob/develop/.github/workflows/bootstrap.yml#L28-L31

### Error message

```console
[spack@cdd985727477 ~]$ spack -d solve zlib
==> [2021-11-04-15:21:32.681260] Imported solve from built-in commands
==> [2021-11-04-15:21:32.681762] Imported solve from built-in commands
==> [2021-11-04-15:21:32.682054] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-11-04-15:21:32.686327] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-11-04-15:21:32.696214] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-11-04-15:21:32.705032] DATABASE LOCK TIMEOUT: 3s
==> [2021-11-04-15:21:32.705058] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-11-04-15:21:32.705232] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-11-04-15:21:32.708827] DATABASE LOCK TIMEOUT: 3s
==> [2021-11-04-15:21:32.708852] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-11-04-15:21:32.708883] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-11-04-15:21:32.709058] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/spack/spack/etc/spack/defaults
==> [2021-11-04-15:21:32.709079] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/spack/spack/etc/spack/defaults/linux
==> [2021-11-04-15:21:32.709097] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/spack/.spack/bootstrap/config
==> [2021-11-04-15:21:32.709114] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/spack/.spack/bootstrap/config/linux
==> [2021-11-04-15:21:32.709246] Reading config file /home/spack/.spack/bootstrap/config/linux/compilers.yaml
==> [2021-11-04-15:21:32.719913] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-11-04-15:21:32.719941] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-11-04-15:21:32.720057] Reading config file /home/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-11-04-15:21:32.723749] Bootstrapping clingo from pre-built binaries
==> [2021-11-04-15:21:32.724358] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
==> [2021-11-04-15:21:32.733600] DATABASE LOCK TIMEOUT: 3s
==> [2021-11-04-15:21:32.733625] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-11-04-15:21:32.741278] Reading config file /home/spack/spack/etc/spack/defaults/mirrors.yaml
==> [2021-11-04-15:21:32.855561] Cached index for https://mirror.spack.io/bootstrap/github-actions/v0.1 already up to date
==> [2021-11-04-15:21:32.861080] Bootstrapping clingo from sources
==> [2021-11-04-15:21:32.878400] '/bin/cmake' '--version'
==> [2021-11-04-15:21:32.882315] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2021-11-04-15:21:32.882407] '/usr/bin/cmake' '--version'
==> [2021-11-04-15:21:32.885946] '/bin/bison' '--version'
==> [2021-11-04-15:21:32.886541] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2021-11-04-15:21:32.886611] '/usr/bin/bison' '--version'
==> [2021-11-04-15:21:32.887353] '/bin/gawk' '--version'
==> [2021-11-04-15:21:32.888446] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2021-11-04-15:21:32.888513] '/usr/bin/gawk' '--version'
==> [2021-11-04-15:21:32.889544] Reading config file /home/spack/spack/etc/spack/defaults/packages.yaml
==> [2021-11-04-15:21:32.908512] [BOOTSTRAP MODULE clingo] Unexpected error "Invalid config scope: 'bootstrap'.  Must be one of odict_keys(['_builtin', 'defaults', 'defaults/linux', 'bootstrap/linux', 'disable_modules', 'overrides-0'])"
==> [2021-11-04-15:21:32.908857] Reading config file /home/spack/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/spack/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/spack/spack/lib/spack/spack/main.py", line 876, in main
    return _main(argv)
  File "/home/spack/spack/lib/spack/spack/main.py", line 859, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/home/spack/spack/lib/spack/spack/main.py", line 529, in _invoke_command
    return_val = command(parser, args)
  File "/home/spack/spack/lib/spack/spack/cmd/solve.py", line 105, in solve
    result = asp.solve(
  File "/home/spack/spack/lib/spack/spack/solver/asp.py", line 1814, in solve
    driver = PyclingoDriver()
  File "/home/spack/spack/lib/spack/spack/solver/asp.py", line 401, in __init__
    bootstrap_clingo()
  File "/home/spack/spack/lib/spack/spack/solver/asp.py", line 380, in bootstrap_clingo
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "/home/spack/spack/lib/spack/spack/bootstrap.py", line 774, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(
  File "/home/spack/spack/lib/spack/spack/bootstrap.py", line 517, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'spack-install' raised ValueError: Invalid config scope: 'bootstrap'.  Must be one of odict_keys(['_builtin', 'defaults', 'defaults/linux', 'bootstrap/linux', 'disable_modules', 'overrides-0'])
    Please run `spack -d spec zlib` for more verbose error messages
```

### Information on your system

podman image ls
REPOSITORY                         TAG         IMAGE ID      CREATED       SIZE
registry.fedoraproject.org/fedora  latest      1b52edb08181  23 hours ago  159 MB

[spack@cdd985727477 ~]$ spack debug report
* **Spack:** 0.16.3-5234-f6ed8b6150
* **Python:** 3.10.0
* **Platform:** linux-fedora35-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed by #27231
