### ISSUE TITLE
No upper bounds on the thread pool size used to search for compilers

### ISSUE THREAD

**Issue by benfulton** [LLNL/spack#27315]
### Steps to reproduce

The command was 

`spack -d install zlib`

The error is in the find_compilers function, when it calls 

`tp = multiprocessing.pool.ThreadPool()`

The CPU count is 128, and since nothing is specified, it tries to grab all 128 cores. Hardcoding it to ThreadPool(8) fixes the issue.

### Error message

==> [2021-11-09-10:44:05.760886] Imported install from built-in commands
==> [2021-11-09-10:44:05.762909] Reading config file /geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/config.yaml
==> [2021-11-09-10:44:05.783034] Imported install from built-in commands
==> [2021-11-09-10:44:05.788462] Reading config file /geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-11-09-10:44:05.822667] Reading config file /geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/config.yaml
==> [2021-11-09-10:44:05.842282] DATABASE LOCK TIMEOUT: 3s
==> [2021-11-09-10:44:05.842323] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-11-09-10:44:05.842678] Reading config file /geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-11-09-10:44:05.874567] DATABASE LOCK TIMEOUT: 3s
==> [2021-11-09-10:44:05.874609] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-11-09-10:44:05.874662] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-11-09-10:44:05.874972] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults
==> [2021-11-09-10:44:05.875007] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/linux
==> [2021-11-09-10:44:05.875043] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/N/u/befulton/Quartz/.spack/bootstrap/config
==> [2021-11-09-10:44:05.875066] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/N/u/befulton/Quartz/.spack/bootstrap/config/linux
==> [2021-11-09-10:44:06.080393] Reading config file /geode2/home/u010/befulton/Quartz/Apps/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/threading.py", line 852, in start
RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/main.py", line 882, in main
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/main.py", line 865, in _main
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/main.py", line 535, in _invoke_command
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/cmd/install.py", line 394, in install
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/cmd/__init__.py", line 166, in parse_specs
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/spec.py", line 2639, in concretize
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/solver/asp.py", line 2012, in solve
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/solver/asp.py", line 464, in __init__
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/solver/asp.py", line 442, in bootstrap_clingo
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/contextlib.py", line 113, in __enter__
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/bootstrap.py", line 691, in ensure_bootstrap_configuration
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/bootstrap.py", line 659, in _add_compilers_if_missing
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/compilers/__init__.py", line 332, in compilers_for_arch
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/compilers/__init__.py", line 182, in all_compilers_config
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/compilers/__init__.py", line 106, in get_compiler_config
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/compilers/__init__.py", line 93, in init_compiler_config
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/compilers/__init__.py", line 215, in find_compilers
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
  File "/N/soft/rhel8/python/3.8.5/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
AttributeError: 'DummyProcess' object has no attribute 'terminate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/N/u/befulton/Quartz/Apps/spack/bin/spack", line 100, in <module>
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/main.py", line 904, in main
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 923, in get
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 638, in get
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 578, in get_config
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/llnl/util/lang.py", line 190, in _memoized_function
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 593, in _get_config_memoized
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 148, in get_section
  File "/geode2/home/u010/befulton/Quartz/Apps/spack/lib/spack/spack/config.py", line 1008, in read_config_file
MemoryError

### Information on your system

* **Spack:** 0.17.0-40-6e6847d9c7
* **Python:** 3.8.5
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mofeing** [comment]
I was having the same error in a HPC system even with just 1 thread. We solved it by modifying the process stack size:
```
ulimit -s 10240
```

Apparently, Linux implements threads as processes with shared memory address space. In systems with limited resources or restrictions, the system may forbid you from creating more threads due to limited memory allocation for stacks.

`10240` is a random number that worked for me. It varies depending on the system and the program.
