### ISSUE TITLE
Fetching doesn't work that well when expand=False

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2739]
There is no way to set `expand=False` at the package-level. Install crashes immediately with:
```
==> Error: AttributeError: 'NoneType' object has no attribute 'lstrip'
/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py:702, in _make_root_stage:
     700      def _make_root_stage(self, fetcher):
     701          # Construct a mirror path (TODO: get this out of package.py)
  >> 702          mp = spack.mirror.mirror_archive_path(self.spec, fetcher)
     703          # Construct a path where the stage should build..
     704          s = self.spec
     705          stage_name = "%s-%s-%s" % (s.name, s.version, s.dag_hash())
     706  
     707          def download_search():
     708              dynamic_fetcher = fs.from_list_url(self)
     709              return [dynamic_fetcher] if dynamic_fetcher else []
     710  
     711          stage = Stage(fetcher, mirror_path=mp, name=stage_name, path=self.path,
     712                        search_fn=download_search)
     713          return stage

```
If you set `expand=False` at the version level and try to fetch a non-checksummed version, you get:
```
$ spack fetch cuda@1.2.3
==> Warning: There is no checksum on file to fetch cuda@1.2.3 safely.
  Fetch anyway? [y/N] y
==> Fetching with no checksum.
  Add a checksum or use --no-checksum to skip this check.
Traceback (most recent call last):
  File "/soft/spack-0.10.0/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/soft/spack-0.10.0/bin/spack", line 208, in main
    _main(args, unknown)
  File "/soft/spack-0.10.0/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/cmd/fetch.py", line 65, in fetch
    package.do_fetch()
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py", line 943, in do_fetch
    self.stage.fetch(mirror_only)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py", line 743, in stage
    self._stage = self._make_stage()
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py", line 723, in _make_stage
    stage = self._make_root_stage(fetcher)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py", line 702, in _make_root_stage
    mp = spack.mirror.mirror_archive_path(self.spec, fetcher)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/mirror.py", line 81, in mirror_archive_path
    spec.name, mirror_archive_filename(spec, fetcher, resourceId))
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/mirror.py", line 56, in mirror_archive_filename
    ext = ext or spec.package.versions[spec.package.version].get(
KeyError: Version('1.2.3')
```

**Comment by citibeth** [comment]
What does expand do?  And why would I want to install non-checksummed software?

**Comment by adamjstewart** [comment]
> What does expand do?

It dictates whether or not the downloaded file should be expanded. This is the default, as most packages download compressed archives. `expand=False` is required for downloading non-compressed installer scripts.

> And why would I want to install non-checksummed software?

You wouldn't, but Spack supports it.

**Comment by citibeth** [comment]
I am dubious that we should continue that support.  Especially if it
creates hard design problems

**Comment by tgamblin** [comment]
@citibeth: we're going to continue that support.  I don't mind hard design problems and I'm maintaining this.

**Comment by adamjstewart** [comment]
Regardless, I think any kwargs that can be passed to the `version()` directive should be able to be declared at the package level as well. If you have 10 versions of the package, there's no sense in specifying `expand` or `git` or `pypi` for every version. `url` currently works this way, but I'm not sure which other kwargs do.
