### ISSUE TITLE
Spack external find: "Error: NamedTemporaryFile() got an unexpected keyword argument 'buffering'"

### ISSUE THREAD

**Issue by jackzzs** [LLNL/spack#27499]
### Steps to reproduce

```console
$ spack external find
==> Error: NamedTemporaryFile() got an unexpected keyword argument 'buffering'

$ ls ~/.spack
cache/

$ spack external list
==> Detectable packages per repository
Repository: builtin
    python    cpio       gcc          hugo      meson     perl          texinfo
    arm       cuda       gdal         intel     mpich     pkg-config    texlive
    autoconf  diffutils  ghostscript  ispc      mvapich2  pkgconf       uftrace
    automake  doxygen    git          krb5      nag       root          visit
    bash      file       git-annex    libfuse   ncurses   rsync         xlc
    bazel     findutils  git-lfs      libtool   ninja     ruby          xlf
    bison     fish       gmake        llvm      opengl    rust          xz
    bzip2     fj         gmt          llvm-doe  openjdk   sed
    ccache    flex       go           lustre    openmpi   spectrum-mpi
    cmake     fzf        gpgme        m4        openssh   sqlite
    jdk       gawk       groff        maven     openssl   tar

```

### Error message

```console
$ spack external find
==> [2021-11-17-17:50:31.799758] Imported external from built-in commands
==> [2021-11-17-17:50:31.800992] Imported external from built-in commands
==> [2021-11-17-17:50:31.801432] Reading config file /home/xxx/bin/spack/etc/spack/defaults/repos.yaml
==> [2021-11-17-17:50:31.879999] Reading config file /home/xxx/bin/spack/etc/spack/defaults/config.yaml
(...)
==> [2021-11-17-17:50:55.901502] '/usr/bin/tex' '--version'
==> [2021-11-17-17:50:55.930001] '/home/xxx/.conda/envs/main/bin/sqlite3' '--version'
Traceback (most recent call last):
  File "/home/xxx/bin/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/xxx/bin/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/home/xxx/bin/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/home/xxx/bin/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/home/xxx/bin/spack/lib/spack/spack/cmd/external.py", line 101, in external
    action[args.external_command](args)
  File "/home/xxx/bin/spack/lib/spack/spack/cmd/external.py", line 75, in external_find
    detected_packages = spack.detection.by_executable(packages_to_check)
  File "/home/xxx/bin/spack/lib/spack/spack/detection/path.py", line 103, in by_executable
    pkg.determine_spec_details(prefix, exes_in_prefix)
  File "/home/xxx/bin/spack/lib/spack/spack/package.py", line 212, in determine_spec_details
    variants = cls.determine_variants(exes, version_str)
  File "/home/xxx/bin/spack/var/spack/repos/builtin/packages/sqlite/package.py", line 116, in determine_variants
    rc_fts5 = call(exe, query_fts(5))
  File "/home/xxx/bin/spack/var/spack/repos/builtin/packages/sqlite/package.py", line 95, in call
    sqlite_stdin.write(query + '\n')
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'buffering'
```

### Information on your system

* **Spack:** 0.17.0-186-9260c38
* **Python:** 2.7.5
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cyrush** [comment]
sorry, I added a dup issue:
https://github.com/spack/spack/issues/27850
