### ISSUE TITLE
Installation issue: py-tomli fails on Fedora 35

### ISSUE THREAD

**Issue by robertu94** [LLNL/spack#27569]
### Steps to reproduce the issue

```console
$ spack external find python
$ spack install --reuse py-tomli
```

### Information on your system

* **Spack:** 0.17.0-2-833dafbbe0
* **Python:** 3.10.0
* **Platform:** linux-fedora35-skylake
* **Concretizer:** clingo

```console
[runderwood@voyager ~]$ python --version
Python 3.10.0
[runderwood@voyager ~]$ pip --version
pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)

```

### Additional information

spack-build-out.txt

```txt
==> py-tomli: Executing phase: 'install'
==> [2021-11-20-06:59:51.268281] '/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq/bin/pip' 'install' '/tmp/runderwood/spack-stage/spack-stage-py-tomli-1.2.1-vtwig2q7qiw4f4uimbcvpqnuhwegcwpq/spack-src/tomli-1.2.1-py3-none-any.whl' '--prefix=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-tomli-1.2.1-vtwig2q7qiw4f4uimbcvpqnuhwegcwpq'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.VersionConflict: (pip 21.2.3 (/usr/lib/python3.10/site-packages), Requirement.parse('pip==21.1.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==21.1.2', 'console_scripts', 'pip')())
  File "/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq/bin/pip", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3.10/site-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/usr/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'pip==21.1.2' distribution was not found and is required by the application
```

spack-build-env.txt

```
BASH_ENV=/usr/share/lmod/lmod/init/bash; export BASH_ENV
function BASH_FUNC__spack_shell_wrapper%%() {  for var in LD_LIBRARY_PATH DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH;
 do
 eval "if [ -n \"\${${var}-}\" ]; then export SPACK_$var=\${${var}}; fi";
 done;
 if [ -n "${ZSH_VERSION:-}" ]; then
 emulate -L sh;
 fi;
 _sp_flags="";
 while [ ! -z ${1+x} ] && [ "${1#-}" != "${1}" ]; do
 _sp_flags="$_sp_flags $1";
 shift;
 done;
 if [ -n "$_sp_flags" ] && [ "${_sp_flags#*h}" != "${_sp_flags}" ] || [ "${_sp_flags#*V}" != "${_sp_flags}" ]; then
 command spack $_sp_flags "$@";
 return;
 fi;
 _sp_subcommand="";
 if [ ! -z ${1+x} ]; then
 _sp_subcommand="$1";
 shift;
 fi;
 case $_sp_subcommand in 
 "cd")
 _sp_arg="";
 if [ -n "$1" ]; then
 _sp_arg="$1";
 shift;
 fi;
 if [ "$_sp_arg" = "-h" ] || [ "$_sp_arg" = "--help" ]; then
 command spack cd -h;
 else
 LOC="$(spack location $_sp_arg "$@")";
 if [ -d "$LOC" ]; then
 cd "$LOC";
 else
 return 1;
 fi;
 fi;
 return
 ;;
 "env")
 _sp_arg="";
 if [ -n "$1" ]; then
 _sp_arg="$1";
 shift;
 fi;
 if [ "$_sp_arg" = "-h" ] || [ "$_sp_arg" = "--help" ]; then
 command spack env -h;
 else
 case $_sp_arg in 
 activate)
 _a=" $@";
 if [ -z ${1+x} ] || [ "${_a#* --sh}" != "$_a" ] || [ "${_a#* --csh}" != "$_a" ] || [ "${_a#* -h}" != "$_a" ] || [ "${_a#* --help}" != "$_a" ]; then
 command spack env activate "$@";
 else
 stdout="$(command spack $_sp_flags env activate --sh "$@")" || return;
 eval "$stdout";
 fi
 ;;
 deactivate)
 _a=" $@";
 if [ "${_a#* --sh}" != "$_a" ] || [ "${_a#* --csh}" != "$_a" ]; then
 command spack env deactivate "$@";
 else
 if [ -n "$*" ]; then
 command spack env deactivate -h;
 else
 stdout="$(command spack $_sp_flags env deactivate --sh)" || return;
 eval "$stdout";
 fi;
 fi
 ;;
 *)
 command spack env $_sp_arg "$@"
 ;;
 esac;
 fi;
 return
 ;;
 "load" | "unload")
 _a=" $@";
 if [ "${_a#* --sh}" != "$_a" ] || [ "${_a#* --csh}" != "$_a" ] || [ "${_a#* -h}" != "$_a" ] || [ "${_a#* --list}" != "$_a" ] || [ "${_a#* --help}" != "$_a" ]; then
 command spack $_sp_flags $_sp_subcommand "$@";
 else
 stdout="$(command spack $_sp_flags $_sp_subcommand --sh "$@")" || return;
 eval "$stdout";
 fi
 ;;
 *)
 command spack $_sp_flags $_sp_subcommand "$@"
 ;;
 esac
}; export -f BASH_FUNC__spack_shell_wrapper%%
function BASH_FUNC_ml%%() {  eval $($LMOD_DIR/ml_cmd "$@")
}; export -f BASH_FUNC_ml%%
function BASH_FUNC_module%%() {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}; export -f BASH_FUNC_module%%
function BASH_FUNC_spack%%() {  : this is a shell function from: /home/runderwood/git/contrib/spack/share/spack/setup-env.sh;
 : the real spack script is here: /home/runderwood/git/contrib/spack/bin/spack;
 _spack_shell_wrapper "$@";
 return $?
}; export -f BASH_FUNC_spack%%
function BASH_FUNC_which%%() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}; export -f BASH_FUNC_which%%
BAT_THEME='Solarized (light)'; export BAT_THEME
CC=/home/runderwood/git/contrib/spack/lib/spack/env/gcc/gcc; export CC
CMAKE_PREFIX_PATH=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq; export CMAKE_PREFIX_PATH
COLORFGBG='0;15'; export COLORFGBG
COLORTERM=truecolor; export COLORTERM
CTEST_PARALLEL_LEVEL=12; export CTEST_PARALLEL_LEVEL
CXX=/home/runderwood/git/contrib/spack/lib/spack/env/gcc/g++; export CXX
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DBUS_SESSION_BUS_ADDRESS
DEBUGINFOD_URLS='https://debuginfod.fedoraproject.org/ https://debuginfod.fedoraproject.org/'; export DEBUGINFOD_URLS
DESKTOP_SESSION=/usr/share/xsessions/plasmax11; export DESKTOP_SESSION
DISPLAY=:0; export DISPLAY
EDITOR=nvim; export EDITOR
F77=/home/runderwood/git/contrib/spack/lib/spack/env/gcc/gfortran; export F77
FC=/home/runderwood/git/contrib/spack/lib/spack/env/gcc/gfortran; export FC
GDK_CORE_DEVICE_EVENTS=1; export GDK_CORE_DEVICE_EVENTS
GTK2_RC_FILES=/home/runderwood/.gtkrc-2.0-kde4; export GTK2_RC_FILES
GTK_IM_MODULE=gtk-im-context-simple; export GTK_IM_MODULE
HISTCONTROL=ignoredups; export HISTCONTROL
HISTSIZE=1000; export HISTSIZE
HOME=/home/runderwood; export HOME
HOSTNAME=voyager; export HOSTNAME
IMSETTINGS_INTEGRATE_DESKTOP=yes; export IMSETTINGS_INTEGRATE_DESKTOP
IMSETTINGS_MODULE=none; export IMSETTINGS_MODULE
INVOCATION_ID=cb781289fbe04f2a8194fc011faad0c3; export INVOCATION_ID
JOURNAL_STREAM=8:30375; export JOURNAL_STREAM
KDEDIRS=/usr; export KDEDIRS
KDE_APPLICATIONS_AS_SCOPE=1; export KDE_APPLICATIONS_AS_SCOPE
KDE_FULL_SESSION=true; export KDE_FULL_SESSION
KDE_SESSION_UID=1000; export KDE_SESSION_UID
KDE_SESSION_VERSION=5; export KDE_SESSION_VERSION
KONSOLE_DBUS_SERVICE=:1.77; export KONSOLE_DBUS_SERVICE
KONSOLE_DBUS_SESSION=/Sessions/1; export KONSOLE_DBUS_SESSION
KONSOLE_DBUS_WINDOW=/Windows/1; export KONSOLE_DBUS_WINDOW
KONSOLE_VERSION=210803; export KONSOLE_VERSION
LAMMPS_POTENTIALS=/usr/share/lammps/potentials; export LAMMPS_POTENTIALS
LANG=en_US.UTF-8; export LANG
LANGUAGE=''; export LANGUAGE
LC_ALL=C; export LC_ALL
LDCXXSHARED='/home/runderwood/git/contrib/spack/lib/spack/env/gcc/g++ -shared'; export LDCXXSHARED
LDSHARED='/home/runderwood/git/contrib/spack/lib/spack/env/gcc/gcc -shared -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now    -g  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now    -g'; export LDSHARED
LESSOPEN='||/usr/bin/lesspipe.sh %s'; export LESSOPEN
LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod; export LMOD_CMD
LMOD_DIR=/usr/share/lmod/lmod/libexec; export LMOD_DIR
LMOD_PKG=/usr/share/lmod/lmod; export LMOD_PKG
LMOD_ROOT=/usr/share/lmod; export LMOD_ROOT
LMOD_SETTARG_FULL_SUPPORT=no; export LMOD_SETTARG_FULL_SUPPORT
LMOD_VERSION=8.4.30; export LMOD_VERSION
LMOD_sys=Linux; export LMOD_sys
LOGNAME=runderwood; export LOGNAME
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:'; export LS_COLORS
MAIL=/var/spool/mail/runderwood; export MAIL
MANAGERPID=1295; export MANAGERPID
MANPATH=/usr/share/man/openmpi-x86_64:/usr/share/man/openmpi-x86_64:/usr/share/lmod/lmod/share/man:; export MANPATH
MODULEPATH=/home/runderwood/git/contrib/spack/share/spack/modules/linux-fedora35-skylake:/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core; export MODULEPATH
MODULEPATH_ROOT=/usr/share/modulefiles; export MODULEPATH_ROOT
MODULESHOME=/usr/share/lmod/lmod; export MODULESHOME
MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed; export MOZ_GMP_PATH
MSI2LMP_LIBRARY=/usr/share/lammps/frc_files; export MSI2LMP_LIBRARY
M_PYTHON_SITELIB=/home/runderwood/.local/lib/python3.10/site-packages; export M_PYTHON_SITELIB
#OLDPWD=/home/runderwood/git/contrib/spack; export OLDPWD
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket; export PAM_KWALLET5_LOGIN
PATH=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq/bin:/home/runderwood/git/contrib/spack/lib/spack/env/gcc:/home/runderwood/git/contrib/spack/lib/spack/env/case-insensitive:/home/runderwood/git/contrib/spack/lib/spack/env:/home/runderwood/git/contrib/spack/bin:/usr/local/cuda/bin:/usr/lib64/openmpi/bin:/home/runderwood/.cargo/bin:/home/runderwood/.local/bin:/home/runderwood/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/runderwood/.fzf/bin; export PATH
PKG_CONFIG_PATH=/home/runderwood/.local/share/pkgconfig/; export PKG_CONFIG_PATH
PROFILEHOME=''; export PROFILEHOME
#PWD=/home/runderwood; export PWD
PYTHONHOME=/usr; export PYTHONHOME
PYTHONPATH=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-setuptools-58.2.0-f6pxnlab6pt4jyjf4gpcqnuxqt5elrrs/lib64/python3.10/site-packages:/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-pip-21.1.2-aeyart66czf33oy3idbdedod5wrorpoq/lib64/python3.10/site-packages:/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-tomli-1.2.1-vtwig2q7qiw4f4uimbcvpqnuhwegcwpq/lib64/python3.10/site-packages:/usr/lib64/python3.10/site-packages/openmpi:; export PYTHONPATH
QT_AUTO_SCREEN_SCALE_FACTOR=0; export QT_AUTO_SCREEN_SCALE_FACTOR
QT_IM_MODULE=xim; export QT_IM_MODULE
SHELL=/bin/bash; export SHELL
SHELL_SESSION_ID=3f6ff882b5fd4d9d8ce93b785e911684; export SHELL_SESSION_ID
SHLVL=1; export SHLVL
SPACK_CC=/usr/bin/gcc; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_SPEC=gcc@11.2.1; export SPACK_COMPILER_SPEC
SPACK_CXX=/usr/bin/g++; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR=/home/runderwood; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=py-tomli-vtwig2q; export SPACK_DEBUG_LOG_ID
SPACK_DTAGS_TO_ADD=--disable-new-dtags; export SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP=--enable-new-dtags; export SPACK_DTAGS_TO_STRIP
SPACK_ENV_PATH=/home/runderwood/git/contrib/spack/lib/spack/env:/home/runderwood/git/contrib/spack/lib/spack/env/case-insensitive:/home/runderwood/git/contrib/spack/lib/spack/env/gcc; export SPACK_ENV_PATH
SPACK_F77=/usr/bin/gfortran; export SPACK_F77
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC=/usr/bin/gfortran; export SPACK_FC
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=''; export SPACK_INCLUDE_DIRS
SPACK_LD_LIBRARY_PATH=/home/runderwood/.local/lib64/:/home/runderwood/.local/lib/:; export SPACK_LD_LIBRARY_PATH
SPACK_LINKER_ARG=-Wl,; export SPACK_LINKER_ARG
SPACK_LINK_DIRS=''; export SPACK_LINK_DIRS
SPACK_PYTHON=/usr/bin/python3; export SPACK_PYTHON
SPACK_ROOT=/home/runderwood/git/contrib/spack; export SPACK_ROOT
SPACK_RPATH_DIRS=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-tomli-1.2.1-vtwig2q7qiw4f4uimbcvpqnuhwegcwpq/lib:/home/runderwood/git/contrib/spack/opt/spack/linux-fedora35-skylake/gcc-11.2.1/py-tomli-1.2.1-vtwig2q7qiw4f4uimbcvpqnuhwegcwpq/lib64; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC='py-tomli@1.2.1%gcc@11.2.1 arch=linux-fedora35-skylake/vtwig2q'; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS=/bin:/usr/bin:/usr/local/bin:/bin64:/usr/bin64:/usr/local/bin64:/include:/usr/include:/usr/local/include:/lib:/usr/lib:/usr/local/lib:/lib64:/usr/lib64:/usr/local/lib64:/:/usr:/usr/local; export SPACK_SYSTEM_DIRS
SPACK_TARGET_ARGS='-march=skylake -mtune=skylake'; export SPACK_TARGET_ARGS
SSH_AGENT_PID=1459; export SSH_AGENT_PID
SSH_ASKPASS=/usr/bin/ksshaskpass; export SSH_ASKPASS
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXhqkcRH/agent.1314; export SSH_AUTH_SOCK
SYSTEMD_EXEC_PID=1537; export SYSTEMD_EXEC_PID
TERM=xterm-256color; export TERM
USER=runderwood; export USER
WINDOWID=85983239; export WINDOWID
XAUTHORITY=/run/user/1000/xauth_PTFTYl; export XAUTHORITY
XCURSOR_SIZE=24; export XCURSOR_SIZE
XCURSOR_THEME=breeze_cursors; export XCURSOR_THEME
XDG_CONFIG_DIRS=/home/runderwood/.config/kdedefaults:/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg; export XDG_CONFIG_DIRS
XDG_CURRENT_DESKTOP=KDE; export XDG_CURRENT_DESKTOP
XDG_DATA_DIRS=/home/runderwood/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share; export XDG_DATA_DIRS
XDG_MENU_PREFIX=kf5-; export XDG_MENU_PREFIX
XDG_RUNTIME_DIR=/run/user/1000; export XDG_RUNTIME_DIR
XDG_SEAT=seat0; export XDG_SEAT
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0; export XDG_SEAT_PATH
XDG_SESSION_CLASS=user; export XDG_SESSION_CLASS
XDG_SESSION_DESKTOP=KDE; export XDG_SESSION_DESKTOP
XDG_SESSION_ID=2; export XDG_SESSION_ID
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1; export XDG_SESSION_PATH
XDG_SESSION_TYPE=x11; export XDG_SESSION_TYPE
XDG_VTNR=2; export XDG_VTNR
XMODIFIERS=@im=none; export XMODIFIERS
which_declare='declare -f'; export which_declare
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by robertu94** [comment]
@adamjstewart I think the new python installation method (especially if we are using --no-deps` may be causing a problem here).  The author of this package has pinned a specific version of pip in their requirements.txt an if it doesn't match the system version we get a build error

This problem also seems to occur on fedora 35 without `--resuse` on the install command.

**Comment by robertu94** [comment]
FYI @Krasow I didn't get to the point where we ran into the bug you saw with py-numcodecs yesterday and hit this bug instead first.

**Comment by adamjstewart** [comment]
I don't think `requirements.txt` is the issue since neither the wheel nor the tarball include this file. Can you try switching from the wheel to the tarball? I'm planning on taking a closer look at this Python build system stuff over winter break.

**Comment by robertu94** [comment]
@adamjstewart I dug a little deeper, and this exception comes from a pip version conflict.  I accidentally had an external python, but not an external pip.  In the spack installed pip there was this contents:

```python
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('pip==21.1.2', 'console_scripts', 'pip')())
```
which then enforced the pip==21.1.2.  However, I am guessing based on the stack trace that it pulled in the library components for `/usr/bin/pip` and was unable to find the library files for the spack-built pip.  Personally, the configuration I used is a configuration that I don't expect spack to support and handle correctly.

I leave it to you whether to close this (my recommendation), or to investigate further if this is expected to work.

**Comment by adamjstewart** [comment]
> I accidentally had an external python, but not an external pip

> it pulled in the library components for `/usr/bin/pip`

These two sentences seem contradictory... I'm surprised that a Spack-installed `pip` wouldn't be able to find its own libraries, setting `PYTHONPATH` should take care of that. It could be a situation where the library is installed in `lib64/python3.6/site-packages` but we add `lib/python3.6/site-packages` to the `PYTHONPATH` instead.

Anyway, I'm fine with closing this, but I'll try to remember to ping you when I do the `PythonPackage` refactor so you can review.

**Comment by robertu94** [comment]
Thanks!  I'll ping you in January if I don't hear anything @adamjstewart
