### ISSUE TITLE
Fail to add build_stage path

### ISSUE THREAD

**Issue by MintMiku** [LLNL/spack#27657]
### Steps to reproduce

We try to add an extra build stage path, and we found it failed.
When we try to add extra misc cache path and test stage path, it works.
```console
spack config --scope=site add "config:build_stage:[\$spack/var/spack/cache/_build-stage/\$user]"
==> Error: Cannot determine valid type for path 'config:build_stage'.
spack config --scope=site add "config:build_stage:\$spack/var/spack/cache/_build-stage/\$user"
==> Error: Cannot determine valid type for path 'config:build_stage'.
```

### Error message

```console
spack --debug --stacktrace config --scope=site add "config:build_stage:[\$spack/var/spack/cache/_build-stage/\$user]"
lib/spack/spack/cmd/__init__.py:123 ==> [2021-11-25-20:26:34.718507] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2021-11-25-20:26:34.721436] Imported config from built-in commands
lib/spack/spack/main.py:884 ==> [2021-11-25-20:26:34.722552] ConfigError: Cannot determine valid type for path 'config:build_stage'.
lib/spack/spack/error.py:54 ==> [2021-11-25-20:26:34.723089] Error: Cannot determine valid type for path 'config:build_stage'.
Traceback (most recent call last):
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/main.py", line 881, in main
    return _main(argv)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/main.py", line 864, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/main.py", line 534, in _invoke_command
    return_val = command(parser, args)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/cmd/config.py", line 481, in config
    action[args.config_command](args)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/cmd/config.py", line 215, in config_add
    spack.config.add(args.path, scope=scope)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/config.py", line 899, in add
    existing = get_valid_type(path)
  File "/GPUFS/sysu_hpcedu_302/swk/env/spack/lib/spack/spack/config.py", line 1100, in get_valid_type
    raise ConfigError("Cannot determine valid type for path '%s'." % path)
spack.config.ConfigError: Cannot determine valid type for path 'config:build_stage'.
```

### Information on your system

* **Spack:** 0.17.0
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
For anybody reading this, a workaround is to edit manually:
```
$ spack config edit config
```

**Comment by alalazo** [comment]
Also, I can't reproduce the error:
![Screenshot from 2023-04-07 10-14-01](https://user-images.githubusercontent.com/4199709/230570650-04f65e23-9e91-4161-a7e5-5771ee90a5c9.png)
