### ISSUE TITLE
Install with cmake (zlib) fails 

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#27652]
### Steps to reproduce

You can reproduce the error with this Dockerfile:
```dockerfile
FROM ubuntu:18.04@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79dbbacddd7d6

LABEL maintainer="Josh Essman <essman1@llnl.gov>, @vsoch"

ARG uptodate_github_commit_spack__spack__develop=90b4f550014f148601c1b5221cea43d08dddde7c
ENV spack_commit=${uptodate_github_commit_spack__spack__develop}
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

RUN apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      curl \
      dh-autoreconf \
      git \
      gnupg2 \
      libssl-dev \
      ninja-build \
      python-dev \ 
      python3-pip \
      python3-setuptools \
      sudo \
      valgrind \
      vim \
      wget

# Install spack
WORKDIR /opt
RUN git clone https://github.com/spack/spack && \
    cd spack && \
    git reset --hard ${spack_commit}
ENV PATH=/opt/spack/bin:$PATH

# Use the autamus build cache for maybe faster install?
RUN python3 -m pip install botocore boto3 && \
    spack mirror add autamus s3://autamus-cache && \
    curl http://s3.amazonaws.com/autamus-cache/build_cache/_pgp/FFEB24B0A9D81F6D5597F9900B59588C86C41BE7.pub > key.pub && \
    spack gpg trust key.pub

# Find packages already installed on system, e.g. autoconf and install cmake
RUN spack external find && \
    spack config add 'packages:all:target:[x86_64]' && \
    spack install cmake@3.20.4

RUN spack view --dependencies no symlink --ignore-conflicts /opt/view cmake@3.20.4
ENV PATH=/opt/view/bin:$PATH

RUN spack external find cmake && \
    spack config add 'packages:cmake:buildable:False'
```
just build it:
```bash
$ docker build -t not-going-to-build-womp-womp .
```

### Error message

```console
Error: Failed to install zlib due to TypeError: sequence item 1: expected str instance, NoneType found
```

### Information on your system

I'm on Ubuntu 18.04, and it fails across Ubuntu versions https://github.com/rse-ops/docker-images/actions/runs/1501912411

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
```
==> [2021-11-25-09:17:52.915521] Error: Failed to install pkgconf due to TypeError: sequence item 1: expected str instance, NoneType found
==> [2021-11-25-09:17:52.916146] InstallError: Terminating after first install failure: sequence item 1: expected str instance, NoneType found
==> [2021-11-25-09:17:52.916183] Error: Terminating after first install failure: sequence item 1: expected str instance, NoneType found
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/util/web.py", line 556, in _urlopen
    return opener(req, *args, **kwargs)
TypeError: open() got an unexpected keyword argument 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/installer.py", line 1640, in install
    self._install_task(task)
  File "/opt/spack/lib/spack/spack/installer.py", line 1165, in _install_task
    full_hash_match):
  File "/opt/spack/lib/spack/spack/installer.py", line 279, in _install_from_cache
    pkg, explicit, unsigned=unsigned, full_hash_match=full_hash_match)
  File "/opt/spack/lib/spack/spack/installer.py", line 405, in _try_install_from_binary_cache
    pkg.spec, full_hash_match=full_hash_match)
  File "/opt/spack/lib/spack/spack/binary_distribution.py", line 1588, in get_mirrors_for_spec
    mirrors=mirrors_to_check)
  File "/opt/spack/lib/spack/spack/binary_distribution.py", line 1506, in try_direct_fetch
    _, _, fs = web_util.read_from_url(buildcache_fetch_url_json)
  File "/opt/spack/lib/spack/spack/util/web.py", line 132, in read_from_url
    response = _urlopen(req, timeout=_timeout, context=context)
  File "/opt/spack/lib/spack/spack/util/web.py", line 561, in _urlopen
    return opener(req, *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/spack/lib/spack/spack/s3_handler.py", line 67, in s3_open
    url, headers, stream = _s3_open(orig_url)
  File "/opt/spack/lib/spack/spack/s3_handler.py", line 45, in _s3_open
    connection=s3_util.get_mirror_connection(parsed))  # noqa: E501
  File "/opt/spack/lib/spack/spack/util/s3.py", line 61, in create_s3_session
    s3_client_args["endpoint_url"] = _parse_s3_endpoint_url(connection["endpoint_url"])  # noqa: E501
  File "/opt/spack/lib/spack/spack/util/s3.py", line 25, in _parse_s3_endpoint_url
    endpoint_url = '://'.join(('https', endpoint_url))
TypeError: sequence item 1: expected str instance, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/opt/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 476, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/opt/spack/lib/spack/spack/cmd/install.py", line 274, in install_specs
    builder.install()
  File "/opt/spack/lib/spack/spack/installer.py", line 1679, in install
    .format(fail_fast_err, str(exc)))
spack.installer.InstallError: Terminating after first install failure: sequence item 1: expected str instance, NoneType found
The command '/bin/sh -c spack -d install --fail-fast cmake@3.20.4' returned a non-zero code: 1
```

Got to love exception based error handling :)

**Comment by haampie** [comment]
@opadron can you fix this?

**Comment by haampie** [comment]
@vsoch i think you'd either have to use an http protocol for the mirror or set S3_ENDPOINT_URL, don't ask me why.

**Comment by vsoch** [comment]
I'm not sure what the change was to start the error, but definitely happy to test any fixes into spack! I'll keep watch of the nightly builds and let you know if/when they are fixed.

**Comment by haampie** [comment]
I'm hitting a seemingly related issue.

```
spack -e . mirror add local file://$PWD/bc
```

Creates this:

```
  mirrors:
    local:
      fetch:
        url: file:///tmp/tmp.82RfP3XQ0J/bc
        access_pair:
        - null
        - null
        access_token: null
        profile: null
        endpoint_url: null
      push:
        url: file:///tmp/tmp.82RfP3XQ0J/bc
        access_pair:
        - null
        - null
        access_token: null
        profile: null
        endpoint_url: null
```

That can't be right. Can that be fixed please? Ping @opadron / @josephsnyder

**Comment by haampie** [comment]
Also:

```
$ spack -e . mirror list
local           CommentedMap([('url', 'file:///tmp/tmp.82RfP3XQ0J/bc'), ('access_pair', [None, None]), ('access_token', None), ('profile', None), ('endpoint_url', None)]) (fetch)
```

**Comment by opadron** [comment]
Likely related to #27694.
