### ISSUE TITLE
Error: errors occurred during concretization of the environment:

### ISSUE THREAD

**Issue by markyoder** [LLNL/spack#27828]
### Steps to reproduce

Summary:
Cannot concretize (some?) environments in (certain?) Spack installations:
```
 $ spack --verbose concretize --force
==> Starting concretization pool with 4 processes
==> Error: errors occurred during concretization of the environment:
```

How to reproduce:
Good question! I have one `spack` installation where this seems to occur. If I duplicate the environment in a different `spack` installation I do not see the problem. See example `curl` environment below. If I try to concretizer, I get the error above. 

How to (mostly) work around:
The behavior is not obviously consistent, but I seem to be able to fix this (concretize successfully) by either:
1. Modifying the compiler, `flags`, `flag`, `flags` by 1) removing the `-we147` flag AND restricting to only one entry, eg `cflags: -O2`.
2. building the environment in a different Spack. I presume a fresh, new installation would do the trick, but `git reset --hard; git pull` does not.
3. Switch from `clingo` to `original` concretizer.

Environment `spack.yaml`:
```
spack:
  # add package specs to the `specs` list
  specs: [curl, autoconf, libtool, automake]
  view: true
  packages:
    curl:
      version: [7.80.0]
    all:
      compiler: [intel@2021.4.0]
  config:
    install_missing_compilers: true
    checksum: true
    deprecated: false
    dirty: false
    ccache: false
    concretizer: clingo
    shared_linking: rpath
    build_stage:
    - /scratch/${user}/spack_stage
    - $tempdir/${user}/spack-stage
    - ~/.spack/stage
#
  compilers:
  - compiler:
      spec: gcc@4.8.5
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags:
        cflags: -mrdrnd
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@19.0.0.117
      paths:
        cc: /share/software/user/restricted/icc/2019/bin/icc
        cxx: /share/software/user/restricted/icc/2019/bin/icpc
        f77: /share/software/user/restricted/ifort/2019/bin/ifort
        fc: /share/software/user/restricted/ifort/2019/bin/ifort
      flags:
        cflags: -O2
        cxxflags: -O2
        fflags: -O2 -fallow-argument-mismatch
      operating_system: centos7
      target: x86_64
      modules: [devel, icc/2019, ifort/2019]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gcc
        cxx: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/g++
        f77: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gfortran
        fc: /home/groups/s-ees/share/cees/spack_compilers/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/gcc-11.2.0-pjl2s6u6mujagujmbvb2chncwdrgeec6/bin/gfortran
      flags:
        cflags: -O2 -mrdrnd
        cxxflags: -O2
        fflags: -O2 -fallow-argument-mismatch
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: intel@2021.4.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/icc
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/icpc
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/ifort
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/intel64/ifort
      flags:
        cflags: -O2 -we147
        cxxflags: -O2 -we147
        fflags: -O2 -fallow-argument-mismatch
      operating_system: centos7
      target: x86_64
      modules: [gcc/9.]
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: oneapi@2021.4.0
      paths:
        cc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/icx
        cxx: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/icpx
        f77: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/ifx
        fc: /home/groups/s-ees/share/cees/spack_cees/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/intel-oneapi-compilers-2021.4.0-2xfl6e7kdhxegq5msukpqoxdmftsu2w6/compiler/2021.4.0/linux/bin/ifx
      flags:
        cflags: -O2
        cxxflags: -O2
        fflags: -O2 -fallow-argument-mismatch
      operating_system: centos7
      target: x86_64
      modules: [gcc/9.]
      environment: {}
      extra_rpaths: []

```

### Error message

```
 $ spack --verbose concretize --force
==> Starting concretization pool with 4 processes
==> Error: errors occurred during concretization of the environment:
```

Looking at debug:
`spack --debug concretize --force`
In this case, it appears to hang up on the `ncurses` package, and is possibly related to switching concretizers?
```
==> [2021-12-06-18:02:06.554133] build(ncurses)
Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/cmd/concretize.py", line 39, in concretize
    concretized_specs = env.concretize(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 1118, in concretize
    return self._concretize_separately(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 1225, in _concretize_separately
    concretized_root_specs = spack.util.parallel.parallel_map(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 135, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 83, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=6131] Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2055, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests, reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2033, in _concretize_from_constraints
    return s.concretized(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2683, in concretized
    clone.concretize(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2639, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 2024, in solve
    return driver.solve(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 592, in solve
    answers = builder.build_specs(tuples)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1958, in build_specs
    self.reorder_flags()
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1875, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 262, in check_same_flags
    assert values1 == values2
AssertionError

[PID=6132] Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2055, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests, reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2033, in _concretize_from_constraints
    return s.concretized(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2683, in concretized
    clone.concretize(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2639, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 2024, in solve
    return driver.solve(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 592, in solve
    answers = builder.build_specs(tuples)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1958, in build_specs
    self.reorder_flags()
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1875, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 262, in check_same_flags
    assert values1 == values2
AssertionError

[PID=6133] Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2055, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests, reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2033, in _concretize_from_constraints
    return s.concretized(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2683, in concretized
    clone.concretize(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2639, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 2024, in solve
    return driver.solve(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 592, in solve
    answers = builder.build_specs(tuples)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1958, in build_specs
    self.reorder_flags()
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1875, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 262, in check_same_flags
    assert values1 == values2
AssertionError

[PID=6134] Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2055, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests, reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/environment/environment.py", line 2033, in _concretize_from_constraints
    return s.concretized(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2683, in concretized
    clone.concretize(tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2639, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 2024, in solve
    return driver.solve(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 592, in solve
    answers = builder.build_specs(tuples)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1958, in build_specs
    self.reorder_flags()
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1875, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 262, in check_same_flags
    assert values1 == values2
AssertionError
```

### Information on your system

* **Spack:** 0.17.0-442-941e650
* **Python:** 3.8.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by markyoder** [comment]
If I do a `spack gc`, I maybe fix the problem with `nurses`, but now get a similar error for `pkgconf`:

```
$ spack --verbose --debug spec ncurses
==> [2021-12-06-18:20:07.354015] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/config.yaml
==> [2021-12-06-18:20:07.371969] Reading config file /home/users/myoder96/.spack/config.yaml
==> [2021-12-06-18:20:07.404750] Reading config file /scratch/users/myoder96/spack_dev/base/spack/var/spack/environments/curl/spack.yaml
==> [2021-12-06-18:20:07.430660] Using environment 'curl'
==> [2021-12-06-18:20:07.433031] Imported spec from built-in commands
==> [2021-12-06-18:20:07.433643] Imported spec from built-in commands
Input spec
--------------------------------
ncurses

Concretized
--------------------------------
==> [2021-12-06-18:20:07.436000] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-06-18:20:07.443253] Deactivated environment 'curl'
==> [2021-12-06-18:20:07.447353] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/config.yaml
==> [2021-12-06-18:20:07.464479] Reading config file /home/users/myoder96/.spack/config.yaml
==> [2021-12-06-18:20:07.467700] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-06-18:20:07.467753] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-06-18:20:07.468104] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-06-18:20:07.475146] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-06-18:20:07.475192] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-06-18:20:07.475252] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-12-06-18:20:07.475550] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults
==> [2021-12-06-18:20:07.475590] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/linux
==> [2021-12-06-18:20:07.475623] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/users/myoder96/.spack/bootstrap/config
==> [2021-12-06-18:20:07.475650] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/users/myoder96/.spack/bootstrap/config/linux
==> [2021-12-06-18:20:07.477341] Reading config file /home/users/myoder96/.spack/bootstrap/config/linux/compilers.yaml
==> [2021-12-06-18:20:07.508622] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-12-06-18:20:07.508692] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-12-06-18:20:07.508973] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-06-18:20:07.659983] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/config.yaml
==> [2021-12-06-18:20:07.725220] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /kt74l7kjzrlp3cgtj2576o33mhsrgyrw" provides the "clingo" Python module
==> [2021-12-06-18:20:07.725953] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/config.yaml
==> [2021-12-06-18:20:07.743241] Reading config file /home/users/myoder96/.spack/config.yaml
==> [2021-12-06-18:20:07.747899] Reading config file /scratch/users/myoder96/spack_dev/base/spack/var/spack/environments/curl/spack.yaml
==> [2021-12-06-18:20:07.774177] Using environment 'curl'
==> [2021-12-06-18:20:07.774373] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/repos.yaml
==> [2021-12-06-18:20:07.815715] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/compilers.yaml
==> [2021-12-06-18:20:07.852172] Reading config file /home/users/myoder96/.spack/linux/compilers.yaml
==> [2021-12-06-18:20:07.861347] Reading config file /scratch/users/myoder96/spack_dev/base/spack/etc/spack/defaults/packages.yaml
==> [2021-12-06-18:20:08.008954] build(ncurses)
==> [2021-12-06-18:20:08.009037] build(pkgconf)
Traceback (most recent call last):
  File "/scratch/users/myoder96/spack_dev/base/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/cmd/spec.py", line 114, in spec
    spec.concretize(**concretize_kwargs)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2639, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/spec.py", line 2610, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 2024, in solve
    return driver.solve(
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 592, in solve
    answers = builder.build_specs(tuples)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1958, in build_specs
    self.reorder_flags()
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 1875, in reorder_flags
    check_same_flags(spec.compiler_flags, compiler_flags)
  File "/scratch/users/myoder96/spack_dev/base/spack/lib/spack/spack/solver/asp.py", line 262, in check_same_flags
    assert values1 == values2
AssertionError
(base) [myoder96@sh03-05n10 /scratch/users/myoder96/spack_dev/base/spack] (job 39987069) $ 

```

**Comment by markyoder** [comment]
Concretizes if I build in a fresh spack install, and it looks like:
`$ spack reindex`

from the root, not in the environment (is `reindex` environment specific?) fixes the problem. I'll tentatively close this.

**Comment by scheibelp** [comment]
> from the root, not in the environment (is reindex environment specific?) fixes the problem. 

`spack reindex` is not environment-specific: if you have manually edited installation prefixes (e.g. if you ``x=`spack location -i foo`; rm -rf $x``) then it will ensure that the Spack installation DB is updated to know that they are no-longer installed. It should be possible to run this with or without an active environment (and both should have the same effect). Were you having an issue where reindexing with an active environment failed?

**Comment by markyoder** [comment]
Nope; I lied. I did that `reindex` in a different install; this is still broken for me -- works in a fresh Spack build; works if I switch back to `original` concretizer.
So is there a way/need to force-reset something when I switch concretizers?

**Comment by scheibelp** [comment]
Interesting, does `spack clean -m -p -f -s` help?

**Comment by markyoder** [comment]
Maybe? I've chased this rabbit down a lot of holes, so It's tough too remember exactly what I did and did not do, before this or after that.

crossing fingers... 

Alas no. But it did get past `ncurses` (or maybe the order changed) and now breaks on `gawk`.  Then, after it fails,  `spack spec {package that did not throw an error}` also.
 
I'll see what happens if I try a few iterations.

**Comment by scheibelp** [comment]
Since you can get desired behavior on a fresh checkout, I'm OK with closing this as-is (especially if you'd prefer not to debug the broken instance). If you need the old instance though, we can keep looking into it.

**Comment by markyoder** [comment]
That's fine to close it. 1) I appear to be able to build the environment in a fresh install, 2) it appears to be a concretizer transition problem (which does not happen often). 
I _was_ hoping to avoid having to reubuild the binaries, but that is certainly not a show-stopper -- is there a good way to salvage the binaries from one spack installation into another (eg, copy `/opt`, then `spack reindex`?)

Thanks for your input; this has been very helpful.

**Comment by scheibelp** [comment]
> is there a good way to salvage the binaries from one spack installation into another (eg, copy /opt, then spack reindex?)

If the old instance is discarded, there isn't an easy way to do this: you would have to use `spack buildcache create`, add the mirror to the new instance, and `spack buildcache install`.

If you `cp -R` the `opt/spack` directory, the `reindex` on the new instance would work, but all the RPATHs of the installed packages would refer to their previous locations, and less commonly (but still often enough to be problematic), packages can also add hardcoded paths to the code.

If you keep the old instance, you could add it as an [upstream](https://spack.readthedocs.io/en/latest/chain.html) for the new instance.

**Comment by markyoder** [comment]
Got it; thanks. Looks like I'm going to need to rebuild -- likely not a bad idea anyway, so I'll go ahead and close this. Thanks again for your help.
