### ISSUE TITLE
Failed to run `spack test` locally

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#2787]
Hi. I failed to run `spack test` locally on CentOS 7 with GCC-4.8.5 . Do I miss any dependency package?

```
$ spack test
Traceback (most recent call last):
  File "/home/rpm/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/rpm/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/rpm/spack/bin/spack", line 170, in _main
    return_val = command(parser, args, unknown_args)
  File "/home/rpm/spack/lib/spack/spack/cmd/test.py", line 108, in test
    return pytest.main(unknown_args + args.tests)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 156, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/rpm/spack/lib/spack/external/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/rpm/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 910, in pytest_cmdline_parse
    self.parse(args)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 1067, in parse
    self._preparse(args, addopts=addopts)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 1027, in _preparse
    self._consider_importhook(args, entrypoint_name)
  File "/home/rpm/spack/lib/spack/external/_pytest/config.py", line 983, in _consider_importhook
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by alalazo** [comment]
@weijianwen It seems you somehow miss `setuptools`...

**Comment by weijianwen** [comment]
Tank you @alalazo . `spack test` works well after installing setuptools.
