### ISSUE TITLE
symlink should have better error message

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#279]
I am seeing this error:

```
$ spack install -v -j1 openblas +ilp64 %gcc@5.3.0-clang-apple-7.0.2
==> Installing openblas
==> Trying to fetch from http://github.com/xianyi/OpenBLAS/archive/v0.2.15.tar.gz
######################################################################## 100.0%
==> Trying to fetch from http://www.agner.org/optimize/objconv.zip
######################################################################## 100.0%
==> Staging archive: /Users/eschnett/src/spack/var/spack/stage/openblas-0.2.15-gpq5etdj36vxztbasmssl5ig43embxcd/v0.2.15.tar.gz
==> Created stage in /Users/eschnett/src/spack/var/spack/stage/openblas-0.2.15-gpq5etdj36vxztbasmssl5ig43embxcd.
==> Staging archive: /Users/eschnett/src/spack/var/spack/stage/resource-objconv-gpq5etdj36vxztbasmssl5ig43embxcd/objconv.zip
Archive:  /Users/eschnett/src/spack/var/spack/stage/resource-objconv-gpq5etdj36vxztbasmssl5ig43embxcd/objconv.zip
  inflating: objconv.exe             
  inflating: objconv-instructions.pdf  
 extracting: source.zip              
 extracting: extras.zip              
  inflating: changelog.txt           
==> Created stage in /Users/eschnett/src/spack/var/spack/stage/resource-objconv-gpq5etdj36vxztbasmssl5ig43embxcd.
Traceback (most recent call last):
  File "/Users/eschnett/src/spack/bin/spack", line 168, in <module>
    main()
  File "/Users/eschnett/src/spack/bin/spack", line 146, in main
    return_val = command(parser, args)
  File "/Users/eschnett/src/spack/lib/spack/spack/cmd/install.py", line 81, in install
    fake=args.fake)
  File "/Users/eschnett/src/spack/lib/spack/spack/package.py", line 838, in do_install
    self.do_patch()
  File "/Users/eschnett/src/spack/lib/spack/spack/package.py", line 724, in do_patch
    self.do_stage()
  File "/Users/eschnett/src/spack/lib/spack/spack/package.py", line 712, in do_stage
    os.symlink(source_path, link_path)
OSError: [Errno 2] No such file or directory
```

Clearly I made an error in my package recipe. However, it's difficult to debug since I don't know which symbolic couldn't be created. I didn't ask for a symbolic link, I think it must be Spack doing this internally, probably having to do with unpacking an archive. This is the relevant description in my recipe:

```
    resource(name='objconv',
             url='http://www.agner.org/optimize/objconv.zip',
             md5='fcf8f01a5683387e17df6d21497d53fa',
             destination='objconv',
             when='+ilp64')
```

Could you output the file names `source_path` and `link_path` with the error message?

**Comment by mathstuf** [comment]
The code doesn't have that symlink call anymore. Seems to have disappeared in 093b8317998c395ed3e2dee7f19d1bdcea1b0560 which also added debugging and changed the logic.

**Comment by tgamblin** [comment]
Closed -- reopen if still reproducible
