### ISSUE TITLE
spack cannot parse special characters in kernel versions

### ISSUE THREAD

**Issue by s-sajid-ali** [LLNL/spack#27960]
### Steps to reproduce

Command in Dockerfile (generated by `spack containerize`):
```
RUN spack -ddd spec hdf5+mpi
```

### Error message

Output:
```
...
Traceback (most recent call last):
  File "/opt/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/opt/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/opt/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/spec.py", line 114, in spec
    spec.concretize(**concretize_kwargs)
  File "/opt/spack/lib/spack/spack/spec.py", line 2648, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/opt/spack/lib/spack/spack/spec.py", line 2619, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests, reuse=reuse)
  File "/opt/spack/lib/spack/spack/solver/asp.py", line 2044, in solve
    return driver.solve(
  File "/opt/spack/lib/spack/spack/solver/asp.py", line 543, in solve
    solver_setup.setup(self, specs, tests=tests, reuse=reuse)
  File "/opt/spack/lib/spack/spack/solver/asp.py", line 1665, in setup
    possible = spack.package.possible_dependencies(
  File "/opt/spack/lib/spack/spack/package.py", line 2785, in possible_dependencies
    if spack.repo.path.is_virtual(pos.name):
  File "/opt/spack/lib/spack/spack/repo.py", line 681, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "/opt/spack/lib/spack/spack/repo.py", line 529, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/opt/spack/lib/spack/spack/repo.py", line 953, in provider_index
    return self.index['providers']
  File "/opt/spack/lib/spack/spack/repo.py", line 359, in __getitem__
    self._build_all_indexes()
  File "/opt/spack/lib/spack/spack/repo.py", line 374, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/opt/spack/lib/spack/spack/repo.py", line 404, in _build_index
    indexer.update(namespaced_name)
  File "/opt/spack/lib/spack/spack/repo.py", line 286, in update
    if spack.repo.path.is_virtual(name, use_index=False):
  File "/opt/spack/lib/spack/spack/repo.py", line 684, in is_virtual
    self.get_pkg_class(pkg_name).virtual)
  File "/opt/spack/lib/spack/spack/repo.py", line 647, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/opt/spack/lib/spack/spack/repo.py", line 1107, in get_pkg_class
    module = self._get_pkg_module(pkg_name)
  File "/opt/spack/lib/spack/spack/repo.py", line 1079, in _get_pkg_module
    module = simp.load_source(fullname, file_path,
  File "/opt/spack/lib/spack/spack/util/imp/importlib_importer.py", line 48, in load_source
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/spack/var/spack/repos/builtin/packages/qt/package.py", line 17, in <module>
    
  File "/opt/spack/lib/spack/spack/version.py", line 181, in __init__
    raise ValueError("Bad characters in version string: %s" % string)
ValueError: Bad characters in version string: 5.4.109+
The command 'docker-shell spack -ddd spec hdf5+mpi' returned a non-zero code: 1
```

### Information on your system

Spack is run in Gitlab CI's Docker-in-Docker mode within an Ubuntu20.04 container. 

Full output is available [here](https://gitlab.com/pirt/pirt-container/-/jobs/1879445701). Note that this mechanism was working fine last month. 

`spack debug report`
```
* **Spack:** 0.17.0
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

## Extras
Kernel version numbers can have a `+` at the end under some circumstances as per [this](https://stackoverflow.com/questions/19333918/dont-add-to-linux-kernel-version) and it might have to be removed when calling `Version()` on the output of `platform.release`. Could we instead parse the first three sets of integers from the linux kernel version?

**Comment by alalazo** [comment]
> Command in Dockerfile (generated by spack containerize):

Where does `-ddd` gets emitted in `spack containerize`?

**Comment by s-sajid-ali** [comment]
>Where does -ddd gets emitted in spack containerize?

I added the `-ddd` in the generated `Dockerfile` to figure out the source of the problem. 

The issue is with the `qt` package recipe as shown on line 1300 of the log : https://gitlab.com/pirt/pirt-container/-/jobs/1879445701
