### ISSUE TITLE
Package py-xrootdpyfs does not concretize with clingo, does with original

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#28060]
### Steps to reproduce

py-xrootdpyfs is not yet in Spack, see PR https://github.com/spack/spack/pull/28058

```console
$ git clone https://github.com/iarspider/spack.git -b add-py-xrootdpyfs
$ spack spec py-xrootdpyfs
```

### Error message

Clingo:

```console
Input spec
--------------------------------
py-xrootdpyfs

Concretized
--------------------------------
==> Error: py-xrootdpyfs is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```

Original:

```console
Input spec
--------------------------------
py-xrootdpyfs

Concretized
--------------------------------
==> Warning: the original concretizer is currently being used.
        Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack starting at v0.18.0
py-xrootdpyfs@0.2.2%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
    ^py-fs@1%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
        ^py-appdirs@1.4.4%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
            ^py-setuptools@59.4.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                ^python@3.8.12%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu20.04-skylake_avx512
                    ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-ubuntu20.04-skylake_avx512
                        ^diffutils@3.8%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                            ^libiconv@1.16%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-skylake_avx512
                    ^expat@2.4.1%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-skylake_avx512
                        ^libbsd@0.11.3%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                            ^libmd@1.0.3%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                    ^gdbm@1.19%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                        ^readline@8.1%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                            ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-skylake_avx512
                                ^pkgconf@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                    ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-skylake_avx512
                        ^libxml2@2.9.12%gcc@9.3.0~python arch=linux-ubuntu20.04-skylake_avx512
                            ^xz@5.2.5%gcc@9.3.0~pic libs=shared,static arch=linux-ubuntu20.04-skylake_avx512
                            ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-skylake_avx512
                        ^tar@1.34%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
                    ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu20.04-skylake_avx512
                    ^openssl@1.1.1l%gcc@9.3.0~docs certs=system arch=linux-ubuntu20.04-skylake_avx512
                        ^perl@5.34.0%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-skylake_avx512
                            ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu20.04-skylake_avx512
                    ^sqlite@3.36.0%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-ubuntu20.04-skylake_avx512
                    ^util-linux-uuid@2.36.2%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
        ^py-pytz@2021.1%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
        ^py-six@1.16.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake_avx512
    ^xrootd@4.12.6%gcc@9.3.0+http~ipo~krb5+python+readline build_type=RelWithDebInfo cxxstd=11 patches=0860cb804d7c67f67f1143049ed52568425add94368a124d60f3e7f21077ad1b arch=linux-ubuntu20.04-skylake_avx512
        ^cmake@3.21.4%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-skylake_avx512
        ^curl@7.80.0%gcc@9.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 tls=openssl arch=linux-ubuntu20.04-skylake_avx512
        ^json-c@0.15%gcc@9.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-skylake_avx512
```

### Information on your system

* **Spack:** 0.13.2-11102-d4bff0b9f5
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** clingo

```console
$ spack -d spec py-xrootdpyfs
spack -d -c config:concretizer:clingo spec py-xrootdpyfs
==> [2021-12-16-23:28:08.582023] Imported spec from built-in commands
==> [2021-12-16-23:28:08.582907] Imported spec from built-in commands
Input spec
--------------------------------
py-xrootdpyfs

Concretized
--------------------------------
==> [2021-12-16-23:28:08.584710] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-16-23:28:08.610279] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-16-23:28:08.622917] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-16-23:28:08.648458] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-16-23:28:08.648566] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-16-23:28:08.649034] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-16-23:28:08.659645] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-16-23:28:08.659756] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-16-23:28:08.659885] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-12-16-23:28:08.660348] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/root/spack/etc/spack/defaults
==> [2021-12-16-23:28:08.660437] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/root/spack/etc/spack/defaults/linux
==> [2021-12-16-23:28:08.660494] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2021-12-16-23:28:08.660539] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2021-12-16-23:28:08.660968] Reading config file /root/.spack/bootstrap/config/linux/compilers.yaml
==> [2021-12-16-23:28:08.692511] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-12-16-23:28:08.692618] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-12-16-23:28:08.692915] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-16-23:28:08.804050] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-16-23:28:08.922652] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /kt74l7kjzrlp3cgtj2576o33mhsrgyrw" provides the "clingo" Python module
==> [2021-12-16-23:28:08.923070] Reading config file /root/spack/etc/spack/defaults/repos.yaml
==> [2021-12-16-23:28:10.323952] Reading config file /root/.spack/linux/compilers.yaml
==> [2021-12-16-23:28:10.333728] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-16-23:28:10.359001] Reading config file /root/spack/etc/spack/defaults/packages.yaml
==> [2021-12-16-23:28:18.358031] UnsatisfiableSpecError: py-xrootdpyfs is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
==> [2021-12-16-23:28:18.358164] Error: py-xrootdpyfs is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
Traceback (most recent call last):
  File "/root/spack/lib/spack/spack/main.py", line 900, in main
    return _main(argv)
  File "/root/spack/lib/spack/spack/main.py", line 883, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/root/spack/lib/spack/spack/main.py", line 553, in _invoke_command
    return_val = command(parser, args)
  File "/root/spack/lib/spack/spack/cmd/spec.py", line 114, in spec
    spec.concretize(**concretize_kwargs)
  File "/root/spack/lib/spack/spack/spec.py", line 2648, in concretize
    self._new_concretize(tests, reuse=reuse)
  File "/root/spack/lib/spack/spack/spec.py", line 2620, in _new_concretize
    result.raise_if_unsat()
  File "/root/spack/lib/spack/spack/solver/asp.py", line 409, in raise_if_unsat
    raise UnsatisfiableSpecError(constraints, conflicts=conflicts)
spack.solver.asp.UnsatisfiableSpecError: py-xrootdpyfs is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```

I have started concretization with `--show-cores=minimized`, but probably won't get the output until tomorrow.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment]
Minimal core:

```
Input spec
--------------------------------
py-xrootdpyfs

Concretized
--------------------------------
==> Error: py-xrootdpyfs is unsatisfiable, conflicts are:
  condition(3835)
  dependency_type(3835,"run")
  imposed_constraint(3835,"version_satisfies","py-fs","0.5.4:1")
  no version satisfies the given constraints
  root("py-xrootdpyfs")
```

So, clingo is fine, it's the old concretizer that is wrong - there is only one version in py-fs - 2.4.14.
