### ISSUE TITLE
spack attribute error on 'package'

### ISSUE THREAD

**Issue by fwang2** [LLNL/spack#2830]
On a vanilla Redhat 6.8 box, I check out a copy of spack and try to run `spack install zeromq`. or other package from `spack list`, I also tried a higher python (2.7.x) with similar results. What am I missing?

```
Traceback (most recent call last):
  File "/ccs/home/f7b/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/ccs/home/f7b/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/ccs/home/f7b/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/cmd/__init__.py", line 118, in parse_specs
    spec.concretize()  # implies normalize
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/spec.py", line 1521, in concretize
    self._expand_virtual_packages(),
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/spec.py", line 1438, in _expand_virtual_packages
    spec)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/concretize.py", line 121, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/concretize.py", line 80, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/package_prefs.py", line 260, in is_spec_buildable
    allpkgs = get_packages_config()
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/package_prefs.py", line 40, in get_packages_config
    if spack.repo.is_virtual(pkg_name)]
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/repository.py", line 348, in is_virtual
    return pkg_name in self.provider_index
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/repository.py", line 234, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/repository.py", line 653, in provider_index
    self._update_provider_index()
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/repository.py", line 647, in _update_provider_index
    self._provider_index.to_yaml(new)
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/llnl/util/lock.py", line 312, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/autofs/xf-svm1_home2/f7b/spack/lib/spack/spack/file_cache.py", line 152, in __exit__
    raise value
AttributeError: package
```

**Comment by scheibelp** [comment]
This appears to be an issue with concretization: e.g. I'm thinking ```spack spec zeromq``` would fail for you in the same fashion.

I'm having trouble replicating this with the latest develop branch, and the relevant lines in the stack trace appear to have changed. Could you try out the latest develop and see if the problem persists? If so, could you post the updated stack trace?

Thanks!

**Comment by scheibelp** [comment]
If you can replicate this issue with the develop branch feel free to reopen. At the moment I'm going to close this since I don't have enough information to replicate and this is pretty old.
