### ISSUE TITLE
spack uninstall: could not remove prefix, directory not empty: '.spack'

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#28428]
### Steps to reproduce

Uninstall a lot of packages.

### Error message

```console
$ spack -d uninstall -ay
...
==> [2022-01-14-20:35:08.168100] Deleting package prefix [py-google-pasta@0.2.0%gcc@8.5.0 arch=linux-rhel8-zen/hh4cupk]
==> [2022-01-14-20:35:08.176987] Deleting DB entry [py-google-pasta@0.2.0%gcc@8.5.0 arch=linux-rhel8-zen/hh4cupk]
==> [2022-01-14-20:35:08.245183] Reading config file /u/stewart1/spack/etc/spack/defaults/modules.yaml
==> [2022-01-14-20:35:08.252506] Reading config file /u/stewart1/spack/etc/spack/defaults/linux/modules.yaml
==> [2022-01-14-20:35:08.258314] NO MODULE WRITTEN: list of enabled module files is empty
==> [2022-01-14-20:35:08.258521] Successfully uninstalled py-google-pasta@0.2.0%gcc@8.5.0 arch=linux-rhel8-zen/hh4cupk
==> [2022-01-14-20:35:08.266673] Deleting package prefix [py-pytest-runner@5.3.1%gcc@8.5.0 arch=linux-rhel8-zen/xo2f4ur]
==> [2022-01-14-20:35:08.442611] RemoveFailedError: Could not remove prefix /u/stewart1/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/py-pytest-runner-5.3.1-xo2f4urfmkeaw54eucoc5spmzjodkp4e for py-pytest-runner@5.3.1%gcc@8.5.0 arch=linux-rhel8-zen/xo2f4ur : [Errno 39] Directory not empty: '.spack'
==> [2022-01-14-20:35:08.442649] Error: Could not remove prefix /u/stewart1/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/py-pytest-runner-5.3.1-xo2f4urfmkeaw54eucoc5spmzjodkp4e for py-pytest-runner@5.3.1%gcc@8.5.0 arch=linux-rhel8-zen/xo2f4ur : [Errno 39] Directory not empty: '.spack'
Traceback (most recent call last):
  File "/u/stewart1/spack/lib/spack/spack/directory_layout.py", line 351, in remove_install_directory
    shutil.rmtree(path)
  File "/usr/lib64/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.6/shutil.py", line 428, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 426, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: '.spack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/stewart1/spack/lib/spack/spack/main.py", line 900, in main
    return _main(argv)
  File "/u/stewart1/spack/lib/spack/spack/main.py", line 883, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/u/stewart1/spack/lib/spack/spack/main.py", line 553, in _invoke_command
    return_val = command(parser, args)
  File "/u/stewart1/spack/lib/spack/spack/cmd/uninstall.py", line 360, in uninstall
    uninstall_specs(args, specs)
  File "/u/stewart1/spack/lib/spack/spack/cmd/uninstall.py", line 335, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/u/stewart1/spack/lib/spack/spack/cmd/uninstall.py", line 237, in do_uninstall
    item.do_uninstall(force=force)
  File "/u/stewart1/spack/lib/spack/spack/package.py", line 2284, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/u/stewart1/spack/lib/spack/spack/package.py", line 2252, in uninstall_by_spec
    spack.store.layout.remove_install_directory(spec, deprecated)
  File "/u/stewart1/spack/lib/spack/spack/directory_layout.py", line 353, in remove_install_directory
    raise RemoveFailedError(spec, path, e)
spack.directory_layout.RemoveFailedError: Could not remove prefix /u/stewart1/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/py-pytest-runner-5.3.1-xo2f4urfmkeaw54eucoc5spmzjodkp4e for py-pytest-runner@5.3.1%gcc@8.5.0 arch=linux-rhel8-zen/xo2f4ur : [Errno 39] Directory not empty: '.spack'
```
This happens every few packages I try to uninstall. If I run the same command again, it successfully uninstalls the packages that failed last time, but immediately runs into the same issue with a different package. Uninstalling everything takes dozens of tries.

### Information on your system

* **Spack:** 0.17.1-834-a2181e9d25
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Workaround:
```console
$ until spack uninstall -ay; do :; done
```

**Comment by alalazo** [comment]
Is there an environment or list of packages that deterministically reproduces this issue? I haven't encountered it in a while so I'm wondering what might be causing it. By any chance, are you registering some installed Spack package as an external later?

**Comment by adamjstewart** [comment]
I'm not using environments or external packages. I simply ran `spack install py-torchgeo` and `spack uninstall --all`. There don't seem to be any particular sets of packages that trigger the issue, rather this affects almost every package I have installed. I've only ever seen this on one system, so I wonder if that system has a strange configuration that is causing this.

**Comment by alalazo** [comment]
I'm not able to reproduce this, and it's being a while since I had any issue with uninstall. Can you confirm @adamjstewart ?

**Comment by adamjstewart** [comment]
I haven't had any issues lately either. Let's close. I'll reopen if it happens again.
