### ISSUE TITLE
Concretization failing with Git hash

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#28516]
### Steps to reproduce

Trying to concretize this environment:
```yaml
spack:
  concretization: together
  view: false
  specs:
  - nalu-wind@8200f4e659bd6c0bcf6f8a0bd0c7ae3d5708e65b+tioga
  - tioga@73a690616d4ca6478a3968fb6b6de3acd92bc71b
  - trilinos@527e5c342119758cf22409a69c4b2fa508c0a12c
  ```
  Where `nalu-wind`'s hash comes from the `master` branch, `trilinos` comes from the `develop` branch, and `tioga` comes from the `exawind` branch which is linked to the `develop` version.
  
  It doesn't work with either of the dependencies.  
  
  I'm not sure if it is related to #28294 
  
  Pinging @becker33 and @vsoch 

### Error message

```console
# spack -d concretize -f
==> [2022-01-19-19:44:43.467151] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/config.yaml
==> [2022-01-19-19:44:43.487790] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/config.yaml
==> [2022-01-19-19:44:43.495971] Reading config file /Users/psakiev/soft/spack-manager/environments/exawind/snapshots/skylake/hash/spack.yaml
==> [2022-01-19-19:44:43.498108] Using environment '/Users/psakiev/soft/spack-manager/environments/exawind/snapshots/skylake/hash'
==> [2022-01-19-19:44:43.502374] Imported concretize from built-in commands
==> [2022-01-19-19:44:43.503042] Imported concretize from built-in commands
==> [2022-01-19-19:44:43.506358] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/repos.yaml
==> [2022-01-19-19:44:43.509292] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/repos.yaml
==> [2022-01-19-19:44:43.810562] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-01-19-19:44:43.817061] Deactivated environment '/Users/psakiev/soft/spack-manager/environments/exawind/snapshots/skylake/hash'
==> [2022-01-19-19:44:43.820122] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/config.yaml
==> [2022-01-19-19:44:43.836216] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/config.yaml
==> [2022-01-19-19:44:43.837783] DATABASE LOCK TIMEOUT: 3s
==> [2022-01-19-19:44:43.837853] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-01-19-19:44:43.838258] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-01-19-19:44:43.845916] DATABASE LOCK TIMEOUT: 3s
==> [2022-01-19-19:44:43.845994] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-01-19-19:44:43.846077] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-01-19-19:44:43.846463] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/psakiev/soft/spack-manager/spack/etc/spack/defaults
==> [2022-01-19-19:44:43.846514] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/darwin
==> [2022-01-19-19:44:43.846568] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/psakiev/.spack/bootstrap/config
==> [2022-01-19-19:44:43.846631] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/psakiev/.spack/bootstrap/config/darwin
==> [2022-01-19-19:44:43.847852] Reading config file /Users/psakiev/.spack/bootstrap/config/darwin/compilers.yaml
==> [2022-01-19-19:44:43.912449] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=x86_64
==> [2022-01-19-19:44:43.912622] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-01-19-19:44:43.913258] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-01-19-19:44:44.586439] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/config.yaml
==> [2022-01-19-19:44:44.702192] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=x86_64 ^python@3.9 /omsvlh5v6fi2saw5qyqvzsbvqpvrf5yw" provides the "clingo" Python module
==> [2022-01-19-19:44:44.703522] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/config.yaml
==> [2022-01-19-19:44:44.722873] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/config.yaml
==> [2022-01-19-19:44:44.726170] Reading config file /Users/psakiev/soft/spack-manager/environments/exawind/snapshots/skylake/hash/spack.yaml
==> [2022-01-19-19:44:44.728211] Using environment '/Users/psakiev/soft/spack-manager/environments/exawind/snapshots/skylake/hash'
==> [2022-01-19-19:44:47.485340] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/darwin/compilers.yaml
==> [2022-01-19-19:44:47.503610] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/packages.yaml
==> [2022-01-19-19:44:47.531319] Reading config file /Users/psakiev/soft/spack-manager/spack/etc/spack/defaults/darwin/packages.yaml
==> [2022-01-19-19:44:57.824053] UnsatisfiableSpecError: (nalu-wind@8200f4e659bd6c0bcf6f8a0bd0c7ae3d5708e65b+tioga, tioga@73a690616d4ca6478a3968fb6b6de3acd92bc71b, trilinos@527e5c342119758cf22409a69c4b2fa508c0a12c) is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
==> [2022-01-19-19:44:57.824097] Error: (nalu-wind@8200f4e659bd6c0bcf6f8a0bd0c7ae3d5708e65b+tioga, tioga@73a690616d4ca6478a3968fb6b6de3acd92bc71b, trilinos@527e5c342119758cf22409a69c4b2fa508c0a12c) is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
Traceback (most recent call last):
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 900, in main
    return _main(argv)
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 883, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 553, in _invoke_command
    return_val = command(parser, args)
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/cmd/concretize.py", line 39, in concretize
    concretized_specs = env.concretize(
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/environment/environment.py", line 1115, in concretize
    return self._concretize_together(tests=tests, reuse=reuse)
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/environment/environment.py", line 1155, in _concretize_together
    concrete_specs = spack.concretize.concretize_specs_together(
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/concretize.py", line 746, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/concretize.py", line 756, in _concretize_specs_together_new
    result.raise_if_unsat()
  File "/Users/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 409, in raise_if_unsat
    raise UnsatisfiableSpecError(constraints, conflicts=conflicts)
spack.solver.asp.UnsatisfiableSpecError: (nalu-wind@8200f4e659bd6c0bcf6f8a0bd0c7ae3d5708e65b+tioga, tioga@73a690616d4ca6478a3968fb6b6de3acd92bc71b, trilinos@527e5c342119758cf22409a69c4b2fa508c0a12c) is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
 ```

### Information on your system

* **Spack:** 0.17.1-681-fc9bfe5317
* **Python:** 3.9.5
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
@psakievich I don't think spack understands the relationship between the commits hashes and the versions defined in the spack repository. Because these three packages have pretty special interdependencies it's hard for them to specify in general what versions work with what. You *might* be able to get it to work by changing (for example) the dependency of naul-wind on trilinos from `trilinos@master,develop` (which is precisely two versions) to `trilinos@master:` (which would include any version that evaluates as "newer" than master, but I'm not sure if git hashes fall in that category).

**Comment by psakievich** [comment]
@sethrj thanks for looking into this. I will have to test this out with your latest changes to the package.

**Comment by sethrj** [comment]
You may end up having to add versions like I specified, but the change to nalu was a prerequisite

**Comment by psakievich** [comment]
@sethrj @becker33 so if I totally remove the versions from `trilinos` and `tioga` then it concretizes successfully.  So it does seem like the git hash wasn't considered new enough with `trilinos@master:` and `tioga@develop:` (it didn't concretize with these changes) I don't think we can go with any older versions of these dependencies for nalu-wind unfortunately.

**Comment by psakievich** [comment]
I'm guessing this is a `concretize.lp thing` then?

**Comment by sethrj** [comment]
I don't understand `concretize.lp thing`? This is ultimately an issue with the Spack version semantics. Spack's versioning class (`spack.version.Version`) knows that `develop` is newer than `master`, `master` is greater than numeric versions, and (this is the key point and the worst part of the version heuristic) **all other alphanumeric versions compare lower than version 0.0.0**. So your trilinos `@527e5...` looks to spack as though it came from 1995 and so won't satisfy the requirement for nalu-wind.

What you'll *probably* have to do is define special version numbers in these packages representing your git hashes and appearing newer than master. For example, you could define in trilinos:
```
    version('master.20220113', commit='527e5c342119758cf22409a69c4b2fa508c0a12c')
```
and use that version number instead of your manual hash (which frankly I don't think spack could download even if it *did* concretize).

**Comment by psakievich** [comment]
Ah I see @sethrj. The precedent is defined in the versions. So the git hash stuff is a newish feature that still needs the documentation merged where you give a hash instead of a version and then it automagically finds the matching hash and downloads it for you. So I think we just need to make it so whatever object representation this has is given the second highest or highest precedent in the Version hierarchy. @becker33 will know if we're on or off track here. I would think it needs to be the highest precedent like develop specs so we can always concretize git hashes.

**Comment by sethrj** [comment]
Oh cool! Well once the ordering for git hashes is such that they're automatically "greater than develop" the changes to nalu-wind (making the version requirements open-ended rather than exact) should fix it.

**Comment by alalazo** [comment]
@haampie fyi

**Comment by psakievich** [comment]
Oh I forgot about this issue. We can probably close it with the git versioning added by #30998
