### ISSUE TITLE
Installation issue: py-scipy 1.7.3 failure on LLNL's RZansel platform

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#28814]
### Steps to reproduce the issue

Mentioning @becker33 in case this issue is LLNL-specific.
*****************************************************************************************

This issue happens for me on LLNL's RZansel platform. To reproduce, follow these steps:

1. Log into LLNL's RZansel platform (IBM power9)
2. Clone most recent hash from `develop`:
```console
[quellyn@rzansel61]$ git clone git@github.com:spack/spack.git
[quellyn@rzansel61]$ cd spack
```

3. Get a compute node:
```console
[quellyn@rzansel61]$ lalloc 1 -q pdebug -W 300
```

4. Load the most recent stable GCC module available:
```console
[quellyn@rzansel4]$ module list

Currently Loaded Modules:
  1) xl/2021.09.22   2) spectrum-mpi/rolling-release   3) cuda/10.1.243   4) StdEnv (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge

[quellyn@rzansel4]$ module unload cuda
[quellyn@rzansel4]$ module swap xl gcc/8.3.1

Due to MODULEPATH changes, the following have been reloaded:
  1) spectrum-mpi/rolling-release

[quellyn@rzansel4]$ module list

Currently Loaded Modules:
  1) StdEnv (S)   2) gcc/8.3.1   3) spectrum-mpi/rolling-release

  Where:
   S:  Module is Sticky, requires --force to unload or purge
```

5. Source the spack setup script, clean up environment:
```console
[quellyn@rzansel4]$ source ./share/spack/setup-env.sh
[quellyn@rzansel4]$ spack clean -ab
[quellyn@rzansel4]$ rm -rf ~/.spack
```

6.  Detect available compilers:
```console
[quellyn@rzansel4]$ spack compiler find

==> Added 7 new compilers to /g/g12/quellyn/.spack/linux/compilers.yaml
    xl_r@16.1  xl@16.1  gcc@8.3.1  gcc@4.9.3  gcc@4.8.5  clang@12.0.1  clang@6.0.0
==> Compilers are defined in the following files:
    /g/g12/quellyn/.spack/linux/compilers.yaml
```

7. Try to build `py-scipy 1.7.3`:
```console
[quellyn@rzansel4]$ spack install py-scipy@1.7.3%gcc@8.3.1
```

The above fails with:
```
Processing /tmp/quellyn/spack-stage/spack-stage-py-scipy-1.7.3-vllws5wm6bhzrohhddgxriwuop6n6kxx/spack-src-src to build t  Added file:///tmp/quellyn/spack-stage/spack-stage-py-scipy-1.7.3-vllws5wm6bhzrohhddgxriwuop6n6kxx/spack-src to build tracker '/tmp/pip-req-tracker-xobymc23'
  Created temporary directory: /tmp/pip-modern-metadata-vsy4e_36
  Preparing metadata (pyproject.toml): started
  Running command /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/python-3.9.10-z7cxgxwgmyuymangexbjg3dfbjwtns4u/bin/python3.9 /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/tmp/tmpktko6ay31-nprcgeuxqrmtvzh  setup.py:491: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-vsy4e_36'), proceeding with generating Cython sources and expanding templates    warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
  Running from SciPy source directory.zed setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-vsy4e_36'),  Traceback (most recent call last):ources and expanding templates
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()om SciPy source directory.
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-setuptools-57.4.0-xs2nb3azns4o2ituffaj5npkkeul43dx/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-setuptools-57.4.0-xs2nb3azns4o2ituffaj5npkkeul43dx/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-setuptools-57.4.0-xs2nb3azns4o2ituffaj5npkkeul43dx/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 631, in <module>
      setup_package()
    File "setup.py", line 608, in setup_package
      cmdclass['build_ext'] = get_build_ext_override()
    File "setup.py", line 242, in get_build_ext_override
      import pythran
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/__init__.py", line 41, in <module>
      from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/toolchain.py", line 6, in <module>
      from pythran.backend import Cxx, Python
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/backend.py", line 7, in <module>
      from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/analyses/__init__.py", line 12, in <module>
      from .aliases import Aliases, StrictAliases
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/analyses/aliases.py", line 6, in <module>
      from pythran.syntax import PythranSyntaxError
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/syntax.py", line 7, in <module>
      from pythran.tables import MODULES
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/pythran/tables.py", line 4524, in <module>
      omp_version = getattr(__import__('omp'), 'VERSION', 45)
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/omp/__init__.py", line 130, in <module>
      sys.modules[__name__] = OpenMP()
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/omp/__init__.py", line 33, in __init__
      self.init_not_msvc()
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pythran-0.9.12-26e5uhqoc7mxs3crrxdoxnh5j5gluyei/lib/python3.9/site-packages/omp/__init__.py", line 110, in init_not_msvc
      self.libomp = ctypes.CDLL(libomp_path)
    File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/python-3.9.10-z7cxgxwgmyuymangexbjg3dfbjwtns4u/lib/python3.9/ctypes/__init__.py", line 374, in __init__
      self._handle = _dlopen(self._name, mode)
  OSError: /usr/tce/packages/gcc/gcc-8.3.1/rh/usr/bin/../lib/gcc/ppc64le-redhat-linux/8/libgomp.so: invalid ELF header
  Preparing metadata (pyproject.toml): finished with status 'error'
WARNING: Discarding file:///tmp/quellyn/spack-stage/spack-stage-py-scipy-1.7.3-vllws5wm6bhzrohhddgxriwuop6n6kxx/spack-src. Command errored out with exit status 1: /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/python-3.9.10-z7cxgxwgmyuymangexbjg3dfbjwtns4u/bin/python3.9 /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/tmp/tmpktko6ay3 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/python-3.9.10-z7cxgxwgmyuymangexbjg3dfbjwtns4u/bin/python3.9 /g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/tmp/tmpktko6ay3 Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/g/g12/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1/py-pip-21.3.1-nprcgeuxqrmtvzhuxhkwinuca4vtj7vo/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
```

The `setuptools` messages are worrying, but this is the one that really caught my eye:
```
  OSError: /usr/tce/packages/gcc/gcc-8.3.1/rh/usr/bin/../lib/gcc/ppc64le-redhat-linux/8/libgomp.so: invalid ELF header
```

It turns out that `libgomp.so` is a script on RZansel:

```console
[quellyn@rzansel61]$ cat /usr/tce/packages/gcc/gcc-8.3.1/rh/usr/lib/gcc/ppc64le-redhat-linux/8/libgomp.so

/* GNU ld script */
OUTPUT_FORMAT(elf64-powerpcle)
INPUT ( /usr/lib64/libgomp.so.1 )
```

By contrast if I look at the closest equivalent GCC module (gcc/8.3.0 module) on a LANL cluster, it's a symlink to a real library:

```console
[quellyn@cn2026 ~]$ ls -la /projects/opt/ppc64le/p9/gcc/8.3.0/lib64/libgomp.so
lrwxrwxrwx 1 root darwin-admin 16 Sep 24  2019 /projects/opt/ppc64le/p9/gcc/8.3.0/lib64/libgomp.so -> libgomp.so.1.0.0
[quellyn@cn2026 ~]$ file /projects/opt/ppc64le/p9/gcc/8.3.0/lib64/libgomp.so.1.0.0
/projects/opt/ppc64le/p9/gcc/8.3.0/lib64/libgomp.so.1.0.0: ELF 64-bit LSB shared object, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, not stripped
```

Note that `py-scipy 1.7.3` builds fine on the LANL cluster.

If I back down to `py-scip 1.6.3` (which does not require `py-pythran`), it builds fine on RZansel.

### Information on your system

```console
[quellyn@rzansel4]$ spack debug report
* **Spack:** 0.17.1-1101-c791ddc742
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8019196/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8019197/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by bvanessen** [comment]
@tgamblin @becker33 This is similar to what I am seeing.

**Comment by ipdemes** [comment]
I am seeing similar error on my MAC laptop. Is there a solution?

**Comment by quellyn** [comment]
Since advancing to `py-scipy@1.8:`, I haven't encountered this issue again.
