### ISSUE TITLE
missing dependency: py-pyopencl depends on py-six

### ISSUE THREAD

**Issue by npf** [LLNL/spack#28916]
### Steps to reproduce

```console
git checkout develop
spack install py-pyopencl
spack load py-pyopencl
```

### Error message

```console
$ python -c "import pyopencl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/grid5000/spack/opt/spack/linux-debian11-x86_64/gcc-10.2.0/py-pyopencl-2020.2.2-hbwcjbcd2atqc4ycj56bpiowbrw3vuse/lib/python3.8/site-packages/pyopencl/__init__.py", line 23, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

### Information on your system

$ spack debug report
* **Spack:** 0.17.1-1045-cd4aad7627
* **Python:** 3.9.2
* **Platform:** linux-debian11-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by npf** [comment]
The bug comes from the fact `py-pytools@2021.2.9` does not depend on `py-six` anymore since commit 3db918b1cdfb720df22d6571804259ede8dc40f7.

My analysis is that `py-pyopencl` imports `py-six` in its `__init__.py`, so it should have a direct dependency on `py-six` rather than relying on `py-six` coming as an indirect dependency e.g. of `py-pytools`.

**Comment by npf** [comment]
Hello, should I close the issue now that it is merged/fixed in develop ?
