### ISSUE TITLE
spack install --test root not working properly in environment

### ISSUE THREAD

**Issue by bvanessen** [LLNL/spack#29447]
### Steps to reproduce

When installing py-numpy in a environment with other root packages and the `--test root` flag is set, it fails to build because it cannot find `py-pytest` and it doesn't show up as a dependency in the concretization.

```
spack add lbann@gitlab-pip-ivybridge +lld +deterministic +vision +numpy +onednn +half +fft ^hydrogen@develop ^dihydrogen@develop ^aluminum@master %clang ^mvapich2 ^hwloc@1.11.13 ^libtool@2.4.2 ^python@3.9.10
spack develop --no-clone -p /usr/WS2/lbannusr/brian-lbann.git lbann@gitlab-pip-ivybridge
spack add py-numpy@1.16.0:
spack concretize --reuse --test root
spack install --reuse -j26 --test root
```

### Error message

```
==> [2022-03-09-13:26:12.477072] '/usr/WS2/lbannusr/spack_installed_packages/catalyst/opt/spack/linux-rhel7-ivybridge/clang-12.0.1/python-3.9.10-qassf33p2hkuptbbkb2yzlq4odqmngej/bin/python3.9' '-c' 'import numpy; numpy.test("full", verbose=2)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/WS2/lbannusr/spack_installed_packages/catalyst/opt/spack/linux-rhel7-ivybridge/clang-12.0.1/py-numpy-1.22.2-wasb6dleomiv433qdtmlkn3msjhzzeqp/lib/python3.9/site-packages/numpy/_pytesttester.py", line 128, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'
```
[spack_lock.txt](https://github.com/spack/spack/files/8226249/spack_lock.txt)
[spack_yaml.txt](https://github.com/spack/spack/files/8226250/spack_yaml.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8226251/spack-build-env.txt)
[spack-build-lbann-gitlab-pip-ivybridge.log](https://github.com/spack/spack/files/8226252/spack-build-lbann-gitlab-pip-ivybridge.log)
[spack-build-out.txt](https://github.com/spack/spack/files/8226253/spack-build-out.txt)

### Information on your system

This happened on pascal, catalyst, and lassen at LLNL LC.

```
* **Spack:** 0.17.1-1431-1c23f5abe0
* **Python:** 3.7.2
* **Platform:** linux-rhel7-ivybridge
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by vvolkl** [comment]
I can confirm - same thing with the catch2 dependency of podio, for example.

**Comment by tmadlener** [comment]
This seems to happen even outside of environments, staying with the podio example:

`spack install --test=root podio` seems to work and install podio, but the tests are not run

On the other hand

`spack dev-build --test=root podio@master` runs into the problem that catch2 is not in the build environment and podio fails at the cmake stage.

**Comment by bvanessen** [comment]
@alalazo @adamjstewart @becker33 @tgamblin @scheibelp Here is the issue that I brought up at the end of the meeting this morning.

**Comment by bvanessen** [comment]
@alalazo @adamjstewart @becker33 @tgamblin @scheibelp Has there been any progress on this issue?

**Comment by bvanessen** [comment]
@alalazo @adamjstewart @becker33 @tgamblin @scheibelp I am still seeing this at the head of develop >v0.18.  Is there anyone looking into this?

**Comment by bvanessen** [comment]
@alalazo

**Comment by alalazo** [comment]
I could reproduce with a simple:
```console
$ spack env activate --temp
$ spack add py-numpy@1.16.0:
$ spack concretize --test=root
$ spack install --test=root
```
in the logs I have:
```
==> [2022-06-23-13:06:18.444765] Running install-time tests
==> [2022-06-23-13:06:18.444853] ('RUN-TESTS: install-time tests [test]',)
==> [2022-06-23-13:06:22.819071] '/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.9.13-dq5pobmzfvky4jpu2isonyrui6juf2kt/bin/python3.9' '-c' 'import numpy; numpy.test("full", verbose=2)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-numpy-1.22.4-nfkkso7nn66cfucuaitz5spak2dx3snz/lib/python3.9/site-packages/numpy/_pytesttester.py", line 128, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by alalazo** [comment]
I think here we have a few design issues to sort out:
1. It probably doesn't make much sense to `spack concretize --test=*` an environment, if all we record are the `build`, `link` and `run` dependencies
2. We can probably attach test dependencies when calling `spack install --test=*` on an environment, but those dependencies specs will not currently be reflected in any data structure related to the environment

Besides that, how are dependencies needed by runtime tests (`spack test`) treated? @becker33 @tldahlgren 

If it matters, we can do things similar to:
```python
>>> s = spack.spec.Spec('py-numpy').concretized()
>>> s.dag_hash()
'nfkkso7nn66cfucuaitz5spak2dx3snz'
>>> len(s.dependencies(deptype='test'))
0
>>>
>>> t = spack.spec.Spec('py-numpy').concretized(tests=True)
>>> t.dag_hash()
'nfkkso7nn66cfucuaitz5spak2dx3snz'
>>> len(t.dependencies(deptype='test'))
2
```
Wondering if with some slight modifications to `concretize.lp` we could reuse a concrete spec and attach to it test dependencies.

**Comment by alalazo** [comment]
## Workaround

If we let `spack install` create the lockfile too:
```console
$ spack env activate --temp
$ spack add py-numpy@1.16.0:
$ spack install --test=root
```
the specs in memory have the test dependencies attached and everything works as expected. Lowering the priority of the bug, since we have a workaround for that.

**Comment by jmansour** [comment]
Unfortunately the work around doesn't appear to consistently work. 

For example, for this env,

```yaml
spack:
  specs:
  - py-numpy
  view: true
  concretizer:
    unify: true
    reuse: false
```

running `spack install --test=root` fails due to `pytest` being missing.  I believe the difference is due to the `concretizer:unify:true` option (which as I understand it, shouldn't even make a difference here). Setting it to `false` results in `pytest` being included generally, although it disappears again under certain other conditions.

**Comment by bvanessen** [comment]
@alalazo Any updates on ways to address this issue?

**Comment by alalazo** [comment]
@bvanessen Not so far. I think addressing this properly require some design changes, maybe also distinguishing between buil-time test dependencies and run-time test dependencies (i.e. the one needed to run `spack test`). @tldahlgren and @becker33 might have a more informed opinion on this.

**Comment by ma595** [comment]
I'm finding that the tests do indeed run with the workaround above. If a test fails however, it seems that the package is removed. Is there a way to install the package even if a test isn't successful? Or even, is there a way to run tests after the package has been installed with `spack install` (i.e. avoiding the use of `spack install --test root`)? Thanks.

**Comment by adamjstewart** [comment]
> Is there a way to install the package even if a test isn't successful?

Nope

> Or even, is there a way to run tests after the package has been installed with `spack install`

Yes, `spack test run ...`

**Comment by tldahlgren** [comment]
> 
> > Or even, is there a way to run tests after the package has been installed with `spack install`
> 
> Yes, `spack test run ...`

To clarify, `spack test run` will run tests through the package's `test()` method, which will include inherited checks when available (e.g. Python's import checks).

**Comment by ma595** [comment]
Thanks. Therefore, to run a series of pytest tests using `spack test run ...` we need to include pytest as a runtime `run` dependency, and implement a `def test(self): ` function pointing to the repo tests (calling pytest using `Executable(py.test)` or similar)?

**Comment by adamjstewart** [comment]
> we need to include pytest as a runtime `run` dependency

Yes. But I'm currently not accepting PRs that add pytest as a `run` dependency because it isn't. The right way to do this would be to make it a `test` dependency. The fact that `test` dependencies don't show up in `spack test run` is a bug IMO.

> and implement a `def test(self):` function pointing to the repo tests (calling pytest using `Executable(py.test)` or similar)?

Yep. See `py-matplotlib` and `py-statsmodels` for examples of this. Currently, there's a whole history of `spack install --test` and `spack test run` not being compatible, so now isn't a great time to try to add new tests. If you want I can link to several open issues on this. I tend to avoid using `spack test run` because of all of these bugs.

**Comment by elenimath** [comment]
@alalazo the workaround doesn't work with `concretizer:unify:true` as mentioned above, but I think #35290 would fix that. 

The problem is actually that `spack concretize --test root` doesn't concretize test dependencies in general when `concretizer:unify` is set to `true` (#35289), but the fix is quite simple.

**Comment by brenthuisman** [comment]
I'm running into our build type == test dependencies being seemingly invisible to Spack (`spack spec -I arbor` and `spack dependencies --deptype test arbor` do not show the Arbor test dependency, Google Test). I'm just doing dev-builds in our CI, so no `spack.yaml` env file to tweak. Is there a workaround for dev-builds?

**Comment by G-Ragghianti** [comment]
We are hitting this bug with the slate package currently.

**Comment by alalazo** [comment]
I think the state didn't change since https://github.com/spack/spack/issues/29447#issuecomment-1223888325 We need to redesign a few things around "test" dependencies to have a proper fix, sorry. I'm bumping up the impact for more visibility of this bug.
