### ISSUE TITLE
spack ci rebuild: import_signing_key: compression algorithm mismatch yields interactive prompt, causes non-zero exit

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#29465]
### Steps to reproduce

`spack ci rebuild` may fail to import a signing key if that signing key encodes a preference for a compression algorithm not available to the GPG where `spack ci rebuild` is run.

For example, if I generate a key using the GPG on my laptop, where `BZIP2` is a supported compression:
```
$laptop> gpg --version
gpg (GnuPG) 2.3.2
libgcrypt 1.9.4
...
Compression: Uncompressed, ZIP, ZLIB, BZIP2

$laptop> gpg --gen-key
...

$laptop> gpg --export-secret-key --armor <LAPTOP-KEYID> > laptop.privkey 
```

This key thus includes `BZIP2` in its list of preferred compression algorithms:
```
$laptop> gpg --list-packets laptop.privkey
...
:signature packet: algo 22, keyid EA123065E4C2285B
...
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
...
```

Trying to import this key subsequently on a system where GPG doesn't support `BZIP2` compression yields an interactive prompt:
```
$ci-system> gpg --version
gpg (GnuPG) 2.3.4
libgcrypt 1.9.4
...
Compression: Uncompressed, ZIP, ZLIB

$ci-system> gpg --import laptop.privkey
gpg: key EA123065E4C2285B: public key "MacMiniTest" imported
gpg: key EA123065E4C2285B: secret key imported
gpg: WARNING: key EA123065E4C2285B contains preferences for unavailable
algorithms on these user IDs:
gpg:          "MacMiniTest": preference for compression algorithm 3
gpg: it is strongly suggested that you update your preferences and
gpg: re-distribute this key to avoid potential algorithm mismatch problems

Set preference list to:
     Cipher: AES256, AES192, AES, 3DES
     AEAD: OCB, EAX
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, ZIP, Uncompressed
     Features: MDC, AEAD, Keyserver no-modify
Really update the preferences? (y/N)
```

The interactive prompt will cause problems for `spack ci rebuild` and other Spack routines relying on non-interactive GPG import:
```
$ci-system> spack -d python
==> [2022-03-11-09:22:44.750258] Imported python from built-in commands
==> [2022-03-11-09:22:44.750636] Imported python from built-in commands
Spack version 0.17.1
Python 3.8.9, Darwin arm64

>>> import spack
>>> spack_gpg = spack.main.SpackCommand('gpg')
==> [2022-03-11-09:24:10.169150] Imported gpg from built-in commands
==> [2022-03-11-09:24:10.176372] Imported gpg from built-in commands

>>> spack_gpg('trust', 'laptop.privkey', output=str)

Set preference list to:
     Cipher: AES256, AES192, AES, 3DES
     AEAD: OCB, EAX
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, ZIP, Uncompressed
     Features: MDC, AEAD, Keyserver no-modify
Really update the preferences? (y/N)
```

Here's what the GitLab pipeline log would look like if `spack ci rebuild` were run under these circumstances:
```
$ spack -d ci rebuild ...
...
==> [2022-03-11-08:22:19.287928] ci.import_signing_key() will attempt to import a key
==> [2022-03-11-08:22:19.829652] spack gpg list:
==> [2022-03-11-08:22:19.829783] gpg: keybox '/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/opt/spack/gpg/pubring.kbx' created
gpg: /Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/opt/spack/gpg/trustdb.gpg: trustdb created

==> [2022-03-11-08:22:20.315908] ProcessError: Command exited with status 2:
    '/Users/eugeneswalker/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.0.0/gnupg-2.3.4-4rlspbhkcvkxnblt63vtgddosm4toxb3/bin/gpg2' '--import' '/var/folders/9z/kbwgst7n3yj5cqnblzh9mk8c0000h0/T/tmpevdrqbfj/signing_key'
==> [2022-03-11-08:22:20.316680] ProcessError: Command exited with status 2:
    '/Users/eugeneswalker/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.0.0/gnupg-2.3.4-4rlspbhkcvkxnblt63vtgddosm4toxb3/bin/gpg2' '--import' '/var/folders/9z/kbwgst7n3yj5cqnblzh9mk8c0000h0/T/tmpevdrqbfj/signing_key'
==> [2022-03-11-08:22:20.316763] Error: Command exited with status 2:
'/Users/eugeneswalker/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.0.0/gnupg-2.3.4-4rlspbhkcvkxnblt63vtgddosm4toxb3/bin/gpg2' '--import' '/var/folders/9z/kbwgst7n3yj5cqnblzh9mk8c0000h0/T/tmpevdrqbfj/signing_key'
Traceback (most recent call last):
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 916, in main
    return _main(argv)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 871, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 899, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 556, in _invoke_command
    return_val = command(parser, args)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/cmd/ci.py", line 645, in ci
    return args.func(args)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/cmd/ci.py", line 330, in ci_rebuild
    spack_ci.import_signing_key(signing_key)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/ci.py", line 1195, in import_signing_key
    key_import_output = spack_gpg('trust', sign_key_path, output=str)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 615, in __call__
    self.returncode = _invoke_command(
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/main.py", line 556, in _invoke_command
    return_val = command(parser, args)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/cmd/gpg.py", line 212, in gpg
    args.func(args)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/cmd/gpg.py", line 170, in gpg_trust
    spack.util.gpg.trust(args.keyfile)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/util/gpg.py", line 96, in _wrapped
    return func(*args, **kwargs)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/util/gpg.py", line 245, in trust
    GPG('--import', keyfile)
  File "/Users/eugeneswalker/builds/xsd85sz4/0/uo/Mac-Mini-Spack-Test/spack/lib/spack/spack/util/executable.py", line 225, in __call__
    raise ProcessError('Command exited with status %d:' %
spack.util.executable.ProcessError: Command exited with status 2:
    '/Users/eugeneswalker/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.0.0/gnupg-2.3.4-4rlspbhkcvkxnblt63vtgddosm4toxb3/bin/gpg2' '--import' '/var/folders/9z/kbwgst7n3yj5cqnblzh9mk8c0000h0/T/tmpevdrqbfj/signing_key'
```

This issue arose a few years ago: https://github.com/spack/spack/issues/15366

Not sure what, if anything, we can/should do about this, other than making sure people are aware that they need to watch out for this?

FYI to: @adamjstewart @scottwittenburg @wspear @shahzebsiddiqui @opadron 

### Information on your system

* **Spack:** 0.17.1-1531-7ad8937d7a
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
Nice, thanks for doing this detective work @eugeneswalker .  Not sure yet what to do about it, but at least now we're aware it's a thing :+1:

**Comment by alalazo** [comment]
Is this still an issue?

**Comment by eugeneswalker** [comment]
> Is this still an issue?

We worked around this by changing the compression algorithm preferences on our E4S key, and also updating GPG version in some of the CI images. But I think the issue still exists if another key were tried that had certain compression algorithm preferences.
