### ISSUE TITLE
Installation issue: Ginkgo

### ISSUE THREAD

**Issue by upsj** [LLNL/spack#29571]
### Steps to reproduce the issue

```console
$ spack spec -l ginkgo
==> Warning: the original concretizer is currently being used.
        Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack starting at v0.18.0
Input spec
--------------------------------
ginkgo

Concretized
--------------------------------
b7vryss  ginkgo@1.4.0%msvc@19.29.30140~cuda~develtools~full_optimizations~hwloc~ipo~oneapi+openmp~rocm+shared build_type=Release patches=8a5b610 arch=windows-windows10-AMD64
l3jwukd      ^cmake@3.21.0%msvc@19.29.30140~doc~ncurses+openssl+ownlibs~qt build_type=Release arch=windows-windows10-AMD64
pf6fue3      ^ninja@1.10.2%msvc@19.29.30140 arch=windows-windows10-AMD64
flbnfa3          ^python@3.9.6%msvc@19.29.30140+bz2+ctypes+dbm~debug~ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat~pythoncmd~readline+shared+sqlite3+ssl+tix+tkinter~ucs4+uuid+zlib patches=01b5df0,784bb70,e27c00f arch=windows-windows10-AMD64
```

### Error message

<details><summary>NameError: name 'UnsupportedCompilerFlag' is not defined</summary>

```
==> Error: NameError: name 'UnsupportedCompilerFlag' is not defined

C:\Users\oss\spack\var\spack\repos\builtin\packages\ginkgo\package.py:98, in cmake_args:
         95        else:
         96            try:
         97                self.compiler.cxx14_flag
  >>     98            except UnsupportedCompilerFlag:
         99                raise InstallError('Ginkgo requires a C++14-compliant C++ compiler')
```

</details>

### Information on your system

* **Spack:** 0.17.1-1606-5a72204d38
* **Python:** 3.9.6
* **Platform:** windows-windows10-AMD64
* **Concretizer:** original

### Additional information

<details><summary>spack-build-env.txt</summary>

```
ALLUSERSPROFILE='C:\ProgramData'; export ALLUSERSPROFILE
APPDATA='C:\Users\oss\AppData\Roaming'; export APPDATA
CC='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'; export CC
CMAKE_PREFIX_PATH='C:\Users\oss\spack\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\ninja-1.10.2-pf6fue3e32lg3nw6gtrjky5phjeh7ykr;C:\Program Files\CMake'; export CMAKE_PREFIX_PATH
COMMONPROGRAMFILES='C:\Program Files\Common Files'; export COMMONPROGRAMFILES
COMMONPROGRAMFILES(X86)='C:\Program Files (x86)\Common Files'; export COMMONPROGRAMFILES(X86)
COMMONPROGRAMW6432='C:\Program Files\Common Files'; export COMMONPROGRAMW6432
COMPUTERNAME=DESKTOP-HP959B3; export COMPUTERNAME
COMSPEC='C:\WINDOWS\system32\cmd.exe'; export COMSPEC
CUDA_PATH='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5'; export CUDA_PATH
CUDA_PATH_V11_4='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4'; export CUDA_PATH_V11_4
CUDA_PATH_V11_5='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5'; export CUDA_PATH_V11_5
CXX='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'; export CXX
DRIVERDATA='C:\Windows\System32\Drivers\DriverData'; export DRIVERDATA
EDITOR=notepad; export EDITOR
F77=None; export F77
FC=None; export FC
GIT_SSH='C:\Program Files\PuTTY\plink.exe'; export GIT_SSH
HOMEDRIVE=C:; export HOMEDRIVE
HOMEPATH='\Users\oss'; export HOMEPATH
INCLUDE='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt'; export INCLUDE
LC_ALL=C; export LC_ALL
LIB='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64'; export LIB
LOCALAPPDATA='C:\Users\oss\AppData\Local'; export LOCALAPPDATA
LOGONSERVER='\\DESKTOP-HP959B3'; export LOGONSERVER
NUMBER_OF_PROCESSORS=24; export NUMBER_OF_PROCESSORS
NVTOOLSEXT_PATH='C:\Program Files\NVIDIA Corporation\NvToolsExt\'; export NVTOOLSEXT_PATH
ONEDRIVE='C:\Users\oss\OneDrive'; export ONEDRIVE
ONEDRIVECONSUMER='C:\Users\oss\OneDrive'; export ONEDRIVECONSUMER
OS=Windows_NT; export OS
OUTPUT='Python 3.9.6'; export OUTPUT
PATH='C:\Users\oss\spack\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\ninja-1.10.2-pf6fue3e32lg3nw6gtrjky5phjeh7ykr\bin;C:\Program Files\CMake\bin;C:\Users\oss\spack\lib\spack\env\case-insensitive;C:\Users\oss\spack\lib\spack\env;C:\Users\oss\spack\lib\spack\env\case-insensitive;C:\Users\oss\spack\lib\spack\env;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;C:\Users\oss\spack\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Calibre2\;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MATLAB\R2021a\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.3.0\;C:\Users\oss\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\oss\AppData\Local\Programs\Python\Python39\;C:\Users\oss\AppData\Local\Microsoft\WindowsApps;C:\Users\oss\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\oss\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe'; export PATH
PATHEXT='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL'; export PATHEXT
PROCESSOR_ARCHITECTURE=AMD64; export PROCESSOR_ARCHITECTURE
PROCESSOR_IDENTIFIER='AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD'; export PROCESSOR_IDENTIFIER
PROCESSOR_LEVEL=23; export PROCESSOR_LEVEL
PROCESSOR_REVISION=7100; export PROCESSOR_REVISION
PROGRAMDATA='C:\ProgramData'; export PROGRAMDATA
PROGRAMFILES='C:\Program Files'; export PROGRAMFILES
PROGRAMFILES(X86)='C:\Program Files (x86)'; export PROGRAMFILES(X86)
PROGRAMW6432='C:\Program Files'; export PROGRAMW6432
PROMPT='[spack] $P$G'; export PROMPT
PSMODULEPATH='C:\Users\oss\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules'; export PSMODULEPATH
PUBLIC='C:\Users\Public'; export PUBLIC
PYTHON_PF_VER='C:\Users\oss\AppData\Local\Programs\Python\Python39\python.exe'; export PYTHON_PF_VER
PY_EXE='C:\Users\oss\AppData\Local\Programs\Python\Python39\python.exe'; export PY_EXE
SPACK='C:\Users\oss\spack\bin\spack'; export SPACK
SPACKINSTDIR='C:\Users\oss'; export SPACKINSTDIR
SPACK_CC='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_SPEC=msvc@19.29.30140; export SPACK_COMPILER_SPEC
SPACK_CXX='C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe'; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR='C:\Users\oss\spack'; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=ginkgo-b7vryss; export SPACK_DEBUG_LOG_ID
SPACK_DTAGS_TO_ADD=--disable-new-dtags; export SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP=--enable-new-dtags; export SPACK_DTAGS_TO_STRIP
SPACK_ENV_PATH='C:\Users\oss\spack\lib\spack\env;C:\Users\oss\spack\lib\spack\env\case-insensitive;C:\Users\oss\spack\lib\spack\env\;C:\Users\oss\spack\lib\spack\env\case-insensitive'; export SPACK_ENV_PATH
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=''; export SPACK_INCLUDE_DIRS
SPACK_LINKER_ARG=-Wl,; export SPACK_LINKER_ARG
SPACK_LINK_DIRS=''; export SPACK_LINK_DIRS
SPACK_ROOT='C:\Users\oss\spack'; export SPACK_ROOT
SPACK_RPATH_DIRS='C:\Users\oss\spack\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\ginkgo-1.4.0-b7vryssdjgm6jqj5crfb6texwfb4aoa5\lib:C:\Users\oss\spack\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\ginkgo-1.4.0-b7vryssdjgm6jqj5crfb6texwfb4aoa5\lib64'; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC='ginkgo@1.4.0%msvc@19.29.30140~cuda~develtools~full_optimizations~hwloc~ipo~oneapi+openmp~rocm+shared build_type=Release patches=8a5b610 arch=windows-windows10-AMD64/b7vryss'; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS='C:\:C:\Program Files:C:\Program Files (x86):C:\Users:C:\ProgramData'; export SPACK_SYSTEM_DIRS
SPACK_TARGET_ARGS=''; export SPACK_TARGET_ARGS
STR_ARGS=' '"'"'ginkgo'"'"''; export STR_ARGS
STR_FLAGS='ECHO is off.'; export STR_FLAGS
STR_SUBCOMMAND=''"'"'install'"'"''; export STR_SUBCOMMAND
SYSTEMDRIVE=C:; export SYSTEMDRIVE
SYSTEMROOT='C:\WINDOWS'; export SYSTEMROOT
TEMP='C:\Users\oss\AppData\Local\Temp'; export TEMP
TMP='C:\Users\oss\AppData\Local\Temp'; export TMP
USERDOMAIN=DESKTOP-HP959B3; export USERDOMAIN
USERDOMAIN_ROAMINGPROFILE=DESKTOP-HP959B3; export USERDOMAIN_ROAMINGPROFILE
USERNAME=oss; export USERNAME
USERPROFILE='C:\Users\oss'; export USERPROFILE
WINDIR='C:\WINDOWS'; export WINDIR
WSLENV=WT_SESSION::WT_PROFILE_ID; export WSLENV
WT_PROFILE_ID='{61c54bbd-c2c6-5271-96e7-009a87ff44bf}'; export WT_PROFILE_ID
WT_SESSION=555437c4-6fa8-4d22-aea9-f947864b43e1; export WT_SESSION
_SP_ARGS=' "ginkgo"'; export _SP_ARGS
_SP_SUBCOMMAND='"install"'; export _SP_SUBCOMMAND
```

</details>

<details><summary>spack-build-out.txt</summary>

```
==> ginkgo: Executing phase: 'cmake'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\oss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\oss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\oss\spack\lib\spack\llnl\util\tty\log.py", line 816, in background_reader
    line = reader.readline()
ValueError: readline of closed file
```

</details>

cc @tcojean

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tcojean** [comment]
I don't think the new msvc compiler has the CXX version support yet.
See: https://github.com/spack/spack/blob/develop/lib/spack/spack/compilers/msvc.py
Against: https://github.com/spack/spack/blob/develop/lib/spack/spack/compilers/gcc.py#L75
