### ISSUE TITLE
Error with `spack fetch`

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#2975]
I see this error after pulling recent changes today:
```
$ spack fetch openssl
Traceback (most recent call last):
  File "/Users/eschnett/src/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/Users/eschnett/src/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/Users/eschnett/src/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/Users/eschnett/src/spack/lib/spack/spack/cmd/fetch.py", line 55, in fetch
    specs = spack.cmd.parse_specs(args.packages, concretize=True)
  File "/Users/eschnett/src/spack/lib/spack/spack/cmd/__init__.py", line 114, in parse_specs
    spec.concretize()  # implies normalize
  File "/Users/eschnett/src/spack/lib/spack/spack/spec.py", line 1525, in concretize
    self._expand_virtual_packages(),
  File "/Users/eschnett/src/spack/lib/spack/spack/spec.py", line 1442, in _expand_virtual_packages
    spec)
  File "/Users/eschnett/src/spack/lib/spack/spack/concretize.py", line 121, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/Users/eschnett/src/spack/lib/spack/spack/concretize.py", line 80, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/Users/eschnett/src/spack/lib/spack/spack/package_prefs.py", line 260, in is_spec_buildable
    allpkgs = get_packages_config()
  File "/Users/eschnett/src/spack/lib/spack/spack/package_prefs.py", line 40, in get_packages_config
    if spack.repo.is_virtual(pkg_name)]
  File "/Users/eschnett/src/spack/lib/spack/spack/repository.py", line 350, in is_virtual
    return pkg_name in self.provider_index
  File "/Users/eschnett/src/spack/lib/spack/spack/repository.py", line 235, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/Users/eschnett/src/spack/lib/spack/spack/repository.py", line 659, in provider_index
    self._update_provider_index()
  File "/Users/eschnett/src/spack/lib/spack/spack/repository.py", line 653, in _update_provider_index
    self._provider_index.to_yaml(new)
  File "/Users/eschnett/src/spack/lib/spack/llnl/util/lock.py", line 312, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/Users/eschnett/src/spack/lib/spack/spack/file_cache.py", line 154, in __exit__
    raise value
AttributeError: package
```

This happens with local packages added; a vanilla checkout works fine. I assume there might be an error in a local package definition.

Unfortunately, a `print` or `tty.warn` in `repository.py`'s `_update_provider_index` does not make it to the screen, as if the `with spack.misc_cache.write_transaction` there ate up all screen output.

**Comment by eschnett** [comment]
Found the problem -- a leftover property declaration that recently became invalid in one of my packages.
