### ISSUE TITLE
Fatal error(s) when merging prefixes

### ISSUE THREAD

**Issue by raullaasner** [LLNL/spack#29852]
### Steps to reproduce

I have installed some packages with two different compilers:

```console
$ spack find
==> 67 installed packages
-- linux-debian11-skylake / gcc@10.2.1 --------------------------
autoconf@2.69                berkeley-db@18.1.40  gawk@5.1.1  gettext@0.21   libsigsegv@2.13  m4@1.4.19   ncurses@6.2    readline@8.1  xz@5.2.5
autoconf-archive@2019.01.06  bzip2@1.0.8          gcc@10.3.0  gmp@6.2.1      libtool@2.4.6    mpc@1.2.1   perl@5.34.0    tar@1.34      zlib@1.2.11
automake@1.16.5              diffutils@3.8        gdbm@1.19   libiconv@1.16  libxml2@2.9.12   mpfr@4.1.0  pkgconf@1.8.0  texinfo@6.5   zstd@1.5.2

-- linux-debian11-skylake / gcc@10.3.0 --------------------------
autoconf-archive@2019.01.06  expat@2.4.6      gdbm@1.19     hwloc@2.7.1           libffi@3.4.2       libsigsegv@2.13  netcdf-c@4.8.1     openblas@0.3.20  pkgconf@1.8.0  tar@1.34
bison@3.8.2                  fftw@3.3.10      gettext@0.21  libbsd@0.11.5         libiconv@1.16      libxml2@2.9.12   netcdf-cxx4@4.3.1  openmpi@4.1.3    python@3.9.10  util-linux-uuid@2.37.4
bzip2@1.0.8                  findutils@4.8.0  hdf5@1.12.1   libedit@3.1-20210216  libmd@1.0.4        m4@1.4.19        ninja@1.10.2       openssh@8.9p1    readline@8.1   xz@5.2.5
doxygen@1.9.3                flex@2.6.3       hdf5@1.12.1   libevent@2.1.12       libpciaccess@0.16  ncurses@6.2      numactl@2.0.14     openssl@1.1.1n   sqlite@3.37.2  zlib@1.2.11
```

I then create an environment and try to install some packages in it:

```console
$ spack env create myenv
$ spack env activate -p myenv
$ spack install -v hdf5%gcc@10.3.0
```

However, when I try to install the netcdf-c package I get an error.

### Error message

```console
$ spack -d install -v netcdf-c%gcc@10.3.0
==> [2022-04-02-18:00:04.650658] Reading config file /data/raull/builds/spack/etc/spack/defaults/config.yaml
==> [2022-04-02-18:00:04.669270] Reading config file /data/raull/builds/spack/var/spack/environments/spexone/spack.yaml
==> [2022-04-02-18:00:04.670865] Using environment 'spexone'
==> [2022-04-02-18:00:04.677740] Imported install from built-in commands
==> [2022-04-02-18:00:04.678742] Imported install from built-in commands
==> [2022-04-02-18:00:04.679276] Reading config file /data/raull/builds/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-04-02-18:00:04.684417] Deactivated environment 'spexone'
==> [2022-04-02-18:00:04.688459] Reading config file /data/raull/builds/spack/etc/spack/defaults/config.yaml
==> [2022-04-02-18:00:04.700489] DATABASE LOCK TIMEOUT: 3s
==> [2022-04-02-18:00:04.700524] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-04-02-18:00:04.700903] Reading config file /data/raull/builds/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-04-02-18:00:04.705731] DATABASE LOCK TIMEOUT: 3s
==> [2022-04-02-18:00:04.705765] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-04-02-18:00:04.705870] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-04-02-18:00:04.706212] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/data/raull/builds/spack/etc/spack/defaults
==> [2022-04-02-18:00:04.706244] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/data/raull/builds/spack/etc/spack/defaults/linux
==> [2022-04-02-18:00:04.706304] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/raull/.spack/bootstrap/config
==> [2022-04-02-18:00:04.706375] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/raull/.spack/bootstrap/config/linux
==> [2022-04-02-18:00:04.707189] Reading config file /home/raull/.spack/bootstrap/config/linux/compilers.yaml
==> [2022-04-02-18:00:04.733496] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2022-04-02-18:00:04.733551] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-04-02-18:00:04.733777] Reading config file /data/raull/builds/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-04-02-18:00:04.845890] Reading config file /data/raull/builds/spack/etc/spack/defaults/config.yaml
==> [2022-04-02-18:00:04.895580] '/opt/local/EOS/nadc_extern/bullseye/bin/python3.10' '-c' '
import json
from sysconfig import (
    get_config_vars,
    get_config_h_filename,
    get_makefile_filename,
    get_paths,
)

config = get_config_vars()
config['"'"'config_h_filename'"'"'] = get_config_h_filename()
config['"'"'makefile_filename'"'"'] = get_makefile_filename()
config.update(get_paths())

print(json.dumps(config))
'
==> [2022-04-02-18:00:04.926608] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10 /hjd4bd5lwuevmep2cnmin7yzkddsf3al" provides the "clingo" Python module
==> [2022-04-02-18:00:04.927163] Reading config file /data/raull/builds/spack/etc/spack/defaults/config.yaml
==> [2022-04-02-18:00:04.940873] Reading config file /data/raull/builds/spack/var/spack/environments/spexone/spack.yaml
==> [2022-04-02-18:00:04.942105] Using environment 'spexone'
==> [2022-04-02-18:00:04.942202] Reading config file /data/raull/builds/spack/etc/spack/defaults/concretizer.yaml
==> [2022-04-02-18:00:04.943601] Reading config file /data/raull/builds/spack/etc/spack/defaults/repos.yaml
==> [2022-04-02-18:00:05.962335] Reading config file /home/raull/.spack/linux/compilers.yaml
==> [2022-04-02-18:00:05.972942] Reading config file /data/raull/builds/spack/etc/spack/defaults/packages.yaml
==> [2022-04-02-18:00:05.991102] Reading config file /home/raull/.spack/linux/packages.yaml
==> [2022-04-02-18:00:11.309354] build(netcdf-c)
==> [2022-04-02-18:00:11.309418] build(autoconf)
==> [2022-04-02-18:00:11.309467] build(automake)
==> [2022-04-02-18:00:11.309515] build(hdf5)
==> [2022-04-02-18:00:11.309595] build(libtool)
==> [2022-04-02-18:00:11.309670] build(m4)
==> [2022-04-02-18:00:11.309729] build(zlib)
==> [2022-04-02-18:00:11.309788] build(openmpi)
==> [2022-04-02-18:00:11.309835] build(xz)
==> [2022-04-02-18:00:11.309882] build(cmake)
==> [2022-04-02-18:00:11.309926] build(perl)
==> [2022-04-02-18:00:11.309986] build(pkgconf)
==> [2022-04-02-18:00:11.310018] build(libevent)
==> [2022-04-02-18:00:11.310066] build(openssh)
==> [2022-04-02-18:00:11.310110] build(libpciaccess)
==> [2022-04-02-18:00:11.310156] build(libxml2)
==> [2022-04-02-18:00:11.310198] build(libsigsegv)
==> [2022-04-02-18:00:11.310228] build(numactl)
==> [2022-04-02-18:00:11.310258] build(openssl)
==> [2022-04-02-18:00:11.310288] build(hwloc)
==> [2022-04-02-18:00:11.310317] build(berkeley-db)
==> [2022-04-02-18:00:11.310347] build(bzip2)
==> [2022-04-02-18:00:11.310377] build(gdbm)
==> [2022-04-02-18:00:11.310406] build(util-macros)
==> [2022-04-02-18:00:11.310436] build(libedit)
==> [2022-04-02-18:00:11.310465] build(diffutils)
==> [2022-04-02-18:00:11.310495] build(ncurses)
==> [2022-04-02-18:00:11.310525] build(libiconv)
==> [2022-04-02-18:00:11.310554] build(readline)
==> [2022-04-02-18:00:11.319274] Ordered hashes [hdf5]: hdf5/351/ee351eb7dfcb8c857e2d85ef1ab95b61ae59cbd647560e10378fa916043a97f9
==> [2022-04-02-18:00:11.319426] Ordered hashes [berkeley-db]: berkeley-db/61/b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522
==> [2022-04-02-18:00:11.319640] Ordered hashes [m4]: m4/39/bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89, m4/40/9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573
==> [2022-04-02-18:00:11.319842] Ordered hashes [numactl]: numactl/166/4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94, numactl/167/62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006, numactl/168/ff37630df599cfabf0740518b91ec8daaf18e8f288b19adaae5364dc1f6b2296
==> [2022-04-02-18:00:11.319929] Ordered hashes [autoconf]: autoconf/25/7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7, autoconf/26/35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2, autoconf/27/a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee
==> [2022-04-02-18:00:11.448742] exactly one match for netcdf-c in env -> jjpmw42rggd2wda7nx67cheh4mrluieq
==> [2022-04-02-18:00:11.449204] just install netcdf-c
==> [2022-04-02-18:00:11.449240] Installing the following cli specs:
==> [2022-04-02-18:00:11.449301]   netcdf-c
==> [2022-04-02-18:00:11.449367] Assessing installation status of environment packages
==> [2022-04-02-18:00:11.466930] All of the packages are already installed
==> [2022-04-02-18:00:11.502358] 0 specs need to be overwritten
==> [2022-04-02-18:00:11.502401] Initializing the build queue from the build requests
==> [2022-04-02-18:00:11.502464] Ensure all dependencies know all dependents across specs
==> [2022-04-02-18:00:11.647808] Updating view at /data/raull/builds/spack/var/spack/environments/spexone/.spack-env/view
==> [2022-04-02-18:00:11.668670] 99 file conflicts
==> [2022-04-02-18:00:11.668712] Creating 184 dirs and 5018 links
Traceback (most recent call last):
  File "/data/raull/builds/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/data/raull/builds/spack/lib/spack/spack/main.py", line 916, in main
    return _main(argv)
  File "/data/raull/builds/spack/lib/spack/spack/main.py", line 871, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/data/raull/builds/spack/lib/spack/spack/main.py", line 899, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/data/raull/builds/spack/lib/spack/spack/main.py", line 551, in _invoke_command
    return_val = command(parser, args)
  File "/data/raull/builds/spack/lib/spack/spack/cmd/install.py", line 483, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/data/raull/builds/spack/lib/spack/spack/cmd/install.py", line 272, in install_specs
    env.install_specs(specs_to_install, args=cli_args, **kwargs)
  File "/data/raull/builds/spack/lib/spack/spack/environment/environment.py", line 1589, in install_specs
    self.regenerate_views()
  File "/data/raull/builds/spack/lib/spack/spack/environment/environment.py", line 1352, in regenerate_views
    view.regenerate(concretized_root_specs)
  File "/data/raull/builds/spack/lib/spack/spack/environment/environment.py", line 576, in regenerate
    raise e
  File "/data/raull/builds/spack/lib/spack/spack/environment/environment.py", line 560, in regenerate
    view.add_specs(*specs, with_dependencies=False)
  File "/data/raull/builds/spack/lib/spack/spack/filesystem_view.py", line 816, in add_specs
    self.link_metadata(specs)
  File "/data/raull/builds/spack/lib/spack/spack/filesystem_view.py", line 841, in link_metadata
    raise MergeConflictSummary(metadata_visitor.file_conflicts)
llnl.util.link_tree.MergeConflictSummary: 104 fatal error(s) when merging prefixes:
    `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-aomjwvke5y6wgugpnqrxrjnvhj7hyicd/.spack/install_environment.json` and `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-mwfcupg66v6smokbnx5so6gysekw5ulw/.spack/install_environment.json` both project to `.spack/hdf5/install_environment.json`    `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-aomjwvke5y6wgugpnqrxrjnvhj7hyicd/.spack/install_manifest.json` and `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-mwfcupg66v6smokbnx5so6gysekw5ulw/.spack/install_manifest.json` both project to `.spack/hdf5/install_manifest.json`    `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-aomjwvke5y6wgugpnqrxrjnvhj7hyicd/.spack/install_times.json` and `/data/raull/builds/spack/opt/spack/linux-debian11-skylake/gcc-10.3.0/hdf5-1.12.1-mwfcupg66v6smokbnx5so6gysekw5ulw/.spack/install_times.json` both project to `.spack/hdf5/install_times.json`
```

I don't understand where the error comes from because I'm unambiguously specifying the library on the command line.

### Information on your system

```console
$ uname -a
Linux janis 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
$ spack debug report
* **Spack:** 0.18.0.dev0 (a58fa289b9fb9b593773ace91b531b9547614771)
* **Python:** 3.10.4
* **Platform:** linux-debian11-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Apparently you have two flavors of hdf5 with a different hash, meaning you're missing `concretization: together` in your spack.yaml (try `spack config edit` with an active environment to edit the file). To see in what way they're different, compare `spack find -v hdf5`.

**Comment by raullaasner** [comment]
Thank you for the comments and especially the `concretization: together` tip! This issue is now solved. I had manually installed `hdf5@1.12.1` whereas `netcdf-c` had built `hdf5@1.12.1+hl` as a dependency which I didn't realize.

**Comment by haampie** [comment]
maybe concretization: together is the better default...

**Comment by waveman68** [comment]
May I suggest an alternate solution using views in the spack.yaml?

```bash
  view:
    default:
      root: .spack-env/view
      exclude: ['%gcc@10.2.1']
```

Access this with `spack config edit` with your environment activated.
