### ISSUE TITLE
clingo fails to install on macos M1: fails at perl

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#29990]
### Steps to reproduce

I am not able to bootstrap clingo

```
spack spec dealii
```

### Error message

```
$ spack -d spec dealii           
...
==> [2022-04-10-09:30:01.296711] Processing perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl: task=priority=0, status=dequeued, start=1649563201.283545, #dependencies=4
==> [2022-04-10-09:30:01.296939] Acquiring a write lock on perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl with timeout 1e-09
==> [2022-04-10-09:30:01.296996] perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl is now write locked
==> [2022-04-10-09:30:01.298483] Installing perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl
==> [2022-04-10-09:30:01.298509] Searching for binary cache of perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl
==> [2022-04-10-09:30:02.625479] Did not find darwin-monterey-aarch64-apple-clang-13.1.6-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl.spec.json on https://mirror.spack.io/build_cache/darwin-monterey-aarch64-apple-clang-13.1.6-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl.spec.json
  Download failed: HTTP Error 404: Not Found
==> [2022-04-10-09:30:02.625906] Did not find darwin-monterey-aarch64-apple-clang-13.1.6-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl.spec.json on https://mirror.spack.io/build_cache/darwin-monterey-aarch64-apple-clang-13.1.6-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2022-04-10-09:30:02.626978] No binary for perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl found: installing from source
==> [2022-04-10-09:30:02.627331] Creating the installation directory /Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl
==> [2022-04-10-09:30:02.647905] '/usr/bin/git' '-C' '/Users/praveen/Applications/spack' 'rev-parse' 'HEAD'
==> Using cached archive: /Users/praveen/Applications/spack/var/spack/cache/_source-cache/archive/35/357951a491b0ba1ce3611263922feec78ccd581dddc24a446b033e25acf242a1.tar.gz
==> Using cached archive: /Users/praveen/Applications/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Already patched perl
==> perl: Executing phase: 'configure'
==> [2022-04-10-09:30:05.176531] Error: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl' '-Dlocincpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/include' '-Dloclibpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/lib' '-Accflags=-DAPPLLIB_EXP=\"/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/lib/perl5\"' '-Duseshrplib' '-Dusethreads'
See build log for details:
  /var/folders/hh/bdt5s8c5131gxplnt9jm24580000gn/T/praveen/spack-stage/spack-stage-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/spack-build-out.txt

Traceback (most recent call last):
  File "/Users/praveen/Applications/spack/lib/spack/spack/build_environment.py", line 1049, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/Users/praveen/Applications/spack/lib/spack/spack/installer.py", line 2017, in build_process
    return installer.run()
  File "/Users/praveen/Applications/spack/lib/spack/spack/installer.py", line 1871, in run
    self._real_install()
  File "/Users/praveen/Applications/spack/lib/spack/spack/installer.py", line 1978, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/Users/praveen/Applications/spack/lib/spack/spack/package.py", line 135, in phase_wrapper
    phase(spec, prefix)
  File "/Users/praveen/Applications/spack/var/spack/repos/builtin/packages/perl/package.py", line 266, in configure
  File "/Users/praveen/Applications/spack/lib/spack/spack/util/executable.py", line 238, in __call__
    raise ProcessError('Command exited with status %d:' %
spack.util.executable.ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl' '-Dlocincpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/include' '-Dloclibpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/lib' '-Accflags=-DAPPLLIB_EXP=\"/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/lib/perl5\"' '-Duseshrplib' '-Dusethreads'
==> [2022-04-10-09:30:05.183670] Flagging perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl as failed: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl' '-Dlocincpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/include' '-Dloclibpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/lib' '-Accflags=-DAPPLLIB_EXP=\"/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/lib/perl5\"' '-Duseshrplib' '-Dusethreads'
==> [2022-04-10-09:30:05.185000] Warning: Skipping build of openssl-1.1.1n-pozurxpoiqt63hxx5i4xq3frqep5cvsb since perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl failed
==> [2022-04-10-09:30:05.185024] Flagging openssl-1.1.1n-pozurxpoiqt63hxx5i4xq3frqep5cvsb as failed
==> [2022-04-10-09:30:05.185343] Warning: Skipping build of cmake-3.23.0-vfzprafyyxqqmxam62cmcypryjjnp7cv since openssl-1.1.1n-pozurxpoiqt63hxx5i4xq3frqep5cvsb failed
==> [2022-04-10-09:30:05.185360] Flagging cmake-3.23.0-vfzprafyyxqqmxam62cmcypryjjnp7cv as failed
==> [2022-04-10-09:30:05.185814] Warning: Skipping build of clingo-bootstrap-spack-ahbkbebvyhx5qsikttd2cwspmauaxlpw since cmake-3.23.0-vfzprafyyxqqmxam62cmcypryjjnp7cv failed
==> [2022-04-10-09:30:05.185830] Flagging clingo-bootstrap-spack-ahbkbebvyhx5qsikttd2cwspmauaxlpw as failed
==> [2022-04-10-09:30:05.186192] Removing build task for clingo-bootstrap-spack-ahbkbebvyhx5qsikttd2cwspmauaxlpw from list
==> [2022-04-10-09:30:05.186236] Removing build task for cmake-3.23.0-vfzprafyyxqqmxam62cmcypryjjnp7cv from list
==> [2022-04-10-09:30:05.186250] Removing build task for openssl-1.1.1n-pozurxpoiqt63hxx5i4xq3frqep5cvsb from list
==> [2022-04-10-09:30:05.186262] Warning: Skipping build of bison-3.8.2-5i2xp6ooix6lpdufqfe5kwrd5byejgbd since perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl failed
==> [2022-04-10-09:30:05.186273] Flagging bison-3.8.2-5i2xp6ooix6lpdufqfe5kwrd5byejgbd as failed
==> [2022-04-10-09:30:05.186639] No build task for clingo-bootstrap-spack-ahbkbebvyhx5qsikttd2cwspmauaxlpw to skip since bison-3.8.2-5i2xp6ooix6lpdufqfe5kwrd5byejgbd failed
==> [2022-04-10-09:30:05.186653] Removing build task for bison-3.8.2-5i2xp6ooix6lpdufqfe5kwrd5byejgbd from list
==> [2022-04-10-09:30:05.187870] Creating stage lock spack-stage-perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl
==> [2022-04-10-09:30:05.187931] Creating stage lock resource-cpanm-cmtrhef3bebrwzl22vkbk6qymy4mduzl
==> [2022-04-10-09:30:05.187978] [BOOTSTRAP MODULE clingo] Unexpected error "Terminating after first install failure: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl' '-Dlocincpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/include' '-Dloclibpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/lib' '-Accflags=-DAPPLLIB_EXP=\"/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/lib/perl5\"' '-Duseshrplib' '-Dusethreads'"
==> [2022-04-10-09:30:05.189031] Reading config file /Users/praveen/Applications/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/Users/praveen/Applications/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/Users/praveen/Applications/spack/lib/spack/spack/main.py", line 915, in main
    return _main(argv)
  File "/Users/praveen/Applications/spack/lib/spack/spack/main.py", line 870, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/praveen/Applications/spack/lib/spack/spack/main.py", line 898, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/praveen/Applications/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/Users/praveen/Applications/spack/lib/spack/spack/cmd/spec.py", line 83, in spec
    specs = [(s, s.concretized()) for s in input_specs]
  File "/Users/praveen/Applications/spack/lib/spack/spack/cmd/spec.py", line 83, in <listcomp>
    specs = [(s, s.concretized()) for s in input_specs]
  File "/Users/praveen/Applications/spack/lib/spack/spack/spec.py", line 2915, in concretized
    clone.concretize(tests=tests)
  File "/Users/praveen/Applications/spack/lib/spack/spack/spec.py", line 2877, in concretize
    self._new_concretize(tests)
  File "/Users/praveen/Applications/spack/lib/spack/spack/spec.py", line 2849, in _new_concretize
    solver = spack.solver.asp.Solver()
  File "/Users/praveen/Applications/spack/lib/spack/spack/solver/asp.py", line 2085, in __init__
    self.driver = PyclingoDriver()
  File "/Users/praveen/Applications/spack/lib/spack/spack/solver/asp.py", line 483, in __init__
    bootstrap_clingo()
  File "/Users/praveen/Applications/spack/lib/spack/spack/solver/asp.py", line 464, in bootstrap_clingo
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "/Users/praveen/Applications/spack/lib/spack/spack/bootstrap.py", line 752, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(
  File "/Users/praveen/Applications/spack/lib/spack/spack/bootstrap.py", line 519, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %apple-clang target=aarch64" due to the following failures:
    'spack-install' raised InstallError: Terminating after first install failure: ProcessError: Command exited with status 1:
    './Configure' '-des' '-Dprefix=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl' '-Dlocincpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/include' '-Dloclibpth=/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/gdbm-1.19-zcq45gihavmhbxmthbg6i7mxegjkq5ep/lib' '-Accflags=-DAPPLLIB_EXP=\"/Users/praveen/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/perl-5.34.1-cmtrhef3bebrwzl22vkbk6qymy4mduzl/lib/perl5\"' '-Duseshrplib' '-Dusethreads'
    Please run `spack -d spec zlib` for more verbose error messages
```

### Information on your system

* **Spack:** 0.18.0.dev0 (7893be7712ed709f6136ac83f49afc3d718d5ddc)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Related to #28190

**Comment by cpraveen** [comment]
#28190 went beyond perl installation and fails not finding python, but I did not see that in my case.

From the above error message, do you see what is the precise problem in my case ?

homebrew has clingo, is it possible to use that with spack.

**Comment by alalazo** [comment]
> homebrew has clingo, is it possible to use that with spack

If it comes with Python bindings yes.

**Comment by cpraveen** [comment]
Is there a way to tell spack to use clingo from homebrew.

**Comment by alalazo** [comment]
You just need to use a Python interpreter which can successfully:
```python
import clingo
```
to run Spack. If that is the case bootstrapping won't happen, since `clingo` is already functional.

**Comment by alalazo** [comment]
Apologies if I can't help more than that, but I have no access to an M1.

**Comment by cpraveen** [comment]
Thank you so much, your message helped me to get it working like this. I use python from conda anyway and installing clingo using conda works with spack, without need to bootstrap. 

Homebrew had clingo but not the python bindings I suppose.

**Comment by cpraveen** [comment]
Related to https://github.com/spack/spack/issues/30021
