### ISSUE TITLE
Help needed: attribute error in call to `self._enable = spack.config.get('config:locks', not is_windows)`

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#30078]
### Summary

If one of the spack developers has an idea please let me know.

I am using a custom script that I run after `spack module lmod refresh` to create a bunch of meta modules for easier handling in our environment. The script goes like this:
```
...
# Find currently active spack environment, activate here
logging.info("Configuring active spack environment ...")
env_dir=os.getenv('SPACK_ENV')
if not env_dir:
    raise Exception("No active spack environment")
env = spack.environment.Environment(env_dir)
spack.environment.environment.activate(env)
logging.info("  ... environment directory: {}".format(env_dir))

# Parse spack main config from environment
logging.info("Parsing spack environment main config ...")
main_config = spack.config.get('config')
install_dir = substitute_config_vars(main_config['install_tree']['root'])
...
```
I have been using this successfully on almost 20 systems (HPCs, Linux, macOS, AWS, ...), but on two macOS notebooks of my team the line `env = spack.environment.Environment(env_dir)` produces the following error:
```
INFO:root:Configuring active spack environment ...
Traceback (most recent call last):
  File "/Users/SOMEUSERNAME/projects/spack-stack/./meta_modules/setup_meta_modules.py", line 192, in <module>
    env = spack.environment.Environment(env_dir)
  File "/Users/SOMEUSERNAME/projects/spack-stack/spack/lib/spack/spack/environment/environment.py", line 622, in __init__
    self.txlock = lk.Lock(self._transaction_lock_path)
  File "/Users/SOMEUSERNAME/projects/spack-stack/spack/lib/spack/spack/util/lock.py", line 31, in __init__
    self._enable = spack.config.get('config:locks', not is_windows)
  File "/Users/SOMEUSERNAME/projects/spack-stack/spack/lib/spack/spack/config.py", line 926, in get
    return config.get(path, default, scope)
  File "/Users/SOMEUSERNAME/projects/spack-stack/spack/lib/spack/llnl/util/lang.py", line 810, in __getattr__
    return getattr(self.instance, name)
  File "/Users/SOMEUSERNAME/projects/spack-stack/spack/lib/spack/llnl/util/lang.py", line 809, in __getattr__
    raise AttributeError()
AttributeError
```
Any clues? Or better suggestions for my script? I need to know a number of things about the active environment, e.g. which compilers, which MPI provider, which type of modules (`lmod` vs `tcl`), ...

### Rationale

I understand that this is a help request that goes beyond the support that you usually provide. Feel free to close the issue if needed.

### Description

I hope to get past this point and complete my meta modules generator on the two problematic systems.

### Additional information

```
> spack --version
0.18.0.dev0 (89f9207aa9a778c60ef6a86f955fd9533d43f43d)
> spack debug report
* **Spack:** 0.18.0.dev0 (89f9207aa9a778c60ef6a86f955fd9533d43f43d)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
We found a way around this, closing
