### ISSUE TITLE
spack mirror create with relative paths doesn't work, an error message with valid url formats would be nice

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#30132]
### Steps to reproduce

```console
spack mirror create -d . zlib
```

### Error message

```console
spack --debug --stacktrace mirror create -d . zlib      
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-18-09:38:14.617687] Imported mirror from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-18-09:38:14.621958] Imported mirror from built-in commands
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.625545] Reading config file /home/stam/projects/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.652218] Reading config file /home/stam/projects/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.683356] Reading config file /home/stam/projects/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:377 ==> [2022-04-18-09:38:14.701888] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:381 ==> [2022-04-18-09:38:14.702246] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.703087] Reading config file /home/stam/projects/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:377 ==> [2022-04-18-09:38:14.726669] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:381 ==> [2022-04-18-09:38:14.726940] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:585 ==> [2022-04-18-09:38:14.727208] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:601 ==> [2022-04-18-09:38:14.727849] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/stam/projects/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:602 ==> [2022-04-18-09:38:14.728052] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/stam/projects/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:601 ==> [2022-04-18-09:38:14.728244] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/stam/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:602 ==> [2022-04-18-09:38:14.728406] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/stam/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.729153] Reading config file /home/stam/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:741 ==> [2022-04-18-09:38:14.767527] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:484 ==> [2022-04-18-09:38:14.767766] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.768305] Reading config file /home/stam/projects/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:14.975019] Reading config file /home/stam/projects/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:89 ==> [2022-04-18-09:38:15.051782] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /dzhvhynye4z7oalowdcy5zt25lej3m2n" provides the "clingo" Python module
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:15.052362] Reading config file /home/stam/projects/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:15.054448] Reading config file /home/stam/projects/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:15.094473] Reading config file /home/stam/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:15.109611] Reading config file /home/stam/projects/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/solver/asp.py:2006 ==> [2022-04-18-09:38:15.243075] build(zlib)
lib/spack/spack/spec.py:2795 ==> [2022-04-18-09:38:15.243927] Ordered hashes [zlib]: zlib/21/0d38234384870bfd34dfcb738a9083952656f0c766a0f5990b1893076b084b76
lib/spack/spack/config.py:1016 ==> [2022-04-18-09:38:15.350559] Reading config file /home/stam/projects/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/stam/projects/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/home/stam/projects/spack/lib/spack/spack/main.py", line 915, in main
    return _main(argv)
  File "/home/stam/projects/spack/lib/spack/spack/main.py", line 870, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/stam/projects/spack/lib/spack/spack/main.py", line 898, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/stam/projects/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/home/stam/projects/spack/lib/spack/spack/cmd/mirror.py", line 380, in mirror
    action[args.mirror_command](args)
  File "/home/stam/projects/spack/lib/spack/spack/cmd/mirror.py", line 330, in mirror_create
    directory = url_util.format(mirror.push_url)
  File "/home/stam/projects/spack/lib/spack/spack/util/url.py", line 123, in format
    parsed_url = parse(parsed_url)
  File "/home/stam/projects/spack/lib/spack/spack/util/url.py", line 79, in parse
    require_url_format(url)
  File "/home/stam/projects/spack/lib/spack/spack/util/url.py", line 348, in require_url_format
    raise ValueError('Invalid url format from url: %s' % url)
ValueError: Invalid url format from url: .
```

### Information on your system

spack debug report
* **Spack:** 0.18.0.dev0 (3835ac0c41ce57dda16de98c40b69dac5d26d34a)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mabraham** [comment]
In Spack 0.18.0, `spack mirror create --directory some-local-dir zlib` does nothing for a long time and then writes the cryptic

```
==> Error: [Errno 2] No such file or directory: '/nethome/mabraham/.spack/cache/indices/18933a7089_5d465a2418.json'
```

I prefer that `spack mirror create --directory` should accept a file path like its name suggests, and optionally work when passed a file URL like "file://some-local-dir" (for backward compatibility)

Otherwise, it may be better that `spack mirror create --directory` should be renamed `spack mirror create --url` if it is important that the user provide a URL.

Or at least the documentation and any examples for `spack mirror create --directory` should hint that a file URL is needed.

**Comment by alalazo** [comment]
This is fixed on:

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-05-03 16-09-07](https://user-images.githubusercontent.com/4199709/235940778-2fa74c3c-2938-4569-9689-620afe45fa92.png)
