### ISSUE TITLE
intel and intelmpi

### ISSUE THREAD

**Issue by cnelson3** [LLNL/spack#3019]
Is anyone else out there having issues getting Spack to play nice with intel and intelmpi?

My `packages.yaml` file is as follows:
```yaml
packages:
  intel-parallel-studio:
    modules:
      intel-parallel-studio.2017@cluster%intel: intel/17.0
    buildable: False
  all:
    compiler: [intel, gcc, pgi]
    providers:
      mpi: [intel-parallel-studio, openmpi, mpich]
      blas: [intel-parallel-studio+mkl, openblas]
      lapack: [intel-parallel-studio+mkl, openblas]
      pil: [py-lillow]
```
when I run the spack spec command on intel-parallel-studio, I get the following:
```bash
ggg:~>spack -d spec intel-parallel-studio
input spec
--------------------------------
intel-parallel-studio+mpi
 
Normalized
--------------------------------
intel-parallel-studio+mpi
 
Concretized
--------------------------------
==> Reading config file /ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/etc/spack/defaults/packages.yaml
==> READ LOCK: /local/cjn/.spack/cache/providers/.builtin-index.yaml.lock[0:0]
[Acquiring]
==> READ LOCK: /local/cjn/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> '/awe/Modules/bin/modulecmd' 'python' 'show' 'intel/17.0'
==> Error: the spec 'intel-parallel-studio' is configured as not buildable, and no matching external installs were found
Traceback (most recent call last):
  File "/prod/acs/spack/spack-dev-20170203/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/lib/spack/spack/cmd/spec.py", line 87, in spec
    spec.concretize()
  File "/ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/lib/spack/spack/spec.py", line 1525, in concretize
    self._expand_virtual_packages(),
  File "/ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/lib/spack/spack/spec.py", line 1442, in _expand_virtual_packages
    spec)
  File "/ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/lib/spack/spack/concretize.py", line 121, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_external(spec)
  File "/ROWAN/group/prod/LINUX_WORKSTATION/acs/spack/spack-dev-20170203/lib/spack/spack/concretize.py", line 90, in _valid_virtuals_and_externals
    raise NoBuildError(spec)
spack.concretize.NoBuildError: The spec 'intel-parallel-studio' is configured as not buildable, and no matching external installs were found
ggg:~>
```
On our systems, the Intel compiler suite (compilers, mkl, & mpi) are installed and maintained by the sys admins, who provide modules for us, _e.g_:
```bash
ggg:~>module avail intel
 
----------------------------------------- Compilers
-----------------------------------------
intel/11.1          intel/13.1          intel/15.0          intel/17.0
intel/13.0.1        intel/14.0          intel/16.0(default)
ggg:~>
```
Any help or advice would be greatly appreciated.

**Comment by pramodk** [comment]
In `packages.yaml` you specified : 

```
    modules:
      intel-parallel-studio.2017@cluster%intel: intel/17.0
```
The syntax is `package_name@version%compiler@version: module_name`. So I think you should use something like : 

```
    modules:
      intel-parallel-studio@cluster.2017.0%intel@17.0.0: intel/17.0
``` 
(check your `compilers.yaml` for compiler spec / version.

For example, my `mvapich2` external package config looks like : 

```
    mvapich2:
        modules:
            mvapich2@2.0.1%gcc@4.9.0: mvapich2/2.0.1-nocuda
```
