### ISSUE TITLE
spack mirror create zlib or whatever package fails with Error: Invalid url format from url: $spack/var/spack/cache

### ISSUE THREAD

**Issue by cessenat** [LLNL/spack#30320]
### Steps to reproduce

That's already since a while that spack mirror create fails
```
$ spack mirror create zlib
==> Error: Invalid url format from url: $spack/var/spack/cache
```

When I read Bug report https://github.com/spack/spack/issues/30132
I got the idea to enforce a mirror path with -d to my actual "$spack/var/spack/cache" as
```
$ spack mirror create -d /home2/cessenat/testspack/spack/var/spack/cache zlib
==> Adding package zlib@1.2.12 to mirror
==> Fetching https://mirror.spack.io/_source-cache/archive/91/91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9.tar.gz
==> Successfully updated mirror in file:///home2/cessenat/testspack/spack/var/spack/cache
  Archive stats:
    0    already present
    1    added
    0    failed to fetch.

```

### Error message

```
$ spack --debug --stacktrace mirror create zlib
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-27-09:22:43.609569] Imported mirror from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-27-09:22:43.612496] Imported mirror from built-in commands
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.613896] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.627193] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.654176] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:376 ==> [2022-04-27-09:22:43.665924] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:380 ==> [2022-04-27-09:22:43.666042] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.666372] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:376 ==> [2022-04-27-09:22:43.673020] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:380 ==> [2022-04-27-09:22:43.673144] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:585 ==> [2022-04-27-09:22:43.673261] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:601 ==> [2022-04-27-09:22:43.673555] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home2/cessenat/testspack/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:602 ==> [2022-04-27-09:22:43.673655] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home2/cessenat/testspack/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:601 ==> [2022-04-27-09:22:43.673754] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/cessenat/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:602 ==> [2022-04-27-09:22:43.673848] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/cessenat/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.674183] Reading config file /home/cessenat/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:741 ==> [2022-04-27-09:22:43.724730] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:484 ==> [2022-04-27-09:22:43.724834] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.725040] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.815473] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:89 ==> [2022-04-27-09:22:43.854453] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /shqedxgvjnhiwdcdrvjhbd73jaevv7wt" provides the "clingo" Python module
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.854724] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.857348] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.883269] Reading config file /home/cessenat/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:43.905537] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/solver/asp.py:2028 ==> [2022-04-27-09:22:44.006618] build(zlib)
lib/spack/spack/spec.py:2825 ==> [2022-04-27-09:22:44.006953] Ordered hashes [zlib]: zlib/21/0d38234384870bfd34dfcb738a9083952656f0c766a0f5990b1893076b084b76
lib/spack/spack/config.py:1016 ==> [2022-04-27-09:22:44.008223] Reading config file /home2/cessenat/testspack/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home2/cessenat/testspack/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/home2/cessenat/testspack/spack/lib/spack/spack/main.py", line 910, in main
    return _main(argv)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/main.py", line 865, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/main.py", line 893, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/cmd/mirror.py", line 380, in mirror
    action[args.mirror_command](args)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/cmd/mirror.py", line 330, in mirror_create
    directory = url_util.format(mirror.push_url)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/util/url.py", line 123, in format
    parsed_url = parse(parsed_url)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/util/url.py", line 79, in parse
    require_url_format(url)
  File "/home2/cessenat/testspack/spack/lib/spack/spack/util/url.py", line 348, in require_url_format
    raise ValueError('Invalid url format from url: %s' % url)
ValueError: Invalid url format from url: $spack/var/spack/cache

```

### Information on your system

$ spack debug report
* **Spack:** 0.18.0.dev0 (d5e1fa5771c9cb1a2b85ab129be182f7081ae7cb)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

I have removed my ~/.spack for the test.
The error is not very new, I would say something like since 3 months.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This is fixed in 

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-05-03 16-10-17](https://user-images.githubusercontent.com/4199709/235941248-227e07dd-b891-4111-a916-8e0421dc24c8.png)
