### ISSUE TITLE
py-matplotlib use leads to Illeagal instruction failure

### ISSUE THREAD

**Issue by healther** [LLNL/spack#3038]
Trying to install py-matplotlib via spack for python 2.7.13 with ucs4 (don't know if the latter will be important, but it lead to some headaches already)

The following scenario leads to the failure:
```
spack install py-matplotlib@2.0.0 +animation +ipython +latex +qt ^python+ucs4
```
after fixing the texlive md5 (is there a way to say -n only for texlive?) the installation goes through but now doing the following:
```
spack load -r py-matplotlib@2.0.0
ipython
import Python 2.7.13 (default, Feb  1 2017, 17:14:18) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.use('Agg')

In [3]: import matplotlib.pyplot as plt

In [4]: plt.figure()
Illegal instruction
```

After some googleing I found the following:
```
gdb --args python -c 'import matplotlib.pyplot as plt; plt.figure()'
Traceback (most recent call last):
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/lib/python2.7/site-packages/site.py", line 34, in __boot
    imp.load_module('site', stream, path, descr)
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

however I don't know what this is trying to tell me or where I would start to fix this.

Can anyone reproduce this issue?

**Comment by adamjstewart** [comment]
@lee218llnl Didn't you do some work on `sysconfigdata` recently? Any ideas?

**Comment by healther** [comment]
Further comments (maybe helpful maybe not):

With a checkout from 2016-12-16 of spack matplotlib works with python2.7.12
With the checkout from 2017-01-26 mpl neither works with python2.7.12 nor with python2.7.13, it also doesn't matter whether it's mpl@2.0.0 or mpl@1.5.3

That's all I had time for today, I'm away for the rest of the week and don't know if I can post updates, but if there is any additional information you need, please ask. I'll try to accommodate you asap

**Comment by lee218llnl** [comment]
@adamjstewart The work I did on sysconfigdata was due to it being renamed in Python 3.6.0, so I don't think this is related.

@healther I see that it is loading system packages from /usr/lib/python2.7/. Are you running /usr/bin/python or a Python install by spack in opt/spack/...?

**Comment by healther** [comment]
Thanks for the catch. I should have seen this...

Although I can't explain why it searches in ```/usr/lib/python2.7/``` at all. 

My path looks like:
```
tr ':' '\n' <<< "$PATH"
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/texlive-live-rjrnwhfvsavyqndzc7loydzdc5m3naxx/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/qhull-2015.2-yokt4yfoeju3ljnedpshmprruwdu5u52/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pyside-1.2.2-f6ii3hnkxzrrr3dkuna4hejl6bm6klev/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/qt-4.8.6-nqttznyhtgrmy7kfn5b7l77ymw7ll326/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/lcms-2.6-sufrkm7utkxxqffj6eqwo656mhoowpp2/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-sphinx-1.4.5-wtmu27hc5ewnw7gnm44gc4q46gpicyr7/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-docutils-0.13.1-hjppm2imtvos4l6qg2tcgjfvmznjbwmv/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-babel-2.3.4-dozzulguugy5t7xgnmw6u37ck4wffvo5/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libxslt-1.1.29-mp2phzuio2o4e6rg6ijeco6m35y6p6nq/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libgcrypt-1.6.2-fza4n7cpipxedtu4wfa2lkyb3fxtyury/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libgpg-error-1.21-ovftrw46vy7t3qfpmc2x4diefnbs74ps/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pillow-3.2.0-zmb2ioxlz2zqehbdiylfbb5mnkdltvup/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-numpy-1.11.2-rqe5qmiobt6uyrics22xrecpqwfljles/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/openblas-0.2.19-5ztk7dagxgubty2gc2rm7m7i3rheyjpp/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nose-1.3.7-lan3iin56vqye22x5eqkxtjpcqggzr5l/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pbr-1.8.1-gbtmhfmn5wuoddjbhhmhfeuyxm5giow3/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-ipython-5.1.0-k5qwto72jxlzlm4vlie3mtvjhzcogpie/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-setuptools-25.2.0-ojtjt3lwkqioyrkd4rav2bocb4ynet23/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pygments-2.1.3-csgpgkt47nzr5vsuo5nwtabn7zg3clyc/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/python-2.7.13-74xbvap5l3stqewqf5pect4phr52lrx4/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/sqlite-3.8.5-wc5tt2d2nxt7l5c2v4og25d54tir2wye/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/readline-6.3-mp5masuh2gryjbetoi3ikqhspzhwvbek/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/openssl-1.0.2j-sv2tytuixjynk4b2dyihmqew6p5ghy3h/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/image-magick-7.0.2-7-766v7ntbwsc4w4xdpavhhnnk56cyntx4/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/pango-1.40.3-qb45drzrsimocjdp5qghcwh4awew2yw3/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/harfbuzz-0.9.37-z7kstfb6dnj5rgwmkv6k3fcn3xbrrykg/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/icu4c-57.1-vbow7yq3jgs64cygc4va5dyswgegzaam/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/cairo-1.14.8-5h6xf7ovzjbsqhtbkxogekbv3bxfr5ll/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/glib-2.49.7-wrmm7vsifqkpad64dxklew65hz4rmw5a/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/pcre-8.39-sy2znjqopdb33eotutqfew5kvr5pkyrd/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/gettext-0.19.8.1-56ehjgm4wpsa4uvn25iufde6oi5ooief/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/tar-1.29-gyinfosokgy2fk6xbj32wh5joqmprzjn/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/ncurses-6.0-d333i77wy7zfhcplvmwawfzwsrlg3hh5/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/fontconfig-2.11.1-5y7mbs77feg47hbv5wgy5mimxvx5w4ua/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libxml2-2.9.4-4bsejknou34k6ttwosbzavqluk5pk4rp/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/ghostscript-9.18-o3tf6evprxjm47lyandq2oqmr6icl3la/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libtiff-4.0.6-pzscsvslx6tenykbrdi3thbd7kgvfqs6/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/xz-5.2.3-vmqlzykhpuho2bcd63suf4nynvlsrodr/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/jpeg-9b-7bestv3xfep2f7jnzkiykp3xbqshw77j/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/freetype-2.7-3cfe3ji55muqofc4b743kjo2o5qwiwzu/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/libpng-1.6.27-5z2jdo3uqzlbggprraifpijfskvp5nqr/bin
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/bzip2-1.0.6-kuhxl2pkyao56s66shznqezf2wr6y6ha/bin
/wang/environment/software/jessie/spack/2017-01-26/bin
/wang/environment/software/jessie/spack/current/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/games
/usr/games
```

and my PYTHONPATH like:
```
tr ':' '\n' <<< "$PYTHONPATH"
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pyside-1.2.2-f6ii3hnkxzrrr3dkuna4hejl6bm6klev/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-sphinx-1.4.5-wtmu27hc5ewnw7gnm44gc4q46gpicyr7/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-sphinx-rtd-theme-0.1.10a0-broyr4tao46zunraldgtj7pb4sabo4sq/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-snowballstemmer-1.2.1-ogoi6xioigey6i4ii7amjoraom24clop/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-jinja2-2.8-etelwsrptn3oavsyj7a7qqsdvkxqcmbe/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-markupsafe-0.23-7eyu3ye7anaicprbnoefesmrxpuvljkh/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-imagesize-0.7.1-ldjauedaoherahnbbwxvpiggxkzuhyx2/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-docutils-0.13.1-hjppm2imtvos4l6qg2tcgjfvmznjbwmv/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-babel-2.3.4-dozzulguugy5t7xgnmw6u37ck4wffvo5/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pytz-2016.6.1-r6cl47qs2rnlwcreqfsjiptqxe3qtf4e/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-alabaster-0.7.9-u3ziwjalxkufrwfwwaiyn7h6evylaeh7/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pyparsing-2.0.3-ywhlw54wrbawzrgye6mm2kcotrkjqb7y/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pillow-3.2.0-zmb2ioxlz2zqehbdiylfbb5mnkdltvup/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-numpy-1.11.2-rqe5qmiobt6uyrics22xrecpqwfljles/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nose-1.3.7-lan3iin56vqye22x5eqkxtjpcqggzr5l/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-mock-2.0.0-sufw452i2nsu433laya42ngyyhx4pfdw/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pbr-1.8.1-gbtmhfmn5wuoddjbhhmhfeuyxm5giow3/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-ipython-5.1.0-k5qwto72jxlzlm4vlie3mtvjhzcogpie/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-traitlets-4.3.1-xbtoxm6pbryltu45kwul3vhjuitvodh4/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-ipython-genutils-0.1.0-4awvvettcfhsraj7gsllzwplaooh3vic/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-enum34-1.1.6-lmxqisxyjsu63u4ibty36smkccvw36ch/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-simplegeneric-0.8.1-gr7jtd5i7votr7ng34acd44saaoawdmn/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-setuptools-25.2.0-ojtjt3lwkqioyrkd4rav2bocb4ynet23/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-prompt_toolkit-1.0.7-xnalyaxbxaq3mkidrqqn25qcc3j2powu/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-wcwidth-0.1.7-2obdxh7gl7eanpd6luwnbeffk6xrfqtg/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pygments-2.1.3-csgpgkt47nzr5vsuo5nwtabn7zg3clyc/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pickleshare-0.7.4-p34z5so3rrnkzsashhdyng42kc3hql5j/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pexpect-4.2.1-wfqvjse335e5x2sxtmbyjuvytegtt333/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-ptyprocess-0.5.1-dpz4dgvakhguibm67xykrpw5fbmzumud/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-pathlib2-2.1.0-amuxhuljhir7ywdvg3hj4z4r5jgdshai/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-decorator-4.0.9-w6drigggdjixd5ita4vi5vst4jfrwybt/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-backports-shutil-get-terminal-size-1.0.0-opanz2xl2yx4bvmnlf5ts2gzvm45fjpj/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-dateutil-2.5.2-fhafqnrvuv5vt5gm4itqyicyteznygkl/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-cycler-0.10.0-mwwdphpydfm3v5o6nk37nrjxwj6sgksv/lib/python2.7/site-packages
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-six-1.10.0-4466llnjcp4obmvztc5a4udjkuoj2rla/lib/python2.7/site-packages
```

and
```
which python
/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/python-2.7.13-74xbvap5l3stqewqf5pect4phr52lrx4/bin/python
```

and 
```
gdb --args $(which python) -c 'import matplotlib.pyplot as plt; plt.figure()'
Traceback (most recent call last):
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-matplotlib-2.0.0-vqmkcvk7carv6uwdb55rvd2uyxlliedf/lib/python2.7/site-packages/site.py", line 34, in __boot
    imp.load_module('site', stream, path, descr)
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

As you can see I'm just pretty much copy/pasting and hoping someone can help me. I know it worked with ```spack``` from december, so I guess something in spack changed, but I have no idea what that could be and why a spacked python is looking at the system python's libraries...

**Comment by muffgaga** [comment]
Sorry for the noise, the issue is related to our inhomogeneous cluster.
The `spack install` was performed on `haswell` nodes, but the frontend machines are `ivybridge`; it seems that `matplotlib` (or some `matplotlib`-related package) uses `-march=native` or similar.
We just realized this and now try to rebuild using `{c,f,cxx}flags = -march=SomeThingOlder`).

**Comment by adamjstewart** [comment]
@muffgaga We have the same setup as you. With some compilers, you can actually specify multiple architectures. We use:
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags:   -axCORE-AVX2,AVX
      cxxflags: -axCORE-AVX2,AVX
      fflags:   -axCORE-AVX2,AVX
    modules: []
    operating_system: centos6
    paths:
      cc:  /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4/compilers_and_libraries_2017.1.132/linux/bin/intel64/icc
      cxx: /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc
      f77: /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4/compilers_and_libraries_2017.1.132/linux/bin/intel64/ifort
      fc:  /soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4/compilers_and_libraries_2017.1.132/linux/bin/intel64/ifort
    spec: intel@17.0.1
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags:   -tp=haswell,sandybridge
      cxxflags: -tp=haswell,sandybridge
      fflags:   -tp=haswell,sandybridge
    modules: []
    operating_system: centos6
    paths:
      cc:  /soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/pgi-16.5-pa5hji6khmosol3h7u65zhw6cy2dnekn/linux86-64/16.5/bin/pgcc
      cxx: /soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/pgi-16.5-pa5hji6khmosol3h7u65zhw6cy2dnekn/linux86-64/16.5/bin/pgc++
      f77: /soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/pgi-16.5-pa5hji6khmosol3h7u65zhw6cy2dnekn/linux86-64/16.5/bin/pgfortran
      fc:  /soft/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-4.4.7/pgi-16.5-pa5hji6khmosol3h7u65zhw6cy2dnekn/linux86-64/16.5/bin/pgfortran
    spec: pgi@16.5-0
    target: x86_64
```
Unfortunately I don't think GCC supports this (yet).
