### ISSUE TITLE
spack under wsl

### ISSUE THREAD

**Issue by x2v0** [LLNL/spack#30394]
### Steps to reproduce

Hi,
I'm trying to use spack  on wsl2 machine

$ spack --debug --stacktrace install cpuinfo

gives exception.
I found the same problem was reported in

[https://githubhot.com/repo/spack/spack/issues/29673](https://githubhot.com/repo/spack/spack/issues/29673)

**_Install any package on Windows e.g. spack install cpuinfo
Spack's tee functionality does not pipe the output to stdout, only the output file._**

Under WSL2 is not possible to redirect to stdout because under windows  "linux console" doesn't exist ( this is conhost.exe subprocess)

Regards. Valeriy 

### Error message

$ spack --debug --stacktrace install cpuinfo

lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-29-10:38:10.459501] Imported install from built-in commands
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:10.462050] Reading config file /home/xtovo/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:10.481499] Reading config file /home/xtovo/.spack/config.yaml
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-29-10:38:10.482219] Imported install from built-in commands
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:10.488630] Reading config file /home/xtovo/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:10.492848] Reading config file /home/xtovo/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:10.494749] Reading config file /home/xtovo/.spack/repos.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:11.971922] Reading config file /home/xtovo/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:11.983960] Reading config file /home/xtovo/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:12.014991] Reading config file /home/xtovo/.spack/packages.yaml
lib/spack/spack/solver/asp.py:2034 ==> [2022-04-29-10:38:21.141590] build(cpuinfo)
lib/spack/spack/solver/asp.py:2034 ==> [2022-04-29-10:38:21.141806] build(cmake)
lib/spack/spack/solver/asp.py:2034 ==> [2022-04-29-10:38:21.142023] build(ninja)
lib/spack/spack/solver/asp.py:2034 ==> [2022-04-29-10:38:21.142266] build(python)
lib/spack/spack/spec.py:2827 ==> [2022-04-29-10:38:21.146043] Ordered hashes [python]: python/13/c129e34472ee39b1083c38a49ad06a8573d8b3b208743a120ca4c0818cdf1801
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:21.146906] Reading config file /home/xtovo/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:377 ==> [2022-04-29-10:38:21.158544] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:381 ==> [2022-04-29-10:38:21.158774] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/installer.py:1493 ==> [2022-04-29-10:38:21.314254] Initializing the build queue from the build requests
lib/spack/spack/installer.py:1109 ==> [2022-04-29-10:38:21.314511] Initializing the build queue for cpuinfo
lib/spack/spack/installer.py:2376 ==> [2022-04-29-10:38:21.314949] Processing dependencies for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x: ('build', 'link', 'run')
lib/spack/spack/installer.py:2112 ==> [2022-04-29-10:38:21.315213] Pkg id cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26 has the following dependents:
lib/spack/spack/installer.py:2114 ==> [2022-04-29-10:38:21.315388] - cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.316411] Requeueing a build task for cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26 with status 'queued'
lib/spack/spack/installer.py:2112 ==> [2022-04-29-10:38:21.385748] Pkg id python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm has the following dependents:
lib/spack/spack/installer.py:2114 ==> [2022-04-29-10:38:21.385952] - ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.387009] Requeueing a build task for python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm with status 'queued'
lib/spack/spack/installer.py:2112 ==> [2022-04-29-10:38:21.426396] Pkg id ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp has the following dependents:
lib/spack/spack/installer.py:2114 ==> [2022-04-29-10:38:21.426617] - cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.427636] Requeueing a build task for ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp with status 'queued'
lib/spack/spack/database.py:481 ==> [2022-04-29-10:38:21.434761] Removing failure marking for cpuinfo
lib/spack/spack/installer.py:2112 ==> [2022-04-29-10:38:21.435170] Pkg id cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x has the following dependents:
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.436221] Requeueing a build task for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x with status 'queued'
lib/spack/spack/installer.py:1499 ==> [2022-04-29-10:38:21.436378] Ensure all dependencies know all dependents across specs
lib/spack/spack/installer.py:1573 ==> [2022-04-29-10:38:21.437773] Processing cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26: task=priority=0, status=dequeued, start=0, #dependencies=0
lib/spack/spack/installer.py:330 ==> [2022-04-29-10:38:21.437939] cmake@3.20.0 : externally installed in /home/xtovo/spack/opt/spack/linux-centos7-x86_64/gcc-11.2.1/cmake-3.20.0-ee5b33twzdwcyev3tljljq4y43lblnyv/bin
lib/spack/spack/installer.py:335 ==> [2022-04-29-10:38:21.438086] cmake@3.20.0 : already registered in DB
[+] /home/xtovo/spack/opt/spack/linux-centos7-x86_64/gcc-11.2.1/cmake-3.20.0-ee5b33twzdwcyev3tljljq4y43lblnyv/bin (external cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26)
lib/spack/spack/installer.py:1471 ==> [2022-04-29-10:38:21.438366] Flagging cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26 as installed
lib/spack/spack/installer.py:1479 ==> [2022-04-29-10:38:21.438541] Removing cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26 from cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x's uninstalled dependencies.
lib/spack/spack/installer.py:2219 ==> [2022-04-29-10:38:21.438725] cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x: Removed cmake-3.20.0-5v2eiyywoh6m6lulkg7fm4qwbgxxho26 from uninstalled deps list: {'ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp'}
lib/spack/spack/installer.py:1357 ==> [2022-04-29-10:38:21.438939] Removing build task for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x from list
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.439081] Requeueing a build task for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x with status 'queued'
lib/spack/spack/installer.py:1573 ==> [2022-04-29-10:38:21.439327] Processing python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm: task=priority=0, status=dequeued, start=0, #dependencies=0
lib/spack/spack/installer.py:330 ==> [2022-04-29-10:38:21.439495] python@3.6.8 : externally installed in /usr
lib/spack/spack/installer.py:335 ==> [2022-04-29-10:38:21.439719] python@3.6.8 : already registered in DB
[+] /usr (external python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm)
lib/spack/spack/installer.py:1471 ==> [2022-04-29-10:38:21.439972] Flagging python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm as installed
lib/spack/spack/installer.py:1479 ==> [2022-04-29-10:38:21.440156] Removing python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm from ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp's uninstalled dependencies.
lib/spack/spack/installer.py:2219 ==> [2022-04-29-10:38:21.440322] ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp: Removed python-3.6.8-irfqr3el4eyvbgxzfm4h5eirotgp3emm from uninstalled deps list: set()
lib/spack/spack/installer.py:1357 ==> [2022-04-29-10:38:21.440485] Removing build task for ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp from list
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.440675] Requeueing a build task for ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp with status 'queued'
lib/spack/spack/installer.py:1573 ==> [2022-04-29-10:38:21.440901] Processing ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp: task=priority=0, status=dequeued, start=1651217901.4402313, #dependencies=1
lib/spack/spack/installer.py:1054 ==> [2022-04-29-10:38:21.441526] Acquiring a write lock on ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp with timeout 1e-09
lib/spack/spack/installer.py:1081 ==> [2022-04-29-10:38:21.441854] ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp is now write locked
lib/spack/spack/stage.py:319 ==> [2022-04-29-10:38:21.443747] Creating stage lock spack-stage-ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp
lib/spack/spack/installer.py:1471 ==> [2022-04-29-10:38:21.444008] Flagging ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp as installed
lib/spack/spack/installer.py:1479 ==> [2022-04-29-10:38:21.444161] Removing ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp from cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x's uninstalled dependencies.
lib/spack/spack/installer.py:2219 ==> [2022-04-29-10:38:21.444333] cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x: Removed ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp from uninstalled deps list: set()
lib/spack/spack/installer.py:1357 ==> [2022-04-29-10:38:21.444486] Removing build task for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x from list
lib/spack/spack/installer.py:1314 ==> [2022-04-29-10:38:21.444696] Requeueing a build task for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x with status 'queued'
lib/spack/spack/installer.py:1071 ==> [2022-04-29-10:38:21.444953] Downgrading to a read lock on ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp with timeout 1e-09
lib/spack/spack/installer.py:1081 ==> [2022-04-29-10:38:21.445173] ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp is now read locked
[+] /home/xtovo/spack/opt/spack/linux-centos7-skylake/gcc-11.2.1/ninja-1.10.2-cmh64pgy3h3odbcpgyqwksdqiocf76zp
lib/spack/spack/installer.py:1573 ==> [2022-04-29-10:38:21.445473] Processing cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x: task=priority=0, status=dequeued, start=1651217901.4386327, #dependencies=2
lib/spack/spack/installer.py:1054 ==> [2022-04-29-10:38:21.445908] Acquiring a write lock on cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x with timeout 1e-09
lib/spack/spack/installer.py:1081 ==> [2022-04-29-10:38:21.446193] cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x is now write locked
lib/spack/spack/stage.py:319 ==> [2022-04-29-10:38:21.449048] Creating stage lock spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/stage.py:319 ==> [2022-04-29-10:38:21.449512] Creating stage lock resource-googletest-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/stage.py:319 ==> [2022-04-29-10:38:21.449872] Creating stage lock resource-googlebenchmark-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/installer.py:1214 ==> [2022-04-29-10:38:21.450657] Installing cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/installer.py:405 ==> [2022-04-29-10:38:21.450891] Searching for binary cache of cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:21.451661] Reading config file /home/xtovo/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1016 ==> [2022-04-29-10:38:21.453172] Reading config file /home/xtovo/.spack/mirrors.yaml
lib/spack/spack/binary_distribution.py:1637 ==> [2022-04-29-10:38:21.456457] Did not find linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json on file:///mirror/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json
  Download failed: <urlopen error [Errno 2] No such file or directory: '/mirror/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json'>
lib/spack/spack/binary_distribution.py:1639 ==> [2022-04-29-10:38:21.456679] Did not find linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json on file:///mirror/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.yaml
  Download failed: <urlopen error [Errno 2] No such file or directory: '/mirror/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.yaml'>
lib/spack/spack/binary_distribution.py:1637 ==> [2022-04-29-10:38:22.921077] Did not find linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json on https://mirror.spack.io/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json
  Download failed: HTTP Error 404: Not Found
lib/spack/spack/binary_distribution.py:1639 ==> [2022-04-29-10:38:22.921406] Did not find linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.json on https://mirror.spack.io/build_cache/linux-centos7-skylake-gcc-11.2.1-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x.spec.yaml
  Download failed: HTTP Error 404: Not Found
lib/spack/spack/installer.py:288 ==> [2022-04-29-10:38:22.921989] No binary for cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x found: installing from source
lib/spack/spack/installer.py:1388 ==> [2022-04-29-10:38:22.922307] Creating the installation directory /home/xtovo/spack/opt/spack/linux-centos7-skylake/gcc-11.2.1/cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x
lib/spack/spack/util/executable.py:197 ==> [2022-04-29-10:38:22.952066] '/usr/bin/git' '-C' '/home/xtovo/spack' 'rev-parse' 'HEAD'
lib/spack/spack/compilers/__init__.py:764 ==> [2022-04-29-10:38:23.097345] [TOOLCHAIN] MATCH Gcc
lib/spack/spack/build_environment.py:385 ==> [2022-04-29-10:38:23.100511] Adding compiler bin/ paths: /home/xtovo/spack/lib/spack/env /home/xtovo/spack/lib/spack/env/case-insensitive /home/xtovo/spack/lib/spack/env/gcc
lib/spack/spack/build_environment.py:805 ==> [2022-04-29-10:38:23.118578] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
lib/spack/spack/util/executable.py:197 ==> [2022-04-29-10:38:23.120192] '/opt/rh/devtoolset-11/root/usr/bin/g++' '-v' '/tmp/spack-implicit-link-infobp5joig2/main.c' '-o' '/tmp/spack-implicit-link-infobp5joig2/output'
lib/spack/spack/compiler.py:108 ==> [2022-04-29-10:38:23.475287] parsing implicit link info
lib/spack/spack/compiler.py:123 ==> [2022-04-29-10:38:23.475820] linker line:  /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/collect2 -plugin /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/liblto_plugin.so -plugin-opt=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper -plugin-opt=-fresolution=/tmp/ccFs9hyg.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-infobp5joig2/output /lib/../lib64/crt1.o /lib/../lib64/crti.o /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/crtbegin.o -L/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11 -L/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../.. /tmp/ccHfvmPg.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/crtend.o /lib/../lib64/crtn.o
lib/spack/spack/compiler.py:139 ==> [2022-04-29-10:38:23.476102] linkdir: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11
lib/spack/spack/compiler.py:139 ==> [2022-04-29-10:38:23.476338] linkdir: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64
lib/spack/spack/compiler.py:139 ==> [2022-04-29-10:38:23.476563] linkdir: /lib/../lib64
lib/spack/spack/compiler.py:139 ==> [2022-04-29-10:38:23.476820] linkdir: /usr/lib/../lib64
lib/spack/spack/compiler.py:139 ==> [2022-04-29-10:38:23.477049] linkdir: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../..
lib/spack/spack/compiler.py:147 ==> [2022-04-29-10:38:23.477277] found raw link dirs: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11, /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/../../..
lib/spack/spack/compiler.py:157 ==> [2022-04-29-10:38:23.477592] found link dirs: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11, /opt/rh/devtoolset-11/root/usr/lib64, /lib64, /usr/lib64, /opt/rh/devtoolset-11/root/usr/lib
lib/spack/spack/fetch_strategy.py:661 ==> [2022-04-29-10:38:23.482553] Using cached archive: /home/xtovo/spack/var/spack/cache/_source-cache/git//Maratyszcza/cpuinfo.git/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz
lib/spack/spack/fetch_strategy.py:661 ==> [2022-04-29-10:38:23.486474] Using cached archive: /home/xtovo/spack/var/spack/cache/_source-cache/archive/94/94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91.zip
lib/spack/spack/fetch_strategy.py:661 ==> [2022-04-29-10:38:23.487687] Using cached archive: /home/xtovo/spack/var/spack/cache/_source-cache/archive/cc/cc463b28cb3701a35c0855fbcefb75b29068443f1952b64dd5f4f669272e95ea.zip
lib/spack/spack/stage.py:555 ==> [2022-04-29-10:38:23.487987] Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
lib/spack/spack/fetch_strategy.py:515 ==> [2022-04-29-10:38:23.491376] Staging archive: /tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz
lib/spack/spack/util/executable.py:197 ==> [2022-04-29-10:38:23.508197] '/mnt/c/WINDOWS/system32/tar.exe' '-oxf' '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'
tar.exe: Error opening archive: Failed to open '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'
lib/spack/spack/error.py:54 ==> [2022-04-29-10:38:23.573618] Error: ProcessError: Command exited with status 1:
    '/mnt/c/WINDOWS/system32/tar.exe' '-oxf' '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'
Traceback (most recent call last):
  File "/home/xtovo/spack/lib/spack/spack/build_environment.py", line 1050, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/xtovo/spack/lib/spack/spack/installer.py", line 2021, in build_process
    return installer.run()
  File "/home/xtovo/spack/lib/spack/spack/installer.py", line 1846, in run
    self.pkg.do_patch()
  File "/home/xtovo/spack/lib/spack/spack/package.py", line 1571, in do_patch
    self.do_stage()
  File "/home/xtovo/spack/lib/spack/spack/package.py", line 1557, in do_stage
    self.stage.expand_archive()
  File "/home/xtovo/spack/lib/spack/spack/util/pattern.py", line 19, in __call__
    for item in self.container]
  File "/home/xtovo/spack/lib/spack/spack/util/pattern.py", line 19, in <listcomp>
    for item in self.container]
  File "/home/xtovo/spack/lib/spack/spack/stage.py", line 609, in expand_archive
    self.fetcher.expand()
  File "/home/xtovo/spack/lib/spack/spack/fetch_strategy.py", line 83, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/xtovo/spack/lib/spack/spack/fetch_strategy.py", line 540, in expand
    decompress(self.archive_file)
  File "/home/xtovo/spack/lib/spack/spack/util/executable.py", line 239, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    '/mnt/c/WINDOWS/system32/tar.exe' '-oxf' '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'
lib/spack/spack/installer.py:1423 ==> [2022-04-29-10:38:23.574043] Flagging cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x as failed: ProcessError: Command exited with status 1:
    '/mnt/c/WINDOWS/system32/tar.exe' '-oxf' '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'
lib/spack/spack/main.py:913 ==> [2022-04-29-10:38:23.576616] ChildError: ProcessError: Command exited with status 1:
    '/mnt/c/WINDOWS/system32/tar.exe' '-oxf' '/tmp/xtovo/spack-stage/spack-stage-cpuinfo-2020-12-17-qukf6z46mntkjigwolqoje5xieukei7x/5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz'

### Information on your system

$ uname -a
Linux x2v0 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ spack debug report
* **Spack:** 0.18.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by x2v0** [comment]
the exception is raised in build_enviroment.py 
def start_build_process(pkg, function, kwargs):

_**# Forward sys.stdin when appropriate, to allow toggling verbosity
        if sys.platform != "win32" and sys.stdin.isatty() and hasattr(sys.stdin,
                                                                      'fileno')**_

**Comment by x2v0** [comment]
Possible solution is to use "uname -a" to detect WSL2
and then do not redirect stdin

**Comment by haampie** [comment]
aren't you running into an issue where tar.exe is used instead of linux tar?

**Comment by x2v0** [comment]
Hi,
Not, I got exception 
but for testing I added to 

build_enviroment.py
def start_build_process(pkg, function, kwargs):


 ***sys.platform = "win32"***

        _# Forward sys.stdin when appropriate, to allow toggling verbosity
        if sys.platform != "win32" and sys.stdin.isatty() and hasattr(sys.stdin,
                                                                      'fileno'):_

and get the problem that you described with tar.exe 
Yes, tar.exe doesn't work

 I suggest to detect WSL2 to use **"uname -a"**
and apply "win32 workaround"  and then to "return to processing in linux style"

**Comment by x2v0** [comment]
An article describing difference between linux and windows consoles
https://devblogs.microsoft.com/commandline/windows-command-line-inside-the-windows-console/

**Comment by x2v0** [comment]
Hi,
did anybody use spack under windows11/WSL2/linux[CentOS7, ubuntu.xxx, etc]?
... or I'm the the first one?

Regards. Valeriy

**Comment by alalazo** [comment]
@johnwparent Do you know if Spack is working correctly under `wsl` now?

**Comment by johnwparent** [comment]
> @johnwparent Do you know if Spack is working correctly under `wsl` now?

@alalazo As far as I understood it, it always has functioned under WSL, this user just encountered the known issue of Spack's interaction with the Windows console (presumably they are running WSL from a Windows terminal instance, otherwise this would not occur).
From what I can tell from the comments, their actual error was self induced? 

FWIW WSL is a full linux VM, Spack works the same way it does on all other linux system with the exception of stdin/out and any mounted volumes, which would be Windows hosted. The conout issue is way back in my backlog of things to do, so it will likely get fixed some time this summer.
