### ISSUE TITLE
Environment expects invalid deplist to be a list of strings, gets a list of Spec objects.

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#30499]
### Steps to reproduce

I don't have a reproducer for you, but it's pretty clear from the exception and code what has gone wrong.  This happens when using a Spack 'Stack' matrix that ends up pairing invalid dependencies with packages.

### Error message

```
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/environment/environment.py", line 2110, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/spec.py", line 2947, in concretized
    clone.concretize(tests=tests)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/spec.py", line 2909, in concretize
    self._new_concretize(tests)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/spec.py", line 2882, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/solver/asp.py", line 2171, in solve
    setup_only=setup_only,
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/solver/asp.py", line 568, in solve
    setup.setup(self, specs)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/solver/asp.py", line 1755, in setup
    raise spack.spec.InvalidDependencyError(spec.name, missing_deps)
spack.spec.InvalidDependencyError: Package paraview does not depend on cubelib%gcc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/environment/environment.py", line 2132, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/environment/environment.py", line 2112, in _concretize_from_constraints
    invalid_deps_string = ['^' + d for d in e.invalid_deps]
  File "/tmp/pflarr/new_spack/linux-rhel7-x86_64_v3-omnipath-none/spack/lib/spack/spack/environment/environment.py", line 2112, in <listcomp>
    invalid_deps_string = ['^' + d for d in e.invalid_deps]
TypeError: must be str, not Spec
```

### Information on your system

This is the lastest Spack develop branch.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment]
For additional context: This is only reproducible using the `clingo` concretizer, and when the invalid dependency is not a possible dependency of the root (i.e. cannot be a transitive dependency under any configuration of specs).
