### ISSUE TITLE
Error: name 'platform' not defined (from Go package)

### ISSUE THREAD

**Issue by benpm** [LLNL/spack#30509]
### Steps to reproduce

```
spack install go
```

### Error message

```
Traceback (most recent call last):  File "/projects/ngc/private/portage-deps/ci/wonton/spack/bin/spack", line 98, in <module>    sys.exit(spack.main.main())  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/main.py", line 915, in main    return _main(argv)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/main.py", line 870, in _main    return finish_parse_and_run(parser, cmd_name, env_format_error)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/main.py", line 898, in finish_parse_and_run    return _invoke_command(command, parser, args, unknown)
  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/cmd/install.py", line 395, in install
    specs = spack.cmd.parse_specs(args.spec, concretize=True, tests=tests)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/cmd/__init__.py", line 165, in parse_specs
    spec.concretize(tests=tests)  # implies normalize  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/spec.py", line 2909, in concretize    self._new_concretize(tests)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/spec.py", line 2882, in _new_concretize    result = solver.solve([self], tests=tests)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/solver/asp.py", line 2159, in solve    if s.virtual:  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/spec.py", line 1534, in virtual    return spack.repo.path.is_virtual(self.name, use_index=False)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/repo.py", line 990, in is_virtual    self.get_pkg_class(pkg_name).virtual)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/repo.py", line 953, in get_pkg_class    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)  File "/projects/ngc/private/portage-deps/ci/wonton/spack/lib/spack/spack/repo.py", line 1296, in get_pkg_class    module = importlib.import_module(fullname)  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                                                                            return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/projects/ngc/private/portage-deps/ci/wonton/spack/var/spack/repos/builtin/packages/go/package.py", line 35, in <module>                                                                                                                    
    """The golang compiler and build environment"""
  File "/projects/ngc/private/portage-deps/ci/wonton/spack/var/spack/repos/builtin/packages/go/package.py", line 144, in Go
    depends_on('gcc@10.4.0:10,11.3.0: languages=go', type='build')
NameError: name 'platform' is not defined
```

### Information on your system

```
* **Spack:** 0.18.0.dev0 (96cc908d69394b292732bfa55abbb50784d9efd8)
* **Python:** 3.9.5
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by benpm** [comment]
Can no longer reproduce, closing
