### ISSUE TITLE
module refresh appears to be broken

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3052]
```
==> Regenerating tcl module files
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/Users/davydden/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/Users/davydden/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/module.py", line 259, in module
    callbacks[args.subparser_name](module_type, specs, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/module.py", line 243, in refresh
    x.write(overwrite=True)
  File "/Users/davydden/spack/lib/spack/spack/modules.py", line 391, in write
    set_module_variables_for_package(package, package.module)
  File "/Users/davydden/spack/lib/spack/spack/build_environment.py", line 380, in set_module_variables_for_package
    m.std_cmake_args = spack.CMakePackage._std_args(pkg)
  File "/Users/davydden/spack/lib/spack/spack/build_systems/cmake.py", line 119, in _std_args
    rpaths = ':'.join(spack.build_environment.get_rpaths(pkg))
  File "/Users/davydden/spack/lib/spack/spack/build_environment.py", line 424, in get_rpaths
    rpaths.extend(d.prefix.lib for d in deps
  File "/Users/davydden/spack/lib/spack/spack/build_environment.py", line 425, in <genexpr>
    if os.path.isdir(d.prefix.lib))
  File "/Users/davydden/spack/lib/spack/spack/spec.py", line 1158, in prefix
    return Prefix(spack.store.layout.path_for_spec(self))
  File "/Users/davydden/spack/lib/spack/spack/directory_layout.py", line 124, in path_for_spec
    _check_concrete(spec)
  File "/Users/davydden/spack/lib/spack/spack/directory_layout.py", line 42, in _check_concrete
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!
```

**Comment by adamjstewart** [comment]
Duplicate of #2911.

**Comment by davydden** [comment]
Thanks, did not notice that one.
