### ISSUE TITLE
concretize: "conflicting option strings: -U, --fresh" error

### ISSUE THREAD

**Issue by benpm** [LLNL/spack#30567]
### Steps to reproduce

Any `spack concretize` command will cause this unexpected error, such as:
```bash
spack concretize --help
```

### Error message

```
lib/spack/spack/config.py:1016 ==> [2022-05-09-08:49:36.899545] Reading config file /projects/ngc/private/portage-deps/ci/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1016 ==> [2022-05-09-08:49:36.913538] Reading config file /projects/ngc/private/portage-deps/ci/ci-support/darwin_spack_config/config.yaml
lib/spack/spack/config.py:1016 ==> [2022-05-09-08:49:36.921159] Reading config file /vast/home/bmastripolito/ngc/tangram/dev/env_coverage/spack.yaml
lib/spack/spack/environment/environment.py:162 ==> [2022-05-09-08:49:36.924483] Using environment '/vast/home/bmastripolito/ngc/tangram/dev/env_coverage'
lib/spack/spack/cmd/__init__.py:123 ==> [2022-05-09-08:49:36.925982] Imported concretize from built-in commands
Traceback (most recent call last):
  File "/projects/ngc/private/portage-deps/ci/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/main.py", line 915, in main
    return _main(argv)
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/main.py", line 870, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    command = parser.add_command(cmd_name)
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/main.py", line 342, in add_command
    module.setup_parser(subparser)
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/cmd/concretize.py", line 31, in setup_parser
    spack.cmd.common.arguments.add_concretizer_args(subparser)
  File "/projects/ngc/private/portage-deps/ci/spack/lib/spack/spack/cmd/common/arguments.py", line 378, in add_concretizer_args
    subgroup.add_argument(
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/argparse.py", line 1434, in add_argument
    return self._add_action(action)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/argparse.py", line 1636, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/argparse.py", line 1448, in _add_action
    self._check_conflict(action)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/argparse.py", line 1585, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/argparse.py", line 1594, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -U/--fresh: conflicting option strings: -U, --fresh
```

### Information on your system

```
* **Spack:** 0.18.0.dev0 (479796c55930f0ce3d27ee1d62182250abe20288)
* **Python:** 3.9.5
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by benpm** [comment]
~~On first glance, the culprit seems to be multiple definitions of the `-U` option:~~
1. [lib/spack/spack/cmd/common/arguments.py:379](https://github.com/spack/spack/blob/a24bae1986c7090eabf7c80c9a690e3e652886e3/lib/spack/spack/cmd/common/arguments.py#L379)
2. [lib/spack/spack/cmd/style.py:170](https://github.com/spack/spack/blob/a24bae1986c7090eabf7c80c9a690e3e652886e3/lib/spack/spack/cmd/style.py#L170)

EDIT: Nevermind, the error still happens when the `'-U'` is removed from the first occurrence.

**Comment by alalazo** [comment]
I can't reproduce on:

* **Spack:** 0.18.0.dev0 (d08520cb15c059142d88af637e86de3b9855974d)
* **Python:** 3.10.2
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Comment by benpm** [comment]
Gonna go ahead and close this issue because I'm also having trouble reproducing on clean install... not sure what I broke, exactly.
