### ISSUE TITLE
Installation issue: clingo-bootstrap

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#30587]
### Steps to reproduce the issue

```console
$ spack -d spec zlib
...
```

### Error message

<details><summary>Error message</summary>

```
==> [2022-05-10-13:16:17.515330] Installing clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt
==> [2022-05-10-13:16:17.515357] Searching for binary cache of clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt
==> [2022-05-10-13:16:18.886607] Did not find darwin-monterey-aarch64-apple-clang-13.1.6-clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt.spec.json on https://mirror.spack.io/build_cache/darwin-monterey-aarch64-apple-clang-13.1.6-clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt.spec.json
  Download failed: HTTP Error 404: Not Found
==> [2022-05-10-13:16:18.886855] Did not find darwin-monterey-aarch64-apple-clang-13.1.6-clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt.spec.json on https://mirror.spack.io/build_cache/darwin-monterey-aarch64-apple-clang-13.1.6-clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt.spec.yaml
  Download failed: HTTP Error 404: Not Found
==> [2022-05-10-13:16:18.887753] No binary for clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt found: installing from source
==> [2022-05-10-13:16:18.888053] Creating the installation directory /Users/adrien/.spack/bootstrap/store/darwin-monterey-aarch64/apple-clang-13.1.6/clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt
==> [2022-05-10-13:16:18.900169] '/usr/bin/git' '-C' '/Users/adrien/Work/Repos/spack' 'rev-parse' 'HEAD'
==> [2022-05-10-13:16:19.471446] Error: IndexError: list index out of range

/Users/adrien/Work/Repos/spack/var/spack/repos/builtin/packages/python/package.py:1081, in headers:
       1078        else:
       1079            headers = find_headers(
       1080                'pyconfig', self.prefix.include, recursive=True)
  >>   1081            config_h = headers[0]
       1082
       1083        headers.directories = [os.path.dirname(config_h)]
       1084        return headers


Traceback (most recent call last):
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/build_environment.py", line 1058, in _setup_pkg_and_run
    kwargs['env_modifications'] = setup_package(
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/build_environment.py", line 801, in setup_package
    set_wrapper_variables(pkg, env_mods)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/build_environment.py", line 454, in set_wrapper_variables
    update_compiler_args_for_dep(dspec)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/build_environment.py", line 448, in update_compiler_args_for_dep
    _prepend_all(include_dirs, query.headers.directories)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/spec.py", line 1060, in __get__
    value = f()
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/spec.py", line 1049, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/Users/adrien/Work/Repos/spack/var/spack/repos/builtin/packages/python/package.py", line 1082, in headers
  File "/Users/adrien/Work/Repos/spack/lib/spack/llnl/util/filesystem.py", line 1446, in __getitem__
    return self.files[item]
IndexError: list index out of range
==> [2022-05-10-13:16:19.472643] Flagging clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt as failed: IndexError: list index out of range
==> [2022-05-10-13:16:19.478878] Creating stage lock spack-stage-clingo-bootstrap-spack-yiushdkdwx5vp6xlqw477xom7zulxlrt
==> [2022-05-10-13:16:19.479669] [BOOTSTRAP MODULE clingo] Unexpected error "Terminating after first install failure: IndexError: list index out of range"
==> [2022-05-10-13:16:19.484953] Reading config file /Users/adrien/Work/Repos/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/Users/adrien/Work/Repos/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/main.py", line 910, in main
    return _main(argv)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/main.py", line 865, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/main.py", line 893, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/cmd/spec.py", line 87, in spec
    specs = [(s, s.concretized()) for s in input_specs]
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/cmd/spec.py", line 87, in <listcomp>
    specs = [(s, s.concretized()) for s in input_specs]
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/spec.py", line 2947, in concretized
    clone.concretize(tests=tests)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/spec.py", line 2909, in concretize
    self._new_concretize(tests)
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/spec.py", line 2881, in _new_concretize
    solver = spack.solver.asp.Solver()
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/solver/asp.py", line 2128, in __init__
    self.driver = PyclingoDriver()
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/solver/asp.py", line 485, in __init__
    bootstrap_clingo()
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/solver/asp.py", line 466, in bootstrap_clingo
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/bootstrap.py", line 752, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(
  File "/Users/adrien/Work/Repos/spack/lib/spack/spack/bootstrap.py", line 519, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %apple-clang target=aarch64" due to the following failures:
    'spack-install' raised InstallError: Terminating after first install failure: IndexError: list index out of range
    Please run `spack -d spec zlib` for more verbose error messages
```
</details>

### Information on your system

* **Spack:** 0.18.0.dev0 (060e88387e7fd27c6e13dc1ca222e3c6b7d7f1fe)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

No such files to upload found.

@alalazo 

The issue relates to #28190, but I decided to install Xcode to have a trouble-free install of clingo.
I removed all installed specs in the bootstrap store. Install started from scratch again, with no external dependencies specified.

A first, non-reproducible error appeared when first trying to install perl. Re-trying passed. So not related to perl.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I just hit this same issue, this also relates to #30513. The "solution" in that PR was to install `file` so we could use pre-compiled binaries, but we don't have those for M1 yet. I think we need to fix external detection for Python's variants. I'll see what I can do.
