### ISSUE TITLE
Installation issue: intel-oneapi-mkl on macOS M1

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#30716]
### Steps to reproduce the issue

I'm trying to install intel-oneapi-mkl on macOS. I see that our Spack package does not yet have support for this, and I don't know how to determine the magic URLs used in the package, so I used the .dmg installer from the website. This seems to have installed correctly, and I added this installation to my list of external packages:
```yaml
packages:
  all:
    providers:
      blas: [intel-oneapi-mkl]
      lapack: [intel-oneapi-mkl]
      mkl: [intel-oneapi-mkl]
  intel-oneapi-mkl:
    buildable: False
    externals:
    - spec: intel-oneapi-mkl@2022.1.0
      prefix: /opt/intel/oneapi/
```
Numpy installs without crashing, but the actual installation can't be imported and any package that depends on it fails to install.

### Error message

```console
$ python
>>> import numpy
Traceback (most recent call last):
  File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/py-numpy-1.22.3-4fwhdjl5bhqnmtaqsag37ys2b3duzc7s/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/py-numpy-1.22.3-4fwhdjl5bhqnmtaqsag37ys2b3duzc7s/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/py-numpy-1.22.3-4fwhdjl5bhqnmtaqsag37ys2b3duzc7s/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/py-numpy-1.22.3-4fwhdjl5bhqnmtaqsag37ys2b3duzc7s/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_cblas_caxpy'
```

### Information on your system

* **Spack:** 0.18.0.dev0 (005a6e4b34d69189f6c137193c2702b882362128)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

@rscohn2 do you have any idea if the .dmg installers for intel-oneapi-mkl happen to work for the new Apple M1 system (aarch64)? Or do they only support x86_64 on macOS for the time being? Are there any other variants of MKL that support M1? Or should I just stick to OpenBLAS for now?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
I have limited experience on mac and no experience on m1. It sounds like you are trying to link in mkl (x86) into a process that is aarch64 and I would not expect that to work. I do expect mkl to work on m1 when everything in the process is x86. I don't know how to make spack do that.

Spack intel packages use the installers from this page: https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html
You can right click on the links to copy the URL.

I did not enable spack packages for mac because the intel installer must be run as root, and that did not fit in well with spack.

**Comment by adamjstewart** [comment]
I no longer use MKL...
