### ISSUE TITLE
Concretizing fails because `libllvm` can't be found, even when not needed.

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#30758]
### Steps to reproduce

```console
$ spack env create foo
$ spack env activate foo
$ spack add libtheora 
$ spack concretize -f
```

### Error message

```console
$ spack --debug --stacktrace concretize -f 
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.240693] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.259016] Reading config file /tmp/pflarr/spack/var/spack/environments/foo/spack.yaml
lib/spack/spack/environment/environment.py:162 ==> [2022-05-20-07:24:28.260512] Using environment 'foo'
lib/spack/spack/cmd/__init__.py:123 ==> [2022-05-20-07:24:28.261326] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-05-20-07:24:28.261837] Imported concretize from built-in commands
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.264409] Reading config file /tmp/pflarr/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/environment/environment.py:186 ==> [2022-05-20-07:24:28.273302] Deactivated environment 'foo'
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.277542] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:383 ==> [2022-05-20-07:24:28.291386] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-05-20-07:24:28.291583] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.292033] Reading config file /tmp/pflarr/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:383 ==> [2022-05-20-07:24:28.300927] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-05-20-07:24:28.301163] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:577 ==> [2022-05-20-07:24:28.301407] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:593 ==> [2022-05-20-07:24:28.301956] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/tmp/pflarr/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:594 ==> [2022-05-20-07:24:28.302144] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/tmp/pflarr/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:593 ==> [2022-05-20-07:24:28.302328] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/pflarr/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:594 ==> [2022-05-20-07:24:28.302505] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/pflarr/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.303091] Reading config file /home/pflarr/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:733 ==> [2022-05-20-07:24:28.322397] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:484 ==> [2022-05-20-07:24:28.322559] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.322880] Reading config file /tmp/pflarr/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.448124] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:90 ==> [2022-05-20-07:24:28.497638] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /vcipwnf57slgoo7busvvkzjkk7vydeb5" provides the "clingo" Python module
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.498474] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.514991] Reading config file /tmp/pflarr/spack/var/spack/environments/foo/spack.yaml
lib/spack/spack/environment/environment.py:162 ==> [2022-05-20-07:24:28.516517] Using environment 'foo'
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.516719] Reading config file /tmp/pflarr/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.547896] Reading config file /home/pflarr/.spack/linux/compilers.yaml
lib/spack/spack/environment/environment.py:1260 ==> [2022-05-20-07:24:28.552540] Starting concretization
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.559312] Reading config file /tmp/pflarr/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/environment/environment.py:186 ==> [2022-05-20-07:24:28.569863] Deactivated environment 'foo'
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.574699] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:383 ==> [2022-05-20-07:24:28.588332] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-05-20-07:24:28.588587] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:577 ==> [2022-05-20-07:24:28.588910] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.589457] Reading config file /tmp/pflarr/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap.py:593 ==> [2022-05-20-07:24:28.597664] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/tmp/pflarr/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:594 ==> [2022-05-20-07:24:28.597874] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/tmp/pflarr/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:593 ==> [2022-05-20-07:24:28.598061] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/pflarr/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:594 ==> [2022-05-20-07:24:28.598246] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/pflarr/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.598706] Reading config file /home/pflarr/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:733 ==> [2022-05-20-07:24:28.617614] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:484 ==> [2022-05-20-07:24:28.617879] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.618697] Reading config file /tmp/pflarr/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.634062] Reading config file /tmp/pflarr/spack/var/spack/environments/foo/spack.yaml
lib/spack/spack/environment/environment.py:162 ==> [2022-05-20-07:24:28.635919] Using environment 'foo'
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:28.636251] Reading config file /tmp/pflarr/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:29.889105] Reading config file /home/pflarr/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:29.893770] Reading config file /tmp/pflarr/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1017 ==> [2022-05-20-07:24:29.968057] Reading config file /home/pflarr/.spack/packages.yaml
Traceback (most recent call last):
  File "/tmp/pflarr/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/tmp/pflarr/spack/lib/spack/spack/main.py", line 910, in main
    return _main(argv)
  File "/tmp/pflarr/spack/lib/spack/spack/main.py", line 865, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/tmp/pflarr/spack/lib/spack/spack/main.py", line 893, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/tmp/pflarr/spack/lib/spack/spack/main.py", line 550, in _invoke_command
    return_val = command(parser, args)
  File "/tmp/pflarr/spack/lib/spack/spack/cmd/concretize.py", line 43, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/tmp/pflarr/spack/lib/spack/spack/environment/environment.py", line 1155, in concretize
    return self._concretize_separately(tests=tests)
  File "/tmp/pflarr/spack/lib/spack/spack/environment/environment.py", line 1264, in _concretize_separately
    debug=tty.is_debug()
  File "/tmp/pflarr/spack/lib/spack/spack/util/parallel.py", line 135, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "/tmp/pflarr/spack/lib/spack/spack/util/parallel.py", line 83, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=32319] Traceback (most recent call last):
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 1304, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spack.pkg.builtin.libllvm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pflarr/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/tmp/pflarr/spack/lib/spack/spack/environment/environment.py", line 2128, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/tmp/pflarr/spack/lib/spack/spack/environment/environment.py", line 2106, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/tmp/pflarr/spack/lib/spack/spack/spec.py", line 2997, in concretized
    clone.concretize(tests=tests)
  File "/tmp/pflarr/spack/lib/spack/spack/spec.py", line 2901, in concretize
    self._new_concretize(tests)
  File "/tmp/pflarr/spack/lib/spack/spack/spec.py", line 2875, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/tmp/pflarr/spack/lib/spack/spack/solver/asp.py", line 2200, in solve
    setup_only=setup_only,
  File "/tmp/pflarr/spack/lib/spack/spack/solver/asp.py", line 571, in solve
    setup.setup(self, specs)
  File "/tmp/pflarr/spack/lib/spack/spack/solver/asp.py", line 1792, in setup
    self.build_version_dict(possible, specs)
  File "/tmp/pflarr/spack/lib/spack/spack/solver/asp.py", line 1320, in build_version_dict
    pkg = spack.repo.get(pkg_name)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 1409, in get
    return path.get(spec)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 444, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 957, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 444, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 1129, in get
    package_class = self.get_pkg_class(spec.name)
  File "/tmp/pflarr/spack/lib/spack/spack/repo.py", line 1306, in get_pkg_class
    raise UnknownPackageError(pkg_name)
spack.repo.UnknownPackageError: Package 'libllvm' not found.
```

### Information on your system

* **Spack:** 0.18.0.dev0 (55f4950ed4bf3aa6cc40fe0d296f99cf2df17903)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Paul-Ferrell** [comment]
Nevermind. Deleting my ~/.spack/ directory fixed this.
