### ISSUE TITLE
Spack silently ignores unknown processor microarchitectures in environments

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#31052]
### Steps to reproduce

Spack doesn't provide a good error message when asking for unknown `target` (processor microarchitecture) on command line,
silently ignores `target` inside environment

```console
$ spack spec zlib
Input spec
--------------------------------
zlib

Concretized
--------------------------------
zlib@1.2.12%gcc@8.5.0+optimize+pic+shared patches=0d38234 arch=linux-almalinux8-skylake_avx512

$ spack spec zlib target=prescott
==> Error: No valid compiler version found for 'zlib'

$ spack env create foobar
$ cat var/spack/environments/foobar/spack.yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [zlib]
  view: true
  concretizer:
    unify: true
  packages:
    all:
      target: [prescott]
$ spack -e foobar concretize -f
==> Concretized zlib
 -   crlh3vy  zlib@1.2.12%gcc@8.5.0+optimize+pic+shared patches=0d38234 arch=linux-almalinux8-skylake_avx512
```

### Error message

```console
$ spack --debug --stacktrace spec zlib target=prescott
lib/spack/spack/cmd/__init__.py:123 ==> [2022-06-08-18:18:16.773558] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-06-08-18:18:16.774889] Imported spec from built-in commands
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.778053] Reading config file /root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.806675] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.824667] Reading config file /root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:383 ==> [2022-06-08-18:18:16.852769] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-06-08-18:18:16.853071] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.853970] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:383 ==> [2022-06-08-18:18:16.864246] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-06-08-18:18:16.864595] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:614 ==> [2022-06-08-18:18:16.864992] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:630 ==> [2022-06-08-18:18:16.865914] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/root/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:631 ==> [2022-06-08-18:18:16.866196] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/root/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:630 ==> [2022-06-08-18:18:16.866504] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:631 ==> [2022-06-08-18:18:16.866724] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.867669] Reading config file /root/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:770 ==> [2022-06-08-18:18:16.901942] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:523 ==> [2022-06-08-18:18:16.902234] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:16.902776] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:17.105851] Reading config file /root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:96 ==> [2022-06-08-18:18:17.201099] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /dzhvhynye4z7oalowdcy5zt25lej3m2n" provides the "clingo" Python module
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:17.201756] Reading config file /root/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:17.209667] Reading config file /root/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:17.217027] Reading config file /root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:17.245102] Reading config file /root/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:18.096286] Reading config file /root/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-08-18:18:18.105848] Reading config file /root/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/main.py:896 ==> [2022-06-08-18:18:18.212803] UnsatisfiableSpecError: No valid compiler version found for 'zlib'
lib/spack/spack/error.py:54 ==> [2022-06-08-18:18:18.213181] Error: No valid compiler version found for 'zlib'
Traceback (most recent call last):
  File "/root/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/root/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/root/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/root/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/root/spack/lib/spack/spack/cmd/spec.py", line 83, in spec
    specs = [(s, s.concretized()) for s in input_specs]
  File "/root/spack/lib/spack/spack/cmd/spec.py", line 83, in <listcomp>
    specs = [(s, s.concretized()) for s in input_specs]
  File "/root/spack/lib/spack/spack/spec.py", line 3013, in concretized
    clone.concretize(tests=tests)
  File "/root/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/root/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/root/spack/lib/spack/spack/solver/asp.py", line 2303, in solve
    setup_only=setup_only,
  File "/root/spack/lib/spack/spack/solver/asp.py", line 680, in solve
    answers = builder.build_specs(tuples)
  File "/root/spack/lib/spack/spack/solver/asp.py", line 2152, in build_specs
    action(*args)
  File "/root/spack/lib/spack/spack/solver/asp.py", line 1978, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: No valid compiler version found for 'zlib'
```

### Information on your system

* **Spack:** 0.19.0.dev0 (d6fabd1533e436cebc94a74fd6d6716f152419fb)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment]
@alalazo if I'm reading the `microarchitectures.json` file correctly, there is no way for spack to set flags for prescott: the inheritance chain is `prescott > pentium4 > pentium3 > pentium2 > i686 > x86`, and none of the processors in that chain have `compiler` section. But still quietly dropping `target` inside environment is not a good move.

**Comment by alalazo** [comment]
> But still quietly dropping target inside environment is not a good move.

Well, prescriptions in`packages.yaml` are preferences, not strict requirements (and always have been). You can say that your preferred target is `power9le` and still concretize on `icelake`. Spack will pick the best `x86_64` architecture for that, according to your configuration.

Concerning:
> spack.solver.asp.UnsatisfiableSpecError: No valid compiler version found for 'zlib'

do you actually have a compiler registered for the `x86` architecture?

**Comment by iarspider** [comment]
Ah, `prescott` is a 32-bit architecture. Stupid me... :)

**Comment by alalazo** [comment]
Marking as not-a-bug and closing
