### ISSUE TITLE
Failure to spec/install with multiple explicitly specified dependencies

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#31094]
### Steps to reproduce

I know this was broken at some point, but I thought fixed later. With the new "reuse" option it's less necessary thankfully, but the failure mode should definitely not be an assertion.

```console
$ spack spec -I py-breathe ^doxygen/wwgy2bu ^python/qqqezh5
==> Error: Class constructor failed for package 'builtin.py-breathe'.

Caused by:
AssertionError:
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1
```

### Error message

```
$ spack -vd spec -I py-breathe ^doxygen/wwgy2bu ^python/qqqezh5
==> [2022-06-11-07:10:23.439845] Imported spec from built-in commands
==> [2022-06-11-07:10:23.441741] Imported spec from built-in commands
==> [2022-06-11-07:10:23.444694] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/config.yaml
==> [2022-06-11-07:10:23.486600] Reading config file /rnsdhpc/code/spack/etc/spack/config.yaml
==> [2022-06-11-07:10:23.493034] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-06-11-07:10:23.505961] DATABASE LOCK TIMEOUT: 3s
==> [2022-06-11-07:10:23.506103] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-06-11-07:10:23.702263] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/config.yaml
==> [2022-06-11-07:10:23.742834] Reading config file /rnsdhpc/code/spack/etc/spack/config.yaml
==> [2022-06-11-07:10:23.746439] DATABASE LOCK TIMEOUT: 3s
==> [2022-06-11-07:10:23.746540] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-06-11-07:10:23.746760] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-06-11-07:10:23.747506] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-06-11-07:10:23.759237] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/rnsdhpc/code/spack/etc/spack/defaults
==> [2022-06-11-07:10:23.759357] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/rnsdhpc/code/spack/etc/spack/defaults/darwin
==> [2022-06-11-07:10:23.759446] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/s3j/.spack/bootstrap/config
==> [2022-06-11-07:10:23.759513] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/s3j/.spack/bootstrap/config/darwin
==> [2022-06-11-07:10:23.760277] Reading config file /Users/s3j/.spack/bootstrap/config/darwin/compilers.yaml
==> [2022-06-11-07:10:23.923820] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=x86_64
==> [2022-06-11-07:10:23.924381] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-06-11-07:10:23.925886] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-06-11-07:10:24.325350] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/config.yaml
==> [2022-06-11-07:11:31.903614] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=x86_64 ^python@3.9 /omsvlh5v6fi2saw5qyqvzsbvqpvrf5yw" provides the "clingo" Python module
==> [2022-06-11-07:11:31.908418] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/concretizer.yaml
==> [2022-06-11-07:11:31.920995] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/repos.yaml
==> [2022-06-11-07:11:31.924629] Reading config file /rnsdhpc/code/spack/etc/spack/repos.yaml
==> [2022-06-11-07:11:32.236191] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/config.yaml
==> [2022-06-11-07:11:32.271913] Reading config file /rnsdhpc/code/spack/etc/spack/config.yaml
==> [2022-06-11-07:11:32.276487] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/mirrors.yaml
==> [2022-06-11-07:11:33.209798] Reading config file /rnsdhpc/code/spack/etc/spack/compilers.yaml
==> [2022-06-11-07:11:33.233388] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/packages.yaml
==> [2022-06-11-07:11:33.289769] Reading config file /rnsdhpc/code/spack/etc/spack/defaults/darwin/packages.yaml
==> [2022-06-11-07:11:33.307114] Reading config file /rnsdhpc/code/spack/etc/spack/packages.yaml
==> [2022-06-11-07:11:54.207012] build(py-breathe)
==> [2022-06-11-07:11:54.252207] AssertionError:
Traceback (most recent call last):
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1125, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 809, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 1363, in extendee_spec
    assert len(deps) == 1
AssertionError
==> [2022-06-11-07:11:54.255916] FailedConstructorError: Class constructor failed for package 'builtin.py-breathe'.

Caused by:
AssertionError:
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1125, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 809, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 1363, in extendee_spec
    assert len(deps) == 1

==> [2022-06-11-07:11:54.256039] Error: Class constructor failed for package 'builtin.py-breathe'.

Caused by:
AssertionError:
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1125, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 809, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 1363, in extendee_spec
    assert len(deps) == 1

Traceback (most recent call last):
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1125, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 809, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 1363, in extendee_spec
    assert len(deps) == 1
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/rnsdhpc/code/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/rnsdhpc/code/spack/lib/spack/spack/cmd/spec.py", line 83, in spec
    specs = [(s, s.concretized()) for s in input_specs]
  File "/rnsdhpc/code/spack/lib/spack/spack/cmd/spec.py", line 83, in <listcomp>
    specs = [(s, s.concretized()) for s in input_specs]
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 3013, in concretized
    clone.concretize(tests=tests)
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/rnsdhpc/code/spack/lib/spack/spack/solver/asp.py", line 2295, in solve
    return self.driver.solve(
  File "/rnsdhpc/code/spack/lib/spack/spack/solver/asp.py", line 680, in solve
    answers = builder.build_specs(tuples)
  File "/rnsdhpc/code/spack/lib/spack/spack/solver/asp.py", line 2182, in build_specs
    root._finalize_concretization()
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 2986, in _finalize_concretization
    spec._cached_hash(ht.package_hash, force=True)
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 1805, in _cached_hash
    hash_string = self.spec_hash(hash)
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 1781, in spec_hash
    return hash.override(self)
  File "/rnsdhpc/code/spack/lib/spack/spack/hash_types.py", line 57, in <lambda>
    override=lambda s: s.package.content_hash())
  File "/rnsdhpc/code/spack/lib/spack/spack/spec.py", line 1515, in package
    self._package = spack.repo.get(self)
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1403, in get
    return path.get(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 438, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 951, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 438, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1136, in get
    raise FailedConstructorError(spec.fullname, *sys.exc_info())
spack.repo.FailedConstructorError: Class constructor failed for package 'builtin.py-breathe'.

Caused by:
AssertionError:
  File "/rnsdhpc/code/spack/lib/spack/spack/repo.py", line 1125, in get
    return package_class(spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 809, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/rnsdhpc/code/spack/lib/spack/spack/package_base.py", line 1363, in extendee_spec
    assert len(deps) == 1
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.19.0.dev0 (bf2b30a5f572fbe5a54a72a0a6d14636e59b8c5e)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This still exists in:

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

To reproduce:
```
$ spack install meson
$ spack uninstall -y meson
$ spack spec -Il meson ^py-pip/<hash1> ^python/<hash2>
```
