### ISSUE TITLE
`\` in username breaks spack

### ISSUE THREAD

**Issue by CreRecombinase** [LLNL/spack#31377]
### Steps to reproduce

Due to fun enterprise stuff I don't fully grasp, my username has a `\` in it (e.g `GROUP\nuser`).   This causes something to break at some point during `spack fetch` 
```console
spack -v fetch libiconv@1.16
```

Somehow `/tmp/GROUP/nuser/spack-stage/spack-stage-libiconv-1.16-2we7xr3tsxc4nuhkcfvxfihifrm7bzt3/libiconv-1.16.tar.gz` gets created, but then spack barks when it can't find `/tmp/GROUP\\nuser/spack-stage/spack-stage-libiconv-1.16-2we7xr3tsxc4nuhkcfvxfihifrm7bzt3/libiconv-1.16.tar.gz`

### Error message

```console
lib/spack/spack/cmd/__init__.py:123 ==> [2022-06-29-13:09:32.799947] Imported fetch from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-06-29-13:09:32.802677] Imported fetch from built-in commands
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:32.807051] Reading config file /home/nuser/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:32.849021] Reading config file /home/nuser/.spack/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:32.864852] Reading config file /home/nuser/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:32.884708] Reading config file /home/nuser/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:33.071836] Reading config file /home/nuser/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:383 ==> [2022-06-29-13:09:33.084068] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:387 ==> [2022-06-29-13:09:33.084457] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:33.086492] Reading config file /home/nuser/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:33.952178] Reading config file /home/nuser/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1017 ==> [2022-06-29-13:09:33.960062] Reading config file /home/nuser/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/solver/asp.py:2133 ==> [2022-06-29-13:09:34.103825] build(libiconv)
lib/spack/llnl/util/filesystem.py:699 ==> [2022-06-29-13:09:34.126975] creating /tmp/GROUP
lib/spack/spack/stage.py:77 ==> [2022-06-29-13:09:34.127589] Warning: Expected /tmp/GROUP to have group 0, but it is 66049
lib/spack/llnl/util/filesystem.py:699 ==> [2022-06-29-13:09:34.128157] creating /tmp/GROUP/nuser
lib/spack/llnl/util/filesystem.py:699 ==> [2022-06-29-13:09:34.129861] creating /tmp/GROUP/nuser/spack-stage
lib/spack/llnl/util/filesystem.py:699 ==> [2022-06-29-13:09:34.130895] creating /tmp/GROUP/nuser/spack-stage/spack-src
lib/spack/spack/stage.py:319 ==> [2022-06-29-13:09:34.135949] Creating stage lock spack-stage-libiconv-1.16-2we7xr3tsxc4nuhkcfvxfihifrm7bzt3
lib/spack/llnl/util/filesystem.py:699 ==> [2022-06-29-13:09:34.136867] creating /tmp/GROUP/nuser/spack-stage/spack-stage-libiconv-1.16-2we7xr3tsxc4nuhkcfvxfihifrm7bzt3
lib/spack/spack/fetch_strategy.py:344 ==> [2022-06-29-13:09:34.138513] Checking existence of https://mirror.spack.io/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
lib/spack/spack/fetch_strategy.py:385 ==> [2022-06-29-13:09:34.467584] Fetching https://mirror.spack.io/_source-cache/archive/e6/e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04.tar.gz
Traceback (most recent call last):
  File "/home/nuser/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/home/nuser/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/nuser/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/nuser/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/nuser/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/nuser/spack/lib/spack/spack/cmd/fetch.py", line 78, in fetch
    spec.package.do_fetch()
  File "/home/nuser/spack/lib/spack/spack/package.py", line 1538, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/home/nuser/spack/lib/spack/spack/util/pattern.py", line 19, in __call__
    for item in self.container]
  File "/home/nuser/spack/lib/spack/spack/util/pattern.py", line 19, in <listcomp>
    for item in self.container]
  File "/home/nuser/spack/lib/spack/spack/stage.py", line 496, in fetch
    self.fetcher.fetch()
  File "/home/nuser/spack/lib/spack/spack/fetch_strategy.py", line 83, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/nuser/spack/lib/spack/spack/fetch_strategy.py", line 330, in fetch
    partial_file, save_file = self._fetch_from_url(url)
  File "/home/nuser/spack/lib/spack/spack/fetch_strategy.py", line 369, in _fetch_from_url
    return self._fetch_urllib(url)
  File "/home/nuser/spack/lib/spack/spack/fetch_strategy.py", line 83, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/nuser/spack/lib/spack/spack/fetch_strategy.py", line 399, in _fetch_urllib
    with open(save_file, 'wb') as _open_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/GROUP\\nuser/spack-stage/spack-stage-libiconv-1.16-2we7xr3tsxc4nuhkcfvxfihifrm7bzt3/libiconv-1.16.tar.gz'
```

### Information on your system

* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.7.10
* **Platform:** linux-amzn2-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Seems like a great way to break applications in general! Is `\n` the literal two bytes or a single newline character?

**Comment by CreRecombinase** [comment]
I'm pretty sure it's just a `\`. There's some kind of Active Directory thing going on I think? To protect the names of the innocent(?) I've changed the log/traceback to a fake username for the github issue; I kept the `\` followed by `n` because I'm not sure if it really is the `\` that's the problem or if it's specifically `\` followed by `n`.

**Comment by CreRecombinase** [comment]
It looks like [`format_os_path` is the culprit](https://github.com/spack/spack/blob/13b0e73a4eed301a75465ef5f1ef8980f4621605/lib/spack/spack/util/path.py#L194).   Specifically [this line ](https://github.com/spack/spack/blob/13b0e73a4eed301a75465ef5f1ef8980f4621605/lib/spack/spack/util/path.py#L212) where `\` is converted to `/`.  Having the function return its input seems to have fixed it

**Comment by haampie** [comment]
Yes, that absolutely makes no sense for Linux. Can you make a PR that drops that transformation?
