### ISSUE TITLE
spack unit-test fails

### ISSUE THREAD

**Issue by certik** [LLNL/spack#31472]
Following the steps from: https://spack.readthedocs.io/en/latest/contribution_guide.html#unit-tests

```console
$ spack unit-test
==> Error: required field "lineno" missing from alias
$ spack  unit-test lib/spack/spack/test/util/util_url.py  
Traceback (most recent call last):
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/ondrej/repos/spack/lib/spack/spack/test/util/util_url.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/ondrej/repos/spack/lib/spack/spack/test/util')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/config.py", line 373, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/ondrej/repos/spack/lib/spack/spack/test/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 939, in _find_spec
AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 941, in _find_spec
  File "<frozen importlib._bootstrap>", line 915, in _find_spec_legacy
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/assertion/rewrite.py", line 139, in find_module
    source_stat, co = _rewrite_test(self.config, fn_pypath)
  File "/Users/ondrej/repos/spack/lib/spack/external/pytest-fallback/_pytest/assertion/rewrite.py", line 335, in _rewrite_test
    co = compile(tree, fn.strpath, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
ERROR: could not load /Users/ondrej/repos/spack/lib/spack/spack/test/conftest.py
```

I use Apple M1.

**Comment by alalazo** [comment]
First link seems to be [this one](https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest). I assume you are using Python 3.10 ? If that's the case, you can `pip install` a new pytest and that will work as a workaround.

I'll check if we can cleanly get rid of our old vendored version and use the internal bootstrapping logic.

**Comment by alalazo** [comment]
Unreproducible as of

* **Spack:** 0.20.0.dev0 (4ace1e660a3ab60a2e510308d700e251126f8c0e)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo
