### ISSUE TITLE
Cannot extract archive, unrecognized file extension: 'None'

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#31499]
### Steps to reproduce

On linux,

```
$ spack -d stage eccodes@2.25.0
==> [2022-07-08-17:43:03.348355] Staging archive: /tmp/harmen/spack-stage/spack-stage-eccodes-2.25.0-svaf535zwdloqoikjuskycdctfqnns7t/eccodes-2.25.0-Source.tar.gz?api=v2
==> [2022-07-08-17:43:03.348504] CommandNotFoundError: Cannot extract archive, unrecognized file extension: 'None'
==> [2022-07-08-17:43:03.348532] Error: Cannot extract archive, unrecognized file extension: 'None'
Traceback (most recent call last):
  File "/home/harmen/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/harmen/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/harmen/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/harmen/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/harmen/spack/lib/spack/spack/cmd/stage.py", line 64, in stage
    package.do_stage()
  File "/home/harmen/spack/lib/spack/spack/package_base.py", line 1577, in do_stage
    self.stage.expand_archive()
  File "/home/harmen/spack/lib/spack/spack/util/pattern.py", line 18, in __call__
    return [getattr(item, self.name)(*args, **kwargs)
  File "/home/harmen/spack/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs)
  File "/home/harmen/spack/lib/spack/spack/stage.py", line 610, in expand_archive
    self.fetcher.expand()
  File "/home/harmen/spack/lib/spack/spack/fetch_strategy.py", line 84, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/harmen/spack/lib/spack/spack/fetch_strategy.py", line 539, in expand
    decompress = decompressor_for(self.archive_file, self.extension)
  File "/home/harmen/spack/lib/spack/spack/util/compression.py", line 258, in decompressor_for
    raise CommandNotFoundError("Cannot extract archive, \
spack.util.executable.CommandNotFoundError: Cannot extract archive, unrecognized file extension: 'None'

```

@scheibelp @johnwparent yet another instance where there's regression on Linux thanks to Windows support. Please fix... it's such a waste of time :(

**Comment by haampie** [comment]
Apart from restoring the pre-Windows behavior, there's multiple better solutions.

First, the original filename is part of the response header and can be parsed from there.

```
$ curl -i https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.25.0-Source.tar.gz?api=v2
HTTP/1.1 200 200
....
Content-Disposition: inline; filename="eccodes-2.25.0-Source.tar.gz"
```

In CURL this is:

```
$ curl -JO https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.25.0-Source.tar.gz?api=v2
curl: Saved to filename 'eccodes-2.25.0-Source.tar.gz'
```

This also solves the special case code for sourceforge...

```
$ curl -LJO https://sourceforge.net/projects/argtable/files/argtable/argtable-2.13/argtable2-13.tar.gz/download
$ ls
argtable2-13.tar.gz
```

Secondly, the best option is to actually parse the file magic bytes to figure out what type of archive it is regardless of the url, or response headers, which should obviously be much more reliable...

**Comment by scheibelp** [comment]
Thanks for pointing this out @haampie, but regarding

> yet another instance where there's regression on Linux thanks to Windows support. Please fix... it's such a waste of time :(

I'm having trouble extracting anything useful from that: we want Windows support; adding features creates bugs; we catch as many as we can with unit/smoke tests. Besides improving the tests and responding to issues as they are brought up, what else is there to do?

**Comment by haampie** [comment]
Sorry, I was frustrated with Spack... I tried parallel `spack install` and hit 5 unique bugs. You'd think that a decade old project that is supposed to install software can install software.

**Comment by adamjstewart** [comment]
Just hit this same issue with PyPI where URLs look like: https://files.pythonhosted.org/packages/b6/3e/cb066e5cb76302f73a20e302b40e6fd5aea9462ce520581165348c008913/Sphinx-5.1.0.tar.gz#sha256=7893d10d9d852c16673f9b1b7e9eda1606b420b7810270294d6e4b44c0accacc

**Comment by haampie** [comment]
#31618 solves this:

on develop:

```
$ spack clean -d && spack stage py-sphinx@5.1.0
==> Warning: Missing a source id for py-sphinx@5.1.0
==> Warning: There is no checksum on file to fetch py-sphinx@5.1.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://files.pythonhosted.org/packages/b6/3e/cb066e5cb76302f73a20e302b40e6fd5aea9462ce520581165348c008913/Sphinx-5.1.0.tar.gz#sha256=7893d10d9d852c16673f9b1b7e9eda1606b420b7810270294d6e4b44c0accacc
==> Error: Cannot extract archive, unrecognized file extension: 'None'
```

with #31618

```
==> Warning: Missing a source id for py-sphinx@5.1.0
==> Warning: There is no checksum on file to fetch py-sphinx@5.1.0 safely.
==>   Fetch anyway? [y/N] y
==> Staged py-sphinx in /tmp/harmen/spack-stage/spack-stage-py-sphinx-5.1.0-l7aqkef3n7j4tpujsea5quofp53jkjdi
``` 

So we should just merge it as a simple quick fix. And in the meantime @johnwparent is working on file magic to detect archive types iiuc.

**Comment by johnwparent** [comment]
> in the meantime @johnwparent is working on file magic to detect archive types iiuc.

Yes, this is correct. That effort can be found at #31589
