### ISSUE TITLE
Error: No module named 'decimal' on environment install

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31502]
### Steps to reproduce

No idea why I'm experiencing this and no one else is, but any time I install an environment, I see an error message.

### Error message

```console
$ spack -d -e . install
...
==> [2022-07-08-10:54:53.744735] Regenerating environment views for /Users/ajstewart/.spack
==> [2022-07-08-10:54:53.899933] View at /Users/ajstewart/.spack/.spack-env/view does not need regeneration.
==> [2022-07-08-10:54:53.900032] Reading config file /Users/ajstewart/spack/etc/spack/defaults/modules.yaml
==> [2022-07-08-10:54:53.907032] Reading config file /Users/ajstewart/spack/etc/spack/defaults/darwin/modules.yaml
==> [2022-07-08-10:54:53.911969] 	WRITE: grep@3.7%apple-clang@13.1.6~pcre arch=darwin-monterey-m1/p6le6uv [/Users/ajstewart/spack/share/spack/modules/darwin-monterey-m1/grep-3.7-apple-clang-13.1.6-p6le6uv]
Traceback (most recent call last):
  File "/Users/ajstewart/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ajstewart/spack/lib/spack/spack/cmd/install.py", line 345, in install
    env.write()
  File "/Users/ajstewart/spack/lib/spack/spack/environment/environment.py", line 1976, in write
    spack.hooks.post_env_write(self)
  File "/Users/ajstewart/spack/lib/spack/spack/hooks/__init__.py", line 75, in __call__
    hook(*args, **kwargs)
  File "/Users/ajstewart/spack/lib/spack/spack/hooks/module_file_generation.py", line 56, in post_env_write
    _for_each_enabled(spec, 'write')
  File "/Users/ajstewart/spack/lib/spack/spack/hooks/module_file_generation.py", line 32, in _for_each_enabled
    getattr(generator, method_name)()
  File "/Users/ajstewart/spack/lib/spack/spack/modules/common.py", line 859, in write
    import jinja2
  File "/Users/ajstewart/spack/lib/spack/external/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/ajstewart/spack/lib/spack/external/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/ajstewart/spack/lib/spack/external/jinja2/defaults.py", line 4, in <module>
    from .tests import TESTS as DEFAULT_TESTS  # noqa: F401
  File "/Users/ajstewart/spack/lib/spack/external/jinja2/tests.py", line 3, in <module>
    import decimal
ModuleNotFoundError: No module named 'decimal'
```
This doesn't make any sense, as `decimal` is a builtin Python module and I have no issues importing it, even within Spack:
```console
$ spack python
Spack version 0.19.0.dev0
Python 3.9.13, Darwin arm64
>>> import decimal
>>> 
```

### Information on your system

* **Spack:** 0.19.0.dev0 (a12ce9fd59c32e650b43610925e454322995a81d)
* **Python:** 3.9.13
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Looking at the stacktrace, it seems the bug is triggered by our vendored version of Jinja2[^1] when trying to write module files.

[^1]: The version we vendor is 2.11.3, which is the last one to support Python 2.7. The last version of Jinja2 is 3.1.2

**Comment by tgamblin** [comment]
I also see this, FWIW.  I'm not able to reproduce it by calling `spack env view regenerate` (even after deleting the view entirely).

**Comment by frejanordsiek** [comment]
I recently got the same error and I think I have successfully determined the cause and how to fix it.

For reference, I got this in both 0.19.0 and 0.19.1.

The problem has to do with which python is used to run spack. If a python installed by spack is earlier in `PATH` than the system python, spack will use that python. The problem occurs if, while installing a package, spack replaces the python that it is running on with a different one. Then, when it goes to rebuild the view, it needs to import the `decimal` module, it no longer exists.

Essentally, spack is rug pulling itself in this situation.

The solution is to set the environmental variable `SPACK_PYTHON` to the path to the system python or some other python interpreter that is guaranteed to be unaffected by whatever spack does.

**Comment by adamjstewart** [comment]
I'm satisfied with this explanation. I don't think there's much Spack can do to prevent this, and we now have a workaround for anyone who searches the repo with the same issue. I think we can close this.

**Comment by frejanordsiek** [comment]
This is probably something that should be added to the documentation, or how spack determines which interpreter to use changed to prevent this.

**Comment by adamjstewart** [comment]
Hmm, how would you propose changing how spack determines which interpreter to use? The interpreter works just fine when you first run spack, the issue is during the middle of runtime.

**Comment by frejanordsiek** [comment]
The list that is checked through is at https://github.com/spack/spack/blob/d15fe6a3459727187dd23b9b18dad18f5fd734fa/bin/spack#L14 . One could add the following at the beginning

* `/usr/local/bin/python3`
* `/usr/bin/python3`
* `/usr/local/bin/python`
* `/usr/bin/python`

which would tend to get the system python first. Though, one problem is that this would be bad inside a virtual environment (I don't know if anyone is running spack inside a python virtual environment, but if anyone is, this would cause problems).

**Comment by adamjstewart** [comment]
The other problem with this is that the system Python tends to be very old, so it helps to prefer the first Python found in the PATH because it's usually the newest. Although preferring the system Python would avoid some issues I've encountered on macOS.

**Comment by tgamblin** [comment]
I'm going to reopen this while I think of ways to prevent it -- I still think it's an issue and we shouldn't just have env installs result in this error.

Thanks to @frejanordsiek for diagnosing this!

**Comment by frejanordsiek** [comment]
As far as how to handle env installs, one possibility is to go through the current list and do `whereis` on each one if finds. If the path that `whereis` returns is clearly a spack installed package, it is skipped and set aside and not used unless there is no other option.

I just found it because I was doing building in stages and doing fresh concretizations (making a tree of containers with different software where each is built from some earlier one in the tree with new stuff added). Even though that wasn't changing the configuration of python, it was causing it to be rebuilt (probably due to a change in its dependencies) which caused the problem.

**Comment by frejanordsiek** [comment]
> The other problem with this is that the system Python tends to be very old, so it helps to prefer the first Python found in the PATH because it's usually the newest. Although preferring the system Python would avoid some issues I've encountered on macOS.

@adamjstewart 

When first making a Spack setup, it has to use the system python (this is listed as one of the dependencies in https://spack.readthedocs.io/en/latest/getting_started.html after all). In order to install python as a package, the system python has to be enough (also, not everyone using Spack will even install python with it). So depending on the system python isn't too bad of a thing to do. Might be a bit slower, but the time spent in the stuff that Spack calls into (like the build system when building packages) generally is much much larger than the time spent in the python interpreter and python modules.

**Comment by frejanordsiek** [comment]
In retrospect, I think `whereis` is not the right approach. However, spack could run the python to get `sys.prefix` and `sys.base_prefix` (https://docs.python.org/3/library/sys.html#sys.prefix and https://docs.python.org/3/library/sys.html#sys.base_prefix). If they are inequal, then the python is in a virtual environment and that should be chosen. Otherwise, it is either a system python, a user manually compiled python, or python that spack installed and is in a view. The latter can be determined by looking at `sys.prefix` which will end with something like `._view/q63knt3ejnbksfgg5b3rkgjlozaz77xk`. Essentially, one just has to look for the `._view` as the parent directory. If it is present, the python must be skipped. Otherwise, it can be accepted.

**Comment by frejanordsiek** [comment]
I made a PR that would fix this. Ended up using a combination of `sys.prefix` and `sys.base_prefix` and using `whereis` to find fallbacks.

**Comment by adamjstewart** [comment]
Is this still an issue? I haven't encountered this in years.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen.
