### ISSUE TITLE
spack on Cray (again)

### ISSUE THREAD

**Issue by roblatham00** [LLNL/spack#3153]
The Argonne 'Theta' system is a little bit different from the NERSC Cray machines.    I know you've been doing a lot of work on Cray systems, so I'm working from a just-checked-out 'develop' version. 

spack finds a whole bunch of compilers:

```% spack compilers
==> Available compilers
-- cce ----------------------------------------------------------
cce@8.5.7  cce@8.5.5  cce@8.5.4  cce@8.5.2  cce@8.5.1  cce@8.5.0  cce@8.4.6

-- gcc ----------------------------------------------------------
gcc@6.3.0  gcc@6.2.0  gcc@6.1.0  gcc@5.3.0  gcc@4.9.3  gcc@4.8

-- intel --------------------------------------------------------
intel@17.0.1.132  intel@17.0.1  intel@17.0.0.098  intel@16.0.3.210
```

Let's look at something simple:

```
% spack spec bzip2
Input spec
--------------------------------
bzip2

Normalized
--------------------------------
bzip2

Concretized
--------------------------------
bzip2@1.0.6%gcc@6.3.0+shared arch=cray-CNL-mic_knl 
```
great! spack found a compiler and the arch.  Let's go!

```
==> Installing bzip2
==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1' 
==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2' 
==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'                                                                               ==> '/opt/cray/pe/modules/3.2.10.5/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'                                                                              ==> Error: SyntaxError: invalid syntax (<string>, line 504)   /gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py:567, in child_execution:                                                                    547      def child_execution(child_connection, input_stream): 
548          try:                                                              
549              setup_package(pkg, dirty=dirty)                               
550              function(input_stream)                                        
551              child_connection.send(None)                                    
552          except StopIteration as e:                                        
553              # StopIteration is used to stop installations                  
554              # before the final stage, mainly for debug purposes            
555              tty.msg(e.message)                                             
556              child_connection.send(None)                                    
557          except:                                                            
558              # catch ANYTHING that goes wrong in the child process         
559              exc_type, exc, tb = sys.exc_info()                           
560                                                                             
561              # Need to unwind the traceback in the child because traceback                                                                                  562              # objects can't be sent to the parent.                         
563              tb_string = traceback.format_exc()                            
564                                                                             
565              # build up some context from the offending package so we can                                                                                   566              # show that, too.                                           
>> 567              package_context = get_package_context(tb)                     
568                                                                             
569              build_log = None                                              
570              if hasattr(pkg, 'log_path'):                                  
571                  build_log = pkg.log_path                                  
572                                                                            
573              # make a pickleable exception to send to parent.              
574              msg = "%s: %s" % (str(exc_type.__name__), str(exc))
575
576              ce = ChildError(msg, tb_string, build_log, package_context)
577              child_connection.send(ce)
578
579          finally:
580              child_connection.close()
Traceback (most recent call last):
  File "/gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py", line 549, in child_execution 
    setup_package(pkg, dirty=dirty)
  File "/gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py", line 492, in setup_package   
    set_compiler_environment_variables(pkg, spack_env)
  File "/gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py", line 227, in set_compiler_environment_variables
    load_module(mod)
  File "/gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py", line 139, in load_module
    error=str), '<string>', 'exec'))
  File "<string>", line 504
    craype-mic-knl requires cce/8.4 or later, intel/14.0 or later, or gcc/5.1 or later
                          ^
SyntaxError: invalid syntax
```

I'm not really sure what's going on here.  Definitely open to the suggestion that I did not do enough configuring -- things seemed to work automatically and I have not had to edit or create any .yaml files by hand ... yet.

 The error is the same as in #2359 , though I don't think for the same reason.  I also found #2572 , but that's been fixed for a few months and also does not seem to be what I'm running into either.

**Comment by mamelara** [comment]
Okay. Weird thing...I was able to reproduce the issue and got the same error. Tried running git bisect to see if there was a bad commit, but now I can't reproduce it! I can get bzip2 to install...

**Comment by roblatham00** [comment]
I see the problem on Theta with 7bebfd29c21 and I went back to December's c3cd948537dc3, both of which failed the same way.

**Comment by mamelara** [comment]
Still unable to reproduce. Can you give me a list of commands you took with a fresh install of Spack?

**Comment by roblatham00** [comment]
Absolutely.  I deleted my `~/.spack` and `~/src/spack` directories, then did the following:
````
% git clone https://github.com/LLNL/spack.git
...
% spack arch
cray-CNL-mic_knl
% spack compilers
==> Available compilers
-- cce ----------------------------------------------------------
cce@8.5.7  cce@8.5.5  cce@8.5.4  cce@8.5.2  cce@8.5.1  cce@8.5.0  cce@8.4.6

-- gcc ----------------------------------------------------------
gcc@6.3.0  gcc@6.2.0  gcc@6.1.0  gcc@5.3.0  gcc@4.9.3  gcc@4.8

-- intel --------------------------------------------------------
intel@17.0.1.132  intel@17.0.1  intel@17.0.0.098  intel@16.0.3.210

% spack install bzip2
==> Installing bzip2
==> Error: SyntaxError: invalid syntax (<string>, line 504)
/gpfs/theta-fs1/home/robl/src/spack/lib/spack/spack/build_environment.py:567, in child_execution:
... (identical error message omitted)
% % git branch -v
* develop 7bebfd29 spectrum-mpi: Add url info to spectrum-mpi package file (#3042)
````

Not sure how much help that is.  Didn't think I was doing anything too complex.

**Comment by mamelara** [comment]
Okay, finally able to reproduce. I was missing the obvious (module load craype-mic-knl), so apologies. 

Okay, so it looks like whenever craype-mic-knl is the target and we unload the current PrgEnv (meaning the PrgEnv currently loaded before you launch spack install) that error message is thrown.  I'm guessing haswell doesn't have an issue with this so we never got it. As you can see from the debug message, we unload all of the PrgEnv and load the appropriate PrgEnv depending on the type of compiler used (gcc, intel, etc). So if we have craype-mic-knl as our target module, we won't be able to do this. 

As you can see mic-knl modulefile has this little block:
```
if { [ file exists "/opt/cray/craype" ]} {
  set start_path "/opt/cray/craype"
} elseif { [ file exists "/opt/cray/pe/craype" ]} {
  set start_path "/opt/cray/pe/craype"
} elseif { [file exists "/opt/cray/xt-asyncpe" ]} {
  set start_path "/opt/cray/xt-asyncpe"
} else {
  puts "Either craype/1.05 or later or xt-asyncpe/5.21 or later  are required."
  exit 1
}
set available_modules [lsort [glob $start_path/*]]
set latest_module [lindex $available_modules [expr [llength $available_modules] - 2]]

if { [file exists "$latest_module/admin/bin/modulefile-utils.tcl" ]} {
  source $latest_module/admin/bin/modulefile-utils.tcl
} else {
  puts stderr "Error: could not find modulefile-utils.tcl."
  puts stderr "Either craype/1.05 or later  or xt-asyncpe/5.21 or later are required."
  exit 1
}

if {[module-info mode load] || [module-info mode switch2]} {
  requires -fatal cce >= 8.4 || intel >= 14.0 || gcc >= 5.1
}

**Comment by roblatham00** [comment]
First time digging into modules, so bear with me as I no doubt ask some dumb questions.

``/opt/cray/pe/craype/2.5.9/modulefiles/craype-mic-knl`` succeeds in finding (in Theta's case) ``/opt/cray/pe/craype/2.5.9/admin/bin/modulefile-utils.tcl`` ( or else we'd have gotten a different error message)

Which part of that last check is failing?  the ``module-info mode load`` or the ``module-info mode switch2``?   Or does it matter?

What's next?  Should I be harassing cray to fix a bug in their module?

**Comment by wscullin** [comment]
Hi Rob,

Cray has a wonderfully non-functional modules setup for anyone not using bash. You'll encounter this later on in Spack. So, in the craype-mic-knl module, there's a line:

`requires -fatal cce >= 8.4 || intel >= 14.0 || gcc >= 5.1`

which one would think means: produce a fatal even if not one of these versions. However, due to order of operations in Tcl, we find things dying unless cce is loaded and at a version greater than 8.4. I'm trying to figure out how to fix this madness right now, but my workaround is to load cce, then carry on using other compilers.

**Comment by roblatham00** [comment]
hah. sonofagun.  After `module load cce`, I can install bzip2:

```
% spack find
==> 1 installed packages.
-- cray-CNL-mic_knl / gcc@6.3.0 ---------------------------------
bzip2@1.0.6
```

thanks for the pointer

**Comment by wscullin** [comment]
FWIW, theta is completely factory  - everything is exactly as Cray ships it, except for the giant glaring security holes in the administration tools and the use of Cobalt.

**Comment by pramodk** [comment]
encountered same on theta. thanks @roblatham00  & @wscullin for pointer!

**Comment by roblatham00** [comment]
Should I open new issues whenever I find a problem building on Cray/Theta ?  I'll treat this ticket as a general umbrella ticket for now but give me a holler if you'd rather me open multiple tickets.

It's been a few months, so I'm synching up with `develop` and trying again.  

```% spack spec bzip2
Input spec
--------------------------------
bzip2

Normalized
--------------------------------
bzip2

Concretized
--------------------------------
bzip2@1.0.6%gcc@4.9.3+shared arch=cray-CNL-mic_knl 
```

looks ok, but `spack install bzip2` fails.  Here's the error from the build log:

```==> Executing phase: 'install'
==> 'make' '-j32' '-f' 'Makefile-libbz2_so'
cc -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -c crctable.c
crctable.c:1:0: error: bad value (knl) for -march= switch 
```
I don't know where the '-march=knl' is coming from or why spack or whatever thought gcc would want it

But hey, if spack thinks I need to use the intel compiler, let's go... except `spack install bzip2%intel` also fails.  More of a front-end / back-end issue, though:  the build log fails because we generated backend code:

```Doing 6 tests (3 compress, 3 uncompress) ...
If there's a problem, things might stop at this point.
 
./bzip2 -1  < sample1.ref > sample1.rb2

Please verify that both the operating system and the processor support Intel(R) AVX512F, ADX, RDSEED, AVX512ER, AVX512PF and AVX512CD instructions.
```


I don't see any of these problems on Cray/Cori.

**Comment by pramodskumbhar** [comment]
And for `gcc`,  I believe `march=knl` is not supported by `gcc 4.9.3`. Using newer version should solve the issue:

```
kumbhar@thetalogin6:~> spack install bzip2 %gcc@6.2.0
==> Installing bzip2
==> Using cached archive: /gpfs/mira-home/kumbhar/spack/var/spack/cache/bzip2/bzip2-1.0.6.tar.gz
==> Staging archive: /gpfs/mira-home/kumbhar/spack/var/spack/stage/bzip2-1.0.6-6v3sprqh4phyhinc7whu24op5s5jjnme/bzip2-1.0.6.tar.gz
==> Created stage in /gpfs/mira-home/kumbhar/spack/var/spack/stage/bzip2-1.0.6-6v3sprqh4phyhinc7whu24op5s5jjnme
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase : 'install'
==> Successfully installed bzip2
  Fetch: 0.00s.  Build: 2.82s.  Total: 2.82s.
[+] /gpfs/mira-home/kumbhar/spack/opt/spack/cray-CNL-mic_knl/gcc-6.2.0/bzip2-1.0.6-6v3sprqh4phyhinc7whu24op5s5jjnme
``

**Comment by roblatham00** [comment]
I don't know what asked gcc-4.9.3 to build with `-march=knl` but I'll gladly remove gcc-4.9.3 from the compilers spack knows about.   I'm building along just fine now, building by hand and declaring as a "system package" anything that cannot handle cross compiling.   Probably fair to close this issue.
