### ISSUE TITLE
Installation issue: r@4.2.0 missing some latex file

### ISSUE THREAD

**Issue by simonLeary42** [LLNL/spack#31567]
### Steps to reproduce the issue

download the checksum for r@4.2.0 from [the latest package file](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/r/package.py) and insert it into the current package file
`spack install r@4.2.0`

### Error message

<details><summary>Error message</summary><pre>
     1862    l.132 \RequirePackage{letltxmacro}[2008/06/13]
     1863                                                  ^^M
     1864    !  ==> Fatal error occurred, no output PDF file produced!
     1865    Calls: <Anonymous> -> texi2pdf -> texi2dvi
     1866    Execution halted
  >> 1867    make[1]: *** [Makefile:74: NEWS.pdf] Error 1
     1868    make[1]: *** Waiting for unfinished jobs....
     1869    make[1]: Leaving directory '/scratch/astroth-gpu001/3152565/simonl
             eary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkkm
             amhmu5n4yl7dx/spack-src/doc'
  >> 1870    make: [Makefile:72: docs] Error 2 (ignored)
     1871    make[1]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1872    make[2]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1873    installing parsed Rd
     1874    make[3]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1875      methods
     1876      grDevices

See build log for details:
  /scratch/astroth-gpu001/3152565/simonleary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkkmamhmu5n4yl7dx/spack-build-out.txt

Traceback (most recent call last):
  File "/modules/spack/lib/spack/spack/build_environment.py", line 1060, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/modules/spack/lib/spack/spack/installer.py", line 2012, in build_process
    return installer.run()
  File "/modules/spack/lib/spack/spack/installer.py", line 1866, in run
    self._real_install()
  File "/modules/spack/lib/spack/spack/installer.py", line 1973, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/modules/spack/lib/spack/spack/package.py", line 139, in phase_wrapper
    phase(spec, prefix)
  File "/modules/spack/lib/spack/spack/build_systems/autotools.py", line 439, in build
    inspect.getmodule(self).make(*params)
  File "/modules/spack/lib/spack/spack/build_environment.py", line 158, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/modules/spack/lib/spack/spack/util/executable.py", line 239, in __call__
    raise ProcessError('Command exited with status %d:' %
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'
==> [2022-07-13-20:41:39.310053] Flagging r-4.2.0-m2qq55cstgtcivkmkkmamhmu5n4yl7dx as failed: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'
==> [2022-07-13-20:41:39.396021] ChildError: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'

</pre></details>

### Information on your system

```
* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** clingo
```

### Additional information

I know this hasn't been released yet, I was trying a hacky solution, I just want to contribute if I can.

maintainers:
@glennpj

[spack-build-env.txt](https://github.com/spack/spack/files/9105962/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9105963/spack-build-out.txt)

My attempt at a workaround:

> ! LaTeX Error: File `letltxmacro.sty' not found.
```
$ apt-file search letltxmacro.sty
texlive-latex-base: /usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty
```
I tried adding `depends_on('texlive')` but the build for that failed. Here's the build-out:
```
==> [2022-07-13-21:06:00.099469] texlive: Executing phase: 'autoreconf'
==> [2022-07-13-21:06:00.131093] texlive: Executing phase: 'configure'
==> [2022-07-13-21:06:00.162441] texlive: Executing phase: 'build'
==> [2022-07-13-21:06:00.192170] texlive: Executing phase: 'install'
==> [2022-07-13-21:06:00.200282] '/modules/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.4.0/perl-5.34.0-pamkqpwy6gmcgudpk454p2htq4so2dsc/bin/perl' './install-tl' '-scheme' 'small' '-repository' 'https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/' '-portable' '-profile' '/scratch/astroth-gpu001/3152599/tmpsuh8rhzb'
Automated TeX Live installation using profile: /scratch/astroth-gpu001/3152599/tmpsuh8rhzb
Loading https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb

=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2021
 repository: 2022
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
```

I was able to get around this by building texlive from source.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by glennpj** [comment]
@simonleary-umass-edu I will look into this. I did not run into this but the build may have picked up  some TeX bits from my system.

**Comment by glennpj** [comment]
> I tried adding `depends_on('texlive')` but the build for that failed.

The texlive build is fixed in the develop branch.

**Comment by glennpj** [comment]
I built `r` on a stripped-down Ubuntu-20.04 system and did not run into the issue. What I think is happening is that the build will look for TeX and if not found skip documentation building. I would bet that a system with a full TeX installation would build documentation.
@simonleary-umass-edu I am not sure how or why things are broken on your system, but I think you have uncovered an issue. Can you confirm that having `depends_on('texlive') in the r package.py and running the following is successful?

```
spack install r ^texlive@2019:
```
Adding a `texlive` dependency is one option, but there may be a way to control documentation building.

**Comment by simonLeary42** [comment]
```
==> Installing poppler-0.79.0-3cqjjx6zp74hwifrbc65veaox3hgvf6r
==> No binary for poppler-0.79.0-3cqjjx6zp74hwifrbc65veaox3hgvf6r found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/f9/f985a4608fe592d2546d9d37d4182e502ff6b4c42f8db4be0a021a1c369528c8.tar.xz
fatal: unable to access 'https://anongit.freedesktop.org/git/poppler/test.git/': server certificate verification failed. CAfile: none CRLfile: none
==> Error: FetchError: All fetchers failed for resource-test-3cqjjx6zp74hwifrbc65veaox3hgvf6r

/modules/spack/lib/spack/spack/package.py:1537, in do_fetch:
       1534
       1535        self.stage.create()
       1536        err_msg = None if not self.manual_download else self.download_instr
  >>   1537        start_time = time.time()
       1538        self.stage.fetch(mirror_only, err_msg=err_msg)
       1539        self._fetch_time = time.time() - start_time
       1540


==> Warning: Skipping build of texlive-2019-f6gtldsnjk3nhvrymbs365xav47ulzfh since poppler-0.79.0-3cqjjx6zp74hwifrbc65veaox3hgvf6r failed
==> Warning: Skipping build of r-4.2.0-yh42xzlray2qdyfudmfrzdt5hdnhmgxr since texlive-2019-f6gtldsnjk3nhvrymbs365xav47ulzfh failed
```

**Comment by glennpj** [comment]
Poppler failing to fetch is a separate issue.
