### ISSUE TITLE
singularityce UnknownVariantError

### ISSUE THREAD

**Issue by simon-Leary42** [LLNL/spack#31794]
### Steps to reproduce the issue

```console
$ spack install singularityce~setuid
```

### Error message

<details><summary>Error message</summary><pre>
==> [2022-07-28-16:52:28.598572] UnknownVariantError: trying to set variant "setuid" in package "singularityce", but the package has no such variant [happened during concretization of singularityce~setuid]
==> [2022-07-28-16:52:28.598629] UnknownVariantError: trying to set variant "setuid" in package "singularityce", but the package has no such variant [happened during concretization of singularityce~setuid]
==> [2022-07-28-16:52:28.598660] Error: trying to set variant "setuid" in package "singularityce", but the package has no such variant [happened during concretization of singularityce~setuid]
Traceback (most recent call last):
  File "/modules/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/modules/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/modules/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/modules/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/modules/spack/lib/spack/spack/cmd/install.py", line 389, in install
    specs = spack.cmd.parse_specs(args.spec, concretize=True, tests=tests)
  File "/modules/spack/lib/spack/spack/cmd/__init__.py", line 164, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/modules/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/modules/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/modules/spack/lib/spack/spack/solver/asp.py", line 2297, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "/modules/spack/lib/spack/spack/solver/asp.py", line 2247, in _check_input_and_extract_concrete_specs
    spack.spec.Spec.ensure_valid_variants(s)
  File "/modules/spack/lib/spack/spack/spec.py", line 3408, in ensure_valid_variants
    raise vt.UnknownVariantError(spec, not_existing)
</pre></details>

### Information on your system

* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** clingo

### Additional information

@alalazo 

the log file doesn't say anything about a build-out file but I don't think it ever got to start building anything.

my package file seems to be up to date with https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/singularityce/package.py

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
The error message says:
```
Error: trying to set variant "setuid" in package "singularityce", but the package has no such variant [happened during concretization of singularityce~setuid]
```
and in fact the `singularityce` package has no `setuid` variant. The correct name for the variant seems to be:
```console
$ spack spec singularityce~suid
Input spec
--------------------------------
singularityce~suid

Concretized
--------------------------------
singularityce@3.9.1%gcc@9.4.0+network~suid arch=linux-ubuntu20.04-icelake
    ^cryptsetup@2.3.5%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^autoconf@2.69%gcc@9.4.0 patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-icelake
            ^m4@1.4.19%gcc@9.4.0+sigsegv buildsystem=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-icelake
                ^diffutils@3.8%gcc@9.4.0 buildsystem=autotools arch=linux-ubuntu20.04-icelake
                    ^libiconv@1.16%gcc@9.4.0 buildsystem=autotools libs=shared,static arch=linux-ubuntu20.04-icelake
                ^libsigsegv@2.13%gcc@9.4.0 buildsystem=autotools arch=linux-ubuntu20.04-icelake
            ^perl@5.34.1%gcc@9.4.0+cpanm+shared+threads arch=linux-ubuntu20.04-icelake
                ^berkeley-db@18.1.40%gcc@9.4.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-icelake
                ^bzip2@1.0.8%gcc@9.4.0~debug~pic+shared arch=linux-ubuntu20.04-icelake
                ^gdbm@1.19%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                    ^readline@8.1.2%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                        ^ncurses@6.2%gcc@9.4.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-icelake
                            ^pkgconf@1.8.0%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                ^zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-icelake
        ^automake@1.16.5%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^gettext@0.21%gcc@9.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-icelake
            ^libxml2@2.9.13%gcc@9.4.0~python arch=linux-ubuntu20.04-icelake
                ^xz@5.2.5%gcc@9.4.0~pic libs=shared,static arch=linux-ubuntu20.04-icelake
            ^tar@1.34%gcc@9.4.0 zip=pigz arch=linux-ubuntu20.04-icelake
                ^pigz@2.7%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                ^zstd@1.5.2%gcc@9.4.0+programs compression=none libs=shared,static arch=linux-ubuntu20.04-icelake
        ^json-c@0.16%gcc@9.4.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
            ^cmake@3.23.2%gcc@9.4.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
                ^openssl@1.1.1q%gcc@9.4.0~docs~shared certs=mozilla patches=3fdcf2d arch=linux-ubuntu20.04-icelake
                    ^ca-certificates-mozilla@2022-03-29%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^libtool@2.4.7%gcc@9.4.0 buildsystem=autotools arch=linux-ubuntu20.04-icelake
        ^lvm2@2.03.14%gcc@9.4.0+pkgconfig arch=linux-ubuntu20.04-icelake
            ^libaio@0.3.110%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^popt@1.16%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^util-linux@2.38%gcc@9.4.0~bash arch=linux-ubuntu20.04-icelake
            ^python@3.9.13%gcc@9.4.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-icelake
                ^expat@2.4.8%gcc@9.4.0+libbsd arch=linux-ubuntu20.04-icelake
                    ^libbsd@0.11.5%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                        ^libmd@1.0.4%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                ^libffi@3.4.2%gcc@9.4.0 buildsystem=autotools arch=linux-ubuntu20.04-icelake
                ^sqlite@3.38.5%gcc@9.4.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-icelake
                ^util-linux-uuid@2.37.4%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^go@1.18%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^git@2.37.0%gcc@9.4.0+man+nls+perl+subtree~svn~tcltk arch=linux-ubuntu20.04-icelake
            ^curl@7.84.0%gcc@9.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 libs=shared,static tls=openssl arch=linux-ubuntu20.04-icelake
            ^libidn2@2.3.0%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                ^libunistring@0.9.10%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
            ^openssh@9.0p1%gcc@9.4.0+gssapi arch=linux-ubuntu20.04-icelake
                ^krb5@1.19.3%gcc@9.4.0+shared arch=linux-ubuntu20.04-icelake
                    ^bison@3.8.2%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
                ^libedit@3.1-20210216%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
            ^pcre2@10.39%gcc@9.4.0~jit+multibyte arch=linux-ubuntu20.04-icelake
        ^go-bootstrap@1.4-bootstrap-20171003%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^libgpg-error@1.45%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^gawk@5.1.1%gcc@9.4.0~nls arch=linux-ubuntu20.04-icelake
            ^gmp@6.2.1%gcc@9.4.0 libs=shared,static arch=linux-ubuntu20.04-icelake
            ^mpfr@4.1.0%gcc@9.4.0 libs=shared,static arch=linux-ubuntu20.04-icelake
                ^autoconf-archive@2022.02.11%gcc@9.4.0 patches=130cd48 arch=linux-ubuntu20.04-icelake
                ^texinfo@6.5%gcc@9.4.0 patches=12f6edb,1732115 arch=linux-ubuntu20.04-icelake
    ^libseccomp@2.5.3%gcc@9.4.0+python arch=linux-ubuntu20.04-icelake
        ^gperf@3.1%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
        ^py-cython@0.29.30%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
            ^py-pip@22.1.2%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
            ^py-setuptools@63.0.0%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
            ^py-wheel@0.37.1%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^shadow@4.8.1%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^squashfs@4.5.1%gcc@9.4.0+gzip~lz4~lzo~xz~zstd default_compression=gzip arch=linux-ubuntu20.04-icelake
```
