### ISSUE TITLE
Recovering from a corrupted hash database

### ISSUE THREAD

**Issue by robers97** [LLNL/spack#31822]
### Steps to reproduce

spack install
==> Installing environment week1
==> All of the packages are already installed

spack module lmod refresh==> Do you want to proceed? [y/n] y

Output is below... I'd like to know how to clean up the hash.

### Error message

==> Error: No installed spec matches the hash: 'sdco4ep'
==> [2022-07-30-18:45:32.103772] Do you want to proceed? [y/n] y
==> [2022-07-30-18:45:37.090477] NoSuchHashError: No installed spec matches the hash: 'sdco4ep'
==> [2022-07-30-18:45:37.090542] Error: No installed spec matches the hash: 'sdco4ep'
Traceback (most recent call last):
  File "/mnt/users/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/mnt/users/amd/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/mnt/users/amd/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/mnt/users/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/mnt/users/spack/lib/spack/spack/cmd/module.py", line 26, in module
    _subcommands[args.module_command](parser, args)
  File "/mnt/users/spack/lib/spack/spack/cmd/modules/__init__.py", line 371, in modules_cmd
    callbacks[args.subparser_name](module_type, specs, args)
  File "/mnt/users/spack/lib/spack/spack/cmd/modules/__init__.py", line 297, in refresh
    writers = [x for x in writers if not x.conf.blacklisted]
  File "/mnt/users/spack/lib/spack/spack/cmd/modules/__init__.py", line 297, in <listcomp>
    writers = [x for x in writers if not x.conf.blacklisted]
  File "/mnt/users/spack/lib/spack/spack/modules/common.py", line 500, in blacklisted
    blacklist_matches = [x for x in blrules if spec.satisfies(x)]
  File "/mnt/users/spack/lib/spack/spack/modules/common.py", line 500, in <listcomp>
    blacklist_matches = [x for x in blrules if spec.satisfies(x)]
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 3619, in satisfies
    other = self._autospec(other)
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 3603, in _autospec
    return Spec(spec_like)
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 1234, in __init__
    spec_list = SpecParser(self).parse(spec_like)
  File "/mnt/users/spack/lib/spack/spack/parse.py", line 157, in parse
    return self.do_parse()
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 5076, in do_parse
    specs.append(self.spec(self.token.value))
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 5276, in spec
    hash_spec = self.spec_by_hash()
  File "/mnt/users/spack/lib/spack/spack/spec.py", line 5213, in spec_by_hash
    raise NoSuchHashError(dag_hash)
spack.spec.NoSuchHashError: No installed spec matches the hash: 'sdco4ep'

### Information on your system

amd@gbyte-r130-rack2-u3-6:~$ spack debug report
* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by robers97** [comment]
I thought about this more.  I believe I removed a spack package directory because I didn't like the name spack create <URL> assigned it.  So I likely upset the database that way.  Any pointers appreciated.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while (and I couldn't reproduce). Feel free to reopen if you want to continue work on this.
