### ISSUE TITLE
Failure when disabling locks and concretizing an environment with a pool

### ISSUE THREAD

**Issue by lrtfm** [LLNL/spack#31833]
### Steps to reproduce

```console
$ cat config.yaml
config:
  locks: false

.... < create and activate an environment with multi-root package >

$ spack concretize -f
==> Starting concretization pool with 5 processes
==> Error: errors occurred during concretization of the environment:
[Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'
[Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'
[Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'
[Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'
```

### Error message

```console
Traceback (most recent call last):
  File "/vol7/home/lrtfm/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/vol7/home/lrtfm/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 1180, in concretize
    return self._concretize_separately(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 1309, in _concretize_separately
    concretized_root_specs = spack.util.parallel.parallel_map(
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/parallel.py", line 135, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/parallel.py", line 83, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=21431] Traceback (most recent call last):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/parallel.py", line 55, in __call__
    value = self.func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2184, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2160, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2998, in concretized
    clone.concretize(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2914, in concretize
    self._new_concretize(tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2889, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2241, in solve
    reusable_specs.extend(self._reusable_specs())
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2207, in _reusable_specs
    index = spack.binary_distribution.update_cache_and_get_specs()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 1899, in update_cache_and_get_specs
    binary_index.update()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 381, in update
    self._write_local_index_cache()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 146, in _write_local_index_cache
    json.dump(self._local_index_cache, new)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/lock.py", line 731, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/file_cache.py", line 151, in __exit__
    rename(cm.tmp_filename, cm.orig_filename)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/path.py", line 151, in path_filter_caller
    return func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/filesystem.py", line 104, in rename
    os.rename(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'

[PID=21433] Traceback (most recent call last):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/parallel.py", line 55, in __call__
    value = self.func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2184, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2160, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2998, in concretized
    clone.concretize(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2914, in concretize
    self._new_concretize(tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2889, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2241, in solve
    reusable_specs.extend(self._reusable_specs())
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2207, in _reusable_specs
    index = spack.binary_distribution.update_cache_and_get_specs()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 1899, in update_cache_and_get_specs
    binary_index.update()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 381, in update
    self._write_local_index_cache()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 146, in _write_local_index_cache
    json.dump(self._local_index_cache, new)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/lock.py", line 731, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/file_cache.py", line 151, in __exit__
    rename(cm.tmp_filename, cm.orig_filename)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/path.py", line 151, in path_filter_caller
    return func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/filesystem.py", line 104, in rename
    os.rename(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'

[PID=21435] Traceback (most recent call last):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/parallel.py", line 55, in __call__
    value = self.func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2184, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/environment/environment.py", line 2160, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2998, in concretized
    clone.concretize(tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2914, in concretize
    self._new_concretize(tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/spec.py", line 2889, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2241, in solve
    reusable_specs.extend(self._reusable_specs())
  File "/vol7/home/lrtfm/spack/lib/spack/spack/solver/asp.py", line 2207, in _reusable_specs
    index = spack.binary_distribution.update_cache_and_get_specs()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 1899, in update_cache_and_get_specs
    binary_index.update()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 381, in update
    self._write_local_index_cache()
  File "/vol7/home/lrtfm/spack/lib/spack/spack/binary_distribution.py", line 146, in _write_local_index_cache
    json.dump(self._local_index_cache, new)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/lock.py", line 731, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/file_cache.py", line 151, in __exit__
    rename(cm.tmp_filename, cm.orig_filename)
  File "/vol7/home/lrtfm/spack/lib/spack/spack/util/path.py", line 151, in path_filter_caller
    return func(*args, **kwargs)
  File "/vol7/home/lrtfm/spack/lib/spack/llnl/util/filesystem.py", line 104, in rename
    os.rename(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/vol7/home/lrtfm/.spack/cache/indices/contents.json.tmp' -> '/vol7/home/lrtfm/.spack/cache/indices/contents.json'
```

### Information on your system

$ spack debug report
* **Spack:** 0.19.0.dev0 (8640e298136c45aab092b2c76810f49593d79a33)
* **Python:** 3.8.13
* **Platform:** linux-rhel6-ivybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Solved by #37608 (in the sense that now you can control parallelism from the command line, so if you remove synchronization via locks you can prescribe `-j 1` to avoid failures).
