### ISSUE TITLE
Installation issue: vasp@6.3.0

### ISSUE THREAD

**Issue by vijaymocherla** [LLNL/spack#31831]
### Steps to reproduce the issue

```console
$ spack -d install -v -j 16 vasp@6.3.0 +scalapack +openmp %aocc@3.1.0 target=zen3 ^amdfftw@3.1 ^amdblis@3.1 threads=openmp ^amdlibflame@3.1 ^amdscalapack@3.1 ^openmpi@4.1.1 fabrics=auto

...
```

### Error message

<details><summary>Error: OSError: No such file or directory: 'arch/makefile.include.linux_gnu_omp'</summary><pre>
 /home/Lib/spack/var/spack/repos/builtin/packages/vasp/package.py:80, in edit:
         77                        spec['qd'].prefix.lib, make_include)
         78        elif '%aocc' in spec:
         79            if '+openmp' in spec:
  >>     80                copy(
         81                    join_path('arch', 'makefile.include.linux_gnu_omp'),
         82                    join_path('arch', 'makefile.include.linux_aocc_omp')
         83                )
</pre>

See build log for details:
  /tmp/root/spack-stage/spack-stage-vasp-6.3.0-erw2ssvvbmoaye4nruuf6hg4nnwvzttr/spack-build-out.txt

Traceback (most recent call last):
  File "/home/Lib/spack/lib/spack/spack/build_environment.py", line 1060, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/Lib/spack/lib/spack/spack/installer.py", line 2012, in build_process
    return installer.run()
  File "/home/Lib/spack/lib/spack/spack/installer.py", line 1866, in run
    self._real_install()
  File "/home/Lib/spack/lib/spack/spack/installer.py", line 1973, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/home/Lib/spack/lib/spack/spack/package.py", line 139, in phase_wrapper
    phase(spec, prefix)
  File "/home/Lib/spack/var/spack/repos/builtin/packages/vasp/package.py", line 81, in edit
    join_path('arch', 'makefile.include.linux_gnu_omp'),
  File "/home/Lib/spack/lib/spack/spack/util/path.py", line 117, in path_filter_caller
    return func(*args, **kwargs)
  File "/home/Lib/spack/lib/spack/llnl/util/filesystem.py", line 451, in copy
    raise IOError("No such file or directory: '{0}'".format(src))
OSError: No such file or directory: 'arch/makefile.include.linux_gnu_omp'
</details>

### Information on your system

* **Spack:** 0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
* **Python:** 3.9.13
* **Platform:** linux-rocky8-zen3
* **Concretizer:** clingo

### Additional information

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Lib/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/home/Lib/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/Lib/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/Lib/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/Lib/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/Lib/spack/lib/spack/spack/cmd/install.py", line 470, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/home/Lib/spack/lib/spack/spack/cmd/install.py", line 262, in install_specs
    env.install_specs(specs_to_install, args=cli_args, **kwargs)
  File "/home/Lib/spack/lib/spack/spack/environment/environment.py", line 1651, in install_specs
    self.regenerate_views()
  File "/home/Lib/spack/lib/spack/spack/environment/environment.py", line 1411, in regenerate_views
    view.regenerate(concretized_root_specs)
  File "/home/Lib/spack/lib/spack/spack/environment/environment.py", line 581, in regenerate
    raise e
  File "/home/Lib/spack/lib/spack/spack/environment/environment.py", line 565, in regenerate
    view.add_specs(*specs, with_dependencies=False)
  File "/home/Lib/spack/lib/spack/spack/filesystem_view.py", line 816, in add_specs
    self.link_metadata(specs)
  File "/home/Lib/spack/lib/spack/spack/filesystem_view.py", line 841, in link_metadata
    raise MergeConflictSummary(metadata_visitor.file_conflicts)
llnl.util.link_tree.MergeConflictSummary: 810 fatal error(s) when merging prefixes:
    `/home/Lib/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/bzip2-1.0.8-3oiqrtw5im7c3j6loliweaeukufeyjew/.spack/install_environment.json` and `/home/Lib/spack/opt/spack/linux-rocky8-zen3/aocc-3.1.0/bzip2-1.0.8-gsbpcxsc34vrfq37r6cp42a2edv6fz7j/.spack/install_environment.json` both project to `.spack/bzip2/install_environment.json`
    `/home/Lib/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/bzip2-1.0.8-3oiqrtw5im7c3j6loliweaeukufeyjew/.spack/install_manifest.json` and `/home/Lib/spack/opt/spack/linux-rocky8-zen3/aocc-3.1.0/bzip2-1.0.8-gsbpcxsc34vrfq37r6cp42a2edv6fz7j/.spack/install_manifest.json` both project to `.spack/bzip2/install_manifest.json`
    `/home/Lib/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/bzip2-1.0.8-3oiqrtw5im7c3j6loliweaeukufeyjew/.spack/install_times.json` and `/home/Lib/spack/opt/spack/linux-rocky8-zen3/aocc-3.1.0/bzip2-1.0.8-gsbpcxsc34vrfq37r6cp42a2edv6fz7j/.spack/install_times.json` both project to `.spack/bzip2/install_times.json`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vijaymocherla** [comment]
@adamjstewart  @fcannini 
 I couldn't find any information on whose maintaining this package but, I found this pull request #15187. 
 Could you please point this to anyone who can help? 
 If am not wrong, I guess there's some issue with `vasp/package.py` that needs to fixed.

**Comment by franciscoadasme** [comment]
Hey everyone,

It seems that the makefile.include files were renamed in v6.3.0, dropping the `linux_` prefix . Removing the prefix from the paths in `vasp/package.py` solves the issue.

However, then I stumbled with another issue related to the compiler options:

```
6 errors found in build log:
     100    make[2]: Leaving directory '/tmp/fadasme/spack-stage/spack-stage-vasp-6.3.2-2g6t7fsrz57v5brkxsuh6o46d6b4sy6q/spack-src/build/std/parser'
     101    rsync -u ../../src/*.F ../../src/*.inc .
     102    rm -f vasp ; make vasp ; cp vasp ../../bin/vasp_std
     103    make[2]: Entering directory '/tmp/fadasme/spack-stage/spack-stage-vasp-6.3.2-2g6t7fsrz57v5brkxsuh6o46d6b4sy6q/spack-src/build/std'
     104    /home/fadasme/spack/lib/spack/env/aocc/clang -Mfree -E -C -w c2f_interface.F >c2f_interface.f90 -DMPI -DMPI_BLOCK=8000 -Duse_collective -DCACHE_SIZE=4000 -Davoidalloc -Duse_bse_te -Dtbdyn -Duse_s
            hmem -DHOST=\"LinuxGNU\" -Dfock_dblbuf -D_OPENMP -Dvasp6 -DscaLAPACK -DNGZhalf
     105    mpif90 -fopenmp -ffree-form -ffree-line-length-none -fno-fortran-main -Mbackslash -ffast-math -march=native -fallow-argument-mismatch -march=native -fallow-argument-mismatch -O3 -I/path/to/your/f
            ftw/installation/include  -c c2f_interface.f90
  >> 106    clang-13: error: unknown argument: '-fallow-argument-mismatch'
  >> 107    clang-13: error: unknown argument: '-fallow-argument-mismatch'
  >> 108    make[2]: *** [makefile:166: c2f_interface.o] Error 1
     109    make[2]: Leaving directory '/tmp/fadasme/spack-stage/spack-stage-vasp-6.3.2-2g6t7fsrz57v5brkxsuh6o46d6b4sy6q/spack-src/build/std'
  >> 110    cp: cannot stat 'vasp': No such file or directory
  >> 111    make[1]: *** [makefile:129: all] Error 1
     112    make[1]: Leaving directory '/tmp/fadasme/spack-stage/spack-stage-vasp-6.3.2-2g6t7fsrz57v5brkxsuh6o46d6b4sy6q/spack-src/build/std'
  >> 113    make: *** [makefile:17: std] Error 2
```

`mpif90` is a MPI wrapper around `flang` from the AOCC compiler suite, which indeed doesn't recognize `-fallow-argument-mismatch`.

**Comment by jeffmacdonald7** [comment]
Im install VASP6.3.2 and getting same dont recognize -fallow-argument-mismatch 

 spack debug report
* **Spack:** 0.19.0.dev0 (d49c992b230f544deeed13fb193d779a53f2f201)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen3
* **Concretizer:** clingo

I dont know how to get rid of it.   I've delete any mention of "allow-argument-mismatch" from all the makefile.includes, but it  keeps coming BACK.


make[2]: Entering directory '/tmp/root/spack-stage/spack-stage-vasp-6.3.2-y7j3ovk3yqe26rs4syb2wewsyqapljnq/spack-src/build/std'
/usr/local/spack/lib/spack/env/aocc/clang -Mfree -E -C -w c2f_interface.F >c2f_interface.f90 -DMPI -DMPI_BLOCK=8000 -Duse_collective -DCACHE_SIZE=4000 -Davoidalloc -Duse_bse_te -Dtbdyn -Duse_shmem -DHOST=\"LinuxGNU\" -Dfock_dblbuf -D_OPENMP -Dvasp6 -DscaLAPACK -DNGZhalf
mpif90 -fopenmp -ffree-form -ffree-line-length-none -fno-fortran-main -Mbackslash -ffast-math -march=native -fallow-argument-mismatch -march=native -fallow-argument-mismatch -O3 -I/path/to/your/fftw/installation/include  -c c2f_interface.f90
clang-13: error: unknown argument: '-fallow-argument-mismatch'
clang-13: error: unknown argument: '-fallow-argument-mismatch'
make[2]: *** [makefile:166: c2f_interface.o] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vasp-6.3.2-y7j3ovk3yqe26rs4syb2wewsyqapljnq/spack-src/build/std'
cp: cannot stat 'vasp': No such file or directory
make[1]: *** [makefile:129: all] Error 1
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-vasp-6.3.2-y7j3ovk3yqe26rs4syb2wewsyqapljnq/spack-src/build/std'
make: *** [makefile:17: std] Error 2
==> [2022-11-14-15:05:32.882108] Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'std' 'gam' 'ncl'

**Comment by jeffmacdonald7** [comment]
nevermind, I figured out my issue.    I had to open up vasp.6.3.2.tgz   edit makefiles so that NONE of them mention -fallow-argument-mismatch.   Then tar and gzip vasp.6.3.2.tgz.   However spack had the old .tgz cache in /tmp/root/blah blah.

# spack clean --all.    <<   solved that however then the sha256 hash no longer match for  vasp.6.3.2.tgz   I just changed vasp/package.py so that the sha256 would match, now getting further.

**Comment by franciscoadasme** [comment]
Hey everyone,

I've finally compiled vasp v6.3.2 using AMD compiler suite and libraries successfully. The main issue is that the spack package is out of date with the Makefile files included in recent versions of VASP (maybe since v6.3 but I couldn't check that). The latest version, v6.3.2, includes Makefile files tailored for AMD (aocc/aocl) where some invalid flags like `-fallow-argument-mismatch` and library names like `-openblas` are not included/changed.

The current spack package doesn't use these files but instead copies the Makefile for GNU compilers and changes some options, but not all of them, leading to the issues reported here. I've changed the `package.py` to use the correct file for aocc/aocl and it worked. I'd submit the changes but they're hacky so it's not for general use. Hope someone with more experience with spack/VASP could fix it.

In the meantime, here is the modified package: [package.py.txt](https://github.com/spack/spack/files/10058121/package.py.txt)

**Comment by jeffmacdonald7** [comment]
@franciscoadasme      package.py worked for me.   THANK YOU.    I had to download it and replace /usr/local/spack/var/spack/repos/builtin/packages/vasp/package.py with it.    The only other thing required is that I had to manually download vasp.6.3.2.tgz, put it in the directory running spack install from.

/var/tmp/VASP_v6.3.2# sha256sum vasp.6.3.2.tgz 
f7595221b0f9236a324ea8afe170637a578cdd5a837cc7679e7f7812f6edf25a  vasp.6.3.2.tgz

if sha256sum vasp.6.3.2.tgz doesnt match whats in package.py....spack wont touch it.

**Comment by serdar-acir** [comment]
The problem is the latest vasp versions require a template file to be worked on which spack does not seem to handle. Here are the steps that you can try to install vasp via spack.
1- untar the tgz file you have.
2- choose a template makefile.include file under src/ and copy it to the upper folder.
3- modify makefile.include according your platform
4- tar the whole directory to create a new tgz file.
For more detailed steps you can refer to vasp.at website. Make sure you meet the requirements too.
Then hopefully you should be able to install it with spack without problems.

**Comment by vijaymocherla** [comment]
Unfortunately, I no longer have access to the VASP tar files. Since I've moved away from my previous group, that had the VASP license. Otherwise, I'd be happy to write a patch for this. I am not sure if the VASP developers hand out single licenses, but if there is a way to get it for testing and other purposes, I'd like to write to them. If anyone knows anything please do let me know.

**Comment by abhiram-88** [comment]
I am running into a similar issue with 6.4.1. 
I tried the steps listed here but still running into undefined_references with mpif90.
