### ISSUE TITLE
Error with original concretizer on petsc package

### ISSUE THREAD

**Issue by Briffou** [LLNL/spack#31895]
### Steps to reproduce

I observe an error with the original concretizer when trying to install Petsc without superlu-dist (then, +fortran is not needed if I'm right)

```console
$ cat $HOME/.spack/config.yaml
config:
  concretizer: original
```
I ran
```console
$ spack spec petsc@3.17.3 ~superlu-dist
```

### Error message

```console
==> Warning: the original concretizer is currently being used.
	Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack in a future version.
==> Error: Invalid variant superlu-dist for spec petsc@3.17.3%gcc@12.1.1~complex~cuda~debug+double+hdf5~hpddm+hypre+metis~mmg+mpi~mumps~parmmg~ptscotch~rocm+shared~superlu-dist~tetgen arch=linux-fedora36-zen2 ^diffutils@3.8%gcc@12.1.1 arch=linux-fedora36-zen2 ^libiconv@1.16%gcc@12.1.1 libs=shared,static arch=linux-fedora36-zen2 ^openblas@0.3.20%gcc@12.1.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-fedora36-zen2 ^pkgconf@1.8.0%gcc@12.1.1 arch=linux-fedora36-zen2 ^python@3.9.13%gcc@12.1.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-fedora36-zen2.
superlu-dist is only available for petsc when satisfying one of [+fortran].
 11:45  …/Travail/bugs_spack  spack --debug --stacktrace spec petsc@3.17.3 ~superlu-dist
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-03-11:46:01.174581] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-03-11:46:01.175267] Imported spec from built-in commands
lib/spack/spack/config.py:1008 ==> [2022-08-03-11:46:01.176921] Reading config file /home/thomasbriffard/Documents/Travail/bugs_spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-03-11:46:01.188107] Reading config file /home/thomasbriffard/.spack/config.yaml
lib/spack/spack/main.py:541 ==> [2022-08-03-11:46:01.193646] Warning: the original concretizer is currently being used.
	Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack in a future version.
lib/spack/spack/config.py:1008 ==> [2022-08-03-11:46:01.194083] Reading config file /home/thomasbriffard/Documents/Travail/bugs_spack/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.262262] diffutils applying constraint iconv
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.273498] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.284686] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.285231] petsc applying constraint blas
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.285689] petsc applying constraint lapack
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.287950] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/config.py:1008 ==> [2022-08-03-11:46:01.296129] Reading config file /home/thomasbriffard/Documents/Travail/bugs_spack/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.406846] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.407287] diffutils applying constraint iconv
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.407805] petsc applying constraint openblas
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.415482] ncurses applying constraint pkgconfig
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.416178] readline applying constraint ncurses
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.416906] gdbm applying constraint readline
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.420004] bzip2 applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.421677] perl applying constraint gdbm@:1.19
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.422336] perl applying constraint berkeley-db
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.422990] perl applying constraint bzip2
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.423698] perl applying constraint zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.424354] openblas applying constraint perl
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.425479] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^iconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.433430] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.433853] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.443206] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.444371] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^iconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.451137] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^iconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.458662] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.470806] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.471220] diffutils applying constraint libiconv
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.471798] petsc applying constraint openblas
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.474080] ncurses applying constraint pkgconfig
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.474775] readline applying constraint ncurses
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.475419] gdbm applying constraint readline
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.477068] bzip2 applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.478223] perl applying constraint gdbm@:1.19
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.478908] perl applying constraint berkeley-db
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.479534] perl applying constraint bzip2
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.480189] perl applying constraint zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.480864] openblas applying constraint perl
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.482029] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.489959] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.490366] python applying constraint pkgconfig@0.9.0:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.499330] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.500563] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.507760] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconfig@0.9.0: ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.515508] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.528900] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.529287] diffutils applying constraint libiconv
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.529845] petsc applying constraint openblas
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.531815] ncurses applying constraint pkgconf
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.532483] readline applying constraint ncurses
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.533100] gdbm applying constraint readline
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.534535] bzip2 applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.535589] perl applying constraint gdbm@:1.19
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.536151] perl applying constraint berkeley-db
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.536712] perl applying constraint bzip2
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.537288] perl applying constraint zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.537881] openblas applying constraint perl
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.538988] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconf ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.547035] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.547444] python applying constraint pkgconf
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.556384] petsc applying constraint diffutils
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.557818] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconf ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.565170] petsc applying constraint openblas ^berkeley-db ^bzip2 ^diffutils ^gdbm@:1.19 ^libiconv ^ncurses ^perl ^pkgconf ^readline ^zlib
lib/spack/spack/spec.py:3211 ==> [2022-08-03-11:46:01.573260] petsc applying constraint python@2.6:2.8,3.4:
lib/spack/spack/config.py:1008 ==> [2022-08-03-11:46:01.581465] Reading config file /home/thomasbriffard/.spack/linux/compilers.yaml
lib/spack/spack/main.py:964 ==> [2022-08-03-11:46:01.618720] SpackError: Invalid variant superlu-dist for spec petsc@3.17.3%gcc@12.1.1~complex~cuda~debug+double+hdf5~hpddm+hypre+metis~mmg+mpi~mumps~parmmg~ptscotch~rocm+shared~superlu-dist~tetgen arch=linux-fedora36-zen2 ^diffutils@3.8%gcc@12.1.1 arch=linux-fedora36-zen2 ^libiconv@1.16%gcc@12.1.1 libs=shared,static arch=linux-fedora36-zen2 ^openblas@0.3.20%gcc@12.1.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-fedora36-zen2 ^pkgconf@1.8.0%gcc@12.1.1 arch=linux-fedora36-zen2 ^python@3.9.13%gcc@12.1.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-fedora36-zen2.
superlu-dist is only available for petsc when satisfying one of [+fortran].
lib/spack/spack/error.py:54 ==> [2022-08-03-11:46:01.618845] Error: Invalid variant superlu-dist for spec petsc@3.17.3%gcc@12.1.1~complex~cuda~debug+double+hdf5~hpddm+hypre+metis~mmg+mpi~mumps~parmmg~ptscotch~rocm+shared~superlu-dist~tetgen arch=linux-fedora36-zen2 ^diffutils@3.8%gcc@12.1.1 arch=linux-fedora36-zen2 ^libiconv@1.16%gcc@12.1.1 libs=shared,static arch=linux-fedora36-zen2 ^openblas@0.3.20%gcc@12.1.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-fedora36-zen2 ^pkgconf@1.8.0%gcc@12.1.1 arch=linux-fedora36-zen2 ^python@3.9.13%gcc@12.1.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-fedora36-zen2.
superlu-dist is only available for petsc when satisfying one of [+fortran].
Traceback (most recent call last):
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/spec.py", line 2926, in concretize
    self._old_concretize(tests)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/spec.py", line 2716, in _old_concretize
    self._concretize_helper(concretizer),
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/spec.py", line 2546, in _concretize_helper
    concretizer.concretize_variants(self),
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/concretize.py", line 422, in concretize_variants
    raise vt.InvalidVariantForSpecError(name, when, spec)
spack.variant.InvalidVariantForSpecError: Invalid variant superlu-dist for spec petsc@3.17.3%gcc@12.1.1~complex~cuda~debug+double+hdf5~hpddm+hypre+metis~mmg+mpi~mumps~parmmg~ptscotch~rocm+shared~superlu-dist~tetgen arch=linux-fedora36-zen2 ^diffutils@3.8%gcc@12.1.1 arch=linux-fedora36-zen2 ^libiconv@1.16%gcc@12.1.1 libs=shared,static arch=linux-fedora36-zen2 ^openblas@0.3.20%gcc@12.1.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-fedora36-zen2 ^pkgconf@1.8.0%gcc@12.1.1 arch=linux-fedora36-zen2 ^python@3.9.13%gcc@12.1.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-fedora36-zen2.
superlu-dist is only available for petsc when satisfying one of [+fortran].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/home/thomasbriffard/Documents/Travail/bugs_spack/spack/lib/spack/spack/cmd/__init__.py", line 241, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Invalid variant superlu-dist for spec petsc@3.17.3%gcc@12.1.1~complex~cuda~debug+double+hdf5~hpddm+hypre+metis~mmg+mpi~mumps~parmmg~ptscotch~rocm+shared~superlu-dist~tetgen arch=linux-fedora36-zen2 ^diffutils@3.8%gcc@12.1.1 arch=linux-fedora36-zen2 ^libiconv@1.16%gcc@12.1.1 libs=shared,static arch=linux-fedora36-zen2 ^openblas@0.3.20%gcc@12.1.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-fedora36-zen2 ^pkgconf@1.8.0%gcc@12.1.1 arch=linux-fedora36-zen2 ^python@3.9.13%gcc@12.1.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-fedora36-zen2.
superlu-dist is only available for petsc when satisfying one of [+fortran].
```

### Information on your system

```
* **Spack:** 0.19.0.dev0 (4aaa3841b8a60387a1c1e25c2c03dbcf22f74964)
* **Python:** 3.10.5
* **Platform:** linux-fedora36-zen2
* **Concretizer:** original
```

The error is not present when using `clingo`.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The old concretizer uses a greedy algorithm, so it's not able to infer that you also want to use `+fortran`. This:
```console
$ spack -c "config:concretizer:original" spec petsc ~superlu-dist+fortran
==> Warning: the original concretizer is currently being used.
	Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack in a future version.
Input spec
--------------------------------
petsc+fortran~superlu-dist

Concretized
--------------------------------
petsc@3.17.3%gcc@9.4.0~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre~int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi~mumps~openmp~p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared~strumpack~suite-sparse~superlu-dist~tetgen~trilinos~valgrind clanguage=C arch=linux-ubuntu20.04-icelake
[ ... ]
```
is a workaround for the issue. I'm closing this since we are not improving the old concretizer going forward.
