### ISSUE TITLE
Verbose option is not working for the install test in math libraries

### ISSUE THREAD

**Issue by renjithravindrankannath** [LLNL/spack#31920]
### Steps to reproduce

After introducing the file install-time-test-log.txt with the test result logs under below commit it is doesn't show the test result with the build logs when we use --verbose in the install command.
https://github.com/spack/spack/commit/0c31ab87c9940465a529a92b9a9fcb6194b7619d
For example with the below command for hipblas@5.1.0 build on the target Mi50 we are not able to see any result for install 
test as below.
`spack install --verbose --test=root hipblas@5.1.0 ^rocsolver@5.1.0 amdgpu_target=gfx906:xnack-`

`
==> Testing package hipblas-5.1.0-ypz3exc
Running build-time tests
('RUN-TESTS: build-time tests [check]',)
==> hipblas: Executing phase: 'install'

`
However we have the result in the file install-time-test-log.txt

### Error message

No error shows indicating the failure if printing in tty

### Information on your system

Mi50 GPUs

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
I observed this too. In many ways, it feels like install-time testing has become a second class citizen compared to post-install testing. Pretty sure logs are still broken and the install will succeed even if the tests fail. Hoping @tldahlgren can solve some of these problems.

**Comment by renjithravindrankannath** [comment]
Is the install time test logs expected to print in the tty(text console) when it is success?
Currently it is printing for the failure case. Please let us know if this behavior is expected.

**Comment by renjithravindrankannath** [comment]
Hi @tldahlgren / @becker33 , Is there anyone looking into this issue?
Please let us know if this is an expected behavior or it is tracked under a different ticket.

**Comment by tldahlgren** [comment]
I am able to reproduce the failure case and see the outputs in the build stage directory's `install-time-test-log.txt` file.  Let me try the success case.

**Comment by tldahlgren** [comment]
I am also able to see the `install-time-test-log.txt` file on success in the same install prefix subdirectory as the build logs.

Success:
```
$ cat opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b/.spack/install-time-test-log.txt
==> Testing package py-wget-3.2-db5npju
==> [2022-11-08-13:05:18.167348] Running install-time tests
==> [2022-11-08-13:05:18.167494] ('RUN-TESTS: install-time tests [test]',)
==> [2022-11-08-13:05:18.176831] Detected the following modules: ['wget']
==> [2022-11-08-13:05:18.177532] checking import of wget
==> [2022-11-08-13:05:18.178052] '/usr/tce/bin/python3.7' '-c' 'import wget'
PASSED
```

Failure:
```
$ cat $TMPDIR/spack-stage/spack-stage-py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b/install-time-test-log.txt 
==> Testing package py-wget-3.2-smjdyen
==> [2022-11-08-13:24:03.165123] Running install-time tests
==> [2022-11-08-13:24:03.165282] ('RUN-TESTS: install-time tests [test]',)
==> [2022-11-08-13:24:03.166556] checking import of foo
==> [2022-11-08-13:24:03.167352] '/usr/tce/bin/python3.7' '-c' 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
FAILED: Command exited with status 1:
    '/usr/tce/bin/python3.7' '-c' 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'

  File "/usr/WS1/dahlgren/releases/spack/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 549, in install
    install_specs(zip(abstract_specs, concrete_specs), install_kwargs, args)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 270, in install_specs
    install_specs_outside_environment(specs, install_kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 346, in install_specs_outside_environment
    builder.install()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1757, in install
    self._install_task(task)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1291, in _install_task
    pkg, build_process, install_args
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py", line 1205, in start_build_process
    p.start()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py", line 1070, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 2088, in build_process
    return installer.run()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1950, in run
    self._real_install()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 2049, in _real_install
    phase_fn.execute()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/builder.py", line 426, in execute
    callback(self.builder)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_systems/_checks.py", line 117, in execute_install_time_tests
    builder.pkg.run_test_callbacks(builder, builder.install_time_test_callbacks, "install")
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/package_base.py", line 2647, in run_test_callbacks
    fn()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/builder.py", line 315, in _adapter
    return bind_method()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_systems/python.py", line 171, in test
    work_dir="spack-test",
==> [2022-11-08-13:24:03.351269] ('RUN-TESTS: method not implemented [test]',)
```
