### ISSUE TITLE
Failed `spack spec` command reports ''Package 'bin' not found"

### ISSUE THREAD

**Issue by jrwrigh** [LLNL/spack#32138]
### Steps to reproduce

I've been able to reproduce on with different combinations of packages, but it specifically fails when I prescribe a package dependency. So of the form `spack spec packageA ^packageB`

```console
$ spack spec cmake ^libuv       
==> Error: Package 'bin' not found.
You may need to run 'spack clean -m'.
```

I've also seen it report out `Package 'defaults' not found`. I have run the suggested `spack clean -m`, but it has no effect. This is being done with a clean clone at ALCF's Theta machine. The only thing I've done was add ALCF's upstream and run `spack compiler find`.

I reported this on the Slack thread: https://spackpm.slack.com/archives/C5W7NKZJT/p1660315192704689. I'm now making into a full issue as @becker33 says:
> I’m guessing there’s some bit of config that’s messed up and playing badly with a bug in our error messages. 

### Error message

```console
$ spack --debug --stacktrace spec cgns ^cmake                                                      
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-14-16:49:01.243305] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-14-16:49:01.244553] Imported spec from built-in commands
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.262575] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.296198] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.316145] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/upstreams.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.326244] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:389 ==> [2022-08-14-16:49:01.349296] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-08-14-16:49:01.435990] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:626 ==> [2022-08-14-16:49:01.436306] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:637 ==> [2022-08-14-16:49:01.436974] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:638 ==> [2022-08-14-16:49:01.437250] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:637 ==> [2022-08-14-16:49:01.437526] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/jrwrigh/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:638 ==> [2022-08-14-16:49:01.437791] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/jrwrigh/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.443971] Reading config file /home/jrwrigh/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:763 ==> [2022-08-14-16:49:01.492392] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:522 ==> [2022-08-14-16:49:01.492677] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:01.493303] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:02.031080] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:107 ==> [2022-08-14-16:49:02.197734] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /dzhvhynye4z7oalowdcy5zt25lej3m2n" provides the "clingo" Python module
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:02.198488] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:02.206149] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:02.252383] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:02.282060] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/executable.py:197 ==> [2022-08-14-16:49:02.932764] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
lib/spack/spack/platforms/cray.py:158 ==> [2022-08-14-16:49:02.941121] using front-end architecture or available ancestor
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:05.534060] Reading config file /home/jrwrigh/.spack/cray/compilers.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-14-16:49:05.867846] Reading config file /lus/swift/home/jrwrigh/.local/src/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.064258] build(cgns)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.064578] build(cmake)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.064825] build(hdf5)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.065090] build(ncurses)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.065351] build(openssl)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.065611] build(ca-certificates-mozilla)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.065871] build(perl)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.066129] build(pkgconf)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.066388] build(berkeley-db)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.066648] build(gdbm)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.066906] build(readline)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.067203] build(diffutils)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.067463] build(bzip2)
lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.067697] build(libiconv)
lib/spack/spack/spec.py:2843 ==> [2022-08-14-16:49:25.080355] Ordered hashes [openssl]: openssl/38/3fdcf2d1e47c34f3a012f23306322c5a35cad55b180c9b6fb34537b55884645c
lib/spack/spack/spec.py:2843 ==> [2022-08-14-16:49:25.082021] Ordered hashes [berkeley-db]: berkeley-db/147/b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522
lib/spack/spack/main.py:964 ==> [2022-08-14-16:49:25.795252] UnknownPackageError: Package 'bin' not found.
    You may need to run 'spack clean -m'.
lib/spack/spack/error.py:54 ==> [2022-08-14-16:49:25.798883] Error: Package 'bin' not found.
You may need to run 'spack clean -m'.
Traceback (most recent call last):
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/spec.py", line 2924, in concretize
    self._new_concretize(tests)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/spec.py", line 2899, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/solver/asp.py", line 2290, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/solver/asp.py", line 619, in solve
    setup.setup(self, specs, reuse=reuse)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/solver/asp.py", line 1836, in setup
    check_packages_exist(specs)
  File "/lus/swift/home/jrwrigh/.local/src/spack/lib/spack/spack/solver/asp.py", line 326, in check_packages_exist
    raise spack.repo.UnknownPackageError(str(s.fullname))
spack.repo.UnknownPackageError: Package 'bin' not found.
    You may need to run 'spack clean -m'.
```

### Information on your system

```console
$  spack debug report
* **Spack:** 0.19.0.dev0 (8c23545a3abd7ea69d73d4a36397df07a44d1959)
* **Python:** 3.6.12
* **Platform:** cray-sles15-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jrwrigh** [comment]
Update: This appears to be a environment issue. The above behavior is observed for my custom zsh environment on theta, _but_ not for a "clean" zsh environment (starting it via `zsh -l -f`). 

The only difference between the environment variables (reported by `env`) is the following:
```diff
❯ diff zsh_norcs_env zsh_normal_env
126c126
< MACHTYPE=x86_64
---
> MACHTYPE=x86_64-suse-linux
146c146
< OSTYPE=linux-musl
---
> OSTYPE=linux
368c368
< SHLVL=3
---
> SHLVL=2
```

I'm not sure if it's expected that these few changes would actually affect how spack runs.

**Comment by jrwrigh** [comment]
Comparing `spack --debug --stacktrace spec cgns ^cmake` output between the two environments doesn't reveal any differences other than the `lib/spack/spack/solver/asp.py:2130 ==> [2022-08-14-16:49:25.064258] build(PACKAGENAME)` output being in a different order.

Also, it's now complaining that:
```
==> Error: Package '1' not found.
You may need to run 'spack clean -m'.
```
