### ISSUE TITLE
Occasional odd (erronous?) environment concretization

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#32193]
### Steps to reproduce

Very infrequently in our CI jobs, the environment concretizes to an odd result. I don't have a reproducer yet, the final concrete environment is here: [bad-spack-env.zip](https://github.com/spack/spack/files/9353243/bad-spack-env.zip).
Roughly speaking, this environment is generated from the following running in a `registry.opensuse.org/opensuse/leap:15`-based container:
```console
$ spack mirror add base s3://spack-binaries/hpctoolkit  # Does not exist
$ spack mirror add tmp-pr s3://spack-binaries-prs/pr31598_hpctoolkit-stack  # Temporary buildcache from https://github.com/spack/spack/pull/31598
$ spack mirror add develop s3://spack-binaries/develop  # Spack public buildcache
$ spack -e /env concretize --reuse
```

This environment is then loaded into a clean container (and fresh Spack) and instantiated with
```console
$ spack -e /env install --only-concrete --no-check-signature
```

### Error message

1. There are somehow `ca-certificates-mozilla` packages in this environment:
    ```console
    $ spack -e /env find -ldfv ca-certificates-mozilla
    ... snip ...
    ==> 2 installed packages
    -- linux-opensuse_leap15-x86_64_v3 / gcc@7.5.0 ------------------
    eyhm24w ca-certificates-mozilla@2022-03-29%gcc 
    s664mns ca-certificates-mozilla@2022-07-19%gcc
    ```
    This environment has `concretizer:unify: true` and only `/s664mns` is in the buildcache.

2. There are two `xz` packages, seemingly identical but with different hashes. This seems to cause Spack to "lose" one unless the concrete environment is active:
    ```console
    $ spack find -ldfvm xz
    ==> 1 installed package
    -- linux-opensuse_leap15-x86_64_v3 / gcc@7.5.0 ------------------
    q7mz3cc xz@5.2.5%gcc +pic libs=shared,static
    
    $ cd spack/opt/spack/linux-opensuse_leap15-x86_64_v3/gcc-7.5.0/
    $ ls -d xz-*
    xz-5.2.5-q7mz3ccvuryqjccv4uspgych3ssoj67m  xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml
    $ diff -sr xz-5.2.5-q7mz3ccvuryqjccv4uspgych3ssoj67m/.spack/spec.json xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml/.spack/spec.json 
    33c33
    <         "hash": "q7mz3ccvuryqjccv4uspgych3ssoj67m"
    ---
    >         "hash": "qbnxrmgfvmo35ycn4zskmy35a2yde4ml"
    $ diff -sr xz-5.2.5-q7mz3ccvuryqjccv4uspgych3ssoj67m/.spack/repos xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml/.spack/repos     
    Files xz-5.2.5-q7mz3ccvuryqjccv4uspgych3ssoj67m/.spack/repos/builtin/packages/xz/package.py and xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml/.spack/repos/builtin/packages/xz/package.py are identical
    Files xz-5.2.5-q7mz3ccvuryqjccv4uspgych3ssoj67m/.spack/repos/builtin/repo.yaml and xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml/.spack/repos/builtin/repo.yaml are identical
    
    $ rm -r xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml/
    $ spack reindex
    ==> Warning: xz@5.2.5%gcc@7.5.0+pic libs=shared,static arch=linux-opensuse_leap15-x86_64_v3/qbnxrmg is being registered in the database with prefix /root/spack/opt/spack/linux-opensuse_leap15-x86_64_v3/gcc-7.5.0/xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml, but this directory does not contain an installation of the spec, due to: Install prefix /root/spack/opt/spack/linux-opensuse_leap15-x86_64_v3/gcc-7.5.0/xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml does not exist.
    $ spack -e /env/ install --only-concrete
    ...
    ==> Installing xz-5.2.5-qbnxrmgfvmo35ycn4zskmy35a2yde4ml
    ```

### Information on your system

* **Spack:** 0.19.0.dev0 (928dfd6e758a9d967251d71260456d57ee5b7ca9)
* **Python:** 3.6.15
* **Platform:** linux-opensuse_leap15-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by blue42u** [comment]
I think this is also related, apparently sometimes the "tainted" hash can cause CI to fail at the very end:
```
==> [2022-08-18-17:29:24.313808] Creating buildcache (unsigned)
==> [2022-08-18-17:29:25.017510] MatchError: errors occurred when looking for specs in the store
    "xz@5.2.5%gcc@7.5.0+pic libs=shared,static arch=linux-opensuse_leap15-x86_64_v3" does not match any installed packages
==> [2022-08-18-17:29:25.017632] Error: errors occurred when looking for specs in the store
"xz@5.2.5%gcc@7.5.0+pic libs=shared,static arch=linux-opensuse_leap15-x86_64_v3" does not match any installed packages
Traceback (most recent call last):
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/cmd/ci.py", line 665, in ci
    return args.func(args)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/cmd/ci.py", line 591, in ci_rebuild
    env, job_spec_json_path, buildcache_mirror_url, sign_binaries==> [2022-08-18-17:25:00.567182] SPACK_BUILDCACHE_DESTINATION=None
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/ci.py", line 1609, in push_mirror_contents
    raise inst
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/ci.py", line 1591, in push_mirror_contents
    _push_mirror_contents(env, specfile_path, sign_binaries, mirror_url)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/ci.py", line 1569, in _push_mirror_contents
    matches = spack.store.specfile_matches(specfile_path, hashes=hashes)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/store.py", line 352, in specfile_matches
    return spack.store.find(query, **kwargs)
  File "/builds/hpctoolkit/hpctoolkit/.spack/lib/spack/spack/store.py", line 335, in find
    long_message="\n".join(errors),
spack.store.MatchError: errors occurred when looking for specs in the store
    "xz@5.2.5%gcc@7.5.0+pic libs=shared,static arch=linux-opensuse_leap15-x86_64_v3" does not match any installed packages
```

**Comment by blue42u** [comment]
After some more experimentation, I was able to build something of a reproducer for issue (2). Apparently the spec is not re-hashed when loading JSON, so if the hash changes it is possible to install identical packages with different hashes, one of which gets "lost":
```console
$ cat /tmp/x/spack.yaml 
spack:
  specs:
  - xz
$ spack -e /tmp/x concretize
==> Starting concretization
==> Environment concretized in 0.53 seconds.
==> Concretized xz
 -   lv3qhls  xz@5.2.5%gcc@9.4.0~pic libs=shared,static arch=linux-ubuntu20.04-zen2

$ patch -p1 -d /opt/spack <<'EOF'
diff --git a/lib/spack/spack/spec.py b/lib/spack/spack/spec.py
index 8a463c2f78..36beffd5a5 100644
--- a/lib/spack/spack/spec.py
+++ b/lib/spack/spack/spec.py
@@ -1788,6 +1788,7 @@ def spec_hash(self, hash):
             return hash.override(self)
         node_dict = self.to_node_dict(hash=hash)
         json_text = sjson.dump(node_dict)
+        json_text += 'CHANGE!'
         return spack.util.hash.b32_hash(json_text)
 
     def _cached_hash(self, hash, length=None, force=False):
EOF
patching file lib/spack/spack/spec.py
$ spack install xz
==> Installing xz-5.2.5-vbexgvfdbatfg6j4r2san23tce45vjoi
==> No binary for xz-5.2.5-vbexgvfdbatfg6j4r2san23tce45vjoi found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/51/5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df.tar.bz2
==> No patches needed for xz
==> xz: Executing phase: 'autoreconf'
==> xz: Executing phase: 'configure'
==> xz: Executing phase: 'build'
==> xz: Executing phase: 'install'
==> xz: Successfully installed xz-5.2.5-vbexgvfdbatfg6j4r2san23tce45vjoi
  Fetch: 0.43s.  Build: 8.10s.  Total: 8.52s.
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/xz-5.2.5-vbexgvfdbatfg6j4r2san23tce45vjoi
$ spack -e /tmp/x install
==> Installing environment /tmp/x
==> Installing xz-5.2.5-lv3qhlscezrjc7yfao45l6u47cczclfk
==> No binary for xz-5.2.5-lv3qhlscezrjc7yfao45l6u47cczclfk found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/51/5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df.tar.bz2
==> No patches needed for xz
==> xz: Executing phase: 'autoreconf'
==> xz: Executing phase: 'configure'
==> xz: Executing phase: 'build'
==> xz: Executing phase: 'install'
==> xz: Successfully installed xz-5.2.5-lv3qhlscezrjc7yfao45l6u47cczclfk
  Fetch: 0.00s.  Build: 8.52s.  Total: 8.52s.
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/xz-5.2.5-lv3qhlscezrjc7yfao45l6u47cczclfk
==> Updating view at /tmp/x/.spack-env/view
$ spack find -ldfvm
==> 1 installed package
-- linux-ubuntu20.04-zen2 / gcc@9.4.0 ---------------------------
vbexgvf xz@5.2.5%gcc ~pic libs=shared,static

$ grep '"hash":' /opt/spack/opt/spack/.spack-db/index.json 
          "hash": "vbexgvfdbatfg6j4r2san23tce45vjoi"
          "hash": "lv3qhlscezrjc7yfao45l6u47cczclfk"
```

If these packages are pushed to a binary mirror, the index has the similar strangeness of having duplicate packages with different hashes:
```console
$ spack -e /tmp/x buildcache create --mirror-url file:///tmp/output -au
==> Pushing binary packages to file:///tmp/output/build_cache
$ spack buildcache create --mirror-url file:///tmp/output -au xz
==> Pushing binary packages to file:///tmp/output/build_cache
$ spack buildcache update-index -d file:///tmp/output
$ grep '"hash"' /tmp/output/build_cache/index.json
          "hash": "lv3qhlscezrjc7yfao45l6u47cczclfk"
          "hash": "vbexgvfdbatfg6j4r2san23tce45vjoi"
```
