### ISSUE TITLE
Naked asserts in asp.py lead to blank error messages

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#32225]
### Steps to reproduce

There are a handful of naked asserts in `asp.py` that can lead to no concretization error messages for users if they are hit.
We should make sure all assertions have an associated message and/or prefer raising exceptions.

```console
spack solve nalu-wind@ec06c188b54f4b9211c65f96f49aff5b04213152+boost+openfast dev_path=/projects/wind/spack-manager/environments/exawind/snapshots/linux-rhel7-sandybridge/2022-08-15/nalu-wind arch=linux-None-x86_64 ^/avs7fvr
==> Error: 
        nalu-wind@ec06c188b54f4b9211c65f96f49aff5b04213152+boost+openfast dev_path=/projects/wind/spack-manager/environments/exawind/snapshots/linux-rhel7-sandybridge/2022-08-15/nalu-wind arch=linux-None-x86_64 ^cmake@3.23.1%clang@12.0.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-x86_64 ^ncurses@6.2%clang@12.0.1~symlinks+termlib abi=none arch=linux-rhel7-x86_64 ^openssl@1.1.1n%clang@12.0.1~docs~shared certs=system arch=linux-rhel7-x86_64 ^zlib@1.2.12%clang@12.0.1+optimize+pic+shared patches=0d38234 arch=linux-rhel7-x86_64 is unsatisfiable, errors are:

```

https://github.com/spack/spack/blob/d8689b50389cca69495ef2600c9e97c6f47a49c8/lib/spack/spack/solver/asp.py#L2229

### Error message

```
==> [2022-08-18-07:50:47.535041] InternalConcretizerError: 
        nalu-wind@ec06c188b54f4b9211c65f96f49aff5b04213152+boost+openfast dev_path=/projects/wind/spack-manager/environments/exawind/snapshots/linux-rhel7-sandybridge/2022-08-15/nalu-wind ^cmake@3.23.1%clang@12.0.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-x86_64 ^ncurses@6.2%clang@12.0.1~symlinks+termlib abi=none arch=linux-rhel7-x86_64 ^openssl@1.1.1n%clang@12.0.1~docs~shared certs=system arch=linux-rhel7-x86_64 ^zlib@1.2.12%clang@12.0.1+optimize+pic+shared patches=0d38234 arch=linux-rhel7-x86_64 is unsatisfiable, errors are:

==> [2022-08-18-07:50:47.535153] Error: 
        nalu-wind@ec06c188b54f4b9211c65f96f49aff5b04213152+boost+openfast dev_path=/projects/wind/spack-manager/environments/exawind/snapshots/linux-rhel7-sandybridge/2022-08-15/nalu-wind ^cmake@3.23.1%clang@12.0.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-x86_64 ^ncurses@6.2%clang@12.0.1~symlinks+termlib abi=none arch=linux-rhel7-x86_64 ^openssl@1.1.1n%clang@12.0.1~docs~shared certs=system arch=linux-rhel7-x86_64 ^zlib@1.2.12%clang@12.0.1+optimize+pic+shared patches=0d38234 arch=linux-rhel7-x86_64 is unsatisfiable, errors are:

Traceback (most recent call last):
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 937, in finish_parse_and_run
    _profile_wrapper(command, parser, args, unknown)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 718, in _profile_wrapper
    return _invoke_command(command, parser, args, unknown_args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/cmd/solve.py", line 192, in solve
    _process_result(result, show, required_format, kwargs)
  File "/projects/wind/spack-manager/spack/lib/spack/spack/cmd/solve.py", line 99, in _process_result
    result.raise_if_unsat()
  File "/projects/wind/spack-manager/spack/lib/spack/spack/solver/asp.py", line 453, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: 
        nalu-wind@ec06c188b54f4b9211c65f96f49aff5b04213152+boost+openfast dev_path=/projects/wind/spack-manager/environments/exawind/snapshots/linux-rhel7-sandybridge/2022-08-15/nalu-wind ^cmake@3.23.1%clang@12.0.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-x86_64 ^ncurses@6.2%clang@12.0.1~symlinks+termlib abi=none arch=linux-rhel7-x86_64 ^openssl@1.1.1n%clang@12.0.1~docs~shared certs=system arch=linux-rhel7-x86_64 ^zlib@1.2.12%clang@12.0.1+optimize+pic+shared patches=0d38234 arch=linux-rhel7-x86_64 is unsatisfiable, errors are:
 
```
There is no error message at all.

### Information on your system

* **Spack:** 0.19.0.dev0 (e8cce0f7cbaa3ecf0b72fcce81d595df67580782)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by psakievich** [comment]
#32237 addresses this issue.  It did not solve the exact error of this case, but still going to close for now. I can't reproduce this on any other machine and I don't have time to track it down on the production machine where the error is occurring. This error is not stopping me from building what I needed to build.
