### ISSUE TITLE
Permission denied while concretizing environment

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#32242]
### Steps to reproduce

```console
$ cd /tmp/x
$ cat spack.yaml
spack:
  specs: [zlib]
  config:
    install_tree:
      root: /somewhere/without/write/permissions
$ spack -e . concretize
==> Starting concretization
==> Error: [Errno 13] Permission denied: '/somewhere'
```

### Error message

```console
$ spack -e . --debug --stacktrace concretize
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.280197] Reading config file <<SPACK>>/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.291317] Reading config file <<HOME>>/.spack/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.293690] Reading config file <<SPACK>>/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.297262] Reading config file /tmp/x/spack.yaml
lib/spack/spack/environment/environment.py:173 ==> [2022-08-18-11:18:11.298548] Using environment '/tmp/x'
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-18-11:18:11.299178] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-18-11:18:11.299575] Imported concretize from built-in commands
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.317219] Reading config file <<SPACK>>/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/environment/environment.py:197 ==> [2022-08-18-11:18:11.320957] Deactivated environment '/tmp/x'
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.323707] Reading config file <<SPACK>>/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.334045] Reading config file <<HOME>>/.spack/config.yaml
lib/spack/spack/database.py:389 ==> [2022-08-18-11:18:11.334817] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-08-18-11:18:11.334932] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.335250] Reading config file <<SPACK>>/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:389 ==> [2022-08-18-11:18:11.338996] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-08-18-11:18:11.339118] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:626 ==> [2022-08-18-11:18:11.339228] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:637 ==> [2022-08-18-11:18:11.339514] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=<<SPACK>>/etc/spack/defaults
lib/spack/spack/bootstrap.py:638 ==> [2022-08-18-11:18:11.339620] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=<<SPACK>>/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:637 ==> [2022-08-18-11:18:11.339715] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=<<HOME>>/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:638 ==> [2022-08-18-11:18:11.339799] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=<<HOME>>/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.340566] Reading config file <<HOME>>/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:763 ==> [2022-08-18-11:18:11.363098] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:522 ==> [2022-08-18-11:18:11.363190] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.363665] Reading config file <<SPACK>>/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.373938] Reading config file <<HOME>>/.spack/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.375541] Reading config file /tmp/x/spack.yaml
lib/spack/spack/environment/environment.py:173 ==> [2022-08-18-11:18:11.376758] Using environment '/tmp/x'
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.377434] Reading config file <<SPACK>>/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.447874] Reading config file <<HOME>>/.spack/linux/compilers.yaml
lib/spack/spack/environment/environment.py:1307 ==> [2022-08-18-11:18:11.466387] Starting concretization
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.476241] Reading config file <<SPACK>>/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-18-11:18:11.537482] Reading config file <<SPACK>>/etc/spack/defaults/bootstrap.yaml
Traceback (most recent call last):
  File "<<SPACK>>/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "<<SPACK>>/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "<<SPACK>>/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "<<SPACK>>/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "<<SPACK>>/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "<<SPACK>>/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "<<SPACK>>/lib/spack/spack/environment/environment.py", line 1180, in concretize
    return self._concretize_separately(tests=tests)
  File "<<SPACK>>/lib/spack/spack/environment/environment.py", line 1309, in _concretize_separately
    concretized_root_specs = spack.util.parallel.parallel_map(
  File "<<SPACK>>/lib/spack/spack/util/parallel.py", line 135, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "<<SPACK>>/lib/spack/spack/util/parallel.py", line 83, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=257710] Traceback (most recent call last):
  File "<<SPACK>>/lib/spack/spack/util/parallel.py", line 55, in __call__
    value = self.func(*args, **kwargs)
  File "<<SPACK>>/lib/spack/spack/environment/environment.py", line 2184, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "<<SPACK>>/lib/spack/spack/environment/environment.py", line 2160, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "<<SPACK>>/lib/spack/spack/spec.py", line 3008, in concretized
    clone.concretize(tests=tests)
  File "<<SPACK>>/lib/spack/spack/spec.py", line 2924, in concretize
    self._new_concretize(tests)
  File "<<SPACK>>/lib/spack/spack/spec.py", line 2899, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "<<SPACK>>/lib/spack/spack/solver/asp.py", line 2313, in solve
    reusable_specs.extend(self._reusable_specs())
  File "<<SPACK>>/lib/spack/spack/solver/asp.py", line 2271, in _reusable_specs
    with spack.store.db.read_transaction():
  File "<<SPACK>>/lib/spack/llnl/util/lang.py", line 840, in __getattr__
    return getattr(self.ref_function(), name)
  File "<<SPACK>>/lib/spack/spack/store.py", line 225, in _store_db
    return store.db
  File "<<SPACK>>/lib/spack/llnl/util/lang.py", line 810, in __getattr__
    return getattr(self.instance, name)
  File "<<SPACK>>/lib/spack/llnl/util/lang.py", line 800, in instance
    self._instance = self.factory()
  File "<<SPACK>>/lib/spack/spack/store.py", line 207, in _store
    return Store(
  File "<<SPACK>>/lib/spack/spack/store.py", line 158, in __init__
    self.db = spack.database.Database(root, upstream_dbs=retrieve_upstream_dbs())
  File "<<SPACK>>/lib/spack/spack/database.py", line 368, in __init__
    fs.mkdirp(self._db_dir)
  File "<<SPACK>>/lib/spack/llnl/util/filesystem.py", line 805, in mkdirp
    raise e
  File "<<SPACK>>/lib/spack/llnl/util/filesystem.py", line 770, in mkdirp
    os.makedirs(path)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/somewhere'
```

### Information on your system

* **Spack:** 0.19.0.dev0 (3d4705ffabe1045a5fca39aa53ad99bdc7ecbdbe)
* **Python:** 3.10.6
* **Platform:** linux-debianunstable-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
What would you expect from the resolution of this bug? We don't need the store to concretize, so we could concretize, but what would you do from there? Or are you just asking for a better error message?

**Comment by blue42u** [comment]
Spack should still concretize the environment, even though it won't be able to install anything. Specifically, I think that means the store should be treated as (almost) read-only for `spack concretize` (and `spack spec`, `spack env`, etc... commands that do not install/remove packages):

 - If the store does not exist, the above commands should not create it.
 - If the store exists from an older version (i.e. needs upgrade/conversion), the upgrade should happen in-memory but failure to write back the updated store should not stop the above commands.
 - If the store exists from the current version, the above commands should not (need to) write back to it.

**Comment by alalazo** [comment]
Sure, I agree with that, but what is the use of a Spack instance pointing to a non-writeable store? Did it happen by chance?

**Comment by blue42u** [comment]
The scenario I ran into is when developing/debugging using the [cloud pipeline environments](https://github.com/spack/spack/tree/develop/share/spack/gitlab/cloud_pipelines/stacks). These have [`install_tree:` set to a path in `/home`](https://github.com/spack/spack/blob/6958b49c2fef38e801b85d10889bfdadc99d9ed1/share/spack/gitlab/cloud_pipelines/configs/config.yaml#L5) which isn't writable on a normal bare-metal development machine. This bug causes commands like `spack concretize` and `spack ci generate` fall over, which makes debugging those commands trickier to do locally. (And yes, I can just remove the `install_tree:`, but it's a pain trying to make sure I don't accidentally commit that one line among tens or hundreds of other changes.)

There are probably other use cases too, e.g. sharing a Spack environment + installed software between multiple users on a shared machine without upstreams.
