### ISSUE TITLE
Installation issue: py-python-dateutil

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#32318]
### Steps to reproduce the issue

The error originally occurred when I tried to build the new py-ghp-import (see #32316 ).

```console
$ spack install py-python-dateutil@2.8.2
...
```

### Error message

<details><summary>Error message</summary><pre>
...
==> Installing py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss
==> No binary for py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss found: installing from source
==> Using cached archive: /usr/WS1/dahlgren/releases/spack/var/spack/cache/_source-cache/archive/01/0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86.tar.gz
==> No patches needed for py-python-dateutil
==> py-python-dateutil: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/usr/tce/bin/python3.7' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss' '.'

2 errors found in build log:
     11    Created temporary directory: /tmp/dahlgren/pip-install-kdmpp6nn
     12    Processing /tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src
     13      Added file:///tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src to build tracker '/tmp/dahlgren/pip-build-tracker-s_t4d44j'
     14      Created temporary directory: /tmp/dahlgren/pip-modern-metadata-8criqzb3
     15      Preparing metadata (pyproject.toml): started
     16      Running command Preparing metadata (pyproject.toml)
  \>\> 17    setup.py:18: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
     18        if LooseVersion(setuptools.__version__) <= LooseVersion("24.3"):
     19      Traceback (most recent call last):
     20        File "/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
     21          main()
     22        File "/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
     23          json_out['return_val'] = hook(**hook_input['kwargs'])
     ...
     62      ╰─> See above for output.
     63    
     64      note: This error originates from a subprocess, and is likely not a
                65      full command: /usr/tce/packages/python/python-3.7.2/bin/python3 /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/tmp/dahlgren/tmpvp1q5o3u
     66      cwd: /tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-2.8.
           2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src
     67      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 68    error: metadata-generation-failed
     69    
     70    × Encountered error while generating package metadata.
     71    ╰─> See above for output.
     72    
     73    note: This is an issue with the package mentioned above, not pip.
     74    hint: See above for details.
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (e29a8eb0ace276a222cb57e388b9a2b8f7a8482c)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/9397824/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9397825/spack-build-out.txt)

@adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I think the error message we care about here is:
```
  pkg_resources.VersionConflict: (packaging 17.1 (/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-packaging-17.1-dvtqkhw64kssdzm7fsb4wpmgzzarv3tq/lib/python3.7/site-packages/packaging-17.1-py3.7.egg), Requirement.parse('packaging>=20.0'))
```
But this is confusing because:

1. python-dateutil doesn't depend on packaging
2. packaging is an external package

Can you try the following patch?
```diff
diff --git a/var/spack/repos/builtin/packages/py-pip/package.py b/var/spack/repos/builtin/packages/py-pip/package.py
index 9dfe764414..5068719a77 100644
--- a/var/spack/repos/builtin/packages/py-pip/package.py
+++ b/var/spack/repos/builtin/packages/py-pip/package.py
@@ -95,6 +95,7 @@ def install(self, spec, prefix):
 
     def setup_dependent_package(self, module, dependent_spec):
         pip = self.spec["python"].command
+        pip.add_default_arg("-s")
         pip.add_default_arg("-m")
         pip.add_default_arg("pip")
         setattr(module, "pip", pip)
```

**Comment by tldahlgren** [comment]
> I think the error message we care about here is:
> 
> ```
>   pkg_resources.VersionConflict: (packaging 17.1 (/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-packaging-17.1-dvtqkhw64kssdzm7fsb4wpmgzzarv3tq/lib/python3.7/site-packages/packaging-17.1-py3.7.egg), Requirement.parse('packaging>=20.0'))
> ```
> 
> But this is confusing because:
> 
> 1. python-dateutil doesn't depend on packaging
> 2. packaging is an external package
> 
> Can you try the following patch?
> 
> ```diff
> diff --git a/var/spack/repos/builtin/packages/py-pip/package.py b/var/spack/repos/builtin/packages/py-pip/package.py
> index 9dfe764414..5068719a77 100644
> --- a/var/spack/repos/builtin/packages/py-pip/package.py
> +++ b/var/spack/repos/builtin/packages/py-pip/package.py
> @@ -95,6 +95,7 @@ def install(self, spec, prefix):
>  
>      def setup_dependent_package(self, module, dependent_spec):
>          pip = self.spec["python"].command
> +        pip.add_default_arg("-s")
>          pip.add_default_arg("-m")
>          pip.add_default_arg("pip")
>          setattr(module, "pip", pip)
> ```

Sure.  Still getting the same errors with the patch.

**Comment by adamjstewart** [comment]
Then I'm stumped. I'm not sure if there's a way to get an external Python to ignore the packages installed in its own site-packages directory, and I'm not sure why pip thinks that `packaging>=20.0` is required to install python-dateutil. We're even using `pip install --no-deps` which _should_ cause pip to ignore dependency requirements altogether. Maybe @pradyunsg can advise on the pip side of things.

**Comment by adamjstewart** [comment]
Wondering if this is related to #29308
