### ISSUE TITLE
Windows: `cache_local` fails when git filesys monitor is running

### ISSUE THREAD

**Issue by KiruyaMomochi** [LLNL/spack#32404]
When playing with spack on Windows, `stage.cache_local` is always failing for packages involving git, due to the directory cannot be renamed.
After checking system file handles, I found the root cause.
The reason is that I have enabled [file system monitor](https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/) globally.

This monitor creates a long running [daemon](https://git-scm.com/docs/git-fsmonitor--daemon) to watch a single working directory and maintain a list of the recently changed files and directories.
After killing this daemon process, rename works successfully.

### Steps to reproduce

1. Enable Git [file system monitor](https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/) globally.
    ```powershell
    git config --global core.fsmonitor true
    ```
2. Install a package that
    - doesn't exist in cache
    - it's source code is fetched from a Git commit
3. It fails to install.

### Error message

`アクセスが拒否されました。` = `Access denied.`
`Searching for libraries xxx in xxx` is added by me.

```log
\lib\spack\spack\util\executable.py:197 ==> [2022-08-27-03:48:44.731128] 'C:\Program Files\Git\cmd\git.exe' '-C' 'C:\ProgramFiles_Portable\spack' 'rev-parse' 'HEAD'
['C:\\ProgramFiles_Portable\\spack\\lib\\spack\\external', 'C:\\ProgramFiles_Portable\\spack\\lib\\spack', 'C:\\Users\\kyaru\\.spack\\bootstrap\\store\\windows-windows10-AMD64\\msvc-19.34.31721\\clingo-bootstrap-spack-ndxj5x7piuc2eyamspv3tvlrr75jexkj\\Lib\\site-packages', 'C:\\Users\\kyaru\\.spack\\bootstrap\\store\\windows-windows10-AMD64\\msvc-19.34.31721\\clingo-bootstrap-spack-ndxj5x7piuc2eyamspv3tvlrr75jexkj\\Lib\\site-packages', 'C:\\ProgramFiles_Portable\\spack\\lib\\spack\\external', 'C:\\ProgramFiles_Portable\\spack\\lib\\spack', 'C:\\ProgramFiles_Portable\\spack/bin', 'C:\\ProgramFiles_Portable\\spack\\lib\\spack\\external', 'C:\\ProgramFiles_Portable\\spack\\lib\\spack', 'C:\\ProgramFiles_Portable\\spack\\bin', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310', 'C:\\Users\\kyaru\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32\\lib', 'C:\\Users\\kyaru\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\Pythonwin']
==> Searching for libraries ninja in C:\ProgramData\chocolatey\
==> Searching for libraries ninja in C:\ProgramData\chocolatey\
==> Searching for libraries python in C:\Users\kyaru\AppData\Local\Programs\Python\Python310
==> Searching for libraries python in C:\Users\kyaru\AppData\Local\Programs\Python\Python310
==> Searching for libraries python in C:\Users\kyaru\AppData\Local\Programs\Python\Python310
Cloning into 'clingo'...
remote: Enumerating objects: 14432, done.
remote: Counting objects: 100% (936/936), done.
remote: Compressing objects: 100% (484/484), done.
remote: Total 14432 (delta 512), reused 764 (delta 434), pack-reused 13496
Receiving objects: 100% (14432/14432), 8.89 MiB | 4.86 MiB/s, done.
Resolving deltas: 100% (9387/9387), done.
Updating files: 100% (961/961), done.
HEAD is now at b87dddc workaround for VS2022 build failures
Submodule 'clasp' (https://github.com/potassco/clasp.git) registered for path 'clasp'
Cloning into 'C:/ProgramFiles_Portable/spack/.staging/xa0082249956/spack-stage-clingo-bootstrap-spack-l2imgpyvl3mbohgflka3nyljhmpalhym/spack-src/clasp'...
Submodule path 'clasp': checked out 'b089aa1509511ab403c0b9abd0d13eb9e873af44'
Submodule 'libpotassco' (https://github.com/potassco/libpotassco.git) registered for path 'clasp/libpotassco'
Cloning into 'C:/ProgramFiles_Portable/spack/.staging/xa0082249956/spack-stage-clingo-bootstrap-spack-l2imgpyvl3mbohgflka3nyljhmpalhym/spack-src/clasp/libpotassco'...
Submodule path 'clasp/libpotassco': checked out '2f9fb7ca2c202f1b47643aa414054f2f4f9c1821'
\lib\spack\spack\error.py:54 ==> [2022-08-27-03:51:01.530016] Error: PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\ProgramFiles_Portable\\spack\\.staging\\xa0082249956\\spack-stage-clingo-          -bootstrap-spack-l2imgpyvl3mbohgflka3nyljhmpalhym\\spack-src\\.git\\modules\\clasp\\modules\\libpotassco\\objects\\pack\\pack-279a9ba4edd6ba3e3fa44acb719fb1c5a66d97c5.idx'

C:\ProgramFiles_Portable\spack\lib\spack\spack\package_base.py:1532, in do_fetch:
       1529
       1530        if checksum and self.version in self.versions:
       1531            self.stage.check()
  >>   1532
       1533        self.stage.cache_local()
       1534
       1535        for patch in self.spec.patches:
```

<details>
<summary>Traceback</summary>

```log
Traceback (most recent call last):
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\build_environment.py", line 1059, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\installer.py", line 2008, in build_process
    return installer.run()
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\installer.py", line 1845, in run
    self.pkg.do_patch()
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\package_base.py", line 1563, in do_patch
    self.do_stage()
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\package_base.py", line 1548, in do_stage
    self.do_fetch(mirror_only)
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\package_base.py", line 1533, in do_fetch
    self.stage.cache_local()
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\util\pattern.py", line 18, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\util\pattern.py", line 18, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\stage.py", line 587, in cache_local
    spack.caches.fetch_cache.store(self.fetcher, self.mirror_paths.storage_path)
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\fetch_strategy.py", line 1724, in store
    fetcher.archive(dst)
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\fetch_strategy.py", line 1017, in archive
    super(GitFetchStrategy, self).archive(destination, exclude=".git")
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\fetch_strategy.py", line 87, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramFiles_Portable\spack\lib\spack\spack\fetch_strategy.py", line 692, in archive
    with temp_rename(self.stage.source_path, self.stage.srcdir):
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\ProgramFiles_Portable\spack\lib\spack\llnl\util\filesystem.py", line 1016, in temp_rename
    shutil.move(orig_path, temp_path)
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 833, in move
    rmtree(src)
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 4 more times]
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\kyaru\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] アクセスが拒否されました。: '<path to staging dir>\\spack-stage-clingo-spack-gf56s5zgv3nfhjmbe3x27dwdwb2jhaan\\spack-src\\.git\\modules\\clasp\\modules\\libpotassco\\objects\\pack\\pack-279a9ba4edd6ba3e3fa44acb719fb1c5a66d97c5.idx'
```

</details>

### Information on your system

* **Spack:** 0.19.0.dev0 (b31cd189a712fe9499e0b9f8f5863797517038d0)
* **Python:** 3.10.5
* **Platform:** windows-windows10-AMD64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by KiruyaMomochi** [comment]
Pinging @scheibelp as mentioned in Slack.
