### ISSUE TITLE
Unable to create bootstrap mirror

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#32431]
### Steps to reproduce

```
spack bootstrap untrust github-actions-v0.2
spack bootstrap untrust github-actions-v0.1
spack -L -ddd bootstrap mirror --binary-packages $(pwd)/opt/boostrap
```

### Error message

```
==> [2022-08-29-21:24:10.961632, 14439] UnsatisfiableSpecError: Cannot find valid provider for virtual iconv
==> [2022-08-29-21:24:10.961816, 14439] Error: Cannot find valid provider for virtual iconv
Traceback (most recent call last):
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/cmd/bootstrap.py", line 452, in bootstrap
    callbacks[args.subcommand](args)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/cmd/bootstrap.py", line 395, in _mirror
    spec = spack.spec.Spec(spec_str).concretized()
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/spec.py", line 3013, in concretized
    clone.concretize(tests=tests)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/solver/asp.py", line 2306, in solve
    setup_only=setup_only,
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/solver/asp.py", line 681, in solve
    answers = builder.build_specs(tuples)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/solver/asp.py", line 2155, in build_specs
    action(*args)
  File "/build/razumov/18-spack-bootstrap/spack/lib/spack/spack/solver/asp.py", line 1981, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: Cannot find valid provider for virtual iconv
```

Full output: https://gist.github.com/iarspider/f853581cdff483be2845c8cc4b82972c

### Information on your system

* **Spack:** 0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
> Cannot find valid provider for virtual iconv

This usually happens after virtual packages are added/removed/renamed and can be solved by `spack clean -m` to purge the virtual provider cache. Can you try that and see if the issue still exists? Hopefully we can find a way to automatically update this cache.

**Comment by alalazo** [comment]
Cannot reproduce on:

* **Spack:** 0.20.0.dev0 (bfa54da2929a6dfea14e04eca036b9409a5aa68b)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-05-11 09-53-07](https://github.com/spack/spack/assets/4199709/47b9efb4-554d-474d-8310-b6846e60a094)
