### ISSUE TITLE
spack checksum does not consider url_for_version

### ISSUE THREAD

**Issue by carsonwoods** [LLNL/spack#32554]
### Steps to reproduce

I was recently modifying the `intel-mpi-benchmarks` package to support both new and older versions of the package which were not included previously. Some older versions of the package have a different URL version format when compared against recent releases. As part of this, it was suggested that I replace the `version()` + custom URL with the `url_for_version()` function. I did so, and removed the standard `URL = "..."` line. The package functions as it should, but I wanted to run the checksum command (like as follows) to ensure the checksums for the new version were correct.
```console
$ spack checksum intel-mpi-benchmarks
==> Error: Could not find any versions for intel-mpi-benchmarks
```
This led to Spack not reporting that ANY versions were available. When I added the URL line back to the package, the `for_url_version()` function still worked as specified on older versions, but the checksum command worked again (though only for versions which matched the `URL = "..."` format. 

It seems like the `spack checksum` command is not evaluating version URL's based on the `url_for_version()` function. 

### Error message

```console
$ spack --debug --stacktrace checksum intel-mpi-benchmarks
lib/spack/spack/cmd/__init__.py:124 ==> [2022-09-07-10:56:00.144027] Imported checksum from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-09-07-10:56:00.144494] Imported checksum from built-in commands
lib/spack/spack/config.py:1010 ==> [2022-09-07-10:56:00.145272] Reading config from file /Users/carsonwoods/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146246] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/defaults/darwin/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146338] Skipping nonexistent config path /etc/spack/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146413] Skipping nonexistent config path /etc/spack/darwin/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146484] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146555] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/darwin/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146625] Skipping nonexistent config path /Users/carsonwoods/.spack/repos.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.146833] Skipping nonexistent config path /Users/carsonwoods/.spack/darwin/repos.yaml
lib/spack/spack/cmd/checksum.py:104 ==> [2022-09-07-10:56:00.171235] Error: Could not find any versions for intel-mpi-benchmarks
lib/spack/spack/config.py:1010 ==> [2022-09-07-10:56:00.171628] Reading config from file /Users/carsonwoods/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179667] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/defaults/darwin/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179757] Skipping nonexistent config path /etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179814] Skipping nonexistent config path /etc/spack/darwin/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179870] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179923] Skipping nonexistent config path /Users/carsonwoods/spack/etc/spack/darwin/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.179976] Skipping nonexistent config path /Users/carsonwoods/.spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-09-07-10:56:00.180029] Skipping nonexistent config path /Users/carsonwoods/.spack/darwin/config.yaml
Traceback (most recent call last):
  File "/Users/carsonwoods/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/Users/carsonwoods/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/carsonwoods/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/carsonwoods/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/Users/carsonwoods/spack/lib/spack/spack/cmd/checksum.py", line 104, in checksum
    tty.die("Could not find any versions for {0}".format(pkg.name))
  File "/Users/carsonwoods/spack/lib/spack/llnl/util/tty/__init__.py", line 256, in die
    sys.exit(1)
```

### Information on your system

* **Spack:** 0.19.0.dev0 (0c12709e5baf1f3e5c888ad18784cb45edffcf8e)
* **Python:** 3.10.6
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

This bug was found in my branch where I was modifying the intel-mpi-benchmarks package, but can be reproduced on develop using any package which has a `url_for_version` function. Simply remove the `URL = "..."` line in that package, then run `spack checksum` on that package. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Yes, `spack versions` and `spack checksum` are a completely different code path from `spack fetch` and `spack install`. This isn't really a bug, just a feature that does not yet exist. The way that `spack versions` and `spack checksum` work is that they look at the `url`, chop off the last part, and search in that location for things that look like files with a name similar to that last bit. This doesn't really work with `url_for_version` which requires you to instantiate the package at a specific version and ask the function which version to search for. It's kind of a chicken and egg problem, you can't use `url_for_version` to compute the URL for a version until after you find the version, so how would you use `url_for_version` to find new versions?

One idea would be to run `url_for_version` for all existing versions to get a list of URL formats and then look in all of those locations. But this would be significantly slower, and I don't think there's an easy way to tell whether or not the function was defined in the base class or overridden in the package. Another option would be to use `urls = [new_url, old_url]` so that Spack can search in both locations.
