### ISSUE TITLE
spack style bootstrapping issues

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#32693]
### Steps to reproduce

```console
$ spack style --fix
==> Running style checks on spack
  selected: isort, mypy, black, flake8
==> Modified files
  var/spack/repos/builtin/packages/py-matplotlib/package.py
==> Error: cannot bootstrap any of the black executables from spec "py-black@:21 %apple-clang target=aarch64" due to the following failures:
github-actions-v0.3 raised NoHeadersError: Unable to locate python headers in any of these locations:
    /Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/python3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/Headers
github-actions-v0.2 raised ValueError: source is not trusted
github-actions-v0.1 raised ValueError: source is not trusted
spack-install raised NoHeadersError: Unable to locate python headers in any of these locations:
    /Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/python3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/Headers
Run `spack --debug ...` for more detailed errors
```
Why can't it find the headers in `/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg`? Because this directory doesn't exist. The correct directory is `/Users/ajstewart/.spack/.spack-env/._view/kqcdhmsfq4y5vhculfimz3omzcwjikqw`. I'm not sure where it's getting the incorrect hash from. `spack clean -a` and `spack reindex` didn't help. `SPACK_PYTHON` is correct and should work fine:
```console
$ echo $SPACK_PYTHON
/Users/ajstewart/.spack/.spack-env/view/bin/python3
$ ls -l /Users/ajstewart/.spack/.spack-env/view/bin/python3
lrwxr-x---  1 ajstewart  staff  88 Sep  3 15:51 /Users/ajstewart/.spack/.spack-env/view/bin/python3 -> /Users/ajstewart/.spack/.spack-env/._view/kqcdhmsfq4y5vhculfimz3omzcwjikqw/bin/python3.9
$ /Users/ajstewart/.spack/.spack-env/view/bin/python3 -m sysconfig | grep h6oacudblohwssd5psvvagvxucromykg
$
```

### Error message

```console
$ spack --debug style --fix
Traceback (most recent call last):
  File "/Users/ajstewart/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 977, in main
    return _main(argv)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 932, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 960, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ajstewart/spack/lib/spack/spack/main.py", line 609, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ajstewart/spack/lib/spack/spack/cmd/style.py", line 452, in style
    commands[tool_name] = bootstrap_fn()
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 883, in ensure_black_in_path_or_raise
    return ensure_executables_in_path_or_raise(["black"], root_spec, check_black)
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 614, in ensure_executables_in_path_or_raise
    raise RuntimeError(msg)
RuntimeError: cannot bootstrap any of the black executables from spec "py-black@:21 %apple-clang target=aarch64" due to the following failures:
github-actions-v0.3 raised NoHeadersError: Unable to locate python headers in any of these locations:
    /Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/python3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/Headers
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 595, in ensure_executables_in_path_or_raise
    spack.user_environment.environment_modifications_for_spec(
  File "/Users/ajstewart/spack/lib/spack/spack/user_environment.py", line 99, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/Users/ajstewart/spack/var/spack/repos/builtin/packages/python/package.py", line 1201, in setup_run_environment
  File "/Users/ajstewart/spack/lib/spack/spack/spec.py", line 1098, in __get__
    value = f()
  File "/Users/ajstewart/spack/lib/spack/spack/spec.py", line 1087, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/Users/ajstewart/spack/var/spack/repos/builtin/packages/python/package.py", line 1115, in headers
    "Unable to locate {} headers in any of these locations:".format(self.name),

github-actions-v0.2 raised ValueError: source is not trusted
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 584, in ensure_executables_in_path_or_raise
    source_is_enabled_or_raise(current_config)
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 464, in source_is_enabled_or_raise
    raise ValueError("source is not trusted")

github-actions-v0.1 raised ValueError: source is not trusted
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 584, in ensure_executables_in_path_or_raise
    source_is_enabled_or_raise(current_config)
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 464, in source_is_enabled_or_raise
    raise ValueError("source is not trusted")

spack-install raised NoHeadersError: Unable to locate python headers in any of these locations:
    /Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/python3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/include/3.9
/Users/ajstewart/.spack/.spack-env/._view/h6oacudblohwssd5psvvagvxucromykg/Headers
  File "/Users/ajstewart/spack/lib/spack/spack/bootstrap.py", line 595, in ensure_executables_in_path_or_raise
    spack.user_environment.environment_modifications_for_spec(
  File "/Users/ajstewart/spack/lib/spack/spack/user_environment.py", line 99, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/Users/ajstewart/spack/var/spack/repos/builtin/packages/python/package.py", line 1201, in setup_run_environment
  File "/Users/ajstewart/spack/lib/spack/spack/spec.py", line 1098, in __get__
    value = f()
  File "/Users/ajstewart/spack/lib/spack/spack/spec.py", line 1087, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/Users/ajstewart/spack/var/spack/repos/builtin/packages/python/package.py", line 1115, in headers
    "Unable to locate {} headers in any of these locations:".format(self.name),
```
Can we also fix these red herring github-actions-v0.X errors? They're just confusing.

### Information on your system

* **Spack:** 0.19.0.dev0 (9e0755ca3a125f6360ea84223630a05363536101)
* **Python:** 3.9.13
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I also started seeing this sometimes ago, but didn't have time to look into it yet. I suspect it's the same as #31265 nowadays (though the failure for bootstrapping `isort` etc. have been multiple, and changed over time).

**Comment by alalazo** [comment]
I think #34029 would solve this. Can you confirm?

**Comment by adamjstewart** [comment]
Will test that out. Note that I'm also seeing an issue with mypy that I reported on Slack:
```console
$ spack style -t mypy
==> Running style checks on spack
  selected: mypy
==> Modified files
==> Running mypy checks
../.spack/.spack-env/view/lib/python3.10/site-packages/numpy/__init__.pyi:638: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
  mypy found errors
==> Error: spack style found errors
```
This was a bug present in older mypy for newer Python (https://github.com/python/mypy/issues/13627), but the version of mypy I'm using should not have that issue. Will also see if your PR fixes that problem too.

**Comment by adamjstewart** [comment]
I wasn't able to reproduce my original issue, so I would be fine with closing this regardless of #34029. However, I'm still seeing the mypy issue above. Let me know if I should open a separate issue for that.

**Comment by alalazo** [comment]
@adamjstewart Apologies for the late reply, going through notifications list today. Let's close this issue, and eventually open a new one if you have a reproducer for https://github.com/spack/spack/issues/32693#issuecomment-1332564092

**Comment by tgamblin** [comment]
resurrecting this one as I'm going to submit a proposed fix and some more details.

**Comment by alalazo** [comment]
@tgamblin Is this one fixed? For what is worth I can bootstrap correctly using:
```console
$ spack bootstrap now --dev
```

* **Spack:** 0.20.0.dev0 (a7b2196eab54de4bb248f1706a1a69fbd1a9758f)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

**Comment by tgamblin** [comment]
I don't think this is fixed until we can bootstrap gracefully without `make` installed in a container.  I think that still gets us into a very broken state.

**Comment by alalazo** [comment]
> I don't think this is fixed until we can bootstrap gracefully without make installed in a container. I think that still gets us into a very broken state.

Sure, was thinking that issue is tracked here https://github.com/spack/spack/issues/35214
