### ISSUE TITLE
Spack caches not updated automatically after git pull

### ISSUE THREAD

**Issue by tbugfinder** [LLNL/spack#32799]
### Steps to reproduce

```console
 ./spack -d install amber
```

### Error message

```console
==> [2022-09-23-20:24:34.801603] Reading config file /home/hpcuser1/spack/etc/spack/defaults/mirrors.yaml
==> [2022-09-23-20:24:37.373507] Reading config file /home/hpcuser1/.spack/linux/compilers.yaml
==> [2022-09-23-20:24:37.378895] Reading config file /home/hpcuser1/spack/etc/spack/defaults/packages.yaml
==> [2022-09-23-20:24:46.492549] SpackError: Cannot find valid provider for virtual pkgconfig
==> [2022-09-23-20:24:46.492681] SpackError: Cannot find valid provider for virtual pkgconfig
==> [2022-09-23-20:24:46.492714] Error: Cannot find valid provider for virtual pkgconfig
Traceback (most recent call last):
  File "/home/hpcuser1/spack/lib/spack/spack/cmd/__init__.py", line 222, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/hpcuser1/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/home/hpcuser1/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/home/hpcuser1/spack/lib/spack/spack/solver/asp.py", line 2306, in solve
    setup_only=setup_only,
  File "/home/hpcuser1/spack/lib/spack/spack/solver/asp.py", line 681, in solve
    answers = builder.build_specs(tuples)
  File "/home/hpcuser1/spack/lib/spack/spack/solver/asp.py", line 2155, in build_specs
    action(*args)
  File "/home/hpcuser1/spack/lib/spack/spack/solver/asp.py", line 1981, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: Cannot find valid provider for virtual pkgconfig

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hpcuser1/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/hpcuser1/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/hpcuser1/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/hpcuser1/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/hpcuser1/spack/lib/spack/spack/cmd/install.py", line 389, in install
    specs = spack.cmd.parse_specs(args.spec, concretize=True, tests=tests)
  File "/home/hpcuser1/spack/lib/spack/spack/cmd/__init__.py", line 236, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Cannot find valid provider for virtual pkgconfig
2022-09-23 20:24:47 hpc0517:bin hpcuser1$
```

### Information on your system

Rocky Linux 8.6
I don't have issues in running it on our Scientific Linux 7.9.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by dipietrantonio** [comment]
I have encountered this issue too, is there a way around it?

**Comment by adamjstewart** [comment]
This usually happens after virtual packages are added/removed/renamed and can be solved by spack clean -m to purge the virtual provider cache. Can you try that and see if the issue still exists? Hopefully we can find a way to automatically update this cache.

**Comment by alalazo** [comment]
@tbugfinder ?

**Comment by tbugfinder** [comment]
Will check, not yet forgotten 🤓

**Comment by dipietrantonio** [comment]
Works for me, thanks.
