### ISSUE TITLE
Multiple extendees error

### ISSUE THREAD

**Issue by salotz-sitx** [LLNL/spack#33040]
### Steps to reproduce

I've been having problems installing and generating specs for certain packages in the current configuration of local packages and those in my build cache. So I think it will be pretty difficult to reproduce and I'm not sure that the particular package here is at fault.

```console
$ spack spec py-importlib-metadata
==> Error: Class constructor failed for package 'builtin.py-importlib-metadata'.

Caused by:
AssertionError: 
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1

```

I had similar errors (with different python packages) recently that were solved simply by providing different variants in the build cache.

I've done some extensive debugging and found that somehow the python spec is added twice to the list of dependencies (I am not sure if its the same hash, but all the variant flags were the same).
I've tracked it down to the point where the second python is introduced when a dependency of `py-importlib-metadata` is added to the spec `py-zipp`, call stack being:

- [SpecBuilder.build_deps](https://github.com/spack/spack/blob/v0.18.0/lib/spack/spack/solver/asp.py#L2152)
- [SpecBuilder.depends_on](https://github.com/spack/spack/blob/v0.18.0/lib/spack/spack/solver/asp.py#L2044).
- [add_dependency_edge](https://github.com/spack/spack/blob/v0.18.0/lib/spack/spack/spec.py#L1476)

I lost the flow of logic in [Spec.add](https://github.com/spack/spack/blob/v0.18.0/lib/spack/spack/spec.py#L820-L829) though as there is some weird state manipulation going on somewhere in there..

Any ideas or tips on maybe identifying why this is getting added? This really seems like a bug in the concretizer and `--reuse` because if I run with `--fresh` it runs successfully, but ignores my build cache and so isn't a viable workaround.

### Error message

```console
$ spack --debug --stacktrace spec py-importlib-metadata

lib/spack/spack/cmd/__init__.py:123 ==> [2022-10-06-00:04:58.803082] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-10-06-00:04:58.804060] Imported spec from built-in commands
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.806376] Reading config file /home/salotz/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.820714] Reading config file /home/salotz/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.830225] Reading config file /home/salotz/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:382 ==> [2022-10-06-00:04:58.842938] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:386 ==> [2022-10-06-00:04:58.843082] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.843505] Reading config file /home/salotz/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:382 ==> [2022-10-06-00:04:58.847859] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:386 ==> [2022-10-06-00:04:58.847998] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:613 ==> [2022-10-06-00:04:58.848137] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:629 ==> [2022-10-06-00:04:58.848511] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/salotz/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:630 ==> [2022-10-06-00:04:58.848623] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/salotz/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:629 ==> [2022-10-06-00:04:58.848737] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/salotz/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:630 ==> [2022-10-06-00:04:58.848842] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/salotz/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.849401] Reading config file /home/salotz/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:769 ==> [2022-10-06-00:04:58.866211] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap.py:522 ==> [2022-10-06-00:04:58.866371] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.866657] Reading config file /home/salotz/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:58.997357] Reading config file /home/salotz/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:96 ==> [2022-10-06-00:04:59.053634] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /shqedxgvjnhiwdcdrvjhbd73jaevv7wt" provides the "clingo" Python module
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.054014] Reading config file /home/salotz/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.057663] Reading config file /home/salotz/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.059109] Reading config file /home/salotz/.spack/repos.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.134044] Reading config file /home/salotz/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.147078] Reading config file /home/salotz/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:04:59.148180] Reading config file /home/salotz/.spack/mirrors.yaml
lib/spack/spack/util/gcs.py:62 ==> [2022-10-06-00:05:00.746007] New GCS bucket:
lib/spack/spack/util/gcs.py:63 ==> [2022-10-06-00:05:00.746368]     name: rvd_spack-cache_testing
lib/spack/spack/util/gcs.py:64 ==> [2022-10-06-00:05:00.746597]     prefix: build_cache/index.json
lib/spack/spack/util/gcs.py:169 ==> [2022-10-06-00:05:00.746851] New GCSBlob
lib/spack/spack/util/gcs.py:170 ==> [2022-10-06-00:05:00.747086]   blob_path = build_cache/index.json
lib/spack/spack/util/web.py:81 ==> [2022-10-06-00:05:01.181793] (uses_ssl) GCS Blob is https
lib/spack/spack/util/gcs.py:62 ==> [2022-10-06-00:05:02.564239] New GCS bucket:
lib/spack/spack/util/gcs.py:63 ==> [2022-10-06-00:05:02.564569]     name: rvd_spack-cache_testing
lib/spack/spack/util/gcs.py:64 ==> [2022-10-06-00:05:02.564794]     prefix: build_cache/index.json.hash
lib/spack/spack/util/gcs.py:169 ==> [2022-10-06-00:05:02.565016] New GCSBlob
lib/spack/spack/util/gcs.py:170 ==> [2022-10-06-00:05:02.565222]   blob_path = build_cache/index.json.hash
lib/spack/spack/binary_distribution.py:437 ==> [2022-10-06-00:05:03.247761] Cached index for gs://rvd_spack-cache_testing/ already up to date
lib/spack/spack/util/gcs.py:62 ==> [2022-10-06-00:05:04.603889] New GCS bucket:
lib/spack/spack/util/gcs.py:63 ==> [2022-10-06-00:05:04.604207]     name: rvd_spack-source-mirror_testing
lib/spack/spack/util/gcs.py:64 ==> [2022-10-06-00:05:04.604425]     prefix: build_cache/index.json
lib/spack/spack/util/gcs.py:169 ==> [2022-10-06-00:05:04.604647] New GCSBlob
lib/spack/spack/util/gcs.py:170 ==> [2022-10-06-00:05:04.604864]   blob_path = build_cache/index.json
lib/spack/spack/database.py:382 ==> [2022-10-06-00:05:05.521297] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:386 ==> [2022-10-06-00:05:05.521878] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:05:07.232791] Reading config file /home/salotz/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:05:07.237300] Reading config file /home/salotz/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1017 ==> [2022-10-06-00:05:07.258395] Reading config file /home/salotz/.spack/packages.yaml
lib/spack/spack/solver/asp.py:2133 ==> [2022-10-06-00:05:12.802075] build(py-importlib-metadata)
lib/spack/spack/repo.py:1136 ==> [2022-10-06-00:05:12.895021] AssertionError: 
Traceback (most recent call last):
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1
AssertionError
lib/spack/spack/main.py:896 ==> [2022-10-06-00:05:12.896342] FailedConstructorError: Class constructor failed for package 'builtin.py-importlib-metadata'.
    
Caused by:
AssertionError: 
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1

lib/spack/spack/error.py:54 ==> [2022-10-06-00:05:12.896590] Error: Class constructor failed for package 'builtin.py-importlib-metadata'.

Caused by:
AssertionError: 
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1

Traceback (most recent call last):
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salotz/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/salotz/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/salotz/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/salotz/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/salotz/spack/lib/spack/spack/cmd/spec.py", line 83, in spec
    specs = [(s, s.concretized()) for s in input_specs]
  File "/home/salotz/spack/lib/spack/spack/cmd/spec.py", line 83, in <listcomp>
    specs = [(s, s.concretized()) for s in input_specs]
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 3013, in concretized
    clone.concretize(tests=tests)
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 2929, in concretize
    self._new_concretize(tests)
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 2903, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/home/salotz/spack/lib/spack/spack/solver/asp.py", line 2295, in solve
    return self.driver.solve(
  File "/home/salotz/spack/lib/spack/spack/solver/asp.py", line 680, in solve
    answers = builder.build_specs(tuples)
  File "/home/salotz/spack/lib/spack/spack/solver/asp.py", line 2182, in build_specs
    root._finalize_concretization()
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 2986, in _finalize_concretization
    spec._cached_hash(ht.package_hash, force=True)
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 1805, in _cached_hash
    hash_string = self.spec_hash(hash)
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 1781, in spec_hash
    return hash.override(self)
  File "/home/salotz/spack/lib/spack/spack/hash_types.py", line 57, in <lambda>
    override=lambda s: s.package.content_hash())
  File "/home/salotz/spack/lib/spack/spack/spec.py", line 1515, in package
    self._package = spack.repo.get(self)
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1409, in get
    return path.get(spec)
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 444, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 957, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 444, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1142, in get
    raise FailedConstructorError(spec.fullname, *sys.exc_info())
spack.repo.FailedConstructorError: Class constructor failed for package 'builtin.py-importlib-metadata'.

Caused by:
AssertionError: 
  File "/home/salotz/spack/lib/spack/spack/repo.py", line 1131, in get
    return package_class(spec)
  File "/home/salotz/spack/lib/spack/spack/package.py", line 798, in __init__
    spack.repo.get(self.extendee_spec)._check_extendable()
  File "/home/salotz/spack/lib/spack/spack/package.py", line 1350, in extendee_spec
    assert len(deps) == 1

```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.8.14
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Investigate if this might also be related to #987

**Comment by salotz-sitx** [comment]
@alalazo It might be under the hood, but I don't think any of these packages are extending multiple extendees.
