### ISSUE TITLE
Concretizer not handling BuildCache recipes in namespaces not defined locally

### ISSUE THREAD

**Issue by greenc-FNAL** [LLNL/spack#33227]
### Steps to reproduce

1. Build a package from a recipe in a non-builtin repo.
2. Upload it to a BuildCache mirror.
3. In a clean Spack instance, configure access to the BuildCache mirror but *not* the non-builtin repo.
4. Attempt to do anything involving the concretizer (`spack stage`, _etc._)

### Error message

Stack trace:
```
==> [2022-10-11-16:37:56.513250] UnknownNamespaceError: Unknown namespace: scd_recipes
==> [2022-10-11-16:37:56.513301] Error: Unknown namespace: scd_recipes
Traceback (most recent call last):
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/main.py", line 995, in main
    return _main(argv)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/main.py", line 950, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/main.py", line 978, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/main.py", line 622, in _invoke_command
    return_val = command(parser, args)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/cmd/stage.py", line 59, in stage
    spec = spack.cmd.matching_spec_from_env(spec)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/cmd/__init__.py", line 254, in matching_spec_from_env
    return spec.concretized()
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/spec.py", line 3050, in concretized
    clone.concretize(tests=tests)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/spec.py", line 2966, in concretize
    self._new_concretize(tests)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/spec.py", line 2941, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/solver/asp.py", line 2392, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/solver/asp.py", line 707, in solve
    answers = builder.build_specs(tuples)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/solver/asp.py", line 2263, in build_specs
    spack.spec.Spec.inject_patches_variant(root)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/spec.py", line 2854, in inject_patches_variant
    pkg_deps = dspec.parent.package_class.dependencies
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/spec.py", line 1548, in package_class
    return spack.repo.path.get_pkg_class(self.fullname)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/repo.py", line 981, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/home/greenc/work/cet-is/sources/Spack/spack/lib/spack/spack/repo.py", line 960, in repo_for_pkg
    raise UnknownNamespaceError(namespace, name=name)
spack.repo.UnknownNamespaceError: Unknown namespace: scd_recipes
```

### Information on your system

[greenc@scisoftbuild01] spack (fnal-develop) (ups) (spack) $ spack debug report
* **Spack:** 0.19.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-scientific7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by gartung** [comment]
@tgamblin @alalazo How would one add the `.spack/repos/repo-name/repo.yaml` to the namespace resolution?

**Comment by gartung** [comment]
My work around has been to always have all of the repos used to create a buildcache defined in the in the spack directory where the installation would be done.

**Comment by alalazo** [comment]
Duplicate of #35790

**Comment by gartung** [comment]
Technically this was reported first so https://github.com/spack/spack/issues/35790 is the duplicate.

**Comment by alalazo** [comment]
In my mind "duplicate of" is commutative - it's just a way to ensure they'll both be closed when we get a fix.
