### ISSUE TITLE
`spack load` errors out if home is not writable or doesn't exist

### ISSUE THREAD

**Issue by giordano** [LLNL/spack#33265]
### Steps to reproduce

On [ARCHER2](https://www.archer2.ac.uk/), UK Tier-1 system, the `home` directory is [not accessible from compute nodes](https://docs.archer2.ac.uk/user-guide/data/#archer2-storage).  Trying to run `spack load` results in an error which makes a job fail:
```console
$ spack -d load --sh sombrero@2021-08-16
==> [2022-10-12-20:19:41.523402] Reading config from file /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/config.yaml
==> [2022-10-12-20:19:41.574805] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/cray/config.yaml
==> [2022-10-12-20:19:41.574858] Skipping nonexistent config path /etc/spack/config.yaml
==> [2022-10-12-20:19:41.574893] Skipping nonexistent config path /etc/spack/cray/config.yaml
==> [2022-10-12-20:19:41.575035] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/config.yaml
==> [2022-10-12-20:19:41.575087] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/cray/config.yaml
==> [2022-10-12-20:19:41.575123] Skipping nonexistent config path /home/d193/d193/giordano/.spack/config.yaml
==> [2022-10-12-20:19:41.575153] Skipping nonexistent config path /home/d193/d193/giordano/.spack/cray/config.yaml
==> [2022-10-12-20:19:41.736786] Reading config from file /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/concretizer.yaml
==> [2022-10-12-20:19:41.759315] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/cray/concretizer.yaml
==> [2022-10-12-20:19:41.759367] Skipping nonexistent config path /etc/spack/concretizer.yaml
==> [2022-10-12-20:19:41.759401] Skipping nonexistent config path /etc/spack/cray/concretizer.yaml
==> [2022-10-12-20:19:41.759531] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/concretizer.yaml
==> [2022-10-12-20:19:41.759576] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/cray/concretizer.yaml
==> [2022-10-12-20:19:41.759612] Skipping nonexistent config path /home/d193/d193/giordano/.spack/concretizer.yaml
==> [2022-10-12-20:19:41.759642] Skipping nonexistent config path /home/d193/d193/giordano/.spack/cray/concretizer.yaml
==> [2022-10-12-20:19:41.772151] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/upstreams.yaml
==> [2022-10-12-20:19:41.772210] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/cray/upstreams.yaml
==> [2022-10-12-20:19:41.772251] Skipping nonexistent config path /etc/spack/upstreams.yaml
==> [2022-10-12-20:19:41.772289] Skipping nonexistent config path /etc/spack/cray/upstreams.yaml
==> [2022-10-12-20:19:41.772326] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/upstreams.yaml
==> [2022-10-12-20:19:41.772363] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/cray/upstreams.yaml
==> [2022-10-12-20:19:41.772394] Skipping nonexistent config path /home/d193/d193/giordano/.spack/upstreams.yaml
==> [2022-10-12-20:19:41.772425] Skipping nonexistent config path /home/d193/d193/giordano/.spack/cray/upstreams.yaml
==> [2022-10-12-20:19:41.774619] Reading config from file /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/excalibur-tests/stage/archer2/compute-node/default/SombreroBenchmark/spack_env/compute-node/spack.yaml
==> [2022-10-12-20:19:41.911887] Using environment '/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/excalibur-tests/stage/archer2/compute-node/default/SombreroBenchmark/spack_env/compute-node'
==> [2022-10-12-20:19:41.993338] Imported load from built-in commands
==> [2022-10-12-20:19:41.993973] Imported load from built-in commands
==> [2022-10-12-20:19:41.996603] Reading config from file /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-10-12-20:19:42.018080] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/cray/bootstrap.yaml
==> [2022-10-12-20:19:42.018131] Skipping nonexistent config path /etc/spack/bootstrap.yaml
==> [2022-10-12-20:19:42.018165] Skipping nonexistent config path /etc/spack/cray/bootstrap.yaml
==> [2022-10-12-20:19:42.018308] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/bootstrap.yaml
==> [2022-10-12-20:19:42.018352] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/cray/bootstrap.yaml
==> [2022-10-12-20:19:42.018385] Skipping nonexistent config path /home/d193/d193/giordano/.spack/bootstrap.yaml
==> [2022-10-12-20:19:42.018415] Skipping nonexistent config path /home/d193/d193/giordano/.spack/cray/bootstrap.yaml
==> [2022-10-12-20:19:42.019218] DATABASE LOCK TIMEOUT: 3s
==> [2022-10-12-20:19:42.019252] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-10-12-20:19:42.023002] Reading config from file /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/repos.yaml
==> [2022-10-12-20:19:42.043108] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/defaults/cray/repos.yaml
==> [2022-10-12-20:19:42.043158] Skipping nonexistent config path /etc/spack/repos.yaml
==> [2022-10-12-20:19:42.043191] Skipping nonexistent config path /etc/spack/cray/repos.yaml
==> [2022-10-12-20:19:42.043317] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/repos.yaml
==> [2022-10-12-20:19:42.043360] Skipping nonexistent config path /mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/etc/spack/cray/repos.yaml
==> [2022-10-12-20:19:42.043394] Skipping nonexistent config path /home/d193/d193/giordano/.spack/repos.yaml
==> [2022-10-12-20:19:42.043425] Skipping nonexistent config path /home/d193/d193/giordano/.spack/cray/repos.yaml
Traceback (most recent call last):
  File "/work/d193/d193/giordano/repo/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/main.py", line 990, in main
    return _main(argv)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/main.py", line 945, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/main.py", line 973, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/main.py", line 622, in _invoke_command
    return_val = command(parser, args)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/cmd/load.py", line 95, in load
    for spec in spack.cmd.parse_specs(args.constraint)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/cmd/load.py", line 95, in <listcomp>
    for spec in spack.cmd.parse_specs(args.constraint)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/cmd/__init__.py", line 270, in disambiguate_spec
    return disambiguate_spec_from_hashes(spec, hashes, local, installed, first)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/cmd/__init__.py", line 287, in disambiguate_spec_from_hashes
    matching_specs = spack.store.db.query(spec, hashes=hashes, installed=installed)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/database.py", line 1550, in query
    local_results = set(self.query_local(*args, **kwargs))
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/database.py", line 1535, in query_local
    return self._query(*args, **kwargs)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/database.py", line 1518, in _query
    if query_spec is any or rec.spec.satisfies(query_spec, strict=True):
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/spec.py", line 3653, in satisfies
    if not self.virtual and other.virtual:
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/spec.py", line 1551, in virtual
    return spack.repo.path.is_virtual(self.name)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 1021, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 901, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 1227, in provider_index
    return self.index["providers"]
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 731, in __getitem__
    self._build_all_indexes()
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 746, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/repo.py", line 755, in _build_index
    index_mtime = self.cache.mtime(cache_filename)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/llnl/util/lang.py", line 810, in __getattr__
    return getattr(self.instance, name)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/llnl/util/lang.py", line 800, in instance
    self._instance = self.factory()
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/caches.py", line 33, in _misc_cache
    return spack.util.file_cache.FileCache(path)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/spack/util/file_cache.py", line 41, in __init__
    mkdirp(self.root)
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/llnl/util/filesystem.py", line 883, in mkdirp
    raise e
  File "/mnt/lustre/a2fs-work3/work/d193/d193/giordano/repo/spack/lib/spack/llnl/util/filesystem.py", line 848, in mkdirp
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/d193'
```
It appears `spack load` internally tries to create a directory in the home causing a failure which is not handled gently.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.19.0.dev0 (8537220b0e5f7e3c2eb2dee2633bf488236fb651)
* **Python:** 3.6.12
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by welucas2** [comment]
If you set these environment variables then Spack will look for and create new YAML configs and cache items in the directories chosen, rather than in your home directory. On ARCHER2, I run the following, which just use a `.spack` directory in my own work directory (note `${HOME/home/work}` resolves as the path to your home directory with 'home' replaced by 'work'):

```bash
export SPACK_USER_CONFIG_PATH=${HOME/home/work}/.spack
export SPACK_USER_CACHE_PATH=${HOME/home/work}/.spack
```

You can set the location to whatever makes sense, such as a shared project directory if you wanted to share Spack with others on your project.

**Comment by giordano** [comment]
@welucas2 this work around gets me going, thanks a lot!  But I still think Spack should handle this more gently, without erroring out badly, so I'll keep the issue open.
