### ISSUE TITLE
Unable to use `target=a64fx` on HPE Apollo 80

### ISSUE THREAD

**Issue by rj-jesus** [LLNL/spack#33432]
I'm unable to specify `target=a64fx` on an HPE Apollo 80 system (see below), which leads to unoptimised builds of most packages.

```
$ spack --debug spec -Il gcc target=a64fx
...
==> [2022-10-20-10:02:50.681833] SpackError: No versions available for package 'gcc'
==> [2022-10-20-10:02:50.682099] Error: No versions available for package 'gcc'
Traceback (most recent call last):
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/spec.py", line 2967, in concretize
    self._new_concretize(tests)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/spec.py", line 2942, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/solver/asp.py", line 2381, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/solver/asp.py", line 706, in solve
    answers = builder.build_specs(tuples)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/solver/asp.py", line 2233, in build_specs
    action(*args)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/solver/asp.py", line 2067, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: No versions available for package 'gcc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/snx11273/home/ri-rjj/.local/opt/spack/lib/spack/spack/cmd/__init__.py", line 241, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: No versions available for package 'gcc'
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.19.0.dev0 (23b8a1636270dd9413c1a44eaa1a2cef4957ccb7)
* **Python:** 3.6.8
* **Platform:** cray-rhel8-aarch64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Which compiler are you trying to use?

**Comment by rj-jesus** [comment]
It might be better to close this issue. I was probably using `gcc@11.1.0`, but it's hard to know for sure as this was quite a while ago!

**Comment by alalazo** [comment]
Thanks for the quick reply. I'll close then, but feel free to reopen the issue or submit a new one if you get back to this again!
