### ISSUE TITLE
`--directory` option is broken for `spack buildcache create`

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#33501]
### Steps to reproduce

In version 0.18, spack started demanding a URL for `--directory` options, but it won't accept a URL for `spack buildcache create --directory ...`. It works in version 0.17. `spack buildcache create --mirror-url ...` seems to work.

```console
$ spack install patchelf
$ spack buildcache create --directory mirror patchelf
==> Error: Invalid url format from url: mirror
$ spack buildcache create --directory file://mirror patchelf
==> Error: expected a local path, but got a URL instead
$ spack buildcache create --mirror-url file://mirror patchelf
==> Pushing binary packages to file:///home/andrew/spack/mirror/build_cache
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
```

### Error message

```console
$ spack --debug --stacktrace buildcache create --allow-root --directory mirror patchelf
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-25-10:30:02.104944] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-25-10:30:02.108996] Imported buildcache from built-in commands
lib/spack/spack/config.py:1004 ==> [2022-10-25-10:30:02.110838] Reading config from file /home/andrew/spack/develop/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.131383] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/defaults/linux/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.131621] Skipping nonexistent config path /etc/spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.131826] Skipping nonexistent config path /etc/spack/linux/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.131985] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.132164] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/linux/config.yaml
lib/spack/spack/config.py:1004 ==> [2022-10-25-10:30:02.132341] Reading config from file /home/andrew/.spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:02.132727] Skipping nonexistent config path /home/andrew/.spack/linux/config.yaml
Traceback (most recent call last):
  File "/home/andrew/spack/develop/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 998, in main
    return _main(argv)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 953, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 981, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 630, in _invoke_command
    return_val = command(parser, args)
  File "/home/andrew/spack/develop/lib/spack/spack/cmd/buildcache.py", line 705, in buildcache
    args.func(args)
  File "/home/andrew/spack/develop/lib/spack/spack/cmd/buildcache.py", line 357, in create_fn
    push_url = spack.mirror.push_url_from_directory(args.directory)
  File "/home/andrew/spack/develop/lib/spack/spack/mirror.py", line 686, in push_url_from_directory
    scheme = url_util.parse(output_directory, scheme="<missing>").scheme
  File "/home/andrew/spack/develop/lib/spack/spack/util/url.py", line 86, in parse
    require_url_format(url)
  File "/home/andrew/spack/develop/lib/spack/spack/util/url.py", line 379, in require_url_format
    raise ValueError("Invalid url format from url: %s" % url)
ValueError: Invalid url format from url: mirror
$ spack --debug --stacktrace buildcache create --allow-root --directory file://mirror patchelf
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-25-10:30:55.720562] Imported buildcache from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-25-10:30:55.724609] Imported buildcache from built-in commands
lib/spack/spack/util/path.py:344 ==> [2022-10-25-10:30:55.726394] Using working directory /home/andrew/spack as base for abspath
lib/spack/spack/config.py:1004 ==> [2022-10-25-10:30:55.727805] Reading config from file /home/andrew/spack/develop/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.748459] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/defaults/linux/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.748699] Skipping nonexistent config path /etc/spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.748866] Skipping nonexistent config path /etc/spack/linux/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.749039] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.749215] Skipping nonexistent config path /home/andrew/spack/develop/etc/spack/linux/config.yaml
lib/spack/spack/config.py:1004 ==> [2022-10-25-10:30:55.749363] Reading config from file /home/andrew/.spack/config.yaml
lib/spack/spack/config.py:994 ==> [2022-10-25-10:30:55.749740] Skipping nonexistent config path /home/andrew/.spack/linux/config.yaml
Traceback (most recent call last):
  File "/home/andrew/spack/develop/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 998, in main
    return _main(argv)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 953, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 981, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/andrew/spack/develop/lib/spack/spack/main.py", line 630, in _invoke_command
    return_val = command(parser, args)
  File "/home/andrew/spack/develop/lib/spack/spack/cmd/buildcache.py", line 705, in buildcache
    args.func(args)
  File "/home/andrew/spack/develop/lib/spack/spack/cmd/buildcache.py", line 357, in create_fn
    push_url = spack.mirror.push_url_from_directory(args.directory)
  File "/home/andrew/spack/develop/lib/spack/spack/mirror.py", line 688, in push_url_from_directory
    raise ValueError("expected a local path, but got a URL instead")
ValueError: expected a local path, but got a URL instead
```

### Information on your system

* **Spack:** 0.19.0.dev0 (272767c67fbc52ecee1c7ec07f3d9c1c9bbc71be)
* **Python:** 3.6.15
* **Platform:** linux-opensuse_leap15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed as of:

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-05-03 17-51-04](https://user-images.githubusercontent.com/4199709/235970022-06e3aa0b-6d2a-4179-83d2-745f765405bc.png)
