### ISSUE TITLE
Installation issue: amdlibm build_args missing arguments

### ISSUE THREAD

**Issue by dylex** [LLNL/spack#33756]
I presume this is related to the recent builder introduction #30738.  The old scons builder called `build_args` and `install_args` with `(spec, prefix)` but these were taken out in this change.  If this is intentional, packages need to be fixed.  If not, maybe they can be added back?

```
==> amdlibm: Executing phase: 'build'
Traceback (most recent call last):
  File "/mnt/sw/nix/store/x791w7gixpcfhqs0bdhgq9q33w8z6lvv-builder.py", line 75, in <module>
    spack.installer.build_process(pkg, opts)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 2052, in build_process
    return installer.run()
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 1914, in run
    self._real_install()
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 2013, in _real_install
    phase_fn.execute()
  File "/mnt/sw/nix/store/x791w7gixpcfhqs0bdhgq9q33w8z6lvv-builder.py", line 61, in wrapPhase
    return f(*args)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 423, in execute
    self.phase_fn(pkg, pkg.spec, pkg.prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 299, in _adapter
    return phase_fn(spec, prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 143, in __forward
    return self.__getattr__(fn_name)(*args, **kwargs)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 75, in __call__
    return self.phase_fn(self.builder.pkg, spec, prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/build_systems/scons.py", line 62, in build
    args = self.build_args()
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 315, in _adapter
    return bind_method()
TypeError: build_args() missing 2 required positional arguments: 'spec' and 'prefix'
```

**Comment by zhan4429** [comment]
I got the same error. Any solution yet?

**Comment by dylex** [comment]
It looks like this may have been fixed by #34481.
