### ISSUE TITLE
Installation issue: py-pyqt5 and multiple build systems

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#33806]
### Steps to reproduce the issue

```console
$ spack install py-pyqt5
...
```

### Error message

<details><summary>Error message</summary><pre>
...
The 'py-pyqt5' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo

### Additional information

@alalazo I think this one is for you. I have not quite wrapped my head around the multi build system PR so I am not sure what the fix is for this yet.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by dylex** [comment]
Here's what I'm getting:
```
==> py-pyqt5: Executing phase: 'configure'
Traceback (most recent call last):
  File "/mnt/sw/nix/store/x791w7gixpcfhqs0bdhgq9q33w8z6lvv-builder.py", line 75, in <module>
    spack.installer.build_process(pkg, opts)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 2052, in build_process
    return installer.run()
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 1914, in run
    self._real_install()
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/installer.py", line 2013, in _real_install
    phase_fn.execute()
  File "/mnt/sw/nix/store/x791w7gixpcfhqs0bdhgq9q33w8z6lvv-builder.py", line 61, in wrapPhase
    return f(*args)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 423, in execute
    self.phase_fn(pkg, pkg.spec, pkg.prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 299, in _adapter
    return phase_fn(spec, prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 143, in __forward
    return self.__getattr__(fn_name)(*args, **kwargs)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/builder.py", line 75, in __call__
    return self.phase_fn(self.builder.pkg, spec, prefix)
  File "/mnt/sw/nix/store/ssk4a8y4sp00w8s4x77rgiivr7sdgb98-spack/lib/spack/spack/build_systems/sip.py", line 160, in configure
    self.python(configure, *args)
AttributeError: 'Adapter' object has no attribute 'python'
```
