### ISSUE TITLE
Upstreams using specialized repos fail to concretize

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#33899]
### Steps to reproduce

Recently spack has stopped working with an upstream that we've been using for months.  The upstream has it's own repo called `cde` where some package modifications are done.
Now when we try to concretize we get an `Unknown namespace error`.

```console
spack config add upstreams:fails:install_tree:/upstream/with/custom/repo/spack/opt/spack
spack concretize 
```

### Error message

```console
spack -d concretize
[...]
 UnknownNamespaceError: Unknown namespace: cde
==> [2022-11-14-12:25:58.778921] Error: Unknown namespace: cde
Traceback (most recent call last):
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/environment/environment.py", line 1279, in concretize
    return self._concretize_together(tests=tests)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/environment/environment.py", line 1332, in _concretize_together
    *self.user_specs, tests=tests
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/concretize.py", line 739, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/concretize.py", line 748, in _concretize_specs_together_new
    result = solver.solve(abstract_specs)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 2433, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 627, in solve
    setup.setup(self, specs, reuse=reuse)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 1987, in setup
    self._facts_from_concrete_spec(reusable_spec, possible)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 1895, in _facts_from_concrete_spec
    self.impose(h, spec, body=True)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 1088, in impose
    imposed_constraints = self.spec_clauses(imposed_spec, body=body, required_from=name)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 1311, in spec_clauses
    clauses = self._spec_clauses(*args, **kwargs)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/solver/asp.py", line 1476, in _spec_clauses
    for virtual in dep.package.virtuals_provided:
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/spec.py", line 1639, in package
    self._package = spack.repo.path.get(self)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/repo.py", line 977, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/home/psakiev/soft/spack-manager/spack/lib/spack/spack/repo.py", line 960, in repo_for_pkg
    raise UnknownNamespaceError(namespace, name=name)
spack.repo.UnknownNamespaceError: Unknown namespace: cde
```

### Information on your system

* **Spack:** 0.19.0.dev0 (f92987b11fec53423d777bd6818e12c71810a8d5)
* **Python:** 3.7.5
* **Platform:** linux-rhel7-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by psakievich** [comment]
@becker33 looks like this is due to #32434
