### ISSUE TITLE
`spack -e ... config update config` fails

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#34031]
### Steps to reproduce

```
$ spack env create foo
$ cat var/spack/environments/foo/spack.yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  concretizer:
    unify: true
  config:
    allow_sgid: false
    shared_linking: 'runpath'
    build_stage::
      $spack/stage
    test_stage::
      $spack/test_stage
    misc_cache::
      $spack/cache
```

### Error message

```
$ spack --debug --stacktrace -e foo config update config
==> [2022-11-21-09:04:58.872932] Reading config from file /build/razumov/nightly-spack/spack/etc/spack/defaults/config.yaml
==> [2022-11-21-09:04:58.901488] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/defaults/linux/config.yaml
==> [2022-11-21-09:04:58.901580] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/config.yaml
==> [2022-11-21-09:04:58.901655] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/linux/config.yaml
==> [2022-11-21-09:04:58.911996] Reading config from file /build/razumov/nightly-spack/spack/etc/spack/defaults/concretizer.yaml
==> [2022-11-21-09:04:58.918360] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/defaults/linux/concretizer.yaml
==> [2022-11-21-09:04:58.918448] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/concretizer.yaml
==> [2022-11-21-09:04:58.918511] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/linux/concretizer.yaml
==> [2022-11-21-09:04:58.918804] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/defaults/upstreams.yaml
==> [2022-11-21-09:04:58.918876] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/defaults/linux/upstreams.yaml
==> [2022-11-21-09:04:58.918972] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/upstreams.yaml
==> [2022-11-21-09:04:58.919032] Skipping nonexistent config path /build/razumov/nightly-spack/spack/etc/spack/linux/upstreams.yaml
==> [2022-11-21-09:04:58.921482] Reading config from file /build/razumov/nightly-spack/spack/var/spack/environments/foo/spack.yaml
==> [2022-11-21-09:04:58.926375] Using environment 'foo'
==> [2022-11-21-09:04:58.927960] Imported config from built-in commands
==> [2022-11-21-09:04:58.931308] Imported config from built-in commands
==> [2022-11-21-09:04:58.932292] Error: Detected permission issues with the following scopes:

	[scope=env:foo, cfg=/build/razumov/nightly-spack/spack/var/spack/environments/foo/spack.yaml]

Either ensure that you have sufficient permissions to modify these files or do not include these scopes in the update.
Traceback (most recent call last):
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/cmd/config.py", line 488, in config
    action[args.config_command](args)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/cmd/config.py", line 287, in config_update
    tty.die(msg)
  File "/build/razumov/nightly-spack/spack/lib/spack/llnl/util/tty/__init__.py", line 256, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system

* **Spack:** 0.19.0 (bb8b4f9979e87ae3fb63a3adcb768eda09e5b059)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment]
The failing check is here: https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/config.py#L248
which is due to the fact that `.../foo/spack.yaml` is indeed not a directory.

**Comment by iarspider** [comment]
After adding a simple "fix":
```
--- a/lib/spack/spack/cmd/config.py
+++ b/lib/spack/spack/cmd/config.py
@@ -259,6 +259,9 @@ def config_update(args):
     for scope in updates:
         cfg_file = spack.config.config.get_config_filename(scope.name, args.section)
         scope_dir = scope.path
+        if isinstance(scope, spack.config.SingleFileScope):
+            scope_dir = os.path.dirname(scope.path)
+
         can_be_updated = _can_update_config_file(scope_dir, cfg_file)
         if not can_be_updated:
             if scope.name == "system":
```

the update starts, but quickly fails:
```
$ spack -d config update config
<...>
==> [2022-11-21-10:11:46.319747] Do you want to proceed? [y/N] y
Traceback (most recent call last):
  File "/build/razumov/nightly-spack/spack/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/build/razumov/nightly-spack/spack/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/cmd/config.py", line 492, in config
    action[args.config_command](args)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/cmd/config.py", line 335, in config_update
    spack.config.config.update_config(args.section, data, scope=scope.name, force=True)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/config.py", line 385, in _method
    return method(self, *args, **kwargs)
  File "/build/razumov/nightly-spack/spack/lib/spack/spack/config.py", line 544, in update_config
    setattr(scope.sections[section][section], yaml.comments.Comment.attrib, comments)
AttributeError: 'dict' object has no attribute '_yaml_comment'
```

**Comment by alalazo** [comment]
It seems this one is not an issue anymore?
```yaml
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  concretizer:
    unify: true
  config:
    allow_sgid: false
    shared_linking: 'runpath'
    build_stage::
      $spack/stage
    test_stage::
      $spack/test_stage
    misc_cache::
      $spack/cache
```
I tried, as you posted:
```console
$ spack env create foo /tmp/spack.yaml
$ spack  -e foo config update config
==> No updates needed for "config" section.
```
Maybe the reproducer misses some relevant parts?
