### ISSUE TITLE
(Failed) install on Google Colab

### ISSUE THREAD

**Issue by mgiugliano** [LLNL/spack#34033]
Any success while installing spack on Google Colab?

I had Python 3.7.15, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 

Trying
```
!git clone -c feature.manyFiles=true https://github.com/spack/spack.git
!./spack/bin/spack install zlib
```

unfortunately failed, returning this error message...

```
==> Bootstrapping clingo from pre-built binaries
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-axtxtavfahxuazw2wueu3tjwwu6ttdfo.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-axtxtavfahxuazw2wueu3tjwwu6ttdfo.spack
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
==> Waiting for zlib-1.2.13-k2wwsnrjulc3xn2dxq5halufptvsrewa
==> Installing zlib-1.2.13-k2wwsnrjulc3xn2dxq5halufptvsrewa
==> No binary for zlib-1.2.13-k2wwsnrjulc3xn2dxq5halufptvsrewa found: installing from source
==> Fetching http://zlib.net/fossils/zlib-1.2.13.tar.gz
==> No patches needed for zlib
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/content/spack/lib/spack/llnl/util/tty/log.py", line 938, in _writer_daemon
    with keyboard_input(stdin) as kb:
  File "/content/spack/lib/spack/llnl/util/tty/log.py", line 233, in __enter__
    if not self._is_background():
  File "/content/spack/lib/spack/llnl/util/tty/log.py", line 159, in _is_background
    return _is_background_tty(self.stream)
  File "/content/spack/lib/spack/llnl/util/tty/log.py", line 62, in _is_background_tty
    return stream.isatty() and os.getpgrp() != os.tcgetpgrp(stream.fileno())
OSError: [Errno 25] Inappropriate ioctl for device
==> Error: BrokenPipeError: [Errno 32] Broken pipe
See build log for details:
  /tmp/root/spack-stage/spack-stage-zlib-1.2.13-k2wwsnrjulc3xn2dxq5halufptvsrewa/spack-build-out.txt
```

Note: the build log file indicated above is empty (i.e. 0 bytes)

**Comment by haampie** [comment]
@tgamblin can you maybe look into this? Not only are these foreground/background tests failing half of the time, but they're also causing spack to break in Google Colab for no good reason :|.
