### ISSUE TITLE
Wrong concretization with invalid variants

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#34089]
### Steps to reproduce

```
$ cat spack.yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  packages:
    all:
      variants: [cxxstd=17, build_type=Release, +cms, 'cuda_arch=60,70,75']
    llvm:
      variants: [+bar]
  view: true
  concretizer:
    unify: false
  specs:
  - llvm@12.0.1.cms +cuda

$ spack env create foo spack.yaml
$ spack -e foo concretize
==> Error: A value for cuda_arch must be specified.
```

### Error message

```
Traceback (most recent call last):
  File "/tmp/spack/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/tmp/spack/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/tmp/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/tmp/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/tmp/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/tmp/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/tmp/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/tmp/spack/lib/spack/spack/environment/environment.py", line 1277, in concretize
    return self._concretize_separately(tests=tests)
  File "/tmp/spack/lib/spack/spack/environment/environment.py", line 1402, in _concretize_separately
    _concretize_task, arguments, max_processes=max_processes, debug=tty.is_debug()
  File "/tmp/spack/lib/spack/spack/util/parallel.py", line 135, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "/tmp/spack/lib/spack/spack/util/parallel.py", line 83, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=2646294] Traceback (most recent call last):
  File "/tmp/spack/lib/spack/spack/util/parallel.py", line 55, in __call__
    value = self.func(*args, **kwargs)
  File "/tmp/spack/lib/spack/spack/environment/environment.py", line 2271, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/tmp/spack/lib/spack/spack/environment/environment.py", line 2247, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/tmp/spack/lib/spack/spack/spec.py", line 3025, in concretized
    clone.concretize(tests=tests)
  File "/tmp/spack/lib/spack/spack/spec.py", line 2941, in concretize
    self._new_concretize(tests)
  File "/tmp/spack/lib/spack/spack/spec.py", line 2916, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/tmp/spack/lib/spack/spack/solver/asp.py", line 2433, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/tmp/spack/lib/spack/spack/solver/asp.py", line 703, in solve
    answers = builder.build_specs(tuples)
  File "/tmp/spack/lib/spack/spack/solver/asp.py", line 2280, in build_specs
    action(*args)
  File "/tmp/spack/lib/spack/spack/solver/asp.py", line 2101, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: A value for cuda_arch must be specified.
```

### Information on your system

* **Spack:** 0.19.0 (bb8b4f9979e87ae3fb63a3adcb768eda09e5b059)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment]
I would expect Spack to complain that `bar` is not a valid variant of `llvm`.

In v0.18.1 (13e6f87ef6527954b152eaea303841978e83b992), the concretization did not fail, but chose `cuda_arch=50`.

**Comment by alalazo** [comment]
@iarspider `cuda_arch` is a [sticky variant](https://spack.readthedocs.io/en/latest/packaging_guide.html#sticky-variants), and as such it needs to be explicitly changed by users. I think this is not an issue, since the message is pretty clear:
```
A value for cuda_arch must be specified.
```

**Comment by iarspider** [comment]
@alalazo So a "sticky" variant is not propagated from `packages:all`? That would explain why Spack complains about "cuda_arch", not about missing `bar` variant

**Comment by alalazo** [comment]
I think there's a fundamental misunderstanding. Here you are asking for preferences, which Spack can decide to override. If `+bar` is not there, Spack will not take that into consideration. I didn't try it, but if you use `require` I expect Spack to error out instead.

**Comment by iarspider** [comment]
That makes sense. Thanks!
