### ISSUE TITLE
intel-oneapi-mkl: trying to source non-existing file: vars.sh

### ISSUE THREAD

**Issue by koysean** [LLNL/spack#34196]
### Steps to reproduce

1. Install hypre (or any package with an MKL dependency) using an external installation of intel-oneapi-mkl which does not contain `vars.sh`.
2. Run `spack load hypre`

### Error message

``` console
$ spack load hypre
[...]
lib/spack/spack/util/environment.py:659 ==> [2022-11-29-18:21:11.937721] EnvironmentModifications.from_sourcing_file: /home/skoyama/oneapi/mkl/<version>/env/vars.sh
Traceback (most recent call last):                                                                                                                                                            
  File "/home/skoyama/spack_instances/e4s-oneapi-test/bin/spack", line 54, in <module>                              
    sys.exit(main())                                                                                                                                                                                               
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack_installable/main.py", line 36, in main          
    sys.exit(spack.main.main(argv))                                                                                                                                                                                
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/main.py", line 1000, in main                                                                                                                                           
    return _main(argv)                                                                                                                                                                                             
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/main.py", line 955, in _main                                                                                                                                           
    return finish_parse_and_run(parser, cmd_name, env_format_error)                                                                                                                                                
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/main.py", line 983, in finish_parse_and_run                                                                                                                            
    return _invoke_command(command, parser, args, unknown)                                                          
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/main.py", line 632, in _invoke_command                                                                                                                                 
    return_val = command(parser, args)                            
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/cmd/load.py", line 115, in load                                                                                                                                        
    env_mod.extend(uenv.environment_modifications_for_spec(spec))  
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/user_environment.py", line 99, in environment_modifications_for_spec                                                                                                    
    spec.package.setup_run_environment(env)                                                                                          
  File "/home/skoyama/spack_instances/e4s-oneapi-test/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py", line 123, in setup_run_environment                                                                                       
                                                          
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/build_systems/oneapi.py", line 108, in setup_run_environment
    join_path(self.component_prefix, "env", "vars.sh")    
  File "/home/skoyama/spack_instances/e4s-oneapi-test/lib/spack/spack/util/environment.py", line 663, in from_sourcing_file
    raise RuntimeError(msg)                                       
RuntimeError: Trying to source non-existing file: /home/skoyama/oneapi/mkl/<version>/env/vars.sh         
```

### Information on your system

* **Spack:** 0.20.0.dev0 (61a7420c94d84888a5408bf88f74076dfc1014fe)
* **Python:** 3.6.15
* **Platform:** linux-sles15-icelake
* **Concretizer:** clingo

### Additional Information

Note: Version numbers are replaced by `<version>` due to a CNDA.

This is on a system with a non-standard OneAPI install - the environment is controlled entirely via modules and `vars.sh` doesn't exist. Unfortunately, it seems that the presence of a `vars.sh` file is hardcoded into the `IntelOneApiPackage` implementation:
https://github.com/spack/spack/blob/c6c74e98ffcf82ecd99522dffe67c03764aed482/lib/spack/spack/build_systems/oneapi.py#L97-L110
This causes `spack load` to fail.

A temporary fix that works on my system is commenting out the above line since the environment is set by modules anyways. I'm not sure if there is a simple fix for this to cover all cases, but it seems strange that Spack should source a script whenever MKL (or any IntelOneApiPackage) is needed, even when the environment is managed by modules. Is there a mechanism by which Spack can change its environment modifications depending on whether externals are pulled in via module?

Here is my `packages.yaml` entry - I had to specify both `prefix` and `modules` to get expected (successful) build behavior (#28768):
```
  intel-oneapi-mkl:
    externals:
      - spec: intel-oneapi-mkl@<version>
        prefix: /home/skoyama/oneapi
        modules:
          - oneapi-prgenv/<version>
    buildable: false
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@rscohn2 FYI

**Comment by rscohn2** [comment]
Feel free to submit a PR that adds a variant that disables loading the vars.sh, if that is all you need. I don't use modules and do not know if other modules users need the vars.sh.
