### ISSUE TITLE
%% not working

### ISSUE THREAD

**Issue by matt-chan** [LLNL/spack#34273]
### Steps to reproduce

Using `%%` to specify compiler does not work.

### Error message

```
$ spack -d spec -U vasp %%nvhpc
==> [2022-12-02-12:53:11.963763] Imported spec from built-in commands
==> [2022-12-02-12:53:11.964228] Imported spec from built-in commands
==> [2022-12-02-12:53:11.964753] SpackError: Unexpected token: '%'  Encountered when parsing spec:
    vasp
     ^
==> [2022-12-02-12:53:11.964787] Error: Unexpected token: '%'  Encountered when parsing spec:
    vasp
     ^
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/spec.py", line 5080, in do_parse
    specs.append(self.spec(self.token.value))
  File "/opt/spack/lib/spack/spack/spec.py", line 5264, in spec
    spec._set_compiler(self.compiler())
  File "/opt/spack/lib/spack/spack/spec.py", line 5356, in compiler
    self.expect(ID)
  File "/opt/spack/lib/spack/spack/parse.py", line 142, in expect
    self.unexpected_token()
  File "/opt/spack/lib/spack/spack/parse.py", line 134, in unexpected_token
    self.next_token_error("Unexpected token: '%s'" % self.next.value)
  File "/opt/spack/lib/spack/spack/parse.py", line 127, in next_token_error
    raise ParseError(message, self.text[0], self.token.end)
spack.parse.ParseError: Unexpected token: '%'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/cmd/__init__.py", line 224, in parse_specs
    specs = spack.spec.parse(sargs)
  File "/opt/spack/lib/spack/spack/spec.py", line 5384, in parse
    return SpecParser().parse(string)
  File "/opt/spack/lib/spack/spack/parse.py", line 158, in parse
    return self.do_parse()
  File "/opt/spack/lib/spack/spack/spec.py", line 5144, in do_parse
    raise SpecParseError(e) from e
spack.spec.SpecParseError: Unexpected token: '%'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/main.py", line 1000, in main
    return _main(argv)
  File "/opt/spack/lib/spack/spack/main.py", line 955, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/opt/spack/lib/spack/spack/main.py", line 983, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 632, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    input_specs = spack.cmd.parse_specs(args.specs)
  File "/opt/spack/lib/spack/spack/cmd/__init__.py", line 242, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Unexpected token: '%'  Encountered when parsing spec:
    vasp
     ^
```

### Information on your system

# spack debug report
* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tgamblin** [comment]
Sorry I misled @matt-chan on slack -- this feature is not implemented yet and I was conflating this with flag propagation from 0.19.  Sorry for the noise 😬
