### ISSUE TITLE
Installation issue: gnuconfig fails to install

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#34470]
### Steps to reproduce the issue

```console
$ spack spec -I dealii
Input spec
--------------------------------
 -   dealii

Concretized
--------------------------------
 -   dealii@9.4.0%apple-clang@14.0.0+adol-c+arborx+arpack+assimp+cgal~cuda~doc~examples+ginkgo~gmsh+gsl+hdf5~int64~ipo+metis+mpi+muparser~nanoflann~netcdf~oce~optflags+p4est+petsc~python+scalapack+simplex+slepc+sundials+symengine+threads+trilinos build_system=cmake build_type=DebugRelease cxxstd=default patches=7869dfa,8a1f7b9 arch=darwin-ventura-m1
 -       ^adol-c@2.7.2%apple-clang@14.0.0~advanced_branching+atrig_erf~boost+doc+examples~openmp~sparse+stdczero+traceless_refcounting build_system=autotools patches=715b878 arch=darwin-ventura-m1
 -           ^gnuconfig@2021-08-14%apple-clang@14.0.0 build_system=generic arch=darwin-ventura-m1
 -       ^arborx@1.3%apple-clang@14.0.0~cuda~ipo+mpi~openmp~rocm+serial~sycl+trilinos build_system=cmake build_type=RelWithDebInfo cxxstd=17 arch=darwin-ventura-m1
 -       ^arpack-ng@3.8.0%apple-clang@14.0.0~ipo+mpi+shared build_system=cmake build_type=RelWithDebInfo arch=darwin-ventura-m1
 -       ^assimp@5.2.4%apple-clang@14.0.0~ipo+shared build_system=cmake build_type=RelWithDebInfo arch=darwin-ventura-m1
 -           ^pkgconf@1.8.0%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -       ^boost@1.79.0%apple-clang@14.0.0+atomic+chrono~clanglibcpp+container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~graph_parallel~icu+iostreams~json+locale+log+math~mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave build_system=generic cxxstd=98 patches=a440f96 visibility=hidden arch=darwin-ventura-m1
 -           ^bzip2@1.0.8%apple-clang@14.0.0~debug~pic+shared build_system=generic arch=darwin-ventura-m1
 -       ^cgal@5.4.1%apple-clang@14.0.0~core~demos+eigen~header_only~imageio~ipo+shared build_system=cmake build_type=Release arch=darwin-ventura-m1
 -           ^eigen@3.4.0%apple-clang@14.0.0~ipo build_system=cmake build_type=RelWithDebInfo arch=darwin-ventura-m1
 -           ^gmp@6.2.1%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -               ^autoconf@2.69%apple-clang@14.0.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=darwin-ventura-m1
 -               ^automake@1.16.5%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -           ^mpfr@4.1.0%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -               ^autoconf-archive@2022.02.11%apple-clang@14.0.0 build_system=autotools patches=139214f arch=darwin-ventura-m1
 -               ^texinfo@6.5%apple-clang@14.0.0 build_system=autotools patches=12f6edb,1732115 arch=darwin-ventura-m1
 -       ^cmake@3.24.3%apple-clang@14.0.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=darwin-ventura-m1
 -           ^ncurses@6.3%apple-clang@14.0.0~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-m1
 -           ^openssl@1.1.1s%apple-clang@14.0.0~docs~shared build_system=generic certs=mozilla arch=darwin-ventura-m1
 -               ^ca-certificates-mozilla@2022-10-11%apple-clang@14.0.0 build_system=generic arch=darwin-ventura-m1
 -       ^ginkgo@1.4.0%apple-clang@14.0.0~cuda~develtools~full_optimizations~hwloc~ipo~oneapi~openmp~rocm+shared build_system=cmake build_type=Release patches=43e571a arch=darwin-ventura-m1
 -       ^gsl@2.7.1%apple-clang@14.0.0~external-cblas build_system=autotools arch=darwin-ventura-m1
 -       ^hdf5@1.12.2%apple-clang@14.0.0+cxx+fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo arch=darwin-ventura-m1
 -       ^intel-tbb@2021.7.0%apple-clang@14.0.0~ipo+shared+tm build_system=cmake build_type=RelWithDebInfo cxxstd=default arch=darwin-ventura-m1
 -           ^hwloc@2.8.0%apple-clang@14.0.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -               ^libxml2@2.10.1%apple-clang@14.0.0~python build_system=autotools arch=darwin-ventura-m1
 -       ^metis@5.1.0%apple-clang@14.0.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=RelWithDebInfo patches=4991da9,93a7903 arch=darwin-ventura-m1
 -       ^muparser@2.2.6.1%apple-clang@14.0.0 build_system=generic arch=darwin-ventura-m1
 -       ^netlib-scalapack@2.2.0%apple-clang@14.0.0~ipo~pic+shared build_system=cmake build_type=Release patches=072b006,1c9ce5f arch=darwin-ventura-m1
 -       ^ninja@1.11.1%apple-clang@14.0.0 build_system=generic arch=darwin-ventura-m1
 -           ^python@3.10.8%apple-clang@14.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=darwin-ventura-m1
 -               ^apple-libuuid@1353.100.2%apple-clang@14.0.0 build_system=bundle arch=darwin-ventura-m1
 -               ^expat@2.4.8%apple-clang@14.0.0~libbsd build_system=autotools arch=darwin-ventura-m1
 -               ^gdbm@1.23%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -               ^gettext@0.21.1%apple-clang@14.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=darwin-ventura-m1
 -                   ^tar@1.34%apple-clang@14.0.0 build_system=autotools zip=pigz arch=darwin-ventura-m1
 -                       ^pigz@2.7%apple-clang@14.0.0 build_system=makefile arch=darwin-ventura-m1
 -                       ^zstd@1.5.2%apple-clang@14.0.0+programs build_system=makefile compression=none libs=shared,static arch=darwin-ventura-m1
 -               ^libffi@3.4.2%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -               ^readline@8.1.2%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -               ^sqlite@3.39.4%apple-clang@14.0.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=darwin-ventura-m1
 -               ^xz@5.2.7%apple-clang@14.0.0~pic build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -       ^openblas@0.3.21%apple-clang@14.0.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=none threads=none arch=darwin-ventura-m1
 -           ^perl@5.36.0%apple-clang@14.0.0+cpanm+shared+threads build_system=generic arch=darwin-ventura-m1
 -               ^berkeley-db@18.1.40%apple-clang@14.0.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-m1
 -       ^openmpi@4.1.4%apple-clang@14.0.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=darwin-ventura-m1
 -           ^openssh@9.1p1%apple-clang@14.0.0+gssapi build_system=autotools arch=darwin-ventura-m1
 -               ^krb5@1.19.3%apple-clang@14.0.0+shared build_system=autotools arch=darwin-ventura-m1
 -                   ^bison@3.8.2%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -               ^libedit@3.1-20210216%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -           ^pmix@4.1.2%apple-clang@14.0.0~docs+pmi_backwards_compatibility~restful build_system=autotools arch=darwin-ventura-m1
 -               ^libevent@2.1.12%apple-clang@14.0.0+openssl build_system=autotools arch=darwin-ventura-m1
 -       ^p4est@2.8%apple-clang@14.0.0+mpi~openmp build_system=autotools arch=darwin-ventura-m1
 -           ^libtool@2.4.7%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -       ^petsc@3.18.1%apple-clang@14.0.0~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre~int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi+mumps~openmp+p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared~strumpack+suite-sparse+superlu-dist~tetgen~trilinos~valgrind build_system=generic clanguage=C arch=darwin-ventura-m1
 -           ^diffutils@3.8%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -               ^libiconv@1.16%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -           ^hypre@2.26.0%apple-clang@14.0.0~complex~cuda~debug+fortran~gptune~int64~internal-superlu~mixedint+mpi~openmp~rocm~shared~superlu-dist~umpire~unified-memory build_system=autotools arch=darwin-ventura-m1
 -           ^mumps@5.5.1%apple-clang@14.0.0~blr_mt+complex+double+float~incfort~int64+metis+mpi~openmp+parmetis~ptscotch~scotch+shared build_system=generic patches=373d736 arch=darwin-ventura-m1
 -           ^parmetis@4.0.3%apple-clang@14.0.0~gdb~int64~ipo+shared build_system=cmake build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=darwin-ventura-m1
 -           ^superlu-dist@7.2.0%apple-clang@14.0.0~cuda~int64~ipo~openmp~rocm+shared build_system=cmake build_type=RelWithDebInfo patches=8da9e21 arch=darwin-ventura-m1
 -       ^slepc@3.18.1%apple-clang@14.0.0+arpack~blopex~cuda~rocm build_system=generic arch=darwin-ventura-m1
 -       ^suite-sparse@5.13.0%apple-clang@14.0.0~cuda~graphblas~openmp+pic build_system=generic arch=darwin-ventura-m1
 -           ^m4@1.4.19%apple-clang@14.0.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=darwin-ventura-m1
 -               ^libsigsegv@2.13%apple-clang@14.0.0 build_system=autotools arch=darwin-ventura-m1
 -       ^sundials@6.4.1%apple-clang@14.0.0+ARKODE+CVODE+CVODES+IDA+IDAS+KINSOL~cuda+examples+examples-install~f2003~fcmix+generic-math~ginkgo~hypre~int64~ipo~klu~kokkos~kokkos-kernels~lapack~magma~monitoring+mpi~openmp~petsc~profiling~pthread~raja~rocm+shared+static~superlu-dist~superlu-mt~sycl~trilinos build_system=cmake build_type=RelWithDebInfo cstd=99 cxxstd=14 logging-level=0 logging-mpi=OFF precision=double arch=darwin-ventura-m1
 -       ^symengine@0.9.0%apple-clang@14.0.0~boostmp~flint~ipo~llvm+mpc+mpfr~openmp~piranha+shared+thread_safe build_system=cmake build_type=Release arch=darwin-ventura-m1
 -           ^cereal@1.3.2%apple-clang@14.0.0~ipo build_system=cmake build_type=RelWithDebInfo patches=2dfa0bf arch=darwin-ventura-m1
 -           ^mpc@1.2.1%apple-clang@14.0.0 build_system=autotools libs=shared,static arch=darwin-ventura-m1
 -       ^trilinos@13.4.0%apple-clang@14.0.0~adelus~adios2+amesos+amesos2+anasazi+aztec~basker+belos~boost~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~gtest~hdf5~hypre+ifpack+ifpack2~intrepid~intrepid2~ipo~isorropia+kokkos+mesquite~minitensor+ml+mpi+muelu+mumps~nox~openmp~panzer~phalanx~piro~python~rocm~rocm_rdc+rol~rythmos+sacado~scorec~shards+shared~shylu~stk~stokhos~stratimikos~strumpack+suite-sparse~superlu+superlu-dist~teko~tempus~thyra+tpetra~trilinoscouplings~wrapper~x11~zoltan~zoltan2 build_system=cmake build_type=RelWithDebInfo cxxstd=14 gotype=long_long arch=darwin-ventura-m1
 -       ^zlib@1.2.13%apple-clang@14.0.0+optimize+pic+shared build_system=makefile arch=darwin-ventura-m1
```

### Error message

```
$ spack install -j8 --only dependencies --fail-fast dealii
==> Installing gnuconfig-2021-08-14-qc2hufswnuji6gclgualbjxnvjenzpyz
==> No binary for gnuconfig-2021-08-14-qc2hufswnuji6gclgualbjxnvjenzpyz found: installing from source
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'Mark' on <module 'ruamel.yaml.error' from '/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/ruamel/yaml/error.py'>
```

### Information on your system

$ spack debug report
* **Spack:** 0.19.0 (bb8b4f9979e87ae3fb63a3adcb768eda09e5b059)
* **Python:** 3.10.8
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### Additional information

Not applicable

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cpraveen** [comment]
Installation gets stuck, does not proceed after printing the error messages, and I have to kill it manually.

**Comment by haampie** [comment]
It seems Spack picks up the wrong `ruamel`, Spack vendors its own patched version. If you run `$spack/bin/spack` you should get the right python search paths for ruamel.

**Comment by cpraveen** [comment]
You mean like this

```
/Users/praveen/Applications/spack/bin/spack install -j8 --only dependencies --fail-fast dealii
==> Installing gnuconfig-2021-08-14-qc2hufswnuji6gclgualbjxnvjenzpyz
==> No binary for gnuconfig-2021-08-14-qc2hufswnuji6gclgualbjxnvjenzpyz found: installing from source
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'Mark' on <module 'ruamel.yaml.error' from '/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/ruamel/yaml/error.py'>
```

I get the same error.
