### ISSUE TITLE
Cannot remove old compilers after migrating to a new machine

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#34917]
### Steps to reproduce

This will be hard to reproduce:

I have spack installed on an external hard drive, which I've been using with an Ubuntu 21.04 machine until a week ago, when I got a new machine with Ubuntu 22.04 and plugged the hard drive to it. I didn't copy the content of `$HOME/.spack` from the old to the new machine (`/home` is not on this hard drive). On the new machine, wanting to wipe-clean my spack installation, I did:
```
spack uninstall --all && spack clean --all
``` 
Then I made it find compilers with `spack compiler find` and started using it.

Now, I noticed that `spack compiler list` shows me this:

```
==> Available compilers
-- clang ubuntu21.04-x86_64 -------------------------------------
clang@12.0.0

-- clang ubuntu22.04-x86_64 -------------------------------------
clang@14.0.0

-- gcc ubuntu21.04-x86_64 ---------------------------------------
gcc@10.3.0  gcc@7.5.0

-- gcc ubuntu22.04-x86_64 ---------------------------------------
gcc@11.3.0
```

3 compilers are from the old machine, even though (1) no package uses them, now that I have uninstalled all of them, and (2) these compilers are not even listed in `$HOME/.spack/linux/compilers.yaml`, only the two from the new machine are listed.

Furthermore, `spack compiler remove gcc@10.3.0` (for instance) fails with this error:

```
==> Error: No compilers match spec gcc@10.3.0
```

It seems that in addition to `$HOME/.spack/linux/compilers.yaml`, spack also keeps compilers in `$SPACK_HOME/etc/spack/linux/compilers.yaml` and the `spack compiler remove` command isn't seeing the compilers that are in this file.

### Error message

With debug flag, the output of the remove command is as follows:

```
==> [2023-01-13-09:39:42.516652] Imported compiler from built-in commands
==> [2023-01-13-09:39:42.518102] Imported compiler from built-in commands
==> [2023-01-13-09:39:42.518691] Reading config from file /home/mdorier/.spack/linux/compilers.yaml
==> [2023-01-13-09:39:42.525260] Error: No compilers match spec gcc@10.3.0
==> [2023-01-13-09:39:42.525774] Reading config from file /projects/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/projects/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/projects/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/projects/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/projects/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/projects/spack/lib/spack/spack/cmd/compiler.py", line 203, in compiler
    action[args.compiler_command](args)
  File "/projects/spack/lib/spack/spack/cmd/compiler.py", line 112, in compiler_remove
    tty.die("No compilers match spec %s" % cspec)
  File "/projects/spack/lib/spack/llnl/util/tty/__init__.py", line 253, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system

* **Spack:** 0.20.0.dev0 (cc333b600c797264aec7ca6f0d77cff1fb658c38)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Can you dump `spack config blame compilers` too?

**Comment by mdorier** [comment]
Sure:

```
spack config blame compilers
---                                                compilers:
/home/mdorier/.spack/linux/compilers.yaml:2        - compiler:
/home/mdorier/.spack/linux/compilers.yaml:3            spec: clang@14.0.0
/home/mdorier/.spack/linux/compilers.yaml:4            paths:
/home/mdorier/.spack/linux/compilers.yaml:5              cc: /usr/bin/clang
/home/mdorier/.spack/linux/compilers.yaml:6              cxx: /usr/bin/clang++
/home/mdorier/.spack/linux/compilers.yaml:7              f77: null
/home/mdorier/.spack/linux/compilers.yaml:8              fc: null
/home/mdorier/.spack/linux/compilers.yaml:9            flags: {}
/home/mdorier/.spack/linux/compilers.yaml:10           operating_system: ubuntu22.04
/home/mdorier/.spack/linux/compilers.yaml:11           target: x86_64
/home/mdorier/.spack/linux/compilers.yaml:12           modules: []
/home/mdorier/.spack/linux/compilers.yaml:13           environment: {}
/home/mdorier/.spack/linux/compilers.yaml:14           extra_rpaths: []
/home/mdorier/.spack/linux/compilers.yaml:15       - compiler:
/home/mdorier/.spack/linux/compilers.yaml:16           spec: gcc@11.3.0
/home/mdorier/.spack/linux/compilers.yaml:17           paths:
/home/mdorier/.spack/linux/compilers.yaml:18             cc: /usr/bin/gcc
/home/mdorier/.spack/linux/compilers.yaml:19             cxx: /usr/bin/g++
/home/mdorier/.spack/linux/compilers.yaml:20             f77: /usr/bin/gfortran
/home/mdorier/.spack/linux/compilers.yaml:21             fc: /usr/bin/gfortran
/home/mdorier/.spack/linux/compilers.yaml:22           flags: {}
/home/mdorier/.spack/linux/compilers.yaml:23           operating_system: ubuntu22.04
/home/mdorier/.spack/linux/compilers.yaml:24           target: x86_64
/home/mdorier/.spack/linux/compilers.yaml:25           modules: []
/home/mdorier/.spack/linux/compilers.yaml:26           environment: {}
/home/mdorier/.spack/linux/compilers.yaml:27           extra_rpaths: []
/projects/spack/etc/spack/linux/compilers.yaml:2   - compiler:
/projects/spack/etc/spack/linux/compilers.yaml:3       spec: clang@12.0.0
/projects/spack/etc/spack/linux/compilers.yaml:4       paths:
/projects/spack/etc/spack/linux/compilers.yaml:5         cc: /usr/bin/clang
/projects/spack/etc/spack/linux/compilers.yaml:6         cxx: /usr/bin/clang++
/projects/spack/etc/spack/linux/compilers.yaml:7         f77: null
/projects/spack/etc/spack/linux/compilers.yaml:8         fc: null
/projects/spack/etc/spack/linux/compilers.yaml:9       flags: {}
/projects/spack/etc/spack/linux/compilers.yaml:10      operating_system: ubuntu21.04
/projects/spack/etc/spack/linux/compilers.yaml:11      target: x86_64
/projects/spack/etc/spack/linux/compilers.yaml:12      modules: []
/projects/spack/etc/spack/linux/compilers.yaml:13      environment: {}
/projects/spack/etc/spack/linux/compilers.yaml:14      extra_rpaths: []
/projects/spack/etc/spack/linux/compilers.yaml:15  - compiler:
/projects/spack/etc/spack/linux/compilers.yaml:16      spec: gcc@10.3.0
/projects/spack/etc/spack/linux/compilers.yaml:17      paths:
/projects/spack/etc/spack/linux/compilers.yaml:18        cc: /usr/bin/gcc
/projects/spack/etc/spack/linux/compilers.yaml:19        cxx: /usr/bin/g++
/projects/spack/etc/spack/linux/compilers.yaml:20        f77: /usr/bin/gfortran
/projects/spack/etc/spack/linux/compilers.yaml:21        fc: /usr/bin/gfortran
/projects/spack/etc/spack/linux/compilers.yaml:22      flags: {}
/projects/spack/etc/spack/linux/compilers.yaml:23      operating_system: ubuntu21.04
/projects/spack/etc/spack/linux/compilers.yaml:24      target: x86_64
/projects/spack/etc/spack/linux/compilers.yaml:25      modules: []
/projects/spack/etc/spack/linux/compilers.yaml:26      environment: {}
/projects/spack/etc/spack/linux/compilers.yaml:27      extra_rpaths: []
/projects/spack/etc/spack/linux/compilers.yaml:28  - compiler:
/projects/spack/etc/spack/linux/compilers.yaml:29      spec: gcc@7.5.0
/projects/spack/etc/spack/linux/compilers.yaml:30      paths:
/projects/spack/etc/spack/linux/compilers.yaml:31        cc: /usr/bin/gcc-7
/projects/spack/etc/spack/linux/compilers.yaml:32        cxx: /usr/bin/g++-7
/projects/spack/etc/spack/linux/compilers.yaml:33        f77: /usr/bin/gfortran-7
/projects/spack/etc/spack/linux/compilers.yaml:34        fc: /usr/bin/gfortran-7
/projects/spack/etc/spack/linux/compilers.yaml:35      flags: {}
/projects/spack/etc/spack/linux/compilers.yaml:36      operating_system: ubuntu21.04
/projects/spack/etc/spack/linux/compilers.yaml:37      target: x86_64
/projects/spack/etc/spack/linux/compilers.yaml:38      modules: []
/projects/spack/etc/spack/linux/compilers.yaml:39      environment: {}
/projects/spack/etc/spack/linux/compilers.yaml:40      extra_rpaths: []
```

**Comment by haampie** [comment]
Can't reproduce...

**Comment by mdorier** [comment]
Maybe a weird pollution from having used this spack installation for years, doing `git pull` occasionally on it and moving it from a machine to another a few times. At any rate, manually removing the faulty compilers.yaml file works, and it's not like spack would have used these compilers anyway as they were for another machine. Feel free to close the issue.

**Comment by haampie** [comment]
Hm, weird issue though. I just tried creating a mismatching os, but yeah, it was removable
