### ISSUE TITLE
Regression when patch a dependency from another repository

### ISSUE THREAD

**Issue by Jordan474** [LLNL/spack#34961]
### Steps to reproduce

This is a regression since 0.19 (#32273 [this line](https://github.com/spack/spack/pull/32273/files#diff-bce41de9ec570584d2140a0307d35bdfe5af8a59065895bcb6f0d701aa231d14L428)):

If you have `depends_on("somedep", patches=["test.patch"])` and `somedep` is not in same repository as your package, you now get an error.

### Error message

```console
$ spack clean -m
$ spack -d spec mypkg
[...]
==> [2023-01-16-17:05:34.644218] Error: Package 'somedep' not found.
You may need to run 'spack clean -m'.
Traceback (most recent call last):
  File "myspack/spack/lib/spack/spack/repo.py", line 1357, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spack.pkg.myrepo.somedep'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myspack/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "myspack/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "myspack/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "myspack/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "myspack/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "myspack/spack/lib/spack/spack/cmd/__init__.py", line 228, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "myspack/spack/lib/spack/spack/spec.py", line 2970, in concretize
    self._new_concretize(tests)
  File "myspack/spack/lib/spack/spack/spec.py", line 2945, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "myspack/spack/lib/spack/spack/solver/asp.py", line 2453, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "myspack/spack/lib/spack/spack/solver/asp.py", line 2401, in _check_input_and_extract_concrete_specs
    if s.virtual:
  File "myspack/spack/lib/spack/spack/spec.py", line 1651, in virtual
    return spack.repo.path.is_virtual(self.name)
  File "myspack/spack/lib/spack/spack/repo.py", line 1021, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "myspack/spack/lib/spack/spack/repo.py", line 901, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "myspack/spack/lib/spack/spack/repo.py", line 1227, in provider_index
    return self.index["providers"]
  File "myspack/spack/lib/spack/spack/repo.py", line 731, in __getitem__
    self._build_all_indexes()
  File "myspack/spack/lib/spack/spack/repo.py", line 746, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "myspack/spack/lib/spack/spack/repo.py", line 777, in _build_index
    indexer.update(namespaced_name)
  File "myspack/spack/lib/spack/spack/repo.py", line 682, in update
    self.index.update_package(pkg_fullname)
  File "myspack/spack/lib/spack/spack/patch.py", line 404, in update_package
    partial_index = self._index_patches(pkg_cls, self.repository)
  File "myspack/spack/lib/spack/spack/patch.py", line 431, in _index_patches
    dspec_cls = repository.get_pkg_class(dependency.spec.name)
  File "myspack/spack/lib/spack/spack/repo.py", line 1359, in get_pkg_class
    raise UnknownPackageError(pkg_name)
spack.repo.UnknownPackageError: Package 'somedep' not found.
    You may need to run 'spack clean -m'.

```

### Information on your system

* **Spack:** 0.19.0 (backports/v0.19.1)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment]
Have been seeing the same issue for some time and was about to submit another bug report before finding this one. 

@alalazo here is a minimal reproducer which might help fixing it:

You create a spackage in a custom repository. The concretization fails if `depends_on` applies patches to a package outside of the custom repository namespace. Removing the patches line makes the concretization work again. Our current workaround is to create a 1:1 copy of the builtin spackage in our custom repository.
```console
spack repo create testing
spack repo add testing
mkdir testing/packages/some_package
cat > testing/packages/some_package/package.py <<EOF
from spack.package import *

class SomePackage(CMakePackage):
    """Placeholder"""

    homepage = "https://github.com/zlib-ng/zlib-ng"
    url = "https://github.com/zlib-ng/zlib-ng/archive/2.0.0.tar.gz"
    git = "https://github.com/zlib-ng/zlib-ng.git"

    version("2.1.5", sha256="3f6576971397b379d4205ae5451ff5a68edf6c103b2f03c4188ed7075fbb5f04")

    depends_on(
        "mpark-variant",
        # remove the patches line and the command will work
        patches=patch(
            "https://raw.githubusercontent.com/lanl/singularity-eos/main/utils/cuda_compatibility.patch",
            sha256="7b3eaa52b5ab23dc45fbfb456528e36742e04b838a5df859eca96c4e8274bb38",
        )
    )
EOF
spack spec some_package
```

```console
$ spack --debug --stacktrace spec some_package
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.460698] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-26-12:41:39.489486] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-26-12:41:39.490010] Imported spec from built-in commands
lib/spack/spack/database.py:645 ==> [2024-01-26-12:41:39.491291] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-01-26-12:41:39.491399] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.493920] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.499068] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.500310] Reading config from file /home/rberger/projects/devops/spack/etc/spack/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-01-26-12:41:39.501673] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.502001] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-01-26-12:41:39.505771] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/rberger/projects/devops/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-01-26-12:41:39.505872] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/rberger/projects/devops/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-01-26-12:41:39.505939] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/rberger/projects/devops/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-01-26-12:41:39.506003] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/rberger/projects/devops/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.506592] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.517548] Reading config from file /home/rberger/projects/devops/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:645 ==> [2024-01-26-12:41:39.523697] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-01-26-12:41:39.523811] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.524346] Reading config from file /home/rberger/projects/devops/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-26-12:41:39.541184] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.541493] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:186 ==> [2024-01-26-12:41:39.547993] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.552624] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.558870] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/build_environment.py:1014 ==> [2024-01-26-12:41:39.569754] Adding env modifications for patchelf
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.597380] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.613379] Reading config from file /home/rberger/projects/devops/.spack/bootstrap/config/packages.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-26-12:41:39.617428] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-26-12:41:39.637560] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:380 ==> [2024-01-26-12:41:39.637681] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:79 ==> [2024-01-26-12:41:39.723195] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10/idkenmhnscjlu5gjqhpcqa4h7o2a7aow" provides the "clingo" Python module
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.723772] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.727740] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.729052] Reading config from file /home/rberger/projects/devops/spack/etc/spack/repos.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-26-12:41:39.762363] Reading config from file /home/rberger/projects/devops/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/main.py:1069 ==> [2024-01-26-12:41:39.796356] UnknownPackageError: Package 'spack.pkg.testing.mpark-variant' not found.
    Use 'spack create' to create a new package.

Did you mean one of the following packages?
  mpark-variant
lib/spack/spack/error.py:52 ==> [2024-01-26-12:41:39.796617] Error: Package 'spack.pkg.testing.mpark-variant' not found.
Use 'spack create' to create a new package.

Did you mean one of the following packages?
  mpark-variant
Traceback (most recent call last):
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 1240, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spack.pkg.testing.mpark-variant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rberger/projects/devops/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/spec.py", line 3020, in concretize
    self._new_concretize(tests)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/spec.py", line 2992, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/solver/asp.py", line 3574, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/solver/asp.py", line 3510, in _check_input_and_extract_concrete_specs
    if s.virtual:
  File "/home/rberger/projects/devops/spack/lib/spack/spack/spec.py", line 1760, in virtual
    return spack.repo.PATH.is_virtual(self.name)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 893, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 773, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 1106, in provider_index
    return self.index["providers"]
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 590, in __getitem__
    self._build_all_indexes()
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 603, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 633, in _build_index
    indexer.update(f"{self.namespace}.{pkg_name}")
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 542, in update
    self.index.update_package(pkg_fullname)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/patch.py", line 370, in update_package
    partial_index = self._index_patches(pkg_cls, self.repository)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/patch.py", line 396, in _index_patches
    dspec_cls = repository.get_pkg_class(dependency.spec.name)
  File "/home/rberger/projects/devops/spack/lib/spack/spack/repo.py", line 1242, in get_pkg_class
    raise UnknownPackageError(fullname)
spack.repo.UnknownPackageError: Package 'spack.pkg.testing.mpark-variant' not found.
    Use 'spack create' to create a new package.

Did you mean one of the following packages?
  mpark-variant
```


* **Spack:** 0.22.0.dev0 (29d784e5fa4651e3a47af766057ebc06ee558420)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-sapphirerapids
* **Concretizer:** clingo

**Comment by rbberger** [comment]
@alalazo any hope this will get fixed anytime soon? we're still running into this again and again in multiple projects.

**Comment by jacobmerson** [comment]
I also hit this bug using Version 0.22.2 (594a376c521cc746978571b1181a47bbcff30a21)

**Comment by cameronrutherford** [comment]
Another +1 to this issue. I thought it was related to https://github.com/spack/spack/issues/45864, but instead I am running into this issue using `spack@develop` from today.

@rbberger suggested that a workaround is to duplicate the upstream package in your local registry, but that isn't ideal as you have to pull in changes regularly. One would hope that this is an easy thing to fix.

**Comment by alalazo** [comment]
Raising impact due to number of +1 in the issue
