### ISSUE TITLE
Spack can't cope with Python disappearing

### ISSUE THREAD

**Issue by mabraham** [LLNL/spack#35226]
### Steps to reproduce

My sysadmins moved the version of python that I was using for spack. I have asked them to be more thoughtful in future. Running spack, I now see the error message below, wherein it cannot find the former oneapi version of python.

The only pythons in my environment are `/usr/bin/python` and `/usr/bin/python3`. So I don't know how it is still trying to use the python I originally asked it to use. Removing the `~/.spack` dir didn't help. `git reset --hard HEAD` on the spack git repo didn't help. Is spack caching a reference to this python somewhere?

### Error message

```console
$ spack --debug install reframe@4.0.1
==> [2023-01-29-01:26:59.663890] Imported install from built-in commands
==> [2023-01-29-01:26:59.667709] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/config.yaml
==> [2023-01-29-01:26:59.695742] Imported install from built-in commands
==> [2023-01-29-01:26:59.702801] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-01-29-01:26:59.724581] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/repos.yaml
==> [2023-01-29-01:26:59.731164] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/config.yaml
==> [2023-01-29-01:26:59.752043] DATABASE LOCK TIMEOUT: 3s
==> [2023-01-29-01:26:59.752107] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-01-29-01:26:59.753413] DATABASE LOCK TIMEOUT: 3s
==> [2023-01-29-01:26:59.753535] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-01-29-01:26:59.753677] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-01-29-01:26:59.754409] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-01-29-01:26:59.764562] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/nfs/site/home/markjame/git/spack/etc/spack/defaults
==> [2023-01-29-01:26:59.764627] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/nfs/site/home/markjame/git/spack/etc/spack/defaults/linux
==> [2023-01-29-01:26:59.764670] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/nfs/site/home/markjame/.spack/bootstrap/config
==> [2023-01-29-01:26:59.764703] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/nfs/site/home/markjame/.spack/bootstrap/config/linux
==> [2023-01-29-01:26:59.766021] Reading config from file /nfs/site/home/markjame/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-01-29-01:26:59.808749] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-01-29-01:26:59.809434] '/usr/bin/patchelf' '--version'
==> [2023-01-29-01:26:59.812885] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-01-29-01:26:59.827105] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-01-29-01:27:03.319871] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/config.yaml
==> [2023-01-29-01:27:03.420344] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/modules.yaml
==> [2023-01-29-01:27:03.443113] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/linux/modules.yaml
==> [2023-01-29-01:27:03.562399] Reading config from file /nfs/site/home/markjame/git/spack/etc/spack/defaults/packages.yaml
==> [2023-01-29-01:27:03.630924] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-01-29-01:27:03.642923] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
...
==> [2023-01-29-01:27:27.076006] No binary for reframe-4.0.1-llhczfc5ejef6ig4jklyijbtrqkodk32 found: installing from source
==> [2023-01-29-01:27:27.076396] Creating the installation directory /nfs/site/home/markjame/git/spack/opt/spack/linux-ubuntu20.04-skylake_avx512/gcc-9.4.0/reframe-4.0.1-llhczfc5ejef6ig4jklyijbtrqkodk32
==> [2023-01-29-01:27:27.100801] '/usr/bin/git' '-C' '/nfs/site/home/markjame/git/spack' 'rev-parse' 'HEAD'
==> [2023-01-29-01:27:27.252530] [TOOLCHAIN] MATCH Gcc
==> [2023-01-29-01:27:27.256981] Adding compiler bin/ paths: /nfs/site/home/markjame/git/spack/lib/spack/env /nfs/site/home/markjame/git/spack/lib/spack/env/case-insensitive /nfs/site/home/markjame/git/spack/lib/spack/env/gcc
==> [2023-01-29-01:27:27.293360] Error: RuntimeError: Unable to locate python command in /opt/intel/oneapi_customer/intelpython/latest/bin

/nfs/site/home/markjame/git/spack/var/spack/repos/builtin/packages/python/package.py:744, in command:
        741                    return Executable(path)
        742
        743            msg = "Unable to locate {0} command in {1}"
  >>    744            raise RuntimeError(msg.format(self.name, self.prefix.bin))


Traceback (most recent call last):
  File "/nfs/site/home/markjame/git/spack/lib/spack/spack/build_environment.py", line 1035, in _setup_pkg_and_run
    kwargs["env_modifications"] = setup_package(
  File "/nfs/site/home/markjame/git/spack/lib/spack/spack/build_environment.py", line 775, in setup_package
    env_mods.extend(modifications_from_dependencies(pkg.spec, context, custom_mods_only=False))
  File "/nfs/site/home/markjame/git/spack/lib/spack/spack/build_environment.py", line 978, in modifications_from_dependencies
    add_modifications_for_dep(dspec)
  File "/nfs/site/home/markjame/git/spack/lib/spack/spack/build_environment.py", line 963, in add_modifications_for_dep
    dpkg.setup_dependent_package(current_module, spec)
  File "/nfs/site/home/markjame/git/spack/var/spack/repos/builtin/packages/python/package.py", line 1155, in setup_dependent_package
  File "/nfs/site/home/markjame/git/spack/var/spack/repos/builtin/packages/python/package.py", line 745, in command
RuntimeError: Unable to locate python command in /opt/intel/oneapi_customer/intelpython/latest/bin
==> [2023-01-29-01:27:27.294072] Flagging reframe-4.0.1-llhczfc5ejef6ig4jklyijbtrqkodk32 as failed: RuntimeError: Unable to locate python command in /opt/intel/oneapi_customer/intelpython/latest/bin
==> [2023-01-29-01:27:27.324788] ChildError: RuntimeError: Unable to locate python command in /opt/intel/oneapi_customer/intelpython/latest/bin
```

### Information on your system

* **Spack:** 0.20.0.dev0 (28c4809a8fea6f51217bca105c8ad19a62a2c5ae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
A couple of questions to troubleshoot this issue:
1. Can you clone somewhere else another instance of Spack and have it working?
2. Can you execute `spack bootstrap now` successfully with this instance of Spack?

**Comment by adamjstewart** [comment]
Do you have this Python listed as an external package in `packages.yaml`?
