### ISSUE TITLE
Error cross-compiling cray-cnl7-haswell -> cray-cnl7-mic_knl with classic intel@2021.2.0

### ISSUE THREAD

**Issue by DarylGrunau** [LLNL/spack#35306]
### Steps to reproduce

In Spack `v0.18.0` I have a Spack Environment prescription to cross-compile for the KNL that looks like this `spack.yaml` file:
```yaml
spack:
  specs:
  - pkg1%intel@2021.2.0
  - pkg2%intel@2021.2.0
  - pkg3%intel@2021.2.0 target=mic_knl
  - pkg4%intel@2021.2.0
  .
  .
  .
```
which would (clingo) concretize the way you'd expect, where all of `pkg3` and it's dependents would be built with `mic_knl` compiler flags.  Running up to `0.20.0.dev0 (d192dab5a1)` this is no longer the case, and I get this error:

```shell
% spack concretize --reuse --force
==> Error: pkg3 compiler 'intel@2021.2.0' incompatible with 'target=mic_knl'
% spack concretize --fresh --force
==> Error: pkg3 compiler 'intel@2021.2.0' incompatible with 'target=mic_knl'
```

### Error message

```console
% spack --debug --stacktrace concretize --reuse --force
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:26.865265] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:26.911148] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.993418] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.994167] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.994795] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.995438] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.996307] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:26.996953] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml'
lib/spack/spack/environment/environment.py:989 ==> [2023-02-02-13:20:26.997339] Creating ConfigScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:INTEL for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.000013] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.001976] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.060994] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.063817] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.067411] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.070743] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.075892] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/spack.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.089372] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/upstreams.yaml
lib/spack/spack/environment/environment.py:174 ==> [2023-02-02-13:20:27.093486] Using environment '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/cmd/__init__.py:125 ==> [2023-02-02-13:20:27.106597] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:125 ==> [2023-02-02-13:20:27.107342] Imported concretize from built-in commands
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.206159] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.218286] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.218799] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.219296] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.219791] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.220283] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:27.220776] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml'
lib/spack/spack/environment/environment.py:989 ==> [2023-02-02-13:20:27.221246] Creating ConfigScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:INTEL for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/environment/environment.py:198 ==> [2023-02-02-13:20:27.221791] Deactivated environment '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.229106] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.237910] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:389 ==> [2023-02-02-13:20:27.267389] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2023-02-02-13:20:27.267714] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:389 ==> [2023-02-02-13:20:27.269702] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2023-02-02-13:20:27.270044] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap/config.py:124 ==> [2023-02-02-13:20:27.270383] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.271167] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:135 ==> [2023-02-02-13:20:27.280564] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:136 ==> [2023-02-02-13:20:27.280861] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:135 ==> [2023-02-02-13:20:27.281155] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/users/dwg/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:136 ==> [2023-02-02-13:20:27.281437] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/users/dwg/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.283869] Reading config from file /users/dwg/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:217 ==> [2023-02-02-13:20:27.360469] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:27.363206] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:179 ==> [2023-02-02-13:20:27.384270] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:29.977094] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.080423] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.098921] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.259318] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.304771] Reading config from file /users/dwg/.spack/bootstrap/config/packages.yaml
lib/spack/spack/bootstrap/_common.py:217 ==> [2023-02-02-13:20:30.338892] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:217 ==> [2023-02-02-13:20:30.344953] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:362 ==> [2023-02-02-13:20:30.345231] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:76 ==> [2023-02-02-13:20:30.416963] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/vcipwnf57slgoo7busvvkzjkk7vydeb5" provides the "clingo" Python module
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.418488] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/config.yaml
lib/spack/spack/util/executable.py:195 ==> [2023-02-02-13:20:30.531749] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
lib/spack/spack/platforms/cray.py:195 ==> [2023-02-02-13:20:30.540813] using front-end architecture or available ancestor
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.546223] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.546767] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.547266] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.547758] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.548252] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml'
lib/spack/spack/environment/environment.py:995 ==> [2023-02-02-13:20:30.548750] Creating SingleFileScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml'
lib/spack/spack/environment/environment.py:989 ==> [2023-02-02-13:20:30.549222] Creating ConfigScope env:/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL:INTEL for '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.552323] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/repos.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.554694] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/modules.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.614289] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/mirrors.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.617533] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/config.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.620983] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/concretizer.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.624279] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/common/bootstrap.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.629463] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/spack.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.642913] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/upstreams.yaml
lib/spack/spack/environment/environment.py:174 ==> [2023-02-02-13:20:30.647148] Using environment '/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL'
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.647582] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.655325] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.770107] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:30.815535] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/packages.yaml
lib/spack/spack/database.py:389 ==> [2023-02-02-13:20:31.605055] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2023-02-02-13:20:31.605425] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:389 ==> [2023-02-02-13:20:31.670255] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2023-02-02-13:20:31.670567] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:31.798437] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:330 ==> [2023-02-02-13:20:31.801947] Checking existence of file://$spack/../spack.mirror/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-02-02-13:20:31.816477] Failure reading URL: <urlopen error [Errno 2] No such file or directory: '/../spack.mirror/build_cache/index.json'>
lib/spack/spack/util/web.py:330 ==> [2023-02-02-13:20:31.816881] Checking existence of file:///usr/projects/shavano/spack-environments/spack.mirror/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-02-02-13:20:31.817527] Failure reading URL: <urlopen error [Errno 2] No such file or directory: '/usr/projects/shavano/spack-environments/spack.mirror/build_cache/index.json'>
lib/spack/spack/util/web.py:330 ==> [2023-02-02-13:20:31.817920] Checking existence of https://pe-serve.lanl.gov/spack-mirror/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-02-02-13:20:31.829914] Failure reading URL: HTTP Error 404: Not Found
lib/spack/spack/util/web.py:330 ==> [2023-02-02-13:20:31.830419] Checking existence of https://mirror.spack.io/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-02-02-13:20:31.986461] Failure reading URL: HTTP Error 404: Not Found
lib/spack/spack/config.py:1007 ==> [2023-02-02-13:20:36.784806] Reading config from file /usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/ENV/INTEL/compilers.yaml
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.830384] UNKNOWN SYMBOL: attr("elfutils", elf)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.832772] UNKNOWN SYMBOL: attr("libunwind", unwind)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.837546] UNKNOWN SYMBOL: attr("intel-oneapi-tbb", tbb)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.839760] UNKNOWN SYMBOL: attr("bison", yacc)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.844838] UNKNOWN SYMBOL: attr("mpich", mpi)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.846248] UNKNOWN SYMBOL: attr("util-linux-uuid", uuid)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.862556] UNKNOWN SYMBOL: attr("libiconv", iconv)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.876551] UNKNOWN SYMBOL: attr("libjpeg-turbo", jpeg)
lib/spack/spack/solver/asp.py:2359 ==> [2023-02-02-13:22:04.894872] UNKNOWN SYMBOL: attr("pkgconf", pkgconfig)
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.507285] Ordered hashes [py-numpy]: py-numpy/140/873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.520990] Ordered hashes [py-numpy]: py-numpy/140/873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.521974] Ordered hashes [py-pythran]: py-pythran/933/b427dcaaa74ed4dfa39c58819e446e86055b65648826a101c08634d3c0be1f95
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.578568] Ordered hashes [paraview]: paraview/106/acb38051dc025dd4d74444c26014141fa8fd3eed4b258e8d4dcf4bb421d19de5
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.579773] Ordered hashes [glew]: glew/860/7992e525975b7e5e9f90ee5b8eece31a98719dc604228b8064cf851568ebf202
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.581002] Ordered hashes [mesa]: mesa/601/ee737d105aac4a9eacbbd504aee44c58b05978e0f2a42f2de088550878219ea3
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.583283] Ordered hashes [llvm]: llvm/125/637916895d45c8abcf308579de41d3b71586794128ab8741238d24208612d0cf, llvm/128/d85ef51601ba51d86241f3b4f0265e385ad2653e7b8a739319427ffc7cc57816, llvm/129/f920173d0258c934f246fcee65864bcbe9dcb1be32d4298f9b6323c364919b99
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.584465] Ordered hashes [py-numpy]: py-numpy/140/873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.599509] Ordered hashes [cta]: cta/935/cb354586f5515e1d5417ea4c0be778f4379182f8583af4c6dfa5d61de3690254
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.600530] Ordered hashes [draco]: draco/772/72d324109ee24bd0c41a107119f34afbaf41b578332d8e65b1a1a615031931f2
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.602024] Ordered hashes [superlu-dist]: superlu-dist/729/8da9e21f724e8f11a5782960cc0322e12f724bf93cead7df517901a788ea3d61
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.611276] Ordered hashes [draco]: draco/772/72d324109ee24bd0c41a107119f34afbaf41b578332d8e65b1a1a615031931f2
lib/spack/spack/spec.py:2871 ==> [2023-02-02-13:22:05.614328] Ordered hashes [hypre]: hypre/91/6e3336b1d62155f6350dfe42b0f9ea25d4fa0af60c7e540959139deb93a26059
lib/spack/spack/main.py:1007 ==> [2023-02-02-13:22:08.074665] UnsatisfiableSpecError: eospac compiler 'intel@2021.2.0' incompatible with 'target=mic_knl'
lib/spack/spack/error.py:54 ==> [2023-02-02-13:22:08.075657] Error: eospac compiler 'intel@2021.2.0' incompatible with 'target=mic_knl'
Traceback (most recent call last):
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/environment/environment.py", line 1280, in concretize
    return self._concretize_together_where_possible(tests=tests)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/environment/environment.py", line 1309, in _concretize_together_where_possible
    for result in solver.solve_in_rounds(self.user_specs, tests=tests):
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/solver/asp.py", line 2566, in solve_in_rounds
    setup, input_specs, reuse=reusable_specs, output=output
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/solver/asp.py", line 761, in solve
    self.handle_error(msg, *args)
  File "/usr/projects/shavanodev/dwg/SE/TKNLI/2.3.0/spack/lib/spack/spack/solver/asp.py", line 655, in handle_error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: eospac compiler 'intel@2021.2.0' incompatible with 'target=mic_knl'
```

### Information on your system

```console
% spack debug report
* **Spack:** 0.20.0.dev0 (d192dab5a1a1a103c84ebef4b8cadd8180658189)
* **Python:** 3.6.15
* **Platform:** cray-sles15-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by DarylGrunau** [comment]
Perusing the commits between `0.18.0` and `0.20.0.dev0` that have KNL relevance I found PR #34609.  In fact making the following mod enables the concretization to complete as expected:
```patch
diff --git a/lib/spack/external/archspec/json/cpu/microarchitectures.json b/lib/spack/external/archspec/json/cpu/microarchitectures.json
index b63149fc4b..90f9d2ce57 100644
--- a/lib/spack/external/archspec/json/cpu/microarchitectures.json
+++ b/lib/spack/external/archspec/json/cpu/microarchitectures.json
@@ -961,7 +961,7 @@
         ],
         "intel": [
           {
-            "versions": "18.0:2021.2",
+            "versions": "18.0:2021.2.0",
             "name": "knl",
             "flags": "-march={name} -mtune={name}"
           }
```
Why?  This looks like a completely fine version range to me (other than the fact that Intel has changed their versioning scheme from 2-digit years to 4-digit specifiers).  Is this a bug in the range processor?

**Comment by DarylGrunau** [comment]
Mentioning @alalazo and @haampie who were part of #34609.
