### ISSUE TITLE
Can't build py-torch with nccl and cuda variant

### ISSUE THREAD

**Issue by smehta99** [LLNL/spack#35374]
### Steps to reproduce

Trying to build py-torch with cuda and nccl capability but I am getting an error.
```console
spack spec py-torch +nccl +cuda cuda_arch=80 ^cuda@11.6.0 ^cray-mpich@8.1.21
```
I added these two lines to `lib/spack/spack/spec` file 
```python
2767         import pprint
2768         pprint.pprint(self.to_dict())
```
and was able to see that the `cuda_arch` does get passed along:
```console
{'spec': {'_meta': {'version': 3},                                                                                                           
          'nodes': [{'concrete': False,                                                                                                      
                     'dependencies': [{'hash': 'dcsskac4grvqskhvztsrb7jtvf2vwcmh',                                                           
                                       'name': 'cray-mpich',                                                                                 
                                       'type': []},                                                                                          
                                      {'hash': 'xqhfeju3vu2uhfczd7r4oloqemlor52y',                                                           
                                       'name': 'cuda',                                                                                       
                                       'type': []}],                                                                                         
                     'hash': 'cqjae7elcdt52mze64n52qmjh3lybcxf',                                                                             
                     'name': 'py-torch',                                                                                                     
                     'parameters': {'cuda': True,                                                                                            
                                    'cuda_arch': ['80'],                                                                                     
                                    'nccl': True},                                                                                           
                     'versions': [':']},                                                                                                     
                    {'concrete': False,                                                                                                      
                     'hash': 'dcsskac4grvqskhvztsrb7jtvf2vwcmh',                                                                             
                     'name': 'cray-mpich',                                                                                                   
                     'version': '8.1.21'},                                                                                                   
                    {'concrete': False,
                     'hash': 'xqhfeju3vu2uhfczd7r4oloqemlor52y',
                     'name': 'cuda',
                     'version': '11.6.0'}]}}
```
Spack command with debug option
```console
==> [2023-02-07-12:35:43.121206] Imported spec from built-in commands                                                                        
==> [2023-02-07-12:35:43.122644] Imported spec from built-in commands                                                                        
==> [2023-02-07-12:35:43.129189] Reading config from file /users/smehta/spack/etc/spack/defaults/config.yaml                 
==> [2023-02-07-12:35:43.200680] Reading config from file /users/smehta/spack/etc/spack/defaults/bootstrap.yaml              
==> [2023-02-07-12:35:43.234355] Reading config from file /users/smehta/spack/etc/spack/defaults/repos.yaml                  
==> [2023-02-07-12:35:43.247265] Reading config from file /users/smehta/spack/etc/spack/defaults/config.yaml                 
==> [2023-02-07-12:35:43.321454] DATABASE LOCK TIMEOUT: 3s                                                                                   
==> [2023-02-07-12:35:43.321573] PACKAGE LOCK TIMEOUT: No timeout                                                                            
==> [2023-02-07-12:35:43.324496] DATABASE LOCK TIMEOUT: 3s                                                                                   
==> [2023-02-07-12:35:43.324596] PACKAGE LOCK TIMEOUT: No timeout                                                                            
==> [2023-02-07-12:35:43.324740] [BOOTSTRAP CONFIG SCOPE] name=_builtin                                                                      
==> [2023-02-07-12:35:43.325770] Reading config from file /users/smehta/spack/etc/spack/defaults/bootstrap.yaml              
==> [2023-02-07-12:35:43.343523] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/users/smehta/spack/etc/spack/defaults         
==> [2023-02-07-12:35:43.343608] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/users/smehta/spack/etc/spack/defaults/li
nux                                                                                                                                          
==> [2023-02-07-12:35:43.343679] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/users/smehta/.spack/bootstrap/config                         
==> [2023-02-07-12:35:43.343733] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/users/smehta/.spack/bootstrap/config/linux             
==> [2023-02-07-12:35:43.346501] Reading config from file /users/smehta/.spack/bootstrap/config/linux/compilers.yaml                         
==> [2023-02-07-12:35:43.439751] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64                                                   
==> [2023-02-07-12:35:43.446142] Reading config from file /users/smehta/spack/etc/spack/defaults/bootstrap.yaml              
==> [2023-02-07-12:35:43.477150] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'       
==> [2023-02-07-12:35:46.584347] Reading config from file /users/smehta/spack/etc/spack/defaults/config.yaml                 
==> [2023-02-07-12:35:46.775331] Reading config from file /users/smehta/spack/etc/spack/defaults/modules.yaml                
==> [2023-02-07-12:35:46.813787] Reading config from file /users/smehta/spack/etc/spack/defaults/linux/modules.yaml          
==> [2023-02-07-12:35:47.170536] Reading config from file /users/smehta/spack/etc/spack/defaults/packages.yaml               
==> [2023-02-07-12:35:47.290785] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-02-07-12:35:47.305940] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-02-07-12:35:47.306042] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-02-07-12:35:47.542539] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/p
rqkzynv2nwko5mktitebgkeumuxkveu" provides the "clingo" Python module
==> [2023-02-07-12:35:47.544212] Reading config from file /users/smehta/spack/etc/spack/defaults/concretizer.yaml
==> [2023-02-07-12:35:47.559146] Reading config from file /users/smehta/spack/etc/spack/defaults/repos.yaml
==> [2023-02-07-12:35:47.803915] Reading config from file /users/smehta/spack/etc/spack/defaults/packages.yaml
==> [2023-02-07-12:35:47.894431] Reading config from file /users/smehta/spack/etc/spack/packages.yaml
==> [2023-02-07-12:35:48.070465] Reading config from file /users/smehta/spack/etc/spack/defaults/config.yaml
==> [2023-02-07-12:35:48.132602] Reading config from file /users/smehta/spack/etc/spack/defaults/mirrors.yaml
==> [2023-02-07-12:35:48.136987] Reading config from file /users/smehta/.spack/mirrors.yaml
==> [2023-02-07-12:35:48.187306] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2023-02-07-12:35:48.353556] Failure reading URL: HTTP Error 404: Not Found
==> [2023-02-07-12:35:54.360431] Reading config from file /users/smehta/.spack/linux/compilers.yaml
==> [2023-02-07-12:36:26.157035] SpackError: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus
==> [2023-02-07-12:36:26.157162] Error: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus
Traceback (most recent call last):
  File "/users/smehta/spack/lib/spack/spack/cmd/__init__.py", line 224, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/users/smehta/spack/lib/spack/spack/spec.py", line 2793, in concretize
    self._new_concretize(tests)
  File "/users/smehta/spack/lib/spack/spack/spec.py", line 2768, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/users/smehta/spack/lib/spack/spack/solver/asp.py", line 2529, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/users/smehta/spack/lib/spack/spack/solver/asp.py", line 761, in solve
    self.handle_error(msg, *args)
  File "/users/smehta/spack/lib/spack/spack/solver/asp.py", line 655, in handle_error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/smehta/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/users/smehta/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/users/smehta/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/users/smehta/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/users/smehta/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/users/smehta/spack/lib/spack/spack/cmd/__init__.py", line 239, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus

### Error message

```console
==> Error: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus
```

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
By default, variants only apply to the root spec, not to all specs recursively. You have a few options to fix this. You can pass the variant recursively (note == instead of =):
```console
$ spack spec py-torch cuda_arch==80
```
or set the following in your `packages.yaml`:
```yaml
packages:
  all:
    variants: cuda_arch=80

**Comment by smehta99** [comment]
Hi! 

I tried the first way with the command: 
```
spack spec py-torch +nccl +cuda cuda_arch==80 ^cuda@11.6.0 ^cray-mpich@8.1.21
```
but got an `Error : NCCL requires CUDA`
also tried:
```
spack spec py-torch +nccl ++cuda cuda_arch==80 ^cuda@11.6.0 ^cray-mpich@8.1.21
```
then got an error saying `Error: Must specify CUDA compute capabilities of your GPU, see https://developer.nvidia.com/cuda-gpus `

but putting it in `packages.yaml` file seems to have worked. Thank you! I am sure I am doing something wrong with the commands that's why I am getting this error but other way worked.

**Comment by adamjstewart** [comment]
Hmm, not sure why you would see that error with == unless one of the packages named the variant differently. But glad it's working with `packages.yaml`!
