### ISSUE TITLE
ImportError: bad magic number in 'jsonschema': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by vkarak** [LLNL/spack#35407]
### Steps to reproduce

Simply running `spack` after pulling the latest `develop`.

### Error message

```console
Traceback (most recent call last):
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 902, in _main
    sys.stdout.write(parser.format_help(level=args.help))
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 368, in format_help
    return self.format_help_sections(level)
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 215, in format_help_sections
    add_all_commands(self)
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 125, in add_all_commands
    for cmd in spack.cmd.all_commands():
  File "/Users/karakasv/local/spack/lib/spack/spack/cmd/__init__.py", line 90, in all_commands
    command_paths += spack.extensions.get_command_paths()  # Extensions
  File "/Users/karakasv/local/spack/lib/spack/spack/extensions.py", line 118, in get_command_paths
    extension_paths = get_extension_paths()
  File "/Users/karakasv/local/spack/lib/spack/spack/extensions.py", line 110, in get_extension_paths
    extension_paths = spack.config.get("config:extensions") or []
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 916, in get
    return config.get(path, default, scope)
  File "/Users/karakasv/local/spack/lib/spack/llnl/util/lang.py", line 826, in __getattr__
    return getattr(self.instance, name)
  File "/Users/karakasv/local/spack/lib/spack/llnl/util/lang.py", line 816, in instance
    self._instance = self.factory()
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 789, in _config
    builtin = InternalConfigScope("_builtin", config_defaults)
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 329, in __init__
    validate({section: dsec}, section_schemas[section])
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 957, in validate
    import jsonschema
ImportError: bad magic number in 'jsonschema': b'\x03\xf3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/karakasv/local/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/Users/karakasv/local/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/Users/karakasv/local/spack/lib/spack/spack/main.py", line 1023, in main
    if spack.config.get("config:debug") or SHOW_BACKTRACE:
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 916, in get
    return config.get(path, default, scope)
  File "/Users/karakasv/local/spack/lib/spack/llnl/util/lang.py", line 826, in __getattr__
    return getattr(self.instance, name)
  File "/Users/karakasv/local/spack/lib/spack/llnl/util/lang.py", line 816, in instance
    self._instance = self.factory()
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 789, in _config
    builtin = InternalConfigScope("_builtin", config_defaults)
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 329, in __init__
    validate({section: dsec}, section_schemas[section])
  File "/Users/karakasv/local/spack/lib/spack/spack/config.py", line 957, in validate
    import jsonschema
ImportError: bad magic number in 'jsonschema': b'\x03\xf3\r\n'
```

### Information on your system

`spack debug report` also crashes, but here are the first lines:

```console
* **Spack:** 0.20.0.dev0 (7f1467e795b1cab8b4855e019910c509896ea0e1)
* **Python:** 3.10.7
* **Platform:** darwin-ventura-skylake
<stacktrace as above>
```

I'm on fish shell. I also did a bisect and found that this regression was introduced by 5175189412.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by vkarak** [comment]
Cleaning completely my local checkout or pull afresh, the problem disappears.

**Comment by haampie** [comment]
Yeah, it happens due to out-of-date pycache
