### ISSUE TITLE
Issue with extracting tar file during package installation

### ISSUE THREAD

**Issue by uturuncoglu** [LLNL/spack#35476]
### Steps to reproduce

I am trying to install `libxml2` using `spack --color always -e . install -j3 --deprecated --no-checksum` under Docker container `22.04.1 LTS (Jammy Jellyfish)` but I am getting following error,

```
==> Installing libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes
==> libxml2 exists in binary cache but with different hash
==> No binary for libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes found: installing from source
==> Using cached archive: /test/.spack-ci/source_cache/_source-cache/archive/5d/5d2cc3d78bec3dbe212a9d7fa629ada25a7da928af432c93060ff5c17ee28a9c.tar.xz
==> Using cached archive: /test/.spack-ci/source_cache/_source-cache/archive/96/96151685cec997e1f9f3387e3626d61e6284d4d6e66e0e440c209286c03e9cc7.tar.gz
/test/.spack-ci/view/bin/tar: Child died with signal 4
/test/.spack-ci/view/bin/tar: Error is not recoverable: exiting now
==> Error: ProcessError: Command exited with status 2:
    '/test/.spack-ci/view/bin/tar' '-oxf' '/tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz'
```

The command ` /usr/bin/tar -oxf /tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz` works without any issue outside of the spack. So, it seem that tar file is fine. I also tried to install `tar` with spack and set PATH to point it but still same issue. 

### Error message

```
lib/spack/spack/fetch_strategy.py:462 ==> [2023-02-13-22:25:39.953109] Staging archive: /tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz
lib/spack/spack/util/executable.py:195 ==> [2023-02-13-22:25:39.954797] '/test/.spack-ci/view/bin/tar' '-oxf' '/tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz'
/test/.spack-ci/view/bin/tar: Child died with signal 4
/test/.spack-ci/view/bin/tar: Error is not recoverable: exiting now
lib/spack/spack/error.py:54 ==> [2023-02-13-22:25:39.973092] Error: ProcessError: Command exited with status 2:
    '/test/.spack-ci/view/bin/tar' '-oxf' '/tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz'
Traceback (most recent call last):
  File "/test/spack/lib/spack/spack/build_environment.py", line 1033, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/test/spack/lib/spack/spack/installer.py", line 2087, in build_process
    return installer.run()
  File "/test/spack/lib/spack/spack/installer.py", line 1924, in run
    self.pkg.do_patch()
  File "/test/spack/lib/spack/spack/package_base.py", line 1485, in do_patch
    self.do_stage()
  File "/test/spack/lib/spack/spack/package_base.py", line 1471, in do_stage
    self.stage.expand_archive()
  File "/test/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/test/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/test/spack/lib/spack/spack/stage.py", line 625, in expand_archive
    self.fetcher.expand()
  File "/test/spack/lib/spack/spack/fetch_strategy.py", line 85, in wrapper
    return fun(self, *args, **kwargs)
  File "/test/spack/lib/spack/spack/fetch_strategy.py", line 482, in expand
    decompress(self.archive_file)
  File "/test/spack/lib/spack/spack/util/compression.py", line 89, in _untar
    tar(archive_file)
  File "/test/spack/lib/spack/spack/util/executable.py", line 238, in __call__
    raise ProcessError("Command exited with status %d:" % proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    '/test/.spack-ci/view/bin/tar' '-oxf' '/tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz'
lib/spack/spack/installer.py:1472 ==> [2023-02-13-22:25:39.973815] Flagging libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes as failed: ProcessError: Command exited with status 2:
    '/test/.spack-ci/view/bin/tar' '-oxf' '/tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz'
```

### Information on your system

* **Spack:** 0.20.0.dev0 (83743d32adb1ea1166248a4f64b93f5d4694c502)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by uturuncoglu** [comment]
BTW, the same code works under Github action without any issue but I think those runners are using different infrastructure.

**Comment by uturuncoglu** [comment]
Is there anybody could help me about solving this issue. I tried different things but I could not find any solution. Maybe there is something missing under this environment that prevents Spack to use tar or it could be package dependent not sure.

**Comment by uturuncoglu** [comment]
I also realized that the error message seems confusing but I tried both the tar installed with spack (`/test/.spack-ci/view/bin/tar`) and also system provided (`/usr/bin/tar`) and both has same issue.

**Comment by haampie** [comment]
Can you try to run it by hand from the build-env?

```
$ spack build-env <the thing you're building> -- bash
# which tar
# tar ...
```

Edit: looks like signal 4 is Illegal Instruction. Maybe the binaries were targeted for a newer arch? (would be weird with /usr/bin/tar, though, but maybe tar picks up a Spack-built xz tool). If you don't control the arch you're running on, just set it to something generic:

```yaml
packages:
    all:
        require: target=x86_64
```

**Comment by uturuncoglu** [comment]
@haampie Thanks for your help. 

I issue the following command `spack build-env libxml2 -- bash`. It did not change the shell prompt like yours (I am not sure why) and its output is something like 

```
root@f028b48f2a4e:/test# spack build-env libxml2 -- bash
root@f028b48f2a4e:/test# which tar
/usr/bin/tar
root@f028b48f2a4e:/test# tar ...
tar: invalid option -- '.'
Try 'tar --help' or 'tar --usage' for more information.
```

Actually, I am using following `spack.yaml` file and target is fixed in there,

```
spack:
  concretizer:
    targets:
      granularity: generic
      host_compatible: false
    unify: when_possible
  specs:
  - zlib@1.2.12 target=x86_64_v4
  - esmf@8.5.0b10+parallelio~xerces target=x86_64_v4
  - parallelio@2.5.10+pnetcdf target=x86_64_v4
  packages:
    all:
      target: [x86_64_v4]
      compiler: [gcc@11.3.0]
  view: /test/.spack-ci/view
  config:
    source_cache: /test/.spack-ci/source_cache
    misc_cache: /test/.spack-ci/misc_cache
    test_cache: /test/.spack-ci/test_cache
    install_tree:
      root: /test/.spack-ci/opt
  compilers:
  - compiler:
      spec: gcc@11.3.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu22.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

This is required otherwise I am getting issue with different GitHub runners and Spack is trying to install again already cached installations. So, this fixes the target.

**Comment by uturuncoglu** [comment]
@haampie The command `/usr/bin/tar -oxf /tmp/root/spack-stage/spack-stage-libxml2-2.10.3-uvxmjosgyvk7c4k5z4nhu4n2rn62jfes/libxml2-2.10.3.tar.xz` also works. BTW, I think that it change the prompt but it is not recognizable in my case.

**Comment by haampie** [comment]
I just used # to mean: in the new shell run this and that.

So, if you're using x86_64_v4 you support only avx512 machines effectively. It's better to go for x86_64 or probably x86_64_v2 is widely supported too. Spack needs to be able to run its build deps on the host arch.

**Comment by uturuncoglu** [comment]
@haampie Okay. Let me try with it. I'll update you. Thanks.

**Comment by uturuncoglu** [comment]
@haampie Okay. The error related with tar is gone but now I am getting following error when I try to build `netcdf-c`. I tried to hack `package.py` of `netcdf-c` by adding `--disable-libxml2`. It compiled but then I got error when I try to read a netcdf file. So, probably `--disable-libxml2` disable some feature that I need. I am not sure why it could not find `xml2-config`. Any idea?

```
==> No patches needed for netcdf-c
==> netcdf-c: Executing phase: 'autoreconf'
==> netcdf-c: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-netcdf-c-4.9.1-upm5ikzjoq4uqdyvcig6o7mz6stcngbo/spack-src/configure' '--prefix=/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/netcdf-c-4.9.1-upm5ikzjoq4uqdyvcig6o7mz6stcngbo' '--enable-v2' '--enable-utilities' '--enable-static' '--enable-largefile' '--enable-netcdf-4' '--disable-fsync' '--enable-dynamic-loading' '--enable-shared' '--disable-dap' '--enable-nczarr' '--disable-byterange' 'ac_cv_lib_curl_curl_easy_setopt=no' '--enable-parallel4' '--disable-jna' '--disable-pnetcdf' 'CC=/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/openmpi-4.1.4-bebvds4cl5unuzfke3ksjmioayio6hrf/bin/mpicc' '--disable-hdf4' '--with-plugin-dir=/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/netcdf-c-4.9.1-upm5ikzjoq4uqdyvcig6o7mz6stcngbo/plugins' 'CFLAGS=-O2 -fPIC' 'CPPFLAGS=-I/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/hdf5-1.14.0-7lnj4liru7nxypz4hmmlo4ui7q5ltqhn/include -I/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/zstd-1.5.2-n6bk6xum5logdrse5crnyb3iwqwdlhtt/include' 'LDFLAGS=-L/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/hdf5-1.14.0-7lnj4liru7nxypz4hmmlo4ui7q5ltqhn/lib -L/test/.spack-ci/opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/zstd-1.5.2-n6bk6xum5logdrse5crnyb3iwqwdlhtt/lib' 'LIBS='

1 error found in build log:
     66    checking whether CURLINFO_RESPONSE_CODE is defined... no
     67    checking whether CURLOPT_BUFFERSIZE is defined... no
     68    checking whether CURLOPT_TCP_KEEPALIVE is defined... no
     69    checking whether libcurl is version 7.66 or later?... no
     70    checking whether to search for and use external libxml2... yes
     71    checking for xml2-config... no
  >> 72    configure: error: Cannot find xml2-config utility. Either install the libxml2 development package, or re-run configure with --disable-libxml2 to use the bundled 
           xml2 parser

See build log for details:
  /tmp/root/spack-stage/spack-stage-netcdf-c-4.9.1-upm5ikzjoq4uqdyvcig6o7mz6stcngbo/spack-build-out.txt
```

**Comment by uturuncoglu** [comment]
I also tried to find it

```
root@f028b48f2a4e:/test# find .spack-ci/. -name "*xml2-config*"
.spack-ci/./._view/b3pnzscxblqzwyxg7cuegbb7jtxgumny/share/man/man1/xml2-config.1
.spack-ci/./._view/b3pnzscxblqzwyxg7cuegbb7jtxgumny/bin/xml2-config
.spack-ci/./._view/b3pnzscxblqzwyxg7cuegbb7jtxgumny/lib/cmake/libxml2/libxml2-config.cmake
.spack-ci/./opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/libxml2-2.10.3-sgjyyommtycg5wurqlhpl26cdg3y3ujd/share/man/man1/xml2-config.1
.spack-ci/./opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/libxml2-2.10.3-sgjyyommtycg5wurqlhpl26cdg3y3ujd/bin/xml2-config
.spack-ci/./opt/linux-ubuntu22.04-x86_64/gcc-11.3.0/libxml2-2.10.3-sgjyyommtycg5wurqlhpl26cdg3y3ujd/lib/cmake/libxml2/libxml2-config.cmake
```

It seems it is not copied to `.spack-ci/view` directory and spack could not find it.

**Comment by haampie** [comment]
You don't need a view to build anything in Spack, Spack sets `PATH=<libxml prefix>/bin:...` in the build environment.

Can you again do `spack build-env netcdf-c -- bash` and run `xml2-config`?

**Comment by uturuncoglu** [comment]
I run the command and it gave error like following which I don't know why

```
root@f028b48f2a4e:/test# spack build-env netcdf-c -- bash 
==> Error: Query of package 'openmpi' for 'headers' failed
	prefix : /test/spack/opt/spack/linux-ubuntu22.04-haswell/gcc-11.3.0/openmpi-4.1.4-tf3j7lwyvoi53y6ibsz3nls2hzlhdulu
```

I could find xml2-config outside of `spack build-env` and it is under `/test/.spack-ci/view/bin/xml2-config`.

**Comment by uturuncoglu** [comment]
@haampie Maybe I could try with `x86_64_v2`.

**Comment by haampie** [comment]
If you have an environment, do it like `spack -e <your env> build-env netcdf-c -- bash` and it will select the spec from the env instead of concretize it oustside the env to something different.

**Comment by uturuncoglu** [comment]
@haampie Thanks for your help. After setting target as `target=x86_64` and installing `libxml2-dev` using `apt-get install libxml2-dev` command. I could able to build without any issue. I think installing `libxml2-dev` package fix the issue related to the `netcdf-c`. I am still not sure why Spack had issue with it.
