### ISSUE TITLE
Cache file useless in offline installation when fetching from a git repo

### ISSUE THREAD

**Issue by Synlvejo** [LLNL/spack#35506]
### Steps to reproduce

Hello, I'm using Spack to install some softwares in a computer without Internet.
When using Spack in a computer with Internet, it's a really usefull tool. Unfortunately, it's very strange in this situation, maybe it's because of my unfamiliarity.

Firstly, I found that ```spack mirror create  package``` will not  iterate through all of Spack’s packages and download the safe ones into a directory structure and just download the package, at least for *Hpctoolkit*, unless adding the ```--denpendencies``` parameter.
Secondly, it was not working when I set the mirror list using ```spack mirror add``` unless I put all the mirrors in ```$SPACH/var/spack/cache``` folder.

The two problems I mentioned can be solved by the two "unless", but there are another two problems I can't.
Third is a bootstrap problem. Because I was using spack to install software offline, I was following the "Mirrors(mirros.yaml)" section to use a mirror way. But ```spack bootstrap status``` command print this message:
```console
Spack v0.20.0.dev0 - python@3.6

[FAIL] Core Functionalities
  [B] MISSING "clingo": required to concretize specs

[PASS] Binary packages

Spack will take care of bootstrapping any missing dependency marked as [B]. Dependencies marked as [-] are instead required to be found on the system
```
Even so, most packages can be installed, but there is one exception which is the fourth problem.
When I use ```spack solve zlib```, spack will install the *clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l*, which is fetched from a github url ```https://github.com/potassco/clingo.git/```. I tried to make a clingo dir, clingo-bootstrap-spack dir with the ```<package-name> - <version> . <extension>``` format and put the clingo dir got by ```git clone``` under the cache dir, but it still reply the FetchError. Just like this:
```console
==> Installing clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
==> No binary for clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l found: installing from source
fatal: unable to access 'https://github.com/potassco/clingo.git/': Failed connect to github.com:443; Connection timed out
==> Error: FetchError: All fetchers failed for spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l

/gs/home/xzbo/spack/lib/spack/spack/package_base.py:1450, in do_fetch:
       1447
       1448        self.stage.create()
       1449        err_msg = None if not self.manual_download else self.download_instr
  >>   1450        start_time = time.time()
       1451        self.stage.fetch(mirror_only, err_msg=err_msg)
       1452        self._fetch_time = time.time() - start_time
       1453


==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
github-actions-v0.4 raised RuntimeError: The binary index is empty
github-actions-v0.3 raised RuntimeError: The binary index is empty
spack-install raised InstallError: Terminating after first install failure: FetchError: All fetchers failed for spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
Run `spack --debug ...` for more detailed errors

```
So if I can know how to install this dependency offline or how to migrate a Spack with correct bootstrap status to a offline computer? Thanks.

### Error message

```console
$ cd var/spack/cache/
$ pwd
/home/xzbo/spack/var/spack/cache
$ ls clingo
clingo-5.6.2.tar.gz
$ ls clingo-bootstrap-spack
clingo-bootstrap-spack-5.6.2.tar.gz
$ ls clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l/
app         cmake           examples    libgringo     libreify    MANIFEST.in     scratch      TODO.md
CHANGES.md  CMakeLists.txt  INSTALL.md  libluaclingo  LICENSE.md  pyproject.toml  setup.py
clasp       doc             libclingo   libpyclingo   Makefile    README.md       third_party

$spack --debug --spacktrace solve zlib
......
[+] /gs/home/xzbo/.spack/bootstrap/store/linux-centos7-cascadelake/gcc-9.4.0/cmake-3.25.2-l5fd3az6moviud43xk2co6gj7gnp4qux
lib/spack/spack/installer.py:1606 ==> [2023-02-16-16:10:06.918484] Processing clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l: task=priority=0, status=dequeued, start=1676535006.7788413, #dependencies=4
lib/spack/spack/installer.py:1087 ==> [2023-02-16-16:10:06.919705] Acquiring a write lock on clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l with timeout 1.000ns
lib/spack/spack/installer.py:1120 ==> [2023-02-16-16:10:06.920501] clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l is now write locked
lib/spack/spack/installer.py:1254 ==> [2023-02-16-16:10:06.936032] Installing clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/installer.py:420 ==> [2023-02-16-16:10:06.937784] Searching for binary cache of clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/stage.py:329 ==> [2023-02-16-16:10:06.940523] Creating stage lock spack-stage-t1r43l55
lib/spack/spack/util/web.py:330 ==> [2023-02-16-16:10:06.960949] Checking existence of https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json.sig
lib/spack/spack/util/web.py:358 ==> [2023-02-16-16:10:47.030531] Failure reading URL: <urlopen error timed out>
lib/spack/spack/fetch_strategy.py:346 ==> [2023-02-16-16:10:47.031426] URL does not exist: https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json.sig
lib/spack/spack/stage.py:522 ==> [2023-02-16-16:10:47.032285] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json.sig
lib/spack/spack/stage.py:508 ==> [2023-02-16-16:10:47.032916] Fetching from https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json.sig failed.
lib/spack/spack/stage.py:329 ==> [2023-02-16-16:10:47.034097] Creating stage lock spack-stage-62eyl7u6
lib/spack/spack/util/web.py:330 ==> [2023-02-16-16:10:47.035165] Checking existence of https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json
lib/spack/spack/util/web.py:358 ==> [2023-02-16-16:11:27.083792] Failure reading URL: <urlopen error timed out>
lib/spack/spack/fetch_strategy.py:346 ==> [2023-02-16-16:11:27.084694] URL does not exist: https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json
lib/spack/spack/stage.py:522 ==> [2023-02-16-16:11:27.085592] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json
lib/spack/spack/stage.py:508 ==> [2023-02-16-16:11:27.086340] Fetching from https://mirror.spack.io/build_cache/linux-centos7-x86_64-gcc-9.4.0-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l.spec.json failed.
lib/spack/spack/installer.py:315 ==> [2023-02-16-16:11:27.087336] No binary for clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l found: installing from source
lib/spack/spack/installer.py:1427 ==> [2023-02-16-16:11:27.097824] Creating the installation directory /gs/home/xzbo/.spack/bootstrap/store/linux-centos7-x86_64/gcc-9.4.0/clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/util/executable.py:195 ==> [2023-02-16-16:11:27.220413] '/bin/git' '-C' '/gs/home/xzbo/spack' 'rev-parse' 'HEAD'
lib/spack/spack/compilers/__init__.py:797 ==> [2023-02-16-16:11:27.938995] [TOOLCHAIN] MATCH Gcc
lib/spack/spack/build_environment.py:450 ==> [2023-02-16-16:11:28.011398] Adding compiler bin/ paths: /gs/home/xzbo/spack/lib/spack/env /gs/home/xzbo/spack/lib/spack/env/case-insensitive /gs/home/xzbo/spack/lib/spack/env/gcc
lib/spack/spack/util/executable.py:195 ==> [2023-02-16-16:11:28.074972] '/usr/bin/python3.6' '-c' '
import json
from sysconfig import (
    get_config_vars,
    get_config_h_filename,
    get_makefile_filename,
    get_paths,
)

config = get_config_vars()
config['"'"'config_h_filename'"'"'] = get_config_h_filename()
config['"'"'makefile_filename'"'"'] = get_makefile_filename()
config.update(get_paths())

print(json.dumps(config))
'
lib/spack/spack/build_environment.py:788 ==> [2023-02-16-16:11:28.305168] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
lib/spack/spack/util/executable.py:195 ==> [2023-02-16-16:11:28.338088] '/opt/ohpc/pub/compiler/gcc/9.4.0/bin/g++' '-v' '/tmp/spack-implicit-link-infoivdbh6k_/main.c' '-o' '/tmp/spack-implicit-link-infoivdbh6k_/output'
lib/spack/spack/compiler.py:105 ==> [2023-02-16-16:11:29.094470] parsing implicit link info
lib/spack/spack/compiler.py:120 ==> [2023-02-16-16:11:29.096089] linker line:  /gs/software/ohpc/pub/compiler/gcc/9.4.0/libexec/gcc/x86_64-redhat-linux/9.4.0/collect2 -plugin /gs/software/ohpc/pub/compiler/gcc/9.4.0/libexec/gcc/x86_64-redhat-linux/9.4.0/liblto_plugin.so -plugin-opt=/gs/software/ohpc/pub/compiler/gcc/9.4.0/libexec/gcc/x86_64-redhat-linux/9.4.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccK87nVY.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-infoivdbh6k_/output /lib/../lib64/crt1.o /lib/../lib64/crti.o /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/crtbegin.o -L/gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0 -L/gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../.. /tmp/cc8pPotU.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/crtend.o /lib/../lib64/crtn.o
lib/spack/spack/compiler.py:136 ==> [2023-02-16-16:11:29.097055] linkdir: /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0
lib/spack/spack/compiler.py:136 ==> [2023-02-16-16:11:29.097905] linkdir: /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../../../lib64
lib/spack/spack/compiler.py:136 ==> [2023-02-16-16:11:29.098726] linkdir: /lib/../lib64
lib/spack/spack/compiler.py:136 ==> [2023-02-16-16:11:29.099552] linkdir: /usr/lib/../lib64
lib/spack/spack/compiler.py:136 ==> [2023-02-16-16:11:29.100363] linkdir: /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../..
lib/spack/spack/compiler.py:144 ==> [2023-02-16-16:11:29.101241] found raw link dirs: /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0, /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0/../../..
lib/spack/spack/compiler.py:154 ==> [2023-02-16-16:11:29.102218] found link dirs: /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib/gcc/x86_64-redhat-linux/9.4.0, /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib64, /lib64, /usr/lib64, /gs/software/ohpc/pub/compiler/gcc/9.4.0/lib
lib/spack/spack/stage.py:329 ==> [2023-02-16-16:11:29.112911] Creating stage lock spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/util/web.py:330 ==> [2023-02-16-16:11:29.153463] Checking existence of https://mirror.spack.io/_source-cache/git/potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz
lib/spack/spack/util/web.py:358 ==> [2023-02-16-16:12:09.208592] Failure reading URL: <urlopen error timed out>
lib/spack/spack/fetch_strategy.py:346 ==> [2023-02-16-16:12:09.209741] URL does not exist: https://mirror.spack.io/_source-cache/git/potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz
lib/spack/spack/stage.py:522 ==> [2023-02-16-16:12:09.210905] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz
lib/spack/spack/util/web.py:330 ==> [2023-02-16-16:12:09.212004] Checking existence of https://mirror.spack.io/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
lib/spack/spack/util/web.py:358 ==> [2023-02-16-16:12:49.261086] Failure reading URL: <urlopen error timed out>
lib/spack/spack/fetch_strategy.py:346 ==> [2023-02-16-16:12:49.261649] URL does not exist: https://mirror.spack.io/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
lib/spack/spack/stage.py:522 ==> [2023-02-16-16:12:49.262194] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
lib/spack/spack/fetch_strategy.py:856 ==> [2023-02-16-16:12:49.262713] Cloning git repository: https://github.com/potassco/clingo.git at commit 2a025667090d71b2c9dce60fe924feb6bde8f667
lib/spack/spack/util/executable.py:195 ==> [2023-02-16-16:12:49.263954] '/bin/git' '--version'
lib/spack/spack/util/executable.py:195 ==> [2023-02-16-16:12:49.273884] '/bin/git' '-c' 'advice.detachedHead=false' 'clone' 'https://github.com/potassco/clingo.git'
Cloning into 'clingo'...
fatal: unable to access 'https://github.com/potassco/clingo.git/': Failed connect to github.com:443; Connection timed out
lib/spack/spack/stage.py:522 ==> [2023-02-16-16:14:56.516665] ProcessError: Command exited with status 128:
    '/bin/git' '-c' 'advice.detachedHead=false' 'clone' 'https://github.com/potassco/clingo.git'
lib/spack/spack/stage.py:508 ==> [2023-02-16-16:14:56.518055] Fetching from https://mirror.spack.io/_source-cache/git/potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz failed.
lib/spack/spack/stage.py:508 ==> [2023-02-16-16:14:56.518949] Fetching from https://mirror.spack.io/clingo-bootstrap/clingo-bootstrap-spack.tar.gz failed.
lib/spack/spack/stage.py:508 ==> [2023-02-16-16:14:56.519792] Fetching from [git] https://github.com/potassco/clingo.git at commit 2a025667090d71b2c9dce60fe924feb6bde8f667 failed.
lib/spack/spack/error.py:54 ==> [2023-02-16-16:14:56.606299] Error: FetchError: All fetchers failed for spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l

/gs/home/xzbo/spack/lib/spack/spack/package_base.py:1450, in do_fetch:
       1447
       1448        self.stage.create()
       1449        err_msg = None if not self.manual_download else self.download_instr
  >>   1450        start_time = time.time()
       1451        self.stage.fetch(mirror_only, err_msg=err_msg)
       1452        self._fetch_time = time.time() - start_time
       1453


Traceback (most recent call last):
  File "/gs/home/xzbo/spack/lib/spack/spack/build_environment.py", line 1038, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/gs/home/xzbo/spack/lib/spack/spack/installer.py", line 2077, in build_process
    return installer.run()
  File "/gs/home/xzbo/spack/lib/spack/spack/installer.py", line 1914, in run
    self.pkg.do_patch()
  File "/gs/home/xzbo/spack/lib/spack/spack/package_base.py", line 1487, in do_patch
    self.do_stage()
  File "/gs/home/xzbo/spack/lib/spack/spack/package_base.py", line 1472, in do_stage
    self.do_fetch(mirror_only)
  File "/gs/home/xzbo/spack/lib/spack/spack/package_base.py", line 1451, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/gs/home/xzbo/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/gs/home/xzbo/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/gs/home/xzbo/spack/lib/spack/spack/stage.py", line 529, in fetch
    raise FetchError(err_msg or default_msg, None)
spack.util.web.FetchError: All fetchers failed for spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/installer.py:1462 ==> [2023-02-16-16:14:56.607816] Flagging clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l as failed: FetchError: All fetchers failed for spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/stage.py:329 ==> [2023-02-16-16:14:56.698383] Creating stage lock spack-stage-clingo-bootstrap-spack-u6pbkakxjn22qxuh6m2tv33j4qhm5g5l
lib/spack/spack/config.py:1007 ==> [2023-02-16-16:14:56.744105] Reading config from file /gs/home/xzbo/spack/etc/spack/defaults/config.yaml

```

### Information on your system

```console
* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
For the bootstrapping issue, did you try to follow:
- https://spack.readthedocs.io/en/latest/bootstrapping.html#creating-a-mirror-for-air-gapped-systems

?

**Comment by Synlvejo** [comment]
> d you try to foll

It confused me for a long time and I'm sorry I haven't searched the "ari gap" key word. It looks fine now. Thank you!

**Comment by alalazo** [comment]
Oh, no worries. Documentation is extensive, and the search on that is not always helpful :slightly_frowning_face: Glad this solved part of the issues.

**Comment by Synlvejo** [comment]
> Oh, no worries. Documentation is extensive, and the search on that is not always helpful 🙁 Glad this solved part of the issues.

Anyway, thanks a lot!
I will check the mirror list problem after my single job installation 🙁. I will add content if there is progress. Thanks again~
