### ISSUE TITLE
Spack fetch errors in build_stage when parallel fetch

### ISSUE THREAD

**Issue by Jordan474** [LLNL/spack#35782]
### Steps to reproduce

When fetching multiple times the same spec at the same time, sometimes there is an error.

I've seen this error regularly in my parallel deployments since at least spack 0.18 (running spack installs in multiple spack env depfile in parallel).

I was able to create a simpler reproducer with Spack 0.20:

To increase the chance of reproducing this bug, I create a spack-env to avoid having to re-concretize each time:

```sh
source share/spack/setup-env.sh

# Local mirror
# Using trilinos for its "large" archive to maybe increase the chance of reproducing the bug
spack mirror create -d $PWD/mymirror trilinos
spack mirror add --scope=site mymirror $PWD/mymirror

# Create and activate env so we concretize only once
spack env create --without-view testenv
spack env activate testenv
spack add trilinos
spack concretize -f

# Get trilinos spec hash
spec=$(spack spec --format '/{hash}')

export SPACK_BACKTRACE=1
```

Test loop: (retry from here if you didn't reproduce the error)

```sh
spack clean -sd
spack fetch $spec
spack fetch $spec & spack fetch $spec & wait
spack fetch $spec & spack fetch $spec & wait
```

(If I don't do the first `spack fetch` I don't seem to see the error... weird.)

### Error message

With spack 0.20, and this reproducer I see `FileExistsError` errors:

```txt
Traceback (most recent call last):
  File ".../git/github.com/spack/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File ".../git/github.com/spack/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File ".../git/github.com/spack/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File ".../git/github.com/spack/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File ".../git/github.com/spack/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File ".../git/github.com/spack/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File ".../git/github.com/spack/spack/lib/spack/spack/cmd/fetch.py", line 74, in fetch
    spec.package.do_fetch()
  File ".../git/github.com/spack/spack/lib/spack/spack/package_base.py", line 1449, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File ".../git/github.com/spack/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File ".../git/github.com/spack/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File ".../git/github.com/spack/spack/lib/spack/spack/stage.py", line 516, in fetch
    self.fetcher.fetch()
  File ".../git/github.com/spack/spack/lib/spack/spack/fetch_strategy.py", line 80, in wrapper
    return fun(self, *args, **kwargs)
  File ".../git/github.com/spack/spack/lib/spack/spack/fetch_strategy.py", line 556, in fetch
    symlink(path, filename)
  File ".../git/github.com/spack/spack/lib/spack/llnl/util/symlink.py", line 27, in symlink
    os.symlink(real_path, link_path)
FileExistsError: [Errno 17] File exists: '.../git/github.com/spack/spack/var/spack/cache/_source-cache/archive/0b/0bce7066c27e83085bc189bf524e535e5225636c9ee4b16291a38849d6c2216d.tar.gz' -> '/tmp/.../spack-stage/spack-stage-trilinos-13.0.1-2f4qdfzhkjzo5k3onespmu6ftgchqa6z/trilinos-release-13-0-1.tar.gz'
```

Another backtrace:

```txt
Traceback (most recent call last):
  File "/home/user/git/github.com/spack/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/home/user/git/github.com/spack/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/cmd/fetch.py", line 74, in fetch
    spec.package.do_fetch()
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/package_base.py", line 1449, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/stage.py", line 516, in fetch
    self.fetcher.fetch()
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/fetch_strategy.py", line 80, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/user/git/github.com/spack/spack/lib/spack/spack/fetch_strategy.py", line 553, in fetch
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/spack-stage/spack-stage-trilinos-13.0.1-2f4qdfzhkjzo5k3onespmu6ftgchqa6z/trilinos-release-13-0-1.tar.gz'
```

In the real world, with a slightly custom(*) spack 0.18 and 0.19, I also see some **other** `FileNotFoundError` error with `spack.fetch_strategy.ChecksumError` errors:

```txt
Traceback (most recent call last):
  File "/home/user/spack-0.19-custom/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/home/user/spack-0.19-custom/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/home/user/spack-0.19-custom/lib/spack/spack/cmd/fetch.py", line 77, in fetch
    spec.package.do_fetch()
  File "/home/user/spack-0.19-custom/lib/spack/spack/package_base.py", line 1457, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/home/user/spack-0.19-custom/lib/spack/spack/util/pattern.py", line 18, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/spack-0.19-custom/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/spack-0.19-custom/lib/spack/spack/stage.py", line 519, in fetch
    self.fetcher.fetch()
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 87, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 345, in fetch
    self._fetch_from_url(url)
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 358, in _fetch_from_url
    return self._fetch_curl(url)
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 87, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 500, in _fetch_curl
    fs.rename(partial_file, save_file)
  File "/home/user/spack-0.19-custom/lib/spack/spack/util/path.py", line 193, in path_filter_caller
    return func(*args, **kwargs)
  File "/home/user/spack-0.19-custom/lib/spack/llnl/util/filesystem.py", line 106, in rename
    os.rename(src, dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/user/spack019-cache/build_stage/spack-stage-trilinos-13.4.0-njar7kred6s2uugdxa6zigejye2bllwx/trilinos-release-13-4-0.tar.gz.part' -> '/tmp/user/spack019-cache/build_stage/spack-stage-trilinos-13.4.0-njar7kred6s2uugdxa6zigejye2bllwx/trilinos-release-13-4-0.tar.gz'
[1]  - 2297057 exit 1     spack fetch trilinos/njar7kr
==> Error: sha256 checksum failed for /tmp/user/spack019-cache/build_stage/spack-stage-trilinos-13.4.0-njar7kred6s2uugdxa6zigejye2bllwx/trilinos-release-13-4-0.tar.gz
Expected 39550006e059043b7e2177f10467ae2f77fe639901aee91cbc1e359516ff8d3e but got 8b97be6f00e986b8e3989457e804dce36466f2dcacd21be27737122a2eaa8d73
Traceback (most recent call last):
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/user/spack-0.19-custom/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/home/user/spack-0.19-custom/lib/spack/spack/cmd/fetch.py", line 77, in fetch
    spec.package.do_fetch()
  File "/home/user/spack-0.19-custom/lib/spack/spack/package_base.py", line 1461, in do_fetch
    self.stage.check()
  File "/home/user/spack-0.19-custom/lib/spack/spack/util/pattern.py", line 18, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/spack-0.19-custom/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/home/user/spack-0.19-custom/lib/spack/spack/stage.py", line 585, in check
    self.fetcher.check()
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 87, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/user/spack-0.19-custom/lib/spack/spack/fetch_strategy.py", line 564, in check
    raise ChecksumError(
spack.fetch_strategy.ChecksumError: sha256 checksum failed for /tmp/user/spack019-cache/build_stage/spack-stage-trilinos-13.4.0-njar7kred6s2uugdxa6zigejye2bllwx/trilinos-release-13-4-0.tar.gz
    Expected 39550006e059043b7e2177f10467ae2f77fe639901aee91cbc1e359516ff8d3e but got 8b97be6f00e986b8e3989457e804dce36466f2dcacd21be27737122a2eaa8d73
```

(*) This last backtrace comes from a slightly custom spack: the lines could be offset. But I don't think the patches change this issue.

Maybe the archive gets corrupted (the file does not exists after the command).

### Information on your system

* **Spack:** 0.20.0.dev0 (e5bd319c19d1c5bb2f41e708c77a477a3f6658b8)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

EDIT: Add note about the last backtrace being from a patched spack.
EDIT: Add another backtrace with  vanilla spack 0.20.

**Comment by haampie** [comment]
I believe this is a bug, since there should be a stage lock.

What's not 100% clear is the expected behavior 🤔 wait for process A to complete staging, only to rm -rf and re-stage in process B?

(Edit: ah, fetching, not staging...)

**Comment by Jordan474** [comment]
I find there is an odd behavior where the first fetch creates the archive in the spec's stage, but then if you run fetch again, this archive becomes a symlink to the one in to `var/spack/cache`... (this cache exists after the first fetch).

Also, not sure but: isn't there a stage lock? if `spack fetch` outputs to the stage dir, shouldn't it be using the stage lock?

**Comment by haampie** [comment]
Right, I think `fetch` puts the archive in the stage dir without expanding it. First fetch may put an archive there, second fetch may use local cache and use a symlink instead. Maybe fetching to cache and always symlinking makes more sense (ah, maybe the point is that some things can only be cached afterwards, like a git clone in stage dir -> tarball in source cache). In any case, irrespective of symlinks vs file, i believe it's supposed to be process safe. (In multiprocess spack install there is no issue since the installer takes a lock on the datbase, and fetching happens after acquiring the lock, and that lock has no bugs ;p)

**Comment by Jordan474** [comment]
I tested before and after #38903, and it fixed this issue for me. Thanks.
