### ISSUE TITLE
`spack solve` doesn't work on non-unified environments

### ISSUE THREAD

**Issue by vanderwb** [LLNL/spack#35981]
### Steps to reproduce

I have a Spack environment with `unify: false` set for concretization, and I have installed multiple versions of the same package with different compilers. If I run `spack solve` on the environment, I get the following error: 
```console
$ spack solve
==> Error: 'eccodes' compiler constraints '%gcc@12.2.0' and '%nvhpc@23.1' are incompatible
```
It seems like `solve` does not respect the unify concretization configuration.

### Error message

```console
$ spack --debug --stacktrace solve
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:44.593177] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:44.840342] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:44.908285] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build/spack.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.125890] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:201 ==> [2023-03-09-17:11:45.148494] Using environment '/glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build'                               lib/spack/spack/cmd/__init__.py:125 ==> [2023-03-09-17:11:45.153550] Imported solve from built-in commands
lib/spack/spack/cmd/__init__.py:125 ==> [2023-03-09-17:11:45.154147] Imported solve from built-in commands
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.203096] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.211254] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build/spack.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.428965] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:225 ==> [2023-03-09-17:11:45.450968] Deactivated environment '/glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build'
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.488145] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.534123] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:391 ==> [2023-03-09-17:11:45.559526] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-03-09-17:11:45.559781] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:391 ==> [2023-03-09-17:11:45.560409] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-03-09-17:11:45.560681] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap/config.py:124 ==> [2023-03-09-17:11:45.560913] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.654708] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:176 ==> [2023-03-09-17:11:45.667954] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.858026] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.929405] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:45.942500] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.074352] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:214 ==> [2023-03-09-17:11:46.133446] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:214 ==> [2023-03-09-17:11:46.138608] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:357 ==> [2023-03-09-17:11:46.138822] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:73 ==> [2023-03-09-17:11:46.170118] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/prqkzynv2nwko5mktitebgkeumuxkveu" provides the "clingo" Python module
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.171346] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.198283] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build/spack.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.415907] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:201 ==> [2023-03-09-17:11:46.438559] Using environment '/glade/scratch/vanderwb/spack-tests/casper/23.03/envs/build'
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.438882] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.444101] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:46.492681] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/database.py:391 ==> [2023-03-09-17:11:46.879497] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-03-09-17:11:46.879762] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1003 ==> [2023-03-09-17:11:47.083863] Reading config from file /glade/scratch/vanderwb/spack-tests/casper/23.03/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:330 ==> [2023-03-09-17:11:47.103693] Checking existence of file:///glade/u/apps/mirror/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-03-09-17:11:47.112832] Failure reading URL: <urlopen error [Errno 2] No such file or directory: '/glade/u/apps/mirror/build_cache/index.json'>
lib/spack/spack/util/web.py:330 ==> [2023-03-09-17:11:47.113186] Checking existence of file:///glade/scratch/vanderwb/spack-tests/casper/mirror/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-03-09-17:11:47.113538] Failure reading URL: <urlopen error [Errno 2] No such file or directory: '/glade/scratch/vanderwb/spack-tests/casper/mirror/build_cache/index.json'>
lib/spack/spack/util/web.py:330 ==> [2023-03-09-17:11:47.113863] Checking existence of https://mirror.spack.io/build_cache/index.json
lib/spack/spack/util/web.py:358 ==> [2023-03-09-17:11:47.243270] Failure reading URL: HTTP Error 404: Not Found
lib/spack/spack/main.py:1007 ==> [2023-03-09-17:12:14.199499] UnsatisfiableSpecError: 'eccodes' compiler constraints '%gcc@12.2.0' and '%nvhpc@23.1' are incompatible
lib/spack/spack/error.py:54 ==> [2023-03-09-17:12:14.209893] Error: 'eccodes' compiler constraints '%gcc@12.2.0' and '%nvhpc@23.1' are incompatible
Traceback (most recent call last):
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/cmd/solve.py", line 185, in solve
    specs, out=output, timers=args.timers, stats=args.stats, setup_only=setup_only
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/solver/asp.py", line 2539, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/solver/asp.py", line 760, in solve
    self.handle_error(msg, *args)
  File "/glade/scratch/vanderwb/spack-tests/casper/23.03/spack/lib/spack/spack/solver/asp.py", line 654, in handle_error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: 'eccodes' compiler constraints '%gcc@12.2.0' and '%nvhpc@23.1' are incompatible

### Information on your system

* **Spack:** 0.20.0.dev0 (7d54c24939a831a223ccc749ad240668f04d15f6)
* **Python:** 3.6.15
* **Platform:** linux-sles15-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This is correct. I think `spack solve` was a sort of "debug" command for developers, so it was never curated like other more used commands. Maybe we should merge the functionality with spec :thinking:
