### ISSUE TITLE
Providing Spack environments on read-only NFS shares

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#36176]
:warning: Reported on Spack v0.17.1 :warning: 

### Steps to reproduce

Install spack on an NFS share and do the following from a client where NFS share mounted as read-only (i.e. with `ro` option)
```console
spack env activate -p myenv
```
A read-only on share would optimize the performance of the Spack. Also, if the NFS share is not read-only. i.e if there are write operations, it seems users are running into permission issues:
```
[user@wmachine ]$ spack env activate -p myenv
==> [2023-03-16-13:03:41.281380] Imported env from built-in commands
==> [2023-03-16-13:03:41.285213] Imported env from built-in commands
==> [2023-03-16-13:03:41.287983] Reading config file /disk/hpcpm/3vg_spack/0171/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/disk/hpcpm/3vg_spack/0171/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/main.py", line 900, in main
    return _main(argv)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/main.py", line 883, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/main.py", line 553, in _invoke_command
    return_val = command(parser, args)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/cmd/env.py", line 554, in env
    action(args)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/cmd/env.py", line 147, in env_activate
    active_env = ev.Environment(env_path)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/environment/environment.py", line 556, in __init__
    with lk.ReadTransaction(self.txlock):
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/llnl/util/lock.py", line 684, in __enter__
    if self._enter() and self._acquire_fn:
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/llnl/util/lock.py", line 711, in _enter
    return self._lock.acquire_read(self._timeout)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/llnl/util/lock.py", line 423, in acquire_read
    wait_time, nattempts = self._lock(fcntl.LOCK_SH, timeout=timeout)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/spack/util/lock.py", line 32, in _lock
    return super(Lock, self)._lock(op, timeout)
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/llnl/util/lock.py", line 286, in _lock
    self._ensure_parent_directory()
  File "/disk/hpcpm/3vg_spack/0171/lib/spack/llnl/util/lock.py", line 358, in _ensure_parent_directory
    os.makedirs(parent)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/disk/hpcpm/3vg_spack/0171/var/spack/environments/myvenv/.spack-env'
```
**Update**: the above mentioned permission error disappears if I set `--disable-locks`. I am not yet sure how safe this is for our use case: single maintainer and multiper users that only activate environments.

### Error message

```console
spack env activate -p myenv
...
I==> Error: [Errno 30] Read-only file system: '/disk/hpcpm/3vg_spack/0171/var/spack/environments/myenv/.spack-env'
```
will run this with `spack debug` shortly to provide more info.

### Information on your system

* **Spack:** 0.17.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Sinan81** [comment]
`--disable-locks` option seem to take care of this error. I am guessing this should be 100% safe if NFS mount is read only.

**Comment by Sinan81** [comment]
just to clarify, in order to improve latency and reduce load on NFS server, we set `actimeo=3600` as mount option (that's NFS client will request metadata only once per hour as opposed to for every time an NFS file is used) . I wonder this might also contribute to the permission issue.

**Comment by Sinan81** [comment]
@alalazo Would it make sense for Spack to automatically check if it's on an read-only NFS mount ( with `ro` mount option) and simply disable locks by default.

**Comment by Sinan81** [comment]
or would it be possible to introduce `locks: False` feature to environment yaml configs.

**Comment by alalazo** [comment]
> or would it be possible to introduce locks: False feature to environment yaml configs.

What is wrong with:
```yaml
spack:
  config:
    locks: false
```
?

**Comment by Sinan81** [comment]
Thanks. I'm sure I tried it once. But it didn't work possibly due to the fact that right now I'm using spack@0.17.1 I'll give it a try again, also with spack development branch.

**Comment by alalazo** [comment]
@Sinan81 Any news?

**Comment by Sinan81** [comment]
spack accepts the config option. However still complains about the read only filesystem unless I use `--disable-locks`
```
$ spack env activate test_sinan
==> Error: [Errno 30] Read-only file system: '/disk/hpcpm/3vg_spack/0171/var/spack/environments/test_sinan/.spack-env'
$ spack --disable-locks env activate test_sinan
$
```

**Comment by Sinan81** [comment]
Note that. the above test was done with spack@0.17.1 I'll also try it with newer spack very soon.

**Comment by Sinan81** [comment]
with spack@0.20 I am getting a similar error as well:
```
$ spack env activate -p test_sinan
==> Warning: couldn't get environment settings for zlib@1.2.13 /gptq4ai
  cannot write to config file [Errno 30] Read-only file system: '/disk/hpcpm/test_sinan/spack-0.20.0/var/spack/environments/test_sinan/.spack.yaml.tmp'
```
note that there's only one package installed in the environment: `zlib`

**Comment by alalazo** [comment]
This seems specific to NFS. I can't reproduce locally with:
```console
$ spack env create -d /tmp/read-only/
==> Created environment in /tmp/read-only
==> You can activate this environment with:
==>   spack env activate /tmp/read-only
$ chmod -R uog-w /tmp/read-only/
$ spack env activate /tmp/read-only/
```

**Comment by Sinan81** [comment]
Why not automatically enable `--disable-locks` on read-only file systems?  Also, Spack should be able to respect `--disable-locks` option in environment config. The fact that it's not doing so seems like a bug to me. If that makes sense, I can look into implementing either of those options in the near future.
