### ISSUE TITLE
depends clause with cppflags does not work

### ISSUE THREAD

**Issue by pbrady** [LLNL/spack#36448]
### Steps to reproduce

Tried to modify a recipe by adding the following clause:

`depends_on('flecsi cppflags="-D_GNU_SOURCE"', when="platform=darwin")`

### Error message

A `spack concretize -f` yields the following error:

```console
Traceback (most recent call last):
  File "/Users/ptb/gitrepos/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/Users/ptb/gitrepos/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/environment/environment.py", line 1327, in concretize
    return self._concretize_together(tests=tests)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/environment/environment.py", line 1379, in _concretize_together
    concrete_specs = spack.concretize.concretize_specs_together(
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/concretize.py", line 739, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/concretize.py", line 746, in _concretize_specs_together_new
    result = solver.solve(abstract_specs, tests=kwargs.get("tests", False))
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/solver/asp.py", line 2551, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/solver/asp.py", line 764, in solve
    answers = builder.build_specs(spec_attrs)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/solver/asp.py", line 2416, in build_specs
    self.reorder_flags()
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/solver/asp.py", line 2323, in reorder_flags
    source = self._specs[name] if name in self._hash_specs else cmd_specs[name]
KeyError: 'flecsi'
```

### Information on your system

Based on  https://spack.readthedocs.io/en/latest/packaging_guide.html#dependency-specs, the above clause shouldn't trigger an error

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by pbrady** [comment]
@becker33 I've opened this issue following our spack discussion
