### ISSUE TITLE
spack fetch doesn't work in Python 3

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3655]
It has something to do with how we handle checksums:
```
$ python3 bin/spack fetch libsigsegv
==> Already downloaded /Users/Adam/spack/var/spack/stage/libsigsegv-2.11-5o3gkmccnzyuuirvrynnm56xebwv2lvd/libsigsegv-2.11.tar.gz
Traceback (most recent call last):
  File "bin/spack", line 220, in <module>
    main(sys.argv)
  File "bin/spack", line 216, in main
    _main(args, unknown)
  File "bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/fetch.py", line 65, in fetch
    package.do_fetch()
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 955, in do_fetch
    self.stage.check()
  File "/Users/Adam/spack/lib/spack/spack/util/pattern.py", line 84, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/Users/Adam/spack/lib/spack/spack/stage.py", line 460, in check
    self.fetcher.check()
  File "/Users/Adam/spack/lib/spack/spack/fetch_strategy.py", line 75, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/Adam/spack/lib/spack/spack/fetch_strategy.py", line 352, in check
    if not checker.check(self.archive_file):
  File "/Users/Adam/spack/lib/spack/spack/util/crypto.py", line 102, in check
    self.hash_fun, filename, block_size=self.block_size)
  File "/Users/Adam/spack/lib/spack/spack/util/crypto.py", line 49, in checksum
    data = file.read(block_size)
  File "/Users/Adam/anaconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
$ python3 bin/spack fetch --no-checksum libsigsegv
==> Already downloaded /Users/Adam/spack/var/spack/stage/libsigsegv-2.11-5o3gkmccnzyuuirvrynnm56xebwv2lvd/libsigsegv-2.11.tar.gz
```

**Comment by adamjstewart** [comment]
Seems related: http://stackoverflow.com/a/27460013/5828163

Maybe we need a better way of hashing things?

**Comment by alalazo** [comment]
I see another problem related to this: all the `python3` tests on Travis are failing on fetch, but none is exiting with non-zero before the unit tests.

**Comment by adamjstewart** [comment]
Anyone know how to get this working? Without fetching we really can't say that Spack supports Python 3.

**Comment by adamjstewart** [comment]
@tgamblin Can we add this to Project v1.0 as a required fix? I would really like to claim that we now support Python 3, but the truth is that we can't even fetch a single tarball.

**Comment by junghans** [comment]
I came across this issue, too, as on Gentoo `/usr/bin/python` is `python3`.

**Comment by adamjstewart** [comment]
Bold move, Gentoo developers.

**Comment by tgamblin** [comment]
Gentoo people are good to have around.
