### ISSUE TITLE
spack 0.19.1  - acfl 22.1 - checksum failed

### ISSUE THREAD

**Issue by ashterenli** [LLNL/spack#36610]
### Steps to reproduce

```
spack install acfl@22.1 %gcc@7.3.1
```

### Error message

```
==> [2023-04-03-13:57:33.668722] Installing acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6
==> [2023-04-03-13:57:33.668807] Searching for binary cache of acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6
==> [2023-04-03-13:57:33.669505] Checking existence of file:///bm/sw_cache/build_cache/index.json
==> [2023-04-03-13:57:33.669895] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2023-04-03-13:57:33.685696] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-03-13:57:35.283107] No binary for acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6 found: installing from source
==> [2023-04-03-13:57:35.283254] Creating the installation directory /bm/sw_spack_0.19.1/spack-0.19.1/opt/spack/[padded-to-128-chars]/linux-amzn2-neoverse_v1/gcc-7.3.1/acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6
==> [2023-04-03-13:57:35.423597] [TOOLCHAIN] MATCH Gcc
==> [2023-04-03-13:57:35.427893] Adding compiler bin/ paths: /bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/env /bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/env/case-insensitive /bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/env/gcc
==> [2023-04-03-13:57:35.458875] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2023-04-03-13:57:35.471101] '/usr/bin/g++' '-v' '/bm/tmpdir/spack-implicit-link-infol_jfnqsz/main.c' '-o' '/bm/tmpdir/spack-implicit-link-infol_jfnqsz/output'
==> [2023-04-03-13:57:35.614837] parsing implicit link info
==> [2023-04-03-13:57:35.615106] linker line:  /usr/libexec/gcc/aarch64-redhat-linux/7/collect2 -plugin /usr/libexec/gcc/aarch64-redhat-linux/7/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/aarch64-redhat-linux/7/lto-wrapper -plugin-opt=-fresolution=/bm/tmpdir/ccZKwshS.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -dynamic-linker /lib/ld-linux-aarch64.so.1 -X -EL -maarch64linux -o /bm/tmpdir/spack-implicit-link-infol_jfnqsz/output /usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64/crt1.o /usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64/crti.o /usr/lib/gcc/aarch64-redhat-linux/7/crtbegin.o -L/usr/lib/gcc/aarch64-redhat-linux/7 -L/usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/aarch64-redhat-linux/7/../../.. /bm/tmpdir/ccm73Ywi.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/aarch64-redhat-linux/7/crtend.o /usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64/crtn.o
==> [2023-04-03-13:57:35.615177] linkdir: /usr/lib/gcc/aarch64-redhat-linux/7
==> [2023-04-03-13:57:35.615209] linkdir: /usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64
==> [2023-04-03-13:57:35.615232] linkdir: /lib/../lib64
==> [2023-04-03-13:57:35.615253] linkdir: /usr/lib/../lib64
==> [2023-04-03-13:57:35.615273] linkdir: /usr/lib/gcc/aarch64-redhat-linux/7/../../..
==> [2023-04-03-13:57:35.615305] found raw link dirs: /usr/lib/gcc/aarch64-redhat-linux/7, /usr/lib/gcc/aarch64-redhat-linux/7/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /usr/lib/gcc/aarch64-redhat-linux/7/../../..
==> [2023-04-03-13:57:35.615372] found link dirs: /usr/lib/gcc/aarch64-redhat-linux/7, /usr/lib64, /lib64, /usr/lib
==> [2023-04-03-13:57:35.640676] Checking existence of file:///bm/sw_cache/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:35.641043] URL does not exist: file:///bm/sw_cache/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:35.641214] FailedDownloadError: Failed to fetch file from URL: file:///bm/sw_cache/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:35.641538] Checking existence of file:///bm/sw_cache/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:35.641810] URL does not exist: file:///bm/sw_cache/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:35.641914] FailedDownloadError: Failed to fetch file from URL: file:///bm/sw_cache/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:35.642168] Checking existence of https://mirror.spack.io/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:36.191141] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-03-13:57:36.191284] URL does not exist: https://mirror.spack.io/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:36.191454] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar
==> [2023-04-03-13:57:36.191769] Checking existence of https://mirror.spack.io/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:36.730551] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-03-13:57:36.730685] URL does not exist: https://mirror.spack.io/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:36.730819] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/acfl/acfl-22.1.tar
==> [2023-04-03-13:57:36.731101] Checking existence of https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/22-1/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
==> [2023-04-03-13:57:37.126116] Fetching https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/22-1/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
==> [2023-04-03-13:58:06.908151] Fetching from file:///bm/sw_cache/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar failed.
==> [2023-04-03-13:58:06.908292] Fetching from file:///bm/sw_cache/acfl/acfl-22.1.tar failed.
==> [2023-04-03-13:58:06.908334] Fetching from https://mirror.spack.io/_source-cache/archive/18/189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b.tar failed.
==> [2023-04-03-13:58:06.908396] Fetching from https://mirror.spack.io/acfl/acfl-22.1.tar failed.
==> [2023-04-03-13:58:08.195818] Error: ChecksumError: sha256 checksum failed for /bm/tmpdir/ec2-user/spack-stage/spack-stage-acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
    Expected 189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b but got bfbfef9099bf0e90480d48b3a1a741d583fc939284f869958e9c09e177098c73

/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/package_base.py:1460, in do_fetch:
       1457        self.stage.fetch(mirror_only, err_msg=err_msg)
       1458        self._fetch_time = time.time() - start_time
       1459
  >>   1460        if checksum and self.version in self.versions:
       1461            self.stage.check()
       1462
       1463        self.stage.cache_local()


Traceback (most recent call last):
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/build_environment.py", line 1057, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/installer.py", line 2087, in build_process
    return installer.run()
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/installer.py", line 1924, in run
    self.pkg.do_patch()
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/package_base.py", line 1493, in do_patch
    self.do_stage()
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/package_base.py", line 1478, in do_stage
    self.do_fetch(mirror_only)
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/package_base.py", line 1461, in do_fetch
    self.stage.check()
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/util/pattern.py", line 18, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/util/pattern.py", line 18, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/stage.py", line 585, in check
    self.fetcher.check()
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/fetch_strategy.py", line 87, in wrapper
    return fun(self, *args, **kwargs)
  File "/bm/sw_spack_0.19.1/spack-0.19.1/lib/spack/spack/fetch_strategy.py", line 514, in check
    "Expected %s but got %s" % (self.digest, checker.sum),
spack.fetch_strategy.ChecksumError: sha256 checksum failed for /bm/tmpdir/ec2-user/spack-stage/spack-stage-acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
    Expected 189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b but got bfbfef9099bf0e90480d48b3a1a741d583fc939284f869958e9c09e177098c73
==> [2023-04-03-13:58:08.196885] Flagging acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6 as failed: ChecksumError: sha256 checksum failed for /bm/tmpdir/ec2-user/spack-stage/spack-stage-acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
    Expected 189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b but got bfbfef9099bf0e90480d48b3a1a741d583fc939284f869958e9c09e177098c73
==> [2023-04-03-13:58:08.244666] ChildError: ChecksumError: sha256 checksum failed for /bm/tmpdir/ec2-user/spack-stage/spack-stage-acfl-22.1-lcmwtlwjtwhvnyjsmlfzwbfqtrhzfws6/arm-compiler-for-linux_22.1_RHEL-7_aarch64.tar
    Expected 189119a72b2cf2840dc85d4fab74435c018e145d03dd3098f23364bd235ffb7b but got bfbfef9099bf0e90480d48b3a1a741d583fc939284f869958e9c09e177098c73
```

### Information on your system

$ spack debug report
* **Spack:** 0.19.1
* **Python:** 3.7.16
* **Platform:** linux-amzn2-neoverse_v1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@annop-w

**Comment by annop-w** [comment]
@alalazo @ashterenli Thanks. This got fixed already in #34997.

**Comment by ashterenli** [comment]
@alalazo Thank you. Did the fix in #34997 got into spack 0.19.1? Or only in master?
