### ISSUE TITLE
spack find error 'Cannot depend on incompatible specs'

### ISSUE THREAD

**Issue by accopeland** [LLNL/spack#36810]
### Steps to reproduce

Issue: spack find returns
```
Error: Cannot depend on incompatible specs
```

Background: I am working on an environment which is partially broken due to a missing package (which is present in another git branch).   I was attempting to resolve a different issue by updating dependencies to use the same most recent setuptools (py-setuptools@67.6.0).   
To debug I did a fresh pull of 'develop' , and confirm that `spack find` works correctly.  I then activate the partially broken env and it produces an error:

``` console
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.
nothing to commit, working tree clean

$ spack env activate acc
==> Error: Package 'nuttcp' not found.
    You may need to run 'spack clean -m'.
==> Error: Environment view is broken due to a missing package or repo.

    To activate without views enabled, activate with:

      spack env activate -V acc

    To remove it and resolve the issue, force concretize with the command:

      spack -e acc concretize --force

$ spack env activate -V acc
$ spack find
==> Error: Cannot depend on incompatible specs 'py-setuptools@65.5.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2' and 'py-setuptools@67.6.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2'
```

### Error message

```console
$ spack -d find
==> [2023-04-12-12:56:58.623140] Reading config from file /clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/etc/spack/defaults/config.yaml
==> [2023-04-12-12:56:58.654272] Reading config from file /clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/etc/spack/defaults/concretizer.yaml
==> [2023-04-12-12:56:58.686960] Reading config from file /clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/var/spack/environments/acc/spack.yaml
==> [2023-04-12-12:56:58.697239] Reading config from file /clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/etc/spack/defaults/config.yaml
==> [2023-04-12-12:56:58.715927] Using environment 'acc'
==> [2023-04-12-12:56:58.731812] Imported find from built-in commands
==> [2023-04-12-12:56:58.732512] Imported find from built-in commands
==> [2023-04-12-12:56:58.736396] DATABASE LOCK TIMEOUT: 60s
==> [2023-04-12-12:56:58.736433] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-04-12-12:56:58.816200] DuplicateDependencyError: Cannot depend on incompatible specs 'py-setuptools@65.5.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2' and 'py-setuptools@67.6.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2'
==> [2023-04-12-12:56:58.816243] Error: Cannot depend on incompatible specs 'py-setuptools@65.5.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2' and 'py-setuptools@67.6.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2'
Traceback (most recent call last):
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec.py", line 1581, in _add_dependency
    dspec.spec.constrain(spec)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec.py", line 3365, in constrain
    raise UnsatisfiableVersionSpecError(self.versions, other.versions)
spack.spec.UnsatisfiableVersionSpecError: 65.5.0 does not satisfy 67.6.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/cmd/find.py", line 253, in find
    decorator, _, roots, _ = setup_env(env)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/cmd/find.py", line 183, in setup_env
    added = set(strip_build(env.added_specs()))
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/cmd/find.py", line 181, in strip_build
    return set(s.copy(deps=("link", "run")) for s in seq)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/cmd/find.py", line 181, in <genexpr>
    return set(s.copy(deps=("link", "run")) for s in seq)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/environment/environment.py", line 1838, in added_specs
    for spec in self.user_specs:
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec_list.py", line 168, in __getitem__
    return self.specs[key]
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec_list.py", line 67, in specs
    for constraint_list in self.specs_as_constraints:
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec_list.py", line 56, in specs_as_constraints
    constraints.append([Spec(item)])
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec.py", line 1342, in __init__
    spack.parser.parse_one_or_raise(spec_like, self)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/parser.py", line 488, in parse_one_or_raise
    result = parser.next_spec(initial_spec)
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/parser.py", line 286, in next_spec
    root_spec._add_dependency(dependency, deptypes=())
  File "/clusterfs/jgi/groups/gentech/homes/accopeland/spack-acc/lib/spack/spack/spec.py", line 1584, in _add_dependency
    "Cannot depend on incompatible specs '%s' and '%s'" % (dspec.spec, spec)
spack.spec.DuplicateDependencyError: Cannot depend on incompatible specs 'py-setuptools@65.5.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2' and 'py-setuptools@67.6.0%gcc@12.2.0 build_system=generic arch=linux-rocky8-zen2'
```

### Information on your system

```
$ uname -a
Linux ln001.jgi 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* **Spack:** 0.20.0.dev0 (a7ae996e6ba25c5e3463cd2ecd7943a106d7c80f)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Can you post the `spack.yaml` and the `spack.lock` file?

**Comment by accopeland** [comment]
Sorry, I removed/reinstalled since I had this error. I will include
spack.lock and spack.yaml if I ever need to report something like this
again. You can close this one.
