### ISSUE TITLE
llvm@16 installed from cache: spack load llvm fails: Unable to locate perl command in...

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#36956]
### Steps to reproduce

`spack load llvm` fails with `llvm@16` installed entirely from build cache.

Here using:
* `spack@develop` (14075f9f4cd82e7af138af0ad822fd9ddb8034fa from `Sat Apr 15 19:02:50 2023 -0700`)
* Ubuntu 20.04, X86_64

Spack environment:
```
spack:
  view: false
  concretizer:
    unify: false
    reuse: false
  packages:
    all:
      target: [x86_64]
  mirrors:
    remote: https://cache.e4s.io/llvm-16/256
  specs:
  - llvm +clang +flang +lld +lldb +llvm_dylib +link_llvm_dylib
  compilers:
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment:
        set:
          LDFLAGS: "-Wl,--copy-dt-needed-entries"
      extra_rpaths: []
```

Error:
```
$> spack -e . buildcache keys -it

$> time spack -e . install --cache-only
...
==> llvm: Successfully installed llvm-16.0.0-g4hdnjfhzfcwq44zctkywkjqgspqrzzq
  Search: 0.00s.  Fetch: 13.44s.  Install: 21.35s.  Total: 34.79s
[+] /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/llvm-16.0.0-g4hdnjfhzfcwq44zctkywkjqgspqrzzq

real	0m54.993s
user	0m18.996s
sys	0m8.215s

$> spack load llvm
==> Error: Unable to locate perl command in /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/perl-5.36.0-ctanfhuupn7wleazovctuss2i7msj6ib/bin
```

With debug:
```
$> spack -d load llvm
...
Traceback (most recent call last):
  File "/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/load.py", line 114, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
  File "/spack/lib/spack/spack/user_environment.py", line 91, in environment_modifications_for_spec
    spack.build_environment.modifications_from_dependencies(
  File "/spack/lib/spack/spack/build_environment.py", line 998, in modifications_from_dependencies
    add_modifications_for_dep(dspec)
  File "/spack/lib/spack/spack/build_environment.py", line 975, in add_modifications_for_dep
    dpkg.setup_dependent_package(current_module, spec)
  File "/spack/var/spack/repos/builtin/packages/perl/package.py", line 377, in setup_dependent_package

  File "/spack/lib/spack/spack/spec.py", line 1180, in __get__
    value = f()
  File "/spack/lib/spack/spack/spec.py", line 1169, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/spack/var/spack/repos/builtin/packages/perl/package.py", line 490, in command

RuntimeError: Unable to locate perl command in /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.2.0/perl-5.36.0-ctanfhuupn7wleazovctuss2i7msj6ib/bin
```

### Information on your system

* **Spack:** 0.20.0.dev0 (14075f9f4cd82e7af138af0ad822fd9ddb8034fa)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by eugeneswalker** [comment]
Looks like this is being triggered by this from Perl's package.py:
* https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/perl/package.py#L365-L383
```
    def setup_dependent_package(self, module, dependent_spec):
        """Called before perl modules' install() methods.
        In most cases, extensions will only need to have one line:
        perl('Makefile.PL','INSTALL_BASE=%s' % self.prefix)
        """

        # If system perl is used through packages.yaml
        # there cannot be extensions.
        if dependent_spec.package.is_extension:
            # perl extension builds can have a global perl
            # executable function
            module.perl = self.spec["perl"].command

            # Add variables for library directory
            module.perl_lib_dir = dependent_spec.prefix.lib.perl5

            # Make the site packages directory for extensions,
            # if it does not exist already.
            mkdirp(module.perl_lib_dir)
```

Any recommendations @becker33?

**Comment by alalazo** [comment]
Seems related to #37704
