### ISSUE TITLE
Package requirements: failure with compiler flags

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#37163]
### Steps to reproduce

With a `packages.yaml` like:

```
packages:
  zlib:
    require: cflags="-g"
```

`spack spec zlib` fails. Claiming that the requirements cannot be satisfied.

### Error message

```
...
spack.error.SpackError: concretization failed for the following reasons:

   1. Cannot satisfy the requirements in packages.yaml for package 'zlib'. You may want to delete them to proceed with concretization. To check where the requirements are defined run 'spack config blame packages'
```

### Information on your system

* `spack config blame packages` shows no non-default config (other than the one I explicitly add in this report)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
@alalazo @becker33 the issue we discussed

**Comment by alalazo** [comment]
@scheibelp The issue with flags is that they're treated differently from variants, and there are currently no rules for `clingo` to generate a set of flags to satisfy the requirement. If you add something like:[^1]
```diff
diff --git a/lib/spack/spack/solver/concretize.lp b/lib/spack/spack/solver/concretize.lp
index e96e108e0e..57c8ff689c 100644
--- a/lib/spack/spack/solver/concretize.lp
+++ b/lib/spack/spack/solver/concretize.lp
@@ -461,6 +461,15 @@ error(100, "Attempted to use external for '{0}' which does not satisfy any confi
 % Config required semantics
 %-----------------------------------------------------------------------------
 
+{ attr("node_flag", A1, A2, A3) } :-
+  requirement_group_member(Y, Package, _),
+  condition_requirement(Y,"node_flag", A1, A2, A3).
+
+{ attr("node_flag_source", A1, A2, A3) } :-
+  requirement_group_member(Y, Package, _),
+  condition_requirement(Y,"node_flag_source", A1, A2, A3).
+
+
 package_in_dag(Package) :-  attr("node", Package).
 package_in_dag(Package) :-  attr("virtual_node", Package).

```
You'll get past the concretization error into an error in the builder:
```console
$ spack -d spec zlib
[ ... ]
==> [2023-04-25-16:10:52.079882] Failure reading URL: HTTP Error 404: Not Found
==> [2023-04-25-16:10:52.082865] Reading config from file /home/culpo/.spack/linux/compilers.yaml
==> [2023-04-25-16:10:52.187133] UNKNOWN SYMBOL: attr("node_compiler", zlib, gcc)
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/__init__.py", line 222, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2821, in concretize
    self._new_concretize(tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2796, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 2736, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 820, in solve
    answers = builder.build_specs(spec_attrs)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 2601, in build_specs
    self.reorder_flags()
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 2519, in reorder_flags
    assert set(compiler_flags) == set(ordered_compiler_flags), msg
AssertionError: {'-g'} does not equal set()
```

[^1]: To be clear, I'm not sure these are the correct rules to be added, but they prove that part of the issue is the absence of any choice rule that let clingo add a flag to the answer set.
