### ISSUE TITLE
Installation issue: python

### ISSUE THREAD

**Issue by awadell1** [LLNL/spack#37171]
### Steps to reproduce the issue

```console
$ spack spec -I python@3.10.10+zlib
Input spec
--------------------------------
 -   python@3.10.10+zlib

Concretized
--------------------------------
[+]  python@3.10.10%gcc@7.5.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline
+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-opensuse15-zen
[+]      ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared build_system=generic arch=linux-opensuse15-zen
[+]          ^diffutils@3.9%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^expat@2.5.0%gcc@7.5.0+libbsd build_system=autotools arch=linux-opensuse15-zen
[+]          ^libbsd@0.11.7%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]              ^libmd@1.0.4%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^gdbm@1.23%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^gettext@0.21.1%gcc@7.5.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-open
suse15-zen
[+]          ^libiconv@1.17%gcc@7.5.0 build_system=autotools libs=shared,static arch=linux-opensuse15-zen
[+]          ^libxml2@2.10.3%gcc@7.5.0~python build_system=autotools arch=linux-opensuse15-zen
[+]          ^tar@1.34%gcc@7.5.0 build_system=autotools zip=pigz arch=linux-opensuse15-zen
[+]              ^pigz@2.7%gcc@7.5.0 build_system=makefile arch=linux-opensuse15-zen
[+]              ^zstd@1.5.5%gcc@7.5.0+programs build_system=makefile compression=none libs=shared,static arch=linux-o
pensuse15-zen
[+]      ^libffi@3.4.4%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^libxcrypt@4.4.33%gcc@7.5.0~obsolete_api build_system=autotools arch=linux-opensuse15-zen
[+]          ^perl@5.36.0%gcc@7.5.0+cpanm+open+shared+threads build_system=generic arch=linux-opensuse15-zen
[+]              ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux
-opensuse15-zen
[+]      ^ncurses@6.4%gcc@7.5.0~symlinks+termlib abi=none build_system=autotools arch=linux-opensuse15-zen
[+]      ^openssl@1.1.1t%gcc@7.5.0~docs~shared build_system=generic certs=mozilla arch=linux-opensuse15-zen
[+]          ^ca-certificates-mozilla@2023-01-10%gcc@7.5.0 build_system=generic arch=linux-opensuse15-zen
[+]      ^pkgconf@1.8.0%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^readline@8.2%gcc@7.5.0 build_system=autotools patches=bbf97f1 arch=linux-opensuse15-zen
[+]      ^sqlite@3.40.1%gcc@7.5.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=l
inux-opensuse15-zen
[+]      ^util-linux-uuid@2.38.1%gcc@7.5.0 build_system=autotools arch=linux-opensuse15-zen
[+]      ^xz@5.4.1%gcc@7.5.0~pic build_system=autotools libs=shared,static arch=linux-opensuse15-zen
[+]      ^zlib@1.2.13%gcc@7.5.0+optimize+pic+shared build_system=makefile arch=linux-opensuse15-zen

$ spack install --overwrite -y python@3.10.10

```

### Error message

Instance of python installed by spack cannot import the zlib module

<details><summary>Error message</summary>

<pre>
```console
❯ spack load python@3.10.10

❯ which python3
/home/awadell/spack/opt/spack/linux-opensuse15-zen/gcc-7.5.0/python-3.10.10-xplxbc5o5jrloglj35wngefohj7tt6ze/bin/python3

❯ python3 -c "import zlib"
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'zlib'

❯ PYTHONHOME=~/spack/opt/spack/linux-opensuse15-zen/gcc-7.5.0/python-3.10.10-xplxbc5o5jrloglj35wngefohj7tt6ze/ python3 -c "import zlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'zlib'
```
</pre></details>

### Information on your system

❯ spack debug report
* **Spack:** 0.20.0.dev0 (c76023d7accc53f40e49481179bdb26c8c18845a)
* **Python:** 3.6.13
* **Platform:** linux-opensuse15-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/11315222/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/11315224/spack-build-env.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/11315241/spack-configure-args.txt)
[spack-build-01-configure-out.txt](https://github.com/spack/spack/files/11315242/spack-build-01-configure-out.txt)

@adamjstewart @pradyunsg @scheibelp @skosukhin 

### Staged Version works

Installing with spack and keeping the stage, results in a usable instance, but the installed version lack's zlib:

```console
❯ spack install --overwrite --keep-stage python@3.10.10+zlib
...

❯ spack cd python@3.10.10+zlib

❯ ./python
Python 3.10.10 (main, Apr 24 2023, 19:39:34) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> 
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I don't see anything suspicious in the build log. And I can't reproduce the issue on macOS. So I'm not sure how much I'll be able to help with this one.

**Comment by alecbcs** [comment]
Also cannot reproduce with a Spack built python on MacOS.

```console
alecbcs@laptop spack % which python3
/Users/alecbcs/.spack/environments/default/.spack-env/view/bin/python3

alecbcs@laptop spack % python3
Python 3.10.10 (main, Apr 28 2023, 11:50:57) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>>
```

**Comment by alecbcs** [comment]
Also cannot reproduce on a Linux machine.

```console
alecbcs@helio:~$ which python
/home/alecbcs/src/spack/spack/opt/spack/linux-debian11-skylake/gcc-10.4.0/python-3.10.10-lah23ebbkr23gs7emc7twtyubsstcv4i/bin/python

alecbcs@helio:~$ python3
Python 3.10.10 (main, Apr 30 2023, 04:28:15) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>>
```

@awadell1 if you try building with a newer GCC do you notice any difference in behavior?

**Comment by awadell1** [comment]
Repeated for `python%aocc@4.0.0` and `python%gcc@12.2.0` and got the same error:

```shell
  ❯ python
 Could not find platform dependent libraries <exec_prefix>
 Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
 Python 3.10.10 (main, May 10 2023, 12:14:14) [GCC 12.2.0] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 Traceback (most recent call last):
   File "/etc/pythonstart", line 7, in <module>
     import readline
 ModuleNotFoundError: No module named 'readline'
 >>> import zlib
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ModuleNotFoundError: No module named 'zlib'
 >>>
 
 awadell at localhost in …/battery_fingerprint on  spack [!?] is 📦 v0.1.0 via 🐍 v3.10.10
 ❯ which python
 /home/awadell/.local/opt/spack/opt/spack/linux-opensuse15-zen3/gcc-12.2.0/python-3.10.10-v6jtlw5aoenlfaqposgtwnek3r4gcs4g/bin/python
 
 awadell at localhost in …/battery_fingerprint on  spack [!?] is 📦 v0.1.0 via 🐍 v3.10.10
 ❯ spack load python%aocc
 
 awadell at localhost in …/battery_fingerprint on  spack [!?] is 📦 v0.1.0 via 🐍 v3.10.10
 ❯ python -c "import zlib"
 Could not find platform dependent libraries <exec_prefix>
 Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
 ModuleNotFoundError: No module named 'zlib'
 
 awadell at localhost in …/battery_fingerprint on  spack [!?] is 📦 v0.1.0 via 🐍 v3.10.10
 ❯ which python
 /home/awadell/.local/opt/spack/opt/spack/linux-opensuse15-zen3/aocc-4.0.0/python-3.10.10-s4vrh6s7renmei37yqk56ca3tvq5k5e3/bin/python
 
```

```

**Comment by awadell1** [comment]
Repeated with a fresh spack install at `v0.19.2` it worked. My platform seems to have changed from 'opensuse15` to `opensuse

```
❯ spack find -dvl python
-- linux-opensuse_leap15-x86_64 / gcc@7.5.0 ---------------------
qnkfop3 python@3.10.8+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060
hm3e2sr     bzip2@1.0.8~debug~pic+shared build_system=generic
t4nrivv         diffutils@3.8 build_system=autotools
dtlqy3l     expat@2.4.8+libbsd build_system=autotools
xcdg7e5         libbsd@0.11.5 build_system=autotools
qsjqv2l             libmd@1.0.4 build_system=autotools
66xgz7d     gdbm@1.23 build_system=autotools
s5efzth     gettext@0.21.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools
x2kk2c5         libiconv@1.16 build_system=autotools libs=shared,static
wqes2qw         libxml2@2.10.1~python build_system=autotools
un3skr2         tar@1.34 build_system=autotools zip=pigz
yml4kw4             pigz@2.7 build_system=makefile
2aw6roh             zstd@1.5.2+programs build_system=makefile compression=none libs=shared,static
65kub6o     libffi@3.4.2 build_system=autotools
xh5brwo     ncurses@6.3~symlinks+termlib abi=none build_system=autotools
iha5s2y     openssl@1.1.1s~docs~shared build_system=generic certs=mozilla
tqrvs6y         ca-certificates-mozilla@2022-10-11 build_system=generic
nafpb3w         perl@5.36.0+cpanm+shared+threads build_system=generic
wu2db26             berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc
7b5e46a     pkgconf@1.8.0 build_system=autotools
5gaembk     readline@8.1.2 build_system=autotools
u7rngke     sqlite@3.39.4+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools
7ngucpr     util-linux-uuid@2.38.1 build_system=autotools
lcejxze     xz@5.2.7~pic build_system=autotools libs=shared,static
67r3lqq     zlib@1.2.13+optimize+pic+shared build_system=makefile

==> 1 installed package
```


spack debug report 
```
 ❯ spack debug report
 * **Spack:** 0.19.2 (45accfac1584ca9c303b61a1f7e9097a3693a73e)
 * **Python:** 3.6.13
 * **Platform:** linux-opensuse_leap15-zen3
 * **Concretizer:** clingo
```

**Comment by alecbcs** [comment]
@awadell1 should we go ahead and close this issue?

**Comment by awadell1** [comment]
Yep, thank you for the help!

**Comment by eugeneswalker** [comment]
> Yep, thank you for the help!

I'm seeing this on a Cray SLES system with `python@3.10.2` -- using spack@develop from today -- never seen this before. Am I understanding that you @awadell1  resolved the issue simply by changing your Spack version? You didn't change anything on your system other than that, that you know of?

**Comment by awadell1** [comment]
I'm fairly confident that I also deleted my already-built packages and cleaned out my `~/.spack` folder of anything that wasn't a config file I wrote (i.e. `~/.spack/cache`).

**Comment by awadell1** [comment]
#39837 seems to resolve this for me. Plus, now I'm not stuck at v0.19.2.

**Comment by vicentebolea** [comment]
New PR here: https://github.com/spack/spack/pull/48575
