### ISSUE TITLE
YAML anchors not expanded correctly

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#37252]
### Steps to reproduce

```console
$ cat c/packages.yaml
packages:
  all:
    require:
    - &common any_of: ['@:']

  zlib:
    require:
    - *common

  mpi:
    require:
    - *common
$ spack -C c/ spec -U zlib
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy the requirements in packages.yaml for package 'zlib'. You may want to delete them to proceed with concretization. To check where the requirements are defined run 'spack config blame packages'
$ spack -C c/ spec -U mpi
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "any_of"
   2. 'any_of' is not a valid dependency for any package in the DAG
```

### Error message

```console
$ spack --debug --stacktrace -C c/ spec -U mpi
lib/spack/spack/cmd/__init__.py:125 ==> [2023-04-27-09:27:44.693053] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:125 ==> [2023-04-27-09:27:44.693548] Imported spec from built-in commands
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.695118] Reading config from file /home/deepthought/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.707639] Reading config from file /home/deepthought/.spack/config.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.710145] Reading config from file /home/deepthought/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.715199] Reading config from file /home/deepthought/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.717187] Reading config from file /home/deepthought/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.728906] Reading config from file /home/deepthought/.spack/config.yaml
lib/spack/spack/database.py:391 ==> [2023-04-27-09:27:44.729684] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-04-27-09:27:44.729795] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:391 ==> [2023-04-27-09:27:44.730087] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-04-27-09:27:44.730202] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap/config.py:125 ==> [2023-04-27-09:27:44.730311] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.730574] Reading config from file /home/deepthought/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2023-04-27-09:27:44.733933] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/deepthought/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2023-04-27-09:27:44.734034] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/deepthought/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2023-04-27-09:27:44.734127] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/deepthought/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2023-04-27-09:27:44.734213] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/deepthought/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.734552] Reading config from file /home/deepthought/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-04-27-09:27:44.768424] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/util/executable.py:195 ==> [2023-04-27-09:27:44.768871] '/usr/bin/patchelf' '--version'
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-04-27-09:27:44.771224] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-04-27-09:27:44.772598] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:376 ==> [2023-04-27-09:27:44.772696] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.772948] Reading config from file /home/deepthought/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.813547] Reading config from file /home/deepthought/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.880381] Reading config from file /home/deepthought/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:78 ==> [2023-04-27-09:27:44.897752] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.11/cizcjj3tx4irs3uzoktrgybq73sz545f" provides the "clingo" Python module
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.898104] Reading config from file /home/deepthought/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.901293] Reading config from file /home/deepthought/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.957863] Reading config from file /home/deepthought/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:44.972289] Reading config from file c/packages.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:45.886421] Reading config from file /home/deepthought/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:45.920257] Reading config from file /home/deepthought/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1010 ==> [2023-04-27-09:27:45.931737] Reading config from file /home/deepthought/.spack/config.yaml
lib/spack/spack/main.py:1007 ==> [2023-04-27-09:27:58.223014] SpackError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "any_of"
   2. 'any_of' is not a valid dependency for any package in the DAG
lib/spack/spack/error.py:54 ==> [2023-04-27-09:27:58.223246] Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "any_of"
   2. 'any_of' is not a valid dependency for any package in the DAG
Traceback (most recent call last):
  File "/home/deepthought/spack/lib/spack/spack/cmd/__init__.py", line 222, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/spec.py", line 2821, in concretize
    self._new_concretize(tests)
  File "/home/deepthought/spack/lib/spack/spack/spec.py", line 2796, in _new_concretize
    result = solver.solve([self], tests=tests)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/solver/asp.py", line 2634, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/solver/asp.py", line 794, in solve
    error_handler.raise_if_errors()
  File "/home/deepthought/spack/lib/spack/spack/solver/asp.py", line 634, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "any_of"
   2. 'any_of' is not a valid dependency for any package in the DAG

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepthought/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deepthought/spack/lib/spack/spack/cmd/__init__.py", line 236, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "any_of"
   2. 'any_of' is not a valid dependency for any package in the DAG
```

### Information on your system

* **Spack:** 0.20.0.dev0 (f6464abfcbd0a1779060f74f54461d9c7c1bec1a)
* **Python:** 3.11.2
* **Platform:** linux-debian12-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by blue42u** [comment]
The root cause appears to be an unintended parsing of the YAML, the `*common` anchor does not expand to the full `any_of: ['@:']` node:
```console
$ spack python
Spack version 0.20.0.dev0
Python 3.11.2, Linux x86_64
>>> import ruamel.yaml
>>> with open("c/packages.yaml", "r") as f: data = ruamel.yaml.load(f)
>>> data["packages"]["zlib"]
{'require': ['any_of']}
```

https://github.com/spack/spack/pull/37008 does NOT fix this, the latest ruamel.yaml still gives the above interpretation. Adding a newline after the `&common` gives the intended parsing (i.e. `*common` expands to `any_of: ['@:']`).

CC @alalazo

**Comment by blue42u** [comment]
After an hour or two reading the [YAML 1.2 spec](https://yaml.org/spec/1.2.2), I think `ruamel.yaml` is correct in this case. The general rule is that `!tags` and `&anchors` bind "closely" to the following (flow) value on the same line, e.g. in the above case `&common` applies to the `any_of` key and not the entire `any_of: ...` mapping. To apply to a block-mapping (or block-sequence) they need to be at the end of a line (ignoring comments).

Although I didn't find this particular example, a number of the tests in the YAML test suite test for something similar:
 - https://github.com/yaml/yaml-test-suite/blob/main/src/ZH7C.yaml
 - https://github.com/yaml/yaml-test-suite/blob/main/src/6BFJ.yaml
 - https://github.com/yaml/yaml-test-suite/blob/main/src/U3XV.yaml

With that in mind, I'm going to call this user error (507 Insufficient Coffee). The error message is still needlessly confusing but that's an issue separate from the YAML anchors.
