### ISSUE TITLE
spack cannot build itself

### ISSUE THREAD

**Issue by ildar** [LLNL/spack#37730]
### Steps to reproduce

git clone --depth=1 https://github.com/spack/spack/
spack/bin/spack install spack

### Error message

...
==> [2023-05-17-01:55:17.879014] SpackError: concretization failed for the following reasons:                                                                              [1/1526]
                                                                                         
   1. 'binutils' required multiple values for single-valued variant 'ld'
==> [2023-05-17-01:55:17.879224] SpackError: concretization failed for the following reasons:

   1. 'binutils' required multiple values for single-valued variant 'ld'
==> [2023-05-17-01:55:17.879308] Error: concretization failed for the following reasons:

   1. 'binutils' required multiple values for single-valued variant 'ld'
Traceback (most recent call last):
  File "/root/spack/lib/spack/spack/cmd/__init__.py", line 220, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/root/spack/lib/spack/spack/spec.py", line 2905, in concretize
    self._new_concretize(tests)
  File "/root/spack/lib/spack/spack/spec.py", line 2880, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/root/spack/lib/spack/spack/solver/asp.py", line 2766, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/root/spack/lib/spack/spack/solver/asp.py", line 817, in solve
    error_handler.raise_if_errors()
  File "/root/spack/lib/spack/spack/solver/asp.py", line 651, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons: 

   1. 'binutils' required multiple values for single-valued variant 'ld'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/root/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/root/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/root/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/root/spack/lib/spack/spack/cmd/install.py", line 368, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/root/spack/lib/spack/spack/cmd/install.py", line 481, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/root/spack/lib/spack/spack/cmd/install.py", line 448, in concrete_specs_from_cli 
    concrete_specs = spack.cmd.parse_specs(
  File "/root/spack/lib/spack/spack/cmd/__init__.py", line 234, in parse_specs
    raise spack.error.SpackError(msg) from e 
spack.error.SpackError: concretization failed for the following reasons:

   1. 'binutils' required multiple values for single-valued variant 'ld'

### Information on your system

tried 3 different systems: RH-based (8,9) + ALTLinux.

* **Spack:** 0.20.0.dev0 (9ee2d79de172de14477a78e5d407548a63eea33a)
* **Python:** 3.9.6
* **Platform:** linux-altlinuxp10-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by ildar** [comment]
I assume this as a **major bug**: it prevents a user to bootstrap spack on his system.

**Comment by haampie** [comment]
It's not a major bug since being able to install spack with spack means that spack already works ;)

Fix is here #37738

**Comment by ildar** [comment]
Thanks a lot for fixing that. I'll try it today.
