### ISSUE TITLE
compilername.Spec has no attribute compilername

### ISSUE THREAD

**Issue by tlivolsi** [LLNL/spack#37774]
### Steps to reproduce

I ran `spack install ...` and `spack uninstall ...`. 

### Error message

```
$ spack --debug --stacktrace install gcc %oneapi@2021.4.0

gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/cmd/__init__.py:123 ==> [2023-05-18-13:02:48.232994] Imported install from built-in commands
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.305120] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.378178] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/cmd/__init__.py:123 ==> [2023-05-18-13:02:48.385531] Imported install from built-in commands
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.526214] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/bootstrap.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.570307] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/repos.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.607326] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.648363] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/database.py:391 ==> [2023-05-18-13:02:48.653117] DATABASE LOCK TIMEOUT: 60s
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/database.py:397 ==> [2023-05-18-13:02:48.653445] PACKAGE LOCK TIMEOUT: No timeout
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/database.py:391 ==> [2023-05-18-13:02:48.654317] DATABASE LOCK TIMEOUT: 60s
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/database.py:397 ==> [2023-05-18-13:02:48.654658] PACKAGE LOCK TIMEOUT: No timeout
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/config.py:125 ==> [2023-05-18-13:02:48.655037] [BOOTSTRAP CONFIG SCOPE] name=_builtin
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.655846] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/bootstrap.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/config.py:138 ==> [2023-05-18-13:02:48.668514] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/config.py:139 ==> [2023-05-18-13:02:48.668812] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/linux
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/config.py:138 ==> [2023-05-18-13:02:48.669112] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/spack/.spack/bootstrap/config
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/config.py:139 ==> [2023-05-18-13:02:48.669414] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/spack/.spack/bootstrap/config/linux
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.693616] Reading config from file /home/spack/.spack/bootstrap/config/linux/compilers.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/_common.py:223 ==> [2023-05-18-13:02:48.838168] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:48.840962] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/bootstrap.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/_common.py:185 ==> [2023-05-18-13:02:48.896899] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:57.130934] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:57.349785] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/modules.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:57.372637] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/linux/modules.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:58.028901] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/packages.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/_common.py:223 ==> [2023-05-18-13:02:58.138300] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/_common.py:223 ==> [2023-05-18-13:02:58.150439] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/core.py:376 ==> [2023-05-18-13:02:58.150697] [BOOTSTRAP MODULE clingo] Try importing from Python
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/bootstrap/_common.py:78 ==> [2023-05-18-13:02:58.292796] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/prqkzynv2nwko5mktitebgkeumuxkveu" provides the "clingo" Python module
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:58.294797] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/concretizer.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:58.309449] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/repos.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:58.475962] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/packages.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:58.554848] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/packages.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:59.355585] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:59.393053] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/config.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:02:59.411576] Reading config from file /gpfs/fs1/software/centos7/spack-latest/etc/spack/defaults/mirrors.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/util/web.py:345 ==> [2023-05-18-13:02:59.431174] Checking existence of https://mirror.spack.io/build_cache/index.json
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/util/web.py:373 ==> [2023-05-18-13:02:59.777846] Failure reading URL: HTTP Error 404: Not Found
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/config.py:996 ==> [2023-05-18-13:03:07.278897] Reading config from file /home/spack/.spack/linux/compilers.yaml
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.718470] UNKNOWN SYMBOL: attr("node_compiler", autoconf, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.719789] UNKNOWN SYMBOL: attr("node_compiler", m4, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.720151] UNKNOWN SYMBOL: attr("node_compiler", autoconf-archive, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.720954] UNKNOWN SYMBOL: attr("node_compiler", tar, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.721283] UNKNOWN SYMBOL: attr("node_compiler", mpfr, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.721877] UNKNOWN SYMBOL: attr("node_compiler", gcc, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.722706] UNKNOWN SYMBOL: attr("node_compiler", gettext, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.723306] UNKNOWN SYMBOL: attr("node_compiler", perl, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.724134] UNKNOWN SYMBOL: attr("node_compiler", bzip2, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.725608] UNKNOWN SYMBOL: attr("node_compiler", gmake, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.726506] UNKNOWN SYMBOL: attr("node_compiler", libtool, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.727052] UNKNOWN SYMBOL: attr("node_compiler", zstd, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.727618] UNKNOWN SYMBOL: attr("node_compiler", libiconv, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.728317] UNKNOWN SYMBOL: attr("node_compiler", libxml2, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.729019] UNKNOWN SYMBOL: attr("node_compiler", gawk, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.729571] UNKNOWN SYMBOL: attr("node_compiler", diffutils, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.729890] UNKNOWN SYMBOL: attr("node_compiler", xz, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.730196] UNKNOWN SYMBOL: attr("node_compiler", automake, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.731061] UNKNOWN SYMBOL: attr("node_compiler", texinfo, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.731319] UNKNOWN SYMBOL: attr("node_compiler", zlib, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.731768] UNKNOWN SYMBOL: attr("node_compiler", gmp, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.734320] UNKNOWN SYMBOL: attr("libiconv", iconv)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.735832] UNKNOWN SYMBOL: attr("node_compiler", ncurses, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/solver/asp.py:2603 ==> [2023-05-18-13:03:26.736169] UNKNOWN SYMBOL: attr("node_compiler", mpc, oneapi)
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py:2819 ==> [2023-05-18-13:03:26.763882] Ordered hashes [gmake]: gmake/142/ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py:2819 ==> [2023-05-18-13:03:26.772330] Ordered hashes [gmp]: gmp/136/69ad2e25f05ff4f347e5372f35f385163c66527000b15f57f0496b5fab62f48c
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py:2819 ==> [2023-05-18-13:03:26.773977] Ordered hashes [tar]: tar/637/d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4, tar/638/08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c, tar/639/5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1538 ==> [2023-05-18-13:03:27.435604] Initializing the build queue from the build requests
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1150 ==> [2023-05-18-13:03:27.435888] Initializing the build queue for gcc
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.444986] Pkg id diffutils-3.8-czzvzvophclh4ewfwmprchlozjxk76s5 has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.445260] - gcc-13.1.0-2cfcrlwszynueckr3lltlxpk3hbwlz5o
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.447628] Requeueing a build task for diffutils-3.8-czzvzvophclh4ewfwmprchlozjxk76s5 with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.452767] Pkg id gawk-4.0.2-bpwf4qukknnaaj2qaypioqa3flhfdc7h has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.453013] - gcc-13.1.0-2cfcrlwszynueckr3lltlxpk3hbwlz5o
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.455366] Requeueing a build task for gawk-4.0.2-bpwf4qukknnaaj2qaypioqa3flhfdc7h with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.457512] Pkg id gmake-3.82-s4shby5ggd6dsljdgqyuo5wjmyey2ksg has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.457752] - gcc-13.1.0-2cfcrlwszynueckr3lltlxpk3hbwlz5o
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.459939] Requeueing a build task for gmake-3.82-s4shby5ggd6dsljdgqyuo5wjmyey2ksg with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.463881] Pkg id autoconf-2.69-67je37rxgfmt4wimknnylfusew5lclww has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.464132] - mpfr-4.2.0-t53tcjqe45m4jgkudi6o5uoe7gecsf5r
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.464353] - gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.466235] Requeueing a build task for autoconf-2.69-67je37rxgfmt4wimknnylfusew5lclww with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.468196] Pkg id automake-1.16.5-ayq7erkj7hom6em5ol4yvdvugpard45m has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.468438] - mpfr-4.2.0-t53tcjqe45m4jgkudi6o5uoe7gecsf5r
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.468655] - gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.470716] Requeueing a build task for automake-1.16.5-ayq7erkj7hom6em5ol4yvdvugpard45m with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.472578] Pkg id libtool-2.10.8-bjaiaqbu5jnxppyubjqgrv6od4jc6dqg has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.472816] - gcc-13.1.0-2cfcrlwszynueckr3lltlxpk3hbwlz5o
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.473046] - gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.473263] - mpfr-4.2.0-t53tcjqe45m4jgkudi6o5uoe7gecsf5r
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.475119] Requeueing a build task for libtool-2.10.8-bjaiaqbu5jnxppyubjqgrv6od4jc6dqg with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.477149] Pkg id m4-1.4.19-kka6dmq2iiyetomqmnppdpiy3woleg3j has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.477388] - mpfr-4.2.0-t53tcjqe45m4jgkudi6o5uoe7gecsf5r
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.477607] - gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.479513] Requeueing a build task for m4-1.4.19-kka6dmq2iiyetomqmnppdpiy3woleg3j with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2179 ==> [2023-05-18-13:03:27.480605] Pkg id gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj has the following dependents:
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.480846] - gcc-13.1.0-2cfcrlwszynueckr3lltlxpk3hbwlz5o
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.481087] - mpfr-4.2.0-t53tcjqe45m4jgkudi6o5uoe7gecsf5r
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:2181 ==> [2023-05-18-13:03:27.481306] - mpc-1.3.1-jrjd2bx2b25lbhj67gbjqqkpepwn4w43
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py:1359 ==> [2023-05-18-13:03:27.484469] Requeueing a build task for gmp-6.2.1-2mz2deu2z4vnhehczoiw4sutyijzkftj with status 'queued'
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/main.py:1021 ==> [2023-05-18-13:03:27.486901] SpecFormatStringError: Attempted to format attribute compilername.Spec  has no attribute compilername
gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/error.py:54 ==> [2023-05-18-13:03:27.510070] Error: Attempted to format attribute compilername.Spec  has no attribute compilername
Traceback (most recent call last):
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py", line 4313, in write_attribute
    current = getattr(current, part)
AttributeError: 'Spec' object has no attribute 'compilername'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/cmd/install.py", line 368, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/cmd/install.py", line 493, in install_without_active_env
    builder.install()
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py", line 1591, in install
    self._init_queue()
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py", line 1540, in _init_queue
    self._add_tasks(request, all_dependencies)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/installer.py", line 1216, in _add_tasks
    spack.store.db.clear_failure(dep, force=False)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/database.py", line 486, in clear_failure
    lock = self._prefix_failures.pop(spec.prefix, None)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py", line 1754, in prefix
    self.prefix = spack.store.layout.path_for_spec(self)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/directory_layout.py", line 335, in path_for_spec
    path = self.relative_path_for_spec(spec)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/directory_layout.py", line 106, in relative_path_for_spec
    path = spec.format(projection)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py", line 4356, in format
    write_attribute(self, attribute, color)
  File "/gpfs/fs1/software/centos7/spack-latest/lib/spack/spack/spec.py", line 4318, in write_attribute
    raise SpecFormatStringError(m)
spack.spec.SpecFormatStringError: Attempted to format attribute compilername.Spec  has no attribute compilername```

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by marcmengel** [comment]
If you have older syntax projections in your config:
```
  install_tree:
    projections:
      all: ...$COMPILERNAME...
```
You get this error...  You need to convert it to {compiler.name}, etc.  as in
 ```
 install_tree:
     projections:
        all: "...{compiler.name} ..." 
```

**Comment by alalazo** [comment]
I'll have a quick look how hard it is to improve the error message on this.

**Comment by pauleonix** [comment]
I ran into the same issue.

**Comment by mcuma** [comment]
Same here, I tend to copy previous version config files to new version. This has taught me to be more careful when diffing the old and new config files.

It'd be nice, though, in the error message, to say something like the projections syntax has changed. That would have saved me some time before resorting to Google and finding this PR. Thanks for having this PR, that saved me a bunch more time.
