### ISSUE TITLE
Cannot edit recipe using fully qualified name

### ISSUE THREAD

**Issue by jedwards4b** [LLNL/spack#37777]
### Steps to reproduce

I'm trying to add a variant to a spack package but running into an issue.  My spack repo list is
```
 spack repo list
==> 4 package repositories.
ncar.hpcd    /glade/work/csgteam/spack-deployments/gust/23.04/envs/build/repos/ncar.hpcd
future       /glade/work/csgteam/spack-deployments/gust/23.04/envs/build/repos/future
builtin      /glade/u/apps/cseg/spack/var/spack/repos/builtin
builtin      /glade/u/apps/gust/23.04/spack/var/spack/repos/builtin
```
and the one I want to modify is the third one.   So I read the docs and it seems like I should be able to do
```
 spack edit builtin.parallelio
==> Error: No package for 'parallelio' was found.
    Use `spack create` to create a new package
```

### Error message

 ```
spack --debug --stacktrace edit builtin.parallelio
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:31.937828] Reading config from file /glade/u/apps/cseg/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:31.972710] Reading config from file /glade/u/apps/cseg/spack/etc/spack/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.036872] Reading config from file /glade/u/apps/cseg/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.061368] Reading config from file /glade/u/apps/cseg/spack/etc/spack/upstreams.yaml
lib/spack/spack/environment/environment.py:1035 ==> [2023-05-18-13:35:32.065362] Creating SingleFileScope env:paralleliobld:/glade/u/apps/gust/23.04/config/modules.yaml for '/glade/u/apps/gust/23.04/config/modules.yaml'
lib/spack/spack/environment/environment.py:1035 ==> [2023-05-18-13:35:32.066048] Creating SingleFileScope env:paralleliobld:/glade/u/apps/gust/23.04/config/repos.yaml for '/glade/u/apps/gust/23.04/config/repos.yaml'
lib/spack/spack/environment/environment.py:1035 ==> [2023-05-18-13:35:32.066691] Creating SingleFileScope env:paralleliobld:/glade/u/apps/gust/23.04/config/compilers.yaml for '/glade/u/apps/gust/23.04/config/compilers.yaml'
lib/spack/spack/environment/environment.py:1035 ==> [2023-05-18-13:35:32.067310] Creating SingleFileScope env:paralleliobld:/glade/u/apps/gust/23.04/config/packages.yaml for '/glade/u/apps/gust/23.04/config/packages.yaml'
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.068294] Reading config from file /glade/u/apps/gust/23.04/config/modules.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.196347] Reading config from file /glade/u/apps/gust/23.04/config/repos.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.199582] Reading config from file /glade/u/apps/gust/23.04/config/compilers.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.248231] Reading config from file /glade/u/apps/gust/23.04/config/packages.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.386515] Reading config from file /glade/u/apps/cseg/spack/var/spack/environments/paralleliobld/spack.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.402851] Reading config from file /glade/u/apps/cseg/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.434819] Reading config from file /glade/u/apps/cseg/spack/etc/spack/config.yaml
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.448361] Reading config from file /glade/u/apps/cseg/spack/etc/spack/upstreams.yaml
lib/spack/spack/environment/environment.py:201 ==> [2023-05-18-13:35:32.451278] Using environment 'paralleliobld'
lib/spack/spack/cmd/__init__.py:125 ==> [2023-05-18-13:35:32.453244] Imported edit from built-in commands
lib/spack/spack/cmd/__init__.py:125 ==> [2023-05-18-13:35:32.454742] Imported edit from built-in commands
lib/spack/spack/config.py:1003 ==> [2023-05-18-13:35:32.459478] Reading config from file /glade/u/apps/cseg/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/cmd/edit.py:46 ==> [2023-05-18-13:35:32.468262] Error: No package for 'parallelio' was found.
    Use `spack create` to create a new package
Traceback (most recent call last):
  File "/glade/u/apps/cseg/spack/lib/spack/spack/main.py", line 1004, in main
    return _main(argv)
  File "/glade/u/apps/cseg/spack/lib/spack/spack/main.py", line 959, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/glade/u/apps/cseg/spack/lib/spack/spack/main.py", line 987, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/glade/u/apps/cseg/spack/lib/spack/spack/main.py", line 636, in _invoke_command
    return_val = command(parser, args)
  File "/glade/u/apps/cseg/spack/lib/spack/spack/cmd/edit.py", line 138, in edit
    edit_package(name, args.repo, args.namespace)
  File "/glade/u/apps/cseg/spack/lib/spack/spack/cmd/edit.py", line 46, in edit_package
    tty.die(
  File "/glade/u/apps/cseg/spack/lib/spack/llnl/util/tty/__init__.py", line 252, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system

/glade/u/apps/cseg/spack> spack debug report
* **Spack:** 0.20.0.dev0 (2a91eedd96291278675e3a43455f418ff2591481)
* **Python:** 3.10.8
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Why do you have 2 repositories named `builtin` in your configuration:
```console
$ spack repo list
==> 4 package repositories.
ncar.hpcd    /glade/work/csgteam/spack-deployments/gust/23.04/envs/build/repos/ncar.hpcd
future       /glade/work/csgteam/spack-deployments/gust/23.04/envs/build/repos/future
builtin      /glade/u/apps/cseg/spack/var/spack/repos/builtin
builtin      /glade/u/apps/gust/23.04/spack/var/spack/repos/builtin
```

? That is not supported by current Spack. Do you see the same issue if you use only one or rename the third to a unique name?

**Comment by alalazo** [comment]
> Do you see the same issue if you use only one or rename the third to a unique name?

I went on trying this and can confirm we have 2 issues. I opened #38220 for the lack of error messages when using 2 repositories with the same namespace. For this one, note that there is a `--repo` argument to `spack edit` that takes a _path_:
```console
$ spack edit --help
usage: spack edit [-h] [-b | -c | -d | -t | -m | -r REPO | -N NAMESPACE] [package]

open package files in $EDITOR

positional arguments:
  package               package name

optional arguments:
  -N NAMESPACE, --namespace NAMESPACE
                        namespace of package to edit
  -b, --build-system    Edit the build system with the supplied name.
  -c, --command         edit the command with the supplied name
  -d, --docs            edit the docs with the supplied name
  -h, --help            show this help message and exit
  -m, --module          edit the main spack module with the supplied name
  -r REPO, --repo REPO  path to repo to edit package in
  -t, --test            edit the test with the supplied name
```
That works, but I agree that it would be more natural to use spec syntax.
