### ISSUE TITLE
spack setup -i fails

### ISSUE THREAD

**Issue by junghans** [LLNL/spack#3795]
```
$ spack setup -i flecsi @develop
==> Generating spconfig.py [flecsi@develop%gcc@6.2.0~debug arch=linux-ubuntu16-x86_64 /ceezqx6]
Traceback (most recent call last):
  File "/home/junghans/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/home/junghans/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/home/junghans/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/home/junghans/spack/lib/spack/spack/cmd/setup.py", line 178, in setup
    inst_args = parser.parse_args(
UnboundLocalError: local variable 'parser' referenced before assignment
```

**Comment by adamjstewart** [comment]
`spack setup` doesn't work. Hasn't for a very long time. I'm adding that to the documentation in #3781. See #2597 and #2662 for details. Also try out #2664 and see if it fixes your problem.

**Comment by citibeth** [comment]
See #2664, I fixed this in December.

**Comment by junghans** [comment]
Nice, still needs to be merged though.
