### ISSUE TITLE
Installation issue: intel-oneapi-compilers

### ISSUE THREAD

**Issue by kaanolgu** [LLNL/spack#37997]
### Steps to reproduce the issue

```console
$ spack install intel-oneapi-compilers
[+] /lustre/home/br-kolgu/spack/opt/spack/cray-rhel8-broadwell/gcc-12.1.0/patchelf-0.16.1-amz4mssrwl6dctoh3agga4rcfwtnt7gi
==> Installing intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7
==> No binary for intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7 found: installing from source
==> Using cached archive: /lustre/home/br-kolgu/spack/var/spack/cache/_source-cache/archive/3a/3ac1c1179501a2646cbb052b05426554194573b4f8e2344d7699eed03fbcfa1d
==> Using cached archive: /lustre/home/br-kolgu/spack/var/spack/cache/_source-cache/archive/76/7639af4b6c928e9e3ba92297a054f78a55f4f4d0db9db0d144cc6653004e4f24
==> Moving resource stage
        source: /tmp/br-kolgu/spack-stage/resource-fortran-installer-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7/spack-src/
        destination: /tmp/br-kolgu/spack-stage/spack-stage-intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7/spack-src/fortran-installer
==> No patches needed for intel-oneapi-compilers
==> intel-oneapi-compilers: Executing phase: 'install'
Process Process-1:
Traceback (most recent call last):
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1051, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 2089, in build_process
    return installer.run()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 1954, in run
    self._real_install()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 2049, in _real_install
    phase_fn.execute()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/builder.py", line 436, in execute
    callback(self.builder)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/builder.py", line 353, in _wrapped
    return fn(builder.pkg_with_dispatcher)
  File "/lustre/home/br-kolgu/spack/var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py", line 244, in extend_config_flags
    classic_flags = ["-gcc-name={}".format(self.compiler.cc)]
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/compilers/gcc.py", line 218, in prefix
    "could not find install prefix of GCC from output:\n\t{}".format(gcc_output)
RuntimeError: could not find install prefix of GCC from output:
        programs: =/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/share/../bin:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../x86_64-suse-linux/bin
libraries: =/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/lib/clang/11.0.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../..:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin/../lib:/lib:/usr/lib


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1068, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1257, in get_package_context
    func = getattr(obj, tb.tb_frame.f_code.co_name, "")
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/compilers/gcc.py", line 218, in prefix
    "could not find install prefix of GCC from output:\n\t{}".format(gcc_output)
RuntimeError: could not find install prefix of GCC from output:
        programs: =/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/share/../bin:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../x86_64-suse-linux/bin
libraries: =/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/lib/clang/11.0.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../..:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin/../lib:/lib:/usr/lib

...
```

### Error message

<details><summary>Error message</summary>

<pre>
```console
$ spack install intel-oneapi-compilers
[+] /lustre/home/br-kolgu/spack/opt/spack/cray-rhel8-broadwell/gcc-12.1.0/patchelf-0.16.1-amz4mssrwl6dctoh3agga4rcfwtnt7gi
==> Installing intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7
==> No binary for intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7 found: installing from source
==> Using cached archive: /lustre/home/br-kolgu/spack/var/spack/cache/_source-cache/archive/3a/3ac1c1179501a2646cbb052b05426554194573b4f8e2344d7699eed03fbcfa1d
==> Using cached archive: /lustre/home/br-kolgu/spack/var/spack/cache/_source-cache/archive/76/7639af4b6c928e9e3ba92297a054f78a55f4f4d0db9db0d144cc6653004e4f24
==> Moving resource stage
        source: /tmp/br-kolgu/spack-stage/resource-fortran-installer-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7/spack-src/
        destination: /tmp/br-kolgu/spack-stage/spack-stage-intel-oneapi-compilers-2023.1.0-hmuz2jnrbtxjho34yv5tf5erqxbnvqm7/spack-src/fortran-installer
==> No patches needed for intel-oneapi-compilers
==> intel-oneapi-compilers: Executing phase: 'install'
Process Process-1:
Traceback (most recent call last):
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1051, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 2089, in build_process
    return installer.run()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 1954, in run
    self._real_install()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/installer.py", line 2049, in _real_install
    phase_fn.execute()
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/builder.py", line 436, in execute
    callback(self.builder)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/builder.py", line 353, in _wrapped
    return fn(builder.pkg_with_dispatcher)
  File "/lustre/home/br-kolgu/spack/var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py", line 244, in extend_config_flags
    classic_flags = ["-gcc-name={}".format(self.compiler.cc)]
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/compilers/gcc.py", line 218, in prefix
    "could not find install prefix of GCC from output:\n\t{}".format(gcc_output)
RuntimeError: could not find install prefix of GCC from output:
        programs: =/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/share/../bin:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../x86_64-suse-linux/bin
libraries: =/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/lib/clang/11.0.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../..:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin/../lib:/lib:/usr/lib


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1068, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/build_environment.py", line 1257, in get_package_context
    func = getattr(obj, tb.tb_frame.f_code.co_name, "")
  File "/lustre/home/br-kolgu/spack/lib/spack/spack/compilers/gcc.py", line 218, in prefix
    "could not find install prefix of GCC from output:\n\t{}".format(gcc_output)
RuntimeError: could not find install prefix of GCC from output:
        programs: =/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/share/../bin:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../x86_64-suse-linux/bin
libraries: =/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/lib/clang/11.0.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../../../lib64:/lib/../lib64:/usr/lib/../lib64:/opt/gcc/8.1.0/snos/lib/gcc/x86_64-suse-linux/8.1.0/../../..:/cm/shared/opt/cray/pe/cce/11.0.4/cce-clang/x86_64/bin/../lib:/lib:/usr/lib

...
```
</pre></details>

### Information on your system

```
$ spack debug report
* **Spack:** 0.20.0.dev0 (3276954ae5806769b6cf4c675c3de1f95b1857e5)
* **Python:** 3.6.8
* **Platform:** cray-rhel8-broadwell
* **Concretizer:** clingo
```

### Additional information

It didn't build any build out or env text files  

```
$ spack spec -l intel-oneapi-compilers
Input spec
--------------------------------
intel-oneapi-compilers

Concretized
--------------------------------
hmuz2jn  intel-oneapi-compilers@2023.1.0%gcc@12.1.0+envmods build_system=generic arch=cray-rhel8-broadwell
amz4mss      ^patchelf@0.16.1%gcc@12.1.0 build_system=autotools arch=cray-rhel8-broadwell
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
It looks like gcc is misconfigured. Can you build other packages with %gcc?

**Comment by kaanolgu** [comment]
Yes I can use the gcc with other packages and also tried `gcc@=12.1.0, gcc@=10.2.0, gcc@=9.2.0 ` no difference in all

**Comment by rscohn2** [comment]
@haampie: The code that queries gcc for its install prefix is not working on this platform (cray?). It does not have the `install:` line. Any ideas on what to do?

**Comment by kaanolgu** [comment]
Hi again, when I did `module purge` before running spack install and changed the spack compilers from cc to gcc. 
it installed it without any errors. 

Update: Did not work afterwards
