### ISSUE TITLE
Concretization error for compilers.yaml: SpecError: Spec version is not concrete: 4

### ISSUE THREAD

**Issue by rickgrubin** [LLNL/spack#38280]
### Steps to reproduce

Create a spack env:
```console
% spack --version
0.19.2 (4e742b3cfa31a8fa5405291749e2b980303205bc)

% ls -FCa
./  ../  common/  install/  site/  .spack-env/  spack.yaml

% cat site/compilers.yaml 
compilers:
- compiler:
    spec: intel@2021.3.0
    paths:
      cc: /apps/USE/easybuild/release/2021.3/software/intel-compilers/2021.3.0/compiler/2021.3.0/linux/bin/intel64/icc
      cxx: /apps/USE/easybuild/release/2021.3/software/intel-compilers/2021.3.0/compiler/2021.3.0/linux/bin/intel64/icpc
      f77: /apps/USE/easybuild/release/2021.3/software/intel-compilers/2021.3.0/compiler/2021.3.0/linux/bin/intel64/ifort
      fc: /apps/USE/easybuild/release/2021.3/software/intel-compilers/2021.3.0/compiler/2021.3.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - env/release/2021.3
    - intel-compilers/2021.3.0
    - GCCcore/10.3.0
    environment: {}
    extra_rpaths: []
```

Also:
```console
% cat common/config.yaml 
config:
  install_hash_length: 7
  install_tree:
    root: $env/install
    projections:
      all: "${COMPILERNAME}/${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"

  build_stage: ${SPACK_STACK_DIR}/cache/build_stage

  test_stage: ${SPACK_STACK_DIR}/cache/test_stage

  source_cache: ${SPACK_STACK_DIR}/cache/source_cache

  misc_cache: ${SPACK_STACK_DIR}/cache/misc_cache

  connect_timeout: 60

% cat spack.yaml 
spack:
  repos:
  - $spack/var/spack/repos/<redacted>-bundles
  - $spack/var/spack/repos/<redacted>

  concretizer:
    unify: when_possible
  config:
    install_tree:
      root: /path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/install
  modules:
    default:
      roots:
        lmod: /path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/install/modulefiles
        tcl: /path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/install/modulefiles
  view: true
  include:
  - site
  - common
  specs:
  - ufs-weather-model-env
```
### Error message
```console
% spack env activate /path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env

% spack -d concretize
[...]
==> [2023-06-08-23:58:35.871738] Reading config from file /path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/compilers.yaml
==> [2023-06-08-23:58:35.921461] SpecError: Spec version is not concrete: 4
==> [2023-06-08-23:58:35.921502] Error: Spec version is not concrete: 4
Traceback (most recent call last):
  File "/path/to/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/path/to/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/path/tok/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/path/to/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/path/to/spack/lib/spack/spack/cmd/concretize.py", line 45, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/path/to/spack/lib/spack/spack/environment/environment.py", line 1271, in concretize
    return self._concretize_together_where_possible(tests=tests)
  File "/path/to/spack/lib/spack/spack/environment/environment.py", line 1300, in _concretize_together_where_possible
    for result in solver.solve_in_rounds(self.user_specs, tests=tests):
  File "/path/to/spack/lib/spack/spack/solver/asp.py", line 2494, in solve_in_rounds
    result, _, _ = self.driver.solve(
  File "/path/to/spack/lib/spack/spack/solver/asp.py", line 628, in solve
    setup.setup(self, specs, reuse=reuse)
  File "/path/to/spack/lib/spack/spack/solver/asp.py", line 2027, in setup
    self.external_packages()
  File "/path/to/spack/lib/spack/spack/solver/asp.py", line 1248, in external_packages
    external_versions = [
  File "/path/to/spack/lib/spack/spack/solver/asp.py", line 1249, in <listcomp>
    (x.version, external_id) for external_id, x in enumerate(external_specs)
  File "/path/to/spack/lib/spack/spack/spec.py", line 3931, in version
    raise spack.error.SpecError("Spec version is not concrete: " + str(self))
spack.error.SpecError: Spec version is not concrete: 4
```

### Information on your system

* **Spack:** 0.19.2 (4e742b3cfa31a8fa5405291749e2b980303205bc)
* **Python:** 3.9.13
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Can you post:
```
$ spack config blame packages
```
?

**Comment by rickgrubin** [comment]
[blame.pkgs.txt](https://github.com/spack/spack/files/11708659/blame.pkgs.txt)

Apologies, uploaded the wrong file the first time, hence the updated comment.

**Comment by alalazo** [comment]
Not sure this is the issue, but there's a malformed external entry in your file:
```
cmake:
/path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/packages.yaml:55         buildable: False
/path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/packages.yaml:56         externals:
/path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/packages.yaml:57         - spec: 3.20.4
/path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/packages.yaml:58           modules:
/path/to/envs/intel-2021.3.0-intelmpi-2021.3.0/ufs-weather-model-env/site/packages.yaml:59           - CMake/3.20.4
```
The spec should say `cmake@3.20.4`

**Comment by rickgrubin** [comment]
Solved:

An entry in the `spack` env's `site/packages.yaml` file was incorrect; rather than `package@x.y.z`, the entry was `x.y.z`

After correcting the missing `package` specifier, concretization was successful.

That said, the error message referencing the `site/compilers.yaml` file is, at best, misleading.

**Comment by alalazo** [comment]
Labeled as not a bug, since the issue is what reported in https://github.com/spack/spack/issues/38280#issuecomment-1586750965 I'll leave this open until we improve the error message.
