### ISSUE TITLE
Internal error when installing multiple variants of one package with `@git.branch=version` syntax

### ISSUE THREAD

**Issue by pauleonix** [LLNL/spack#38484]
### Steps to reproduce

First build works (independent of the variant), e.g.
```console
$ spack install gsl-lite@git.master=0.42 build_type=Release
...
```
Second build fails
```console
$ spack install gsl-lite@git.master=0.42 build_type=Debug
=> Error:                                                                                                                                     
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")                                                                                
  internal_error("imposed hash without imposing all variant values")
```

### Error message

```console                                                 
$ spack --debug --stacktrace install gsl-lite@git.master=0.42 build_type=Debug                                              
lib/spack/spack/cmd/__init__.py:123 ==> [2023-06-20-14:26:15.433414] Imported install from built-in commands
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.440440] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:123 ==> [2023-06-20-14:26:15.485258] Imported install from built-in commands
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.500795] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.537915] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.550326] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:391 ==> [2023-06-20-14:26:15.583006] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-06-20-14:26:15.583294] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/database.py:391 ==> [2023-06-20-14:26:15.584844] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:397 ==> [2023-06-20-14:26:15.585187] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap/config.py:125 ==> [2023-06-20-14:26:15.585375] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.585824] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2023-06-20-14:26:15.592970] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/export/home/pauleonix/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2023-06-20-14:26:15.593130] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/export/home/pauleonix/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2023-06-20-14:26:15.593282] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/export/home/pauleonix/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2023-06-20-14:26:15.593425] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/export/home/pauleonix/.spack/bootstrap/config/linux
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.595464] Reading config from file /export/home/pauleonix/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-20-14:26:15.704682] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64                                                                                                                                                   [27/232]
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:15.707884] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:185 ==> [2023-06-20-14:26:15.737945] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.258639] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.388368] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.401565] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.498147] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.530265] Reading config from file /export/home/pauleonix/.spack/bootstrap/config/packages.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-20-14:26:19.559225] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-20-14:26:19.583170] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:376 ==> [2023-06-20-14:26:19.583327] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:78 ==> [2023-06-20-14:26:19.619947] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10/2l45t4kw3cqqwj6vbxhfwhzlo6b3q2p4" provides the "clingo" Python module
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.620569] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.627305] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.690945] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.723023] Reading config from file /export/home/pauleonix/.spack/packages.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.769226] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:19.794957] Reading config from file /export/home/pauleonix/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:345 ==> [2023-06-20-14:26:19.797941] Checking existence of https://mirror.spack.io/build_cache/index.json
lib/spack/spack/util/web.py:373 ==> [2023-06-20-14:26:20.440526] Failure reading URL: HTTP Error 404: Not Found
lib/spack/spack/config.py:996 ==> [2023-06-20-14:26:22.764978] Reading config from file /export/home/pauleonix/.spack/linux/compilers.yaml
lib/spack/spack/cmd/install.py:452 ==> [2023-06-20-14:26:41.457247] SpackError: 
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")
  internal_error("imposed hash without imposing all variant values")

lib/spack/spack/main.py:1021 ==> [2023-06-20-14:26:41.457461] SpackError: 
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")
  internal_error("imposed hash without imposing all variant values")

lib/spack/spack/error.py:54 ==> [2023-06-20-14:26:41.458766] Error: 
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")
  internal_error("imposed hash without imposing all variant values")

Traceback (most recent call last):
  File "/export/home/pauleonix/spack/lib/spack/spack/cmd/__init__.py", line 220, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/export/home/pauleonix/spack/lib/spack/spack/spec.py", line 2915, in concretize
    self._new_concretize(tests)
  File "/export/home/pauleonix/spack/lib/spack/spack/spec.py", line 2891, in _new_concretize
    result.raise_if_unsat()
  File "/export/home/pauleonix/spack/lib/spack/spack/solver/asp.py", line 481, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: 
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")
  internal_error("imposed hash without imposing all variant values")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/export/home/pauleonix/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/export/home/pauleonix/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/export/home/pauleonix/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/export/home/pauleonix/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/export/home/pauleonix/spack/lib/spack/spack/cmd/install.py", line 368, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/export/home/pauleonix/spack/lib/spack/spack/cmd/install.py", line 481, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/export/home/pauleonix/spack/lib/spack/spack/cmd/install.py", line 448, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/export/home/pauleonix/spack/lib/spack/spack/cmd/__init__.py", line 234, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: 
        gsl-lite@git.master=0.42 build_type=Debug is unsatisfiable, errors are:
  internal_error("Reuse version weight used for build package")
  internal_error("imposed hash without imposing all variant values")
```

### Information on your system

* **Spack:** 0.20.0 (456db45c4a84ccbdb1277874b31b677141641078)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by biddisco** [comment]
just to add my +1 to this issue. I also have this trouble when using syntax like
```
dla-future@git.03d3a0f494d07a94913ab868eb7e38ba7adadc48=develop +cuda ...
```
which will build/install, but a subsequent 
```
dla-future@git.abcdeff494d07a94913ab868eb7e38ba7adadc48=develop +cuda ...
```
will fail unless I delete the first build before attempting the second

**Comment by cameronrutherford** [comment]
+1 to this. Found errors running in GitHub actions when attempting to build and use GHCR build cache https://github.com/pnnl/ExaGO/actions/runs/7022681715/job/19107549413

```
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    exago@develop+hiop~ipopt+mpi+python~raja ^openmpi arch=None-None-x86_64_v2 is unsatisfiable, errors are:
    internal_error("Reuse version weight used for build package")
    internal_error("must choose a single version to satisfy version constraints")
    internal_error("version weights must exist and be unique")
```

With develop command

```
spack -e . develop --path=$(pwd) exago@git.spack-ubuntu-cache-dev=develop
```

First build went through fine, but re-running was giving errors

**Comment by blue42u** [comment]
+1, still experiencing this error on:
* **Spack:** 0.22.0.dev0 (b1ab01280af1ec3065594b739dc2bde3f2107510)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

Minimal reproducer:
```console
$ spack install zlib-ng@git.2.1.5=2.1.5 -opt
$ spack spec zlib-ng@git.2.1.5=2.1.5 +opt
```

**Comment by psakievich** [comment]
I started working on this today. The semi good news is this is isolated to `--reuse` if you disable reuse then the issue goes away.  Still working to understand what is going on.


This is my current test case based on @blue42u 's minimal reproducer
``` console
$ spack install zlib-ng@2.1.5
$ spack install zlib-ng@git.2.1.5=2.1.5
$ spack solve --show asp zlib-ng@2.1.5~opt > non-git-asp.out # solve succeeds
$ spack solve --show asp zlib-ng@git.2.1.5=2.1.5~opt > asp.out # solve fails
$ diff asp.out non-git-asp.out
```

Non-ordering based solver diffs I've identified are:
```
42209c42209,42210
< pkg_fact("zlib-ng",version_satisfies("git.2.1.5=2.1.5","git.2.1.5=2.1.5")).
---
> pkg_fact("zlib-ng",version_satisfies("2.1.5","2.1.5")).
> pkg_fact("zlib-ng",version_satisfies("2.1.5","git.2.1.5=2.1.5")).
35485c35485
< % Spec: zlib-ng@git.2.1.5=2.1.5~opt
---
> % Spec: zlib-ng@2.1.5~opt
35489c35489
< condition_reason(5291,"zlib-ng@git.2.1.5=2.1.5~opt requested explicitly").
---
> condition_reason(5291,"zlib-ng@2.1.5~opt requested explicitly").
35498c35498
< pkg_fact("zlib-ng",effect_msg("zlib-ng@git.2.1.5=2.1.5~opt")).
---
> pkg_fact("zlib-ng",effect_msg("zlib-ng@2.1.5~opt")).
35500c35500
< imposed_constraint(5293,"node_version_satisfies","zlib-ng","git.2.1.5=2.1.5").
---
> imposed_constraint(5293,"node_version_satisfies","zlib-ng","2.1.5").
```

**Comment by psakievich** [comment]
If I extend this case above I see something interesting
``` console
$ spack solve --fresh --show asp zlib-ng@2.1.5~opt > fresh-non-git-asp.out # solve succeeds
$ spack solve --fresh --show asp zlib-ng@git.2.1.5=2.1.5~opt > fresh-asp.out # solve succeeds
$ diff asp.out fresh-asp.out

34897,34903c34835,34840
< pkg_fact("zlib-ng",version_declared("2.1.6",0,"package_py")).
< pkg_fact("zlib-ng",version_declared("2.1.5",1,"package_py")).
< pkg_fact("zlib-ng",version_declared("2.1.4",2,"package_py")).
< pkg_fact("zlib-ng",version_declared("2.0.7",3,"package_py")).
< pkg_fact("zlib-ng",version_declared("2.0.0",4,"package_py")).
< pkg_fact("zlib-ng",version_declared("git.2.1.5=2.1.5",5,"installed")).
< pkg_fact("zlib-ng",version_declared("2.1.5",6,"installed")).
---
> pkg_fact("zlib-ng",version_declared("git.2.1.5=2.1.5",0,"spec")).
> pkg_fact("zlib-ng",version_declared("2.1.6",1,"package_py")).
> pkg_fact("zlib-ng",version_declared("2.1.5",2,"package_py")).
> pkg_fact("zlib-ng",version_declared("2.1.4",3,"package_py")).
> pkg_fact("zlib-ng",version_declared("2.0.7",4,"package_py")).
> pkg_fact("zlib-ng",version_declared("2.0.0",5,"package_py")).
```

So the weights of the `--fresh` case are totally different b/c it is an unknown version that comes from the spec at that point.

Comparing the non-git fresh is not that way
``` console
$ diff *non-git*

34839a34902,34903
> pkg_fact("zlib-ng",version_declared("git.2.1.5=2.1.5",5,"installed")).
> pkg_fact("zlib-ng",version_declared("2.1.5",6,"installed")).
```

**Comment by psakievich** [comment]
For those interested in this issue please feel free to try out #43859 and weigh in.
