### ISSUE TITLE
unable to install MDSplus

### ISSUE THREAD

**Issue by Fiss-and-Fuse** [LLNL/spack#38566]
### Steps to reproduce

create a non-spack virtual enviornment, then enter that environment. load spack, then try 

'spack install mdsplus'
this results in error 1

then try

`spack install mdsplus fflags=\"-O3 -fallow-argument-mismatch\"`

this results in error 2

then try 'spack -d install mdsplus fflags=\"-O3 -fallow-argument-mismatch\"'

this results in error 3

### Error message
```
1) Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'V=1'

9 errors found in build log:
     3935    
     3936       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3937          |                               2
     3938    ......
     3939       31 |       dsc = descr(IDTYPE_FLOAT,resultarr,20,0)
     3940          |                               1
  >> 3941    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
     3942    mdslib_fremotetest.f:35:33:
     3943    
     3944       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3945          |                               2
     3946    ......
     3947       35 |       dsc = descr(IDTYPE_CSTRING,cresult,0,12)
     3948          |                                 1
  >> 3949    Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(12)/REAL(4)).
     3950    mdslib_fremotetest.f:42:33:
     3951    
     3952       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3953          |                               2
     3954    ......
     3955       42 |       dsc = descr(IDTYPE_CSTRING,cresult,0,12)
     3956          |                                 1
  >> 3957    Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(12)/REAL(4)).
     3958    mdslib_fremotetest.f:46:30:
     3959    
     3960       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3961          |                               2
     3962    ......
     3963       46 |       dsc = descr(IDTYPE_LONG,42042,0)
     3964          |                              1
  >> 3965    Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(4)).
     3966    mdslib_fremotetest.f:50:30:
     3967    
     3968       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3969          |                               2
     3970    ......
     3971       50 |       dsc = descr(IDTYPE_LONG,iresult,0)
     3972          |                              1
  >> 3973    Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(4)).
     3974    mdslib_fremotetest.f:54:31:
     3975    
     3976       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3977          |                               2
     3978    ......
     3979       54 |       dsc = descr(IDTYPE_FLOAT,resultarr,20,0)
     3980          |                               1
  >> 3981    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
     3982    mdslib_fremotetest.f:64:31:
     3983    
     3984       27 |       dsc = descr(IDTYPE_FLOAT,result,0)
     3985          |                               2
     3986    ......
     3987       64 |       dsc = descr(IDTYPE_FLOAT,array2d,nx,ny,0)
     3988          |                               1
  >> 3989    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
  >> 3990    make[1]: *** [Makefile:88: /pscratch/sd/t/train349/spack-scratch/spackbuild/spack-stage-mdsplus-stable_release-7-96-17-lvjhtlaxx2pejmnx2gscvip6saf75apj/spack-src/bin/mdsl
             ib_fremotetest] Error 1
     3991    make[1]: Leaving directory '/pscratch/sd/t/train349/spack-scratch/spackbuild/spack-stage-mdsplus-stable_release-7-96-17-lvjhtlaxx2pejmnx2gscvip6saf75apj/spack-src/mdslib'
  >> 3992    make: *** [Makefile:98: mdslib] Error 2

2) Error: {'-O3', '-march=znver3', '-fallow-argument-mismatch'} does not equal {'-march=znver3'}

3) ==> [2023-06-26-12:14:40.767463] Imported install from built-in commands
==> [2023-06-26-12:14:40.769212] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/config.yaml
==> [2023-06-26-12:14:40.782497] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/config.yaml
==> [2023-06-26-12:14:40.782665] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/config.yaml
==> [2023-06-26-12:14:40.790135] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/config.yaml
==> [2023-06-26-12:14:40.790211] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/config.yaml
==> [2023-06-26-12:14:40.790278] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/config.yaml
==> [2023-06-26-12:14:40.790352] Skipping nonexistent config path /global/homes/t/train349/.spack/config.yaml
==> [2023-06-26-12:14:40.790402] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/config.yaml
==> [2023-06-26-12:14:40.790681] Imported install from built-in commands
==> [2023-06-26-12:14:40.794273] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/concretizer.yaml
==> [2023-06-26-12:14:40.798008] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/concretizer.yaml
==> [2023-06-26-12:14:40.798074] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/concretizer.yaml
==> [2023-06-26-12:14:40.798117] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/concretizer.yaml
==> [2023-06-26-12:14:40.798162] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/concretizer.yaml
==> [2023-06-26-12:14:40.798201] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/concretizer.yaml
==> [2023-06-26-12:14:40.798244] Skipping nonexistent config path /global/homes/t/train349/.spack/concretizer.yaml
==> [2023-06-26-12:14:40.798283] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/concretizer.yaml
==> [2023-06-26-12:14:40.798464] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/repos.yaml
==> [2023-06-26-12:14:40.799777] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/repos.yaml
==> [2023-06-26-12:14:40.799908] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/repos.yaml
==> [2023-06-26-12:14:40.801057] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/repos.yaml
==> [2023-06-26-12:14:40.801120] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/repos.yaml
==> [2023-06-26-12:14:40.801164] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/repos.yaml
==> [2023-06-26-12:14:40.801209] Skipping nonexistent config path /global/homes/t/train349/.spack/repos.yaml
==> [2023-06-26-12:14:40.801249] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/repos.yaml
==> [2023-06-26-12:14:42.031926] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/packages.yaml
==> [2023-06-26-12:14:42.048861] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/packages.yaml
==> [2023-06-26-12:14:42.048970] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/packages.yaml
==> [2023-06-26-12:14:42.144779] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/packages.yaml
==> [2023-06-26-12:14:42.144843] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/packages.yaml
==> [2023-06-26-12:14:42.144886] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/packages.yaml
==> [2023-06-26-12:14:42.144931] Skipping nonexistent config path /global/homes/t/train349/.spack/packages.yaml
==> [2023-06-26-12:14:42.144964] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/packages.yaml
==> [2023-06-26-12:14:42.145556] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/bootstrap.yaml
==> [2023-06-26-12:14:42.149146] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/bootstrap.yaml
==> [2023-06-26-12:14:42.149203] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/bootstrap.yaml
==> [2023-06-26-12:14:42.149239] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/bootstrap.yaml
==> [2023-06-26-12:14:42.149277] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/bootstrap.yaml
==> [2023-06-26-12:14:42.149314] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/bootstrap.yaml
==> [2023-06-26-12:14:42.149350] Skipping nonexistent config path /global/homes/t/train349/.spack/bootstrap.yaml
==> [2023-06-26-12:14:42.149387] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/bootstrap.yaml
==> [2023-06-26-12:14:42.149615] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/upstreams.yaml
==> [2023-06-26-12:14:42.149674] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/upstreams.yaml
==> [2023-06-26-12:14:42.149796] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/upstreams.yaml
==> [2023-06-26-12:14:42.151789] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/upstreams.yaml
==> [2023-06-26-12:14:42.151855] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/upstreams.yaml
==> [2023-06-26-12:14:42.151899] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/upstreams.yaml
==> [2023-06-26-12:14:42.151944] Skipping nonexistent config path /global/homes/t/train349/.spack/upstreams.yaml
==> [2023-06-26-12:14:42.151984] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/upstreams.yaml
==> [2023-06-26-12:14:42.152039] DATABASE LOCK TIMEOUT: 120s
==> [2023-06-26-12:14:42.152060] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-26-12:14:42.221551] DATABASE LOCK TIMEOUT: 120s
==> [2023-06-26-12:14:42.221650] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-26-12:14:42.339281] Reading config from file /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/mirrors.yaml
==> [2023-06-26-12:14:42.340221] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/mirrors.yaml
==> [2023-06-26-12:14:42.340428] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/mirrors.yaml
==> [2023-06-26-12:14:42.341497] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/mirrors.yaml
==> [2023-06-26-12:14:42.341565] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/mirrors.yaml
==> [2023-06-26-12:14:42.341623] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/mirrors.yaml
==> [2023-06-26-12:14:42.341672] Skipping nonexistent config path /global/homes/t/train349/.spack/mirrors.yaml
==> [2023-06-26-12:14:42.341717] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/mirrors.yaml
==> [2023-06-26-12:14:42.342379] Checking existence of file:///global/cfs/cdirs/nstaff/www/spack/caches/builtin/build_cache/index.json
==> [2023-06-26-12:14:42.414592] Cached index for file:///global/cfs/cdirs/nstaff/www/spack/caches/builtin already up to date
==> [2023-06-26-12:14:42.414968] Checking existence of file:///global/cfs/cdirs/nstaff/www/spack/caches/dev/build_cache/index.json
==> [2023-06-26-12:14:42.418977] Cached index for file:///global/cfs/cdirs/nstaff/www/spack/caches/dev already up to date
==> [2023-06-26-12:14:42.419129] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2023-06-26-12:14:42.903418] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-06-26-12:14:42.905551] DATABASE LOCK TIMEOUT: 120s
==> [2023-06-26-12:14:42.905597] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-26-12:14:42.965657] DATABASE LOCK TIMEOUT: 120s
==> [2023-06-26-12:14:42.965703] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-26-12:14:44.545440] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/compilers.yaml
==> [2023-06-26-12:14:44.545539] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/defaults/linux/compilers.yaml
==> [2023-06-26-12:14:44.545648] Reading config from file /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/compilers.yaml
==> [2023-06-26-12:14:44.567113] Skipping nonexistent config path /global/common/software/nersc/pm-2023q1/spack-stacks-1/config/linux/compilers.yaml
==> [2023-06-26-12:14:44.567186] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/compilers.yaml
==> [2023-06-26-12:14:44.567234] Skipping nonexistent config path /global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/etc/spack/linux/compilers.yaml
==> [2023-06-26-12:14:44.567308] Skipping nonexistent config path /global/homes/t/train349/.spack/compilers.yaml
==> [2023-06-26-12:14:44.567355] Skipping nonexistent config path /global/homes/t/train349/.spack/linux/compilers.yaml
==> [2023-06-26-12:15:07.376930] build(mdsplus)
Traceback (most recent call last):
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/bin/spack", line 56, in <module>
    sys.exit(main())
             ^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/cmd/install.py", line 531, in install
    abstract_specs, concrete_specs = specs_from_cli(args, install_kwargs, reporter)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/cmd/install.py", line 447, in specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/cmd/__init__.py", line 228, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/spec.py", line 2941, in concretize
    self._new_concretize(tests)
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/spec.py", line 2916, in _new_concretize
    result = solver.solve([self], tests=tests)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/solver/asp.py", line 2458, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/solver/asp.py", line 708, in solve
    answers = builder.build_specs(tuples)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/solver/asp.py", line 2316, in build_specs
    self.reorder_flags()
  File "/global/common/software/nersc/pm-2022q4/sw/spack-0.19.2/lib/spack/spack/solver/asp.py", line 2211, in reorder_flags
    assert spec_compiler_flags_set == compiler_flags_set, "%s does not equal %s" % (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'-fallow-argument-mismatch', '-march=znver3', '-O3'} does not equal {'-march=znver3'}
```

* **Python:** 3.11.3
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### Information on your system

pearlmutter training account for hackathon

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Follow-up: user reports that error 2 does not occur with latest spack

Error 1 might be a build issue for `mdsplus` on this system: does the associated site for `mdsplus` have recommendations related to building with this flag, or for resolving this error message, or building on this type of system?

**Comment by alalazo** [comment]
Converting to "build error" following https://github.com/spack/spack/issues/38566#issuecomment-1608406876
