### ISSUE TITLE
Error in environment for spec without name (hash only)

### ISSUE THREAD

**Issue by EbiArnie** [LLNL/spack#38580]
### Steps to reproduce

I want to add a concrete and installed spec to an environment (to keep it from
being uninstalled).
To do this, I just add the hash to the environment.
The environment accepts the hash, but doesn't actually like it -
find and concretize will now give an error.

```console
# Create a clean env
$ spack env create bug1
==> Created environment 'bug1' in /home/arnie/r/spack/var/spack/environments/bug1
==> You can activate this environment with:
==>   spack env activate bug1


# Grab the hash of any installed package
$ spack find -L zlib
-- linux-ubuntu22.04-icelake / gcc@11.3.0 -----------------------
x4i2jhsuf2lpcrktxvrbrupsbs5dmvhh zlib@1.2.13

-- linux-ubuntu22.04-x86_64_v3 / gcc@11.3.0 ---------------------
mntflxrgekkm5lbpbl5r66lh2ieted4y zlib@1.2.13
==> 2 installed packages

# Add package by hash
$ spack -e bug1 add /x4i2jhsuf
==> Adding /x4i2jhsuf to environment bug1


# The environment spack.yaml now looks like this:
spack:
  # add package specs to the `specs` list
  specs:
  - /x4i2jhsuf
  view: true
  concretizer:
    unify: true

# These will now give errors
$ spack -e bug1 concretize
==> Error: Invalid module name:

$ spack -e bug1 install
==> Error: Invalid module name:

$ spack -e bug1 spec
==> Error: Invalid module name:

$ spack -e bug1 find
==> In environment bug1
==> Root specs
==> Error: integer division or modulo by zero
```

### Error message

```console
$ spack --debug --stacktrace -e bug1 concretize
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.783963] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.801009] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.815444] Reading config from file /home/arnie/r/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.819209] Reading config from file /home/arnie/r/spack/var/spack/environments/bug1/spack.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.821052] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.837828] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/environment/environment.py:207 ==> [2023-06-27-11:04:08.850282] Using environment 'bug1'
lib/spack/spack/cmd/__init__.py:123 ==> [2023-06-27-11:04:08.852796] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2023-06-27-11:04:08.853201] Imported concretize from built-in commands
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.862356] Reading config from file /home/arnie/r/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/database.py:396 ==> [2023-06-27-11:04:08.873650] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:402 ==> [2023-06-27-11:04:08.873974] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.896015] Reading config from file /home/arnie/r/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.901027] Reading config from file /home/arnie/r/spack/var/spack/environments/bug1/spack.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.902930] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.915778] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/environment/environment.py:231 ==> [2023-06-27-11:04:08.928715] Deactivated environment 'bug1'
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.932910] Reading config from file /home/arnie/r/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.934370] Reading config from file /home/arnie/r/spack/etc/spack/repos.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.936717] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.949224] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/database.py:396 ==> [2023-06-27-11:04:08.961862] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/database.py:402 ==> [2023-06-27-11:04:08.961996] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap/config.py:125 ==> [2023-06-27-11:04:08.962130] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.962512] Reading config from file /home/arnie/r/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2023-06-27-11:04:08.967033] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/arnie/r/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2023-06-27-11:04:08.967197] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/arnie/r/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2023-06-27-11:04:08.967320] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/arnie/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2023-06-27-11:04:08.967422] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/arnie/.spack/bootstrap/config/linux
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.969697] Reading config from file /home/arnie/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-27-11:04:08.989076] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:08.989364] Reading config from file /home/arnie/r/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:185 ==> [2023-06-27-11:04:08.997322] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.029306] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.078365] Reading config from file /home/arnie/r/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.086098] Reading config from file /home/arnie/r/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.128046] Reading config from file /home/arnie/r/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-27-11:04:09.149862] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-06-27-11:04:09.152412] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:376 ==> [2023-06-27-11:04:09.152517] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:78 ==> [2023-06-27-11:04:09.168494] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10/idkenmhnscjlu5gjqhpcqa4h7o2a7aow" provides the "clingo" Python module
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.169249] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.182260] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.196800] Reading config from file /home/arnie/r/spack/var/spack/environments/bug1/spack.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.198845] Reading config from file /home/arnie/r/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.211794] Reading config from file /home/arnie/r/spack/etc/spack/config.yaml
lib/spack/spack/environment/environment.py:207 ==> [2023-06-27-11:04:09.223943] Using environment 'bug1'
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.224109] Reading config from file /home/arnie/r/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.227883] Reading config from file /home/arnie/r/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:986 ==> [2023-06-27-11:04:09.229159] Reading config from file /home/arnie/r/spack/etc/spack/repos.yaml
lib/spack/spack/main.py:1021 ==> [2023-06-27-11:04:09.231152] InvalidModuleNameError: Invalid module name:
lib/spack/spack/error.py:54 ==> [2023-06-27-11:04:09.236643] Error: Invalid module name:
Traceback (most recent call last):
  File "/home/arnie/r/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/home/arnie/r/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/arnie/r/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/arnie/r/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/home/arnie/r/spack/lib/spack/spack/cmd/concretize.py", line 46, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/home/arnie/r/spack/lib/spack/spack/environment/environment.py", line 1346, in concretize
    return self._concretize_together(tests=tests)
  File "/home/arnie/r/spack/lib/spack/spack/environment/environment.py", line 1441, in _concretize_together
    concrete_specs: List[spack.spec.Spec] = spack.concretize.concretize_specs_together(
  File "/home/arnie/r/spack/lib/spack/spack/concretize.py", line 743, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/home/arnie/r/spack/lib/spack/spack/concretize.py", line 750, in _concretize_specs_together_new
    result = solver.solve(abstract_specs, tests=kwargs.get("tests", False))
  File "/home/arnie/r/spack/lib/spack/spack/solver/asp.py", line 2777, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "/home/arnie/r/spack/lib/spack/spack/solver/asp.py", line 2730, in _check_input_and_extract_concrete_specs
    spack.spec.Spec.ensure_valid_variants(s)
  File "/home/arnie/r/spack/lib/spack/spack/spec.py", line 3487, in ensure_valid_variants
    pkg_cls = spec.package_class
  File "/home/arnie/r/spack/lib/spack/spack/spec.py", line 1743, in package_class
    return spack.repo.path.get_pkg_class(self.fullname)
  File "/home/arnie/r/spack/lib/spack/spack/repo.py", line 849, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/home/arnie/r/spack/lib/spack/spack/repo.py", line 1236, in get_pkg_class
    class_name = nm.mod_to_class(pkg_name)
  File "/home/arnie/r/spack/lib/spack/spack/util/naming.py", line 54, in mod_to_class
    validate_module_name(mod_name)
  File "/home/arnie/r/spack/lib/spack/spack/util/naming.py", line 156, in validate_module_name
    raise InvalidModuleNameError(mod_name)
spack.util.naming.InvalidModuleNameError: Invalid module name:
```

### Information on your system

* **Spack:** 0.21.0.dev0 (ab10b645c615255a0eb3f124a870c0de52123f00)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed, thanks for reporting.
