### ISSUE TITLE
Remote activities interrupted – Corrupt/rogue mirror?

### ISSUE THREAD

**Issue by Meax5qiu** [LLNL/spack#38612]
### Steps to reproduce

I do have a spack installation where everything (that only relies on local access) does just fine. Right now I am in the process of installing more packages. This worked fine until about half an hour ago, when (apparently) interaction with the Spack servers/mirrors (installation, information retrieval) stopped working.

I don't believe that this is a duplicate, but rather (I guess) it has to do with a transient condition on the spack servers. Commands that worked fine an hour ago, are broken now.

I'm not actually trying to install `tar` (I managed to install it already), but I have chosen this package since it is simple enough to not distract with compilcations from complex build processes.

Affected commands (incomplete list, most likely more):
```
spack install $PACKAGE
spack spec -I $PACKAGE
```

### Error message

```
$ spack install tar
==> Error: source code string cannot contain null bytes
```

```
$ spack --debug install tar

[... a lot of debug stuff that doesn't seem relevant, but I can still post it if needed ...]

==> [2023-06-28-15:37:33.579440] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2023-06-28-15:37:33.659895] Failure reading URL: Download failed: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/usr/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/usr/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/usr/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/usr/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/usr/lib/spack/spack/cmd/install.py", line 531, in install
    abstract_specs, concrete_specs = specs_from_cli(args, install_kwargs, reporter)
  File "/usr/lib/spack/spack/cmd/install.py", line 447, in specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/usr/lib/spack/spack/cmd/__init__.py", line 228, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/usr/lib/spack/spack/spec.py", line 2941, in concretize
    self._new_concretize(tests)
  File "/usr/lib/spack/spack/spec.py", line 2916, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/usr/lib/spack/spack/solver/asp.py", line 2452, in solve
    result, _, _ = self.driver.solve(
  File "/usr/lib/spack/spack/solver/asp.py", line 628, in solve
    setup.setup(self, specs, reuse=reuse, namespace=namespace)
  File "/usr/lib/spack/spack/solver/asp.py", line 1950, in setup
    possible = spack.package_base.possible_dependencies(
  File "/usr/lib/spack/spack/package_base.py", line 2662, in possible_dependencies
    pkg.possible_dependencies(visited=visited, **kwargs)
  File "/usr/lib/spack/spack/package_base.py", line 789, in possible_dependencies
    dep_cls.possible_dependencies(
  File "/usr/lib/spack/spack/package_base.py", line 789, in possible_dependencies
    dep_cls.possible_dependencies(
  File "/usr/lib/spack/spack/package_base.py", line 789, in possible_dependencies
    dep_cls.possible_dependencies(
  [Previous line repeated 18 more times]
  File "/usr/lib/spack/spack/package_base.py", line 783, in possible_dependencies
    dep_cls = spack.repo.path.get_pkg_class(dep_name)
  File "/usr/lib/spack/spack/repo.py", line 981, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/usr/lib/spack/spack/repo.py", line 1357, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
```

Of course, the first thing I checked was if it is a network issue. `mirror.spack.io` is alive and reachable from here. The base URL https://mirror.spack.io is readable (XML gibberish), the file https://mirror.spack.io/build_cache/index.json does not exist (HTTP 404, error code `NoSuchKey`). Tried from several independent entry points into the internet (so it's not an in-house network bug or a firewall issue on my side).

### Information on your system

```
$ spack debug report
* **Spack:** 0.19.0
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Meax5qiu** [comment]
I am not reliably able to reproduce this error. On another machine (identical hardware/software + shared home & spack root), I loaded the same packages (`spack find --loaded -L` bitwise identical), and everything works fine. On the first machine – still broken...

**Comment by alalazo** [comment]
@Meax5qiu Do you have a custom repository? It seems the issue might be coming from some `package.py`, given the stacktrace.

**Comment by alalazo** [comment]
I think the issue here is with a package recipe that contains null characters. Here's a hint how to fix that https://stackoverflow.com/questions/2398393/identifying-and-removing-null-characters-in-unix/2399817#2399817 MArking as not-a-bug for the time being, until I hear back from you.
