### ISSUE TITLE
RISC-V bootstrap issue

### ISSUE THREAD

**Issue by naromero77** [LLNL/spack#38622]
### Steps to reproduce

I am on RISC-V system and the Spack bootstrap phase is failing with the develop branch. I have encountered similar issues with previous releases. On top of that, I am also working on an NFS file system *without* file locking that has the habit of introducing other esoteric issues as well:

For the record, I use version 1 of this RISC-V board: 
https://www.starfivetech.com/en/site/boards

```
spack bootstrap now
```

I don't see an  error, but it looks like the bootstrap phase abruptly dies.

Then if I check the status, I do see an error:
```
n.a.romero@sal-starfive01:~/spack_test$ spack bootstrap status
Spack v0.21.0.dev0 - python@3.10

[PASS] Core Functionalities

==> Error: cannot load package 'go-bootstrap' from the 'builtin' repository: 'riscv64'

```

Just as a data point, in a previous release version of Spack (0.19.2) there was an import test in the bootstrap that seemed to fail in spite of things being installing correctly (almost like a race condition). I ended up hacking things a bit and adding the following to my ~/.bashrc to get things to work properly in the bootstrap.
```
export PYTHONPATH=/sal/home/n.a.romero/.spack/bootstrap/store/linux-ubuntu22.04-riscv64/gcc-11.3.0/clingo-bootstrap-spack-x7yw2k7bgvjubn3w3vddl75eg54volpj/lib/python3.10/site-packages
```

Also, FWIW, I have the following in my ~/.spack/config,yaml:
```
config:
  locks: false
  connection_timeout: 0
```

### Error message

Output from ``spack --debug bootstrap now`` shown below:

```
==> [2023-06-28-20:29:02.120078] Imported bootstrap from built-in commands
==> [2023-06-28-20:29:02.176764] Imported bootstrap from built-in commands
==> [2023-06-28-20:29:02.185738] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-06-28-20:29:02.374761] Reading config from file /sal/home/n.a.romero/.spack/bootstrap.yaml
==> [2023-06-28-20:29:02.430291] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/config.yaml
==> [2023-06-28-20:29:02.994691] Reading config from file /sal/home/n.a.romero/.spack/config.yaml
==> [2023-06-28-20:29:03.074388] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/repos.yaml
==> [2023-06-28-20:29:03.172848] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/config.yaml
==> [2023-06-28-20:29:03.720390] Reading config from file /sal/home/n.a.romero/.spack/config.yaml
==> [2023-06-28-20:29:03.753539] DATABASE LOCK TIMEOUT: 60s
==> [2023-06-28-20:29:03.754661] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-28-20:29:03.764096] DATABASE LOCK TIMEOUT: 60s
==> [2023-06-28-20:29:03.765139] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-28-20:29:03.766416] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-06-28-20:29:03.773145] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-06-28-20:29:03.941909] Reading config from file /sal/home/n.a.romero/.spack/bootstrap.yaml
==> [2023-06-28-20:29:03.980493] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/sal/home/n.a.romero/spack_test/spack/etc/spack/defaults
==> [2023-06-28-20:29:03.981514] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/linux
==> [2023-06-28-20:29:03.982512] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/sal/home/n.a.romero/.spack/bootstrap/config
==> [2023-06-28-20:29:03.983324] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/sal/home/n.a.romero/.spack/bootstrap/config/linux
==> [2023-06-28-20:29:03.989822] Reading config from file /sal/home/n.a.romero/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-06-28-20:29:04.573676] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=riscv64
==> [2023-06-28-20:29:04.578873] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-06-28-20:29:04.884009] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=riscv64'
==> [2023-06-28-20:29:14.300832] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/config.yaml
==> [2023-06-28-20:29:16.441351] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/packages.yaml
==> [2023-06-28-20:29:17.235376] Reading config from file /sal/home/n.a.romero/.spack/bootstrap/config/packages.yaml
==> [2023-06-28-20:32:44.317017] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=riscv64'
==> [2023-06-28-20:32:44.367783] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/modules.yaml
==> [2023-06-28-20:32:44.672338] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/linux/modules.yaml
==> [2023-06-28-20:32:44.784463] Adding env modifications for gnuconfig
==> [2023-06-28-20:32:44.785030] Added env modifications for gnuconfig
==> [2023-06-28-20:32:44.847361] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=riscv64
==> [2023-06-28-20:32:44.887401] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=riscv64
==> [2023-06-28-20:32:44.887902] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-06-28-20:32:45.396723] '/usr/bin/python3.10' '-c' '
import json
from sysconfig import (
    get_config_vars,
    get_config_h_filename,
    get_makefile_filename,
    get_paths,
)

config = get_config_vars()
config['"'"'config_h_filename'"'"'] = get_config_h_filename()
config['"'"'makefile_filename'"'"'] = get_makefile_filename()
config.update(get_paths())

print(json.dumps(config))
'
==> [2023-06-28-20:32:45.815916] Warning: Spec clingo-bootstrap@=spack%gcc@=11.3.0~docs~ipo+python~static_libstdcpp build_system=cmake build_type=Release arch=linux-ubuntu22.04-riscv64 ^bison@=3.8.2%gcc@=11.3.0 build_system=autotools arch=linux-ubuntu22.04-riscv64 ^cmake@=3.22.1%gcc@=11.3.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-riscv64 ^python@=3.10%gcc@=11.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,f2fd060 arch=linux-ubuntu22.04-riscv64 ^re2c@=2.2%gcc@=11.3.0 build_system=generic arch=linux-ubuntu22.04-riscv64 did not provide module clingo
==> [2023-06-28-20:32:45.869387] Bootstrapping clingo from pre-built binaries
==> [2023-06-28-20:32:45.938274] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/mirrors.yaml
==> [2023-06-28-20:32:45.974186] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/index.json
==> [2023-06-28-20:32:46.318821] DATABASE LOCK TIMEOUT: 60s
==> [2023-06-28-20:32:46.320105] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-28-20:32:47.038412] Bootstrapping clingo from pre-built binaries
==> [2023-06-28-20:32:47.104897] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.3/build_cache/index.json
==> [2023-06-28-20:32:47.261049] DATABASE LOCK TIMEOUT: 60s
==> [2023-06-28-20:32:47.262172] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-06-28-20:32:47.740037] Bootstrapping clingo from sources
==> [2023-06-28-20:32:49.020519] '/bin/cmake' '--version'
==> [2023-06-28-20:32:49.158108] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2023-06-28-20:32:49.162187] '/usr/bin/cmake' '--version'
==> [2023-06-28-20:32:49.250173] '/bin/bison' '--version'
==> [2023-06-28-20:32:49.266172] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2023-06-28-20:32:49.269581] '/usr/bin/bison' '--version'
==> [2023-06-28-20:32:49.286673] '/bin/gawk' '--version'
==> [2023-06-28-20:32:49.305140] no bin/ dir found in /bin. Cannot add it as a Spack package
==> [2023-06-28-20:32:49.308863] '/usr/bin/gawk' '--version'
==> [2023-06-28-20:32:49.475200] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/config.yaml
==> [2023-06-28-20:32:50.019474] Reading config from file /sal/home/n.a.romero/.spack/config.yaml
==> [2023-06-28-20:32:50.541797] clingo-bootstrap applying constraint python
==> [2023-06-28-20:32:50.590992] python applying constraint pkgconfig@0.9.0:
==> [2023-06-28-20:32:50.651825] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2023-06-28-20:32:50.683187] clingo-bootstrap applying constraint re2c@0.13:
==> [2023-06-28-20:32:50.713233] clingo-bootstrap applying constraint python
==> [2023-06-28-20:32:50.801267] Reading config from file /sal/home/n.a.romero/spack_test/spack/etc/spack/defaults/config.yaml
==> [2023-06-28-20:32:51.365910] Reading config from file /sal/home/n.a.romero/.spack/config.yaml
Traceback (most recent call last):
  File "/sal/home/n.a.romero/spack_test/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/cmd/bootstrap.py", line 468, in bootstrap
    callbacks[args.subcommand](args)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/cmd/bootstrap.py", line 450, in _now
    spack.bootstrap.ensure_core_dependencies()
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/bootstrap/core.py", line 562, in ensure_core_dependencies
    ensure_clingo_importable_or_raise()
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/bootstrap/core.py", line 497, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(module="clingo", abstract_spec=clingo_root_spec())
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/bootstrap/core.py", line 403, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=riscv64" due to the following failures:
spack-install raised UnknownPackageError: Package 'spack.pkg.builtin.pkgconfig' not found.
    You may need to run 'spack clean -m'.
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/bootstrap/core.py", line 388, in ensure_module_importable_or_raise
    if current_bootstrapper.try_import(module, abstract_spec):
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/bootstrap/core.py", line 297, in try_import
    concrete_spec._old_concretize(  # pylint: disable=protected-access
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/spec.py", line 2778, in _old_concretize
    self._expand_virtual_packages(concretizer),
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/spec.py", line 2686, in _expand_virtual_packages
    copy.normalize(force=True)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/spec.py", line 3405, in normalize
    self.validate_or_raise()
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/spec.py", line 3461, in validate_or_raise
    spack.repo.path.get_pkg_class(spec.fullname)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/repo.py", line 849, in get_pkg_class
    return self.repo_for_pkg(pkg_name).get_pkg_class(pkg_name)
  File "/sal/home/n.a.romero/spack_test/spack/lib/spack/spack/repo.py", line 1242, in get_pkg_class
    raise UnknownPackageError(fullname)
```

I find it odd that its complaining about pkconfig since it is in fact installed as part of Ubuntu:
```
n.a.romero@sal-starfive01:~/spack_test$ dpkg -l | grep -i pkg-config
ii  pkg-config                               0.29.2-1ubuntu3                         riscv64      manage compile and link flags for libraries

```

### Information on your system

* **Spack:** 0.21.0.dev0 (c3f4822f92e0afc70f3a642310c7e1282434d397)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-u74mc
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
After some pair debugging with @naromero77 , the issue is with computing the module paths for these RISC-V boards. `clingo` installs correctly, but we compute the wrong path to be added to `sys.path`, In particular `clingo` is installed under `<some-dir>/site-packages`, but:
```
$ python -m sysconfig
```
outputs:
```
Paths:
        data = "/usr/local"
        include = "/usr/include/python3.10"
        platinclude = "/usr/include/python3.10"
        platlib = "/usr/local/lib/python3.10/dist-packages"
        platstdlib = "/usr/lib/python3.10"
        purelib = "/usr/local/lib/python3.10/dist-packages"
        scripts = "/usr/local/bin"
        stdlib = "/usr/lib/python3.10"
```
so we look under the wrong `dist-packages` folder for the `clingo` extension.

**Comment by nazavode** [comment]
Experiencing exactly the same issue on a different `riscv64` system ([Milk-V Pioneer](https://milkv.io/pioneer)) that ships with Fedora 38.

**Comment by naromero77** [comment]
@alalazo To follow-up from our conversation earlier today. I tried this PR: https://github.com/spack/spack/pull/40773

But I am still encountering a bootstrapping issue with clingo:
```

==> [2023-12-06-18:13:15.012907] Reading config from file /sal/home/n.a.romero/.spack/config.yaml
Traceback (most recent call last):
  File "/sal/home/n.a.romero/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/sal/home/n.a.romero/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/sal/home/n.a.romero/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/sal/home/n.a.romero/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/sal/home/n.a.romero/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/sal/home/n.a.romero/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/sal/home/n.a.romero/spack/lib/spack/spack/cmd/bootstrap.py", line 463, in bootstrap
    callbacks[args.subcommand](args)
  File "/sal/home/n.a.romero/spack/lib/spack/spack/cmd/bootstrap.py", line 445, in _now
    spack.bootstrap.ensure_core_dependencies()
  File "/sal/home/n.a.romero/spack/lib/spack/spack/bootstrap/core.py", line 568, in ensure_core_dependencies
    ensure_clingo_importable_or_raise()
  File "/sal/home/n.a.romero/spack/lib/spack/spack/bootstrap/core.py", line 503, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(module="clingo", abstract_spec=clingo_root_spec())
  File "/sal/home/n.a.romero/spack/lib/spack/spack/bootstrap/core.py", line 395, in ensure_module_importable_or_raise
    assert exception_handler, (
AssertionError: expected at least one exception to have been raised at this point: while bootstrapping clingo
```
