### ISSUE TITLE
spack external find errors out on unreadable path

### ISSUE THREAD

**Issue by mathomp4** [LLNL/spack#38733]
### Steps to reproduce

I ran `spack external find` and it errored out as a path is unreadable by users:

```console
$ spack external find
==> Error: [Errno 13] Permission denied: '/usr/local/lib'
$ ls -ltr /usr/local/  | grep lib
drwxr-xr-x    4 root   root  4096 Aug  5  2021 lib64/
drwx------    9 root   root  4096 Aug 27  2022 lib/
```

It looks like `spack external find` assumes `/usr/local/lib` is readable.

I naively tried `--exclude /usr/local/lib` but `--exclude` is for excluding packages.

### Error message

I also ran:
```console
spack --debug --traceback external find
```
The ending traceback is:
```
Traceback (most recent call last):
  File "/discover/nobackup/mathomp4/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 1024, in main
    return _main(argv)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 979, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 1007, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/cmd/external.py", line 258, in external
    action[args.external_command](args)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/cmd/external.py", line 164, in external_find
    detected_packages.update(spack.detection.by_library(pkg_cls_to_check, path_hints=args.path))
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/detection/path.py", line 149, in by_library
    libraries_in_ld_and_system_library_path(path_hints=path_hints)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/detection/path.py", line 90, in libraries_in_ld_and_system_library_path
    return path_to_dict(search_paths)
  File "/gpfsm/dnb44/mathomp4/spack/lib/spack/spack/detection/common.py", line 115, in path_to_dict
    for lib in os.listdir(search_path):
PermissionError: [Errno 13] Permission denied: '/usr/local/lib'
```

I can provide the full debug if needed, but it is...long!

### Information on your system

* **Spack:** 0.21.0.dev0 (95847a0b373d1fe55772ff39d58aa616bec88932)
* **Python:** 3.9.12
* **Platform:** linux-sles12-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@mathomp4 Can you check #38755 and see if it doesn't error this time?

**Comment by mathomp4** [comment]
> @mathomp4 Can you check #38755 and see if it doesn't error this time?

@alalazo I did a `gh pr checkout 38755` and:

```
$ spack external find
==> The following specs have been detected on this system and added to /home/mathomp4/.spack/packages.yaml
autoconf@2.69    ccache@3.1.9    diffutils@3.3     git@2.12.3                        groff@1.22.2   ninja@1.11.1         swig@3.0.10
automake@1.13.4  cmake@3.5.2     findutils@4.5.12  git@2.31.1                        libtool@2.4.2  openssh@7.2p2        tar@1.34
automake@1.15.1  coreutils@8.25  flex@2.5.37       git@2.40.1.459.g48d89b51b3.dirty  libtool@2.4.6  openssl@1.0.2j-fips  texinfo@4.13
binutils@2.31.1  curl@7.37.0     gawk@4.1.0        git@2.40.1.459.g48d89b51b3.dirty  m4@1.4.16      pkg-config@0.28
bison@2.7        cvs@1.12.12     gawk@5.1.0        gmake@4.0                         m4@1.4.18      subversion@1.8.19
```

I'm not sure why git was found twice, but still, huzzah!

**Comment by alalazo** [comment]
> I'm not sure why git was found twice,

Do you have the same spec in path under two different directories? For instance a view and its prefix/bin ? That's the only guess I have right now...

**Comment by mathomp4** [comment]
Well, it is a cluster with modules and my bashrc is a crazy melange of bash no one should use but I need for productivity. My guess is at login my PATH is a crazy mishmash and poor spack is doing its best. :) 

I can always clean up the `packages.yaml`.
