### ISSUE TITLE
Internal concretizer error, not printing any error message

### ISSUE THREAD

**Issue by rcplane** [LLNL/spack#38794]
### Steps to reproduce

Need to obtain WRF weather research forecast model to compile WRF and dependency libraries with Intel compiler.

Dockerfile, built on Ubuntu 22.04:

```dockerfile
from ghcr.io/spack/tutorial:isc23
USER root
RUN cat /etc/os-release
RUN bash -c "echo hi"
RUN bash -c "git clone --depth=100 --branch=releases/v0.20 https://github.com/spack/spack.git ~/spack"
RUN bash -c "echo '. share/spack/setup-env.sh' >> /root/.bashrc"
RUN bash -c "which spack"
RUN bash -c "spack install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric"
```

```
 > [7/7] RUN bash -c "spack install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric":                      
47.92 ==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
47.92     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
------
Dockerfile:16
--------------------
  14 |     RUN bash -c "echo '. share/spack/setup-env.sh' >> /root/.bashrc"
  15 |     RUN bash -c "which spack"
  16 | >>> RUN bash -c "spack install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric"
  17 |     
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c bash -c \"spack install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric\"" did not complete successfully: exit code: 1
```

### Error message

there is no error message, debug mode output is

<details>

<summary>Debug output</summary>

```
#11 [8/8] RUN bash -c "spack -d install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric"
#11 0.557 ==> [2023-07-08-18:23:19.040830] Imported install from built-in commands
#11 0.559 ==> [2023-07-08-18:23:19.042676] Reading config from file /root/spack/etc/spack/defaults/config.yaml
#11 0.580 ==> [2023-07-08-18:23:19.063419] Reading config from file /etc/spack/config.yaml
#11 0.582 ==> [2023-07-08-18:23:19.065678] Imported install from built-in commands
#11 0.585 ==> [2023-07-08-18:23:19.069052] Reading config from file /root/spack/etc/spack/defaults/concretizer.yaml
#11 0.591 ==> [2023-07-08-18:23:19.074638] Reading config from file /etc/spack/concretizer.yaml
#11 0.592 ==> [2023-07-08-18:23:19.076011] Reading config from file /root/spack/etc/spack/defaults/repos.yaml
#11 0.816 ==> [2023-07-08-18:23:19.299269] Reading config from file /root/spack/etc/spack/defaults/packages.yaml
#11 0.847 ==> [2023-07-08-18:23:19.330361] Reading config from file /etc/spack/packages.yaml
#11 33.79 ==> [2023-07-08-18:23:52.276560] DATABASE LOCK TIMEOUT: 60s
#11 33.79 ==> [2023-07-08-18:23:52.276691] PACKAGE LOCK TIMEOUT: No timeout
#11 33.79 ==> [2023-07-08-18:23:52.277423] Reading config from file /root/spack/etc/spack/defaults/mirrors.yaml
#11 33.80 ==> [2023-07-08-18:23:52.279406] Checking existence of https://mirror.spack.io/build_cache/index.json
#11 34.15 ==> [2023-07-08-18:23:52.634862] Failure reading URL: HTTP Error 404: Not Found
#11 34.62 ==> [2023-07-08-18:23:53.107677] '/usr/bin/clang-cpp-14' '--version'
#11 34.63 ==> [2023-07-08-18:23:53.108351] '/bin/clang' '--version'
#11 34.63 ==> [2023-07-08-18:23:53.109520] '/usr/bin/clang-cpp-14' '--version'
#11 34.63 ==> [2023-07-08-18:23:53.110028] '/bin/clang' '--version'
#11 34.69 ==> [2023-07-08-18:23:53.173535] '/usr/bin/clang-14' '--version'
#11 34.69 ==> [2023-07-08-18:23:53.174629] '/usr/bin/clang++-14' '--version'
#11 34.69 ==> [2023-07-08-18:23:53.175220] '/usr/bin/clang++-14' '--version'
#11 34.69 ==> [2023-07-08-18:23:53.175560] '/usr/bin/clang-14' '--version'
#11 34.72 ==> [2023-07-08-18:23:53.200876] '/usr/bin/clang++' '--version'
#11 34.72 ==> [2023-07-08-18:23:53.201730] '/usr/bin/clang' '--version'
#11 34.72 ==> [2023-07-08-18:23:53.202476] '/usr/bin/clang' '--version'
#11 34.72 ==> [2023-07-08-18:23:53.203331] '/usr/bin/clang++' '--version'
#11 34.74 ==> [2023-07-08-18:23:53.226791] '/bin/clang++-14' '--version'
#11 34.74 ==> [2023-07-08-18:23:53.227312] '/bin/clang-cpp-14' '--version'
#11 34.75 ==> [2023-07-08-18:23:53.228064] '/bin/clang++-14' '--version'
#11 34.75 ==> [2023-07-08-18:23:53.228249] '/bin/clang-cpp-14' '--version'
#11 34.77 ==> [2023-07-08-18:23:53.254134] '/bin/clang++' '--version'
#11 34.77 ==> [2023-07-08-18:23:53.254902] '/bin/clang-14' '--version'
#11 34.77 ==> [2023-07-08-18:23:53.255483] '/bin/clang-14' '--version'
#11 34.77 ==> [2023-07-08-18:23:53.256174] '/bin/clang++' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.281294] '/usr/bin/gfortran' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.281952] '/bin/gfortran-11' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.284178] '/usr/bin/gfortran' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.285645] '/usr/bin/gfortran-10' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.286000] '/bin/gfortran-10' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.287253] '/usr/bin/gfortran-10' '--version'
#11 34.80 ==> [2023-07-08-18:23:53.288107] '/usr/bin/gfortran-11' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.288489] '/usr/bin/cc' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.288981] '/usr/bin/gfortran-11' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.290723] '/bin/gfortran' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.291912] '/bin/cc' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.293068] '/usr/bin/gcc-11' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.293967] '/bin/gcc' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.294773] '/bin/g++-11' '--version'
#11 34.81 ==> [2023-07-08-18:23:53.295826] '/bin/gcc' '-dumpversion'
#11 34.81 ==> [2023-07-08-18:23:53.296373] '/usr/bin/gcc-11' '-dumpversion'
#11 34.81 ==> [2023-07-08-18:23:53.296818] '/usr/bin/gfortran-11' '-dumpversion'
#11 34.82 ==> [2023-07-08-18:23:53.298654] '/bin/gcc' '-dumpfullversion'
#11 34.82 ==> [2023-07-08-18:23:53.299066] '/bin/g++-11' '-dumpversion'
#11 34.82 ==> [2023-07-08-18:23:53.299522] '/usr/bin/gfortran-11' '-dumpfullversion'
#11 34.82 ==> [2023-07-08-18:23:53.301343] '/usr/bin/gcc-11' '-dumpfullversion'
#11 34.82 ==> [2023-07-08-18:23:53.301746] '/bin/gcc-10' '--version'
#11 34.82 ==> [2023-07-08-18:23:53.302807] '/bin/g++-11' '-dumpfullversion'
#11 34.82 ==> [2023-07-08-18:23:53.303910] '/bin/gfortran' '-dumpversion'
#11 34.82 ==> [2023-07-08-18:23:53.304556] '/usr/bin/gcc' '--version'
#11 34.82 ==> [2023-07-08-18:23:53.306129] '/bin/gcc-10' '-dumpversion'
#11 34.82 ==> [2023-07-08-18:23:53.306755] '/bin/g++-10' '--version'
#11 34.82 ==> [2023-07-08-18:23:53.307154] '/bin/gfortran' '-dumpfullversion'
#11 34.82 ==> [2023-07-08-18:23:53.308632] '/bin/gcc-10' '-dumpfullversion'
#11 34.83 ==> [2023-07-08-18:23:53.309856] '/bin/gfortran-10' '-dumpversion'
#11 34.83 ==> [2023-07-08-18:23:53.310453] '/bin/g++-10' '-dumpversion'
#11 34.83 ==> [2023-07-08-18:23:53.310848] '/usr/bin/gcc' '-dumpversion'
#11 34.83 ==> [2023-07-08-18:23:53.311512] '/usr/bin/g++-11' '--version'
#11 34.83 ==> [2023-07-08-18:23:53.313239] '/bin/gfortran-10' '-dumpfullversion'
#11 34.83 ==> [2023-07-08-18:23:53.313913] '/usr/bin/gcc' '-dumpfullversion'
#11 34.83 ==> [2023-07-08-18:23:53.314291] '/bin/g++-10' '-dumpfullversion'
#11 34.83 ==> [2023-07-08-18:23:53.315708] '/usr/bin/g++-11' '-dumpversion'
#11 34.83 ==> [2023-07-08-18:23:53.316522] '/bin/gfortran-11' '-dumpversion'
#11 34.83 ==> [2023-07-08-18:23:53.317384] '/usr/bin/gcc-10' '--version'
#11 34.83 ==> [2023-07-08-18:23:53.317757] '/usr/bin/g++-11' '-dumpfullversion'
#11 34.83 ==> [2023-07-08-18:23:53.318465] '/bin/g++' '--version'
#11 34.84 ==> [2023-07-08-18:23:53.320354] '/usr/bin/g++-10' '--version'
#11 34.84 ==> [2023-07-08-18:23:53.320916] '/bin/gfortran-11' '-dumpfullversion'
#11 34.84 ==> [2023-07-08-18:23:53.322480] '/usr/bin/g++-10' '-dumpversion'
#11 34.84 ==> [2023-07-08-18:23:53.322891] '/bin/g++' '-dumpversion'
#11 34.84 ==> [2023-07-08-18:23:53.324334] '/usr/bin/gcc-10' '-dumpversion'
#11 34.84 ==> [2023-07-08-18:23:53.324794] '/usr/bin/gfortran' '-dumpversion'
#11 34.84 ==> [2023-07-08-18:23:53.325270] '/usr/bin/g++-10' '-dumpfullversion'
#11 34.84 ==> [2023-07-08-18:23:53.327145] '/bin/g++' '-dumpfullversion'
#11 34.84 ==> [2023-07-08-18:23:53.328071] '/usr/bin/gcc-10' '-dumpfullversion'
#11 34.85 ==> [2023-07-08-18:23:53.328999] '/usr/bin/gfortran' '-dumpfullversion'
#11 34.85 ==> [2023-07-08-18:23:53.330025] '/usr/bin/g++' '--version'
#11 34.85 ==> [2023-07-08-18:23:53.330498] '/usr/bin/gfortran' '-dumpfullversion'
#11 34.85 ==> [2023-07-08-18:23:53.331815] '/bin/gcc-11' '--version'
#11 34.85 ==> [2023-07-08-18:23:53.333067] '/usr/bin/gfortran-10' '-dumpversion'
#11 34.85 ==> [2023-07-08-18:23:53.334396] '/usr/bin/gfortran-10' '-dumpversion'
#11 34.85 ==> [2023-07-08-18:23:53.334996] '/usr/bin/g++' '-dumpversion'
#11 34.85 ==> [2023-07-08-18:23:53.335403] '/usr/bin/gfortran-10' '-dumpfullversion'
#11 34.85 ==> [2023-07-08-18:23:53.337093] '/bin/gcc-11' '-dumpversion'
#11 34.85 ==> [2023-07-08-18:23:53.337900] '/usr/bin/g++' '-dumpfullversion'
#11 34.86 ==> [2023-07-08-18:23:53.339748] '/bin/gcc-11' '-dumpfullversion'
#11 34.86 ==> [2023-07-08-18:23:53.341534] Couldn't get version for compiler /usr/bin/clang-cpp-14
#11 34.86 ==> [2023-07-08-18:23:53.341668] Couldn't get version for compiler /usr/bin/clang-14
#11 34.86 ==> [2023-07-08-18:23:53.341775] Couldn't get version for compiler /usr/bin/clang
#11 34.86 ==> [2023-07-08-18:23:53.342216] Couldn't get version for compiler /bin/clang-cpp-14
#11 34.86 ==> [2023-07-08-18:23:53.342703] Couldn't get version for compiler /bin/clang-14
#11 34.86 ==> [2023-07-08-18:23:53.342929] Couldn't get version for compiler /bin/clang
#11 34.86 ==> [2023-07-08-18:23:53.343013] Couldn't get version for compiler /usr/bin/clang++-14
#11 34.86 ==> [2023-07-08-18:23:53.343064] Couldn't get version for compiler /usr/bin/clang++
#11 34.86 ==> [2023-07-08-18:23:53.343130] Couldn't get version for compiler /bin/clang++-14
#11 34.86 ==> [2023-07-08-18:23:53.343211] Couldn't get version for compiler /bin/clang++
#11 34.86 ==> [2023-07-08-18:23:53.343278] Couldn't get version for compiler /usr/bin/clang-cpp-14
#11 34.86 ==> [2023-07-08-18:23:53.343379] Couldn't get version for compiler /usr/bin/clang-14
#11 34.86 ==> [2023-07-08-18:23:53.343548] Couldn't get version for compiler /usr/bin/clang
#11 34.86 ==> [2023-07-08-18:23:53.343652] Couldn't get version for compiler /bin/clang-cpp-14
#11 34.86 ==> [2023-07-08-18:23:53.343740] Couldn't get version for compiler /bin/clang-14
#11 34.86 ==> [2023-07-08-18:23:53.343934] Couldn't get version for compiler /bin/clang
#11 34.86 ==> [2023-07-08-18:23:53.344225] Couldn't get version for compiler /usr/bin/clang++-14
#11 34.86 ==> [2023-07-08-18:23:53.344454] Couldn't get version for compiler /usr/bin/clang++
#11 34.86 ==> [2023-07-08-18:23:53.344672] Couldn't get version for compiler /bin/clang++-14
#11 34.86 ==> [2023-07-08-18:23:53.344889] Couldn't get version for compiler /bin/clang++
#11 34.86 ==> [2023-07-08-18:23:53.345167] Couldn't get version for compiler /usr/bin/gfortran
#11 34.86 ==> [2023-07-08-18:23:53.345318] Couldn't get version for compiler /usr/bin/gfortran-10
#11 34.86 ==> [2023-07-08-18:23:53.345616] Couldn't get version for compiler /usr/bin/gfortran-11
#11 34.86 ==> [2023-07-08-18:23:53.345833] Couldn't get version for compiler /bin/gfortran
#11 34.86 ==> [2023-07-08-18:23:53.346051] Couldn't get version for compiler /bin/gfortran-10
#11 34.86 ==> [2023-07-08-18:23:53.346272] Couldn't get version for compiler /bin/gfortran-11
#11 34.86 ==> [2023-07-08-18:23:53.346485] Couldn't get version for compiler /usr/bin/gfortran
#11 34.86 ==> [2023-07-08-18:23:53.346699] Couldn't get version for compiler /usr/bin/gfortran-10
#11 34.86 ==> [2023-07-08-18:23:53.346914] Couldn't get version for compiler /usr/bin/gfortran-11
#11 34.86 ==> [2023-07-08-18:23:53.347128] Couldn't get version for compiler /bin/gfortran
#11 34.86 ==> [2023-07-08-18:23:53.347362] Couldn't get version for compiler /bin/gfortran-10
#11 34.86 ==> [2023-07-08-18:23:53.347578] Couldn't get version for compiler /bin/gfortran-11
#11 34.86 ==> [2023-07-08-18:23:53.347791] Couldn't get version for compiler /usr/bin/cc
#11 34.86 ==> [2023-07-08-18:23:53.348000] Couldn't get version for compiler /bin/cc
#11 34.86 ==> [2023-07-08-18:23:53.348228] Couldn't get version for compiler /usr/bin/gfortran
#11 34.86 ==> [2023-07-08-18:23:53.348445] Couldn't get version for compiler /usr/bin/gfortran-10
#11 34.86 ==> [2023-07-08-18:23:53.348663] Couldn't get version for compiler /usr/bin/gfortran-11
#11 34.87 ==> [2023-07-08-18:23:53.348876] Couldn't get version for compiler /bin/gfortran
#11 34.87 ==> [2023-07-08-18:23:53.349118] Couldn't get version for compiler /bin/gfortran-10
#11 34.87 ==> [2023-07-08-18:23:53.349351] Couldn't get version for compiler /bin/gfortran-11
#11 34.87 ==> [2023-07-08-18:23:53.349567] Couldn't get version for compiler /usr/bin/gfortran
#11 34.87 ==> [2023-07-08-18:23:53.349779] Couldn't get version for compiler /usr/bin/gfortran-10
#11 34.87 ==> [2023-07-08-18:23:53.349997] Couldn't get version for compiler /usr/bin/gfortran-11
#11 34.87 ==> [2023-07-08-18:23:53.350212] Couldn't get version for compiler /bin/gfortran
#11 34.87 ==> [2023-07-08-18:23:53.350430] Couldn't get version for compiler /bin/gfortran-10
#11 34.87 ==> [2023-07-08-18:23:53.350673] Couldn't get version for compiler /bin/gfortran-11
#11 43.13 ==> [2023-07-08-18:24:01.612665] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
#11 43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
#11 43.13 ==> [2023-07-08-18:24:01.612812] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
#11 43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
#11 43.13 ==> [2023-07-08-18:24:01.612858] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
#11 43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
#11 43.13 Traceback (most recent call last):
#11 43.13   File "/root/spack/lib/spack/spack/cmd/__init__.py", line 220, in parse_specs
#11 43.13     spec.concretize(tests=tests)  # implies normalize
#11 43.13     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/spec.py", line 2926, in concretize
#11 43.13     self._new_concretize(tests)
#11 43.13   File "/root/spack/lib/spack/spack/spec.py", line 2902, in _new_concretize
#11 43.13     result.raise_if_unsat()
#11 43.13   File "/root/spack/lib/spack/spack/solver/asp.py", line 481, in raise_if_unsat
#11 43.13     raise InternalConcretizerError(constraints, conflicts=conflicts)
#11 43.13 spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
#11 43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
#11 43.13 
#11 43.13 The above exception was the direct cause of the following exception:
#11 43.13 
#11 43.13 Traceback (most recent call last):
#11 43.13   File "/root/spack/lib/spack/spack/main.py", line 1018, in main
#11 43.13     return _main(argv)
#11 43.13            ^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/main.py", line 973, in _main
#11 43.13     return finish_parse_and_run(parser, cmd_name, env_format_error)
#11 43.13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
#11 43.13     return _invoke_command(command, parser, args, unknown)
#11 43.13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/main.py", line 650, in _invoke_command
#11 43.13     return_val = command(parser, args)
#11 43.13                  ^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/cmd/install.py", line 368, in install
#11 43.13     install_without_active_env(args, install_kwargs, reporter_factory)
#11 43.13   File "/root/spack/lib/spack/spack/cmd/install.py", line 481, in install_without_active_env
#11 43.13     concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
#11 43.13                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/cmd/install.py", line 448, in concrete_specs_from_cli
#11 43.13     concrete_specs = spack.cmd.parse_specs(
#11 43.13                      ^^^^^^^^^^^^^^^^^^^^^^
#11 43.13   File "/root/spack/lib/spack/spack/cmd/__init__.py", line 234, in parse_specs
#11 43.13     raise spack.error.SpackError(msg) from e
#11 43.13 spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
#11 43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
#11 ERROR: process "/bin/sh -c bash -c \"spack -d install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric\"" did not complete successfully: exit code: 1
------
 > [8/8] RUN bash -c "spack -d install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric":
43.13   File "/root/spack/lib/spack/spack/cmd/install.py", line 481, in install_without_active_env
43.13     concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
43.13                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
43.13   File "/root/spack/lib/spack/spack/cmd/install.py", line 448, in concrete_specs_from_cli
43.13     concrete_specs = spack.cmd.parse_specs(
43.13                      ^^^^^^^^^^^^^^^^^^^^^^
43.13   File "/root/spack/lib/spack/spack/cmd/__init__.py", line 234, in parse_specs
43.13     raise spack.error.SpackError(msg) from e
43.13 spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
43.13     wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric is unsatisfiable, errors are:
------
Dockerfile:17
--------------------
  15 |     RUN bash -c "which spack"
  16 |     RUN bash -c "spack debug report"
  17 | >>> RUN bash -c "spack -d install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric"
  18 |     
  19 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c bash -c \"spack -d install -j $(nproc) wrf@4.3.3%intel build_type=dm+sm ^intel-oneapi-mpi+external-libfabric\"" did not complete successfully: exit code: 1
```

</details>

### Information on your system

* **Spack:** 0.20.1 (e8658d6493887ef702dd38f0e9ee5870a1651c1e)
* **Python:** 3.11.2
* **Platform:** linux-ubuntu22.04-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
There is no `intel` compiler installed in the `tutorial` image:
![Screenshot from 2023-07-10 10-54-15](https://github.com/spack/spack/assets/4199709/f10d6420-f503-43ee-b17d-574a613483f3)

Therefore when you ask to install a spec with `%intel` (a non-existing compiler) the concretizer errors out, since the problem is "unsolvable". 

I'm tagging this as low-priority, since we can do better with the error message, but please note that:
- The `tutorial` image is not meant for production
- You need to `spack compiler find` a compiler before you can use it in specs
