### ISSUE TITLE
Spack freezes on specific typo in recipe

### ISSUE THREAD

**Issue by Jordan474** [LLNL/spack#39016]
### Steps to reproduce

For example, with this specific mistake in a recipe:

```console
$ spack edit lsof
# CHANGE
    def install(self, spec, prefix):
# TO
    def install(self, invalid):

$ spack install lsof
==> Installing lsof-4.91-g34ogep5avzxz4vio7vwfvcexoct3pfo [1/1]
==> No binary for lsof-4.91-g34ogep5avzxz4vio7vwfvcexoct3pfo found: installing from source
==> Using cached archive: /.../spack/var/spack/cache/_source-cache/archive/3c/3ca57887470fdf223a8e8aae4559cd3a26787bea93b94336c90ee8062e29e352.tar.gz
==> No patches needed for lsof
==> lsof: Executing phase: 'install'
Process Process-1:
Traceback (most recent call last):
  File "/.../spack/lib/spack/spack/build_environment.py", line 1050, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/.../spack/lib/spack/spack/installer.py", line 2510, in build_process
    return installer.run()
  File "/.../spack/lib/spack/spack/installer.py", line 2375, in run
    self._real_install()
  File "/.../spack/lib/spack/spack/installer.py", line 2470, in _real_install
    phase_fn.execute()
  File "/.../spack/lib/spack/spack/builder.py", line 433, in execute
    self.phase_fn(pkg, pkg.spec, pkg.prefix)
  File "/.../spack/lib/spack/spack/builder.py", line 309, in _adapter
    return phase_fn(spec, prefix)
TypeError: Lsof.install() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.10-ahhxrmd6fzjqjcvnf3ct5inkowfamkyg/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/.../spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.10-ahhxrmd6fzjqjcvnf3ct5inkowfamkyg/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/.../spack/lib/spack/spack/build_environment.py", line 1067, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/.../spack/lib/spack/spack/build_environment.py", line 1278, in get_package_context
    if isinstance(obj, CONTEXT_BASES) and typename not in basenames:
UnboundLocalError: local variable 'typename' referenced before assignment

... freeze ...
```

### Error message

Spack does print the error but the command freezes instead of exit with a failure.

**Note:** This actually **revealed 2 issues**:

1. A bug in boiler plate code of child process error handling code (typename UnboundLocalError)

2. A bug in child process unexpected exit handling (the freeze/infinite wait)

### Information on your system

* **Spack:** 0.21.0.dev0 (ae08b25dacd56b287d8c80ad648b998cfa2ec8cb)
* **Python:** 3.10.10
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed in:

* **Spack:** 0.21.0.dev0 (f9457fa80ba51d14610df8b57a6b5a514d6bb6ff)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

Thanks for the clear reproducer!
