### ISSUE TITLE
spack remove fails in very simple case

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#39387]
### Steps to reproduce

Using
* spack@develop (9438cac219cc7ff127e03bc8a09dcb5d67124bb7 from `Thu Aug 10 22:58:05 2023 +0200`)

**Update:** `git bisect` says this stopped working @ 3c3a4c75776ece43c95df46908dea026ac2a9276 (CC @alalazo)

spack.yaml
```
spack:
  view: false

  concretizer:
    reuse: false
    unify: false

  compilers:
  - compiler:
      spec: gcc@=11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  specs:
  - zlib
  - bricks ~cuda
```

**spack remove** fails to remove `bricks ~cuda`
```
$> spack -e . concretize -f
$> spack -e . remove bricks~cuda
==> Error: cannot remove bricks~cuda from /e4s-ci-command/tmp/spack.yaml, no such spec exists
```

### Error message

```
$> spack -d --stacktrace -e . remove bricks~cuda
...
lib/spack/spack/main.py:1026 ==> [2023-08-10-20:55:38.738885] SpackEnvironmentError: cannot remove bricks~cuda from /e4s-ci-command/tmp/spack.yaml, no such spec exists
lib/spack/spack/error.py:52 ==> [2023-08-10-20:55:38.739118] Error: cannot remove bricks~cuda from /e4s-ci-command/tmp/spack.yaml, no such spec exists
Traceback (most recent call last):
  File "/spack/lib/spack/spack/environment/environment.py", line 2704, in remove_user_spec
    self.pristine_configuration["specs"].remove(user_spec)
  File "/usr/lib/python3.8/_collections_abc.py", line 997, in remove
    del self[self.index(value)]
  File "/usr/lib/python3.8/_collections_abc.py", line 911, in index
    raise ValueError
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/remove.py", line 41, in remove
    env.remove(spec, args.list_name, force=args.force)
  File "/spack/lib/spack/spack/environment/environment.py", line 1217, in remove
    self.manifest.remove_user_spec(str(spec))
  File "/spack/lib/spack/spack/environment/environment.py", line 2710, in remove_user_spec
    raise SpackEnvironmentError(msg) from e
spack.environment.environment.SpackEnvironmentError: cannot remove bricks~cuda from /e4s-ci-command/tmp/spack.yaml, no such spec exists
```

@becker33 

### Information on your system

* **Spack:** 0.21.0.dev0 (9438cac219cc7ff127e03bc8a09dcb5d67124bb7)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed as of:

* **Spack:** 0.21.0.dev0 (ee6ae402aa46b6742e9f4f2041e232caa3af5a8f)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

As a note, this is due to some normalization of the spec string and removal based on string match. It won't happen when using `spack add` instead of manual editing.

**Comment by haampie** [comment]
makes sense to just use satisfies, so you can write `spack remove bricks`

**Comment by alalazo** [comment]
Not sure about that:
```yaml
spack:
  specs:
  - bricks+foo
  - bricks
  - bricks~bar
```
Right now with exact match semantic we can remove the middle one without touching the other two.

**Comment by eugeneswalker** [comment]
If we have an environment written in a more readable, non-normalized format:
```
...
  specs:
  - zlib
  - bricks ~cuda
```

Can Spack write this back out in normalized format? Do you know the call for this?
