### ISSUE TITLE
Installation issue: anything that depends on openssl on rhel7 build hosts, defaults to openssl 1.1.1

### ISSUE THREAD

**Issue by perrymil** [LLNL/spack#39448]
### Steps to reproduce the issue

```console
$ git pull
$ spack install libssh2
...
```

### Error message

<details><summary>Error message</summary>
==> Installing libssh2-1.11.0-pkqgxn2i4zfcvhztjngomcegji67fdsc [46/162]
==> No binary for libssh2-1.11.0-pkqgxn2i4zfcvhztjngomcegji67fdsc found: installing from source
Process Process-1:
Traceback (most recent call last):
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 1048, in _setup_pkg_and_run
    pkg, dirty=kwargs.get("dirty", False), context=context
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 779, in setup_package
    set_wrapper_variables(pkg, env_mods)
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 522, in set_wrapper_variables
    update_compiler_args_for_dep(dspec)
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 494, in update_compiler_args_for_dep
    dep_link_dirs.extend(query.libs.directories)
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/spec.py", line 1237, in __get__
    value = f()
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/spec.py", line 1226, in <lambda>
    callbacks_chain.append(lambda: getattr(pkg, self.attribute_name))
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/var/spack/repos/builtin/packages/openssl/package.py", line 392, in libs
    )
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/llnl/util/lang.py", line 486, in __getitem__
    return self.dict[key]
KeyError: 'shared'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 1067, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/spack/build_environment.py", line 1256, in get_package_context
    func = getattr(obj, tb.tb_frame.f_code.co_name, "")
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/var/spack/repos/builtin/packages/openssl/package.py", line 392, in libs
    )
  File "/home/exacloud/gscratch/ACC/spackTestLandia/spack/lib/spack/llnl/util/lang.py", line 486, in __getitem__
    return self.dict[key]
KeyError: 'shared'
<pre>
...
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### Additional information

I think its failing before getting to the build log?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by perrymil** [comment]
This is consistent with a new spack repo using the development branch. It works on a rhel9 host, but not on rhel7 hosts.

**Comment by perrymil** [comment]
For some reason its pulling in openssl 1.1.1 instead of 3.2.1 as a dependency.

This is a consistent problem on centos7/rhel7 hosts

If I manually specify openssl@3.2.1 as a dependency of libssh2, i.e. spack install libssh2 ^openssl@3.2.1 it works, but by default it tries to use 1.1.1
