### ISSUE TITLE
pymol: Not able to install PyMOL due to circular dependency

### ISSUE THREAD

**Issue by w8jcik** [LLNL/spack#39530]
### Steps to reproduce

```console
spack spec --fresh py-pymol@2.5.0
```

Tested branches `v0.20.1` and `develop-2023-07-30`.

I assume that it is some kind of regression, since this package must have been working before.

It might be of course due to change in package definitions.

### Error message

```console
==> Error: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)
```

`spack -d spec --fresh py-pymol@2.5.0`
```console
==> [2023-08-19-15:07:40.196864] Imported spec from built-in commands
==> [2023-08-19-15:07:40.197497] Imported spec from built-in commands
==> [2023-08-19-15:07:40.198718] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/config.yaml
==> [2023-08-19-15:07:40.223955] DATABASE LOCK TIMEOUT: 60s
==> [2023-08-19-15:07:40.224001] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-19-15:07:40.226396] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/bootstrap.yaml
==> [2023-08-19-15:07:40.236505] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/repos.yaml
==> [2023-08-19-15:07:40.239521] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-08-19-15:07:40.239846] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/bootstrap.yaml
==> [2023-08-19-15:07:40.247214] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/data/users/w8jcik/thesis/.spack/etc/spack/defaults
==> [2023-08-19-15:07:40.247261] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/data/users/w8jcik/thesis/.spack/etc/spack/defaults/linux
==> [2023-08-19-15:07:40.247296] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/users/w8jcik/.spack/bootstrap/config
==> [2023-08-19-15:07:40.247324] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/users/w8jcik/.spack/bootstrap/config/linux
==> [2023-08-19-15:07:40.248173] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/config.yaml
==> [2023-08-19-15:07:40.270503] Reading config from file /home/users/w8jcik/.spack/bootstrap/config/linux/config.yaml
==> [2023-08-19-15:07:40.282906] DATABASE LOCK TIMEOUT: 60s
==> [2023-08-19-15:07:40.282953] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-19-15:07:40.283091] Reading config from file /home/users/w8jcik/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-08-19-15:07:40.342482] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-08-19-15:07:40.343138] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/bootstrap.yaml
==> [2023-08-19-15:07:40.355995] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-08-19-15:07:40.496336] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/modules.yaml
==> [2023-08-19-15:07:40.508406] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/linux/modules.yaml
==> [2023-08-19-15:07:40.782404] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/packages.yaml
==> [2023-08-19-15:07:40.817749] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-08-19-15:07:40.820698] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-08-19-15:07:40.820747] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-08-19-15:07:40.856265] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9/gqcctd2ejbgvyvyt4umqpetfoogfycwu" provides the "clingo" Python module
==> [2023-08-19-15:07:40.856603] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/concretizer.yaml
==> [2023-08-19-15:07:40.863866] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/repos.yaml
==> [2023-08-19-15:07:40.945846] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/packages.yaml
==> [2023-08-19-15:07:42.904587] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/linux/compilers.yaml
==> [2023-08-19-15:07:42.927257] Reading config from file /data/users/w8jcik/thesis/.spack/etc/spack/defaults/config.yaml
==> [2023-08-19-15:07:58.575765] SpackError: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)
==> [2023-08-19-15:07:58.575898] Error: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)
Traceback (most recent call last):
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/spec.py", line 2999, in concretize
    self._new_concretize(tests)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/spec.py", line 2974, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/solver/asp.py", line 2780, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/solver/asp.py", line 815, in solve
    error_handler.raise_if_errors()
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/solver/asp.py", line 649, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/cmd/spec.py", line 108, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/data/users/w8jcik/thesis/.spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)
```

### Information on your system

Ubuntu 22.04 LTS.

`spack debug report`
* **Spack:** 0.21.0.dev0 (ad0b70a64a4f84825df9bd231f94b1b4e9ec1ffe)
* **Python:** 3.9.2
* **Platform:** linux-archrolling-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Changed the labels, since this is not an error with core Spack, but rather an issue with the recipe.

**Comment by w8jcik** [comment]
The issue in the core Spack is that the resulting error message is not readable.  
Error says that the cycle is between 25 pairs of packages.

**Comment by alalazo** [comment]
Improving error messages is tracked in other issues, #40173 should hopefully improve this too
