### ISSUE TITLE
User config is problematic when moving across multiple major versions at once

### ISSUE THREAD

**Issue by xiaor2** [LLNL/spack#39592]
### Steps to reproduce

```console
$ git clone -c feature.manyFiles=true https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh
$ module load gcc/11.2.0
$ spack install hdf5%gcc@11.2.0 target=x86_64 +cxx+fortran+hl+pic+shared+threadsafe
```

### Error message

![image](https://github.com/spack/spack/assets/80271418/9e53978a-8fcc-4c17-acf1-2c5ff1594b09)

### Information on your system

![image](https://github.com/spack/spack/assets/80271418/ff009570-557b-4f5c-898b-8b1909bf9204)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by xiaor2** [comment]
I tried to use the updates command, and it told me no thing to update.

**Comment by alalazo** [comment]
@michaelkuhn Can you look at this? We might need to write a few lines in `spack/schema/config.py::update`

**Comment by alalazo** [comment]
Also, not clear to me when `config` should be written to disk during an install. @xiaor2 Can you post your config.yaml and maybe also the output of:
```
$ spack config blame config
```
?

**Comment by michaelkuhn** [comment]
I think I have already seen this on Slack but could not figure out what causes it. Is there any way to reproduce this? If I add `terminal_title` to my config, I just get the warning, not the error.

**Comment by xiaor2** [comment]
Sure. @alalazo Would this help to figure out what causes it? @michaelkuhn 
![image](https://github.com/spack/spack/assets/80271418/fab4cfad-f58e-4447-a8dd-2d233576e137)

**Comment by alalazo** [comment]
@xiaor2 I don't see `config:terminal_title` in your configuration :thinking:

**Comment by alalazo** [comment]
Can you show a stacktrace? Like:
```console
$ spack -d install zlib
```

**Comment by xiaor2** [comment]
Sure. @alalazo 
```
[xiaor2@cc-login2 ~]$ export SPACK_ROOT=/projects/ctessum/xiaor2/software_installs/spack
[xiaor2@cc-login2 ~]$ source ${SPACK_ROOT}/share/spack/setup-env.sh
[xiaor2@cc-login2 ~]$ spack -d install zlib
==> [2023-08-26-12:09:55.381475] Imported install from built-in commands
==> [2023-08-26-12:09:55.384234] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/config.yaml
==> [2023-08-26-12:09:55.439721] Imported install from built-in commands
==> [2023-08-26-12:09:55.588897] DATABASE LOCK TIMEOUT: 60s
==> [2023-08-26-12:09:55.589119] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-26-12:09:55.594012] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-08-26-12:09:55.630976] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/repos.yaml
==> [2023-08-26-12:09:55.656008] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-08-26-12:09:55.656891] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-08-26-12:09:55.677374] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults
==> [2023-08-26-12:09:55.677479] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/linux
==> [2023-08-26-12:09:55.677584] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/xiaor2/.spack/bootstrap/config
==> [2023-08-26-12:09:55.677652] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/xiaor2/.spack/bootstrap/config/linux
==> [2023-08-26-12:09:55.679847] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/config.yaml
==> [2023-08-26-12:09:55.732234] Reading config from file /home/xiaor2/.spack/bootstrap/config/linux/config.yaml
==> [2023-08-26-12:09:55.747651] Warning: config:terminal_title has been replaced by install_status and is ignored
==> [2023-08-26-12:09:55.750331] DATABASE LOCK TIMEOUT: 3s
==> [2023-08-26-12:09:55.750491] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-26-12:09:55.752946] Reading config from file /home/xiaor2/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-08-26-12:09:55.833265] Reading config from file /projects/ctessum/xiaor2/software_installs/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/projects/ctessum/xiaor2/software_installs/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/cmd/install.py", line 358, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/cmd/install.py", line 471, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/cmd/install.py", line 439, in concrete_specs_from_cli
    args.spec, concretize=True, tests=install_kwargs["tests"]
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/spec.py", line 2993, in concretize
    self._new_concretize(tests)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/spec.py", line 2964, in _new_concretize
    solver = spack.solver.asp.Solver()
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/solver/asp.py", line 2875, in __init__
    self.driver = PyclingoDriver()
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/solver/asp.py", line 700, in __init__
    bootstrap_clingo()
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/solver/asp.py", line 578, in bootstrap_clingo
    with spack.bootstrap.ensure_bootstrap_configuration():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/bootstrap/config.py", line 105, in ensure_bootstrap_configuration
    with _ensure_bootstrap_configuration():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/bootstrap/config.py", line 170, in _ensure_bootstrap_configuration
    spack.config.set("config", user_configuration["config"])
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/config.py", line 915, in set
    return CONFIG.set(path, value, scope)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/config.py", line 382, in _method
    return method(self, *args, **kwargs)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/config.py", line 653, in set
    self.update_config(path, value, scope=scope)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/config.py", line 382, in _method
    return method(self, *args, **kwargs)
  File "/projects/ctessum/xiaor2/software_installs/spack/lib/spack/spack/config.py", line 531, in update_config
    raise RuntimeError(msg)
RuntimeError: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

        spack config [--scope=<scope>] update config

Note that previous versions of Spack will not be able to use the updated configuration.
```

**Comment by getianao** [comment]
I encountered the same issue when attempting to install a new version of Spack while preserving the existing one. Deleting the old user-scope configuration files located at` ~/.spack/` resolved this problem.

**Comment by kishoryd** [comment]
how to delete user scope at this directory? can someone confirm the issue has resolved or not. I'm also facing the same issue as well.

**Comment by kishoryd** [comment]
please find the output:
> spack config blame config
---                                                  config:
/home/apps/spack/etc/spack/defaults/config.yaml:19     install_tree:
/home/apps/spack/etc/spack/defaults/config.yaml:20       root: $spack/opt/spack
/home/apps/spack/etc/spack/defaults/config.yaml:21       projections:
/home/apps/spack/etc/spack/defaults/config.yaml:22         all: '{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
/home/apps/spack/etc/spack/defaults/config.yaml:33     template_dirs:
/home/apps/spack/etc/spack/defaults/config.yaml:34     - $spack/share/spack/templates
/home/apps/spack/etc/spack/defaults/config.yaml:37     license_dir: $spack/etc/spack/licenses
/home/apps/spack/etc/spack/defaults/config.yaml:69     build_stage:
/home/apps/spack/etc/spack/defaults/config.yaml:70     - $tempdir/$user/spack-stage
/home/apps/spack/etc/spack/defaults/config.yaml:71     - $user_cache_path/stage
/home/apps/spack/etc/spack/defaults/config.yaml:77     test_stage: $user_cache_path/test
/home/apps/spack/etc/spack/defaults/config.yaml:81     source_cache: $spack/var/spack/cache
/home/apps/spack/etc/spack/defaults/config.yaml:90     misc_cache: $user_cache_path/cache
/home/apps/spack/etc/spack/defaults/config.yaml:96     connect_timeout: 10
/home/apps/spack/etc/spack/defaults/config.yaml:101    verify_ssl: True
/home/apps/spack/etc/spack/defaults/config.yaml:109    suppress_gpg_warnings: False
/home/apps/spack/etc/spack/defaults/config.yaml:115    install_missing_compilers: False
/home/apps/spack/etc/spack/defaults/config.yaml:120    checksum: True
/home/apps/spack/etc/spack/defaults/config.yaml:125    deprecated: False
/home/apps/spack/etc/spack/defaults/config.yaml:130    dirty: False
/home/apps/spack/etc/spack/defaults/config.yaml:138    build_language: C
/home/apps/spack/etc/spack/defaults/config.yaml:147    locks: True
/home/apps/spack/etc/spack/defaults/config.yaml:152    url_fetch_method: urllib
/home/apps/spack/etc/spack/defaults/config.yaml:165    ccache: False
/home/apps/spack/etc/spack/defaults/config.yaml:181    concretizer: clingo
/home/apps/spack/etc/spack/defaults/config.yaml:188    db_lock_timeout: 60
/home/apps/spack/etc/spack/defaults/config.yaml:196    package_lock_timeout: null
/home/apps/spack/etc/spack/defaults/config.yaml:201    shared_linking:
/home/apps/spack/etc/spack/defaults/config.yaml:206      type: rpath
/home/apps/spack/etc/spack/defaults/config.yaml:212      bind: False
/home/apps/spack/etc/spack/defaults/config.yaml:217    allow_sgid: True
/home/apps/spack/etc/spack/defaults/config.yaml:223    install_status: True
/home/apps/spack/etc/spack/defaults/config.yaml:227    binary_index_ttl: 600
/home/apps/spack/etc/spack/defaults/config.yaml:229    flags:
/home/apps/spack/etc/spack/defaults/config.yaml:231      keep_werror: none
_builtin                                               debug: False
_builtin                                               build_jobs: 16

**Comment by alalazo** [comment]
I still can't reproduce. Can anybody post a reproducer e.g. in a docker environment?

**Comment by tobbez** [comment]
Encountered this problem, and managed to work around it by removing `~/.spack/bootstrap/` (which was then recreated by the next spack invocation).

Here are the contents of `~/.spack/bootstrap/config/` (from before applying the workaround) in case that helps: [spack_bootstrap_config.tar.gz](https://github.com/spack/spack/files/12910581/spack_bootstrap_config.tar.gz).

**Comment by HuangLianghong** [comment]
> I still can't reproduce. Can anybody post a reproducer e.g. in a docker environment?

This issue happens when I `git clone` a new version of spack (not sure whether `git pull` in the old repository will trigger this issue) and try to install any software. I solve the issue by deleting `~/.spack/`.

**Comment by alalazo** [comment]
@HuangLianghong Ok, that makes sense if you are updating from an old version of Spack. Is this the case? Which version of Spack are you currently using?

**Comment by HuangLianghong** [comment]
@alalazo Yes, I first delete the old spack folder and then clone a new spack repository. Now I am using `0.22.0.dev0 (b1ab01280af1ec3065594b739dc2bde3f2107510)`.

**Comment by alalazo** [comment]
Can you also post what was the previous version?

**Comment by HuangLianghong** [comment]
@alalazo Sry, I have already deleted the previous version, and I can't remember it. But its highest supported CUDA safe version is 11.7.0.

**Comment by mark14wu** [comment]
> I encountered the same issue when attempting to install a new version of Spack while preserving the existing one. Deleting the old user-scope configuration files located at` ~/.spack/` resolved this problem.

Encountered exactly the same issue on a campus cluster having an older version of spack. `spack config update config` did nothing to the old config files, thus I have to delete `~/.spack/` by hand.

FYI: the older spack version is 0.17.1, and the newer version is 0.22.0

**Comment by alalazo** [comment]
@mark14wu That wouldn't surprise me. We use update functions to move from `0.X` to `0.X+1`, in case there is a breaking change. Usually we remove the update after `0.X+2` so doing a `0.X+5` transition all at once, while keeping configuration, might be breaking (v0.17 was deprecated a couple years ago, more or less).

**Comment by mark14wu** [comment]
I see. Thank you for your explanation!

> @mark14wu That wouldn't surprise me. We use update functions to move from `0.X` to `0.X+1`, in case there is a breaking change. Usually we remove the update after `0.X+2` so doing a `0.X+5` transition all at once, while keeping configuration, might be breaking (v0.17 was deprecated a couple years ago, more or less).
