### ISSUE TITLE
Concretizer internal error when running spack spec intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0

### ISSUE THREAD

**Issue by danielahlin** [LLNL/spack#39698]
### Steps to reproduce

```console
# Start with fresh develop branch
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
# Init spack
source spack/share/spack/setup-env.sh
# Try to spec intel-oneapi-mpi built with oneapi 
spack -d spec intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0
```

### Error message

Without debug:
```console
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0 is unsatisfiable, errors are:
```

With debug:
```console
==> [2023-08-30-13:07:58.483839] Imported spec from built-in commands
==> [2023-08-30-13:07:58.484514] Imported spec from built-in commands
==> [2023-08-30-13:07:58.485708] Reading config from file /home/someuser/spack/etc/spack/defaults/config.yaml                                      
==> [2023-08-30-13:07:58.514935] DATABASE LOCK TIMEOUT: 60s
==> [2023-08-30-13:07:58.515042] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-30-13:07:58.519775] Reading config from file /home/someuser/spack/etc/spack/defaults/bootstrap.yaml                                   
==> [2023-08-30-13:07:58.533664] Reading config from file /home/someuser/spack/etc/spack/defaults/repos.yaml                                       
==> [2023-08-30-13:07:58.538054] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-08-30-13:07:58.538537] Reading config from file /home/someuser/spack/etc/spack/defaults/bootstrap.yaml                                   
==> [2023-08-30-13:07:58.547448] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/someuser/spack/etc/spack/defaults                              
==> [2023-08-30-13:07:58.547501] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/someuser/spack/etc/spack/defaults/linux                  
==> [2023-08-30-13:07:58.547526] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/someuser/.spack/bootstrap/config                              
==> [2023-08-30-13:07:58.547544] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/someuser/.spack/bootstrap/config/linux                  
==> [2023-08-30-13:07:58.548724] Reading config from file /home/someuser/spack/etc/spack/defaults/config.yaml                                      
==> [2023-08-30-13:07:58.574923] Reading config from file /home/someuser/.spack/bootstrap/config/linux/config.yaml                                 
==> [2023-08-30-13:07:58.588989] DATABASE LOCK TIMEOUT: 60s
==> [2023-08-30-13:07:58.589096] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-08-30-13:07:58.589388] Reading config from file /home/someuser/.spack/bootstrap/config/linux/compilers.yaml                              
==> [2023-08-30-13:07:58.625561] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64                                                         
==> [2023-08-30-13:07:58.626038] Reading config from file /home/someuser/spack/etc/spack/defaults/bootstrap.yaml                                   
==> [2023-08-30-13:07:58.641769] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'             
==> [2023-08-30-13:07:58.761320] Reading config from file /home/someuser/spack/etc/spack/defaults/modules.yaml                                     
==> [2023-08-30-13:07:58.777810] Reading config from file /home/someuser/spack/etc/spack/defaults/linux/modules.yaml                               
==> [2023-08-30-13:07:58.868357] Reading config from file /home/someuser/spack/etc/spack/defaults/packages.yaml                                    
==> [2023-08-30-13:07:58.916986] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64                                                               
==> [2023-08-30-13:07:58.921859] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64                                            
==> [2023-08-30-13:07:58.921962] [BOOTSTRAP MODULE clingo] Try importing from Python                                                               
==> [2023-08-30-13:07:58.952296] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/prqkzynv2nwko5mktitebgkeumuxkveu" provides the "clingo" Python module
==> [2023-08-30-13:07:58.952966] Reading config from file /home/someuser/spack/etc/spack/defaults/concretizer.yaml                                 
==> [2023-08-30-13:07:58.963006] Reading config from file /home/someuser/spack/etc/spack/defaults/repos.yaml                                       
==> [2023-08-30-13:07:59.026593] Reading config from file /home/someuser/spack/etc/spack/defaults/packages.yaml                                    
==> [2023-08-30-13:07:59.070093] Reading config from file /home/someuser/spack/etc/spack/defaults/config.yaml                                      
==> [2023-08-30-13:07:59.097859] Reading config from file /home/someuser/spack/etc/spack/defaults/mirrors.yaml                                     
==> [2023-08-30-13:08:01.075283] Reading config from file /home/someuser/.spack/linux/compilers.yaml                                               
==> [2023-08-30-13:08:11.315491] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0 is unsatisfiable, errors are:                                                                       
==> [2023-08-30-13:08:11.320547] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0 is unsatisfiable, errors are:                                                                       
Traceback (most recent call last):
  File "/home/someuser/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs                                                            
    spec.concretize(tests=tests)  # implies normalize
  File "/home/someuser/spack/lib/spack/spack/spec.py", line 2992, in concretize                                                                    
    self._new_concretize(tests)
  File "/home/someuser/spack/lib/spack/spack/spec.py", line 2965, in _new_concretize                                                               
    result.raise_if_unsat()
  File "/home/someuser/spack/lib/spack/spack/solver/asp.py", line 494, in raise_if_unsat                                                           
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0 is unsatisfiable, errors are:                                                                       

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/someuser/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/home/someuser/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/someuser/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run                                                          
    return _invoke_command(command, parser, args, unknown)
  File "/home/someuser/spack/lib/spack/spack/main.py", line 647, in _invoke_command                                                                
    return_val = command(parser, args)
  File "/home/someuser/spack/lib/spack/spack/cmd/spec.py", line 101, in spec                                                                       
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)                                                                         
  File "/home/someuser/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs                                                            
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    intel-oneapi-mpi@2021.10.0%oneapi@2023.2.0 is unsatisfiable, errors are:
```

### Information on your system

* **Spack:** 0.21.0.dev0 (78fe2c63fa84478d294ecbd7ba5d694fa4bcd09c)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by danielahlin** [comment]
I forgot to explicitly add that oneapi@2023.2.0 has not been installed and configured in the spack deployment above. So no compiler of that name exists. Still - an internal error is not the best thing here.
