### ISSUE TITLE
error in spack extensions

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#398]
bash-4.1$ spack extensions python@3.5.1
Traceback (most recent call last):
  File "/g/g0/lee218/src/pkg/spack/bin/spack", line 176, in <module>
    main()
  File "/g/g0/lee218/src/pkg/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/nfs/tmp2/lee218/pkg/spack/lib/spack/spack/cmd/extensions.py", line 77, in extensions
    extensions = spack.repo.extensions_for(spec)
AttributeError: 'RepoPath' object has no attribute 'extensions_for'

**Comment by tgamblin** [comment]
Fixed by #399
