### ISSUE TITLE
Concretizer internal error when running spack spec mpi%gcc or another virtual package

### ISSUE THREAD

**Issue by obressand-cea** [LLNL/spack#40099]
### Steps to reproduce

# Start with fresh develop branch
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
# Init spack
source spack/share/spack/setup-env.sh
# Try to spec mpi%gcc
spack -d spec mpi%gcc

### Error message

==> [2023-09-20-14:31:07.893713] Imported spec from built-in commands
==> [2023-09-20-14:31:07.894093] Imported spec from built-in commands
==> [2023-09-20-14:31:07.894605] Reading config from file /tmp/my/spack/etc/spack/defaults/config.yaml
==> [2023-09-20-14:31:07.905555] DATABASE LOCK TIMEOUT: 60s
==> [2023-09-20-14:31:07.905616] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-09-20-14:31:07.911361] Reading config from file /tmp/my/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-20-14:31:07.915638] Reading config from file /tmp/my/spack/etc/spack/defaults/repos.yaml
==> [2023-09-20-14:31:07.916695] Reading config from file /home/bressand/.spack/repos.yaml
==> [2023-09-20-14:31:07.917878] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-09-20-14:31:07.918072] Reading config from file /tmp/my/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-20-14:31:07.921579] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/tmp/my/spack/etc/spack/defaults
==> [2023-09-20-14:31:07.921604] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/tmp/my/spack/etc/spack/defaults/linux
==> [2023-09-20-14:31:07.921617] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/bressand/.spack/bootstrap/config
==> [2023-09-20-14:31:07.921627] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/bressand/.spack/bootstrap/config/linux
==> [2023-09-20-14:31:07.922074] Reading config from file /tmp/my/spack/etc/spack/defaults/config.yaml
==> [2023-09-20-14:31:07.931991] Reading config from file /home/bressand/.spack/bootstrap/config/linux/config.yaml
==> [2023-09-20-14:31:07.937101] DATABASE LOCK TIMEOUT: 60s
==> [2023-09-20-14:31:07.937136] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-09-20-14:31:07.937254] Reading config from file /home/bressand/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-09-20-14:31:07.957824] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-09-20-14:31:07.958042] Reading config from file /tmp/my/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-20-14:31:07.964127] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-09-20-14:31:08.036615] Reading config from file /tmp/my/spack/etc/spack/defaults/packages.yaml
==> [2023-09-20-14:31:23.949326] Reading config from file /tmp/my/spack/etc/spack/defaults/modules.yaml
==> [2023-09-20-14:31:23.955617] Reading config from file /tmp/my/spack/etc/spack/defaults/linux/modules.yaml
==> [2023-09-20-14:31:23.958840] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-09-20-14:31:23.959435] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-09-20-14:31:23.959458] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-09-20-14:31:23.965296] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10/idkenmhnscjlu5gjqhpcqa4h7o2a7aow" provides the "clingo" Python module
==> [2023-09-20-14:31:23.965535] Reading config from file /tmp/my/spack/etc/spack/defaults/concretizer.yaml
==> [2023-09-20-14:31:23.969931] Reading config from file /tmp/my/spack/etc/spack/defaults/repos.yaml
==> [2023-09-20-14:31:23.970908] Reading config from file /home/bressand/.spack/repos.yaml
==> [2023-09-20-14:31:23.993311] Reading config from file /tmp/my/spack/etc/spack/defaults/config.yaml
==> [2023-09-20-14:31:24.003443] Reading config from file /tmp/my/spack/etc/spack/defaults/mirrors.yaml
==> [2023-09-20-14:31:24.005754] Reading config from file /tmp/my/spack/etc/spack/defaults/packages.yaml
==> [2023-09-20-14:31:24.063465] Reading config from file /home/bressand/.spack/linux/compilers.yaml
==> [2023-09-20-14:31:28.191716] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    mpi%gcc is unsatisfiable, errors are:
==> [2023-09-20-14:31:28.193752] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    mpi%gcc is unsatisfiable, errors are:
Traceback (most recent call last):
  File "/tmp/my/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/tmp/my/spack/lib/spack/spack/spec.py", line 2957, in concretize
    self._new_concretize(tests)
  File "/tmp/my/spack/lib/spack/spack/spec.py", line 2930, in _new_concretize
    result.raise_if_unsat()
  File "/tmp/my/spack/lib/spack/spack/solver/asp.py", line 506, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    mpi%gcc is unsatisfiable, errors are:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/my/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
  File "/tmp/my/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/tmp/my/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/tmp/my/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
  File "/tmp/my/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/tmp/my/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    mpi%gcc is unsatisfiable, errors are:

### Information on your system

Spack: develop https://github.com/spack/spack/commit/35223543e9fa97f2706738abcce74477ceb274d9)
Python: 3.10.12
Platform: linux-ubuntu22.04-skylake
Concretizer: clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed on:

* **Spack:** 0.21.0.dev0 (6aa8d76e3213e03a8b404ea84441dd1ffed21960)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

I still have to decide whether this might be considered a bug, or if it is just a bad error message. What is your use case in asking to install "any mpi but compiled with gcc"?

**Comment by haampie** [comment]
This is now an error message ahead of concretization cause the concretizer doesn't support the input. But `mpi%gcc` is unambiguous in contrast to `mpi+foo` (virtual variant or provider variant?) so it could be fixed at the solver level.
