### ISSUE TITLE
concretizer internal error: slate +sycl +mpi %oneapi from PR#39927

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#40118]
### Steps to reproduce

Trying to concretize `slate +sycl +mpi` in the environment attached below triggers a `concretizer internal error` using:
* Using `G-Ragghianti:gragghia/slate_sycl` from https://github.com/spack/spack/pull/39927
* Docker container image `ecpe4s/ubuntu20.04-runner-x86_64-oneapi:2023.07.21`
* OneAPI 2023.2.0

Spack environment: [spack.yaml.txt](https://github.com/spack/spack/files/12677940/spack.yaml.txt)

Error:
```
$> time spack -e . concretize -f -j18
==> Starting concretization
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    slate+mpi+sycl is unsatisfiable, errors are:

real	0m20.524s
user	0m19.935s
sys	0m0.597s
```

Any idea @alalazo ?

### Error message

```
$> time spack --debug --stacktrace -e . concretize -f -j18
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-09-20-15:21:53.870392] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/util/executable.py:193 ==> [2023-09-20-15:21:53.870995] '/opt/bootstrap/view/bin/patchelf' '--version'
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-09-20-15:21:53.884464] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-09-20-15:21:53.888760] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:376 ==> [2023-09-20-15:21:53.888899] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:53.889922] Reading config from file /spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:53.923690] Reading config from file /spack.yaml
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:53.952929] Reading config from file /spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:208 ==> [2023-09-20-15:21:53.975779] Using environment '/'
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:53.975959] Reading config from file /spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:54.098255] Reading config from file /spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:988 ==> [2023-09-20-15:21:54.256125] Reading config from file /spack/etc/spack/defaults/packages.yaml
Traceback (most recent call last):
  File "/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/concretize.py", line 44, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/spack/lib/spack/spack/environment/environment.py", line 1336, in concretize
    return self._concretize_separately(tests=tests)
  File "/spack/lib/spack/spack/environment/environment.py", line 1518, in _concretize_separately
    concretized_root_specs = spack.util.parallel.parallel_map(
  File "/spack/lib/spack/spack/util/parallel.py", line 133, in parallel_map
    raise_if_errors(*results, debug=debug)
  File "/spack/lib/spack/spack/util/parallel.py", line 81, in raise_if_errors
    raise RuntimeError(error_fmt.format(msg))
RuntimeError: [PID=470] Traceback (most recent call last):
  File "/spack/lib/spack/spack/util/parallel.py", line 53, in __call__
    value = self.func(*args, **kwargs)
  File "/spack/lib/spack/spack/environment/environment.py", line 2424, in _concretize_task
    return _concretize_from_constraints(spec_constraints, tests)
  File "/spack/lib/spack/spack/environment/environment.py", line 2400, in _concretize_from_constraints
    return s.concretized(tests=tests)
  File "/spack/lib/spack/spack/spec.py", line 3096, in concretized
    clone.concretize(tests=tests)
  File "/spack/lib/spack/spack/spec.py", line 2992, in concretize
    self._new_concretize(tests)
  File "/spack/lib/spack/spack/spec.py", line 2965, in _new_concretize
    result.raise_if_unsat()
  File "/spack/lib/spack/spack/solver/asp.py", line 497, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    slate+mpi+sycl is unsatisfiable, errors are:


real	0m20.089s
user	0m19.408s
sys	0m0.667s
```

### Information on your system

* **Spack:** 0.21.0.dev0 (7550fc0e75afa3430d8b05ae2a17c1e06e517a51)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Unreproducible for me using:

* **Spack:** 0.21.0.dev0 (8a0de10f60ead1398419257fc2efa37a9bc24b3c)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-10-13 11-02-11](https://github.com/spack/spack/assets/4199709/884f9064-8514-4f19-9233-c56265e9c91c)

**Comment by eugeneswalker** [comment]
> Unreproducible for me using:
> 
>     * **Spack:** 0.21.0.dev0 ([8a0de10](https://github.com/spack/spack/commit/8a0de10f60ead1398419257fc2efa37a9bc24b3c))
> 
>     * **Python:** 3.8.10
> 
>     * **Platform:** linux-ubuntu20.04-icelake
> 
>     * **Concretizer:** clingo
> 
> 
> ![Screenshot from 2023-10-13 11-02-11](https://user-images.githubusercontent.com/4199709/274852889-884f9064-8514-4f19-9233-c56265e9c91c.png)

This error was flagged as part of the CI for this now-merged PR:
* https://github.com/spack/spack/commit/1b75651af6e84cd8ad41bbd0257ab16e09389eec

The error was because the slate +sycl PR required `intel-oneapi-mpi` specifically for the MPI, where the E4S environment had `packages:mpi:require:mpich` -- although that wasn't clear from the concretizer error message, we figured it out and updated the PR to not require intel-oneapi-mpi specifically. Forgot to close this! Sorry!  Thank you!
