### ISSUE TITLE
Concretizer internal error with a spec that previously worked

### ISSUE THREAD

**Issue by v-dobrev** [LLNL/spack#40264]
### Steps to reproduce

```console
./bin/spack spec -I xsdk-examples@0.4.0
```

### Error message

```console
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    xsdk-examples@0.4.0 is unsatisfiable, errors are:
```

Debug output:
```console
>./bin/spack -d spec -I xsdk-examples@0.4.0
==> [2023-09-30-13:11:05.949225] Imported spec from built-in commands
==> [2023-09-30-13:11:05.949588] Imported spec from built-in commands
==> [2023-09-30-13:11:05.950212] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/config.yaml
==> [2023-09-30-13:11:05.963093] DATABASE LOCK TIMEOUT: 60s
==> [2023-09-30-13:11:05.963133] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-09-30-13:11:05.965687] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-30-13:11:05.990111] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/repos.yaml
==> [2023-09-30-13:11:05.992437] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-09-30-13:11:05.992654] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-30-13:11:05.996474] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/dobrev1/spack/etc/spack/defaults
==> [2023-09-30-13:11:05.996501] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/Users/dobrev1/spack/etc/spack/defaults/darwin
==> [2023-09-30-13:11:05.996523] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/dobrev1/.spack/bootstrap/config
==> [2023-09-30-13:11:05.996540] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/dobrev1/.spack/bootstrap/config/darwin
==> [2023-09-30-13:11:05.997031] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/config.yaml
==> [2023-09-30-13:11:06.008945] Reading config from file /Users/dobrev1/.spack/bootstrap/config/darwin/config.yaml
==> [2023-09-30-13:11:06.014515] DATABASE LOCK TIMEOUT: 60s
==> [2023-09-30-13:11:06.014562] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-09-30-13:11:06.014733] Reading config from file /Users/dobrev1/.spack/bootstrap/config/darwin/compilers.yaml
==> [2023-09-30-13:11:06.044687] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %apple-clang target=aarch64
==> [2023-09-30-13:11:06.061290] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=aarch64
==> [2023-09-30-13:11:06.061419] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-09-30-13:11:06.061689] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-09-30-13:11:06.176991] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/packages.yaml
==> [2023-09-30-13:11:06.194389] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/darwin/packages.yaml
==> [2023-09-30-13:11:06.222105] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=aarch64 ^python@3.9/p2cyqcsow6k6prfryoqb7usv27hhofuq" provides the "clingo" Python module
==> [2023-09-30-13:11:06.222535] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/concretizer.yaml
==> [2023-09-30-13:11:06.227132] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/repos.yaml
==> [2023-09-30-13:11:06.278689] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/packages.yaml
==> [2023-09-30-13:11:06.296195] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/darwin/packages.yaml
==> [2023-09-30-13:11:06.303387] Reading config from file /Users/dobrev1/spack/etc/spack/packages.yaml
==> [2023-09-30-13:11:06.331952] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/config.yaml
==> [2023-09-30-13:11:06.344053] Reading config from file /Users/dobrev1/spack/etc/spack/defaults/mirrors.yaml
==> [2023-09-30-13:11:08.636503] Reading config from file /Users/dobrev1/spack/etc/spack/compilers.yaml
==> [2023-09-30-13:11:22.908916] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    xsdk-examples@0.4.0 is unsatisfiable, errors are:
==> [2023-09-30-13:11:22.909025] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    xsdk-examples@0.4.0 is unsatisfiable, errors are:
Traceback (most recent call last):
  File "/Users/dobrev1/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/Users/dobrev1/spack/lib/spack/spack/spec.py", line 2959, in concretize
    self._new_concretize(tests)
  File "/Users/dobrev1/spack/lib/spack/spack/spec.py", line 2932, in _new_concretize
    result.raise_if_unsat()
  File "/Users/dobrev1/spack/lib/spack/spack/solver/asp.py", line 506, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    xsdk-examples@0.4.0 is unsatisfiable, errors are:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dobrev1/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
  File "/Users/dobrev1/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/dobrev1/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/dobrev1/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
  File "/Users/dobrev1/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/Users/dobrev1/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    xsdk-examples@0.4.0 is unsatisfiable, errors are:
```

### Information on your system

```console
>./bin/spack debug report
* **Spack:** 0.21.0.dev0 (08a9345fccd6c3cb9c574101e9b98abc1e2c4131)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m2
* **Concretizer:** clingo
```
The default configured compiler is `apple-clang@14.0.3`.

⚠️ This issue is not specific to this machine -- it happens on other machines as well, e.g. on Linux with gcc 11.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by balay** [comment]
git bisect suggests the above failure started with:

```
commit b7cc4bd247c6dacf1fd1f6076e8d6e92c7c916b5
Author: Massimiliano Culpo <massimiliano.culpo@gmail.com>
Date:   Wed Jun 21 06:29:16 2023 +0200

    Reduce the dependency types in a solve

    Count the maximum number of nodes based on dependency types

 lib/spack/spack/solver/asp.py | 29 +++++++++++++++++++++++++----
 1 file changed, 25 insertions(+), 4 deletions(-)
```

However - the message here is different

```
balay@xsdk:/data/balay/spack.aa>./bin/spack spec  xsdk-examples@0.4.0 %gcc@11.3.1 ^amrex dimensions=3
==> Error: module 'spack.repo' has no attribute 'path'
```

**Comment by balay** [comment]
```diff
diff --git a/var/spack/repos/builtin/packages/xsdk-examples/package.py b/var/spack/repos/builtin/packages/xsdk-examples/package.py
index 1f39bcada7..15ba3d5e14 100644
--- a/var/spack/repos/builtin/packages/xsdk-examples/package.py
+++ b/var/spack/repos/builtin/packages/xsdk-examples/package.py
@@ -39,11 +39,11 @@ class XsdkExamples(CMakePackage, CudaPackage, ROCmPackage):
     # Use ^dealii~hdf5 because of HDF5 linking issue in deal.II 9.4.0.
     # Disable 'arborx' to remove the 'kokkos' dependency which conflicts with
     # the internal Kokkos used by 'trilinos':
-    depends_on("xsdk@0.8.0 ~arborx ^mfem+pumi ^dealii~hdf5", when="@0.4.0")
+    #depends_on("xsdk@0.8.0 ~arborx ^mfem+pumi ^dealii~hdf5", when="@0.4.0")
     depends_on("xsdk@0.8.0 ^mfem+strumpack", when="@0.4.0 ^xsdk+strumpack")
     depends_on("xsdk@0.8.0 ^mfem+ginkgo", when="@0.4.0 ^xsdk+ginkgo")
     depends_on("xsdk@0.8.0 ^mfem+hiop", when="@0.4.0 ^xsdk+hiop")
-    depends_on("xsdk@0.8.0 ^sundials+magma", when="@0.4.0 +cuda")
+    #depends_on("xsdk@0.8.0 ^sundials+magma", when="@0.4.0 +cuda")
     depends_on("xsdk@0.7.0", when="@0.3.0")
     depends_on("xsdk@0.7.0 ^mfem+strumpack", when="@0.3.0 ^xsdk+strumpack")
     depends_on("xsdk@0.7.0 ^sundials+magma", when="@0.3.0 +cuda")
```

Additional note:

Removing the first dependency helps with:
```console
./bin/spack spec  xsdk-examples@0.4.0 %gcc@11.3.1 ^amrex dimensions=3
```
And removing the second dependency helps with:
```console
./bin/spack spec xsdk-examples@0.4.0 %gcc@11.3.1 +cuda cuda_arch=70 ^cuda@11.7.1 ^openmpi ^amrex dimensions=3
```
[but the build can be broken with incorrect dependencies?]

**Comment by haampie** [comment]
@alalazo

```
9f8edbf6bf6bb86ac448f6132f766e65ae1424ef is the first bad commit
commit 9f8edbf6bf6bb86ac448f6132f766e65ae1424ef
Author: Massimiliano Culpo <massimiliano.culpo@gmail.com>
Date:   Thu Jun 29 11:26:25 2023 +0200

    Add a new configuration option to select among different concretization modes
    
    The "concretizer" section has been extended with a "duplicates:strategy"
    attribute, that can take three values:
    
    - "none": only 1 node per package
    - "minimal": allow multiple nodes opf specific packages
    - "full": allow full duplication for a build tool

 etc/spack/defaults/concretizer.yaml   |   6 ++
 lib/spack/spack/schema/concretizer.py |   6 ++
 lib/spack/spack/solver/asp.py         |  60 +++++---------
 lib/spack/spack/solver/concretize.lp  |  25 ++++--
 lib/spack/spack/solver/counter.py     | 148 ++++++++++++++++++++++++++++++++++
 5 files changed, 197 insertions(+), 48 deletions(-)
 create mode 100644 lib/spack/spack/solver/counter.py
```
