### ISSUE TITLE
 py-cutadapt - spack won't load python dependencies automatically

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#4041]
Hi

I created a new package using "spack create."  How fun!  This is such great software!!!

This is the template:

```
from spack import *

class PyCutadapt(PythonPackage):
    """Cutadapt finds and removes adapter sequences, primers, poly-A tails and other types of unwanted sequence from your high-throughput sequencing reads."""

    homepage = "https://pypi.python.org/pypi/cutadapt"
    url      = "https://pypi.python.org/packages/4b/a0/caf0a418d64a69da12c0f5ede20830f0b7dba2d29efa3f667f1ce69e78da/cutadapt-1.13.tar.gz"

    version('1.13', '2d2d14e0c20ad53d7d84b57bc3e63b4c')

    depends_on('py-setuptools',        type=('build', 'run'))
    depends_on('py-xopen',        type=('build', 'run'))
    depends_on('py-six',        type=('build', 'run'))
    depends_on('py-packaging',        type=('build', 'run'))
    depends_on('py-pyparsing',        type=('build', 'run'))
    depends_on('py-appdirs',        type=('build', 'run'))
    depends_on('py-pip',        type=('build', 'run'))

```

```
[root@node123 ~]# spack info py-cutadapt
PythonPackage:    py-cutadapt
Homepage:         https://pypi.python.org/pypi/cutadapt

Safe versions:  
    1.13    https://pypi.python.org/packages/4b/a0/caf0a418d64a69da12c0f5ede20830f0b7dba2d29efa3f667f1ce69e78da/cutadapt-1.13.tar.gz

Variants:
    None

Installation Phases:
    build    install

Build Dependencies:
    py-appdirs  py-packaging  py-pip  py-pyparsing  py-setuptools  py-six  py-xopen  python

Link Dependencies:
    python

Run Dependencies:
    py-appdirs  py-packaging  py-pip  py-pyparsing  py-setuptools  py-six  py-xopen  python

Virtual Packages: 
    None

Description:
    Cutadapt finds and removes adapter sequences, primers, poly-A tails and
    other types of unwanted sequence from your high-throughput sequencing
    reads.

```

Though when I run spack load the run dependencies are not included so I have to load them individually.

I tried spack activate per [https://spack.readthedocs.io/en/latest/basic_usage.html#specs-dependencies](url) but that does not work.

**Comment by adamjstewart** [comment]
I don't currently use modules, so I'll let someone else comment on the `spack load` dilemma.

> I tried `spack activate` ... but that does not work.

What does not work about it? `spack activate` should symlink all of the Python packages you install to the base Python installation so you only have to load a single module and you don't need to set `PYTHONPATH`.

**Comment by alalazo** [comment]
For the module files you may want t have a look [here](http://spack.readthedocs.io/en/latest/module_file_support.html#autoload-dependencies). The default configuration we ship doesn't generate code to automatically load other modules. You need to write a custom `modules.yaml` that contains:
```yaml
modules:
  tcl:
    ^python:
      autoload: 'direct'
```

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart 

But I don't see the extension activated:

```
[root@node114 ~]# spack load python@2.7.13 %gcc@4.4.6

[root@node114 ~]# which python
/pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.6/python-2.7.13-mpz42h4l6tlizjwropjqvmjkepz25hpt/bin/python

[root@node114 ~]# python --version
Python 2.7.13

[root@node114 ~]# spack activate py-cutadapt
==> Activated extension py-cutadapt@1.13%gcc@4.4.6 arch=linux-rhel6-x86_64 /klysrs7 for python@2.7.13~tk~ucs4%gcc@4.4.6

[root@node114 ~]# spack extensions python@2.7.13 %gcc@4.4.6                                                                                                                                                                                   
==> python@2.7.13%gcc@4.4.6~tk~ucs4 arch=linux-rhel6-x86_64 /mpz42h4 has no extensions.

[root@node114 ~]# spack extensions python                                                                                                                                                                                                     
==> Error: python matches multiple packages.
  Matching packages:
    mpz42h4 python@2.7.13%gcc@4.4.6 arch=linux-rhel6-x86_64 
    5ogh6la python@2.7.13%gcc@6.3.0 arch=linux-rhel6-x86_64 
    ab5wsqm python@3.4.3%gcc@4.4.6 arch=linux-rhel6-x86_64 
    lsjctw7 python@3.5.2%gcc@4.4.6 arch=linux-rhel6-x86_64 
    pndebbt python@3.5.2%gcc@6.3.0 arch=linux-rhel6-x86_64 
    homuiqv python@3.6.0%gcc@4.4.6 arch=linux-rhel6-x86_64 
    2pfngwu python@3.6.0%gcc@6.3.0 arch=linux-rhel6-x86_64 
  Use a more specific spec.

[root@node114 ~]# spack extensions python /2pfngwu
==> python@3.6.0%gcc@6.3.0~tk~ucs4 arch=linux-rhel6-x86_64 /2pfngwu has no extensions.

[root@node114 ~]# spack extensions python /homuiqv
==> python@3.6.0%gcc@4.4.6~tk~ucs4 arch=linux-rhel6-x86_64 /homuiqv has no extensions.

[root@node114 ~]# spack extensions python /pndebbt
==> python@3.5.2%gcc@6.3.0~tk~ucs4 arch=linux-rhel6-x86_64 /pndebbt has no extensions.

[root@node114 ~]# spack extensions python /lsjctw7
==> python@3.5.2%gcc@4.4.6~tk~ucs4 arch=linux-rhel6-x86_64 /lsjctw7 has no extensions.

[root@node114 ~]# spack extensions python /ab5wsqm
==> python@3.4.3%gcc@4.4.6~tk~ucs4 arch=linux-rhel6-x86_64 /ab5wsqm has no extensions.

[root@node114 ~]# spack extensions python /5ogh6la
==> python@2.7.13%gcc@6.3.0~tk~ucs4 arch=linux-rhel6-x86_64 /5ogh6la has no extensions.

[root@node114 ~]# spack extensions python /mpz42h4
==> python@2.7.13%gcc@4.4.6~tk~ucs4 arch=linux-rhel6-x86_64 /mpz42h4 has no extensions.

[root@node114 ~]# cutadapt 
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.6/python-2.7.13-mpz42h4l6tlizjwropjqvmjkepz25hpt/bin/cutadapt", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

```

@alalazo 

Thanks!  I added the file though not all of the dependencies are loaded.

```
[root@node114 ~]# cat ~/.spack/modules.yml 
modules:
  tcl:
    ^python:
      autoload: 'direct'

root@node114 ~]# source /pbtech_mounts/softlib001/apps/EL6/spack/share/spack/setup-env.sh        
                                                                                                                                  
[root@node114 ~]# spack load py-cutadapt
Autoloading py-xopen-0.1.1-gcc-4.4.6-h4gmfpi

```
@alalazo 

I am not sure what I did but now the modulefile contains:

```
}

if ![ is-loaded python-2.7.13-gcc-4.4.6-mpz42h4 ] {
    puts stderr "Autoloading python-2.7.13-gcc-4.4.6-mpz42h4"
    module load python-2.7.13-gcc-4.4.6-mpz42h4
}

if ![ is-loaded py-xopen-0.1.1-gcc-4.4.6-h4gmfpi ] {
    puts stderr "Autoloading py-xopen-0.1.1-gcc-4.4.6-h4gmfpi"
    module load py-xopen-0.1.1-gcc-4.4.6-h4gmfpi
}
```

How can I make the module file contain the rest?  I did "spack refresh py-cutadapt" and now the above isn't present in the modulefile anymore!

**Comment by adamjstewart** [comment]
> But I don't see the extension activated:

`spack extensions` doesn't work and hasn't worked for the longest time. See http://spack.readthedocs.io/en/latest/known_issues.html#spack-extensions-doesn-t-work

> ```
> [root@node114 ~]# cutadapt 
> Traceback (most recent call last):
>   File "/pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.6/python-2.7.13-mpz42h4l6tlizjwropjqvmjkepz25hpt/bin/cutadapt", line 7, in <module>
>     from pkg_resources import load_entry_point
> ImportError: No module named pkg_resources
```
Question: Did you add the `run` type dependency on `py-setuptools` after you build the package? If so you need to reinstall it for it to be registered in the database.

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart 

I had 

> depends_on('py-setuptools',        type=('build', 'run'))

In place within spack/var/spack/repos/builtin/packages/py-cutadapt/package.py before installing whereas I added these after building:
```

    depends_on('py-xopen',        type=('build', 'run'))
    depends_on('py-six',        type=('build', 'run'))
    depends_on('py-packaging',        type=('build', 'run'))
    depends_on('py-pyparsing',        type=('build', 'run'))
    depends_on('py-appdirs',        type=('build', 'run'))
    depends_on('py-pip',        type=('build', 'run'))
```

**Comment by adamjstewart** [comment]
You can also check in the Python installation directory to see whether or not things are getting symlinked:
```
<prefix>/lib/python2.7/site-packages/
```
But yeah, you'll have to reinstall `py-cutadapt` to make sure the dependencies are in the database.

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart @alalazo 

Thanks for your patience.

**Comment by adamjstewart** [comment]
Once you have it working, feel free to submit a PR and we can get it added to Spack. I'll probably have a few comments for improvements as well.

**Comment by JusticeForMikeBrown** [comment]
It is now working after reinstalling!!!!

```
[root@node114 ~]# spack load python@2.7.13

[root@node114 ~]# spack activate py-cutadapt
==> Activated extension py-appdirs@1.4.3%gcc@4.4.6 arch=linux-rhel6-x86_64 /ql7ici2 for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-pyparsing@2.2.0%gcc@4.4.6 arch=linux-rhel6-x86_64 /rhyvm55 for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-six@1.10.0%gcc@4.4.6 arch=linux-rhel6-x86_64 /7x32cua for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-packaging@16.8%gcc@4.4.6 arch=linux-rhel6-x86_64 /tu5rl2k for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-setuptools@34.4.1%gcc@4.4.6 arch=linux-rhel6-x86_64 /lls77cr for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-pip@9.0.1%gcc@4.4.6 arch=linux-rhel6-x86_64 /poidxnq for python@2.7.13~tk~ucs4%gcc@4.4.6
==> Activated extension py-cutadapt@1.13%gcc@4.4.6 arch=linux-rhel6-x86_64 /t4kxsr6 for python@2.7.13~tk~ucs4%gcc@4.4.6
```

```
[root@node114 ~]# cutadapt | head
cutadapt version 1.13
Copyright (C) 2010-2017 Marcel Martin <marcel.martin@scilifelab.se>

cutadapt removes adapter sequences from high-throughput sequencing reads.

Usage:
    cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq

For paired-end reads:
    cutadapt -a ADAPT1 -A ADAPT2 [options] -o out1.fastq -p out2.fastq in1.fastq in2.fastq

```
