### ISSUE TITLE
@-sign in dev_path variant mistaken for another version

### ISSUE THREAD

**Issue by jonasjucker** [LLNL/spack#40449]
### Steps to reproduce

If the dev_path variant contains any "@-sign", i.e like `/path/with/_@_/sign` or `/path/with@2/sign` spack complains about multiple versions.
Below to commands that reproduce the issue.

```console
spack spec xz@5.4%gcc dev_path=/path/with/_@_/sign
spack spec xz@5.4%gcc dev_path=/path/with@2/sign
```

Either spack should catch that case and report a proper error as it does so for
```console
spack spec xz@5.4%gcc dev_path=/path/@/sign
==> Error: unexpected tokens in the spec string
xz@5.4%gcc dev_path=/path/@/sign
                          ^
```
or it should escape it and treat is as a regular path.

**Some context**

Our Jenkins CI-server appends "@"-signs to workspace paths whenever a pipeline is executed multiple times in parallel, i.e.
`/workspace/parallel_pipeline` for first execution

`/workspace/parallel_pipeline@2` for second execution

and `/workspace/parallel_pipeline@3` for third execution in parallel.

In case we use `spack dev-build` or `spack develop` in build 2 or 3 spack fails.

### Error message

```console
==> Error: xz@5.4%gcc dev_path=/path/with/_ cannot have multiple versions
```

``` console
lib/spack/spack/cmd/__init__.py:121 ==> [2023-10-11-12:22:21.711799] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:121 ==> [2023-10-11-12:22:21.713069] Imported spec from built-in commands
lib/spack/spack/config.py:988 ==> [2023-10-11-12:22:21.742338] Reading config from file /scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:634 ==> [2023-10-11-12:22:21.777248] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2023-10-11-12:22:21.777781] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/main.py:1025 ==> [2023-10-11-12:22:21.778911] SpackError: xz@5.4%gcc dev_path=/path/with/_ cannot have multiple versions
lib/spack/spack/error.py:52 ==> [2023-10-11-12:22:21.779850] Error: xz@5.4%gcc dev_path=/path/with/_ cannot have multiple versions
Traceback (most recent call last):
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/cmd/__init__.py", line 215, in parse_specs
    specs = spack.parser.parse(sargs)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/parser.py", line 444, in parse
    return SpecParser(text).all_specs()
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/parser.py", line 300, in all_specs
    return list(iter(self.next_spec, None))
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/parser.py", line 279, in next_spec
    root_spec = SpecNodeParser(self.ctx).parse(initial_spec)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/parser.py", line 366, in parse
    f"{initial_spec} cannot have multiple versions"
spack.spec.MultipleVersionError: xz@5.4%gcc dev_path=/path/with/_ cannot have multiple versions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/cmd/spec.py", line 100, in spec
    input_specs = spack.cmd.parse_specs(args.specs)
  File "/scratch/e1000/meteoswiss/scratch/juckerj/spack_debug_report/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: xz@5.4%gcc dev_path=/path/with/_ cannot have multiple versions
```

### Information on your system

* **Spack:** 0.21.0.dev0 (da030617a1008dc74a960e9af7ca25f8e8072281)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed, thanks for the report
