### ISSUE TITLE
Version conflict of py-pandas and py-openpyxl

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#40452]
### Steps to reproduce the issue

@adamjstewart 

This error pops up in one of the JCSDA applications:
```
Traceback (most recent call last):
  File "/Users/heinzell/work/github-admin/github-admin-develop/github_api/./commit_summary.py", line 489, in <module>
    main()
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-click-8.0.3-edxrx3v/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-click-8.0.3-edxrx3v/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-click-8.0.3-edxrx3v/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-click-8.0.3-edxrx3v/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/heinzell/work/github-admin/github-admin-develop/github_api/./commit_summary.py", line 159, in main
    summary_output(df_all, xml)
  File "/Users/heinzell/work/github-admin/github-admin-develop/github_api/./commit_summary.py", line 435, in summary_output
    df_contrib = pd.read_excel(fuser, sheet_name='ALL', index_col=None, engine="openpyxl")
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 556, in __init__
    import_optional_dependency("openpyxl")
  File "/Users/heinzell/prod/spack-stack-1.5.0/envs/unified-env/install/apple-clang/13.1.6/py-pandas-1.5.3-jnyekmt/lib/python3.10/site-packages/pandas/compat/_optional.py", line 171, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.0.7' or newer of 'openpyxl' (version '3.0.3' currently installed).
```
The versions in use are: `py-pandas@1.5.3` (not sure how this relates to the 3.0.7 version reported above) and `py-openpyxl@3.0.3`

**To Reproduce**
Reproducer:
```
#!/usr/bin/env python3

import pandas as pd
from pathlib import Path

user_file = "AOP2023 Q2 GitHub usernames.xlsx"
fuser = Path('input/'+user_file)
df_contrib = pd.read_excel(fuser, sheet_name='ALL', index_col=None, engine="openpyxl")
```
I will note that `py-openpyxl` is an optional dependency of `py-pandas` or vice versa.

### Error message

<details><summary>Error message</summary>

<pre>
...
</pre></details>
See above

### Information on your system

```
* **Spack:** 0.21.0.dev0 (8296fcf898cb2997ad309273ab8480114c134bca)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo
```

### Additional information

n/a

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@adamjstewart The simplest solution might be as follows, but I will note that optional dependencies in `py-pandas` aren't configured and that the dependencies in `py-openpyxl` don't match what's in the packages `requirements.txt` file (e.g. https://foss.heptapod.net/openpyxl/openpyxl/-/blob/3.0.3/requirements.txt). But I unfortunately don't have the time to redo all of this (if deemed necessary).
```
diff --git a/var/spack/repos/builtin/packages/py-openpyxl/package.py b/var/spack/repos/builtin/packages/py-openpyxl/package.py
index 4d81f37222..2e2fbb9105 100644
--- a/var/spack/repos/builtin/packages/py-openpyxl/package.py
+++ b/var/spack/repos/builtin/packages/py-openpyxl/package.py
@@ -12,6 +12,7 @@ class PyOpenpyxl(PythonPackage):
     homepage = "https://openpyxl.readthedocs.org/"
     pypi = "openpyxl/openpyxl-3.0.3.tar.gz"

+    version("3.0.7", sha256="6456a3b472e1ef0facb1129f3c6ef00713cebf62e736cd7a75bcc3247432f251")
     version("3.0.3", sha256="547a9fc6aafcf44abe358b89ed4438d077e9d92e4f182c87e2dc294186dc4b64")
     version("2.4.5", sha256="78c331e819fb0a63a1339d452ba0b575d1a31f09fdcce793a31bec7e9ef4ef21")
     version("2.2.0", sha256="c34e3f7e3106dbe6d792f35d9a2f01c08fdd21a6fe582a2f540e39a70e7443c4")
diff --git a/var/spack/repos/builtin/packages/py-pandas/package.py b/var/spack/repos/builtin/packages/py-pandas/package.py
index 1a46b9a9c6..6abd9aab7c 100644
--- a/var/spack/repos/builtin/packages/py-pandas/package.py
+++ b/var/spack/repos/builtin/packages/py-pandas/package.py
@@ -127,4 +127,7 @@ class PyPandas(PythonPackage):
     # Optional dependencies
     # https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies

+    # https://github.com/spack/spack/issues/40452
+    depends_on("py-openpyxl@3.0.7:", type=("run"), when="@1.5.3:")
+
     skip_modules = ["pandas.tests", "pandas.plotting._matplotlib", "pandas.core._numba.kernels"]
```
