### ISSUE TITLE
`Containerize` doesn't read templates

### ISSUE THREAD

**Issue by matt-chan** [LLNL/spack#40475]
### Steps to reproduce

I followed the [containerize documentation](https://spack.readthedocs.io/en/latest/containers.html#extending-the-jinja2-templates) exactly and it couldn't find the custom templates.

<img width="199" alt="image" src="https://github.com/spack/spack/assets/1048117/fa1c23dd-5095-4c8e-a3de-56e8dade5437">

### Error message

```console
# spack -d containerize
==> [2023-10-12-04:51:19.340450] Imported containerize from built-in commands
==> [2023-10-12-04:51:19.340901] Imported containerize from built-in commands
==> [2023-10-12-04:51:19.405615] Reading config from file /home/hpcadmin/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/hpcadmin/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/hpcadmin/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/home/hpcadmin/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
  File "/home/hpcadmin/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/hpcadmin/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/hpcadmin/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
  File "/home/hpcadmin/spack/lib/spack/spack/cmd/containerize.py", line 48, in containerize
    recipe = spack.container.recipe(config, last_phase=args.last_stage)
  File "/home/hpcadmin/spack/lib/spack/spack/container/writers/__init__.py", line 64, in recipe
    return create(configuration, last_phase)()
  File "/home/hpcadmin/spack/lib/spack/spack/container/writers/__init__.py", line 314, in __call__
    t = env.get_template(template_name)
  File "/home/hpcadmin/spack/lib/spack/external/_vendoring/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/hpcadmin/spack/lib/spack/external/_vendoring/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/hpcadmin/spack/lib/spack/external/_vendoring/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/hpcadmin/spack/lib/spack/external/_vendoring/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: CustomDockerfile
```

### Information on your system

* **Spack:** 0.21.0.dev0 (deec1b7c2e05abcd224a73c0d53470e90b7df5bf)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Hard to say if this is the issue without further information, but you need to have the environment active if you put the extra template dir in the `spack.yaml`:
```console
$ spack -e <path-to-spack-yaml-dir> containerize
```

**Comment by matt-chan** [comment]
Yep that was it. It works now. I'll PR the docs to make it explicit
