### ISSUE TITLE
Installation issue: py-pyarrow@13.0.0

### ISSUE THREAD

**Issue by orliac** [LLNL/spack#40798]
### Steps to reproduce the issue

Modify the recipe for py-pyarrow for version 13.0.0 with:
``` 
19d18
<     version("13.0.0", sha256="83333726e83ed44b0ac94d8d7a21bbdee4a05029c3b1e8db58a863eec8fd8a33")
42d40
<     depends_on("python@3.11:", type=("build", "run"), when="@13.0.0:")
50d47
<     depends_on("py-cython@3.0.5:", type="build", when="@13.0.0:")
68d64
<         "@13.0.0",
```

```console
$ spack spec -I 
$ spack spec -I py-pyarrow@13.0.0
Input spec
--------------------------------
 -   py-pyarrow@13.0.0

Concretized
--------------------------------
 -   py-pyarrow@13.0.0%gcc@11.3.0~cuda~dataset~orc~parquet build_system=python_pip arch=linux-rhel8-cascadelake
[+]      ^arrow@13.0.0%gcc@11.3.0~brotli~compute~cuda~gandiva~glog~hdfs+ipc~ipo~jemalloc~lz4~orc~parquet+python+shared~snappy~tensorflow~zlib~zstd build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]          ^boost@1.83.0%gcc@11.3.0~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber+filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=a440f96 visibility=hidden arch=linux-rhel8-cascadelake
[+]          ^flatbuffers@2.0.6%gcc@11.3.0~ipo~python+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]          ^gmake@4.4.1%gcc@11.3.0~guile build_system=generic arch=linux-rhel8-cascadelake
[+]          ^ninja@1.11.1%gcc@11.3.0+re2c build_system=generic arch=linux-rhel8-cascadelake
[+]              ^re2c@2.2%gcc@11.3.0 build_system=generic arch=linux-rhel8-cascadelake
[+]          ^openssl@3.1.3%gcc@11.3.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel8-cascadelake
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@11.3.0 build_system=generic arch=linux-rhel8-cascadelake
[+]              ^perl@5.38.0%gcc@11.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel8-cascadelake
[+]                  ^berkeley-db@18.1.40%gcc@11.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-cascadelake
[+]          ^rapidjson@1.2.0-2022-03-09%gcc@11.3.0~doc~ipo build_system=cmake build_type=Release generator=make patches=a4316c5 arch=linux-rhel8-cascadelake                                                                                                                                                   
[+]          ^re2@2023-09-01%gcc@11.3.0~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]              ^abseil-cpp@20230125.3%gcc@11.3.0~ipo+shared build_system=cmake build_type=Release cxxstd=14 generator=make arch=linux-rhel8-cascadelake                                                                                                                                                       
[+]          ^snappy@1.1.10%gcc@11.3.0~ipo+pic~shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]          ^utf8proc@2.8.0%gcc@11.3.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]          ^xsimd@8.1.0%gcc@11.3.0~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel8-cascadelake
[+]      ^cmake@3.27.7%gcc@11.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel8-cascadelake
[+]          ^curl@8.4.0%gcc@11.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel8-cascadelake                                                                                                                                       
[+]              ^nghttp2@1.57.0%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^ncurses@6.4%gcc@11.3.0~symlinks+termlib abi=none build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^zlib-ng@2.1.4%gcc@11.3.0+compat+opt build_system=autotools arch=linux-rhel8-cascadelake
[+]      ^pkgconf@1.9.5%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]      ^py-cython@3.0.5%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]          ^py-pip@23.1.2%gcc@11.3.0 build_system=generic arch=linux-rhel8-cascadelake
[+]      ^py-numpy@1.26.1%gcc@11.3.0 build_system=python_pip patches=873745d arch=linux-rhel8-cascadelake
[+]          ^openblas@0.3.24%gcc@11.3.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-rhel8-cascadelake
[+]          ^py-pyproject-metadata@0.7.1%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]      ^py-pip@23.0%gcc@11.3.0 build_system=generic arch=linux-rhel8-cascadelake
[+]      ^py-setuptools@68.0.0%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]      ^py-setuptools-scm@7.1.0%gcc@11.3.0+toml build_system=python_pip arch=linux-rhel8-cascadelake
[+]          ^git@2.42.0%gcc@11.3.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^autoconf@2.69%gcc@11.3.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel8-cascadelake
[+]              ^automake@1.16.5%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^libiconv@1.17%gcc@11.3.0 build_system=autotools libs=shared,static arch=linux-rhel8-cascadelake
[+]              ^libidn2@2.3.4%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]                  ^libunistring@1.1%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^libtool@2.4.7%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^m4@1.4.19%gcc@11.3.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel8-cascadelake
[+]                  ^libsigsegv@2.14%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^openssh@9.5p1%gcc@11.3.0+gssapi build_system=autotools arch=linux-rhel8-cascadelake
[+]                  ^krb5@1.20.1%gcc@11.3.0+shared build_system=autotools arch=linux-rhel8-cascadelake
[+]                      ^bison@3.8.2%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]                      ^findutils@4.9.0%gcc@11.3.0 build_system=autotools patches=440b954 arch=linux-rhel8-cascadelake
[+]                  ^libedit@3.1-20210216%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^pcre2@10.42%gcc@11.3.0~jit+multibyte build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^py-packaging@23.1%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]              ^py-flit-core@3.9.0%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]          ^py-tomli@2.0.1%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]          ^py-typing-extensions@4.8.0%gcc@11.3.0 build_system=python_pip arch=linux-rhel8-cascadelake
[+]      ^py-wheel@0.41.2%gcc@11.3.0 build_system=generic arch=linux-rhel8-cascadelake
[+]      ^python@3.11.6%gcc@11.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-rhel8-cascadelake
[+]          ^bzip2@1.0.8%gcc@11.3.0~debug~pic+shared build_system=generic arch=linux-rhel8-cascadelake
[+]              ^diffutils@3.9%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^expat@2.5.0%gcc@11.3.0+libbsd build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^libbsd@0.11.7%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]                  ^libmd@1.0.4%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^gdbm@1.23%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^gettext@0.22.3%gcc@11.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^libxml2@2.10.3%gcc@11.3.0+pic~python+shared build_system=autotools arch=linux-rhel8-cascadelake
[+]              ^tar@1.34%gcc@11.3.0 build_system=autotools zip=pigz arch=linux-rhel8-cascadelake
[+]                  ^pigz@2.7%gcc@11.3.0 build_system=makefile arch=linux-rhel8-cascadelake
[+]                  ^zstd@1.5.5%gcc@11.3.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel8-cascadelake
[+]          ^libffi@3.4.4%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^libxcrypt@4.4.35%gcc@11.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel8-cascadelake
[+]          ^readline@8.2%gcc@11.3.0 build_system=autotools patches=bbf97f1 arch=linux-rhel8-cascadelake
[+]          ^sqlite@3.43.2%gcc@11.3.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^util-linux-uuid@2.38.1%gcc@11.3.0 build_system=autotools arch=linux-rhel8-cascadelake
[+]          ^xz@5.4.1%gcc@11.3.0~pic build_system=autotools libs=shared,static arch=linux-rhel8-cascadelake

```

### Error message

<details><summary>Error message</summary>

<pre>
[+] /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-setuptools-scm-7.1.0-42cwh36x52la2uo6wsgsnv2tvzpkh762
==> Waiting for py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey
==> Installing py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey [55/56]
==> No binary for py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey found: installing from source
==> Using cached archive: /work/backup/ska/orliac/spack-dev/var/spack/cache/_source-cache/archive/83/83333726e83ed44b0ac94d8d7a21bbdee4a05029c3b1e8db58a863eec8fd8a33.tar.gz
==> No patches needed for py-pyarrow
==> py-pyarrow: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/python-3.11.6-mplzs4kvr3w6uxzsyhnsbdun5vfers5j/bin/python3.11' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey' '.'

2 errors found in build log:
     11    Created temporary directory: /tmp/pip-ephem-wheel-cache-dmy8fpxk
     12    Processing /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src
     13      Added file:///tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src to build tracker '/tmp/
           pip-build-tracker-hd_de9bl'
     14      Created temporary directory: /tmp/pip-modern-metadata-mlc9q8hx
     15      Preparing metadata (pyproject.toml): started
     16      Running command Preparing metadata (pyproject.toml)
  >> 17    <string>:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
     18      Traceback (most recent call last):
     19        File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/
           lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
     20          main()
     21        File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/
           lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
     22          json_out['return_val'] = hook(**hook_input['kwargs'])
     23                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

     ...

     40      ╰─> See above for output.
     41    
     42      note: This error originates from a subprocess, and is likely not a problem with pip.
     43      full command: /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/python-3.11.6-mplzs4kvr3w6uxzsyhnsbdun5
           vfers5j/bin/python3.11 /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534
           zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpn1
           r2_su1
     44      cwd: /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src
     45      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 46    error: metadata-generation-failed
     47    
     48    × Encountered error while generating package metadata.
     49    ╰─> See above for output.
     50    
     51    note: This is an issue with the package mentioned above, not pip.
     52    hint: See above for details.

See build log for details:
  /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-build-out.txt

</pre></details>

```
$ cat  /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-build-out.txt
==> py-pyarrow: Executing phase: 'install'
==> [2023-10-31-11:55:39.099121] '/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/python-3.11.6-mplzs4kvr3w6uxzsyhnsbdun5vfers5j/bin/python3.11' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey' '.'
Using pip 23.0 from /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip (python 3.11)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-build-tracker-hd_de9bl
Initialized build tracking at /tmp/pip-build-tracker-hd_de9bl
Created build tracker: /tmp/pip-build-tracker-hd_de9bl
Entered build tracker: /tmp/pip-build-tracker-hd_de9bl
Created temporary directory: /tmp/pip-install-ycazoqd2
Created temporary directory: /tmp/pip-ephem-wheel-cache-dmy8fpxk
Processing /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src
  Added file:///tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src to build tracker '/tmp/pip-build-tracker-hd_de9bl'
  Created temporary directory: /tmp/pip-modern-metadata-mlc9q8hx
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  <string>:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Traceback (most recent call last):
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-setuptools-68.0.0-af3wrber5vm7pn42stbyj5dmeosh7hek/lib/python3.11/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-setuptools-68.0.0-af3wrber5vm7pn42stbyj5dmeosh7hek/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-setuptools-68.0.0-af3wrber5vm7pn42stbyj5dmeosh7hek/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 44, in <module>
  Exception: Please update your Cython version. Supported Cython >= 0.29.31, < 3.0
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/python-3.11.6-mplzs4kvr3w6uxzsyhnsbdun5vfers5j/bin/python3.11 /work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpn1r2_su1
  cwd: /tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 722, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 415, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 539, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/work/ska/soft/spack/radiblocks/rb-dev0/opt/spack/linux-rhel8-cascadelake/gcc-11.3.0/py-pip-23.0-v3y6csj4rvrs474m7534zwxnwnabsdbg/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
Removed file:///tmp/orliac/spack-stage-izar/spack-stage-py-pyarrow-13.0.0-mqcyltsrblphziews2fpkoub5vh472ey/spack-src from build tracker '/tmp/pip-build-tracker-hd_de9bl'
Removed build tracker: '/tmp/pip-build-tracker-hd_de9bl'
```

### Information on your system

* **Spack:** 0.21.0.dev0 (160bfd881ddcb32a9b0fa1bd6eabe2f70b9bba41)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-cascadelake
* **Concretizer:** clingo

### Additional information

@adamjstewart
[spack-build-out.txt](https://github.com/spack/spack/files/13215937/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/13215938/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
> Please update your Cython version. Supported Cython >= 0.29.31, < 3.0

The error is pretty clear. Can you submit a PR that fixes the missing upperbound on Cython?

**Comment by orliac** [comment]
yes, but I try to build against cython > 3 explicitly, c.f. the description above for the change I made in the recipe:
```
50d47
<     depends_on("py-cython@3.0.5:", type="build", when="@13.0.0:")
```

**Comment by orliac** [comment]
OK, closing the issue. Looking at the pyproject.toml there is no support in pyarrow for cython3 yet.
