### ISSUE TITLE
concretizer internal error

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#40869]
### Steps to reproduce

```console
$ spack install visit%gcc@11.4.0+mpi+gui~silo~mfem ^python@3.7.7+shared ^mesa@21.2.5+opengl ^vtk@8.1.0 ^qt%gcc@11.4.0
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")
```

### Error message

```console
$ spack --debug --stacktrace install visit%gcc@11.4.0+mpi+gui~silo~mfem ^python@3.7.7+shared ^mesa@21.2.5+opengl ^vtk@8.1.0 ^qt%gcc@11.4.0
lib/spack/spack/cmd/__init__.py:121 ==> [2023-11-03-13:16:16.377882] Imported install from built-in commands
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.380951] Reading config from file /home/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:121 ==> [2023-11-03-13:16:16.390403] Imported install from built-in commands
lib/spack/spack/database.py:634 ==> [2023-11-03-13:16:16.396776] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2023-11-03-13:16:16.397435] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.398318] Reading config from file /home/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.406296] Reading config from file /home/benwibking/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2023-11-03-13:16:16.407972] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.408243] Reading config from file /home/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2023-11-03-13:16:16.411862] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/benwibking/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2023-11-03-13:16:16.411952] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/benwibking/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2023-11-03-13:16:16.412034] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/benwibking/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2023-11-03-13:16:16.412115] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/benwibking/.spack/bootstrap/config/linux
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.412597] Reading config from file /home/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.421131] Reading config from file /home/benwibking/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:634 ==> [2023-11-03-13:16:16.425264] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2023-11-03-13:16:16.425360] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.425863] Reading config from file /home/benwibking/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-11-03-13:16:16.434182] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=aarch64
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.434426] Reading config from file /home/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:185 ==> [2023-11-03-13:16:16.439192] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=aarch64'
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.489423] Reading config from file /home/benwibking/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.495232] Reading config from file /home/benwibking/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/build_environment.py:1003 ==> [2023-11-03-13:16:16.510605] Adding env modifications for patchelf
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.528823] Reading config from file /home/benwibking/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-11-03-13:16:16.542596] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=aarch64
lib/spack/spack/bootstrap/_common.py:223 ==> [2023-11-03-13:16:16.543033] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=aarch64
lib/spack/spack/bootstrap/core.py:380 ==> [2023-11-03-13:16:16.543108] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:78 ==> [2023-11-03-13:16:16.550435] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=aarch64 ^python@3.12/er73owosuqfmmkxvuw3f7sqnvvj6s4xp" provides the "clingo" Python module
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.550667] Reading config from file /home/benwibking/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.553829] Reading config from file /home/benwibking/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.574914] Reading config from file /home/benwibking/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.587819] Reading config from file /home/benwibking/.spack/packages.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.636322] Reading config from file /home/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:16.645303] Reading config from file /home/benwibking/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:988 ==> [2023-11-03-13:16:18.257564] Reading config from file /home/benwibking/.spack/linux/compilers.yaml
lib/spack/spack/cmd/install.py:441 ==> [2023-11-03-13:16:36.106008] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")
lib/spack/spack/main.py:1025 ==> [2023-11-03-13:16:36.106102] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")
lib/spack/spack/error.py:52 ==> [2023-11-03-13:16:36.107207] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")
Traceback (most recent call last):
  File "/home/benwibking/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/spec.py", line 2987, in concretize
    self._new_concretize(tests)
  File "/home/benwibking/spack/lib/spack/spack/spec.py", line 2960, in _new_concretize
    result.raise_if_unsat()
  File "/home/benwibking/spack/lib/spack/spack/solver/asp.py", line 505, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/benwibking/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/benwibking/spack/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/cmd/install.py", line 437, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benwibking/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit%gcc@11.4.0+gui~mfem+mpi~silo ^mesa@21.2.5+opengl ^python@3.7.7+shared ^qt%gcc@11.4.0 ^vtk@8.1.0 is unsatisfiable, errors are:
    internal_error("Build version weight used for reused package")
    internal_error("Reuse version weight used for build package")
    internal_error("Reused OS incompatible with build OS")
```

### Information on your system

* **Spack:** 0.21.0.dev0 (668a5b45e5ca5b5c16ea042d0121c5a958564089)
* **Python:** 3.12.0
* **Platform:** linux-fedora_asahi_remix39-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I think this was solved by #41061 On develop I get:
![Screenshot from 2023-11-14 15-32-09](https://github.com/spack/spack/assets/4199709/0312b7af-8ae9-47e0-b0f7-81e19ee39d3e)

which seems to suggest that the request of using `python@3.7.7` is the issue.

**Comment by alalazo** [comment]
@becker33 I think we can improve on the displayed chains, since the only incompatibility here seems in Item 7
