### ISSUE TITLE
Unclear error message for a typo in a depends_on directive

### ISSUE THREAD

**Issue by bvanessen** [LLNL/spack#41059]
### Steps to reproduce

On the `develop-2023-11-12` tag

This command fails
```console
spack solve lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a
```

this command succeeds
```console
spack solve lbann@develop+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a
```

### Error message

```console
lbannusr@tioga11 [~] %> spack solve lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a                                                                         
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a is unsatisfiable
```

```console
lbannusr@tioga11 [~] %> spack -d solve lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a
==> [2023-11-13-17:51:56.490179] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/defaults/config.yaml
==> [2023-11-13-17:51:56.529587] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/config.yaml
==> [2023-11-13-17:51:56.550048] Imported solve from built-in commands
==> [2023-11-13-17:51:56.550929] Imported solve from built-in commands
==> [2023-11-13-17:51:56.555430] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/defaults/concretizer.yaml
==> [2023-11-13-17:51:56.565306] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/defaults/repos.yaml
==> [2023-11-13-17:51:59.635684] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/defaults/packages.yaml
==> [2023-11-13-17:52:00.936343] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/upstreams.yaml
==> [2023-11-13-17:52:00.938638] DATABASE LOCK TIMEOUT: 60s
==> [2023-11-13-17:52:00.938702] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-11-13-17:52:00.972296] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/defaults/mirrors.yaml
==> [2023-11-13-17:52:07.295806] Reading config from file /g/g14/lbannusr/spack_repos/spack_test.git/etc/spack/compilers.yaml
==> [2023-11-13-17:52:49.816725] InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a is unsatisfiable
==> [2023-11-13-17:52:49.817881] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a is unsatisfiable
Traceback (most recent call last):
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/main.py", line 1064, in main
    return _main(argv)
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args.command, env_format_error)
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/main.py", line 1047, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/cmd/solve.py", line 192, in solve
    _process_result(result, show, required_format, kwargs)
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/cmd/solve.py", line 94, in _process_result
    result.raise_if_unsat()
  File "/g/g14/lbannusr/spack_repos/spack_test.git/lib/spack/spack/solver/asp.py", line 513, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lbann@develop%rocmcc@5.6.0+deterministic+distconv+numpy+rocm+unit_tests+vision amdgpu_target=gfx90a is unsatisfiable
lbannusr@tioga11 [~] %> 
```

### Information on your system

```console
develop-2023-11-12

lbannusr@tioga11 [~] %> spack debug report
* **Spack:** 0.22.0.dev0 (15dcd3c65c6bbf36127c4cc4d0ed767c14d396b2)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I ~can~ can't reproduce on:

* **Spack:** 0.22.0.dev0 (8a8dcb9479add8fefaa6ecf3beb74cfe9b73d193)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

Do you have any specific configuration that is missing in the report?

**Comment by bvanessen** [comment]
@alalazo I don't think so.  Do you need anything else?

**Comment by alalazo** [comment]
Apologies, I wrote the opposite of what I meant above.

**Comment by scheibelp** [comment]
[reproducer-11-15-23.txt](https://github.com/spack/spack/files/13369327/reproducer-11-15-23.txt)

I have uploaded an environment (attached) which allowed me to reproduce this error

This environment concretizes for me using f6b23b4653c73f60e826086154cad3040c1b61a7 (thanks to @bvanessen who did some testing of different commits) from November 5th and more specifically bisection identifies b5538960c325a849bddc35506e4c219cee40a1d8

**Comment by alalazo** [comment]
Thanks @scheibelp I could reproduce on 

* **Spack:** 0.22.0.dev0 (2f24aeb7f690a7cc73996479b0028a273e91d9df)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-11-16 08-46-06](https://github.com/spack/spack/assets/4199709/548c3496-8b2c-4161-a1b4-884188de2a0c)

Trying to check if this is indeed a bug.

**Comment by alalazo** [comment]
I can reduce the issue to:
```console
$ spack spec lbann ^protobuf@3.21.12
```
Applying this diff:
```diff
diff --git a/lib/spack/spack/solver/asp.py b/lib/spack/spack/solver/asp.py
index 806bbac28f..16838ea317 100644
--- a/lib/spack/spack/solver/asp.py
+++ b/lib/spack/spack/solver/asp.py
@@ -713,6 +713,7 @@ def _get_cause_tree(
         (condition_id, set_id) in which the latter idea means that the condition represented by
         the former held in the condition set represented by the latter.
         """
+        seen = set(seen)
         seen.add(cause)
         parents = [c for e, c in condition_causes if e == cause and c not in seen]
         local = "required because %s " % conditions[cause[0]]
diff --git a/lib/spack/spack/solver/concretize.lp b/lib/spack/spack/solver/concretize.lp
index d5f24ddc3b..5c256f7145 100644
--- a/lib/spack/spack/solver/concretize.lp
+++ b/lib/spack/spack/solver/concretize.lp
@@ -246,7 +246,7 @@ possible_version_weight(node(ID, Package), Weight)
 
 % If there is at least a version that satisfy the constraint, impose a lower
 % bound on the choice rule to avoid false positives with the error below
-1 { attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
+{ attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
   :- attr("node_version_satisfies", node(ID, Package), Constraint),
      pkg_fact(Package, version_satisfies(Constraint, _)),
      internal_error("must choose a single version to satisfy version constraints").
```
I obtained the following error:
```
$ spack spec lbann ^protobuf@3.21.12
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'protobuf@3.21.12'
   2. Cannot satisfy 'protobuf@3.21.12'
        required because lbann ^protobuf@3.21.12 requested from CLI 
   3. Cannot satisfy 'protobuf@3.10.0:3.21.12' and 'protobuf@3.21.12
        required because lbann depends on protobuf@3.10.0:3.21.12+shared 
          required because lbann ^protobuf@3.21.12 requested from CLI 
        required because lbann ^protobuf@3.21.12 requested from CLI 
   4. Cannot satisfy 'protobuf@3.10' and 'protobuf@3.21.12
        required because py-protobuf depends on protobuf@3.10 when @3.10+cpp 
          required because lbann depends on py-protobuf@3.10.0:4.21.12+cpp when +pfe 
            required because lbann ^protobuf@3.21.12 requested from CLI 
        required because lbann ^protobuf@3.21.12 requested from CLI 
```
The issue seems to be the pinned version of protobuf. I'm trying to understand where do we have a request for `@3.10`

**Comment by alalazo** [comment]
There is a typo in `lbann`:
```python
depends_on("zlib-api", when="^protobuf@3.11:")
```
Note the extra `^` sigil. So, this is strictly not a bug imo, but I'll leave it open because we can improve error reporting and auditing to make it easier to debug.
