### ISSUE TITLE
Deficient error message on concretization failure

### ISSUE THREAD

**Issue by greenc-FNAL** [LLNL/spack#41141]
### Steps to reproduce

```console
spack -d --timestamp install gobject-introspection@1.49.2 ^glib build_system=autotools
```

See https://spackpm.slack.com/archives/C03CY91JG3A/p1700238441855299 for background.

Problems with the error message (see below for error text):

1. Missing close-quotes:
   ```console
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
   ```
1. Confusing empty `[]`:
   ```console
   required because glib variant build_system value autotools when [, , ]
   ```
1. Confusing claim for cause: on its face, the simultaneous requirements `glib@2.49.2:` and `glib@:2.57` are eminently satisfiable, yet the concretizer claims this is not possible.

### Error message

```console
$ spack -d --timestamp install gobject-introspection@1.49.2 ^glib build_system=autotools
==> [2023-11-17-10:58:59.708485] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/config.yaml
==> [2023-11-17-10:58:59.746661] Imported install from built-in commands
==> [2023-11-17-10:58:59.759549] Imported install from built-in commands
==> [2023-11-17-10:58:59.763280] DATABASE LOCK TIMEOUT: 60s
==> [2023-11-17-10:58:59.763360] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-11-17-10:58:59.763569] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/bootstrap.yaml
==> [2023-11-17-10:58:59.773543] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/repos.yaml
==> [2023-11-17-10:58:59.777057] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-11-17-10:58:59.777438] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/bootstrap.yaml
==> [2023-11-17-10:58:59.785428] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults
==> [2023-11-17-10:58:59.785470] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/linux
==> [2023-11-17-10:58:59.785515] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/greenc/.spack/bootstrap/config
==> [2023-11-17-10:58:59.785537] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/greenc/.spack/bootstrap/config/linux
==> [2023-11-17-10:58:59.786473] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/config.yaml
==> [2023-11-17-10:58:59.813689] Reading config from file /home/greenc/.spack/bootstrap/config/linux/config.yaml
==> [2023-11-17-10:58:59.827243] DATABASE LOCK TIMEOUT: 60s
==> [2023-11-17-10:58:59.827299] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-11-17-10:58:59.827512] Reading config from file /home/greenc/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-11-17-10:58:59.855374] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-11-17-10:58:59.855789] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/bootstrap.yaml
==> [2023-11-17-10:58:59.869757] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-11-17-10:58:59.872861] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/modules.yaml
==> [2023-11-17-10:58:59.886971] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/linux/modules.yaml
==> [2023-11-17-10:58:59.914959] Adding env modifications for patchelf
==> [2023-11-17-10:58:59.969999] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/packages.yaml
==> [2023-11-17-10:59:00.010476] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-11-17-10:59:00.012048] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-11-17-10:59:00.012095] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-11-17-10:59:00.138361] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9/bhqgwuvef354fwuxq7heeighavunpber" provides the "clingo" Python module
==> [2023-11-17-10:59:00.138821] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/concretizer.yaml
==> [2023-11-17-10:59:00.147744] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/repos.yaml
==> [2023-11-17-10:59:00.213582] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/packages.yaml
==> [2023-11-17-10:59:00.261157] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/config.yaml
==> [2023-11-17-10:59:00.288694] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/defaults/mirrors.yaml
==> [2023-11-17-10:59:00.944736] Reading config from file /home/greenc/work/cet-is/sources/Spack/spack/run/etc/spack/compilers.yaml
==> [2023-11-17-10:59:05.408065] SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'glib@:2.57'
   2. Cannot satisfy 'glib@:2.57'
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
        required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
==> [2023-11-17-10:59:05.408218] SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'glib@:2.57'
   2. Cannot satisfy 'glib@:2.57'
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
        required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
==> [2023-11-17-10:59:05.408274] Error: concretization failed for the following reasons:

   1. Cannot satisfy 'glib@:2.57'
   2. Cannot satisfy 'glib@:2.57'
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
        required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
Traceback (most recent call last):
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/spec.py", line 2987, in concretize
    self._new_concretize(tests)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/spec.py", line 2959, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/solver/asp.py", line 3219, in solve
    result, _, _ = self.driver.solve(
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/solver/asp.py", line 997, in solve
    error_handler.raise_if_errors()
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/solver/asp.py", line 823, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'glib@:2.57'
   2. Cannot satisfy 'glib@:2.57'
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
        required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/main.py", line 1064, in main
    return _main(argv)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args.command, env_format_error)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/main.py", line 1047, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/cmd/install.py", line 437, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/home/greenc/work/cet-is/sources/Spack/spack/run/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'glib@:2.57'
   2. Cannot satisfy 'glib@:2.57'
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
   3. Cannot satisfy 'glib@2.49.2:' and 'glib@:2.57
        required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
        required because glib variant build_system value autotools when [, , ] 
          required because gobject-introspection depends on glib@2.49.2: when @1.49.2: 
            required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
          required because gobject-introspection@1.49.2 ^glib build_system=autotools requested from CLI 
```

### Information on your system

* **Spack:** 0.22.0.dev0 (ec8bd38c4e79646af4683659266e1ba2e886e9a9)
* **Python:** 3.9.14
* **Platform:** linux-almalinux9-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by greenc-FNAL** [comment]
@becker33 @alalazo

**Comment by greenc-FNAL** [comment]
More information:

* Editing the `glib` recipe to remove the `deprecated=True` clause from the entry for version `2.56.4` allows the concretization—and subsequent installation—to proceed.

This would suggest that the root cause of the concretization failure is the deprecation of any version that would satisfy `build_system=autotools`. However, this would raise the question of why:
```console
$ spack install gobject-introspection@2.49.2 ^glib@2.56.4
```
fails when I explicitly ask for a deprecated version.

**Comment by alalazo** [comment]
Bug confirmed. The issue is that deprecated versions are not added to the solve, unless explicitly requested via configuration:
```console
$ spack -c config:deprecated:true spec gobject-introspection@1.49.2 ^glib build_system=autotools
```
The diagnostic needs to be improved, since right now it doesn't give hints on the real cause of the unsat concretization.

**Comment by greenc-FNAL** [comment]
> Bug confirmed. The issue is that deprecated versions are not added to the solve, unless explicitly requested via configuration:

Does this mean that you believe the fact that the deprecated versions are not added to the solve is a bug, or just that the diagnostic needs to be improved?

**Comment by alalazo** [comment]
Just that diagnostic need to be improved, the removal of deprecated versions from the solve by default was asked as a bug fix on an inconsistent behavior when developing v0.21.

**Comment by greenc-FNAL** [comment]
Would it be feasible/reasonable to allow `depcrecated: True` as a package-specific directive in `packages.yaml` and associated sections in e.g. `spack.yaml`? That would seem to be at least as appropriate a place as `config.yaml`, and would allow us to avoid the needs of one package disrupting the concretization of the entire package set.
