### ISSUE TITLE
Can't concretize deprecated package

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [LLNL/spack#41179]
### Steps to reproduce

```console
git clone -b releases/v0.21 https://github.com/spack/spack
cd spack/
. share/spack/setup-env.sh
spack env create test
spack env activate test
spack add pango ^harfbuzz@2.3.1
spack concretize
```

### Error message

```console
==> [2023-11-20-09:12:58.676762] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:58.696098] Reading config from file /dev/shm/spack/var/spack/environments/test/spack.yaml
==> [2023-11-20-09:12:58.704737] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:58.723244] Using environment 'test'
==> [2023-11-20-09:12:58.726583] Imported concretize from built-in commands
==> [2023-11-20-09:12:58.727011] Imported concretize from built-in commands
==> [2023-11-20-09:12:58.736038] Reading config from file /dev/shm/spack/etc/spack/defaults/concretizer.yaml
==> [2023-11-20-09:12:58.744233] DATABASE LOCK TIMEOUT: 60s
==> [2023-11-20-09:12:58.744275] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-11-20-09:12:58.744410] Reading config from file /dev/shm/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-11-20-09:12:58.750385] Reading config from file /dev/shm/spack/var/spack/environments/test/spack.yaml
==> [2023-11-20-09:12:58.759211] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:58.777577] Deactivated environment 'test'
==> [2023-11-20-09:12:58.778782] Reading config from file /dev/shm/spack/etc/spack/defaults/repos.yaml
==> [2023-11-20-09:12:58.781172] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-11-20-09:12:58.781421] Reading config from file /dev/shm/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-11-20-09:12:58.787128] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/dev/shm/spack/etc/spack/defaults
==> [2023-11-20-09:12:58.787159] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/dev/shm/spack/etc/spack/defaults/linux
==> [2023-11-20-09:12:58.787183] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/user/.spack/bootstrap/config
==> [2023-11-20-09:12:58.787207] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/user/.spack/bootstrap/config/linux
==> [2023-11-20-09:12:58.787886] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:58.805819] Reading config from file /home/user/.spack/bootstrap/config/linux/config.yaml
==> [2023-11-20-09:12:58.816090] DATABASE LOCK TIMEOUT: 60s
==> [2023-11-20-09:12:58.816134] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-11-20-09:12:58.816342] Reading config from file /home/user/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-11-20-09:12:58.841533] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-11-20-09:12:58.841768] Reading config from file /dev/shm/spack/etc/spack/defaults/bootstrap.yaml
==> [2023-11-20-09:12:58.851471] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-11-20-09:12:58.853251] Reading config from file /dev/shm/spack/etc/spack/defaults/modules.yaml
==> [2023-11-20-09:12:58.863400] Reading config from file /dev/shm/spack/etc/spack/defaults/linux/modules.yaml
==> [2023-11-20-09:12:58.880154] Adding env modifications for patchelf
==> [2023-11-20-09:12:58.920495] Reading config from file /dev/shm/spack/etc/spack/defaults/packages.yaml
==> [2023-11-20-09:12:58.950813] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-11-20-09:12:58.951791] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-11-20-09:12:58.951823] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-11-20-09:12:59.048139] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/t4yf34cuvquqp5xd66zybmcfyhwbdlsf" provides the "clingo" Python module
==> [2023-11-20-09:12:59.048999] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:59.068963] Reading config from file /dev/shm/spack/var/spack/environments/test/spack.yaml
==> [2023-11-20-09:12:59.077726] Reading config from file /dev/shm/spack/etc/spack/defaults/config.yaml
==> [2023-11-20-09:12:59.095849] Using environment 'test'
==> [2023-11-20-09:12:59.095934] Reading config from file /dev/shm/spack/etc/spack/defaults/concretizer.yaml
==> [2023-11-20-09:12:59.101924] Reading config from file /dev/shm/spack/etc/spack/defaults/repos.yaml
==> [2023-11-20-09:12:59.162912] Reading config from file /dev/shm/spack/etc/spack/defaults/packages.yaml
==> [2023-11-20-09:12:59.194983] Reading config from file /dev/shm/spack/etc/spack/defaults/mirrors.yaml
==> [2023-11-20-09:13:03.296971] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'harfbuzz@2.3.1'
   2. Cannot satisfy 'harfbuzz@2.3.1'
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   3. Cannot satisfy 'harfbuzz@3:' and 'harfbuzz@2.3.1
        required because harfbuzz variant build_system value meson when [, , ] 
          required because pango depends on harfbuzz@1.2.3: when @1.41: 
            required because pango ^harfbuzz@2.3.1 requested from CLI 
          required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   4. Cannot satisfy 'harfbuzz@2.6.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   5. Cannot satisfy 'harfbuzz@2.0.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   6. Cannot satisfy 'harfbuzz@1.4.2:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   7. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   8. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.41: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
==> [2023-11-20-09:13:03.297064] Error: concretization failed for the following reasons:

   1. Cannot satisfy 'harfbuzz@2.3.1'
   2. Cannot satisfy 'harfbuzz@2.3.1'
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   3. Cannot satisfy 'harfbuzz@3:' and 'harfbuzz@2.3.1
        required because harfbuzz variant build_system value meson when [, , ] 
          required because pango depends on harfbuzz@1.2.3: when @1.41: 
            required because pango ^harfbuzz@2.3.1 requested from CLI 
          required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   4. Cannot satisfy 'harfbuzz@2.6.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   5. Cannot satisfy 'harfbuzz@2.0.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   6. Cannot satisfy 'harfbuzz@1.4.2:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   7. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   8. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.41: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
Traceback (most recent call last):
  File "/dev/shm/spack/lib/spack/spack/main.py", line 1064, in main
    return _main(argv)
  File "/dev/shm/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args.command, env_format_error)
  File "/dev/shm/spack/lib/spack/spack/main.py", line 1047, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/dev/shm/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/dev/shm/spack/lib/spack/spack/cmd/concretize.py", line 44, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/dev/shm/spack/lib/spack/spack/environment/environment.py", line 1368, in concretize
    return self._concretize_together(tests=tests)
  File "/dev/shm/spack/lib/spack/spack/environment/environment.py", line 1488, in _concretize_together
    *specs_to_concretize, tests=tests
  File "/dev/shm/spack/lib/spack/spack/concretize.py", line 741, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/dev/shm/spack/lib/spack/spack/concretize.py", line 750, in _concretize_specs_together_new
    abstract_specs, tests=kwargs.get("tests", False), allow_deprecated=allow_deprecated
  File "/dev/shm/spack/lib/spack/spack/solver/asp.py", line 3220, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/dev/shm/spack/lib/spack/spack/solver/asp.py", line 997, in solve
    error_handler.raise_if_errors()
  File "/dev/shm/spack/lib/spack/spack/solver/asp.py", line 823, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'harfbuzz@2.3.1'
   2. Cannot satisfy 'harfbuzz@2.3.1'
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   3. Cannot satisfy 'harfbuzz@3:' and 'harfbuzz@2.3.1
        required because harfbuzz variant build_system value meson when [, , ] 
          required because pango depends on harfbuzz@1.2.3: when @1.41: 
            required because pango ^harfbuzz@2.3.1 requested from CLI 
          required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango ^harfbuzz@2.3.1 requested from CLI 
   4. Cannot satisfy 'harfbuzz@2.6.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.6.0: when @1.49: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   5. Cannot satisfy 'harfbuzz@2.0.0:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@2.0.0: when @1.44: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   6. Cannot satisfy 'harfbuzz@1.4.2:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.4.2: when @1.43: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   7. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.42: 
          required because pango ^harfbuzz@2.3.1 requested from CLI 
   8. Cannot satisfy 'harfbuzz@1.2.3:' and 'harfbuzz@2.3.1
        required because pango ^harfbuzz@2.3.1 requested from CLI 
        required because pango depends on harfbuzz@1.2.3: when @1.41: 
          required because pango ^harfbuzz@2.3.1 requested from CLI
```

### Information on your system

```
* **Spack:** 0.22.0.dev0 (868a3c43e4206f864121cdb81f9613ff260a3a3b)
* **Python:** 3.6.8
* **Platform:** linux-centos8-zen3
* **Concretizer:** clingo
```
(note that I have encountered this on multiple systems)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Did you try:
```
spack -c "config:deprecated:true" concretize
```
? With that I get:
![Screenshot from 2023-11-20 19-02-07](https://github.com/spack/spack/assets/4199709/bf9b6f98-6685-459e-bf25-4f1116b4bdc5)

**Comment by AlexanderRichert-NOAA** [comment]
Nope, but that did it, thanks. Maybe a default changed? Anyway, as long as this reflects the desired behavior then please close this.

**Comment by alalazo** [comment]
I think it was this PR in the 0.21.0.dev0 https://github.com/spack/spack/pull/38181, which was considered a bug fix rather than a breaking change (there was an inconsistent behavior between installation and concretization of deprecated versions).
