### ISSUE TITLE
Spack Database Locks - Permission Issue?

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#4122]
Hi

I pulled latest code from develop yesterday and now I am getting the following error when doing "spack find."

```
user@server[~]$ spack find
==> Error: Can't take exclusive lock on read-only file: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock

user@server[~]$ ls -ltr /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock
-rwxr-xr-x 1 root root 27 May  4 08:11 /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock

```

As you can see the lock file is owned by root as is our entire NFS-exported spack installation.  I can run "spack find" as root on a node though the above error happens when ran as another non-root user.

Root owned everything before pulling the latest changes from git so I wanted to make sure that the problem isn't the permissions I have in place.

```
[root@node103 spack]# spack find | head
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
autoconf@2.69
automake@1.15
bamtools@2.4.1
bcftools@1.4
bedtools2@2.26.0
binutils@2.28
binutils@2.28
bison@3.0.4
boost@1.63.0

[root@node103 spack]# ls -ltr /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db
total 160
-rwxr-xr-x 1 root root     27 Apr 28 15:33 prefix_lock
-rw-r--r-- 1 root root 153869 Apr 28 15:44 index.json
-rwxr-xr-x 1 root root     27 May  4 08:20 lock
```

**Comment by JusticeForMikeBrown** [comment]
After changing permissions on the lock file to o+w spack find works.  Though can you confirm this would be recommended?

**Comment by adamjstewart** [comment]
@tgamblin

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart @tgamblin 

I closed this as I am no longer experiencing the issue though it would be nice to know whether changing permissions would be the ideal solution.

**Comment by tgamblin** [comment]
`spack find` is supposed to be a read-only operation and work on RO filesystems (or on directories you don't have permissions for).

This could be one of two things:
1. The DB access part of `spack find` decided that something was amiss with the DB or with some installation directory and

**Comment by JusticeForMikeBrown** [comment]
@tgamblin 

Sure, I did chmod o-w /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock

As non-root user:

```
nonroot@aristotle[~/ldap]$ spack -d find
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> Error: Can't take exclusive lock on read-only file: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock

```

**Comment by JusticeForMikeBrown** [comment]
I am running into issues with database locks:

```
==> Installing gsl
==> Fetching http://mirror.switch.ch/ftp/mirror/gnu/gsl/gsl-2.3.tar.gz
######################################################################## 100.0%
==> Staging archive: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/gsl-2.3-oodluy7yx54aylki2xcehp7js4rljbxm/gsl-2.3.tar.gz
==> Created stage in /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/gsl-2.3-oodluy7yx54aylki2xcehp7js4rljbxm
==> Ran patch() for gsl
==> Building gsl [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Successfully installed gsl
  Fetch: 11.87s.  Build: 59.40s.  Total: 1m 11.27s.
[+] /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/gsl-2.3-oodluy7yx54aylki2xcehp7js4rljbxm
```

**==> Error: Timed out waiting for lock.**

**Comment by JusticeForMikeBrown** [comment]
If I remove world-writable permissions the problem does not go away.

**Comment by JusticeForMikeBrown** [comment]
```

==> Ran patch() for gsl
==> Building gsl [AutotoolsPackage]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/.lock[61945378425127064:1] [Acquiring]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[8736295814517748467:1] [Acquiring]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Installing /tmp/root/spack-stage/spack-stage-Fprbsi/gsl-2.3/spack-build.out to /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.5.4/gsl-2.3-6j5r3a2kd7s6p6trnkrytv3n3im52eih/.spack/build.out
==> Installing /tmp/root/spack-stage/spack-stage-Fprbsi/gsl-2.3/spack-build.env to /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.5.4/gsl-2.3-6j5r3a2kd7s6p6trnkrytv3n3im52eih/.spack/build.env
==> Installing /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/repos/builtin/packages/gsl/package.py to /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.5.4/gsl-2.3-6j5r3a2kd7s6p6trnkrytv3n3im52eih/.spack/repos/builtin/packages/gsl
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE : gsl@2.3%gcc@4.5.4 arch=linux-rhel6-x86_64 /6j5r3a2 [/pbtech_mounts/softlib001/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64/gsl-2.3-gcc-4.5.4-6j5r3a2]
==> Warning: Module file already exists : skipping creation
file : /pbtech_mounts/softlib001/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64/gsl-2.3-gcc-4.5.4-6j5r3a2
spec : gsl@2.3%gcc@4.5.4 arch=linux-rhel6-x86_64
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==>     WRITE : gsl@2.3%gcc@4.5.4 arch=linux-rhel6-x86_64 /6j5r3a2 [/pbtech_mounts/softlib001/apps/EL6/spack/share/spack/dotkit/linux-rhel6-x86_64/gsl-2.3-gcc-4.5.4-6j5r3a2.dk]
==> Warning: Module file already exists : skipping creation
file : /pbtech_mounts/softlib001/apps/EL6/spack/share/spack/dotkit/linux-rhel6-x86_64/gsl-2.3-gcc-4.5.4-6j5r3a2.dk
spec : gsl@2.3%gcc@4.5.4 arch=linux-rhel6-x86_64
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[8736295814517748467:1] [Released]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/.lock[61945378425127064:1] [Released]
==> Successfully installed gsl
  Fetch: 0.01s.  Build: 44.55s.  Total: 44.56s.
[+] /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.5.4/gsl-2.3-6j5r3a2kd7s6p6trnkrytv3n3im52eih
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
```

Error:

```

Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 465, in main
    return _main(command, parser, args, unknown)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 353, in _main
    return_val = command(parser, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/install.py", line 348, in install
    package.do_install(**kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1330, in do_install
    self.spec, spack.store.layout, explicit=explicit
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 86, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 645, in add
    with self.write_transaction():
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 301, in __enter__
    if self._enter() and self._acquire_fn:
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 332, in _enter
    return self._lock.acquire_write(self._timeout)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 221, in acquire_write
    self._lock(fcntl.LOCK_EX, timeout=timeout)   # can raise LockError.
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 137, in _lock
    raise LockError("Timed out waiting for lock.")
llnl.util.lock.LockError: Timed out waiting for lock.

```

**Comment by JusticeForMikeBrown** [comment]
I deleted the lock file and could install GSL.

**Comment by JusticeForMikeBrown** [comment]
Spack find now also works without world-writable permissions so I am closing this issue.

**Comment by Yejashi** [comment]
A little late, but i'm running spack inside a singularity container and i am also getting the read only error when trying 'spack find'.

**Comment by haampie** [comment]
Can you provide a reproducer @Yejashi?

**Comment by Yejashi** [comment]
To preface, i was trying to create a container image for an HPC application. After installing all the necessary dependencies needed for said application within the image, i then tried running it. I initally ran it in sandbox mode, and every thing seemed to be fine. 

Once i ran it in the regular, sif file, mode however, it would give me 
`Apptainer> spack find
==> Error: [Errno 30] Read-only file system: '/opt/spack/opt/spack/.spack-db/lock'`

The same goes when i try to load packages.
`Apptainer> spack load gcc@9.2.0
==> Error: [Errno 30] Read-only file system: '/opt/spack/opt/spack/.spack-db/lock'`

**Comment by spoutn1k** [comment]
Getting the same error in a container (https://oaciss.uoregon.edu/e4s/images/23.05/e4s-oneapi-x86_64-23.05.sif). Interestingly, this only happens on a more recent host with `apptainer@1.1.9`.

```
Singularity> spack --version
0.20.0.dev0 (0dc6c421561a59e2b00b1daf634c1216f843daa0)
Singularity> spack -d find trilinos -o trace
==> [2023-07-18-12:00:13.353843] Imported find from built-in commands
==> [2023-07-18-12:00:13.355409] Imported find from built-in commands
==> [2023-07-18-12:00:13.357669] Reading config from file /spack/etc/spack/defaults/config.yaml
==> [2023-07-18-12:00:13.401028] DATABASE LOCK TIMEOUT: 60s
==> [2023-07-18-12:00:13.401124] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/find.py", line 248, in find
    results = args.specs(**q_args)
  File "/spack/lib/spack/spack/cmd/common/arguments.py", line 90, in _specs
    for s in spack.store.db.query(spec, **kwargs):
  File "/spack/lib/spack/spack/database.py", line 1562, in query
    local_results = set(self.query_local(*args, **kwargs))
  File "/spack/lib/spack/spack/database.py", line 1546, in query_local
    with self.read_transaction():
  File "/spack/lib/spack/llnl/util/lock.py", line 720, in __enter__
    if self._enter() and self._acquire_fn:
  File "/spack/lib/spack/llnl/util/lock.py", line 748, in _enter
    return self._lock.acquire_read(self._timeout)
  File "/spack/lib/spack/llnl/util/lock.py", line 454, in acquire_read
    wait_time, nattempts = self._lock(LockType.READ, timeout=timeout)
  File "/spack/lib/spack/spack/util/lock.py", line 39, in _lock
    return super(Lock, self)._lock(op, timeout)
  File "/spack/lib/spack/llnl/util/lock.py", line 313, in _lock
    self._file = file_tracker.get_fh(self.path)
  File "/spack/lib/spack/llnl/util/lock.py", line 125, in get_fh
    fd = os.open(path, os_mode)
OSError: [Errno 30] Read-only file system: '/spack/opt/spack/.spack-db/lock' 
```
