### ISSUE TITLE
Intel compiler incompatible with `target=x86_64_v3`

### ISSUE THREAD

**Issue by lorisercole** [LLNL/spack#41229]
### Steps to reproduce

I am trying to concretize this environment:
```yaml
spack:
  concretizer:
    unify: when_possible
    targets:
      host_compatible: false
  compilers:
    - compiler:
        spec: gcc@13.2.0
        paths:
          cc:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/bin/gcc
          cxx: /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/bin/g++
          f77: /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/bin/gfortran
          fc:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/bin/gfortran
        flags: {}
        operating_system: almalinux8
        target: x86_64
        modules: []
        environment: {}
        extra_rpaths:
          - /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/lib64
    - compiler:
        spec: intel@2021.10.0
        paths:
          cc:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/intel-oneapi-compilers-2023.2.1-pmsufbfvvfl5llv5mf3zaunuw2eqgd6m/compiler/latest/linux/bin/intel64/icc
          cxx: /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/intel-oneapi-compilers-2023.2.1-pmsufbfvvfl5llv5mf3zaunuw2eqgd6m/compiler/latest/linux/bin/intel64/icpc
          f77: /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/intel-oneapi-compilers-2023.2.1-pmsufbfvvfl5llv5mf3zaunuw2eqgd6m/compiler/latest/linux/bin/intel64/ifort
          fc:  /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/intel-oneapi-compilers-2023.2.1-pmsufbfvvfl5llv5mf3zaunuw2eqgd6m/compiler/latest/linux/bin/intel64/ifort
        flags: {}
        operating_system: almalinux8
        target: x86_64
        modules: []
        environment: {}
        extra_rpaths:
          - /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/intel-oneapi-compilers-2023.2.1-pmsufbfvvfl5llv5mf3zaunuw2eqgd6m/compiler/latest/linux/lib
          # to link most recent libstdc++:
          - /anfhome/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-13.2.0-ond4wfm74x2lrxj7yamnglzwtagpb6dq/lib64
  packages:
    all:
      require: [target=x86_64_v3]
    hpcx-mpi:
      buildable: false
      externals:
        - spec: hpcx-mpi@2.15
          prefix: /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi
  view: false
  specs:
   - xtb@6.6.1%intel ^intel-oneapi-mkl~cluster threads=none
   - xtb@6.6.1%gcc ^intel-oneapi-mkl~cluster threads=none
```
The intel compiler was previously built via spack (`intel-oneapi-compilers@2023.2.1`).

### Error message

```console
==> [2023-11-23-11:13:04.133180] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. NodeArgument(id='0', pkg='xtb') compiler 'intel@2021.10.0' incompatible with 'target=x86_64_v3'
==> [2023-11-23-11:13:04.133281] Error: concretization failed for the following reasons:

   1. NodeArgument(id='0', pkg='xtb') compiler 'intel@2021.10.0' incompatible with 'target=x86_64_v3'
Traceback (most recent call last):
  File "/anfhome/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/anfhome/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/anfhome/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/anfhome/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/anfhome/spack/lib/spack/spack/cmd/concretize.py", line 44, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/anfhome/spack/lib/spack/spack/environment/environment.py", line 1330, in concretize
    return self._concretize_together_where_possible(tests=tests)
  File "/anfhome/spack/lib/spack/spack/environment/environment.py", line 1398, in _concretize_together_where_possible
    for result in solver.solve_in_rounds(specs_to_concretize, tests=tests):
  File "/anfhome/spack/lib/spack/spack/solver/asp.py", line 2990, in solve_in_rounds
    setup, input_specs, reuse=reusable_specs, output=output
  File "/anfhome/spack/lib/spack/spack/solver/asp.py", line 858, in solve
    error_handler.raise_if_errors()
  File "/anfhome/spack/lib/spack/spack/solver/asp.py", line 681, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. NodeArgument(id='0', pkg='xtb') compiler 'intel@2021.10.0' incompatible with 'target=x86_64_v3'
```
NOTE: If instead I just use:
```yaml
  packages:
    all:
      target: [x86_64_v3]
```
the `xtb%intel` package will be concretized with `arch=linux-almalinux8-zen2` (wrong, I am building from a zen2 machine BTW), while `xtb%gcc` will have `arch=linux-almalinux8-x86_64_v3` (correct).

### Information on your system

* **Spack:** 0.21.0.dev0 (a2bbf5ec01ac32ab0383cced936d45ce967daa42)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by lorisercole** [comment]
The reason was an outdated `archspec` package.
Commit 3302b17 introduced `intel` support for `x86_64_v3`, see [here](https://github.com/spack/spack/blame/8ccfe9f710a440a6e0b2f523816d13aa8dac4482/lib/spack/external/archspec/json/cpu/microarchitectures.json#L317-L323).
Thanks to @becker33 for pointing it out!
