### ISSUE TITLE
concretizer internal error: visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#41405]
### Steps to reproduce

```console
~ spack install visit@3.3.3%mpi+gui+osmesa~vtkm ^python@3.8.17+shared ^mesa@21.2.5+opengl ^llvm@11.0.1 ^vtk@8.1.0+osmesa

==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable
```

### Error message

```console
~ spack --debug --stacktrace install visit@3.3.3%mpi+gui+osmesa~vtkm ^python@3.8.17+shared ^mesa@21.2.5+opengl ^llvm@11.0.1 ^vtk@8.1.0+osmesa

lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.450251] Reading config from file /Users/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:121 ==> [2023-12-03-15:50:56.462103] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:121 ==> [2023-12-03-15:50:56.462652] Imported install from built-in commands
lib/spack/spack/database.py:634 ==> [2023-12-03-15:50:56.468287] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2023-12-03-15:50:56.468414] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.468613] Reading config from file /Users/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.489218] Reading config from file /Users/benwibking/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2023-12-03-15:50:56.490937] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.491201] Reading config from file /Users/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2023-12-03-15:50:56.494103] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/benwibking/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2023-12-03-15:50:56.494185] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/Users/benwibking/spack/etc/spack/defaults/darwin
lib/spack/spack/bootstrap/config.py:138 ==> [2023-12-03-15:50:56.494263] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/benwibking/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2023-12-03-15:50:56.494339] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/benwibking/.spack/bootstrap/config/darwin
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.494851] Reading config from file /Users/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.503366] Reading config from file /Users/benwibking/.spack/bootstrap/config/darwin/config.yaml
lib/spack/spack/database.py:634 ==> [2023-12-03-15:50:56.507769] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2023-12-03-15:50:56.507876] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.508573] Reading config from file /Users/benwibking/.spack/bootstrap/config/darwin/compilers.yaml
lib/spack/spack/bootstrap/_common.py:224 ==> [2023-12-03-15:50:56.533579] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %apple-clang target=aarch64
lib/spack/spack/bootstrap/_common.py:224 ==> [2023-12-03-15:50:56.543847] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=aarch64
lib/spack/spack/bootstrap/core.py:380 ==> [2023-12-03-15:50:56.543981] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.544297] Reading config from file /Users/benwibking/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.623611] Reading config from file /Users/benwibking/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.637246] Reading config from file /Users/benwibking/spack/etc/spack/defaults/darwin/packages.yaml
lib/spack/spack/bootstrap/_common.py:78 ==> [2023-12-03-15:50:56.657034] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=aarch64 ^python@3.11/sgf6pgn4ihfcbxutxhevp36n3orfpdkw" provides the "clingo" Python module
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.657704] Reading config from file /Users/benwibking/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.661412] Reading config from file /Users/benwibking/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.696014] Reading config from file /Users/benwibking/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.709055] Reading config from file /Users/benwibking/spack/etc/spack/defaults/darwin/packages.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.770061] Reading config from file /Users/benwibking/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:56.779500] Reading config from file /Users/benwibking/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:989 ==> [2023-12-03-15:50:58.345883] Reading config from file /Users/benwibking/.spack/darwin/compilers.yaml
lib/spack/spack/cmd/install.py:441 ==> [2023-12-03-15:51:10.586601] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable
lib/spack/spack/main.py:1069 ==> [2023-12-03-15:51:10.586693] SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable
lib/spack/spack/error.py:52 ==> [2023-12-03-15:51:10.587770] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable
Traceback (most recent call last):
  File "/Users/benwibking/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/spec.py", line 2987, in concretize
    self._new_concretize(tests)
  File "/Users/benwibking/spack/lib/spack/spack/spec.py", line 2960, in _new_concretize
    result.raise_if_unsat()
  File "/Users/benwibking/spack/lib/spack/spack/solver/asp.py", line 513, in raise_if_unsat
    raise InternalConcretizerError(constraints, conflicts=conflicts)
spack.solver.asp.InternalConcretizerError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/benwibking/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/Users/benwibking/spack/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/cmd/install.py", line 437, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benwibking/spack/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa is unsatisfiable
```

### Information on your system

* **Spack:** 0.22.0.dev0 (88e738c34346031ce875fdd510dd2251aa63dad7)
* **Python:** 3.11.6
* **Platform:** darwin-sonoma-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
There are a lot of issues in the input spec:
```console
==> Error: concretization failed for the following reasons:

   1. Cannot set the required compiler: visit%mpi
   2. vtk: '+osmesa' conflicts with '+qt'
   3. visit: '+gui' conflicts with '+osmesa'
   4. vtk: '+osmesa' conflicts with '+qt'
        required because conflict constraint +qt 
          required because visit depends on vtk@8.1:8+opengl2 
            required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
          required because visit depends on vtk+qt when +gui 
          required because visit depends on vtk+mpi when +mpi 
          required because visit depends on vtk+osmesa when +osmesa 
          required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
        required because conflict is triggered when +osmesa 
          required because visit depends on vtk@8.1:8+opengl2 
            required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
          required because visit depends on vtk+qt when +gui 
          required because visit depends on vtk+mpi when +mpi 
          required because visit depends on vtk+osmesa when +osmesa 
          required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
   5. visit: '+gui' conflicts with '+osmesa'
        required because conflict is triggered when +gui 
          required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
        required because conflict constraint +osmesa 
          required because visit@3.3.3%mpi+gui+osmesa~vtkm ^llvm@11.0.1 ^mesa@21.2.5+opengl ^python@3.8.17+shared ^vtk@8.1.0+osmesa requested explicitly 
```
Tried to concretize with:

* **Spack:** 0.23.0.dev0 (8020a111df142696721bdd2ea64a4e61e548ad4a)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
