### ISSUE TITLE
Fix error message for spack install deprecated package

### ISSUE THREAD

**Issue by tygoetsch** [LLNL/spack#41592]
### Steps to reproduce

`spack install expat@2.4.8` produces an error message that conflicts with the spack documentation on deprecating old versions of packages: https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions

### Error message

Regular Output:
```
$ spack install expat@2.4.8
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI
```

Debug Output:
```
$ spack --debug install expat@2.4.8
==> [2023-12-12-12:16:53.668752] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/config.yaml
==> [2023-12-12-12:16:53.827967] Imported install from built-in commands
==> [2023-12-12-12:16:53.831248] Imported install from built-in commands
==> [2023-12-12-12:16:53.914548] DATABASE LOCK TIMEOUT: 60s
==> [2023-12-12-12:16:53.914856] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-12-12-12:16:53.915903] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/bootstrap.yaml
==> [2023-12-12-12:16:53.966082] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/repos.yaml
==> [2023-12-12-12:16:53.991262] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-12-12-12:16:53.992591] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/bootstrap.yaml
==> [2023-12-12-12:16:54.054845] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/tgoetsch/repos/spack_develop/etc/spack/defaults
==> [2023-12-12-12:16:54.055127] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/tgoetsch/repos/spack_develop/etc/spack/defaults/linux
==> [2023-12-12-12:16:54.055266] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/users/tgoetsch/.spack/bootstrap/config
==> [2023-12-12-12:16:54.055406] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/users/tgoetsch/.spack/bootstrap/config/linux
==> [2023-12-12-12:16:54.058697] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/config.yaml
==> [2023-12-12-12:16:54.161210] Reading config from file /users/tgoetsch/.spack/bootstrap/config/linux/config.yaml
==> [2023-12-12-12:16:54.210363] DATABASE LOCK TIMEOUT: 60s
==> [2023-12-12-12:16:54.210646] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-12-12-12:16:54.211669] Reading config from file /users/tgoetsch/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-12-12-12:16:54.414506] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-12-12-12:16:54.426554] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/bootstrap.yaml
==> [2023-12-12-12:16:54.524619] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-12-12-12:16:54.548263] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/modules.yaml
==> [2023-12-12-12:16:54.650724] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/linux/modules.yaml
==> [2023-12-12-12:16:54.821057] Adding env modifications for patchelf
==> [2023-12-12-12:16:55.140107] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/packages.yaml
==> [2023-12-12-12:16:55.308546] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-12-12-12:16:55.318090] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-12-12-12:16:55.318193] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-12-12-12:16:58.457198] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/prqkzynv2nwko5mktitebgkeumuxkveu" provides the "clingo" Python module
==> [2023-12-12-12:16:58.459175] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/concretizer.yaml
==> [2023-12-12-12:16:58.497514] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/repos.yaml
==> [2023-12-12-12:16:58.777877] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/packages.yaml
==> [2023-12-12-12:16:58.920148] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/config.yaml
==> [2023-12-12-12:16:59.016396] Reading config from file /home/tgoetsch/repos/spack_develop/etc/spack/defaults/mirrors.yaml
==> [2023-12-12-12:17:01.758423] Reading config from file /users/tgoetsch/.spack/linux/compilers.yaml
==> [2023-12-12-12:17:10.482541] SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI
==> [2023-12-12-12:17:10.482756] SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI
==> [2023-12-12-12:17:10.482842] Error: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI
Traceback (most recent call last):
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/spec.py", line 2987, in concretize
    self._new_concretize(tests)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/spec.py", line 2959, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/solver/asp.py", line 3258, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/solver/asp.py", line 997, in solve
    error_handler.raise_if_errors()
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/solver/asp.py", line 823, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/cmd/install.py", line 438, in concrete_specs_from_cli
    args.spec, concretize=True, tests=install_kwargs["tests"]
  File "/home/tgoetsch/repos/spack_develop/lib/spack/spack/cmd/__init__.py", line 232, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: concretization failed for the following reasons:

   1. Cannot satisfy 'expat@2.4.8'
   2. Cannot satisfy 'expat@2.4.8'
        required because expat@2.4.8 requested from CLI
```

### Information on your system

* **Spack:** 0.22.0.dev0 (37cdcc7172adf6347dd6ce08017e0e08916bb2fe)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alecbcs** [comment]
@becker33 ^
