### ISSUE TITLE
Deprecation not behaving like in the docs

### ISSUE THREAD

**Issue by aurianer** [LLNL/spack#42037]
### Steps to reproduce

Example taken from the [docs](https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions)
```
spack install openssl@1.0.1e
```
Fails with a concretization error instead of asking to fetch anyway.
The command with an extra `--deprecated` installs correctly

### Error message

```
$  spack --debug --stacktrace install  openssl@1.0.1e 
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.541648] Reading config from file /home/emily/install/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.577363] Reading config from file /home/emily/.spack/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-10-21:36:27.583853] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-10-21:36:27.585374] Imported install from built-in commands
lib/spack/spack/database.py:645 ==> [2024-01-10-21:36:27.589751] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-01-10-21:36:27.589963] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.590338] Reading config from file /home/emily/install/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.599936] Reading config from file /home/emily/install/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.602493] Reading config from file /home/emily/.spack/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-01-10-21:36:27.604852] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.605363] Reading config from file /home/emily/install/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-01-10-21:36:27.612874] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/emily/install/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-01-10-21:36:27.613073] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/emily/install/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-01-10-21:36:27.613243] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/emily/.spack/cache/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-01-10-21:36:27.613390] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/emily/.spack/cache/bootstrap/config/linux
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.614560] Reading config from file /home/emily/install/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.638233] Reading config from file /home/emily/.spack/cache/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:645 ==> [2024-01-10-21:36:27.650527] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-01-10-21:36:27.650719] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.651249] Reading config from file /home/emily/.spack/cache/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-10-21:36:27.671892] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.672442] Reading config from file /home/emily/install/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:186 ==> [2024-01-10-21:36:27.685800] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.689104] Reading config from file /home/emily/install/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.702248] Reading config from file /home/emily/install/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/build_environment.py:1014 ==> [2024-01-10-21:36:27.722336] Adding env modifications for patchelf
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.774669] Reading config from file /home/emily/install/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-10-21:36:27.807488] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-01-10-21:36:27.808725] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:380 ==> [2024-01-10-21:36:27.808859] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:79 ==> [2024-01-10-21:36:27.919163] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.10/idkenmhnscjlu5gjqhpcqa4h7o2a7aow" provides the "clingo" Python module
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.919707] Reading config from file /home/emily/install/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.926723] Reading config from file /home/emily/install/spack/etc/spack/concretizer.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.928297] Reading config from file /home/emily/install/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.930117] Reading config from file /home/emily/.spack/repos.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:27.976896] Reading config from file /home/emily/install/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:28.007649] Reading config from file /home/emily/.spack/packages.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:28.133484] Reading config from file /home/emily/install/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:28.154798] Reading config from file /home/emily/.spack/config.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:28.156762] Reading config from file /home/emily/install/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1092 ==> [2024-01-10-21:36:28.543556] Reading config from file /home/emily/.spack/linux/compilers.yaml
lib/spack/spack/cmd/install.py:441 ==> [2024-01-10-21:36:32.460641] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'openssl@1.0.1e'
   2. Cannot satisfy 'openssl@1.0.1e'
        required because openssl@1.0.1e requested explicitly 
lib/spack/spack/main.py:1069 ==> [2024-01-10-21:36:32.460818] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'openssl@1.0.1e'
   2. Cannot satisfy 'openssl@1.0.1e'
        required because openssl@1.0.1e requested explicitly 
lib/spack/spack/error.py:52 ==> [2024-01-10-21:36:32.469193] Error: concretization failed for the following reasons:

   1. Cannot satisfy 'openssl@1.0.1e'
   2. Cannot satisfy 'openssl@1.0.1e'
        required because openssl@1.0.1e requested explicitly 
Traceback (most recent call last):
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/emily/install/spack/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/emily/install/spack/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/home/emily/install/spack/lib/spack/spack/cmd/install.py", line 437, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/home/emily/install/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/home/emily/install/spack/lib/spack/spack/spec.py", line 3016, in concretize
    self._new_concretize(tests)
  File "/home/emily/install/spack/lib/spack/spack/spec.py", line 2988, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/emily/install/spack/lib/spack/spack/solver/asp.py", line 3496, in solve
    result, _, _ = self.driver.solve(
  File "/home/emily/install/spack/lib/spack/spack/solver/asp.py", line 1040, in solve
    error_handler.raise_if_errors()
  File "/home/emily/install/spack/lib/spack/spack/solver/asp.py", line 862, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot satisfy 'openssl@1.0.1e'
   2. Cannot satisfy 'openssl@1.0.1e'
        required because openssl@1.0.1e requested explicitly 
```

### Information on your system

```
$  spack debug report
* **Spack:** 0.22.0.dev0 (f552dbd19918b6c928dd482e1de92d920902f1f3)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Hm yeah, at some point we started not putting deprecated versions in the solve altogether, which has the downside of worse error messages.

@alalazo / @becker33 should we restore old behavior or leave it as is and update docs?

**Comment by alalazo** [comment]
We can check if it is feasible to intercept that kind of issue (no version found) in ASP and emit a better error message during post processing.
