### ISSUE TITLE
Cannot add packages config with `any_of` from commandline

### ISSUE THREAD

**Issue by aurianer** [LLNL/spack#42366]
### Steps to reproduce

This errors out:
```
spack config add "packages:all:require:any_of:['%nvhpc','%gcc']"
```
also with:
```
spack config add "packages:all:require:[any_of:['%nvhpc','%gcc']]"
```
whereas this works:
```
spack config add "packages:all:require:['%gcc']"
```
I also tried with double quotes instead of single quotes and tried escaping them.

### Error message

```
$  spack -d --stacktrace config add "packages:all:require:any_of:[\"%nvhpc\",\"%gcc\"]"
lib/spack/spack/config.py:1094 ==> [2024-01-30-10:35:39.835271] Reading config from file /home/emily/install/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1094 ==> [2024-01-30-10:35:39.881880] Reading config from file /home/emily/.spack/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-30-10:35:39.888290] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-01-30-10:35:39.891877] Imported config from built-in commands
lib/spack/spack/config.py:1094 ==> [2024-01-30-10:35:39.893610] Reading config from file /home/emily/.spack/packages.yaml
lib/spack/spack/main.py:1069 ==> [2024-01-30-10:35:39.936367] ConfigFormatError: <unknown file>: {'any_of': ['%nvhpc', '%gcc']} is not valid under any of the given schemas
lib/spack/spack/error.py:52 ==> [2024-01-30-10:35:39.945008] Error: <unknown file>: {'any_of': ['%nvhpc', '%gcc']} is not valid under any of the given schemas
Traceback (most recent call last):
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 1058, in validate
    spack.schema.Validator(schema).validate(test_data)
  File "/home/emily/install/spack/lib/spack/external/_vendoring/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: {'any_of': ['%nvhpc', '%gcc']} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['packages']['properties']['all']['properties']['require']:
    {'oneOf': [{'items': {'oneOf': [{'additionalProperties': False,
                                     'properties': {'any_of': {'items': {'type': 'string'},
                                                               'type': 'array'},
                                                    'message': {'type': 'string'},
                                                    'one_of': {'items': {'type': 'string'},
                                                               'type': 'array'},
                                                    'spec': {'type': 'string'},
                                                    'when': {'type': 'string'}},
                                     'type': 'object'},
                                    {'type': 'string'}]},
                'type': 'array'},
               {'type': 'string'}]}

On instance['packages']['all']['require']:
    {'any_of': ['%nvhpc', '%gcc']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/emily/install/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/emily/install/spack/lib/spack/spack/cmd/config.py", line 591, in config
    action[args.config_command](args)
  File "/home/emily/install/spack/lib/spack/spack/cmd/config.py", line 233, in config_add
    spack.config.add(args.path, scope=scope)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 924, in add
    CONFIG.set(path, new, scope)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 394, in _method
    return method(self, *args, **kwargs)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 695, in set
    self.update_config(section, section_data, scope=scope)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 394, in _method
    return method(self, *args, **kwargs)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 558, in update_config
    scope._write_section(section)
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 157, in _write_section
    validate(validate_data, SECTION_SCHEMAS[section])
  File "/home/emily/install/spack/lib/spack/spack/config.py", line 1064, in validate
    raise ConfigFormatError(e, data, filename, line_number) from e
spack.config.ConfigFormatError: <unknown file>: {'any_of': ['%nvhpc', '%gcc']} is not valid under any of the given schemas
```

### Information on your system

```
$  spack debug report
* **Spack:** 0.22.0.dev0 (dee0f138b853a3ed98cce5533d5fbd2dafd91d24)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
For people reading this, the "workaround" is to edit the YAML file with:
```
$ spack config edit packages
```
:slightly_smiling_face:

**Comment by aurianer** [comment]
My issue is that I was trying to do that from a Dockerfile where I could not directly `config edit`. In that case the workaround is simply to edit the corresponding file from the command line:
```
# package.yaml path to adapt for the scope wanted, here is for site
$ printf "  all:\n    require:\n    - any_of: [\"nvhpc\", \"gcc\"]" >> $SPACK_ROOT/etc/spack/packages.yaml
 ```

**Comment by alalazo** [comment]
In that case you could use a `COPY` statement

**Comment by aurianer** [comment]
Could you elaborate? Not sure I got what you mean :)

**Comment by alalazo** [comment]
You can prepare the `packages.yaml` and use a ` COPY` statement in the Dockerfile. Then, depending on your use case, you can place that `packages.yaml` in a common scope or elsewhere (in which case you just need to use `spack -C <custom-dir>`).
