### ISSUE TITLE
spack edit -f new_package fails

### ISSUE THREAD

**Issue by lyon-fnal** [LLNL/spack#430]
I'm trying to create a new git-based package in spack. Following the documentation I do,

```
bash-4.1$ spack edit -f gccxml
==> Error: Package gccxml not found.
```

The `-f` is supposed to create the `packages.py` file even if the package is new. 

Turning on debug, I get,
```
bash-4.1$ spack -d edit -f gccxml
Traceback (most recent call last):
  File "/Users/lyon/Development/spack/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/Users/lyon/Development/spack/spack/lib/spack/spack/cmd/edit.py", line 127, in edit
    edit_package(name, args.repo, args.namespace, args.force)
  File "/Users/lyon/Development/spack/spack/lib/spack/spack/cmd/edit.py", line 65, in edit_package
    path = repo.filename_for_package_name(name)
  File "/Users/lyon/Development/spack/spack/lib/spack/spack/repository.py", line 321, in filename_for_package_name
    return self.repo_for_pkg(pkg_name).filename_for_package_name(pkg_name)
  File "/Users/lyon/Development/spack/spack/lib/spack/spack/repository.py", line 67, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/Users/lyon/Development/spack/spack/lib/spack/spack/repository.py", line 304, in repo_for_pkg
    raise UnknownPackageError(spec.name)
spack.repository.UnknownPackageError: Package gccxml not found.
```

The `repo_for_pkg` function demands that the package exists. 

The `spack edit -f` feature is a nice one - can it be restored? Thanks!!!  -- Adam Lyon (Fermilab)

**Comment by tgamblin** [comment]
@lyon-fnal: Oops -- recent refactoring to enable external package repositories caused a regression on this.  Can you try the fix I just pushed?

**Comment by alfredo-gimenez** [comment]
I was having this issue too, the fix worked for me :)

**Comment by lyon-fnal** [comment]
Yep - it works now. I appreciate you fixing it so quickly! Thanks -- Adam
