### ISSUE TITLE
Error: concretization produces spec that does not satisfy the request. Possible false positive ?

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#43118]
### Steps to reproduce

With `spack/etc/spack/default/compilers.yaml` defined as:
```yaml
compilers:
- compiler:
    spec: clang@12.0.1.gcc.8.3.1
    paths:
      cc: /usr/tce/packages/clang/clang-12.0.1/bin/clang
      cxx: /usr/tce/packages/clang/clang-12.0.1/bin/clang++
      fc: /usr/tce/packages/xl/xl-2021.09.22/bin/xlf2003_r
      f77: /usr/tce/packages/xl/xl-2021.09.22/bin/xlf_r
    flags:
      cflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      cxxflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      fflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
    operating_system: rhel7
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
```

When running :
```console
spack spec umpire@develop ~shared tests=basic %clang@=12.0.1.gcc.8.3.1 cxxflags=="-fsanitize=address"
```
Spack is failing to concretize while it used to work before commit "55bbb1098436d6ac9d83fea0715a3daa7be02ed3" (https://github.com/spack/spack/pull/42655).
 
I understand it could be that Spack is now warning me that the resulting spec is inconsistent with what I asked, however I cannot tell how.
 
Instead, I suspect that Spack is not able to determine that the resulting spec satisfies the requirement because of the stacking of flags coming from both the compiler definition and the spec itself.

### Error message

```console
$ spack --debug --stacktrace spec umpire@develop ${SPEC}
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:25.137035] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-03-11-03:53:25.239978] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-03-11-03:53:25.241366] Imported spec from built-in commands
lib/spack/spack/database.py:645 ==> [2024-03-11-03:53:25.413057] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-03-11-03:53:25.413602] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:25.420500] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:25.524842] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.152083] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.249444] Reading config from file /g/g91/bernede1/.spack/packages.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.522232] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.576424] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.616952] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-03-11-03:53:31.628813] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.630377] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-03-11-03:53:31.659319] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-03-11-03:53:31.659937] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-03-11-03:53:31.660554] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/g/g91/bernede1/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-03-11-03:53:31.661156] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/g/g91/bernede1/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.664784] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.761303] Reading config from file /g/g91/bernede1/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:645 ==> [2024-03-11-03:53:31.810794] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-03-11-03:53:31.811494] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.825557] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/compilers.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:31.857430] Reading config from file /g/g91/bernede1/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-03-11-03:53:32.030889] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=ppc64le
lib/spack/spack/util/executable.py:219 ==> [2024-03-11-03:53:32.049830] '/usr/tcetmp/bin/patchelf' '--version'
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:32.056175] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:186 ==> [2024-03-11-03:53:32.104983] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=ppc64le'
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:33.888073] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:33.935425] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/build_environment.py:1014 ==> [2024-03-11-03:53:34.196515] Adding env modifications for patchelf
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:34.204423] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-03-11-03:53:34.314895] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=ppc64le
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-03-11-03:53:34.318879] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=ppc64le
lib/spack/spack/bootstrap/core.py:380 ==> [2024-03-11-03:53:34.319282] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:79 ==> [2024-03-11-03:53:34.495387] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=ppc64le ^python@3.7/6wk7qj2hdglt2sjtec4mv7ibsvhw53ge" provides the "clingo" Python module
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:34.496835] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:34.594249] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:34.702042] Reading config from file /g/g91/bernede1/.spack/packages.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:40.480597] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/compilers.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:40.501191] Reading config from file /g/g91/bernede1/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1095 ==> [2024-03-11-03:53:40.647247] Reading config from file /usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/etc/spack/defaults/config.yaml
lib/spack/spack/util/executable.py:219 ==> [2024-03-11-03:53:42.264311] '/usr/tce/packages/clang/clang-12.0.1/bin/clang' '--version'
lib/spack/spack/solver/asp.py:3183 ==> [2024-03-11-03:54:12.048839] UNKNOWN SYMBOL: attr("external_conditions_hold", NodeArgument(id='0', pkg='cmake'), 6)
lib/spack/spack/solver/asp.py:3183 ==> [2024-03-11-03:54:12.049989] UNKNOWN SYMBOL: attr("external_conditions_hold", NodeArgument(id='0', pkg='gmake'), 0)
lib/spack/spack/spec.py:2935 ==> [2024-03-11-03:54:12.069554] Ordered hashes [gmake]: gmake/586/fe5b60d091c33f169740df8cb718bf4259f84528b42435194ffe0dd5b79cd125, gmake/587/ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f
lib/spack/spack/package_base.py:1646 ==> [2024-03-11-03:54:12.090083] Missing a source id for umpire@develop
lib/spack/spack/package_base.py:1646 ==> [2024-03-11-03:54:12.158688] Missing a source id for camp@main
lib/spack/spack/main.py:1069 ==> [2024-03-11-03:54:12.219088] InternalConcretizerError: Internal Spack error: the solver completed but produced specs that do not satisfy the request.
	Unsatisfied input specs:
	Input spec: umpire@develop%clang@=12.0.1.gcc.8.3.1 cxxflags=='-fsanitize=address' ~shared tests=basic
	Candidate spec: umpire@=develop%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' +c~cuda+device_alloc~deviceconst+examples~fortran~ipo~numa~openmp~rocm~shared build_system=cmake build_type=Release generator=make tests=basic arch=linux-rhel7-power9le ^[deptypes=build] blt@=0.5.3%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1'  build_system=generic arch=linux-rhel7-power9le ^[deptypes=build,link] camp@=main%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~cuda~ipo~openmp~rocm~tests build_system=cmake build_type=Release generator=make arch=linux-rhel7-power9le ^[deptypes=build,run] cmake@=3.23.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel7-power9le ^[deptypes=build] gmake@=4.2.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-rhel7-power9le
lib/spack/spack/error.py:52 ==> [2024-03-11-03:54:12.235079] Error: Internal Spack error: the solver completed but produced specs that do not satisfy the request.
	Unsatisfied input specs:
	Input spec: umpire@develop%clang@=12.0.1.gcc.8.3.1 cxxflags=='-fsanitize=address' ~shared tests=basic
	Candidate spec: umpire@=develop%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' +c~cuda+device_alloc~deviceconst+examples~fortran~ipo~numa~openmp~rocm~shared build_system=cmake build_type=Release generator=make tests=basic arch=linux-rhel7-power9le ^[deptypes=build] blt@=0.5.3%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1'  build_system=generic arch=linux-rhel7-power9le ^[deptypes=build,link] camp@=main%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~cuda~ipo~openmp~rocm~tests build_system=cmake build_type=Release generator=make arch=linux-rhel7-power9le ^[deptypes=build,run] cmake@=3.23.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel7-power9le ^[deptypes=build] gmake@=4.2.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-rhel7-power9le
Traceback (most recent call last):
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/spec.py", line 3025, in concretize
    self._new_concretize(tests)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/spec.py", line 2997, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/solver/asp.py", line 3406, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/usr/WS2/bernede1/Umpire/1726526-1709744152/spack-and-build-root/spack/lib/spack/spack/solver/asp.py", line 829, in solve
    "Internal Spack error: the solver completed but produced specs"
spack.solver.asp.InternalConcretizerError: Internal Spack error: the solver completed but produced specs that do not satisfy the request.
	Unsatisfied input specs:
	Input spec: umpire@develop%clang@=12.0.1.gcc.8.3.1 cxxflags=='-fsanitize=address' ~shared tests=basic
	Candidate spec: umpire@=develop%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' +c~cuda+device_alloc~deviceconst+examples~fortran~ipo~numa~openmp~rocm~shared build_system=cmake build_type=Release generator=make tests=basic arch=linux-rhel7-power9le ^[deptypes=build] blt@=0.5.3%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1'  build_system=generic arch=linux-rhel7-power9le ^[deptypes=build,link] camp@=main%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~cuda~ipo~openmp~rocm~tests build_system=cmake build_type=Release generator=make arch=linux-rhel7-power9le ^[deptypes=build,run] cmake@=3.23.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel7-power9le ^[deptypes=build] gmake@=4.2.1%clang@=12.0.1.gcc.8.3.1 cflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' cxxflags=='-fsanitize=address' fflags='--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1' ~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-rhel7-power9le
```
	

### Information on your system

* **Spack:** 0.22.0.dev0 (55bbb1098436d6ac9d83fea0715a3daa7be02ed3)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

### General information

This issue relates to https://github.com/spack/spack/issues/38664

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Isn't this the same as #38664 ? Spack has to combine the flags from the request `cxxflags=="-fsanitize=address"` with those from the compiler. Am I missing other differences?

**Comment by adrienbernede** [comment]
@alalazo it is certainly related, @scheibelp asked that I file it and mention #38664. To me, it’s a different use case to verify when the fix comes.

Here are the differences I see:
- #38664 was an issue happening only in the context of environments.
- The present issue wasn’t _visible_ (we might say it was "tolerated") before #42655 was merged.

Admittedly, I thought it was slightly different also in the fact that it’s happening with a tag passed with the "==" syntax. But it turns out I have only one job with "flag stacking", so, yeah, it’s the same symptoms, but now expanding outside the context of environments.

In the end, if you consider those to be the same issue, I don’t mind merging them, as long as both contexts are covered.
