### ISSUE TITLE
Installation issue: valgrind

### ISSUE THREAD

**Issue by tlivolsi** [LLNL/spack#43278]
### Steps to reproduce the issue

```console
[svcbuilder@ilogin1 valgrind]$ spack spec -I valgrind~mpi %aocc@4.1.0 target=zen3
Input spec
--------------------------------
 -   valgrind%aocc@4.1.0~mpi arch=None-None-zen3

Concretized
--------------------------------
 -   valgrind@3.20.0%aocc@4.1.0+boost~mpi+only64bit~ubsan build_system=autotools libs=shared,static arch=linux-rhel8-zen3
[+]      ^boost@1.84.0%aocc@4.1.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test+thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=a440f96 visibility=hidden arch=linux-rhel8-zen3
[e]      ^gmake@4.2.1%aocc@4.1.0~guile build_system=autotools patches=ca60bd9,fe5b60d arch=linux-rhel8-zen3
...
```

### Error message

<details><summary>Error message</summary>

<pre>
[svcbuilder@ilogin1 spack]$ spack install valgrind~mpi %aocc@4.1.0 target=zen3
[+] /gpfs/fs1/soft/improv/software/spack-built/linux-rhel8-zen3/aocc-4.1.0/boost-1.84.0-e4z74wl
[+] /usr (external gmake-4.2.1-yvifmwuvnio5uqiq6ue4xnwxsf6pv7i4)
==> Installing valgrind-3.20.0-g5ussz5pdfabcmwei3wfcshn4awu47un [3/3]
==> No binary for valgrind-3.20.0-g5ussz5pdfabcmwei3wfcshn4awu47un found: installing from source
==> Using cached archive: /gpfs/fs1/soft/improv/spack/var/spack/cache/_source-cache/archive/85/8536c031dbe078d342f121fa881a9ecd205cb5a78e639005ad570011bdb9f3c6.tar.bz2
==> Ran patch() for valgrind
==> valgrind: Executing phase: 'autoreconf'
==> valgrind: Executing phase: 'configure'
==> valgrind: Executing phase: 'build'
==> valgrind: Executing phase: 'install'
Process Process-1:
Traceback (most recent call last):
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4211, in __getitem__
    (x for x in order() if (not x.virtual) and x.package.provides(name)),
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/build_environment.py", line 1115, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/installer.py", line 2475, in build_process
    return installer.run()
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/installer.py", line 2352, in run
    spack.hooks.post_install(self.pkg.spec, self.explicit)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/hooks/__init__.py", line 67, in __call__
    hook(*args, **kwargs)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/hooks/module_file_generation.py", line 37, in post_install
    _for_each_enabled(spec, "write", explicit)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/hooks/module_file_generation.py", line 29, in _for_each_enabled
    getattr(generator, method_name)()
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/modules/common.py", line 912, in write
    if not overwrite and os.path.exists(self.layout.filename):
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/modules/lmod.py", line 279, in filename
    f"{self.use_name}.{self.extension}",  # file name
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/modules/common.py", line 577, in use_name
    name = self.spec.format_path(projection)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4589, in format_path
    fs.polite_filename(self.format(x)) for x in input_path_components
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4589, in <listcomp>
    fs.polite_filename(self.format(x)) for x in input_path_components
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4529, in format
    write_attribute(self, attribute, color)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4425, in write_attribute
    current = self[dep]
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4215, in __getitem__
    raise KeyError(f"No spec with name {name} in {self}")
KeyError: 'No spec with name mpi in valgrind@=3.20.0%aocc@=4.1.0+boost~mpi+only64bit~ubsan build_system=autotools libs=shared,static arch=linux-rhel8-zen3 ^[deptypes=build,link] boost@=1.84.0%aocc@=4.1.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test+thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=a440f96 visibility=hidden arch=linux-rhel8-zen3 ^[deptypes=build] gmake@=4.2.1%aocc@=4.1.0~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-rhel8-zen3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4211, in __getitem__
    (x for x in order() if (not x.virtual) and x.package.provides(name)),
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/build_environment.py", line 1132, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/build_environment.py", line 1340, in get_package_context
    func = getattr(obj, tb.tb_frame.f_code.co_name, "")
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/modules/common.py", line 577, in use_name
    name = self.spec.format_path(projection)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4589, in format_path
    fs.polite_filename(self.format(x)) for x in input_path_components
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4589, in <listcomp>
    fs.polite_filename(self.format(x)) for x in input_path_components
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4529, in format
    write_attribute(self, attribute, color)
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4425, in write_attribute
    current = self[dep]
  File "/gpfs/fs1/soft/improv/spack/lib/spack/spack/spec.py", line 4215, in __getitem__
    raise KeyError(f"No spec with name {name} in {self}")
KeyError: 'No spec with name mpi in valgrind@=3.20.0%aocc@=4.1.0+boost~mpi+only64bit~ubsan build_system=autotools libs=shared,static arch=linux-rhel8-zen3 ^[deptypes=build,link] boost@=1.84.0%aocc@=4.1.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test+thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=a440f96 visibility=hidden arch=linux-rhel8-zen3 ^[deptypes=build] gmake@=4.2.1%aocc@=4.1.0~guile build_system=generic patches=ca60bd9,fe5b60d arch=linux-rhel8-zen3'
==> Error: Failed to install valgrind due to InstallError: The process has stopped unexpectedly (exit 1)
</pre></details>

### Information on your system

```console
[svcbuilder@ilogin1 spack]$ spack debug report
* **Spack:** 0.22.0.dev0 (f8e70a0c969a7c8c6b918252711ba4ce12fdc417)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/14658951/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14658952/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tlivolsi** [comment]
This was due to a misconfiguration on my end.
