### ISSUE TITLE
`spack ci reproduce-build` doesn't work on macOS

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#43341]
### Steps to reproduce

Pick any recent failing macOS pipeline and try to reproduce it locally:
```console
> spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/10467600/artifacts
==> Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/10467600/artifacts

==> Job ran with the following image: ghcr.io/spack/e4s-ubuntu-18.04:v2021-10-18
checkout_commit: de1f9593c618417b4a3fdd1f7544cb09609408a8
merge_commit: 71bd5f97eac7f5231a4464cd8642547c09bdcb4e
==> Job ran with the following tags: ['macos-ventura', 'apple-clang-15', 'aarch64-macos', 'public']
==> 
To run the docker reproducer:

    - Start the docker container install       $ /Users/Adam/Downloads/test/ci_reproduction/start.sh
```
Although it detects that the job was run on macOS aarch64 with Apple Clang, it downloads an Ubuntu image that obviously does not have Apple Clang installed.

### Error message

```console
> bash /Users/Adam/Downloads/test/ci_reproduction/start.sh
Unable to find image 'ghcr.io/spack/e4s-ubuntu-18.04:v2021-10-18' locally
v2021-10-18: Pulling from spack/e4s-ubuntu-18.04
f46992f278c2: Pull complete 
8a04986b61ce: Pull complete 
2873c1fae810: Pull complete 
Digest: sha256:ecd5b14e4ad6c3d5fdf522fcf7b81ed412dc001d5f5b016431db75195a6dc570
Status: Downloaded newer image for ghcr.io/spack/e4s-ubuntu-18.04:v2021-10-18
...
==> Installing py-kornia-rs-0.1.1-hgmbxj2hrvuo5fj56jw7zs6jxmspor33 [1/1]
==> Error: CompilerAccessError: Compiler 'apple-clang@=15.0.0' has executables that are missing or are not executable: ['/usr/bin/clang', '/usr/bin/clang++', '/opt/homebrew/bin/gfortran-12', '/opt/homebrew/bin/gfortran-12']
Traceback (most recent call last):
  File "/Users/gitlab-runner-1/builds/sjHgqsSH/0/spack/spack/lib/spack/spack/build_environment.py", line 1113, in _setup_pkg_and_run
    pkg, dirty=kwargs.get("dirty", False), context=Context.from_string(context)
  File "/Users/gitlab-runner-1/builds/sjHgqsSH/0/spack/spack/lib/spack/spack/build_environment.py", line 753, in setup_package
    set_compiler_environment_variables(pkg, env_mods)
  File "/Users/gitlab-runner-1/builds/sjHgqsSH/0/spack/spack/lib/spack/spack/build_environment.py", line 319, in set_compiler_environment_variables
    compiler.verify_executables()
  File "/Users/gitlab-runner-1/builds/sjHgqsSH/0/spack/spack/lib/spack/spack/compiler.py", line 398, in verify_executables
    raise CompilerAccessError(self, missing)
spack.compiler.CompilerAccessError: Compiler 'apple-clang@=15.0.0' has executables that are missing or are not executable: ['/usr/bin/clang', '/usr/bin/clang++', '/opt/homebrew/bin/gfortran-12', '/opt/homebrew/bin/gfortran-12']
```

### Information on your system

* **Spack:** 0.22.0.dev0 (446c0f232528ddfde812f084d64b6cbe239c9992)
* **Python:** 3.11.6
* **Platform:** darwin-sonoma-m2
* **Concretizer:** clingo

@scottwittenburg @kwryankrattiger @zackgalbreath @haampie 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by kwryankrattiger** [comment]
This is a known issue. Currently the reproducer does not support reproduction on metal.

This is something that we are interested in implementing so I think it is worth adding to the road map especially since we have more metal-only platforms we are testing (cray/macos/windows).

**Comment by kwryankrattiger** [comment]
There are two issues with macos reproduction:

1. The generated gitlab ci yaml is wrong
2. The reproduction script for meta runners is written as python but contains shell commands.

Th generation bug is related to the `.../configs/darwin/ci.yaml` not being processed correctly, it is supposed to remove the `image` attribute but it is leaving the default. This results in the macos reproducer attempting to run inside an ubuntu container with `apple-clang` in the concrete environment. That is just not going to work.

To hack this locally to do reproducer builds you can hard code ignoring the image detection in the `reproduce_ci_build` ref. `lib/spack/spack/ci.py:1841`

Hotfix patch to disable container reproducer

```diff
@ -1838,7 +1838,7 @@ def reproduce_ci_job(url, work_dir, autostart, gpg_url, runtime):

     job_image = None
     setup_result = False
-    if "image" in job_yaml:
+    if False:
         job_image_elt = job_yaml["image"]
         if "name" in job_image_elt:
             job_image = job_image_elt["name"]
```

The reproduction script issue is less of a problem since it will probably execute the `.py` file as bash since the `process_command` puts the `#!/bin/bash` at the top. But that should also be fixed for cross-platform reproduction on windows on well.

Hotfix patch to enable autostart

```diff
@@ -2000,10 +2000,11 @@ def reproduce_ci_job(url, work_dir, autostart, gpg_url, runtime):
                 ]
             )
     else:
-        process_command("reproducer", entrypoint_script, work_dir, run=False)
+        autostart = autostart and setup_result
+        process_command("reproducer", entrypoint_script, work_dir, run=autostart)

         inst_list.append("\nOnce on the tagged runner:\n\n")
-        inst_list.extent(["    - Run the reproducer script", f"       $ {work_dir}/reproducer.py"])
+        inst_list.extent(["    - Run the reproducer script", f"       $ {work_dir}/reproducer.{platform_script_ext}"])

     if not setup_result:
         inst_list.append("\n    - Clone spack and acquire tested commit")
```

**Comment by kwryankrattiger** [comment]
@adamjstewart have you been able to confirm the reproducer on mac since the fix went in? I don't have a way to test it myself.

**Comment by adamjstewart** [comment]
New bug:
```
> spack -d ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/10646430/artifacts
==> [2024-04-07-14:35:25.594518] Reading config from file /Users/Adam/spack/etc/spack/defaults/config.yaml
==> [2024-04-07-14:35:25.627152] Imported ci from built-in commands
==> [2024-04-07-14:35:25.627771] Imported ci from built-in commands
==> [2024-04-07-14:35:25.628084] Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/10646430/artifacts

==> [2024-04-07-14:35:26.400884] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['spack.lock']
==> [2024-04-07-14:35:26.401467] Find complete: /Users/Adam/Downloads/ci_reproduction ['spack.lock']
==> [2024-04-07-14:35:26.401510] Found lock file in: /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction
==> [2024-04-07-14:35:26.401539] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['*.yaml', '*.yml']
==> [2024-04-07-14:35:26.402465] Find complete: /Users/Adam/Downloads/ci_reproduction ['*.yaml', '*.yml']
==> [2024-04-07-14:35:26.402499] yaml files:
==> [2024-04-07-14:35:26.402521]   /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/spack.yaml
==> [2024-04-07-14:35:26.402541]   /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/cloud-ci-pipeline.yml
==> [2024-04-07-14:35:26.502124] 
/Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/cloud-ci-pipeline.yml is likely your pipeline file
==> [2024-04-07-14:35:26.502160] Relative environment path used by cloud job: jobs_scratch_dir/concrete_environment
==> [2024-04-07-14:35:26.502796] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['install.sh']
==> [2024-04-07-14:35:26.503031] Find complete: /Users/Adam/Downloads/ci_reproduction ['install.sh']
==> [2024-04-07-14:35:26.503068] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['repro.json']
==> [2024-04-07-14:35:26.503263] Find complete: /Users/Adam/Downloads/ci_reproduction ['repro.json']
==> [2024-04-07-14:35:26.503329] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['spack_info.txt']
==> [2024-04-07-14:35:26.503520] Find complete: /Users/Adam/Downloads/ci_reproduction ['spack_info.txt']
==> [2024-04-07-14:35:26.503560] Found job:
==> [2024-04-07-14:35:26.503576] ordereddict([('variables', ordereddict([('CI_GPG_KEY_ROOT', '/etc/protected-runner'), ('CI_JOB_SIZE', 'default'), ('SPACK_DISABLE_LOCAL_CONFIG', '1'), ('SPACK_JOB_SPEC_DAG_HASH', '7q6dbl63cdainoybtrwqdmoc4emxfrje'), ('SPACK_JOB_SPEC_PKG_NAME', 'freetype'), ('SPACK_JOB_SPEC_PKG_VERSION', '2.6.1'), ('SPACK_JOB_SPEC_COMPILER_NAME', 'apple-clang'), ('SPACK_JOB_SPEC_COMPILER_VERSION', '15.0.0'), ('SPACK_JOB_SPEC_ARCH', 'darwin-ventura-aarch64'), ('SPACK_JOB_SPEC_VARIANTS', '+pic+shared build_system=autotools'), ('SPACK_SPEC_NEEDS_REBUILD', 'True'), ('SPACK_CDASH_BUILD_NAME', 'freetype@2.6.1%apple-clang@=15.0.0 hash=7q6dbl63cdainoybtrwqdmoc4emxfrje arch=darwin-ventura-aarch64 (Machine Learning MPS)'), ('SPACK_CDASH_BUILD_STAMP', '20240405-0729-Machine Learning MPS')])), ('before_script', ['export SPACK_USER_CACHE_PATH="${CI_PROJECT_DIR}/_user_cache/"', 'uname -a || true', 'grep -E "vendor|model name" /proc/cpuinfo 2>/dev/null | sort -u || head -n10 /proc/cpuinfo 2>/dev/null || true', 'nproc || true', '. "./share/spack/setup-env.sh"', 'spack --version', 'spack arch', 'cat /proc/loadavg || true', "cat /proc/meminfo | grep 'MemTotal\\|MemFree' || true", 'spack list --count', 'spack env activate --without-view ${SPACK_CONCRETE_ENV_DIR}', 'spack compiler list', 'if [ -n "$SPACK_BUILD_JOBS" ]; then spack config add "config:build_jobs:$SPACK_BUILD_JOBS"; fi', 'mkdir -p ${SPACK_ARTIFACTS_ROOT}/user_data', 'k=$CI_GPG_KEY_ROOT/e4s.gpg; [[ -r $k ]] && spack gpg trust $k', 'k=$CI_GPG_KEY_ROOT/intermediate_ci_signing_key.gpg; [[ -r $k ]] && spack gpg trust $k', 'k=$CI_GPG_KEY_ROOT/spack_public_key.gpg; [[ -r $k ]] && spack gpg trust $k']), ('script', ['spack config blame mirrors', 'spack --color=always --backtrace ci rebuild --tests > >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_out.txt) 2> >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_err.txt >&2)']), ('after_script', ['./bin/spack python ${CI_PROJECT_DIR}/share/spack/gitlab/cloud_pipelines/scripts/common/aggregate_package_logs.spack.py --prefix /home/software/spack:${CI_PROJECT_DIR}/opt/spack --log install_times.json ${SPACK_ARTIFACTS_ROOT}/user_data/install_times.json', 'cat /proc/loadavg || true', "cat /proc/meminfo | grep 'MemTotal\\|MemFree' || true"]), ('id_tokens', ordereddict([('GITLAB_OIDC_TOKEN', ordereddict([('aud', '${OIDC_TOKEN_AUDIENCE}')]))])), ('tags', ['macos-ventura', 'apple-clang-15', 'aarch64-macos', 'public']), ('needs', [ordereddict([('job', 'ml-darwin-aarch64-mps-generate'), ('pipeline', '671257')])]), ('artifacts', ordereddict([('when', 'always'), ('paths', ['jobs_scratch_dir/logs', 'jobs_scratch_dir/reproduction', 'jobs_scratch_dir/tests', 'jobs_scratch_dir/user_data'])])), ('stage', 'stage-6'), ('retry', ordereddict([('max', 2), ('when', ['unknown_failure', 'script_failure', 'api_failure', 'stuck_or_timeout_failure', 'runner_system_failure', 'runner_unsupported', 'stale_schedule', 'archived_failure', 'unmet_prerequisites', 'scheduler_failure', 'data_integrity_failure'])])), ('interruptible', True)])
checkout_commit: 1b86a842ead6e745fa1b0c718d93e673e1e00c84
merge_commit: d70f7c00ceb976d9a727281688e0b0769b3ad4f3
==> [2024-04-07-14:35:26.504317] '/usr/bin/git' 'log' '-1' '1b86a842ead6e745fa1b0c718d93e673e1e00c84'
==> [2024-04-07-14:35:26.516772] Error: Missing commit: 1b86a842ead6e745fa1b0c718d93e673e1e00c84
==> [2024-04-07-14:35:26.516810] Error: Failed to automatically setup the tested version of spack in your local reproduction directory.

    This can happen if the spack you are using to run this command is not a git
    repo, or if it is a git repo, but it does not have the commits needed to
    recreate the tested merge commit.  If you are trying to reproduce a spack
    PR pipeline job failure, try fetching the latest develop commits from
    mainline spack and make sure you have the most recent commit of the PR
    branch in your local spack repo.  Then run this command again.
    Alternatively, you can also manually clone spack if you know the version
    you want to test.
        
==> [2024-04-07-14:35:26.516839] Job ran with the following tags: ['macos-ventura', 'apple-clang-15', 'aarch64-macos', 'public']
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Adam/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1068, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1021, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1051, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/ci.py", line 851, in ci
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/ci.py", line 806, in ci_reproduce
    return spack_ci.reproduce_ci_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/ci.py", line 1925, in reproduce_ci_job
    ["git", "config", "--global", "--add", "safe.directory", mount_as_dir],
                                                             ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'mount_as_dir' where it is not associated with a value
```
Interestingly, if I run this again:
```
> spack -d ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/10646430/artifacts
==> [2024-04-07-14:35:29.267889] Reading config from file /Users/Adam/spack/etc/spack/defaults/config.yaml
==> [2024-04-07-14:35:29.301616] Imported ci from built-in commands
==> [2024-04-07-14:35:29.302218] Imported ci from built-in commands
==> [2024-04-07-14:35:29.302515] Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/10646430/artifacts

==> [2024-04-07-14:35:30.016577] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['spack.lock']
==> [2024-04-07-14:35:30.017200] Find complete: /Users/Adam/Downloads/ci_reproduction ['spack.lock']
==> [2024-04-07-14:35:30.017241] Found lock file in: /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/concrete_environment
==> [2024-04-07-14:35:30.017270] Find (recursive): /Users/Adam/Downloads/ci_reproduction ['*.yaml', '*.yml']
==> [2024-04-07-14:35:30.018277] Find complete: /Users/Adam/Downloads/ci_reproduction ['*.yaml', '*.yml']
==> [2024-04-07-14:35:30.018309] yaml files:
==> [2024-04-07-14:35:30.018330]   /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/concrete_environment/spack.yaml
==> [2024-04-07-14:35:30.018351]   /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/spack.yaml
==> [2024-04-07-14:35:30.018367]   /Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/cloud-ci-pipeline.yml
==> [2024-04-07-14:35:30.127196] 
/Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/reproduction/cloud-ci-pipeline.yml is likely your pipeline file
==> [2024-04-07-14:35:30.127242] Relative environment path used by cloud job: jobs_scratch_dir/concrete_environment
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Adam/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1068, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1021, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1051, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/ci.py", line 851, in ci
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/ci.py", line 806, in ci_reproduce
    return spack_ci.reproduce_ci_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/ci.py", line 1802, in reproduce_ci_job
    shutil.copyfile(lock_file, copy_lock_path)
  File "/Users/Adam/spack/var/spack/environments/default/.spack-env/._view/ixaogr5qu4ydlyufpmjxxogq2k2hitqk/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/concrete_environment/spack.lock' and '/Users/Adam/Downloads/ci_reproduction/jobs_scratch_dir/concrete_environment/spack.lock' are the same file
```

**Comment by kwryankrattiger** [comment]
I configured that I am getting the `configure` script and the `config.guess` copied over, but for some reason the `config.log` is still skipped.

Any thoughts @trws @adamjstewart

**Comment by trws** [comment]
None that are all that useful, it should definitely be there unless it's cleared out for some reason.
