### ISSUE TITLE
Unicode Problems with Python 2.6.9?

### ISSUE THREAD

**Issue by mamelara** [LLNL/spack#4339]
While running spack compiler find on Edison, I came across this error message:
```
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/util/multiproc.py", line 37, in fun
    pipe.send(f(x))
    pipe.send(f(x))
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
    pipe.send(f(x))
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 475, in __init__
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 475, in __init__
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 475, in __init__
    c = SpecParser().parse_compiler(arg)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 3032, in parse_compiler
    self.setup(text)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 168, in setup
    c = SpecParser().parse_compiler(arg)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 3032, in parse_compiler
    self.setup(text)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 168, in setup
    c = SpecParser().parse_compiler(arg)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/spec.py", line 3032, in parse_compiler
    self.setup(text)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 168, in setup
    self.push_tokens(self.lexer.lex(text))
    self.push_tokens(self.lexer.lex(text))
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 103, in lex
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 103, in lex
    self.push_tokens(self.lexer.lex(text))
    tokens = self.lex_word(word)
    tokens = self.lex_word(word)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 96, in lex_word
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 103, in lex
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 96, in lex_word
    raise LexError("Invalid character", word, word.index(remainder))
    raise LexError("Invalid character", word, word.index(remainder))
    tokens = self.lex_word(word)
  File "/global/u2/m/mamelara/spack/lib/spack/spack/parse.py", line 96, in lex_word
LexError: Invalid character
    raise LexError("Invalid character", word, word.index(remainder))
LexError: Invalid character
LexError: Invalid character
```

Was confused  because spack compiler find ran fine on Cori and I haven't had this issue before with Edison.

Doing some investigating via print statements led me to this:
```bash
# In def setup in class Parser, shlex.split() line
TEXT= gcc@4.7.2
<type 'unicode'>
['g\x00\x00\x00c\x00\x00\x00c\x00\x00\x00@\x00\x00\x004\x00\x00\x00.\x00\x00\x007\x00\x00\x00.\x00\x00\x002\x00\x00\x00']
```
Checked to see whether a different python would be able to handle it and after module loading spack compiler find worked.

Edison version: 2.6.9
Cori version: 2.7.9

I'm not too familiar with how older (<= 2.6.9) versions of Python handle unicode, or if this is a common problem. It's solved via module loading a more recent python but that shouldn't be necessary. Anyway to fix this with older Python versions?

**Comment by becker33** [comment]
@mamelara does #5033 resolve this without introducing #4355?
