### ISSUE TITLE
Spack-Python scripting broken with SpackCommands

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#43555]
### Steps to reproduce

A basic spack-python script 
``` python
#!/usr/bin/env spack-python

from spack.main import SpackCommand

find = SpackCommand("find")

find()
```
fails on develop. Reverting #41789 allows it to run again.

### Error message

``` console
$ ./failure.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/psakiev/scratch/exawind-manager/scripts/failure.py", line 7, in <module>
    find()
  File "/Users/psakiev/scratch/exawind-manager/spack/lib/spack/spack/main.py", line 720, in __call__
    with log_output(out, echo=True):
  File "/Users/psakiev/scratch/exawind-manager/spack/lib/spack/llnl/util/tty/log.py", line 566, in __enter__
    self.process.start()
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/psakiev/bin/._spack-editor/ihytzstzzfgpzbduifmmfbsx3aexejws/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
==> Error:
```

### Information on your system

* **Spack:** 0.22.0.dev0 (fb6741cf859424bb6e7c0973ea8e47e390ecad12)
* **Python:** 3.10.12
* **Platform:** darwin-sonoma-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by trws** [comment]
After some digging into this, I think it worked before because the script wasn't actually run as a true "__main__" module. Otherwise this should have been a failure from the start.  With multiprocessing used in `log.py` anything that runs back to that point at the top level unprotected by `if __name__ == '__main__':` should blow up this way.  It's a change in behavior, but I'm not sure the new behavior is wrong since it's what would happen if you run the same script with `python` with the correct import paths:

```
❯ PYTHONPATH=./lib/spack:./lib/spack/external:./lib/spack/external/_vendoring python3 ./test-script.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/test-script.py", line 6, in <module>
    find()
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/lib/spack/spack/main.py", line 720, in __call__
    with log_output(out, echo=True):
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/lib/spack/llnl/util/tty/log.py", line 566, in __enter__
    self.process.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

Traceback (most recent call last):
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/./test-script.py", line 6, in <module>
    find()
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/lib/spack/spack/main.py", line 720, in __call__
    with log_output(out, echo=True):
  File "/Users/scogland1/Workspace/dir.noindex/Repos/spack/lib/spack/llnl/util/tty/log.py", line 643, in __exit__
    string = self.parent_pipe.recv()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
```

**Comment by psakievich** [comment]
Thanks @trws. Your diagnosis makes sense to me. It seems that just making sure all `spack.main.SpackCommands` are called from inside `__main__` is sufficient to resolve this issue functionally.

``` python
#!/usr/bin/env spack-python

from spack.main import SpackCommand

find = SpackCommand("find")

if __name__=="__main__":
    find()
```
At a minimum we should update the documentation. It would be nice to have a way to detect this and give a better error thou.
