### ISSUE TITLE
Reuse can prevent specs from concretizing

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#43663]
### Steps to reproduce

Using the following db:

[spack-db.develop.7e14ff806a.2024-04-15-151420.tar.gz](https://github.com/spack/spack/files/14979489/spack-db.develop.7e14ff806a.2024-04-15-151420.tar.gz)

The following fails:

```console
> spack spec gdal+mdb
```
whereas the following succeed:
```console
> spack spec gdal@3.4+mdb
> spack spec --fresh gdal+mdb
```
It seems like reuse is preventing clingo from choosing an older version of GDAL.

### Error message

```console
> spack -d spec gdal+mdb
...
Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1068, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1021, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 1051, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/Users/Adam/spack/lib/spack/spack/spec.py", line 2997, in concretize
    self._new_concretize(tests)
  File "/Users/Adam/spack/lib/spack/spack/spec.py", line 2970, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/solver/asp.py", line 3548, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/solver/asp.py", line 853, in solve
    raise InternalConcretizerError(
spack.solver.asp.InternalConcretizerError: Internal Spack error: the solver completed but produced specs that do not satisfy the request. Please report a bug at https://github.com/spack/spack/issues
	Unsatisfied input specs:
	Input spec: gdal+mdb
	Candidate spec: gdal@=3.8.3...
```

### Information on your system

* **Spack:** 0.22.0.dev0 (7e14ff806a63bf2af2a07f49fc13ed5b111a76ac)
* **Python:** 3.11.6
* **Platform:** darwin-sonoma-m2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
The issue is that `gdal@=3.8.3` is reused by the solver, which lacks `+mdb` because it's a conditional variant `when="@:3.4"`. Will investigate why that happens.
