### ISSUE TITLE
Spack does not access user-configured mirrors.

### ISSUE THREAD

**Issue by LorienLV** [LLNL/spack#43718]
### Steps to reproduce

I am trying to use spack mirrors to install gcc@10.3.0 in a server without outgoing internet access. However, it seems that spack does not access user-configured mirrors when performing the install command. I am using spack v0.21.2, and I have also tried v0.21.0 with the same result.

I have created the mirror in my local computer with `spack mirror create -D gcc@10.3.0` and copied it to the server. In the server, I do (I suppress sensible information from the output):
```console
$spack mirror add local-mirror file://$HOME/spack-offline-mirror
$spack mirror list
local-mirror [sb] file://$HOME/spack-offline-mirror
spack-public [s ] https://mirror.spack.io
```

When I execute `spack install gcc@10`, spack reads `$HOME/spack/etc/spack/defaults/mirrors.yaml` but it does not read `$HOME/.spack/mirrors.yaml`, so it never accesses the local mirror. The installation eventually fails due to time-outs trying to access the unreachable remote mirrors.

### Error message

```console 
$spack --debug install gcc@10
==> [2024-04-18-14:18:12.370964] Reading config from file $HOME/spack/etc/spack/defaults/config.yaml
==> [2024-04-18-14:18:12.404925] Imported install from built-in commands
==> [2024-04-18-14:18:12.405897] Imported install from built-in commands
==> [2024-04-18-14:18:12.408722] DATABASE LOCK TIMEOUT: 60s
==> [2024-04-18-14:18:12.408785] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-04-18-14:18:12.408943] Reading config from file $HOME/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-04-18-14:18:12.427396] Reading config from file $HOME/spack/etc/spack/defaults/repos.yaml
==> [2024-04-18-14:18:12.430067] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-04-18-14:18:12.430371] Reading config from file $HOME/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-04-18-14:18:12.436288] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=$HOME/spack/etc/spack/defaults
==> [2024-04-18-14:18:12.436333] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=$HOME/spack/etc/spack/defaults/linux
==> [2024-04-18-14:18:12.436355] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=$HOME/.spack/bootstrap/config
==> [2024-04-18-14:18:12.436371] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=$HOME/.spack/bootstrap/config/linux
==> [2024-04-18-14:18:12.437074] Reading config from file $HOME/spack/etc/spack/defaults/config.yaml
==> [2024-04-18-14:18:12.455937] Reading config from file $HOME/.spack/bootstrap/config/linux/config.yaml
==> [2024-04-18-14:18:12.465920] DATABASE LOCK TIMEOUT: 60s
==> [2024-04-18-14:18:12.465977] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-04-18-14:18:12.466159] Reading config from file $HOME/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-04-18-14:18:12.496374] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2024-04-18-14:18:12.496639] Reading config from file $HOME/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-04-18-14:18:12.506834] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2024-04-18-14:18:12.507338] Bootstrapping patchelf from pre-built binaries
==> [2024-04-18-14:18:12.509696] Reading config from file $HOME/spack/etc/spack/defaults/mirrors.yaml
==> [2024-04-18-14:18:12.511609] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/index.json
==> [2024-04-18-14:18:52.658204] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:18:52.660911] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2024-04-18-14:18:52.661460] Bootstrapping patchelf from pre-built binaries
==> [2024-04-18-14:18:52.664115] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/index.json
==> [2024-04-18-14:19:32.789178] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:19:32.791585] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2024-04-18-14:19:32.792031] Bootstrapping patchelf@0.13.1: %gcc target=x86_64 from sources
==> [2024-04-18-14:19:33.071882] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.072124] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.072295] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.072654] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.076001] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.076213] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.077046] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.077549] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:33.115017] '/usr/bin/bison' '--version'
==> [2024-04-18-14:19:33.115349] '/usr/bin/gawk' '--version'
==> [2024-04-18-14:19:33.116495] '/usr/bin/git' '--version'
==> [2024-04-18-14:19:33.178870] Reading config from file $HOME/spack/etc/spack/defaults/packages.yaml
==> [2024-04-18-14:19:59.898549] patchelf applying constraint gmake
==> [2024-04-18-14:19:59.903853] patchelf applying constraint gmake
==> [2024-04-18-14:19:59.920916] [BOOTSTRAP] Try installing 'patchelf@0.13.1: %gcc target=x86_64' from sources
==> [2024-04-18-14:19:59.927636] Initializing the build queue from the build requests
==> [2024-04-18-14:19:59.927679] Initializing the build queue for patchelf
==> [2024-04-18-14:19:59.930690] Pkg id gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 has the following dependents:
==> [2024-04-18-14:19:59.930730] - patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7
==> [2024-04-18-14:19:59.934049] Requeueing a build task for gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 with status 'queued'
==> [2024-04-18-14:19:59.934641] Pkg id patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7 has the following dependents:
==> [2024-04-18-14:19:59.935321] Requeueing a build task for patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7 with status 'queued'
==> [2024-04-18-14:19:59.935361] Ensure all dependencies know all dependents across specs
==> [2024-04-18-14:19:59.941370] Processing gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7: task=priority=0, status=dequeued, start=0, #dependencies=0
==> [2024-04-18-14:19:59.941824] Acquiring a write lock on gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 with timeout 1.000ns
==> [2024-04-18-14:19:59.942001] gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 is now write locked
==> [2024-04-18-14:19:59.943555] Searching for binary cache of gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
==> [2024-04-18-14:19:59.945345] Checking existence of https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json.sig
==> [2024-04-18-14:20:40.082831] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:20:40.082949] URL does not exist: https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json.sig
==> [2024-04-18-14:20:40.083076] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json.sig
==> [2024-04-18-14:20:40.083101] Fetching from https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json.sig failed.
==> [2024-04-18-14:20:40.083588] Checking existence of https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json
==> [2024-04-18-14:21:20.208609] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:21:20.208760] URL does not exist: https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json
==> [2024-04-18-14:21:20.208907] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json
==> [2024-04-18-14:21:20.208934] Fetching from https://mirror.spack.io/build_cache/linux-rhel9-x86_64-gcc-11.3.1-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7.spec.json failed.
==> [2024-04-18-14:21:20.209759] Creating the installation directory $HOME/.spack/bootstrap/store/linux-rhel9-x86_64/gcc-11.3.1/gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
==> [2024-04-18-14:21:20.211843] '/usr/bin/git' '-C' '$HOME/spack' 'rev-parse' 'HEAD'
==> [2024-04-18-14:19:59.943177] Installing gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 [1/2]
==> [2024-04-18-14:21:20.209113] No binary for gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 found: installing from source
==> [2024-04-18-14:21:20.290112] [TOOLCHAIN] MATCH Gcc
==> [2024-04-18-14:21:20.292608] Adding compiler bin/ paths: $HOME/spack/lib/spack/env $HOME/spack/lib/spack/env/case-insensitive $HOME/spack/lib/spack/env/gcc
==> [2024-04-18-14:21:20.313250] setup_package: grabbing modifications from dependencies
==> [2024-04-18-14:21:20.313309] Adding env modifications for gmake
==> [2024-04-18-14:21:20.313785] setup_package: collected all modifications from dependencies
==> [2024-04-18-14:21:20.313838] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2024-04-18-14:21:20.313989] setup_package: loading compiler modules
==> [2024-04-18-14:21:20.314475] '/usr/bin/g++' '-v' '/scratch/tmp/spack-implicit-link-infoz3o5zjyo/main.c' '-o' '/scratch/tmp/spack-implicit-link-infoz3o5zjyo/output'
==> [2024-04-18-14:21:20.378127] parsing implicit link info
==> [2024-04-18-14:21:20.378322] linker line:  /usr/libexec/gcc/x86_64-redhat-linux/11/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/11/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper -plugin-opt=-fresolution=/scratch/tmp/ccESk8mp.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /scratch/tmp/spack-implicit-link-infoz3o5zjyo/output /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/11/crtbegin.o -L/usr/lib/gcc/x86_64-redhat-linux/11 -L/usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/11/../../.. /scratch/tmp/ccDcslAj.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-redhat-linux/11/crtend.o /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64/crtn.o
==> [2024-04-18-14:21:20.378364] linkdir: /usr/lib/gcc/x86_64-redhat-linux/11
==> [2024-04-18-14:21:20.378383] linkdir: /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64
==> [2024-04-18-14:21:20.378398] linkdir: /lib/../lib64
==> [2024-04-18-14:21:20.378412] linkdir: /usr/lib/../lib64
==> [2024-04-18-14:21:20.378425] linkdir: /usr/lib/gcc/x86_64-redhat-linux/11/../../..
==> [2024-04-18-14:21:20.378449] found raw link dirs: /usr/lib/gcc/x86_64-redhat-linux/11, /usr/lib/gcc/x86_64-redhat-linux/11/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /usr/lib/gcc/x86_64-redhat-linux/11/../../..
==> [2024-04-18-14:21:20.378494] found link dirs: /usr/lib/gcc/x86_64-redhat-linux/11, /usr/lib64, /lib64, /usr/lib
==> [2024-04-18-14:21:20.380163] Checking existence of https://mirror.spack.io/_source-cache/archive/dd/dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3.tar.gz
==> [2024-04-18-14:22:00.540469] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:22:00.540595] URL does not exist: https://mirror.spack.io/_source-cache/archive/dd/dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3.tar.gz
==> [2024-04-18-14:22:00.540741] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/archive/dd/dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3.tar.gz
==> [2024-04-18-14:22:00.540800] Checking existence of https://mirror.spack.io/gmake/gmake-4.4.1.tar.gz
==> [2024-04-18-14:22:40.665854] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:22:40.665997] URL does not exist: https://mirror.spack.io/gmake/gmake-4.4.1.tar.gz
==> [2024-04-18-14:22:40.666154] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/gmake/gmake-4.4.1.tar.gz
==> [2024-04-18-14:22:40.666224] Checking existence of https://ftpmirror.gnu.org/make/make-4.4.1.tar.gz
==> [2024-04-18-14:22:50.701399] Failure reading URL: <urlopen error [Errno 101] Network is unreachable>
==> [2024-04-18-14:22:50.701627] URL does not exist: https://ftpmirror.gnu.org/make/make-4.4.1.tar.gz
==> [2024-04-18-14:22:50.701655] Checking existence of https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz
==> [2024-04-18-14:23:00.736818] Failure reading URL: <urlopen error [Errno 101] Network is unreachable>
==> [2024-04-18-14:23:00.737017] URL does not exist: https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz
==> [2024-04-18-14:23:00.737042] Checking existence of http://ftpmirror.gnu.org/make/make-4.4.1.tar.gz
==> [2024-04-18-14:23:10.898846] Failure reading URL: <urlopen error [Errno 101] Network is unreachable>
==> [2024-04-18-14:23:10.899081] URL does not exist: http://ftpmirror.gnu.org/make/make-4.4.1.tar.gz
==> [2024-04-18-14:23:10.899306] FailedDownloadError: Failed to fetch file from URL: http://ftpmirror.gnu.org/make/make-4.4.1.tar.gz
==> [2024-04-18-14:23:10.899349] Fetching from https://mirror.spack.io/_source-cache/archive/dd/dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3.tar.gz failed.
==> [2024-04-18-14:23:10.899366] Fetching from https://mirror.spack.io/gmake/gmake-4.4.1.tar.gz failed.
==> [2024-04-18-14:23:10.899380] Fetching from https://ftpmirror.gnu.org/make/make-4.4.1.tar.gz failed.
==> [2024-04-18-14:23:10.919699] Error: FetchError: All fetchers failed for spack-stage-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
Traceback (most recent call last):
  File "$HOME/spack/lib/spack/spack/build_environment.py", line 1110, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "$HOME/spack/lib/spack/spack/installer.py", line 2497, in build_process
    return installer.run()
  File "$HOME/spack/lib/spack/spack/installer.py", line 2338, in run
    self.pkg.do_patch()
  File "$HOME/spack/lib/spack/spack/package_base.py", line 1464, in do_patch
    self.do_stage()
  File "$HOME/spack/lib/spack/spack/package_base.py", line 1449, in do_stage
    self.do_fetch(mirror_only)
  File "$HOME/spack/lib/spack/spack/package_base.py", line 1433, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "$HOME/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "$HOME/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "$HOME/spack/lib/spack/spack/stage.py", line 525, in fetch
    raise spack.error.FetchError(err_msg or default_msg, None)
spack.error.FetchError: All fetchers failed for spack-stage-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
==> [2024-04-18-14:23:10.920106] Flagging gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 as failed: FetchError: All fetchers failed for spack-stage-gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
==> [2024-04-18-14:23:10.924402] Warning: Skipping build of patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7 since gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 failed
==> [2024-04-18-14:23:10.924491] Flagging patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7 as failed
==> [2024-04-18-14:23:10.925065] Removing build task for patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7 from list
==> [2024-04-18-14:23:10.926680] Downgrading to a read lock on gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 with timeout 1.000ns
==> [2024-04-18-14:23:10.926767] gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 is now read locked
==> [2024-04-18-14:23:10.926806] Releasing read lock on gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7
==> [2024-04-18-14:23:10.926988] Error: patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7: Package was not installed
==> [2024-04-18-14:23:10.927011] Associating installation failure with first missing package (patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7) from patchelf-0.18.0-2h4zmbuizfwujez4ruunydrns2sihyf7
==> [2024-04-18-14:23:10.941353] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1:0.13 %gcc target=x86_64
==> [2024-04-18-14:23:10.948169] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1:0.13 %gcc target=x86_64'
==> [2024-04-18-14:23:10.948757] Bootstrapping patchelf from pre-built binaries
==> [2024-04-18-14:23:10.952121] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/index.json
==> [2024-04-18-14:23:51.090016] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:23:51.092578] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1:0.13 %gcc target=x86_64'
==> [2024-04-18-14:23:51.093131] Bootstrapping patchelf from pre-built binaries
==> [2024-04-18-14:23:51.095744] Checking existence of https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/index.json
==> [2024-04-18-14:24:31.221359] Failure reading URL: <urlopen error timed out>
==> [2024-04-18-14:24:31.224454] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1:0.13 %gcc target=x86_64'
==> [2024-04-18-14:24:31.224963] Bootstrapping patchelf@0.13.1:0.13 %gcc target=x86_64 from sources
==> [2024-04-18-14:24:32.230002] '/usr/bin/gawk' '--version'
==> [2024-04-18-14:24:32.230022] '/usr/bin/bison' '--version'
==> [2024-04-18-14:24:32.230065] '/usr/bin/git' '--version'
==> [2024-04-18-14:24:32.367967] patchelf applying constraint gmake
==> [2024-04-18-14:24:32.384841] patchelf applying constraint gmake
==> [2024-04-18-14:24:32.394390] [BOOTSTRAP] Try installing 'patchelf@0.13.1:0.13 %gcc target=x86_64' from sources
==> [2024-04-18-14:24:32.400913] Initializing the build queue from the build requests
==> [2024-04-18-14:24:32.400957] Initializing the build queue for patchelf
==> [2024-04-18-14:24:32.403952] Pkg id gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 has the following dependents:
==> [2024-04-18-14:24:32.403991] - patchelf-0.13.1-y56iymhapf72opsbr4fumf5g3q72kzty
==> [2024-04-18-14:24:32.407318] Requeueing a build task for gmake-4.4.1-xfe4facpjmuozxmqiajiowkgj3sf55m7 with status 'queued'
==> [2024-04-18-14:24:32.408912] Reading config from file $HOME/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 551, in ensure_patchelf_in_path_or_raise
    return ensure_executables_in_path_or_raise(
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 472, in ensure_executables_in_path_or_raise
    raise RuntimeError(msg)
RuntimeError: cannot bootstrap any of the patchelf executables from spec "patchelf@0.13.1: %gcc target=x86_64" due to the following failures:
github-actions-v0.5 raised RuntimeError: The binary index is empty
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 266, in try_search_path
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 221, in _install_and_test
    raise RuntimeError("The binary index is empty")

github-actions-v0.4 raised RuntimeError: The binary index is empty
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 266, in try_search_path
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 221, in _install_and_test
    raise RuntimeError("The binary index is empty")

spack-install raised InstallError: Installation request failed.  Refer to reported errors for failing package(s).
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 342, in try_search_path
    concrete_spec.package.do_install()
  File "$HOME/spack/lib/spack/spack/package_base.py", line 1812, in do_install
    PackageInstaller([(self, kwargs)]).install()
  File "$HOME/spack/lib/spack/spack/installer.py", line 2263, in install
    raise InstallError(


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "$HOME/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "$HOME/spack/lib/spack/spack/main.py", line 1066, in main
    return _main(argv)
  File "$HOME/spack/lib/spack/spack/main.py", line 1019, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "$HOME/spack/lib/spack/spack/main.py", line 1049, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "$HOME/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "$HOME/spack/lib/spack/spack/cmd/install.py", line 357, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "$HOME/spack/lib/spack/spack/cmd/install.py", line 470, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "$HOME/spack/lib/spack/spack/cmd/install.py", line 437, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "$HOME/spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "$HOME/spack/lib/spack/spack/spec.py", line 3000, in concretize
    self._new_concretize(tests)
  File "$HOME/spack/lib/spack/spack/spec.py", line 2971, in _new_concretize
    solver = spack.solver.asp.Solver()
  File "$HOME/spack/lib/spack/spack/solver/asp.py", line 3142, in __init__
    self.driver = PyclingoDriver()
  File "$HOME/spack/lib/spack/spack/solver/asp.py", line 841, in __init__
    bootstrap_clingo()
  File "$HOME/spack/lib/spack/spack/solver/asp.py", line 634, in bootstrap_clingo
    spack.bootstrap.ensure_core_dependencies()
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 565, in ensure_core_dependencies
    ensure_patchelf_in_path_or_raise()
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 555, in ensure_patchelf_in_path_or_raise
    return ensure_executables_in_path_or_raise(
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 472, in ensure_executables_in_path_or_raise
    raise RuntimeError(msg)
RuntimeError: cannot bootstrap any of the patchelf executables from spec "patchelf@0.13.1:0.13 %gcc target=x86_64" due to the following failures:
github-actions-v0.5 raised RuntimeError: The binary index is empty
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 266, in try_search_path
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 221, in _install_and_test
    raise RuntimeError("The binary index is empty")

github-actions-v0.4 raised RuntimeError: The binary index is empty
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 266, in try_search_path
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 221, in _install_and_test
    raise RuntimeError("The binary index is empty")

spack-install raised AssertionError: 
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 447, in ensure_executables_in_path_or_raise
    if current_bootstrapper.try_search_path(executables, abstract_spec):
  File "$HOME/spack/lib/spack/spack/bootstrap/core.py", line 342, in try_search_path
    concrete_spec.package.do_install()
  File "$HOME/spack/lib/spack/spack/package_base.py", line 1812, in do_install
    PackageInstaller([(self, kwargs)]).install()
  File "$HOME/spack/lib/spack/spack/installer.py", line 2000, in install
    self._init_queue()
  File "$HOME/spack/lib/spack/spack/installer.py", line 1949, in _init_queue
    self._add_tasks(request, all_dependencies)
  File "$HOME/spack/lib/spack/spack/installer.py", line 1615, in _add_tasks
    spack.store.STORE.failure_tracker.clear(dep, force=False)
  File "$HOME/spack/lib/spack/spack/database.py", line 496, in clear
    lock.release_write()
  File "$HOME/spack/lib/spack/llnl/util/lock.py", line 627, in release_write
    assert self._writes > 0
```

### Information on your system

- Local Computer:
```
* **Spack:** 0.21.2 (89319413d5d90caa9bea98e3419f8aeab61a2a0d)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo
```
- Server:
```
* **Spack:** 0.21.2 (89319413d5d90caa9bea98e3419f8aeab61a2a0d)
* **Python:** 3.9.16
* **Platform:** linux-rhel9-sapphirerapids
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The issue can be reproduced on v0.21.2, but seems to be solved on `develop`.

**Comment by alalazo** [comment]
It seems Spack is halting during the bootstrap phase, because an alternative bootstrap store was not configured. Can you try following this:
- https://spack.readthedocs.io/en/latest/bootstrapping.html#creating-a-mirror-for-air-gapped-systems

and report back whether you were able to bootstrap correctly? For what is worth, I think this issue would be reproduced by just:
```console
$ spack bootstrap now
```
Can you confirm?

**Comment by LorienLV** [comment]
> It seems Spack is halting during the bootstrap phase, because an alternative bootstrap store was not configured. Can you try following this:
> 
> * https://spack.readthedocs.io/en/latest/bootstrapping.html#creating-a-mirror-for-air-gapped-systems
> 
> and report back whether you were able to bootstrap correctly? For what is worth, I think this issue would be reproduced by just:
> 
> ```
> $ spack bootstrap now
> ```
> 
> Can you confirm?

You are absolutely right. Thank you very much. I think it would make a lot of sense to add a reference to offline bootstrapping in the mirrors section of the documentation.

**Comment by alalazo** [comment]
Triaging as not-a-bug, but keeping the issue open until we add a link to the docs as you suggested. Feel free to submit a PR :slightly_smiling_face:
