### ISSUE TITLE
Error: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

### ISSUE THREAD

**Issue by abhisheks1460** [LLNL/spack#43900]
While installing any package i m receiving this error ,I m suing spack version 0.17.1.    

===========================================================

  #spack install aoflagger
==> Warning: config:terminal_title has been replaced by install_status and is ignored
==> Error: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

	spack config [--scope=<scope>] update config

Note that previous versions of Spack will not be able to use the updated configuration.

==========================================================================

       #spack -d install aoflagger
==> [2024-04-29-19:50:14.468797] Reading config from file /home/apps/spack/etc/spack/defaults/config.yaml
==> [2024-04-29-19:50:14.527210] Imported install from built-in commands
==> [2024-04-29-19:50:14.529002] Imported install from built-in commands
==> [2024-04-29-19:50:14.529951] Reading config from file /home/apps/spack/etc/spack/defaults/concretizer.yaml
==> [2024-04-29-19:50:14.544507] Reading config from file /home/apps/spack/etc/spack/defaults/repos.yaml
==> [2024-04-29-19:50:14.910647] Reading config from file /home/apps/spack/etc/spack/defaults/packages.yaml
==> [2024-04-29-19:50:14.959354] Reading config from file /home/apps/spack/etc/spack/compilers.yaml
==> [2024-04-29-19:50:15.081911] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infot1frek1s/main.c' '-o' '/tmp/spack-implicit-link-infot1frek1s/output'
==> [2024-04-29-19:50:15.171557] '/opt/ohpc/pub/compiler/gcc/8.3.0/bin/gcc' '-v' '/tmp/spack-implicit-link-infohq8396fg/main.c' '-o' '/tmp/spack-implicit-link-infohq8396fg/output'
==> [2024-04-29-19:50:15.282409] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/gcc-12.2.0-5episdn64ynux75ivyfkodajcog7gaxb/bin/gcc' '-v' '/tmp/spack-implicit-link-info3h0wa5y0/main.c' '-o' '/tmp/spack-implicit-link-info3h0wa5y0/output'
==> [2024-04-29-19:50:15.413727] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/gcc-13.1.0-pq36qqwphwaii23k3capyyajavo2w2td/bin/gcc' '-v' '/tmp/spack-implicit-link-infog0kbkiys/main.c' '-o' '/tmp/spack-implicit-link-infog0kbkiys/output'
==> [2024-04-29-19:50:15.549506] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.2.0/nvhpc-22.7-qthdnnsghzce7imwkw74ogv6yuqegxh6/Linux_x86_64/22.7/compilers/bin/nvc' '-v' '/tmp/spack-implicit-link-infozkd0z658/main.c' '-o' '/tmp/spack-implicit-link-infozkd0z658/output'
==> [2024-04-29-19:50:15.798894] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/gcc-11.3.0-ctdmhs3sgm2ppuxyyf5vkemmkhh7fyj5/bin/gcc' '-v' '/tmp/spack-implicit-link-infov767494e/main.c' '-o' '/tmp/spack-implicit-link-infov767494e/output'
==> [2024-04-29-19:50:15.952202] '/home/apps/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/intel-oneapi-compilers-2021.4.0-6646aaqgo7fktbu3bqqghjcmruodstdc/compiler/2021.4.0/linux/bin/intel64/icc' '-v' '/tmp/spack-implicit-link-infou4cuprs0/main.c' '-o' '/tmp/spack-implicit-link-infou4cuprs0/output'
==> [2024-04-29-19:50:16.132784] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/intel-oneapi-compilers-2022.0.1-ksraq7ruceaa3h4wpxe5q34s6o25kl6m/compiler/2022.0.1/linux/bin/intel64/icc' '-v' '/tmp/spack-implicit-link-infoyj8stmc1/main.c' '-o' '/tmp/spack-implicit-link-infoyj8stmc1/output'
==> [2024-04-29-19:50:16.346983] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/intel-oneapi-compilers-2022.0.1-ksraq7ruceaa3h4wpxe5q34s6o25kl6m/compiler/2022.0.1/linux/bin/icx' '-v' '/tmp/spack-implicit-link-info1nav6ptq/main.c' '-o' '/tmp/spack-implicit-link-info1nav6ptq/output'
==> [2024-04-29-19:50:16.532826] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-11.3.0/gcc-12.1.0-6ii3twpqhl3quisppdm2fl46fy2kh7dn/bin/gcc' '-v' '/tmp/spack-implicit-link-infoenr7lcgl/main.c' '-o' '/tmp/spack-implicit-link-infoenr7lcgl/output'
==> [2024-04-29-19:50:16.670591] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-stuxtrpa3qzgxaf7xdmyjgrrzqd6jyy5/compiler/2022.1.0/linux/bin/intel64/icc' '-v' '/tmp/spack-implicit-link-infoq9cz102r/main.c' '-o' '/tmp/spack-implicit-link-infoq9cz102r/output'
==> [2024-04-29-19:50:16.881922] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-stuxtrpa3qzgxaf7xdmyjgrrzqd6jyy5/compiler/2022.1.0/linux/bin/icx' '-v' '/tmp/spack-implicit-link-infoi1nttfh_/main.c' '-o' '/tmp/spack-implicit-link-infoi1nttfh_/output'
==> [2024-04-29-19:50:17.097961] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/intel-oneapi-compilers-2023.0.0-rbsfm5ke3oyu2wwz3sazavywg2xn2we5/compiler/2023.0.0/linux/bin/intel64/icc' '-v' '/tmp/spack-implicit-link-infodh4zxoba/main.c' '-o' '/tmp/spack-implicit-link-infodh4zxoba/output'
==> [2024-04-29-19:50:17.330328] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-12.1.0/intel-oneapi-compilers-2023.0.0-rbsfm5ke3oyu2wwz3sazavywg2xn2we5/compiler/2023.0.0/linux/bin/icx' '-v' '/tmp/spack-implicit-link-info86magks5/main.c' '-o' '/tmp/spack-implicit-link-info86magks5/output'
==> [2024-04-29-19:50:17.557036] '/home/apps/spack/opt/spack/linux-centos7-cascadelake/gcc-13.1.0/nvhpc-23.7-snu63rlj6laeai5qyp436vlr6estme5i/Linux_x86_64/23.7/compilers/bin/nvc' '-v' '/tmp/spack-implicit-link-infopg5b8hau/main.c' '-o' '/tmp/spack-implicit-link-infopg5b8hau/output'
==> [2024-04-29-19:50:17.808153] DATABASE LOCK TIMEOUT: 60s
==> [2024-04-29-19:50:17.808483] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-04-29-19:50:20.320362] Reading config from file /home/apps/spack/etc/spack/defaults/mirrors.yaml
==> [2024-04-29-19:50:20.330523] Reading config from file /home/apps/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-04-29-19:50:20.342392] Reading config from file /home/apps/spack/etc/spack/defaults/repos.yaml
==> [2024-04-29-19:50:20.347229] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-04-29-19:50:20.347708] Reading config from file /home/apps/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-04-29-19:50:20.357165] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/apps/spack/etc/spack/defaults
==> [2024-04-29-19:50:20.357212] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/apps/spack/etc/spack/defaults/linux
==> [2024-04-29-19:50:20.357247] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2024-04-29-19:50:20.357271] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2024-04-29-19:50:20.358470] Reading config from file /home/apps/spack/etc/spack/defaults/config.yaml
==> [2024-04-29-19:50:20.387547] Reading config from file /root/.spack/bootstrap/config/linux/config.yaml
==> [2024-04-29-19:50:20.421226] Warning: config:terminal_title has been replaced by install_status and is ignored
==> [2024-04-29-19:50:20.423065] DATABASE LOCK TIMEOUT: 3s
==> [2024-04-29-19:50:20.423231] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-04-29-19:50:20.423931] Reading config from file /home/apps/spack/etc/spack/defaults/packages.yaml
==> [2024-04-29-19:50:20.520733] Reading config from file /root/.spack/bootstrap/config/packages.yaml
==> [2024-04-29-19:50:20.530168] Reading config from file /root/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-04-29-19:50:20.559649] Reading config from file /home/apps/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/apps/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/apps/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/home/apps/spack/lib/spack/spack/main.py", line 1068, in main
    return _main(argv)
  File "/home/apps/spack/lib/spack/spack/main.py", line 1021, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/apps/spack/lib/spack/spack/main.py", line 1051, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/apps/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/home/apps/spack/lib/spack/spack/cmd/install.py", line 354, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/apps/spack/lib/spack/spack/cmd/install.py", line 466, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/home/apps/spack/lib/spack/spack/cmd/install.py", line 434, in concrete_specs_from_cli
    args.spec, concretize=True, tests=install_kwargs["tests"]
  File "/home/apps/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/home/apps/spack/lib/spack/spack/spec.py", line 2988, in concretize
    self._new_concretize(tests)
  File "/home/apps/spack/lib/spack/spack/spec.py", line 2961, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/apps/spack/lib/spack/spack/solver/asp.py", line 3645, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/home/apps/spack/lib/spack/spack/solver/asp.py", line 806, in solve
    self.control = control or default_clingo_control()
  File "/home/apps/spack/lib/spack/spack/solver/asp.py", line 92, in default_clingo_control
    control = clingo().Control()
  File "/home/apps/spack/lib/spack/spack/solver/core.py", line 132, in clingo
    clingo_mod = _bootstrap_clingo()
  File "/home/apps/spack/lib/spack/spack/solver/core.py", line 197, in _bootstrap_clingo
    with spack.bootstrap.ensure_bootstrap_configuration():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/apps/spack/lib/spack/spack/bootstrap/config.py", line 105, in ensure_bootstrap_configuration
    with _ensure_bootstrap_configuration():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/apps/spack/lib/spack/spack/bootstrap/config.py", line 172, in _ensure_bootstrap_configuration
    spack.config.set("config", user_configuration["config"])
  File "/home/apps/spack/lib/spack/spack/config.py", line 966, in set
    return CONFIG.set(path, value, scope)
  File "/home/apps/spack/lib/spack/spack/config.py", line 395, in _method
    return method(self, *args, **kwargs)
  File "/home/apps/spack/lib/spack/spack/config.py", line 665, in set
    self.update_config(path, value, scope=scope)
  File "/home/apps/spack/lib/spack/spack/config.py", line 395, in _method
    return method(self, *args, **kwargs)
  File "/home/apps/spack/lib/spack/spack/config.py", line 544, in update_config
    raise RuntimeError(msg)
RuntimeError: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

	spack config [--scope=<scope>] update config

Note that previous versions of Spack will not be able to use the updated configuration.
You have mail in /var/spool/mail/root

**Comment by wdconinc** [comment]
Did you try `spack config update config`? Can you install aoflagger after doing that?

**Comment by pelesh** [comment]
I had a similar issue. In my case `spack config update config` didn't work. I got a message that my configuration does not need updating but the the problem with spack installation persisted. The workaround I found was to nuke `.spack` in my home directory.

**Comment by alalazo** [comment]
@pelesh We usually don't ensure compatibility across many minor versions of Spack, so it doesnt' surprise me that you could get issues updating from v0.17 to v0.22. What we do our best to ensure, is a nice transition from `v0.X` to `v0.(X+1)`
