### ISSUE TITLE
Using binary mirrors leads to failed `gcc-runtime` installation attempts

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#43919]
### Steps to reproduce

On develop as of 7f2cedd, with https://binaries.spack.io/develop enabled:
```
spack install hpctoolkit@develop
```

### Error message

```
# spack install hpctoolkit@develop
[+] /usr (external glibc-2.26-u5o2ui5hp25pjdeegbglnqoq3igyfugp)
[+] /usr (external glibc-2.31-rqsk6y6vyszetxyj4r4bb6hbctkczdc7)
[+] /usr (external glibc-2.26-eipasphh2e3xzuik4hkdqhc3zudkpng2)
[+] /usr (external glibc-2.31-byt4lnjfqoh7d6tq5cwr5odnypog4wpj)
[+] /usr (external glibc-2.27-7szejbslpapi5j3jiih2kanghyaq4xds)
==> Installing gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw [6/115]
==> No binary for gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw found: installing from source
Process Process-1:
Traceback (most recent call last):
  File "/workspaces/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
KeyError: (<spack.pkg.builtin.gcc-runtime.GccRuntime object at 0x7fd655591a90>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 1148, in _setup_pkg_and_run
    kwargs["env_modifications"] = setup_package(
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 777, in setup_package
    setup_context.set_all_package_py_globals()
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 1021, in set_all_package_py_globals
    set_package_py_globals(pkg, context=Context.BUILD)
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 583, in set_package_py_globals
    module.std_cmake_args = spack.build_systems.cmake.CMakeBuilder.std_args(pkg)
  File "/workspaces/spack/lib/spack/spack/build_systems/cmake.py", line 378, in std_args
    define("CMAKE_INSTALL_RPATH", spack.build_environment.get_rpaths(pkg)),
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 749, in get_rpaths
    if pkg.compiler.modules and len(pkg.compiler.modules) > 1:
  File "/workspaces/spack/lib/spack/llnl/util/lang.py", line 163, in _memoized_function
    ret = func(*args, **kwargs)
  File "/workspaces/spack/lib/spack/spack/package_base.py", line 1406, in compiler
    return spack.compilers.compiler_for_spec(self.spec.compiler, self.spec.architecture)
  File "/workspaces/spack/lib/spack/spack/compilers/__init__.py", line 81, in converter
    return function(cspec_like, *args, **kwargs)
  File "/workspaces/spack/lib/spack/spack/compilers/__init__.py", line 707, in compiler_for_spec
    raise NoCompilerForSpecError(compiler_spec, arch_spec.os)
spack.compilers.NoCompilerForSpecError: No compilers for operating system amzn2 satisfy spec gcc@=12.3.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
KeyError: (<spack.pkg.builtin.gcc-runtime.GccRuntime object at 0x7fd655591a90>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 1168, in _setup_pkg_and_run
    package_context = get_package_context(tb)
  File "/workspaces/spack/lib/spack/spack/build_environment.py", line 1376, in get_package_context
    func = getattr(obj, tb.tb_frame.f_code.co_name, "")
  File "/workspaces/spack/lib/spack/llnl/util/lang.py", line 163, in _memoized_function
    ret = func(*args, **kwargs)
  File "/workspaces/spack/lib/spack/spack/package_base.py", line 1406, in compiler
    return spack.compilers.compiler_for_spec(self.spec.compiler, self.spec.architecture)
  File "/workspaces/spack/lib/spack/spack/compilers/__init__.py", line 81, in converter
    return function(cspec_like, *args, **kwargs)
  File "/workspaces/spack/lib/spack/spack/compilers/__init__.py", line 707, in compiler_for_spec
    raise NoCompilerForSpecError(compiler_spec, arch_spec.os)
spack.compilers.NoCompilerForSpecError: No compilers for operating system amzn2 satisfy spec gcc@=12.3.0
==> Warning: Skipping build of intel-xed-2023.10.11-elzilkonqqc2arjbnyijxc3m5jwvqife since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of hpctoolkit-develop-crrmo3z3kx62p3eweibsd75j336ajse5 since intel-xed-2023.10.11-elzilkonqqc2arjbnyijxc3m5jwvqife failed
==> Warning: Skipping build of xerces-c-3.2.5-dwmmccc64wrwuirmgw5isztbeopsj3nk since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of boost-1.85.0-rjy3trp2n7h4vh3w6mkmwaurf7u53epi since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of dyninst-13.0.0-e3urf3ssghjifufkt7om55dw53rdbpiz since boost-1.85.0-rjy3trp2n7h4vh3w6mkmwaurf7u53epi failed
==> Warning: Skipping build of xxhash-0.8.1-bhon2eivydbyic3mq3k7rolxiycniuwd since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of elfutils-0.190-hnmpsslyipswp44kf66vazoxvjd7erkx since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of hpcviewer-2024.02-5amidaywexf7ginkkcxmijgzbeyapny4 since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Warning: Skipping build of libiberty-2.41-yywqnaejzojnjajz3nzrhctrzsroxc2l since gcc-runtime-12.3.0-uevtwg5yr6iwwykiegilq2jj4ycbjwxw failed
==> Error: Failed to install gcc-runtime due to InstallError: The process has stopped unexpectedly (exit 1)
[+] /workspaces/spack/opt/spack/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/gcc-runtime-11.1.0-lo2p3rjfs3gigbx3cxmuajzwqghbbdk7
==> Installing gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c [8/115]
==> Fetching https://binaries.spack.io/develop/build_cache/linux-amzn2-x86_64_v3-gcc-7.3.1-gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c.spec.json.sig
gpg: Signature made Sat Apr 27 12:07:33 2024 PDT
gpg:                using RSA key D2C7EB3F2B05FA86590D293C04001B2E3DB0C723
gpg: Good signature from "Spack Project Official Binaries <maintainers@spack.io>" [ultimate]
==> Fetching https://binaries.spack.io/develop/build_cache/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-runtime-7.3.1/linux-amzn2-x86_64_v3-gcc-7.3.1-gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c.spack
==> Extracting gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c from binary cache
==> gcc-runtime: Successfully installed gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c
  Search: 0.00s.  Fetch: 2.61s.  Install: 0.18s.  Extract: 0.14s.  Relocate: 0.04s.  Total: 2.79s
[+] /workspaces/spack/opt/spack/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-runtime-7.3.1-c53mdnjuggqhxhglafqbwckxawooh75c
...
```

### Information on your system

* **Spack:** 0.22.0.dev0 (7f2cedd31fa83e404c9701d93c9496d6d1824e4e)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by wdconinc** [comment]
This is the `spack spec` for the same install, including what's available on binaries.
```
# spack spec hpctoolkit@develop
Input spec
--------------------------------
 -   hpctoolkit@develop

Concretized
--------------------------------
 -   hpctoolkit@develop%gcc@11.4.0~cuda~level_zero~mpi~opencl+papi~python~rocm~strip+viewer build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64_v3
 -       ^boost@1.85.0%gcc@11.4.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug~exception~fiber+filesystem+graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random+regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test+thread+timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=a440f96 visibility=global arch=linux-ubuntu20.04-x86_64_v3
[+]      ^bzip2@1.0.8%gcc@7.3.1~debug~pic+shared build_system=generic arch=linux-amzn2-x86_64_v3
[+]          ^diffutils@3.10%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]          ^gcc-runtime@7.3.1%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
[e]          ^glibc@2.26%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]          ^gmake@4.4.1%gcc@7.3.1~guile build_system=generic arch=linux-amzn2-x86_64_v3
 -       ^cmake@3.27.9%gcc@7.3.1~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-amzn2-x86_64_v3
 -           ^curl@8.6.0%gcc@7.3.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-amzn2-x86_64_v3
[+]              ^nghttp2@1.57.0%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -               ^openssl@3.2.1%gcc@7.3.1~docs+shared build_system=generic certs=mozilla arch=linux-amzn2-x86_64_v3
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
 -                   ^perl@5.38.0%gcc@7.3.1+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-amzn2-x86_64_v3
[+]                      ^berkeley-db@18.1.40%gcc@7.3.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-amzn2-x86_64_v3
[+]              ^pkgconf@1.9.5%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]          ^ncurses@6.4%gcc@7.3.1~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-amzn2-x86_64_v3
 -       ^dyninst@13.0.0%gcc@11.4.0~ipo+openmp~stat_dysect~static build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64_v3
 -       ^elfutils@0.190%gcc@11.4.0~debuginfod+exeprefix~nls build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]          ^libiconv@1.17%gcc@7.3.1 build_system=autotools libs=shared,static arch=linux-amzn2-x86_64_v3
 -           ^m4@1.4.19%gcc@11.1.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64_v3
[+]              ^diffutils@3.10%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^libiconv@1.17%gcc@11.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64_v3
 -               ^libsigsegv@2.14%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]          ^zstd@1.5.6%gcc@7.3.1+programs build_system=makefile compression=none libs=shared,static arch=linux-amzn2-x86_64_v3
 -       ^gcc-runtime@12.3.0%gcc@12.3.0 build_system=generic arch=linux-amzn2-x86_64_v3
[e]          ^glibc@2.26%gcc@12.3.0 build_system=autotools arch=linux-amzn2-x86_64_v3
[e]      ^glibc@2.31%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -       ^hpcviewer@2024.02%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[+]          ^openjdk@11.0.20.1_1%gcc@7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3
 -       ^intel-tbb@2021.9.0%gcc@7.3.1~ipo+shared+tm build_system=cmake build_type=Release cxxstd=default generator=make patches=91755c6 arch=linux-amzn2-x86_64_v3
 -           ^hwloc@2.9.1%gcc@7.3.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-amzn2-x86_64_v3
 -               ^libpciaccess@0.17%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -                   ^libtool@2.4.7%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]                      ^findutils@4.9.0%gcc@7.3.1 build_system=autotools patches=440b954 arch=linux-amzn2-x86_64_v3
[+]                      ^m4@1.4.19%gcc@7.3.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-amzn2-x86_64_v3
[+]                          ^libsigsegv@2.14%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]                  ^util-macros@1.19.3%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]              ^libxml2@2.10.3%gcc@7.3.1+pic~python+shared build_system=autotools arch=linux-amzn2-x86_64_v3
 -       ^intel-xed@2023.10.11%gcc@11.4.0~debug+pic build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -           ^python@3.11.7%gcc@7.3.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-amzn2-x86_64_v3
 -               ^expat@2.6.2%gcc@7.3.1+libbsd build_system=autotools arch=linux-amzn2-x86_64_v3
[+]                  ^libbsd@0.12.1%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
[+]                      ^libmd@1.0.4%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -               ^gdbm@1.23%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -               ^gettext@0.22.4%gcc@7.3.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-amzn2-x86_64_v3
 -                   ^tar@1.34%gcc@7.3.1 build_system=autotools zip=pigz arch=linux-amzn2-x86_64_v3
[+]                      ^pigz@2.8%gcc@7.3.1 build_system=makefile arch=linux-amzn2-x86_64_v3
[+]              ^libffi@3.4.6%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -               ^libxcrypt@4.4.35%gcc@7.3.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-amzn2-x86_64_v3
 -               ^readline@8.2%gcc@7.3.1 build_system=autotools patches=bbf97f1 arch=linux-amzn2-x86_64_v3
 -               ^sqlite@3.43.2%gcc@7.3.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-amzn2-x86_64_v3
[+]              ^util-linux-uuid@2.38.1%gcc@7.3.1 build_system=autotools arch=linux-amzn2-x86_64_v3
 -       ^libiberty@2.41%gcc@11.4.0+pic build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]      ^libunwind@1.6.2%gcc@7.3.1~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib build_system=autotools components=none libs=shared,static arch=linux-amzn2-x86_64_v3
 -       ^meson@1.3.2%gcc@7.3.1 build_system=python_pip patches=0f0b1bd arch=linux-amzn2-x86_64_v3
 -           ^py-pip@23.1.2%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
 -           ^py-setuptools@69.2.0%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
 -           ^py-wheel@0.41.2%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
 -       ^ninja@1.11.1%gcc@7.3.1+re2c build_system=generic arch=linux-amzn2-x86_64_v3
[+]          ^re2c@2.2%gcc@7.3.1 build_system=generic arch=linux-amzn2-x86_64_v3
[+]      ^papi@7.1.0%gcc@7.5.0~cuda~debug+example~infiniband~lmsensors~nvml~powercap~rapl~rocm~rocm_smi~sde+shared~static_tools build_system=autotools patches=48cb202 arch=linux-ubuntu18.04-x86_64_v3
[+]          ^gcc-runtime@7.5.0%gcc@7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3
[e]          ^glibc@2.27%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]          ^gmake@4.4.1%gcc@7.5.0~guile build_system=generic arch=linux-ubuntu18.04-x86_64_v3
 -       ^pkgconf@1.9.5%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -           ^gcc-runtime@11.1.0%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[e]          ^glibc@2.31%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -           ^gmake@4.4.1%gcc@11.1.0~guile build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -       ^xerces-c@3.2.5%gcc@11.4.0 build_system=autotools cxxstd=default netaccessor=curl transcoder=iconv arch=linux-ubuntu20.04-x86_64_v3
 -       ^xxhash@0.8.1%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64_v3
[+]      ^xz@5.4.6%gcc@7.3.1+pic build_system=autotools libs=shared,static arch=linux-amzn2-x86_64_v3
 -       ^yaml-cpp@0.7.0%gcc@11.1.0~ipo+pic+shared~tests build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64_v3
 -           ^cmake@3.27.9%gcc@11.1.0~doc+ncurses~ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64_v3
 -               ^curl@8.6.0%gcc@11.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^nghttp2@1.57.0%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -                   ^openssl@3.2.1%gcc@11.1.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64_v3
[+]                      ^ca-certificates-mozilla@2023-05-30%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -                       ^perl@5.38.0%gcc@11.1.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu20.04-x86_64_v3
[+]                          ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64_v3
 -                           ^gdbm@1.23%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^pkgconf@1.9.5%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]              ^expat@2.6.2%gcc@11.1.0+libbsd build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^libbsd@0.12.1%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                      ^libmd@1.0.4%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -               ^jsoncpp@1.9.5%gcc@11.1.0~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64_v3
 -                   ^meson@1.3.2%gcc@11.1.0 build_system=python_pip patches=0f0b1bd arch=linux-ubuntu20.04-x86_64_v3
 -                       ^py-pip@23.1.2%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -                       ^py-setuptools@69.2.0%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -                       ^py-wheel@0.41.2%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -                       ^python@3.11.7%gcc@11.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu20.04-x86_64_v3
 -                           ^gettext@0.22.4%gcc@11.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                              ^libxml2@2.10.3%gcc@11.1.0+pic~python+shared build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -                               ^tar@1.34%gcc@11.1.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64_v3
[+]                                  ^pigz@2.8%gcc@11.1.0 build_system=makefile arch=linux-ubuntu20.04-x86_64_v3
[+]                          ^libffi@3.4.6%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -                           ^libxcrypt@4.4.35%gcc@11.1.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-x86_64_v3
[+]                          ^readline@8.2%gcc@11.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64_v3
 -                           ^sqlite@3.43.2%gcc@11.1.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]                          ^util-linux-uuid@2.38.1%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
 -                   ^ninja@1.11.1%gcc@11.1.0+re2c build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[+]                      ^re2c@2.2%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
 -               ^libarchive@3.7.1%gcc@11.1.0+iconv build_system=autotools compression=bz2lib,lz4,lzma,lzo2,zlib,zstd crypto=openssl libs=shared,static programs=none xar=expat arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^lz4@1.9.4%gcc@11.1.0+pic build_system=makefile libs=shared,static arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^lzo@2.10%gcc@11.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^xz@5.4.6%gcc@11.1.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64_v3
[+]                  ^zstd@1.5.6%gcc@11.1.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64_v3
[+]              ^libuv@1.46.0%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]              ^ncurses@6.4%gcc@11.1.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu20.04-x86_64_v3
[+]              ^rhash@1.4.2%gcc@11.1.0 build_system=makefile patches=093518c,3fbfe46 arch=linux-ubuntu20.04-x86_64_v3
[+]              ^zlib-ng@2.1.6%gcc@11.1.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu20.04-x86_64_v3
[+]          ^gcc-runtime@11.1.0%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[+]          ^gmake@4.4.1%gcc@11.1.0~guile build_system=generic arch=linux-ubuntu20.04-x86_64_v3
[+]      ^zlib-ng@2.1.6%gcc@7.3.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-amzn2-x86_64_v3
```

**Comment by alalazo** [comment]
The issue here is that the index points to specs that cannot be fetched. These specs have a compiler that you don't have locally (or even a different os). Spack is failing when trying to "build" the binaries it can't fetch :cry: So two issues:
1. We shouldn't fall back to build specs that originated from a buildcache / store
2. We might have an index that is out of sync with the specs in the buildcache?

**Comment by alalazo** [comment]
This is a debug log of a similar failure:

![Screenshot from 2024-04-30 19-06-55](https://github.com/spack/spack/assets/4199709/a0adb524-4baa-415e-ad7e-0cc125f98326)

**Comment by alalazo** [comment]
From direct messages on Slack, it's confirmed that the mirror in the issue has a bad index (it mentions specs that have been removed from the buildcache).

**Comment by alalazo** [comment]
Also, the error seems to happen only with the `develop` buildcache (which aggregates all the others)

**Comment by wdconinc** [comment]
Just got bit by this again. If this is indeed due to a bad index on the buildcache, is there a way to make package removes from the buildcache maintain consistency by first removing them from the index and only then the actual package? I don't know how that cleanup looks like, but I suspect right now it is evicting first and then running a buildcache update-index.

**Comment by cameronrutherford** [comment]
https://github.com/LLNL/hiop/actions/runs/10563547004/job/29264000945 - I think I am getting bit by the same issue in this pipeline? Error isn't with `gcc-runtime`, but rather `gmake` in this case.

I don't really know what to try in order to fix the error on my end apart from stop using the buildcache entirely...

**Comment by cameronrutherford** [comment]
https://github.com/ORNL/ReSolve/actions/runs/10167437431/job/28119894149 - I checked ReSolve for a comparison here (ExaGO can be compared to as well...), and the reason we are seeing the failures in HiOp but not ReSolve is that we have our own cached version of gmake being pulled in from the GHCR spack mirror that we are hosting.

Seems like hosting a similar thing for HiOp will fix the problem, for me, so I will create an issue for that and work on it to fix that package's pipelines.

Would be nice to not have this issue sporadically re-appear on spack's end however.

**Comment by vmiheer** [comment]
Is the workaround to remove binary mirror?

**Comment by alalazo** [comment]
> Is the workaround to remove binary mirror?

I wouldn't advise using the `develop` binary mirror in production, or for any use other than testing - due to the number of duplicates it contains. It's better to rely on one of the `develop-<date>` snapshots, or a tagged release.
