### ISSUE TITLE
"Error: 'name'", caused by exception somewhere deep

### ISSUE THREAD

**Issue by paulmelis** [LLNL/spack#43951]
### Discussed in https://github.com/spack/spack/discussions/43925

<div type='discussions-op-text'>

<sup>Originally posted by **paulmelis** April 30, 2024</sup>
I've been trying to figure out why I'm getting this error with pretty much every command I try (and it's a bit hard to find this particular error):

```
paulm@j21n14:~/spack$ git branch -v
* releases/v0.21 89319413 Update CHANGELOG and set version to v0.21.2
paulm@j21n14:~/spack$ . share/spack/setup-env.sh
paulm@j21n14:~/spack$ spack list
==> Error: 'name'
```

This is with a fresh clone as per the tutorial, on an arm64 system (`spack arch` output is `linux-debian12-neoverse_v2`) that I haven't been working a lot yet. Spack seems to work fine on another compute system we have.</div>

**Comment by alalazo** [comment]
Check with debug flags on:
```
$ spack -d list
```
This gives back a stacktrace. It's very likely a KeyError we don't handle properly.

**Comment by eugene-tam-dpie** [comment]
I have the exact same problem for multiple branches
Output from `spack -d list` in `releases/v0.22 594a376c52` below...
```
==> [2024-10-05-14:19:29.516544] Reading config from file /home/foobar/spack/etc/spack/defaults/config.yaml
==> [2024-10-05-14:19:29.594338] Imported list from built-in commands
==> [2024-10-05-14:19:29.595540] Imported list from built-in commands
==> [2024-10-05-14:19:29.596402] Reading config from file /home/foobar/spack/etc/spack/defaults/repos.yaml
Traceback (most recent call last):
  File "/home/foobar/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
KeyError: (<spack.repo.RepoPath object at 0x15027f5a4710>, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foobar/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
KeyError: (<spack.repo.RepoPath object at 0x15027f5a4710>, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foobar/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/foobar/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/home/foobar/spack/lib/spack/spack/main.py", line 1069, in main
    return _main(argv)
  File "/home/foobar/spack/lib/spack/spack/main.py", line 1022, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/foobar/spack/lib/spack/spack/main.py", line 1052, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/foobar/spack/lib/spack/spack/main.py", line 649, in _invoke_command
    return_val = command(parser, args)
  File "/home/foobar/spack/lib/spack/spack/cmd/list.py", line 325, in list
    pkgs = set().union(*[set(repo.all_package_names(args.virtuals)) for repo in repos])
  File "/home/foobar/spack/lib/spack/spack/cmd/list.py", line 325, in <listcomp>
    pkgs = set().union(*[set(repo.all_package_names(args.virtuals)) for repo in repos])
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 739, in all_package_names
    return self._all_package_names(include_virtuals)
  File "/home/foobar/spack/lib/spack/llnl/util/lang.py", line 163, in _memoized_function
    ret = func(*args, **kwargs)
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 736, in _all_package_names
    return sorted(self._all_package_names_set(include_virtuals), key=lambda n: n.lower())
  File "/home/foobar/spack/lib/spack/llnl/util/lang.py", line 163, in _memoized_function
    ret = func(*args, **kwargs)
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 731, in _all_package_names_set
    return {name for repo in self.repos for name in repo.all_package_names(include_virtuals)}
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 731, in <setcomp>
    return {name for repo in self.repos for name in repo.all_package_names(include_virtuals)}
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 1164, in all_package_names
    return [x for x in names if not self.is_virtual(x)]
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 1164, in <listcomp>
    return [x for x in names if not self.is_virtual(x)]
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 1213, in is_virtual
    return pkg_name in self.provider_index
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 1108, in provider_index
    return self.index["providers"]
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 590, in __getitem__
    self._build_all_indexes()
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 603, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 624, in _build_index
    indexer.read(old) if old else indexer.create()
  File "/home/foobar/spack/lib/spack/spack/repo.py", line 506, in read
    self.index = spack.provider_index.ProviderIndex.from_json(stream, self.repository)
  File "/home/foobar/spack/lib/spack/spack/provider_index.py", line 243, in from_json
    lambda vpkg, plist: (
  File "/home/foobar/spack/lib/spack/spack/provider_index.py", line 273, in _transform
    for name, mappings in providers.items()
  File "/home/foobar/spack/lib/spack/spack/provider_index.py", line 273, in <genexpr>
    for name, mappings in providers.items()
  File "/home/foobar/spack/lib/spack/spack/provider_index.py", line 272, in <listcomp>
    (name, out_mapping_type([transform_fun(vpkg, pset) for vpkg, pset in mapiter(mappings)]))
  File "/home/foobar/spack/lib/spack/spack/provider_index.py", line 244, in <lambda>
    spack.spec.SpecfileV4.from_node_dict(vpkg),
  File "/home/foobar/spack/lib/spack/spack/spec.py", line 4983, in from_node_dict
    name, node = cls.name_and_data(node)
  File "/home/foobar/spack/lib/spack/spack/spec.py", line 5183, in name_and_data
    return node["name"], node
KeyError: 'name'
```

**Comment by kit-** [comment]
In my case there was a conflict with files in my local cache (~/.spack/cache) from a previous Spack installation. Removing that cleared this issue.

**Comment by eugene-tam-dpie** [comment]
> In my case there was a conflict with files in my local cache (~/.spack/cache) from a previous Spack installation. Removing that cleared this issue.

Despite by spack being a fresh clone on a clean install, that did the trick for me!
Cheers for the tip!

**Comment by germasch** [comment]
I figured I'll bump this, since it just happened to me, too -- following the instructions on how to do a fresh install of spack and got the cryptic `==> Error: 'name'`.

I found this thread, and the resolution (removing old spack cache) worked, but it'd be nicer if there was at least a better error message.
