### ISSUE TITLE
`spack checksum` not working after #44030

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#44052]
### Steps to reproduce

Try to checksum a new version of `gcc`:
```console
$ spack -d checksum gcc 14.1.0
```

### Error message

This is what I get on `develop`:
```console
$ spack -d checksum gcc 14.1.0
==> [2024-05-07-12:38:03.805722] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-05-07-12:38:03.836615] Imported checksum from built-in commands
==> [2024-05-07-12:38:03.837267] Imported checksum from built-in commands
==> [2024-05-07-12:38:03.837779] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2024-05-07-12:38:03.942655] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-05-07-12:38:03.974176] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/linux/packages.yaml
==> [2024-05-07-12:38:03.988652] Checking existence of https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:38:03.989182] certs: relative path not allowed: $SSL_CERT_FILE
==> [2024-05-07-12:38:04.821662] Found 1 version of gcc
==> [2024-05-07-12:38:04.837237] Checking existence of https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:38:05.602867] Failure reading URL: GET https://mirror.easyname.at/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz returned 404: Not Found
==> [2024-05-07-12:38:05.603251] URL does not exist: https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:38:05.603674] FailedDownloadError: Failed to fetch file from URL: https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:38:05.603750] Fetching from https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz failed.
==> [2024-05-07-12:38:05.604810] [WORKER] Something failed on https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz, skipping.  (All fetchers failed for spack-stage-tl480uex)
==> [2024-05-07-12:38:05.608752] Error: Could not fetch any versions for gcc
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1069, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1022, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1052, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 649, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/checksum.py", line 171, in checksum
    version_hashes = spack.stage.get_checksums_for_versions(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/stage.py", line 1223, in get_checksums_for_versions
    tty.die(f"Could not fetch any versions for {package_name}")
  File "/home/culpo/PycharmProjects/spack/lib/spack/llnl/util/tty/__init__.py", line 249, in die
    sys.exit(1)
SystemExit: 1
```
If I revert #44030:
```console
$ spack -d checksum gcc 14.1.0
==> [2024-05-07-12:37:27.946764] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-05-07-12:37:27.974475] Imported checksum from built-in commands
==> [2024-05-07-12:37:27.975098] Imported checksum from built-in commands
==> [2024-05-07-12:37:27.975648] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2024-05-07-12:37:28.086718] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-05-07-12:37:28.118058] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/linux/packages.yaml
==> [2024-05-07-12:37:28.132520] Checking existence of https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:37:28.133361] URLLIB: Looking for custom SSL certs at /home/culpo/PycharmProjects/spack/etc/spack/defaults/$SSL_CERT_FILE
==> [2024-05-07-12:37:28.133452] URLLIB: Custom SSL certs not found
==> [2024-05-07-12:37:28.993637] Failure reading URL: GET https://mirror.easyname.at/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz returned 404: Not Found
==> [2024-05-07-12:37:28.993960] Checking existence of https://ftpmirror.gnu.org/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:37:29.892709] Failure reading URL: GET https://mirror.easyname.at/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz returned 404: Not Found
==> [2024-05-07-12:37:29.892961] Checking existence of https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:37:30.510314] Found 1 version of gcc
==> [2024-05-07-12:37:30.517418] Checking existence of https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:37:30.860218] Fetching https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
==> [2024-05-07-12:37:38.971810] Checksummed 1 version of gcc:

    version("14.1.0", sha256="e283c654987afe3de9d8080bc0bd79534b5ca0d681a73a11ff2b5d3767426840")

```

### Information on your system

* **Spack:** 0.22.0.dev0 (f7afd67a266be82d426ce3a6d80e7a7c7500d122)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Ok, it might have been accidental: it's the ftp mirror not behaving, and for some reason I got a streak of 5 / 6 tries in which it was working with the revert and not working on develop. Closing the issue.
