### ISSUE TITLE
Cannot install musl

### ISSUE THREAD

**Issue by jor-webber** [LLNL/spack#44352]
### Steps to reproduce

```spack install musl```

### Error message

```lib/spack/spack/error.py:52 ==> [2024-05-23-13:38:22.963365] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    musl is unsatisfiable
Traceback (most recent call last):
  File "/opt/user_facing_spack/lib/spack/spack/main.py", line 1069, in main
    return _main(argv)
  File "/opt/user_facing_spack/lib/spack/spack/main.py", line 1022, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/opt/user_facing_spack/lib/spack/spack/main.py", line 1052, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/opt/user_facing_spack/lib/spack/spack/main.py", line 649, in _invoke_command
    return_val = command(parser, args)
  File "/opt/user_facing_spack/lib/spack/spack/cmd/install.py", line 354, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/opt/user_facing_spack/lib/spack/spack/cmd/install.py", line 466, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/opt/user_facing_spack/lib/spack/spack/cmd/install.py", line 433, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/opt/user_facing_spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/opt/user_facing_spack/lib/spack/spack/spec.py", line 2995, in concretize
    self._new_concretize(tests)
  File "/opt/user_facing_spack/lib/spack/spack/spec.py", line 2968, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/opt/user_facing_spack/lib/spack/spack/solver/asp.py", line 3849, in solve
    result, _, _ = self.driver.solve(
  File "/opt/user_facing_spack/lib/spack/spack/solver/asp.py", line 929, in solve
    result.raise_if_unsat()
  File "/opt/user_facing_spack/lib/spack/spack/solver/asp.py", line 472, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    musl is unsatisfiable```

### Information on your system

* **Spack:** 0.23.0.dev0 (90c0889533cbfd202ba89611acab1006c088df13)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-sandybridge
* **Concretizer:** clingo


### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
This is expected, as of 0.22 we treat `glibc` and `musl` as external / system packages.

Note that `spack install musl` wasn't very useful by itself in spack 0.21 and older. You could maybe tell `gcc` to use musl start files and link against its libc, but you wouldn't have libstdc++ for musl, so no way to compile c++.

**Comment by jor-webber** [comment]
Understood thank you! That is useful to know.
