### ISSUE TITLE
Cannot put externals dependencies in speclist for environment

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#44533]
### Steps to reproduce

@haampie @alalazo 

Using any commit >= 7041261 (https://github.com/spack/spack/pull/44374)

Create an env like:

```
spack:
  specs:
  - perl-xml-regexp
  - perl@5.30.3
  view: false
  concretizer:
    unify: true
  packages:
    perl:
      externals:
      - spec: perl@5.30.3
        prefix: /usr/
```

(I think you can do this with any package in spack, the important thing is that you have an external package, and a non-external package that depends on it, where both are in the spec list - FWIW I cannot reproduce the issue unless I have a non-external dependent in my speclist)

then 

```
$ spack concretize -f -U
$ spack install
```

### Error message

```
...
$ spack install
[+] /usr/ (external perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve)
==> Error: perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve cannot be installed locally: is external
```

### Full debug output

```
$ spack -d install
==> [2024-06-03-18:10:42.716451] Reading config from file /Users/scheibel1/Desktop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-03-18:10:42.733317] Reading config from file /Users/scheibel1/Desktop/spack/spack/var/spack/environments/external1/spack.yaml
==> [2024-06-03-18:10:42.738149] Using environment 'external1'
==> [2024-06-03-18:10:42.742733] Imported install from built-in commands
==> [2024-06-03-18:10:42.743691] Imported install from built-in commands
==> [2024-06-03-18:10:42.751996] Reading config from file /Users/scheibel1/Desktop/spack/spack/var/spack/environments/external1/spack.yaml
==> [2024-06-03-18:10:42.754588] Deactivated environment 'external1'
==> [2024-06-03-18:10:42.757098] Using environment 'external1'
==> [2024-06-03-18:10:42.757385] Reading config from file /Users/scheibel1/Desktop/spack/spack/etc/spack/defaults/concretizer.yaml
==> [2024-06-03-18:10:42.765717] '/usr/bin/git' '-C' '/Users/scheibel1/Desktop/spack/spack' 'rev-parse' 'HEAD'
==> [2024-06-03-18:10:42.783649] Reading config from file /Users/scheibel1/Desktop/spack/spack/etc/spack/defaults/repos.yaml
==> [2024-06-03-18:10:42.815391] Reading config from file /Users/scheibel1/Desktop/spack/spack/etc/spack/defaults/packages.yaml
==> [2024-06-03-18:10:42.833822] Reading config from file /Users/scheibel1/Desktop/spack/spack/etc/spack/defaults/darwin/packages.yaml
==> [2024-06-03-18:10:42.841259] Reading config from file /Users/scheibel1/.spack/packages.yaml
==> [2024-06-03-18:10:42.844865] DATABASE LOCK TIMEOUT: 60s
==> [2024-06-03-18:10:42.844906] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-06-03-18:10:42.851228] Initializing the build queue from the build requests
==> [2024-06-03-18:10:42.851272] Initializing the build queue for perl-xml-regexp
==> [2024-06-03-18:10:42.852095] Pkg id perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve has the following dependents:
==> [2024-06-03-18:10:42.852120] - perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53
==> [2024-06-03-18:10:42.852751] Reading config from file /Users/scheibel1/.spack/darwin/compilers.yaml
==> [2024-06-03-18:10:42.856721] Requeueing a build task for perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve with status 'queued'
==> [2024-06-03-18:10:42.857109] Pkg id perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53 has the following dependents:
==> [2024-06-03-18:10:42.858192] Requeueing a build task for perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53 with status 'queued'
==> [2024-06-03-18:10:42.858238] Initializing the build queue for perl
==> [2024-06-03-18:10:42.858465] perl@5.30.3 : externally installed in /usr/
==> [2024-06-03-18:10:42.858489] perl@5.30.3 : already registered in DB
[+] /usr/ (external perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve)
==> [2024-06-03-18:10:42.859275] Flagging perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve as installed
==> [2024-06-03-18:10:42.859306] Removing perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve from perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53's uninstalled dependencies.
==> [2024-06-03-18:10:42.859338] Removing build task for perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53 from list
==> [2024-06-03-18:10:42.859358] Requeueing a build task for perl-xml-regexp-0.04-ht7rwyki4z6awxzxnxtqi4dbr2eimh53 with status 'queued'
==> [2024-06-03-18:10:42.859376] Ensure all dependencies know all dependents across specs
==> [2024-06-03-18:10:42.859430] Processing perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve: task=priority=0, status=dequeued, start=0, #dependencies=0
==> [2024-06-03-18:10:42.859619] Acquiring a write lock on perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve with timeout 1.000ns
==> [2024-06-03-18:10:42.859736] perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve is now write locked
==> [2024-06-03-18:10:42.859800] ExternalPackageError: perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve cannot be installed locally: is external
==> [2024-06-03-18:10:42.859818] Error: perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve cannot be installed locally: is external
Traceback (most recent call last):
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/main.py", line 1069, in main
    return _main(argv)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/main.py", line 1022, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/main.py", line 1052, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/main.py", line 649, in _invoke_command
    return_val = command(parser, args)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/cmd/install.py", line 351, in install
    install_with_active_env(env, args, install_kwargs, reporter_factory)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/cmd/install.py", line 420, in install_with_active_env
    env.install_specs(specs_to_install, **install_kwargs)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/environment/environment.py", line 1963, in install_specs
    PackageInstaller([spec.package for spec in specs], install_args).install()
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/installer.py", line 2078, in install
    self._prepare_for_install(task)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/installer.py", line 1324, in _prepare_for_install
    self._ensure_install_ready(task.pkg)
  File "/Users/scheibel1/Desktop/spack/spack/lib/spack/spack/installer.py", line 1424, in _ensure_install_ready
    raise ExternalPackageError(f"{pre} is external")
spack.installer.ExternalPackageError: perl-5.30.3-dxlnhzs5kuljd7qb6ydqv7napwrqtdve cannot be installed locally: is external
```

### Information on your system

* **Spack:** 0.23.0.dev0 (70412612c79af495fb2b2223edac4bd5a70a813a)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment]
I'm also seeing something similar with reconcretizing an environment that uses a package as root spec (and is a dependency of another root) when using an upstream (chained spack installation), e.g.:
```
==> Error: r3d-master-wl6obs7zllezqvez23x477eoxoskgjok cannot be installed locally: is upstream
```
The initial concretization and install went fine, only after changing something unrelated and reconcretizing does this show up.
