### ISSUE TITLE
modules.yaml config file. Adding ${PACKAGE}_ROOT variable to lmod modulefile

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4462]
Currently my modules.yaml config file looks like:

```
modules:
  enable:
    - lmod
    - tcl
  lmod:
    hash_length: 0
    core_copmilers: ['gcc@4.8.5']
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH
```

I would like to add an environment variable ${PACKAGE} to all module files. The spack documentation contains an example on how to do this for environment modules:

```
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
```

Does anybody know how to get the same for lmod modules ?

When using

```
modules:
  enable:
    - lmod
    - tcl
  lmod:
    hash_length: 0
    core_copmilers: ['gcc@4.8.5']
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH
    environment:
      set:   
        '${PACKAGE}_ROOT': '${PREFIX}'
```

spack refresh fails with

```
Traceback (most recent call last):
  File "/cluster/apps/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/cluster/apps/spack/lib/spack/spack/main.py", line 437, in main
    parser.add_command(command_name)
  File "/cluster/apps/spack/lib/spack/spack/main.py", line 248, in add_command
    module = spack.cmd.get_module(name)
  File "/cluster/apps/spack/lib/spack/spack/cmd/__init__.py", line 87, in get_module
    level=0)
  File "/cluster/apps/spack/lib/spack/spack/cmd/module.py", line 35, in <module>
    from spack.cmd.common import arguments
  File "/cluster/apps/spack/lib/spack/spack/cmd/common/arguments.py", line 30, in <module>
    import spack.modules
  File "/cluster/apps/spack/lib/spack/spack/modules.py", line 73, in <module>
    _module_config = spack.config.get_config('modules')
  File "/cluster/apps/spack/lib/spack/spack/config.py", line 401, in get_config
    data = scope.get_section(section)
  File "/cluster/apps/spack/lib/spack/spack/config.py", line 179, in get_section
    data   = _read_config_file(path, schema)
  File "/cluster/apps/spack/lib/spack/spack/config.py", line 275, in _read_config_file
    validate_section(data, schema)
  File "/cluster/apps/spack/lib/spack/spack/config.py", line 151, in validate_section
    raise ConfigFormatError(e, data)
spack.config.ConfigFormatError: /cluster/home/spackapps/.spack/linux/modules.yaml:46: {'set': {'${PACKAGE}_ROOT': '${PREFIX}'}} is not of type 'array'
```

**Comment by samfux84** [comment]
Problem solved:

modules:
  enable:
    - lmod
    - tcl
  lmod:
    hash_length: 0
    core_copmilers: ['gcc@4.8.5']
    all:
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH
