### ISSUE TITLE
==> Error: Spack concretizer internal error. ....................gdal is unsatisfiable

### ISSUE THREAD

**Issue by wglanfield-rms** [LLNL/spack#44769]
### Steps to reproduce

```
[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal@3.9.0 %gcc@10.2.0 arch=linux-centos7-x86_64
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal@3.9.0%gcc@10.2.0 arch=linux-centos7-x86_64 is unsatisfiable

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal@3.9.0 %gcc@10.2.0 arch=linux-centos7-x86_64
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal@3.9.0%gcc@10.2.0 arch=linux-centos7-x86_64 is unsatisfiable

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal@3.8.4 %gcc@10.2.0 arch=linux-centos7-x86_64
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal@3.8.4%gcc@10.2.0 arch=linux-centos7-x86_64 is unsatisfiable

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal@3.8.4
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal@3.8.4 is unsatisfiable

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal@3.9.0
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal@3.9.0 is unsatisfiable

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack install gdal
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable
```

### Error message

```
[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack --debug --stacktrace install gdal
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:13:59.643811] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-06-19-10:13:59.701824] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-06-19-10:13:59.703868] Imported install from built-in commands
lib/spack/spack/database.py:646 ==> [2024-06-19-10:13:59.886605] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-06-19-10:13:59.887130] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:13:59.888037] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:13:59.903345] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:00.066153] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:00.621904] Reading config from file /home/hpcadmin/.spack/linux/compilers.yaml
lib/spack/spack/util/executable.py:233 ==> [2024-06-19-10:14:00.778395] '/bin/gcc' '-v' '/tmp/spack-implicit-link-info935ac8in/main.c' '-o' '/tmp/spack-implicit-link-info935ac8in/output'
lib/spack/spack/util/executable.py:233 ==> [2024-06-19-10:14:00.850973] '/opt/rh/devtoolset-7/root/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infowfsuwtfc/main.c' '-o' '/tmp/spack-implicit-link-infowfsuwtfc/output'
lib/spack/spack/database.py:646 ==> [2024-06-19-10:14:01.088825] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-06-19-10:14:01.089310] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.172542] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/database.py:646 ==> [2024-06-19-10:14:01.300864] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-06-19-10:14:01.301473] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.302456] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.318330] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-06-19-10:14:01.324803] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.325932] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-06-19-10:14:01.338915] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-06-19-10:14:01.339368] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-06-19-10:14:01.339830] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/hpcadmin/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-06-19-10:14:01.340254] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/hpcadmin/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.342356] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.383824] Reading config from file /home/hpcadmin/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:646 ==> [2024-06-19-10:14:01.406395] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-06-19-10:14:01.406980] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.407898] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.474216] Reading config from file /home/hpcadmin/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:231 ==> [2024-06-19-10:14:01.664090] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
lib/spack/spack/bootstrap/core.py:355 ==> [2024-06-19-10:14:01.664586] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.665779] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:83 ==> [2024-06-19-10:14:01.841783] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.6/t4yf34cuvquqp5xd66zybmcfyhwbdlsf" provides the "clingo" Python module
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:01.843169] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:02.118521] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:07.837965] Reading config from file /home/hpcadmin/.spack/linux/compilers.yaml
lib/spack/spack/util/executable.py:233 ==> [2024-06-19-10:14:07.858558] '/bin/gcc' '-v' '/tmp/spack-implicit-link-infowbfz_etx/main.c' '-o' '/tmp/spack-implicit-link-infowbfz_etx/output'
lib/spack/spack/util/executable.py:233 ==> [2024-06-19-10:14:07.924692] '/opt/rh/devtoolset-7/root/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-info6u3aar0s/main.c' '-o' '/tmp/spack-implicit-link-info6u3aar0s/output'
lib/spack/spack/config.py:1123 ==> [2024-06-19-10:14:08.115452] Reading config from file /mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/install.py:436 ==> [2024-06-19-10:14:24.146834] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable
lib/spack/spack/main.py:1072 ==> [2024-06-19-10:14:24.147189] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable
lib/spack/spack/error.py:52 ==> [2024-06-19-10:14:24.163223] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable
Traceback (most recent call last):
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/main.py", line 1069, in main
    return _main(argv)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/main.py", line 1022, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/main.py", line 1052, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/main.py", line 649, in _invoke_command
    return_val = command(parser, args)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/cmd/install.py", line 353, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/cmd/install.py", line 465, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/cmd/install.py", line 433, in concrete_specs_from_cli
    args.spec, concretize=True, tests=install_kwargs["tests"]
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/spec.py", line 2993, in concretize
    self._new_concretize(tests)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/spec.py", line 2966, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/solver/asp.py", line 3844, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/solver/asp.py", line 929, in solve
    result.raise_if_unsat()
  File "/mnt/opt/Centos7/hpc/spack/spack_Jun_2024/spack/lib/spack/spack/solver/asp.py", line 472, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable
```

### Information on your system

[hpcadmin@ukvmlx-head-01 GDAL-3.9.0_gcc-10.2.0]$ spack debug report

* **Spack:** 0.23.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Cannot really reproduce without more information:
```console
$ spack spec gdal
Input spec
--------------------------------
 -   gdal

Concretized
--------------------------------
 -   gdal@3.9.0%gcc@9.4.0~archive~armadillo~arrow~basisu~blosc~brunsli~cfitsio~crnlib~cryptopp~csharp+curl~deflate~ecw+expat~filegdb~freexl~fyba+geos~gif~gta~hdf4~hdf5~hdfs~heif~iconv~idb~ipo~java+jpeg~jxl~kdu~kea~lerc~libaec~libcsf~libkml~liblzma~libqb3~libxml2~luratech~lz4~mongocxx~mrsid~mssql_ncli~mssql_odbc~mysql~netcdf~odbc~odbccpp~ogdi~opencad~opencl~openexr~openjpeg~openssl~oracle~parquet~pcidsk~pcre2~pdfium+png~podofo~poppler~postgresql~python~qhull~rasterlite2~rdb~sfcgal~spatialite+sqlite3~teigha~tiledb~webp~xercesc~zstd build_system=cmake build_type=Release generator=ninja arch=linux-ubuntu20.04-icelake
 -       ^cmake@3.29.4%gcc@9.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-icelake
 -           ^gmake@4.4.1%gcc@9.4.0~guile build_system=generic arch=linux-ubuntu20.04-icelake
 -           ^ncurses@6.5%gcc@9.4.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu20.04-icelake
 -       ^curl@8.7.1%gcc@9.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-icelake
 -           ^nghttp2@1.62.0%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -               ^diffutils@3.10%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -                   ^libiconv@1.17%gcc@9.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-icelake
 -           ^openssl@3.3.1%gcc@9.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-icelake
 -               ^ca-certificates-mozilla@2023-05-30%gcc@9.4.0 build_system=generic arch=linux-ubuntu20.04-icelake
 -           ^perl@5.38.2%gcc@9.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu20.04-icelake
 -               ^berkeley-db@18.1.40%gcc@9.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-icelake
 -               ^bzip2@1.0.8%gcc@9.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-icelake
 -               ^gdbm@1.23%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^expat@2.6.2%gcc@9.4.0+libbsd build_system=autotools arch=linux-ubuntu20.04-icelake
 -           ^libbsd@0.12.2%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -               ^libmd@1.0.4%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^gcc-runtime@9.4.0%gcc@9.4.0 build_system=generic arch=linux-ubuntu20.04-icelake
 -       ^geos@3.12.2%gcc@9.4.0~ipo+shared build_system=cmake build_type=Release generator=ninja arch=linux-ubuntu20.04-icelake
[e]      ^glibc@2.31%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^json-c@0.16%gcc@9.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-icelake
 -       ^libgeotiff@1.7.1%gcc@9.4.0+jpeg+proj+zlib build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^libjpeg-turbo@3.0.0%gcc@9.4.0~ipo~jpeg8~partial_decoder+pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-ubuntu20.04-icelake
 -           ^nasm@2.15.05%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^libpng@1.6.39%gcc@9.4.0~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-ubuntu20.04-icelake
 -       ^libtiff@4.6.0%gcc@9.4.0+ccitt~ipo~jbig+jpeg~jpeg12~lerc~libdeflate+logluv~lzma+lzw+next~old-jpeg+packbits~pic~pixarlog+shared+thunder~webp+zlib~zstd build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-icelake
 -       ^ninja@1.12.0%gcc@9.4.0+re2c build_system=generic arch=linux-ubuntu20.04-icelake
 -           ^python@3.11.9%gcc@9.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu20.04-icelake
 -               ^gettext@0.22.5%gcc@9.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu20.04-icelake
 -                   ^libxml2@2.10.3%gcc@9.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu20.04-icelake
 -                   ^tar@1.34%gcc@9.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-icelake
 -                       ^pigz@2.8%gcc@9.4.0 build_system=makefile arch=linux-ubuntu20.04-icelake
 -                       ^zstd@1.5.6%gcc@9.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-icelake
 -               ^libffi@3.4.6%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -               ^libxcrypt@4.4.35%gcc@9.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-icelake
 -               ^util-linux-uuid@2.40.1%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -               ^xz@5.4.6%gcc@9.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-icelake
 -           ^re2c@2.2%gcc@9.4.0 build_system=generic arch=linux-ubuntu20.04-icelake
 -       ^pkgconf@2.2.0%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^proj@9.4.1%gcc@9.4.0+curl~ipo~pic+shared+tiff build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-icelake
 -       ^sqlite@3.43.2%gcc@9.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-icelake
 -           ^readline@8.2%gcc@9.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-icelake
 -       ^zlib-ng@2.1.6%gcc@9.4.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu20.04-icelake

```

**Comment by wglanfield-rms** [comment]
So do you want the output from "spack spec info"? I'm relatively new to spack having inherited it in my new role.

If so......................basically the same as the install error

[hpcadmin@ukvmlx-head-02 ~]$ spack spec gdal
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gdal is unsatisfiable

**Comment by alalazo** [comment]
No, I mean. I can concretize `gdal` (see above) - so it's something specific about your configuration. Can you post the output of `spack config blame` ?
