### ISSUE TITLE
Installation issue: snakemake run time error

### ISSUE THREAD

**Issue by potter-s** [LLNL/spack#44944]
### Steps to reproduce the issue

```
$ spack spec -I <spec>
Input spec
--------------------------------
 -   snakemake@8.14.0

Concretized
--------------------------------
[+]  ckobjl4  snakemake@8.14.0%gcc@11.4.0~ftp~google-cloud~http~reports~s3 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  sh6gyz6      ^py-appdirs@1.4.4%gcc@11.4.0 build_system=python_pip patches=006d203 arch=linux-ubuntu22.04-x86_64_v3
[+]  i4ufjpu      ^py-configargparse@1.2.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  uie2anr      ^py-connectionpool@0.0.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  hcgqkqy      ^py-datrie@0.8.2%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  5elbfgt          ^py-cython@0.29.36%gcc@11.4.0 build_system=python_pip patches=c4369ad arch=linux-ubuntu22.04-x86_64_v3
[+]  r735hd2          ^py-pytest-runner@6.0.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  qdwtwbn              ^py-setuptools-scm@7.1.0%gcc@11.4.0+toml build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  juc3z3y                  ^git@2.42.0%gcc@11.4.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  mnfnoa5                      ^autoconf@2.69%gcc@11.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu22.04-x86_64_v3
[+]  d3cncgl                      ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  ijsmc3j                      ^curl@8.4.0%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu22.04-x86_64_v3
[+]  my64owh                          ^nghttp2@1.57.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  hayvt3w                      ^libidn2@2.3.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  2bbbduc                          ^libunistring@1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  rgag55h                      ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  jnv5nut                      ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-x86_64_v3
[+]  zuopqri                          ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  zjwxy3z                      ^openssh@9.5p1%gcc@11.4.0+gssapi build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  tjiqlym                          ^krb5@1.20.1%gcc@11.4.0+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  lza42n2                              ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  cws3eft                              ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu22.04-x86_64_v3
[+]  s4kq4wo                          ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  bhevh4b                      ^pcre2@10.42%gcc@11.4.0~jit+multibyte build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  qdjqac2                  ^py-tomli@2.0.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  wtghaxf                  ^py-typing-extensions@4.8.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  vnwp34y      ^py-docutils@0.20.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  tbgkayq      ^py-gitpython@3.1.27%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  bumxtbo          ^py-gitdb@4.0.9%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  c4qjxef              ^py-smmap@5.0.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  lunyss7      ^py-humanfriendly@10.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  duwicax      ^py-jinja2@3.1.2%gcc@11.4.0~i18n build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  ryskg62          ^py-markupsafe@2.1.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  itzuwp4      ^py-jsonschema@4.17.3%gcc@11.4.0~format-nongpl build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  64vjzlj          ^py-attrs@23.1.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  nhnzoe4          ^py-hatch-fancy-pypi-readme@23.1.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3ga75ui          ^py-hatch-vcs@0.3.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  onenij5          ^py-hatchling@1.18.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  usxnklc              ^py-editables@0.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  7i4lufl              ^py-packaging@23.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3ggwskh              ^py-pathspec@0.11.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  2hmrsvl              ^py-pluggy@1.0.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  b7ypdwb              ^py-trove-classifiers@2023.8.7%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  ctq6ywc                  ^py-calver@2022.6.26%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  e75w55f          ^py-pyrsistent@0.19.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  g3oljms      ^py-nbformat@5.8.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  cxesiu5          ^py-fastjsonschema@2.16.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  f5sx3tr          ^py-hatch-nodejs-version@0.3.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  hjisbyz          ^py-jupyter-core@5.3.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  qj64vtw              ^py-platformdirs@3.10.0%gcc@11.4.0~wheel build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  qlc5ex3          ^py-traitlets@5.9.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  g5rag64      ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  5ndb5xd      ^py-psutil@5.9.5%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  mg4w2va      ^py-pulp@2.6.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3nh6at6      ^py-pyyaml@6.0%gcc@11.4.0+libyaml build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  5idu6no          ^libyaml@0.2.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  znvoani              ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  ksif2vy      ^py-requests@2.31.0%gcc@11.4.0~socks build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  faibycl          ^py-certifi@2023.7.22%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  mi3ex42          ^py-charset-normalizer@3.3.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  7xvdcaf          ^py-idna@3.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  bcaefvn              ^py-flit-core@3.9.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  4mgfvd7          ^py-urllib3@2.0.6%gcc@11.4.0~brotli~secure~socks build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3kj2ha5      ^py-reretry@0.11.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  kfhb262          ^py-pbr@5.10.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  e4rc5s3      ^py-setuptools@68.0.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  idmkljw      ^py-smart-open@5.2.1%gcc@11.4.0~azure~gcs+http~s3 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  5c5yh6c      ^py-stopit@1.1.2%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3b63fn6      ^py-tabulate@0.8.9%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  qgs277c      ^py-throttler@1.2.2%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  sguwfgx      ^py-toposort@1.6%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  e7tv4cz      ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  uxiuo5k      ^py-wrapt@1.15.0%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  6k7nj4m      ^py-yte@1.5.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  fajvfol          ^py-dpath@2.0.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  3rfl7c3          ^py-plac@1.3.5%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  uplmzhu          ^py-poetry-core@1.6.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]  ybsi7tl      ^python@3.11.6%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-x86_64_v3
[+]  4oz3kpf          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  ueheij3              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  demnlle          ^expat@2.5.0%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  nrlj4tj              ^libbsd@0.11.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  kg5ets2                  ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  m626hzw          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  y26lmlo          ^gettext@0.22.3%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  ivn4eq4              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]  67qoxbv              ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  vdb3ozo              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-x86_64_v3
[+]  catlxmo                  ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-x86_64_v3
[+]  jkznmrm                  ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]  ra2t3ha          ^libffi@3.4.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  hezcx7g          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-x86_64_v3
[+]  dg34i2a              ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-x86_64_v3
[+]  ku7makq                  ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-x86_64_v3
[+]  qqlh6as          ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  35j7wvr          ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-x86_64_v3
[+]  ct4al4u              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]  zjgtpdo          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  xxgqlmj          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-x86_64_v3
[+]  m2h5dly          ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  thv4zdp          ^util-linux-uuid@2.38.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]  axxqoeq          ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]  5xcetrv          ^zlib-ng@2.1.4%gcc@11.4.0+compat+opt build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
```

### Error message

<details><summary>run time error: No module named 'snakemake_interface_common'</summary>

<pre>
$ snakemake
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/snakemake-8.14.0-ckobjl4oi5rpnooxyclrq2x6r7ro6lzm/bin/snakemake", line 7, in <module>
    from snakemake.cli import main
  File "/home/spack/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/snakemake-8.14.0-ckobjl4oi5rpnooxyclrq2x6r7ro6lzm/lib/python3.11/site-packages/snakemake/__init__.py", line 7, in <module>
    from snakemake.common import __version__, PIP_DEPLOYMENTS_PATH
  File "/home/spack/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/snakemake-8.14.0-ckobjl4oi5rpnooxyclrq2x6r7ro6lzm/lib/python3.11/site-packages/snakemake/common/__init__.py", line 22, in <module>
    from snakemake_interface_common.exceptions import WorkflowError
ModuleNotFoundError: No module named 'snakemake_interface_common'
</pre></details>

NB this happens with all v. 8.x, but not with the latest 
[spack-build-env.txt](https://github.com/user-attachments/files/16028236/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/16028237/spack-build-out.txt)
7.x

### Information on your system

```
* **Spack:** 0.21.0 (65d3221a9c436e77af9e802e543c71bd702ff4e2)
* **Python:** 3.11.6
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo
```

### Additional information

The build works fine, it is only a run time issue and appears specific to v 8. Used Spack 0.21.0 and also 0.21.2, thanks in advance for any help @adamjstewart and @marcusboden .

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by w8jcik** [comment]
Dependencies of Snakemake keep changing, so one cannot just install a newer version without altering the package.

The last described Snakemake version in the repository is 8.5.2
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/snakemake/package.py

This branch adds 8.11.4 https://github.com/spack/spack/pull/43437/files.

Similar update is possible for 8.14.0.

**Comment by potter-s** [comment]
Thanks for your response and work in trying to get the package working. It must be very frustrating for your PRs not to be accepted. Interestingly I get a similar issue trying to run v 8.5.2 however. I wonder if there's a dependency missing there too. There is a package for this: https://pypi.org/project/snakemake-interface-common/.

Simon

**Comment by potter-s** [comment]
Thanks for your response. Interestingly I get a similar issue trying to run v 8.5.2 however. I wonder if there's a dependency missing there too. There is a package for this: https://pypi.org/project/snakemake-interface-common/.

Simon

**Comment by w8jcik** [comment]
There were some changes to handling of Python in Spack. It is probably not related, but could you try calling Snakemake as a module? Does it change anything?

```
python -m snakemake
```

Regarding `py-snakemake-interface-common`: The package is present in Spack and listed as dependency.

**Comment by w8jcik** [comment]
It is a while since this issue was opened. Maybe it got fixed with Spack update or package recipe update.

Based on the fact that I am using this package without import errors, I am closing this issue for now.

Feel free to reopen if you test latest Spack version (`develop` branch or some 0.23 release in the future) and still experience import error.
