### ISSUE TITLE
spack checksum circular import

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#45156]
### Steps to reproduce

```console
> spack checksum zlib 1.3.1
```
Note that the error does not occur unless a single version is requested. The error does not occur for 0 versions or 2+ versions, or if the `@` sigil is used.

### Error message

```console
> spack checksum zlib 1.3.1
==> Found 1 version of zlib
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/python-3.11.6-7kc3atdlybs3ishfi7zhmy3zhjvulalv/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/python-3.11.6-7kc3atdlybs3ishfi7zhmy3zhjvulalv/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/python-3.11.6-7kc3atdlybs3ishfi7zhmy3zhjvulalv/lib/python3.11/concurrent/futures/process.py", line 249, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/python-3.11.6-7kc3atdlybs3ishfi7zhmy3zhjvulalv/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/lib/spack/spack/stage.py", line 34, in <module>
    import spack.caches
  File "/Users/Adam/spack/lib/spack/spack/caches.py", line 14, in <module>
    import spack.config
  File "/Users/Adam/spack/lib/spack/spack/config.py", line 42, in <module>
    import spack.compilers
  File "/Users/Adam/spack/lib/spack/spack/compilers/__init__.py", line 22, in <module>
    import spack.compiler
  File "/Users/Adam/spack/lib/spack/spack/compiler.py", line 24, in <module>
    import spack.spec
  File "/Users/Adam/spack/lib/spack/spack/spec.py", line 76, in <module>
    import spack.hash_types as ht
  File "/Users/Adam/spack/lib/spack/spack/hash_types.py", line 8, in <module>
    import spack.repo
  File "/Users/Adam/spack/lib/spack/spack/repo.py", line 575, in <module>
    class RepoIndex:
  File "/Users/Adam/spack/lib/spack/spack/repo.py", line 593, in RepoIndex
    cache: spack.caches.FileCacheType,
           ^^^^^^^^^^^^
AttributeError: cannot access submodule 'caches' of module 'spack' (most likely due to a circular import)
==> Error: A process in the process pool was terminated abruptly while the future was running or pending.
```

### Information on your system

* **Spack:** 0.23.0.dev0 (cef9c36183eb627898d5f12590fba4327198872e)
* **Python:** 3.11.6
* **Platform:** darwin-sonoma-m2
* **Concretizer:** clingo

@alecbcs and @haampie have done the most work on `spack checksum` recently and may be able to quickly debug this.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mathomp4** [comment]
@adamjstewart I can't ever get it *not* to crash. I've been trying to do `spack checksum gftl` and once I try any checksum it crashes. If I ask for 2 versions, one version, all versions...always crash.

ETA: Note, my spack is picking up the Python 3.12 from homebrew, so it seems to not be python version dependent (between 3.11 and 3.12 at least).

**Comment by adamjstewart** [comment]
I noticed something similar to this if I change the URL or try to create a new package.

**Comment by alecbcs** [comment]
Performed a git bisect and found the offending commit to be `95cf341b5064608650ccdd67f5fed35ba6c56a7d` or #45053.

@alalazo do you know what might be going on here?

**Comment by alalazo** [comment]
> do you know what might be going on here?

It seems a circular import due to the type hint, which was not caught in CI :sweat: The underlying cause is our abuse of globals, and the fact that globals are spread around different modules. Let me fix it.

**Comment by alalazo** [comment]
It also seems to be platform dependent:
```console
$ spack checksum zlib 1.3.1
==> Found 1 version of zlib
==> Fetching http://zlib.net/fossils/zlib-1.3.1.tar.gz

    version("1.3.1", sha256="9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23")

```
on:
* **Spack:** 0.23.0.dev0 (60e75c92348749bedfcfc64b88d11ebd61c1a7c5)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Comment by alalazo** [comment]
I just want to leave this quote here https://github.com/golang/go/issues/30247#issuecomment-463940936 :slightly_smiling_face:

**Comment by adamjstewart** [comment]
Oh how I wish that quote also applied to dependency cycles in the Python ecosystem... (I'm looking at you TensorFlow).
