### ISSUE TITLE
spack checksum does not find latest package version on PyPI

### ISSUE THREAD

**Issue by lgorenstein** [LLNL/spack#45186]
### Steps to reproduce

Aiming to add new versions for `py-globus-sdk`, I noticed that `spack checksum --latest` only finds an older 3.39.0:

```console
$ bin/spack checksum -b --latest py-globus-sdk
==> Found 1 version of py-globus-sdk
==> Fetching https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.39.0.tar.gz

    version("3.39.0", sha256="10af5291ba261e817665d5951948206232ecebccdc2aa8adc0528f0031ab80c3")
```

and does _not_ find the current 3.41.0:

```console
$ bin/spack checksum -b py-globus-sdk 3.41.0
==> Error: Could not find any remote versions for py-globus-sdk
```

### Error message

The `globus-sdk` on PyPI *[has](https://pypi.org/project/globus-sdk/#history)* 3.39.0, 3.40.0 and 3.41.0 versions (with 3.41.0 being the latest).

The interesting part is that attempts to manually pull the URL fail for 3.41.0 (note the zero size):
```console
$ curl -LO https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.39.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  195k  100  195k    0     0   628k      0 --:--:-- --:--:-- --:--:--  628k

$ curl -LO https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.41.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

$ ls -l globus-sdk-3.*
-rw-r--r-- 1 lev lev 200513 Jul  9 19:42 globus-sdk-3.39.0.tar.gz
-rw-r--r-- 1 lev lev      0 Jul  9 19:43 globus-sdk-3.41.0.tar.gz
```

At the same time, the _"Download files"_ sections on PyPI has a fully-functioning download [link](https://files.pythonhosted.org/packages/ee/8c/f7af8a2d90d10b9f05f4d08bfd6faaf53f1cc52d4be19a9701a6bad40554/globus_sdk-3.41.0.tar.gz) with a very long hash instead of the `/source/g/globus-sdk/` path) 

------------

So it looks like _something_ has changed on PyPI and `spack checksum` is no longer able to decipher correct download link?

Here's a full stack trace for completeness:
```console
$ spack --debug --stacktrace checksum py-globus-sdk 3.41.0
lib/spack/spack/config.py:1123 ==> [2024-07-10-20:00:27.752382] Reading config from file /home/lev/repos/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-07-10-20:00:27.792104] Imported checksum from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-07-10-20:00:27.792896] Imported checksum from built-in commands
lib/spack/spack/config.py:1123 ==> [2024-07-10-20:00:27.795617] Reading config from file /home/lev/repos/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1123 ==> [2024-07-10-20:00:27.808693] Reading config from file /home/lev/repos/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1123 ==> [2024-07-10-20:00:27.840388] Reading config from file /home/lev/repos/spack/etc/spack/defaults/linux/packages.yaml
lib/spack/spack/util/web.py:434 ==> [2024-07-10-20:00:27.974788] Checking existence of https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.41.0.tar.gz
lib/spack/spack/util/web.py:71 ==> [2024-07-10-20:00:27.975460] certs: relative path not allowed: $SSL_CERT_FILE
lib/spack/spack/util/web.py:462 ==> [2024-07-10-20:00:28.335415] Failure reading URL: HEAD https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.41.0.tar.gz returned 404: Not Found
lib/spack/spack/util/web.py:640 ==> [2024-07-10-20:00:28.352606] SPIDER: [depth=0, max_depth=0, urls=3]
lib/spack/spack/util/web.py:765 ==> [2024-07-10-20:00:28.604823] SPIDER: [url=ParseResult(scheme='https', netloc='pypi.org', path='/simple/globus-sdk/', params='', query='', fragment='')]
lib/spack/spack/util/web.py:762 ==> [2024-07-10-20:00:28.660636] Error in _spider: <class 'spack.util.web.SpackWebError'>:Download failed: GET https://files.pythonhosted.org/packages/source/g/globus-sdk returned 404: Not Found
  Traceback (most recent call last):
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 199, in read_from_url
    response = urlopen(request)
  File "/home/lev/repos/spack/lib/spack/llnl/util/lang.py", line 763, in __call__
    return self.instance(*args, **kwargs)
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 135, in dispatch_open
    return opener.open(fullurl, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 61, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://files.pythonhosted.org/packages/source/g/globus-sdk returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 683, in _spider
    response_url, _, response = read_from_url(url, "text/html")
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 201, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://files.pythonhosted.org/packages/source/g/globus-sdk returned 404: Not Found

lib/spack/spack/util/web.py:765 ==> [2024-07-10-20:00:28.662633] SPIDER: [url=ParseResult(scheme='https', netloc='files.pythonhosted.org', path='/packages/source/g/globus-sdk', params='', query='', fragment='')]
lib/spack/spack/util/web.py:762 ==> [2024-07-10-20:00:28.667224] Error in _spider: <class 'spack.util.web.SpackWebError'>:Download failed: GET https://files.pythonhosted.org/packages/source/g/globus-sdk/ returned 404: Not Found
  Traceback (most recent call last):
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 199, in read_from_url
    response = urlopen(request)
  File "/home/lev/repos/spack/lib/spack/llnl/util/lang.py", line 763, in __call__
    return self.instance(*args, **kwargs)
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 135, in dispatch_open
    return opener.open(fullurl, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 61, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://files.pythonhosted.org/packages/source/g/globus-sdk/ returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 683, in _spider
    response_url, _, response = read_from_url(url, "text/html")
  File "/home/lev/repos/spack/lib/spack/spack/util/web.py", line 201, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://files.pythonhosted.org/packages/source/g/globus-sdk/ returned 404: Not Found

lib/spack/spack/util/web.py:765 ==> [2024-07-10-20:00:28.668496] SPIDER: [url=ParseResult(scheme='https', netloc='files.pythonhosted.org', path='/packages/source/g/globus-sdk/', params='', query='', fragment='')]
lib/spack/spack/cmd/checksum.py:157 ==> [2024-07-10-20:00:28.842513] Error: Could not find any remote versions for py-globus-sdk
Traceback (most recent call last):
  File "/home/lev/repos/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
  File "/home/lev/repos/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/lev/repos/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/lev/repos/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/home/lev/repos/spack/lib/spack/spack/cmd/checksum.py", line 157, in checksum
    tty.die(f"Could not find any remote versions for {pkg.name}")
  File "/home/lev/repos/spack/lib/spack/llnl/util/tty/__init__.py", line 249, in die
    sys.exit(1)
SystemExit: 1
```

### Information on your system

Freshly-cloned develop branch. Ubuntu 22.04 VM on Windows 11 under WSL2.

* **Spack:** 0.23.0.dev0 (09b89e87a461f5a9492df9759849e48ae0e4c335)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by lgorenstein** [comment]
Looks like this stems from a difference between `-` and `_` in package names.

Older versions (up to 3.39.0) are recognized with a `-` (`globus-sdk`):
```console
$ curl -sI https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.39.0.tar.gz | grep location || echo "Not found"
location: https://files.pythonhosted.org/packages/c4/c8/3260a14651d768fdd67fcaef9341f0999a860fe24956ec966d45e9ed73cf/globus-sdk-3.39.0.tar.gz

$ curl -sI https://files.pythonhosted.org/packages/source/g/globus_sdk/globus_sdk-3.39.0.tar.gz | grep location || echo "Not found"
Not found
```

And newer ones require a `_` instead (`globus_sdk`):
```console
$ curl -sI https://files.pythonhosted.org/packages/source/g/globus-sdk/globus-sdk-3.41.0.tar.gz | grep location || echo "Not found"
Not found

$ curl -sI https://files.pythonhosted.org/packages/source/g/globus_sdk/globus_sdk-3.41.0.tar.gz | grep location || echo "Not found"
location: https://files.pythonhosted.org/packages/ee/8c/f7af8a2d90d10b9f05f4d08bfd6faaf53f1cc52d4be19a9701a6bad40554/globus_sdk-3.41.0.tar.gz
```

**Comment by sirosen** [comment]
:wave: Hi all, globus-sdk maintainer here (@lgorenstein and I have the pleasure of working together)!

I've been bitten by changes from `-` to `_` recently in some builds due to a change in `setuptools` or maybe one of its dependencies like `importlib_metadata`. I can't recall the exact details, but the long and short is that there have been some recent  changes in the packaging toolchain which impact dist filenames.
As our team has discussed, this is actually a fix -- using underscores is what [the spec requires (PEP 491)](https://peps.python.org/pep-0491/#escaping-and-unicode).

My understanding of this issue is that this _may_ be revealing an underlying unsafe assumption about the mapping of a project name to the sdist filenames. The main alternative I can imagine, not knowing how Spack works, is that the expected dist filename pattern is provided somewhere explicitly in package metadata, and needs to be corrected.

We're generally happy to take feedback about our packaging, and if there's info we can provide we're definitely ready and willing to help out by answering questions! We can also make some changes to our package within reason, but I can't make promises about what we'd be willing to do. (For example, reverting back to an older version of `setuptools` to produce non-spec-compliant dist filenames again is not an option I'm considering here.)

**Comment by haampie** [comment]
We should use the PyPI API if we're not already, instead of using a generic web spider (edit: for discovering new versions)

But yeah, lack of proper normalization in pypi is a pain, I ran into that before: https://github.com/pypi/conveyor/issues/23. The other thing is if you have a one-off version, we need to edit `url_for_version` to deal with it, there's no way to download by (unambiguous) shasum.

**Comment by wdconinc** [comment]
I filed #45349 for the `py-globus-sdk` updates.

@haampie I don't think there's an issue yet for "use PyPI API for PythonPackage instead of spider". Do you want this issue to become that issue?
