### ISSUE TITLE
Spack install from custom repo on macOS Sonoma M1 broken

### ISSUE THREAD

**Issue by japlews** [LLNL/spack#45197]
### Steps to reproduce

Create a trivial repo, or, e.g., use `tutorial`, with some package with minimal dependencies.
```console
$ spack env create -d my-env
$ spack env activate ./my-env
$ spack repo add <trivial-external-repo>
$ spack add <package-from-trivial-external-repo>
$ spack concretize -f # succeeds
$ spack install # fails
```

### Error message

For instance, using the `tutorial` repo and `hdf5` package
```console
$ spack install
lib/spack/spack/error.py:52 ==> [2024-07-11-11:57:16.407226] Error: ModuleNotFoundError: No module named 'spack.pkg.tutorial'
lib/spack/spack/installer.py:1850 ==> [2024-07-11-11:57:16.407417] Flagging hdf5-1.10.7-w5tapn2w2btdzjzqo2tbq34jxqvac75y as failed: expected str, bytes or os.PathLike object, not NoneType
lib/spack/spack/installer.py:2161 ==> [2024-07-11-11:57:16.408917] Error: Failed to install hdf5 due to TypeError: expected str, bytes or os.PathLike object, not NoneType
lib/spack/spack/config.py:1117 ==> [2024-07-11-11:57:16.414947] Reading config from file /Users/japlews/Work/github/tutorial/spack.yaml
lib/spack/spack/environment/environment.py:248 ==> [2024-07-11-11:57:16.416179] Deactivated environment '/Users/japlews/Work/github/tutorial'
lib/spack/spack/environment/environment.py:224 ==> [2024-07-11-11:57:16.418999] Using environment '/Users/japlews/Work/github/tutorial'
lib/spack/spack/util/executable.py:233 ==> [2024-07-11-11:57:16.422091] '/opt/homebrew/bin/git' '-C' '/Users/japlews/Work/github/spack' 'rev-parse' 'HEAD'
lib/spack/spack/environment/environment.py:777 ==> [2024-07-11-11:57:16.436828] View at /Users/japlews/Work/github/tutorial/.spack-env/view does not need regeneration.
Traceback (most recent call last):
  File "/Users/japlews/Work/github/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/cmd/install.py", line 352, in install
    install_with_active_env(env, args, install_kwargs, reporter_factory)
  File "/Users/japlews/Work/github/spack/lib/spack/spack/cmd/install.py", line 423, in install_with_active_env
    env.install_specs(specs_to_install, **install_kwargs)
  File "/Users/japlews/Work/github/spack/lib/spack/spack/environment/environment.py", line 1969, in install_specs
    PackageInstaller([spec.package for spec in specs], install_args).install()
  File "/Users/japlews/Work/github/spack/lib/spack/spack/installer.py", line 2116, in install
    self._install_task(task, install_status)
  File "/Users/japlews/Work/github/spack/lib/spack/spack/installer.py", line 1669, in _install_task
    spack.package_base.PackageBase._verbose = spack.build_environment.start_build_process(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/build_environment.py", line 1313, in start_build_process
    child_result.print_context()
  File "/Users/japlews/Work/github/spack/lib/spack/spack/error.py", line 53, in print_context
    if self.long_message:
       ^^^^^^^^^^^^^^^^^
  File "/Users/japlews/Work/github/spack/lib/spack/spack/build_environment.py", line 1477, in long_message
    test_log = join_path(os.path.dirname(self.log_name), spack_install_test_log)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 181, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Also worth noting that reverting commit 95cf341b5064608650ccdd67f5fed35ba6c56a7d on #45053 fixed this for me.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.23.0.dev0 (cea1d8b9359c9004f809eb48b3a73f1956bcf51b)
* **Python:** 3.12.4
* **Platform:** darwin-sonoma-m1
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I can reproduce on:

* **Spack:** 0.23.0.dev0 (2aa6939b9627d4f1a46596feb71997b9551581a4)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

More specifically, all the installations from `builtin` go fine, while `tutorial.hdf5` fails with:
```
Traceback (most recent call last):
  File "/Users/spack-bootstrap-runner/github/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/cmd/install.py", line 352, in install
    install_with_active_env(env, args, install_kwargs, reporter_factory)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/cmd/install.py", line 423, in install_with_active_env
    env.install_specs(specs_to_install, **install_kwargs)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/environment/environment.py", line 1969, in install_specs
    PackageInstaller([spec.package for spec in specs], install_args).install()
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/installer.py", line 2116, in install
    self._install_task(task, install_status)
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/installer.py", line 1669, in _install_task
    spack.package_base.PackageBase._verbose = spack.build_environment.start_build_process(
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/build_environment.py", line 1313, in start_build_process
    child_result.print_context()
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/error.py", line 53, in print_context
    if self.long_message:
  File "/Users/spack-bootstrap-runner/github/spack/lib/spack/spack/build_environment.py", line 1477, in long_message
    test_log = join_path(os.path.dirname(self.log_name), spack_install_test_log)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Working on a fix.

**Comment by alalazo** [comment]
This seems to be the relevant part:
```
lib/spack/spack/error.py:52 ==> [2024-07-11-11:57:16.407226] Error: ModuleNotFoundError: No module named 'spack.pkg.tutorial'
```
The custom repository is not reconstructed correctly in the child process.

**Comment by alalazo** [comment]
@japlews See #45229 Can you confirm it fixes the issue also for you?

**Comment by japlews** [comment]
@alalazo Yes, confirmed that works! Thanks for the quick fix.
