### ISSUE TITLE
Unable to install re2c package

### ISSUE THREAD

**Issue by Controlsim** [LLNL/spack#45343]
### Steps to reproduce

Run following command 👍 (Package is listed in spack's standard package list)
spack install re2c@3.1.2

### Error message

Error: FetchError: All fetchers failed for re2c-3.0-nizmxiv

System Information
Operating System: Windows 10, version 19045
Compilers: MSVC v19.40.33812
Spack Version: 0.23.0.dev0
Python Version: 3.11.9

### Information on your system

$ spack -d install re2c
==> [2024-07-20-20:35:15.243460] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/config.yaml
==> [2024-07-20-20:35:15.274460] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/windows/config.yaml
==> [2024-07-20-20:35:16.204108] Imported install from built-in commands
==> [2024-07-20-20:35:16.210173] Imported install from built-in commands
==> [2024-07-20-20:35:16.213173] DATABASE LOCK TIMEOUT: 60s
==> [2024-07-20-20:35:16.213173] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-07-20-20:35:16.214173] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/concretizer.yaml
==> [2024-07-20-20:35:16.236821] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/packages.yaml
==> [2024-07-20-20:35:16.310823] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/windows/packages.yaml
==> [2024-07-20-20:35:16.326830] Reading config from file C:/Users/deepa/.spack/packages.yaml
==> [2024-07-20-20:35:16.336829] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/repos.yaml
==> [2024-07-20-20:35:21.832600] DATABASE LOCK TIMEOUT: 60s
==> [2024-07-20-20:35:21.832600] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-07-20-20:35:21.837509] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/mirrors.yaml
==> [2024-07-20-20:35:22.073626] DATABASE LOCK TIMEOUT: 60s
==> [2024-07-20-20:35:22.074625] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-07-20-20:35:22.075626] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/bootstrap.yaml
==> [2024-07-20-20:35:22.176187] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/repos.yaml
==> [2024-07-20-20:35:22.183175] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/packages.yaml
==> [2024-07-20-20:35:22.230172] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/windows/packages.yaml
==> [2024-07-20-20:35:22.237175] Reading config from file C:/Users/deepa/.spack/packages.yaml
==> [2024-07-20-20:35:22.242180] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-07-20-20:35:22.244176] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/bootstrap.yaml
==> [2024-07-20-20:35:22.254178] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=C:/msys64/home/deepa/s
pack/etc/spack/defaults
==> [2024-07-20-20:35:22.255178] [BOOTSTRAP CONFIG SCOPE] name=defaults/windows, path=C:/msys64/home
/deepa/spack/etc/spack/defaults/windows
==> [2024-07-20-20:35:22.256175] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=C:/Users/deepa/.spack
/bootstrap/config
==> [2024-07-20-20:35:22.256175] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/windows, path=C:/Users/deep
a/.spack/bootstrap/config/windows
==> [2024-07-20-20:35:22.259170] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/config.yaml
==> [2024-07-20-20:35:22.289171] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/windows/config.yaml
==> [2024-07-20-20:35:22.299175] Reading config from file C:/Users/deepa/.spack/bootstrap/config/win
dows/config.yaml
==> [2024-07-20-20:35:22.331174] DATABASE LOCK TIMEOUT: 60s
==> [2024-07-20-20:35:22.332175] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-07-20-20:35:22.333175] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/packages.yaml
==> [2024-07-20-20:35:22.386177] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/windows/packages.yaml
==> [2024-07-20-20:35:22.392172] Reading config from file C:/Users/deepa/.spack/bootstrap/config/pac
kages.yaml
==> [2024-07-20-20:35:22.416172] Reading config from file C:/Users/deepa/.spack/bootstrap/config/win
dows/compilers.yaml
==> [2024-07-20-20:35:22.473032] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %msvc platform=
windows target=x86_64
==> [2024-07-20-20:35:22.474034] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-07-20-20:35:22.477034] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/bootstrap.yaml
==> [2024-07-20-20:35:22.710006] Bootstrapping clingo from pre-built binaries
==> [2024-07-20-20:35:22.726005] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defau
lts/mirrors.yaml
==> [2024-07-20-20:35:22.735007] Checking existence of https://mirror.spack.io/bootstrap/github-acti
ons/v0.5/build_cache/index.json
==> [2024-07-20-20:35:22.736005] certs: relative path not allowed: $SSL_CERT_FILE
==> [2024-07-20-20:35:23.193943] Failure reading URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED
] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
==> [2024-07-20-20:35:23.283020] Bootstrapping clingo from pre-built binaries
==> [2024-07-20-20:35:23.363984] Checking existence of https://mirror.spack.io/bootstrap/github-acti
ons/v0.4/build_cache/index.json
==> [2024-07-20-20:35:23.411988] Failure reading URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED
] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
==> [2024-07-20-20:35:23.424986] Bootstrapping clingo from sources
==> [2024-07-20-20:35:39.518081] curl applying constraint zlib-api
==> [2024-07-20-20:35:39.561082] cmake applying constraint zlib-api
==> [2024-07-20-20:35:39.564081] cmake applying constraint curl
==> [2024-07-20-20:35:39.567082] cmake applying constraint zlib-api
==> [2024-07-20-20:35:39.573083] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.592082] python-venv applying constraint python
==> [2024-07-20-20:35:39.601083] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:39.607084] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.609083] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:39.612083] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:39.615083] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:39.647081] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:39.650081] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.651082] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:39.652083] python-venv applying constraint python
==> [2024-07-20-20:35:39.654081] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:39.655081] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:39.664081] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:39.666081] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.668083] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:39.670083] python-venv applying constraint python
==> [2024-07-20-20:35:39.672082] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:39.674082] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:39.847088] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:39.942087] ninja applying constraint python
==> [2024-07-20-20:35:39.950087] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.955082] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:39.957088] python-venv applying constraint python
==> [2024-07-20-20:35:39.960088] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:39.962090] re2c applying constraint cmake
==> [2024-07-20-20:35:39.965083] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:39.968083] winbison applying constraint cmake
==> [2024-07-20-20:35:39.971087] winbison applying constraint ninja
==> [2024-07-20-20:35:39.975088] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:39.981082] clingo-bootstrap applying constraint ninja
==> [2024-07-20-20:35:39.984082] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:39.989080] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:39.993083] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:39.997083] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:40.151089] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2024-07-20-20:35:40.157081] clingo-bootstrap applying constraint ninja
==> [2024-07-20-20:35:40.159089] ninja applying constraint python
==> [2024-07-20-20:35:40.163081] clingo-bootstrap applying constraint python
==> [2024-07-20-20:35:40.165081] clingo-bootstrap applying constraint python-venv
==> [2024-07-20-20:35:40.168083] python-venv applying constraint python
==> [2024-07-20-20:35:40.171083] clingo-bootstrap applying constraint re2c@0.13:
==> [2024-07-20-20:35:40.172083] re2c applying constraint cmake
==> [2024-07-20-20:35:40.175088] clingo-bootstrap applying constraint winbison@2.4.12:
==> [2024-07-20-20:35:40.178083] winbison applying constraint cmake
==> [2024-07-20-20:35:40.181087] winbison applying constraint ninja
==> [2024-07-20-20:35:40.583084] Ordered hashes [clingo-bootstrap]: clingo-bootstrap/5/4ccfd173d439e
d1e23eff42d5a01a8fbb21341c632d86b5691242dc270dbf065, clingo-bootstrap/6/311bd2ae3f2f5274d1d36a2d65f8
87dfdf4c309a3c6bb29a53bbafb82b42ba7a, clingo-bootstrap/7/c5c4db292a920ded6eecfbb6749d88ce9c4f179500a
ee6aee3a417b93c7c5c7a
==> [2024-07-20-20:35:40.584081] Ordered hashes [cmake]: cmake/28/d041289e3e9483cbdbbac46705a1fb01a7
c40a8fc13e291229fb4fa2b071369b
==> [2024-07-20-20:35:40.585081] Ordered hashes [python]: python/14/01b5df08776d2c3ffeb75da4ccff144c
d554b63fcf9962f27c6ecb5fca06a33d, python/15/fc5b6c586b1b654ac2ed00ba6417b1eb526bd24a0dc28074ce14ff56
f6057f7c, python/20/bccfd87e518d2ebc1dafe5d009b9071c046fe8400d52d2f0283bda6904c4dbf1, python/21/7abb
961432aa530349755d639c2902a342f3b5744d11103901e0acf88fae533e
==> [2024-07-20-20:35:41.286088] [BOOTSTRAP MODULE clingo] Try installing 'clingo-bootstrap@spack+py
thon %msvc platform=windows target=x86_64' from sources
==> [2024-07-20-20:35:41.288090] Initializing the build queue from the build requests
==> [2024-07-20-20:35:41.288090] Initializing the build queue for clingo-bootstrap
==> [2024-07-20-20:35:41.296088] Pkg id cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6 has the
 following dependents:
==> [2024-07-20-20:35:41.297088] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.297088] - re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g
==> [2024-07-20-20:35:41.298088] - winbison-2.5.25-3xtcqo4cauinbkytcok7iqhv6uljzw6q
==> [2024-07-20-20:35:41.323090] Requeueing a build task for cmake-3.28.3-msvc11-ptf373demmkmhl3tjzv
qg2zoj3mxzyl6 with status 'queued'
==> [2024-07-20-20:35:41.326082] Pkg id python-3.11.9-r7uewr7spwhnhe3nxrvqupvrqadoobon has the follo
wing dependents:
==> [2024-07-20-20:35:41.326082] - python-venv-1.0-7hy6byljqwdb2olijqvk5cl5sb6bighq
==> [2024-07-20-20:35:41.326082] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.327088] - ninja-1.12.0-zash4lg5nsumch6t6dnjzn4kxhwcbfmu
==> [2024-07-20-20:35:41.334088] Requeueing a build task for python-3.11.9-r7uewr7spwhnhe3nxrvqupvrq
adoobon with status 'queued'
==> [2024-07-20-20:35:41.336088] Pkg id python-venv-1.0-7hy6byljqwdb2olijqvk5cl5sb6bighq has the fol
lowing dependents:
==> [2024-07-20-20:35:41.337088] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.345082] Requeueing a build task for python-venv-1.0-7hy6byljqwdb2olijqvk5cl
5sb6bighq with status 'queued'
==> [2024-07-20-20:35:41.347087] Pkg id re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g has the following
dependents:
==> [2024-07-20-20:35:41.347087] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.355088] Requeueing a build task for re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn
4g with status 'queued'
==> [2024-07-20-20:35:41.356089] Removing failure marking for re2c
==> [2024-07-20-20:35:41.359090] Pkg id ninja-1.12.0-zash4lg5nsumch6t6dnjzn4kxhwcbfmu has the follow
ing dependents:
==> [2024-07-20-20:35:41.360085] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.360085] - winbison-2.5.25-3xtcqo4cauinbkytcok7iqhv6uljzw6q
==> [2024-07-20-20:35:41.368087] Requeueing a build task for ninja-1.12.0-zash4lg5nsumch6t6dnjzn4kxh
wcbfmu with status 'queued'
==> [2024-07-20-20:35:41.369086] Pkg id winbison-2.5.25-3xtcqo4cauinbkytcok7iqhv6uljzw6q has the fol
lowing dependents:
==> [2024-07-20-20:35:41.369086] - clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk
==> [2024-07-20-20:35:41.376086] Requeueing a build task for winbison-2.5.25-3xtcqo4cauinbkytcok7iqh
v6uljzw6q with status 'queued'
==> [2024-07-20-20:35:41.378086] Removing failure marking for clingo-bootstrap
==> [2024-07-20-20:35:41.378086] Pkg id clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk has
the following dependents:
==> [2024-07-20-20:35:41.387086] Requeueing a build task for clingo-bootstrap-spack-lftl63pdsfltvio7
n3zgdmpmgchyj3lk with status 'queued'
==> [2024-07-20-20:35:41.387086] Ensure all dependencies know all dependents across specs
==> [2024-07-20-20:35:41.596958] Processing cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6: ta
sk=priority=0, status=dequeued, start=0, #dependencies=0
==> [2024-07-20-20:35:41.596958] cmake@3.28.3-msvc11 : externally installed in C:\Program Files\Micr
osoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake
==> [2024-07-20-20:35:41.597968] cmake@3.28.3-msvc11 : already registered in DB
[+] C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\C
Make\CMake (external cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6)
==> [2024-07-20-20:35:41.601968] Flagging cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6 as in
stalled
==> [2024-07-20-20:35:41.601968] Removing cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6 from
clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk's uninstalled dependencies.
==> [2024-07-20-20:35:41.602976] Removing build task for clingo-bootstrap-spack-lftl63pdsfltvio7n3zg
dmpmgchyj3lk from list
==> [2024-07-20-20:35:41.603968] Requeueing a build task for clingo-bootstrap-spack-lftl63pdsfltvio7
n3zgdmpmgchyj3lk with status 'queued'
==> [2024-07-20-20:35:41.603968] Removing cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6 from
re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g's uninstalled dependencies.
==> [2024-07-20-20:35:41.604959] Removing build task for re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g f
rom list
==> [2024-07-20-20:35:41.605958] Requeueing a build task for re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn
4g with status 'queued'
==> [2024-07-20-20:35:41.606958] Removing cmake-3.28.3-msvc11-ptf373demmkmhl3tjzvqg2zoj3mxzyl6 from
winbison-2.5.25-3xtcqo4cauinbkytcok7iqhv6uljzw6q's uninstalled dependencies.
==> [2024-07-20-20:35:41.606958] Removing build task for winbison-2.5.25-3xtcqo4cauinbkytcok7iqhv6ul
jzw6q from list
==> [2024-07-20-20:35:41.607956] Requeueing a build task for winbison-2.5.25-3xtcqo4cauinbkytcok7iqh
v6uljzw6q with status 'queued'
==> [2024-07-20-20:35:41.608958] Processing python-3.11.9-r7uewr7spwhnhe3nxrvqupvrqadoobon: task=pri
ority=0, status=dequeued, start=0, #dependencies=0
==> [2024-07-20-20:35:41.609958] python@3.11.9 : externally installed in C:\msys64\mingw64
==> [2024-07-20-20:35:41.609958] python@3.11.9 : already registered in DB
[+] C:\msys64\mingw64 (external python-3.11.9-r7uewr7spwhnhe3nxrvqupvrqadoobon)
==> [2024-07-20-20:35:41.613960] Flagging python-3.11.9-r7uewr7spwhnhe3nxrvqupvrqadoobon as installe
d
==> [2024-07-20-20:35:41.613960] Removing python-3.11.9-r7uewr7spwhnhe3nxrvqupvrqadoobon from python
-venv-1.0-7hy6byljqwdb2olijqvk5cl5sb6bighq's uninstalled dependencies.
==> [2024-07-20-20:35:41.614961] Removing build task for python-venv-1.0-7hy6byljqwdb2olijqvk5cl5sb6
bighq from list
==> [2024-07-20-20:35:41.614961] Requeueing a build task for python-venv-1.0-7hy6byljqwdb2olijqvk5cl
==> [2024-07-20-20:35:41.674511] Checking existence of https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.
spec.json.sig
==> [2024-07-20-20:35:41.719507] Failure reading URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
==> [2024-07-20-20:35:41.720507] URL does not exist: https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.sp
ec.json.sig
==> [2024-07-20-20:35:41.721508] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-niz
mxivanjnnzhuvom2sxm6xhknwkn4g.spec.json.sig
==> [2024-07-20-20:35:41.721508] Fetching from https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.spec.jso
n.sig failed.
==> [2024-07-20-20:35:41.727508] Checking existence of https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.
spec.json
==> [2024-07-20-20:35:41.775876] Failure reading URL: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
==> [2024-07-20-20:35:41.776878] URL does not exist: https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.sp
ec.json
==> [2024-07-20-20:35:41.777879] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-niz
mxivanjnnzhuvom2sxm6xhknwkn4g.spec.json
==> [2024-07-20-20:35:41.777879] Fetching from https://mirror.spack.io/build_cache/windows-windows10.0.19045-x86_64-msvc-19.40.33812-re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g.spec.jso
n failed.
==> [2024-07-20-20:35:41.780876] No binary for re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g found: installing from source
==> [2024-07-20-20:35:41.781878] Creating the installation directory C:\Users\deepa\.spack\bootstrap\store\windows-windows10.0.19045-x86_64\msvc-19.40.33812\re2c-3.0-nizmxivanjnnzhuvo
m2sxm6xhknwkn4g
==> [2024-07-20-20:35:56.139792] Error: FetchError: All fetchers failed for re2c-3.0-nizmxiv
Traceback (most recent call last):
  File "C:/msys64/home/deepa/spack/lib/spack/spack/build_environment.py", line 1136, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/installer.py", line 2447, in build_process
    return installer.run()
           ^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/installer.py", line 2298, in run
    self.pkg.do_patch()
  File "C:/msys64/home/deepa/spack/lib/spack/spack/package_base.py", line 1552, in do_patch
    self.do_stage()
  File "C:/msys64/home/deepa/spack/lib/spack/spack/package_base.py", line 1540, in do_stage
    self.do_fetch(mirror_only)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/package_base.py", line 1524, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/stage.py", line 560, in fetch
    raise spack.error.FetchError(err_msg or default_msg, None)
spack.error.FetchError: All fetchers failed for re2c-3.0-nizmxiv
==> [2024-07-20-20:35:56.141794] Flagging re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g as failed: FetchError: All fetchers failed for re2c-3.0-nizmxiv
==> [2024-07-20-20:35:56.143793] Warning: Skipping build of clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk since re2c-3.0-nizmxivanjnnzhuvom2sxm6xhknwkn4g failed
==> [2024-07-20-20:35:56.144796] Flagging clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk as failed
==> [2024-07-20-20:35:56.147791] Removing build task for clingo-bootstrap-spack-lftl63pdsfltvio7n3zgdmpmgchyj3lk from list
==> [2024-07-20-20:35:56.157792] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defaults/config.yaml
==> [2024-07-20-20:35:56.187798] Reading config from file C:/msys64/home/deepa/spack/etc/spack/defaults/windows/config.yaml
Traceback (most recent call last):
  File "C:/msys64/home/deepa/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/cmd/install.py", line 354, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/cmd/install.py", line 468, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/cmd/install.py", line 435, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/cmd/__init__.py", line 177, in parse_specs
    spec.concretize(tests=tests)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/spec.py", line 3091, in concretize
    self._new_concretize(tests)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/spec.py", line 3064, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/solver/asp.py", line 3880, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/solver/asp.py", line 828, in solve
    self.control = control or default_clingo_control()
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/solver/asp.py", line 96, in default_clingo_control
    control = clingo().Control()
              ^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/solver/core.py", line 132, in clingo
    clingo_mod = _bootstrap_clingo()
                 ^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/solver/core.py", line 198, in _bootstrap_clingo
    spack.bootstrap.ensure_clingo_importable_or_raise()
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 478, in ensure_clingo_importable_or_raise
    ensure_module_importable_or_raise(module="clingo", abstract_spec=clingo_root_spec())
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 382, in ensure_module_importable_or_raise
    raise ImportError(msg)
ImportError: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %msvc platform=windows target=x86_64" due to the following failures:
github-actions-v0.5 raised RuntimeError: The binary index is empty
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 367, in ensure_module_importable_or_raise
    if current_bootstrapper.try_import(module, abstract_spec):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 233, in try_import
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 200, in _install_and_test
    raise RuntimeError("The binary index is empty")

github-actions-v0.4 raised RuntimeError: The binary index is empty
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 367, in ensure_module_importable_or_raise
    if current_bootstrapper.try_import(module, abstract_spec):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 233, in try_import
    return self._install_and_test(abstract_spec, bincache_platform, data, test_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 200, in _install_and_test
    raise RuntimeError("The binary index is empty")

spack-install raised InstallError: Terminating after first install failure: FetchError: All fetchers failed for re2c-3.0-nizmxiv
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 367, in ensure_module_importable_or_raise
    if current_bootstrapper.try_import(module, abstract_spec):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/deepa/spack/lib/spack/spack/bootstrap/core.py", line 287, in try_import
    concrete_spec.package.do_install(fail_fast=True)
  File "C:/msys64/home/deepa/spack/lib/spack/spack/package_base.py", line 1900, in do_install
    PackageInstaller([self], kwargs).install()
  File "C:/msys64/home/deepa/spack/lib/spack/spack/installer.py", line 2167, in install
    raise InstallError(f"{fail_fast_err}: {str(exc)}", pkg=pkg)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
We don't have any version matching `re2c@3.1.2`. The latest version known to Spack is v3.0
