### ISSUE TITLE
`depends_on("cxx", type="test")` (for header-only packages) not possible

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#45573]
### Steps to reproduce

With https://github.com/spack/spack/pull/45549/commits/746d311d41859939d4573e5dc4bc14a7d41b4094, we get https://github.com/spack/spack/actions/runs/10220817292/job/28281979448?pr=45549.

### Error message

```
==> [2024-08-02-19:11:40.912730] RepoError: cannot load package 'fastor' from the 'builtin' repository: languages must be of 'build' type
==> [[20](https://github.com/spack/spack/actions/runs/10220817292/job/28281979448?pr=45549#step:7:21)24-08-02-19:11:40.912781] Error: cannot load package 'fastor' from the 'builtin' repository: languages must be of 'build' type
Traceback (most recent call last):
  File "/home/runner/work/spack/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
           ~~~~~~~~~~^^^^^
KeyError: (<spack.repo.RepoPath object at 0x7f1f9a5d0e50>, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/spack/spack/lib/spack/llnl/util/lang.py", line 161, in _memoized_function
    return func.cache[key]
           ~~~~~~~~~~^^^^^
KeyError: (<spack.repo.RepoPath object at 0x7f1f9a5d0e50>, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/spack/spack/lib/spack/spack/repo.py", line 1261, in get_pkg_class
    module = importlib.import_module(fullname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line [24](https://github.com/spack/spack/actions/runs/10220817292/job/28281979448?pr=45549#step:7:25)1, in _call_with_frames_removed
  File "/home/runner/work/spack/spack/var/spack/repos/builtin/packages/fastor/package.py", line 10, in <module>
    """Fastor is a lightweight high performance tensor algebra framework
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/spack/spack/var/spack/repos/builtin/packages/fastor/package.py", line 24, in Fastor
    
  File "/home/runner/work/spack/spack/lib/spack/spack/directives.py", line [35](https://github.com/spack/spack/actions/runs/10220817292/job/28281979448?pr=45549#step:7:36)3, in _wrapper
    result = decorated_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/spack/spack/lib/spack/spack/directives.py", line 605, in depends_on
    assert type == "build", "languages must be of 'build' type"
           ^^^^^^^^^^^^^^^
AssertionError: languages must be of 'build' type
```

### Information on your system

Issue occurred on CI system, in job [prechecks / audit / package-audits (ubuntu-latest, bash)](https://github.com/spack/spack/actions/runs/10220817292/job/28281979448?pr=45549). Unable to get `spack debug report` from that...

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by trsxvz** [comment]
Still relevant with compilers as nodes (reproduced on v1.2.2, same rule on develop). The directive now accepts `depends_on("cxx", type="test")` and `--test` does pull the compiler into the DAG, but the wrapper is only injected for build-typed language edges (`solver/asp.py`: `when="%[deptypes=build virtuals=cxx] ..."`, same gate in `runtimes.py` for flags). So nothing sets `CXX`: the tests are compiled by whatever `c++` is in `PATH`, while the spec reports the Spack compiler.

Reproducer: a header-only CMake package with `depends_on("cxx", type="test")` and `BUILD_TESTING=self.run_tests`, `spack install --test=root`, then `grep CXX <prefix>/.spack/spack-build-env.txt` (empty) and the compiler identification in the build log. `cpu-features` only works because its `depends_on("c", type="build")` injects the wrapper.

Workaround: `CMAKE_CXX_COMPILER=self.spec["cxx"].package.cxx` under `run_tests`. Would a PR extending the wrapper and flag injection to `deptypes=build,test` be welcome?
