### ISSUE TITLE
`spack solve` does not concretize environments with `concretizer:unify:false`

### ISSUE THREAD

**Issue by JohnGouwar** [LLNL/spack#45600]
### Steps to reproduce

1. Create the following spack.yaml file:
```yaml
spack:
  # add package specs to the `specs` list
  specs: 
    - "zlib@1.3"
    - "zlib@1.2"
  view: false
  concretizer:
    unify: false
```
2. Run the following command:
```console
$ cd /path/to/spack.yaml
$ spack -e . solve
```

### Error message

```console
$ spack -e . --debug solve
==> [2024-08-06-12:49:39.168218] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/config.yaml
==> [2024-08-06-12:49:39.186073] Reading config from file /home/jgouwar/.spack/config.yaml
==> [2024-08-06-12:49:39.189854] Reading config from file /home/jgouwar/Git/llnl/bugs/solve_vs_install/spack.yaml
==> [2024-08-06-12:49:39.199515] Using environment '/home/jgouwar/Git/llnl/bugs/solve_vs_install'
==> [2024-08-06-12:49:39.210735] Imported solve from built-in commands
==> [2024-08-06-12:49:39.211730] Imported solve from built-in commands
==> [2024-08-06-12:49:39.213621] DATABASE LOCK TIMEOUT: 60s
==> [2024-08-06-12:49:39.213746] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-08-06-12:49:39.214061] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/concretizer.yaml
==> [2024-08-06-12:49:39.220742] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/packages.yaml
==> [2024-08-06-12:49:39.248058] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/repos.yaml
==> [2024-08-06-12:49:39.349817] Reading config from file /home/jgouwar/.spack/linux/compilers.yaml
==> [2024-08-06-12:49:39.359644] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infoi_3_r_eo/main.c' '-o' '/tmp/spack-implicit-link-infoi_3_r_eo/output'
==> [2024-08-06-12:49:39.400033] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infofoza6ih3/main.c' '-o' '/tmp/spack-implicit-link-infofoza6ih3/output'
==> [2024-08-06-12:49:39.513363] DATABASE LOCK TIMEOUT: 60s
==> [2024-08-06-12:49:39.513440] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-08-06-12:49:39.605060] DATABASE LOCK TIMEOUT: 60s
==> [2024-08-06-12:49:39.605109] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-08-06-12:49:39.666866] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/mirrors.yaml
==> [2024-08-06-12:49:39.668426] Reading config from file /home/jgouwar/.spack/mirrors.yaml
==> [2024-08-06-12:49:39.671966] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-08-06-12:49:39.678342] Deactivated environment '/home/jgouwar/Git/llnl/bugs/solve_vs_install'
==> [2024-08-06-12:49:39.699744] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/repos.yaml
==> [2024-08-06-12:49:39.701278] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/packages.yaml
==> [2024-08-06-12:49:39.729345] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-08-06-12:49:39.729763] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-08-06-12:49:39.735035] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/jgouwar/Git/llnl/spack/etc/spack/defaults
==> [2024-08-06-12:49:39.735085] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/jgouwar/Git/llnl/spack/etc/spack/defaults/linux
==> [2024-08-06-12:49:39.735124] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/jgouwar/.spack/bootstrap/config
==> [2024-08-06-12:49:39.735145] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/jgouwar/.spack/bootstrap/config/linux
==> [2024-08-06-12:49:39.736411] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/config.yaml
==> [2024-08-06-12:49:39.755868] Reading config from file /home/jgouwar/.spack/bootstrap/config/linux/config.yaml
==> [2024-08-06-12:49:39.766123] DATABASE LOCK TIMEOUT: 60s
==> [2024-08-06-12:49:39.766214] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-08-06-12:49:39.766471] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/packages.yaml
==> [2024-08-06-12:49:39.794943] Reading config from file /home/jgouwar/.spack/bootstrap/config/packages.yaml
==> [2024-08-06-12:49:39.798977] Reading config from file /home/jgouwar/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-08-06-12:49:39.823873] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
==> [2024-08-06-12:49:39.823932] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-08-06-12:49:39.824165] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-08-06-12:49:39.925001] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.12/zcw5ieomfwwpzpzpabetix2plfqzpvwd" provides the "clingo" Python module
==> [2024-08-06-12:49:39.925733] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/config.yaml
==> [2024-08-06-12:49:39.945501] Reading config from file /home/jgouwar/.spack/config.yaml
==> [2024-08-06-12:49:39.949480] Using environment '/home/jgouwar/Git/llnl/bugs/solve_vs_install'
==> [2024-08-06-12:49:39.949921] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/concretizer.yaml
==> [2024-08-06-12:49:40.317702] Reading config from file /home/jgouwar/Git/llnl/spack/etc/spack/defaults/packages.yaml
==> [2024-08-06-12:49:40.345576] Reading config from file /home/jgouwar/.spack/linux/compilers.yaml
==> [2024-08-06-12:49:40.354359] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-info4b8yni_z/main.c' '-o' '/tmp/spack-implicit-link-info4b8yni_z/output'
==> [2024-08-06-12:49:40.395246] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infounhzes77/main.c' '-o' '/tmp/spack-implicit-link-infounhzes77/output'
==> [2024-08-06-12:49:40.495693] [REUSE] Issues when trying to reuse glibc@2.35%clang@14.0.0 build_system=autotools arch=linux-ubuntu22.04-icelake/khap2xm: Unknown namespace: abi_splice.test
==> [2024-08-06-12:49:40.495900] [REUSE] Issues when trying to reuse glibc@2.35%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-icelake/5abgwhd: Unknown namespace: abi_splice.test
==> [2024-08-06-12:49:43.464482] UnsatisfiableSpecError: failed to concretize `zlib@1.3`, `zlib@1.2` for the following reasons:
     1. Cannot select a single "version" for package "zlib"
     2. Cannot satisfy 'zlib@1.3'
     3. Cannot satisfy 'zlib@1.2'
     4. Cannot satisfy 'zlib@1.3'
        required because zlib@1.3 requested explicitly 
     5. Cannot satisfy 'zlib@1.2'
        required because zlib@1.2 requested explicitly 
     6. Cannot satisfy 'zlib@1.3' and 'zlib@1.2
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
     7. Cannot satisfy 'zlib@1.2' and 'zlib@1.3
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
==> [2024-08-06-12:49:43.464583] Error: failed to concretize `zlib@1.3`, `zlib@1.2` for the following reasons:
     1. Cannot select a single "version" for package "zlib"
     2. Cannot satisfy 'zlib@1.3'
     3. Cannot satisfy 'zlib@1.2'
     4. Cannot satisfy 'zlib@1.3'
        required because zlib@1.3 requested explicitly 
     5. Cannot satisfy 'zlib@1.2'
        required because zlib@1.2 requested explicitly 
     6. Cannot satisfy 'zlib@1.3' and 'zlib@1.2
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
     7. Cannot satisfy 'zlib@1.2' and 'zlib@1.3
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
Traceback (most recent call last):
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/cmd/solve.py", line 180, in solve
    result = solver.solve(
             ^^^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/solver/asp.py", line 3880, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/solver/asp.py", line 901, in solve    error_handler.raise_if_errors()
  File "/home/jgouwar/Git/llnl/spack/lib/spack/spack/solver/asp.py", line 757, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: failed to concretize `zlib@1.3`, `zlib@1.2` for the following reasons:
     1. Cannot select a single "version" for package "zlib"
     2. Cannot satisfy 'zlib@1.3'
     3. Cannot satisfy 'zlib@1.2'
     4. Cannot satisfy 'zlib@1.3'
        required because zlib@1.3 requested explicitly 
     5. Cannot satisfy 'zlib@1.2'
        required because zlib@1.2 requested explicitly 
     6. Cannot satisfy 'zlib@1.3' and 'zlib@1.2
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
     7. Cannot satisfy 'zlib@1.2' and 'zlib@1.3
        required because zlib@1.2 requested explicitly 
        required because zlib@1.3 requested explicitly 
```

### Information on your system

* **Spack:** 0.23.0.dev0 (425bba2f1ace61fc7a4b3a7100bd3997debfef44)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu22.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by JohnGouwar** [comment]
I believe the error stems from the [these lines](https://github.com/spack/spack/blob/f3c21b0177ea1bd69b5fea5b2e785e9d23292e4e/lib/spack/spack/cmd/solve.py#L177C1-L177C33). `spack solve` does not check whether the concretizer has `unify: false`, and sends all of the specs to the concretizer to be unified. Contrast [this lines](https://github.com/spack/spack/blob/f3c21b0177ea1bd69b5fea5b2e785e9d23292e4e/lib/spack/spack/cmd/concretize.py#L47C9-L47C74) in `spack concretize`. `env.concretize()` does check whether `unify` is true or false, and spins up the appropriate concretization pool if false.

**Comment by JohnGouwar** [comment]
https://github.com/spack/spack/commit/e42a4a8bac1f7e79abdd3227a7a743a55044a270 <- closes this issue
