### ISSUE TITLE
Spack errors out when py-webcolors package is loaded

### ISSUE THREAD

**Issue by jaguillette** [LLNL/spack#45970]
After loading the `py-jupyterlab` package, I have noticed that spack commands fail with a Python stack trace. I've tracked the issue down to a dependency of `py-jupyterlab`: `py-webcolors`. Here is an example of the problematic behavior, loading `py-webcolors` and then getting an error from a spack command. The error below comes up on most spack commands. The only exception that I found was `spack --version`

```
[jeg390@ip-10-140-214-57 ~]$ spack find --loaded
==> 0 loaded packages
[jeg390@ip-10-140-214-57 ~]$ spack load py-webcolors
[jeg390@ip-10-140-214-57 ~]$ spack find --loaded
Traceback (most recent call last):
  File "/shared/home/jeg390/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
  File "/shared/home/jeg390/spack/lib/spack/spack/main.py", line 1011, in _main
    cmd_name, args.command = resolve_alias(cmd_name, args.command)
  File "/shared/home/jeg390/spack/lib/spack/spack/main.py", line 887, in resolve_alias
    all_commands = spack.cmd.all_commands()
  File "/shared/home/jeg390/spack/lib/spack/spack/cmd/__init__.py", line 84, in all_commands
    command_paths += spack.extensions.get_command_paths()  # Extensions
  File "/shared/home/jeg390/spack/lib/spack/spack/extensions.py", line 171, in get_command_paths
    extension_paths = get_extension_paths()
  File "/shared/home/jeg390/spack/lib/spack/spack/extensions.py", line 135, in get_extension_paths
    extension_paths = spack.config.get("config:extensions") or []
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 963, in get
    return CONFIG.get(path, default, scope)
  File "/shared/home/jeg390/spack/lib/spack/llnl/util/lang.py", line 740, in __getattr__
    return getattr(self.instance, name)
  File "/shared/home/jeg390/spack/lib/spack/llnl/util/lang.py", line 730, in instance
    self._instance = self.factory()
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 828, in create
    builtin = InternalConfigScope("_builtin", CONFIG_DEFAULTS)
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 341, in __init__
    validate({section: dsec}, SECTION_SCHEMAS[section])
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 1077, in validate
    import jsonschema
  File "/shared/home/jeg390/spack/lib/spack/external/_vendoring/jsonschema/__init__.py", line 14, in <module>
    from jsonschema._format import (
  File "/shared/home/jeg390/spack/lib/spack/external/_vendoring/jsonschema/_format.py", line 346, in <module>
    import webcolors
  File "/shared/home/jeg390/spack/opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/py-webcolors-24.6.0-t4uavbxq5vkbuzhjooc7a3hzj7beqqve/lib/python3.11/site-packages/webcolors/__init__.py", line 12, in <module>
    from ._conversion import (
  File "/shared/home/jeg390/spack/opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/py-webcolors-24.6.0-t4uavbxq5vkbuzhjooc7a3hzj7beqqve/lib/python3.11/site-packages/webcolors/_conversion.py", line 49
    if hex_value := color_map.get(name.lower()):
                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/home/jeg390/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/shared/home/jeg390/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/shared/home/jeg390/spack/lib/spack/spack/main.py", line 1089, in main
    if spack.config.get("config:debug") or SHOW_BACKTRACE:
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 963, in get
    return CONFIG.get(path, default, scope)
  File "/shared/home/jeg390/spack/lib/spack/llnl/util/lang.py", line 740, in __getattr__
    return getattr(self.instance, name)
  File "/shared/home/jeg390/spack/lib/spack/llnl/util/lang.py", line 730, in instance
    self._instance = self.factory()
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 828, in create
    builtin = InternalConfigScope("_builtin", CONFIG_DEFAULTS)
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 341, in __init__
    validate({section: dsec}, SECTION_SCHEMAS[section])
  File "/shared/home/jeg390/spack/lib/spack/spack/config.py", line 1077, in validate
    import jsonschema
  File "/shared/home/jeg390/spack/lib/spack/external/_vendoring/jsonschema/__init__.py", line 14, in <module>
    from jsonschema._format import (
  File "/shared/home/jeg390/spack/lib/spack/external/_vendoring/jsonschema/_format.py", line 346, in <module>
    import webcolors
  File "/shared/home/jeg390/spack/opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/py-webcolors-24.6.0-t4uavbxq5vkbuzhjooc7a3hzj7beqqve/lib/python3.11/site-packages/webcolors/__init__.py", line 12, in <module>
    from ._conversion import (
  File "/shared/home/jeg390/spack/opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/py-webcolors-24.6.0-t4uavbxq5vkbuzhjooc7a3hzj7beqqve/lib/python3.11/site-packages/webcolors/_conversion.py", line 49
    if hex_value := color_map.get(name.lower()):
                  ^
SyntaxError: invalid syntax
```

The `:=` operator was introduced in Python 3.8, but this environment is using Python 3.11, so that shouldn't be an issue. What I'm wondering is:

1. What's the issue in the `py-webcolors` package?
2. Why is it being invoked whenever a spack command is run?

Currently, when `py-webcolors` is loaded, or when a package that depends on it is loaded, spack commands cease to function. I've tried this on a fresh install from the dev branch, as well as our existing installation. This is running in AWS on Amazon Linux 2 EC2 instances.

**Comment by wdconinc** [comment]
Your spack environment may include python 3.11, but spack itself uses the same system python version from before you had that environment installed (which I suspect is 3.7).

We normally vendor what is required for the core functionality (i.e. `jsonschema` in the backtrace). It seems `jsonschema` does not specify `webcolors` as a dependency for the version 3.2.0 that we vendor.

In the short term, you can change the python version that spack uses by setting `SPACK_PYTHON` to the version installed in your environment. Of course, that only works as long as that version remains installed.

**Comment by jaguillette** [comment]
That gets around the issue in environments where it comes up. Thanks! Should I leave the issue open for a longer-term fix?

**Comment by wdconinc** [comment]
Please keep it open as this is something that affects user experience and has a non-discoverable workaround.

@alalazo How do we avoid that the system python (which we allow to be 3.6 or 3.7) picks up python packages installed by spack in environments that may not support the older system python version? Should we clear spack package/view directories from the `PYTHONPATH` in `bin/spack`?

**Comment by haampie** [comment]
Looks like `lib/spack/external/_vendoring/jsonschema/_format.py` has various optional dependencies:

```python
try:
  import x
except ImportError:
  pass
else:
  # do stuff with x
```

we should probably delete those bits.
