### ISSUE TITLE
setting config options is sensitive to order?

### ISSUE THREAD

**Issue by cwsmith** [LLNL/spack#45984]
### Steps to reproduce

I use the following script (and more) to setup a new spack install for testing of a package and hit a error if `spack config add config:target:x86_64` was called after `spack config add config:install_tree:$work/install`.  

```
#!/bin/bash
date=`date +%F-%H-%M`
work=$PWD/testSpack_${date}
mkdir -p $work
pushd $work
git clone -b develop git@github.com:spack/spack.git
pushd spack

# setup scratch space for spack
spackScratch=$work/spack_scratch
mkdir -p $spackScratch
export SPACK_USER_CACHE_PATH=$spackScratch
export SPACK_DISABLE_LOCAL_CONFIG=true #disable use of user and system config files

export SPACK_ROOT=$PWD
source $SPACK_ROOT/share/spack/setup-env.sh

#spack config add config:target:x86_64 #works
spack config add config:install_tree:$work/install
spack config add config:target:x86_64 #fails
```

### Error message

Running the failed command in debug mode produces the following:

```
$ spack --debug --stacktrace config add config:target:x86_64
lib/spack/spack/config.py:1116 ==> [2024-08-23-13:29:34.693476] Reading config from file /space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1116 ==> [2024-08-23-13:29:34.703017] Reading config from file /space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/etc/spack/config.yaml
lib/spack/spack/cmd/__init__.py:119 ==> [2024-08-23-13:29:34.718386] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-08-23-13:29:34.719626] Imported config from built-in commands
Traceback (most recent call last):
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/cmd/config.py", line 590, in config
    action[args.config_command](args)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/cmd/config.py", line 233, in config_add
    spack.config.add(args.path, scope=scope)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/config.py", line 958, in add
    CONFIG.set(path, new, scope)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/config.py", line 400, in _method
    return method(self, *args, **kwargs)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/config.py", line 695, in set
    self.update_config(section, section_data, scope=scope)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/config.py", line 400, in _method
    return method(self, *args, **kwargs)
  File "/space/cwsmith/testSpack/testSpack_2024-08-23-13-29/spack/lib/spack/spack/config.py", line 543, in update_config
    raise RuntimeError(msg)
RuntimeError: The "config" section of the configuration needs to be written to disk, but is currently using a deprecated format. Please update it using:

        spack config [--scope=<scope>] update config

Note that previous versions of Spack will not be able to use the updated configuration.
```

### Information on your system

```
* **Spack:** 0.23.0.dev0 (906799eec510527077422cb913997bb3eec56aa3)
* **Python:** 3.9.18
* **Platform:** linux-rhel9-skylake
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I'm a bit confused. We don't have any `config:target` option, so what is:
```console
$ spack config add config:target:x86_64
```
supposed to do?

**Comment by alalazo** [comment]
So, it turns out Spack tells you exactly what to do. This line:
```console
$ spack config add config:install_tree:$work/install
```
adds an entry in the configuration like:
```yaml
config:
  install_tree: <path>
```
which was deprecated in f616422fd7a7201144934ffaa64483115f60bdd0 (Spack v0.16).  If you do:
```console
$ spack config update config
```
Spack will update to the current format, after which:
```console
$ spack config add config:target:x86_64
```
works (but will have no effect, see https://github.com/spack/spack/issues/45984#issuecomment-2459891784)
