### ISSUE TITLE
`spack concretize` fails in environments with `develop` packages with non-default variant values that are not part of the dependency tree

### ISSUE THREAD

**Issue by tmadlener** [LLNL/spack#46546]
### Steps to reproduce

See [this comment](https://github.com/spack/spack/issues/46546#issuecomment-2370810521) for a smaller and entirely builtin reproducer.

As the title suggests, I didn't manage to cut this down to anything more minimal, so the setup is unfortunately slightly involved at the moment. I am still trying to figure out how to make it smaller. I haven't been able to trigger this with packages that are in the `builtin` repository of spack. I also haven't tried any other external repositories, so this might be an issue with the `key4hep-spack` repository. In any case, I would be glad for any inputs.

Starting from scratch, with a fresh clone of spack
```console
$ git clone https://github.com/key4hep/key4hep-spack
$ spack repo add key4hep-spack
$ spack env create repro-env
$ spack env activate repro-env
$ spack add key4hep-stack
$ spack develop -p /tmp/path-doesnot-matter lich@master build_type=RelWithDebInfo
$ spack concretize -f
==> Error: 133178611194208
```

If I remove the `build_type=RelWithDebInfo` variant specification, (i.e. `spack develop -p /tmp/path-doesnot-matter lich@master`, the environment can be concretized. I have tried to reproduce this with builtin packages, but was not able to trigger the same issue, i.e. the following concretizes successfully
```console
spack env create repro-env
spack env activate repro-env
spack add podio+sio
spack develop -p /tmp/path-doesnot-matter sio@master build_type=RelWithDebInfo
spack concretize -f
````

### Error message

The problem is a `KeyError` that goes uncaught here:
https://github.com/spack/spack/blob/93ab70b07c0563f3bb9fe278da443e6a09b5eb7e/lib/spack/spack/solver/asp.py#L2504

```console
$ spack --debug --stacktrace concretize -f
Traceback (most recent call last):
  File "/home/tmadlener/work/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/tmadlener/work/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/home/tmadlener/work/spack/lib/spack/spack/main.py", line 1017, in main
    return _main(argv)
  File "/home/tmadlener/work/spack/lib/spack/spack/main.py", line 970, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/tmadlener/work/spack/lib/spack/spack/main.py", line 1000, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/tmadlener/work/spack/lib/spack/spack/main.py", line 595, in _invoke_command
    return_val = command(parser, args)
  File "/home/tmadlener/work/spack/lib/spack/spack/cmd/concretize.py", line 47, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/home/tmadlener/work/spack/lib/spack/spack/environment/environment.py", line 1455, in concretize
    return self._concretize_together(tests=tests)
  File "/home/tmadlener/work/spack/lib/spack/spack/environment/environment.py", line 1574, in _concretize_together
    concrete_specs: List[spack.spec.Spec] = spack.concretize.concretize_specs_together(
  File "/home/tmadlener/work/spack/lib/spack/spack/concretize.py", line 80, in concretize_specs_together
    result = solver.solve(
  File "/home/tmadlener/work/spack/lib/spack/spack/solver/asp.py", line 4091, in solve
    result, _, _ = self.driver.solve(
  File "/home/tmadlener/work/spack/lib/spack/spack/solver/asp.py", line 828, in solve
    asp_problem = setup.setup(specs, reuse=reuse, allow_deprecated=allow_deprecated)
  File "/home/tmadlener/work/spack/lib/spack/spack/solver/asp.py", line 2689, in setup
    self.define_variant_values()
  File "/home/tmadlener/work/spack/lib/spack/spack/solver/asp.py", line 2504, in define_variant_values
    vid = self.variant_ids_by_def_id[variant_def_id]
KeyError: 136986431901504
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.23.0.dev0 (44215de24e4553c2174717f3d30282ccf8713bdc)
* **Python:** 3.10.13
* **Platform:** linux-ubuntu22.04-skylake
```

This has been introduced fairly recently, and bisecting it leads to #44425. As already said above, I am not entirely sure whether this is a spack issue, or a key4hep-spack issue that was simply lurking before and now started to fail. Any hints on how to debug this further are greatly appreciated. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tmadlener** [comment]
After some more trial and error, I have been able to come up with a smaller reproducer. More importantly, it doesn't require any non builtin packages. It also makes it a bit more obvious on what is happening. However, I have no idea why it worked before and doesn't now.

```bash
spack env create repro-env
spack env activate repro-env
spack add hdf5
spack develop -p /tmp/doesnot/matter podio@master build_type=RelWithDebInfo
```
Leads to 
```console
==> Error: 134408207912528
```

Which is the same lookup error as originally reported. The issue in this case is that `podio` is not a dependency of `hdf5`. Hence, the possible values for `podio`s variants are never put into the `variant_ids_by_def_id`, because `define_variant` is never called for `podio`. Looking into `spack.solver.asp.SpackSolverSetup.setup` it looks like `pkg_rules` is never called for the `dev_specs`.

I think overall the behavior is correct here. But maybe the error message can be improved somehow?
