### ISSUE TITLE
`spack bootstrap` does not factor in libc

### ISSUE THREAD

**Issue by pranav-sivaraman** [LLNL/spack#46564]
### Steps to reproduce

```shell
spack -d solve zstd
``` 

### Error message

```shell
==> [2024-09-24-22:14:06.716686] Reading config from file /root/spack/etc/spack/defaults/config.yaml
==> [2024-09-24-22:14:06.723929] Reading config from file /root/.spack/config.yaml
==> [2024-09-24-22:14:06.730227] Imported solve from built-in commands
==> [2024-09-24-22:14:06.730507] Imported solve from built-in commands
==> [2024-09-24-22:14:06.730919] DATABASE LOCK TIMEOUT: 60s
==> [2024-09-24-22:14:06.730945] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-09-24-22:14:06.731009] Reading config from file /root/spack/etc/spack/defaults/concretizer.yaml
==> [2024-09-24-22:14:06.733517] Reading config from file /root/spack/etc/spack/defaults/packages.yaml
==> [2024-09-24-22:14:06.745060] Reading config from file /root/.spack/packages.yaml
==> [2024-09-24-22:14:06.749909] Reading config from file /root/spack/etc/spack/defaults/repos.yaml
==> [2024-09-24-22:14:06.803513] Reading config from file /root/.spack/linux/compilers.yaml
==> [2024-09-24-22:14:06.807812] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-info7gz6t4ol/main.c' '-o' '/tmp/spack-implicit-link-info7gz6t4ol/output'
==> [2024-09-24-22:14:06.826084] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infonpu6qzub/main.c' '-o' '/tmp/spack-implicit-link-infonpu6qzub/output'
==> [2024-09-24-22:14:06.887153] DATABASE LOCK TIMEOUT: 60s
==> [2024-09-24-22:14:06.887191] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-09-24-22:14:06.887471] Reading config from file /root/spack/etc/spack/defaults/mirrors.yaml
==> [2024-09-24-22:14:06.888628] DATABASE LOCK TIMEOUT: 60s
==> [2024-09-24-22:14:06.888646] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-09-24-22:14:06.888699] Reading config from file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-09-24-22:14:06.891007] Reading config from file /root/spack/etc/spack/defaults/repos.yaml
==> [2024-09-24-22:14:06.891600] Reading config from file /root/spack/etc/spack/defaults/packages.yaml
==> [2024-09-24-22:14:06.902897] Reading config from file /root/.spack/packages.yaml
==> [2024-09-24-22:14:06.908070] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-09-24-22:14:06.908216] Reading config from file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-09-24-22:14:06.910253] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/root/spack/etc/spack/defaults
==> [2024-09-24-22:14:06.910270] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/root/spack/etc/spack/defaults/linux
==> [2024-09-24-22:14:06.910284] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2024-09-24-22:14:06.910293] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2024-09-24-22:14:06.910739] Reading config from file /root/spack/etc/spack/defaults/config.yaml
==> [2024-09-24-22:14:06.917239] Reading config from file /root/.spack/bootstrap/config/linux/config.yaml
==> [2024-09-24-22:14:06.920476] DATABASE LOCK TIMEOUT: 60s
==> [2024-09-24-22:14:06.920498] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-09-24-22:14:06.920565] Reading config from file /root/spack/etc/spack/defaults/packages.yaml
==> [2024-09-24-22:14:06.931559] Reading config from file /root/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-09-24-22:14:06.937056] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=aarch64
==> [2024-09-24-22:14:06.937076] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-09-24-22:14:06.937170] Reading config from file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-09-24-22:14:06.964144] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=aarch64 ^python@3.12/er73owosuqfmmkxvuw3f7sqnvvj6s4xp" provides the "clingo" Python module
==> [2024-09-24-22:14:06.964512] Reading config from file /root/spack/etc/spack/defaults/config.yaml
==> [2024-09-24-22:14:06.971053] Reading config from file /root/.spack/config.yaml
Traceback (most recent call last):
  File "/root/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/main.py", line 1017, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/main.py", line 970, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/main.py", line 1000, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/main.py", line 595, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/cmd/solve.py", line 181, in solve
    result = solver.solve(
             ^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/solver/asp.py", line 4091, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/solver/asp.py", line 818, in solve
    self.control = control or default_clingo_control()
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/solver/asp.py", line 96, in default_clingo_control
    control = clingo().Control()
              ^^^^^^^^
  File "/root/spack/lib/spack/spack/solver/core.py", line 133, in clingo
    return _set_clingo_module_cache(clingo_mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/spack/lib/spack/spack/solver/core.py", line 139, in _set_clingo_module_cache
    importlib.import_module("clingo.ast")
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'clingo.ast'
``` 

### Information on your system

* **Spack:** 0.23.0.dev0 (022eca1cfe5156c1552e62d08207c61b75924630)
* **Python:** 3.12.6
* **Platform:** linux-alpine3-m1

Here's the bootstrap status
```shell
Spack v0.23.0.dev0 - python@3.12

[PASS] Core Functionalities

[FAIL] Binary packages
  [B] MISSING "file": required to analyze files for buildcaches
  [B] MISSING "gpg2": required to sign/verify buildcaches


Spack will take care of bootstrapping any missing dependency marked as [B]. Dependencies marked as [-] are instead required to be found on the system.
``` 
### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by pranav-sivaraman** [comment]
```shell
 spack bootstrap now                                                                                     root@7fc293e4fd19 10:32:53 PM
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-patchelf-0.18.0-4txke6ixd2zg2yzg33l3fqnjyassono7.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/patchelf-0.18.0/linux-centos7-aarch64-gcc-10.2.1-patchelf-0.18.0-4txke6ixd2zg2yzg33l3fqnjyassono7.spack
==> Installing "patchelf@=0.18.0%gcc@=10.2.1 ldflags='-static-libstdc++ -static-libgcc'  build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-libgpg-error-1.47-b7o5zrguyniw5362eey3peglzhlmig7l.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/libgpg-error-1.47/linux-centos7-aarch64-gcc-10.2.1-libgpg-error-1.47-b7o5zrguyniw5362eey3peglzhlmig7l.spack
==> Installing "libgpg-error@=1.47%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-libassuan-2.5.6-6k2arop3mjwfhe4cwga6a775ud5m4scp.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/libassuan-2.5.6/linux-centos7-aarch64-gcc-10.2.1-libassuan-2.5.6-6k2arop3mjwfhe4cwga6a775ud5m4scp.spack
==> Installing "libassuan@=2.5.6%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-libgcrypt-1.10.2-eh5h3zisjkupzr2pgqarvgs2fm7pun5r.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/libgcrypt-1.10.2/linux-centos7-aarch64-gcc-10.2.1-libgcrypt-1.10.2-eh5h3zisjkupzr2pgqarvgs2fm7pun5r.spack
==> Installing "libgcrypt@=1.10.2%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-libiconv-1.17-vgk2zgjeflpnksj3lywuwdzs2nez63qv.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/libiconv-1.17/linux-centos7-aarch64-gcc-10.2.1-libiconv-1.17-vgk2zgjeflpnksj3lywuwdzs2nez63qv.spack
==> Installing "libiconv@=1.17%gcc@=10.2.1 build_system=autotools libs=shared,static arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-libksba-1.6.4-au3xdl4oyfbxat6dknp3mldid7gupgt5.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/libksba-1.6.4/linux-centos7-aarch64-gcc-10.2.1-libksba-1.6.4-au3xdl4oyfbxat6dknp3mldid7gupgt5.spack
==> Installing "libksba@=1.6.4%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-npth-1.6-ja7cauk7yhhyj7msnprlirue7cn3jpnj.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/npth-1.6/linux-centos7-aarch64-gcc-10.2.1-npth-1.6-ja7cauk7yhhyj7msnprlirue7cn3jpnj.spack
==> Installing "npth@=1.6%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-pinentry-1.2.1-6yo4flozla2tvw3ojkh2atvnfxuqx6ym.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/pinentry-1.2.1/linux-centos7-aarch64-gcc-10.2.1-pinentry-1.2.1-6yo4flozla2tvw3ojkh2atvnfxuqx6ym.spack
==> Installing "pinentry@=1.2.1%gcc@=10.2.1 build_system=autotools gui=tty arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-zlib-ng-2.1.3-4cgenrt3rcinueq6peyolxhegnryoeem.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/zlib-ng-2.1.3/linux-centos7-aarch64-gcc-10.2.1-zlib-ng-2.1.3-4cgenrt3rcinueq6peyolxhegnryoeem.spack
==> Installing "zlib-ng@=2.1.3%gcc@=10.2.1+compat+opt build_system=autotools patches=299b958,ae9077a,b692621 arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-gnupg-2.4.3-lrmigjenpqj5fy4ojcs5jy6doktiu4qz.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/gnupg-2.4.3/linux-centos7-aarch64-gcc-10.2.1-gnupg-2.4.3-lrmigjenpqj5fy4ojcs5jy6doktiu4qz.spack
==> Installing "gnupg@=2.4.3%gcc@=10.2.1 build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64-gcc-10.2.1-clingo-bootstrap-spack-er73owosuqfmmkxvuw3f7sqnvvj6s4xp.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-aarch64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-aarch64-gcc-10.2.1-clingo-bootstrap-spack-er73owosuqfmmkxvuw3f7sqnvvj6s4xp.spack
==> Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs+ipo+optimized+python+static_libstdcpp build_system=cmake build_type=Release generator=make patches=bebb819,ec99431 arch=linux-centos7-aarch64" from a buildcache
``` 
Seems to be fetching from the `linux-centos7-aarch64` binary cache which I think is the problem. I guess I need to install clingo separately.

**Comment by haampie** [comment]
>  linux-alpine3-m1

interesting ;)

we should improve the bootstrap command and add ^glibc or ^musl depending on the libc determined from the currently running python process
