### ISSUE TITLE
spack module DB locking problem

### ISSUE THREAD

**Issue by garvct** [LLNL/spack#468]
I am not successful in building spack software and loading spack built software at the same time.

I get the following error.

[b3b@service2 ~]$ spack load git
Traceback (most recent call last):
  File "/apps/local/spack/bin/spack", line 176, in <module>
    main()
  File "/apps/local/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/apps/local/spack/lib/spack/spack/cmd/module.py", line 107, in module
    module_find(args.module_type, args.spec)
  File "/apps/local/spack/lib/spack/spack/cmd/module.py", line 68, in module_find
    specs = spack.installed_db.query(spec)
  File "/apps/local/spack/lib/spack/spack/database.py", line 551, in query
    with self.read_transaction():
  File "/apps/local/spack/lib/spack/spack/database.py", line 598, in __enter__
    if self._enter() and self._acquire_fn:
  File "/apps/local/spack/lib/spack/spack/database.py", line 608, in _enter
    return self._db.lock.acquire_read(self._timeout)
  File "/apps/local/spack/lib/spack/llnl/util/lock.py", line 103, in acquire_read
    self._lock(fcntl.LOCK_SH, timeout)   # can raise LockError.
  File "/apps/local/spack/lib/spack/llnl/util/lock.py", line 76, in _lock
    raise LockError("Timed out waiting for lock.")
llnl.util.lock.LockError: Timed out waiting for lock.

In this case I was building gcc@4.9.3 and at the same time trying to load git (spack load git).
This seems like a severe limitation in a multi-user environment. Is this a limitation in spack or maybe my configuration is wrong or there is an easy work-around?

Thanks,
Cormac.

**Comment by tgamblin** [comment]
Yep, this was reported in #218.  I would like to get this fixed soon -- we added DB support (which makes `spack find` much faster) but the locking is too coarse at the moment.  The plan is to do coarse-grained locking on package install directories themselves, and to only take short locks on the DB.  This will allow, among other things, parallel builds (where the dep dag is farmed out to nodes bottom-up).  It's coming.

**Comment by tgamblin** [comment]
Closing as duplicate (but yes it's an important issue).
