### ISSUE TITLE
A non existing replacement in splice configuration prevents any concretization

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#46924]
### Steps to reproduce

Add a non-existing spec replacement to the splice configuration, for instance:
```yaml
concretizer:
  splice:
    explicit:
    - target: trilinos
      replacement: trilinos/lolol
      transitive: false
```
Then try to concretize anything (including any spec that doesn't have `trilinos` among possible dependencies):
```console
$ spack spec gmake
==> Error: No spec with hash lolol could be found to match trilinos/lolol. Either the hash does not exist, or it does not match other spec constraints.
```

### Error message

<details>

<summary>$ spack -d spec gmake</summary>

```console
==> [2024-10-11-21:00:21.150623] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-10-11-21:00:21.201884] Imported spec from built-in commands
==> [2024-10-11-21:00:21.203277] Imported spec from built-in commands
==> [2024-10-11-21:00:21.204707] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-11-21:00:21.204837] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-11-21:00:21.217425] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-11-21:00:21.217566] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-11-21:00:21.217787] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/concretizer.yaml
==> [2024-10-11-21:00:21.224040] Reading config from file /home/culpo/.spack/concretizer.yaml
==> [2024-10-11-21:00:21.226337] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-10-11-21:00:21.275452] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2024-10-11-21:00:21.390948] Reading config from file /home/culpo/.spack/linux/compilers.yaml
==> [2024-10-11-21:00:21.413726] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infoyzjaqv_p/main.c' '-o' '/tmp/spack-implicit-link-infoyzjaqv_p/output'
==> [2024-10-11-21:00:21.528614] '/usr/bin/clang-11' '-v' '/tmp/spack-implicit-link-infoufa70qls/main.c' '-o' '/tmp/spack-implicit-link-infoufa70qls/output'
==> [2024-10-11-21:00:21.619791] '/usr/bin/clang-12' '-v' '/tmp/spack-implicit-link-infomhkpfjik/main.c' '-o' '/tmp/spack-implicit-link-infomhkpfjik/output'
==> [2024-10-11-21:00:21.706515] '/usr/bin/gcc-8' '-v' '/tmp/spack-implicit-link-info0x2f8lxp/main.c' '-o' '/tmp/spack-implicit-link-info0x2f8lxp/output'
==> [2024-10-11-21:00:21.765384] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-info2tnu8mnp/main.c' '-o' '/tmp/spack-implicit-link-info2tnu8mnp/output'
==> [2024-10-11-21:00:21.825995] '/usr/bin/gcc-10' '-v' '/tmp/spack-implicit-link-info1skbb_u9/main.c' '-o' '/tmp/spack-implicit-link-info1skbb_u9/output'
==> [2024-10-11-21:00:21.989388] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-11-21:00:21.989475] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-11-21:00:21.990260] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/mirrors.yaml
==> [2024-10-11-21:00:21.992687] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-11-21:00:21.997980] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2024-10-11-21:00:21.999276] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-10-11-21:00:22.028762] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-10-11-21:00:22.029202] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-11-21:00:22.034952] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/culpo/PycharmProjects/spack/etc/spack/defaults
==> [2024-10-11-21:00:22.034997] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/culpo/PycharmProjects/spack/etc/spack/defaults/linux
==> [2024-10-11-21:00:22.035025] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/culpo/.spack/bootstrap/config
==> [2024-10-11-21:00:22.035043] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/culpo/.spack/bootstrap/config/linux
==> [2024-10-11-21:00:22.036016] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-10-11-21:00:22.049159] Reading config from file /home/culpo/.spack/bootstrap/config/linux/config.yaml
==> [2024-10-11-21:00:22.057531] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-11-21:00:22.057620] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-11-21:00:22.057823] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-10-11-21:00:22.084016] Reading config from file /home/culpo/.spack/bootstrap/config/packages.yaml
==> [2024-10-11-21:00:22.090143] Reading config from file /home/culpo/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-10-11-21:00:22.137727] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
==> [2024-10-11-21:00:22.137813] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-10-11-21:00:22.138127] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-11-21:00:22.214152] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.11/55qeu52pkt5shpwd7ulugv7wzt5j7vqd" provides the "clingo" Python module
==> [2024-10-11-21:00:22.214696] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/concretizer.yaml
==> [2024-10-11-21:00:22.219601] Reading config from file /home/culpo/.spack/concretizer.yaml
==> [2024-10-11-21:00:24.149925] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-10-11-21:00:24.178986] Reading config from file /home/culpo/.spack/linux/compilers.yaml
==> [2024-10-11-21:00:24.200478] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infoin3q2qlu/main.c' '-o' '/tmp/spack-implicit-link-infoin3q2qlu/output'
==> [2024-10-11-21:00:24.323493] '/usr/bin/clang-11' '-v' '/tmp/spack-implicit-link-info76vv8d1a/main.c' '-o' '/tmp/spack-implicit-link-info76vv8d1a/output'
==> [2024-10-11-21:00:24.416710] '/usr/bin/clang-12' '-v' '/tmp/spack-implicit-link-info9fv1bb9k/main.c' '-o' '/tmp/spack-implicit-link-info9fv1bb9k/output'
==> [2024-10-11-21:00:24.511987] '/usr/bin/gcc-8' '-v' '/tmp/spack-implicit-link-infonhuiv00d/main.c' '-o' '/tmp/spack-implicit-link-infonhuiv00d/output'
==> [2024-10-11-21:00:24.579322] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infotpjatrkx/main.c' '-o' '/tmp/spack-implicit-link-infotpjatrkx/output'
==> [2024-10-11-21:00:24.646102] '/usr/bin/gcc-10' '-v' '/tmp/spack-implicit-link-infoa72qwkrn/main.c' '-o' '/tmp/spack-implicit-link-infoa72qwkrn/output'
==> [2024-10-11-21:00:37.322853] UNKNOWN SYMBOL: attr("language", NodeArgument(id='0', pkg='gmake'), c)
==> [2024-10-11-21:00:37.323004] UNKNOWN SYMBOL: attr("variant_value", NodeArgument(id='0', pkg='glibc'), build_system, autotools)
==> [2024-10-11-21:00:37.323192] UNKNOWN SYMBOL: attr("variant_value", NodeArgument(id='0', pkg='gcc-runtime'), build_system, generic)
==> [2024-10-11-21:00:37.323269] UNKNOWN SYMBOL: attr("variant_value", NodeArgument(id='0', pkg='gmake'), guile, False)
==> [2024-10-11-21:00:37.323370] UNKNOWN SYMBOL: attr("language", NodeArgument(id='0', pkg='glibc'), c)
==> [2024-10-11-21:00:37.323401] UNKNOWN SYMBOL: attr("variant_value", NodeArgument(id='0', pkg='gmake'), build_system, generic)
==> [2024-10-11-21:00:37.323446] UNKNOWN SYMBOL: attr("language", NodeArgument(id='0', pkg='glibc'), cxx)
==> [2024-10-11-21:00:37.366019] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/mirrors.yaml
==> [2024-10-11-21:00:37.369398] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-10-11-21:00:37.389390] InvalidHashError: No spec with hash lolol could be found to match trilinos/lolol. Either the hash does not exist, or it does not match other spec constraints.
==> [2024-10-11-21:00:37.389462] Error: No spec with hash lolol could be found to match trilinos/lolol. Either the hash does not exist, or it does not match other spec constraints.
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1017, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 970, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1000, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 595, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/__init__.py", line 178, in parse_specs
    spec.concretize(tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2831, in concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 4122, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 900, in solve
    answers = builder.build_specs(spec_attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 3822, in build_specs
    specs = self.execute_explicit_splices()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 3833, in execute_explicit_splices
    replacement.replace_hash()
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2105, in replace_hash
    self._dup(self.lookup_hash())
              ^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2082, in lookup_hash
    spec._dup(self._lookup_hash())
              ^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2063, in _lookup_hash
    raise InvalidHashError(self, self.abstract_hash)
spack.spec.InvalidHashError: No spec with hash lolol could be found to match trilinos/lolol. Either the hash does not exist, or it does not match other spec constraints.

```

</details>

### Information on your system

* **Spack:** 0.23.0.dev0 (629a3e9396e62895f95c1306375c3b15a48c06d3)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@becker33 @tgamblin

**Comment by tgamblin** [comment]
Doesn't seem like a bug to me. If you ask for a splice that doesn't exist, and it warns you about that, that seems expected to me.

**Comment by alalazo** [comment]
Even if `gmake` couldn't in any way have trilinos among deps?

**Comment by tgamblin** [comment]
Oh ok, I see what you are saying. I think we shouldn't bother raising if the splice wouldn't even be executed b/c the roots don't depend on the spliced spec.
