### ISSUE TITLE
spack external find openmpi fails on latest

### ISSUE THREAD

**Issue by sachiac** [LLNL/spack#47064]
### Steps to reproduce

MPI_HOME is /home/software/openmpi/aocc42/4.1.6_ucx_mt

```
$ git clone https://github.com/spack/spack.git
$ .  spack/share/spack/setup-env.sh
$ module purge && module load openmpi
$ spack external find openmpi
```

### Error message

```
==> Warning: error detecting "openmpi" from prefix /home/software/openmpi/aocc42/4.1.6_ucx_mt/bin ['fabrics']
==> No new external packages detected
```

### Information on your system

* **Spack:** 0.23.0.dev0 (2da812cbad004e5167e82ca2740c1d3575ccf7be)
* **Python:** 3.9.16
* **Platform:** linux-rocky9-zen4

```
$ spack -d external find openmpi
==> [2024-10-17-14:42:30.444389] Reading config from file /local/sachiac/spack/etc/spack/defaults/config.yaml
==> [2024-10-17-14:42:30.468746] Imported external from built-in commands
==> [2024-10-17-14:42:30.470015] Imported external from built-in commands
==> [2024-10-17-14:42:30.470324] Reading config from file /local/sachiac/spack/etc/spack/defaults/repos.yaml
==> [2024-10-17-14:42:30.471724] Reading config from file /local/sachiac/spack/etc/spack/defaults/packages.yaml
==> [2024-10-17-14:42:30.500246] Reading config from file /home/sachiac/.spack/packages.yaml
==> [2024-10-17-14:42:30.664221] '/home/software/openmpi/aocc42/4.1.6_ucx_mt/bin/ompi_info'
==> [2024-10-17-14:42:30.752409] '/home/software/openmpi/aocc42/4.1.6_ucx_mt/bin/ompi_info' '-a'
==> [2024-10-17-14:42:30.840327] Warning: error detecting "openmpi" from prefix /home/software/openmpi/aocc42/4.1.6_ucx_mt/bin ['fabrics']
==> [2024-10-17-14:42:30.840427] The following files in /home/software/openmpi/aocc42/4.1.6_ucx_mt/bin were decidedly not part of the package openmpi: /home/software/openmpi/aocc42/4.1.6_ucx_mt/bin/ompi_info
==> [2024-10-17-14:42:30.846433] No new external packages detected
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sachiac** [comment]
the same sequence works in 0.22.2:

```$ spack debug report
* **Spack:** 0.22.2 (594a376c521cc746978571b1181a47bbcff30a21)
* **Python:** 3.9.16
* **Platform:** linux-rocky9-zen4
* **Concretizer:** clingo
```

**Comment by haampie** [comment]
Try with
```
diff --git a/lib/spack/spack/detection/path.py b/lib/spack/spack/detection/path.py
index e8081f6e3c..b28cfa9ae8 100644
--- a/lib/spack/spack/detection/path.py
+++ b/lib/spack/spack/detection/path.py
@@ -277,6 +277,7 @@ def detect_specs(
                 warnings.warn(
                     f'error detecting "{pkg.name}" from prefix {candidate_path} [{str(e)}]'
                 )
+                raise
 
             if not specs:
                 files = ", ".join(_convert_to_iterable(items_in_prefix))
```

and `spack --backtrace external find openmpi`

**Comment by haampie** [comment]
#47082 should improve error reporting. There you just need `spack --backtrace external find ...`

**Comment by sachiac** [comment]
```
[asachita@genoa021 spack]$ spack --backtrace external find openmpi
==> Warning: error detecting "openmpi" from prefix /home/software/openmpi/aocc42/4.1.6_ucx_mt/bin: Traceback (most recent call last):
  File "/mnt/beegfs/asachita/spack/lib/spack/spack/detection/path.py", line 275, in detect_specs
    pkg.determine_spec_details(candidate_path, items_in_prefix)
  File "/mnt/beegfs/asachita/spack/lib/spack/spack/package_base.py", line 241, in determine_spec_details
    variants = cls.determine_variants(objs, version_str)
  File "/mnt/beegfs/asachita/spack/var/spack/repos/builtin/packages/openmpi/package.py", line 807, in determine_variants
    used_fabrics = []
  File "/mnt/beegfs/asachita/spack/var/spack/repos/builtin/packages/openmpi/package.py", line 1418, in get_options_from_variant
    if getattr(values, "feature_values", None):
KeyError: 'fabrics'

==> No new external packages detected
[asachita@genoa021 spack]$ 
```

**Comment by alalazo** [comment]
The issue might have to do with this PR https://github.com/spack/spack/pull/44425 since the `openmpi` package was not updated, and uses some "internal" API calls. 

If it's worth it, we might add detection tests for the `openmpi` package, and hopefully, next time, detect the failure in the PR that caused it.

**Comment by haampie** [comment]
So, we did not fix this, but only improved the error message? 😕

**Comment by sachiac** [comment]
confirmed!  thanks!
