### ISSUE TITLE
Spack concretizer internal error. ("must have exactly one condition_set for literals")

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#47157]
### Steps to reproduce

```
spack install spiral-software%gcc@12.3.0 #Assume the hash is d4cc
spack install fftx^/d44c
```
I was having issues with the spiral-software dependency for fftx so I built it first and then requested fftx build with the version I built explicitly. This failed. `spack install spiral-software%gcc@12.3.0` worked, but built a new spiral-software so maybe the default variants from the one I built initially weren't suitable for fftx. Since I was able to build fftx this bug is bypassed for me but it probably should still be addressed.

### Error message

```
spack -d install fftx^/d44c
==> [2024-10-22-12:26:19.595433] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/config.yaml
==> [2024-10-22-12:26:19.669862] Imported install from built-in commands
==> [2024-10-22-12:26:19.671519] Imported install from built-in commands
==> [2024-10-22-12:26:19.681651] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-22-12:26:19.681716] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-22-12:26:19.707755] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-22-12:26:19.707811] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-22-12:26:19.708005] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/concretizer.yaml
==> [2024-10-22-12:26:19.714863] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/packages.yaml
==> [2024-10-22-12:26:19.766642] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/repos.yaml
==> [2024-10-22-12:26:19.930124] Reading config from file /home/wspear/.spack/linux/compilers.yaml
==> [2024-10-22-12:26:19.963707] '/usr/bin/gcc-11' '-v' '/tmp/spack-implicit-link-infolhng_m92/main.c' '-o' '/tmp/spack-implicit-link-infolhng_m92/output'
==> [2024-10-22-12:26:20.010260] '/usr/bin/gcc-12' '-v' '/tmp/spack-implicit-link-infog1_expqt/main.c' '-o' '/tmp/spack-implicit-link-infog1_expqt/output'
==> [2024-10-22-12:26:20.083963] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-info81xsf4sg/main.c' '-o' '/tmp/spack-implicit-link-info81xsf4sg/output'
==> [2024-10-22-12:26:20.133937] '/usr/bin/clang-14' '-v' '/tmp/spack-implicit-link-infodcdtqr3l/main.c' '-o' '/tmp/spack-implicit-link-infodcdtqr3l/output'
==> [2024-10-22-12:26:20.223959] '/usr/bin/clang-15' '-v' '/tmp/spack-implicit-link-infojzk2_v2x/main.c' '-o' '/tmp/spack-implicit-link-infojzk2_v2x/output'
==> [2024-10-22-12:26:20.312467] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-info3d5padeh/main.c' '-o' '/tmp/spack-implicit-link-info3d5padeh/output'
==> [2024-10-22-12:26:20.395803] '/usr/bin/gcc-14' '-v' '/tmp/spack-implicit-link-infoxjnf3onj/main.c' '-o' '/tmp/spack-implicit-link-infoxjnf3onj/output'
==> [2024-10-22-12:26:20.557853] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-22-12:26:20.557927] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-22-12:26:20.607813] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/mirrors.yaml
==> [2024-10-22-12:26:20.610593] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-22-12:26:20.617475] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/repos.yaml
==> [2024-10-22-12:26:20.619142] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/packages.yaml
==> [2024-10-22-12:26:20.657215] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-10-22-12:26:20.657557] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-22-12:26:20.663742] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/wspear/bin/SPACK/spack/etc/spack/defaults
==> [2024-10-22-12:26:20.663789] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/wspear/bin/SPACK/spack/etc/spack/defaults/linux
==> [2024-10-22-12:26:20.663834] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/wspear/.spack/bootstrap/config
==> [2024-10-22-12:26:20.663872] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/wspear/.spack/bootstrap/config/linux
==> [2024-10-22-12:26:20.665013] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/config.yaml
==> [2024-10-22-12:26:20.683035] Reading config from file /home/wspear/.spack/bootstrap/config/linux/config.yaml
==> [2024-10-22-12:26:20.692756] DATABASE LOCK TIMEOUT: 60s
==> [2024-10-22-12:26:20.692807] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-10-22-12:26:20.692998] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/packages.yaml
==> [2024-10-22-12:26:20.729646] Reading config from file /home/wspear/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-10-22-12:26:20.764988] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
==> [2024-10-22-12:26:20.765037] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-10-22-12:26:20.765307] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-10-22-12:26:20.857138] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.12/zcw5ieomfwwpzpzpabetix2plfqzpvwd" provides the "clingo" Python module
==> [2024-10-22-12:26:20.858037] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/concretizer.yaml
==> [2024-10-22-12:26:23.824624] Reading config from file /home/wspear/bin/SPACK/spack/etc/spack/defaults/packages.yaml
==> [2024-10-22-12:26:23.859483] Reading config from file /home/wspear/.spack/linux/compilers.yaml
==> [2024-10-22-12:26:23.888935] '/usr/bin/gcc-11' '-v' '/tmp/spack-implicit-link-info2kgrtyhb/main.c' '-o' '/tmp/spack-implicit-link-info2kgrtyhb/output'
==> [2024-10-22-12:26:23.943257] '/usr/bin/gcc-12' '-v' '/tmp/spack-implicit-link-info_asvug83/main.c' '-o' '/tmp/spack-implicit-link-info_asvug83/output'
==> [2024-10-22-12:26:23.996753] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infoyqs2zyd6/main.c' '-o' '/tmp/spack-implicit-link-infoyqs2zyd6/output'
==> [2024-10-22-12:26:24.050474] '/usr/bin/clang-14' '-v' '/tmp/spack-implicit-link-info6sgb2swm/main.c' '-o' '/tmp/spack-implicit-link-info6sgb2swm/output'
==> [2024-10-22-12:26:24.138018] '/usr/bin/clang-15' '-v' '/tmp/spack-implicit-link-infod0waitux/main.c' '-o' '/tmp/spack-implicit-link-infod0waitux/output'
==> [2024-10-22-12:26:24.228951] '/usr/bin/clang' '-v' '/tmp/spack-implicit-link-infouvpqxzju/main.c' '-o' '/tmp/spack-implicit-link-infouvpqxzju/output'
==> [2024-10-22-12:26:24.313715] '/usr/bin/gcc-14' '-v' '/tmp/spack-implicit-link-infom5b2p2pq/main.c' '-o' '/tmp/spack-implicit-link-infom5b2p2pq/output'
==> [2024-10-22-12:26:40.612695] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    fftx ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] bzip2@=1.0.8%gcc@=12.3.0~debug~pic+shared build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=12.3.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] cmake@=3.30.5%gcc@=12.3.0~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892 arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] curl@=8.10.1%gcc@=12.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu24.04-westmere ^[deptypes=build] diffutils@=3.10%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=link] gcc-runtime@=14.2.0%gcc@=14.2.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gdbm@=1.23%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=iconv,libc] glibc@=2.39%gcc@=14.2.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gmake@=4.4.1%gcc@=12.3.0~guile build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] ncurses@=6.5%gcc@=12.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] nghttp2@=1.63.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] openssl@=3.3.1%gcc@=12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu24.04-westmere ^[deptypes=build] perl@=5.40.0%gcc@=12.3.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] readline@=8.2%gcc@=12.3.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu24.04-westmere ^spiral-software@=8.5.1%gcc@=12.3.0~fftx~hcol~ipo~jit~mpi~simt build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.2.1%gcc@=12.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu24.04-westmere is unsatisfiable, errors are:
    internal_error("must have exactly one condition_set for literals")
==> [2024-10-22-12:26:40.612856] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    fftx ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] bzip2@=1.0.8%gcc@=12.3.0~debug~pic+shared build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=12.3.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] cmake@=3.30.5%gcc@=12.3.0~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892 arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] curl@=8.10.1%gcc@=12.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu24.04-westmere ^[deptypes=build] diffutils@=3.10%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=link] gcc-runtime@=14.2.0%gcc@=14.2.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gdbm@=1.23%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=iconv,libc] glibc@=2.39%gcc@=14.2.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gmake@=4.4.1%gcc@=12.3.0~guile build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] ncurses@=6.5%gcc@=12.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] nghttp2@=1.63.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] openssl@=3.3.1%gcc@=12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu24.04-westmere ^[deptypes=build] perl@=5.40.0%gcc@=12.3.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] readline@=8.2%gcc@=12.3.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu24.04-westmere ^spiral-software@=8.5.1%gcc@=12.3.0~fftx~hcol~ipo~jit~mpi~simt build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.2.1%gcc@=12.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu24.04-westmere is unsatisfiable, errors are:
    internal_error("must have exactly one condition_set for literals")
==> [2024-10-22-12:26:40.612942] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    fftx ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] bzip2@=1.0.8%gcc@=12.3.0~debug~pic+shared build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=12.3.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] cmake@=3.30.5%gcc@=12.3.0~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892 arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] curl@=8.10.1%gcc@=12.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu24.04-westmere ^[deptypes=build] diffutils@=3.10%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=link] gcc-runtime@=14.2.0%gcc@=14.2.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gdbm@=1.23%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=iconv,libc] glibc@=2.39%gcc@=14.2.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gmake@=4.4.1%gcc@=12.3.0~guile build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] ncurses@=6.5%gcc@=12.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] nghttp2@=1.63.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] openssl@=3.3.1%gcc@=12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu24.04-westmere ^[deptypes=build] perl@=5.40.0%gcc@=12.3.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] readline@=8.2%gcc@=12.3.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu24.04-westmere ^spiral-software@=8.5.1%gcc@=12.3.0~fftx~hcol~ipo~jit~mpi~simt build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.2.1%gcc@=12.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu24.04-westmere is unsatisfiable, errors are:
    internal_error("must have exactly one condition_set for literals")
Traceback (most recent call last):
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/main.py", line 1013, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/main.py", line 966, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/main.py", line 996, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/main.py", line 591, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/cmd/install.py", line 351, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/cmd/install.py", line 465, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/cmd/install.py", line 432, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/cmd/__init__.py", line 178, in parse_specs
    spec.concretize(tests=tests)
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/spec.py", line 2831, in concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/solver/asp.py", line 4122, in solve
    result, _, _ = self.driver.solve(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/solver/asp.py", line 927, in solve
    result.raise_if_unsat()
  File "/home/wspear/bin/SPACK/spack/lib/spack/spack/solver/asp.py", line 479, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    fftx ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] bzip2@=1.0.8%gcc@=12.3.0~debug~pic+shared build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=12.3.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build] cmake@=3.30.5%gcc@=12.3.0~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892 arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] curl@=8.10.1%gcc@=12.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu24.04-westmere ^[deptypes=build] diffutils@=3.10%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=link] gcc-runtime@=14.2.0%gcc@=14.2.0 build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gdbm@=1.23%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=iconv,libc] glibc@=2.39%gcc@=14.2.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] gmake@=4.4.1%gcc@=12.3.0~guile build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] ncurses@=6.5%gcc@=12.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] nghttp2@=1.63.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] openssl@=3.3.1%gcc@=12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu24.04-westmere ^[deptypes=build] perl@=5.40.0%gcc@=12.3.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu24.04-westmere ^[deptypes=build virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=12.3.0 build_system=autotools arch=linux-ubuntu24.04-westmere ^[deptypes=build,link] readline@=8.2%gcc@=12.3.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu24.04-westmere ^spiral-software@=8.5.1%gcc@=12.3.0~fftx~hcol~ipo~jit~mpi~simt build_system=cmake build_type=Release generator=make arch=linux-ubuntu24.04-westmere ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.2.1%gcc@=12.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu24.04-westmere is unsatisfiable, errors are:
    internal_error("must have exactly one condition_set for literals")

```

### Information on your system

* **Spack:** 0.23.0.dev0 (50aa5a7b249da2105d7601a3af4fb6e8a6de6844)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu24.04-westmere

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
> I was having issues with the spiral-software dependency for fftx

Which kind of issues?

**Comment by wspear** [comment]
These issues: https://github.com/spack/spack/issues/47151
