### ISSUE TITLE
spack concretize failed with cryptic "TypeError: '<' not supported between instances of 'bool' and 'str'"

### ISSUE THREAD

**Issue by lrbison** [LLNL/spack#47446]
### Steps to reproduce

I recently upgraded spack on develop branch.  Now I find the following error message when trying to install or spec any package (using glibc as an example)

```
$ spack spec  glibc
==> Error: '<' not supported between instances of 'bool' and 'str'
```

but with --fresh:

```
$ spack spec --fresh glibc
Input spec
--------------------------------
 -   glibc

Concretized
--------------------------------
[e]  glibc@2.31%gcc@13.3.0 build_system=autotools arch=linux-ubuntu20.04-neoverse_v1
```

### Error message

```
ubuntu@ip-172-31-47-127:/fsx/spack$ spack --debug --stacktrace spec glibc
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.700619] Reading config from file /fsx/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.720887] Reading config from file /home/ubuntu/.spack/config.yaml
lib/spack/spack/cmd/__init__.py:120 ==> [2024-11-05-17:12:33.747806] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:120 ==> [2024-11-05-17:12:33.748821] Imported spec from built-in commands
lib/spack/spack/database.py:620 ==> [2024-11-05-17:12:33.757866] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-05-17:12:33.758218] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.759250] Reading config from file /fsx/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/database.py:620 ==> [2024-11-05-17:12:33.799518] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-05-17:12:33.799925] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.800835] Reading config from file /fsx/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.828232] Reading config from file /fsx/spack/etc/spack/packages.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.860569] Reading config from file /fsx/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:33.863685] Reading config from file /home/ubuntu/.spack/repos.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:34.049315] Reading config from file /fsx/spack/etc/spack/compilers.yaml
lib/spack/spack/config.py:1104 ==> [2024-11-05-17:12:34.058777] Reading config from file /home/ubuntu/.spack/compilers.yaml
lib/spack/spack/util/executable.py:234 ==> [2024-11-05-17:12:34.106340] '/fsx/spack/opt/spack/linux-ubuntu20.04-aarch64/gcc-14.1.0/gcc-13.3.0-egc7334b2otxw5czkhs3pkb6ond5wf54/bin/gcc' '-v' '/tmp/spack-implicit-link
-infoqjuamftv/main.c' '-o' '/tmp/spack-implicit-link-infoqjuamftv/output'
lib/spack/spack/util/executable.py:234 ==> [2024-11-05-17:12:34.181220] '/fsx/spack/opt/spack/linux-ubuntu20.04-aarch64/gcc-12.2.0/gcc-14.1.0-vddjahktngfeejoaxh5myru5vh5o6tcm/bin/gcc' '-v' '/tmp/spack-implicit-link
-infooe8kl1xc/main.c' '-o' '/tmp/spack-implicit-link-infooe8kl1xc/output'
lib/spack/spack/util/executable.py:234 ==> [2024-11-05-17:12:34.254907] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infoco8kjqon/main.c' '-o' '/tmp/spack-implicit-link-infoco8kjqon/output'
lib/spack/spack/util/executable.py:234 ==> [2024-11-05-17:12:34.314338] '/fsx/spack/opt/spack/linux-ubuntu20.04-aarch64/gcc-9.4.0/gcc-12.2.0-nyyjbfj6kfxvigtbighni2jet5ubqyjt/bin/gcc' '-v' '/tmp/spack-implicit-link-
infob7c72t30/main.c' '-o' '/tmp/spack-implicit-link-infob7c72t30/output'
lib/spack/spack/database.py:620 ==> [2024-11-05-17:12:34.644091] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-05-17:12:34.644438] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/fsx/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/fsx/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/fsx/spack/lib/spack/spack/main.py", line 1014, in main
    return _main(argv)
  File "/fsx/spack/lib/spack/spack/main.py", line 967, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/fsx/spack/lib/spack/spack/main.py", line 997, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/fsx/spack/lib/spack/spack/main.py", line 592, in _invoke_command
    return_val = command(parser, args)
  File "/fsx/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/fsx/spack/lib/spack/spack/cmd/__init__.py", line 180, in parse_specs
    return _concretize_spec_pairs(to_concretize, tests=tests)
  File "/fsx/spack/lib/spack/spack/cmd/__init__.py", line 197, in _concretize_spec_pairs
    concretized = concretize_method(to_concretize, tests=tests)
  File "/fsx/spack/lib/spack/spack/concretize.py", line 72, in concretize_together
    concrete_specs = concretize_specs_together(to_concretize, tests=tests)
  File "/fsx/spack/lib/spack/spack/concretize.py", line 55, in concretize_specs_together
    result = solver.solve(abstract_specs, tests=tests, allow_deprecated=allow_deprecated)
  File "/fsx/spack/lib/spack/spack/solver/asp.py", line 4235, in solve
    result, _, _ = self.solve_with_stats(specs, **kwargs)
  File "/fsx/spack/lib/spack/spack/solver/asp.py", line 4222, in solve_with_stats
    reusable_specs.extend(self.selector.reusable_specs(specs))
  File "/fsx/spack/lib/spack/spack/solver/asp.py", line 4164, in reusable_specs
    result.extend(reuse_source.selected_specs())
  File "/fsx/spack/lib/spack/spack/solver/asp.py", line 3983, in selected_specs
    return [s for s in self.factory() if self.is_selected(s)]
  File "/fsx/spack/lib/spack/spack/solver/asp.py", line 4029, in _specs_from_store
    return store.db.query(installed=True)
  File "/fsx/spack/lib/spack/spack/database.py", line 1712, in query
    return sorted(results)
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 383, in lt
    return (other is not None) and lazy_lt(self._cmp_iter, other._cmp_iter)
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 292, in lazy_lt
    return left < right
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 383, in lt
    return (other is not None) and lazy_lt(self._cmp_iter, other._cmp_iter)
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 292, in lazy_lt
    return left < right
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 383, in lt
    return (other is not None) and lazy_lt(self._cmp_iter, other._cmp_iter)
  File "/fsx/spack/lib/spack/llnl/util/lang.py", line 292, in lazy_lt
    return left < right
TypeError: '<' not supported between instances of 'bool' and 'str'
ubuntu@ip-172-31-47-127:/fsx/spack$
```

### Information on your system

```
ubuntu@ip-172-31-47-127:/fsx/spack$ spack debug report
* **Spack:** 0.23.0.dev0 (2b9c6790f22db8161f1dca9a37bdf5d68ab90482)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-neoverse_v1
```

```
commit 2b9c6790f22db8161f1dca9a37bdf5d68ab90482 (HEAD -> develop, origin/develop, origin/HEAD)
Date:   Tue Nov 5 15:50:48 2024 +0100
```

It seems this could be related to https://github.com/spack/spack/issues/28012 and https://github.com/spack/spack/issues/28260, but that was fixed by https://github.com/spack/spack/pull/29013 in 2022.  Is there a reason it is back?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Can you apply

```diff
diff --git a/lib/spack/llnl/util/lang.py b/lib/spack/llnl/util/lang.py
index f43773346a..e4e306b8f6 100644
--- a/lib/spack/llnl/util/lang.py
+++ b/lib/spack/llnl/util/lang.py
@@ -380,6 +380,8 @@ def eq(self, other):
     def lt(self, other):
         if self is other:
             return False
+        if hasattr(self, "to_json") and hasattr(other, "to_json"):
+            print(f"{self.to_json()} --- {other.to_json()}")
         return (other is not None) and lazy_lt(self._cmp_iter, other._cmp_iter)
 
     def ne(self, other):
```

and report back the last line of that with the two specs that fail to compare?

**Comment by lrbison** [comment]
Last print is:
```
{"spec":{"_meta":{"version":4},"nodes":[{"name":"libfabric","version":"1.20.1","arch":{"platform":"linux","platform_os":"ubuntu20.04","target":{"name":"neoverse_v1","vendor":"ARM","features":["aes","asimd","asimddp","asimdfhm","asimdhp","asimdrdm","atomics","bf16","cpuid","crc32","dcpodp","dcpop","dgh","dit","evtstrm","fcma","flagm","fp","fphp","i8mm","ilrcpc","jscvt","lrcpc","pmull","rng","sha1","sha2","sha3","sha512","sve","svebf16","svei8mm","uscat"],"generation":0,"parents":["neoverse_n1","armv8.4a"],"cpupart":"0xd40"}},"compiler":{"name":"gcc","version":"14.1.0"},"namespace":"builtin","parameters":{"build_system":"autotools","debug":false,"fabrics":["efa","shm"],"kdreg":false,"uring":false,"cflags":[],"cppflags":[],"cxxflags":[],"fflags":[],"ldflags":[],"ldlibs":[]},"external":{"path":"/opt/amazon/efa/","module":null,"extra_attributes":{}},"package_hash":"iwqv2d7ef734gesh5stowiwtqs6fhqzo3qioefktmnvnnmj7wfiq====","hash":"mwdouj7h64qwxpm64ku52yynkjwbdgbs"}]}} --- {"spec":{"_meta":{"version":4},"nodes":[{"name":"libfabric","version":"1.20.1","arch":{"platform":"linux","platform_os":"ubuntu20.04","target":"aarch64"},"compiler":{"name":"arm","version":"23.10"},"namespace":"builtin","parameters":{"build_system":"autotools","debug":false,"fabrics":["efa","shm","sockets","tcp","udp"],"kdreg":false,"uring":false,"cflags":[],"cppflags":[],"cxxflags":[],"fflags":[],"ldflags":[],"ldlibs":[]},"external":{"path":"/opt/amazon/efa/","module":null,"extra_attributes":{}},"package_hash":"iwqv2d7ef734gesh5stowiwtqs6fhqzo3qioefktmnvnnmj7wfiq====","hash":"yjuvwyct3suyqeh4p4qbxyp7nmpiycfv"}]}}
```

I've prettied it up a little:

First:
```json
{
  "spec": {
    "_meta": {
      "version": 4
    },
    "nodes": [
      {
        "name": "libfabric",
        "version": "1.20.1",
        "arch": {
          "platform": "linux",
          "platform_os": "ubuntu20.04",
          "target": {
            "name": "neoverse_v1",
            "vendor": "ARM",
            "features": [
              "aes",
              "asimd",
              "asimddp",
              "asimdfhm",
              "asimdhp",
              "asimdrdm",
              "atomics",
              "bf16",
              "cpuid",
              "crc32",
              "dcpodp",
              "dcpop",
              "dgh",
              "dit",
              "evtstrm",
              "fcma",
              "flagm",
              "fp",
              "fphp",
              "i8mm",
              "ilrcpc",
              "jscvt",
              "lrcpc",
              "pmull",
              "rng",
              "sha1",
              "sha2",
              "sha3",
              "sha512",
              "sve",
              "svebf16",
              "svei8mm",
              "uscat"
            ],
            "generation": 0,
            "parents": [
              "neoverse_n1",
              "armv8.4a"
            ],
            "cpupart": "0xd40"
          }
        },
        "compiler": {
          "name": "gcc",
          "version": "14.1.0"
        },
        "namespace": "builtin",
        "parameters": {
          "build_system": "autotools",
          "debug": false,
          "fabrics": [
            "efa",
            "shm"
          ],
          "kdreg": false,
          "uring": false,
          "cflags": [],
          "cppflags": [],
          "cxxflags": [],
          "fflags": [],
          "ldflags": [],
          "ldlibs": []
        },
        "external": {
          "path": "/opt/amazon/efa/",
          "module": null,
          "extra_attributes": {}
        },
        "package_hash": "iwqv2d7ef734gesh5stowiwtqs6fhqzo3qioefktmnvnnmj7wfiq====",
        "hash": "mwdouj7h64qwxpm64ku52yynkjwbdgbs"
      }
    ]
  }
}
```
Second:
```json
{
  "spec": {
    "_meta": {
      "version": 4
    },
    "nodes": [
      {
        "name": "libfabric",
        "version": "1.20.1",
        "arch": {
          "platform": "linux",
          "platform_os": "ubuntu20.04",
          "target": "aarch64"
        },
        "compiler": {
          "name": "arm",
          "version": "23.10"
        },
        "namespace": "builtin",
        "parameters": {
          "build_system": "autotools",
          "debug": false,
          "fabrics": [
            "efa",
            "shm",
            "sockets",
            "tcp",
            "udp"
          ],
          "kdreg": false,
          "uring": false,
          "cflags": [],
          "cppflags": [],
          "cxxflags": [],
          "fflags": [],
          "ldflags": [],
          "ldlibs": []
        },
        "external": {
          "path": "/opt/amazon/efa/",
          "module": null,
          "extra_attributes": {}
        },
        "package_hash": "iwqv2d7ef734gesh5stowiwtqs6fhqzo3qioefktmnvnnmj7wfiq====",
        "hash": "yjuvwyct3suyqeh4p4qbxyp7nmpiycfv"
      }
    ]
  }
}
```

**Comment by lrbison** [comment]
Thank you for the swift action!  I can confirm that after git pull, that both my example as well as my actual workload install have been fixed!
