### ISSUE TITLE
Spack concretizer internal error

### ISSUE THREAD

**Issue by sachiac** [LLNL/spack#47565]
### Steps to reproduce

```
  $  git clone --depth=100 https://github.com/spack/spack.git
  $  . spack/share/spack/setup-env.sh
  $  spack spec aocc
```

### Error message

```
/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    aocc is unsatisfiable
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.23.0.dev0 (99fd37931c117c2842c503d623aa9749891a9203)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen4
```
full debug output from command:

```
==> [2024-11-12-09:57:03.398209] Reading config from file /home/sachiac/spack/etc/spack/defaults/config.yaml
==> [2024-11-12-09:57:03.416136] Imported spec from built-in commands
==> [2024-11-12-09:57:03.416615] Imported spec from built-in commands
==> [2024-11-12-09:57:03.417115] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-12-09:57:03.417150] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-12-09:57:03.417332] Reading config from file /home/sachiac/spack/etc/spack/defaults/concretizer.yaml
==> [2024-11-12-09:57:03.424438] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-12-09:57:03.424469] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-12-09:57:03.430829] Reading config from file /home/sachiac/spack/etc/spack/defaults/packages.yaml
==> [2024-11-12-09:57:03.448879] Reading config from file /home/sachiac/spack/etc/spack/defaults/repos.yaml
==> [2024-11-12-09:57:03.540247] Reading config from file /home/sachiac/.spack/linux/compilers.yaml
==> [2024-11-12-09:57:03.607346] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.607851] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.610195] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.612621] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.640173] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.643645] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.649144] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.649962] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.651472] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.655109] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.655425] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.655474] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.656786] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.684190] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.814079] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.814080] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.814750] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.817744] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.837504] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.837507] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.858915] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.858961] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.859279] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.861494] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.866417] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.882530] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.882598] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:03.895220] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.015211] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.016167] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.019205] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.038034] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.059329] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.059345] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.060567] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.061835] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.061928] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.064096] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.069405] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.082854] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.082853] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.102730] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.245702] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-12-09:57:04.245796] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-12-09:57:04.246505] Reading config from file /home/sachiac/spack/etc/spack/defaults/mirrors.yaml
==> [2024-11-12-09:57:04.250375] Reading config from file /home/sachiac/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-11-12-09:57:04.254497] Reading config from file /home/sachiac/spack/etc/spack/defaults/repos.yaml
==> [2024-11-12-09:57:04.255522] Reading config from file /home/sachiac/spack/etc/spack/defaults/packages.yaml
==> [2024-11-12-09:57:04.273964] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-11-12-09:57:04.274212] Reading config from file /home/sachiac/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-11-12-09:57:04.277472] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/sachiac/spack/etc/spack/defaults
==> [2024-11-12-09:57:04.277498] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/sachiac/spack/etc/spack/defaults/linux
==> [2024-11-12-09:57:04.277518] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/sachiac/.spack/bootstrap/config
==> [2024-11-12-09:57:04.277528] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/sachiac/.spack/bootstrap/config/linux
==> [2024-11-12-09:57:04.278103] Reading config from file /home/sachiac/spack/etc/spack/defaults/config.yaml
==> [2024-11-12-09:57:04.288303] Reading config from file /home/sachiac/.spack/bootstrap/config/linux/config.yaml
==> [2024-11-12-09:57:04.293809] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-12-09:57:04.293841] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-12-09:57:04.293954] Reading config from file /home/sachiac/spack/etc/spack/defaults/packages.yaml
==> [2024-11-12-09:57:04.331607] Reading config from file /home/sachiac/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-11-12-09:57:04.381341] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.383273] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.386612] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.387798] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.388934] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.389259] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.389375] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.389384] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.389521] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.391203] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.393633] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.393880] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.397963] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.431209] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:04.495079] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
==> [2024-11-12-09:57:04.495172] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-11-12-09:57:04.495668] Reading config from file /home/sachiac/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-11-12-09:57:04.529041] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64 ^python@3.10/4pi6zqqe2vm6ehc7qb4se3ql53m6relx" provides the "clingo" Python module
==> [2024-11-12-09:57:04.529806] Reading config from file /home/sachiac/spack/etc/spack/defaults/concretizer.yaml
==> [2024-11-12-09:57:05.930109] Reading config from file /home/sachiac/spack/etc/spack/defaults/packages.yaml
==> [2024-11-12-09:57:05.949011] Reading config from file /home/sachiac/.spack/linux/compilers.yaml
==> [2024-11-12-09:57:05.955442] Reading config from file /home/sachiac/spack/etc/spack/defaults/config.yaml
==> [2024-11-12-09:57:06.002048] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.005166] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.005397] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.005570] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.006668] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.007071] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.007977] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.007973] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.008356] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.009071] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.009625] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.011584] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.012581] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.013219] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.117140] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.117432] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.118638] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.120172] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.122368] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.123324] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.123949] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.123957] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.124529] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.125184] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.126022] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.126436] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.131842] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.131920] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.238375] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.238677] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.240909] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.240997] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.242012] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.242707] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.243362] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.243603] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.244528] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.244446] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.245188] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.248278] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.250902] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
==> [2024-11-12-09:57:06.251260] cannot scan '/usr/bin' for external software: [Errno 13] Permission denied: '/usr/bin/MultEvent'
/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/sachiac/spack/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

==> [2024-11-12-09:57:13.560970] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    aocc is unsatisfiable
==> [2024-11-12-09:57:13.561181] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    aocc is unsatisfiable
Traceback (most recent call last):
  File "/home/sachiac/spack/lib/spack/spack/main.py", line 1013, in main
    return _main(argv)
  File "/home/sachiac/spack/lib/spack/spack/main.py", line 966, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/home/sachiac/spack/lib/spack/spack/main.py", line 996, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/sachiac/spack/lib/spack/spack/main.py", line 592, in _invoke_command
    return_val = command(parser, args)
  File "/home/sachiac/spack/lib/spack/spack/cmd/spec.py", line 103, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/home/sachiac/spack/lib/spack/spack/cmd/__init__.py", line 181, in parse_specs
    return _concretize_spec_pairs(to_concretize, tests=tests)
  File "/home/sachiac/spack/lib/spack/spack/cmd/__init__.py", line 198, in _concretize_spec_pairs
    concretized = concretize_method(to_concretize, tests=tests)
  File "/home/sachiac/spack/lib/spack/spack/concretize.py", line 75, in concretize_together
    concrete_specs = concretize_specs_together(to_concretize, tests=tests)
  File "/home/sachiac/spack/lib/spack/spack/concretize.py", line 58, in concretize_specs_together
    result = solver.solve(abstract_specs, tests=tests, allow_deprecated=allow_deprecated)
  File "/home/sachiac/spack/lib/spack/spack/solver/asp.py", line 4238, in solve
    result, _, _ = self.solve_with_stats(specs, **kwargs)
  File "/home/sachiac/spack/lib/spack/spack/solver/asp.py", line 4228, in solve_with_stats
    return self.driver.solve(
  File "/home/sachiac/spack/lib/spack/spack/solver/asp.py", line 930, in solve
    result.raise_if_unsat()
  File "/home/sachiac/spack/lib/spack/spack/solver/asp.py", line 478, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    aocc is unsatisfiable
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sachiac** [comment]
this happens on other packages, too (e.g., zlib, hpl)

**Comment by sachiac** [comment]
FWIW, this runs OK on a fedora 40 host using the same version

**Comment by haampie** [comment]
I guess something goes wrong detecting compilers (is `spack compiler list` empty?) and then the next the error message is horrible, it should've just said there are no compilers.

**Comment by alalazo** [comment]
The error above is because Spack has no compilers configured. This should be solved by #45189, since compilers are automatically detected, if none is available:
```console
$ spack compiler list
==> No compilers available. Run `spack compiler find` to autodetect compilers
$ spack spec zlib-ng
==> Compilers have been configured automatically from PATH inspection
 -   zlib-ng@2.2.3+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^compiler-wrapper@1.0 build_system=generic arch=linux-ubuntu20.04-icelake
[e]      ^gcc@10.5.0~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages='c,c++,fortran' patches=2c18531 arch=linux-ubuntu20.04-icelake
 -       ^gcc-runtime@10.5.0 build_system=generic arch=linux-ubuntu20.04-icelake
[e]      ^glibc@2.31 build_system=autotools arch=linux-ubuntu20.04-icelake
 -       ^gmake@4.4.1~guile build_system=generic arch=linux-ubuntu20.04-icelake
```
