### ISSUE TITLE
Installation issue: Variant `~mpi` not working for py-netcdf4@1.7.1 

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#47652]
### Steps to reproduce the issue

The latest version of py-netcdf4 fails to build when the variant `~mpi` is set, because it still wants `mpi4py` (see error message below).
```console
$ spack spec py-netcdf4 ~mpi
Input spec
--------------------------------
 -   py-netcdf4~mpi

Concretized
--------------------------------
 -   py-netcdf4@1.7.1.post2%oneapi@2024.2.1~mpi build_system=python_pip patches=255b5ae arch=linux-oracle9-skylake
[e]      ^glibc@2.34%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]      ^hdf5@1.14.3%oneapi@2024.2.1~cxx+fortran+hl~ipo~java~map+mpi+shared~subfiling~szip+threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8,f42732a arch=linux-oracle9-skylake
[+]          ^cmake@3.27.9%oneapi@2024.2.1~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892 arch=linux-oracle9-skylake
[+]          ^gmake@4.4.1%gcc@11.4.1~guile build_system=generic arch=linux-oracle9-skylake
[+]              ^gcc-runtime@11.4.1%gcc@11.4.1 build_system=generic arch=linux-oracle9-skylake
[e]          ^intel-oneapi-mpi@2021.13%oneapi@2024.2.1~classic-names+envmods~external-libfabric~generic-names~ilp64 build_system=generic arch=linux-oracle9-skylake
[+]          ^pkg-config@0.29.2%oneapi@2024.2.1+internal_glib build_system=autotools arch=linux-oracle9-skylake
[+]          ^zlib-ng@2.2.1%oneapi@2024.2.1+compat~new_strategies+opt+pic+shared build_system=autotools arch=linux-oracle9-skylake
[e]      ^intel-oneapi-runtime@2024.2.1%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake
[+]      ^netcdf-c@4.9.2%oneapi@2024.2.1+blosc~byterange+dap~fsync~hdf4~jna~logging+mpi~nczarr_zip+optimize~parallel-netcdf+pic+shared~szip+zstd build_system=autotools patches=0161eb8 arch=linux-oracle9-skylake
[+]          ^bzip2@1.0.8%oneapi@2024.2.1~debug~pic+shared build_system=generic arch=linux-oracle9-skylake
[e]              ^diffutils@3.7%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]          ^c-blosc@1.21.5%oneapi@2024.2.1+avx2~ipo build_system=cmake build_type=Release generator=make arch=linux-oracle9-skylake
[+]              ^lz4@1.10.0%oneapi@2024.2.1+pic build_system=makefile libs=shared,static arch=linux-oracle9-skylake
[+]              ^snappy@1.2.1%oneapi@2024.2.1~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-oracle9-skylake
[+]          ^curl@8.10.1%oneapi@2024.2.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-oracle9-skylake
[+]              ^nghttp2@1.63.0%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]          ^libxml2@2.10.3%oneapi@2024.2.1+pic~python+shared build_system=autotools arch=linux-oracle9-skylake
[+]              ^libiconv@1.17%oneapi@2024.2.1 build_system=autotools libs=shared,static arch=linux-oracle9-skylake
[+]          ^zstd@1.5.6%oneapi@2024.2.1+pic+programs build_system=makefile compression=none libs=shared,static arch=linux-oracle9-skylake
[+]      ^py-certifi@2023.7.22%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]      ^py-cftime@1.0.3.4%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]      ^py-cython@0.29.36%oneapi@2024.2.1 build_system=python_pip patches=c4369ad arch=linux-oracle9-skylake
[+]      ^py-numpy@1.26.4%oneapi@2024.2.1 build_system=python_pip patches=873745d arch=linux-oracle9-skylake
[e]          ^intel-oneapi-mkl@2024.2%oneapi@2024.2.1~cluster+envmods~gfortran~ilp64+shared build_system=generic mpi_family=none threads=none arch=linux-oracle9-skylake
[+]          ^py-meson-python@0.16.0%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]              ^meson@1.5.1%oneapi@2024.2.1 build_system=python_pip patches=0f0b1bd arch=linux-oracle9-skylake
[+]                  ^ninja@1.12.1%oneapi@2024.2.1+re2c build_system=generic arch=linux-oracle9-skylake
[+]                      ^re2c@3.1%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]              ^py-pyproject-metadata@0.7.1%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]      ^py-pip@23.1.2%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake
[+]      ^py-setuptools@69.2.0%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake
[+]      ^py-setuptools-scm@8.0.4%oneapi@2024.2.1+toml build_system=python_pip arch=linux-oracle9-skylake
[e]          ^git@2.43.0%oneapi@2024.2.1+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-oracle9-skylake
[+]          ^py-packaging@24.1%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]              ^py-flit-core@3.8.0%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]          ^py-tomli@2.0.1%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]          ^py-typing-extensions@4.12.2%oneapi@2024.2.1 build_system=python_pip arch=linux-oracle9-skylake
[+]      ^py-wheel@0.41.2%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake
[+]      ^python@3.11.7%oneapi@2024.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic~pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-oracle9-skylake
[+]          ^gdbm@1.23%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[e]          ^gettext@0.21%oneapi@2024.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-oracle9-skylake
[+]          ^libffi@3.4.6%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]          ^libxcrypt@4.4.35%oneapi@2024.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-oracle9-skylake
[+]              ^perl@5.40.0%oneapi@2024.2.1+cpanm+opcode+open+shared+threads build_system=generic arch=linux-oracle9-skylake
[+]                  ^berkeley-db@18.1.40%oneapi@2024.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-oracle9-skylake
[+]          ^ncurses@6.5%oneapi@2024.2.1~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-oracle9-skylake
[+]          ^openssl@3.4.0%oneapi@2024.2.1~docs+shared build_system=generic certs=mozilla arch=linux-oracle9-skylake
[+]              ^ca-certificates-mozilla@2023-05-30%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake
[+]          ^readline@8.2%oneapi@2024.2.1 build_system=autotools patches=bbf97f1 arch=linux-oracle9-skylake
[+]          ^sqlite@3.46.0%oneapi@2024.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-oracle9-skylake
[+]          ^util-linux-uuid@2.40.2%oneapi@2024.2.1 build_system=autotools arch=linux-oracle9-skylake
[+]          ^xz@5.4.6%oneapi@2024.2.1~pic build_system=autotools libs=shared,static arch=linux-oracle9-skylake
[+]      ^python-venv@1.0%oneapi@2024.2.1 build_system=generic arch=linux-oracle9-skylake```


### Error message

<details><summary>Error message</summary>

<pre>
==> py-netcdf4: Executing phase: 'install'
==> [2024-11-17-07:40:08.091994] '/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/python-venv-1.0-r37ymjk/bin/python3' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-netcdf4-1.7.1.post2-dcdo2to' '.'
Using pip 23.1.2 from /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip (python 3.11)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-build-tracker-zfv60wqm
Initialized build tracking at /tmp/pip-build-tracker-zfv60wqm
Created build tracker: /tmp/pip-build-tracker-zfv60wqm
Entered build tracker: /tmp/pip-build-tracker-zfv60wqm
Created temporary directory: /tmp/pip-install-to48_07u
Created temporary directory: /tmp/pip-ephem-wheel-cache-pcbjai57
Processing /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/cache/build_stage/spack-stage-py-netcdf4-1.7.1.post2-dcdo2tojqw6mhlxqcjfkxs6f7wesrjpl/spack-src
  Added file:///home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/cache/build_stage/spack-stage-py-netcdf4-1.7.1.post2-dcdo2tojqw6mhlxqcjfkxs6f7wesrjpl/spack-src to build tracker '/tmp/pip-build-tracker-zfv60wqm'
  Created temporary directory: /tmp/pip-modern-metadata-_nagpvpz
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  -L/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/netcdf-c-4.9.2-d75t5eo/lib -lnetcdf
  -L/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/hdf5-1.14.3-dh4r5rf/lib -lhdf5
  using /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/netcdf-c-4.9.2-d75t5eo/bin/nc-config...
  checking /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/netcdf-c-4.9.2-d75t5eo/include...
  hdf5 headers not found in /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/netcdf-c-4.9.2-d75t5eo/include
  nc-config did provide path to HDF5 headers, search standard locations...
  checking /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/hdf5-1.14.3-dh4r5rf/include...
  HDF5 library version: 1.14.3 headers found in /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/hdf5-1.14.3-dh4r5rf/include
  HDF5 library version: 1.14.3 found in /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/hdf5-1.14.3-dh4r5rf
  using netcdf library version b'4.9.2'
  using Cython to compile netCDF4.pyx...
  netcdf lib has parallel functions
  Traceback (most recent call last):
    File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-setuptools-69.2.0-5qnsl6t/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-setuptools-69.2.0-5qnsl6t/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 401, in <module>
  ModuleNotFoundError: No module named 'mpi4py'
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/python-venv-1.0-r37ymjk/bin/python3 /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpmbiu7_z3
  cwd: /home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/cache/build_stage/spack-stage-py-netcdf4-1.7.1.post2-dcdo2tojqw6mhlxqcjfkxs6f7wesrjpl/spack-src
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 713, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/envs/ue-oneapi-2024.2.1/install/oneapi/2024.2.1/py-pip-23.1.2-lph5dyp/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
Removed file:///home/dom/work/spack-stack/spack-stack-unpin-shapely-etc-and-fewer-modules/cache/build_stage/spack-stage-py-netcdf4-1.7.1.post2-dcdo2tojqw6mhlxqcjfkxs6f7wesrjpl/spack-src from build tracker '/tmp/pip-build-tracker-zfv60wqm'
Removed build tracker: '/tmp/pip-build-tracker-zfv60wqm'
</pre></details>


### Information on your system

```
$ spack debug report
* **Spack:** 0.23.0.dev0 (b6ef265ec4582ddca131534a9d314e233919ae69)
* **Python:** 3.9.18
* **Platform:** linux-oracle9-skylake
```

### Additional information

[spack-build-01-install-out.txt](https://github.com/user-attachments/files/17791900/spack-build-01-install-out.txt)
[spack-build-env.txt](https://github.com/user-attachments/files/17791901/spack-build-env.txt)
[spack-build-env-mods.txt](https://github.com/user-attachments/files/17791902/spack-build-env-mods.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/17791903/spack-build-out.txt)

Tagging @skosukhin as instructed below

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Chrismarsh** [comment]
The `netcdf-c` and `hdf5` packages enable their `+mpi` variants by default. I've made the changes in #47824 to fix this.
