### ISSUE TITLE
`spack ci reproduce-build` errors when the working dir is `pwd`

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#47677]
### Steps to reproduce

```console
$ spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/13748522/artifacts --working-dir .
==> Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/13748522/artifacts

==> Job ran with the following image: ghcr.io/spack/tutorial-ubuntu-22.04:v2023-10-30
checkout_commit: 2e71bc640c1ccc273b7bc71f5791316ec1832157
merge_commit: 6421e2a557b5e4c34db7d5908d6508966cb481e0
==> Job ran with the following tags: ['x86_64_v3', 'spack', 'public']
==> Error: 'entrypoint.sh' and '/tmp/foo/entrypoint.sh' are the same file
```

### Error message

```
==> [2024-11-19-17:32:21.008478] spack entrypoint arguments: [['git', 'config', '--global', '--add', 'safe.directory', '/builds/spack/spack'], ['.', '/builds/spack/spack/share/spack/setup-env.sh'], [], ['spack', 'env', 'activate', '/builds/spack/spack/jobs_scratch_dir/concrete_environment'], ['/builds/spack/spack/jobs_scratch_dir/reproduction/install.sh'], ['echo', 'Re-run install script using:\n\t/builds/spack/spack/jobs_scratch_dir/reproduction/install.sh'], ['exec', '$@']]
Traceback (most recent call last):
  File "/home/culpo/github/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/main.py", line 1013, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/main.py", line 966, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/main.py", line 996, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/main.py", line 592, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/cmd/ci.py", line 677, in ci
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/cmd/ci.py", line 632, in ci_reproduce
    return spack_ci.reproduce_ci_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/github/spack/lib/spack/spack/ci.py", line 1795, in reproduce_ci_job
    process_command(
  File "/home/culpo/github/spack/lib/spack/spack/ci.py", line 1923, in process_command
    shutil.copyfile(script, copy_path)
  File "/home/culpo/opt/pythons/store/linux-ubuntu20.04-icelake/gcc-9.4.0/python-3.11.5-h5d2gutqb6teuasq5i7vfryha2wszqqa/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'entrypoint.sh' and '/tmp/foo/entrypoint.sh' are the same file
```

### Information on your system

* **Spack:** 0.24.0.dev0 (5325cfe8654ef6e7f02a7ed1e892a4f2870d07f0)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@scottwittenburg @kwryankrattiger fyi

**Comment by haampie** [comment]
Also if you run this command a second time it fails.
