### ISSUE TITLE
Installation issue: All packages (also curl)

### ISSUE THREAD

**Issue by hjjvandam** [LLNL/spack#47694]
### Steps to reproduce the issue

```console
$ spack spec -I curl
/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
```

### Error message

<details><summary>Error message</summary>

<pre>
Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
</pre></details>

### Information on your system

spack debug report
* **Spack:** 0.24.0.dev0 (0ff3e863151a2c74ac202eefc0b4d3f65b39a85e)
* **Python:** 3.9.18
* **Platform:** linux-almalinux9-aarch64

### Additional information

@alecbcs 
[spack-build-out.txt.gz](https://github.com/user-attachments/files/17833149/spack-build-out.txt.gz)
[spack-build-env.txt](https://github.com/user-attachments/files/17833150/spack-build-env.txt)

Note that my problems started on Monday when the new version AlmaLinux 9.5 was released. With it the GCC compilers were promoted from version 11.4.1 to 11.5.0. The result was that the GCC compilers were rejected as is shown below with the output of `spack -d install curl`. I tested the GCC C-compiler with "hello world" and it compiled and ran fine. So it isn't that the compiler is not available or not working properly. There must be another reason that Spack rejects the compilers. 
```bash
$spack -d install curl
==> [2024-11-20-15:59:31.208835] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/config.yaml
==> [2024-11-20-15:59:31.252694] Imported install from built-in commands
==> [2024-11-20-15:59:31.253454] Imported install from built-in commands
==> [2024-11-20-15:59:31.260411] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/concretizer.yaml
==> [2024-11-20-15:59:31.285196] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-20-15:59:31.285242] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-20-15:59:31.289379] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/packages.yaml
==> [2024-11-20-15:59:31.318874] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/repos.yaml
==> [2024-11-20-15:59:32.123097] Reading config from file /home/hubertusvandam.linux/.spack/linux/compilers.yaml
==> [2024-11-20-15:59:32.340482] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-20-15:59:32.340553] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-20-15:59:32.351641] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/mirrors.yaml
==> [2024-11-20-15:59:32.388499] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-20-15:59:32.388570] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-20-15:59:32.394841] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/bootstrap.yaml
==> [2024-11-20-15:59:32.403228] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/repos.yaml
==> [2024-11-20-15:59:32.406488] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/packages.yaml
==> [2024-11-20-15:59:32.430200] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-11-20-15:59:32.431016] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/bootstrap.yaml
==> [2024-11-20-15:59:32.435202] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults
==> [2024-11-20-15:59:32.435229] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/linux
==> [2024-11-20-15:59:32.435260] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/hubertusvandam.linux/.spack/bootstrap/config
==> [2024-11-20-15:59:32.435277] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/hubertusvandam.linux/.spack/bootstrap/config/linux
==> [2024-11-20-15:59:32.436458] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/config.yaml
==> [2024-11-20-15:59:32.447179] Reading config from file /home/hubertusvandam.linux/.spack/bootstrap/config/linux/config.yaml
==> [2024-11-20-15:59:32.452464] DATABASE LOCK TIMEOUT: 60s
==> [2024-11-20-15:59:32.452488] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-11-20-15:59:32.453243] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/packages.yaml
==> [2024-11-20-15:59:32.468438] Reading config from file /home/hubertusvandam.linux/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-11-20-15:59:32.474947] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=aarch64
==> [2024-11-20-15:59:32.474967] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-11-20-15:59:32.475707] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/bootstrap.yaml
==> [2024-11-20-15:59:32.519798] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc platform=linux target=aarch64 ^python@3.9/a5mztd53ktxnhvzkr3lqaceuw2tmi3bv" provides the "clingo" Python module
==> [2024-11-20-15:59:32.520914] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/concretizer.yaml
==> [2024-11-20-15:59:36.289891] Reading config from file /Users/hubertusvandam/Documents/spack.nosync/etc/spack/defaults/packages.yaml
==> [2024-11-20-15:59:36.310657] Reading config from file /home/hubertusvandam.linux/.spack/linux/compilers.yaml
==> [2024-11-20-15:59:36.318425] the C compiler /usr/bin/gcc does not exist, or does not run correctly. The compiler gcc@=11.5.0 will not be used during concretization.
/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

==> [2024-11-20-15:59:39.818948] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
==> [2024-11-20-15:59:39.819041] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
==> [2024-11-20-15:59:39.819077] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
Traceback (most recent call last):
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/main.py", line 1013, in main
    return _main(argv)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/main.py", line 966, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/main.py", line 996, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/main.py", line 592, in _invoke_command
    return_val = command(parser, args)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/cmd/install.py", line 351, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/cmd/install.py", line 465, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/cmd/install.py", line 432, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/cmd/__init__.py", line 185, in parse_specs
    return _concretize_spec_pairs(to_concretize, tests=tests)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/cmd/__init__.py", line 199, in _concretize_spec_pairs
    return [concrete or abstract.concretized()]
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/spec.py", line 2973, in concretized
    clone.concretize(tests=tests)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/spec.py", line 2855, in concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/asp.py", line 4409, in solve
    result, _, _ = self.solve_with_stats(specs, **kwargs)
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/asp.py", line 4399, in solve_with_stats
    return self.driver.solve(
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/asp.py", line 950, in solve
    result.raise_if_unsat()
  File "/Users/hubertusvandam/Documents/spack.nosync/lib/spack/spack/solver/asp.py", line 479, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    curl is unsatisfiable
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
can you remove you compiler config (`spack config blame compilers`) and run spack compiler find again?

**Comment by hjjvandam** [comment]
Thanks. I have tried that now. But the outcome remains unchanged. Spack still rejects the compilers. The compilers.yaml reads
```yaml
compilers:
- compiler:
    spec: gcc@=11.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: almalinux9
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```
which seems correct. The file `/usr/bin/gcc` exists and I get
```bash
/usr/bin/gcc --version
gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-2)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
which is what I expect.

**Comment by haampie** [comment]
Can you follow the steps in https://github.com/spack/spack/issues/47385#issuecomment-2455255882 / https://github.com/spack/spack/issues/47385#issuecomment-2456486251?

Looks like in your case though we have no verbose compilation output from the compiler. It's cached in `~/.spack/cache/compilers/compilers.json` normally, I gues it cached an empty string or something. Could see if that's true and whether deleting that file fixes the issue.

**Comment by hjjvandam** [comment]
I think you are right. I have debugged this a little bit and found that the code reuses the compiler cache rather than actually trying whether the compiler works. The `~/.spack/cache/compilers/compilers.json` contained
```json
{"349c58973ec6b47bfcbf611a0509f625afcd5357b7c3535b573d2a76d35aab2b":{"c_compiler_output":null,"real_version":"11"}}
```
I guess this result stemmed from the period when I was trying to build a new container while the new version of AlmaLinux was being rolled out. During those few hours there were inconsistencies on the mirrors regarding the package catalogues and the packages that were actually present. Some time on Tuesday this cache file was created as a result. Since then nothing worked anymore. Deleting this cache file solved the problem. The newly generated cache file contains something like
```json
{"349c58973ec6b47bfcbf611a0509f625afcd5357b7c3535b573d2a76d35aab2b":{"c_compiler_output":"Using built-in specs.\n[...]","real_version":"11"}}
```
Meaning `c_compiler_output` is no longer `null` and now Spack is happy to use the GCC compilers again.
