### ISSUE TITLE
spack cannot install or spec anything from a fresh install

### ISSUE THREAD

**Issue by Omstavan** [LLNL/spack#47760]
### Steps to reproduce

Spack cannot install anything on a fresh WSL ubuntu install and fresh spack. I have tried wiping and reinstalling WSL and reinstalling Ubuntu 22.04 and 24.04 on WSL. I have looked at bug #44145 and #44154 and I don't think this is the same issue as I tried to switch to the latest develop branch (develop-2024-11-17) and still got the same error. I start with a completely fresh install of WSL ( details listed in the last section ). I run  
```
 git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh 
```

And attempting to install or spec anything, for e.g. using the command:

`spack install lmod` gives the error:
``` 
spack install lmod
==> Fetching https://ghcr.io/v2/spack/bootstrap-buildcache-v1/blobs/sha256:af305366a56ff47603977201d86a296cfaf6f5e6ed38412ecd68efb3e8ad9799
==> Fetching https://ghcr.io/v2/spack/bootstrap-buildcache-v1/blobs/sha256:97f8ea17f3df3fb38904450114cbef9b4b0ea9c94da9de7a49b70b707012277a
==> Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs+ipo+optimized+python+static_libstdcpp build_system=cmake build_type=Release generator=make patches=bebb819,ec99431 arch=linux-centos7-x86_64" from a buildcache
/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lmod is unsatisfiable
```

### Error message

```
spack --debug --stacktrace install lmod
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:38:44.960262] Reading config from file /home/omstavan/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:125 ==> [2024-11-23-16:38:44.982985] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:125 ==> [2024-11-23-16:38:44.983827] Imported install from built-in commands
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:38:44.984883] Reading config from file /home/omstavan/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/database.py:596 ==> [2024-11-23-16:38:44.999606] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-23-16:38:44.999923] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:38:45.000359] Reading config from file /home/omstavan/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:38:45.019006] Reading config from file /home/omstavan/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/database.py:596 ==> [2024-11-23-16:39:08.395025] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-23-16:39:08.395222] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.408714] Reading config from file /home/omstavan/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/database.py:596 ==> [2024-11-23-16:39:08.419356] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-23-16:39:08.419524] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.419752] Reading config from file /home/omstavan/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.423552] Reading config from file /home/omstavan/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.424558] Reading config from file /home/omstavan/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/config.py:126 ==> [2024-11-23-16:39:08.438824] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.439345] Reading config from file /home/omstavan/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:139 ==> [2024-11-23-16:39:08.442450] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/omstavan/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:140 ==> [2024-11-23-16:39:08.442625] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/omstavan/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:139 ==> [2024-11-23-16:39:08.442742] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/omstavan/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:140 ==> [2024-11-23-16:39:08.442847] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/omstavan/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.443787] Reading config from file /home/omstavan/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:596 ==> [2024-11-23-16:39:08.452057] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:183 ==> [2024-11-23-16:39:08.452256] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:08.454018] Reading config from file /home/omstavan/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:242 ==> [2024-11-23-16:39:09.152326] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc platform=linux target=x86_64
lib/spack/spack/bootstrap/core.py:345 ==> [2024-11-23-16:39:09.152541] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:09.152935] Reading config from file /home/omstavan/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/core.py:227 ==> [2024-11-23-16:39:09.161851] Bootstrapping clingo from pre-built binaries
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:09.162816] Reading config from file /home/omstavan/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:74 ==> [2024-11-23-16:39:09.167573] certs: relative path not allowed: $SSL_CERT_FILE
lib/spack/spack/database.py:596 ==> [2024-11-23-16:39:10.309392] DATABASE LOCK TIMEOUT: Nones
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.335295] Reading config from file /home/omstavan/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.336982] Reading config from file /home/omstavan/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.344086] Reading config from file /home/omstavan/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/fetch_strategy.py:527 ==> [2024-11-23-16:39:10.792425] Using cached archive: /home/omstavan/spack/var/spack/cache/blobs/sha256/af305366a56ff47603977201d86a296cfaf6f5e6ed38412ecd68efb3e8ad9799
lib/spack/spack/fetch_strategy.py:527 ==> [2024-11-23-16:39:10.797955] Using cached archive: /home/omstavan/spack/var/spack/cache/blobs/sha256/97f8ea17f3df3fb38904450114cbef9b4b0ea9c94da9de7a49b70b707012277a
lib/spack/spack/binary_distribution.py:2614 ==> [2024-11-23-16:39:10.802590] Verified SHA256 checksum of the build cache
lib/spack/spack/binary_distribution.py:2618 ==> [2024-11-23-16:39:10.803197] Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs+ipo+optimized+python+static_libstdcpp build_system=cmake build_type=Release generator=make patches=bebb819,ec99431 arch=linux-centos7-x86_64" from a buildcache
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.805256] Reading config from file /home/omstavan/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/binary_distribution.py:2271 ==> [2024-11-23-16:39:10.902212] Relocating package from
  /root/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_place to /home/omstavan/.spack/bootstrap/store.
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.920019] Reading config from file /home/omstavan/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.926512] Reading config from file /home/omstavan/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/hooks/module_file_generation.py:23 ==> [2024-11-23-16:39:10.928433] NO MODULE WRITTEN: list of enabled module files is empty
lib/spack/spack/hooks/drop_redundant_rpaths.py:100 ==> [2024-11-23-16:39:10.932057] Patched rpath in lib/python3.12/site-packages/clingo.cpython-312-x86_64-linux-gnu.so from b'/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/gcc-runtime-10.2.1-7rv2b76tgxqmkwtmngiamwac632cjjba/lib:/opt/_internal/cpython-3.12.7/lib:/opt/python/cp312-cp312/lib:/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10' to b'/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64'
lib/spack/spack/hooks/drop_redundant_rpaths.py:100 ==> [2024-11-23-16:39:10.932600] Patched rpath in lib64/libclingo.so.4.0 from b'/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/gcc-runtime-10.2.1-7rv2b76tgxqmkwtmngiamwac632cjjba/lib:/opt/_internal/cpython-3.12.7/lib:/opt/python/cp312-cp312/lib:/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10' to b'/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib:/home/omstavan/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack-et3twemsecqryfzl23e3cmsbca534dlo/lib64'
lib/spack/spack/bootstrap/_common.py:94 ==> [2024-11-23-16:39:10.947096] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack%gcc+python arch=linux-None-x86_64 ^python@3.12/et3twemsecqryfzl23e3cmsbca534dlo" provides the "clingo" Python module
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:10.947749] Reading config from file /home/omstavan/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:11.087445] Reading config from file /home/omstavan/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:11.104335] Reading config from file /home/omstavan/.spack/linux/compilers.yaml
lib/spack/spack/config.py:1097 ==> [2024-11-23-16:39:11.313361] Reading config from file /home/omstavan/spack/etc/spack/defaults/config.yaml
/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1160:3-38: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1266:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1267:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1311:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1319:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1320:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1326:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1327:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1366:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1387:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1388:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1389:6-41: info: atom does not occur in any rule head:
  compiler_os(CompilerID,CompilerOS)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1415:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1416:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1417:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1421:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1422:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1423:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1442:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/omstavan/spack/lib/spack/spack/solver/concretize.lp:1443:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

lib/spack/spack/cmd/install.py:436 ==> [2024-11-23-16:39:15.886625] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lmod is unsatisfiable
lib/spack/spack/main.py:1016 ==> [2024-11-23-16:39:15.886880] SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lmod is unsatisfiable
lib/spack/spack/error.py:55 ==> [2024-11-23-16:39:15.898271] Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lmod is unsatisfiable
Traceback (most recent call last):
  File "/home/omstavan/spack/lib/spack/spack/main.py", line 1013, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/main.py", line 966, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/main.py", line 996, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/main.py", line 592, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/cmd/install.py", line 351, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/omstavan/spack/lib/spack/spack/cmd/install.py", line 465, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/cmd/install.py", line 432, in concrete_specs_from_cli
    concrete_specs = spack.cmd.parse_specs(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/cmd/__init__.py", line 185, in parse_specs
    return _concretize_spec_pairs(to_concretize, tests=tests)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/cmd/__init__.py", line 199, in _concretize_spec_pairs
    return [concrete or abstract.concretized()]
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/spec.py", line 2973, in concretized
    clone.concretize(tests=tests)
  File "/home/omstavan/spack/lib/spack/spack/spec.py", line 2855, in concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/solver/asp.py", line 4410, in solve
    result, _, _ = self.solve_with_stats(specs, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/solver/asp.py", line 4400, in solve_with_stats
    return self.driver.solve(
           ^^^^^^^^^^^^^^^^^^
  File "/home/omstavan/spack/lib/spack/spack/solver/asp.py", line 951, in solve
    result.raise_if_unsat()
  File "/home/omstavan/spack/lib/spack/spack/solver/asp.py", line 480, in raise_if_unsat
    raise SolverError(constraints, conflicts=conflicts)
spack.solver.asp.SolverError: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    lmod is unsatisfiable
```

### Information on your system

```
spack debug report
* **Spack:** 0.24.0.dev0 (39a081d7fd3935aad8891446508fa773f6e2408c)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu24.04-skylake
```

WSL version
```
PS C:\Users\omsta> wsl --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2454
```
Ubuntu version:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```
I don't think this is related to #47565 because that error message also seems to have a bunch of "permission denied". However, the `spack compiler list` command indeed seems to be empty:
```
spack compiler list
==> No compilers available. Run `spack compiler find` to autodetect compilers
spack compiler find
==> Found no new compilers
==> Compilers are defined in the following files:
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Omstavan** [comment]
Installing `build-essential` resolved the issue by adding compilers. I will close this bug, since my issue is resolved, but the error message might need improvement. It might also be useful to list requirements, since I assumed spack could fulfill the requirements by bootstrapping but it didn't do it here.
