### ISSUE TITLE
Installation issue: sundials

### ISSUE THREAD

**Issue by pbrady** [LLNL/spack#48140]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
^sundials@7.1.1%clang@17.0.6 cxxflags='--gcc-install-dir=/vast/projects/opt/centos8/x86_64/gcc/11.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0' +ARKODE~CVODE~CVODES~IDA~IDAS~KINSOL~cuda~examples~examples-install~f2003~fcmix~ginkgo~hypre~int64~ipo~klu~kokkos~kokkos-kernels~lapack~magma~monitoring~mpi~openmp~petsc~profiling~pthread~raja~rocm+shared+static~superlu-dist~superlu-mt~sycl~trilinos build_system=cmake build_type=Release cstd=99 cxxstd=17 generator=make logging-level=2 precision=double arch=linux-rhel8-haswell
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing sundials-7.1.1-vero2hzzrf3i43w4rehzapttgn3v7tfy [26/29]
==> No binary for sundials-7.1.1-vero2hzzrf3i43w4rehzapttgn3v7tfy found: installing from source
==> Using cached archive: /vast/home/ptb/spack/var/spack/cache/_source-cache/git//LLNL/sundials.git/c28eaa3764a03705d61decb6025b409360e9d53f.tar.gz
==> Warning: Using download cache instead of version control
  The required sources are normally checked out from a version control system, but have been archived in download cache: file:///vast/home/ptb/spack/var/spack/cache/_source-cache/git//LLNL/sundials.git/c28eaa3764a03705d61decb6025b409360e9d53f.tar.gz. Spack lacks a tree hash to verify the integrity of this archive. Make sure your download cache is in a secure location.
==> No patches needed for sundials
==> sundials: Executing phase: 'cmake'
==> sundials: Executing phase: 'build'
==> sundials: Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/vast/home/ptb/spack/opt/spack/linux-rhel8-haswell/clang-17.0.6/sundials-7.1.1-vero2hzzrf3i43w4rehzapttgn3v7tfy/examples/arkode/C_openmp/Makefileffg82uhn'

/vast/home/ptb/spack/var/spack/repos/builtin/packages/sundials/package.py:683, in filter_compilers:
        680
        681        for filename in cc_files:
        682            filter_file(
  >>    683                os.environ["CC"], self.compiler.cc, os.path.join(dirname, filename), **kwargs
        684            )
        685
        686        for filename in cc_files:
</pre></details>

### Information on your system

* **Spack:** 0.24.0.dev0 (c213a8c2a727e494b2f5ebc1c17e22b239312738)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-haswell

### Additional information

[spack-build-out.txt](https://github.com/user-attachments/files/18154790/spack-build-out.txt)

The error is a post-install error so the application is able to successfully use sundials.  It seems the error is related to filtering example files.  However, I have built sundials with `~examples` so the file isn't there.

maintainers:
@balos1 @cswoodward @gardner48 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by pbrady** [comment]
I've tried this with a few different combinations and so far this only impacts clang.  gcc runs through the build without errors

**Comment by pbrady** [comment]
I ran with `--debug` here's the relevant portion of the output.  Note that the original reported error was on a linux system.  This same error occurs on my mac:

```console
==> [2024-12-19-10:06:41.415457] Installing sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna [39/90]
==> [2024-12-19-10:06:41.417194] No binary for sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna found: installing from source
==> Warning: Using download cache instead of version control
  The required sources are normally checked out from a version control system, but have been archived in download cache: file:///Users/ptb/gitrepos/spack/var/spack/cache/_source-cache/git//LLNL/sundials.git/c28eaa3764a03705d61decb6025b409360e9d53f.tar.gz. Spack lacks a tree hash to verify the integrity of this archive. Make sure your download cache is in a secure location.
==> Using cached archive: /Users/ptb/gitrepos/spack/var/spack/cache/_source-cache/git//LLNL/sundials.git/c28eaa3764a03705d61decb6025b409360e9d53f.tar.gz
==> No patches needed for sundials
==> sundials: Executing phase: 'cmake'
==> sundials: Executing phase: 'build'
==> sundials: Executing phase: 'install'
==> [2024-12-19-10:07:09.699304] Error: FileNotFoundError: [Errno 2] No such file or directory: '/Users/ptb/gitrepos/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna/examples/arkode/C_openmp/Makefileu4gnouo2'

/Users/ptb/gitrepos/spack/var/spack/repos/builtin/packages/sundials/package.py:682, in filter_compilers:
        679        ]
        680
        681        for filename in cc_files:
  >>    682            filter_file(
        683                os.environ["CC"], self.compiler.cc, os.path.join(dirname, filename), **kwargs
        684            )
        685

See build log for details:
  /var/folders/c7/8jd35_cn1d780xhx4jwpzt40000rgj/T/ptb/spack-stage/spack-stage-sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna/spack-build-out.txt

Traceback (most recent call last):
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/build_environment.py", line 1207, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/installer.py", line 2492, in build_process
    return installer.run()
           ~~~~~~~~~~~~~^^
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/installer.py", line 2368, in run
    self._real_install()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/installer.py", line 2457, in _real_install
    phase_fn.execute()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/builder.py", line 359, in execute
    callback(self.builder)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/ptb/gitrepos/spack/lib/spack/spack/builder.py", line 272, in _wrapped
    return fn(builder.pkg_with_dispatcher)
  File "/Users/ptb/gitrepos/spack/var/spack/repos/builtin/packages/sundials/package.py", line 682, in filter_compilers
    filter_file(
    ~~~~~~~~~~~^
        os.environ["CC"], self.compiler.cc, os.path.join(dirname, filename), **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ptb/gitrepos/spack/lib/spack/llnl/util/filesystem.py", line 347, in filter_file
    fd, temp_path = tempfile.mkstemp(prefix=os.path.basename(path), dir=os.path.dirname(path))
                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ptb/gitrepos/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/python-3.13.0-6obz6cms4ak3tmtgyrcm2pc3th6i4oqc/lib/python3.13/tempfile.py", line 357, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/Users/ptb/gitrepos/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/python-3.13.0-6obz6cms4ak3tmtgyrcm2pc3th6i4oqc/lib/python3.13/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ptb/gitrepos/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna/examples/arkode/C_openmp/Makefileu4gnouo2'
==> [2024-12-19-10:07:09.699704] Flagging sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna as failed: FileNotFoundError: [Errno 2] No such file or directory: '/Users/ptb/gitrepos/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna/examples/arkode/C_openmp/Makefileu4gnouo2'
==> [2024-12-19-10:07:09.702304] No task for massapp-develop-6nt5o7rl2d5yy3ax2kpy7ib63rfvevrn to skip since sundials-7.1.1-6ppqot4fuo34rcbkexxetul2zhmy5qna failed
```

**Comment by pbrady** [comment]
So the error is due to `tempfile.mkstemp` trying to create a temp file in a directory that doesn't exist.  Seems like this should be done _after_ the `ignore_absent` check.  Here's the offending bit of code in `filesystem.py`:

```python
    for path in path_to_os_path(*filenames):
        fd, temp_path = tempfile.mkstemp(prefix=os.path.basename(path), dir=os.path.dirname(path))
        os.close(fd)

        if ignore_absent and not os.path.exists(path):
            tty.debug(f'FILTER FILE: file "{path}" not found. Skipping to next file.')
            continue
        else:
            tty.debug(f'FILTER FILE: {path} [replacing "{regex}"]')
```
I suppose clang and gcc coupled with cmake may have different rules on creating the directories.  I'll open a PR for further discussion on this potential solution

**Comment by pbrady** [comment]
Already fixed!
