### ISSUE TITLE
How to add new compiler entry on Cray platform?  (TypeError: sequence item 2: expected string, NoneType found)

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5051]
Spack auto-detects cray compilers/programming-environemnt and generate `$HOME/cray/compilers.yaml`. This works fine.

Now I would like create new environment (with additional modules) which has say `PrgEnv-intel` and `perftools` module also loaded. (typically for profiling code etc). So I created  `~/.spack/compilers.yaml` as:

```
 compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-intel
    - perftools
    - !!python/unicode 'intel/17.0.0.098'
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@18
    target: any
```

Say `intel@18` is new spec /version. Now I want to use it as:

```
$ spack -d install hdf %intel@18
==> Reading config file /gpfs/mira-home/kumbhar/spack/etc/spack/defaults/packages.yaml
==> Reading config file /home/kumbhar/.spack/cray/packages.yaml
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/kumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Released]
==> Reading config file /home/kumbhar/.spack/compilers.yaml
==> Reading config file /home/kumbhar/.spack/cray/compilers.yaml
==> WRITE LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Acquiring]
==> WRITE LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Acquired]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Released]
==> link /gpfs/mira-home/kumbhar/spack/var/spack/stage/hdf-4.2.13-ctnw3fw6wjv5vvu3iitdgbyzvy2x2j3p -> /tmp/kumbhar/spack-stage/spack-stage-lM2hY_
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Acquiring]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Acquired]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/prefix_lock[751457697703474669:1] [Released]
==> Installing hdf dependencies
==> flex@system : externally installed in /usr
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> flex@system : generating module file
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/mira-home/kumbhar/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE : flex@system%intel@18+lex arch=cray-CNL-mic_knl /nodwgbb [/gpfs/mira-home/kumbhar/spack/share/spack/modules/cray-CNL-mic_knl/flex-system-intel-18-nodwgbb]
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'perftools'
Traceback (most recent call last):
  File "/home/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/main.py", line 552, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/main.py", line 444, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/cmd/install.py", line 361, in install
    package.do_install(**kwargs)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/package.py", line 1241, in do_install
    **kwargs
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/package.py", line 1204, in do_install
    return self._process_external_package(explicit)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/package.py", line 1146, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/hooks/module_file_generation.py", line 32, in post_install
    generator.write()
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/modules.py", line 398, in write
    set_module_variables_for_package(self.pkg, self.pkg.module)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/build_environment.py", line 349, in set_module_variables_for_package
    m.std_cmake_args = spack.CMakePackage._std_args(pkg)
  File "/gpfs/mira-home/kumbhar/spack/lib/spack/spack/build_systems/cmake.py", line 116, in _std_args
    rpaths = ':'.join(spack.build_environment.get_rpaths(pkg))
TypeError: sequence item 2: expected string, NoneType found
```

Is it possible to create such mix environments on Cray system? Or is this a bug?

**Comment by pramodskumbhar** [comment]
my bad! sorry for noise! I thought `perftools-base` is not `prerequisite` on Cray KNL system. Typically we need to load `perftools-base` otherwise we get : 

```
module load perftools
--------------------------------------------------------------------------------
Error: The Perftools module is available only after the perftools-base module
is loaded.

The Perftools-base module:
    - Provides access to Perftools man pages, Reveal and Cray Apprentice2
    - Does not alter compiling or program behavior
    - Makes the following instrumentation modules available:
```

But I didn't see this warning/error in spack debug output. After adding `perftools-base` module in new compiler works fine.

We can close this ticket (it would be useful to get module error message though...)
