### ISSUE TITLE
How to build docs locally ? Getting "AttributeError: type object 'NewBase' has no attribute 'enabled'"

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5082]
How to build documentation locally?

I am reading instructions [here](http://spack.readthedocs.io/en/latest/contribution_guide.html?highlight=sphinx#documentation-tests) and doing:

```
cd lib/spack/docs
make clean
make
```

which gives:

```
make
sphinx-build -b html -d _build/doctrees  -E . _build/html
Running Sphinx v1.4.1
making output directory...
0.10.0
Creating file ./spack.rst.
Creating file ./spack.build_systems.rst.
Creating file ./spack.cmd.rst.
Creating file ./spack.cmd.common.rst.
Creating file ./spack.compilers.rst.
Creating file ./spack.hooks.rst.
Creating file ./spack.operating_systems.rst.
Creating file ./spack.platforms.rst.
Creating file ./spack.schema.rst.
Creating file ./spack.test.rst.
Creating file ./spack.test.cmd.rst.
Creating file ./spack.util.rst.
Creating file ./llnl.rst.
Creating file ./llnl.util.rst.
Creating file ./llnl.util.tty.rst.

Exception occurred:
  File "/Users/kumbhar/workarena/software/sources/spack/lib/spack/spack/fetch_strategy.py", line 84, in __init__
    if cls.enabled:
AttributeError: type object 'NewBase' has no attribute 'enabled'
The full traceback has been saved in /tmp/sphinx-err-LlqwUm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

And mentioned log file ` /tmp/sphinx-err-LlqwUm.log` has:

```
# Sphinx version: 1.4.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 132, in __init__
    confoverrides or {}, self.tags)
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 289, in __init__
    execfile_(filename, config)
  File "/Library/Python/2.7/site-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 508, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 122, in <module>
    import fileinput, spack
  File "/Users/kumbhar/workarena/software/sources/spack/lib/spack/spack/__init__.py", line 87, in <module>
    import spack.fetch_strategy
  File "/Users/kumbhar/workarena/software/sources/spack/lib/spack/spack/fetch_strategy.py", line 88, in <module>
    class FetchStrategy(with_metaclass(FSMeta, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/kumbhar/workarena/software/sources/spack/lib/spack/spack/fetch_strategy.py", line 84, in __init__
    if cls.enabled:
AttributeError: type object 'NewBase' has no attribute 'enabled'
```

**Comment by adamjstewart** [comment]
What version of `six` are you using?
```
$ python
>>> import six
>>> print(six.__version__)
1.10.0
```
Try upgrading to a newer version of `six` and see if that solves the problem.

**Comment by pramodskumbhar** [comment]
thanks @adamjstewart ! By default OS X had `1.4.1` which was causing this trouble.
All looks good after upgrade!
