### ISSUE TITLE
Issue with spack module refresh and multiple architectures with shared filesystem

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5218]
Suppose we have shared file system for `linux-centos7-ppc64le` (power8) and `linux-centos7-x86_64` system. When I check installed packages I see packages from both architectures:

```
$ spack find
==> 55 installed packages.
-- linux-centos7-ppc64le / gcc@4.8.5 ----------------------------
autoconf@system  cmake@3.8.1  ncurses@system          neuron@master    openmpi@2.0.2      py-appdirs@1.4.3  py-packaging@16.8  .....

-- linux-centos7-ppc64le / xl@14.1 ------------------------------
autoconf@system  cmake@3.8.1         hdf5@1.8.18    mod2c@develop           neurodamus@develop  openmpi@2.0.2             pkg-config@0.29.1     zlib@1.2.8 ....


-- linux-centos7-x86_64 / intel@17.0.1 --------------------------
autoconf@system  cmake@2.8.12  intelmpi@develop  mvapich2@2.2  neurodamus@hippocampus  ....
```
Now when I do `spack module refresh` I end up with:

```
mus/hippocampus-intel-ocno]
Traceback (most recent call last):
  File "/gpfs/homeb/pcp0/pcp0043/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/main.py", line 552, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/main.py", line 444, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/cmd/module.py", line 267, in module
    callbacks[args.subparser_name](module_type, specs, args)
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/cmd/module.py", line 251, in refresh
    x.write(overwrite=True)
  File "/gpfs/homeb/pcp0/pcp0043/spack/lib/spack/spack/modules.py", line 394, in write
    package.setup_dependent_package(self.pkg.module, self.spec)
  File "/gpfs/homeb/pcp0/pcp0043/spack/var/spack/repos/builtin/packages/intelmpi/package.py", line 37, in setup_dependent_package
    bindir = self.get_bin_dir()
  File "/gpfs/homeb/pcp0/pcp0043/spack/var/spack/repos/builtin/packages/intelmpi/package.py", line 20, in get_bin_dir
    raise RuntimeError('No suitable Intel MPI bindir found')
RuntimeError: No suitable Intel MPI bindir found
```
The `Intel MPI` module is available on `x86_64` login node and not `power8`. It seems like currently `refresh` command is trying to regenerate all modules. Is there any way to say just refresh modules for specific architecture? Or any other solution to avoid this issue?

**Comment by scheibelp** [comment]
It looks like you can specify a constraint like:

```spack module refresh arch=linux-rhel6-x86_64```

does that give you what you want?

**Comment by pramodskumbhar** [comment]
Oh, thats what I wanted!
I didn't realise `constraint`  means I can use regular constrains we use while packaging!
