### ISSUE TITLE
IOError in shebang_too_long

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#525]
I see this error from Spack, after (!) it tells me that everything was installed fine:

```
==> Staging archive: /home/eschnett/src/spack/var/spack/stage/petsc-3.6.3-n7zkl4axrbwhf4wxnhyxkgqt5mhb45fe/petsc-3.6.3.tar.gz
==> Created stage in /home/eschnett/src/spack/var/spack/stage/petsc-3.6.3-n7zkl4axrbwhf4wxnhyxkgqt5mhb45fe
==> No patches needed for petsc
==> Building petsc
==> Successfully installed petsc
  Fetch: 1m 8.63s.  Build: 4m 39.41s.  Total: 5m 48.04s.
[+] /home/eschnett/src/spack/opt/spack/linux-x86_64/gcc-5.3.0-spack/petsc-3.6.3-n7zkl4axrbwhf4wxnhyxkgqt5mhb45fe
Traceback (most recent call last):
  File "/home/eschnett/src/spack/bin/spack", line 176, in <module>
    main()
  File "/home/eschnett/src/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/home/eschnett/src/spack/lib/spack/spack/cmd/install.py", line 81, in install
    fake=args.fake)
  File "/home/eschnett/src/spack/lib/spack/spack/package.py", line 946, in do_install
    spack.hooks.post_install(self)
  File "/home/eschnett/src/spack/lib/spack/spack/hooks/__init__.py", line 69, in __call__
    hook(pkg)
  File "/home/eschnett/src/spack/lib/spack/spack/hooks/sbang.py", line 75, in post_install
    if shebang_too_long(path):
  File "/home/eschnett/src/spack/lib/spack/spack/hooks/sbang.py", line 39, in shebang_too_long
    with open(path, 'r') as script:
IOError: [Errno 21] Is a directory: '/home/eschnett/src/spack/opt/spack/linux-x86_64/gcc-5.3.0-spack/petsc-3.6.3-n7zkl4axrbwhf4wxnhyxkgqt5mhb45fe/bin/julia'
```

**Comment by alalazo** [comment]
The issue is known (see #517). Needs to be fixed.
