### ISSUE TITLE
[Question] External packages module requirement to work with Spack?

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5273]
Suppose I have following external module:

```
module show nix/bgq/cmake/3.3.2
-------------------------------------------------------------------
/gpfs-path-xxx//modules-bgq-lugano-all/nix/bgq/cmake/3.3.2:

module-whatis	 cmake for BGQ backend  generated by nix
prepend-path	 PATH /gpfs-path/store/636l7bvg95fvdyffddw8g94cxwsrb1v8-generated-env-module-cmake/bin
-------------------------------------------------------------------
```

Then I add entry in `packages.yaml` as :

```
    cmake:
        modules:
            cmake@3.3.2%xl@12.1 arch=bgq-cnk-ppc64: nix/bgq/cmake/3.3.2
        buildable: False
        version: [3.3.2]
```

While installation I see:

```
==> cmake@3.9.0 : generating module file
==> Error: 'NoneType' object has no attribute 'startswith'
```

Debug shows :

```
==> cmake@3.3.2 : generating module file
==> SKIP: shebang filtering [external package]
==> READ LOCK: /gpfs/bbp.cscs.ch/home/kumbhar/spack_install/bgq/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/bbp.cscs.ch/home/kumbhar/spack_install/bgq/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/bbp.cscs.ch/home/kumbhar/spack_install/bgq/.spack-db/lock[0:0] [Released]
==> 	WRITE : cmake@3.3.2%xl@12.1~doc+ncurses+openssl+ownlibs~qt arch=bgq-cnk-ppc64 /gshkzty [/gpfs/bbp.cscs.ch/home/kumbhar/spack_modules/bgq/tcl/bgq-cnk-ppc64/cmake-3.3.2-xl-12.1-gshkzty]
Traceback (most recent call last):
  File "/gpfs-path/softwares/sources/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/main.py", line 552, in main
    return _main(command, parser, args, unknown)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/main.py", line 444, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/cmd/install.py", line 361, in install
    package.do_install(**kwargs)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/package.py", line 1272, in do_install
    **kwargs
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/package.py", line 1272, in do_install
    **kwargs
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/package.py", line 1233, in do_install
    return self._process_external_package(explicit)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/package.py", line 1175, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/hooks/module_file_generation.py", line 32, in post_install
    generator.write()
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/modules.py", line 380, in write
    env = inspect_path(self.spec.prefix)
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/spec.py", line 1364, in prefix
    return Prefix(spack.store.layout.path_for_spec(self))
  File "/gpfs-path/softwares/sources/spack/lib/spack/spack/directory_layout.py", line 127, in path_for_spec
    assert(not path.startswith(self.root))
AttributeError: 'NoneType' object has no attribute 'startswith'
```

So are there any prerequisite for external modules to play nicely with Spack?

cc: @alalazo

**Comment by scheibelp** [comment]
Sorry about the late response: 

It seems Spack is generating a module file for the package even though the external package has a module. It probably shouldn't do that.

Could you list the command you are using which leads to this error? Something appears to have changed in your last 2 examples because the printouts are different with and without the debug:

`==> cmake@3.9.0 : generating module file`

and 

`==> cmake@3.3.2 : generating module file`

It also appears you are running with a version of Spack other than develop.

**Comment by pramodskumbhar** [comment]
I am trying now from develop. Here is module:

```
$ module show cmake/3.5.2
-------------------------------------------------------------------
/cineca/prod/opt/modulefiles/base/tools/cmake/3.5.2:

conflict	cmake
setenv	CMAKE_HOME	/cineca/prod/opt/tools/cmake/3.5.2/none
prepend-path	PATH	/cineca/prod/opt/tools/cmake/3.5.2/none/bin	:
module-whatis	cmake build system
-------------------------------------------------------------------
```

All cleanup:
```
$ spack module refresh --delete-tree -y
==> Regenerating tcl module files
$ rm -rf ~/SPACK_INSTALL/*
```

```
$ spack -d install -v reportinglib %intel
==> Reading config file /marconi/home/userexternal/pkumbhar/spack/etc/spack/defaults/packages.yaml
==> Reading config file /marconi/home/userexternal/pkumbhar/.spack/linux/packages.yaml
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Released]
==> Reading config file /marconi/home/userexternal/pkumbhar/.spack/linux/compilers.yaml
==> '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'list'
==> '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'show' 'cmake/3.5.2'
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Acquiring]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Released]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/prefix_lock[676478728866344491:1] [Released]
==> Installing reportinglib dependencies
==> cmake@3.5.2 : has external module in cmake/3.5.2
==> cmake@3.5.2 : is actually installed in None
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Released]
==> cmake@3.5.2 : generating module file
==> SKIP: shebang filtering [external package]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Released]
==> 	BLACKLIST : cmake@3.5.2%intel@17.0.4~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 /betoegn [matches : cmake  ]
==> cmake@3.5.2 : registering into DB
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /marconi/home/userexternal/pkumbhar/SPACK_INSTALL/knl/.spack-db/lock[0:0] [Released]
==> Installing reportinglib
==> Error: AttributeError: 'NoneType' object has no attribute 'startswith'
AttributeError: AttributeError: 'NoneType' object has no attribute 'startswith'

/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/build_environment.py:576, in child_process:
     26
     27                # build up some context from the offending package so we can
     28                # show that, too.
  >> 29                package_context = get_package_context(tb)
```

 `==> cmake@3.5.2 : is actually installed in None` gives hint?

**Comment by pramodskumbhar** [comment]
Another issue  (may be related to  #4667 ?):

I haven module entry into `compilers.yaml` as:

```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: [intel/pe-xe-2017--binary]
    operating_system: centos7
    paths:
      cc: /marconi/prod/opt/compilers/intel/pe-xe-2017/binary/bin/icc
```

And install gives: 

```
$ spack -d install -v mypackage 

==> Reading config file /marconi/home/userexternal/pkumbhar/spack/etc/spack/defaults/packages.yaml
==> Reading config file /marconi/home/userexternal/pkumbhar/.spack/linux/packages.yaml
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /marconi/home/userexternal/pkumbhar/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Released]
==> Reading config file /marconi/home/userexternal/pkumbhar/.spack/linux/compilers.yaml
==> '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'list'
==> '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'show' 'intel/pe-xe-2017--binary'
==> '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'unload' 'intel'
Traceback (most recent call last):
  File "/marconi/home/userexternal/pkumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/cmd/install.py", line 336, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/cmd/__init__.py", line 118, in parse_specs
    spec.concretize()  # implies normalize
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/spec.py", line 1909, in concretize
    load_module(mod)
  File "/marconi/home/userexternal/pkumbhar/spack/lib/spack/spack/util/module_cmd.py", line 134, in load_module
    error=str), '<string>', 'exec'))
  File "<string>", line 1, in <module>
  File "<string>", line 1
    /tmp/modulescript_49669_0
    ^
SyntaxError: invalid syntax
```

that file in `/tmp` looks like:

```
$ cat /tmp/modulescript_49669_0
os.unlink('/tmp/modulescript_49669_0')
import os
```

If I execute that modulecmd manually I get:

```
$ '/marconi/prod/opt/environment/module/3.2.10/none/modulecmd.tcl' 'python' 'unload' 'intel'
exec '/tmp/modulescript_50577_0'
```

On this [MARCONI system](http://www.hpc.cineca.it/news/marconi-new-cineca-supercomputer) I am not able use any modules. Any hints?

**Comment by scheibelp** [comment]
> Another issue (may be related to #4667 ?)

IMO it would be best to report this as a separate issue (and if you feel it is related then include a pointer to here).

I don't know if this is causing the problem you mention in https://github.com/LLNL/spack/issues/5273#issuecomment-328363658, but I notice two things:

* Your compiler entry doesn't include a `spec`
* The modules for the compiler entry is `intel/pe-xe-2017--binary` - is it supposed to contain two dashes?

**Comment by pramodskumbhar** [comment]
> IMO it would be best to report this as a separate issue 

ok, will do.

> Your compiler entry doesn't include a spec

updated full spec (Initially I copied just part of it)

> The modules for the compiler entry is intel/pe-xe-2017--binary - is it supposed to contain two dashes?

yes, all modules have two dashes:

```
petsc/3.7.5_complex--intelmpi--2017--binary
pnetcdf/1.7--intelmpi--2017--binary
....
```

**Comment by scheibelp** [comment]
Hi @alalazo I was wondering about your opinion on https://github.com/LLNL/spack/issues/5273#issuecomment-328248907 (namely that we shouldn't be generating module files for packages with `external-module`)

**Comment by pramodskumbhar** [comment]
> namely that we shouldn't be generating module files for packages with external-module

@alalazo ? Wouldn't it better use/load existing modules?

**Comment by alalazo** [comment]
@scheibelp Sorry for the late reply, I lost this among a lot of other Github notifications. I can think of at least one case in which we still want to generate module files for externals: `lmod` + the external provides a virtual spec that is part of the hierarchy. If you don't have the module in place, you won't be able to access to anything that depends on it.

**Comment by alalazo** [comment]
@pramodk Is this still an issue?

**Comment by pramodskumbhar** [comment]
@alalazo : I tried latest develop now and updated [this comment](https://github.com/LLNL/spack/issues/5273#issuecomment-328363658). If you have suggestions / need any debug info, let me know. This is on Marconi system @ Cineca.

**Comment by alalazo** [comment]
@pramodk This issue seems to me specific to Marconi, right? It's difficult to push this further without access to the system :smirk:

**Comment by pramodskumbhar** [comment]
yeah true, I am not actively working on marconi at the moment. If require we can close this for now. (when I get back to marconi, will try to get more debug info and then will reopen again)

**Comment by becker33** [comment]
@parmodskumbhar is this resolved by #12693?
