### ISSUE TITLE
Aborting spack install (Ctl+C) sometime makes shell unusable

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5629]
I was installing some package but then hit `Ctl+C`. After this I don't see anything what I type :)

```
checking for dlopen in -ldl... yes
Signal received : entering python shell.
Traceback:
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 616, in fork
    child_result = parent_pipe.recv()

>>> Signal received : entering python shell.
Traceback:
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 605, in fork
    p.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 99, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 560, in child_process
    return_value = function()
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1394, in build_process
    with log_output(self.log_path, echo, True) as logger:
  File "/gpfs/kumbhar/spack/lib/spack/llnl/util/tty/log.py", line 319, in __enter__
    self.process.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 99, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/llnl/util/tty/log.py", line 465, in _writer_daemon
    line = in_pipe.readline()


Signal received : entering python shell.
Traceback:
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 616, in fork
    child_result = parent_pipe.recv()
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)

Traceback (most recent call last):
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 616, in fork
    child_result = parent_pipe.recv()
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)
RuntimeError: can't re-enter readline
Signal received : entering python shell.
Traceback:
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 605, in fork
    p.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 99, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 560, in child_process
    return_value = function()
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1403, in build_process
    phase(self.spec, self.prefix)
  File "/gpfs/kumbhar/spack/lib/spack/llnl/util/tty/log.py", line 403, in __exit__
    self.echo = self.parent.recv()

>>> Signal received : entering python shell.
Traceback:
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)

>>> Signal received : entering python shell.
Traceback:
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
Signal received : entering python shell.
Traceback:
  File "/gpfs/kumbhar/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/kumbhar/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1431, in do_install
    self, build_process, dirty=dirty)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 605, in fork
    p.start()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 104, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 99, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/gpfs/kumbhar/spack/lib/spack/spack/build_environment.py", line 560, in child_process
    return_value = function()
  File "/gpfs/kumbhar/spack/lib/spack/spack/package.py", line 1403, in build_process
    phase(self.spec, self.prefix)
  File "/gpfs/kumbhar/spack/lib/spack/llnl/util/tty/log.py", line 403, in __exit__
    self.echo = self.parent.recv()
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)

    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
>>>     return raw_input(prompt)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)
RuntimeError: can't re-enter readline
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)
  File "/gpfs/kumbhar/spack/lib/spack/spack/util/debug.py", line 47, in debug_handler
    i.interact(message)
  File "/usr/lib64/python2.6/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib64/python2.6/code.py", line 281, in raw_input
    return raw_input(prompt)
RuntimeError: can't re-enter readline


 2017-10-05 22:18:35 ☆  <= here I pressed enter
± |llnl_develop {18} ?:4 ✗| → ==> WRITE LOCK: /gpfs/some-path/install/install/viz/.spack-db/prefix_lock[9031590227502111406:1] [Released]
==> WRITE LOCK: /gpfs/kumbhar/spack/var/spack/stage/.lock[3377321669309954226:1] [Released]


 2017-10-05 22:18:43 ☆  <= here I typed ls
± |llnl_develop {18} ?:4 ✗| → a  bin  etc  lib  LICENSE  NOTICE  opt  pytest.ini  README.md  share  templates  var
```

Now I have to re-open new shell.

**Comment by sknigh** [comment]
``` bash
stty sane
```

**Comment by junghans** [comment]
This is a bug in `bash`, just type `reset` and the shell is back to normal.

**Comment by tgamblin** [comment]
Is there something we can do in the error handler to ensure things get set back to normal?

**Comment by tldahlgren** [comment]
@pramodskumbhar Is this still an issue for you since the parallel build support refactoring?

**Comment by pramodk** [comment]
I haven’t come across this recently. So can be closed. (pramodskumbhar was my alias)

**Comment by tldahlgren** [comment]
Closing since appears to no longer be an issue.
