### ISSUE TITLE
Error: Specs passed to a DirectoryLayout must be concrete!

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#5633]
My CI build failed like so:

```
==> Installing libtiff
==> Fetching file:///tmp/apps-build-mirror.55e1sE/mirror/libtiff/libtiff-4.0.8.tar.gz
==> Staging archive: /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/var/spack/stage/libtiff-4.0.8-iaxe3tnkwwhupjmyxbcnrdoarbfkinzb/tiff-4.0.8.tar.gz
==> Created stage in /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/var/spack/stage/libtiff-4.0.8-iaxe3tnkwwhupjmyxbcnrdoarbfkinzb
==> No patches needed for libtiff
==> Building libtiff [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libtiff
  Fetch: 0.01s.  Build: 11.30s.  Total: 11.31s.
[+] /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/libtiff-4.0.8-iaxe3tnkwwhupjmyxbcnrdoarbfkinzb
==> Error: Specs passed to a DirectoryLayout must be concrete!
```

**Comment by hartzell** [comment]
I was in the process of installing `r+X`, I'm trying to figure out which package caused the complaint.

**Comment by hartzell** [comment]
Here's the tail end of a `spack -d install r@3.3.2+X` in the directory in which the CI job was running:

```
==> Successfully installed libtiff
  Fetch: 0.01s.  Build: 11.59s.  Total: 11.60s.
[+] /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/libtiff-4.0.8-iaxe3tnkwwhupjmyxbcnrdoarbfkinzb
==> WRITE LOCK: /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> link /scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/var/spack/stage/libtiff-4.0.8-iaxe3tnkwwhupjmyxbcnrdoarbfkinzb -> /tmp/hartzelg/spack-stage/spack-stage-vv_iW5
Traceback (most recent call last):
  File "./bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/cmd/install.py", line 397, in install
    package.do_install(**kwargs)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/package.py", line 1334, in do_install
    **kwargs
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/package.py", line 1438, in do_install
    self.spec, spack.store.layout, explicit=explicit
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/database.py", line 86, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/database.py", line 646, in add
    self._add(spec, directory_layout, explicit=explicit)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/database.py", line 627, in _add
    new_spec._mark_concrete()
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/spec.py", line 1891, in _mark_concrete
    if s.concrete and s.package.installed:
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/package.py", line 909, in installed
    return os.path.isdir(self.prefix)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/package.py", line 914, in prefix
    return self.spec.prefix
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/spec.py", line 1382, in prefix
    return Prefix(spack.store.layout.path_for_spec(self))
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/directory_layout.py", line 124, in path_for_spec
    _check_concrete(spec)
  File "/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/lib/spack/spack/directory_layout.py", line 42, in _check_concrete
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!
```

**Comment by scheibelp** [comment]
I'm working on reproducing this but I suspect I know what the problem is

**Comment by bvanessen** [comment]
I have a similar issue with
[vanessen@catalyst160:spack_candle.git]$ spack install py-matplotlib +image %gcc@7.1.0
...
==> Error: Specs passed to a DirectoryLayout must be concrete!
