### ISSUE TITLE
Using lmod in some cases raises a strange error

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#5870]
I'm trying to use lmod to test new changes to `setup-env.sh`, and I'm getting this bizarre error message:

```
spack -d help
==> Reading config file /home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml
Traceback (most recent call last):
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py", line 279, in _read_config_file
    data = _mark_overrides(syaml.load(f))
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py", line 213, in load
    return yaml.load(*args, **kwargs)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py", line 102, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py", line 142, in construct_mapping
    "found already in-use key (%s)" % key, key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml", line 17, column 3
found already in-use key (lmod)
  in "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml", line 49, column 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/main.py", line 436, in _main
    spack.hooks.pre_run()
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/__init__.py", line 69, in __call__
    for module in all_hook_modules():
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/__init__.py", line 57, in all_hook_modules
    mod = imp.load_source(mod_name, path)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/module_file_generation.py", line 25, in <module>
    import spack.modules
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/__init__.py", line 32, in <module>
    from .dotkit import DotkitModulefileWriter
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/dotkit.py", line 28, in <module>
    from .common import BaseConfiguration, BaseFileLayout
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/common.py", line 71, in <module>
    configuration = spack.config.get_config('modules')
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py", line 409, in get_config
    data = scope.get_section(section)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py", line 180, in get_section
    data   = _read_config_file(path, schema)
  File "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py", line 287, in _read_config_file
    "Error parsing yaml%s: %s" % (str(e.context_mark), e.problem))
spack.config.ConfigFileError: Error parsing yaml  in "/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml", line 17, column 3: found already in-use key (lmod)
```

It happens even when using `spack help` (as evidenced by the command and error message above), and on loading `etc/spack/defaults/modules.yaml`.

It seems to be taking issue with my enabling of the `lmod` option, complaining that its already in use. This is strange because this is the only config file on my system attempting to define the `lmod` option.

The only thing I can think of is that this particular installation of spack used to be a `tcl` installation, i.e. I was using `environment-modules` and am now attempting to test `lmod`. Do I need to clear the cache in `~/.spack` or something?

I'll update with what I learn as I try to fix this bug.

**Comment by krafczyk** [comment]
Okay, stupid problem,

I discovered that I indeed had an additional `lmod:` section at the bottom of my `modules.yaml` file... closing.
