### ISSUE TITLE
Cannot Build Abyss - Missing Autoconf?

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#5891]
Never seen this type of error before:

```
==> No patches needed for abyss
==> Building abyss [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Error: RuntimeError: Cannot generate configure: missing dependencies ['autoconf', 'automake']
RuntimeError: RuntimeError: Cannot generate configure: missing dependencies ['autoconf', 'automake']

/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/build_systems/autotools.py:210, in autoreconf:
     7             missing = [x for x in autotools if x not in spec]
     8             if missing:
     9                 msg = 'Cannot generate configure: missing dependencies {0}'
  >> 10                raise RuntimeError(msg.format(missing))
     11            tty.msg('Configure script not found: trying to generate it')
     12            tty.warn('*********************************************************')
     13            tty.warn('* If the default procedure fails, consider implementing *')
```

I have all of the `autotools` packages present...

**Comment by JusticeForMikeBrown** [comment]
I have tried ```spack clean --all``` as well as ```reindex``` but no luck.

```
[root@node118 ~]# spack find -l -v autoconf automake %gcc@6.3.0
==> 3 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
iquqclp autoconf@2.69

-- linux-rhel6-x86_64 / gcc@6.3.0 -------------------------------
g6cguwi autoconf@2.69  y3w6wkw automake@1.15
```

```

==> boost is already installed in /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/boost-1.63.0-eu4aw5v6ewmqd5kuzieorttiljxcuscv
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[1340953091361655936:1] [Released]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Acquiring]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Acquired]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Acquired]
==> sqlite is already installed in /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/sqlite-3.20.0-ojc3hqrfu2wzdm4fihdj7b6gv2mhhoe6
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[4117092570076763848:1] [Released]
==> Installing abyss
==> Fetching from /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/cache/abyss/abyss-2.0.2.tar.gz failed.
==> md5 checksum failed for /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/abyss-2.0.2-hqjvuciejufdjlv3cg2ytuftyx2z6han/2.0.2.tar.gz
    Expected 1623f55ad7f4586e80f6e74b1f27c798 but got bb3f8cebf121312bf81789d963b4ecc5
==> Fetching https://github.com/bcgsc/abyss/archive/2.0.2.tar.gz
==> '/usr/bin/curl' '-C' '-' '-o' '/pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/abyss-2.0.2-hqjvuciejufdjlv3cg2ytuftyx2z6han/2.0.2.tar.gz.part' '-f' '-D' '-' '-L' 'https://github.com/bcgsc/abyss/archive/2.0.2.tar.gz' '-#'
######################################################################## 100.0%
==> Already staged abyss-2.0.2-hqjvuciejufdjlv3cg2ytuftyx2z6han in /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/abyss-2.0.2-hqjvuciejufdjlv3cg2ytuftyx2z6han
==> No patches needed for abyss
==> Building abyss [AutotoolsPackage]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/.lock[8211244693683961360:1] [Acquiring]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/.lock[8211244693683961360:1] [Acquired]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[2164451330803270938:1] [Acquiring]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[2164451330803270938:1] [Acquired]
==> Executing phase: 'autoreconf'
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/prefix_lock[2164451330803270938:1] [Released]
==> WRITE LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/.lock[8211244693683961360:1] [Released]
==> Error: RuntimeError: Cannot generate configure: missing dependencies ['autoconf', 'automake']
RuntimeError: RuntimeError: Cannot generate configure: missing dependencies ['autoconf', 'automake']

/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/build_systems/autotools.py:210, in autoreconf:
     7             missing = [x for x in autotools if x not in spec]
     8             if missing:
     9                 msg = 'Cannot generate configure: missing dependencies {0}'
  >> 10                raise RuntimeError(msg.format(missing))
     11            tty.msg('Configure script not found: trying to generate it')
     12            tty.warn('*********************************************************')
     13            tty.warn('* If the default procedure fails, consider implementing *')

See build log for details:
  /pbtech_mounts/softlib001/apps/EL6/spack/var/spack/stage/abyss-2.0.2-hqjvuciejufdjlv3cg2ytuftyx2z6han/abyss-2.0.2/spack-build.out
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/build_environment.py", line 560, in child_process
    return_value = function()
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 1403, in build_process
    phase(self.spec, self.prefix)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py", line 110, in phase_wrapper
    phase(spec, prefix)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/build_systems/autotools.py", line 210, in autoreconf
    raise RuntimeError(msg.format(missing))
RuntimeError: Cannot generate configure: missing dependencies ['autoconf', 'automake']

```

**Comment by JusticeForMikeBrown** [comment]
This still occurs with latest pull from ```develop```

**Comment by akthoma** [comment]
I believe I should be able to fix this--I'll have an update for you tomorrow.

**Comment by akthoma** [comment]
Scratch that, I squeezed it in today. Fixed by https://github.com/LLNL/spack/pull/5973

**Comment by JusticeForMikeBrown** [comment]
boom goes the dynamite!
