### ISSUE TITLE
Spack does not uncompress some archives

### ISSUE THREAD

**Issue by loikki** [LLNL/spack#5946]
Hi,
I had a few problems with the installation of gettext/glib. I was getting the following error:
```
==> Installing gettext

==> Using cached archive: /media/loikki/data/Linux/spack/var/spack/cache/gettext/gettext-0.19.8.1.tar.xz

==> Staging archive: /media/loikki/data/Linux/spack/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv/gettext-0.19.8.1.tar.xz

==> Created stage in /media/loikki/data/Linux/spack/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv

==> Error: TypeError: coercing to Unicode: need string or buffer, NoneType found

TypeError: TypeError: coercing to Unicode: need string or buffer, NoneType found

/media/loikki/data/Linux/spack/lib/spack/spack/package.py:1085, in do_patch:

     49                    # Touch bad file if anything goes wrong.

     50                    tty.msg('Patch %s failed.' % patch.path_or_url)

     51                    touch(bad_file)

  >> 52                    raise

     53    

     54            if has_patch_fun:

     55                try:
```

I have been able to solve it by uncompressing the archive (tar.xz) manually in var/spack/stage/gettext-*

I am on a x86 Ubuntu system with the spack branch "develop" (last commit 882480fad629f9e98f7b6c83b7dc98ac7d836cc3).

Best regards,

**Comment by scheibelp** [comment]
I'll be able to look at this tomorrow

**Comment by scheibelp** [comment]
I'm having trouble replicating this. Could you post a full stack trace, along with any additional info that is printed if you retry this with `spack -d install...`?

Spack should be able to decompress `.xz` archives, so just to make sure: after the installation failed there wasn't a decompressed archive in the staging directory (I want to distinguish this from the possibility that the uncompressed archive was present but corrupted somehow).

**Comment by scheibelp** [comment]
I think this may be related to https://github.com/LLNL/spack/pull/5544 and https://github.com/LLNL/spack/issues/3018. I'll be looking at it more

**Comment by loikki** [comment]
In `/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv`, I have only the archive `gettext-0.19.8.1.tar.xz` after the installation.

```
==> Reading config file /media/loikki/data/Linux/spack/etc/spack/defaults/packages.yaml
==> Reading config file /home/loikki/.spack/packages.yaml
==> READ LOCK: /home/loikki/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/loikki/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/loikki/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /home/loikki/.spack/linux/compilers.yaml
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Acquired]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Acquired]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[8089151702949599452:1] [Released]
==> Installing gettext dependencies
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Acquired]
==> bzip2 is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/bzip2-1.0.6-mwamumjkh6rxeweisznsjr6csal3zjf4
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3657034053680353721:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Acquired]
==> pkg-config is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/pkg-config-0.29.2-76z7ehwugj6njw7gnvw4alwhjvillfwk
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[9212668357362925162:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Acquired]
==> xz is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/xz-5.2.3-h3ory2zam5p62ylfvpfe34u6wqbp3ac7
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[2264904023317655542:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Acquired]
==> zlib is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/zlib-1.2.11-lv5fablff56f75cdcf2uumekpj5f5k6f
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[3367892088394333743:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Acquired]
==> libxml2 is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/libxml2-2.9.4-rhgdmu662mplulkgxt2cxtv3yj2xhmkf
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4964685506146832221:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Acquired]
==> ncurses is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/ncurses-6.0-oh6pqtyx4ugpoybifwzlh26jho3aqkcd
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[4106856419501966971:1] [Released]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Acquiring]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Acquired]
==> WRITE LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Released]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Acquiring]
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Acquired]
==> tar is already installed in /media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/tar-1.29-2rty7povwxlht7s6qraskwdwpsp2r2pk
==> READ LOCK: /media/loikki/data/Linux/spack/opt/spack/.spack-db/prefix_lock[7652679952069487420:1] [Released]
==> Installing gettext
==> Using cached archive: /media/loikki/data/Linux/spack/var/spack/cache/gettext/gettext-0.19.8.1.tar.xz
==> Staging archive: /media/loikki/data/Linux/spack/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv/gettext-0.19.8.1.tar.xz
==> '/media/loikki/data/Linux/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/tar-1.29-2rty7povwxlht7s6qraskwdwpsp2r2pk/bin/tar' '-xf' '/media/loikki/data/Linux/spack/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv/
gettext-0.19.8.1.tar.xz'                                                                                                                                                                                                                   
==> Created stage in /media/loikki/data/Linux/spack/var/spack/stage/gettext-0.19.8.1-4ccocozzduy3q5ig7rcc63xlu2uahasv
==> Error: TypeError: coercing to Unicode: need string or buffer, NoneType found
TypeError: TypeError: coercing to Unicode: need string or buffer, NoneType found

/media/loikki/data/Linux/spack/lib/spack/spack/package.py:1085, in do_patch:
     49                    # Touch bad file if anything goes wrong.
     50                    tty.msg('Patch %s failed.' % patch.path_or_url)
     51                    touch(bad_file)
  >> 52                    raise
     53    
     54            if has_patch_fun:
     55                try:


Traceback (most recent call last):
  File "/media/loikki/data/Linux/spack/lib/spack/spack/build_environment.py", line 562, in child_process
    return_value = function()
  File "/media/loikki/data/Linux/spack/lib/spack/spack/package.py", line 1361, in build_process
    self.do_patch()
  File "/media/loikki/data/Linux/spack/lib/spack/spack/package.py", line 1077, in do_patch
    with working_dir(self.stage.source_path):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/media/loikki/data/Linux/spack/lib/spack/llnl/util/filesystem.py", line 282, in working_dir
    os.chdir(dirname)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by loikki** [comment]
Strange, I reinstalled everything and now the install is fine

**Comment by scheibelp** [comment]
> Strange, I reinstalled everything and now the install is fine

To sanity-check: did you install in the same place? If so, do you have a notion of what changed?

Did you have any module files associated with external packages (in `packages.yaml`) or with your compiler (in `compilers.yaml`) that have changed recently?

**Comment by loikki** [comment]
I installed everything at the same place and did not change my .spack/*.yaml files (I have just done a rm spack; git clone spack; spack install ...).

I think the best is to close the issue now, and I will open it again when I am able to reproduce the bug

**Comment by scheibelp** [comment]
> I think the best is to close the issue now, and I will open it again when I am able to reproduce the bug

That sounds good to me - thanks for the updates!
