### ISSUE TITLE
`spack mirror` : wrong dependency resolution

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#805]
The command : 

``` shell
$ spack mirror create -d /home/mculpo/production/spack-mirror -D espresso+mpi+scalapack%gcc@5.3.0^openblas+shared^openmpi+psm
==> Error: Multiple providers found for 'mpi': ['mvapich2@2.2b%gcc@5.3.0~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp~psm~remshell~slurm~sock=production', 'openmpi@1.10.2%gcc@5.3.0+psm~tm~verbs=production']

```

fails with an error on the current `develop`, while : 

``` shell
$ spack mirror create -d /home/mculpo/production/spack-mirror -D espresso+mpi+scalapack%gcc@5.3.0^openblas+shared^netlib-scalapack^openmpi+psm
==> Adding package fftw@3.3.4 to mirror
==> fftw@3.3.4 : already added
==> Adding package netlib-scalapack@2.0.2 to mirror
==> netlib-scalapack@2.0.2 : already added
==> Adding package openmpi@1.10.2 to mirror
==> openmpi@1.10.2 : already added
==> Adding package espresso@5.3.0 to mirror
==> espresso@5.3.0 : already added
==> Adding package libpciaccess@0.13.4 to mirror
==> libpciaccess@0.13.4 : already added
==> Adding package cmake@3.5.2 to mirror
==> cmake@3.5.2 : already added
==> Adding package openblas@0.2.17 to mirror
==> openblas@0.2.17 : already added
==> Adding package hwloc@1.11.2 to mirror
==> hwloc@1.11.2 : already added
==> Adding package openssl@1.0.2g to mirror
==> openssl@1.0.2g : already added
==> Adding package zlib@1.2.8 to mirror
==> zlib@1.2.8 : already added
==> Adding package libtool@2.4.6 to mirror
==> libtool@2.4.6 : already added
==> Adding package ncurses@6.0 to mirror
==> ncurses@6.0 : already added
==> Successfully updated mirror in /home/mculpo/production/spack-mirror
```

completes successfully. It seems a bug to me the fact that, if not mentioned explicitly in the command line, `netlib-scalapack` mpi is resolved to be something else than `openmpi`. Note that : 

``` shell
$ spack install espresso+mpi+scalapack%gcc@5.3.0^openblas+shared^openmpi+psm
```

**does not** present the same problem.

**Comment by KineticTheory** [comment]
I'm seeing a similar problem with current `develop`:

```
spack mirror create -d $MIRROR_DIR -D mumps 
==> Error: Multiple providers found for 'blas': ['mkl@11.3.3.210%gcc@4.8.5 arch=linux-redhat7-x86_64', 'openblas@0.2.18%gcc@4.8.5+fpic~openmp+shared arch=linux-redhat7-x86_64']

spack mirror create -d $MIRROR_DIR -D mumps ^openblas
==> Error: Multiple providers found for 'blas': ['atlas@3.10.2%gcc@4.8.5+shared arch=linux-redhat7-x86_64', 'openblas@0.2.18%gcc@4.8.5+fpic~openmp+shared arch=linux-redhat7-x86_64']
```

**Comment by alalazo** [comment]
Trying this right now, getting a different error:
```console
$ spack mirror create -d /home/mculpo/production/spack-mirror -D espresso+mpi+scalapack^openblas+shared^openmpi+psm
Traceback (most recent call last):
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 224, in mirror
    action[args.mirror_command](args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 202, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/mirror.py", line 167, in create
    s.concretize()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1521, in concretize
    self._expand_virtual_packages(),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1416, in _expand_virtual_packages
    self_index = ProviderIndex(self.traverse(), restrict=True)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/provider_index.py", line 87, in __init__
    self.update(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/provider_index.py", line 106, in update
    if spec.satisfies(provider_spec, deps=False):
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2049, in satisfies
    if not self.variants.satisfies(other.variants, strict=var_strict):
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 627, in satisfies
    if strict or self.spec._concrete:
AttributeError: 'NoneType' object has no attribute '_concrete'
```
I am getting the same error with other packages too:
```console
$ spack mirror create -d ~/production/spack-mirror gcc
Traceback (most recent call last):
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 224, in mirror
    action[args.mirror_command](args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 202, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/mirror.py", line 167, in create
    s.concretize()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1520, in concretize
    changes = (self.normalize(force),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1816, in normalize
    any_change = self._normalize_helper(visited, spec_deps, provider_index)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1765, in _normalize_helper
    pkg_dep = self._evaluate_dependency_conditions(dep_name)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1629, in _evaluate_dependency_conditions
    sat = self.satisfies(when_spec, strict=True)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2070, in satisfies
    return self.satisfies_dependencies(other, strict=deps_strict)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2100, in satisfies_dependencies
    self_index = ProviderIndex(self.traverse(), restrict=True)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/provider_index.py", line 87, in __init__
    self.update(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/provider_index.py", line 106, in update
    if spec.satisfies(provider_spec, deps=False):
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2049, in satisfies
    if not self.variants.satisfies(other.variants, strict=var_strict):
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 627, in satisfies
    if strict or self.spec._concrete:
AttributeError: 'NoneType' object has no attribute '_concrete'
```

**Comment by alalazo** [comment]
Update: trying on a08ccbedeede499a568c5c818579320ab41247c4 gives:
```console
$ spack mirror create -d /home/mculpo/production/spack-mirror -D espresso+mpi+scalapack ^openblas+shared^openmpi+psm
Traceback (most recent call last):
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/mculpo/PycharmProjects/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 224, in mirror
    action[args.mirror_command](args)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/cmd/mirror.py", line 202, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/mirror.py", line 170, in create
    s.concretize()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1526, in concretize
    self._concretize_helper())
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1365, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1375, in _concretize_helper
    (spack.concretizer.concretize_architecture(self),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/concretize.py", line 253, in concretize_architecture
    root_arch = spec.root.architecture
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 960, in root
    first_root = next(depiter).parent.root
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 960, in root
    first_root = next(depiter).parent.root
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 960, in root
    first_root = next(depiter).parent.root
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 960, in root
    first_root = next(depiter).parent.root
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 960, in root
    first_root = next(depiter).parent.root
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 961, in root
    assert(all(first_root is d.parent.root for d in depiter))
AssertionError
```

**Comment by alalazo** [comment]
As of 269925f77539436045d8a1c2a7d8325d3e8d8c7f it works:
```console
$ spack mirror create -d /home/mculpo/production/spack-mirror -D espresso+mpi+scalapack^openblas+shared^openmpi fabrics=psm
==> Adding package espresso@6.1.0 to mirror
==> espresso@6.1.0 : already added
==> Adding package libpciaccess@0.13.5 to mirror
==> libpciaccess@0.13.5 : already added
==> Adding package libxml2@2.9.4 to mirror
==> libxml2@2.9.4 : already added
==> Adding package ncurses@6.0 to mirror
==> ncurses@6.0 : already added
==> Adding package openssl@1.0.2k to mirror
==> openssl@1.0.2k : already added
==> Adding package openblas@0.2.20 to mirror
==> openblas@0.2.20 : already added
==> Adding package libtool@2.4.6 to mirror
==> libtool@2.4.6 : already added
==> Adding package netlib-scalapack@2.0.2 to mirror
==> netlib-scalapack@2.0.2 : already added
==> Adding package libsigsegv@2.11 to mirror
==> libsigsegv@2.11 : already added
==> Adding package m4@1.4.18 to mirror
==> m4@1.4.18 : already added
==> Adding package cmake@3.8.1 to mirror
==> cmake@3.8.1 : already added
==> Adding package zlib@1.2.11 to mirror
==> zlib@1.2.11 : already added
==> Adding package fftw@3.3.6-pl2 to mirror
==> fftw@3.3.6-pl2 : already added
==> Adding package hwloc@1.11.7 to mirror
==> hwloc@1.11.7 : already added
==> Adding package util-macros@1.19.1 to mirror
==> util-macros@1.19.1 : already added
==> Adding package openmpi@2.1.1 to mirror
==> openmpi@2.1.1 : already added
==> Adding package xz@5.2.3 to mirror
==> xz@5.2.3 : already added
==> Adding package elpa@2016.05.004 to mirror
==> elpa@2016.05.004 : already added
==> Adding package pkg-config@0.29.2 to mirror
==> pkg-config@0.29.2 : already added
==> Successfully updated mirror in /home/mculpo/production/spack-mirror
  Archive stats:
    19   already present
    0    added
    0    failed to fetch.
```
Probably it was fixed when we went to the bottom of all the weird issues exposed by MV variants.
