### ISSUE TITLE
[Broken] Broken Python Package

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#860]
I can't install python@2.7.11.  I have no idea why, it worked before, and not much has changed since.  I get:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/sysconfig.py", line 636, in <module>
    _main()
  File "/usr/lib64/python2.7/sysconfig.py", line 624, in _main
    _generate_posix_vars()
  File "/usr/lib64/python2.7/sysconfig.py", line 304, in _generate_posix_vars
    raise IOError(msg)
IOError: invalid Python installation: unable to open /tmp/rpfische/spack-stage/spack-stage-o8cV36/Python-2.7.11/pyconfig-64.h (No such file or directory)
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1
```

Sure enough, pyconfig-64.h does not exist.  pyconfig.h does.

[python-spack-build.txt](https://github.com/LLNL/spack/files/239625/python-spack-build.txt)

**Comment by alalazo** [comment]
Is this still an issue?

**Comment by citibeth** [comment]
No

**Comment by alalazo** [comment]
@citibeth I am closing the issue then. Re-open it if you think it is the case.
