### ISSUE TITLE
Document required filesystem locking semantics

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#925]
From a user attempting to run spack on a filesystem without flock:

```
I started playing around with spack on my mac (I was trying to evaluate it when compared to brew) and I find it beatiful! 

I then decided to start using it on our cluster, but I had no luck with the latest version. After cloning spack from github, any time I try installing a package I get this error:

$ spack install dealii
Traceback (most recent call last):
  File "/home/mathlab/spack/bin/spack", line 176, in <module>
    main()
  File "/home/mathlab/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/home/mathlab/spack/lib/spack/spack/cmd/install.py", line 74, in install
    with spack.installed_db.write_transaction():
  File "/home/mathlab/spack/lib/spack/spack/database.py", line 598, in __enter__
    if self._enter() and self._acquire_fn:
  File "/home/mathlab/spack/lib/spack/spack/database.py", line 616, in _enter
    return self._db.lock.acquire_write(self._timeout)
  File "/home/mathlab/spack/lib/spack/llnl/util/lock.py", line 123, in acquire_write
    self._lock(fcntl.LOCK_EX, timeout)   # can raise LockError.
  File "/home/mathlab/spack/lib/spack/llnl/util/lock.py", line 64, in _lock
    fcntl.lockf(self._fd, op | fcntl.LOCK_NB)
IOError: [Errno 38] Function not implemented


```

**Comment by davydden** [comment]
@luca-heltai ping.

**Comment by luca-heltai** [comment]
Apparently this issue is related to mismatching Python configurations on my system. I installed a local version of conda, and the issue changed. Now I don't seem able to compile any package, because my cluster configuration heavily uses LD_LIBRARY_PATH variables, which seem to be ignored by the environment set up by spack...

**Comment by luca-heltai** [comment]
I spoke too early. Apparently the issue is still there, but sometimes it randomly works.

**Comment by luca-heltai** [comment]
This should definitely be documented...
