### ISSUE TITLE
Spack spec glib fails

### ISSUE THREAD

**Issue by JRWynneIII** [LLNL/spack#995]
The spec can be normalized but it seems that concretization fails with parser error. I tried running
```
spack --debug spec glib
```
to get more info and it looks like the problem is internally in spack:
```
Input spec
------------------------------
  glib

Normalized
------------------------------
  glib
      ^libffi
      ^pkg-config
      ^zlib

Concretized
------------------------------
Traceback (most recent call last):
  File "/sw/eos/.spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/cmd/spec.py", line 58, in spec
    spec.concretize()
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/spec.py", line 1039, in concretize
    self._expand_virtual_packages(),
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/spec.py", line 959, in _expand_virtual_packages
    spec)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/concretize.py", line 110, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/concretize.py", line 76, in _valid_virtuals_and_externals
    externals = spec_externals(cspec)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/config.py", line 678, in spec_externals
    external_spec = spack.spec.Spec(external_spec, external=path)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/spec.py", line 459, in __init__
    spec_list = SpecParser().parse(spec_like)
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/parse.py", line 124, in parse
    return self.do_parse()
  File "/autofs/nccs-svm1_sw/eos/.spack/lib/spack/spack/spec.py", line 2068, in do_parse
    raise SpecParseError(e)
spack.spec.SpecParseError: Unexpected token
```

**Comment by adamjstewart** [comment]
@JRWynneIII Are you running off of the latest development branch? I can't recreate this problem.

**Comment by JRWynneIII** [comment]
Yes, I just pulled from develop about an hour ago.

**Comment by adamjstewart** [comment]
Hmm. What does your compilers.yaml file look like? (`spack config get compilers`)

**Comment by JRWynneIII** [comment]
This is my current compilers.yaml:
```
compilers:
  linux-x86_64:
    gcc@4.3.4:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    gcc@4.9.0:
      cc: /opt/gcc/4.9.0/bin/gcc
      cxx: /opt/gcc/4.9.0/bin/g++
      f77: /opt/gcc/4.9.0/bin/gfortran
      fc: /opt/gcc/4.9.0/bin/gfortran
    intel@15.0.2:
      cc: /opt/intel/composer_xe_2015.2.164/bin/intel64/icc
      cxx: /opt/intel/composer_xe_2015.2.164/bin/intel64/icpc
      f77: /opt/intel/composer_xe_2015.2.164/bin/intel64/ifort
      fc: /opt/intel/composer_xe_2015.2.164/bin/intel64/ifort
    gcc@4.4.7:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    gcc@4.8.2:
      cc: /ccs/compilers/gcc/rhel6-x86_64/4.8.2/bin/gcc
      cxx: /ccs/compilers/gcc/rhel6-x86_64/4.8.2/bin/g++
      f77: /ccs/compilers/gcc/rhel6-x86_64/4.8.2/bin/gfortran
      fc: /ccs/compilers/gcc/rhel6-x86_64/4.8.2/bin/gfortran
```
When I was trying (and failing) to install glib, i used %gcc@4.4.7 if that makes any difference.

**Comment by JRWynneIII** [comment]
Okay I found my problem. I had previously added an external build for glib in my packages.yaml and didn't realize that would interfere. Everything now works.

**Comment by tgamblin** [comment]
We should probably add something to actually point you to the offending line of packages.yaml.  What did that line look like?

**Comment by JRWynneIII** [comment]
My packages.yaml looked like:
```
packages:
  glib:
    paths:
      glib@2.36.4%gcc@4.3.4=Linux_x86_64: /sw/xk6/glib/2.36.4/sles11.1_gnu4.3.4
```
After I removed that I was able to run spack spec and also successfully install it

**Comment by adamjstewart** [comment]
Wonder if it's because the `=Linux_x86_64` syntax got changed to `arch=Linux_x86_64`

**Comment by JRWynneIII** [comment]
I changed it so that it reads now
```
glib@2.36.4%gcc@4.3.4 arch=Linux_x86_64
```
And that seemed to allow it to concretize, so that may have been it. I didn't realize the syntax had changed; I added that line a while back and forgot about it.

**Comment by tgamblin** [comment]
The old syntax should continue to work,  @becker33?

**Comment by becker33** [comment]
No, the current develop branch doesn’t accept the old architecture syntax.

-Greg
